rancher/dashboard

shell/pages/auth/login.vue
This uses `markRaw()` on each member of `providerComponents` to communicate to Vue that the components do not need to be made reactive.
Fixes #11772
- Add `markRaw()` to each member of `providerComponents`
`providerComponents` is a reactive object, and components don't need to be added to Vue's reactivity system. We use `markRaw()` to ensure that the component is not made a reactive object. 
- Enable third-party auth providers to test this
=> Resolve reactive object warning for components in `Login.vue`

cypress/jenkins/init.sh
A couple of adjustments, one typo fix and improve logic on Job Type existing which we don't need a Rancher built.
update the Jenkins initi script
CI Jenkins
CI Jenkins init
=> [Automation] - Fixing typo and do not deploy Rancher when existing is used and init cluster is yes

shell/components/form/Labels.vue, shell/components/formatter/InternalExternalIP.vue, shell/detail/helm.cattle.io.projecthelmchart.vue, shell/edit/auth/ldap/config.vue, shell/edit/cis.cattle.io.clusterscan.vue, shell/edit/cis.cattle.io.clusterscanprofile.vue, shell/edit/provisioning.cattle.io.cluster/tabs/registries/index.vue, shell/edit/resources.cattle.io.backup.vue, shell/edit/resources.cattle.io.restore.vue, shell/pages/c/_cluster/uiplugins/AddExtensionRepos.vue, shell/promptRemove/management.cattle.io.roletemplate.vue
This resolves a breaking change in Vue3 that treats `<template>` tags with no special directives as plain elements[^1] by removing the extra `<template>` tags from each component.
> `<template>` tags with no special directives (v-if/else-if/else, v-for, or v-slot) are now treated as plain elements and will result in a native `<template>` element instead of rendering its inner content.
This PR addresses more than just the CIS Benchmark, but I decided to address all of these instances after identifying the root cause to be the same for each occurrence 
Fixes #11910
Fixes #11913
Fixes #11912
[^1]: https://v3-migration.vuejs.org/breaking-changes/#other-minor-changes
- remove extra `<template>` tags from components
It might be a good idea to replace these instances of `<template>` with `<div>` …
=> Remove extra `<template>` tags from components

cypress/jenkins/junit_to_qase.py
Fixes https://github.com/rancher/qa-tasks/issues/1542
Adding the Automation status toUI  Cases in Qase
The API documentation is very ambiguous as to what values and which post data keys should be included or updated to update the Automation Status.
Here's a comparison:
- The left request data is pushed on new Cases that has the Automation Status: **Automated.**
- The right pane is for new Cases with Automation Status: **Manual**.
This change updates the New case POST as the left pane.
Also this change updates the Existing case PATCH as the left pane too.
Jenkins Qase reporting
- [ x The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
=> [Automation] - Add the Automation Status as "Automated" to UI Cases

cypress/e2e/tests/pages/generic/about.spec.ts
Fixes #
- In v2.9-head the links the UI uses to provide the download cli links will soon be updated to 2.9.2 
- Those links though are dead and won't exist until after 2.9.2 is released
- In the short term check that they're dead
- Note 1 - Once they're fixed we'll know, as the e2e tests will start failing
- Note 2 - This will fail until v2.9-head [changes](https://github.com/rancher/rancher/pull/47148) merge and build happens. We can force merge if needs be
=> Ensure we check for correct status code when testing cli download links

shell/components/SortableTable/index.vue, shell/core/plugin-routes.ts, shell/mixins/fetch.client.js, shell/package.json, shell/pages/index.vue
Fixes https://github.com/rancher/dashboard/issues/11795
- Bump `vue-router@4.4.3`
- Update router API calls and fix `resolveRoute` validation to avoid error in case of `afterLoginRoute` is invalid or doesn't exist.
- Fix `fetch.client.js`
- Harvester standalone mode: the new shell should make Harvester extension loads without errors when used as separated UI
- Harvester built-in extension: the dashboard should work correctly when navigating to Virtualization Manager -> Harvester clusters
- Harvester extension installation: todo
=> Fix navigation guard for standalone extensions

shell/components/CodeMirror.vue, shell/components/YamlEditor.vue
Fixes #11701 
This PR fixes Codemirror styling (used in yaml editor and a couple other places). There were two main issues: this new library introduced new styles, which can be overwritten via prop (added here). The new library also had a hardcoded font value the old did not. 
I also noticed some Codemirror elements are arranged differently. I left all this alone, I wouldn't consider it a bug and it looks better now anyway:
(old)
(new)
The resize nullpx nullpx message reported in #11701 is a known issue with the library https://github.com/rennzhang/codemirror-editor-vue3/issues/54
'View as Yaml' and 'Edit as Yaml' pages
Create/edit a configmap with json values
Detail view of a resource with json annotations
(old)
(new)
(old)
(new)
(old)
(new)
=> Fix yaml editor styling

cypress/e2e/po/edit/services.po.ts, cypress/e2e/po/edit/workloads.po.ts, cypress/e2e/po/pages/explorer/services.po.ts, cypress/e2e/po/pages/explorer/workloads.po.ts, cypress/e2e/tests/pages/explorer/service-discovery/services.spec.ts, cypress/e2e/tests/pages/explorer2/workloads/workloads.spec.ts, shell/assets/translations/en-us.yaml, shell/edit/service.vue, shell/edit/workload/__tests__/index.test.ts, shell/edit/workload/index.vue
Fixes #11889 
Fixed validation errors being shown before the form. Overall, this is more of a temporary solution and validation should be standardized and re-implemented in a more consistent way.
Additionally, addressed the error messages not closing.
- Workloads create page should not show a validation error before type is selected
- Service create page should not show a validation error before type is selected
N/A
=> Vue3: Fixed validation errors shown prematurely for Workload and Service forms

package.json, shell/initialize/install-plugins.js, shell/package.json, shell/yarn.lock, yarn.lock
When running an extension locally in the dev environment with the latest Vue3 changes that uses the CodeMirror plugin, you will get an warning in the console:
```console
warning  in ./node_modules/@rancher/shell/initialize/install-plugins.js
export 'InstallCodemirro' (imported as 'InstallCodemirro') was not found in 'codemirror-editor-vue3' (possible exports: CodeMirror, GlobalCmComponent, InstallCodeMirror, VueCodemirror, createLinkMark, createLog, createLogMark, createTitle, default, getLinkMarks, getLocalTime, getLogMark, logErrorType)
```
This fixes the import and export for `InstallCodeMirror`.
An extension using the CodeMirror plugin.
=> Fix InstallCodeMirror export

cypress/e2e/po/components/namespace-filter.po.ts, cypress/e2e/tests/pages/explorer2/namespace-picker.spec.ts, shell/components/nav/NamespaceFilter.vue
This adds a `@click` event handler to the namespace filter input. Doing this allows the input to be selected after making a selection in the dropdown.
Fixes #11928 
- Add a `@click` handler to `ns-filter-input` input
This regression was introduced in #11762, which added a `@click.prevent` handler to prevent multiple events from quickly toggling the namespace filter dropdown from opened to closed. 
An alternative solution to this PR would be to revert the change made in #11762 and redesign the solution entirely. I thought the solution presented in this PR to be more straightforward, the tradeoff being that it requires the special case for the `@click` handler. 
- Namespace Filter
- NA
=> Allow the namespace filter to be selected after making selection in the dropdown

.github/workflows/build-extension-charts.yml, docusaurus/docs/extensions/publishing.md
Fixes #11947 
This is candidate to backport for `release-2.9` branch because of the recent problems with the `master` reusable workflow (minus the docs changes, ofc)
- Fool proofing reusable build extensions chart workflow to only run with a tagged release (needs failure to reinforce problem with correct trigger of the reusable workflow)
- Improve publishing docs
=> update extensions build chart workflow to only work with tagged releases

package.json, shell/components/CodeMirror.vue, shell/components/nav/WindowManager/ContainerShell.vue, shell/initialize/install-plugins.js, shell/package.json, yarn.lock
Fixes #11812 
Fixes #11970 
Fixes #11932
This fixes the styling issues for the kubectl and container shell windows, the errors in the console created by the `resize-observer` component, and the Yaml editor being unable to show diffs.
- Removed lingering outline style for terminal focus
- Fixed class selector targeting `.unlabeled-select` with the `:deep()` method while using an un-scoped style tag
- Errors in the console were caused by the `resize-observer`
- They were related to using the outdated library for `vue-resize` which is pinned to Vue 2
- Updated the vue-resize library to `vue3-resize` 
- Fixed the naming scheme of the `codeMirrorRef` instance to `cminstance`
I was unable to get the `scoped` style to work within the ContainerShell component, which is odd considering the …
=> ContainerShell window manager fixes

cypress/e2e/po/pages/explorer/nodes.po.ts, cypress/e2e/tests/pages/explorer2/nodes/node-detail.spec.ts, cypress/e2e/tests/pages/explorer2/nodes/node-list.spec.ts, shell/config/router/routes.js
Fixes #11815 
The node detail page route should match `/c/:cluster/:product/:resource/:id` and instead it's matched to `/c/:cluster/:product/:resource/:namespace/:id?` , where the node id is parsed as a namespace parameter instead, and a create page is rendered (because there's no resource id passed to ResourceDetail). You can see this with the [vue-router path-checker tool](https://paths.esm.dev/?p=AAMeJY2BucBsIOAKAGcUuE7AA7APpglgkqImqy_rmqKsTloCFBDRBJrE4FqncVqZeq0BMATYCzBHabo4CI3mBwBk&t=/c/local/explorer/nodes/some-node-id%23pods#).
vue-router behaviour seems to have changed in v4. Though this wasn't called out in the migration guide, note that [this section](https://v3.router.vuejs.org/guide/essentials/dynamic-matching.html#matching-priority) about priority is not present in the [v4 …
=> vue3 - fix detail page routing 

cypress/e2e/tests/pages/users-and-auth/index.spec.ts, cypress/support/commands/commands.ts
Fixes https://github.com/rancher/qa-tasks/issues/1400
Adding new scenarios to the user retention test automation suite.
The account has the `Disable After` and `Delete After` enabled.
Checking a standard user can't access the Retention settings.
Automation of User retention settings
CI execution
Jenkins/GA
=> [Automation] - Additional user retention settings tests

shell/assets/styles/base/_variables.scss, shell/assets/styles/global/_layout.scss, shell/components/Loading.vue
Fixes #5245
- Windows Manager sits below side nav and main screen content
- shell, log streaming
- The relative and content loading indicator covers a specific area or the main screen content
- Bug - relative and content loading indicator appears over windows manager
- Fix
- apply different z-index to main and other modes of loading indicator
- assign a higher z-index to windows manager (higher than main screen content)
Tested
- mode - relative
- shell/chart/monitoring/index.vue
- shell/components/Wizard.vue
- shell/components/nav/GlobalLoading.vue
- shell/pages/auth/login.vue
- mode - content
- shell/pages/c/_cluster/monitoring/index.vue
- shell/edit/namespace.vue - shell/pages/c/_cluster/settings/banners.vue
- mode - main
- not actually used... and currently broken (new burger menu is …
=> Ensure loading indicator doesn't show outside it's context

docusaurus/docs/internal/testing/e2e-test.md
- Improve the docs describing PO usage, in particular at what level they should be created and some good/bad examples
=> Improve e2e docs on PO usages

shell/components/form/ArrayList.vue, shell/pages/c/_cluster/apps/charts/install.vue
Fixes #11927
Reduce the height of humongous `input` elements in the ArrayList component
- use the correct `$unlabeled-input-height` variable for the height of a basic input field
- previously this was `$input-height`, designed for input with a label
Additionally
- Sneaked in a comment linking to an issue in another bit of code (which will help anyone who tries to utilise it)
Fleet Create Repo
OPA Gateway Constraint
Storage Class Customize Mount Options
Fleet Create Repo
OPA Gateway Constraint
Auth Provider Allowed Principals (unchanged)
Storage Class Customize Mount Options
- Cluster Management --> Clusters --> Create --> RKE2 --> Cluster Configuration Advanced --> view all inputs in tab
=> Fix humongous height of inputs in array list

shell/components/InputOrDisplay.vue
On Harvester, we have some errors when using the `InputOrDisplay` component as a container - probably something related to the use of `setup` function or dynamic HTML build.
https://github.com/torchiaf/harvester/blob/62da7658669d156d63b0d385a2978ab9d37637de/pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineCpuMemory.vue#L81-L94
The current PR just simplify the implementation and fixes the issue.
After
=> Simplify InputOrDisplay.vue component

shell/components/ResourceDetail/index.vue
This resolves an issue that we've been seeing in edit components where the `resource` data prop, being passed to dynamically rendered components via `v-bind="$data"`, is overwriting props in a grandchild component at the root of the child. The root cause of this issue is directly attributed to how Vue3 manages fallthrough attributes[^1][^2].
[^1]: https://vuejs.org/guide/components/attrs.html#fallthrough-attributes
[^2]: https://vuejs.org/api/built-in-directives.html#v-bind
Fixes #
- rename `resource` to `resourceType` to prevent `resource` colliding with granchild props as a fallthrough attribute
I'm identifying all instances of `resource:` in our edit components with the following
```
grep -rc --exclude-dir=node_modules/ 'resource:' shell/edit/ | grep -v ":0" …
```
=> Rename `resource` to `resourceType` in `ResourceDetail`

pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue, pkg/rancher-components/src/components/Form/Radio/RadioButton.vue, pkg/rancher-components/src/components/Form/TextArea/TextAreaAutoGrow.vue, pkg/rancher-components/src/components/StringList/StringList.vue, pkg/rancher-components/src/shim-vue.d.ts
This resolves typescript warnings for Rancher Components.
Fixes #11977 
- Update `pkg/rancher-components/src/shim-vue.d.ts`
- Remove instances of `@ts-nocheck`
- Resolve each error flagged by tsc
=> Resolve typescript warnings for Rancher Components

shell/edit/logging-flow/index.vue
This resolves an issue with adding a include / exclude pod card to the list when creating a new flow for the logging chart.
Fixes #11933 
- replace `set()` usage with assignment
- create a new array to ensure that reactivity is triggered for `matches`
We encountered a similar issue related to using push that was resolved in #11788
- https://github.com/rancher/dashboard/pull/11788/files#diff-ac9d14c56bc5c1631a8b0bb855b7d34cb69d9d1be89f1c3b72c31f03381939f7R160
- Logging (see issue description)
- Logging (see issue description)
=> Fix logging flow rules

shell/components/SortableTable/index.vue
These emits were being done within the selection.js mixin. I looked through all the other mixins and didn't find additional emits.
I noticed this while working on harvester.
You can try selecting items on listing pages and look to see if there's emit warnings in the console.
None, emits really don't seem to do much more than annotate interfaces.
=> Adding missing emits values to sortable table

shell/components/CopyCode.vue
Fixes https://github.com/rancher/dashboard/issues/12004
Migrate to Vue3 `slots` API.
=> Fix `slots.default` API

cypress/e2e/tests/pages/generic/about.spec.ts, shell/assets/translations/en-us.yaml, shell/config/uiplugins.js, shell/pages/c/_cluster/uiplugins/index.vue
Fixes #11996 
- fix problem with `semver.satifies` and version strings with suffixes by removing them using `semver.coerce` (removes `-rcXXX`, `-head`, `-013565asd123sdf34-head`, etc)
- have special logic to do a rancher version check as in `-head` versions of Rancher, the rancher version check is not employed by the backend, therefore we can't rely on it and do it on the frontend side
- remove duplicated method `isChartVersionAvailableForInstall ` as it was duplicated with `isSupportedChartVersion ` and adjust logic
- This will also fix a related problem that Elemental QA just reported. Check issue body
- Will need forward-porting to `master`
=> Fix e2e tests failing on 2.9 because of extension version that shouldn't be available to install

shell/models/management.cattle.io.user.js
This fixes an issue with sorting user retention values in in the users table by defaulting to 0 in the event that the value would be `undefined`.
Fixes #12013 
- Default to 0 instead of `undefined`
It appears that sortable table does not sort nicely when working with values like `undefined`; the table will end up with a mixture of values that are sorted in seeming random order. This might be a good area to investigate in the future.
- Sorting by Last Login, Disabled In, Deleted In in the users table 
- Sorting by Last Login, Disabled In, Deleted In in the users table
=> Fix sorting for user retention fields

cypress/e2e/tests/pages/explorer/apps/charts.spec.ts, shell/pages/c/_cluster/apps/charts/chart.vue, shell/pages/c/_cluster/apps/charts/install.vue
Fixes #11931
The issue was caused due to a watch on the `$route.query` object, when that changed we would call `$fetch` a second time before leaving the page.
Added a condition to check for an empty query object before calling `$fetch`
When navigating backwards (from `apps/charts/chart` to `apps/charts`) the query object is empty, the watch is still used when the route contains the query, e.g. when selecting a different version from the Readme view.
- Navigate to `apps/charts`
- Select a chart
- Ensure the version select still works
- Navigate back to the charts page
- Ensure no errors are logged in the console
https://github.com/user-attachments/assets/abac7e37-fdb2-4765-a79b-faa113fc3be4
=> Ensure fetch is not called when navigating backwards

shell/pages/c/_cluster/fleet/index.vue
Fixes #11883 
- remove `v-bind` of `$attrs` that was wrongfully propagating an `outlet` class
=> Fix: Vue3: Fleet's dashboard table has too much padding

shell/components/ResourceDetail/Masthead.vue, shell/detail/workload/index.vue
Fixes #11905 
- Fix spacing issue in `deployments` restart count in Masthead
- Fix extra Namespace column in the table for `pods` in `workloads` detail view (check example `fleet-controller` deployment via `workloads` list -> detail view)
**1. Extra editor tab** -> no need to fix, as per https://github.com/rancher/dashboard/issues/11905#issuecomment-2367670918
=> Fix Vue3: Several issues on Pod detail view

shell/assets/translations/en-us.yaml, shell/config/product/cis.js, shell/edit/cis.cattle.io.clusterscan.vue, shell/models/cis.cattle.io.clusterscan.js, shell/models/cis.cattle.io.clusterscanprofile.js
Fixes  #11911, #11915     => ( epic  #11799 ) 
- modify `clusterscan` model to apply defaults on edit/create view instead of model because of schema diet changes ( `v1/schemaDefinitions` information is not available when hard refreshing the edit/create/detail views)
- add missing translations in `clusterscan` edit view
- fix broken links in `clusterscan` and `clusterscanprofile`
- Install CIS Benchmark cluster tool helm chart
Cluster --> Tools --> install CIS Benchmark --> refresh
- Check all resource views in CIS Benchmark ( `clusterscan`, `clusterscanprofile`, `clusterscanbenchmark`)
=> Fix Vue3: CIS Benchmark issues

cypress/e2e/po/edit/provisioning.cattle.io.cluster/create/cluster-create.po.ts, cypress/e2e/tests/pages/global-settings/peformance.spec.ts, cypress/e2e/tests/pages/manager/cluster-manager.spec.ts, cypress/e2e/tests/pages/manager/mock-responses.ts, docusaurus/docs/extensions/api/components/node-drivers.md, shell/components/Questions/index.vue, shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/models/nodedriver.js, shell/store/type-map.js
Fixes #11982
Fixes #11983
I've combined these fixed into a single change, mainly to reduce testing overhead (and also given the size of the second fix)
Fix 1 - Allow node driver addCloudCredentials property to be overriden
- Node drivers will [now](https://github.com/rancher/dashboard/pull/10403) skip cloud cred requirment when creating a cluster given the node drivers spec.addCloudCredentials value
- However some drivers included in rancher have the incorrect value (see [here](https://github.com/rancher/rancher/blob/7bd6951a7d07f8b00b61811fd89cc673319f85b4/pkg/data/management/machinedriver_data.go#L140))
- To avoid tracking down all providers allow a workaround
- Allow ui extensions to override the addCloudCredentials value by supplying `plugin.register('cloud-credential', '<provider>', …
=> Fix two node driver based issues

shell/edit/resources.cattle.io.backup.vue
Fixes https://github.com/rancher/backup-restore-operator/issues/554
This change seeks to make the default form value match the one we cite as recommended on the page.
Because Rancher Backups may contain secrets this visual nudge towards encryption reinforces our recommendation.
Many users may be hosting their own S3 they feel is secure enough and can easily opt-out still.
The larger concept here is that our defaults currently opt for ease of use over security.
This minor change aligns more with best-practice will only adding a very small friction for users opting out of higher security via encryption.
Any GUI tests that expect `useEncryption` to be false by default will see a different default option.
Unless already covered by tests, I'm not sure if changing the default needs to be …
=> Adjust Rancher Backups default encryption setting value

cypress/jenkins/init.sh
First part of https://github.com/rancher/qa-tasks/issues/1549
Adding logic to execute the Jenkins CI initialization script on Alpine Linux images. This allows the execution on the new runners.
Explicitly set the `GOROOT` to the downloaded golang extracted tar.
Everything else is shell agnostic and runs transparently in then `ash` shell.
Alpine Linux isn't binary compatible by default with the golang Linux binaries as it ships with the C lib `musl`. The go binaries require `glibc`. Adding `gcompat` fix this.
Jenkins
=> [UI] - Adding logic to enable init.sh execution on Alpine Linux

shell/pages/c/_cluster/apps/charts/install.vue, shell/store/catalog.js
This removes the ability to add custom steps while installing charts. 
Several issues with this feature were uncovered while reviewing #12010. Most notably, custom steps would fail to render if specific top-level variables (`label`, `subtext`) weren't defined. Since this feature does not appear to be in active use, we decided to remove it at this point.
Fixes #11898 
- Remove the ability to add custom chart steps
- Add `markRaw` to dynamically rendered component to prevent Vue from warning about adding reactivity to components that don't need it
- Installing charts
- Installing charts
=> Remove custom chart steps feature

shell/components/form/ArrayList.vue
This is in support of Harvester. The forked version of ArrayListSelect was using this field in this way:
You can add the required field to any array list which has a title.
Shouldn't be any. Respects the existing default of false.
This change adds the exact same visual that was present in harvester even though I don't love it:
=> Allow users to specify that an array list is required

cypress/e2e/tests/navigation/side-nav/product-side-nav.spec.ts, shell/components/nav/Type.vue, shell/components/nav/__tests__/Type.test.ts
Fixes #11904 
In Vue 3, isActive behavior has changed:
https://router.vuejs.org/guide/essentials/active-links#When-are-links-active-
https://v3.router.vuejs.org/api/#active-class
Created computed property that matches old behavior to use instead of router's isActive.
Note: If you navigate to workloads, close group tab and re-open it again, 'Workload' tab is not highlighted. This is unrelated to Vue3 migration and can be reproduced on 2.9. It is not part of this fix and we might want to address it in the future.
Changed behavior to match Vue2
1. Go to "Local" cluster -> Workloads -> Pods
2. Click on any pod to go into "Details" page
3. "Pods" should still be selected in side nav
Side bar navigation
https://github.com/user-attachments/assets/c16fb751-e5ac-4ddc-9f86-a1b271744800
=> Vue3: Fixed navigation active style not applied

shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml
2.8 Backport of #12021
This PR adds a translation for `ovhcloudmks` kontainer driver, so that it can show correctly `OVHcloud MKS` in the UI.
Adds 2 lines with a mapping ovhcloudmks: OVHCloud MKS in the translation yaml files.
Simple
Nothing in particular, OVH will test this.
Risk is extremely low for regressions
=> [Backport 2.8] Adding translation for OVHCloud Managed Kubernetes Service

shell/components/ButtonMultiAction.vue, shell/components/ExplorerProjectsNamespaces.vue, shell/components/SortableTable/index.vue, shell/components/__tests__/ButtonMultiAction.test.ts
This creates a new button component, `ButtonMultiAction.vue`, and replaces two targeted instances to address styling issues with Projects/Namespaces. 
There are other instances that can be replaced, but they have been left untouched to limit the scope of this change.
Fixes #12007 
- Create new component, `ButtonMultiAction.vue`
- Replace in-table multi action button
- Replace in-table multi action button in `shell/components/ExplorerProjectsNamespaces.vue` 
While investigating the issue, it became clear that there is a difference between how scoped styles are applied to slot content in Vue3 when compared to previous versions of Vue. Looking at the similarities between the two implementations told me that a component could be created.
An alternative approach would be to duplicate the class …
=> Create new `ButtonMultiAction.vue` component

shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml
2.9 Backport of #12021
This PR adds a translation for `ovhcloudmks` kontainer driver, so that it can show correctly `OVHcloud MKS` in the UI.
Adds 2 lines with a mapping ovhcloudmks: OVHCloud MKS in the translation yaml files.
Simple
Nothing in particular, OVH will test this.
Risk is extremely low for regressions
=> [Backport 2.9] Adding translation for OVHCloud Managed Kubernetes Service

shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml
This PR adds a translation for `ovhcloudmks` kontainer driver, so that it can show correctly `OVHcloud MKS` in the UI.
Adds 2 lines with a mapping ovhcloudmks: OVHCloud MKS in the translation yaml files.
Simple
Nothing in particular, OVH will test this.
Risk is extremely low for regressions
=> Adding translation for OVHCloud Managed Kubernetes Service

shell/edit/provisioning.cattle.io.cluster/rke2.vue
This corrects the key used for version info assignment from `chartName` to a computed property name. This regression was introduced during the initial Vue3 migration push while attempting to get a functional RKE2 provisioning[^1]
This also corrects keys that were incorrectly replaced at the time. 
[^1]: https://github.com/rancher/dashboard/commit/31646c2eae647c090accdc1e777f247779f6cc6f#diff-6836ab4af70ed1f33db60d2de9a0087b636d7604c3f1cf6bb6525f50f16a69aeR1544
Fixes #12016 
- Update all invalid instances where set was replace and a computed property name should have been used
- We might want to double-check the linked commit[^1] for any other instances that might have been overlooked
- RKE2 cluster provisioning (instructions in linked issue)
- RKE2 cluster provisioning
=> Correct key for version info assigment

shell/assets/translations/en-us.yaml, shell/config/uiplugins.js, shell/pages/c/_cluster/uiplugins/PluginInfoPanel.vue, shell/pages/c/_cluster/uiplugins/index.vue
Fixes #12001 
**Forward-port of PRs #11997 and #12018** 
- Forward-port of PRs #11997 and #12018
**To test on a 2.9 and 2.10 systems**
- Add the `ui-plugin-examples` repo -> branch `main` and make sure that messages in the extension card and slide-in panel buttons are matching the annotations for that repo
- Add the `elemental-ui` repo -> branch `gh-pages` and make sure that messages in the extension card and slide-in panel buttons are matching the annotations for that repo
**2.9**
**2.10**
=> forward-port PRs 11997 and 12018

cypress/e2e/po/detail/node.po.ts, cypress/e2e/po/pages/cluster-manager/namespace.po.ts, cypress/e2e/tests/pages/explorer2/nodes/node-detail.spec.ts, shell/components/ResourceDetail/Masthead.vue
Fixes https://github.com/rancher/dashboard/issues/11815#issuecomment-2364194178
=> refactor node detail e2e  test to use detail page po

.github/workflows/release-shell-pkg.yaml
This Fixes an issue with legacy shell package publishing that is caused by a node-version mismatch between the runner environment and verdaccio requirements.
Example [failed run](https://github.com/rancher/dashboard/actions/runs/11056962212/job/30719699143#step:7:40)
- Removed corepack enabling step and duplicate node env setup
- Skipped test-plugin-build step as verdaccio will not be compatible with the node env (`v16.20.2`)
<details>
<summary><b><i>Shell publish local test run</b></i></summary>
```console
$ act -W .github/workflows/release-shell-pkg.yaml --env GITHUB_REF_NAME=shell-pkg-v2.0.2-rc.1 --env GITHUB_REF=refs/tags/shell-pkg-v2.0.2-rc.1 -q
INFO[0000] Using docker host 'unix:///var/run/docker.sock', and daemon socket 'unix:///var/run/docker.sock' 
[Publish Shell Package/build] 🚀 …
```
=> Fix publish shell workflow node-version mismatch

shell/assets/translations/en-us.yaml
Contributes to #12067 
As part of the manual backport of #12067, the warning message needed to be updated since the tabs for addon configs got separated.
=> Update warning message

shell/components/form/LabeledSelect.vue
This filters the attrs that have already been applied to the wrapper `div` of `LabeledSelect` so that they don't get applied to the inner `v-select`.
This duplicate application was causing additional classes like `mr-10` & `in-input` to be applied to both the wrapper `div` and `v-select`, causing visual regressions when custom classes were applied.  
Fixes #11954 
- Filter attrs to be applied to `v-select` in `LabeledSelect.vue`
- This looks related to issues that were addressed by #11869
- This changes all instances of `LabeledSelect`, so we will need to assert that other usages haven't regressed
- All instances of `LabeledSelect`
=> LabeledSelect: Filter `$attrs` applied to `v-select`

shell/components/nav/Header.vue, shell/components/nav/HeaderPageActionMenu.vue, shell/composables/useClickOutside.ts
This creates a new component for the header page actions. 
I chose to create a new component because I found that it was easier to troubleshoot and iterate upon the component while troubleshooting issues with the click behavior. 
Fixes #12025 
- Extract page actions into a new component (`HeaderPageActionMenu.vue`)
- Create a new composable to allow for fine-grained control for detecting clicks outside of page actions
The blur event of the original implementation was conflicting with click events for items within the dropdown, resulting in the dropdown closing before the actual selection was made. The approach taken here aims to accomplish the following:
1. Simplify the template for the page actions
2. Allow for more control over click behavior to toggle the dropdown
- Page actions menu
- …
=> Resolve issues with selecting page actions

shell/store/growl.js
This replaces the growl `stack` array so that it's guaranteed the watcher in `shell/components/GrowlManager.vue` will more reliably trigger when changes are made.
https://github.com/rancher/dashboard/blob/9489da3568db485d75b2dae49b580df4c6099f2b/shell/components/GrowlManager.vue#L17-L25
Fixes #12097 
- Use the spread operator to build a new array instead of using push to reliably trigger reactivity
While testing, I noted that the behavior was very inconsistent. There were times that the countdown timer would init and others where nothing would happen. 
We've seen this behavior in other areas where mutations methods aren't reliably triggering reactivity. I think that it makes sense to follow-up with a minimal repro to understand why exactly this can be an issue. The Vue docs explicitly …
=> Mutate growl stack in a reactive way

shell/edit/provisioning.cattle.io.cluster/rke2.vue
Contributes to #12067 
As part of the manual backport of #12067, the additionalmanifest component was missing the refresh yaml trigger that it had before being separated from Add-on config tab.
=> Fix additional manifest yaml issue

shell/edit/provisioning.cattle.io.cluster/rke2.vue
Contributes to #12067 
As part of the manual backport of #12067, the additionalmanifest component was missing the refresh yaml trigger that it had before being separated from Add-on config tab.
=> Fix initial additionalManifest render issue

shell/components/nav/TopLevelMenu.vue, shell/components/nav/__tests__/TopLevelMenu.test.ts, shell/pages/home.vue
Fixes #11999
Fixes #12009
Issue one - No Local Pagination in Home Page clusters list
- List has proven bad a performing at scale (~700 clusters can add CPU bottlenecks for searching, leaving page, etc of ~13 seconds)
- Enable local pagination to render less and improve performance
Issue two - Burger menu clusters lists scale badly with lots of clusters
- Before PR
- loop over all clusters 16 times
- root clusters computed method call took ~700ms
- i've seen this take over a second on other installs, and is called multiple times in a row, blocking UI until complete
- With PR
- loop over all clusters 6 times (could be less, but we start hitting churn in other ways
- root clusters computed method call takes ~85ms
- Details
- Root clusters list (2 loops dropped)
- Key prov clusters by mgmt …
=> Improve performance of home page when there are lots of clusters

cypress/e2e/blueprints/explorer/workloads/deployments/deployment-create.ts, cypress/e2e/po/components/button-dropdown.po.ts, cypress/e2e/po/components/labeled-select.po.ts, cypress/e2e/po/components/tabbed.po.ts, cypress/e2e/po/components/workloads/container-mount-paths.po.ts, cypress/e2e/po/components/workloads/pod-storage.po.ts, cypress/e2e/po/components/yaml-editor.po.ts, cypress/e2e/po/pages/explorer/workloads/workloads.po.ts, cypress/e2e/tests/pages/explorer2/workloads/deployments.spec.ts, shell/components/ButtonDropdown.vue, shell/edit/workload/index.vue, shell/edit/workload/storage/ContainerMountPaths.vue, shell/edit/workload/storage/index.vue, shell/models/workload.js
Fixes #11957 
Fixes #12020 
This PR includes a few fixes for pod and container storage. 
#11957  - corrected issue with codemirror not rendering
#12020 - fixed issue with slot content not rendering + issues with prop mutation in ContainerMountPaths
- view config of a workload with projected volume source 
- edit config of a workload with projected volume source 
- create/edit a workload with volumes and container volume mounts
You will need a deployment with a projected volume defined to test #11957
<details>
<summary>sample workload</summary>
```
metadata:
name: test-multi-vol
spec:
progressDeadlineSeconds: 600
replicas: 1
revisionHistoryLimit: 10
selector:
matchLabels:
workload.user.cattle.io/workloadselector: …
```
=> Vue3 fix workload storage

cypress/e2e/tests/pages/global-settings/settings-p2.spec.ts, shell/assets/translations/en-us.yaml, shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/edit/provisioning.cattle.io.cluster/tabs/AddOnAdditionalManifest.vue, shell/edit/provisioning.cattle.io.cluster/tabs/AddOnConfig.vue, shell/utils/cluster.js
Fixes #12066 
Moved `additionalManifest` section from `AddOnConfig.vue` to its own component, so it can be a separate tab.
Moved `labelForAddon` method to `shell/utils/cluster.js` in order to be re-used in couple of places as a helper.
Updated `rke2.vue` and `AddOnConfig.vue` in order to show separate tabs for each add-on configuration.
- Addon configuration should be correctly applied when creating a cluster
- Addon examples
- each Container Network (see Basics tab) has it's own config
- vSphere provider
- This is specific per kube distro, kube version and cloud provider. Changing this combination may result in different chart values
- Additional Manifest should be correct applied when creating a cluster
Provisioning clusters.
=> Split RKE2 Addon Configuration out into multiple tabs

pkg/harvester-manager/l10n/en-us.yaml, pkg/harvester-manager/machine-config/harvester.vue, shell/assets/translations/en-us.yaml
Related issue https://github.com/harvester/harvester/issues/5774
Blocked by https://github.com/harvester/dashboard/pull/1154
Blocked by https://github.com/harvester/pcidevices/pull/91
- https://github.com/harvester/harvester/pull/6096 introduced the new `/v1/harvester/cluster` endpoint to provide available Harvester resources; we are now using those information to get the allocatable number for each vGpu device.
- Fixing the vGpu validation; We are now counting the `nodePools` x `machineCount` to check if there are enough  vGpu devices to be assigned to each machine.
- In legacy Harvester versions - `/v1/harvester/cluster` endpoint is not available and the UI will not be able to calculate the `allocatable` label. We will leave it empty - see screenshots-  and add some notes in the …
=> Improve vGPU allocation

shell/edit/networking.k8s.io.ingress/RulePath.vue
Fixes #12011
Although I have not been able to reproduce a case where the definition breaks (https://codesandbox.io/p/sandbox/yy4cgk), this PR addresses the styling issue by correcting the `:deep()` definition got lost during the migration.
Navigate to `Ingress edit > Rule path` (e.g.: `/c/local/explorer/networking.k8s.io.ingress/create#rules`
=> Fix Ingress Rule Path CSS

shell/components/form/LabeledSelect.vue, shell/components/form/__tests__/LabeledSelect.test.ts
Fixes #12117 
- fix issue with `LabeledSelect` in mode multiple by allowing the binding of the attribute to the element `v-select` that was incorrectly being filtered out
- Test repro case(s) in issue + test some other areas that use `LabeledSelect` with `multiple="true"`
- Just to discard any regressions, do a quick test of different instances of `LabeledSelect`, even if they don't use  `multiple="true"`
=> fix bug with LabeledSelect with "multiple" attribute

cypress/e2e/po/side-bars/product-side-nav.po.ts, cypress/e2e/tests/pages/manager/jwt-authentication.spec.ts, shell/config/product/manager.js
Fixes #11461 
Simple fix to add the `ifHaveType` to the product configuration.
Automated test added for standard user.
=> Hide JWT Authentication if user does not have access to the required type

shell/models/steve-schema.ts
Fixes #11615
- /schemaDefinition requests can fail due to cache recreation
- previously this would return a 500 and we'd try a number of times again hoping cache comes back up
- the status code is now a more accurate 503, so plug that in
- i saw some cases where 500 recovers, so keeping that in there
=> Handle more accurate schemaDefinition cache updating error response

shell/components/nav/Header.vue
Fixes https://github.com/harvester/harvester/issues/4040
- We are setting the `$route` to `immediate: true` so that it runs again when refreshing the browser's window and imports again the `NavHeaderRight` component.
=> [backport 2.8] Fix Nav Header elements on page refresh

shell/components/nav/Header.vue
Fixes https://github.com/harvester/harvester/issues/4040
- We are setting the `$route` to `immediate: true` so that it runs again when refreshing the browser's window and imports again the `NavHeaderRight` component.
=> [backport 2.9] Fix Nav Header elements on page refresh

shell/scripts/extension/bundle
Fixes #12153 
- fix issue `-printf` not working on mac os
The reason for this is that the `-printf` option is not supported by the default`find` command on macOS because it uses the BSD version of find, which doesn't have this option. The `-printf` option is available in the GNU version of find, commonly found on Linux systems.
- Follow instructions on issue
=> [Backport] fix issue -printf mac os not working

shell/assets/styles/global/_tooltip.scss, shell/components/fleet/FleetStatus.vue
Fixes #11967
It seems most issues with this dropdown have been fixed, likely by https://github.com/rancher/dashboard/pull/11880. This PR removes a lingering arrow. Compared to 2.9 there is a slightly larger margin at the top of the dropdown but I think it needed it - previously the dropdown appeared to be touching the summary text (see screenshots)
Fleet summary count dropdowns
none
this PR:
In 2.9:
=> fix fleet summary tooltip styling

package.json, yarn.lock
This bumps yaml to 2.5.1
Fixes #12090 
It looks like this dependency is only used in `pkg/harvester-manager/machine-config/harvester.vue`
- `pkg/harvester-manager/machine-config/harvester.vue`
=> Bump `yaml` to 2.5.1

shell/components/nav/Header.vue, shell/components/nav/HeaderPageActionMenu.vue
This properly scopes styles for `.actions` in the header to `HEADER.rd-header-right`. 
A regression in header styles was introduced in #12076 where a new component was created for the header actions. The styles associated with the actions were migrated over into the new component, removing this specificity; headers used throughout Dashboard then contained actions with the following styles to cause a center alignment:
```
align-items: center;
cursor: pointer;
display: flex;
```
Fixes #12108 
Fixes #12162
- Remove offending styles for the action class from `HeaderPageActionMenu.vue`
- Reintroduce styles for the action class to `Header.vue` 
This is a CSS specificity issue where we have a special case to control actions in the page header vs. actions that are used in different section …
=> Fix style regression in header component

shell/models/management.cattle.io.cluster.js
Fixes #11874 
The dashboard is setting the wrong value for the `provider` query param when loading some ember pages. It looks like the bug came in here https://github.com/rancher/dashboard/pull/9868/files#diff-9be0247bdd17368e0b020b8ab4933b0c53f2f4bbdb0b1936066fa67703e519d4R91 
It seems that #11874 is happening because when a new cluster template revision is selected, some ember components re-initialize, and at that second partial load, the incorrect `provider` query param causes ember to not load rke1 form components. There's probably something messy going on over in Ember, but fixing the query param being sent over seems the safest solution, vs digging into ember route-changing logic.
Verify that the right create/edit pages load for the following cluster types:
- RKE1 custom
- RKE2 …
=> Fix RKE1 upgrading via template

shell/package.json, shell/scripts/publish-shell.sh, shell/scripts/typegen.sh
Fixes #12147
The `node_modules/.bin` is no longer accessible due to a typo within the `BASE_DIR` variable
- Replaced the single `&` with a double `&&` in both publish-shell.sh and typegen.sh scripts 
- Added `pipefail` to `publish-shell` script to ensure it will exit when a command has an error
Using a single ampersand & instead of a double ampersand && will run the preceding command in the background rather than sequentially. 
- Publishing of shell packages
=> Fix reference to tsc binary when publishing shell

shell/plugins/global-formatters.js
This modifies the regular expression that matches components in `shell/plugins/global-formatters.js` so that only one set of components is matched by `require.context()`.
Fixes #11786 
- Update the regular expression that matches global formatters
Inspecting the components reveals that there are two sets of components that are matched by `require.context()`, for example:
```
./AppSummaryGraph.vue
components/formatter/AppSummaryGraph.vue
```
This looks to be a breaking change in Webpack5, but documentation about this breaking change is hard to find, but a comment left in a webpack issue somewhat confirms this change in behavior[^1].
[^1]: https://github.com/webpack/webpack/issues/12087#issuecomment-737872247 
- Loading global formatters
- Loading global formatters
=> Remove duplicate global formatters matched by `require.context()`

shell/components/nav/Header.vue, shell/components/nav/HeaderPageActionMenu.vue
This fixes regressions in header tooltips that were introduced in #12076 by reintroducing styles that were removed from the `Header.vue` and overriding styles in `HeaderPageActionMenu.vue` with the deep selector. 
Fixes #12174 
- Reintroduce styles to `Header.vue` that were removed in #12076
- Attach popover to div in `HeaderPageActionMenu.vue` so that styles can be accessed via `deep` selector 
It became obvious that the original implementation only worked because of the global styles bug that was corrected in #12172. This PR aims to undo some changes and fix the header popover styles so that they won't regress from 2.9. 
Header changes have affected different areas of dashboard in the past, it's important to make sure that the following are styled as expected:
- Page header for the …
=> Fix header tooltip styles

cypress/support/e2e.ts, package.json, yarn.lock
Fixes #
https://github.com/rancher/qa-tasks/issues/1549
Adding the `cypress-mochawesome-reporter` library to generate an HTML report on Jenkins including zipped screenshots
Adding as `devDependency`
GA CI
Jenkins CI
Automation pipelines
=> [Automation][v2.8] - adding cypress-mochawesome-reporter for jenkins html report

cypress/e2e/tests/pages/global-settings/feature-flags.spec.ts
Feature flag test is failing eg https://github.com/rancher/dashboard/actions/runs/11260516944/job/31313511381 We have hardcoded the expected number of features as 15. The number of feature flags in rancher has increased to 16 https://github.com/rancher/rancher/pull/47437
=> update feature flag table test to dynamically check feature flag count

shell/config/labels-annotations.js, shell/models/cloudcredential.js
Contributes to #11270
- Update label with latest value
- Improve fn that updates cloud cred fn
- make it more efficient when fetching cluster
- add consistent error handling
- annotation update hasn't been merged yet, so when testing it needs to be reverted
=> Update harvester cloud cred expiration annotation, improve renew function

shell/package.json, shell/scripts/publish-shell.sh, shell/scripts/typegen.sh
Fixes #12186 
The `node_modules/.bin` is no longer accessible due to a typo within the `BASE_DIR` variable
- Replaced the single `&` with a double `&&` in both publish-shell.sh and typegen.sh scripts 
- Added `pipefail` to `publish-shell` script to ensure it will exit when a command has an error
Using a single ampersand & instead of a double ampersand && will run the preceding command in the background rather than sequentially. 
- Publishing of shell packages
=> [Backport 2.8] Fix reference to tsc binary when publishing shell

shell/package.json, shell/scripts/publish-shell.sh, shell/scripts/typegen.sh
Fixes #12187
The `node_modules/.bin` is no longer accessible due to a typo within the `BASE_DIR` variable
- Replaced the single `&` with a double `&&` in both publish-shell.sh and typegen.sh scripts 
- Added `pipefail` to `publish-shell` script to ensure it will exit when a command has an error
Using a single ampersand & instead of a double ampersand && will run the preceding command in the background rather than sequentially. 
- Publishing of shell packages
=> [Backport 2.9] - Fix reference to tsc binary when publishing shell

shell/components/ExplorerProjectsNamespaces.vue
This uses the `fullColspan` slot prop for calculating the `colspan` of empty content slots in `shell/components/ExplorerProjectsNamespaces.vue`; `fullColspan` allows for properly filling available space in the table when columns are dynamically added via extensions.
Fixes #11474 
- Replace `colspan="5"` with `:colspan="fullColspan"` for both empty content slots in `shell/components/ExplorerProjectsNamespaces.vue`
- Projects & Namespaces
- Projects & Namespaces
=> Use `fullColspan` for `projectsWithoutNamespaces`

pkg/gke/components/Networking.vue, pkg/gke/components/__tests__/Networking.test.ts
Fixes #8749 
GKE provisioning form no longer sets `clusterIpv4CidrBlock` ('Pod Secondary CIDR Block') when `clusterSecondaryRangeName` ('Pod Secondary Address Range') is set and no longer sets `servicesIpv4CidrBlock` when `servicesSecondaryRangeName` is set
Create a new gke cluster and select a Pod Secondary Address Range: the Pod Secondary CIDR Block input should be populated, but disabled, and the save request should include an empty string for `clusterIpv4CidrBlock`. Same deal with Services Secondary Address Range and `servicesIpv4CidrBlock`.
=> Fix GKE clusterIpv4CidrBlock and clusterSecondaryRangeName fields

shell/package.json, shell/scripts/typegen.sh
Fixes #12226 
When running the publish-shell workflow the typegen script would not include the necessary typescript definitions for the `@rancher/shell` library.
The issue was caused by incorrectly referencing the shell directory within the runner. When the script is ran locally there is no issue as the `shell` directory is accessible. However, within a workflow runner the `shell` directory was in a different location.
- Replaced the `BASE_DIR` value to use `git rev-parse --show-toplevel` to ensure the correct repository level regardless of the runner's current working directory.
- Replaced the `shell/*` directory matching when running the `tsc` command to `SHELL_DIR` which is accessible to the worker.
- Added a log of the contents within the `${SHELL_DIR}/tmp` directory.
- Publishing a …
=> typegen path fix

shell/mixins/create-edit-view/impl.js, shell/mixins/labeled-form-element.ts, shell/mixins/vue-select-overrides.js
Looks like these got missed in the original cleanup. I'm guessing these were missed because they were in mixins so I went through all of the mixins and found a couple more that were missed.
https://github.com/rancher/dashboard/issues/12130
None, no functional changes. It just cleans up some warnings.
=> Fixing more warnings around having the 'emits' component prop

shell/components/nav/Header.vue
Contributes to https://github.com/harvester/harvester/issues/4040
- We are setting the `$route` to `immediate: true` so that it runs again when refreshing the browser's window and imports again the `NavHeaderRight` component.
=> Fix nav-headers

shell/vue.config.js
This removes tests from Dashboard's main bundle.
Fixes #12244 
- Use webpack ignore plugin to omit all `__tests__` directories
I found test files in production builds dating all the way back to v2.8.2. I'm unsure if we always contained test files, but it's clear to me that they need to be removed.
- Confirm that tests are removed from build artifacts
- Search for common test patterns to make sure tests aren't missed
- `yarn analyze` can help to confirm, alternatively inspect the primary `index.js` for deployed versions of Dashboard
- NA
- Taken from `webpack-bundle-analyzer`
=> Remove tests from bundle

shell/components/ResourceDetail/index.vue
This prevents ResourceDetail from invoking `fetch()` when navigating back. 
This PR applies existing work performed in #11986 to `shell/components/ResourceDetail/index.vue`.
Fixes #12219 
Fixes #12073
- add a guard to the `$route.query` watcher to prevent fetch from navigating when routing back
- We previously encountered this error in other areas, see #11986 for more details
- ResourceDetail is the only remaining component that needs to be addressed to resolve the problem
ResourceDetail involves almost every edit component in Dashboard.
Routing back in for edit components of Dashboard could break.
=> Prevent `fetch` when navigating on pages that contain `ResourceDetail`

cypress/jenkins/transform-junit.sh
Alpine doesn't allow libraries management using pip directly and encourage (enforces?) the use of their APK packages.
This will allow the transform of the XML Junit report used to report to Qase
Tested the install of the packages and the `python3` invocation in an AWS Alpine AMI.
=> [Automation] - Install libraries using apk if OS is Alpine

cypress/e2e/blueprints/explorer/rbac/third-party-principals-get.ts, cypress/e2e/tests/pages/explorer2/project-namespace.spec.ts, pkg/aks/components/CruAks.vue, pkg/eks/components/CruEKS.vue, pkg/gke/components/CruGKE.vue, shell/config/labels-annotations.js, shell/edit/management.cattle.io.project.vue, shell/edit/provisioning.cattle.io.cluster/index.vue
Fixes #11852 
This PR adds an annotation to projects and v3 clusters when using third-party auth. There is a corresponding [ember PR](https://github.com/rancher/ui/pull/5180) which covers rke1 clusters and importing aks/eks/gke clusters
Using local auth, verify that no principal id annotation is set when creating projects and aks/eks/gke clusters. Using third party auth, verify that the `field.cattle.io/creator-principal-name` is set when creating projects and aks/eks/gke clusters.
=> Set creator principal id annotation when creating projects and v3 clusters

shell/assets/styles/global/_tooltip.scss
This removes custom positioning of tooltip arrows that appears to have been causing regressions in tooltip arrow styles dependent upon placement. 
Fixes #12197
- Remove css attributes related to positioning for tooltip arrow and arrow container
I can assume that this was broken across the board with previous versions of `v-tooltip`, but these styles appear to be no longer needed now that we have migrated to `floating-vue`.
These are global styles that affect all tooltips used throughout dashboard.
The scope of this changes addresses all tooltips. We will want to confirm that arrows are properly located for tooltips that render
- to the top
- to the bottom
- to the left
- to the right
- a large amount of content
- a small amount of content
=> Remove custom positioning of tooltip arrows

cypress/e2e/po/components/sortable-table.po.ts, cypress/e2e/tests/pages/manager/cluster-provisioning-amazon-ec2-rke1.spec.ts, cypress/e2e/tests/pages/manager/cluster-provisioning-amazon-ec2-rke2.spec.ts, cypress/e2e/tests/pages/manager/cluster-provisioning-azure-rke1.spec.ts, cypress/e2e/tests/pages/manager/cluster-provisioning-azure-rke2.spec.ts, cypress/globals.d.ts, cypress/support/commands/rancher-api-commands.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1559
=> fix flaky provisioning tests

shell/config/labels-annotations.js, shell/models/catalog.cattle.io.app.js
Fixes #11675 
Adjusted matchingChart function to return chart with matching repository. This ensures that we do not prompt for upgrade apps that have higher version in an unrelated repo.
1. Added support for new label catalog.cattle.io/cluster-repo-name
2. Changed preferedChartName to chartName to make searching for matching chart return chart with correct repo 
1. Add 2 repositories:
test1: https://eva-vashkevich.github.io/helm_test/
test2: https://eva-vashkevich.github.io/helm_test2/
2. Go to Charts and install "cert-manager" version 0.1.0 from both repos call it cert-man1 and cert-man2
3. Go to "installed apps" and check that only cert-man2 has upgrade available
4. Go to repositories and remove "test1"
5. Go to "installed apps" and confirm again that only cert-man2 has upgrade …
=> [FEAT] Added support for cluster-repo-name label for app upgrades

shell/components/form/ArrayList.vue, shell/machine-config/vmwarevsphere.vue
Fixes #9817 
Fixes #12271 
This PR updates the vsphere machine config to use networks' `moid` instead of `name`.  This requires the use a new endpoint for networks, `meta/vsphere/networks-extended`, which contains extra information.
This PR also corrects a reactivity issue in ArrayList:
https://github.com/user-attachments/assets/a0ff1d3f-e66d-40d7-b761-87e2d983192d
Create an RKE2 vsphere cluster and verify that:
1. the machine pool is saved with the networks' moid instead of name
2. you are able to select a network other than the default (first) option
Create an RKE2 vsphere cluster with at least 1 network and 'vapp' auto mode selected ('Use vapp to configure networks with network protocol profiles'), verify that the save request vapp properties reference the network name, not full path …
=> update vsphere machine config to use new networks endpoint

shell/components/ResourceDetail/index.vue
This resolves an issue that was preventing the detail page from rendering. #12237 introduced a change that would prevent errors from being thrown if `fetch()` was invoked against a route without any keys in its query - a use case that was required for navigating between tabs in edit views.
This fix attempts to address a change in timing between route watchers and component unmounting by slightly modifying the approach taken in #12237 by watching the route and only allowing `fetch()` to re-invoke if the route hasn't changed. The differences observed appear to be related to:
- Vue2: Component unmounts before the route watcher invokes
- Vue3: Watcher triggers before the component unmounts, potentially raising unhandled exceptions during navigation between pages & tabs 
Fixes #12267 
Fixes …
=> Watch and compare route before re-invoking `fetch()` in ResourceDetail

shell/components/CodeMirror.vue
This modifies the CSS in `shell/components/CodeMirror.vue` so that styles can properly be applied to the keymap icons.
`.codemirror-container` and `.keymap.overlay` are siblings in the rendered DOM output. This change in styles reflects that.
There's now duplication in the grouping of our `.code-mirror` styles in `CodeMirror.vue`. I'm opting to leave the separate to reduce the amount of churn in this change, but I'm completely open to merging the two groups if we feel that's the best for future maintenance. 
Fixes #12195
- Refactor styles in `shell/components/CodeMirror.vue`
- CodeMirror styles
- CodeMirror with keymaps defined
- CodeMirror styles
=> Fix keymap icon positioning in codemirror

pkg/gke/components/CruGKE.vue
Fixes #11864 
This PR updates the gke provisioning form to ensure that any default configuration applied when creating clusters _copies_ the defaults defined in the component instead of _modifying_ the default configuration object, so that when the component is reused, the default configuration has not been changed.
1. Create a new GKE cluster and enable private cluster, private endpoint, and master authorized network (all under the advanced section of the networking tab)
2. After saving, go to create another GKE cluster: verify that the advanced networking section has been reset to default values (all 3 checkboxes unchecked)
none
=> fix gke provisioning form stale data

shell/mixins/vue-select-overrides.js
Fixes #12273 
As discussed with @codyrancher we probably don't want the emits array at all in `vue-select-overrides.js`. It does all the emitting on a vue instance that gets passed to the `mappedKeys` method.
Local -> Apps -> Charts
Click "All" dropdown
Try unselecting any item
n/a
=> Fix selection issue with the charts dropdown

shell/detail/provisioning.cattle.io.cluster.vue, shell/list/provisioning.cattle.io.cluster.vue, shell/pages/c/_cluster/apps/charts/index.vue
Fixes #11311
`window.c` is defined then never referenced. The 3 edited pages still render without errors.
cluster list view
cluster detail view
apps & marketplace charts list
=>  remove references to window.c

shell/models/provisioning.cattle.io.cluster.js
This resolves additional errors that can be raised in the console by using optional chaining when attempting to access `machineSelectorConfig`.
Fixes #12194 
- Use optional chaining when accessing properties of `machineSelectorConfig`
This resolves an entire class of errors that would previously print to the console.
- Creating RKE2 clusters, the issue has a test case to work with
- N/A
=> Use optional chaining on `machineSelectorConfig`

shell/assets/translations/en-us.yaml, shell/components/formatter/CloudCredExpired.vue, shell/components/formatter/Date.vue, shell/config/labels-annotations.js, shell/list/provisioning.cattle.io.cluster.vue, shell/models/cloudcredential.js, shell/models/provisioning.cattle.io.cluster.js, shell/pages/c/_cluster/manager/cloudCredential/index.vue
Fixes #11332
- Cherry-picked PR using commits from https://github.com/rancher/dashboard/pull/12038
- Also cherry-pick of https://github.com/rancher/dashboard/pull/12203
- Also fix for cloud cred annotation collection (backport https://github.com/rancher/dashboard/pull/12230)
=> [2.10] Show Cloud Credential Expiration information for Harvester Creds, add actions to renew

shell/plugins/dashboard-store/mutations.js
Fixes #12189
Fixes #12194
Fixes #12192
- `reactive` was applied to objects that made it into the store via loadAll (or loadPage)
- objects that are assigned to a component `data` object should also be reactive
- however there are scenarios where changes to existing or new properties on these object did not trigger reactivity (computed, watch, etc)
- fix is two parts
- Ensure all model instances that make it into the store are reactive
- where we just stick something from `classify` straight into the store... wrap it with reactive
- this covers almost all `loadX` functions (multi, selector, merge, add) and batchChanges
- Ensure new properties added to a reactive object aren't ignored
- in `replace` re-reactive the object if there's new properties
- As per issue
- Creating a resource, …
=> Update model reactivety

shell/edit/ui.cattle.io.navlink.vue
Fixes #11937 
- Add top-level non-custom element in order to fix error information when creating NavLink is not shown to user
Although the changes look bigger, what was needed to make it work was just adding a `div` as the outermost container to wrap the `CruResource` component. No errors were being thrown, so I don't know the root cause for this.
Also, it may be important to cover all of the `CruResource` usages to check if it's a general problem or not and act accordingly.
- Cluster Explorer --> Header `Resource Search` --> type in NavLink --> click on NavLink --> Create
- Enter `AAA` for the name --> Enter anything for `Destination URL` --> Create
- Should show the error from the network request to the user
https://github.com/user-attachments/assets/84a1d175-54e1-463e-a95c-b2b2cd514952
=> FIX: Vue3 => Error info when creating NavLink is not shown to user

shell/edit/cis.cattle.io.clusterscanbenchmark.vue, shell/edit/constraints.gatekeeper.sh.constraint/index.vue, shell/edit/fleet.cattle.io.cluster.vue, shell/edit/helm.cattle.io.projecthelmchart.vue, shell/edit/k8s.cni.cncf.io.networkattachmentdefinition.vue, shell/edit/kontainerDriver.vue, shell/edit/logging-flow/index.vue, shell/edit/management.cattle.io.projectroletemplatebinding.vue, shell/edit/management.cattle.io.user.vue, shell/edit/monitoring.coreos.com.alertmanagerconfig/index.vue, shell/edit/monitoring.coreos.com.alertmanagerconfig/receiverConfig.vue, shell/edit/monitoring.coreos.com.prometheusrule/index.vue, shell/edit/monitoring.coreos.com.receiver/index.vue, shell/edit/monitoring.coreos.com.route.vue, shell/edit/networking.istio.io.destinationrule/index.vue, shell/edit/nodeDriver.vue, shell/edit/provisioning.cattle.io.cluster/import.vue
This resolves an issue with Vue 3 fallthrough attributes overwriting props for root-level ancestor components by adding `inheritAttrs: false` to each component in question. Adding `inheritAttrs: false` to the component allows us to specify that fallthrough attributes should not be automatically applied to the root-level element in a component.
Fixes #12298 
- Add `inheritAttrs: false` to components that might have a conflict with fallthrough attributes and the `errors` prop in root-level components
See #12298 for additional notes on why certain components were not modified. We can still opt to add `inheritAttrs: false` to these components, but I'm of the mindset that it's better to only apply the change if it is needed.
See https://github.com/rancher/dashboard/pull/11956#issuecomment-24008 …
=> Add `inheritAttrs: false` to edit components

pkg/gke/components/Config.vue, pkg/gke/components/CruGKE.vue, pkg/gke/components/__tests__/Config.test.ts
Fixes #12261 
Fixes #12260 
updates the GKE provisioning form so that when a user selects a zone, the `locations` field (which otherwise maps to the list of extra zones) includes that zone. 
1. Create a 'zonal' GKE cluster without adding zones (default configuration), wait for the cluster to become active
2. Once the cluster has finished provisioning verify that you can edit it and add extra zones (`gkeConfig.locations` in the save request), and that the cluster is eventually 'active' again
3. Create a new 'zonal' gke cluster and define extra zones initially
4. Wait for the cluster to provision; verify that you can add/remove extra zones
=> include gke zone in list of extra locations

cypress/e2e/po/pages/explorer/cluster-dashboard.po.ts, cypress/e2e/tests/pages/explorer/dashboard/cluster-dashboard.spec.ts, shell/pages/c/_cluster/explorer/__tests__/index.test.ts, shell/pages/c/_cluster/explorer/index.vue
Fixes #12259 
This PR tweaks the logic used to show fleet and cattle agent statuses on the cluster explorer dashboard. Previously we checked that the user was able to list deployments; now we check that they can see the namespace the deployments would be in.
Cluster explorer dashboard with both local and downstream clusters (local will not show cattle agent), both as admin and a user with project membership only, as outlined in #12259
=> Fix fleet cattle healthcheck

cypress/e2e/tests/pages/explorer/dashboard/cluster-dashboard.spec.ts, shell/components/form/ColorInput.vue, shell/components/form/__tests__/ColorInput.test.ts
This adds a disabled prop to `ColorInput.vue` so that we can better control how the disabled state and styles are applied.
Fixes #12274 
- Add disabled prop to `ColorInput.vue`
- Add `isDisabled` computed prop to determine if `disabled` styles and state should be applied 
The original regression looks related to how fallthrough attributes are applied to components in Vue3. I thought it best to explicitly define a `disabled` prop so that we can more easily control disabled states in this component.
Anywhere that the color picker is used, see issue for more details.
Anywhere that the color picker is used.
=> Add disabled prop to `ColorInput.vue`

shell/components/SortableTable/actions.js, shell/components/SortableTable/selection.js, shell/mixins/browser-tab-visibility.js, shell/mixins/metric-poller.js, shell/mixins/resource-fetch.js
This replaces any remaining `beforeDestroy` lifecycle options with `beforeDestroy`, as mentioned in the Vue 3 migration guide[^1]. This change should also properly clean up the metrics poller, resolving the attached issue.
Fixes #12292 
- Replace `beforeDestroy` lifecycle option with `beforeUnmount`
I searched for instances of `destroyed` in Dashboard, but did not find any. I'm not aware of any other lifecycle options that would need to update at this point.
A lot of these lifecycle hooks are used in mixins. There's a good example to test in the associated issue, but also consider testing
- Sortable Table
- Resource Fetch
- Browser Tab Visibility
This should be fixing regressions in each of the affected areas, as `beforeDestroy` is no longer a valid hook.
=> Replace `beforeDestroy` lifecycle option with `beforeUnmount`

shell/assets/translations/en-us.yaml, shell/models/provisioning.cattle.io.cluster.js, shell/pages/c/_cluster/explorer/__tests__/index.test.ts, shell/pages/c/_cluster/explorer/index.vue
Fixes https://github.com/rancher/dashboard/issues/12221
=> Lowercase architecture labels

shell/edit/workload/mixins/workload.js, shell/models/workload.js
This clones `defaultContainer` to prevent this object from being modified by reference in container forms.
`defaultContainer` retains its values even after navigating away from the workload create form. This behavior was not observed in Vue2, and it requires further investigation to fully understand.
To address this issue in the short term, using `structuredClone` to create a deep copy of defaultContainer ensures that modifications to the container do not persist after navigating away from the form.
Fixes #12243 
- clone `defaultContainer` when applying defaults to workload forms
See case in attached issue.
This fixes an existing regression, I don't foresee this causing issues elsewhere.
=> Clone `defaultContainer` to apply defaults for workload forms

cypress/e2e/tests/pages/manager/kontainer-drivers.spec.ts
Enabling the Kontainer-Driver's can delete drivers in bulk e2e test. #12286 
This was disabled because it would block the workflow when we first migrated to vue3. We're now re-enabling those tests.
None, only an e2e test was modified.
None, only an e2e test was modified.
=> Enabling the Kontainer-Driver's `can delete drivers in bulk` e2e test.

shell/models/cloudcredential.js
Fix cloud-credential being displayed if the expiry annotation has a Unix timestamp of "0".
When Rancher is upgraded and there are cloud-credentials for a Harvester cluster without a token (e.g. when the token expired and purged or was manually removed), the cloud-credential's expiry will be updated with a Unix timestamp of "0" (i.e. as if the token had expired at 00:00 AM on Jan 1st 1970), since the actual time of expiry of the token can not be determined.
This fix makes the UI display such a cloud credential correctly as "expired".
Related to: https://github.com/rancher/rancher/issues/47583
Related to: https://github.com/rancher/rancher/issues/47667
When the cloud-credential annotation `rancher.io/expiration-timestamp` has the value `"0"`, the getter function `expires()` will return an …
=> Fix cloud-credential expiry display

cypress/e2e/tests/pages/manager/cloud-credential.spec.ts
Improve cloud cred e2e tests
- This is a direct cherry-pick of https://github.com/rancher/dashboard/pull/12206
=> [2.10] Improve cloud cred e2e tests

cypress/e2e/tests/pages/manager/registries.spec.ts, shell/edit/provisioning.cattle.io.cluster/tabs/registries/RegistryConfigs.vue
We weren't updating the model correctly in the RegistryConfigs, this fixes the updating and re-enables the appropriate test.
Possibly the Registry tabs in some resources like rke2.
=> Re-enabling `Registries for RKE2` e2e test 

shell/models/cloudcredential.js
Fix cloud-credential being displayed if the expiry annotation has a Unix timestamp of "0".
When Rancher is upgraded and there are cloud-credentials for a Harvester cluster without a token (e.g. when the token expired and purged or was manually removed), the cloud-credential's expiry will be updated with a Unix timestamp of "0" (i.e. as if the token had expired at 00:00 AM on Jan 1st 1970), since the actual time of expiry of the token can not be determined.
This fix makes the UI display such a cloud credential correctly as "expired".
Related to: https://github.com/rancher/rancher/issues/47583
Related to: https://github.com/rancher/rancher/issues/47667
When the cloud-credential annotation `rancher.io/expiration-timestamp` has the value `"0"`, the getter function `expires()` will return an …
=> [Backport v2.9] Fix cloud-credential expiry display

cypress/e2e/tests/pages/generic/home.spec.ts, shell/assets/translations/en-us.yaml
Fixes #12083 
Updated the what's new message for 2.10 and updated the version number in the link.
See screenshot.
Kept the message short - `Learn more about the improvements and new capabilities in this version and read about the UI framework migration in 2.10`
We will need to update the docs with more information.
To test, log in and view the updated banner on the home page. If it is hidden, click on the three dots icon in the top-right of the page and click on 'Restore hidden cards'.
I have updated the version number in the Chinese translation but not the message. This translation will be removed at a later date/time.
=> Update what's new message for 2.10

shell/models/cloudcredential.js
Ensure harvester cloud creds with expiration date of 0 are sorted correctly
- Follows on from https://github.com/rancher/dashboard/pull/12335
- and comment in https://github.com/rancher/dashboard/pull/12336
- sort order should be expired --> expiring --> never expires
- ensure expired 0 is not in the same bucket as never expires
- Harvester Cloud Credential page with an expired annotation value of 0 appear immediately after / before (depending on sort order) expiring and then expired tokens 
- I hacked `get expires()` for an easier production
=> Ensure harvester cloud creds with expiration date of 0 are sorted correctly

cypress/e2e/tests/pages/fleet/gitrepo.spec.ts, cypress/e2e/tests/pages/generic/diagnostic.spec.ts, cypress/e2e/tests/pages/global-settings/settings-p2.spec.ts, cypress/e2e/tests/pages/manager/repositories.spec.ts, shell/pages/diagnostic.vue
- Re-enabling Diagnostics Page e2e test
- Re-enabling can create an oci repository with basic auth e2e test
- Re-enabling the Git Repo e2e tests
- Enabling two more e2e tests in settings-p2
$route had a circular reference so I added it to a list of other fields that shouldn't be serialized.
The tests are doing that already
None
=> Enabling several E2E tests that were disabled for the vue3 migration

shell/models/management.cattle.io.cluster.js
Fixes #12272 
Improves the parsing of the badge color annotation.
Note, I tweaked the default badge color, so that the text color chosen is white - this has better contrast.
Test manually:
Edit the local cluster management resource from the kubectl shell, with:
`kubectl edit clusters.management.cattle.io local`
add annotations:
```
ui.rancher/badge-text: Example Text
ui.rancher/badge-color: '#ff0000     '
```
(note the trailing spaces)
Save the resource and verify that the cluster badge is shown correctly at the top:
update the badge annotation via the same shell method:
```
ui.rancher/badge-text: Example Text
ui.rancher/badge-color: '///'
```
Save the resource and verify that the cluster badge is shown correctly at the top with the default badge color:
=> Improve parsing of cluster badge color

shell/components/fleet/FleetClusters.vue, shell/detail/fleet.cattle.io.cluster.vue, shell/detail/fleet.cattle.io.gitrepo.vue, shell/models/fleet.cattle.io.gitrepo.js, shell/pages/c/_cluster/fleet/index.vue, shell/utils/string.js
Fixes #12232
- Performance Fix
- go back to using git repo status cluster ready / desired stats instead of costly clusterResourceStatus (churn can call this a LOT)
- Improve load time of fleet cluster detail page
- Bug Fix
- Using targetClustersReady and targetClusters doesn't seem to work in some cases, revert back to previous
- General Fixes
- Fix weird fleet cluster list column alignment
As per issue
- Git repo detail page loads fine (on navigation and refresh)
- Fleet Dashboard page shows correct stats for 
- clusters ready - now matches repo list's cluster stats 
- bundles ready - no change (except 0 now displays as such, rather than ?)
- resources ready - no change (except 0 now displays as such, rather than ?)
=> [2.10] Fleet Improvements

shell/pages/c/_cluster/apps/charts/install.vue
Fixes #12205 
Added a class to fix the styling issue by taking into account the footer height.
Same as described on the issue's repro steps.
Since the styling is applied to the banner itself only, there shouldn't be any side effects, hopefully.
https://github.com/user-attachments/assets/d81d8657-6e14-42a7-bfb4-78d2c1c5ff93
=> Fix namespace create banner in basics step

shell/components/form/HookOption.vue, shell/components/form/LifecycleHooks.vue
Fixes #12383 
Fixed httpget fileds not rendering when creating a workload.
Removed inner template tag since it looks like it was redundant.
Inner template and its content was treated by Vue as an HTML template element as described in
https://vuejs.org/api/built-in-special-elements#template , so it wasn't rendered.
Workloads -> Deployments -> General ->Lifecycle Hooks
For both PodStart and PodStop if "Create HTTP request" is selected, HttpGet configuration should be visible, editable and if saved, it should be respected. 
Same applies to editing existing configuration
Just workloads should be affected
=> Fixed httpget options not showing up

shell/components/nav/Header.vue, shell/pages/auth/logout.vue
Fixes #12314 
- adapt SAML logout logic to rely on info from public `authprovider` endpoint for SAML Single Logout feature
- Minor css fix on avatar drop menu `logout` item
- can be tested with `v2.10-dae07ed09601506420c133a69d6e6d27bb7a53ec-head` Rancher image
Follow repro steps in https://github.com/rancher/dashboard/issues/12314
Test also with an `admin` role user. Test the different logout scenarios as well (logout from all, logout only from Rancher and change the auth config options so that the avatar link for `logout` does different types of logout without the presence of the modal)
=> Support standard user handling SAML SLO feature

cypress/e2e/tests/pages/extensions/extensions.spec.ts, shell/pages/c/_cluster/uiplugins/index.vue
Fixes #12398  
- fix issue banner extensions prime users not being displayed due to setting value being defined as an empty string by backend 
- add e2e test
- Check issue description for repro steps
=> [backport 2.9] fix issue banner extensions prime users not being displayed

shell/edit/management.cattle.io.project.vue
Fixes #12287
- introduced via https://github.com/rancher/dashboard/pull/12233
- fix isn't required for changes to hosted providers as it's only added to the create part 
- on edit of a project, if the signed in user is not local, an immutable annotation was updated (norman like resource with annotation of cattle.io)
- fix is to only set annotation on create
When signed in with an auth provider...
- edit the default project 
- create a new project
- edit new project
as above but for local user
=> Only set immutable annotation on create of project

shell/edit/provisioning.cattle.io.cluster/__tests__/Advanced.test.ts, shell/edit/provisioning.cattle.io.cluster/tabs/Advanced.vue
Fixes #12368 
`agentConfig` is not an empty object and attempting to update the object to true will fail, the input should update the `protect-kernel-defaults` property within the object.
- Added an extra condition to check for the `agentConfig['protect-kernel-defaults']` property
- Fixed `serverArg` property in `showEmptyKubeletArg` method to `serverArgs`.
=> Fix agentConfig checkbox input

shell/components/formatter/SecretData.vue
https://github.com/rancher/dashboard/issues/12255
**First note:**
This issue doesn't require the user to filter anything on the list page. The page just needs to contain a tls cert secret with a special format.
**Second note:**
This one has been difficult to reproduce due to my lack of knowledge in certs.  It looks like you need to have a cert with a specially formed SANs to get this issue to reproduce. I artificially reproduced this issue using this key, cert (unused) and made a diff to the model.
MyKey.key
```
-----BEGIN PRIVATE KEY-----
MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQCi+jqGS26sAKyg
C3i/8Jce5nxvVWLvS+fQQm4lu8g//ddsrU2Ga+FGhP79/zsBhU7tJG2tswm5vxzz
mCeJKYJBS8Oqu5IN0MdBZfcmPjvA+q0s+k03FjBLlFl+aeg+1xK4rhg02WgF2QQe …
```
=> Resolving an issue where we don't check to see if unrepeatedSans exists before using it

shell/edit/cis.cattle.io.clusterscan.vue, shell/pages/c/_cluster/apps/charts/install.vue
Fixes #12412
Fixes #12416
UnitInput controls with value set as v-model.number didn't get updated correctly during migration. If control doesn't have corresponding @input event, value was not getting updated. 
N/A
N/A
See linked issues for reproduction steps
None
=> Fixed UnitInput value not updating

scripts/check-i18n-links
Fixes #12422
Updates the documentation link checker to correctly parse the version number following other recent changes.
The version number was moved to `version.js`, so the script needs to read that too.
Also:
1. Added more resilience, so it will fail if it does not parse this correctly.
2. Fixed the error reporting when a link access fails
3. Logged detected links that the check skips (those not beginning with the docsBase property)
=> Fix documentation link check script

shell/edit/cis.cattle.io.clusterscan.vue
Fixes #12411
Note: https://github.com/rancher/dashboard/issues/12412 is required to fix the specific issue on that field.
We were previously clearing out the `spec` of the resource on edit. Don't know why.
This PR updates that so that we preserve the data in the resource on edit
Test as per the issue above.
Due to time constraints, this will need manual testing.
=> Ensure we don't lose values on edit of cluster scan resources

shell/components/nav/WorkspaceSwitcher.vue
Fixes #12388 
- remove `append-to-body="false"` from the Fleet workspace switcher to fix render issue of dropdown in Firefox
The problem is that Firefox doesn't calculate the width well with this `inline` class presenthttps://github.com/rancher/dashboard/blob/master/shell/components/form/Select.vue#L244 when appending `v-select` dropdown to the element.
We could have removed the `inline` class, but I think it's less prone to risks if we just let the dropdown to be appended to the `body` element rather than the dropdown as it forces `v-select` to calculate both width and position and apply it to the element without any relative measurements like `%`.
Original work done in https://github.com/rancher/dashboard/pull/2170
https://vue-select.org/api/props.html#appendtobody
- check workspace …
=> Fix issue with Workspace dropdown in Firefox

shell/edit/fleet.cattle.io.gitrepo.vue
Fixes #12391
Missed from
- https://github.com/rancher/dashboard/pull/11956#issuecomment-2422936450
- https://github.com/rancher/dashboard/issues/12298
- https://github.com/rancher/dashboard/pull/12299
i could reproduce this in release-2.9 head
git repo create / edit with failures
given recent git repo url change though to reproduce an easy error try creating a git repo with a name of an existing one
=> Fix errors not showing in fleet git repo form

shell/assets/translations/en-us.yaml, shell/edit/fleet.cattle.io.gitrepo.vue, shell/utils/validators/formRules/__tests__/index.test.ts, shell/utils/validators/formRules/index.ts
Fixes #12204 
Removing git repo format validation because we want to test the formatting more for now.
Added https://github.com/rancher/dashboard/issues/12432 to add better format validation to this page.
Removed format validation for the git repository input field. 
Field is still marked as required.
None
Fleet -> Git repo -> Create
Repository URL field should be marked as required, but we do not test the format of the url
None
=> Removed repo format validation

cypress/e2e/tests/pages/fleet/gitrepo.spec.ts, shell/edit/monitoring.coreos.com.prometheusrule/AlertingRule.vue, shell/edit/monitoring.coreos.com.prometheusrule/index.vue
Fixes #12436 
Fixed 'Override Group Interval' and 'Wait to fire for' fields when creating Prometheus rule.
During vue migration, .includes usage inside set became corrupted.
Make sure that 'Override Group Interval' and 'Wait to fire for' fields can be set correctly:
Install monitoring chart
Once chart installed successfully goto Monitoring->Advanced->PromethuesRules->Create Rule.
Create prometheus rules and add alerting rules with "wait to fire for" and "Override Group Interval" values.
None
=> Fixed UnitInput value not being set correctly in monitoring

shell/edit/provisioning.cattle.io.cluster/tabs/MachinePool.vue
Fixes #12428 
- fix unit input for `unhealthy node timeout` on machine pools in cluster provisioning
Been checking all the usages of `v-model.number` and:
- `shell/components/form/Ports.vue` -> Component not used in dashboard code (hasn't been touched in quite a while codewise)
- `shell/components/form/ServicePorts.vue` -> used in edit view of `services` and works fine
- `shell/edit/provisioning.cattle.io.cluster/tabs/MachinePool.vue` -> Used in cluster provisioning machine pools and was broken (object of this fix)
- test unit input for `unhealthy node timeout` on machine pools in cluster provisioning
https://github.com/user-attachments/assets/d235b588-6b26-4ffc-998f-c83f10b3b749
=> Test v-model.number usage in 2.10 / vue3 world - fix broken unitInput

cypress/e2e/po/detail/management.cattle.io.roletemplate.po.ts, cypress/e2e/tests/pages/users-and-auth/roles.spec.ts, shell/components/PromptRemove.vue, shell/components/ResourceDetail/Masthead.vue
backport of https://github.com/rancher/dashboard/pull/12270
fixes: https://github.com/rancher/dashboard/issues/12218
=> [backport-2.9]: Fix a problem with deleting role templates from their detail pages

shell/plugins/steve/mutations.js, shell/plugins/steve/subscribe.js, shell/utils/__tests__/object.test.ts, shell/utils/object.js
Fixes #12406 
Fixes #11541 
In Vue 3, the reactivity system uses proxies to make objects reactive. These proxies cannot be serialized or cloned using the structured clone algorithm, which is why we're encountering the `DataCloneError` when attempting to send data that includes these proxies via `postMessage`.
Unfortunately, it wasn't as simple as just converting the `data` object to a raw object and sending that to `postMessage` as there are nested reactive objects that wouldn't be converted in this way. So I implemented a method that would recursively convert all of the proxy objects into raw using Vue's provided `toRaw` method.
- Added `deepToRaw` method to the `object` utils
- Before passing the data to loadSchemas, we convert all of the proxied objects to raw
- Replaced usage of …
=> Add deepToRaw method for recursively converting proxy objects to raw

shell/components/ResourceTable.vue, shell/components/SortableTable/index.vue, shell/components/SortableTable/sorting.js
Fixes #12437
- Switching between fleet workspaces which contain the same number of resources will fail to update the rows
- sometimes this would happen anyway, for instance the generation of the resource was updated
- Caused by change in reactivity with base [fn](https://github.com/rancher/dashboard/blob/master/shell/components/SortableTable/sorting.js#L35) in sortable table pagination pipeline
- this was fired with stale rows (rows from old workspace) BUT would be cached against the new state (new workspace)
- whenever the pipeline was triggered again (sans other changes) it would then return the cached stale rows
- fixed by providing a specific hash to use instead of one generated on demand (which fetched new state)
- i've limited this to the workspace world to reduce impact / bugs
- …
=> Ensure lists update when switching between workspaces with the same number of rows

shell/components/form/LabeledSelect.vue
Fixes #12342 
Fix the issue with `LabeledSelect` when `taggable` is `true` by allowing the binding of the attribute to the element v-select that was being filtered out.
I traced back the previous change for filtering `taggable` to [the original issue](https://github.com/rancher/dashboard/issues/11954) and checked if this change broke that fix, and it's not breaking it. To discard any regressions, a quick test of different instances of `LabeledSelect` would be great, even if they don't use `:taggable="true"`
https://github.com/user-attachments/assets/321f31c9-cf21-4b59-b89e-d4d828c67339
=> Fix tagging not working when creating a logging flow

shell/edit/monitoring.coreos.com.prometheusrule/AlertingRule.vue
Fixes #12453 
There was an issue with vue's reactivity detecting the deep nested changes on `this.value.annotation`, tried updating the whole annotations object to fix the issue.
https://github.com/user-attachments/assets/f2103eba-292f-415e-83e2-6108097cd42b
=> Fix annotation changes not being reactive

docusaurus/docs/internal/testing/e2e-test.md
Update e2e docs / guide given https://github.com/rancher/dashboard/pull/12366
=> Update e2e docs

pkg/eks/components/Logging.vue
Fixes #12482 
This PR fixes a vue3-related migration in the EKS provisioning form. I searched for other lingering `@input` listeners in the hosted provider packages, but looks like it was just this logging component.
=> fix eks logging checkbox event listeners

shell/edit/provisioning.cattle.io.cluster/tabs/registries/RegistryMirrors.vue
This resolves a simple data binding issue in `RegistryMirrors.vue`; data binding for custom components should be using `@update:value` instead of `@input`.
Fixes #12524 
- Use `@update:value` instead of `@input` for `ArrayListGrouped` component
- `ArrayListGrouped` emits an `update:value` event instead of `input`, this is the root cause behind the issue
- RKE2 Cluster Configuration: Registries
- NA
=> Bind updates with `@update:value` in `RegistryMirrors.vue`

pkg/aks/components/CruAks.vue
Fixes #12525 
This uses `semver.coerce()` to get a valid semantic version for the original Kubernetes version in `CruAks.vue`. The form could fail to render if the Kubernetes version is not a valid semver and `semver.coerce()` will correctly evaluate to a semantic version.
In the production example, 1.29 is used for the Kubernetes version:
```
az aks create --resource-group th-rg --no-ssh-key --kubernetes-version 1.29 --name th-az-imported-293 --node-count 1 --location eastus
```
1.29 is a valid Kubernetes version and will default to the latest release[^1] (1.29.10 at the time of writing).
1.29 is stored in `aksConfig.kubernetesVersion`; this is not a valid `semver`, so an unhandled exception is thrown and the page fails to render correctly. 
It's entirely possible that …
=> Use `semver.coerce()` to get valid kubernetes version

cypress/e2e/tests/pages/explorer/dashboard/cluster-dashboard.spec.ts, cypress/e2e/tests/pages/fleet/dashboard.spec.ts, cypress/e2e/tests/pages/manager/cilium-cni.spec.ts, cypress/e2e/tests/pages/manager/edit-fake-cluster.spec.ts
=> Enable title and some cluster management e2e tests

shell/store/features.js, shell/utils/v-sphere.ts
Fixes #12545
- cherry-pick backport of https://github.com/rancher/dashboard/pull/12547
- note no changes in rke2.vue required (newer versions do not look at vpshere provider string
=> [backport v2.8.10] CSI/CPI pre-bootstrap secrets are being created when the feature flag is disabled

cypress/e2e/tests/pages/generic/about.spec.ts
- head points to 2.10.0 cli binaries, which aren't available
- v2.10-head points at 2.9.0 binaries which are available
- this causes are e2e tests that check links (amongst other things) to 404
- so now we check for 404 and need to change back to 200 when the binaries are there
- https://github.com/rancher/dashboard/issues/12576
=> Fix e2e failing due to unavailable cli binaries

pkg/aks/components/AksNodePool.vue, shell/components/SideNav.vue, shell/components/TableDataUserIcon.vue, shell/components/nav/TopLevelMenu.vue, shell/directives/clean-tooltip.js
This replaces `v-tooltip` with `v-clean-tooltip`. It appears that some new features written since the introduction of `v-clean-tooltip` haven't been using the new directive.
This also fixes the `v-clean-tooltip` directive in Vue3. The API for directives has changed in Vue3:
- `bind` is now `beforeMount`
- `update` has been removed and `updated` is recommended 
Fixes #12564
- replace `v-tooltip` with `v-clean-tooltip`
- update `v-clean-tooltip` to use Vue3 compatible API
=> Replace `v-tooltip` with `v-clean-tooltip`

cypress/e2e/tests/pages/generic/about.spec.ts, shell/assets/translations/en-us.yaml, shell/components/formatter/ClusterProvider.vue, shell/models/__tests__/management.cattle.io.cluster.test.ts, shell/models/__tests__/provisioning.cattle.io.cluster.test.ts, shell/models/management.cattle.io.cluster.js, shell/models/provisioning.cattle.io.cluster.js
Fixes #12506
Fixes #12339 
Fixes #12576 
This PR reverts https://github.com/rancher/dashboard/pull/12177 as well as much of https://github.com/rancher/dashboard/pull/9868
I reverted most of #9868 and moved a critical component of that fix into a display-only property, so it would not interfere with iframed edit pages (causing #12506 and #12339). I also found a simpler approach to determining whether or not a cluster is imported, which doesn't depend on ember query params: as noted in pre-existing inline documentation, constructing those ember params involves "much indirect mapping" -- in other words, it's difficult to follow. 
Verify the provider/distro column of the cluster management list view as well as the edit config view for each of the following: 
local clusters:
downstream …
=> Fix editing local rke1 and eks clusters

shell/components/LandingPagePreference.vue, shell/pages/auth/login.vue, shell/pages/prefs.vue, shell/store/i18n.js
Contributes to https://github.com/rancher/dashboard/issues/12347
=> Harvester shell integration - remove LocaleSelector when is Harvester standalone UI

shell/assets/translations/en-us.yaml
Contributes to https://github.com/rancher/dashboard/issues/12347
=> Harvester shell integration - add translations

shell/edit/provisioning.cattle.io.cluster/index.vue
Fixes #12541 
This PR modifies a change that came in [here](https://github.com/mantis-toboggan-md/dashboard/commit/4cca5faf81dd658464b086c67894642f909ee6fc#diff-7655093720dda329bd1d1b72936a782cd7178edadbf55a7c1b8b58fb394f77cfR190) to support the AKS/EKS/GKE ui extensions, so other hosted providers are still able to load custom ember ui.
Ensure that hosted 
create,edit, import existing aks/eks/gke clusters -- make sure the vue is still loading for these cluster types
https://github.com/user-attachments/assets/8849e5f7-2abf-418c-8234-d374766589f7
https://github.com/user-attachments/assets/b203edd1-ff35-4d34-99bd-6a8c4239e274
=> fix ember routing for hosted clusters that are not EKS AKS nor GKE

shell/pages/c/_cluster/fleet/index.vue
Fixes #10632 
Removed unnecessary class `.fleet-dashboard` as it wasn't referenced anywhere else, and its `min-height: 100vh` styling was causing the issue. Note that you would only see the scroll bar if you had the os setting enabled to always show the scroll bars:
Try different browsers and turn on the os setting mentioned above.
I've already tried different pages on the fleet section and couldn't find any regression there, but would be good if a second person test it too.
=> Fix fleet dashboard page's scroll bar

cypress/e2e/tests/pages/global-settings/settings-p2.spec.ts
Fixes #
- In Rancher `v2.11-3544e2a5117833c9b5dc66628af034322ead317c-head` version, the telemetry-opt default value is `out` -> UI `Opt-out of Telemetry`
The `Use the default value` button should correctly be enabled.
=> Fix telemetry-opt e2e test

.github/workflows/test.yaml
We are replacing the download server because of frequent unavailability.
=> fix e2e chrome installation

shell/assets/translations/en-us.yaml, shell/components/formatter/ClusterProvider.vue, shell/models/__tests__/management.cattle.io.cluster.test.ts, shell/models/__tests__/provisioning.cattle.io.cluster.test.ts, shell/models/management.cattle.io.cluster.js, shell/models/provisioning.cattle.io.cluster.js
Backport of #12583
Fixes #12506
Fixes #12339 
Fixes #12576 
This PR reverts https://github.com/rancher/dashboard/pull/12177 as well as much of https://github.com/rancher/dashboard/pull/9868
I reverted most of #9868 and moved a critical component of that fix into a display-only property, so it would not interfere with iframed edit pages (causing #12506 and #12339). I also found a simpler approach to determining whether or not a cluster is imported, which doesn't depend on ember query params: as noted in pre-existing inline documentation, constructing those ember params involves "much indirect mapping" -- in other words, it's difficult to follow. 
Verify the provider/distro column of the cluster management list view as well as the edit config view for each of the following: 
local clusters: …
=> [Backport] Fix editing local rke1 and eks clusters

shell/vue.config.js
Fixes: #12511
**TL;DR**: Drop the web-worker polyfill. It's for ancient browsers and confuses tooling that works with performance captures.
**QA NOTE**: No user visible change expected, this is only to aid developers interpreting performance captures, eg. following https://github.com/rancherlabs/rancher-process/blob/main/docs/documentation/howtos/browser_performance_capture.md
The BLOB code from web-worker is minified, and contains source maps that are then passed over by webpack - that creates a situation of minified code inside BLOB inside minified code which confuses some tools, eg.
https://github.com/jantimon/chrome-profile-sourcemap-resolver/pull/4
That could be fixed, but the only reason to do so would be supporting very old (pre-2013) browsers, so we are better off removing the …
=> Avoid embedding web-worker polyfill

shell/assets/translations/en-us.yaml, shell/edit/provisioning.cattle.io.cluster/__tests__/DirectoryConfig.test.ts, shell/edit/provisioning.cattle.io.cluster/tabs/DirectoryConfig.vue
Fixes #12455 
- disable Data Directories inputs in edit mode
- update unit tests
- create a cluster with some Data Directories config (RKE2)
- edit that cluster and check that inputs are disabled and radio options are hidden
=> Data Directories should not be editable after creation

shell/assets/translations/en-us.yaml, shell/edit/provisioning.cattle.io.cluster/__tests__/DirectoryConfig.test.ts, shell/edit/provisioning.cattle.io.cluster/tabs/Advanced.vue, shell/edit/provisioning.cattle.io.cluster/tabs/DirectoryConfig.vue
Fixes #12617 
- Updated UI for Data Directories to match v2.10 (also takes into account k8s version type when creating the base k8s distro folder from default)
- disable Data Directories inputs in edit mode
- update unit tests
- create a cluster with some Data Directories config (RKE2)
- edit that cluster and check that inputs are disabled and radio options are hidden
**UI before**
**UI after**
=> [backport v2.9.5] RKE2 cluster provision: Data Directories should not be editable after creation

pkg/aks/util/__tests__/validators.test.ts, pkg/eks/util/__tests__/validators.test.ts, pkg/eks/util/validators.ts, shell/edit/constraints.gatekeeper.sh.constraint/index.vue
Fixes #12442
I'm not sure why these instances of `$set` weren't caught in the vue3 migration. I searched the codebase and only additional instance I found was in gatekeeper constraints
In addition to what is described in #12442, check creating gatekeeper constraints with parameters defined
=> remove $set usage in eks provisioning and gatekeeper constraints

shell/components/nav/TopLevelMenu.vue
Fixes #11809 
Changed width setting so that it doesn't need scroller on smaller screens. 
Tested on Chrome, Firefox and Safari
N/A
N/A
Burger menu:
- Check cluster list with burger menu with 1 cluster both open and collapsed. Try different window sizes.
- Add more clusters (ie import custom clusters) until it requires virtual scroll in the side menu. Repeat step 1.
No horizontal scroll should be visible, clusters should be able to get pinned, layout should seem reasonable.
N/A
https://github.com/user-attachments/assets/e69cff4c-0597-4750-96dc-2e5884c8fd77
https://github.com/user-attachments/assets/fc64477b-a471-408a-bcc2-1efcc2a42356
=> Fixed cluster list in burger menu having unnecessary horizontal scroll

shell/assets/translations/en-us.yaml, shell/edit/provisioning.cattle.io.cluster/__tests__/DirectoryConfig.test.ts, shell/edit/provisioning.cattle.io.cluster/tabs/Advanced.vue, shell/edit/provisioning.cattle.io.cluster/tabs/DirectoryConfig.vue
This reverts commit 6a92a261c7839c56f2542de6e19ee3f6ab56cdbb.
Still working on the v2.9.4 release and this work is planned for v2.9.5.
- Confirm that the revert is accurate and that the feature behaves as it did before this change was introduced
- See PR #12619 for details
=> [2.9.4] Revert "backport-pr-12611 (#12619)"

cypress/e2e/tests/pages/explorer/apps/charts.spec.ts
This disables the generic icon check for the Logging chart. It's currently generic in `2.10-head` and will need to fixed at a later date:
- Disable generic icon check for the Logging chart
- The icon is currently generic in `2.10-head`
- `Charts have expected icons` e2e test passes
=> Disable check for generic icon for Logging chart

shell/assets/translations/en-us.yaml, shell/edit/provisioning.cattle.io.cluster/__tests__/DirectoryConfig.test.ts, shell/edit/provisioning.cattle.io.cluster/tabs/DirectoryConfig.vue
This reverts commit b4e5aba61c61e91d79eb5d7ee12706d58fc39d75.
Still working on the v2.10.0 release and this work is planned for v2.10.1.
- Confirm that the revert is accurate and that the feature behaves as it did before this change was introduced
- See PR #12620 for details
=> [2.10.0] Revert "backport-pr-12611 (#12620)"

shell/models/fleet.cattle.io.gitrepo.js
Follow up of #12521
Fixes the GitRepos list being empty in the Cluster details view.
The cluster lists used to get the `Cluster` object data is based on `targetClusters` spec, which may vary depending on the context. Since `resourcesStatuses` now iterates on `BundleDeployments` resources directly, it should skip those deployed in a cluster that is not present in the `targetClusters`.
=> Fix empty GitRepos list on Cluster details

cypress/e2e/tests/pages/fleet/advanced/bundles.spec.ts, shell/components/ResourceDetail/index.vue, shell/components/fleet/FleetRepos.vue, shell/config/labels-annotations.js, shell/detail/fleet.cattle.io.bundle.vue, shell/detail/fleet.cattle.io.gitrepo.vue, shell/models/fleet.cattle.io.bundle.js, shell/models/fleet.cattle.io.gitrepo.js, shell/pages/c/_cluster/fleet/index.vue, shell/types/resources/fleet.d.ts, shell/utils/auth.js, shell/utils/fleet.ts
Fixes https://github.com/rancher/dashboard/issues/12517
GitRepo details include a tab for `Resources`, which iterates over the list of `status.resources` in the `GitRepo` object. However, this is inaccurate, since the source of truth for resources are `BundleDeployments`, as they may vary depending on the target cluster customization.
- The code used `find` to pick just the first bundle deployment matching the cluster label, which is totally wrong. Now we iterate directly on bundle deployments instead, then pick the target cluster as necessary.
- The biggest part of the `Bundles` payload is the `spec.resources`, as it basically contains all the raw chart contents. I've modified the getter to make steve omit that field.
- In order to allow this, I also had to refactor the Bundle view to …
=> [2.9] Use BundleDeployment status to calculate GitRepo resources

.github/workflows/build-extension-catalog.yml, .github/workflows/build-extension-charts.yml, .github/workflows/release-shell-pkg.yaml, shell/scripts/extension/parse-tag-name, shell/scripts/publish-shell.sh
Fixes #12159 
Fixes #12032 
Based on the work done in https://github.com/aalves08/dashboard/pull/4
- Adjust extension workflows in branch `release 2.8` for nightly run tests for extensions
=> Adjust extension workflows in branch 'release 2.8' for nightly run tests for extensions

.eslintrc.default.js, eslint-local-rules/v-clean-tooltip.js, package.json, pkg/rancher-components/package.json
Wanted to automate the ability to detect an issue with using v-tooltip over v-clean-tooltip. I wrote a custom linter rule so we can catch this in CI.
I noticed that we currently exclude linting rancher-components from our root directory. I'd think we'd just want to include everything but I'm not sure.
None, it's in a way an additional test.
None
**Example:**
**You can disable the rule in the template using:**
=> Adding a custom lint rule to ensure we use v-clean-tooltip instead of v-tooltip directives.

shell/components/SideNav.vue, shell/pages/auth/login.vue
Previous [PR change](https://github.com/rancher/dashboard/pull/12352) miss to hide locale selector in SideNav for harvester, the locale selector still appears in login and SideNav within harvester-ui-extension standalone mode.
We need to have @rancher/shell : `3.0.1-rc2` release after this PR merge.
Fixes #
https://github.com/rancher/dashboard/issues/12347
https://github.com/harvester/harvester/issues/6928
After fix (I test this PR change under harvester-ui-extension/node_modules/@rancher/shell)
Login page
SideNav
=> Hide local selector for harvester in login and SideNav

cypress/e2e/tests/pages/users-and-auth/users.spec.ts, shell/assets/translations/en-us.yaml
Fixes #12689 
- fix e2e test following removal of restricted admin role
=> fix e2e test following removal of restricted admin role

cypress/e2e/po/lists/role-list.po.ts, cypress/e2e/tests/pages/users-and-auth/roles.spec.ts, shell/models/management.cattle.io.globalrole.js
Fixes #12146
- fix issue with clone of global role with `inheritedClusterRoles`
- add e2e test
- Go to `local` cluster -> header -> and import the YAML on the issue body https://github.com/rancher/dashboard/issues/12146
- Go to `Users & Authentication` -> `Role Templates` -> `Global Role` and find the imported role on the list. Afterwards click on the row action menu `clone` and fill out the `name` field and press save
- check the network request or the YAML for the newly created role from the clone and make sure `inheritedClusterRoles` exists 
https://github.com/user-attachments/assets/74457e71-4444-47a3-8b4e-11cac3645c51
=> fix issue with clone of global role with inheritedClusterRoles

cypress/e2e/po/lists/role-list.po.ts, cypress/e2e/tests/pages/users-and-auth/roles.spec.ts, shell/models/management.cattle.io.globalrole.js
**backport PR [12707](https://github.com/rancher/dashboard/pull/12707)**
Fixes #12457 
- fix issue with clone of global role with `inheritedClusterRoles`
- add e2e test
- Go to `local` cluster -> header -> and import the YAML on the issue body https://github.com/rancher/dashboard/issues/12146
- Go to `Users & Authentication` -> `Role Templates` -> `Global Role` and find the imported role on the list. Afterwards click on the row action menu `clone` and fill out the `name` field and press save
- check the network request or the YAML for the newly created role from the clone and make sure `inheritedClusterRoles` exists 
https://github.com/user-attachments/assets/74457e71-4444-47a3-8b4e-11cac3645c51
=> fix issue with clone of global role with inheritedClusterRoles - 2.10 backport

shell/vue.config.js
Fixes #
`RegExp(`/pkg.${ excluded }/`)` is excluding everything starting with `/pkg.harvester`, therefore also `/pkg.harvester-manager`
=> Include `harvester-manager` in hot-reload watchOptions

shell/vue.config.js
Fxes: #12514
Port of https://github.com/rancher/dashboard/pull/12400
=>  [2.10 backport] Avoid embedding web-worker polyfill

shell/pages/c/_cluster/explorer/__tests__/index.test.ts, shell/pages/c/_cluster/explorer/index.vue
Fixes #12685
**NOTE:** started with the 2.10 issue repro. Will do a forward port to 2.11
- fix issue with display of fleet and cattle agent status on cluster dashboard view with very limited user permissions (as per https://github.com/rancher/dashboard/issues/12680#issuecomment-2506489417)
- The `View Monitoring` custom role allows for the user to have access to the namespaces that were the condition to display the boxes, but the user didn't have permissions to view `Deployments` and `Statefulsets` which are the resources that hold the status information
Repro steps as per https://github.com/rancher/dashboard/issues/12680#issuecomment-2506489417
=> fix issue with display of fleet and cattle agent status on cluster dashboard view with very limited user permissions

shell/components/ResourceDetail/Masthead.vue, shell/components/ResourceDetail/index.vue, shell/list/management.cattle.io.podsecurityadmissionconfigurationtemplate.vue, shell/models/nodedriver.js
Fixes #12478
Added some error catching to
- node drivers
- pod security admissions
- edit YAML for fleet git repos
Create a new standard user with this custom roles:
{ resource: "fleetworkspaces", verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]},
{ resource: "gitrepos", verbs: ["list"]},
{ resource: "bundles", verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]},
Log in as this user. 
Going to the following pages shouldn't throw any errors in the console:
Cluster management -> Advanced -> Pod Security Admissions
Cluster management -> Drivers -> Node Drivers
Continuous delivery -> Git repos -> Edit YAML for existing git repo should open with an error banner
None
=> fixed some console errors for standard user

cypress/e2e/po/components/workloads/pod-storage.po.ts, cypress/e2e/tests/pages/explorer2/workloads/deployments.spec.ts, shell/assets/translations/en-us.yaml, shell/edit/workload/index.vue, shell/edit/workload/storage/csi/index.vue, shell/edit/workload/storage/index.vue
This resolves an issue with selecting options for Pod Storage: CSI. It appears that there are two different ways that an option can be represented, by either being a string or an object with a label key. It also appears that periods are exclusively used for i18n selectors, so the key for Longhorn has been updated to use `-` instead. 
Fixes #11899 
- Create methods for getting CSI option labels
- Replace periods with `-` in keys like `driver.longhorn.io` so that the i18n implementation will properly match a translation.
- Add e2e test for selecting Longhorn CSI Pod storage
- Options for CSI can be either a string or an object; objects contain a label property
See associated issue for more instructions.
- Adding CSI storage driver in pod storage
- Editing CSI storage driver in pod storage
- …
=> Allow Longhorn CSI storage driver to be selected

cypress/e2e/tests/pages/global-settings/settings-p2.spec.ts, shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml, shell/config/settings.ts, shell/pages/auth/setup.vue
Fixes: #12639
This PR removes code related to telemetry. This removal is planned for 2.11. Related PRs:
- https://github.com/rancher/rancher/pull/48031
- https://github.com/rancher/rancher-docs/pull/1567
The JIRA issue for this is SURE-9295.
I am not super familiar with this repository so if there is anything that needs changing please let me know. But I think this should be fairly straightforward.
=> Remove mentions of rancher telemetry

shell/components/nav/TopLevelMenu.vue
Fixes #12758 
Changed css to exclude pins instead of specifying which element to apply to include more cases.
1. Install an extension from https://nwmac.github.io/rancher-dev-portal/
2. All items on app bar (top level menu) should be positioned the same
3. Create a new imported cluster without actually importing it.
4. Pin the new cluster and local cluster. Pin positioning should be the same.
Top level menu application bar
=> [FIX] Fixed app icon aligntment for extensions with image icon

package.json, pkg/rancher-components/package.json, shell/package.json, shell/yarn.lock, yarn.lock
This removes the unused `vue-template-compiler`; it is no longer required in Vue3 projects
Fixes #12751
=> Remove `vue-template-complier` dependency

shell/components/ResourceYaml.vue
This removes the `onChanges()` method from `ResourceYaml.vue` because the intent of the code is not clear and appears to provide no benefit in testing. This is a source of frustration for some users, making it impossible to add comments to YAML. 
It appears that this function exists to automatically adjust the indentation of comment lines; it has failed to accomplish this task during testing. If users wish to format yaml, we should support this with an explicit action in the YAML editor, not something that is performed on every keypress.
Fixes #11226 
- remove the `onChanges()` method from `ResourceYaml.vue`
- this method doesn't appear to function
- it is the root cause of clobbering user input
YAML editors throughout Dashboard: we want to make sure that we can edit, delete, and create …
=> Remove `onChanges()` method in `ResourceYaml.vue`

.github/workflows/test.yaml, cypress/e2e/tests/pages/generic/home.spec.ts
Fixes #https://github.com/rancher/dashboard/issues/11836
- Unpinned Chrome version
- Moved Can navigate to release notes page for latest Rancher version to run last; The test clicks on a link that opens a new tab which is causing issues with subsequent tests (once we are able to upgrade our Cypress version, test order will not matter).
=> [backport 2.9.5] unpin chrome version

shell/scripts/test-plugins-build.sh
Fixes #12598
- add check/test for CAPI extension
- add check/test for Observability extension
=> add missing checks for extensions that have now been migrated to vue3

pkg/harvester-manager/l10n/en-us.yaml, pkg/harvester-manager/list/harvesterhci.io.management.cluster.vue, shell/utils/uiplugins.ts
Contributes to https://github.com/rancher/dashboard/issues/12688
We noticed that the latest version Harvester version is installed ignoring the compatibility, in case of there are no compatible versions.
We want to show a warning message in case the Harvester installation fails due to missing compatible Harvester versions with Rancher.
Before
After
=> [backport 2.10] Virtualization Management, show warning message if there are no compatible Harvester versions

.github/workflows/test.yaml
Disable vai tests until backend issues resolved
See https://github.com/rancher/dashboard/issues/12856 to enable again
=> Disable vai tests given backend failures

package.json, shell/package.json, shell/yarn.lock, yarn.lock
This bumps `@types/node` to 20.17.6.
`@types/node` was recently targeting node 16, which Dashboard no longer supports as of the Vue 3 migration. 
- bump `@types/node` to 20.17.6
- Dashboard no longer supports node 16 after migrating to Vue 3
=> Bump `@types/node` to 20.17.6

pkg/aks/components/CruAks.vue
Fixes #12861 
Backport of https://github.com/rancher/dashboard/pull/12865
=> [2.10.1]Fix AKS nodegroup upgrade validation

pkg/aks/components/CruAks.vue
Fixes #12862
This is a follow on from https://github.com/rancher/dashboard/pull/12532 We started using `semver.coerce` on the AKS cluster version because it may not specify a patch version (eg if provisioned outside rancher, `"1.30"` would be a valid cluster k8s version). Consequently the `originalVersion` prop went from being a string to a semver object. This appears to be _mostly_ fine, as we are mostly using semver to compare versions and semver doesn't care; however, [in nodegroups](https://github.com/rancher/dashboard/blob/master/pkg/aks/components/AksNodePool.vue#L126) we are merely checking if versions are equal and use a simple equality comparison.
I think the simplest fix is to make sure that `originalVersion` is a string again. I verified that this change wont re-introduce …
=> Fix AKS nodegroup upgrade validation

shell/dialog/DrainNode.vue
Fixes #12632 
DrainNode dialog didn't get updated correctly as part of Vue 3 migration
Nodes -> Drain dialog. 
Input elements should be editable. 
After saving, request should contain correct data that matches edited configuration
N/A
https://github.com/user-attachments/assets/cc0938b4-02fc-4968-8cfb-08d97745d550
=> [FIX] Fixed drain worker form being uneditable

shell/dialog/DrainNode.vue
Fixes #12673
DrainNode dialog didn't get updated correctly as part of Vue 3 migration
Downstream cluster -> Nodes -> Drain dialog
Input elements should be editable.
After saving, request should contain correct data that matches edited configuration
None
https://github.com/user-attachments/assets/d5407d52-9927-4422-9962-a04e666af48d
=> [2.10.1] Fixed drain worker form being uneditable

cypress/e2e/tests/pages/explorer/apps/repositories.spec.ts, pkg/aks/components/CruAks.vue
Fixes #12860 
Backport of https://github.com/rancher/dashboard/pull/12865
=> [2.9.5] Fix AKS nodegroup upgrade validation

pkg/harvester-manager/l10n/en-us.yaml, pkg/harvester-manager/list/harvesterhci.io.management.cluster.vue, shell/utils/uiplugins.ts
Contributes to https://github.com/rancher/dashboard/issues/12640
We noticed that the latest version Harvester version is installed ignoring the compatibility, in case of there are no compatible versions.
We want to show a warning message in case the Harvester installation fails due to missing compatible Harvester versions with Rancher.
Before
After
=> Virtualization Management, show warning message if there are no compatible Harvester versions

shell/assets/styles/base/_mixins.scss, shell/assets/styles/themes/_light.scss, shell/assets/translations/en-us.yaml, shell/components/nav/TopLevelMenu.vue
Fixes #12769
This PR adds keyboard navigation support to the top-left app bar hamburger menu.
Load the UI, press the Tab key - you will see focus indication on the menu icon.
You can now press SPACE or ENTER to expand/collapse the button.
This also adds the `aria-label` and `role` attributes to the button.
=> Fix top-level burger menu keyboard navigation

docusaurus/docs/extensions/changelog.md, package.json, pkg/aks/tsconfig.json, pkg/eks/tsconfig.json, pkg/gke/tsconfig.json, pkg/harvester-manager/tsconfig.json, pkg/kubectl-explain/tsconfig.json, pkg/rancher-components/package.json, shell/package.json, shell/tsconfig.json, shell/types/vue-shim.d.ts, shell/yarn.lock, yarn.lock
This enhances in-editor typescript support by
- ensuring that `shell/types/vue-shim.d.ts` is included in the typescript config
- removing vue2 type augments from `shell/types/vue-shim.d.ts`
- updating typescript to 5.6.3 
Fixes #12893
I tested this change in Zed, Webstorm, and VS Code - typescript support appears to be improved across the board with regards to properly detecting aliased imports and detecting Vue augments. 
VS Code allows for selecting the typescript version; developers can choose to use VS Code's version or the workspace version. Later versions of Typescript appear to better handle multiple tsconfigs, so updating typescript to 5.6.3 resolves the import issue nicely. This is also the default version that is currently used in VS Code as of writing.  
> NOTE: Make sure to …
=> Update typescript configs for better in-editor support

cypress/e2e/tests/pages/explorer/apps/repositories.spec.ts
Partially addresses https://github.com/rancher/dashboard/issues/12099
This PR corrects some retry logic in one of the e2e tests I'm seeing fail often.
You an see an example of this failure on our sorry cypress instance `.../instance/7a973f49-6fff-40d3-8054-9c5aa95a653b/test/r7
`
Each time this test runs it adds a repo name to `reposToDelete`. After each attempt, the afterEach hook tries to delete all repos in `reposToDelete`. If the test fails and retries, the afterEach hook will be retrying a repo deletion, get a 404 not found, and error out. 
The simplest fix here seems to be to ignore these errors in afterEach. We could also refactor the test so it only attempts to delete one repo each run.
=> Reduce flakiness in explorer/apps/repositories.spec.ts

cypress/e2e/po/edit/provisioning.cattle.io.cluster/create/cluster-create.po.ts, cypress/e2e/tests/pages/manager/cluster-manager.spec.ts, pkg/aks/provisioner.ts, pkg/eks/provisioner.ts, pkg/gke/provisioner.ts, shell/core/types-provisioning.ts, shell/edit/provisioning.cattle.io.cluster/index.vue
Fixes #12898 
This PR updates the AKS, EKS, and GKE ui extensions to hide their respective cluster creation cards when their kontainer driver is deactivated.
The PR changes the behavior of the `disabled` property of the ClusterProvisioner class so that it aligns with what happens when a node/kontainer driver with custom ui is deactivated. Rather than showing disabled cards the cards are gone entirely.
- disable aks, eks, gke kontainer drivers and verify that the associated card is gone from the cluster creation page after each is disabled
- re-enable those providers and verify that the cards are back
- verify that clicking the cards loads the newer vue ui
=> Hide AKS, EKS, and GKE cards when their kontainer drivers are deactivated

cypress/e2e/po/edit/provisioning.cattle.io.cluster/create/cluster-create.po.ts, cypress/e2e/tests/pages/manager/cluster-manager.spec.ts, pkg/aks/provisioner.ts, pkg/eks/provisioner.ts, pkg/gke/provisioner.ts, shell/core/types-provisioning.ts, shell/edit/provisioning.cattle.io.cluster/index.vue
Fixes #12901
backport of https://github.com/rancher/dashboard/pull/12903
=> [2.10.2]Hide AKS, EKS, and GKE cards when their kontainer drivers are deactivated

cypress/e2e/tests/pages/global-settings/settings-p2.spec.ts
Temporarily stop failing settings-p2 system registry setting e2e test
- See https://github.com/rancher/dashboard/issues/12936 for details
- This PR should be reverted once that issue is resolved  
- (requires calico tab in rke create page, which isn't there because 2.9 dockerhub head doesn't serve the related addon chart)
=> Temporarily stop failing settings-p2 system registry setting e2e test

cypress/e2e/po/edit/provisioning.cattle.io.cluster/create/cluster-create.po.ts, cypress/e2e/tests/pages/manager/cluster-manager.spec.ts, pkg/aks/provisioner.ts, pkg/eks/provisioner.ts, pkg/gke/provisioner.ts, shell/core/types-provisioning.ts, shell/edit/provisioning.cattle.io.cluster/index.vue
Fixes #12902
backport of https://github.com/rancher/dashboard/pull/12903
=> [2.9.6]Hide AKS, EKS, and GKE cards when their kontainer drivers are deactivated

shell/package.json, shell/scripts/extension/parse-tag-name
Fixes #[12718](https://github.com/rancher/dashboard/issues/12718)
- fix `parse-tag-name` to prevent workflow from running when a tag check is not met (`gh run cancel` is not enough)
- bump `shell` version
=> [2.9] fix parse-tag-name to prevent workflow from running when a tag check is not met

shell/package.json, shell/scripts/extension/parse-tag-name
Fixes #[12718](https://github.com/rancher/dashboard/issues/12718)
- fix `parse-tag-name` to prevent workflow from running when a tag check is not met (`gh run cancel` is not enough)
- bump `shell` version
=> [2.8] fix parse-tag-name to prevent workflow from running when a tag check is not met

pkg/harvester-manager/index.ts, shell/components/Tabbed/index.vue, shell/components/form/ResourceTabs/index.vue, shell/core/plugin.ts
Fixes #11122 
- Improve extension point for `tabs` to allow more use cases (also implement a "default" for locationConfig IF there's no `mode` specified)
- Add the following code to https://github.com/rancher/dashboard/blob/master/pkg/harvester-manager/index.ts:
```
plugin.addTab(
TabLocation.RESOURCE_DETAIL,
{ resource: ['persistentvolumeclaim', 'storage.k8s.io.storageclass', 'configmap'] },
{
name:       'some-name',
labelKey:   'generic.comingSoon',
label:      'some-label',
weight:     -5,
showHeader: true,
tooltip:    'this is a tooltip message',
component:  () => import('./../../shell/components/BackLink.vue')
}
);
```
- Check that tabs are added ONLY in `detail` view mode and that it cover the scenario specified on the issue
- Check other general uses of the TAB extension point and …
=> Fix Unable to add extension tab to Edit Storage Class page

shell/core/types.ts, shell/package.json
Fixes #12899 (low bar fix)
- add `ifHave` property to types + bump shell
=> [release-2.9] Add type for mechanism to allow to register custom pages conditionally (based on resource type)

shell/core/types.ts, shell/package.json
Fixes #12899 (low bar fix)
- add `ifHave` property to types + bump shell
=> [release-2.8] Add type for mechanism to allow to register custom pages conditionally (based on resource type)

creators/extension/app/files/.github/workflows/build-extension-catalog.yml, creators/extension/package.json
Fixes #12943 
- Updated `image-catalog` workflow to use the correct branch in `legacy-v2` world
- bump creators package
=> [release-2.8] Creating legacy-v2 app, image catalog workflow is using master branch wrongfully

creators/extension/app/files/.github/workflows/build-extension-catalog.yml, creators/extension/package.json
Fixes #12943 
- Updated `image-catalog` workflow to use the correct branch in `legacy-v2` world
- bump creators package
=> [release-2.9] Creating legacy-v2 app, image catalog workflow is using master branch wrongfully

scripts/aws/update-data, shell/assets/data/aws-regions.json
Fixes #12977 
This PR migrates the AWS script to use `axios` in place of the `request` library.
Note, there was one new region, so this PR updates the metadata to include that.
=> Migrate AWS script to axios

shell/core/types.ts
Fixes #12945
- Adds missing types used in extensions. Cross-checked with extension docs to see what was missing in product/pages configuration
=> [release-2.9] add missing types for extensions

shell/core/types.ts
Fixes #12945
- Adds missing types used in extensions. Cross-checked with extension docs to see what was missing in product/pages configuration
=> [release-2.8] add missing types for extensions

shell/core/types.ts
Fixes #12945
- Adds missing types used in extensions. Cross-checked with extension docs to see what was missing in product/pages configuration
- clone repo [https://github.com/masap/supportability-review-app-210](https://github.com/masap/supportability-review-app-210)
- yarn link this PR's `shell` to that repo
- confirm that there are no more TS errors from the extension registration functions
=> add missing types for extensions

shell/components/nav/TopLevelMenu.helper.ts, shell/components/nav/TopLevelMenu.vue, shell/store/index.js, shell/types/store/vuex.d.ts
Contributes to #10283, related to https://github.com/rancher/dashboard/pull/11663
- Reduce the flicker of cluster icons when the top level menu component is recreated given a change to the page's layout
- Add finer changes and comments to reduce churn from user / system changes to resources
- SSP enabled / disabled
- Initial load of dashboard - icons should show promptly
- When changing page's that have different layouts (home --> specific cluster --> home) the cluster icons should not flicker
=> Two side nav improvements

shell/components/form/NodeScheduling.vue, shell/components/form/__tests__/NodeScheduling.test.ts
=> Fix Node Scheduling / Node Name option in Workloads page

shell/components/form/NodeScheduling.vue, shell/components/form/__tests__/NodeScheduling.test.ts
=> [2.10.2] Fix Node Scheduling / Node Name option in Workloads page

shell/chart/monitoring/StorageClassSelector.vue
Fixes #12972 
As part of Vue 3 migration, we needed to remove @input from compponents that use LabeledSelect
Occurred changes and/or fixed issues
Fixed event listener in StorageClassSelector.
Technical notes summary
Areas or cases that should be tested
Create a new StorageClass
Apps -> Charts -> Monitoring -> Install/Update -> Prometheus -> Persistent Storage for Prometheus -> Storage Class name -> You should be able to select a storage class
Apps -> Charts -> Monitoring -> Install/Update -> Grafana -> "Enable with PVC Template" Grafana storage -> Storage Class name -> You should be able to select a storage class
Areas which could experience regressions
None
=> [2.10] Storage class selector not working

creators/extension/app/files/.github/workflows/build-extension-catalog.yml, creators/extension/package.json, docusaurus/docs/extensions/known-issues.md
Fixes #12993 
- fix workflow for `catalog` build on `creators` package by adding missing `tagged_release` input
- adds documentation for issues  #12988 and #12995
=> fix wf catalog build on creators + creators version bump

pkg/rancher-components/src/components/Banner/Banner.vue, pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue, shell/assets/styles/global/_button.scss, shell/assets/translations/en-us.yaml, shell/components/ActionMenu.vue, shell/components/BannerGraphic.vue, shell/components/ButtonMultiAction.vue, shell/components/CommunityLinks.vue, shell/components/SortableTable/THead.vue, shell/components/SortableTable/index.vue, shell/components/SortableTable/selection.js, shell/pages/home.vue
Fixes #12776 
- Fix keyboard navigation on `home` page
- checkbox is now visibly focusable
- `Banner` component has correct roles, labels and is focusable
- `SortableTable` component has been fixed for basic keyboard nav (sorting, checkboxes, links, open/close row action menu)
- Go to the `home` page and browse the page with the tab key
- use `enter` or `space` key to trigger UI elements on the page
https://github.com/user-attachments/assets/47ee2472-9fb8-445d-b808-a4330f7ad9d2
=> fix keyboard nav for home page

.github/workflows/test.yaml, scripts/e2e-docker-start
Fixes: #12936
- without this it doesn't look like rancher serves up the correct CNi charts related to the version of kube (1.28 and below are fine, 1.29 and above will fail to fetch charts)
=> Use correct container registry for latest 2.9 `head` builds

cypress/e2e/tests/pages/global-settings/settings-p2.spec.ts
Reverts rancher/dashboard#12937
- Now that we're running against the latest `-head` (https://github.com/rancher/dashboard/pull/12935) we can re-enable tests that rely on it
=> Re-enable tests that rely on latest 2.9 image

cypress/e2e/po/components/header.po.ts, cypress/e2e/po/edit/fleet/gitrepo-edit.po.ts, cypress/e2e/po/pages/fleet/fleet-dashboard.po.ts, cypress/e2e/tests/pages/fleet/dashboard.spec.ts, cypress/support/types/menu-actions.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1360
This PR reenables existing and adds new Fleet Dashboard view tests
=> automation: fleet dashboard tests

shell/components/PaginatedResourceTable.vue, shell/components/ResourceList/index.vue, shell/components/SortableTable/THead.vue, shell/components/SortableTable/index.vue, shell/mixins/resource-fetch.js
It wasn't readily apparent what the expected behavior was around things like alt-loading and the manual refresh so I did what made sense to me. See the video to see if it's what we want or if adjustments need to be made.
fixes https://github.com/rancher/dashboard/issues/12748
We no longer flicker the no-rows messaging when first loading one of the server-side pagination pages.
SSP and non-SSP resource list pages.
I think that this should be manually tested, it seems a little difficult to test given the nature of network latency and debouncing we have.
The behavior seen in this video has changed some since the latest rebase. https://github.com/rancher/dashboard/pull/12884/files#diff-16199a1483a9651b7f40bfcb61ed890469ea35d889aee82b0f50b95d2ed2057eR506-R510 Causes the refresh button to no …
=> Resolving some issues around rendering pagination loading on resource list pages

pkg/gke/components/Networking.vue, pkg/gke/components/__tests__/Networking.test.ts, pkg/gke/util/__mocks__/gcp.ts
Fixes #12471 
Backport of https://github.com/rancher/dashboard/pull/13030
=> [2.10.2] update gke networking to select the default network by default

creators/extension/app/files/.gitlab-ci.yml, creators/extension/package.json, shell/scripts/.gitlab/workflows/build-extension-catalog.gitlab-ci.yml
This updates the target branch of the reusable workflow within the `.gitlab-ci.yml` file that is imported into an extension through the creator and ensures we are targeting the correct branch of the workflow file.
- Bumped yq version `v4.4.6`
- Bumped extension creator version `2.0.8`
=> [2.9] Align gitlab reusable workflow with release-2.9

pkg/aks/components/CruAks.vue, pkg/aks/components/__tests__/CruAks.test.ts
Fixes #11841 
This bug is specific to AKS clusters that have been created in Rancher, but not yet created in AKS. To repro, you can use the default AKS configuration options (except region) but you need to edit the cluster immediately after creating it to see the bug. This PR tweaks some login in the location-fetching method that failed to account for this inbetweeny edit mode.
1. Create a new AKS cluster - after entering in credentials, regions should be loaded and east us selected by default.
2. Change the region to something else
3. Set other required fields and save
4. immediately edit the cluster. The region dropdown should show whatever region you picked in step 2. If you open the dropdown, you should see a list of regions to select.
=> fix aks region being overwritten when editing unprovisioned aks clusters

cypress/e2e/po/components/addon-config.po.ts, cypress/e2e/po/components/create-edit-view.po.ts, cypress/e2e/po/edit/provisioning.cattle.io.cluster/create/cluster-create-rke2-custom.po.ts, cypress/e2e/tests/pages/manager/cluster-manager.spec.ts, pkg/eks/components/CruEKS.vue, shell/components/CodeMirror.vue, shell/components/YamlEditor.vue, shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/edit/provisioning.cattle.io.cluster/tabs/AddOnConfig.vue
Fixes #12466 
Backport of https://github.com/rancher/dashboard/pull/13017
=> [2.10.2] Fix rke2 addon validation

shell/components/GrowlManager.vue
Fixes #10247
This PR fixes the alignment issues on the growl component.
Removed margin which caused the issue, reduced the size of the icon slightly for better presentation and tweaked the padding to accommodate the case where a message is used without a title.
See original issue - use the kubeconfig operation from the action menu.
Before:
After: (with this PR's fixes)
=> Fix icon alignment in the growl component

shell/components/ClusterIconMenu.vue, shell/components/nav/TopLevelMenu.helper.ts, shell/models/management.cattle.io.cluster.js
Fixes #12582
Ensures we show the cluster icon badge color for the local cluster.
Add a new getter to the cluster model to return the `iconColor` independently of the badge.
Follow test case in the issue above - add a background color to the local cluster and check that this is now shown on the cluster icon in the app bar.
Before: (rancher icon for the local cluster shows no color)
After: (rancher icon for the local cluster now shows the color)
=> Show badge color for local cluster

cypress/e2e/tests/pages/global-settings/feature-flags.spec.ts, shell/assets/translations/en-us.yaml, shell/config/product/settings.js, shell/config/table-headers.js, shell/list/management.cattle.io.feature.vue
Fixes #11305
This PR renames the column name on the feature flag page and also the message in the confirmation modal.
The terminology now is 'Restart Rancher' (where 'Rancher' is the vendor name)
Table columns only accept a label key which can not have params, so we evaluate the table header with the vendor name when we add the table headers for the feature flag table.
1. Visually check that the column name has changed.
2. Try and activate/deactivate a feature flag that requires restart and check the message is correctly updated. 
List, showing new name for list column for restart:
Modal dialog for activate/de-activate:
=> Improve feature flag restart terminology

.github/workflows/test-extension-workflows-master.yml, .github/workflows/test-extension-workflows-release-2.8.yml, .github/workflows/test-extension-workflows-release-2.9.yml
Fixes #
There was a small typo in the variable we were referencing in the outputs. This will ensure we are using the same `EXTENSION_TAG` variable everywhere in these workflows rather than `EXTENSIONS_TAG`.
=> Typo in Extensions workflows test outputs

docusaurus/docusaurus.config.js
Fixes #12542 
This PR resolves the issue with old links (e.g., `/extensions/extensions-getting-started`) not properly redirecting to the latest version (`/extensions/next/extensions-getting-started`) for versioned extensions documentation.
- Fixed the `createRedirects` function to handle unversioned routes (`/extensions/...`) and redirect them to the latest version (`/extensions/next/...`).
- Scoped the redirect logic to only affect unversioned routes (`/extensions/...`) and not interfere with existing versioned routes such as `/extensions/v2/....`
The `createRedirects` logic checks for routes under `/extensions/next/` and generates redirects for their unversioned counterparts (`/extensions/...`). This ensures that unversioned links point to the latest version (`v3`) without impacting …
=> Return the old path when `next` is missing from the url

shell/vue.config.js
This allows HMR to trigger when changes are made to Rancher Components and Harvester by omitting the `excludes` argument from `getWatcherIgnored()`. Watch and WatchOptions work to allow Webpack to watch files and recompile whenever they change - I don't see any benefit in excluding Rancher Components and Harvester from this process by default.
As I understand, the `excludes` variable exists to control production builds; this change will only affect development.
This also includes a change to clean up the `appConfig` param in `shell/vue.config`.
The prefix `_` is a convention to indicate that a parameter is expected, but unused within a function. We make use of `appConfig` in the default export, so we can remove the `_` and supply a default value for `appConfig` if nothing is passed.
- HMR …
=> Allow HMR in Rancher Components and Harvester

shell/edit/workload/mixins/workload.js
Fixes #13001
The data  method is expected to return a plain JavaScript object, which will be made reactive by Vue. Accessing or modifying unreturned data attributes  in the data method may result in undesired issues
ref: https://vuejs.org/api/options-state.html#data
1. When the component is initialized, the method call to select the first container is placed in the created  lifecycle hooks.
2. watch the active container changes and update `fvFormRuleSets`, in order to display the image form status in real time.
1. should manual test that the form error prompts for the container are correct when creating or editing a workload
ref: https://github.com/rancher/dashboard/issues/13001
=> chore(workload): disable access to unreturned data attributes in data method

pkg/gke/components/CruGKE.vue
Added `data-testid` to GKE elements for e2e tests - cluster name and cluster description - to be validated in an e2e test that provisions a GKE cluster with default settings and verifies that the cluster was successfully created with the correct settings. Unblocks the test development tracked by issue https://github.com/rancher/qa-tasks/issues/1571
=> adding data-testid to mandatory GKE elements for e2e tests locators

package.json, scripts/e2e-docker-start
`head` recently introduced a breaking that causes e2e tests to fail in several way. This is a temporary change to allow e2e tests to run successfully while we work on a fix.
With this change, e2e tests they will explicitly target `v2.11-2053ce644a31cd8053d1f58e2487154b0b8513b6-head` instead of `head`; the backend is essentially pinned to this version until we can unblock it.
=> Pin Rancher version to `v2.11-2053ce644a31cd8053d1f58e2487154b0b8513b6-head` for e2e tests

.github/dependabot.yml
This sets dependabot to check for updates weekly instead of daily.
The current setting of daily appears to be quite aggressive and I think that a weekly check will allow us time to work through the backlog of updates. It also appears that the `open-pull-requests-limit` option[^1] might apply to each individual directory as opposed to max items for a category. We might want to consider scaling this number down if we find that open PRs from dependabot are still too much.
[^1]: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#open-pull-requests-limit-
=> Restrict dependabot checks to weekly instead of daily

pkg/aks/l10n/en-us.yaml, pkg/aks/util/__tests__/validators.test.ts, pkg/aks/util/validators.ts
Fixes #11843 
This PR updates the AKS node pool count validator to include a maximum value.
1. open the AKS cluster creation form and fill in required fields
2. set the aks pool's node count to something >1000
3. verify that an error icon is shown and save button disabled
4. add another node pool and switch to its tab
5. verify that the first node pool's tab has an error icon
6. nav back to the first pool and reduce the node count to <1000
7. verify that the create button is re-enabled and error message gone
None; changes are very narrow in scope
=> validate that AKS node pool count is no more than 1000

cypress/e2e/po/components/create-edit-view.po.ts, cypress/e2e/po/edit/fleet/fleet.cattle.io.clustergroup.po.ts, cypress/e2e/po/pages/fleet/fleet.cattle.io.clustergroup.po.ts, cypress/e2e/tests/pages/fleet/cluster-groups.spec.ts, cypress/e2e/tests/pages/fleet/dashboard.spec.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1362
- This PR reenables existing and adds new Fleet Cluster Groups tests.
- It also fixes a failure seen in Jenkins runs in Fleet Dashboard test
> Fleet Dashboard -> can clone a git repo: AssertionError: Timed out retrying after 10000ms: Expected to find element: `.vs__dropdown-menu > li`, but never found it."
=> automation: fleet cluster groups tests

shell/assets/translations/en-us.yaml, shell/pages/c/_cluster/settings/performance.vue
Adding deprecated messaging to the performance settings page
Fixes #12873
N/A
Performance settings page
N/A
https://github.com/user-attachments/assets/e86f0a19-935e-412d-8e87-0a67908bb079
=> Adding deprecated messaging to the performance settings page

shell/components/form/LabeledSelect.vue
Fixes [#6946](https://github.com/harvester/harvester/issues/6946)
when there were no options, the prompt text `start typing to delete an item` would appear even if the select was not searchable.
- Modified the logic to ensure the prompt only shows if the select is searchable
The `showTagPrompts` was introduced in [PR#12350](https://github.com/rancher/dashboard/pull/12350)
Ref: https://github.com/rancher/dashboard/pull/12350/files#diff-5316c4da698262a356a5f70f02f4d94b95c66b780cedf9cb04515deb011017d8R148-R151
Verify the prompt text only appears when:
- There are no options available and select is both taggable and searchable
Prompt display behavior in `LabeledSelect` component when there are no options
Show `No options` if the select was not searchable
=> LabeledSelect: Show tag prompts only if select is searchable

package.json, shell/components/fleet/FleetBundles.vue, shell/list/fleet.cattle.io.bundle.vue
Fixes #13136
- Forward port of https://github.com/rancher/dashboard/pull/13135
- Note test was not disabled on master. I'm guessing this is because we've pinned the `head` image the e2e tests use so does not contain the fleet regression
> Note - i've muddled branch names up. local branch as 2.10, but correctly from master merging to master
=> Fix gitrepo bundle list and bundle list when there's a gitrepo that does not contain a summary

cypress/e2e/po/pages/extensions.po.ts, cypress/e2e/tests/pages/explorer/apps/charts.spec.ts, cypress/e2e/tests/pages/explorer/apps/repositories.spec.ts, cypress/e2e/tests/pages/extensions/extensions.spec.ts, cypress/e2e/tests/pages/extensions/kubewarden.spec.ts
Fixes #
https://github.com/rancher/qa-tasks/issues/1558
https://github.com/rancher/qa-tasks/issues/1575
https://github.com/rancher/qa-tasks/issues/1560
https://github.com/rancher/qa-tasks/issues/1557
This PR fixes flaky tests seen in Jenkins pipeline test runs. See above links for details.
=> automation: fix flaky tests based on jenkins failures

shell/components/auth/SelectPrincipal.vue, shell/components/form/LabeledSelect.vue
LabeledSelect wasn't explicitly emitting search event.
Added an explicit search event. It should be working as before.
Search should work in anything that uses SelectPrincipal : 
- Cluster member editor (Cluster and Project Members -> Cluster membership -> Add), 
- Project member editor (Cluster and Project Members -> Project membership -> Add) , 
- Configuring any auth provider (github, azuread, etc)
or GitPicker (not used in dashboard code)
None
=> Fixed LabeledSelect not emitting search explicitly

cypress/e2e/tests/pages/manager/cluster-manager.spec.ts, cypress/support/commands/rancher-api-commands.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1638
=> automation: add step to ensure aks is enabled

.github/workflows/test.yaml, docusaurus/docs/internal/testing/e2e-test.md, package.json, scripts/e2e
Fixes #13138
[Added ability to skip Sorry Cypress dashboard](https://github.com/rancher/dashboard/pull/13146/files#diff-8cb4f24c0ba5f6c40b682ffa5d952615082882a11904f3f0faa54ccc942827bc) outside the code and keep E2E tests.
[Added documentation](https://github.com/rancher/dashboard/pull/13146/files#diff-47048a370a6d29aece29830f830c85eff2ff74ef809999d08055f0fbcd3ff4de) to the new skip methodologies.
E2E script will now have the options to run:
- Using Sorry Cypress dashboard as we always did ([CI example](https://github.com/rancher/dashboard/actions/runs/12831157113/job/35781037294?pr=13146#step:7:26))
- Using just E2E and no dashboard, skipping via label ([CI example](https://github.com/cnotv/dashboard/actions/runs/12830898058/job/35780227768#step:7:11))
- Using just E2E and no dashboard, …
=> Allow to skip Cypress dashboard E2E tests using a label or env var

cypress/e2e/po/components/card.po.ts, cypress/e2e/po/pages/global-settings/feature-flags.po.ts, cypress/e2e/tests/pages/global-settings/feature-flags.spec.ts, shell/list/management.cattle.io.feature.vue
Fixes #11167
This PR fixes the issue above and adds an e2e test to cover the changes.
We now revert the change to the feature flag model if the API request to update it fails, ensuring it does not appear changed in the UI.
We also improve the error message, taking the message from the error response if available.
Finally, this PR fixes a small bug, where if an error occurred, closing the dialog and clicking enable/disable again on a flag would show the previous error.
Note: We can't wire this into the flags that require restart, as the API does not always return before it restarts, so the API call can error, but that can indicate that a restart has started.
=> Fix state is not reset when feature flag API request fails

pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue, shell/edit/__tests__/fleet.cattle.io.gitrepo.test.ts, shell/edit/fleet.cattle.io.gitrepo.vue
Fixes https://github.com/rancher/dashboard/issues/11300
Fleet -> GitRepo -> create or edit
=> Fleet Resource Handling - Replace warning banners with tooltips

cypress/e2e/blueprints/manager/registries-rke2-payload.ts, cypress/e2e/po/components/registries-tab.po.ts, cypress/e2e/po/components/select-or-create-auth.po.ts, cypress/e2e/tests/pages/explorer/apps/repositories.spec.ts, cypress/e2e/tests/pages/manager/registries.spec.ts, shell/assets/translations/en-us.yaml, shell/components/form/SelectOrCreateAuthSecret.vue, shell/config/types.js
Fixes #13116
This PR adds support for creation of the `rke.cattle.io/auth-config` (RKE Auth Config) when setting a secret for the registry configuration on cluster creation.
Note we already showed RKE Auth config secrets in the drop-down, but we did not offer the user the ability to create them from the cluster creation screen - this has now been addded.
The changes are all in the `SelectOrCreateAuthSecret` component. The remaining code is to add a new E2E test for these changes.
Note the relevant e2e tests are also updated to delete the secrets and clusters that they create.
I also create the grammar on the create labels - I believe it should be 'an' and not 'a' for the options we have.
Cluster creation with registry configuration and RKE auth config secret auth.
New option is added to …
=> Add support for creation of registry secret using RKE auth config type

shell/edit/fleet.cattle.io.gitrepo.vue
=> Handle correctDrift:enabled undefined value

shell/assets/translations/en-us.yaml, shell/components/ResourceDetail/Masthead.vue, shell/list/management.cattle.io.setting.vue
Fixes #12787 
- fix keyboard nav on settings list page 
- settings edit page
**NOTE: `edit setting` action menu on each setting will be fixed by https://github.com/rancher/dashboard/pull/13019**
- improved show/hide settings list template because it was reliant on a v-if and rendered 2 different buttons that essentially worked as toggle
- needed to tweak the masthead component so that the `focus-visible` CSS state for the title link is actually visible for the user
- also verified that https://github.com/rancher/dashboard/issues/9790 did not regress
=> fix keyboard nav on settings page

pkg/rancher-components/src/components/Form/Radio/RadioButton.vue, pkg/rancher-components/src/components/Form/Radio/RadioGroup.vue, shell/assets/styles/base/_basic.scss, shell/assets/styles/base/_mixins.scss, shell/assets/styles/global/_button.scss, shell/assets/styles/global/_form.scss, shell/components/ButtonGroup.vue, shell/components/form/LabeledSelect.vue, shell/components/form/Select.vue, shell/mixins/vue-select-overrides.js
Fixes #12791 
- Fixes keyboard navigation on the user `preferences` page
- Fixes `Select` component implementation so that it opens on enter/space and not open just on focus
- Fixes `LabeledSelect` component implementation so that it opens on enter/space and not open just on focus
- Fixes `ButtonGroup` so that is keyboard navigable
- Fixes `RadioGroup` and `RadioButton` so that is keyboard navigable
- Test `LabeledSelect`'s and `Select`'s thoroughly throughout the UI, especially more "exotic" implementations. Basic use case should be covered.
https://github.com/user-attachments/assets/324306c6-e4ad-4214-b1d0-f1da2ee647f7
=> fix key nav on preferences page

shell/edit/__tests__/management.cattle.io.setting.test.ts, shell/edit/management.cattle.io.setting.vue
Fixes #13163
- The errors variable in `management.cattle.io.setting.vue` is being overwritten by the errors variable in `@shell/mixins/create-edit-view` mixin.
- We generated a javascript error to test the error's banner. Alternatively, a webhook or a proxy server can be used to generate an API error. See issue's description.
- Edit settings, UI validations
=> Fix errors propagation in Settings edit page

shell/package.json, shell/yarn.lock
Extensions are failing to run in dev mode due to a dependency mismatch after bumping vue to 3.5. Adding `entities` as a dependency of shell helps to resolve issues that have been experienced.
=> Add entities to shell dependencies

shell/assets/styles/base/_basic.scss, shell/assets/styles/vendor/vue-select.scss, shell/assets/translations/en-us.yaml, shell/components/Carousel.vue, shell/components/SelectIconGrid.vue, shell/components/form/Select.vue, shell/pages/c/_cluster/apps/charts/index.vue
Fixes #12783 
- Fixes keyboard navigation on the `charts` page
- Fixes `Select` component implementation so that it opens on enter/space and not open just on focus
- Fixes `SelectIconGrid` so that it allows for keyboard nav
- Fixes `Carousel` so that it allows for keyboard nav
**There's a bug on the `Rules` tab in `ingress` create screen https://github.com/rancher/dashboard/issues/13147 that is proven not to be related to any change of this PR. Ignore it if testing `Select`'s on that area.**
- test `charts` page
- test areas where `SelectIconGrid` is implemented (navlink groups, cluster provisioning, charts, auth provider)
- Test `Select`'s thoroughly throughout the UI, especially more "exotic" implementations. Basic use case should be covered.
=> fix key nav on charts page

shell/assets/translations/en-us.yaml, shell/mixins/chart.js, shell/models/catalog.cattle.io.app.js
Fixes #13126 
We already had the warning messages in place, this PR adds the vendor to those messages.
I tested this using the test repo provided by Diogo from the Mapps team:
Git Url: `https://github.com/diogoasouza/charts`
Branch: `test-annotation`
1. Find `Istio` from the above repo, and install version `105.5.3+up1.24.1`(It has `catalog.cattle.io/managed` set to Flux).
2. Once installed, go to the Installed Apps page and choose Edit/Upgrade from the action menu for `rancher-istio`.
3. Check if **Flux** is included in the warning message on the installing page.
4. Go back to the Installed Apps page.
5. Choose Delete from the action menu.
6. Check if **Flux** is included in the warning message on the modal.
1. Go to the Installed Apps page, and find `rancher-webhook` that is managed by …
=> Add custom vendor to managed apps warning messages for delete and upgrade

pkg/harvester-manager/l10n/en-us.yaml, pkg/harvester-manager/list/harvesterhci.io.management.cluster.vue, pkg/harvester-manager/types.js, shell/utils/uiplugins.ts
=> Match Harvester community repo check via regex

pkg/harvester-manager/list/harvesterhci.io.management.cluster.vue, shell/utils/uiplugins.ts
Contributes to #13199
- Add missing `await`s
- Remove this.harvesterRepository assignment from Install function to avoid multiple repo refresh
=> Fix missing await async calls getting Harvester repository

cypress/jenkins/Jenkinsfile, cypress/jenkins/cypress.config.jenkins.ts, cypress/jenkins/init.sh
ATTENTION!! 
Depends on https://github.com/rancherlabs/corral-packages/pull/71 to be merged in the corral-packages repo
Fixes #https://github.com/rancher/qa-tasks/issues/1641
Supports e2e tests in https://github.com/rancher/dashboard/pull/12934 by Adding the GKE credentials to the jenkins file
GKE cred was stored in the secrets manager with the jenkins identifier tag for the e2e tests that validate GKE cluster provisioning to be executed in the pipeline that stores cloud credentials
Run all e2e tests via the jenkins pipeline
Cluster provisioning tests
Cloud credentials creation tests
Any other tests that rely on authentication with cloud credentials
=> Add GKE credential to jenkinsfile 

cypress/e2e/po/lists/fleet/fleet.cattle.io.cluster.po.ts, cypress/e2e/tests/pages/fleet/fleet-clusters.spec.ts, cypress/globals.d.ts, cypress/support/commands/rancher-api-commands.ts, shell/assets/translations/en-us.yaml, shell/components/fleet/FleetClusters.vue, shell/models/fleet.cattle.io.cluster.js
Fixes #11241
- Added labels subRow to Cluster List
Show more button
=> Fleet: Add CLusters labels

shell/plugins/steve/steve-pagination-utils.ts
Fixes #11627
- covers cases like filtering for a kube version (v1.31.1+k3s1)
- filtering SSP lists
=> Encode the filter param that SSP uses

package.json, pkg/rancher-components/package.json, pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.test.ts, pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue, shell/package.json, shell/utils/validators/cron-schedule.js, shell/utils/validators/formRules/__tests__/index.test.ts, shell/utils/validators/formRules/index.ts, storybook/src/stories/Form/Input.mdx, storybook/src/stories/Form/Input.stories.ts, yarn.lock
Fixes #12229
- Updated library to match new cronjob language terms
- Updated LabelInput logic to accept periodical values as validation of hints with another library which does not support them
- Bumped all 3 packages containing `cronstrue` lib
- Replaced form validation code duplication with exported util, to avoid refactoring in https://github.com/rancher/dashboard/issues/13202
- Extended test to
- Form validation
- Label input with
- Normal
- Periodical
- Invalid
- Added Storybook stories for
- SubLabel
- Cron type
- Normal
- Periodical
- Error
- Multiline
- Added Form rules JSDocs to validation types, to explain how do they work
**Rancher Manager**
**Storybook**
=> Crontab @daily marked as invalid in Rancher Cronjobs

shell/assets/translations/en-us.yaml, shell/edit/auth/ldap/__tests__/config.test.ts, shell/edit/auth/ldap/config.vue
Fixes #12871
Added checkbox with field `searchUsingServiceAccount` only if `type` is `openldap` or `freeipa`.
- Added checkbox and i18n
- Created new unit test for the view to ensure the checkbox
- Auth provider configuration with OpenLDAP, search "Setting up an OpenLDAP Auth Provider on Rancher Dashboard for testing" in Confluence if needed
- Member search on Cluster member configuration
Configuration checkbox
Payload submission
User search
=> Auth Providers: Add search_using_service_account field

cypress/e2e/po/other-products/cis-benchmark.po.ts, cypress/e2e/tests/pages/charts/cis-benchmark.spec.ts
Fixes #
https://github.com/rancher/qa-tasks/issues/1547
Adding p0 tests for the UI chart. Includes install and a Scan. Basic functionality. 
As well as a YAML view check.
E2E tests. CI
CI
=> [UI] - Adding CIS chart UI tests

shell/assets/translations/en-us.yaml, shell/components/ProgressBarMulti.vue, shell/components/form/PlusMinus.vue, shell/components/formatter/WorkloadHealthScale.vue
Fixes #12782 
- Fix workload health keyboard navigation and accessibility
=> fix workload health accessibility

shell/core/plugins.js
Fixes #13205
This PR improves the error handling when we load extensions.
I checked out the elemental-ui extension with the 2.9 branch, built it and served it up locally and developer loaded it into a 2.11 UI running locally - to reproduce trying to load a Vue 2 extension into Vue 3.
We don't have any exception handling in the load - the script for the extension loads, so our onloadhandler gets called. The script has an exception when it is evaluated at load time (error reading 'extend'), but this does not affect our code path - we check window[id]`  is set, but because the injected script errored, it is an empty object and does not have the default function, so the real error for us is when we call that method here - https://github.com/rancher/dashboard/blob/master/shell/core/plugins.js#L …
=> Add error handling to extension load

cypress/e2e/po/components/growl-manager.po.ts, cypress/e2e/po/components/key-value.po.ts, cypress/e2e/po/components/tabbed.po.ts, cypress/e2e/po/edit/resource-detail.po.ts, cypress/e2e/po/edit/services.po.ts, cypress/e2e/po/pages/explorer/services.po.ts, cypress/e2e/po/pages/extensions.po.ts, cypress/e2e/po/pages/global-settings/home-links.po.ts, cypress/e2e/tests/pages/explorer/service-discovery/services.spec.ts, cypress/e2e/tests/pages/extensions/extensions.spec.ts, shell/components/form/KeyValue.vue, shell/components/form/__tests__/KeyValue.test.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1581
This PR also includes small fixes to address flaky Extensions tests.
=> automation: services - external name tests

cypress/e2e/po/components/component.po.ts, cypress/e2e/po/edit/policy/network-policy.po.ts, cypress/e2e/po/pages/explorer/network-policy.po.ts, cypress/e2e/po/pages/global-settings/performance.po.ts, cypress/e2e/tests/pages/explorer/policy/network-policy.spec.ts, cypress/e2e/tests/pages/global-settings/performance.spec.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1589
- Updated name of performance spec (peformance->performance)
- Moved location of policy/network-policy folder
- Updated network-policy po file to be able to construct the page URL dynamically 
- Added test and updated existing network-policy tests based on PO file changes
=> automation: add coverage for labeledinput using v-model.value.number

shell/list/workload.vue
Fixes #13197
- this normally comes from the schema
- `shell/components/ResourceList/index.vue` schema --> shell/components/ResourceList/Masthead.vue --> _typeDisplay?
- there's an override in the resource list though that looks at the custom list's object typeDisplay param
- `shell/components/ResourceList/index.vue` `this.customTypeDisplay = component.typeDisplay.apply(this);`
- typeDisplay is a method outside of the vue method param and was removed in one of the pagination PRs
- fix is to add it back in again
Note - Given https://github.com/rancher/dashboard/pull/13219 this PR now only includes the comment
- Workload list title
=> Fix workload list header text

pkg/aks/components/AksNodePool.vue, shell/components/ButtonMultiAction.vue, shell/components/auth/Principal.vue, shell/edit/auth/saml.vue, shell/pages/diagnostic.vue
This resolves Vue compiler warnings that started appearing after the upgrade to Vue 3.5.
Fixes #13124
- Fix warnings about table structure
- Fix warnings about defineEmits
It appears that this is a behavior that was introduced in to vuejs/core#12088. There's some debate as to whether or not the message is always valid, but it appeared simple enough for us to update our table usage to resolve the warning and clean up the console output.
The affected tables should be reviewed for regressions:
- Diagnostics
- AksNodePool
- Saml
- Principal
The affected tables should be reviewed for regressions:
- Diagnostics
- AksNodePool
- Saml
- Principal
=> Resolve Vue compiler warnings after upgrade to 3.5

shell/assets/translations/en-us.yaml, shell/edit/fleet.cattle.io.gitrepo.vue, shell/utils/validators/formRules/__tests__/index.test.ts, shell/utils/validators/formRules/index.ts
=> Fleet: validate GitRepo Url

shell/assets/styles/base/_basic.scss, shell/assets/styles/global/_button.scss
This updates tertiary button to include the same focus ring used for other button styles. 
This also removes some focus styles that were applied to all buttons by default; these no longer appear to be relevant.
Tertiary buttons are on display for provisioning Amazon EKS clusters (see screenshots).
Button styles across the board. It's good to review existing button styles to assert that the removed styles do not regress.
=> Add focus ring to tertiary buttons

pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue, shell/components/GrowlManager.vue, shell/components/form/ChangePassword.vue
This adds alert roles to the sections that are called out in #12812:
- Users Retention Settings: Cron Schedule
- Create User: Password mismatch
- Health Scale Component: Growl messages
Fixes #12812 
This adds the alert role to the base components so that the issue will be resolved in as many instances as possible.
- Users Retention Settings: Cron Schedule
- Create User: Password mismatch
- Health Scale Component: Growl messages
- Users Retention Settings: Cron Schedule
- Create User: Password mismatch
- Health Scale Component: Growl messages
=> Add missing alert roles to User Retention, Create User, & Health Scale

shell/assets/translations/en-us.yaml, shell/components/SortableTable/index.vue, shell/components/YamlEditor.vue
This adds aria labels to the table filter input and the Import YAML code editor.
Fixes #12818
- add aria label to the table filter input
- add aria label the Import YAML code editor
🗒️ NOTE: The code mirror component requires a special option, `screenReaderLabel`, to assign the `aria-label` to the correct element.
- Basic table filters should now have an aria label associated with them
- Import YAML code editor should have an aria label associated with it
- NA
- NA
=> Add aria labels to table filters and Import YAML code editor

.github/workflows/storybook.yaml
Minor update to github workflow
=> Move env var to only be available to publish step

pkg/rancher-components/src/components/Form/ToggleSwitch/ToggleSwitch.vue
This adds additional WAI-ARIA Roles, States, and Properties to ToggleSwitch. Noted missing properties and keyboard interactions:
- role
- aria-label
- @keydown.enter - defined as optional, but I opted to include it here
Fixes #12817 
`aria-label` is set to `onLabel` because this should be the primary when working with the switch.
The following patterns specified for the switch pattern in the APG[^1] have been implemented. Patterns not implemented are not relevant to this PR.
[^1]: https://www.w3.org/WAI/ARIA/apg/patterns/switch/
- ✅ Space: When focus is on the switch, changes the state of the switch.
- ✅ Enter (Optional): When focus is on the switch, changes the state of the switch.
WAI-ARIA Roles, States, and Properties
- ✅ The switch has role switch.
- ✅ The switch has an accessible …
=> Add WAI-ARIA Roles, States, and Properties to ToggleSwitch

pkg/gke/components/GKENodePool.vue, pkg/gke/components/__tests__/GKENodePool.test.ts
Fixes #12674 
Backport of https://github.com/rancher/dashboard/pull/13310
=>  [2.10.3] GKE - disable the 'max pods per node' field when editing node pools

pkg/gke/components/GKENodePool.vue, pkg/gke/components/__tests__/GKENodePool.test.ts
Fixes #12508 
1. Create a new GKE cluster - max pods per node should be editable
2. Once the cluster has provisioned, edit it - max pods should be uneditable
3. Add a new node pool to an existing cluster - the new pool's max pods should be editable
none
=> GKE - disable the 'max pods per node' field when editing node pools

shell/components/ClusterIconMenu.vue, shell/components/nav/TopLevelMenu.vue, shell/models/management.cattle.io.cluster.js
Fixes #13128 
Backport of #12582
=> [2.9.7] - Backport fix for the badge background color issue

pkg/gke/components/GKENodePool.vue, pkg/gke/components/__tests__/GKENodePool.test.ts
Fixes #12721 
Backport of https://github.com/rancher/dashboard/pull/13310/
=> [2.9.7] GKE - disable the 'max pods per node' field when editing node pools

cypress/e2e/po/pages/home.po.ts, cypress/e2e/po/side-bars/page-actions.po.ts, cypress/e2e/tests/pages/generic/home.spec.ts, cypress/globals.d.ts, cypress/support/commands/rancher-api-commands.ts, shell/assets/translations/en-us.yaml, shell/components/BannerGraphic.vue, shell/config/page-actions.js, shell/pages/home.vue
Fixes #13251
This PR modifies the UI slightly to avoid the issue with keyboard navigation on the banner close icon.
The banner can now be shown/hidden by the page action menu - this feels like a better fit.
PR adds an e2e test to cover the change.
Restore hidden cards now only restores the what's new and login preference banner visibility.
=> Remove close button from banner and move to a page action

package.json
Fixes #https://github.com/rancher/qa-tasks/issues/1677
Sorry-Cypress instance is down; all e2e tests are failing due to this. Disabling it to unblock GA CI
=> disable sorry cypress

shell/assets/translations/en-us.yaml, shell/components/form/FileSelector.vue, shell/components/form/KeyValue.vue
This improves accessibility of `KeyValue.vue` by:
- adding missing aria labels to `KeyValue.vue` 
- adding missing button roles to buttons used throughout the `KeyValue.vue`
- adding table-style grouping with grid roles[^1]
I recommend reviewing this PR commit-by-commit due to the large restructuring of the template with the introduction of row/rowgroup roles.
[^1]: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/gridcell_role#rowheader
Fixes #12813 
🗒️ NOTE: The code mirror component requires a special option, `screenReaderLabel`, to assign the `aria-label` to the correct element.
🗒️ NOTE: This makes use of CSS Subgrids, which should have widespread browser support as of 2023[^2]
[^2]: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout/Subgrid
ℹ️ INFO: …
=> Improve accessibility of `KeyValue.vue`

package.json
Fixes #
- disable sorry cypress due to DO outage, based on https://github.com/rancher/dashboard/pull/13337/files
=> disable sorry cypress due to DO outage

shell/components/Tabbed/index.vue, shell/components/form/ResourceTabs/index.vue, shell/core/plugin.ts, shell/package.json
Fixes #[13166](https://github.com/rancher/dashboard/issues/13166)
- Backport PR https://github.com/rancher/dashboard/pull/12886
- Bump shell version
Check repro steps on original PR https://github.com/rancher/dashboard/pull/12886
=> backport PR 12886 - improvement Tabs extension point

shell/assets/styles/themes/_dark.scss
Fixes #9799
Simple color change for the active nav section for dark mode.
Use a dark grey rather than a color determined off of the primary color.
Set to dark mode.
Go to cluster explorer for a cluster, open one of the nav sections and verify the background color is now grey (see image below).
Go to global settings and change `ui-brand` to `suse` and `csp` and verify that the above again.
=> Improve color used for primary active nav section

pkg/rancher-components/src/components/RcDropdown/RcDropdown.vue, pkg/rancher-components/src/components/RcDropdown/RcDropdownTrigger.vue, pkg/rancher-components/src/components/RcDropdown/useDropdownCollection.ts, pkg/rancher-components/src/components/RcDropdown/useDropdownContext.ts
This ensures that the first item in a dropdown menu only receives focus if the menu is triggered via keyboard interaction. 
Fixes #13358
- Prevents focus of the first dropdown menu item when triggering the dropdown with a mouse
When the dropdown is triggered with the mouse, the focus is sent to the dropdown container. This allows for:
- enabling keyboard interactions to properly set the focus after the dropdown has been triggered via the mouse
- tab behavior of closing the menu and navigating the next tabbable element to remain consistent with keyboard navigation
- Page actions menu
- User Menu
- Page actions menu
- User Menu
https://github.com/user-attachments/assets/5f0b8e4e-089d-4f93-84bc-f5a7f978cd3e
=> RcDropdown: Only focus first element with keyboard input

shell/components/ResourceDetail/Masthead.vue
Provisioning wizard's masthead had a scroller appear next to subtype title
Create cluster -> select any type. No scroller should be visible in the Masthead
Any ResourceDetail page can be affected.
Before
After
=> Fixed scroller appearing provisioning masthead

shell/assets/translations/en-us.yaml, shell/components/form/SSHKnownHosts/KnownHostsEditDialog.vue, shell/components/form/SSHKnownHosts/__tests__/KnownHostsEditDialog.test.ts, shell/components/form/SSHKnownHosts/index.vue, shell/components/form/SelectOrCreateAuthSecret.vue, shell/components/form/__tests__/SSHKnownHosts.test.ts, shell/detail/secret.vue, shell/edit/fleet.cattle.io.gitrepo.vue, shell/edit/secret/index.vue, shell/edit/secret/ssh.vue, shell/models/fleet.cattle.io.gitrepo.js, shell/models/secret.js
Fixes #11236
This PR enhances the `SelectOrCreateAuthSecret` component so that for the SSH secret type, it can also support the `known_hosts` field. Note that this is non-standard in that known hosts is not part of the standard k8s SSH secret type. This is only used by Fleet.
The Fleet GitRepo use of the above control enables the new field, so that when creating a GitRepo, you can specify the known hosts information.
Lastly, the secret view is updated, so that if an SSH secret has the `known_hosts` data key, we will show this on the detail screen and also allow the user to edit via the config screen.
Creating a Git Repo with a secret with known hosts. Validate that the secret that is created has the known_hosts data field and validate that this can be edited in the secrets screen.
The …
=> Add support for known hosts on ssh secret in Fleet Git Repo

shell/mixins/auth-config.js
This resolves an issue where OpenLDAP would not disable properly for auth providers like Okta, Shibboleth, etc.. Explicitly setting `openLdapConfig` to `null` allows the value to be picked up and processed by the PUT request.  
Fixes #13373 
- set `openLdapConfig` to `null`
Explicitly setting `openLdapConfig` to `null` allows the value to be picked up and processed by the PUT request.  
- Okta auth providers
- OpenLDAP for Auth providers
- NA
=> Set `openLdapConfig` to `null`

shell/components/ResourceTable.vue, shell/components/SortableTable/index.vue
This refactors the event listener that was attached to the window so that it is now attached the sortable table. The table needs to listen to the keyup event and the row needs to receive focus in order for this to work; the row's tabindex is set to -1 so that it is not navigable via keyboard.
Fixes #13239
- Refactor event listener for the enter key so that it is no longer attached to the window object, but the sortable table instead
- Prevent event propagation when the action menu button is activated via the enter key
The design of the Checkbox component is quite interesting in that it customizes how events are emitted, rendering common strategies to stop event propagation via `keydown.enter.stop` useless. Rather than attempt a refactor of the Checkbox implementation at this time, I …
=> Fix select behavior for ResourceTable when the enter key is pressed

shell/components/form/LabeledSelect.vue, shell/components/form/Select.vue
Fixes #13252 
- prevent scroll when hitting space key on selects
=> prevent scroll when hitting space key on selects

shell/assets/translations/en-us.yaml, shell/components/SelectIconGrid.vue, shell/pages/c/_cluster/apps/charts/chart.vue, shell/pages/c/_cluster/explorer/tools/index.vue, shell/pages/c/_cluster/uiplugins/index.vue
Fixes #12810 
- add missing alt attribute for informative images
- the `alt` added to the `SelectIconGrid` tackles grid card areas such as cluster provisioning, charts main screen, navlinks groups and auth providers
=> add missing alt attribute for informative images

cypress/e2e/tests/pages/generic/get-support.spec.ts, cypress/e2e/tests/pages/generic/home.spec.ts, shell/config/home-links.js
This PR updates the forum url from https://forums.rancher.com to https://forums.suse.com - the old URL is redirecting to the new, but e2e tests do consider this a failure: https://github.com/rancher/dashboard/actions/runs/13317789813/job/37196017760#step:8:195
'Forums' link on home page
=> Fix e2e tests - change forums.rancher.com to forums.suse.com

shell/edit/provisioning.cattle.io.cluster/index.vue
Partially revert https://github.com/rancher/dashboard/pull/13347/
Needed for #13106 
In #13347 I moved subType computations into one function for readability. Ultimately this causes `emberLink` to recursively call itself when editing virtual clusters as they are technically imported, but also have an annotation specifying a different subType (ie different UI to use). 
This PR primarily effects virtual clusters (or any cluster with custom UI that may be recognized as imported). To test, you will need to run the [virtual clusters ui extension](https://github.com/rancher/virtual-clusters-ui) locally, using [yarn link](https://extensions.rancher.io/extensions/next/advanced/yarn-link) to use code from this PR.
1. create a virtual cluster with default options
2. attempt to edit the cluster …
=> partially revert 13347

shell/initialize/install-plugins.js, shell/plugins/shortkey.js
This disables vue-shortkey when modals are active by creating a new option when registering vue-shortkey, `containerAvoided`, that will prevent triggering if active elements are a child of the modal container.
Fixes #13237 
- add new method to vue-shortkey to prevent triggering when the active element is a child of a given container
- register the modal as a container that should disable vue-shortkey
We might need to consider if any modals rely on keyboard shortcuts registered via vue-shortkey; they would no longer work with this change.
Example: https://github.com/rancher/dashboard/issues/13237#issuecomment-2659782111
- Raise modals on pages that contain keyboard shortcuts
- Ensure that keyboard shortcuts do not trigger when modal is active
- If vue-shortkey registers shortcuts for use …
=> Prevent activating shortkeys when modals are active

shell/components/CruResource.vue
Fixes #12783 
- fix issue with secrets create options not being key nav accessible
=> fix issue with secrets create options not being key nav accessible

shell/components/fleet/FleetBundles.vue, shell/components/fleet/FleetResources.vue, shell/components/fleet/FleetSummary.vue, shell/components/fleet/__tests__/FleetSummary.test.ts, shell/detail/fleet.cattle.io.cluster.vue, shell/detail/fleet.cattle.io.gitrepo.vue, shell/list/fleet.cattle.io.bundle.vue, shell/models/fleet.cattle.io.gitrepo.js, shell/pages/c/_cluster/fleet/index.vue
Change how the GitRepo status info is obtained and processed, by consuming the new fields exposed by Fleet.
Fixes #13243
This PR changes (again, see #12896) the way that bundles state is processed, by iterating over the list of bundles, for simplicity.
Also:
- It uses the new `PerClusterResourceCounts` status field
- Uses the new format for `Resources.perClusterState` in order to build the GitRepo's resource table, getting rid of BundleDeployments altogether.
- Fixes the resource counts in the summary of GitRepo detail pages.
There is a small regression in the Resources table for GitRepos, since the info backing the `Age` column is no longer available. However, this field was often blank as it's not always available.
=> Simplify handling of GitRepo status resources

shell/components/form/LabeledSelect.vue, shell/components/form/__tests__/LabeledSelect.test.ts
Fixes #
Adding an early return in focusSearch() method:
- Executing the focus logic it's not necessary if the component is `disabled`.
- The early return will skip the open=true assignment 
`this.$refs['select-input'].open = true;`
=> Early return in `focusSearch` method when `LabeledSelect` is disabled

shell/components/form/Members/MembershipEditor.vue, shell/edit/management.cattle.io.project.vue
Fixes #12885 
In `MembershipEditor.vue` where we request to fetch the members, the `force: true` flag was needed to be added to `roleBindingRequestParams` in order to get the members.
Please watch the recorded video for a manual test.
https://github.com/user-attachments/assets/c40e8ecf-c5c2-4cc6-a81c-3b0cec35c32a
=> Fix project members not showing up when switching projects

pkg/gke/components/AccountAccess.vue, pkg/gke/components/AdvancedOptions.vue, pkg/gke/components/Config.vue, pkg/gke/components/CruGKE.vue, pkg/gke/components/Import.vue, pkg/gke/l10n/en-us.yaml, pkg/gke/provisioner.ts, pkg/gke/util/gcp.ts, shell/edit/provisioning.cattle.io.cluster/index.vue
Fixes #12408 
This PR adds the initial import page for GKE clusters.
I had to re-arrange some elements of the GKE provisioning form so I could better reuse components between the import and create/edit cluster views. It may be easier to view this PR commit-by-commit for that reason. 
First, go make a GKE cluster or two to import into Rancher.
1. Navigate to the cluster management list view and click 'import existing'
2. Select GKE
3. Enter credentials: if the rancher instance already has at least on gcp cloud credential defined, you should see a dropdown to pick it and an input for the project id. If you don't already have a gcp cloud credential you should see the form to add one
4. Click 'authenticate' - the remainder of the form should load (smaller form than GKE creation)
5. Try …
=> Import GKE clusters

shell/components/PromptRemove.vue
Fixes #4849
- Ensure when uninstalling a cluster tool to offer user the option to also uninstall (if exists) the accompanying crd app.
- This was an existing mechanism broken in two places
- the option is only offered in the cluster tool screen and checked it was there by currentRouter.currentRoute.name. this was no longer correct
- the checkbox was grouped with the confirm delete mechanism
- also fixed some spacing issues
- delete an app from cluster tools page with/without deleting the crd. deleting an app without deleting it's crd should mean any resource nav sections remain (good one to test with is CIS Benchmarch
- deleting an app from the apps list should remain unchanged
- deleting any resource that requires confirmation should remain unchanged
=> Fix offer to uninstall crd app on cluster tools app uninstall

shell/assets/translations/en-us.yaml, shell/edit/provisioning.cattle.io.cluster/CustomCommand.vue, shell/edit/provisioning.cattle.io.cluster/__tests__/CustomCommand.test.ts
Fixes https://github.com/rancher/dashboard/issues/7250
Making the windows messaging more prominent while trying to prevent multiple adjacent banners.
I also added some unit tests to avoid further manual verification.
Custom rke2 clusters on the registration tab.
Custom rke2 clusters on the registration tab.
=> Make a windows workers role warning more prominent

shell/components/Tabbed/index.vue
Fixes #13260 
- fix tab component keyboard navigation
- went for the [automatic](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-automatic/) approach here
=> fix tab component keyboard navigation

pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue, shell/assets/translations/en-us.yaml, shell/components/SortableTable/THead.vue, shell/components/SortableTable/index.vue, shell/utils/string.js
Fixes #12794
- add sortable table a11y fixes according to issue #12794
=> small sortable table a11y fixes

package.json, shell/assets/translations/en-us.yaml, shell/detail/fleet.cattle.io.gitrepo.vue, shell/edit/__tests__/fleet.cattle.io.gitrepo.test.ts, shell/edit/fleet.cattle.io.gitrepo.vue, shell/edit/workload/Job.vue, shell/models/fleet.cattle.io.gitrepo.js, yarn.lock
Fixes #7824
We are adding the possibility to:
- enable/disable polling.
- set up the `pollingInterval` value when creating/editing GitRepos.
- It should be possible to enable/disable polling
- It should be possible to assign the polling interval in edit mode and display the value in view mode
- Default Polling Interval should be 60 seconds when creating new GitRepo
- The value in the input field should be 15 seconds when editing a GitRepo and `spec.pollingInterval` is `undefined`
- A warning should be displayed in case of the polling interval is lower than 15 seconds
- A warning should be displayed in case of a webhook is configured https://fleet.rancher.io/webhook
GitRepo, edit page
Create/Edit
[Screencast from 2025-02-13 17-48-28.webm](https://github.com/user-attachments/assets/c4b8e32a- …
=> Fleet: expose Polling Interval for GitRepos

jest.setup.js, pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue, pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue, pkg/rancher-components/src/components/LabeledTooltip/LabeledTooltip.vue, shell/assets/translations/en-us.yaml, shell/components/ClusterBadge.vue, shell/components/ClusterIconMenu.vue, shell/components/ClusterProviderIcon.vue, shell/components/form/KeyValue.vue, shell/components/formatter/LiveDate.vue, shell/components/nav/Pinned.vue, shell/directives/strip-aria-label.js, shell/directives/strip-html-aria-label.js, shell/edit/workload/index.vue, shell/initialize/install-directives.js, shell/pages/c/_cluster/explorer/ConfigBadge.vue, shell/pages/c/_cluster/explorer/index.vue, storybook/.storybook/preview.ts
Fixes #12807 
- created `v-stripped-aria-label` directive so that we can re-use tooltip texts as aria-label's while stripping out HTML tags 
- add missing textual descriptions for cluster appearance in multiple places
- enable key tooltip containers to reveal their tooltips with keyboard navigation
=> Fix textual descriptions for cluster appearance in multiple places

shell/components/form/LabeledSelect.vue, shell/components/form/Select.vue
Fixes #13252 
- prevent scroll when hitting arrow down key on selects, as identified in https://github.com/rancher/dashboard/issues/13252#issuecomment-2672428059
=> prevent scroll when hitting arrow down key on selects

shell/pages/c/_cluster/legacy/project/index.vue
Fixes #12622
Fixes the above issue.
The `apps` page that was being used as the initial redirect when selecting a project has been removed.
This PR updates this to now go to the legach project-scoped Config Maps page.
Follow the steps in the linked issue and validate that you now go the Config Maps page and do not see the previous schema error message.
=> Fix legacy projects redirect

cypress/e2e/blueprints/fleet/gitrepos.ts, cypress/e2e/tests/pages/fleet/gitrepo.spec.ts, shell/assets/translations/en-us.yaml, shell/components/ResourceDetail/Masthead.vue, shell/components/ResourceDetail/__tests__/Masthead.test.ts, shell/components/fleet/FleetSummary.vue, shell/components/fleet/__tests__/FleetSummary.test.ts, shell/config/labels-annotations.js, shell/detail/fleet.cattle.io.bundle.vue, shell/detail/fleet.cattle.io.gitrepo.vue, shell/edit/fleet.cattle.io.gitrepo.vue, shell/models/fleet.cattle.io.bundle.js, shell/models/fleet.cattle.io.gitrepo.js
Fixes #13189
Adding `createdBy` labels to save the author of Fleet GitRepos @edenhernandez-suse 
```
fleet.cattle.io/created-by-user-id
fleet.cattle.io/created-by-display-name
```
- The UI assigns the labels on GitRepo creation.
- The users cannot change or delete the labels.
- The 'clone' action automatically removes the labels inherited from source GitRepo.
- The new  'Created By' label is visible in the Resource header of the GitRepo and Bundle details pages.
- 'Created By' contains the name of the user that created the Repo with the link to the user's details, if logged user has permissions, otherwise just a plain text.
- In case of missing labels (previous versions), the label is simply hidden.
cc @manno 
- It's still possible to manually edit the YAML files and remove or change the …
=> Fleet: Created By label

shell/components/PromptRemove.vue, shell/dialog/DeactivateDriverDialog.vue, shell/promptRemove/management.cattle.io.globalrole.vue, shell/promptRemove/management.cattle.io.project.vue, shell/promptRemove/management.cattle.io.roletemplate.vue, shell/promptRemove/mixin/roleDeletionCheck.js, shell/promptRemove/pod.vue, shell/utils/__tests__/string.test.ts, shell/utils/string.js
Fixes #13455
- Any of Remove dialogs using the default `shell/components/PromptRemove.vue` component.
- Go to Fleet -> Advanced -> Workspaces
- Create some new workspaces, even empty
- Select N workspaces and click on Delete action
- DeactivateDriverDialog: `shell/dialog/DeactivateDriverDialog.vue`
- Go to Cluster Management -> Drivers -> Node Drivers
- Select N active drivers
- Click on Delete action
- Each dialogs defined in `shell/promptRemove`
- Go to Projects/Namespaces _or_ Users-> RoleTemplate _or_ Workspaces -> Pods
- Select N items
- Click on Delete action
=> Delete dialogs, fix list of items message and Vue warnings

shell/components/auth/login/ldap.vue
Fixes #13499 
- add missing `loadPLugins` method to `ldap` login interface
=> add missing loadPLugins method to ldap login interface

shell/components/fleet/ForceDirectedTreeChart/index.vue
=> Fleet: fix graph zoomFit function in case of null root node

shell/components/nav/NamespaceFilter.vue
Change the way we size the ns-glass element responsible for closing the dropdown if you click outside of the element
Fixes https://github.com/rancher/dashboard/issues/6748
Updated the styling to make sure the element covers the entire screen while ensuring we never overflow the boundaries of the screen.
I deciding to switch the position from absolute to fixed. Previously we covered the entire screen (except the banner) with the element anyway
We now just make it fixed and use right, bottom instead of width and height to guarantee we never exceed the bounds of the window so we won't scroll. We also include the banner because I don't think we intended on omitting it anyway.
Namespace filter on a couple pages.
Nothing known. It's possibly but unlikely that we may have another element we …
=> Change the way we size the ns-glass element responsible for closing the dropdown if you click outside of the element

shell/assets/translations/en-us.yaml, shell/edit/auth/__tests__/oidc.test.ts, shell/edit/auth/oidc.vue
This Add ability to modify `groupSearchEnabled` for Generic OIDC/Keycloak
Fixes #12853 
- Add a new checkbox to modify `groupSearchEnabled`
- Configuring OIDC is a hassle, DM me and we can work on configuring an environment
- OIDC/Keycloak auth providers
- NA
=> Add ability to modify `GroupSearchEnabled` for OIDC/Keycloak auth providers

shell/components/CodeMirror.vue, shell/components/nav/WindowManager/ContainerShell.vue
Fixes #13506 
- update wrongly used patterns for `computed` properties using `$refs`
- Just learned that `$refs` aren't reactive and in the first evaluation of a `computed` they are always `undefined`, which in conjunction with the condition `this.isCodeMirrorContainerFocused && (ev.code === 'Enter' || ev.code === 'Space')` triggered the focus (`this.isCodeMirrorContainerFocused` => `this.currFocusedElem === this.$refs?.codeMirrorContainer` => `undefined` === `undefined`).
- `Import YAML` modal (triggered from header)
- configmap, as per original issue
- `ContainerShell` -> opening terminal and clicking `space`
=> Fix issue with configmap description and pressing `space` shifting focus

shell/mixins/__tests__/auth-config.test.ts, shell/mixins/auth-config.js, shell/store/__tests__/auth.test.ts, shell/store/auth.js, shell/utils/__tests__/array.test.ts, shell/utils/array.ts
Fixes #12477
Included scopes in the Keycloack pop-up as indicated in the issue.
- Replaced `addObjects()` with new `joinStringList()`, including unit tests
- Added tests to the `redirectTo`  action to generate redirect URL to auth provider pop up with all the involved cases
- Added tests to the `test` action to pass all the required options to compose the redirect URL
- Added tests to the `auth-config` mixin used in the view to submit the auth configuration
- Added tests to the utility function `concatStrings()`
**Side notes as report:**
It seems like `scope` was not added to the whole logic after passing the list from the UI. The function where it gets added has not been changed for 5 years and was not working, so nothing about this feature has been used before.
The scopes seem to be in …
=> Generic OIDC group scope is not sent in the request formed by the UI

shell/components/form/ResourceTabs/index.vue, shell/pages/c/_cluster/explorer/EventsTable.vue, shell/store/type-map.utils.ts
=> Add Event schema null checks

shell/assets/translations/en-us.yaml, shell/edit/provisioning.cattle.io.cluster/tabs/etcd/index.vue
Updating the wording used for etcd snapshots
Fixes https://github.com/rancher/dashboard/issues/12487
Before:
After:
=> Updating the wording used for etcd snapshots

shell/components/nav/TopLevelMenu.helper.ts, shell/plugins/steve/steve-pagination-utils.ts
- blocker on steve bump to rancher/rancher (to get fix for BE filter bug)
Fixes #13268
- as per title, now that the v1 mgmt cluster status.connected property is supported wire it in
- side nav cluster list should order clusters in
- local cluster
- running
- name
- side nav
=> Wire in new status.connected property

cypress/e2e/po/components/tabbed.po.ts, cypress/e2e/po/pages/extensions.po.ts, cypress/e2e/tests/pages/extensions/extensions.spec.ts, cypress/support/commands/rancher-api-commands.ts, shell/assets/translations/en-us.yaml, shell/pages/c/_cluster/uiplugins/index.vue
Fixes #13468
Fixed #8134
Only shows built-in extensions on the new 'built-in' tab, which is now only shown when the user has enabled the extension developer preference.
Validate that when you go to 'Extensions' that no built-in extensions show up.
Go to preferences and enable the preference 'Enable Extension developer features'.
Go back to extensions and you should see a new `Built-in` tab:
=> Don't show built-in extensions by default

shell/assets/translations/en-us.yaml, shell/edit/auth/ldap/__tests__/config.test.ts, shell/edit/auth/ldap/config.vue
This adds the "User Login Filter" input to the LDAP config form.
Fixes #13419
- Add "User Login Filter" input to the LDAP config form
- Re-flow form contents (requires manually shifting each input by one)
Because this change include moving form elements around, I recommend reviewing each commit one at a time.
- Active Directory
- OpenLDAP 
- FreeIPA
- NA
=> Add "User Login Filter" input to the LDAP auth provider config

cypress/e2e/po/side-bars/user-menu.po.ts, cypress/e2e/tests/pages/global-settings/performance.spec.ts, cypress/e2e/tests/pages/user-menu/preferences.spec.ts, cypress/e2e/tests/priority/vai-setup.spec.ts, shell/assets/styles/themes/_light.scss, shell/assets/translations/en-us.yaml, shell/components/Collapse.vue, shell/config/settings.ts, shell/pages/c/_cluster/settings/performance.vue, shell/plugins/steve/steve-pagination-utils.ts, shell/scripts/typegen.sh, shell/types/resources/settings.d.ts, shell/utils/pagination-utils.ts
Fixes #13089
- Previously the ui-performance object ssp object contained a required set of resources to apply ssp to
- This isn't workable going forward where the available resources will be updated between versions
- i.e upgraded clusters won't get the new settings
- Now the default is to use a the inbuilt default resources which can change between versions
- Users can override if they wish (for preference OR in case of bugs)
- Fresh system (or with `/v3/settings/ui-performance` value set to an empty string). No pagination anywhere 
- Check SSP on, no other changes. Pagination on for places like the home page
- When running in dev, in performance page, use the `defaults` button and enable SSP to populate the `resources with default`. Pagination on for places like the home page. Tweak the …
=> Update pagination settings (almost) ready for production

shell/components/form/KeyValue.vue
Fixes #13470 , #13471 
The filtering toggle in `KeyValue.vue` has never worked properly. There were two sources of truth in there, first `filteredRows` which was filtering items that are a system label, passed as `protectedKeys` prop, and the second was `this.rows` which includes the whole items. When rendering, the component was using `filteredRows` but when adding or removing items, `this.rows` was being mutated by using the index of items in `filteredRows`.
You can see this issue by going to Explorer => Projects/Namespaces => Edit Config => Check Pod Security Admission Tab => enable any of the items there => Check Labels & Annotations Tab => Add a label using "Z" for its key and label => Try to Remove
Because there's no unique property in a label to rely on, you need to either create a …
=> Hide filtered items in KeyValue

shell/assets/translations/en-us.yaml, shell/models/management.cattle.io.kontainerdriver.js, shell/models/provisioning.cattle.io.cluster.js
Fixes #13331
This PR removes editing of Kev1 clusters and the ability to dive into the details. It also puts back in the strings for Kev1 clusters with `(Unsupported Kev1)`.
Manually create a kev1 cluster using an old version of the UI (e.g. 2.9) and going to `g/clusters/add/launch/amazoneks` (for AWS) and creating a KEV1 cluster.
It does not matter if the cluster finishes provisioning to verify this PR.
Expected is as above - the `Edit Config` is removed from the action menu, the cluster name is not a link so you can not go to details and the Provider shows that it is unsupported kev1.
=> Disable editing and detail view for kev1 clusters

cypress/e2e/tests/pages/users-and-auth/users.spec.ts
Fix `users.spec.ts` - `can Deactivate and Activate user` test
=> Fix `users.spec.ts` E2E tests

shell/components/CodeMirror.vue, shell/components/ResourceYaml.vue, shell/components/YamlEditor.vue, shell/components/form/SSHKnownHosts/KnownHostsEditDialog.vue
Fixes #13528 
- Fixes issue `1` by adding the `inert` HTML attribute when in view mode (disabled) https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inert so that element and it's children aren't focusable
- Fixes issue `2` by updating CSS on modal + adding padding to bottom of `CodeMirror` component so that it can fit the "escape to blur" message
- @torchiaf regarding the issue with `escape` closing the modal and not leaving the code mirror focus trap, it will be fixed once https://github.com/rancher/dashboard/pull/13519 get's merged.
After that you'll only need to add to AppModal component inside of that modal the following: `:trigger-focus-trap="true"`.
This will make the modal a focus trap itself while it's open.
=> fix misc issues with codemirror and a11y

shell/mixins/vue-select-overrides.js
Fixes #13262  -> comment https://github.com/rancher/dashboard/issues/13262#issuecomment-2683180400
- fix error with option selected having index `-1` in `Select` component
- Test with the referred input in the issue comment. Trick is to have selected the "search" input on the `Select` and not an actual option
@izaac this the correct scenario, right? It was the only way I could repro it
=> fix error with option selected having index -1 in `Select` component

cypress/e2e/tests/pages/users-and-auth/users.spec.ts, shell/components/__tests__/Collapse.test.ts
=> Fix users e2e tests 2

pkg/eks/components/AccountAccess.vue, pkg/eks/components/CruEKS.vue, pkg/eks/components/Import.vue, pkg/eks/components/NodeGroup.vue, pkg/eks/l10n/en-us.yaml, pkg/eks/provisioner.ts, pkg/eks/types/index.d.ts, pkg/eks/util/__tests__/validators.test.ts, pkg/eks/util/validators.ts, pkg/gke/components/Import.vue, shell/assets/styles/base/_helpers.scss
Fixes #12409 
Similar to https://github.com/rancher/dashboard/pull/13447
For testing purposes you should be to use my existing eks cluster `nb-eks` inn the `us-west-2` region
1. Navigate to the cluster management list view and click 'import existing'
2 Select EKS
3. Enter credentials: if the rancher instance already has at least on aws credential defined, you should see a dropdown to pick it and an input for the project id. If you don't already have a aws  credential you should see the form to add one
4. Click 'authenticate' - the remainder of the form should load (smaller form than EKS creation)
5.Try selecting different regions - the cluster dropdown should reload (you should see aws api calls in the network tab)
6. Name your cluster - verify that name form validators are used
7.Add …
=> Import EKS clusters

shell/pages/c/_cluster/uiplugins/index.vue
Fixes #13541
This PR makes a minor update so that built-in extensions never show on the `installed` tab, even when the extension developer preference is set.
The `Installed` tab is only for extensions that have been manually installed by the user.
The `Updates` tab will never show built-in extensions, as they are not installed so won't have updates.
Built-in extensions will appear on the `Built-in` and `All` tabs when the preference is set.
Validate that with the developer preference set, the `Installed` tab does NOT show built-in extensions.
=> Never show built-in extensions on the 'installed' tab

pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue, shell/assets/translations/en-us.yaml, shell/components/AppModal.vue, shell/components/ButtonGroup.vue, shell/components/CodeMirror.vue, shell/components/PodSecurityAdmission.vue, shell/components/PromptRemove.vue, shell/components/nav/Header.vue, shell/components/nav/WindowManager/index.vue, shell/mixins/vue-select-overrides.js, shell/pages/c/_cluster/apps/charts/index.vue
Fixes #12811 
- Fixes a11y issue `223`, focus trap on `LabeledSelect` inside `Import Extension Catalog` modal by refactoring the mechanism to prevent `escape` key handler on modals based on other UI elements like `CodeMirror` and `LabeledSelect`. Architecture is now only based on preventing propagation of events 🪄 
Should be tested also the `Import YAML` modal since it features both `LabeledSelect` and `CodeMirror` as UI elements that have the need to prevent that `escape` key handler on `AppModal`
- a11y issue `177` fixed on a previous PR
- Fixes a11y issue `166` by improving aria-label's for the `ButtonGroup`
- Fixes a11y issue `155` and `179`  by allowing `LabeledInput` to pass an `aria-label` as a prop of `LabeledInput`. This covers the cases where `LabeledInput` is used without a …
=> fix misc issues for a11y

cypress/e2e/po/components/action-menu.po.ts, shell/components/ActionMenuShell.vue, shell/pages/c/_cluster/uiplugins/index.vue, shell/store/action-menu.js
This replaces the extensions menu with the ActionMenuShell component. Using the new action menu component provides us with out of the box accessibility features and keyboard navigation.
Fixes #13504
- Accept custom actions in ActionMenuShell
- Replace extensions menu with ActionMenuShell
The design of the existing action menu operates in such a way that emitted events are not declared. I attempted to find a way to work around the Vue warnings we receive when emitting events in this way, but we might need to refactor how custom actions are emitted. I'm open to suggestions on how to resolve this without requiring a larger refactor.
- Extensions menu
- Extensions menu
=> Replace extension menu with `ActionMenuShell.vue`

shell/assets/translations/en-us.yaml, shell/edit/resources.cattle.io.backup.vue
Adding the ability to configure resource sets to `resources.cattle.io.backup`
Fixes: https://github.com/rancher/dashboard/issues/12997
_You'll need to install the `Rancher Backup` app first._
- The `resources.cattle.io.backup` edit/detail page.
- You should test the backup page while creating and deleting the `resources.cattle.io.resourceset`. To create I just cloned the existing and changed the name field in the yaml.
- Same as above
https://github.com/user-attachments/assets/fab0e9d9-8a9c-4d34-b1ab-3712e2d97506
Forgot to include deleting the selected resource in the video:
=> Adding the ability to configure resource sets to `resources.cattle.io.backup`

cypress/e2e/po/extensions/imported/cluster-edit.po.ts, cypress/e2e/po/extensions/imported/cluster-import-generic.po.ts, cypress/e2e/tests/pages/manager/cluster-manager.spec.ts, pkg/imported/components/CruImported.vue, pkg/imported/l10n/en-us.yaml, shell/assets/translations/en-us.yaml, shell/utils/validators/formRules/__tests__/index.test.ts, shell/utils/validators/formRules/index.ts
Adding the Registries accordion to the imported clusters edit pages
Fixes https://github.com/rancher/dashboard/issues/13063
Just a port from ember to vue.
Nothing of note, just followed the existing patterns.
The registries tab within the generic import provisioning page.
This is new and unlikely to affect other areas.
=> Adding the Registries accordion to the imported clusters edit pages

shell/utils/validators/formRules/__tests__/index.test.ts, shell/utils/validators/formRules/index.ts
Handle empty registryUrls
Fixes https://github.com/rancher/dashboard/issues/13559
Fixing an issue where our validation didn't accept empty urls even though the field isn't required.
Don't return an error on empty string.
Imported generic clusters should be able to edit and save without entering a registryUrl.
=> Handle empty registryUrls

pkg/imported/components/Basics.vue, pkg/imported/components/CruImported.vue, pkg/imported/components/VersionManagement.vue, pkg/imported/l10n/en-us.yaml, pkg/imported/util/shared.ts, shell/assets/translations/en-us.yaml, shell/config/labels-annotations.js, shell/config/settings.ts
Fixes #13069 
Added an controls to disable version management for imported cluster.
Added a new Radio button group to allow users to disable version management for the cluster. 
Please refer to the RFC and ux mockups for more detail
1. On cluster import switching between options should update warning text. Saving the cluster with 'global default' should set the value of 'rancher.io/imported-cluster-version-management' annotation to match the global setting.
2. On cluster edit, switching between options should update the warnings. 
3. On edit, if 'K8s version management' is set to disabled, K8s version information and Upgrade strategy controls should be hidden
4. If it is set to enabled, K8s version information and Upgrade strategy controls should be visible and editable
5. If it is Set to …
=> [FEAT] Option to disable version management for imported cluster

shell/components/nav/WindowManager/ContainerShell.vue
Fixes #13555 
- Fixes scenario where when user clicks outside shell window should clear message "press escape to blur"
=> Fix Press Escape key to blur from terminal shows when terminal does not have focus

shell/pages/c/_cluster/explorer/__tests__/index.test.ts, shell/pages/c/_cluster/explorer/index.vue
Fixes #13580
The UI calculates the Fleet status based on the status of `fleet-agent` StatefulSet.
Fleet agent is changed from `StatefulSet` to `Deployment` in 2.11
- Permissions to GET StatefulSet resources is not more required:
```
this.$store.getters['cluster/canList'](WORKLOAD_TYPES.STATEFUL_SET)
```
- Local cluster explorer -> Dashboard -> Fleet healthbox
- Downstream clusters -> Dashboard -> Fleet healthbox
Fleet healthbox
Fleet Deployment API call
=> Change Fleet agent from StatefulSet to Deployment for Fleet Healthbox calculation

shell/assets/styles/base/_basic.scss, shell/assets/styles/global/_labeled-input.scss, shell/assets/styles/global/_select.scss, shell/assets/styles/themes/_dark.scss, shell/assets/styles/themes/_light.scss, shell/components/form/Password.vue, shell/components/form/UnitInput.vue
This updates focus styles for inputs to match the updated design and colors.
Fixes #13522 
- Add new colors, `waterhole` & `waterhole-60`
- Change display of inputs from `display: table` to `display: flex`
- Update focus ring offset
- Add focus ring to select component
In order to resolve an issue with displaying the focus ring in Firefox, we had to update the display of the labeled input from `table` to `flex`. This change requires some additional style updates. For example, the password input needed some additional changes to properly display the show/hide toggle.
- Inputs & Selects
- Forms
- Labeled Input
=> Update focus styles for inputs

shell/assets/translations/en-us.yaml
Fixes a typo found https://suse.slack.com/archives/C02AXMUQ4A1/p1741190572831509
=> Fixing a typo on the resource set options

pkg/aks/components/Config.vue
Fixes #12917 
Used the existing prop `valueCanBeEmpty` in `KeyValue` component to allow having empty tags in AKS provisioning.
same as the original issue's repro steps
=> AKS - Fix adding empty tags

cypress/e2e/tests/pages/manager/cluster-manager.spec.ts, shell/models/nodedriver.js
Fixes  https://github.com/rancher/dashboard/issues/13602
Added the Oracle provider to the hardcoded CLOUD_CREDENTIAL_OVERRIDE list, similar to the previous fix https://github.com/rancher/dashboard/pull/11984 for Nutanix
- Verified that the cloud credential selector appears and functions correctly for Oracle OCI.
- Confirmed that other providers were unaffected by this change.
=> Fix Missing Cloud Credential Selector on Create Oracle OCI Cluster Page

shell/edit/auth/ldap/config.vue
This restores all form inputs for the Customize Schema section for the LDAP configuration form to their appropriate columns by refactoring this section to use CSS flexbox.
Fixes #13616
- Replace custom rows and columns for the Customize Schema section of the LDAP form with a CSS flexbox implementation
🗒️ NOTE: if this refactor it too risky, we can revert to the previous implementation and manually shuffle around inputs in the rows/columns. I took on this effort because it was rather straightforward to implement and it improves the developer experience for managing these inputs moving forward.
PR #13464 introduced a change that regressed the layout of the Customize Schema section in the LDAP forms. I think that relying on CSS flexbox to layout the columns makes it much more clear that …
=> Use CSS flexbox for LDAP schema columns

shell/assets/translations/en-us.yaml, shell/components/CodeMirror.vue, shell/components/nav/WindowManager/ContainerShell.vue
The escape key conflicts with modal editing when working in VIM mode. Using `Shift+Escape` helps to prevent that conflict.
Fixes #13601 
- Use `Shift+Escape` to exit code mirror and shell focus trap
I think there's an argument that can be made for making this key combo a configurable preference in the future.
- Code Mirror
- Default Keybinds
- Vim Keybinds
- Emacs Keybinds
- Shell
- Code Mirror
- Shell
=> Use `Shift+Escape` for terminal and editor escape sequence 

cypress/e2e/po/pages/global-settings/settings.po.ts, cypress/e2e/tests/pages/global-settings/settings.spec.ts, shell/list/management.cattle.io.setting.vue
Fixes #13587 
Fixed broken text.
Re-enabled skipped 'can update engine-iso-url' test
=> Fixed broken banner text in Global settings

shell/components/formatter/ServiceType.vue
This makes `headless` and `clusterIp` into computed props so that they can be picked up better by reactivity.
Fixes #12982 
- Make `headless` and `clusterIp` computed props in `ServiceType.vue`
`headless` was defined in the body of `data` in such a way that it was preventing the component from picking up on reactive changes. This would cause the component to not re-render even when data changed. Specify computed props resolves the issue with the component.
See issue for details.
Local Cluster => Service Discovery => Serivces => Apply sorting to the table
Local Cluster => Service Discovery => Serivces => Apply sorting to the table
=> `ServiceType.vue`: Make `headless` and `clusterIp` computed props

cypress/e2e/tests/pages/explorer2/cluster-project-members.spec.ts, shell/components/ResourceDetail/Masthead.vue
Fixes https://github.com/rancher/dashboard/issues/13546
Fixes https://github.com/rancher/dashboard/issues/13570
It looks like https://github.com/rancher/dashboard/commit/c6db1b70dfd5a4a7b252585e7904ff45b59c3e0f#diff-dcf43af1960ee931344da2d37e6237c086acbdacc5d16489ec02e67319c27338R590 wanted to shift just the title over but inadvertently shifted the namespace as well. We now make the same change but on a more specific element.
Detail pages with namespaces (secret, configmap)
Detail pages with namespaces (secret, configmap)
You can see that we still display list page mastheads as expected, focus appears to not be cut off, we handle overflow of long names and the title and namespaces are now aligned.
https://github.com/user-attachments/assets/efea8763-d957-47a5-8602-db644f20c6f0
Fixed the …
=> Updating how we move the title using css

pkg/harvester-manager/machine-config/harvester.vue
Fixes https://github.com/rancher/dashboard/issues/13119
n/a
Relocate the request in the already existing try-catch block.
Create a Harvester guest cluster.
n/a
n/a
=> The page `Cluster: Create Harvester` crashes when the vgpudevice request fails

pkg/aks/components/__tests__/Config.test.ts, shell/assets/styles/themes/_dark.scss
Fixes #13122
Fixes the group style for dark mode in the dropdown.
Note, the style `` is only used in one place, so changing this color should not have other impact.
For now, have chosen the corresponding color to the light mode.
We will review all colors in a future release.
=> Fix dark mode color for dropdown group

shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml, shell/config/version.js, shell/pages/home.vue
Fixes: #13603
Bump current version from 2.10 to 2.11
- bump version const
- const only seems to be used on doc links
- community docs for 2.11 are up, prime docs pending
- use version const in what's new link text in home page
- Home Page --> `Links` card --> Docs link should go to https://ranchermanager.docs.rancher.com/v2.11 (and not v2.10
- Selection of other links. Nice way to check, see https://github.com/rancher/dashboard/blob/master/pkg/rancher-prime/docs.ts#L16 and search for $V$
=> Bump current version from 2.10 to 2.11

shell/components/ResourceTable.vue, shell/detail/provisioning.cattle.io.cluster.vue
Fixes #13659 
- hide grouping controls for `machines` and `machine pools` in prov cluster details view corresponding tab
I couldn't reproduce this in a very recent backend version + current master.
However I did notice that the grouping controls in the issue screenshots was not there, but on my env it was present but not actually performing anything meaningful. I think that we want to continue to display the grouping by pools as it was it's default but it's pointless to see those in this table by namespace as they will always belong to the same namespace.
I've created a prop that hides the grouping controls without disabling the grouping enforced by this resource table (pools)
- Re-test this with the described env to double-check that we can't repro the original issue
- I don't think this …
=> RKE2 Cluster Detail Page: Machine Pools List is not grouped by pool / machine deployment

pkg/aks/components/CruAks.vue, pkg/aks/components/Import.vue, pkg/aks/components/__tests__/CruAks.test.ts
Fixes #13647
Fixes #12407 - see [comment](https://github.com/rancher/dashboard/issues/12407#issuecomment-2699640626)
This PR corrects some error handling around the aks import cluster component: previously when no clusters were found in azure the dropdown component received `null` options and broke the page.
This PR also fixes an issue where the imported cluster name validator would run when loading the regular AKS provisioning form
Import an AKS cluster - test that the form loads when AKS clusters are not available and when they are
Also test scenario described in #13647 (create new AKS cluster)
old ui for comparison:
=> Fix AKS import page when no aks clusters are found

shell/config/labels-annotations.js, shell/pages/home.vue, shell/plugins/steve/steve-pagination-utils.ts, shell/utils/cluster.js
Fixes #12890
- There is now an annotation on the v1 prov cluster that displays the name of the cluster regardless of provisioner
- Wire this in to the home page list sorting by name
> There needs to be a combination of both rke1 and rke2 cluters - they can be of type imported
- order of home page clusters when sorting by name
=> Wire in sorting/filtering clusters on new cluster human name label

cypress/e2e/tests/pages/generic/home.spec.ts, shell/assets/translations/en-us.yaml
Fixes #13657 
Simple translation string change.
Home page what's new message.
=> Remove Vue 3 information from the what's new message

pkg/imported/components/Basics.vue, pkg/imported/components/CruImported.vue, pkg/imported/components/VersionManagement.vue
Fixes #13619 
Hid Cluster version management for RKE1 cluster
- Changed the conditions on when to show and initialize version management.
- Replaced a few cases checks that were supposed to only affect create but were also affecting config mode
- Hid Registries for Rke1
- Showed K8s version management for imported cluster in Pending state
Refer to issue description for the test case
None
=> [FIX] Hid version management for RKE1

cypress/e2e/tests/pages/fleet/gitrepo.spec.ts, shell/edit/__tests__/fleet.cattle.io.gitrepo.test.ts, shell/edit/fleet.cattle.io.gitrepo.vue, shell/edit/monitoring.coreos.com.prometheusrule/AlertingRule.vue, shell/edit/monitoring.coreos.com.prometheusrule/index.vue, shell/utils/duration.js
Fixes #13661
- The UI now accepts `pollingInterval` string in both integer and ISO 8601 duration format (i.e.: `1m3s` = `63` seconds).
- The UI now converts the `pollingInterval` value from int string to duration string before saving.
Edit 
- Go to local cluster -> Open Kubectl Shell
- Create some new GitRepos in `fleet-local` workspace
```
kubectl -n fleet-local apply -f https://raw.githubusercontent.com/manno/fleet-experiments/refs/heads/main/gitrepo-lots.yaml
```
- Select one of the new GitRepos and edit the `pollingInterval` field -> save.
Create
- Clone one of the GitRepos, edit the `pollingInterval` and save.
[Screencast from 2025-03-10 18-45-13.webm](https://github.com/user-attachments/assets/e4e41e87-73b6-4ce2-861d-60683b849943)
=> Fleet, fix pollingInterval format

cypress/e2e/po/edit/provisioning.cattle.io.cluster/create/cluster-create.po.ts, cypress/e2e/tests/pages/manager/cluster-provisioning-azure-rke2.spec.ts, shell/cloud-credential/azure.vue, shell/edit/provisioning.cattle.io.cluster/SelectCredential.vue
Fixes #13590 
There are 2 components to this fix:
1. The SelectCredential component expects test functions to either return true, false, or throw an error: when the azure credential test fails, the test function should throw an error instead of returning a parsed error message
2. When the SelectCredential component catches an error thrown by a test function it should return, not saving the bad credential
Attempt creating azure credentials with invalid values during AKS cluster creation and rke2 azure cluster creation
Creating valid azure credentials
=> fix azure credential test function

shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #12967 
- fix issue with `CA cert bundle` not resizing properly by displaying it's parent component ONLY if the `registry` tab is active
As per https://github.com/rancher/dashboard/issues/12967#issuecomment-2701831931, 
This is broken in 2.10 (2.10.0). I believe the problem lies with the repro steps:
Go to Cluster Managements -> Create a new RKE2 cluster
Click on Registries tab
Add a new Registry Authentication in the array group field
Add a long text in "Ca Bundle" field
Now, if you do an `edit` to that cluster, it get's you into the edit interface, but on the "basics" tab. If you click on the "registries" tab, you'll see the element "broken".
If you refresh the edit page interface, but with the `Registry` tab already open (url with `#registry`) then you get the visual of the UI …
=> fix issue with CA cert bundle not resizing properly on cluster edit

pkg/imported/components/CruImported.vue, shell/components/form/SchedulingCustomization.vue, shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/models/cluster.js
Fixes #13615 #13611 #13630
- Hid  'Cluster agent' tab for local cluster
- Adjusted Scheduling customization behavior when feature is disabled
1. Enable 'cluster-agent-scheduling-customization' feature flag
2. Cluster management -> Edit Local cluster -> 'Cluster agent' tab should be hidden
3. When editing local cluster, 'clusterAgentDeploymentCustomization.schedulingCustomization' field should not be present in the request
3. Provision a new RKE2 cluster
4. Have Scheduling Customization enabled
5. Disable 'cluster-agent-scheduling-customization' feature flag 
6. Go back to the cluster you just created
7. Scheduling Customization  should be enabled, but 'Apply global settings for Priority Class and Pod Disruption Budget' should be hidden
Imported cluster behavior can be affected
=> [FIX] Scheduling customization adjustments

pkg/gke/components/CruGKE.vue
Fixes #13562 
Moved nodePools configuration to non-imported block, since cluster import doesn't need it and doesn't have them defined
- Import GKE -> select credential -> no error should be shown in the console
- Edit imported GKE -> no error should be shown in the console
- Create GKE -> no error should be shown in the console
- Edit existing GKE -> no error should be shown in the console
GKE provisioning and import (both create and edit)
=> Fixed error shown in console when importing GKE

shell/mixins/__tests__/auth-config.test.ts, shell/mixins/auth-config.js, shell/store/__tests__/auth.test.ts, shell/store/auth.js, shell/utils/__tests__/array.test.ts, shell/utils/array.ts
Fixes #12589
Check original PR for details https://github.com/rancher/dashboard/pull/13514
=> [backport v2.10.4] Generic OIDC group scope is not sent in the request formed by the UI 

cypress/e2e/po/components/toggle-switch.po.ts, cypress/e2e/po/edit/chart-repositories.po.ts, cypress/e2e/po/edit/pod-security-admissions.po.ts, cypress/e2e/po/pages/account-api-keys.po.ts, cypress/e2e/po/pages/global-settings/settings.po.ts, cypress/e2e/po/pages/login-page.po.ts, cypress/e2e/po/side-bars/burger-side-menu.po.ts, cypress/e2e/po/side-bars/user-menu.po.ts, cypress/e2e/tests/accessibility/shell.spec.ts, cypress/support/commands/accessiblity.ts, package.json, shell/components/PromptChangePassword.vue, shell/components/nav/Header.vue, yarn.lock
Fixes #https://github.com/rancher/qa-tasks/issues/1639
- Added more accessibility tests
- Improved output readability by separating test suites and test cases before listing accessibility violations
=> add more accessibility tests

pkg/imported/components/CruImported.vue, pkg/imported/l10n/en-us.yaml
Fixes #13303 
Added missing banner.
Cluster management -> Local -> edit
Make sure Member roles accordion has a warning banner 
"Caution: This is the cluster that Rancher is using as a data store. Only administrators should be given write access to this cluster.
Users with write access to this cluster can use it to grant themselves access to any other cluster managed by this installation."
Imported cluster creation and edit should not show the banner
=> Fixed missing banner when editing local cluster

shell/components/formatter/ServiceType.vue
This ensures that the translation properly updates when sorting by making the translation a computed property.
Fixes #12982
- Move the translation from data to a computed property
This is really just a cherry pick of a change from one of the 2.12 PRs for correcting antipatterns in data props #13669 (a1e78f5fd7871764d86929387cdc86f5b2516d98).
I originally limited my change in an attempt to avoid disrupting too much, but it appears that the correct choice would have been to go all the way.
See [this comment](https://github.com/rancher/dashboard/issues/12982#issuecomment-2712090380) for details
Local Cluster => Service Discovery => Services => Sorting on Type should work correctly; the default translation should properly update in the cell if it is replace with a different string.
- NA
=> Replace translated data prop with computed prop in ServiceType

.github/workflows/test.yaml, shell/components/auth/login/ldap.vue
Fixes #13500 
- add missing `loadPLugins` method to `ldap` login interface
=> add loadPLugins method to ldap login interface

jest.setup.js, shell/components/auth/Principal.vue, shell/components/auth/__tests__/Principal.test.ts, shell/components/form/Members/MembershipEditor.vue, shell/components/form/Members/__tests__/MembershipEditor.test.ts, shell/components/form/__tests__/ArrayList.test.ts
Fixes #13167
Fixes #13319
Made component Principal (the user card) to fetch again the member data on prop change (the ID passed in the array).
- Moved `Principal` logic within a method and called on prop change
- Added Jest setup configuration to prevent Vue warns to spam the console while debugging
- Added unit tests
- `ArrayList` 
- Added case with more items
- Update test to get correct emitters (the removed one is confusing) which require mocked timers
- `MembershipEditor` ensured removing a member is still working correctly as in the component
- `Principal` test to update fetched values on prop change
As by issue
https://github.com/user-attachments/assets/f918b82d-a465-4e72-adaf-a0e42aeba31e
=> Last Project Member removal in Rancher Dashboard

pkg/rancher-components/src/components/Form/Radio/RadioButton.vue, pkg/rancher-components/src/components/Form/Radio/RadioGroup.vue, shell/edit/__tests__/cis.cattle.io.clusterscan.test.ts, shell/edit/cis.cattle.io.clusterscan.vue
Fixes #13376
Extended further custom validation for CIS Benchmark as for other 3 cases.
- Added `data-testid` of `RadioButton`
- Created validation for CIS Benchmark
=> Schedule: When creating a CIS Benchmark scan the input @daily is accepted but the 'Create' button remains greyed out

shell/edit/logging-flow/Match.vue
Fixes https://github.com/rancher/dashboard/issues/13600
=> Remove duplicate container selector in Logging, create Cluster Flow page

pkg/harvester-manager/machine-config/harvester.vue
Fixes https://github.com/rancher/dashboard/issues/13404
=> [2.10] The page Cluster: Create Harvester crashes when the vgpudevice request fails

shell/models/__tests__/catalog.cattle.io.app.test.ts, shell/models/catalog.cattle.io.app.js
Fixes #13704 
- Made matching chart logic more strict
- Updated unit test mocks to be more accurate
=> Disallow matching charts with undefined home values

pkg/eks/components/Config.vue, pkg/eks/components/CruEKS.vue, pkg/eks/components/Networking.vue, pkg/eks/components/__tests__/Config.test.ts, pkg/eks/components/__tests__/CruEKS.test.ts, pkg/eks/components/__tests__/Networking.test.ts, shell/store/aws.js
Fixes #11554 
This PR updates aws api calls made in the EKS provisioning form to account for pagination. The instance type api call already handled pagination. `describeKeyPairs` and `describeSecurityGroups` are not paginated.
[DescribeAddonVersions](https://docs.aws.amazon.com/eks/latest/APIReference/API_DescribeAddonVersions.html) 
[ListRoles](https://docs.aws.amazon.com/IAM/latest/APIReference/API_ListRoles.html) 
[DescribeLaunchTemplates](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeLaunchTemplates.html) 
[DescribeKeyPairs](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeKeyPairs.html) - not paginated
[ListKeys](https://docs.aws.amazon.com/kms/latest/APIReference/API_ListKeys.html)
[DescribeVpcs](https://docs.aws.amazon.com/AWSEC2/latest/APIRefe …
=> [2.12] Handle pagination in EKS AWS ListRoles request

package.json, scripts/e2e-docker-start
#13760 
Similar to https://github.com/rancher/dashboard/pull/10189/fileswe need to update e2e references on the release-2.11 branch to use 2.11 rancher image tags
=> update e2e to use 2.11-head instead of head

shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/utils/object.js
=> Forwardport the fix for vSphere cpi/csi config

shell/edit/auth/__tests__/oidc.test.ts, shell/edit/auth/oidc.vue, shell/edit/provisioning.cattle.io.cluster/__tests__/Advanced.test.ts
Fixes #12926
Since the issue is not clear, the steps are:
- Navigate to `User & Authentication` > `Auth Provider` > `Keycloak OIDC`, or `/c/local/auth/config/keycloakoidc?mode=edit`
- Scroll down and add an URL or any string value to `Endpoints > URL`
- `Issuer` URL should get prefixed with specified URL
- Add `realm` input
- The realm value should be appended to both `Issuer` and `Auth endpoint`
Changed auto-generated URL structure:
- From: `https://my.url/auth/realms/my-realm`
- To: `https://my.url/realms/my-realm`
- Removed `console.log()` from `shell/edit/provisioning.cattle.io.cluster/__tests__/Advanced.test.ts`
- Added unit tests for the input autocompletion
https://github.com/user-attachments/assets/45cdfb8f-ca0e-47a2-91e0-52469592e35a
=> [BUG] Keycloak generated Auth and Issuer endpoints are using outdated URL patterns

cypress/e2e/po/pages/explorer/coordination.k8s.io.lease.ts, cypress/e2e/tests/pages/explorer/more-resources/yaml/no-form-resource.spec.ts
Fixes https://github.com/rancher/dashboard/issues/5092
We add one e2e test to cover a case where we had a bug in the past around creating a new resource via yaml when the resource doesn't have a custom form.
None
None
=> Adding a test to ensure we can create resource without custom forms via yaml

shell/components/nav/Group.vue
Fixes https://github.com/rancher/dashboard/issues/11228
Adding one more level of indentation for our navigation elements.
Side navigation in explorer
Possibly something with the class `label` could have additional `padding-left` but I believe the scope is sufficiently narrow to avoid this.
=> Adding another indentation level in our navigation menu

shell/config/router/routes.js, shell/core/plugin-routes.ts, shell/core/plugins.js
Removing extension router logic that's no longer necessary with the bump of vue-router
Fixes #11876
There shouldn't be any logical changes.
It's now possible to use the vue-router addRoute instead of replacing the matcher to add/override routes. This simplifies the routing logic that happens extensions add routes.
Global extensions, cluster extensions and Harvester
Global extensions, cluster extensions and Harvester
https://github.com/user-attachments/assets/e8e3dd56-dda3-4038-8945-66aaefaf8b3c
=> Removing extension router logic that's no longer necessary with the bump of vue-router

shell/edit/provisioning.cattle.io.cluster/tabs/etcd/index.vue
Fixes: https://github.com/rancher/dashboard/issues/13497
https://jira.suse.com/browse/SURE-9817
Properly handle missing object data
Message me if you'd like creds to an instance that's already done the upgrade cycle.
1. Create a rancher v2.9-head instance
2. Create a cluster with a k8s version `v1.27.16+rke2r2` (DO, EC2 providers work)
3. Upgrade the rancher instance to head
4. Edit the cluster and then click on the etcd tab (it should now render)
i. Without my changes I had to click between tabs a few times and wait before the etcd tab would stop rendering.
=> Better handling of rendering the etcd page when a no longer supported k8s version is used

shell/models/__tests__/logging.banzaicloud.io.flow.test.ts, shell/models/logging.banzaicloud.io.flow.js
Fixes https://github.com/rancher/dashboard/issues/13743 (based on https://github.com/rancher/dashboard/pull/13744, credits to @skanakal for finding the problem and solution)
@skanakal I found it easier to reproduce your fix on my fork and work on the unit test from it. Thank you for the fix 🙇 
The issue is that [get outputs()](https://github.com/rancher/dashboard/blob/master/shell/models/logging.banzaicloud.io.flow.js#L64) is fetching outputs based only on their names `(output.name)`. Since multiple outputs can share the same name but exist in different namespaces, the filtering logic does not distinguish between outputs from different namespaces.
- Also add unit test
1. Install rancher-logging latest
2. Create multiple logging outputs with the same name (e.g., "output-file") in several …
=> Ensure correct Output col in Flow list view by filtering ns

shell/assets/translations/en-us.yaml, shell/chart/monitoring/prometheus/index.vue, shell/components/form/MatchExpressions.vue, shell/detail/__tests__/autoscaling.horizontalpodautoscaler.test.ts, shell/detail/autoscaling.horizontalpodautoscaler/index.vue, shell/edit/autoscaling.horizontalpodautoscaler/metric-identifier.vue, shell/edit/fleet.cattle.io.clustergroup.vue, shell/edit/provisioning.cattle.io.cluster/tabs/Advanced.vue
Fixes #12699 
Our HPA detail page couldn't handle the format of non-resource metrics:
```
metrics:
- type: Resource
resource:
name: cpu
target:
type: Utilization
averageUtilization: 50
- type: Pods
pods:
metric:
name: packets-per-second
target:
type: AverageValue
averageValue: 1k
- type: Object
object:
metric:
name: requests-per-second
describedObject:
apiVersion: networking.k8s.io/v1
kind: Ingress
name: main-route
target:
type: Value
value: 10k
```
- Fixed how we process metrics
- Fixed metric selector header being shown when no metrics are visible ( HorizontalPodAutoscaler -> Config)
- Moved headers to slots in a few components
Local -> Service discovery -> HorizontalPodAutoscalers
- Create an HPA with metrics that include an external metric or any other non-resource metric
- HPA-> …
=> [FIX] Adjusted HPA to handle non-resource metrics

pkg/harvester-manager/edit/harvesterhci.io.management.cluster.vue
Fixes # https://github.com/harvester/harvester/issues/7809
Fix missing error banner in edit harvesterhci.io.management.cluster when input invalid cluster name : `1.5.0`.
https://github.com/user-attachments/assets/7360675e-ec9d-446c-930d-683bf8ca63ff
=> fix: missing error banner in edit harvesterhci.io.management.cluster

docusaurus/docs/extensions/catalog.mdx, docusaurus/docusaurus.config.js, docusaurus/extensionSidebar.js, docusaurus/extensions/catalog/partner/cloudcasa.yaml, docusaurus/extensions/catalog/partner/kamaji.yaml, docusaurus/extensions/catalog/partner/nutanix.yaml, docusaurus/extensions/catalog/prime/elemental.yaml, docusaurus/extensions/catalog/prime/kubewarden.yaml, docusaurus/extensions/catalog/prime/neuvector.yaml, docusaurus/extensions/catalog/prime/observability.yaml, docusaurus/plugins/catalog/Catalog.tsx, docusaurus/plugins/catalog/CatalogCard.tsx, docusaurus/plugins/catalog/index.js, docusaurus/plugins/catalog/styles.css
Fixes #13512
The goal here is to have a new page as part of the extensions documentation - https://extensions.rancher.io/ - where we can list extensions and provide a mechanism for the community to share details of their extensions.
This PR adds an extensions catalog page to our extension docs.
Each extension is declared in a yaml file and a custom docusaurus plugin generates an index from these.
A custom mdx page renders the catalog page.
This also includes information on how users can submit their extensions to the catalog.
This PR also populates the initial catalog based on Prime and Partner extensions.
Example of the generated page: 
[ExtensionsCatalog.pdf](https://github.com/user-attachments/files/19250652/ExtensionsCatalog.pdf)
=> Add extension catalog page and initial contents

shell/assets/translations/en-us.yaml, shell/components/SortableTable/THead.vue
Fixes #8191 
- add missing alt to sorting icons
- Other sorting items had been addressed in https://github.com/rancher/dashboard/pull/12966
=> add missing alt to sorting icons

cypress/jenkins/Jenkinsfile, cypress/jenkins/cypress.sh, cypress/jenkins/init.sh, package.json
Adds ability to run visual tests on CI and send build to percy dashboard.
=> Jenkins percy configuration

shell/components/nav/Type.vue
Fixes #13820 
- add missing `aria-current` to nav links https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-current
=> add missing aria-current to nav links

shell/components/LocaleSelector.vue, shell/components/form/Select.vue
Fixes #13816 
- add missing lang HTML attribute to `LocaleSelector`
=> add missing lang HTML attribute to locale selector

shell/components/ButtonGroup.vue
Fixes #13814 
- add missing `aria-pressed` state to `ButtonGroup`
=> add missing aria-pressed state

shell/assets/styles/themes/_light.scss, shell/assets/styles/themes/_suse.scss, shell/utils/color.js
This ensures that the keyboard focus color is consistent with the theme by using HSL() for programmatic color control of keyboard focus. SASS variables don't help in scenarios where the theme can be modified.
Fixes #13566 
- Add css variable to control the color of keyboard focus
- Use HSL() to for programmatic color control of keyboard focus
- Update brand css variables
`shell/utils/color.js` appears to have a little quirk. Our themes darken primary color for `--primary-hover-bg`, but setting a custom color for branding will lighten the color instead. I added a line to override the keyboard focus so that it remains consistent.
Keyboard focus colors and themes:
- Default light
- Default dark
- Suse/prime
- Custom primary colors
NA
=> Set keyboard focus color for suse/prime theme

pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue, pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue
Fixes #13829
- fix missing `describedby` on `Checkbox` and `LabeledInput`
- update `LabeledInput` to only show either `cronHint` or `subLabel` (I don't both at the same time would work)
- work based on https://benmyers.dev/blog/aria-labels-and-descriptions/#providing-multiple-ids + https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-describedby
=> fix missing describedby on Checkbox and LabeledInput

shell/assets/translations/en-us.yaml, shell/components/SortableTable/index.vue, shell/components/nav/Jump.vue
Fixes #13835 
- fix unclear functionality for filter inputs for a11y
=> fix unclear functionality for filter inputs for a11y

shell/assets/translations/en-us.yaml, shell/components/SortableTable/index.vue
Fixes #8114 
- add missing aria labels and roles for pagination of sortable tables
=> add missing aria labels and roles for pagination of sortable tables

shell/assets/translations/en-us.yaml, shell/edit/auth/ldap/__tests__/config.test.ts, shell/edit/auth/ldap/config.vue
This reverts commit 85c31a40731652231cf51f6945a699bec04d3571.
Testing exposed that this feature requires all three attributes (`searchUsingServiceAccount` flag, plus separate credentials via `searchServiceAccountDistinguishedName` and `searchServiceAccountPassword`) to function properly.
Reverting this change will prevent confusion until a fix can be applied to make the feature functional.
- Revert commit 85c31a40731652231cf51f6945a699bec04d3571
See the original issue/PR for more context
- https://github.com/rancher/dashboard/issues/12871
- #13223
`searchUsingServiceAccount` field should be removed from config forms for openLDAP and freeIPA auth providers. 
Auth providers should successfully create with this field removed.
NA
=> [backport v2.11.0] Revert "Auth Providers: Add search_using_service_account field #13223"

shell/assets/translations/en-us.yaml, shell/edit/auth/ldap/__tests__/config.test.ts, shell/edit/auth/ldap/config.vue
This reverts commit 85c31a40731652231cf51f6945a699bec04d3571.
Testing exposed that this feature requires all three attributes (`searchUsingServiceAccount` flag, plus separate credentials via `searchServiceAccountDistinguishedName` and `searchServiceAccountPassword`) to function properly.
Reverting this change will prevent confusion until a fix can be applied to make the feature functional.
- Revert commit 85c31a40731652231cf51f6945a699bec04d3571
See the original issue/PR for more context
- https://github.com/rancher/dashboard/issues/12871
- #13223
`searchUsingServiceAccount` field should be removed from config forms for openLDAP and freeIPA auth providers. 
Auth providers should successfully create with this field removed.
NA
=> Revert "Auth Providers: Add search_using_service_account field #13223"

shell/core/types.ts, shell/package.json
Fixes #13858 
- fix missing types for `weightGroup` and `weightType`
- bump shell version
- advertised for extension developers as per https://extensions.rancher.io/extensions/next/api/nav/side-menu
=> fix missing types for weightGroup and weightType

shell/machine-config/__tests__/vmwarevsphere.test.ts, shell/machine-config/vmwarevsphere.vue
Fixes #12590 
We've updated networks to include MOID when creating a vSphere cluster, but for previously created clusters with a selected network we would still show the old network without MOID. This PR makes sure a correct network is selected for them by looking at the list of the available networks and finding a match.
- `syncNetworkValueForLegacyLabels` created to find a network match
-  unit test
For the dev env, you can checkout to a commit before the change we made to support moid(e.g. 614826f92b), and create a vsphere cluster while a network is selected. Then checkout to this PR and see that the issue is fixed.
=> Fix vSphere MOID not showing up for previously selected networks

.github/workflows/scripts/pr-gh-project.js
Fixes #13882
Tweak to script to only log PRs that fix the same issue as the PR being closed.
=> Minor fix to gh project automation script logging

shell/components/PromptRemove.vue, shell/dialog/DeactivateDriverDialog.vue, shell/dialog/GitRepoForceUpdateDialog.vue, shell/promptRemove/management.cattle.io.fleetworkspace.vue, shell/promptRemove/management.cattle.io.globalrole.vue, shell/promptRemove/management.cattle.io.project.vue, shell/promptRemove/management.cattle.io.roletemplate.vue, shell/promptRemove/pod.vue, shell/utils/__tests__/string.test.ts, shell/utils/string.js
=> Restore resourceNames util for extensions compatibility

pkg/rancher-components/src/components/Form/ToggleSwitch/ToggleSwitch.vue, pkg/rancher-components/src/components/RcDropdown/RcDropdown.vue, pkg/rancher-components/src/components/RcDropdown/RcDropdownMenu.vue, pkg/rancher-components/src/components/RcDropdown/RcDropdownTrigger.vue, shell/components/SortableTable/index.vue, shell/components/StatusBadge.vue
This reverts any Vue 3.5 features that might be used in Rancher Dashboard so that Rancher Shell can maintain compatibility with Rancher Dashboard v2.10/Vue 3.2. 
- Replace `useTemplateRef` with `ref` for Vue 3.2.47 compatibility of shell
- Replace Reactive Props Destructure with `withDefaults` macro
Several Vue 3.5 features that were added to Rancher Dashboard for v2.11 have caused backwards incompatibility issues with recent shell versions and Rancher Dashboard v2.10. Dashboard 2.10 still has a dependency on Vue 3.2.47. Therefore, any apis introduced for Vue 3.5 will throw an error when accessed in extensions that are loaded in Dashboard 2.10.
This was uncovered in the latest Harvester extension loaded on Rancher Dashboard 2.10. This change will need to be tested in a similar setup.
- …
=> Revert Vue 3.5 features added to dashboard to maintain compatibility with Vue 3.2

pkg/imported/components/CruImported.vue
We no properly reset the registry value if the enable checkbox is disabled
We now show both the networking and registry accordions in the detail config view
Fixes #13864
Fixes #13863
- A variable rename didn't include updating a watcher function
- I initially decided we didn't want to show the registry accordion based on the networking accordion but it looks like we want to show both.
Generic import cluster detail and edit pages
Generic import cluster detail and edit pages
Create:
Edit:
Detail:
=> Fixing two issues around generic import registries accordion

shell/pages/c/_cluster/apps/charts/chart.vue
Fixes #13911
Trivial fix - we aren't currently supporting maintainer info with the `url` - only those with the `email` field.
Add application collection to Rancher Manager.
Browse to any Application Collection chart and on the right hand side, observe that the link for the `SUSE LLC` maintainer is now a URL and clicking on it opens the SUSE Web site.
Previously, if you hovered on the link, you'd see the target was incorrectly `mailto:undefined`. 
- x ] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
=> Fix chart maintainer link to work with urls and emails

pkg/imported/components/CruImported.vue
Fixes #13778 
Hid accordions that should not be shown for RKE1 when editing or viewing config an imported RKE1 cluster.
- Import RKE1 cluster
- Go to edit
- Only Member roles and Labels and annotations accordions should be shown
- Go to View Config for that cluster
- Only Member roles and Labels and annotations accordions should be shown
other imported clusters
=> Hid Networking and Advanced accordions for RKE1 imported cluster

cypress/e2e/po/components/action-menu-shell.po.ts, cypress/e2e/po/pages/explorer/workloads-replicasets.po.ts, cypress/e2e/po/prompts/ResourceSearchDialog.po.ts, cypress/e2e/tests/pages/explorer2/workloads/replicasets.spec.ts, shell/models/workload.js
Fixes #13885
This PR removes the Rollback action for resource sets and adds an e2e test for this.
The fix is trivial - https://github.com/rancher/dashboard/pull/13915/files#diff-0543f2863aeb84f2e4f2d12196a7f8cb5c7ba9e06f11990b0a0f4cd27dbbe560R37-R40
The bulk of this PR is the new e2e test.
=> Remove rollback action from ReplicaSet resource

pkg/rancher-components/src/components/RcDropdown/RcDropdown.vue, pkg/rancher-components/src/components/RcDropdown/RcDropdownTrigger.vue, pkg/rancher-components/src/components/RcDropdown/useDropdownCollection.ts, pkg/rancher-components/src/components/RcDropdown/useDropdownContext.ts, shell/components/LocaleSelector.vue
This replaces the locale selector on the login page with the RcDropdown component.
Fixes #13486
- Replace locale selector on the login page with RcDropdown component
- Add ability to focus last item when pressing up on the keyboard after opening menu with the mouse
This is a fairly straightforward transfer of the custom dropdown menu to RcDropdown. I opted to use RcDropdown instead of the props-driven RcDropdownMenu component because the existing implementation requires less refactoring for the component-driven approach.
- Locale selector
- Locale selector
Pay attention to any accessibility enhancements that might have been previously made in recent PRs. We do not want to regress in these areas.
=> Replace locale selector on login page with RcDropdown component

cypress/e2e/po/pages/cluster-manager/cloud-credentials-create-aws.po.ts, cypress/e2e/po/pages/cluster-manager/cloud-credentials-create.po.ts, cypress/e2e/tests/pages/manager/cloud-credential.spec.ts, shell/cloud-credential/aws.vue, shell/edit/cloudcredential.vue
Fixes #13802
This one is frustrating, it's absolutely not obvious what the root problem is. I found a fix through trial and error to narrow the change down.
For some reason if you visit the page after selecting the subtype if you then make the form valid it causes an event/state change to propagate all the to the root of the app and forces a re-render. 
The issue stopped once I removed the wrapping element but that broke other aspects because inherrited attributes were overwriting expected values for props. I then narrowed this down to `done-params` being present ultimately fixed the behavior.
Looking at all references to `done-params` doesn't explain the fix. And just adding other attributes in it's place doesn't either.
Cloud credentials which have validation. Azure, AWS, and S3 …
=> Preventing the re-render of cloud credentials when validation takes place

jest.setup.js, shell/components/auth/__tests__/RoleDetailEdit.test.ts, shell/components/form/ArrayList.vue, shell/components/form/Command.vue, shell/components/form/EnvVars.vue, shell/components/form/HealthCheck.vue, shell/components/form/HookOption.vue, shell/components/form/LifecycleHooks.vue, shell/components/form/MatchExpressions.vue, shell/components/form/NameNsDescription.vue, shell/components/form/Networking.vue, shell/components/form/NodeAffinity.vue, shell/components/form/NodeScheduling.vue, shell/components/form/PodAffinity.vue, shell/components/form/Probe.vue, shell/components/form/ResourceQuota/Project.vue, shell/components/form/ResourceSelector.vue, shell/components/form/Security.vue, shell/components/form/ShellInput.vue, shell/components/form/Tolerations.vue, shell/components/form/ValueFromResource.vue, shell/components/form/WorkloadPorts.vue, shell/components/form/__tests__/ArrayList.test.ts, shell/components/form/__tests__/MatchExpressions.test.ts, shell/components/form/__tests__/NameNsDescription.test.ts, shell/components/form/__tests__/Probe.test.ts, shell/edit/__tests__/monitoring.coreos.com.prometheusrule.test.ts, shell/edit/logging.banzaicloud.io.output/__tests__/logging.banzaicloud.io.output.test.ts, shell/edit/persistentvolume/__tests__/persistentvolume.test.ts
This refactors form components that contain initialization logic in their data props so that they use patterns that are more idiomatic to Vue.
Fixes #13702 
🗒️ NOTE: I recommend reviewing this PR commit-by-commit to reduce the complexity of reviewing some larger changes. 
🗒️ NOTE: This is a large PR that touches many forms throughout Dashboard. I am open to splitting this into smaller PRs if we find that validating and testing these changes takes too much effort.
Some form components require a larger refactor than others because of watcher usage. Watchers will trigger when watched values are updated in the created hook; this is undesirable because this modifies component behavior on initial render, potentially introducing regressions in forms. Refactoring these components to use setup() …
=> Refactor form components so data prop no longer contains init logic

cypress/e2e/tests/pages/manager/gke-cluster-provisioning.spec.ts
Fixes https://github.com/rancher/qa-tasks/issues/1716 - but first this PR needs to be merged https://github.com/rancherlabs/corral-packages/pull/75
Fix decoding the secret of e2e GKE cluster provisioning test. It was being encoded twice. 
Also, it includes a temporary workaround while bug https://github.com/rancher/qa-tasks/issues/1717 is not fixed, which consists of a duplicate line of code that types the entire input string in the Service Account field when creating GKE cloud credential.
Running the `gke-cluster-provisioning.spec.ts` in Jenkins. Test is expected to pass
=> Fix Decoding secret of e2e GKE cluster provisioning test

pkg/harvester-manager/machine-config/harvester.vue
Fixes #13067 
Previously `cpuCount`, `memorySize` and `disk.size` fields were only get validated for having a value, but now their value should be at least `1`.
- Added `validatorMinimumField` to check for minimum value
- Replaced `validatorRequiredField` with `validatorMinimumField` for the mentioned fields
https://github.com/user-attachments/assets/b63729fd-9572-40c6-998c-a9d3da57b3d8
=> Update Harvester validation on cpu/memory/disk fields

cypress/e2e/po/pages/cluster-manager/cloud-credentials-create-aws.po.ts, cypress/e2e/po/pages/cluster-manager/cloud-credentials-create.po.ts, cypress/e2e/tests/pages/manager/cloud-credential.spec.ts, shell/cloud-credential/aws.vue, shell/edit/cloudcredential.vue
Fixes #13804
This one is frustrating, it's absolutely not obvious what the root problem is. I found a fix through trial and error to narrow the change down.
For some reason if you visit the page after selecting the subtype if you then make the form valid it causes an event/state change to propagate all the to the root of the app and forces a re-render. 
The issue stopped once I removed the wrapping element but that broke other aspects because inherrited attributes were overwriting expected values for props. I then narrowed this down to `done-params` being present ultimately fixed the behavior.
Looking at all references to `done-params` doesn't explain the fix. And just adding other attributes in it's place doesn't either.
Cloud credentials which have validation. Azure, AWS, and S3 …
=> [backport 2.11.1] Preventing the re-render of cloud credentials when validation takes place

shell/components/form/NameNsDescription.vue, shell/components/form/__tests__/NameNsDescription.test.ts
This sets a value for the name input in the NameNsDescription component when the `nameKey` prop is provided.
Fixes #13952 
- Properly sets the name input in the NameNsDescription component when the `nameKey` prop is provided
- Unit test the input
The root cause of this issue has to do with improperly accesses the `v` value after refactoring. 
- regression introduced in #13703
NameNsDescription should provide properly set values when: 
- navigating to Local Cluster Explorer => Projects/Namespaces
- click on "Group by Project"
- click on "Edit Config" in the dropdown menu next to "Create Namespace"
NA
NA
=> Set the value for the name input when `nameKey` is provided 

pkg/imported/components/CruImported.vue
We no properly reset the registry value if the enable checkbox is disabled
We now show both the networking and registry accordions in the detail config view
Fixes #13917
Fixes #13916
- A variable rename didn't include updating a watcher function
- I initially decided we didn't want to show the registry accordion based on the networking accordion but it looks like we want to show both.
Generic import cluster detail and edit pages
Generic import cluster detail and edit pages
Create:
Edit:
Detail:
=> [backport 2.11.1] Fixing two issues around generic import registries accordion

pkg/rancher-components/src/components/Form/Radio/RadioGroup.vue, shell/assets/styles/base/_basic.scss, shell/components/LandingPagePreference.vue
Fixes #13837
- fix grouping of `RadioGroup` with meaningful title/description
=> fix grouping of RadioGroup with meaningful title

shell/edit/auth/__tests__/oidc.test.ts, shell/edit/auth/oidc.vue, shell/edit/provisioning.cattle.io.cluster/__tests__/Advanced.test.ts
Fixes #13878
Backport PR: https://github.com/rancher/dashboard/pull/13767
Just cherry-picked.
=> [backport v2.11.1] [BUG] Keycloak generated Auth and Issuer endpoints are using outdated URL patterns

shell/assets/translations/en-us.yaml, shell/edit/auth/__tests__/oidc.test.ts, shell/edit/auth/oidc.vue, storybook/src/stories/Components/ArrayList.stories.ts, storybook/src/stories/Components/KeyValue.stories.ts
Fixes #13771
- Updated validation to prevent the described scenario
- Auth endpoint it's now required from the form
- Basic scopes are now required from the view, as they are equally added programmatically in the store
- Updated tooltip for the scopes
- Updated KeyValue Story while testing around a similar requirement
- Grouped existing tests
- Added test to ensure the save button is disabled (check the title, too much movement due grouping tests):
- `given missing required basic scopes`
- `given missing Auth endpoint URL`
https://github.com/user-attachments/assets/16229b9d-ca49-41eb-89b2-0746c18473a0
=> Auth Provider create/edit form can be saved with some mandatory fields in blank

shell/edit/auth/__tests__/oidc.test.ts, shell/edit/auth/oidc.vue
Fixes #11649
Manual testing required
=> fix(auth/oidc): reset issuer and auth endpoint if oidcUrls.url is empty

shell/server/har-file.js
Fixes #13934 
Improves the HAR file replay:
- Maps old operator-based URL for ui extensions to the built-in API
- Supports requests with the query string which contains `excludes` and 1 or more other query string parameters - previously only supported the `excludes` query string parameter
This makes is possible to use a HAR file created on an older version of Rancher (e.g. 2.8) with the latest code.
=> Improve handling of har files generated with older versions

shell/assets/translations/en-us.yaml, shell/edit/provisioning.cattle.io.cluster/tabs/etcd/index.vue
Fixes #13920
Someone noticed that this should only apply to S3 and the original issue called for that as well. I just missed that bit when implementing.
Now we conditionally show the S3 messaging when S3 is selected.
The etcd tab in cluster creation/editing for rke2
The etcd tab in cluster creation/editing for rke2
https://github.com/user-attachments/assets/1de747fd-022c-4e74-9972-330c6e147d94
=> Made the new s3 snapshot units/tooltip show when s3 is selected

shell/edit/auth/__tests__/oidc.test.ts, shell/edit/auth/oidc.vue
Fixes #13115
Backport of these PRs:
https://github.com/rancher/dashboard/pull/11650
https://github.com/rancher/dashboard/pull/13968
=> [backport v2.11.1] In Auth Provider Keycloak (OIDC) page, empty the issuer and the auth endpoint inputs if URL gets cleared in Generate mode

shell/assets/translations/en-us.yaml, shell/components/form/MatchExpressions.vue, shell/detail/__tests__/autoscaling.horizontalpodautoscaler.test.ts, shell/detail/autoscaling.horizontalpodautoscaler/index.vue, shell/edit/autoscaling.horizontalpodautoscaler/metric-identifier.vue
Fixes #13538 
Backport of https://github.com/rancher/dashboard/pull/13776
- Fixed how we process metrics
- Fixed metric selector header being shown when no metrics are visible ( HorizontalPodAutoscaler -> Config)
Local -> Service discovery -> HorizontalPodAutoscalers
Create an HPA with metrics that include an external metric or any other non-resource metric
HPA-> detail
All metrics should be displayed. No error should be thrown to the console
None
=> [2.11.1] Adjusted HPA to handle non-resource metrics

cypress/e2e/po/components/workloads/pod.po.ts, cypress/e2e/tests/pages/explorer2/workloads/pods.spec.ts, shell/edit/workload/index.vue, shell/edit/workload/mixins/workload.js
0c6eb6473d7809fb94576bd66c96c29f260f2090 introduced a change that moved the call to `selectContainer` out `data` and into the `created` hook. Before this change, any modifications made by invoking `selectContainer` would get overwritten by setting container in the data prop. `selectContainer` only needs to be invoked once on first render, and the changed method in `shell/edit/workload/index.vue` satisfies this requirement.
Fixes #13958 
- Remove call to `selectContainer` in `created` hook of `shell/edit/workload/mixins/workload.js`
This was only an issue for Pods, other forms like Deployments were not affected by this behavior. 
Workload creation: Pods, but also Deployments, Jobs, Daemonsets, etc..
Workload creation: Pods, but also Deployments, Jobs, Daemonsets, etc.. …
=> Workload Mixin: Remove call to `selectContainer` from `created` hook

cypress/e2e/po/pages/cluster-manager/cloud-credentials-create.po.ts, cypress/e2e/tests/pages/manager/cloud-credential.spec.ts, shell/edit/provisioning.cattle.io.cluster/SelectCredential.vue
Fixes #13802
Added the same changes we made in https://github.com/rancher/dashboard/pull/13921 to the SelectCredential.vue component
The create cloud credentials component on the create cluster page.
The create cloud credentials component on the create cluster page.
Demonstrated on the azure page because I had aws creds which would prevent me from seeing this component. You have to refresh on the provider page to reproduce without this change.
https://github.com/user-attachments/assets/9690b725-b990-43db-b533-6fa479719fb3
=> Fixing the focus loss issue of the cloud credentials creator on the create cluster pages

shell/assets/translations/en-us.yaml, shell/edit/provisioning.cattle.io.cluster/tabs/etcd/index.vue
Fixes #13943
Someone noticed that this should only apply to S3 and the original issue called for that as well. I just missed that bit when implementing.
Now we conditionally show the S3 messaging when S3 is selected.
The etcd tab in cluster creation/editing for rke2
The etcd tab in cluster creation/editing for rke2
https://github.com/user-attachments/assets/1de747fd-022c-4e74-9972-330c6e147d94
=> [backport 2.11.1] Made the new s3 snapshot units/tooltip show when s3 is selected

.github/workflows/close-stale-enhancement-requests.yaml
This is an effort to de-clutter our issues to make prioritization easier.
This PR will enable a dry-run only for testing.
Details:
- This will run ever 4 hours initially because we're rate limited on how many issues we can process at a time. This should change in the future.
- We will not close any issues that have the `JIRA` label because we won't want to close customer issues by accident.
- We will only close issues with the label `kind/enhancement`
- We will only close issues after 548 days or 1.5 years
- We will add the label `auto-close` so we can periodically look to see if someone has re-opened and updated on of these issues.
- We will add this message when closing `We're closing this enhancement because it hasn't been active nor has been prioritized in over 1.5 years. If this …
=> Adding a stale bot to close out `kind/enhancement` issues which haven't seen activity in more than a 1.5 years.

cypress/e2e/po/components/workloads/pod.po.ts, cypress/e2e/tests/pages/explorer2/workloads/pods.spec.ts, shell/edit/workload/index.vue, shell/edit/workload/mixins/workload.js
fixes #13971
Original PR body:
0c6eb6473d7809fb94576bd66c96c29f260f2090 introduced a change that moved the call to `selectContainer` out `data` and into the `created` hook. Before this change, any modifications made by invoking `selectContainer` would get overwritten by setting container in the data prop. `selectContainer` only needs to be invoked once on first render, and the changed method in `shell/edit/workload/index.vue` satisfies this requirement.
Fixes #13958 
- Remove call to `selectContainer` in `created` hook of `shell/edit/workload/mixins/workload.js`
This was only an issue for Pods, other forms like Deployments were not affected by this behavior. 
Workload creation: Pods, but also Deployments, Jobs, Daemonsets, etc..
Workload creation: Pods, but also Deployments, Jobs, …
=> [backport v2.10.5] Workload Mixin: Remove call to `selectContainer` from `created` hook

pkg/imported/components/CruImported.vue
Fixes #13798
Backport issue. Hid accordions that should not be shown for RKE1 when editing or viewing config an imported RKE1 cluster.
Import RKE1 cluster
Go to edit
Only Member roles and Labels and annotations accordions should be shown
Go to View Config for that cluster
Only Member roles and Labels and annotations accordions should be shown
None
=> [2.11] Hid Networking and Advanced accordions for RKE1 imported cluster

pkg/eks/components/CruEKS.vue
Fixes #11336 
This PR removes a workaround that was previously added to bypass some outdated backend validation. Since rancher now supports EKS clusters with exclusively self-managed nodes, users should be able to save EKS clusters without managed node groups defined (ie, no node groups configured in the form)
I have a 2.11-head setup with the requisite EKS clusters already available that others may borrow to expedite testing
1. Create an EKS cluster w/ self-managed nodes
2. Import the cluster into Rancher
3. Edit the cluster, but do not add node groups: you should be able to save the cluster successfully
4. Edit and add a node group
5. Edit again and attempt to remove the node group you added in step 4
6. Verify that the network request to update the cluster includes an empty array of …
=> Save EKS clusters with empty array of nodegroups

pkg/eks/components/CruEKS.vue
Backport of #13987 
Fixes #13682
=> [2.11.1] Save EKS clusters with empty array of nodegroups

cypress/e2e/po/pages/cluster-manager/cloud-credentials-create.po.ts, cypress/e2e/tests/pages/manager/cloud-credential.spec.ts, shell/edit/provisioning.cattle.io.cluster/SelectCredential.vue
Fixes #13804
Added the same changes we made in https://github.com/rancher/dashboard/pull/13921 to the SelectCredential.vue component
The create cloud credentials component on the create cluster page.
The create cloud credentials component on the create cluster page.
Demonstrated on the azure page because I had aws creds which would prevent me from seeing this component. You have to refresh on the provider page to reproduce without this change.
https://github.com/user-attachments/assets/9690b725-b990-43db-b533-6fa479719fb3
=> [backport-2.11] Fixing the focus loss issue of the cloud credentials creator on the create cluster pages

shell/machine-config/__tests__/vmwarevsphere.test.ts, shell/machine-config/vmwarevsphere.vue
Fix vSphere MOID not showing up for previously selected networks
Fixes #12683
=> Backport [2.11.1] -  vSphere MOID

shell/models/management.cattle.io.node.js
Fixes #11624 
Note my comment on the above issue - there are still problems with the kontainer cluster detail view, but they will be addressed in 2.12/when certain pagination work is ready
This PR updates the management node model to hide the 'scale down' action if the norman representation of the node doesn't have a 'scaledown' link defined. 
The management node scaledown action uses the `ScaleMachineDownDialog` component, which, in turn, tries to use a 'scaledown' norman action: https://github.com/rancher/dashboard/blob/master/shell/dialog/ScaleMachineDownDialog.vue#L80-L87 - so this change should be safe for all cluster types.
Kontainer driver cluster detail page should not show a 'scale down' action in the 'machine pools' tab
rke1 clusters should still show the 'scale down' action …
=> Hide the 'scale down' action on the kontainer driver cluster detail page

cypress/e2e/po/components/async-button.po.ts, cypress/e2e/tests/pages/global-settings/branding.spec.ts, shell/assets/styles/global/_button.scss, shell/components/AsyncButton.vue, shell/components/__tests__/AsyncButton.test.ts
Fixes #12793 
- update `AsyncButton` to fix problem with not being able to have to keyboard nav focus back to the element when performing an action triggered by it
The `branding.spec` test for `primary color` keeps failing because it asserts a slightly different rgb than expected. I can't find the exact root cause but it only happens sporadically while testing it locally. Original assertion is around `rgb(248, 13, 216)` while sometimes it gets `rgb(249, 63, 224)`. Retries for this test are not working properly because after the first fail, the `primary color` checked starts already as checked and makes subsequent retries always fail.
https://github.com/user-attachments/assets/28e0f0d8-f99e-4a9a-a264-7825adbe515b
=> update AsyncButton to fix problem with keyboard nav focus

shell/pages/diagnostic.vue
Fixes #11231
This PR updates the diagnostic page to fetch schema info for the clusters in addition to counts.
It then includes that in the report on screen and the download json.
Test the diagnostic page renders and that the download still works.
Diagnostic page now shows schema count for each cluster and shows the custom schemas for a given cluster:
=> Include schema info on the diagnostic view and download

shell/pages/home.vue
Fixes #10791
Simple fix to make sure cluster names on the home page don't overflow but are displayed truncated with ellipsis.
Manual test required, since this is a visual issue. 
Create a cluster with a long name and validate that on the home page, this is correctly displayed with ellipsis and does not overflow onto the text for the next column.
With this PR fix:
before:
=> Ensure long cluster names are truncated

shell/pages/c/_cluster/apps/charts/chart.vue
Fixes #13913
Backport of https://github.com/rancher/dashboard/pull/13912
Trivial fix - we aren't currently supporting maintainer info with the `url` - only those with the `email` field.
Add application collection to Rancher Manager.
Browse to any Application Collection chart and on the right hand side, observe that the link for the `SUSE LLC` maintainer is now a URL and clicking on it opens the SUSE Web site.
Previously, if you hovered on the link, you'd see the target was incorrectly `mailto:undefined`.
=> [backport v2.11.1] Fix chart maintainer link to work with urls and emails

shell/components/ExplorerMembers.vue
=> Backport [2.11.1] - Project members not showing up

shell/models/cloudcredential.js
Fixes #13186
- expiring / expired runs off of cc model's `expireData`
- if neither are true this used to return null
- this meant `shell/components/formatter/CloudCredExpired.vue` errored out, even if there as a expiration date that should show
- expired, expiring and cc with expiration date over 7 days away
=> Ensure all harvester expiring dates are shown

docusaurus/plugins/catalog/styles.css
Update for #13512
Small tweak to make the extensions catalog docs page responsive, so on small screens (e.g. phone), we use a single column to display the extensions.
Current page: https://extensions.rancher.io/extensions/next/catalog
=> Fix responsiveness for small screens for extensions catalog docs page

pkg/harvester-manager/machine-config/harvester.vue
Update Harvester validation on cpu/memory/disk fields
Fixes #13727
=> Backport [2.11.1] - Harvester negative values

pkg/harvester-manager/machine-config/harvester.vue
Update Harvester validation on cpu/memory/disk fields
Fixes #13868
=> Backport [2.10.5] - Harvester negative values

pkg/harvester-manager/machine-config/harvester.vue
Update Harvester validation on cpu/memory/disk fields
Fixes #13869
=> Backport [2.9.9] - Harvester negative values

shell/core/types.ts, shell/list/provisioning.cattle.io.cluster.vue, shell/pages/home.vue, shell/store/type-map.js
Fixes #14012
This PR adds configuration for the provisioning cluster resource to allow the `create` and `import` locations to be overridden by an extension.
This is then wired into the cluster list and home page views.
Extensions can change the locations - an example use case is where you might want a user to only be able to create or import a single cluster type - for example, adding this in a product file in an extension would only allow them to create/import EKS clusters:
```
export function init(plugin: any, store: any) {
const {configureType } = plugin.DSL(store, 'manager');
configureType('provisioning.cattle.io.cluster', {
custom: {
createLocation: (params: any) => {
return {
name:  'c-cluster-product-resource-create',
query: {
type: 'amazoneks'
},
params
}
},
importLocation: …
```
=> Allow cluster create and import locations to be overridden

pkg/imported/components/CruImported.vue, shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/edit/provisioning.cattle.io.cluster/tabs/AgentConfiguration.vue, shell/store/features.js, shell/utils/cluster.js
Fixes #13665
Fixed comments left from Scheduling customization feature
- Added comment indicating that if initSchedulingCustomization needs to be changed, we should do it in 2 files
- Made sure that if you create a cluster with scheduling customization enabled, then disable the feature, edit the cluster and disable scheduling customization, it won't disappear before save
- Added error catching for JSON parse
For rke2 and imported generic cluster:
1. Enable Scheduling customization feature
2. Create 2 clusters: one with scheduling customization checkbox checked and one with it unchecked
3. Disable feature
4. Go to edit clusters:
5. For the one created with SC unchecked, scheduling customization checkbox should not be visible
6. Fore the one with SC checked, scheduling customization section …
=> Fixed feedback left from scheduling customization feature

pkg/imported/components/CruImported.vue
Fixes #13798 
Removed Basics tab for imported RKE1 cluster
Import RKE1 cluster -> edit -> check that only 'Member roles' and 'Labels and annotations' tabs are visible
Make sure that Basics tab is still visible for :
- generic cluster import
- local non-RKE1 cluster
- editing imported non-RKE1 cluster
None
=> [2.11.1]Hid Basics tab for imported RKE1 cluster

cypress/e2e/po/pages/users-and-auth/roles.po.ts, cypress/e2e/po/side-bars/product-side-nav.po.ts, cypress/e2e/tests/navigation/side-nav/product-side-nav-highlighting.spec.ts, shell/components/nav/Group.vue, shell/components/nav/Type.vue, shell/config/router/routes.js
Fixes #10997
Fixes #11335
This PR improves the highlighting mechanism for the product side navigation to address a number of bugs where the navigation does not expand the appropriate group and/or does not highlight the appropriate navigation item:
1. Cluster and Project Members
2. Role Templates
3. Charts - Chart detail and Chart install pages
4. User retention settings
(1) and (2) are fixed by ensuring we ignore the # in the URL - these pages have tabs which places the tab name in the URL after the hash and previously we were doing an exact URL match. Now we ignore the shebang
(3) Is caused by simply not knowing the parent navigation item - this is fixed by placing the routes in a group, as children of a base route and updating the active check logic to look at the parent route where …
=> Ensure product-level navigation highlights the correct item

shell/components/ExplorerProjectsNamespaces.vue, shell/components/SortableTable/index.vue, shell/composables/useFeatureFlag.ts, shell/composables/useRuntimeFlag.ts
This replaces the grouped table actions in the projects namespaces explorer with the new dropdown menu.
Fixes #13938 
- Create a `useFeatureFlag` composable for sharing feature flags across components
- Replace the grouped table actions with the new dropdown menu component
- This is behind a feature flag to maintain Rancher Shell backwards compatibility with Rancher 2.10
- Projects/Namespaces should show the new dropdown menu 
- Menu options should be the same as they were before
- Styles and spacing when working with the new component
=> Replace table group actions with new dropdown component

shell/components/form/EnvVars.vue
Fixes #14071
From the UI, it visually removed { name: 'y', value: 'z' } (the last row) — not { name: 'c', value: 'd' } which data shows was removed.
Even though the method removed the correct item from the array, Vue uses the key value (:key="i") to track DOM elements, and seems here the issue arises...
Deployment environment variables.
Anywhere EnvVars are used.
=> EnvVars Removal Fix

pkg/imported/components/CruImported.vue
Fixes #13778 
Removed basics tab for imported RKE1 cluster
Import RKE1 cluster -> edit -> check that only 'Member roles' and 'Labels and annotations' tabs are visible
Make sure that Basics tab is still visible for :
- generic cluster import
- local non-RKE1 cluster
- editing imported non-RKE1 cluster
None
=> Hid Basics tab for imported RKE1 cluster

shell/components/form/EnvVars.vue
Fixes #14097
From the UI, it visually removed { name: 'y', value: 'z' } (the last row) — not { name: 'c', value: 'd' } which data shows was removed.
Even though the method removed the correct item from the array, Vue uses the key value (:key="i") to track DOM elements, and seems here the issue arises...
Deployment environment variables.
Anywhere EnvVars are used.
=> [backport 2.10.5] EnvVars Removal Fix

shell/components/form/EnvVars.vue
Fixes #14096
From the UI, it visually removed { name: 'y', value: 'z' } (the last row) — not { name: 'c', value: 'd' } which data shows was removed.
Even though the method removed the correct item from the array, Vue uses the key value (:key="i") to track DOM elements, and seems here the issue arises...
Deployment environment variables.
Anywhere EnvVars are used.
=> [backport 2.11.1] EnvVars Removal Fix

shell/components/DisableAuthProviderModal.vue, shell/components/ModalWithCard.vue, shell/components/MoveModal.vue, shell/components/form/SSHKnownHosts/KnownHostsEditDialog.vue, shell/components/form/SSHKnownHosts/__tests__/KnownHostsEditDialog.test.ts, shell/components/form/SSHKnownHosts/index.vue, shell/components/form/__tests__/SSHKnownHosts.test.ts
Fixes #13901 
Fixes #13902 
Fixes #13903 
Fixes #13909 
- Fix focus trap for `DisableAuthProviderModal` modal
- Fix focus trap for `ModalWithCard` modal
- Fix focus trap for `MoveModal` modal
- Fix focus trap for `KnowHostsEditDialog` modal + style and aria related fixes
- Disable focus trap for units tests in `KnowHostsEditDialog.test.ts` and `SSHKnowHosts.test.ts`
Had to disable focus trap for units tests in `KnowHostsEditDialog.test.ts` and `SSHKnowHosts.test.ts` since I couldn't really fix the render issues that prevent the focus trap from finding an assignable target at activation-time.
- To test the `DisableAuthProviderModal` modal you'll need to enable an auth provider like OpenLDAP (check internal guide), then when disabling it the modal is triggered
- To test the `ModalWithCard` …
=> fix focus trap in various modals

shell/assets/translations/en-us.yaml, shell/components/ResourceTable.vue, shell/detail/provisioning.cattle.io.cluster.vue
Fixes #13627
- Provide a way to override list grouping options at component level (ResourceTable)
- Explicitly supply grouping for cluster detail view rke1 pool and rke2 machine deployment lists
- Previously only the groupBy option could be supplied (the property to group on), everything else came from the product config for the resource
- product level config for group options only supplemented them, they did not replace
- the pool/machine deployment lists needed to replace group options
- create an rke1 cluster with multiple pools. go to the detail view. see that the `Machine Pool` table has group by options for flat list and pool
- create an rke2 cluster with multiple pools. go to the detail view. see that the `Machine Pool` table has group by options for flat list and pool
- group by …
=> Show group by buttons in cluster detail RKE1 Pool and RKE2 MachineDeployment lists

pkg/rancher-components/src/components/Form/ToggleSwitch/ToggleSwitch.test.ts, pkg/rancher-components/src/components/Form/ToggleSwitch/ToggleSwitch.vue
#13880 introduced a regression that caused the ToggleSwitch to no longer apply focus styles. The update from `useTemplateRef` to `ref`[^1] required that the ref be returned from `setup()`:
[^1]: https://vuejs.org/guide/essentials/template-refs
> If not using <script setup>, make sure to also return the ref from setup():
Adding return statements for the refs resolves this error. A similar change was made to `shell/components/SortableTable/index.vue` in the aforementioned PR, but the same change was not applied to ToggleSwitch.
Fixes #13566 
- Add a return statement for refs in ToggleSwitch.vue
- Add unit tests to assert that focus styles are applied when ToggleSwitch receives focus
- The update from `useTemplateRef` to `ref`[^1] required that the ref be returned from `setup()`
- …
=> Fix issue where ToggleSwitch didn't apply focus styles

cypress/e2e/tests/pages/extensions/kubewarden.spec.ts
There's an issue with the Kubewarden e2e tests, see example [run here](https://github.com/rancher/dashboard/actions/runs/14451677709/job/40528431300#step:8:130).
The side-menu navigation item name has been updated from "Kubewarden" to "Admission Policy Management". The PR with said change: https://github.com/rancher/kubewarden-ui/pull/1141
This updates the side-menu navigation item entry lookup.
=> Update Kubewarden side-menu item name

shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #13930 
Taking into account the negative number when assigning color to the machine pool chips.
You need to manually type negative numbers in order to test this.
=> Machine Pool Chips Color for Negative Numbers

pkg/harvester-manager/list/harvesterhci.io.management.cluster.vue
Fixes # https://github.com/harvester/harvester/issues/8054
Disable `Manage` button in virt manage page for non-support harvester version
We will backport to 2.11.1 once this PR merged.
**Disabled**
https://github.com/user-attachments/assets/354e18db-8761-44f0-ac95-94ac7476e6c4
**Enabled**
https://github.com/user-attachments/assets/c2b70360-47e1-4f98-b291-60086e7fb4d1
=> Disable manage button in virt manage page for non-supported harvester version

shell/components/AppModal.vue, shell/components/PromptModal.vue, shell/composables/focusTrap.ts
Fixes #13905
- Fix focus trap for `PromptModal` component
- Given the architecture of the component we need to adjust the type of focus trap used in `AppModal` because when `AppModal` is rendered the generic component inside the `default` slot isn't rendered yet
- Go to `Fleet` and create a `GitRepo`. Then just go Fleet `GitRepo` table row actions `Force Update`
https://github.com/user-attachments/assets/97853244-72d0-4822-851c-3d43194e90a5
=> fix focus trap for `PromptModal`component

cypress/e2e/po/pages/explorer/workloads/workloads.po.ts, cypress/e2e/tests/pages/explorer2/workloads/deployments.spec.ts, shell/components/form/EnvVars.vue, shell/components/form/ValueFromResource.vue
Removing some some extra `toRef` usages that seemed to be causing some issues for our deployment EnvVars component.
Fixes #14068
I found this issue when looking at https://github.com/rancher/dashboard/issues/14071#event-17211287597. It would render objects in the EnvVars component by default.
https://github.com/user-attachments/assets/77665fc1-a8e8-4bbe-9833-32880476c200
Deployment EnvVars component.
Anywhere there's EnvVars
=> Removing some some extra `toRef` usages that seemed to be causing some issues for our deployment EnvVars component.

shell/components/nav/TopLevelMenu.vue
This change removes warnings that were printed to the console when hovering over primary navigation items. The `popperOptions` prop was removed from floating-vue[^1] and hasn't done anything since we migrated to Vue3.
[^1]: https://floating-vue.starpad.dev/migration/migration-from-v3#removed-props
- Remove deleted `popperOptions` prop from the return value of `getTooltipConfig()`
- The `popperOptions` prop was removed from floating-vue[^1] and hasn't done anything since we migrated to Vue3
- Primary navigation
- Primary navigation
=> Remove deleted props from tooltips

shell/pages/auth/login.vue, shell/pages/auth/verify.vue, shell/pages/c/_cluster/apps/charts/install.vue, shell/pages/c/_cluster/auth/config/index.vue, shell/pages/c/_cluster/explorer/EventsTable.vue, shell/pages/c/_cluster/explorer/index.vue, shell/pages/c/_cluster/monitoring/monitor/_namespace/_id.vue, shell/pages/c/_cluster/monitoring/monitor/create.vue, shell/pages/c/_cluster/monitoring/route-receiver/_id.vue, shell/pages/c/_cluster/monitoring/route-receiver/create.vue, shell/pages/c/_cluster/uiplugins/CatalogList/index.vue, shell/pages/diagnostic.vue, shell/pages/fail-whale.vue
This refactors pages that contain initialization logic in their data props so that they use patterns that are more idiomatic to Vue.
Fixes #13670 
This moves data initialization into the created hook for page components that contain complex logic in their data prop.
Each of these cases map quite nicely to the created hook. 
- Each page affected by this PR
- Pages affect by this PR
- Cluster counts[^1]
[^1]: https://github.com/rancher/dashboard/pull/13672#discussion_r1988721878
NA
=> Refactor pages so data prop no longer contains init logic

cypress/e2e/tests/pages/extensions/kubewarden.spec.ts
Backport of #14127 
There's an issue with the Kubewarden e2e tests, see example [run here](https://github.com/rancher/dashboard/actions/runs/14451677709/job/40528431300#step:8:130).
The side-menu navigation item name has been updated from "Kubewarden" to "Admission Policy Management". The PR with said change: https://github.com/rancher/kubewarden-ui/pull/1141
This updates the side-menu navigation item entry lookup.
=> [Backport 2.11] Update Kubewarden side-menu item name

pkg/harvester-manager/list/harvesterhci.io.management.cluster.vue
Fixes # https://github.com/harvester/harvester/issues/8054
Backport PR from https://github.com/rancher/dashboard/pull/14118 .
=> [Backport 2.11] Disable manage button in virt manage page for non-support harvester cluster

cypress/e2e/po/components/sortable-table.po.ts, pkg/rancher-components/src/components/RcDropdown/RcDropdown.vue, pkg/rancher-components/src/components/RcDropdown/RcDropdownItem.vue, shell/components/ActionDropdownShell.vue, shell/components/SortableTable/actions.js, shell/components/SortableTable/index.vue
This replaces the ActionDropdown implementation with one that uses the new dropdown component.
Fixes #13196 
- Create new `ActionDropdownShell.vue` component
- Replace `ActionDropdown` with `ActionDropdownShell`
We keep the two components because we need to support Rancher v2.10 in extensions. We can remove the `ActionDropdown` implementation after we drop support for Rancher v2.10.
Bulk action menus throughout dashboard should render the same options. All options should work the same as before.
Action menus used throughout dashboard. Clicking on items might not work as expected. Items might not render when they should.
=> Replace ActionDropdown with RcDropdown

cypress/e2e/po/components/action-menu.po.ts, cypress/e2e/tests/pages/users-and-auth/roles.spec.ts, pkg/rancher-components/src/components/RcButton/RcButton.vue, pkg/rancher-components/src/components/RcButton/types.ts, shell/components/ResourceDetail/Masthead.vue, shell/components/ResourceDetail/__tests__/Masthead.test.ts
This replaces the dropdown used in the header of the detail pages with the new dropdown component.
Fixes #13595 
- Replace actions in detail header with RcDropdown
- Update unit tests
We need to keep the old implementation around for shell so that extensions will continue to work in Rancher 2.10.
Actions on Details pages should render the same menu options as before. 
Actions on Details pages.
=> Replace actions in detail header with RcDropdown

shell/components/GrowlManager.vue, shell/components/ModalManager.vue, shell/components/SlideInPanelManager.vue, shell/components/__tests__/ModalManager.spec.ts, shell/components/__tests__/SlideInPanelManager.spec.ts, shell/components/templates/default.vue, shell/components/templates/home.vue, shell/components/templates/plain.vue, shell/config/store.js, shell/plugins/internal-api/shell/shell.api.ts, shell/public/index.html, shell/store/modal.ts, shell/store/slideInPanel.ts, shell/types/internal-api/shell/growl.d.ts, shell/types/internal-api/shell/modal.d.ts, shell/types/internal-api/shell/slideIn.d.ts, shell/types/vue-shim.d.ts
Related #12705 
Follow on #13839
Follow-on to the previous PR, this introduces two new components (`ModalManager` and `SlideInPanelManager`) and a new `ShellApi` (`$shell`). These additions enable programmatic control of modals, notifications, and slide-in panels through a unified API.
- Introduced a new internal API (`shell.api.ts`) that extends `BaseApi` and provides three methods:
- `growl`: Dispatches growl notifications via Vuex.
- `modal`: Opens modals by committing to the `modal` store module.
- `slideInPanel`: Opens a slide-in panel via the `slideInPanel` store module.
- `ModalManager` is a new component that listens to the `modal` store module to render dynamic modals.
- `SlideInPanelManager` is a new component that listens to the `slideInPanel` store module and renders a …
=> Initial `$shell` api - add `ModalManager` and `SlideInPanelManager`

shell/edit/cloudcredential.vue, shell/edit/provisioning.cattle.io.cluster/SelectCredential.vue
Fixes #13802
I reverted the `done-param` changes, I still have no idea why those functioned. 
I was able to trace what was causing the re-renders further and it seems to be caused by re-computing the component that we wanted to render even if that component didn't change. We now manually compute these values which prevents the re-render from occurring when the form input becomes valid.
Cloud credentials create pages, hosted providers create credentials  section, node provisioned cluster create credentials section.
Anywhere with creating/selecting credentials.
=> Replace the done param fix and changed how we render the credential dynamic components

cypress/e2e/po/pages/fleet/gitrepo-create.po.ts, cypress/e2e/tests/pages/fleet/gitrepo.spec.ts, package.json, pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue, pkg/rancher-components/src/components/LabeledTooltip/LabeledTooltip.vue, yarn.lock
Adds visual test coverage to git repo banners:
https://github.com/rancher/qa-tasks/issues/1679
=> adds visual test to fleet icon messages

shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/utils/object.js
Fixes #12418 
We had to revert the previous fix for the issue since it caused a regression. This PR addresses the issue again without causing a regression.
The reason behind the regression was mutating the original object when merging the default values with the user's current values. Now, by passing an empty object as the first argument to the Lodash's `mergeWith` function, we clone the object so the original object doesn't get mutated anymore.
We have unit tests for the helper function in `shell/utils/__tests__/object.test.ts`, but a manual test should be done
We need to re-test [this issue](https://github.com/rancher/dashboard/issues/13768)
https://github.com/user-attachments/assets/369dafe6-7761-4c4f-8c53-a74ef6e44329
=> Fix RKE2 Addon Config Values Persistency

shell/config/uiplugins.js, shell/scripts/extension/bundle, shell/scripts/extension/helm/charts/ui-plugin-server/templates/cr.yaml, shell/scripts/extension/helm/charts/ui-plugin-server/values.yaml, shell/scripts/extension/helmpatch, shell/scripts/extension/publish
Fixes #13200 
> **Note:**
> I will provide a custom image of `rancher/rancher` which includes the functionality for the new CRD for a UIPlugin resource.
This PR introduces support for compressed UI plugin endpoints and enhances Helm chart configuration to dynamically set plugin endpoints based on the build environment (GitHub or ECI).
- Added validation for compressedEndpoint alongside endpoint in plugin resource checks.
- Updated Helm charts to configure endpoint and compressedEndpoint via values, allowing dynamic URL generation.
- Refactored the helmpatch script to automate endpoint configuration for GitHub and container builds.
- Added .tgz packaging for extensions to support compressed plugin delivery.
- Removed manual Helm chart patching in favor of environment-driven configuration. …
=> Incorporate compressedEndpoint property into extension charts

cypress/e2e/tests/pages/users-and-auth/users.spec.ts, shell/assets/translations/en-us.yaml, shell/components/GlobalRoleBindings.vue, shell/components/ResourceDetail/index.vue, shell/edit/management.cattle.io.user.vue
This emits  an `update:mode` event that sets to mode to "edit" and refreshes all resource-related variables when the `updateRoles()` method fails during user creation. This provides an opportunity for users to correct mistakes while still staying in the "Create User" context.
Fixes #13539 
- Switch mode to "edit" if the `updateRoles()` method fails during user creation
- Add a user readable error message if an escalation error is raised
An alternate approach that explored navigating to an edit route was explored, but this required re-rendering the entire form and would eliminate the error message; additional state to persist the error messages would be required and I found that requirement to be more complex than the approach taken here.
User Creation: See details in the associated issue. …
=> Enter edit mode if updating roles fails during user creation

cypress/e2e/po/pages/explorer/workloads/workloads.po.ts, cypress/e2e/tests/components/yaml-editor.spec.ts, shell/assets/styles/base/_helpers.scss, shell/components/SortableTable/THead.vue
Fixes #7269 
Added a new CSS helper class for disabling word breaks on texts using `white-space: nowrap;`.
=> Fix table headers word break

cypress/e2e/tests/pages/manager/kontainer-drivers.spec.ts
The Tencent TKE kontainer driver has been removed - see https://github.com/rancher/rancher/issues/48759
This PR updates an e2e test that referenced the TKE driver to use LKE instead.
=> update kontainer driver deactivation test to use LKE driver

pkg/aks/components/Config.vue, pkg/aks/components/__tests__/Config.test.ts, pkg/aks/l10n/en-us.yaml
Fixes  https://github.com/rancher/dashboard/issues/11884
filters the available versions to only include versions that are:
- The same minor version as originalVersion
- OR Upgrades to one version above
- Create AKS cluster from Rancher UI and select lowest supported k8s version
- Upgrade version to highest supported version
=> AKS-Allow version upgrade only from current version to > 1 minor version

shell/components/SortableTable/selection.js
This removes right-click context menus from tables. Items in the context menu should be accessible via the overflow menu in tables.
Fixes #14154 
- remove right-click context menus from tables
Right-click context menus were initially implemented to provide quick access to table-related actions. Review of the context menus indicates that these menus are not intuitive and are often overlooked. This lack of discoverability impacts user experience, especially for users who rely on keyboard navigation or screen readers.
Tables used throughout Rancher Dashboard
There might be tables that can have a right-click context menu without also having the overflow button for the action menu. These instances will need to be addressed if they are encountered.
NA
=> Remove right-click context menu from tables

shell/edit/cloudcredential.vue, shell/edit/provisioning.cattle.io.cluster/SelectCredential.vue
Fixes #13804
Original pr https://github.com/rancher/dashboard/pull/14095
I reverted the `done-param` changes, I still have no idea why those functioned. 
I was able to trace what was causing the re-renders further and it seems to be caused by re-computing the component that we wanted to render even if that component didn't change. We now manually compute these values which prevents the re-render from occurring when the form input becomes valid.
Cloud credentials create pages, hosted providers create credentials  section, node provisioned cluster create credentials section.
Anywhere with creating/selecting credentials.
=> [2.11.2] Replace the done param fix and changed how we render the credential dynamic components

pkg/eks/components/CruEKS.vue, pkg/eks/components/NodeGroup.vue, pkg/eks/components/__tests__/NodeGroup.test.ts, pkg/eks/types/aws-sdk.d.ts
Fixes #14062
Backport. Added error listener to NodeGroups in EKS. This ensures we don't swallow the errors that happen while fetching LaunchTemplate info
EKS creation and edit:
Force a network error while loading launchTemplate versions. (or programmatically throw an error inside fetchLaunchTemplateVersionInfo)
Verify that the error is displayed
None
=> [2.10.6] Added error listener to NodeGroups in EKS

pkg/eks/components/CruEKS.vue, pkg/eks/components/NodeGroup.vue, pkg/eks/components/__tests__/NodeGroup.test.ts, pkg/eks/types/aws-sdk.d.ts
Fixes #14061
Backport. Added error listener to NodeGroups in EKS. This ensures we don't swallow the errors that happen while fetching LaunchTemplate info
EKS creation and edit:
Force a network error while loading launchTemplate versions. (or programmatically throw an error inside fetchLaunchTemplateVersionInfo)
Verify that the error is displayed
None
=> [2.11.2] Added error listener to NodeGroups in EKS

cypress/e2e/tests/pages/generic/home.spec.ts
Increasing visual test coverage with Percy on dashboard home page.
=> add visual check to clusters dashboard page

.github/workflows/close-stale-enhancement-requests.yaml
I verified that our criteria is respected and we don't get erroneous closing. Right now the bot is actually too conservative.
Because we update labels, milestones etc practically none of our issues are considered stale. For the time being I marked everything that's older than 1.5 years as stale manually which will allow this bot to close them given our other criteria and leave the comment.
There's 3 options to allow this bot to run:
- We can manually mark things as stale periodically and this will run
- We can avoid updating issues unless we intend on actually prioritizing them
- We can use the `ignore-updates` option but this would also ignore comments. https://github.com/actions/stale?tab=readme-ov-file#ignore-updates . _(I'm in favor of this option since we welcome the users to re-open …
=> Enabling stalebot

shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/pages/c/_cluster/apps/charts/install.vue, shell/utils/__tests__/object.test.ts, shell/utils/object.js
Fixes #13980 
Changes to merge behavior so that user supplied values overwrite default values when merging. The lodash merge operation merges object properties recursively, meaning that any keys in the left-most object will remain present. The customizer function works to overwrite any duplicate properties present in the user values.
- Updates merge behavior so that userValues overwrite default values
I considered using lodash `assign`, but that behaves in such a way that the user values would completely pave over any and all default values. Using `mergeWith` with the spread operator for objects allows us to preserve existing default properties while overwriting and preserving user provided keys as they were provided.
See issues for test cases.
This only really updates the merging …
=> Overwrite default chart values with user supplied values

pkg/harvester-manager/list/harvesterhci.io.management.cluster.vue, shell/components/SortableTable/paging.js
Fixes #14179
- We want to keep 5 as rows limit to leave some extra space below to the table for the extensions messages and use the value from 'Table rows per Page' preference when there are no messages.
[Screencast from 2025-04-30 11-20-36.webm](https://github.com/user-attachments/assets/939c3e9b-3b96-46d5-b21a-7efb714a54e8)
=> Fix rows limit in Harvester clusters table

cypress/e2e/po/components/sortable-table.po.ts, cypress/e2e/tests/pages/charts/logging.spec.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1798
The CRD removal takes some time to reflect in the UI which was causing the logging test to fail. Fixed by conditionally waiting until it's gone.
=> fix logging chart test

shell/pages/c/_cluster/uiplugins/index.vue
Fixes #14080 
This PR updates the plugin index page to check for experimental and certified labels on the version of the extension shown in the card instead of checking if _any_ version of the extension has those labels.
You can test this using the capi ui extension.
1. Navigate to the extensions page, click the kebab menu in the upper right and select 'manage repositories'
2. Add a repository with the following settings:
Name: capi-ui
Target: http(s) URL to an index generated by Helm (default option)
Index URL: https://rancher.github.io/capi-ui-extension
3. Go back to the extensions page and check the 'available' tab
Result:
the capi ui extension should not have an 'experimental' label
=> only show experimental or certified labels on extensions if the latest version is experimental/certified

shell/components/auth/login/ldap.vue
Fixes #14235 
This prevents the default form submit behavior in `ldap.vue`.
- Add `@submit.prevent` to ldap login form
#13954 introduced a change to resolve issues with focus behavior when the async button component entered a disabled state. It turns out that the disabled attributed on the button was preventing the default submit behavior, and changing this reintroduced the default form submit behavior.
The recommended way to submit forms in vue is to utilize `@submit.prevent` to disable the default form submit behavior and define our own submit logic. We want to retain the changes made to async button so that keyboard focus remains consistent.
- OpenLDAP login
- NA
=> Prevent default form submit behavior for open ldap

cypress/e2e/tests/pages/explorer2/resource-search.spec.ts, shell/assets/translations/en-us.yaml, shell/components/nav/Group.vue, shell/components/nav/Jump.vue, shell/store/type-map.js
Fixes #12648
^ @richard-cox Well, partially fixes the issue above - does not support filtering on the shortNames - we don't have those on the schemas - we'd have to fetch the k8s schema info, which is a large amount of data, so I suggest we don't do this for now - with what we have, I think you can find what you are looking for.
Simple fix - if the human-readable label does not match, then we use the string `Human Label (resource name.resource group)` and search on that.
In addition, fixed a couple of small bugs:
- The group headers no longer receive focus, don't show hover styling and can't be clicked - previously, you could click on these and it would navigate under the dialog
- Added a header to the dialog and a short text line to make this feature slightly clearer
- Changed label and …
=> Resource Search: Add ability to search by group

shell/core/types.ts, shell/list/provisioning.cattle.io.cluster.vue, shell/pages/home.vue, shell/store/type-map.js
Fixes #14067 
Backport of https://github.com/rancher/dashboard/pull/14041 for 2.11.2.
This PR adds configuration for the provisioning cluster resource to allow the `create` and `import` locations to be overridden by an extension.
This is then wired into the cluster list and home page views.
Extensions can change the locations - an example use case is where you might want a user to only be able to create or import a single cluster type - for example, adding this in a product file in an extension would only allow them to create/import EKS clusters:
```
export function init(plugin: any, store: any) {
const {configureType } = plugin.DSL(store, 'manager');
configureType('provisioning.cattle.io.cluster', {
custom: {
createLocation: (params: any) => {
return {
name: …
```
=> [2.11.2] Allow cluster create and import locations to be overridden

shell/store/index.js
Fixes # https://github.com/harvester/harvester/issues/6841#issuecomment-2834527613
Port the same change from https://github.com/harvester/dashboard/pull/1236.
Subscribe rancher socket for harvester standalone UI that websocket can connect to `/v3/token` to get latest data update.
https://github.com/user-attachments/assets/bdda83c3-e6e9-413d-9793-2d7af1af69a6
=> Subscribe rancher socket for harvester standalone UI

pkg/rancher-components/src/components/Form/Checkbox/Checkbox.test.ts, pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue, pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.test.ts, pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue, pkg/rancher-components/src/components/Form/Radio/RadioButton.test.ts, pkg/rancher-components/src/components/Form/Radio/RadioButton.vue, pkg/rancher-components/src/components/Form/Radio/RadioGroup.test.ts, pkg/rancher-components/src/components/Form/Radio/RadioGroup.vue, shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml, shell/components/LandingPagePreference.vue, shell/components/form/BannerSettings.vue, shell/components/form/ColorInput.vue, shell/components/form/LabeledSelect.vue, shell/components/form/NotificationSettings.vue, shell/components/form/__tests__/ColorInput.test.ts, shell/components/form/__tests__/LabeledSelect.test.ts, shell/pages/c/_cluster/settings/banners.vue
Fixes #14092 
- Fixes the settings area for `banners` in order to improve context of screen reader output for the UI elements involved
- Adds unit tests related to `a11y`
- Some of these fixes might differ in their pattern because, imo, our HTML markup is bloating some of our components, making it much more difficult to get the same screen readers outputs as one would get by browsing https://www.w3.org/WAI/ARIA/apg/patterns/ various examples with the screen reader
=> Improve Banners settings screen reader output

cypress/e2e/po/edit/provisioning.cattle.io.cluster/tabs/machine-pools-tab-rke2.po.ts, cypress/e2e/tests/pages/manager/cluster-provisioning-azure-rke2.spec.ts, shell/edit/provisioning.cattle.io.cluster/tabs/MachinePool.vue, shell/utils/validators/machine-pool.ts
=> [Backport 2.11.2] - Machine pool validation

cypress/e2e/po/edit/provisioning.cattle.io.cluster/tabs/machine-pools-tab-rke2.po.ts, cypress/e2e/tests/pages/manager/cluster-provisioning-azure-rke2.spec.ts, shell/edit/provisioning.cattle.io.cluster/tabs/MachinePool.vue, shell/utils/validators/machine-pool.ts
=> [Backport 2.10.6] - Machine pool validation

.github/workflows/scripts/pr-gh-project.js
This PR updates our workflow that handles the `Fixes` notation to ensure that all PRs are linked to an issue - this will ensure that issues go through the correct QA process and that PRs not detected as being linked to an issue by our bot will not fall through the cracks and be missed by QA.
If you really need a PR to not be linked to an issue, you can add the `QA/None` label to the PR.
=> Enforce linking of PRs to issues

pkg/rancher-components/src/components/RcButton/RcButton.vue, shell/assets/translations/en-us.yaml, shell/components/nav/NamespaceFilter.vue
This updates the namespace filter to make is more keyboard accessible. This also updates aria attributes so that different elements and behaviors of the namespace filter can be better detected by screen readers.
Fixes #12779
- Fix roles for namespace filter options
- Replace namespace filter icons with buttons
- Fix RcButton classes
- Update namespace filter roles and keyboard behavior
- Update aria attributes
Most notably, the keyboard behavior has been updated so that all elements are accessible via keyboard:
- Namespace filter is focused
- Down/Enter opens the namespace filter and focuses on the filter input
- Namespace filter is opened
- Tab will focus the next element
- Down will enter the list of options
- Tabbing away from final element in the dropdown will close the dropdown and …
=> Update `namespaceFilter` accessibility features

shell/components/form/MatchExpressions.vue
Fixes https://github.com/rancher/dashboard/issues/13677
Added `.trim()` to `rule.key` to remove leading and trailing spaces before submitting the value.
- Create a Rancher (latest version) and import a Harvester cluster.
- Click on "Create Harvester RKE2 Cluster" and enter Harvester credentials.
- In the Machine Pool section: Click "Show Advanced" > Click "Add NodeSelector" button > Click "Add Rule"
- Add a key with a trailing space and proceed.
=> trim nodeselector keys to prevent backend rejection

shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/pages/c/_cluster/apps/charts/install.vue, shell/utils/__tests__/object.test.ts, shell/utils/object.js
=> [Backport 2.10.6] - Logging chart yaml

.github/workflows/scripts/pr-gh-project.js
Fixes #14010
Reverts the previous fix for this issue, since this may be causing workflow approval issues.
=> Revert changes to enforce PR linking

pkg/rancher-components/src/components/RcDropdown/RcDropdown.vue, pkg/rancher-components/src/components/RcDropdown/RcDropdownItem.vue, pkg/rancher-components/src/components/RcDropdown/RcDropdownItemCheckbox.vue, pkg/rancher-components/src/components/RcDropdown/RcDropdownItemSelect.vue, pkg/rancher-components/src/components/RcDropdown/index.ts, pkg/rancher-components/src/components/RcDropdown/useDropdownItem.ts, shell/components/LocaleSelector.vue, shell/components/form/LabeledSelect.vue, shell/components/form/Select.vue, shell/components/nav/WindowManager/ContainerLogs.vue, shell/components/nav/WindowManager/ContainerLogsActions.vue, shell/mixins/vue-select-overrides.js
This replaces the custom container actions dropdown menu with the new dropdown menu component.
Fixes #14157
- Create a new dropdown menu item checkbox component
- Create a new dropdown menu item select component
- Abstract duplicated dropdown menu item logic into new composable, `useDropdownItem`
- Create a dedicated component for comtainer logs actions
- Replace container logs actions implementation with new component
I opted to keep the design as close as possible to the existing implementation. Unfortunately, this means that we are utilizing a non-standard pattern with the Labeled Select in the menu, but it keeps the design consistent with what we had before. I attempted to create a sub-menu abstraction that I had 90% working, but I was taking too much time to finalize the components; …
=> Replace container logs actions with new dropdown menu component

shell/edit/provisioning.cattle.io.cluster/__tests__/DirectoryConfig.test.ts, shell/edit/provisioning.cattle.io.cluster/tabs/DirectoryConfig.vue
Fixes #14291
Original kudos to @khushalchandak17 for the fix in https://github.com/rancher/dashboard/pull/14262. 
Backport of https://github.com/rancher/dashboard/pull/14267
- address issue with common config and updating k8s version
- updates unit tests
Test creating and editing clusters with all three directory configuration options (Default, Common, Custom) and changing the Kubernetes version during and after creation to ensure the directory settings behave as described.
=> backport pr 14277 - 2.10.6

shell/edit/provisioning.cattle.io.cluster/__tests__/DirectoryConfig.test.ts, shell/edit/provisioning.cattle.io.cluster/tabs/DirectoryConfig.vue
Fixes #14290
Original kudos to @khushalchandak17 for the fix in https://github.com/rancher/dashboard/pull/14262. 
Backport of https://github.com/rancher/dashboard/pull/14267
- address issue with common config and updating k8s version
- updates unit tests
Test creating and editing clusters with all three directory configuration options (Default, Common, Custom) and changing the Kubernetes version during and after creation to ensure the directory settings behave as described.
=> backport pr 14277 - 2.11.2

shell/utils/validators/formRules/__tests__/index.test.ts, shell/utils/validators/formRules/index.ts
=> Regression while adding validation library 

pkg/aks/components/CruAks.vue, pkg/aks/components/__tests__/CruAks.test.ts, pkg/aks/util/__mocks__/aks.ts
Backport of #14280 
fixes #13721
=> [2.11.2]Use management cluster status.version.gitVersion to filter upgrade options when AKS cluster configs are missing a patch number

pkg/aks/components/CruAks.vue, pkg/aks/components/__tests__/Config.test.ts, pkg/aks/components/__tests__/CruAks.test.ts, pkg/aks/util/__mocks__/aks.ts
Fixes #12535 - see https://github.com/rancher/dashboard/issues/12535#issuecomment-2736071342
This PR updates the AKS provisioning form to use the management cluster's status.gitVersion to filter the list of available upgrade versions when the cluster config is missing a patch version, which may happen when provisioning through terraform.
1. Create a new AKS cluster with an older k8s version (eg 1.30.1)
2. Edit the cluster and just verify that the form has loaded correctly, the kubernetes version dropdown shows '1.30.1', and the dropdown options no longer include 1.30.0
3. Edit the cluster to update the k8s version to one without a patch number. I did this through the norman api ui: 
a) navigate to `<rancher url>/v3/clusters`, look through the list, and click the id of the AKS cluster you …
=> Use management cluster status.version.gitVersion to filter upgrade options when AKS cluster configs are missing a patch number

shell/utils/validators/formRules/index.ts
Fixes #14278
We are changing the `gitRepository` validation rule to accept `%20` encoded white spaces.
We are not going to use a more complex regex to avoid performance issues.
Fleet -> GitRepo create
- Go to Fleet -> GitRepos -> Create
- Add spaces in the url field:
- `https://github.com/rancher/dashbo%20ard/` ok
- `https://github.com/rancher/da%20shbo%20ard/` ok
- `https://github.com/rancher/dashbo   ard/` ko
=> Fleet allow encoded whitespaces in gitRepo url field

shell/utils/validators/formRules/index.ts
=> [2.11.2] Fleet allow encoded whitespaces in gitRepo url field

cypress/e2e/tests/priority/vai-setup.spec.ts, cypress/globals.d.ts, cypress/support/commands/rancher-api-commands.ts, package.json, scripts/e2e-docker-start
Fix E2E tests
- Wait for settings resource to be available before trying to set it and silently fail
- The test should be improved and validate that the setting is correctly applied, however that whole block us due to be removed soon (days) via https://github.com/rancher/dashboard/pull/14086
- Recent backend change ([Steve bump](https://github.com/rancher/rancher/commit/2a62ae06a70febc82556e9c77a6b4c1a0645d735)) is causing e2e tests to fail in CI. We need to pin our e2e tests to older rancher image (8f008ca4123bcb0ab521cc4a0a592d845db870c3)
=> Ensure rancher is ready before setting up vai tests and Pin e2e tests

pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue, shell/assets/translations/en-us.yaml, shell/pages/prefs.vue
Fixes #13610 
Adds a tooltip to the pref for the UI Extensions developer.
Also increases the spacing between the tooltip icon and the text as it was cramped.
Manually check the prefs page shows the new tooltip.
Now:
Before:
=> Add an explanation to the UI Extension Developer preference

shell/detail/node.vue, shell/store/type-map.utils.ts
Fixes #13747
- make ported `createHeaders` schema null safe
- ensure node detail page handles no pods permissions
- both are pre 2.11 issues (though some code has changed locations)
- similar concept to https://github.com/rancher/dashboard/pull/13478, but not same specifics 
- user could not see events so no schema
- in data we access headers for events with missing schema
- discovered when investigating https://github.com/rancher/dashboard/issues/13722
- as per issue
=> Improve handling of missing schemas

shell/components/form/NameNsDescription.vue
Needed for [#64](https://github.com/rancher/capi-ui-extension/issues/64)
Added a prop to remove name field from NameNSDescription compionent
Check that if no prop is provided, name is displayed.
Check if nameHidden is set to true, name is not displayed.
None
=> Made name optional in NameNSDescription component

package.json, scripts/e2e-docker-start
Fixes #https://github.com/rancher/dashboard/issues/14332
This PR unpins the e2e tests from older version of Rancher - use `head` image instead.
=> unpin e2e tests

shell/detail/catalog.cattle.io.app.vue, shell/pages/c/_cluster/apps/charts/install.vue, shell/utils/object.js
Fixes rancher/rancher#50291
This reverts changes to object merge behavior because the existing behavior is destructive when merging deeply nested user values. 
- Revert changes to object merge behavior
For example, a default object contains the value:
```js
a: {
b: true,
c: true,
d: {
e: true,
f: {
g: true,
e: { },
f: [ ],
},
},
}
```
and a user value modifies `g`, which is stored as:
```js
a: {
d: {
f: {
g: false,
},
},
}
```
When the object is merged, deeply nested values will only be taken from the user values, causing properties to be lost. Furthermore, default properties for `f` can also be dropped. This operation is too destructive, and it's better to merge user-supplied properties with defaults than to drastically alter YAML altogether.
See associated issue for details. We will …
=> Revert custom object merge behavior

.github/workflows/scripts/pr-gh-project.js
Re-adds back https://github.com/rancher/dashboard/pull/14010
This was removed as we thought it was causing workload approvals, but does not seem to be, so adding back.
I have decided to only add this for PR open/edit and not on close - this does not make sense to fail the workflow when a PR is closed.
Marking as QA/None since this was previously reviewed and merged.
=> GH Workflow: Add back in GitHub fixes notation check

shell/components/Tabbed/index.vue, shell/components/form/ResourceTabs/index.vue
Fixes #14321 
- Reconnect `resource` to `Tabbed` component via `ResourceTabs`
**NOTE: Observability environments are very short-lived, so this requires some urgency to review while the env is still up**
A bug was introduced via https://github.com/rancher/dashboard/pull/12886 where I incorrectly "disconnected" the `resource` prop from being passed to the `Tab` component, causing a problem on the `Observability` extension, reproducible on the extension version `2.0.1`.
This won't catch all the use cases for `Tabbed`, but at least it assures it's wired in where `Tabbed` is used via `ResourceTabs` (that's covering 16 different detail views on the UI), where this particular extension is applied.
Mitigation has already been done on the extension side via …
=> reconnect `resource` to `Tabbed` component via `ResourceTabs`

shell/components/form/LabeledSelect.vue, shell/components/form/Select.vue, shell/components/form/__tests__/LabeledSelect.test.ts, shell/components/form/__tests__/Select.test.ts
Fixes #14361 
- fix problem with `space` key on searchable selects 
- test both `LabeledSelect` and `Select` components, both `searchable` or not
- possible regression on https://github.com/rancher/dashboard/issues/13252#issuecomment-2672428059
=> fix problem with space key on searchable selects

cypress/support/commands/accessiblity.ts
Fixes #14297 
- re-enable color contrast tests for a11y
=> re-enable color contrast tests

cypress/e2e/po/components/create-edit-view.po.ts, cypress/e2e/po/extensions/imported/cluster-edit.po.ts, cypress/e2e/po/extensions/imported/cluster-import-generic.po.ts, cypress/e2e/tests/pages/manager/cluster-manager.spec.ts, pkg/imported/components/Basics.vue, pkg/imported/components/CruImported.vue, pkg/imported/components/VersionManagement.vue, pkg/imported/components/__tests__/versionManagement.test.ts, shell/edit/provisioning.cattle.io.cluster/index.vue
Fixes #13614 
Changed the condition for the version management info banner.
Additionally, fixed wording when going from 
default (enabled) -> enabled and default (disabled) -> disabled.
Cluster agent will not redeploy in that case, so we should not warn about it.
Now, for local cluster, only show the banner if we are switching between a default and non-default values.
For imported cluster, now only warn about cluster agent redeployment if we are switching from enabled to disabled (including default) and vice versa.
Cluster import:
Banner should be displayed
Editing imported cluster:
Banner should be hidden if no changes were made.
If changes were made, banner should have the following content:
| Case                                                         | Result  | …
=> Hid agent redeployment wording from version management banner for local cluster

cypress/e2e/blueprints/cluster_management/eks-default-settings.ts, cypress/e2e/po/components/labeled-select.po.ts, cypress/e2e/po/edit/cloud-credentials-eks.po.ts, cypress/e2e/po/edit/provisioning.cattle.io.cluster/create/cluster-create-eks.po.ts, cypress/e2e/tests/pages/manager/eks-cluster-provisioning.spec.ts, pkg/eks/components/AccountAccess.vue, pkg/eks/components/NodeGroup.vue
Fixes #https://github.com/rancher/qa-tasks/issues/1572
This e2e test suite comprises eks cluster provisioning tests that create a cluster by filling the mandatory fields and create a cluster with default values.
- Added PO for eks Create cluster Page.
- Added `data-testid` for the NodeRole field
- Added supporting function `checkContainsOptionSelected()` in `Labeled-Select.po` that matches partially/contains the expected value
- Created blueprint file that contains all the default eks config values from `CruEKS.vue`
- EKS cluster provisioning
- cluster provisioning for other hosted providers
- e2e tests for other providers (amazon ec2, azure, gke, rke2/rke1, etc)
=> Eks automation - e2e tests

cypress/e2e/tests/pages/explorer/dashboard/cluster-dashboard.spec.ts, shell/pages/c/_cluster/explorer/index.vue
Fixes #14394
This PR fixes the issue above.
The existing code does handle the case where the backend API returns an error code, but does not then use this correctly.
This PR is a relatively small fix, which ensures we hide the boxes when we get errors from the APIs, since these indicate that the user does not have permission. 
Automated tests are extended to cover the gap - I believe they are sufficient to cover the use cases given the code paths that we have.
Before:
After:
=> Don't show agent status when API calls fail

shell/components/Tabbed/index.vue, shell/components/form/ResourceTabs/index.vue
Fixes #14380
- Reconnect `resource` to `Tabbed` component via `ResourceTabs`
**NOTE: Observability environments are very short-lived, so this requires some urgency to review while the env is still up**
A bug was introduced via https://github.com/rancher/dashboard/pull/12886 where I incorrectly "disconnected" the `resource` prop from being passed to the `Tab` component, causing a problem on the `Observability` extension, reproducible on the extension version `2.0.1`.
This won't catch all the use cases for `Tabbed`, but at least it assures it's wired in where `Tabbed` is used via `ResourceTabs` (that's covering 16 different detail views on the UI), where this particular extension is applied.
Mitigation has already been done on the extension side via …
=> backport PR 14357

shell/utils/grafana.js
Fixes #14374
We now hide the timepicker and refresh buttons on all grafana dashboards in the app.
We just had to add the newly added `_dash.hideTimePicker=true` query param to the urls. [docs](https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v11-3/#scenes-powered-dashboards-are-generally-available)
It's a pain to actually test this in a local cluster. You won't see actual data because of a same origin issue. This goes back a long way https://github.com/rancher/rancher/issues/31891. For testing this locally I think it's sufficient to verify that the widgets are no longer present even if data is missing.
I validated on all of the pages listed below and verified that the new parameter doesn't break old versions of the grafana dashboard.
There are the locations of all the grafana …
=> Hide the newly added timepicker/refresh controls from grafana dashboard

pkg/harvester-manager/machine-config/harvester.vue, shell/plugins/dashboard-store/getters.js, shell/plugins/steve/getters.js, shell/plugins/steve/steve-pagination-utils.ts, shell/types/store/dashboard-store.types.ts, shell/utils/cluster.js
Fixes #14420
Fixes #11549
I've combined two bug fixes as they both require a harvester instance to validate, and are small
Bug 1 - #14420 - Ensure harvester clusters are filtered out from side nav and cluster home page
- with FF `harvester-baremetal-container-workload` disabled (which is the default) harvester clusters should be hidden from normal cluster lists
- this was happened as before for cluster management (unchanged), but was broken in side nav and home page cluster list
- the code for this was written but not wired in
Bug 2 - #11549 - Ensure harvester machine config options are correctly presented
- once a downstream harvester cluster is imported, users can provisioned rancher instances into it (cluster management --> create --> harvester)
- this requires make http requests to …
=> SSP: Fix two harvester related bugs

shell/components/PaginatedResourceTable.vue, shell/components/SortableTable/selection.js, shell/mixins/resource-fetch.js
Fixes #14448
- On manul refresh with vai on ensure that the table's selection state (row highlighting, checkbox, total count at top) is reset once the user has clicked refresh
- need to understand how this should / will work when resource's are automatically updated
- vai on, any list, make a few selections hit refresh
- projects/namespace list `move` namespace (though this looks already broken)
=> Ensure refresh button correctly clears table selection

shell/chart/monitoring/index.vue, shell/components/form/ResourceTabs/index.vue, shell/config/product/explorer.js, shell/models/service.js, shell/plugins/steve/steve-pagination-utils.ts
Fixes #11536
Fixes #11539
Fixes #11540
Also
Fixes #14446
Fixes #14445
- Fields in install monitoring wizard were empty (#11536, #11539, #11540)
- exception caused by missing backend indexed fields
- exception meant a number of input options were not populated
- these fields have now been indexed, so no code changes required to fix (just comments tidied up)
- Review sorting/filtering on other fields that depended on backend indexing or bug fixes 
- some are fine (removed comments associated with them)
- some are still not (created new issues and updated comments)
- Fix sorting storage classes by `default` column
- Fixed issue when searching `services`, ensure column using local property targetPort are not used when searching server side (#14446)
- Can now sort on service type
- Can now …
=> Fix failure to fetch workload resources in monitoring chart install

.github/workflows/port-issue.yaml, shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #14355
Updates issue backport bot to use full URL rather than the issue number.
=> Update backport bot to use issue URL rather than issue Number

shell/components/CruResource.vue
Fixes #14462 
Separated new namespace creation logic from a check to see if CruResource should create a new namespace.
CAPI providers usually have pre-defined namespaces they are supposed to be created at. Those namespaces usually do not exist if provider has not been installed before. Without this change, it is impossible to pre-set the namespace we want to create and we would have to rely on users to know the correct namespace name and create it using 'Create New Namespace' functionality of the NameNsDescription control, which would set createNamespace state to true. We want to avoid having to rely on the user to do this, however, there was no other way to overwrite the value of createNamespace check. With this change, other components can call createNamespaceIfNeeded method directly, …
=> Separated creating new namespace from createNamespace check

shell/components/nav/NamespaceFilter.vue
This adds the `.self` modifier to the namespace keydown event so that the handler only triggers if `event.target` is the element itself. This allows the child input to accept space as an input.
Fixes #14425 
- add the `.self` modifier to the namespace keydown event
- `.self` only triggers handler if `event.target` is the element itself, not the child
- Namespace picker
- The `.prevent` modifier was added to stop the page from scrolling when using space to open the namespace picker
NA
=> Add self modifier to namespace keydown

pkg/rancher-prime/l10n/en-us.yaml, pkg/rancher-prime/pages/Registration.vue, pkg/rancher-prime/pages/__tests__/Registration.test.ts, pkg/rancher-prime/pages/registration.composable.ts, shell/assets/styles/base/_functions.scss, storybook/src/stories/Components/BadgeState.stories.ts
Fixes #14151
To test the UI either disable the check or run a Rancher Prime instance.
```ts
if (!plugin.environment.isPrime) {
return false;
}
```
Updated content as in issue definition.
Validation stays the same.
- Fixed BadgeState story to render correctly
https://github.com/user-attachments/assets/5b8d395f-67d6-42cf-af17-a60215322e0b
=> Update Rancher Prime registration UI

cypress/e2e/tests/pages/manager/machine-sets.spec.ts
A visual test has been created using Percy to verify the machine sets screen within Rancher. The goal of this test is to ensure that the user interface is displayed correctly and detect any unexpected visual changes
Page route:
`qa.rancher.space/dashboard/c/_/manager/cluster.x-k8s.io.machineset`
=> Implementation of Visual Test with Percy for Machine sets page #14386

shell/plugins/steve/steve-pagination-utils.ts
Updates to the cluster lists in the side nav are not updating correctly when clusters are created or deleted. This is one of the final hurdles to enabling SSP by default, so disable ssp for those cases to unblock a lot of activity
- Remove locations from allow list
- Will be reverted as part of https://github.com/rancher/dashboard/issues/14493
- side nav updates when a cluster is created/deleted 
- when on the home page
- when on the cluster manager cluster list
- when clusters are created/deleted in another browser
- none
=> SSP: Disable SSP for side nav and home page cluster list

cypress/e2e/po/pages/explorer/charts/install-charts.po.ts, cypress/e2e/tests/pages/charts/chart-install-wizard.spec.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1795
Adding a basic validation for a Resource UI element LabeledSelector that let the user pick existing resources during the Chart Wizard.
In this case the test chart has a ConfigMaps selector. 
The repo URL is suggested in the EPIC linked in the task for reproducibility.
N/A
N/A
=> Automation - Adding a test to check the Resource UI elements in the Chart Wizard

cypress/e2e/tests/pages/explorer/more-resources/api/custom-resource-definitions.spec.ts
Temporarily disable CRD tests for vai given https://github.com/rancher/rancher/issues/50687
- issue to revert https://github.com/rancher/dashboard/issues/14533
=> Disable VAI on test for CRD resource

cypress/e2e/po/pages/fleet/fleet.cattle.io.application.po.ts, cypress/e2e/tests/pages/fleet/gitrepo.spec.ts, shell/assets/translations/en-us.yaml, shell/components/fleet/FleetClusterTargets/TargetsList.vue, shell/components/fleet/FleetClusterTargets/index.vue, shell/components/fleet/FleetRepos.vue, shell/components/fleet/__tests__/FleetClusterTargets.test.ts, shell/components/fleet/__tests__/FleetOCIStorageSecret.test.ts, shell/components/fleet/dashboard/ResourceDetails.vue, shell/components/form/MatchExpressions.vue, shell/config/table-headers.js, shell/edit/fleet.cattle.io.gitrepo.vue, shell/edit/fleet.cattle.io.helmop.vue, shell/models/fleet-application.js, shell/types/fleet.d.ts, shell/utils/__tests__/fleet.test.ts, shell/utils/fleet.ts
Fixes #13924
We want to improve the Cluster targets functionalities in GitRepos and HelmOps wizards.
- YAML editor for advanced scenarios has been removed
-  The new form can handle the following use cases:
- No clusters
- All Clusters
- Select multiple clusters and/or matching expressions
- We don't want to handle clusterGroups and clusterGroupsExpressions; These 2 scenarions are considered complex and can be handled directly in the YAML editor.
- We display a warning message to inform the users to handle complex scenarios using the YAML editor.
- default target in flett-local workspace will be local cluster.
- We changed the 'Target' column in each GitRepos and HelmOps tables to be consistent with the new scenarios (remove ClusterGroups values)
- Create/Edit GitRepos and HelmOps
- …
=> Fleet add Cluster targets Match Expressions

shell/dialog/MoveNamespaceDialog.vue
This explicitly sets data to `undefined` for when cancelling `MoveNamespaceDialog.vue` to fix an issue with the cancel button preventing the modal from raising again. 
Fixes #14392
- pass undefined to close event in `MoveNamespaceDialog.vue`
The `click` event was implicitly passed to close when clicking on the cancel button. This can cause issues in `togglePromptModal` in `shell/store/action-menu.js`. `data` is defined, but it doesn't have a value for `performCallback`; `showModal` will default to true, but the modal will no longer and the `modalData` will become malformed. Making sure that we don't provided any data resolves the issues.
See issue for details.
This should only affect the `MoveNamespaceDialog`.
NA
=> Explicitly pass `undefined` when closing MoveNamespaceDialog.vue

shell/components/Resource/Detail/TitleBar/__tests__/composables.test.ts, shell/components/Resource/Detail/TitleBar/composables.ts, shell/components/Resource/Detail/TitleBar/index.vue
Adding a quick fix to allow showing graph view option for fleet
Masthead on a page that should have the view options and a page that shouldn't
https://github.com/user-attachments/assets/2eebb04e-b99a-4dfd-b54f-3eea0316c800
=> Adding a quick fix to allow showing graph view option for fleet

cypress/e2e/tests/pages/explorer2/storage/configmap.spec.ts, cypress/globals.d.ts, cypress/support/commands/rancher-api-commands.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1888
Adding same checks to other kubernetes objects pagination lists. (i.e Pods) to ConfigMaps
This will enable comparison tests using pre-existing and fresh install Rancher versions for pagination validations
N/A just CI
CI
=> Automation ConfigMaps pagination tests

shell/dialog/ImportDialog.vue
This stops `ImportDialog.vue` from attempting to mutate the `defaultNamespace` prop and uses it as a default value for a `selectedNamespace` data prop instead.
Fixes #14644 
- Use `defaultNamespace` prop as default value for `selectedNamespace` data prop
Mutating props is heavily discouraged in Vue - using `defaultNamespace` as a default value for a data prop helps to avoid the issue of mutating props altogether. 
- Import YAML dialog
- Import YAML dialog
NA
=> Use `defaultNamespace` prop as a default value

cypress/e2e/po/components/workloads/redeploy-dialog.po.ts, cypress/e2e/po/pages/explorer/workloads-daemonsets.po.ts, cypress/e2e/po/pages/explorer/workloads-statefulsets.po.ts, cypress/e2e/po/pages/explorer/workloads/workloads-deployments.po.ts, cypress/e2e/tests/pages/explorer2/workloads/daemonsets.spec.ts, cypress/e2e/tests/pages/explorer2/workloads/deployments.spec.ts, cypress/e2e/tests/pages/explorer2/workloads/statefulsets.spec.ts
Fixes #14455 
Add e2e coverage for the `Redeploy` action across all three workload types (DaemonSet, Deployment, StatefulSet).
=> [Automation] Workload: Add redeploy dialog tests

shell/components/form/KeyValue.vue
Fixes https://github.com/rancher/dashboard/issues/13070
handle multiple separators (: and =) in a line by finding the index of the first occurrence of either separator using a regular expression. After identifying the separator, we use the substring method to separate the key and value.
As mentioned in the issue repro steps.
=>  Improved Handling of Multiple Separators in Environment Variable Parsing

shell/assets/translations/en-us.yaml, shell/components/form/KeyValue.vue, shell/components/form/Labels.vue, shell/components/form/__tests__/Labels.test.ts
=> [2.11.4] Fix protected Labels

pkg/rancher-prime/index.ts, pkg/rancher-prime/l10n/en-us.yaml, pkg/rancher-prime/pages/Registration.vue, pkg/rancher-prime/pages/registration.composable.test.ts, pkg/rancher-prime/pages/registration.composable.ts
Fixes #13400
Notification is displayed if rancher registration status is not active.
- Corrected getters to use `manager` instead of `cluster`
- Allowed `store` to be passed by the registration composable
https://github.com/user-attachments/assets/3ec7d787-9c06-4b43-a80b-256139f5da87
=> Add SCC registration notification

shell/pages/c/_cluster/fleet/index.vue
Fixes:
- Workspace title grouped inside an `h2` element, font sizes fixed
- State group titles font sizes fixed, spacing adjusted
- Spacing between app cards reduced
- Spacing between state groups adjusted
- Expand/collapse icons in the global button and cards changed to down/up
=> Fleet dashboard refinements

shell/pages/home.vue
Fixes #10791 
- fix long cluster names (truncate) on home page cluster list if the cluster is not active
**- Can only be validated manually. No tests are available for this**
- provision a cluster that is not active with a long name
- check that truncation is done
https://github.com/user-attachments/assets/fca63349-561b-4a60-a08f-73e880cddd88
=> fix long cluster names (truncate) on home page cluster list if the cluster is not active

shell/components/CruResource.vue, shell/components/ResourceDetail/legacy.vue, shell/components/ResourceYaml.vue, shell/components/form/Footer.vue
Fixes #13689
- Hide Footer errors and remove duplicates from errors in the header - in the video below we are saving multiple times but new error strings are discarded if already existing in the list.
[Screencast from 2025-07-08 11-18-17.webm](https://github.com/user-attachments/assets/9fa87ace-c30e-46a4-adb6-5c2cddd79c89)
- Errors are now sticky and always visible
[Screencast from 2025-07-08 11-23-12.webm](https://github.com/user-attachments/assets/059222ce-df9b-44dd-8456-a4e808059c91)
- Added `closable` option in Footer errors - it can be tested in dev, by setting `show-errors="true"` to `ResourceYaml`
- Any resource -> click on 'Edit Config' action -> apply some changes and Save
- Any resource -> click on 'Edit Config' action -> click on 'Edit as YAML' in the footer -> apply some …
=> Fix error messages presentation bugs

shell/components/DetailText.vue, shell/components/Resource/Detail/ResourceTabs/SecretDataTab/Basic.vue, shell/components/Resource/Detail/ResourceTabs/SecretDataTab/BasicAuth.vue, shell/components/Resource/Detail/ResourceTabs/SecretDataTab/ServiceAccountToken.vue, shell/components/Resource/Detail/ResourceTabs/SecretDataTab/Ssh.vue, shell/composables/resources.test.ts, shell/composables/resources.ts
Fixes #13547
_The repro steps outlined in the original issue are a little finicky. The secret gets immediately deleted from the backend so you only see on the same page load as doing the yaml import. If you refresh you'll need to import again._
We now default to an empty string which allows the rest of the component to run as expected.
I also made the auth type components props optional since they can come back undefined. This resolves some console warnings.
While testing this it also became apparent we weren't properly redirecting to failwhale when a resource didn't exist. I added that functionality as well.
Anywhere that has `<DetailText />`. I think verifying in the secret detail page is sufficient.
Same as above
https://github.com/user-attachments/assets/d1c9d03b-f9cc-4919-8925-6f48b71 …
=> Resolving an issue when DetailText receives undefined/null value

shell/components/form/SecretSelector.vue, shell/components/form/SimpleSecretSelector.vue
Fixes #14474
- two fixes, two places
- Fix - ensure filter=x=1,x=2 format is used and not filter=x=1,2
- this must have worked at some point...
- Fix - ensure partial filter is used when searching secrets by name
- same here...
- SimpleSecretSelector is only used in monitoring alertmanager receive config
- See issue for repro steps
- whoever created it should have used SecretSelector instead
- SecretSelector is only used in logging output providers
- Logging --> Outputs --> Create --> Outputs tab --> Access secret fields
as per issue, plus SecretSelector via steps above
localised changes, shouldn't cause regressions elsewhere
=> Ensure correct syntax is used with SSP and the secret selectors

shell/components/fleet/dashboard/ResourceCard.vue, shell/components/fleet/dashboard/ResourceCardSummary.vue
Fixes:
- Card error text doesn't have a fixed height
- The cards take 100% of height, adapting to the maximum height in their row (max of 5 lines of error message).
=> Fleet dashboard Card errors not fixed height, height adapted to the row

cypress/e2e/tests/pages/virtualization-mgmt/harvester.spec.ts, pkg/harvester-manager/models/harvesterhci.io.management.cluster.js, shell/models/provisioning.cattle.io.cluster.js
Fixes #14285 
Disabled editing Harvester clusters from Cluster Management.
When we enable harvester-baremetal-container-workload feature flag, Harvester clusters become available in Cluster Management. Users should not be able to edit Harvester clusters from there, so editing action has been removed and is only added when access through Harvester Clusters
Import Harvester cluster
Global settings -> feature flags -> "harvester-baremetal-container-workload" -> enable
Cluster Management -> Harvester cluster -> action menu should NOT have an option to edit a cluster
Cluster Management -> non-Harvester cluster -> action menu should have an option to edit a cluster
Virtualization Management -> Harvester cluster -> action menu should have an option to edit a cluster
List of actions available to …
=> Disabled editing Harvester cluster from Cluster management

cypress/e2e/tests/pages/charts/logging.spec.ts, shell/components/RelatedResources.vue
Fixes https://github.com/rancher/dashboard/issues/14624
modified the logic to correctly detect whether a resource still exists or not, and then fallback to a better default state. 
If a resource was deleted, the backend (/v1) still returns a relationship for it but without a state,current code assumes missing state = "active": That means deleted resources (no longer present in the cluster) are wrongly shown as "active", which is misleading.
=> display 'missing' state for deleted related resources in app view

shell/assets/translations/en-us.yaml, shell/edit/provisioning.cattle.io.cluster/__tests__/rke2.test.ts, shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #13894 
This PR moves the logic to generate a kubeconfig secret and set that as well as other chart values from saveOverride into a before save hook, so that the code runs before switching to the yaml view.  
1. Navigate to the cluster manager cluster list view and click create
2. Select the harvester rke2 option
3. Select a cloud credential and fill all required fields in the machine config section
4. Open browser dev tools network tab and watch network requests
5. Click edit as yaml
6. Verify that a secret was created and referenced in the cluster yaml
=> set harvester chart values in before save hook instead of saveOverride

pkg/aks/components/Config.vue, pkg/aks/components/__tests__/Config.test.ts, pkg/aks/util/validators.ts
Fixes #12985
This PR has some small fixes to the AKS networking section:
- fixed the label on the outboundType input
- fixed the LoadbalancerSKU validator always returning an error when User Defined Routing is selected
- marked virtual network as required when User Defined Routing is selected
- automatically switch to the azure network plugin when User Defined Routing is selected
=> aks networking validation fixes and user-defined-routing fixes

shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/plugins/dashboard-store/__tests__/normalize.test.ts, shell/plugins/dashboard-store/__tests__/utils/normalize-usecases.ts, shell/plugins/dashboard-store/normalize.js
Fixes #14397 
- replace `mergeWithReplace` and `merge` with `handleConflict` function on machine pools sync mechanism
- I've had a go at creating unit tests and hit a lot of barriers along the way because the `handleConflict` uses a lot of accessorial methods, but I just couldn't circumvent the problems I hit on `changeset` method, so this needs to be manually tested
- Install Elemental `3.x.x` along with the operator
- Go to `Elemental`, `Inventory of Machines` and create an instance of this resource via `create YAML` where you should:
1) add any name
2) on `metadata`, add the following label 
```
labels:  
key: 'some-string'
```
having a label with key `key` is important
- On the list view of `Inventory of Machines`, select that row item and on the table actions (bulk) select `Create …
=> replace `mergeWithReplace` and `merge` with `handleConflict` function on machine pools sync mechanism

shell/edit/networking.k8s.io.ingress/Certificate.vue
This is a follow-up to provide a more targeted approach after the revert in #14742.
Fixes #14404
> 🗒️ Note: `secretVal` was added to the local state for `Certificate.vue`
> 
> Default Ingress Controller Certificate was unable to be selected when updating `secretName` in the watcher - this happens because we set `secretName` to null in the `update` method if the default ingress controller certificate method is selected. Based on this logic, `null` and the default value are the same. This change means that the default value is selected on first render, but the end result should be the same: a value of `null` for `secretName`. 
We need to watch changes to `value` in `Certificate.vue` in order to ensure that the component triggers changes - without an ID to properly track changes in …
=> Watch `value` to ensure that Certificate hosts and secretName update in DOM

shell/models/provisioning.cattle.io.cluster.js, shell/utils/__tests__/create-yaml.test.ts, shell/utils/create-yaml.js
Fixes #8480 
As the `profile` property is currently [removed before sending the request](https://github.com/rancher/dashboard/blob/7d9cea18a05807ecfe069389bdac4539ae9381e8/shell/edit/provisioning.cattle.io.cluster/rke2.vue#L1360-L1363) to the backend, this PR adds the ability to determine fields which should be commented out within a resource's YAML representation.
I added a method on the `provisioning.cattle.io.cluster` model to return an array of field options which should be commented out, during the [creation of the yaml](https://github.com/rancher/dashboard/blob/7d9cea18a05807ecfe069389bdac4539ae9381e8/shell/edit/provisioning.cattle.io.cluster/rke2.vue#L1754-L1765), `createYaml` will fetch the `commentFieldsOptions` from the resource's model and will comment out the properties …
=> Add ability to configure commentFieldsOptions on resource model for createYaml

shell/assets/styles/themes/_dark.scss, shell/assets/styles/themes/_light.scss, shell/components/Resource/Detail/Metadata/IdentifyingInformation/index.vue, shell/components/Resource/Detail/Metadata/KeyValue.vue, shell/components/Resource/Detail/Metadata/Rectangle.vue, shell/components/Resource/Detail/SpacedRow.vue, shell/components/Resource/Detail/TitleBar/index.vue, shell/components/SlideInPanelManager.vue, shell/components/formatter/PodImages.vue
Fixing the issues outlined here:
Some overlap with the above screenshot but here was the original fix requests.
> e.g the overlay for the drawer should've been dark, not white; the labels and annotations do not stretch for full width, they embrace the content and have a max-width + I believe the heigh is off a bit; the 'view labels' and 'view annotations' links are not styled correctly, they should be blue; the 'image' value in the meta column for the 1st screenshot breaks format + the shade of grey used on the labels in the 1st meta column is too light; the badge in the page title is too close to the title itself; etc)
Just style and template changes
Shown in the outline and the video
https://github.com/user-attachments/assets/e3b84637-571e-4ccc-961f-87da7a388cbe
=> Putting together a smattering of style fixes that were pointed out during a design review

shell/edit/networking.k8s.io.ingress/Certificate.vue, shell/edit/networking.k8s.io.ingress/__tests__/Certificate.test.ts
This resolves an issue with displaying the correct value for Certificate - Secret Name when editing Ingress certificates.
Fixes #14404
- Initialize `secretVal` if `value.secretName` has data
- Unit test changes to assert that defaults are set correctly
- Regression was introduced via #14755
Editing Ingress certificates that don't contain a default value for Certificate - Secret Name.
Ingress certificates
=> Certificate.vue: Initialize secretVal if `value.secretName` has data

shell/components/formatter/__tests__/LiveDate.test.ts
This uses jest fake timers and sets a system time for the LiveDate unit tests.
While rare, there are scenarios where using the actual system time can fail the LiveDate unit test[^1] - these failures can occur if a test takes too long, or runs at an inopportune time. Making use of fake timers allows the LiveData tests to be deterministic.
[^1]: Example of LiveDate failure in CI: https://github.com/rancher/dashboard/actions/runs/16271213959/job/45939063987
- LiveDate unit test should pass
- LiveDate unit test should pass
NA
=> Use fake timers in LiveDate unit tests

pkg/harvester-manager/machine-config/harvester.vue, shell/utils/pagination-utils.ts
Fixes #11549
- Fix issue where vai filters to a downstream cluster with vai disabled fails
- At some point harvester will bump to 2.12.0 which will then have it enabled. Until then revert back to the old way
- spin up a harvester cluster and in Advanced / Cloud Configuration Templates create one User and one Network 
- import a harvester cluster into rancher
- create (in cluster manager) a harvester cluster --> advanced
- user and data drop downs should contain the templates above
=> Harvester machine config fix

shell/components/form/Networking.vue, shell/components/form/__tests__/Networking.test.ts
=> fix(Networking): fix unable to edit Host Aliases configuration of a workload pod

pkg/rancher-prime/config/constants.ts, pkg/rancher-prime/pages/Registration.vue, pkg/rancher-prime/pages/registration.composable.test.ts, pkg/rancher-prime/pages/registration.composable.ts
Fixes #14675
Fixes #14814
- Added offline implementation (#14675)
- Fixed issue with online registration glitch due latest condition of registration still in status `In Progress` (#14814)
- Updated condition specification of complete 
- Added further unit tests:
- initialization
- download
- Code cleanup
https://github.com/user-attachments/assets/ff0f0e9a-1f11-4150-a29f-1286b1dc0e65
=> Implement CRD logic for SCC registration offline

pkg/rancher-prime/pages/registration.composable.test.ts, pkg/rancher-prime/pages/registration.composable.ts
Fixes #14813
Fixed registration to be updated.
- Added unit tests for offline registration
- Ensured secret to be loaded also in registering offline third step
https://github.com/user-attachments/assets/4a825d7e-7cb5-4084-8df8-a592381e91ca
=> SCC Offline registration status does not update on complete

pkg/eks/components/AccountAccess.vue, pkg/gke/components/CruGKE.vue, shell/components/google/AccountAccess.vue, shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #13605 
Fixes #14847
- Placing SelectCredential inside a div made it no longer occupy the whole view, so the footer during credential creation was no longer sticking to the bottom of the page
- Added footer to the authentication step during GCE creation
- Made footers for all credentials the same size
While creating and editing clusters (hosted, node-driver or custom) footer should always be present and be at the bottom of the screen. That includes creating new credential 
Creating, viewing and editing clusters could experience unexpected side-effects to styling
=> Fixed footer inconsistency for different providers

shell/edit/networking.k8s.io.ingress/Certificate.vue, shell/edit/networking.k8s.io.ingress/__tests__/Certificate.test.ts
This is a follow-up to PRs #14755 and #14784 to address some issues that I noted in Certificate.vue during development - adding test coverage and removing dead code from the component.
Fixes #
- Remove unused `addHost()` method
- Remove unused `@update:value` event listener 
- Add additional unit tests to improve the coverage of Certificate.vue
`addHost()` is unused.
`@update:value` does not belong on a div and is not listening to any events. 
Adding test coverage helps to prevent regressions in the future. 
- Navigate to Local Cluster Explorer => Service Discovery => Ingresses
- Click on Create
- Click on the Certificates Tab and click Create
Adding, updating, and deleting certificates should behave as they did before.
The removal of `addHost()` could break some parent component that was …
=> Clean up dead code in Certificate.vue and add additional unit tests

shell/assets/styles/themes/_dark.scss, shell/assets/styles/themes/_light.scss, shell/components/CodeMirror.vue, shell/components/Loading.vue, shell/components/form/FileImageSelector.vue
fixes #14856
The loading overlay and modal/drawer overlays
=> Reverted the color of the loading background while maintaining the new color for the rest of overlays

shell/edit/workload/index.vue
Fixes #14728
This issue seems to have been originally created with the fix for https://github.com/rancher/dashboard/issues/11889.
We no longer show the workload/index.vue page so this shouldn't be a problem anymore. Regardless, I did go to `/dashboard/c/local/explorer/workload` and clicked create to verify that the premature errors aren't showing with this change.
=> Fixes an issue where workload yaml editors didn't show errors

shell/machine-config/__tests__/vmwarevsphere.test.ts, shell/machine-config/vmwarevsphere.vue
Fixes #14872
This PR updates the vSphere machine config component to prevent it from altering networks without user input. Previously we were checking if the machine pool had configured networks using name or MOID, and converting those with names to MOID, to align with a UI change that came in 2.10.
Instead of altering the machine config spec, I updated the network getter to convert names to MOID in the component template only.
The scenario described in #14872
=> vsphere network name correction

cypress/e2e/po/components/registries-tab.po.ts, cypress/e2e/tests/pages/manager/registries.spec.ts, shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/edit/provisioning.cattle.io.cluster/tabs/registries/index.vue
Fixes #11134 
Made 'Show Advanced' section independent from the 'Enable cluster scoped container registry ..." checkbox
I've checked with Hostbusters and these sections are independent of each other.
Cluster management -> any RKE2/Custom cluster -> Registries
Show advanced (and area hidden under it) should always be there, independently from 'Enable cluster scoped container registry ..." checkbox
None
=> Decoupled Show Advanced from the checkbox in Registries

.github/workflows/build-extension-charts.yml
Fixes #14761
- adjust main workflow to be able to create a PR instead of committing directly to a given branch
This is based on the work done with this PR + the change https://github.com/aalves08/ui-plugin-examples/blob/main/.github/workflows/build-extension-charts.yml where I've added the new input `create_pr` along with changing the branch for testing. The latest workflow run yielded https://github.com/aalves08/ui-plugin-examples/actions/runs/16270065373/job/45935202787 (failing because I am missing a github env var) + https://github.com/rancher/ui-plugin-examples/pull/68 where we can see the PR created (at least it provided me the link for it because it failed on the github env var part.
The only concern I've got is: https://github.com/rancher/ui-plugin-examples/pull/68/files#diff-ed438 …
=> adjust main workflow to be able to create a PR instead of committing directly to a given branch

cypress/e2e/tests/pages/manager/repositories.spec.ts, cypress/e2e/tests/pages/users-and-auth/roles.spec.ts, package.json, shell/assets/translations/en-us.yaml, shell/components/Drawer/ResourceDetailDrawer/__tests__/composables.test.ts, shell/components/Drawer/ResourceDetailDrawer/composables.ts, shell/components/Resource/Detail/Metadata/__tests__/composables.test.ts, shell/components/Resource/Detail/Metadata/composables.ts, shell/components/Resource/Detail/TitleBar/__tests__/composables.test.ts, shell/components/Resource/Detail/TitleBar/composables.ts, shell/models/management.cattle.io.setting.js, shell/package.json, shell/plugins/dashboard-store/resource-class.js, shell/utils/dynamic-importer.js, shell/yarn.lock, yarn.lock
fixes #14824
Ultimately composables weren't a good fit for supporting the show configuration action and instead of supporting two versions I replaced the composable with showConfiguration on the reosurce models. This lead to seemingly more code changes but most of it is just moving the code.
Areas which show action menus for resources
It's a new feature so I don't expect a regression but possibly in the menus.
Showing that we include the `Show Configuration` action on resources that have an edit config or yaml page available but hide it on the resources that don't.
https://github.com/user-attachments/assets/6224da06-3f69-46a4-bb01-6fe9dbe1642a
=> Adding the Show Configuration action to all resource availableActions

shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/edit/provisioning.cattle.io.cluster/tabs/AgentConfiguration.vue, shell/edit/provisioning.cattle.io.cluster/tabs/DirectoryConfig.vue, shell/edit/provisioning.cattle.io.cluster/tabs/MachinePool.vue, shell/edit/provisioning.cattle.io.cluster/tabs/etcd/S3Config.vue, shell/edit/provisioning.cattle.io.cluster/tabs/registries/RegistryConfigs.vue, shell/edit/provisioning.cattle.io.cluster/tabs/registries/RegistryMirrors.vue, shell/edit/provisioning.cattle.io.cluster/tabs/upgrade/DrainOptions.vue
This refactors data props that contain initialization logic so that they use patterns that are more idiomatic to Vue.
Fixes #14863 
- Refactor data props in 
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
- shell/edit/provisioning.cattle.io.cluster/tabs/AgentConfiguration.vue
- shell/edit/provisioning.cattle.io.cluster/tabs/DirectoryConfig.vue
- shell/edit/provisioning.cattle.io.cluster/tabs/MachinePool.vue
- shell/edit/provisioning.cattle.io.cluster/tabs/etcd/S3Config.vue
- shell/edit/provisioning.cattle.io.cluster/tabs/registries/RegistryConfigs.vue
- shell/edit/provisioning.cattle.io.cluster/tabs/registries/RegistryMirrors.vue
- shell/edit/provisioning.cattle.io.cluster/tabs/upgrade/DrainOptions.vue
The most complex changes in this PR involve shifting initialization logic outside …
=> Clean up data props in `provisioning.cattle.io.cluster`

shell/assets/translations/en-us.yaml, shell/components/CruResource.vue, shell/components/InstallHelmCharts.vue, shell/pages/c/_cluster/apps/charts/install.vue
Fixes #13105 
This PR adds a component to install charts outside the apps and marketplace with minimal configuration. 
Test using https://github.com/rancher/capi-ui-extension/pull/169
none
https://github.com/user-attachments/assets/748bdf28-80e7-4dff-8f6c-f18696f17662
=> Add a button to quickly install helm charts outside the apps and marketplace

cypress/jenkins/cypress.config.jenkins.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1904
Jenkins recurring test runs were failing when running against head image due to a missing Cypress task registration. Added cypress-terminal-report plugin to Jenkins configuration to resolve the issue.
- Verified fix works: Tests run successfully with the plugin enabled
- Confirmed root cause: Disabling the plugin brings back the original ctrLogFiles error
=> [Automation]: Add missing cypress-terminal-report plugin to Jenkins config

cypress/e2e/po/pages/explorer/charts/chart.po.ts, cypress/e2e/tests/pages/explorer/apps/charts.spec.ts, package.json, scripts/e2e-docker-start
This targets the staging registry for running e2e tests in the release-2.11 branch.
- target the staging registry for running e2e tests in the release-2.11 branch
This is release maintenance. See #14364 for a reference to the change made for release-2.10
e2e tests should pass in CI
e2e tests should pass in CI
NA
=> [2.11] Migrate to staging registry for e2e tests

pkg/rancher-components/src/components/RcDropdown/RcDropdown.test.ts, pkg/rancher-components/src/components/RcDropdown/RcDropdown.vue, pkg/rancher-components/src/components/RcDropdown/useDropdownContext.ts
Fixes #14418
This can be tested in Harvester 1.6 or manually adding custom actions in dev:
<details>
<summary>Long actions list example</summary>
```
get _availableActions() {
const out = super._availableActions;
insertAt(out, 0, {
action:   'pause',
label:    this.t('fleet.gitRepo.actions.pause.label'),
icon:     'icon icon-pause',
bulkable: true,
enabled:  !!this.links.update && !this.spec?.paused
});
insertAt(out, 1, {
action:   'unpause',
label:    this.t('fleet.gitRepo.actions.unpause.label'),
icon:     'icon icon-play',
bulkable: true,
enabled:  !!this.links.update && this.spec?.paused === true
});
insertAt(out, 2, {
action:   'enablePollingAction',
label:    this.t('fleet.gitRepo.actions.enablePolling.label'),
icon:     'icon icon-endpoints_connected',
bulkable: true,
enabled: …
```
=> Fix RcDropdown overflow

shell/components/form/SecretSelector.vue, shell/components/form/labeled-select-utils/labeled-select-pagination.ts, shell/edit/logging.banzaicloud.io.output/index.vue, shell/edit/logging.banzaicloud.io.output/providers/awsElasticsearch.vue
Fixes #14849
- re-render the core controls, reset the selected values
- also
- fixed typing in labeled-select-pagination. something over the versions broke this. however.. a lot of the custom typing now isn't needed
- removed empty comment root output edit page
- removed debug line in awsElasticsearch
- install logging app
- nav go Logging --> Outputs --> create
- in output tab, leave Amazon Elasticsearch selected, in Access select a secret and key in both sections
- change the namespace at the top
- The selections should be cleared
- secrets in the new namespace should be shown in the access dropdowns (and their keys)
- tests with the elastic search output, however in theory all others are affected
- create rke2 cluster --> registries tab --> show advanced --> TLS Secret drop down (note …
=> Ensure SecretSelector resets on namespace change

shell/components/Resource/Detail/Metadata/index.vue
fixes #14996
When I re-introduced the ExtensionPanel I did it as a separate child of the Metadata component. This implicitly disables inheritAttrs so the class was no longer being passed.
We now explicitly bind the attrs to the appropriate child.
The masthead on any resource detail page
The masthead on any resource detail page
=> Resolves a spacing issue for metadata components

pkg/aks/components/CruAks.vue, pkg/gke/components/CruGKE.vue, shell/utils/__tests__/kontainer.test.ts, shell/utils/kontainer.ts
Fixes #14720
Fixes #11413 
**EDIT:
NOTE ABOUT AKS**
There is an open issue with one field in AKS, `linuxAdminUsername` https://github.com/rancher/rancher/issues/51297...a side effect of this bug is that PUT requests to update aks clusters always include this field. From what I can see, the UI code is still functioning correctly.
This PR fixes a mistake in the AKS and GKE edit pages that effectively prevented the upstream syncing functionality from running on save. That syncing functionality generally should be verified in AKS and GKE - I've described some scenarios to check below. This functionality has been enabled for EKS for a few releases.
This PR also fixes an issue where some edits would not be reflected when re-loading the UI for up to 5 minutes.
I also fixed an issue setting GKE …
=> Fix AKS, GKE upstream spec diff

cypress/e2e/po/components/tabbed.po.ts, cypress/e2e/po/detail/provisioning.cattle.io.cluster/cluster-detail.po.ts, cypress/e2e/po/side-bars/detail-drawer.po.ts, cypress/e2e/tests/pages/manager/cluster-manager.spec.ts, pkg/harvester-manager/models/harvesterhci.io.management.cluster.js, shell/components/Drawer/ResourceDetailDrawer/index.vue, shell/components/Tabbed/index.vue, shell/models/provisioning.cattle.io.cluster.js, shell/plugins/dashboard-store/resource-class.js
Fixes #14285 
Fixes #15005  
Modified detail drawer to only allow editing if that action is enabled for the resource. This prevented loading Ember pages for Harvester cluster from management cluster detail page.
Added a way to see if cluster should be editable.
Separated check if resource can be edited through config vs through yaml.
Only enabled config tab for Harvester when it is accessed through Virtualization Manager
Added a new canEdit property to the models that indicates that resource configuration should be editable.
For edit:
1. Create a standard user and add them as Cluster Member to a cluster.
2. Log in as that user
3. Cluster Management -> Check that 'Show Configuration' is enabled.
4. Verify that you can only view Config and YAML tabs but not edit them
5. Log in as admin
6. …
=> Fixed Harvester detail page through Cluster Management

shell/components/form/ResourceTabs/index.vue
Implements the tab styling in #13328
Updates the style of Tabs on detail pages to reflect the new design. I can provide a link to figma if you'd like.
Detail and edit pages with `ResourceTabs`
I know the Node resource has both an edit and detail page with resource tabs.
Same as above
Detail:
Edit:
=> Update resource table styling

cypress/e2e/po/components/tabbed.po.ts, cypress/e2e/po/detail/provisioning.cattle.io.cluster/cluster-detail.po.ts, cypress/e2e/po/side-bars/detail-drawer.po.ts, cypress/e2e/tests/pages/manager/cluster-manager.spec.ts, pkg/harvester-manager/models/harvesterhci.io.management.cluster.js, shell/components/Drawer/ResourceDetailDrawer/index.vue, shell/components/Tabbed/index.vue, shell/models/provisioning.cattle.io.cluster.js, shell/plugins/dashboard-store/resource-class.js
Fixes #15022 
Fixes #14969 
This is a backport. Please refer to the 2.13 issues
Added a new canEdit property to the models that indicates that resource configuration should be editable.
For edit:
Create a standard user and add them as Cluster Member to a cluster.
1. Log in as that user
2. Cluster Management -> Go to that cluster's detail page ->'Show Configuration'
3. Verify that you can only view Config and YAML tabs but not edit them
4. Log in as admin
5. Cluster Management ->  Go to that cluster's detail page ->'Show Configuration'
6. Verify that you can edit Config tab and view YAML tab
7. Go to local cluster -> workloads. Find one that allows editing YAML. 
8. Go to details -> 'Show configuration'
9. Verify that you can view and edit both Config and YAML tabs
For Harvester:
1. Import …
=> [2.12.1] Fixed Harvester detail page access through Cluster Management

shell/edit/networking.k8s.io.ingress/Certificate.vue, shell/edit/networking.k8s.io.ingress/DefaultBackend.vue, shell/edit/networking.k8s.io.ingress/IngressClass.vue, shell/edit/networking.k8s.io.ingress/Rule.vue, shell/edit/networking.k8s.io.ingress/RulePath.vue
This refactors form components that contain initialization logic in their data props so that they use patterns that are more idiomatic to Vue.
Fixes #14777
- Refactor data props in 
- shell/edit/networking.k8s.io.ingress/Certificate.vue
- shell/edit/networking.k8s.io.ingress/DefaultBackend.vue
- shell/edit/networking.k8s.io.ingress/IngressClass.vue
- shell/edit/networking.k8s.io.ingress/Rule.vue
- shell/edit/networking.k8s.io.ingress/RulePath.vue
The most complex changes in this PR involve shifting initialization logic outside of `data()` and into the `created()` hook. We will want to validate that the initialization order remains correct in cases where the `created()` hook already contains logic.
Assert that CRUD operations behave as expected for
- …
=> Remove complex init logic from ingress data props

shell/detail/workload/index.vue, shell/mixins/resource-fetch-api-pagination.js, shell/models/workload.js, shell/plugins/dashboard-store/actions.js
Blocked on https://github.com/rancher/dashboard/pull/14994
Fixes #14981
- Navigating from a list to a detail page resulted in missed resource updates
- In vai on world when we leave a list we forget the type completely (removes resources from store and unwatches it)
- However this process would happen after the navigation to the resource detail page and it's process to find and watch the resource
- This meant the page would show a stale resource that was removed from store. So even if we started a watch for it any updates would be on a different resource to the one used to show the detail view
- Fix is to forget type with beforeUnmount rather than unmounted
- Fix a gap in the watch mechanism
- This is slightly related to above, but wasn't the fix for it. However it's an improvement that …
=> Fix general and specific resource detail watch issues

pkg/rancher-prime/pages/registration.composable.test.ts, pkg/rancher-prime/pages/registration.composable.ts
Fixes #14940
Updated the logic as indicated in comment: https://github.com/rancher/dashboard/issues/14940#issuecomment-3136144587
Added case for errors and specifically the order mentioned.
https://github.com/user-attachments/assets/bbe00735-450b-4924-a0e8-7f9078414f2c
=> SCC - unclear error message for invalid registration code

shell/models/__tests__/node.test.ts, shell/models/cluster/node.js
Fixes #15050 
- fix issue with pods capacity on node list view
- add unit test
- remove tests that are duplicated in a different model unit test `management.cattle.io.node`
- Provision a RKE2 cluster
- once that cluster is online, edit that cluster and on `Advanced` - `Additional kubelet args` set the following value: `max-pods=1000`
- On cluster explorer, `nodes` list, check that pods percentage bar is correct
Before
After
=> fix issue with pods capacity on node list view

shell/components/Resource/Detail/Metadata/composables.ts, shell/components/Resource/Detail/Metadata/index.vue, shell/components/Resource/Detail/TitleBar/composables.ts, shell/components/Resource/Detail/TitleBar/index.vue
Puts the following extension points back into the masthead:
- PanelLocation.DETAILS_MASTHEAD
- PanelLocation.DETAIL_TOP
fixes #15021
The extension points were omitted from the new design. This puts them back in.
I used the https://github.com/rancher/ui-plugin-examples with a `yarn link @rancher/shell` to verify these changes. The plugin examples will add both panels to the gitrepo resource.
=> [backport 2.12.1] Resolved an issue where the new masthead broke the existing extension panels

pkg/rancher-components/src/components/RcDropdown/RcDropdown.test.ts, pkg/rancher-components/src/components/RcDropdown/RcDropdown.vue, pkg/rancher-components/src/components/RcDropdown/useDropdownContext.ts
=> [2.12.1] Fix RcDropdown overflow

.github/workflows/port-pr-bot.yaml
This adds `GH_TOKEN` the to Por PR step of the `port-pr-bot` workflow.
=> Add `GH_TOKEN` to `port-pr-bot` workflow 

pkg/rancher-prime/pages/registration.composable.ts
=> [backport v2.12.1] SCC Page fetches all secrets

shell/components/form/ClusterAppearance.vue
Fixes #14304 
Fixes #14305 
- fix keyboard focus being trapped in cluster appearance modal
- fixes cluster appearance modal not being activated by enter key
=> fix keyboard focus being trapped in cluster appearance modal

cypress/e2e/po/components/registries-tab.po.ts, shell/components/AdvancedSection.vue
Fixes #14306
- fix keyboard nav on show advanced in cluster create/edit
https://github.com/user-attachments/assets/c03a1543-31cf-44bf-9c70-cbff676dea0a
=> fix keyboard nav on show advanced in cluster create/edit

cypress/e2e/po/detail/provisioning.cattle.io.cluster/cluster-detail.po.ts, cypress/e2e/tests/pages/manager/cluster-manager.spec.ts, pkg/harvester-manager/models/harvesterhci.io.management.cluster.js, shell/components/Resource/Detail/Masthead/composable.ts, shell/components/Resource/Detail/Masthead/index.vue, shell/components/Resource/Detail/Metadata/IdentifyingInformation/identifying-fields.ts, shell/components/Resource/Detail/Page.vue, shell/components/Resource/Detail/TitleBar/index.vue, shell/detail/__tests__/provisioning.cattle.io.cluster.test.ts, shell/detail/configmap.vue, shell/detail/provisioning.cattle.io.cluster.vue, shell/detail/secret.vue, shell/models/provisioning.cattle.io.cluster.js
Fixes #14977
- Created the masthead component to make it easier to share across multiple pages.
- Added a slot so pages can control what gets rendered as additional actions
- Added the explore button back to the cluster management detail page using the slot
Configmap, secret and provisioning.cattle.io.cluster detail pages.
See above
The spacing between buttons are larger than the original but consistent with our new styling.
=> Adds support for for an additional actions slot in our titlebar/masthead

pkg/kubectl-explain/components/SlideInPanel.vue, pkg/rancher-components/src/components/Card/Card.vue, shell/components/SlideInPanelManager.vue
Fixes #13344 
- remove unsused focus trap from `Card` component 
- add refs wherever possible for focus trap init
From the 5 hits we got on code search for the focus trap init methods usage:
- `Card` component -> removed as there is no usage for focus trap with `Card` component
- `SlideInPanel` -> kube-explain built-in extension icon on header for resources - init element replaced. Cannot replace `initialFocus` element as it's not rendered in the DOM yet
- `AppModal` - cannot be replaced as the whole logic is conditional and there's no `ref` access on `setup` method
- `SlideInPanelManager` -> `Show configuration` action for any table row resource item - init element and `initialFocus` element replaced
- `PluginInfoPanel` -> Extension Slide In Panel - cannot use refs as elements aren't …
=> add refs wherever possible for focus trap init

shell/detail/__tests__/workload.test.ts, shell/detail/workload/index.vue
Fixes  https://github.com/rancher/dashboard/issues/15068
Added try ... catch, Prevents one bad ingress from breaking all logic.
when the input allIngresses array contains malformed or incomplete Ingress objects (e.g., missing spec.rules, http.paths, or backend.service.name or even with a defaultbackend), the function prematurely exits or throws an error. As a result, valid Ingresses that follow in the list are not evaluated, leading to incorrect or incomplete matching results...
Repro steps mentioned in the above issue...
=> Fix matchingingresses method

pkg/harvester-manager/machine-config/harvester.vue
Fixes #15171
When creating harvester downstream cluster, change `user & network data` to show by id ({namespace}/{name})
=> fix: show user data and network data by id

shell/edit/provisioning.cattle.io.cluster/tabs/etcd/index.vue
Fixes #14144 
I've introduced a regression with https://github.com/rancher/dashboard/pull/14557 when re-enabling etcd Automatic backups. This fixes it
Cluster management -> Create any RKE2 cluster -> etcd
Enable 'Save Backups to S3'
Disable 'Automatic Backups'
Enable 'Automatic Backups'
'Save Backups to S3' radio button should have 'Disable' selected
None
=> Fixed radiobutton when enabling and disabling automatic backups

shell/mixins/__tests__/chart.test.ts, shell/mixins/chart.js, shell/pages/c/_cluster/apps/charts/chart.vue, shell/store/__tests__/catalog.test.ts, shell/store/catalog.js
Fixes #15144 
`showDeprecated` flag was added to the store getter `calatog/chart` when the checkbox "Show deprecated apps" was added to the UI in 2.9 in order to show/hide deprecated charts. The url query parameter(`?deprecated` or `?deprecated=true`) was missing in a couple of places such as when we get the versions from the store or when we go to the install/upgrade page.
- Added missing deprecated parameter to `'catalog/version'` and `install` method
- Unit tests
Make sure you can install deprecated charts
Check Explorer => Cluster tools page, you should not see a deprecated chart by default like `Istio`, but by manually adding `deprecated=true` to the url you should be able to see it
https://github.com/user-attachments/assets/edb38efc-c680-4c3c-8fb3-9e1cedf8686c
=> Fix deprecated charts not being returned from store

shell/edit/provisioning.cattle.io.cluster/rke2.vue
The `credentialId` was mutated into `credential` in 32b6280d4bb9f8a49ce8ac661c6822a5b7bfd44e. This had the unintended side effect of the footer being hidden for standard users who are cluster owners.
Fixes #15216 
- Replace `credential` with `credentialId` in the `hideFooter()` computed prop
It looks like this was unintentionally changed in #14829. If we do wish to change the logic, we must do so in a more intentional way. 
See the attached issue for the repro steps.
NA - this is resolving an identified regression.
NA
=> Use `credentialId` instead of `credential` in `hideFooter()` computed

pkg/harvester-manager/machine-config/harvester.vue
Fixes #15234
- lots more detail in the issue
- add a try/catch around vai in host/imported harvester cluster
- if this fails it just reverts back to previously (fetch all configmaps)
- as per issue
- no other areas
- see 'expected' section of issue
=> Fallback to legacy configmaps request when vai state is underterminable

shell/edit/monitoring.coreos.com.alertmanagerconfig/index.vue, shell/edit/monitoring.coreos.com.alertmanagerconfig/receiverConfig.vue, shell/utils/alertmanagerconfig.js
Fixes #14946
- Errors are all around Monitoring --> Alerting --> Create/Edit/View AlertmangerConfigs page + view AlertmanagerConfigs Add Reciever page
- don't try to find a resource if in create mode
- add additional comments to confusing code
- don't try to validate values that won't be there on create
- ensure schema definitions are cached correctly (no id)
- a lot of these bugs are currently harmless, given the areas they affect are hidden by https://github.com/rancher/dashboard/issues/14944
Things i've picked up not solved by this PR
- `Alerting` group in `Monitoring` group is misaligned
- Edit component is miss-used as a Detail page, which introduces weird routing everywhere
- Edit component tries to use ResourceTable with non-resources. Think this is because it wants actions
- …
=> Fix issues in AlertManageConfig Receivers page

pkg/rancher-prime/pages/registration.composable.test.ts, pkg/rancher-prime/pages/registration.composable.ts
Fixes #15232
Fixes #14940
Fixes #14985
Updated logic so the message would be always provided by the `currentCondition` and will stop on certain types.
This will remove entirely the implementation set in place with https://github.com/rancher/dashboard/issues/14940
https://github.com/user-attachments/assets/d9e6a1bd-e3d4-4285-9a2c-815fdbc25806
=> Update last update check to point last conditions and ignore the status

shell/assets/translations/en-us.yaml, shell/pages/c/_cluster/manager/drivers/kontainerDriver/index.vue
Fixes #15257
This PR adds the Ember deprecation banner to the kontainer drivers page.
It is only shown if the user is an admin.
Note: The banner text is the same as was used in the Ember page - we are moving it here to be less intrusive. The work to remove it from the Ember UI is in a separate PR in the ui repository.
As an admin user, go to the kontainer driver page and check that the banner shows.
As a non-admin (e.g. standard user), go to the kontainer driver page and check that the banner does not show.
=> Show Ember deprecation banner on kontainer drivers page only when admin

shell/mixins/chart.js, shell/models/chart.js
Fixes #15144 
This PR addresses two other places where there were issues with the deprecated charts that was not considered on the [previous PR](https://github.com/rancher/dashboard/pull/15149):
- cancel redirect logic should consider the deprecated status
- installing a deprecated chart from cluster tools should be working
https://github.com/user-attachments/assets/1299a554-4fe5-49f8-93ff-8e8f5e88c2b1
=> Deprecated charts - fix cancel redirect and installation from the tools page

shell/edit/fleet.cattle.io.cluster.vue
Fixes #15284
Cached resource's re-watch was introduced in https://github.com/rancher/dashboard/pull/15011.
However, the `dispatch('watch')` call  triggers an `unwatch` with missing `type` and `id` params.
It seems we have a raise condition or a bug in the re-watch mechanism.
[Screencast from 2025-09-02 10-15-44.webm](https://github.com/user-attachments/assets/b705bba3-eac3-47fa-805a-7794031a7e56)
UPDATE @richard-cox :
When the `ui-sql-cache` flag (pagination) is `disabled`, the UI shows the updates, when enabled it doesn't.
Using a local UI instance on `master` branch, I compared the websocket incoming messages with the 2 flag conditions after adding a new label and hitting `save` in the edit form.
Left enabled, right disabled:
In the left side - no updates, flag enabled - there is a …
=> Fix missing Fleet clusters updates after saving

shell/assets/translations/en-us.yaml, shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/edit/provisioning.cattle.io.cluster/tabs/etcd/S3Config.vue, shell/edit/provisioning.cattle.io.cluster/tabs/etcd/index.vue, shell/utils/__tests__/setting.test.js, shell/utils/validators/formRules/index.ts, shell/utils/validators/setting.js
Fixes #14800 
Backport of https://github.com/rancher/dashboard/pull/14557
=> [2.12] Added input validation to s3 endpoint field in cluster

shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #15329 
This PR fixes an issue saving a node driver cluster from the yaml view, either on initial creation or when adding a new machine pool.
Provisioning node driver clusters involves creating more than just the provisioning.cattle.io.cluster resource: the UI will also create a cloud-provider-specific machine config resource and add a reference to it in the provisioning cluster spec. This complicates the edit-as-yaml experience, which only shows the provisioning cluster resource.
When users click the 'edit as yaml' button, the UI will save all machine configs and add references to the provisioning cluster resource. When a user clicks 'save,' whether in yaml or form mode, the machine configs are saved, then the provisioning cluster resource is saved.
If editing an existing cluster, …
=> Fix error when creating node driver clusters from yaml view

.github/workflows/port-pr.yaml, .github/workflows/scripts/pr-gh-project.js
This fixes an issue where the `pr-gh-project` bot will update the milestone for backports raised by the `port-pr` bot.
This also adds a new, optional, target issue arg to the backport bot command. 
- Prevent updating milestone if PR was raised by bot
- Accept optional issue number in backport bot
`port-pr` has been migrated to a github app, which means that it now triggers other github actions, including `pr-gh-project`. 
The updated syntax for triggering the backport bot should be `/backport ${target-milestone} ${target-branch} ${target-issue}`.
This change affects both the `port-pr` & `pr-gh-project` workflows. We will need to ensure the following:
- Backports can accept an optional milestone
- PRs raised by the backport bot adds a closing keyword to the PR body that targets the …
=> Prevent `pr-gh-project` from updating milestone for backport PRs raised by the bot

storybook/.storybook/main.ts, storybook/.storybook/preview.ts, storybook/package.json, storybook/src/assets/style.scss, storybook/yarn.lock
The themeing in storybook was a little off. I noticed that the changes to rancher was causing the conflict.
I also made it easier to switch between the themes and get the background colors to change in the stories.
Just storybook stories in both docs and examples
Same as above
https://github.com/user-attachments/assets/dd2d5a4d-8765-4386-842b-ae13f5abb1fc
=> Fixing the storybook theme to work with the changes to the dashboard themes

shell/config/product/explorer.js
=> [backport v2.12.2] Give more intuitive name to the SCC operator deployment in the side menu

shell/store/type-map.js
fixes #15402
Reintroducing a stub implementation of `type-map/hasGraph` for backwards compatibility of extensions.
Extensions with detail pages effectively have a copy of @shell/ResourceDetail/index.vue which checks hasGraph. If they get built with a new shell they'll be fine but without it they'll break.
Details pages on extensions like Elemental.
=> Reintroducing a stub implementation of `type-map/hasGraph` for backwards compatibility of extensions.

shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/machine-config/components/GCEImage.vue, shell/machine-config/google.vue
Fixes #15417
Adding a new machine pool was being treated as edit and not creation, so I was not fetching and setting the required information.
Modified rke2.vue to assign projectId from existing pool to all new pools
Modified google.vue and GCEImage.vue files to differentiate between editing and creation better.
Instead of re-authenticating with projectId and credentials like we do for GKE, I am taking projectId from an existing pool since we already confirmed that it is valid during provisioning, and we do not re-check credentials for any other provider on edit.
1. Enable Google GCE driver
2. Provision GCE instance. Make sure provisioning was successful
3. Edit -> Machine Pools -> Make sure existing pool was loaded successfully and you can modify it
4. Add new pool. No errors should be …
=> Fixed adding a new machine pool to existing GCE instance

pkg/rancher-components/src/components/Card/Card.vue, pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue, pkg/rancher-components/src/components/Form/Radio/RadioButton.vue, pkg/rancher-components/src/components/Form/Radio/RadioGroup.vue, pkg/rancher-components/src/components/LabeledTooltip/LabeledTooltip.vue, shell/assets/styles/global/_tooltip.scss
This scopes css for all components in Rancher Components so that css will apply only to elements of the components in question. 
Fixes #15422
- Add scoped attribute to all components in Rancher Components
Since css in these components were applied globally when the components were rendered, there's a chance that other components could regress as a result of adding the scoped attribute. The only area where I see the highest risk of regression is in `LabeledTooltip.vue`, where we apply styles to `v-popper` via `.v-popper__popper.v-popper--theme-tooltip {`. 
Checkboxes, radio buttons, radio groups, cards and labeled tooltips should all render properly. We need to confirm that other weren't inadvertently relying on one of these styles being active while any of the given components were …
=> Add scoped css attribute to Rancher Components

pkg/gke/components/Config.vue, pkg/imported/components/Basics.vue, shell/components/PodSecurityAdmission.vue, shell/components/form/ProjectMemberEditor.vue, shell/edit/provisioning.cattle.io.cluster/tabs/AddOnAdditionalManifest.vue, shell/edit/provisioning.cattle.io.cluster/tabs/AddOnConfig.vue, shell/edit/provisioning.cattle.io.cluster/tabs/Basics.vue, shell/edit/provisioning.cattle.io.cluster/tabs/etcd/S3Config.vue, shell/edit/provisioning.cattle.io.cluster/tabs/registries/index.vue, shell/edit/provisioning.cattle.io.cluster/tabs/upgrade/DrainOptions.vue
Fixes #14481
Add `mode` to a handful of input components that needed the prop.
There are still a large number of input components missing this prop. Most of the remaining ones are in locations where the mode doesn't make sense such as dialogs, the chart index page, settings pages.
The areas outlined in https://github.com/rancher/dashboard/issues/14481
- GKE Config area
- Imported Basics accordion
- Pod Security Admission for namespace `Show Configuration`
- All the tabs when viewing the `Show Configuration` of an rke2 cluster
The areas outlined in https://github.com/rancher/dashboard/issues/14481
- GKE Config area
- Imported Basics accordion
- Pod Security Admission for namespace `Show Configuration`
- All the tabs when viewing the `Show Configuration` of an rke2 cluster
=> Ensuring Checkbox components have the `mode` prop where appropriate

shell/components/PromptRemove.vue
When clicking on the cluster name it will now select the entire name.
Fixes #8825
Followed the suggestion mentioned here https://github.com/rancher/dashboard/issues/8825#issuecomment-3284624736
The delete cluster prompt
The delete cluster prompt
https://github.com/user-attachments/assets/653e8806-a56f-4d23-ae87-38923c15ca94
=> Making it easier for a user to select a name to confirm deleting a resource

shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/machine-config/components/GCEImage.vue, shell/machine-config/google.vue
Fixes #15447 
Backport of https://github.com/rancher/dashboard/pull/15446
=> [2.12] Fixed adding a new machine pool to existing GCE instance

docusaurus/docs/extensions/api/table-columns.md, docusaurus/docs/extensions/performance/scaling/lists.md, shell/components/ResourceTable.vue, shell/config/product/explorer.js, shell/core/plugin.ts, shell/core/types.ts, shell/plugins/steve/steve-pagination-utils.ts
Fixes #15480
- add option to supply an additional column definition to addTableColumn to use when SSP is enabled
Additionally
- update list of compatible columns to search/sort on given BE fixes being resolved
- this is designed to support running old extensions in new dashboard
- additional param is not supplied
- stale ResourceTable should not encounter new format of config (which would need an updated shell with non-stale ResourceTable)
- also designed to support running new extensions in old dashboards
- the new param is just ignored
- examples have been added - https://github.com/rancher/ui-plugin-examples/pull/72
with ui-sql-cache off and on
- run dashboard from this PR
- install the extenions-api-demo from https://github.com/rancher/ui-plugin-examples/pull/72
- visit the configmap, …
=> Update addTableColumn to support server-side pagination

shell/utils/validators/formRules/__tests__/index.test.ts, shell/utils/validators/formRules/index.ts
=> [2.12.3] Fleet allow SSH url with numeric ports

cypress/jenkins/Jenkinsfile_multi
Fixes #https://github.com/rancher/qa-tasks/issues/2027
Replaced dynamic K3s version fetching with static versions that are passed in JJB. This PR relies on https://github.com/rancherlabs/jenkins-job-builder/pull/888
=> [Automation] update k8s versions support for Jenkins

cypress/e2e/tests/pages/virtualization-mgmt/harvester.spec.ts, shell/components/form/SimpleSecretSelector.vue
Fixes #15517
Change `allSecretsSettings.mapResult` and `paginateSecretsSetting.mapResult ` to   `allSecretsSettings.updateResources` and `paginateSecretsSetting.updateResources ` in `SimpleSecretSelector.vue` file, Because the caller (ResourceLabeledSelect.vue file) has already been modified.
=> fix(SimpleSecretSelector): fix Secret with Auth Password display error

cypress/e2e/tests/pages/manager/jwt-authentication.spec.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1974
There's is a URL mismatch between VAI on/off environments (when calling `fetchJWTAuthentication` intercept). Jenkins CI runs with VAI disabled, causing a URL mismatch.
Expected: /v1/management.cattle.io.clusterproxyconfigs?pagesize=100000 (VAI on)
Actual: /v1/management.cattle.io.clusterproxyconfigs (VAI off)
Updated the intercept pattern to handle both query parameter variations. Tested fix in both VAI enabled and disabled environments.
=> fix jwt auth tests p2

pkg/rancher-prime/config/constants.ts, pkg/rancher-prime/index.ts, pkg/rancher-prime/pages/registration.composable.test.ts, pkg/rancher-prime/pages/registration.composable.ts
Fixes #15580
Fixes #15581
Notification is now removed on:
- succesful registration
- initialization to cleanup leftovers
https://github.com/user-attachments/assets/1d6c0d41-d790-43cc-b6ff-24b61ab7c3c4
=> SCC Registered users still see notification

shell/components/form/SecretSelector.vue
Fixes # https://github.com/harvester/harvester/issues/6107
In harvester UI, there doesn't have `cluster` inStore that causes ResourceLabeledSelect.vue unable to fetch the secret data back.
Change the logic to use `harvester` inStore when using in harvester UI.
Harvester create logging Flow 
Rancher create logging Flow
=> fix: use harvester inStore to GET secret data when creating Flow on Harvester
