assets/styles/base/_basic.scss, components/SortableTable/index.vue, components/cru/rio.cattle.io.v1.router/Rule.vue, components/cru/rio.cattle.io.v1.router/index.vue, components/form/Checkbox.vue, components/form/RadioButton.vue, utils/object.js
box shadow on selected input 
re-ordering rules within routes works
default checkbox and radio
=> fix reordering

components/cru/rio.cattle.io.v1.router/Destination.vue, components/cru/rio.cattle.io.v1.router/Match.vue, components/cru/rio.cattle.io.v1.router/Redirect.vue, components/cru/rio.cattle.io.v1.router/Rule.vue, components/cru/rio.cattle.io.v1.router/index.vue, components/form/KeyValue.vue
added 'remove' button for multiple destinations 
selecting destination service version actually does something (lol)
removed errant custom checkbox I forgot previously
some kinda error info if router creation doesn't work
=> remove button for weighted destinations

components/cru/rio.cattle.io.v1.router/Destination.vue, components/cru/rio.cattle.io.v1.router/Match.vue, components/cru/rio.cattle.io.v1.router/Rule.vue, components/cru/rio.cattle.io.v1.router/index.vue
repopulate form correctly in 'edit' mode
=> fix editing

components/cru/rio.cattle.io.v1.router/Rule.vue, components/form/InputWithSelect.vue
un-break router creation page
select/text input combo dropdown collapses as expected when clicked away from
=> click away from select

components/cru/rio.cattle.io.v1.router/Headers.vue, components/cru/rio.cattle.io.v1.router/Rule.vue, components/cru/rio.cattle.io.v1.router/index.vue, components/form/InputWithSelect.vue
* remove button removes
* cancel button cancels
* header add/set/remove dropdowns are not searchable
* 'fordward' changed to 'forward'
* rule position numbers start at 1
* errors are displayed at bottom of page
* rewrite headers section completely hidden if redirect selected
=> fix remove button

components/cru/rio.cattle.io.v1.router/Rule.vue
Fixes issue #51 - form inputs need to be clicked twice
=> radio button click twice

assets/styles/vendor/vue-select.scss, components/cru/rio.cattle.io.v1.router/Destination.vue, components/cru/rio.cattle.io.v1.router/Fault.vue, components/cru/rio.cattle.io.v1.router/Headers.vue, components/cru/rio.cattle.io.v1.router/Rule.vue, components/cru/rio.cattle.io.v1.router/index.vue
* fixes issue #50 - headers are moved outside inputs for destinations and header rewrite
* fixes alignment of dropdown+string input text
=> Multi-service destination headers outside inputs

components/cru/rio.cattle.io.v1.router/Match.vue, components/cru/rio.cattle.io.v1.router/Rule.vue, components/cru/rio.cattle.io.v1.router/index.vue, components/formatters/RouterDestination.vue, components/formatters/RouterMatch.vue, config/table-headers.js
router table with cols per: https://xd.adobe.com/view/3ad96e6a-2043-4dfc-7f39-c94dc27f25e5-4ce8/
clean out more empty fields before saving router
=> Router list view

components/Card.vue, components/cru/rio.cattle.io.v1.service/Top.vue, components/cru/rio.cattle.io.v1.service/index.vue, components/cru/rio.cattle.io.v1.stack.vue, components/form/Checkbox.vue, config/demoSpecs.js, mixins/create-edit-view.js, pages/rio/_resource/create.vue, pages/rio/discover.vue
per: https://xd.adobe.com/view/81fe5a29-d025-43f1-73c9-45dd94023348-f7cf/
* 'Create stack from GH' links to prepopulated create stack page with riofile demo: https://github.com/rancher-max/riofile-demo.git
* 'Deploy service with Dockerfile' links to prepopulated create service page with rancher demo: 
https://github.com/ibuildthecloud/rancher-demo
* download icon links to git repos
* Other two demos unavailable
=> 'discover rio' page

components/cru/rio.cattle.io.v1.service/index.vue, components/form/NameNsDescription.vue
#90 - default create-service ns picker to first of currently selected namespaces
#92 - hide create-service tabs and add button to toggle them
=> default ns and hide additional form fields

components/cru/rio.cattle.io.v1.router/Rule.vue, components/form/InputWithSelect.vue
*  #86 - make dropdown the same height as other inputs 
* dropdown chevron in dropdown/string combo spins like other dropdowns
=> router form fixes

components/SortableTable/THead.vue, components/detail/rio.cattle.io.v1.service.vue, components/formatters/BadgeState.vue
* #109 -service detail view endpoints are in their own table
* aforementioned endpoints are links now
=> Service detail view

components/cru/rio.cattle.io.v1.router/Destination.vue, components/formatters/RouterDestination.vue, components/formatters/RouterMatch.vue
* router destination has 'app' instead of 'service' key
* router list shows — for empty columns
=> router destination fix

plugins/norman/resource-instance.js
=> download yaml function downloads yamls

pages/auth/setup.vue
=> re-added suggested password

components/ContainerExec/Logs.vue, components/ContainerExec/ShellSocket.vue
#117 
* modal sized to take up (almost) full screen 
* 'x' in top-right closes modal
* clicking outside modal does not close modal
* connection status is explicitly stated
* modal has a border and stronger box-shadow
=> cleanup modal styling

components/RioDetail.vue, components/cru/rio.cattle.io.v1.service/Top.vue, components/cru/rio.cattle.io.v1.service/index.vue
=> Fix tab behavior in service clone/edit 

components/cru/rio.cattle.io.v1.router/Rule.vue, components/cru/rio.cattle.io.v1.router/index.vue, components/form/NameNsDescription.vue
=> preserve uuid to allow reordering route rules

components/RioDetail.vue
Re-add default to '_VIEW' when mode isn't explicitly given in route query
=> realMode defaulting

components/nav/Type.vue
https://github.com/rancherlabs/dashboard/issues/119
=> 119 fix nav resize

assets/styles/global/_button.scss
https://github.com/rancherlabs/dashboard/issues/112
=> 112 action menu fix

plugins/norman/mutations.js, store/auth.js, store/index.js
#142 - Norman store data ('types') cleared on logout
=> clear norman store on logout

components/Card.vue, components/PromptRemove.vue, layouts/default.vue, models/core.v1.pod.js, pages/index.vue, plugins/norman/actions.js, plugins/norman/resource-instance.js, store/actionMenu.js
=> open modal to confirm resource delete

components/cru/rio.cattle.io.v1.router/Destination.vue, components/cru/rio.cattle.io.v1.router/Rule.vue, components/cru/rio.cattle.io.v1.router/index.vue
=> destination dropdown is namespace specific

components/cru/core.v1.configmap.vue, components/cru/core.v1.secret.vue, components/cru/rio.cattle.io.v1.externalservice.vue, components/cru/rio.cattle.io.v1.router/index.vue, components/cru/rio.cattle.io.v1.service/Top.vue, components/cru/rio.cattle.io.v1.service/index.vue, components/cru/rio.cattle.io.v1.stack.vue, components/form/LabeledSelect.vue, components/form/NameNsDescription.vue, mixins/create-edit-view.js
=> create new NS in other create forms

assets/styles/global/_labeled-input.scss, components/cru/core.v1.namespace/ResourceQuota.vue, components/cru/core.v1.namespace/index.vue, components/cru/rio.cattle.io.v1.router/Destination.vue, components/cru/rio.cattle.io.v1.service/Labels.vue, components/form/KeyValue.vue, components/form/NameNsDescription.vue, config/friendly.js, config/packages.js, config/types.js, mixins/create-edit-view.js, pages/auth/login.vue, pages/explorer/_group/_resource/create.vue, pages/explorer/_group/_resource/index.vue, utils/object.js
=> namespace create

assets/styles/global/_button.scss, components/SortableTable/index.vue, components/cru/admin.rio.cattle.io.v1.publicdomain.vue, components/cru/core.v1.configmap.vue, components/cru/core.v1.secret.vue, components/cru/rio.cattle.io.v1.externalservice.vue, components/cru/rio.cattle.io.v1.router/Rule.vue, components/cru/rio.cattle.io.v1.service/Top.vue, components/form/Checkbox.vue, components/form/Footer.vue, components/formatters/BadgeState.vue
https://github.com/rancherlabs/dashboard/issues/163
=> button, alignment and checkbox issues

components/cru/rio.cattle.io.v1.router/Rule.vue, components/cru/rio.cattle.io.v1.router/index.vue, components/formatters/RouterMatch.vue
=> create router without weighted destination

assets/styles/global/_labeled-input.scss, components/PromptRemove.vue, components/cru/core.v1.namespace/index.vue, components/cru/rio.cattle.io.v1.router/Rule.vue, components/form/KeyValue.vue, plugins/norman/actions.js, plugins/norman/resource-instance.js, store/actionMenu.js, utils/download.js
=> bulk delete

components/cru/admin.rio.cattle.io.v1.publicdomain.vue, components/cru/rio.cattle.io.v1.externalservice.vue, components/cru/rio.cattle.io.v1.router/Fault.vue, components/cru/rio.cattle.io.v1.router/Match.vue, components/cru/rio.cattle.io.v1.router/StringMatch.vue, components/cru/rio.cattle.io.v1.service/Top.vue, components/cru/rio.cattle.io.v1.service/Upgrading.vue, components/form/InputWithSelect.vue, models/rio.cattle.io.v1.service.js
#197  
#171  
#172  
#198 
#200
#203 
#201  defaults to branch 'master' and dockerfile path '/Dockerfile'
#187 swapped out <select> for vue-select, which doesn't support grouping options :\
=> various creation bugs

assets/styles/vendor/vue-select.scss, components/cru/admin.rio.cattle.io.v1.publicdomain.vue, components/form/InputWithSelect.vue
Styled dropdowns to match single-option dropdowns from router creation page
Fixed text alignment in select/string input combos
=> Publicdomain styling

components/PromptRemove.vue, components/RioDetail.vue, components/cru/core.v1.namespace/ResourceQuota.vue, components/cru/core.v1.namespace/index.vue, components/form/NameNsDescription.vue, components/form/UnitInput.vue, mixins/create-edit-view.js, pages/explorer/_group/_resource/_id.vue, plugins/norman/actions.js, plugins/norman/resource-instance.js
=> namespace edit/cone

assets/styles/global/_form.scss, assets/styles/vendor/vue-select.scss, components/RioDetail.vue, components/cru/rio.cattle.io.v1.router/Destination.vue, components/cru/rio.cattle.io.v1.router/Headers.vue, components/cru/rio.cattle.io.v1.router/Match.vue, components/cru/rio.cattle.io.v1.router/Rule.vue, components/cru/rio.cattle.io.v1.router/StringMatch.vue, components/cru/rio.cattle.io.v1.router/index.vue, components/cru/rio.cattle.io.v1.service/Top.vue, components/cru/rio.cattle.io.v1.service/Upgrading.vue, components/cru/rio.cattle.io.v1.service/index.vue, components/cru/rio.cattle.io.v1.stack.vue, components/detail/rio.cattle.io.v1.service.vue, components/form/Checkbox.vue, components/form/InputWithSelect.vue, components/form/KeyValue.vue, components/form/NameNsDescription.vue, config/packages.js, mixins/labeled-form-element.js
#199 
#167 - focus 'Name' field on load in all create forms
#222
#207
#206
#208
#226 
#227
=> Bugfix create forms generally

components/cru/admin.rio.cattle.io.v1.publicdomain.vue, components/cru/rio.cattle.io.v1.externalservice.vue, components/form/Checkbox.vue, components/form/Target.vue, models/rio.cattle.io.v1.externalservice.js
=> external service points to app/version not service

components/cru/core.v1.namespace/ResourceQuota.vue, components/cru/core.v1.namespace/index.vue
=> edit namespace

assets/translations/en-us.yaml, components/nav/Footer.vue, config/cookies.js, config/footer.js, config/packages.js, layouts/default.vue, middleware/authenticated.js, middleware/i18n.js, nuxt.config.js, package.json, pages/auth/login.vue, pages/index.vue, pages/prefs.vue, plugins/i18n.js, plugins/norman/resource-instance.js, plugins/shortkey.js, store/i18n.js, store/prefs.js, tsconfig.json, utils/socket.ts, yarn.lock
- Reorganize header
- i18n framework
- `dev` preference for lang toggle and View in API action
- Fix web socket client SSR
- Shortcut keys plugin
=> i18n, new header

config/friendly.js, config/packages.js, config/table-headers.js, config/types.js, layouts/default.vue, models/user.js, pages/settings/_resource/index.vue, plugins/norman/resource-instance.js
#263 
* added settings package
* users list view per: https://xd.adobe.com/view/9c156c12-cdea-4121-683a-454e3d63be31-ea24/
=> user list page

components/Tabbed/index.vue, config/friendly.js, config/packages.js, detail/core.v1.namespace.vue, edit/core.v1.namespace/ResourceQuota.vue, layouts/default.vue
Proposed changes
======
Exposes cluster package. The cluster api is not finished yet so the cluster package still contains some duplicate entries.
Exposes the namespace detail page. I would imagine this API will change in the future to be contained under the cluster so I've placed it under the cluster package currently. 
Removes border styles on the tabbed component. The new mocks show the tables as borderless. 
Types of changes
======
New Feature
Linked Issues
======
rancher/dashboard#270
Further comments
======
=> Namespace Detail

components/formatter/RouterDestination.vue, edit/rio.cattle.io.v1.router/Redirect.vue
=> router list view 'target' column includes links

components/RioDetail.vue, components/form/Checkbox.vue, components/form/InputWithSelect.vue, components/form/KeyValue.vue, components/form/NameNsDescription.vue, components/form/Target.vue, edit/rio.cattle.io.v1.router/Destination.vue, edit/rio.cattle.io.v1.router/Headers.vue, edit/rio.cattle.io.v1.router/Match.vue, edit/rio.cattle.io.v1.router/Rule.vue, edit/rio.cattle.io.v1.router/index.vue, mixins/labeled-form-element.js
=> fix view=>edit route

components/form/InputWithSelect.vue, components/form/KeyValue.vue, components/form/NameNsDescription.vue, mixins/labeled-form-element.js
fixing the fix I made before because it wasn't fully fixed
=> remove injected prop from generic components

edit/rio.cattle.io.v1.router/Destination.vue, edit/rio.cattle.io.v1.router/Match.vue, edit/rio.cattle.io.v1.router/Rule.vue
On third thought, injected props are ill-suited to this purpose, and have been removed everywhere
=> remove all 'disabledInput' injected prop

assets/styles/themes/_light.scss, components/Alert.vue, components/ConsumptionGauge.vue, components/CopyToClipboardText.vue, components/DetailTop.vue, components/DetailTopColumn.vue, components/Layout/Stack/HStack.vue, components/Layout/Stack/VStack.vue, components/Layout/Stack/index.vue, components/PercentageCircle.vue, components/ResourceTable.vue, components/RioDetail.vue, components/formatter/PercentageBar.vue, config/friendly.js, config/table-headers.js, detail/core.v1.node.vue, models/core.v1.node.js, pages/rio/_resource/index.vue
=> Adding the 'node' list and detail view

config/packages.js, layouts/default.vue
hide broken links from side nav: 
* unavailable cluster-level resources
* app mesh when linkerd is not enabled
=> sidenav broken links

.storybook/main.js, .storybook/preview.js, assets/fonts/icons/style.scss, assets/styles/base/_basic.scss, assets/styles/fonts/_fira.scss, assets/styles/fonts/_icons.scss, components/ActionMenu.vue, components/Card.stories.js, components/Loading.vue, components/ResourceYaml.vue, components/SortableTable/index.vue, components/charts/LinePlot.vue, components/form/InputWithSelect.vue, components/form/Target.vue, components/formatter/BadgeState.vue, components/formatter/RouterDestination.vue, config/packages.js, edit/rio.cattle.io.v1.router/Headers.vue, edit/rio.cattle.io.v1.router/Match.vue, edit/rio.cattle.io.v1.router/index.vue, layouts/default.vue, nuxt.config.js, package.json, stories/Card.stories.js, stories/DesignSystems.stories.js, yarn.lock
Proposed changes
======
This PR adds StorybookJS as a dependency which allows us to host a nice style/component guide which I believe will make new components and styles more discoverable and centralized.
Additionally, in order to get storybook working I needed to update several dependencies and remove others. I've removed an old babel-core dependency and upgraded us to babel 7 which doesn't reveal any side effects. I've upgraded some outdated dependencies and removed an unneeded resolution with the core upgrade. I have also upgraded Nuxt to use core 3 from 2 and changed the configuration.
Also note, I had to change the SCSS import paths to remove the alias so we can import `app.scss` into our stories. I think we can piggyback on the babel config through storybook to make these alias work …
=> Add Storybookjs

components/ConsumptionGauge.stories.js, components/ConsumptionGauge.vue, components/PercentageBar.stories.js, components/PercentageBar.vue, components/PercentageCircle.stories.js, components/PercentageCircle.vue, components/formatter/PercentageBar.vue
I also refactored PercentageBar so that it can  be a resusable
component. The reusable component is then thinly wrapped by
the formatter.
=> Defining stories for some components

assets/styles/themes/_light.scss, components/SortableTable/THead.vue, components/SortableTable/index.vue, config/friendly.js, config/table-headers.js, detail/core.v1.configmap.vue
=> Create the ConfigMap detail view

components/form/Target.vue, edit/rio.cattle.io.v1.router/Headers.vue, edit/rio.cattle.io.v1.router/Match.vue, edit/rio.cattle.io.v1.router/index.vue
I thought I'd removed this (unnecessary) prop from everywhere but apparently I did not
=> remove disabledInput prop

.gitignore, components/RbacPermissions.vue, components/RioDetail.vue, components/TabbedLinks/index.vue, components/TableRbacRules.vue, components/formatter/IconIsDefault.stories.js, components/formatter/IconIsDefault.vue, config/friendly.js, config/packages.js, config/table-headers.js, config/types.js, detail/rbac.authorization.k8s.io.v1.clusterrole.vue, detail/rbac.authorization.k8s.io.v1.role.vue, edit/rbac.authorization.k8s.io.v1.clusterrole.vue, edit/rbac.authorization.k8s.io.v1.role.vue, layouts/default.vue, nuxt.config.js, pages/rbac/_resource/_id.vue, pages/rbac/_resource/_namespace/_id.vue, pages/rbac/_resource/create.vue, pages/rbac/roles.vue, pages/rbac/roles/cluster.vue, pages/rbac/roles/global.vue, pages/rbac/roles/index.vue, plugins/norman/resource-instance.js
Adds the Cluster and Global RBAC roles sections.
Also adds config change to run lint on save.
=> Security/RBAC Cluster and Global Roles pages

components/LabelsAndAnnotations/Editor.stories.js, components/LabelsAndAnnotations/Editor.vue, components/LabelsAndAnnotations/Tabs.stories.js, components/LabelsAndAnnotations/Tabs.vue, detail/core.v1.namespace.vue, edit/core.v1.namespace/index.vue
These components are going to be used in more than one spot so it made sense to extract them.
=> Creating LabelsAndAnnotations Editor/Tabs

components/formatter/Port.vue, edit/workload/WorkloadPorts.vue, edit/workload/index.vue, pages/c/_cluster/workloads/create.vue, pages/c/_cluster/workloads/index.vue
* define ports during workload creation
* view ports in workload list
* return to workload list after creating successfully or clicking 'cancel' button
=> workload - ports

components/form/InputWithSelect.vue, components/form/LabeledInput.vue, components/form/NameNsDescription.vue, components/formatter/Endpoints.vue, config/table-headers.js, edit/workload/Command.vue, edit/workload/ValueFromResource.vue, edit/workload/WorkloadPorts.vue, edit/workload/index.vue, pages/c/_cluster/workloads/index.vue
#330 
list: 
* show endpoints, not ports
* age sorts by creation time
create/edit:
* remove autocomplete from name field
* focus 'name' field initially
* remove description placeholder when focused
* focus host port field initially
* focus type field in value from resource row initially
* add 'remove' button to Add from Resource section
=> workload UI issues

pages/c/_cluster/workloads/_namespace/_id.vue, pages/c/_cluster/workloads/create.vue
=> redirect after create

components/Tabbed/index.vue, components/form/RadioGroup.vue, edit/workload/Security.vue, edit/workload/Upgrading.vue, edit/workload/index.vue
#330 
fixes:
* radio button group keyboard accessibility
* tabs keyboard accessibility 
* (appearance of) double footer after page refresh
=> workload create bugfixes

assets/styles/global/_form.scss, components/Tabbed/index.vue, components/TabbedLinks/index.vue, components/form/InputWithSelect.vue, components/form/KeyValue.vue, components/form/RadioButton.vue, components/form/RadioGroup.vue, edit/workload/Scheduling.vue, edit/workload/Security.vue, edit/workload/WorkloadPorts.vue, edit/workload/index.vue
https://github.com/rancher/dashboard/issues/321
=> 321 continued

components/GatekeeperConfig.vue, config/type-config.js, pages/c/_cluster/gatekeeper/index.vue
Minor PR to get the nav link moved so Cody can start placing the constraints and templates on the Gatekeeper index.
=> Opa Feedback

components/form/MatchKinds.vue, components/form/NamespaceList.vue, components/form/RuleSelector.vue
Switching because scope is deprecated.
=> Switch from scope to slot-scope

components/GatekeeperTables.vue, pages/c/_cluster/gatekeeper/index.vue
=> Add constaint and template tables to the OPA page.

components/DetailTop.vue, components/form/ArrayList.vue, components/form/MatchKinds.vue, components/form/NamespaceList.vue, components/form/RuleSelector.vue, components/formatter/IngressTarget.vue, components/formatter/Link.vue, components/formatter/List.vue, config/nav-cluster.js, config/table-headers.js, config/type-config.js, detail/networking.k8s.io.v1beta1.ingress.vue, layouts/default.vue
=> Ingress list/detail

components/GatekeeperConfig.vue, config/type-config.js, models/app.js, models/project.cattle.io.v3.app.js, pages/c/_cluster/gatekeeper/index.vue, plugins/steve/resource-instance.js, store/index.js
Updates from the review of Gatekeeper. 
Also removes refs for core.v1.
rancher/dashboard#304
=> GateKeeper Feedback

components/GatekeeperConfig.vue, pages/c/_cluster/gatekeeper/index.vue
Adds waitForState to namespace check
Fixes bug where versions were undefined
Feedback from design review
=> Opa.feedback

assets/styles/global/_labeled-input.scss, assets/styles/global/_tooltip.scss, assets/styles/themes/_dark.scss, assets/styles/themes/_light.scss, components/DetailTop.vue, components/Layout/Stack/index.vue, components/ResourceDetail.vue
https://github.com/rancher/dashboard/issues/368
https://github.com/rancher/dashboard/issues/380
=> top detail styles

assets/styles/app.scss, assets/styles/global/_tooltip.scss, assets/styles/vendor/vue-js-modal.scss, components/Card.vue, components/GatekeeperConfig.vue, components/PromptRemove.vue
https://github.com/rancher/dashboard/issues/381
=> 381 opa. still needs banner styles

pages/c/_cluster/workloads/index.vue
=> workload list bugfix

assets/styles/global/_tooltip.scss, assets/styles/vendor/vue-select.scss, assets/translations/en-us.yaml, components/Accordion.vue, components/GatekeeperConfig.vue, components/form/ArrayList.vue, layouts/default.vue, pages/c/_cluster/gatekeeper/index.vue
https://github.com/rancher/dashboard/issues/392
=> gatekeeper fixes

pages/c/_cluster/gatekeeper/index.vue
rancher/dashboard#406
from https://github.com/rancher/system-charts/blob/dev/charts/rancher-gatekeeper-operator/v0.1.0/values.yaml
=> update default config for gatekeeper

assets/translations/en-us.yaml, components/InfoBox.vue, components/InfoBoxCluster.vue, components/PercentageBar.vue, config/labels-annotations.js, config/type-config.js, config/types.js, models/management.cattle.io.cluster.js, models/node.js, pages/c/_cluster/index.vue, utils/units.js
First iteration of cluster over page.
rancher/dashboard#350
=> Cluster Detail Overview

components/form/RadioButton.vue, shared/gatekeeper-constraint.vue
=> Adding enforcement action param to constraints

shared/gatekeeper-constraint.vue
=> Adding ApiGroups to Constraints by default

components/GatekeeperConfig.vue
https://github.com/rancher/dashboard/issues/425
=> experimental flag

assets/styles/base/_typography.scss, components/GatekeeperConfig.vue
https://github.com/rancher/dashboard/issues/426
=> opa gatekeeper layout

.gitignore, assets/styles/global/_columns.scss, assets/translations/en-us.yaml, components/GatekeeperConfig.vue, components/InfoBox.vue, components/InfoBoxCluster.vue, components/PercentageBar.vue, components/SortableTable/index.vue, components/formatter/LiveDate.vue, components/nav/Type.vue, config/type-config.js, config/types.js, models/event.js, models/node.js, pages/c/_cluster/gatekeeper/index.vue, pages/c/_cluster/index.vue, store/type-map.js, utils/units.js
Addresses feedback in rancher/dashboard#414
=> Cluster Overview Feedback

assets/styles/global/_form.scss, components/DetailTop.vue, components/SortableTable/index.vue, components/form/ArrayList.vue, components/form/Checkbox.vue, components/form/InputWithSelect.vue, components/form/KeyValue.vue, components/form/LabeledInput.vue, components/form/NameNsDescription.vue, components/form/Probe.vue, components/form/RadioGroup.vue, detail/pod.vue, detail/workload.vue, edit/workload/Command.vue, edit/workload/Job.vue, edit/workload/Scheduling.vue, edit/workload/Selectors.vue, edit/workload/Upgrading.vue, edit/workload/ValueFromResource.vue, edit/workload/index.vue
#421 - workload detail page UI issues
* also fixes issues with nodeAffinity in workload creation
=> workload detail and create bugfixes

assets/styles/themes/_light.scss, assets/styles/vendor/vue-js-modal.scss
https://github.com/rancher/dashboard/issues/461
https://github.com/rancher/dashboard/issues/463
=> outline color 461

assets/styles/themes/_dark.scss
https://github.com/rancher/dashboard/issues/370
=> diff colors added to dark

components/form/RadioGroup.vue, edit/secret.vue, edit/workload/Scheduling.vue
=> fix secret create

components/ResourceYaml.vue, components/form/NameNsDescription.vue, config/type-config.js, models/apps.daemonset.js, models/apps.deployment.js, models/apps.replicaset.js, models/apps.statefulset.js, models/batch.cronjob.js, models/batch.job.js, models/replicationcontroller.js, models/workload.js, pages/c/_cluster/workloads/_namespace/_id.vue, pages/c/_cluster/workloads/index.vue, plugins/steve/actions.js, plugins/steve/resource-instance.js, store/type-map.js
=>  workload edit route

assets/translations/en-us.yaml, components/GatekeeperConfig.vue, pages/c/_cluster/gatekeeper/index.vue
The parameter that housed the version of the OPA app was renamed this updates the name to match.
Also adds some missing translations for this section. 
rancher/dashboard#457
=> OPA App Version Missing

components/form/LabeledSelect.vue, edit/workload/Command.vue, edit/workload/ValueFromResource.vue
=> fix workload env variables

components/form/ArrayList.vue, components/form/NamespaceList.vue, shared/gatekeeper-constraint.vue
- Make system namespaces a part of the excluded namespaces match by default.
- Remove system namespaces from the options of namespace match
- Ensure that the types are getting edited appropriately.
rancher/dashboard#455
rancher/dashboard#503
=> Namespace filtering and type editing

components/form/InputWithSelect.vue, components/form/LabeledSelect.vue
set 'label' as the default label field for LabeledSelects
allow setting of same label prop in InputWithSelect
=> use label as default label key

assets/translations/en-us.yaml, components/form/Labels.vue, config/table-headers.js, detail/configmap.vue, edit/configmap.vue
=> Updating configMaps to be better inline with mocks

components/form/InputWithSelect.vue, components/form/LabeledSelect.vue, components/formatter/IngressTarget.vue, config/table-headers.js, detail/networking.k8s.io.ingress.vue, edit/networking.k8s.io.ingress/Rule.vue, edit/networking.k8s.io.ingress/index.vue, plugins/steve/resource-instance.js
- Fixed a number of unhandled exceptions
- Fixes some issues with rules vs backend property references
- Made pages more consistent with mocks
rancher/dashboard#272
=> Fixing up ingress pages

components/InfoBoxCluster.vue
=> display k8s version in version section

components/InfoBoxCluster.vue
=> cluster info box doesn't need to grow on large screens

config/type-config.js, edit/secret.vue, models/secret.js
https://github.com/rancher/dashboard/issues/264#issuecomment-619261732
=> fix secret typeDisplay

components/form/LabeledSelect.vue, config/table-headers.js, edit/secret.vue, models/secret.js
#264 
* allow custom types in Type dropdown
* change display names for some secret types 
* fix error w/ saving TLS certs
=> secrets bugfixes

components/BreadCrumbs.vue, components/ResourceDetail/Masthead.vue, components/ResourceDetail/index.vue, edit/rbac.authorization.k8s.io.role.vue, edit/workload/index.vue, layouts/default.vue, pages/c/_cluster/_resource/index.vue, utils/string.js
#538 
* add breadcrumbs
* move namespace (or project on namespace pages) below title
* yaml/overview toggle (if custom overview page exists; generic to be added)
=> masthead changes

config/type-config.js, detail/configmap.vue, edit/configmap.vue
=> Updating ConfigMap pages to reflect new requirements

assets/translations/en-us.yaml, components/BreadCrumbs.vue, components/ResourceDetail/Masthead.vue, components/ResourceDetail/index.vue, components/form/NameNsDescription.vue, detail/configmap.vue, detail/node.vue, detail/pod.vue, detail/rbac.authorization.k8s.io.clusterrole.vue, detail/rbac.authorization.k8s.io.role.vue, detail/rio.cattle.io.service.vue, detail/secret.vue, detail/workload.vue, edit/namespace/index.vue
* use translation strings
* use cluster nameDisplay instead of id
* fix bug on namespace create page
=> masthead fixes

assets/styles/base/_typography.scss, assets/styles/vendor/vue-select.scss, components/form/LabeledSelect.vue, components/nav/Header.vue, stories/DesignSystemsHeaders.stories.mdx
https://github.com/rancher/dashboard/issues/552https://github.com/rancher/dashboard/issues/552
=> cluster dropdown, searchable dropdowns

detail/secret.vue, edit/secret.vue
* swap table for keyvalue component in opaque secret detail page
* add placeholder text to cert input fields
=> secrets tweaks

detail/secret.vue
https://github.com/rancher/dashboard/issues/264#issuecomment-623758215
=> fix data header in opaque detail view

components/ResourceDetail/index.vue, components/ResourceYaml.vue, components/YamlEditor.vue
=> 'read from file' button for YAML editor

assets/styles/base/_helpers.scss, components/formatter/VerticalScroll.vue, detail/secret.vue, pages/c/_cluster/_resource/index.vue
https://github.com/rancher/dashboard/issues/620
https://github.com/rancher/dashboard/issues/598
https://github.com/rancher/dashboard/issues/623
=> node detail, scroll helper

detail/configmap.vue, edit/configmap.vue
https://github.com/rancher/dashboard/issues/265#issuecomment-622199169
=> Modify spacing and sizing on the configmap pages

detail/node.vue
- Remove state from detail top.
- Make ip address in detail top copy to clipboard
- Removed search from Conditions, Info, Taints
https://github.com/rancher/dashboard/issues/241#issuecomment-626026375
=> Making minor updates to Node detail page

components/form/LabeledSelect.vue, components/formatter/IngressTarget.vue, components/formatter/Link.vue, detail/networking.k8s.io.ingress.vue, edit/networking.k8s.io.ingress/Rule.vue, edit/networking.k8s.io.ingress/RulePath.vue, edit/networking.k8s.io.ingress/index.vue, plugins/steve/mutations.js, shared/networking.k8s.io.ingress/Certificate.vue, shared/networking.k8s.io.ingress/DefaultBackend.vue
=> Updating Ingress to implement new requirements

assets/styles/themes/_light.scss, components/BadgeState.vue, components/ResourceDetail/Masthead.vue, models/node.js, plugins/steve/resource-instance.js
https://github.com/rancher/dashboard/issues/241#issuecomment-626209671
=> Adding node cordon badging

assets/translations/en-us.yaml, components/formatter/KeyValue.vue, components/formatter/ServiceTargets.vue, components/formatter/ServiceType.vue, config/table-headers.js, config/types.js, edit/service.vue, list/service.vue
Updates to the service list page based on feedback. This PR adds a few new formatters; KeyValue, ServiceTargets, and ServiceTypes. There is currently some duplication with rancher/dashboard#642 and the DEFAULT_SERVICE_TYPES. The objects are duplicated in those but I will resolve them after the respective PRs have been merged and the other PR will use the object from types.js in this PR.
=> Service List Updates

assets/translations/en-us.yaml, components/ResourceDetail/index.vue, components/ResourceList/Masthead.vue, components/form/NamespaceList.vue, config/type-config.js, models/gatekeeper-constraint.js, models/templates.gatekeeper.sh.constrainttemplate.js, pages/c/_cluster/_resource/index.vue, pages/c/_cluster/gatekeeper/constraints/create.vue, pages/c/_cluster/gatekeeper/constraints/index.vue, pages/c/_cluster/gatekeeper/templates/index.vue, plugins/steve/normalize.js, plugins/steve/resource-instance.js, plugins/steve/resource-proxy.js
- Constraint YAML cancel button will take you back to the constraint
page.
- Updated the mastheads of constraint and template.
- Constraint Create as Yaml now works
- Constraints and templates can be cloned now.
rancher/rancher#523
rancher/rancher#622
rancher/rancher#398
=> Making a number of OPA fixes

components/SortableTable/index.vue, components/SortableTable/selection.js, components/form/KeyValue.vue, detail/configmap.vue
I did switch to using the sortable table as vince suggested. The sortable table introduced that border that separates the border from the content and I preferred the way it looked so I left it in. Let me know if you'd like it removed.
rancher/dashboard#589
=> Changing KeyValue to meet requirements.

edit/secret.vue
=> hide private key on edit

components/SortableTable/index.vue, components/form/KeyValue.vue
https://github.com/rancher/dashboard/issues/589#issuecomment-632263082
=> Hide the no rows messaging in keyValues when editing

components/form/LabeledSelect.vue, components/form/NodeAffinity/NodeSelectorTerm.vue, edit/workload/Command.vue, edit/workload/ValueFromResource.vue, mixins/labeled-form-element.js
#603 
move labels outside dropdowns, into headers in workload environment variables
=> design issues - dropdown

assets/translations/en-us.yaml, components/DetailTop.vue, components/formatter/Date.vue, components/formatter/SecretData.vue, config/type-config.js, detail/secret.vue, edit/secret.vue, models/secret.js, package.json, yarn.lock
=> show cert issuer and expiration in secret list

detail/node.vue
per: https://github.com/rancher/dashboard/pull/699#discussion_r431337493
(the checkboxes are fixed in #699 )
=> add conditions component to node detail

components/GenericResourceDetail.vue, components/ResourceDetail/Masthead.vue, components/form/Conditions.vue
#542 
* hide yaml/overview toggle on generic detail 
* fix last updated in conditions table
* remove border from yaml
=> generic detail - pr feedback

components/GatekeeperConfig.vue
=> Increase timeout for Gatekeeper enable `waitForCondition`

components/form/MatchExpressions.vue, edit/networking.k8s.io.ingress/Rule.vue, edit/networking.k8s.io.ingress/RulePath.vue, shared/networking.k8s.io.ingress/Certificate.vue
https://github.com/rancher/dashboard/issues/667
=> ingress edit

components/form/LabeledInput.vue, components/form/LabeledSelect.vue, components/form/MatchExpressions.vue, components/form/NodeAffinity.vue, edit/workload/Networking.vue, edit/workload/Scheduling.vue, edit/workload/index.vue
#686 
* fix spacing of matchExpressions components in list
* do not show node selectors on initial workload create (show buttons to add them)
* when adding a node selector, always have space for one rule ready
* hide buttons in view mode
* match styling of keyValue component
=> matchExpressions feedback

pages/c/_cluster/index.vue
=> Add description to cluster over header

detail/secret.vue
show decoded secret data in detail view
=> Update secret detail

assets/styles/themes/_dark.scss, assets/styles/themes/_light.scss, assets/translations/en-us.yaml, components/ResourceTable.vue, components/SortableTable/index.vue, components/nav/Group.vue, list/namespace.vue, models/namespace.js, plugins/steve/resource-instance.js
https://github.com/rancher/dashboard/issues/543
=> 543 folder label prefix

assets/styles/base/_helpers.scss, assets/styles/vendor/vue-select.scss, components/form/ArrayList.vue, components/formatter/KeyValue.vue, edit/service.vue
https://github.com/rancher/dashboard/issues/668
=> Service - Design Issues #668

assets/translations/en-us.yaml, components/ResourceDetail/index.vue, components/form/ServicePorts.vue, components/formatter/ServiceTargets.vue, components/formatter/ServiceType.vue, edit/service.vue
https://github.com/rancher/dashboard/issues/583#issuecomment-630593656
=> Service create/edit requirements updates

models/node.js
=> Updating the source of internal/external ips for nodes

assets/translations/en-us.yaml
contrains -> constraints
configuartion -> configuration
=> Fix minor typos

edit/workload/index.vue
=> Image Name missing from workloads page

assets/translations/en-us.yaml, components/ClusterDisplayProvider.vue
=> Add node driver names for providers

components/SortableTable/index.vue, components/form/KeyValue.vue, components/formatter/KeyValue.vue
https://github.com/rancher/dashboard/issues/732
=> key value fixes

edit/service.vue
=> Change all service tab help-text to banners to match styles

components/form/NodeAffinity.vue, components/form/Scheduling.vue, edit/workload/index.vue
https://github.com/rancher/dashboard/issues/686#issuecomment-639988270
Also, ensure matchExpression 'values' is formatted correctly before saving
=> Match expressions bugs

components/form/ArrayList.vue, components/form/MatchKinds.vue, shared/gatekeeper-constraint.vue
- Make a close icon button for removing a kind
- Update the visuals for a single kind
- Don't remove the empty ApiGroup default value.
rancher/dashboard#392
=> Improving the UI for the Constraints Kind tab

assets/styles/vendor/vue-select.scss, components/form/ArrayList.vue
https://github.com/rancher/dashboard/issues/668
=> port dropdown and arraylist gap

components/BreadCrumbs.vue, components/SortableTable/index.vue, components/formatter/ServiceType.vue, components/nav/ClusterSwitcher.vue, components/nav/Header.vue, config/schema.js, config/types.js, edit/service.vue, list/namespace.vue, middleware/authenticated.js, models/cluster.js, models/management.cattle.io.cluster.js, models/service.js, nuxt.config.js, pages/c/_cluster/gatekeeper/index.vue, pages/c/_cluster/index.vue, pages/c/_cluster/rio/index.vue, plugins/steve/getters.js, plugins/steve/subscribe.js, store/index.js, store/prefs.js, store/type-map.js
=> Standalone steve, variable width table columns

assets/styles/global/_columns.scss, components/GenericResourceDetail.vue, components/InfoBox.vue, components/PercentageBar.vue, components/SortableTable/index.vue, components/form/KeyValue.vue, components/form/ServicePorts.vue, components/nav/ClusterSwitcher.vue, detail/configmap.vue, detail/secret.vue, edit/configmap.vue, edit/networking.k8s.io.ingress/DefaultBackend.vue, edit/networking.k8s.io.ingress/Rule.vue, edit/networking.k8s.io.ingress/index.vue, edit/secret.vue, pages/auth/login.vue, shared/gatekeeper-constraint.vue
@vincent99 this isn't the most elegant solution but it works without breaking other dropdowns. please review
=> cluster switcher dropdown fix

assets/translations/en-us.yaml
=> Change service SA 'None' label

assets/styles/global/_tooltip.scss
use variable for prefs dd text color so that it works with themes
rancher/dashboard#704
=> Prefs Dropdown Theme Issues

assets/translations/en-us.yaml, components/form/ServicePorts.vue, edit/service.vue, mixins/create-edit-view.js, models/service.js, plugins/steve/resource-instance.js, utils/custom-validators.js, utils/string.js, utils/validators.js, utils/validators/index.js, utils/validators/service-port.js
Supports basic types string, int, bool, array etc
Supports custom validation logic
Adds initial service validations
Adds additional error processing logic to better parse Kubernetes api errors
Fixes some minor bugs found while writing custom validation for service
rancher/dashboard#189
=> Adds client side validation

components/PromptRemove.vue
=> redirect from resource-specifc page after deleting that resource

components/DetailTop.vue, components/ResourceDetail/index.vue, components/form/KeyValue.vue, components/form/NameNsDescription.vue
https://github.com/rancher/dashboard/issues/370
=> yaml create view

edit/secret.vue
=> address field when editing registry secrets

assets/translations/en-us.yaml, components/Card.vue, components/PromptRemove.vue, components/SortableTable/index.vue, components/SortableTable/selection.js, components/SortableTable/selectionStore.js, store/action-menu.js
#731 
two parts to this: 
* add a scrollbar when the modal is longer than the page
* make it much more unlikely that the modal ever _is_ so long by fixing `Card` padding
=> delete prompt styling for many resources

components/form/Security.vue
=> Replacing the drop capabilities label that was inadvertently removed

components/Tabbed/index.vue
Fixed error when active tab was empty and default tab was found. The additional el-if checks should have been placed in the first branch  as they really only apply when active tab is empty. 
Removed unneeded hash event listener.
=> Tabbed Bugs

components/formatter/IngressTarget.vue, edit/networking.k8s.io.ingress/Rules.vue, edit/networking.k8s.io.ingress/index.vue, models/networking.k8s.io.ingress.js
-Accounts for undefined hosts and paths
-Accounts for wildcards in hosts
-Accounts for protocol+host+paths not being a url
-Removes links from paths on the detail page
rancher/dashboard#762
=> Updating the way we display rules on the ingress list and detail pages

components/SortableTable/selection.js
=> fix tableAction when args=null

edit/secret.vue
#763 
* default to Artifactory if the secret's URL includes 'artifactory'
* change the variable name to URL since it's not really a domain name
=> edit artifactory registry secrets

assets/styles/global/_tooltip.scss, components/ButtonDropdown.vue, components/ResourceList/Masthead.vue
Fixes SSR issue where dropdown button filled the entire actions container due to v-tooltip getting placed into the dom only being hidden with visibility. Additionally I moved the styles for this to tooltip so the styles would take effect immediately as well. 
Fixes issue with no-create perms by hiding the button. 
Fixes but with missing button type on the dropdown trigger icon which caused form submits to occur anytime we clicked the trigger button when in a form.
Fixes some css targets to make them more generic.
Adds sizes to the button dropdown allowing consumer to pass xs, sm, lg as options.
=> Button Dropdown Bugs

assets/translations/en-us.yaml, pages/c/_cluster/explorer/index.vue
- This will allow us to get the appropriate singular/plural for the labels
- Updates Total Resources to reflect the new spacing that was added
rancher/dashboard#887
=> Updating the usage of labelFor on the cluster overview resource gauges

config/labels-annotations.js
=> Update description annotation to match ember

components/formatter/InternalExternalIP.vue
=> Combine internal/external ip when they're the same on the node list page

assets/translations/en-us.yaml, chart/istio.vue, components/Wizard.vue, components/form/KeyValue.vue, config/types.js
=> istio create

components/ResourceDetail/index.vue, components/SortableTable/THead.vue, components/SortableTable/index.vue, detail/rio.cattle.io.service.vue
https://github.com/rancher/dashboard/issues/944
=> sortable table changes

utils/object.js
refactored `cleanUp` so it works with keys that have dots in their names
=> refactor cleanUp

assets/styles/global/_labeled-input.scss, components/Tabbed/index.vue, components/form/ArrayList.vue, components/form/Command.vue, components/form/EnvVars.vue, components/form/LabeledInput.vue, components/form/MatchExpressions.vue, components/form/NodeScheduling.vue, components/form/ValueFromResource.vue, edit/workload/index.vue
#942 #939 #937 #983 #936 #942 #669
=> workload create/edit fixes

assets/translations/en-us.yaml, chart/istio.vue, chart/logging/providers/elasticsearch.vue, components/ResourceDetail/index.vue, components/ResourceYaml.vue, components/YamlEditor.vue, components/form/FileSelector.vue, components/form/KeyValue.vue, edit/secret.vue
If we're okay with this I'll replace the remaining fileChange locations.
=> Create a FileSelector component

components/Tabbed/index.vue
align the advanced/hidden-by-default tabs with regular tabs
=> no advanced tabs indentation

components/form/WorkloadPorts.vue
remove table from workloadports
=> workloadports style

store/type-map.js
https://github.com/rancher/dashboard/issues/887#issuecomment-667216451
=> Ensuring labelFor adds the 's' to 0 counts

assets/translations/en-us.yaml, config/table-headers.js, detail/node.vue, models/node.js
- Reordered Internal/External IP header
- Prioritized external ip for the detail top
- Added external ip to the addresses table
rancher/dashboard#1000
rancher/dashboard#1002
rancher/dashboard#1003
=> Cleaning up some internal/external ip address problems

assets/translations/en-us.yaml, chart/logging/index.vue, chart/logging/providers/elasticsearch.vue, chart/logging/providers/kafka.vue, chart/logging/providers/options.js, chart/logging/providers/splunk.vue, chart/logging/providers/syslog.vue
rancher/dashboard#895
rancher/dashboard#973
=> Adding kafka, splung and syslog logging providers     

README.md
Signed-off-by: pmc <pangmengchen@deepexi.com>
fix doc mistake
```yarn run devx```  to ``` yarn run dev```
=> doc: fix doc mistake

assets/styles/base/_color.scss, assets/styles/global/_tooltip.scss, assets/styles/themes/_dark.scss, assets/styles/themes/_light.scss, assets/styles/vendor/vue-select.scss, components/ActionMenu.vue, components/SortableTable/THead.vue, components/nav/Jump.vue
https://github.com/rancher/dashboard/issues/927
=> 927 issues

chart/istio.vue, components/Tabbed/Tab.vue
Moved things into tabs, added overlay file example and clearer description:
=> istio ui demo feedback

components/DetailTop.vue
https://github.com/rancher/dashboard/issues/817#issuecomment-670183487
=> Switching DetailTop's annotation table to KeyValue component

chart/monitoring/index.vue
=> fix default retention size monitoring

assets/styles/base/_helpers.scss, assets/styles/themes/_dark.scss, assets/styles/themes/_light.scss, components/SimpleBox.vue, components/Tabbed/index.vue, components/form/InputWithSelect.vue, components/form/MatchExpressions.vue, components/form/NodeAffinity.vue, components/form/PodAffinity.vue, components/form/Probe.vue, components/nav/Header.vue
https://github.com/rancher/dashboard/issues/1045
tabs fix
buttons fix
=> active tab and small button fix

edit/networking.k8s.io.ingress/index.vue
=> Updating Ingress to make use of CruResource

edit/configmap.vue, edit/service.vue
- Hiding for configmap and service pages
rancher/dashboard#1091
=> Hiding the labels and annotations tab for view mode

pages/c/_cluster/explorer/index.vue
https://github.com/rancher/dashboard/issues/925#issuecomment-674199876
=> Updating the cluster explorer to use the appropriate cluster object

components/ContainerResourceLimit.vue, edit/workload/Job.vue, edit/workload/index.vue
=> workload create fixes

assets/styles/global/_tooltip.scss, assets/styles/themes/_light.scss, assets/styles/vendor/vue-select.scss, components/nav/Header.vue, components/nav/ProductSwitcher.vue
https://github.com/rancher/dashboard/issues/1044
=> header fix

assets/translations/en-us.yaml, chart/istio.vue, components/Tabbed/Tab.vue, pages/c/_cluster/apps/install.vue
=> Istio v1 conflict

assets/styles/base/_basic.scss, assets/styles/themes/_dark.scss, assets/styles/themes/_light.scss, components/SortableTable/index.vue, components/nav/ClusterSwitcher.vue, components/nav/Header.vue, components/nav/NamespaceFilter.vue, components/nav/ProductSwitcher.vue, pages/prefs.vue
https://github.com/rancher/dashboard/issues/1043
=> prefs page

assets/translations/en-us.yaml, edit/workload/Job.vue
#1120 
`backOfflimit` -> `backoffLimit`
=> backoffLimit typo

assets/translations/en-us.yaml, chart/monitoring/ClusterSelector.vue
=> Expose rke2 cluster type on monitoring chart

assets/translations/en-us.yaml, components/CruResource.vue, components/form/KeyValue.vue, components/form/MatchKinds.vue, components/form/NamespaceList.vue, components/form/RuleSelector.vue, edit/gatekeeper-constraint.vue, pages/c/_cluster/gatekeeper/constraints/create.vue, pages/c/_cluster/gatekeeper/constraints/index.vue, utils/create-yaml.js
There's been significant changes to a number of our base components that didn't get carried over to constraints since it's an exceptional type.
- This migrated over to cru-resource
- Updated all of the helper components to handle the lack of tables in arraylist
- Updated how create-edit-view is used
- Properly saves now
- Can edit parameters as yaml
- Can edit yaml
- Constraint spec renders full object
https://github.com/rancher/dashboard/issues/1100
https://github.com/rancher/dashboard/issues/1099
https://github.com/rancher/dashboard/issues/1011
https://github.com/rancher/dashboard/issues/622
=> Fixing opa constraint bitrot issues

assets/translations/en-us.yaml, components/Glance.vue, config/types.js, pages/c/_cluster/explorer/index.vue, pages/c/_cluster/istio/index.vue, utils/string.js
=> Istio overview page, no Grafana link yet

assets/translations/en-us.yaml, pages/c/_cluster/istio/index.vue
=> update howto text

assets/styles/base/_basic.scss, components/SortableTable/THead.vue, components/SortableTable/index.vue, components/SortableTable/selection.js, components/form/Checkbox.vue, components/nav/Favorite.vue, pages/c/_cluster/apps/install.vue, plugins/lookup.js
- Add and remove global.cattle.* values (https://github.com/rancher/dashboard/issues/1180)
- Checkbox key events for SortableTable
=> global.cattle.* values, checkboxes

assets/translations/en-us.yaml, chart/logging/index.vue
- Added the 'Additional Loggers' tab
- Added a Cluster Flow placeholder
rancher/dashboard#1109
K3S:
Not K3S:
=> Updating the logging installation options

components/Tabbed/index.vue, components/form/Checkbox.vue, components/form/Container.vue, components/form/WorkloadPorts.vue, detail/pod.vue
=> add container name and image to pod detail

config/product/logging.js
=> Removing logging from the product page

assets/translations/en-us.yaml, components/CruResource.vue, components/form/RadioButton.vue, components/form/RadioGroup.vue, config/product/explorer.js, config/types.js, edit/resources.cattle.io.backup.vue
=> backup create page

assets/translations/en-us.yaml, components/CruResource.vue, components/CruResourceFooter.vue, components/ResourceDetail/index.vue, components/ResourceList/index.vue, components/form/MatchExpressions.vue, components/nav/Footer.vue, components/nav/Header.vue, components/nav/ProductSwitcher.vue, config/product/apps.js, config/product/backup.js, config/product/ecm.js, config/product/explorer.js, config/product/fleet.js, edit/configmap.vue, edit/fleet.cattle.io.clustergroup.vue, edit/gatekeeper-constraint.vue, edit/namespace.vue, edit/networking.k8s.io.ingress/index.vue, edit/service.vue, edit/workload/index.vue, store/type-map.js, utils/create-yaml.js, utils/selector.js
- Nav changes for fleet
- Use default slot for CruResource form content instead of "define"
- Fleet ClusterGroups
- Don't show a cancel button on view pages
=> Fleet and fleet accessories

chart/monitoring/alerting/index.vue, chart/monitoring/index.vue
This PR reverts the auto creation of the default namespace and secret config by the UI. The backend will you a pre-install hook to create the defaults. 
https://github.com/rancher/dashboard/issues/1088#issuecomment-689035231
PR is in draft until @aiyengar2 gives the go ahead to merge so we can sync the backend and front end changes.
=> Remove default secret/namespace creation Monitoring/Alerting V2

assets/styles/themes/_light.scss, assets/translations/en-us.yaml, components/form/FileSelector.vue, components/form/Labels.vue, components/form/NameNsDescription.vue, components/formatter/ResourceSetLink.vue, config/product/backup.js, config/types.js, edit/resources.cattle.io.backup.vue, edit/resources.cattle.io.restore.vue, layouts/default.vue, pages/c/_cluster/backup/index.vue, store/type-map.js
#1125  
I'm not really sure where to put the warning about the credential secret; @lvuch might have a better idea there.
=> restore crd create page

assets/translations/en-us.yaml, components/formatter/VirtualServiceGateways.vue, config/product/istio.js, pages/c/_cluster/istio/index.vue
#1184 
(afaik we don't have a working URL for Kiali yet)
=> istio ux changes

chart/logging/providers/elasticsearch.vue, chart/logging/providers/kafka.vue, chart/logging/providers/splunk.vue, components/form/SecretSelector.vue, edit/admin.rio.cattle.io.publicdomain.vue, edit/logging.banzaicloud.io.clusteroutput.vue, edit/networking.k8s.io.ingress/Certificates.vue, edit/secret.vue, edit/workload/storage/Secret.vue, models/secret.js
rancher/dashboard#1031
Demo:
Unfiltered secrets:
Notes:
- I updated the providers to deal with compilation issues but I don't expect them to work until I update the Output crds.
- I created the clusterOutput page just to demo, this will get updates with the Output crd changes.
=> Adding an OpaqueSecretSelector

pages/c/_cluster/gatekeeper/templates/index.vue
=> Updating the yaml location for gatekeeper templates

assets/translations/en-us.yaml, components/ResourceDetail/Masthead.vue, components/SortableTable/index.vue, components/form/ArrayList.vue, components/form/NameNsDescription.vue, components/formatter/BadgeStateFormatter.vue, config/product/rancher-cis-benchmark.js, config/types.js, detail/cis.cattle.io.clusterscan.vue, edit/cis.cattle.io.clusterscan.vue, edit/cis.cattle.io.clusterscanprofile.vue, models/cis.cattle.io.clusterscan.js, pages/c/_cluster/backup/index.vue, pages/c/_cluster/cis/index.vue, plugins/steve/resource-instance.js
#1202 
updated nav:
#1035 
#1036 
List page:
Create page:
Detail page:
=> Cis ClusterScanProfile, ClusterScan CRD pages

assets/styles/themes/_dark.scss, components/CruResourceFooter.vue, components/PromptRemove.vue, components/form/MatchExpressions.vue, edit/service.vue
https://github.com/rancher/dashboard/issues/1235
=> polish minor issues

components/formatter/VirtualServiceGateways.vue, models/service.js, pages/c/_cluster/istio/index.vue
#1247 
Updated url url to `api/v1/namespaces/istio-system/services/http:kiali:20001/proxy/`
=> update kiali url

assets/styles/vendor/vue-select.scss, assets/translations/en-us.yaml, components/CruResource.vue, components/DetailTop.vue, components/form/PodAffinity.vue, components/form/Tolerations.vue, components/form/WorkloadPorts.vue, detail/workload/index.vue, edit/PersistentVolumeClaim.vue, edit/workload/Job.vue, edit/workload/Upgrading.vue, edit/workload/index.vue, models/workload.js
#693 
#1001 
#1257 
#1160 
#1140 
#1158 
#1161 
#1052 
#1153
=> Bugfix workload details

assets/translations/en-us.yaml, components/SortableTable/selection.js, edit/logging.banzaicloud.io.clusterflow.vue, edit/logging.banzaicloud.io.flow.vue, models/logging.banzaicloud.io.clusterflow.js, models/logging.banzaicloud.io.clusteroutput.js, models/logging.banzaicloud.io.flow.js, models/logging.banzaicloud.io.output.js, pages/c/_cluster/logging/index.vue
rancher/dashboard#1127
rancher/dashboard#1126
Notes:
I need to update outputRefs to local/globalOutputRefs but I'll do this in a followup after I update my cluster and retest.
=> Creating the flow and clusterFlow pages

chart/logging/index.vue
Needed to be updated per this comment https://github.com/rancher/dashboard/issues/1244#issuecomment-695121332
=> Converting toleration values from booleans to strings

assets/translations/en-us.yaml, components/form/InputWithSelect.vue, components/form/NameNsDescription.vue, config/product/explorer.js, detail/management.cattle.io.fleetworkspace.vue, list/fleet.cattle.io.clustergroup.vue, models/fleet.cattle.io.clustergroup.js, pages/c/_cluster/apps/install.vue
- Choose chart if no match found, add namespace, select project ns
- Fleet list views
=> Fleet list view, add ns/project on app deploy

assets/styles/themes/_light.scss, assets/translations/en-us.yaml, chart/backup-restore-operator/S3.vue, chart/backup-restore-operator/index.vue, components/form/LabeledSelect.vue, components/form/RadioGroup.vue, config/labels-annotations.js, edit/resources.cattle.io.backup.vue, edit/resources.cattle.io.restore.vue, pages/c/_cluster/apps/install.vue
#1019 
Also, updated the display name to 'Backup & Restore Operator' for #1186
=> Backup restore op deployment

assets/styles/global/_tooltip.scss
https://github.com/rancher/dashboard/issues/1265
=> ui design issues

chart/logging/index.vue
Related to https://github.com/rancher/charts/pull/673/files
=> renamed tolerations to fluentbit_tolerations

assets/translations/en-us.yaml, chart/monitoring/index.vue, chart/monitoring/prometheus/index.vue
=> Add warning when users already have pods with prometheus containers

components/SortableTable/selection.js, components/SortableTable/selectionStore.js, edit/logging.banzaicloud.io.clusterflow.vue, edit/logging.banzaicloud.io.flow.vue, models/logging.banzaicloud.io.clusterflow.js, models/logging.banzaicloud.io.flow.js
- I also noticed that initialSelection was no longer working so I
fixed that as well.
rancher/dashboard#1127
rancher/dashboard#1126
=> Switching flow pages to local/globalOutputRefs

components/form/RadioButton.vue, edit/resources.cattle.io.backup.vue, edit/resources.cattle.io.restore.vue
=> fix encryption config name typo

chart/backup-restore-operator/index.vue
https://github.com/rancher/dashboard/issues/1019#issuecomment-696856214
=> set s3.enabled true when s3 is default storage choice

components/form/ArrayList.vue, components/form/KeyValue.vue, components/form/RadioButton.vue, edit/catalog.cattle.io.clusterrepo.vue, edit/service.vue
https://github.com/rancher/dashboard/issues/1293
https://github.com/rancher/dashboard/issues/1304
=> ui design polish

assets/translations/en-us.yaml, edit/workload/index.vue
=> use pod template for labels/annotations

assets/translations/en-us.yaml
https://github.com/rancher/dashboard/issues/1256
I only did CIS and Backup/Restore.
=> Added descriptions for Rancher operator CRDs.

edit/workload/index.vue, models/workload.js
=> update workload selector matchLabels when adding pod labels

assets/styles/themes/_dark.scss, assets/styles/themes/_light.scss, chart/backup-restore-operator/index.vue, components/CruResourceFooter.vue, components/FileDiff.vue, components/Questions/Question.js, components/ResourceYaml.vue, components/form/Footer.vue, components/form/NameNsDescription.vue, pages/c/_cluster/apps/install.vue
- Fix default="false" value for boolean questions
- Lowercase all names becaues k8s won't take upper
- Form actions on the right
- File diff colors
- Yaml preview for chart installs
- For special charts with fixed namespace/name, go to upgrade if you try to install it again
- Fix edit backup chart
=> Chart stuff

assets/translations/en-us.yaml, edit/resources.cattle.io.backup.vue, edit/resources.cattle.io.restore.vue
https://github.com/rancher/dashboard/issues/1395
=> Add tooltip for backup for encryption config

assets/translations/en-us.yaml
https://github.com/rancher/dashboard/issues/1403
=> Update Entrypoint to Command

components/SortableTable/index.vue, detail/cis.cattle.io.clusterscan.vue
=> cis clusterscan fixes

assets/translations/en-us.yaml, edit/resources.cattle.io.backup.vue, edit/resources.cattle.io.restore.vue, models/resources.cattle.io.restore.js
=> backup crd issues

config/product/monitoring.js
Until we come up with a better solution to check for this particular chart as it is a unique situation. 
rancher/dashboard#1430
=> Switch monitoring product to single type check

assets/styles/global/_tooltip.scss, assets/translations/en-us.yaml, components/ButtonDropdown.vue, edit/workload/storage/index.vue
=> add dropdown-only variation of buttondropdown

assets/translations/en-us.yaml, config/product/gatekeeper.js, pages/c/_cluster/gatekeeper/index.vue, pages/c/_cluster/logging/index.vue
=> Updating Gatekeeper navigation

assets/translations/en-us.yaml, components/nav/WindowManager/ContainerLogs.vue, components/nav/WindowManager/ContainerShell.vue, components/nav/WindowManager/Window.vue, pages/c/_cluster/longhorn/index.vue
https://github.com/rancher/dashboard/issues/1288
https://github.com/rancher/dashboard/issues/1461
=> window tabs and card design

assets/translations/en-us.yaml
https://github.com/rancher/dashboard/issues/1476
=>  RKE Federal to RKE Government

components/PromptRemove.vue
=> Correctly resetting the error member when closing

assets/translations/en-us.yaml, chart/monitoring/ClusterSelector.vue, chart/monitoring/alerting/index.vue, chart/monitoring/grafana/index.vue, chart/monitoring/index.vue, chart/monitoring/prometheus/index.vue, components/form/RadioGroup.vue
Feel free to squash this PR. I broke each bug in the collective bug attached down into a separate commit but I am not sure we have to keep that kind of history around after merge.  
rancher/dashboard#1230
=> Monitoring General Bugs and Feedback

assets/translations/en-us.yaml, components/form/LabeledSelect.vue, edit/logging-flow/index.vue
=> Allowing flow to use both global and local outputRefs

edit/logging.banzaicloud.io.output/index.vue, utils/create-yaml.js
CruResource needs to take the modified value in
order to display the appropriate yaml.
Also the Output and ClusterOutput spec has a
type of `.spec` so I had to put an exception in
create-yaml.
rancher/dashboard#1420
rancher/dashboard#1421
=> Switched to modifying this.value directly

components/CruResource.vue, components/formatter/PodImages.vue, config/product/explorer.js, detail/workload/index.vue, edit/PersistentVolumeClaim.vue, edit/workload/storage/PVC.vue, edit/workload/storage/Secret.vue, edit/workload/storage/index.vue, models/workload.js
#1276 #1059 #1358 #1292 #1459 #1480 #1460
=> more workload fixes

chart/logging/index.vue
deployToControlPlane wasn't retaining the value when switching between yaml and form
rancher/dashboard#1320
=> Correcting an issue with deployToControlPlane

edit/logging-flow/index.vue
=> Ensure logging flows are up to date for the yaml editor

pages/c/_cluster/apps/install.vue
- Preserve systemDefaultRegistry and globals if different than default
=> Preserve systemDefaultRegistry if edited

plugins/steve/subscribe.js, store/index.js, utils/socket.js
- Reconnect to the right cluster when you switch clusters
=> Reconnect to right cluster when switching clusters

components/form/RadioButton.vue
https://github.com/rancher/dashboard/issues/1489
https://github.com/rancher/dashboard/issues/1230
=> 1230 add back outline of default

assets/translations/en-us.yaml, chart/rancher-backup/index.vue, components/form/LabeledSelect.vue, components/form/LabeledTooltip.vue, edit/resources.cattle.io.restore.vue
#1391 #1443  #1393 #1451 #1538 #1537 #1540
=> restore, deployment fixes

chart/monitoring/alerting/index.vue
=> fix bug in resetting alertmanager configsecret

components/form/LabeledTooltip.vue
=> fix dropdown arrows when tooltip present

assets/translations/en-us.yaml, chart/logging/index.vue
=> Removing deploy to controlplane nodes

edit/resources.cattle.io.restore.vue
=> fix restore storage field re-population

assets/translations/en-us.yaml, chart/monitoring/index.vue, pages/c/_cluster/monitoring/index.vue
Warn and prevent install of Mon v2 if Mon v1 is installed.
Show warning on overview if Mon v1 is installed.
https://github.com/rancher/dashboard/issues/1565
https://github.com/rancher/dashboard/issues/1566
=> Monitoring Page Updates

edit/persistentvolumeclaim.vue, edit/workload/VolumeClaimTemplate.vue, edit/workload/storage/PVC.vue, models/persistentvolumeclaim.js, models/workload.js
=>  fix pvc create in workload

chart/rancher-backup/S3.vue
=> add optionkey to secret select

chart/monitoring/index.vue, pages/c/_cluster/monitoring/index.vue
Needed to exclude monitoring v2 from the check
rancher/dashboard#1565
=> Update Monitoring V1 check

edit/logging-flow/index.vue
=> Remove match and filters when they're empty

config/labels-annotations.js, models/namespace.js
To exclude {c,u,p}-xxxxx namespaces
=> Switch system namspace annotation

edit/workload/VolumeClaimTemplate.vue
=> fix statefulset creation

assets/translations/en-us.yaml, models/logging.banzaicloud.io.clusterflow.js, models/logging.banzaicloud.io.flow.js, plugins/steve/resource-instance.js, utils/custom-validators.js, utils/validators/flow-output.js
=> Adding validation to verify atleast one local or global output is selected

assets/translations/en-us.yaml, edit/resources.cattle.io.backup.vue
=> Backup text updates

config/product/explorer.js, store/type-map.js
=> check if user can view workloads before adding to nav

components/nav/Group.vue, components/nav/Type.vue
https://github.com/rancher/dashboard/issues/1372
=> side nav active state

edit/networking.k8s.io.ingress/index.vue
=> Reorder the ingress tabs

edit/logging-flow/index.vue
https://github.com/rancher/dashboard/issues/1590#issuecomment-702968319
=> Removing empty matches and filters from flows before edit as yaml

components/ResourceDetail/index.vue, components/form/Checkbox.vue, detail/pod.vue
=> fix pod detailtop, storage

components/form/Command.vue, edit/workload/index.vue, edit/workload/storage/Mount.vue, models/workload.js
=> fix workload stdin/tty fields

components/form/LabeledInput.vue, components/form/NameNsDescription.vue
=> Making Name required for non-namespaced resources

assets/translations/en-us.yaml, detail/secret.vue, edit/secret.vue
#1500 
Updated cert and registry detail views to use KeyValue (like opaque):
Updated text and spacing for registry type:
=> secrets UI issues

assets/styles/base/_mixins.scss, assets/styles/themes/_light.scss, components/SimpleBox.vue, components/Tabbed/index.vue, components/form/Command.vue, components/form/Container.vue, components/form/HealthCheck.vue, components/form/MatchExpressions.vue, components/form/Networking.vue, components/form/PodScheduling.vue, components/form/Scheduling.vue, components/form/Security.vue, components/form/Tolerations.vue, edit/logging.banzaicloud.io.output/providers/elasticsearch.vue, edit/resources.cattle.io.restore.vue, edit/service.vue, edit/workload/index.vue, edit/workload/storage/ephemeralVolume/index.vue
https://github.com/rancher/dashboard/issues/1278
https://github.com/rancher/dashboard/issues/967 -- still needs dev eyeballs
https://github.com/rancher/dashboard/issues/1609
https://github.com/rancher/dashboard/issues/1262
=> daemon and cronjobs top tabs

components/form/KeyValue.vue
=> Showing filesize when adding a binary file in KeyValue component

detail/cis.cattle.io.clusterscan.vue
=> fix clusterscan test sorting

components/form/ArrayList.vue, components/form/Networking.vue, edit/workload/index.vue
https://github.com/rancher/dashboard/issues/1278
=> 1278 revisit

components/form/KeyValue.vue, edit/secret.vue
I added the modifyFile to KeyValue instead of adding a watcher in Secret because keyValue doesn't react to value updates
=> Modify secret data keys so they conform to the expected format

detail/cis.cattle.io.clusterscan.vue
=> Refresh clusterscan report details when scan status changes

components/form/ArrayList.vue, components/form/TextAreaAutoGrow.vue
=> Adding the ability to paste multiline strings into ArrayLists

assets/translations/en-us.yaml, pages/c/_cluster/istio/index.vue
#1646  - updated monitoring link to direct to dashboard monitoring specifically
=> istio overview link to rancher-monitoring

assets/translations/en-us.yaml, config/product/logging.js, config/table-headers.js, edit/logging.banzaicloud.io.output/index.vue, models/logging.banzaicloud.io.output.js
=> Add Providers to the list view of ClusterOutputs

edit/networking.k8s.io.ingress/DefaultBackend.vue, edit/networking.k8s.io.ingress/Rule.vue, edit/networking.k8s.io.ingress/RulePath.vue, edit/networking.k8s.io.ingress/Rules.vue, edit/networking.k8s.io.ingress/index.vue, models/networking.k8s.io.ingress.js
- default backend was renamed from backend to defaultBackend
- backend schema was changed to have nested port and service name
rancher/dashboard#1634
=> Adding more versioning support to ingress

assets/styles/base/_variables.scss, assets/styles/fonts/_icons.scss, assets/styles/global/_button.scss, assets/styles/global/_labeled-input.scss, assets/styles/global/_tooltip.scss, components/form/KeyValue.vue, components/form/WorkloadPorts.vue, components/nav/ClusterSwitcher.vue, components/nav/NamespaceFilter.vue, edit/workload/storage/index.vue
https://github.com/rancher/dashboard/issues/1556
https://github.com/rancher/dashboard/issues/1578
https://github.com/rancher/dashboard/issues/1648
=> mostly input changes

assets/translations/en-us.yaml, components/BadgeState.vue, components/ProgressBarMulti.vue, components/RelatedResources.vue, components/ResourceDetail/Masthead.vue, components/ResourceTable.vue, components/SortableTable/index.vue, components/SortableTable/selection.js, components/formatter/AppSummaryGraph.vue, components/nav/ProductSwitcher.vue, config/product/apps.js, config/table-headers.js, detail/catalog.cattle.io.app.vue, models/catalog.cattle.io.app.js, plugins/steve/resource-instance.js, utils/string.js
- App shortcut to the installed apps page instead of charts
- RelatedResources for Apps
- Dynamically load real model to show actions
- Successful badge border
=> Related resources table for apps

components/formatter/AppSummaryGraph.vue, models/catalog.cattle.io.app.js
- Combine states with same color into one bar piece
- Show helm operation on app remove
=> Show chart removal operation logs

assets/translations/en-us.yaml, components/ButtonDropdown.vue, detail/workload/index.vue, edit/workload/storage/index.vue, edit/workload/storage/secret.vue
#1645 - check if secret volume is actually a certificate and label appropriately
=> show secret volume type correctly in workload detail

models/networking.k8s.io.ingress.js, plugins/steve/getters.js
=> Adding a pathExistsInSchema getter

store/type-map.js
Moved the getInstances to a module local variable to avoid the ssr warning "Cannot stringify a function getInstances".
Verified on both ssr and spa. 
I was a little surprised that this works but it seems to indicate we do a complete build of a type-map on both the front and the back. I figured ssr would just have the frontend deserialize the state from the backend.
=> Removing spoofed getInstances from type-map store

assets/translations/en-us.yaml, components/formatter/FleetSummaryGraph.vue, list/fleet.cattle.io.gitrepo.vue, models/fleet.cattle.io.gitrepo.js
=> Fix target type display

layouts/error.vue
=> Redirect errors from outside the base url

chart/istio.vue, components/Tabbed/index.vue, pages/c/_cluster/apps/install.vue
- Drop toggling hidden tabs support
- Chart values.yaml fixes, istio extra values editor, rancher/dashboard#1166
=> Values Yaml editing

assets/translations/en-us.yaml, config/labels-annotations.js, config/product/explorer.js, list/catalog.cattle.io.app.vue, models/catalog.cattle.io.app.js, pages/c/_cluster/apps/charts.vue, pages/c/_cluster/apps/install.vue, store/catalog.js
=> Don't suggest upgrade of hidden/managed charts

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml
Add simple Chinese translation
=> Add simple chinese translation

config/product/longhorn.js
=> Remove types from longhorn product for now

middleware/authenticated.js
=> Catch requests for route outside of base url earlier

assets/translations/en-us.yaml, edit/monitoring.coreos.com.receiver/index.vue, models/monitoring.coreos.com.receiver.js
https://github.com/rancher/dashboard/issues/1238#issuecomment-721858073
=> Adding name validation to receivers.

assets/translations/en-us.yaml, config/labels-annotations.js, pages/c/_cluster/apps/charts.vue, pages/c/_cluster/apps/install.vue, store/catalog.js
https://github.com/rancher/rancher/issues/29934
=> Support chart display name

utils/validators/pod-affinity.js
=> fix pod affinity validation when affinity is not defined

components/form/ArrayList.vue, components/form/ArrayListGrouped.vue
rancher/dashboard#1737
Look n feel:
Usage/Interface:
=> Adding the ArrayListGrouped component

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, components/formatter/LiveDate.vue, components/nav/Header.vue, pages/c/_cluster/explorer/index.vue
=> Update cluster dashboard Chinese tranlation

components/form/KeyValue.vue, edit/configmap.vue
#1754 
add/ add from file button changes requested are being tracked in this issue: #1723 
keyValue changes requested are in this PR: #1716
=> update configmap to show binaryData and data in one place

assets/styles/global/_labeled-input.scss, assets/styles/vendor/vue-select.scss, assets/translations/en-us.yaml, components/form/EnvVars.vue, components/form/InputWithSelect.vue, components/form/LabeledInput.vue, components/form/MatchExpressions.vue, components/form/PodAffinity.vue, components/form/PodScheduling.vue, components/form/Security.vue, components/form/WorkloadPorts.vue, edit/workload/index.vue, utils/object.js
#1717 
- move replicas, schedule, service name out of container tab
- filter services in statefulset creation to those in the currently selected namespace
- remove schedule section from job and daemon set
#1727 - restyle port section and add host IP field
#1741 - fix add drop capabilities.
note: this isn't a change to `LabeledSelect`, just a change to its use in the `Security` component
#1729
=> workload create polish

components/CodeMirror.vue, detail/workload/index.vue, edit/workload/storage/index.vue
=> fallback content for unsupported volume types in workload detail

assets/translations/en-us.yaml, edit/workload/index.vue
=> add imagePullSecrets to container form

components/form/MatchExpressions.vue, components/form/NodeAffinity.vue, components/form/PodAffinity.vue, edit/workload/VolumeClaimTemplate.vue, edit/workload/storage/index.vue
#1737 - updates usage of `.simple-box` in workload creation to the `InfoBox` component
=> update simple-box to InfoBox

components/ResourceDetail/Masthead.vue
https://github.com/rancher/dashboard/issues/720#issuecomment-729083040 - updates the sensitive data buttongroup so clicking the active button doesn't do anything (same behavior as overview | yaml buttongroup)
=> fix show/hide sensitive data buttongroup behavior

config/product/monitoring.js, config/types.js, edit/monitoring.coreos.com.receiver/index.vue, edit/monitoring.coreos.com.receiver/types/opsgenie.vue, edit/monitoring.coreos.com.receiver/types/pagerduty.vue, models/monitoring.coreos.com.receiver.js
rancher/dashboard#1216
I'll submit a separate PR when I get the icons and will update the OpsGenie fields if Arvind thinks they need to be changed. https://github.com/rancher/dashboard/issues/1216#issuecomment-729901523
=> Adding PagerDuty and OpsGenie receivers

edit/networking.k8s.io.ingress/index.vue
=> Hiding Annotations/Labels tab when in view.

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, components/form/ArrayList.vue, components/form/KeyValue.vue, edit/secret.vue, store/type-map.js
Update RBAC and storage chinese translation
=> Update RBAC and storage chinese translation

edit/resources.cattle.io.backup.vue
=> fix backup encryption secret search

config/product/monitoring.js, edit/monitoring.coreos.com.receiver/types/slack.vue
=> Adding a new field to the alert receiver slack config

components/form/RadioGroup.vue
RadioGroup show label on the detail page
=> RadioGroup show label on the detail page

config/product/monitoring.js, config/types.js, edit/monitoring.coreos.com.receiver/index.vue, edit/monitoring.coreos.com.receiver/types/opsgenie.vue
- Adding the responders field to opsgenie
- Providing some helper text to pagerduty
rancher/dashboard#1216
=> Updating the pagerduty and opsgenie receivers

assets/styles/base/_variables.scss, edit/networking.k8s.io.ingress/Certificate.vue, edit/networking.k8s.io.ingress/RulePath.vue
=> Make a few changes to rule paths to better integrate the Labeled/Select changes

assets/styles/base/_mixins.scss, assets/styles/global/_form.scss, assets/translations/en-us.yaml, components/form/ArrayList.vue, components/form/ArrayListGrouped.vue, components/form/KeyValue.vue, components/form/Select.vue, edit/networking.k8s.io.ingress/Certificate.vue, edit/networking.k8s.io.ingress/Certificates.vue, edit/networking.k8s.io.ingress/Rule.vue, edit/networking.k8s.io.ingress/RulePath.vue, edit/networking.k8s.io.ingress/Rules.vue, edit/networking.k8s.io.ingress/index.vue, models/networking.k8s.io.ingress.js
Enabling the selection of non existant  certificates in Ingress
- Also switched to using ArrayList within Certificate
- Small tweaks to ensure the tls objest is observable
rancher/dashboard#1812
Switching Ingress over to using the ArrayListGroup component
Made a few changes to improve the performance of the page. I experienced noticeable lag while editing the paths.
Updated KeyValue to address spacing and protip change requests.
**Note: @lvuch  Do we want to add changing the color of labels based on status into the LabeledSelect component update?**
=> Ingress new secret

detail/networking.k8s.io.ingress.vue
=> Updating the Ingress detail view to only contain the rules table

assets/translations/en-us.yaml, detail/pod.vue, detail/workload/index.vue, edit/workload/index.vue, models/pod.js, models/workload.js
=> Workload detail

components/form/SecretSelector.vue
rancher/dashboard#1374
Notes:
- I noticed that secret selector doesn't display in view mode (LabeledSelect doesn't) which I will fix in the as part of the logging polish if it looks like it's necessary.
- I chose to only provide the None value for the secret name and not they key since None shouldn't really be an option for the key on secret selectors that want the key.
- When selecting a secret name the key is cleared since a key may not be the same between secrets.
=> Added none as an option to secret selectors

assets/styles/global/_button.scss, assets/styles/global/_form.scss, assets/styles/themes/_dark.scss, assets/translations/en-us.yaml, components/Tabbed/Tab.vue, components/form/ArrayList.vue, components/form/KeyValue.vue, components/form/Labels.vue, components/form/MatchExpressions.vue, components/form/Ports.vue, components/form/ServicePorts.vue, edit/logging-flow/index.vue, edit/rio.cattle.io.router/Headers.vue, edit/rio.cattle.io.router/index.vue, edit/rio.cattle.io.service/Command.vue, edit/workload/index.vue, layouts/default.vue
https://github.com/rancher/dashboard/issues/1718
=> #1939 redux

assets/styles/global/_select.scss, assets/styles/vendor/vue-select.scss, components/form/InputWithSelect.vue, components/form/KeyValue.vue, components/form/LabeledInput.vue, components/form/LabeledSelect.vue, components/form/MatchExpressions.vue, components/form/NameNsDescription.vue, components/form/Select.vue, components/form/ServicePorts.vue, components/nav/ClusterSwitcher.vue, edit/constraints.gatekeeper.sh.constraint/Scope.vue, edit/logging-flow/Match.vue
Z-indexing issues for dd content
Dropdown height issues
Placeholder placement issues
rancher/dashboard#1896
rancher/dashboard#1933
Still a couple remaining items re: button dropdown that will be addressed in another PR.
=> Dropdown bugs

components/ButtonDropdown.vue, components/DetailTop.vue, components/ResourceDetail/Masthead.vue, components/form/KeyValue.vue, components/form/NodeScheduling.vue, components/form/ValueFromResource.vue, components/form/WorkloadPorts.vue, detail/cis.cattle.io.clusterscan.vue, edit/monitoring.coreos.com.prometheusrule/AlertingRule.vue, edit/monitoring.coreos.com.prometheusrule/GroupRules.vue, edit/service.vue, edit/workload/VolumeClaimTemplate.vue, edit/workload/index.vue, edit/workload/storage/Mount.vue
https://github.com/rancher/dashboard/issues/1871
=> more polish for resources

edit/workload/index.vue
=> scaling and upgrading

edit/constraints.gatekeeper.sh.constraint/index.vue
rancher/dashboard#1889
rancher/dashboard#1954
=> Hide namespace lists based on scope and show subtype within OPA constraints

assets/translations/en-us.yaml
https://github.com/rancher/dashboard/issues/1851#issuecomment-738296593
=> Updating a field label for logging install

assets/translations/en-us.yaml, edit/logging.banzaicloud.io.output/index.vue, edit/logging.banzaicloud.io.output/providers/awsElasticsearch.vue, edit/logging.banzaicloud.io.output/providers/azurestorage.vue, edit/logging.banzaicloud.io.output/providers/cloudwatch.vue, edit/logging.banzaicloud.io.output/providers/datadog.vue, edit/logging.banzaicloud.io.output/providers/file.vue, edit/logging.banzaicloud.io.output/providers/forward.vue, edit/logging.banzaicloud.io.output/providers/gcs.vue, edit/logging.banzaicloud.io.output/providers/kinesisStream.vue, edit/logging.banzaicloud.io.output/providers/logdna.vue, edit/logging.banzaicloud.io.output/providers/logz.vue, edit/logging.banzaicloud.io.output/providers/loki.vue, edit/logging.banzaicloud.io.output/providers/newrelic.vue, edit/logging.banzaicloud.io.output/providers/s3.vue, edit/logging.banzaicloud.io.output/providers/splunkHec.vue, edit/logging.banzaicloud.io.output/providers/sumologic.vue, models/logging.banzaicloud.io.output.js
- Also added ssl/ca to Forward, Loki and Splunk
- Changed Certificates header to Connection so I could include more for one of the providers
rancher/dashboard#1191
@vincent99 what do we want to do for the view on these? Also, do we want to make the provider a subtype now?
=> Adding new logging Outputs and ClusterOutputs

assets/styles/global/_form.scss, assets/styles/global/_labeled-input.scss, assets/styles/themes/_dark.scss, assets/styles/themes/_light.scss, assets/translations/en-us.yaml, components/form/RadioButton.vue, components/form/ServicePorts.vue, edit/constraints.gatekeeper.sh.constraint/index.vue, edit/monitoring.coreos.com.receiver/index.vue, edit/service.vue
https://github.com/rancher/dashboard/issues/1984
https://github.com/rancher/dashboard/issues/1204
=> styling changes

components/form/SecretSelector.vue, edit/logging.banzaicloud.io.output/index.vue, edit/logging.banzaicloud.io.output/providers/awsElasticsearch.vue, edit/logging.banzaicloud.io.output/providers/azurestorage.vue, edit/logging.banzaicloud.io.output/providers/cloudwatch.vue, edit/logging.banzaicloud.io.output/providers/datadog.vue, edit/logging.banzaicloud.io.output/providers/elasticsearch.vue, edit/logging.banzaicloud.io.output/providers/file.vue, edit/logging.banzaicloud.io.output/providers/forward.vue, edit/logging.banzaicloud.io.output/providers/gcs.vue, edit/logging.banzaicloud.io.output/providers/kafka.vue, edit/logging.banzaicloud.io.output/providers/kinesisStream.vue, edit/logging.banzaicloud.io.output/providers/logdna.vue, edit/logging.banzaicloud.io.output/providers/logz.vue, edit/logging.banzaicloud.io.output/providers/loki.vue, edit/logging.banzaicloud.io.output/providers/newrelic.vue, edit/logging.banzaicloud.io.output/providers/s3.vue, edit/logging.banzaicloud.io.output/providers/splunkHec.vue, edit/logging.banzaicloud.io.output/providers/sumologic.vue, pages/design-system/form-controls.vue
=> Adding namespace filtering to SecretSelector

components/nav/Group.vue, utils/units.js
- Also fixed a nav warning that showed up in the console by updating the expected prop type of expanded
rancher/dashboard#2023
=> Having parseSi handle increment null/undefined in the same way

assets/styles/global/_form.scss, assets/styles/global/_labeled-input.scss, assets/styles/global/_tooltip.scss, components/form/LabeledTooltip.vue, components/form/TextAreaAutoGrow.vue, pages/design-system/form-controls.vue
https://github.com/rancher/dashboard/issues/1982
=> tooltip fixes

config/product/cis.js, edit/cis.cattle.io.clusterscan.vue, list/cis.cattle.io.clusterscan.vue, models/cis.cattle.io.clusterscanbenchmark.js, models/cis.cattle.io.clusterscanreport.js, plugins/steve/resource-instance.js
=> cis-admin role bugs, test sorting

components/formatter/IconText.vue, config/product/cis.js, detail/cis.cattle.io.clusterscan.vue, edit/cis.cattle.io.clusterscan.vue, models/cis.cattle.io.clusterscanbenchmark.js, plugins/steve/resource-instance.js
=> remove getIcon prop, cis report-fetching fix

components/form/KeyValue.vue, components/form/Labels.vue
=> allow empty label/annotation values

edit/constraints.gatekeeper.sh.constraint/Scope.vue, edit/constraints.gatekeeper.sh.constraint/index.vue
=> Fixing the value of 'Namespace & Cluster' to be '*'

assets/translations/en-us.yaml, components/form/Checkbox.vue, edit/logging.banzaicloud.io.output/providers/forward.vue, edit/logging.banzaicloud.io.output/providers/syslog.vue, models/logging.banzaicloud.io.output.js
- Also made it so when checkboxes are disabled it will show the not
allowed cursor
rancher/dashboard#1992
rancher/dashboard#1991
=> Adding syslog as an output

edit/logging.banzaicloud.io.output/providers/syslog.vue
=> Making transport a dropdown since it has an enumeration of values

assets/styles/global/_cards.scss, assets/styles/themes/_dark.scss, pages/c/_cluster/istio/index.vue
#1863 - @lvuch can you check out the styling on the disabled `.link-container`?
=> update jaeger link, link-container disabled style

components/form/LabeledInput.vue, components/form/RadioButton.vue, config/product/cis.js, detail/cis.cattle.io.clusterscan.vue, edit/cis.cattle.io.clusterscan.vue, models/cis.cattle.io.clusterscan.js, package.json, yarn.lock
#1996 #2070 #2071 #2033 
Disabled radio group selection:
Validate cron field:
Dropdown in the scan detail page closed state fixed (dropdown size issue being tracked here #2031 ):
=> scan inputs, validate cron

detail/workload/index.vue
=> fix cronjob detail

components/form/ArrayListGrouped.vue, edit/monitoring.coreos.com.receiver/index.vue, edit/monitoring.coreos.com.receiver/types/opsgenie.vue, edit/monitoring.coreos.com.receiver/types/pagerduty.vue
- Changed the default value of integration type in PagerDuty
- Changed the height of one of the inputs in OpsGenie
- Made sure the remove button was hidden in ArrayListGrouped when in _VIEW mode
https://github.com/rancher/dashboard/issues/1216#issuecomment-745130811
=> Fixing a few minor issues with monitoring receivers

assets/images/pl/README.md
Issue https://github.com/rancher/rancher/issues/29813
=> Fixed vue path to use custom logos

edit/networking.k8s.io.ingress/Rule.vue, edit/networking.k8s.io.ingress/RulePath.vue
- Also noticed height issues witht he unlabled inputs so I fixed those too
rancher/dashboard#2059
=> Ensuring all fields of ingress rules updates the model

assets/styles/global/_form.scss, assets/styles/themes/_dark.scss, assets/styles/themes/_light.scss, assets/styles/vendor/vue-js-modal.scss, components/PromptRemove.vue, components/nav/Group.vue
https://github.com/rancher/dashboard/issues/2089
https://github.com/rancher/dashboard/issues/1823
https://github.com/rancher/dashboard/issues/1831
https://github.com/rancher/dashboard/issues/1795
=> minor ui visual fixes

components/form/KeyValue.vue, edit/configmap.vue, edit/namespace.vue, edit/networking.k8s.io.ingress/index.vue, edit/service.vue
https://github.com/rancher/dashboard/issues/1720
=> general spacing issues

assets/translations/en-us.yaml
=> fix cis scan alerting warning message

chart/istio.vue
=> istio 1.7.301 install page error

assets/translations/en-us.yaml, edit/logging.banzaicloud.io.output/providers/elasticsearch.vue, edit/logging.banzaicloud.io.output/providers/forward.vue, edit/logging.banzaicloud.io.output/providers/kafka.vue, edit/logging.banzaicloud.io.output/providers/logdna.vue, edit/logging.banzaicloud.io.output/providers/logz.vue, edit/logging.banzaicloud.io.output/providers/options.js, edit/logging.banzaicloud.io.output/providers/splunkHec.vue, edit/logging.banzaicloud.io.output/providers/utils.js, models/logging.banzaicloud.io.output.js, utils/custom-validators.js, utils/validators/logging-outputs.js
- Making logdna apiKey a required field
- Ensuring the ports are with a valid port range and changing it to min or max if it's not
rancher/dashboard#2075
rancher/dashboard#2074
=> Small fixes to logging outputs

assets/translations/en-us.yaml, components/form/InputWithSelect.vue, components/form/MatchExpressions.vue, components/form/NodeAffinity.vue, components/form/PodAffinity.vue, edit/fleet.cattle.io.clustergroup.vue, edit/fleet.cattle.io.gitrepo.vue
=> Fleet bugs

components/form/ArrayList.vue, components/form/ArrayListGrouped.vue, components/form/MatchExpressions.vue, components/form/NodeAffinity.vue, components/form/NodeScheduling.vue, components/form/PodAffinity.vue, edit/monitoring.coreos.com.prometheusrule/AlertingRule.vue, edit/monitoring.coreos.com.prometheusrule/GroupRules.vue, edit/monitoring.coreos.com.prometheusrule/RecordingRule.vue, edit/workload/VolumeClaimTemplate.vue, edit/workload/storage/Mount.vue, edit/workload/storage/index.vue, edit/workload/storage/persistentVolumeClaim/persistentvolumeclaim.vue
I also made a couple of stylistic changes to the mount component under
workloads since the spacing was a little off.
rancher/dashboard#1919
rancher/dashboard#1962
@westlywright can you verify that the Prometheus changes seem alright?
@mantis-toboggan-md can you verify that the workload changes seem alright?
I would like to note that I found a couple functional issues that I didn't resolve because I wasn't sure if they were things you were already working on.
1. Node Scheduling priority doesn't seem to get saved or perhaps not shown when editing
2. Pod Scheduling 'Pods in these namespaces' don't seem to get saved
=> Replacing Inbox v-for with ArrayListGrouped

components/PromptRemove.vue
=> Deleting a node required name confirmation now

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, components/form/SecretSelector.vue, config/table-headers.js, edit/logging-flow/Match.vue, edit/logging-flow/index.vue, edit/logging.banzaicloud.io.output/index.vue, edit/logging.banzaicloud.io.output/providers/awsElasticsearch.vue, edit/logging.banzaicloud.io.output/providers/azurestorage.vue, edit/logging.banzaicloud.io.output/providers/cloudwatch.vue, edit/logging.banzaicloud.io.output/providers/datadog.vue, edit/logging.banzaicloud.io.output/providers/elasticsearch.vue, edit/logging.banzaicloud.io.output/providers/forward.vue, edit/logging.banzaicloud.io.output/providers/gcs.vue, edit/logging.banzaicloud.io.output/providers/kafka.vue, edit/logging.banzaicloud.io.output/providers/kinesisStream.vue, edit/logging.banzaicloud.io.output/providers/logz.vue, edit/logging.banzaicloud.io.output/providers/loki.vue, edit/logging.banzaicloud.io.output/providers/newrelic.vue, edit/logging.banzaicloud.io.output/providers/s3.vue, edit/logging.banzaicloud.io.output/providers/splunkHec.vue, edit/logging.banzaicloud.io.output/providers/sumologic.vue, edit/logging.banzaicloud.io.output/providers/syslog.vue, pages/c/_cluster/logging/index.vue
- Spacing
- Consistency between outputs
- Better messaging
- Disabling namespacing on cluster resources
- Namespace filtering
rancher/dashboard#1977
=> Addressing a number of minor logging issues

assets/styles/themes/_dark.scss, assets/styles/themes/_light.scss, components/ButtonDropdown.vue, components/form/Labels.vue, components/form/MatchExpressions.vue, components/form/PodAffinity.vue, edit/workload/index.vue, layouts/default.vue
https://github.com/rancher/dashboard/issues/2043
https://github.com/rancher/dashboard/issues/2105
=> more ui polish

components/form/ArrayList.vue, components/form/ArrayListGrouped.vue
rancher/dashboard#742
Verified on three separate pages and ensured ArrayListGrouped still looks correct.
=> Switching ArrayList to grid for consistency sake

components/form/Networking.vue, edit/workload/Job.vue
=> workload bugs

assets/translations/en-us.yaml, components/form/ServicePorts.vue, edit/secret.vue
=> add * to required fields

components/PromptRemove.vue
https://github.com/rancher/dashboard/issues/2130
=> 2130 card actions

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, pages/c/_cluster/explorer/index.vue
https://github.com/rancher/dashboard/issues/1711#issuecomment-752284383
=> Switched Pods Reserved to Pods Used for accuracy

assets/translations/en-us.yaml
https://github.com/rancher/dashboard/issues/2144
=> Add back missing CRD text for clusteroutput

edit/monitoring.coreos.com.prometheusrule/GroupRules.vue, edit/monitoring.coreos.com.prometheusrule/index.vue
until a standalone detail page is added for Prom rules this was the lowest impact change to remove the add rule and remove rule buttons.
rancher/dashboard#2149
=> Hide prom rule add/remove buttons on 'view' mode

components/PromptRemove.vue
=> delete modal name confirm bug

assets/translations/en-us.yaml, components/RelatedResources.vue, components/Tabbed/Tab.vue, components/formatter/Endpoints.vue, detail/service.vue, edit/service.vue, models/service.js
Polish updates and bug fixes for the Service Create page.
New Service Detail Page.
Note: This may show a conflict until [this](https://github.com/rancher/dashboard/pull/2156) is merged. I needed the tooltip additions on Tab but the PR hasn't been merged as of writing this.
rancher/dashboard#717
rancher/dashboard#1772
rancher/dashboard#1826
rancher/dashboard#2040
=> Services Polish

pages/c/_cluster/apps/charts.vue, pages/c/_cluster/apps/install.vue
=> prevent error when installing/upgrading chart without annotations

assets/styles/app.scss, assets/styles/global/_resource.scss, assets/translations/en-us.yaml, chart/monitoring/index.vue, components/CruResource.vue, components/Tabbed/Tab.vue, components/form/LabeledInput.vue, components/form/LabeledSelect.vue, components/form/LabeledTooltip.vue, components/formatter/RunBookLink.vue, edit/monitoring.coreos.com.receiver/index.vue, edit/monitoring.coreos.com.receiver/types/opsgenie.vue, edit/monitoring.coreos.com.receiver/types/pagerduty.vue, edit/monitoring.coreos.com.receiver/types/slack.vue, models/monitoring.coreos.com.receiver.js, pages/c/_cluster/monitoring/index.vue
Config Page:
Separate chart config options into tabs
Overview:
Link box style and spacing consistency updates. 
Updates the canDelete check for receivers so the root receiver does not display the delete action at all. 
Create Receiver general style updates.
Exposes table of active alerts (see screenshot) below the external links.
Table includes severity, name, and alert message. If the alert message includes a runbook link (further info about the alert) the message will externally link to the run book. 
rancher/dashboard#1806
rancher/dashboard#1986
=> Monitoring Polish

detail/node.vue
=> Adding dashIfEmpty to the info table value header of nodes detail page

layouts/default.vue, pages/c/_cluster/explorer/index.vue
https://github.com/rancher/dashboard/issues/2183
This pr addresses the cross browser positioning issue while maintaining even amount of space from h1 to nav bar and vertically centered positioning.
=> header overflow and positioning

assets/translations/en-us.yaml, edit/logging-flow/index.vue
https://github.com/rancher/dashboard/issues/2145#issuecomment-754787043
=> Indicating when outputs and cluster outputs no longer exist when editing flows/clusterflows

edit/workload/storage/index.vue
=> fix workload storage dropdown labels

assets/translations/en-us.yaml, config/product/auth.js, edit/auth/github.vue, edit/auth/googleoauth.vue, edit/auth/ldap/config.vue, edit/auth/ldap/index.vue, edit/auth/saml.vue, mixins/auth.js, models/management.cattle.io.authconfig.js, plugins/steve/resource-instance.js, store/auth.js, store/github.js
=> ldap, saml, google auth

assets/translations/en-us.yaml, edit/monitoring.coreos.com.receiver/types/opsgenie.vue
Changes a missed label and fixes a css alignment issue for opsgenie table. 
rancher/dashboard#1806
rancher/dashboard#1986
=> Monitoring Polish Bugs

assets/styles/base/_variables.scss, assets/styles/global/_button.scss, assets/styles/global/_form.scss, assets/styles/global/_select.scss, assets/styles/global/_tooltip.scss, assets/styles/themes/_light.scss, components/ButtonDropdown.vue, components/ContainerResourceLimit.vue, components/ResourceDetail/Masthead.vue, components/ResourceList/Masthead.vue, components/SortableTable/index.vue, components/nav/ClusterSwitcher.vue, components/nav/Header.vue, components/nav/NamespaceFilter.vue, components/nav/ProductSwitcher.vue, components/nav/WorkspaceSwitcher.vue, pages/design-system/index.vue
https://github.com/rancher/dashboard/issues/2209
=> refinements

assets/translations/en-us.yaml, chart/logging/index.vue
rancher/dashboard#2199
rancher/dashboard#2234
=> Adding a new field to logging and correcting a typo for monitoring

chart/logging/index.vue
While testing the original implementation I didn't run into any focus
issues but after merging from mainline if the input loses focus the
input was lost. This appeared to be a reactivity issue
https://github.com/rancher/dashboard/issues/2199#issuecomment-768438436
=> Making the logging options nested objects reactive

assets/styles/global/_button.scss, assets/styles/global/_form.scss, assets/styles/global/_select.scss, assets/styles/themes/_light.scss, components/ButtonDropdown.vue, components/ButtonGroup.vue, components/ResourceDetail/Masthead.vue, components/SortableTable/index.vue, components/form/Checkbox.vue, components/form/InputWithSelect.vue, components/nav/ClusterSwitcher.vue, components/nav/Header.vue, components/nav/NamespaceFilter.vue
also has fix for: https://github.com/rancher/dashboard/issues/2248
addresses: dropdown height, poor contrast
=> dropdown height adjustment

assets/translations/en-us.yaml, edit/auth/saml.vue, mixins/auth.js, nuxt.config.js, pages/auth/login.vue, pages/auth/verify.vue, store/auth.js
=> saml auth fix

assets/translations/en-us.yaml, components/form/ArrayList.vue, config/product/explorer.js, config/table-headers.js, config/types.js, detail/rbac.authorization.k8s.io.roletemplate.vue, edit/rbac.authorization.k8s.io.roletemplate.vue, list/rbac.authorization.k8s.io.roletemplate.vue, models/rbac.authorization.k8s.io.roletemplate.js, plugins/steve/resource-instance.js
=> Adding the RBAC List, Edit and Details pages

assets/translations/en-us.yaml, components/auth/AllowedPrincipals.vue, components/auth/login/saml.vue, edit/auth/googleoauth.vue, edit/auth/ldap/index.vue, edit/auth/saml.vue, mixins/auth-config.js, pages/auth/verify.vue, plugins/steve/resource-instance.js, store/auth.js, utils/validators/index.js
=> fix ldap/saml add users and groups

assets/translations/en-us.yaml, components/SortableTable/index.vue, detail/cis.cattle.io.clusterscan.vue, models/management.cattle.io.cluster.js, pages/c/_cluster/explorer/index.vue
=> fix scan create, add remediation to scan detail

chart/rancher-backup/index.vue
=> do not show rwx pv for backup

edit/auth/github.vue, edit/auth/googleoauth.vue, edit/auth/ldap/index.vue, edit/auth/saml.vue, mixins/auth-config.js, pages/auth/login.vue, pages/auth/verify.vue, pages/c/_cluster/auth/config/_id.vue, pages/c/_cluster/auth/config/index.vue
#2253 - added an 'edit config' button to the page when a provider is enabled + updated some routing so the user isn't directed to that page in 'view' mode, with the add users/groups inputs disabled
#2258 
#2291 
#2276 
#2227
=> various auth bugs

components/CruResource.vue, components/CruResourceFooter.vue, components/ResourceDetail/index.vue, components/auth/AllowedPrincipals.vue, components/auth/login/saml.vue, edit/auth/azuread.vue, edit/auth/github.vue, edit/auth/googleoauth.vue, edit/auth/ldap/config.vue, edit/auth/ldap/index.vue, edit/auth/saml.vue, mixins/auth-config.js, models/management.cattle.io.authconfig.js, pages/auth/login.vue, pages/c/_cluster/auth/config/_id.vue, plugins/steve/resource-instance.js, store/auth.js, utils/auth.js
- #2273 I think this is related to AllowedPrincipalIds being undefined; that shouldn't happen if the auth config flow completes correctly (looking at you saml), but I added a catch for the possibility anyway.
- Also, some small changes to ldap inputs.
- Somehow my goToEdit button made it into master but not the goToEdit function. So here is that function!
=> auth 'goToEdit' missing

config/types.js, edit/autoscaling.horizontalpodautoscaler/index.vue
- See https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
- Addresses #2324
=> When creating a HPA only show scalable workloads

assets/translations/en-us.yaml, components/EventsTable.vue, components/RelatedWorkloadsTable.vue, components/StatusTable.vue, config/product/explorer.js, edit/persistentvolume/index.vue, edit/persistentvolumeclaim.vue, models/persistentvolume.js
=> Migrating the PersistentVolumeClaim pages

components/form/LabeledInput.vue, edit/auth/googleoauth.vue, edit/auth/ldap/config.vue, mixins/auth-config.js, models/management.cattle.io.authconfig.js, plugins/steve/resource-instance.js
#2116 - updated to hide text for multiline-password inputs; I also noticed an issue when adding users/groups to a google oauth config caused by the loss of `oauthCredential` and `serviceAccountCredential` from the auth config
#2252 #2339
=> auth component issues

edit/monitoring.coreos.com.receiver/types/pagerduty.vue, edit/monitoring.coreos.com.receiver/types/slack.vue
https://github.com/rancher/dashboard/issues/2249
=> tooltip change to helper text

config/types.js, edit/autoscaling.horizontalpodautoscaler/index.vue
Select Workload Fixes
- Remove CRON_JOB and JOB from scalable workload types
- Show workload type in workload select
- Helps address rancher/dashboard#2324
=> Improve create HPA workload select

list/workload.vue, models/workload.js
#2375
#2325 filtered out things with owners but did it backwards and showed only the ones that do instead of don't.
=> Fix workload filtering

assets/styles/global/_form.scss, components/form/Select.vue
https://github.com/rancher/dashboard/issues/2346
=> Unlabeled selects add view only state

chart/rancher-backup/index.vue
=> Ensure bound PVs are filtered when creating the Rancher Backup app

assets/styles/base/_color.scss, assets/styles/base/_variables.scss, assets/styles/global/_button.scss, components/form/ArrayList.vue, edit/logging-flow/index.vue, edit/monitoring.coreos.com.receiver/auth.vue, edit/monitoring.coreos.com.receiver/index.vue, edit/monitoring.coreos.com.receiver/tls.vue, edit/monitoring.coreos.com.receiver/types/email.vue, edit/monitoring.coreos.com.receiver/types/opsgenie.vue, edit/monitoring.coreos.com.receiver/types/pagerduty.vue, edit/monitoring.coreos.com.receiver/types/slack.vue, edit/monitoring.coreos.com.receiver/types/webhook.vue, edit/networking.k8s.io.ingress/Certificates.vue, edit/networking.k8s.io.ingress/Rules.vue, models/monitoring.coreos.com.receiver.js
- Also fixed some mode issues with ArrayListGrouped that showed up on the view of these pages. Still need more tweaking to make it look good though.
rancher/dashboard#1818
I considered moving require tls to the tls section but I didn't since it's not a part of the http_config so I was trying to stick with the existing logical grouping.
=> Adding tls and auth fields to the email and webhook receivers

assets/styles/base/_variables.scss, components/form/Select.vue, config/product/explorer.js, edit/rbac.authorization.k8s.io.roletemplate.vue, models/rbac.authorization.k8s.io.roletemplate.js, plugins/steve/resource-instance.js, store/type-map.js, utils/create-yaml.js
- edit yaml didn't show yaml because a schema wasn't defined
- edit yaml didn't save because the update link wasn't correct
- saving yaml didn't update the models in the stores
- not all input elements were passed the mode when looking at the config view
- the select and array list components had visual issues in view mode (didn't show the values and the buttons didn't line up well)
- cloning failed due to cleanForNew not accounting for the template property
https://github.com/rancher/dashboard/issues/2111#issuecomment-777066167
=> Resolving several issues around role template

components/Import.vue
=> Fix import default namespace picker

edit/management.cattle.io.setting.vue, list/management.cattle.io.setting.vue, models/management.cattle.io.feature.js
Fixes the bugs found by QA for #2216
=> Fix global settings issues

models/management.cattle.io.feature.js, plugins/steve/resource-instance.js
#2421
Tweaks the label to be consistent with the Ember UI
=> Change label for disabled feature flag

assets/translations/en-us.yaml, components/nav/Header.vue, pages/account/index.vue
#2087 
This PR fixes the issue in the front-end - the page will display and show a warning if the user does not have access to the Management.Token schema
=> API Keys: Fix issue if user does not have access to the TOKEN schema

assets/translations/en-us.yaml, components/ActionMenu.vue, models/management.cattle.io.feature.js
#2439 
This PR addresses this issue
=> Feature Flags: Don't show activate options if user does not have permission

.drone.yml, assets/translations/en-us.yaml, config/product/auth.js, list/management.cattle.io.feature.vue, nuxt.config.js, package.json, pages/prefs.vue
- Use node 12 for builds, and fix build on node >= 14
- Feature flags should use management store
- Hide users & auth product behind dev flag
=> Feature flags should use management store, node >= 14 support, hide user mgmt

edit/storage.k8s.io.storageclass/index.vue
- overlooked replacing one of the modeOverrides from a previous commit
https://github.com/rancher/dashboard/issues/2429#issuecomment-786302302
=> Removing modeOverride from CruResource

edit/persistentvolumeclaim.vue
When creating a PVC from an existing PV ember would set the capacity of the PVC to be the capacity of the selected PV. This adds that same behavior.
As a part of this I reset the value of the pv when switching sources to be consistent and to force the user to select the pv in order to trigger setting the capacity in case the value was changed by switching between sources.
rancher/dashboard#2448
=> Make the capacity of a PVC match a PV when selected

config/product/explorer.js
https://github.com/rancher/dashboard/issues/2111#issuecomment-786761541
=> hide rbac role template

edit/monitoring.coreos.com.receiver/types/email.vue, edit/monitoring.coreos.com.receiver/types/webhook.vue
https://github.com/rancher/dashboard/issues/1818#issuecomment-786761144
=> hide tls and auth fields from email and webhook receivers

components/formatter/VirtualServiceGateways.vue
#2467 - change VirtualServiceGateways to not assume Istio is installed into the namespace 'istio-system'
=> fix istio virtual service gateway table formatter

config/product/auth.js, edit/auth/github.vue, edit/auth/ldap/config.vue, mixins/auth-config.js
Tweaks to various auth input fields + hide auth providers if the user doesn't have access to that type
#2252 #2451 
issue 1 from https://github.com/rancher/dashboard/issues/2116#issuecomment-785547243
=> auth component input tweaks

assets/translations/en-us.yaml, edit/monitoring.coreos.com.receiver/auth.vue, edit/monitoring.coreos.com.receiver/types/email.vue, edit/monitoring.coreos.com.receiver/types/webhook.vue
- Nested tls and auth appropriately for email and webhook
- Added bearer-token-file
- Made the auth mechanisms mutually exclusive
https://github.com/rancher/dashboard/issues/1818#issuecomment-786942888
=>  Fixed the schema for email and webhook receiver configs

assets/translations/en-us.yaml, config/product/explorer.js, edit/rbac.authorization.k8s.io.roletemplate.vue, models/rbac.authorization.k8s.io.roletemplate.js, utils/custom-validators.js, utils/validators/role-template.js
- Ensuring that the verbs field is filled out
rancher/dashboard#2358
=> Adding validation to role template

config/product/auth.js
- These were fixed in real-time as part of the review of #2601
=> Missing fix for groups list

edit/management.cattle.io.user.vue
- Previously we saved the steve user and then changed the norman users password
- This process lead to the user edits being lost
- This is partly due to
- some kind of race condition occurring between the two quick requests
- the setpassword request, in the api, sets mustChangePassword to false
- So now we..
- change the norman users password first
- wait 5 seconds (!!) - (This needs to be discussed, see API bug comment below)
- change the norman users details
Other details...
- The old ember ui has this same issue
- Addresses bug found in #2524
- I've created a bug for the API to address the possible race condition - https://github.com/rancher/rancher/issues/31883
=> Ensure edits to a user's details and password are both saved correctly

config/product/auth.js
- The Groups list would not display In a system where global role bindings existed that pointed to a group from an old, disabled auth provider
- On my local system I had group roles bound to github groups... however my current auth provider was keycloak
- This led to requests to the github principals failing with `SAML: Invalid principal type`
- Now we cater for principals that aren't retrievable
=> Groups List: Guard against systems with global role bindings in historic auth providers

components/nav/Header.vue, components/nav/NamespaceFilter.vue
=> Fix for regression in namespace ctrl rendering

assets/translations/en-us.yaml, edit/persistentvolumeclaim.vue
=> Adding the 'Use default class' options to persistent volume claims

detail/workload/index.vue
#2390 
Simple fix for conditional logic to show tab
=> removed conditional logic to always show job tab

components/nav/WindowManager/ContainerLogs.vue, components/nav/WindowManager/ContainerShell.vue, components/nav/WindowManager/Window.vue
=> Fix rendering issues with the pod shell/logs window

assets/translations/en-us.yaml, edit/monitoring.coreos.com.receiver/index.vue, edit/monitoring.coreos.com.receiver/types/webhook.add.vue, edit/monitoring.coreos.com.receiver/types/webhook.banner.vue, edit/monitoring.coreos.com.receiver/types/webhook.vue, models/monitoring.coreos.com.receiver.js
We're adding more messaging and pre-populating the url field.
rancher/dashboard#2622
=> Making the use of MSTeams and AlibabaCloudSMS webhook receivers easier to use

components/nav/WindowManager/ContainerLogs.vue, components/nav/WindowManager/ContainerShell.vue, store/wm.js
#2646 
Also fix connection leaks when switching containers or closing tabs
=> Fix switching containers in shell/logs

assets/translations/en-us.yaml, edit/auth/saml.vue, mixins/auth-config.js
=> saml placeholders, shibb after disable

components/form/Select.vue
=> pass closeOnSelect prop through Select to v-select

components/ContainerResourceLimit.vue
=> Remove default vals for namespace resources

chart/logging/index.vue
=> Remap rke.windows to rke for logging values

assets/translations/en-us.yaml, models/catalog.cattle.io.app.js, pages/c/_cluster/apps/charts.vue, pages/c/_cluster/apps/install.vue, pages/prefs.vue, store/prefs.js, utils/version.js
=> Charts filter

assets/translations/en-us.yaml, edit/monitoring.coreos.com.receiver/types/webhook.add.vue
https://github.com/rancher/dashboard/issues/2622#issuecomment-816023579
=> Making text changes to webhook receivers to accomodate backend naming changes

assets/translations/en-us.yaml, components/DashboardMetrics.vue, components/DashboardOptions.vue, components/EtcdInfoBanner.vue, components/GrafanaDashboard.vue, components/Tabbed/Tab.vue, pages/c/_cluster/explorer/index.vue, utils/grafana.js
Dark:
Light:
Etcd banner
rancher/dashboard#812
=> Adding grafana graphs to the explorer index

pages/c/_cluster/apps/install.vue
=> Updating the order of chart versions on the install page

assets/translations/en-us.yaml, components/DashboardMetrics.vue, components/GrafanaDashboard.vue
=> Adding a link to the corresponding grafana dashboard within GrafanaDashboards.

pages/c/_cluster/apps/install.vue
=> Showing the Edit as Yaml button for all chart install tabs

pages/c/_cluster/explorer/index.vue
https://github.com/rancher/dashboard/issues/812#issuecomment-821351218
=> Making it so we see etcd metrics for rke.window clusters

components/nav/Favorite.vue, components/nav/Type.vue
Fixes a fww icon alignment issues
=> [2.6] Adjust icon alignments

assets/styles/themes/_light.scss, components/SortableTable/index.vue
Fixes a couple of issues:
- Adds border back to tables
- Reverts disabled color in light mode that looked too dark
=> [2.6] Fix minor styling issues

assets/translations/en-us.yaml, components/InfoBox.vue, edit/auth/github.vue, edit/auth/googleoauth.vue, pages/c/_cluster/auth/config/index.vue, utils/auth.js
#2655 - I updated the GH styling to match the Ember UI then updated the Google OAuth styling as well so the two are consistent with each other.
#2654
=> [2.6] Auth styling

edit/resources.cattle.io.restore.vue
=> [2.5.8] fix lost storageLocation.s3 for backup restore

edit/resources.cattle.io.restore.vue
=> [2.6] fix lost storageLocation.s3 for backup restore

assets/translations/en-us.yaml, edit/workload/index.vue, edit/workload/storage/index.vue, utils/validators/container-images.js
2.5.8 PR: https://github.com/rancher/dashboard/pull/2739
=> [2.6]  fix sidecar indexing, container image validation, workload storage pvc namespacing

assets/translations/en-us.yaml, components/nav/Group.vue, components/nav/Header.vue, components/nav/Jump.vue, components/nav/Type.vue, models/secret.js
Added as search icon in header bar
Keyboard shortcut still supported
Also fixes a bug with TLS certificates (in secrets.js)
=> [2.6] Add resource search back

assets/styles/themes/_dark.scss, assets/styles/themes/_light.scss, components/SortableTable/index.vue, components/form/KeyValue.vue
- table colors and hover/select state
- input backgrounds
=> [2.6] polish colors and style

assets/translations/en-us.yaml, components/BannerGraphic.vue, components/CommunityLinks.vue, components/SimpleBox.vue, components/SortableTable/index.vue, components/form/RadioGroup.vue, mixins/closeable.js, pages/c/_cluster/explorer/index.vue, pages/home/index.vue, pages/index.vue, pages/release-notes.vue, store/prefs.js, utils/units.js, utils/version.js
This takes the changes in PR #2584 and combines some changes and tweaks I'd made.
=> [2.6] Home Page

assets/translations/en-us.yaml, chart/rancher-alerting-drivers.vue, edit/monitoring.coreos.com.receiver/types/webhook.add.vue
=> [backport] Accomadating some minor UX change requests related to the rancher-alerting-drivers

assets/translations/en-us.yaml, chart/rancher-alerting-drivers.vue, edit/monitoring.coreos.com.receiver/types/webhook.add.vue
=> Accomadating some minor UX change requests related to the rancher-alerting-drivers

assets/translations/zh-hans.yaml
update CN contents in zh-hans.yaml
=> [2.5.8] update CN yaml

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml
- updated dashboard for CN
- fixed a typo in EN
=> [2.6] update dashboard for CN

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml
I don't know what happened here but there's tons of duplicate keys and other YAML errors...
=> Revert "[2.6] update dashboard for CN"

assets/translations/zh-hans.yaml
=> Revert "[2.5.8] update CN yaml"

components/form/KeyValue.vue, components/form/Security.vue, edit/workload/index.vue
2.6 flavor of this PR: https://github.com/rancher/dashboard/pull/2817
=> [2.6] workload sidecar fixes

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml
- fixed tons of duplicated keys and other YAML errors in @https://github.com/rancher/dashboard/pull/2798 and @https://github.com/rancher/dashboard/pull/2821. (done)
- updated dashboard for CN (done)
- fixed a typo in EN (done)
- comment out untranslated keys in zh-hans.yaml (in progress)
=> [2.6] update zh hans.yaml

edit/auth/googleoauth.vue, mixins/auth-config.js, plugins/steve/resource-instance.js
2.5.8 PR: https://github.com/rancher/dashboard/pull/2832
=> [2.6] google oauth

pages/c/_cluster/apps/install.vue
https://github.com/rancher/dashboard/issues/2837
=> [2.5.8] Add rke[Windows]PathPrefix global values

assets/styles/global/_gauges.scss, assets/translations/en-us.yaml, components/AlertTable.vue, components/ConsumptionGauge.vue, components/CountGauge.vue, components/PercentageBar.vue, components/SimpleBox.vue, pages/c/_cluster/explorer/HardwareResourceGauge.vue, pages/c/_cluster/explorer/ResourceSummary.vue, pages/c/_cluster/explorer/index.vue, pages/c/_cluster/monitoring/index.vue
#2737 with/without monitoring:
=> 2.6 cluster dashboard gauges

components/nav/Group.vue, components/nav/Type.vue
Fixes a couple of side-nav styling issues:
- 2nd level nav is not indented correctly
- 2nd level nav headers do not show hover background
- Improved styling of 2nd level nav items (reduce font size and less padding)
=> Fix side-nav styling issues

assets/translations/zh-hans.yaml
- add translations to new keys
- comment out **all** untranslated keys in zh-hans.yaml, associated with previous PR: https://github.com/rancher/dashboard/pull/2826
=> [2.6] update zh-hans.yaml, comment out all untranslated keys in zh-hans.yaml

edit/workload/index.vue
=> added min input value

assets/translations/zh-hans.yaml
- Fix indentation and duplicated keys errors in zh-hans.yaml
- Update zh-hans.yaml
- comment out untranslated keys in zh-hans.yaml
=> [2.5.8] Update zh-hans.yaml

assets/translations/en-us.yaml, pages/home/index.vue
=> explorer button in home page  cluster table

components/nav/Header.vue
- almost match line-height of button
- remove unused styles
=> Fix vertical alignment of icons in header top right buttons

pages/c/_cluster/monitoring/index.vue
=> Disable wrapping on the name column of the monitoring active alerts table

components/DetailText.vue
=> DetailText escape

components/form/ShellInput.vue
2.5.8 pr: https://github.com/rancher/dashboard/pull/2884
=> fix shellinput string parsing regex

components/ContainerResourceLimit.vue
=> Fix create/edit of resources that use ContainerResourceLimit

store/catalog.js, store/index.js
- catalog lives outside normal steve hydrate process
- now on client init we check charts are hydrated
=> Ensure catalog charts are rehydrated

components/CountBox.vue
This PR updates the styling of the CountBox component - removing the gradient background and making it consistent with the update 2.6 styling.
=> Update styling of CountBox component

assets/translations/en-us.yaml, components/form/SelectOrCreateAuthSecret.vue, edit/fleet.cattle.io.gitrepo.vue
=> Add support for helmSecretName in GitRepo 

assets/translations/en-us.yaml, components/AdvancedSection.vue, components/form/KeyValue.vue, components/nav/Header.vue, config/product/manager.js, edit/provisioning.cattle.io.cluster/NodePool.vue, edit/provisioning.cattle.io.cluster/rke2.vue, layouts/default.vue, machine-config/amazonec2.vue, machine-config/digitalocean.vue, models/management.cattle.io.cluster.js, models/provisioning.cattle.io.cluster.js, plugins/portal.js
- Cluster Tools only makes sense in Explorer
- Node Pool taints & labels
- Single + bulk download kubeconfig
=> Cluster features

assets/translations/en-us.yaml, pages/about.vue
=> Add Download CLI links to About Page

assets/translations/en-us.yaml, components/form/Checkbox.vue, config/private-label.js, middleware/authenticated.js, pages/auth/login.vue, pages/auth/setup.vue
=> initial setup flow

assets/translations/en-us.yaml, components/form/NameNsDescription.vue, pages/c/_cluster/apps/install.vue
- update icon and text for slide in 'dock' button
- update command step terminology (to align with step name)
- notify user that the custom namespace will be created
=> Minor tweaks to helm chart install process

assets/styles/global/_labeled-input.scss, assets/styles/themes/_light.scss, assets/translations/en-us.yaml, components/BrandImage.vue, components/CommunityLinks.vue, components/CruResourceFooter.vue, components/FixedBanner.vue, components/form/ColorInput.vue, components/form/FileSelector.vue, components/nav/Header.vue, components/nav/TopLevelMenu.vue, config/footer.js, config/product/settings.js, layouts/default.vue, layouts/home.vue, layouts/plain.vue, pages/auth/login.vue, pages/c/_cluster/settings/brand.vue, pages/home/index.vue, pages/support/index.vue
=> ui-banners, ui-pl, ui-logos settings page

components/BrandImage.vue
https://github.com/rancher/dashboard/issues/2506#issuecomment-843630454
=> fix BrandImage path when no ui-logo-light/dark

assets/translations/en-us.yaml, components/CopyCode.vue, components/PromptRestore.vue, components/SortableTable/index.vue, components/formatter/Si.vue, config/table-headers.js, config/types.js, detail/provisioning.cattle.io.cluster.vue, edit/provisioning.cattle.io.cluster/rke2.vue, layouts/default.vue, list/provisioning.cattle.io.cluster.vue, machine-config/amazonec2.vue, models/etcdbackup.js, models/provisioning.cattle.io.cluster.js, pages/home.vue, plugins/steve/actions.js, plugins/steve/resource-instance.js, plugins/steve/resource-proxy.js, plugins/steve/subscribe.js, store/action-menu.js
- Infammable means flammable? (readonly flag was backwards)
- Trim whitespace on command copy (#2991)
- AKS/EKS/GKE showing unknown node provider
- Handle missing server/agentArgs
- Add cluster buttons to home
- Start etcd-snapshot options
- RKE1 Snapshots
- RKE2 Snapshot list (create/restore API calls TBD)
=> Cluster bugs, etcd snapshot

pages/support/index.vue
Adds basic regex checking for the support subscription key
=> Add simple validation for subscription key

assets/translations/en-us.yaml, components/Banner.vue, components/FixedBanner.vue, pages/auth/setup.vue
- Use consistent vendor name (for now)
- Fix typo
- Improve presentation of banner component
- Tweak presentation of setup page
=> Styling refinements

assets/translations/en-us.yaml, pages/support/index.vue
completes the work on #2505 
This PR improves the presentation when support is enabled.
Also fixes a small issue where the dialog briefly flips between add/remove when you press the button in it.
=> Refinements to the support page

assets/translations/zh-hans.yaml
Community user suggested the translations below have some minor errors. Update the translations to fix these errors.
=> [2.5.8] update zh-hans translation

assets/translations/zh-hans.yaml
Community user suggested the translations below have some minor errors. Update the translations to fix these errors.
=> [2.6] update zh-hans translation

models/namespace.js
=> Switching the move icon for namespaces

assets/translations/en-us.yaml, config/settings.js, mixins/brand.js, pages/c/_cluster/settings/brand.vue, utils/color.js
=> custom color

assets/translations/en-us.yaml
https://github.com/rancher/dashboard/issues/2400#issuecomment-812007356
=> Adding a link to our documentation for monitoring receiver ssl sections

pages/home.vue
=> Add margin to home page

assets/translations/en-us.yaml, models/management.cattle.io.kontainerdriver.js
=> Fix for bug with embedding of Alibaba ACK

components/nav/TopLevelMenu.vue, config/settings.js
=> hide support link for non-admins

assets/translations/en-us.yaml, cloud-credential/vmwarevsphere.vue
rancher/dashboard#2969
Dashboard:
Ember:
=> Adding vsphere cloud credentials

middleware/authenticated.js, pages/auth/login.vue, pages/auth/setup.vue
- only affected unauthed world where partial settings list was fetched
- addresses #3160
=> Fix missing settings on log on

assets/translations/en-us.yaml, edit/auth/oidc.vue
- Ensure we clear custom form values when auth provider is disabled (#3159)
- When we no longer have custom form values ensure correct 'custom endpoints' is selected
- ~~blocked on #3164~~
=> Fix two OIDC Auth Provider form issues

config/types.js, edit/management.cattle.io.project.vue
=> Making use of the rancher/norman api to create/update projects

config/product/explorer.js, edit/node.vue
=> Porting node editing from ember to dashboard

models/management.cattle.io.kontainerdriver.js
=> Add Azure V2 to cluster selctor on create

assets/translations/en-us.yaml, components/CommunityLinks.vue, config/footer.js, config/settings.js, pages/c/_cluster/settings/brand.vue, pages/home.vue, pages/support/index.vue
=> support links tweaks

edit/namespace.vue
=> Use project container default values when creating a namespace

pages/c/_cluster/settings/brand.vue
Addresses #3140 
Make sure we don't build up error messages
=> Brand settings: Don't accumulate errors

pages/auth/login.vue
This PR adds support for the dark theme login background image.
=> Add support for dark themed login background image

assets/styles/themes/_dark.scss, assets/styles/themes/_light.scss
Addresses #3228 
Removed the background color from the header buttons.
Changed the text color in light mode to be the same as body text.
=> Update style of the header buttons

components/nav/Header.vue
=> Fix text overflow for cluster name

layouts/error.vue, middleware/authenticated.js, nuxt.config.js, plugins/back-button.js
=> Address issue where back button do cluster manager can give page not found error

pages/c/_cluster/settings/brand.vue
This PR addresses #3235
It also fixes:
- Save gives error
- Community links checkbox uses a string as value not boolean
=> Brand Setting Page fixes

assets/translations/en-us.yaml, components/MoveModal.vue, components/SortableTable/index.vue, components/dialog/AddProjectMemberDialog.vue, components/form/ArrayList.vue, components/form/ProjectMemberEditor.vue, config/product/explorer.js, config/query-params.js, config/types.js, edit/management.cattle.io.clusterroletemplatebinding.vue, edit/management.cattle.io.project.vue, edit/management.cattle.io.projectroletemplatebinding.vue, models/management.cattle.io.projectroletemplatebinding.js, pages/c/_cluster/explorer/members/index.vue
=> Migrating the project membership pages from ember to vue

pages/c/_cluster/apps/charts/install.vue
- Also tweak comments and vertical spacing
- addresses #3217
=> Chart Install: Show version selector when coming from cluster tools

components/nav/TopLevelMenu.vue
=> Remove primary/branded colour of local cluster side menu item

components/ContainerResourceLimit.vue, edit/management.cattle.io.project.vue
https://github.com/rancher/dashboard/issues/3104#issuecomment-858114480
=> Applying units to container resource limits for namespace editing

assets/translations/en-us.yaml, config/product/explorer.js, store/type-map.js
https://github.com/rancher/dashboard/issues/3278
=> Only show Cluster Members if the user has access

assets/translations/en-us.yaml, config/labels-annotations.js, config/product/explorer.js, models/management.cattle.io.clusterroletemplatebinding.js, pages/c/_cluster/explorer/members/index.vue, store/type-map.js
With the new check we can show a user who doesn't have access to other users a list of members while still omitting the system users.
https://github.com/rancher/dashboard/issues/3256
=> Updating how we check to see if a clusterroletemplatebinding isSystem

assets/translations/en-us.yaml, components/ResourceList/Masthead.vue, components/nav/Group.vue, config/product/explorer.js, config/types.js, edit/management.cattle.io.clusterroletemplatebinding.vue, pages/c/_cluster/_product/namespaces.vue, pages/c/_cluster/_product/projectsnamespaces.vue, pages/c/_cluster/explorer/members/index.vue
https://github.com/rancher/dashboard/issues/3247
=> Adding another custom permission option for cluster members and allow virtualtypes to be favorited

components/nav/WindowManager/ContainerShell.vue
We can't rely on the `currentCluster` os info as the indicator of what shell command should be used when connecting. I've added a work around to load the node that pod lives in but this will only work when users have access to the node as well. This is not guaranteed. I will open a backend ticket to add a steve formatter to add the os info to the pod. 
rancher/dashboard#3157
=> Windows Shell Bug

components/SortableTable/index.vue, pages/c/_cluster/explorer/tools/index.vue
- addresses #3288
- also added better gating when checking for legacy helm chart version
=> Show the bottom border of a table's status row

components/form/LabeledTooltip.vue
=> Fix styling issue of code block inside of a tooltip

assets/translations/en-us.yaml
=> Fix typo for multi-cluster apps

components/nav/Header.vue
=> Tweak tooltip hover on cluster name

config/product/fleet.js, list/management.cattle.io.feature.vue, store/features.js, store/type-map.js
=> Only show Continuous Delivery global app when feature flag is enabled

config/product/explorer.js
https://github.com/rancher/dashboard/issues/557#issuecomment-867158644
=> Making nodes editable

config/product/explorer.js
=> Removing ClusterRoleBindings, ClusterRoles, RoleBindings and Roles from the main RBAC nav

components/FleetResources.vue
Before:
After:
Issue: https://github.com/rancher/dashboard/issues/3390
=> Link fleet resources to individual resource detail pages

assets/translations/en-us.yaml, models/cluster.x-k8s.io.machine.js, models/cluster/node.js, models/management.cattle.io.node.js
=> Add 'Download SSH Key' action for Management Nodes

assets/translations/en-us.yaml, cloud-credential/vmwarevsphere.vue, components/form/ArrayList.vue, components/form/ArrayListSelect.vue, components/form/KeyValue.vue, components/form/LabeledSelect.vue, machine-config/vmwarevsphere.vue, utils/computed.js
Also fixed a bug with the vsphere credentials.
rancher/dashboard#2969
rancher/dashboard#3326
=> Adding the vSphere maching-config

list/management.cattle.io.feature.vue
=> Ignore errors when updating feature flag that requires a restart

models/provisioning.cattle.io.cluster.js
=> Prevent user from deleting the local cluster

assets/translations/en-us.yaml, components/dialog/AddClusterMemberDialog.vue, components/form/Members/ClusterMembershipEditor.vue, components/form/Members/ClusterPermissionsEditor.vue, components/form/Members/MembershipEditor.vue, components/form/Members/ProjectMembershipEditor.vue, components/form/ProjectMemberEditor.vue, edit/management.cattle.io.clusterroletemplatebinding.vue, edit/management.cattle.io.project.vue, edit/provisioning.cattle.io.cluster/import.vue, edit/provisioning.cattle.io.cluster/rke2.vue, models/management.cattle.io.clusterroletemplatebinding.js, models/management.cattle.io.projectroletemplatebinding.js, pages/c/_cluster/explorer/members/index.vue
=> Adding cluster membership to the rke2 pages

components/form/SecretSelector.vue, components/form/SelectOrCreateAuthSecret.vue
**Form fields in Cluster Private Registry & Agent Environment Vars tabs tweaks**
#3184 
Added css styling to make forms consistent height
=> Form field changes in Cluster Private Registry CSS changes

assets/translations/en-us.yaml, content/docs/en-us/release-notes.md, pages/docs/_doc.vue
First version of release notes.
Improved presentation of markdown docs.
=> Add release notes and improve presentation

models/management.cattle.io.nodetemplate.js
=> Make node template description safer for new clusters

components/nav/Group.vue, config/product/legacy.js, layouts/default.vue, pages/c/_cluster/legacy/project/pipelines.vue, store/type-map.js
=> Fix various side navigation bugs

store/type-map.js
=> Fix for #3436

assets/translations/en-us.yaml, components/LandingPagePreference.vue, components/SingleClusterInfo.vue, models/management.cattle.io.cluster.js, pages/c/_cluster/explorer/ResourceSummary.vue, pages/c/_cluster/explorer/index.vue, pages/home.vue
=> Improvements to the home page for single cluster install

components/EmberPage.vue, components/nav/WindowManager/index.vue
=> IFrame height should take into account the window manager when shown

assets/styles/themes/_dark.scss
=> Improve borders of simple box in dark mode

assets/translations/en-us.yaml, components/form/Taints.vue, edit/provisioning.cattle.io.cluster/MachinePool.vue, machine-config/amazonec2.vue
#3354 
Changed which translation to use to be consistent with other keyValue labels in form
=> Inconsistent option title and labels on buttons for node-label and node-taint for node driver

assets/styles/themes/_dark.scss, assets/styles/themes/_light.scss, components/SortableTable/index.vue
Addresses #2958
Tidy up table colors
Remove unused colors
Add color for table row background
Added a 2 pixel border on the group header so it looks a little better when the first row in the group is selected
=> Improve color contrast on table groups in dark mode

list/group.principal.vue, models/group.principal.js, pages/c/_cluster/explorer/tools/index.vue
=> Ensure remove respects ability to skip confirmation (Cluster tools, group principal)

assets/translations/en-us.yaml, list/management.cattle.io.feature.vue, pages/auth/setup.vue
#3286 
- hide the serverUrl step in the initial setup flow if mcm=false 
- prompt for the serverUrl to be set in the mcm feature flag confirmation modal (if not set already)
=> prompt for serverurl when enabling mcm

components/nav/WindowManager/ContainerShell.vue, edit/provisioning.cattle.io.cluster/rke2.vue
=> Shell timeout, machine config field rename

edit/management.cattle.io.user.vue
- For instance with --features=multi-cluster-management=false
- addresses #3451
=> Fix create/edit user when global roles are unavailable

edit/namespace.vue
=> Create namespace: Fix duplicate projects in dropdown

components/MoveModal.vue
#3456 - this issue is seen specifically when attempting to move a namespace not in a project
=> fix namespace move-project action

content/docs/en-us/release-notes.md, pages/docs/_doc.vue
=> Improve presentation of release notes

edit/workload/index.vue
=> Fix issue with name losing focus on deployment create

components/ResourceYaml.vue, pages/c/_cluster/apps/charts/install.vue
=> Fix broken YAML diff

components/nav/Group.vue, components/nav/Jump.vue
=> Fix broken resource search

assets/styles/global/_resource.scss, components/CruResource.vue
=> Fix minor issue with icon alignment on create page

assets/styles/base/_basic.scss
login page/ global dark hover fix
=> focus btn on dark fix

assets/translations/en-us.yaml, edit/networking.istio.io.destinationrule/LoadBalancer.vue, edit/networking.istio.io.destinationrule/index.vue, models/networking.istio.io.destinationrule.js
#1106 
Istio Destination Create Edit Form
=> Istio CRD Destination Rule Form

assets/translations/en-us.yaml, components/IconMessage.vue, components/ResourceDetail/index.vue
Addresses #3436 from a UI point of view
Created backend ticket to look at why the resource is being returned: https://github.com/rancher/rancher/issues/33657
=> Catch resource not found on ResourceDetail view

utils/select.js
=> Fix OPA Gatekeeper constraint creation bug (namespace)

scripts/backend
Simple script for running backend in docker - helps with resetting the password. Also makes it easy to deploy single cluster mode.
=> Helper script for running backend in docker

edit/management.cattle.io.project.vue
=> Only show the project members tab to users who have access to members

assets/translations/en-us.yaml, edit/provisioning.cattle.io.cluster/AgentEnv.vue
#3184 
Update KeyValue component key name
=> Custom Cluster Agent Environment Vars Key Title Change

assets/translations/en-us.yaml, edit/auth/oidc.vue
This reverts commit 828e7e12de0c1b1620cc5ed984f6e31c494a555c.
=> Revert "Optionally supply 'service' account to keycloak auth config"

content/docs/en-us/getting-started.md, pages/docs/_doc.vue
=> Initial Getting Started doc

mixins/auth-config.js
- When setting up an auth provider the config is tested and the user validates against said provider
- We then fetch the principals to find the authenticated user and save it in the auth config
- If however the config is updated by the backend as part of the test process we save a stale version overwriting those changes
- So ensure we reload the resource before proceeding
=> [2.6] Reload Auth Config before saving new principal id

config/labels-annotations.js, edit/management.cattle.io.project.vue, models/management.cattle.io.project.js
https://github.com/rancher/dashboard/issues/3550
=> Removing the member owner requirement from system and default projects

config/labels-annotations.js, edit/management.cattle.io.project.vue, models/management.cattle.io.project.js
https://github.com/rancher/dashboard/issues/3550
backport: https://github.com/rancher/dashboard/pull/3561
=> [backport] Removing the member owner requirement from system and default projects

pages/c/_cluster/explorer/members/index.vue
https://github.com/rancher/dashboard/issues/3537
=> Have it so we show the Default Admin member on rke1 clusters

pages/c/_cluster/explorer/members/index.vue
https://github.com/rancher/dashboard/issues/3537
backport: https://github.com/rancher/dashboard/pull/3570
=> [backport] Have it so we show the Default Admin member on rke1 clusters

edit/management.cattle.io.project.vue
Backport of https://github.com/rancher/dashboard/pull/3582
=> [2.6]display errors from project create/edit

edit/management.cattle.io.project.vue
=> [master]display errors from project create/edit

pages/auth/setup.vue
- setup page covers use case where user has to change password on first log in
- #3612
=> [2.6] Fix issue where setup fields were shown when user was changing password on log in

pages/auth/setup.vue
- setup page covers use case where user has to change password on first log in
- master port of #3614
- #3612
=> [master] Fix issue where setup fields were shown when user was changing password on log in

components/BrandImage.vue, mixins/brand.js
=> [master] Ensure we don't generically `management/findAll` settings type before logging in

detail/fleet.cattle.io.cluster.vue, edit/fleet.cattle.io.cluster.vue
=> fix bug fetching mgmt cluster on fleet cluster detail/edit

detail/fleet.cattle.io.cluster.vue, edit/fleet.cattle.io.cluster.vue
backport of https://github.com/rancher/dashboard/pull/3540
=> [2.6] fix bug fetching mgmt cluster on fleet cluster detail/edit

assets/translations/en-us.yaml
=> Update text for RKE template creation to match ember UI

assets/translations/en-us.yaml, models/provisioning.cattle.io.cluster.js, utils/custom-validators.js, utils/validators/cluster-name.js
=> [2.6]cluster name validation

assets/translations/en-us.yaml, models/provisioning.cattle.io.cluster.js, utils/custom-validators.js, utils/validators/cluster-name.js
https://github.com/rancher/dashboard/pull/3616
=> [master] cluster name validation

edit/management.cattle.io.user.vue
=> [master]focus username field initially on create user page

edit/management.cattle.io.user.vue
https://github.com/rancher/dashboard/pull/3618
=> [2.6]focus username field initially on create user page 

cloud-credential/gcp.vue, edit/monitoring.coreos.com.receiver/index.vue
- click was failing due to
```
The .native modifier for v-on is only valid on components but it was used on <div>
```
- also fix linting error
- #3617
=> [2.6] Fix click of receiver type in create receiver page

cloud-credential/gcp.vue, edit/monitoring.coreos.com.receiver/index.vue
- click was failing due to
```
The .native modifier for v-on is only valid on components but it was used on <div>
```
- also fix linting error
- #3636
- #3617
=> [master] Fix click of receiver type in create receiver page

cloud-credential/gcp.vue, edit/provisioning.cattle.io.cluster/rke2.vue
https://github.com/rancher/dashboard/pull/3634
=> [2.6]fix rke2 edit done route

assets/translations/en-us.yaml
=> [2.6] Update text for RKE template creation to match ember UI

machine-config/vmwarevsphere.vue
=> Preventing the hostsystem value receiving the SENTINEL value

assets/translations/en-us.yaml, edit/provisioning.cattle.io.cluster/rke2.vue
https://github.com/rancher/dashboard/issues/3589
=> Inform the users that legacy features aren't supported in k8s 1.21+

assets/translations/en-us.yaml, edit/provisioning.cattle.io.cluster/rke2.vue
https://github.com/rancher/dashboard/issues/3589
forwardport of https://github.com/rancher/dashboard/pull/3650
=> [forwardport] Inform the users that legacy features aren't supported in k8s 1.21+

edit/provisioning.cattle.io.cluster/rke2.vue
https://github.com/rancher/dashboard/pull/3663
=> [2.6]fix rke2 defaults

mixins/auth-config.js
=> [master] Reload Auth Config before saving new principal id

components/form/Members/MembershipEditor.vue
Making an exception for cluster/project owners when filtering out system bindings. Also making sure we filter out the default binding when evaluating newBindings since this yielded us adding a second admin to project pages.
https://github.com/rancher/dashboard/issues/3550#issuecomment-891359765
=> Making the default admin show up for default/system projects

components/form/Members/MembershipEditor.vue
Making an exception for cluster/project owners when filtering out system bindings. Also making sure we filter out the default binding when evaluating newBindings since this yielded us adding a second admin to project pages.
https://github.com/rancher/dashboard/issues/3550#issuecomment-891359765
forwardport of https://github.com/rancher/dashboard/pull/3656
=> [forwardport] Making the default admin show up for default/system projects

components/nav/Group.vue
#3512 - this can be reproduced by using the ROUTER_BASE environment variable (see slack thread)
=> fix left nav group expansion

components/nav/Group.vue
#3512 
https://github.com/rancher/dashboard/pull/3676
=> [2.6] bugfix nav product switch

cloud-credential/vmwarevsphere.vue
=> Vsphere authentication

cloud-credential/vmwarevsphere.vue
rancher/dashboard#3526
forwardport of https://github.com/rancher/dashboard/pull/3685
=> [forwardport] Vsphere authentication

components/nav/Type.vue
#3652 
backport of https://github.com/rancher/dashboard/pull/3696
=> [2.6]fix selecting currently-active nav item

components/nav/Type.vue
=> [master]fix selecting currently-active nav item

assets/translations/en-us.yaml, detail/provisioning.cattle.io.cluster.vue, models/cluster/node.js, models/management.cattle.io.node.js
#3366
backport of https://github.com/rancher/dashboard/pull/3702
=> [2.6]add norman node scale down action

assets/translations/en-us.yaml, detail/provisioning.cattle.io.cluster.vue, models/management.cattle.io.node.js
=> [master]add norman node scale down action

components/form/Members/MembershipEditor.vue, edit/provisioning.cattle.io.cluster/import.vue, edit/provisioning.cattle.io.cluster/rke2.vue, models/provisioning.cattle.io.cluster.js
1) Ensure we don't nav away while calling `this.save`
2) Ensure we don't nav away when errors in `this.save`
This should resolve #3396 and most of #3677
2.6 PR #3711
=> [master] Ensure we wait for required resources before leaving cluster import / create rke2

components/IndentedPanel.vue, components/ResourceDetail/index.vue, components/nav/TopLevelMenu.vue, config/query-params.js, edit/provisioning.cattle.io.cluster/import.vue, edit/provisioning.cattle.io.cluster/index.vue, edit/provisioning.cattle.io.cluster/rke2.vue, layouts/plain.vue, list/management.cattle.io.setting.vue, list/provisioning.cattle.io.cluster.vue, mixins/chart.js, models/chart.js, models/provisioning.cattle.io.cluster.js, pages/c/_cluster/apps/charts/install.vue, pages/c/_cluster/settings/brand.vue, store/catalog.js, store/index.js
- master port of #3554
#3416 
Contains #3711
=> [master] Non-admin permissions based errors

mixins/auth-config.js
The newly created auth model ends up missing secrets so we add them back before we attempt to resave the auth model.
https://github.com/rancher/dashboard/issues/3734
=> Ensuring that secrets are added to the new auth model

mixins/auth-config.js
The newly created auth model ends up missing secrets so we add them back before we attempt to resave the auth model.
https://github.com/rancher/dashboard/issues/3734
forward port of https://github.com/rancher/dashboard/pull/3739
=> [forwardport] Ensuring that secrets are added to the new auth model

models/rke-machine.cattle.io.vmwarevspheremachinetemplate.js
=> Fixing the memory and cpu paths

models/rke-machine.cattle.io.vmwarevspheremachinetemplate.js
rancher/dashboard#3679
forwardport of https://github.com/rancher/dashboard/pull/3741
=> [forwardport] Fixing the memory and cpu paths

edit/provisioning.cattle.io.cluster/ACE.vue, edit/provisioning.cattle.io.cluster/rke2.vue
https://github.com/rancher/dashboard/issues/3727
forward port of https://github.com/rancher/dashboard/pull/3746
=> [forwardport] Ensuring radio fields are set for automatic snapshots and authorized endpoints

edit/provisioning.cattle.io.cluster/ACE.vue, edit/provisioning.cattle.io.cluster/rke2.vue
https://github.com/rancher/dashboard/issues/3727
=> Ensuring radio fields are set for automatic snapshots and authorized endpoints

cloud-credential/generic.vue
=> [master]prepopulate keys on edit generic cloud cred
