rancher/dashboard

cloud-credential/generic.vue
#3723 
backport of https://github.com/rancher/dashboard/pull/3753
=> [2.6]pre-populate keys on edit generic cloud cred

pages/auth/login.vue
https://github.com/rancher/dashboard/issues/3526#issuecomment-896215589
=> Adding whitespace trim to the username on login

pages/auth/login.vue
https://github.com/rancher/dashboard/issues/3526#issuecomment-896215589
forwardport of https://github.com/rancher/dashboard/pull/3766
=> [forwardport] Adding whitespace trim to the username on login

models/management.cattle.io.node.js
#3366
backport of https://github.com/rancher/dashboard/pull/3748
=> [2.6]disable scaledown when last node in only pool

components/form/ServicePorts.vue
#3701 
backport of https://github.com/rancher/dashboard/pull/3759
=> [2.6]fix service targetport type

machine-config/azure.vue
#3758 
backport of https://github.com/rancher/dashboard/pull/3764
=> [2.6]fix azure machine config requests

edit/provisioning.cattle.io.cluster/index.vue
If you go straight from home page to create then you may not have listed prov/mgmt clusters and have them listening for changes yet.
=> [Master] Make sure we're subscribed to clusters

assets/translations/en-us.yaml, components/form/Members/MembershipEditor.vue
#3790 
backport of https://github.com/rancher/dashboard/pull/3799
=> [2.6]remove references to /v1/users in membershipeditor

components/PromptRestore.vue, pages/c/_cluster/auth/roles/index.vue
- Effects those without local cluster access but with `Manage Roles` global role
- #3783
- master port #3822
=> [2.6] Ensure those without access to local cluster can still create cluster & project roles

pages/c/_cluster/auth/roles/index.vue
- Effects those without local cluster access but with `Manage Roles` global role
- #3783
=> [master] Ensure those without access to local cluster can still create cluster & project roles

config/types.js, detail/provisioning.cattle.io.cluster.vue, models/management.cattle.io.nodepool.js
backport of https://github.com/rancher/dashboard/pull/3845
=> [2.6]use norman node pool for scale up/down

components/GlobalRoleBindings.vue, components/auth/RoleDetailEdit.vue, config/types.js, models/management.cattle.io.globalrole.js, models/management.cattle.io.globalrolebinding.js, models/management.cattle.io.roletemplate.js
forwardport of https://github.com/rancher/dashboard/pull/3849
=> [forwardport] Migrating RBAC to use the norman API

nuxt.config.js, pages/docs/_doc.vue
2.6 branch fix
Addresses #3462
=> [2.6] Fix formatting on release notes page

assets/translations/en-us.yaml, components/Banner.vue, components/ResourceList/Masthead.vue, components/Tabbed/index.vue, components/form/SelectOrCreateAuthSecret.vue, config/product/auth.js, config/product/manager.js, config/types.js, detail/management.cattle.io.user.vue, detail/provisioning.cattle.io.cluster.vue, edit/provisioning.cattle.io.cluster/MachinePool.vue, edit/provisioning.cattle.io.cluster/RegistryConfigs.vue, edit/provisioning.cattle.io.cluster/RegistryMirrors.vue, edit/provisioning.cattle.io.cluster/S3Config.vue, edit/provisioning.cattle.io.cluster/index.vue, edit/provisioning.cattle.io.cluster/rke2.vue, list/provisioning.cattle.io.cluster.vue, mixins/child-hook.js, models/management.cattle.io.node.js, models/provisioning.cattle.io.cluster.js, pages/c/_cluster/explorer/index.vue, plugins/steve/getters.js, plugins/steve/index.js, plugins/steve/subscribe.js, store/features.js, store/index.js, store/plugins.js, utils/validators/cluster-name.js
- Show error if there's no KDM data
- Allow empty cluster name (#3798)
- Only show cloud-providers applicable to selected driver (#3709)
- Edit yaml for !rke2 cluster should show mgmt cluster
- Blocked create verb
- vsphere -> rancher-vsphere (rancher/issues#33875)
- Bucket is required if not in cloud-cred
- Socket Debug option
- Hide removed pools from list
- Disable unreferenced types
- Need edit to take snapshots
- Use norman action for download rke1 ssh keys
- Don't ask for cloud cred on view
- Define & use canList before findAlls instead of schemaFor
- Handle no access to see machine config (rancher/rancher#34256)
- Hooks should be applied serially so later priorities can depend on earlier
- Simpler private registry option (rancher/rancher#34223)
=> [Master] More & less bugs

components/form/Members/ClusterMembershipEditor.vue, components/form/Members/ClusterPermissionsEditor.vue, components/form/Members/MembershipEditor.vue, components/form/Members/ProjectMembershipEditor.vue, edit/management.cattle.io.project.vue, edit/provisioning.cattle.io.cluster/import.vue, edit/provisioning.cattle.io.cluster/rke2.vue, pages/c/_cluster/explorer/members/index.vue
- Ensure users can only see cluster/project membership details if they have perms to
Addresses: #3721, part of #3721
2.6: #3780
=> [master] Ensure base users with create cluster rights can create / manage cluster

components/Markdown.vue
=> [2.6] Markdown: Don't render relative links as anchors

components/EmberPage.vue, store/auth.js, utils/ember-page.js
- on auth/logout ensure the iframe is removed instead of waiting for the timer
- solution probably over implemented, but wanted to ensure timer is also cleared on logout
Addresses #3884
Master PR #3889
=> [2.6] Ensure iframe is cleared on log out

components/EmberPage.vue, store/auth.js, utils/ember-page.js
- on auth/logout ensure the iframe is removed instead of waiting for the timer
- solution probably over implemented, but wanted to ensure timer is also cleared on logout
Addresses #3884
2.6 PR #3888
=> [master] Ensure iframe is cleared on log out

assets/translations/en-us.yaml
This will provide us with a friendly name when refrencing the azurekubernetesservice provider
https://github.com/rancher/dashboard/issues/3714#issuecomment-900700120
=> [2.6] Adding the azurekubernetesservice provider key

assets/translations/en-us.yaml
This will provide us with a friendly name when refrencing the azurekubernetesservice provider
https://github.com/rancher/dashboard/issues/3714#issuecomment-900700120
=> [master] Adding the azurekubernetesservice provider key

components/form/Members/MembershipEditor.vue
We now filter based on the binding.user.isSystem setting.
https://github.com/rancher/dashboard/issues/3256#issuecomment-901020053
=> [master] Updating how we do binding filtering

components/form/Members/MembershipEditor.vue
We now filter based on the binding.user.isSystem setting.
https://github.com/rancher/dashboard/issues/3256#issuecomment-901020053
=> [2.6] Updating how we do binding filtering

components/form/Members/ClusterPermissionsEditor.vue, components/form/Members/MembershipEditor.vue, components/form/Members/ProjectMembershipEditor.vue, edit/management.cattle.io.clusterroletemplatebinding.vue
#3907 
backport of https://github.com/rancher/dashboard/pull/3915
=> [2.6]fix clusterrolebinding creation for standard user

mixins/brand.js
#3861 
backport of https://github.com/rancher/dashboard/pull/3922
=> fix custom brand when subscription enabled

assets/translations/en-us.yaml, config/product/legacy.js
2.6 port of https://github.com/rancher/dashboard/pull/3932
=> [2.6] Embed secrets page for leagcy project secrets

assets/translations/en-us.yaml, config/product/legacy.js
=> [master] Embed secrets page for legacy project secrets

middleware/authenticated.js, store/index.js
#3867 - Small change needed; looks like there was some code intended to catch this error that just wasn't quite.
=> [master]catch cluster not found errors

middleware/authenticated.js, store/index.js
#3867 
backport of https://github.com/rancher/dashboard/pull/3954
=> [2.6]catch cluster not found errors

components/dialog/AddProjectMemberDialog.vue, components/form/Members/ClusterMembershipEditor.vue, components/form/Members/ClusterPermissionsEditor.vue, components/form/Members/MembershipEditor.vue, components/form/Members/ProjectMembershipEditor.vue, edit/management.cattle.io.project.vue, edit/provisioning.cattle.io.cluster/import.vue, edit/provisioning.cattle.io.cluster/rke2.vue, models/clusterroletemplatebinding.js, models/projectroletemplatebinding.js, pages/c/_cluster/explorer/members/index.vue
Removed binding filtering and now just use norman bindings. The backend actually does the filtering when using norman.
https://github.com/rancher/dashboard/issues/3768#issuecomment-901827980
=> [master] Now directly create and interact with norman bindings

components/dialog/AddProjectMemberDialog.vue, components/form/Members/ClusterMembershipEditor.vue, components/form/Members/ClusterPermissionsEditor.vue, components/form/Members/MembershipEditor.vue, components/form/Members/ProjectMembershipEditor.vue, edit/management.cattle.io.project.vue, edit/provisioning.cattle.io.cluster/import.vue, edit/provisioning.cattle.io.cluster/rke2.vue, models/clusterroletemplatebinding.js, models/projectroletemplatebinding.js, pages/c/_cluster/explorer/members/index.vue
Removed binding filtering and now just use norman bindings. The backend actually does the filtering when using norman.
https://github.com/rancher/dashboard/issues/3768#issuecomment-901827980
=> [2.6] Now directly create and interact with norman bindings

assets/translations/en-us.yaml, edit/provisioning.cattle.io.cluster/CustomCommand.vue, list/node.vue, models/management.cattle.io.cluster.js
This displays warning to the user, notifying them that workloads will deploy to both windows and linux nodes. This warning is displayed while registering windows nodes or viewing a collection of nodes for a cluster that contains windows nodes. 
#3921
=> [master] Warn users about adding windows and linux nodes

components/Questions/Map.vue, config/product/explorer.js, edit/provisioning.cattle.io.cluster/rke2.vue, list/management.cattle.io.setting.vue, machine-config/generic.vue, machine-config/vmwarevsphere.vue, models/management.cattle.io.setting.js
- Prevent edit of settings set by env var
- Less loading in cluster create, preserve vmware values (#3924)
- Exclude cloud cred keys from generic machine config (#3851)
=> [Master] bugs

components/Questions/Map.vue, config/product/explorer.js, edit/provisioning.cattle.io.cluster/rke2.vue, list/management.cattle.io.setting.vue, machine-config/generic.vue, machine-config/vmwarevsphere.vue, models/management.cattle.io.setting.js
- Separate group for upgrade controller
- Prevent edit of settings set by env var
- Less loading in cluster create, preserve vmware values (#3924)
- Exclude cloud cred keys from generic machine config (#3851)
=> [2.6] bugs

pages/c/_cluster/auth/roles/index.vue
- take into account `blocked-PUT`
2.6: #3968
=> [master] Ensure create role button shows in Roles page

pages/c/_cluster/auth/roles/index.vue
- take into account blocked-PUT
Master: #3967
=> [2.6] Ensure create role button shows in Roles page

models/management.cattle.io.project.js
#3828 
backport of https://github.com/rancher/dashboard/pull/3970
=> [2.6]revert to using norman to delete projects

pages/docs/_doc.vue
=> [master] Fix svg icon color in doc page

pages/docs/_doc.vue
Port of https://github.com/rancher/dashboard/pull/3978
=> [2.6] Fix svg icon color in doc page

config/private-label.js, edit/management.cattle.io.setting.vue, pages/auth/login.vue, pages/support/index.vue, store/index.js
=> [2.6] Fix for vendor not showing as 'SUSE Rancher'

config/private-label.js, edit/management.cattle.io.setting.vue, pages/auth/login.vue, pages/support/index.vue, store/index.js
Addresses https://github.com/rancher/dashboard/issues/3982
The vendor needs to be changed to SUSE Rancher if the ui-brand setting is suse.
=> [master] Fix for vendor not showing as 'SUSE Rancher'

docs/developer/getting-started/development.md
This adds some documentation on creating custom validation functions to our developer guide. I figured it would be good to have a few examples out there for new people to reference.
=> [master] Outline steps for creating custom validation function

assets/styles/themes/_dark.scss, assets/styles/themes/_light.scss
=> [2.6] Fix text color in namespace dropdown

assets/styles/themes/_dark.scss, assets/styles/themes/_light.scss
=> [master] Fix text color in namespace dropdown

components/PromptRestore.vue, edit/provisioning.cattle.io.cluster/SelectCredential.vue, edit/provisioning.cattle.io.cluster/rke2.vue, machine-config/amazonec2.vue, machine-config/azure.vue, machine-config/digitalocean.vue, machine-config/vmwarevsphere.vue, store/digitalocean.js
=> [Master] I can't believe it's more bugs

components/PromptRestore.vue, edit/management.cattle.io.project.vue, edit/provisioning.cattle.io.cluster/SelectCredential.vue, edit/provisioning.cattle.io.cluster/rke2.vue, machine-config/amazonec2.vue, machine-config/azure.vue, machine-config/digitalocean.vue, machine-config/vmwarevsphere.vue, store/digitalocean.js
=> [2.6] I can't believe it's more bugs

edit/management.cattle.io.project.vue
(not as bad as it looks, the file had the wrong line endings)
=> Empty resource quota

assets/translations/en-us.yaml, config/settings.js, mixins/brand.js, pages/c/_cluster/settings/brand.vue
This allows colors for links to be customized in the dashboard. 
#4019
=> Allow link colors to be customized

components/nav/Jump.vue
=> Hide legacy resources in resource search

edit/management.cattle.io.clusterroletemplatebinding.vue
=> Show error message when adding user to cluster

assets/translations/en-us.yaml, components/form/Security.vue, edit/workload/index.vue
#4099 
An input has been added in Security Context tab when creating a new workload.
=> Add Pod Filesystem Group input in workload creation

assets/translations/en-us.yaml, edit/provisioning.cattle.io.cluster/rke2.vue
Addresses https://github.com/rancher/dashboard/issues/4081
=> Change suffix used for 'keep last N snapshots'

plugins/steve/hybrid-class.js, plugins/steve/resource-proxy.js, plugins/steve/steve-class.js
=> Handle Norman types via Steve

edit/storage.k8s.io.storageclass/provisioners/kubernetes.io/azure-disk.vue
https://github.com/rancher/dashboard/issues/4134
=> Removing the ability to create new Azure Disk storage classes with the shared kind

models/cluster/node.js
https://github.com/rancher/dashboard/issues/4169
=> Remove delete as an available action to nodes provisioned by the cloud provider k8s services

config/product/istio.js, config/types.js, pages/c/_cluster/explorer/tools/index.vue, store/type-map.js
Addresses #4072 
Also fixes issue where v1 apps are no longer detected
=> Fix issue where istio appear in side nav when v1 Istio is installed

config/types.js, edit/fleet.cattle.io.cluster.vue, models/management.cattle.io.fleetworkspace.js
https://github.com/rancher/dashboard/issues/4167
https://github.com/rancher/dashboard/issues/4188
=> Switching fleetworkspace to norman and correcting how fleet clusters search for other clusters

edit/provisioning.cattle.io.cluster/rke2.vue
=> Only show latest minor rke2/k3s releases

components/PromptRestore.vue
https://github.com/rancher/dashboard/issues/4221
=> Handling the case where etcdSnapshotRestore isn't defined

components/form/Labels.vue, models/app.class.js, models/configmap.class.js, models/pod.class.js, models/workload.class.js
=> fix workload class, label and annotation component

plugins/steve/actions.js, plugins/steve/index.js, plugins/steve/mutations.js, plugins/steve/subscribe.js, utils/promise.js
=> Defer duplicate requests in flight

assets/translations/en-us.yaml, components/auth/SelectPrincipal.vue, components/form/ProjectMemberEditor.vue
https://github.com/rancher/dashboard/issues/4004#issuecomment-925213902
=> fix add project member select placeholder

assets/translations/en-us.yaml, edit/fleet.cattle.io.gitrepo.vue, list/fleet.cattle.io.bundle.vue
Addresses remaining issues on https://github.com/rancher/dashboard/issues/4250
=> Fix issues with fleet and Harvester clusters

chart/monitoring/ClusterSelector.vue
https://github.com/rancher/dashboard/issues/4288
=> Updating Prometheus default memory limit

models/management.cattle.io.cluster.js
Fixes a minor issue - saw this when importing a Harvester cluster
=> Fix issue accessing provider if status is undefined

assets/translations/en-us.yaml, list/harvesterhci.io.management.cluster.vue
=> Harvester: Add intro block to VMgmt when there are no Harvester clusters

components/CommunityLinks.vue, components/PromptRemove.vue, components/ResourceTable.vue, components/YamlEditor.vue, components/formatter/HarvesterIpAddress.vue, components/nav/Header.vue, config/product/harvester.js, edit/harvesterhci.io.host/HarvesterDisk.vue, edit/harvesterhci.io.virtualmachinebackup.vue, edit/harvesterhci.io.virtualmachineimage.vue, edit/kubevirt.io.virtualmachine/VirtualMachineCloudConfig.vue, edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue, edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue, list/harvesterhci.io.host/index.vue, list/harvesterhci.io.virtualmachinebackup.vue, mixins/brand.js, mixins/harvester-vm.js, models/harvester/configmap.class.js, models/harvester/kubevirt.io.virtualmachine.js, models/management.cattle.io.project.js, pages/c/_cluster/harvester/support/index.vue, plugins/extend-router.js, store/harvester-common.js, store/index.js, utils/validators/vm-datavolumes.js
rancher:
- https://github.com/rancher/dashboard/issues/4299
Fix isNamespaced's resource filter condition
harvester:
singleVirtualCluster bug fix
=> HARVESTER: harvester bug fix

docs/developer/getting-started/development.md, docs/developer/getting-started/development_environment.md
Sources:
- Nancy
- Vince
- Team discussions
- Trial and error
=> Expand developer docs

config/labels-annotations.js, edit/fleet.cattle.io.gitrepo.vue, edit/harvesterhci.io.management.cluster.vue, utils/cluster.js
Addresses https://github.com/rancher/rancher/issues/34880, https://github.com/rancher/rancher/issues/34954
=> Change Harvester cluster label, exclude harvester clusters from fleet targets

docs/developer/getting-started/development.md
Follow up to https://github.com/rancher/dashboard/pull/4473
=> Remove outdated info

plugins/steve/hybrid-class.js, plugins/steve/mutations.js
=> hybrid class fix

edit/workload/storage/index.vue
#4356 
Add complexity Volume Name generation to avoid duplicates (eg from vol-1 to vol-uryd3)
=> Workload volumes duplicate auto-generated names

edit/logging-flow/index.vue
Addresses https://github.com/rancher/dashboard/issues/4415
=> rancher-logging: Show all global ClusterOutputs when creating a namespaced Flow

detail/workload/index.vue, models/apps.deployment.js
rancher/rancher#1879
For testing you will have to test this on a local cluster unless you have your cluster setup behind a domain with a valid certificate due to https://github.com/rancher/rancher/issues/31891
=> Adding metrics to the Deployment display page

assets/translations/en-us.yaml, machine-config/azure.vue
=> Adding the plan field to the azure driver

assets/translations/en-us.yaml, components/form/KeyValue.vue, components/form/LabeledInput.vue, plugins/core-store/resource-class.js, products/epinio/config/product/epinio.js, products/epinio/edit/services.vue, products/epinio/list/namespaces.vue, products/epinio/list/services.vue, products/epinio/models/applications.js, products/epinio/models/epinio-resource.js, products/epinio/models/services.js, products/epinio/pages/c/_cluster/applications/index.vue
=> Add Epinio service create form

list/management.cattle.io.feature.vue, models/management.cattle.io.feature.js
Addresses #4556 
- Added a lock icon alongside the name when feature flag is locked
- Hides enable/disable action for locked feature flags
-
=> Hide enabled/disable actions for locked feature flags

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, components/HarvesterServiceAddOnConfig.vue, edit/provisioning.cattle.io.cluster/rke2.vue, edit/service.vue, utils/cluster.js
- https://github.com/rancher/dashboard/issues/4451
=> HARVESTER: Better loadblancer config of Harvester cloud provider

config/labels-annotations.js, pages/c/_cluster/apps/charts/install.vue
Addresses #4402 
This PR checks for the presence of the migrated app annotation and when present will also send that annotation when performing an upgrade.
=> Pass migrated annotation when present

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, components/form/UnitInput.vue, config/settings.js, detail/harvesterhci.io.management.cluster.vue, detail/provisioning.cattle.io.cluster.vue, machine-config/harvester.vue
- https://github.com/rancher/dashboard/issues/4531
- https://github.com/harvester/harvester/issues/1030
**Additional Context**
[Import cluster instuction]
[Setting Config]
[Machine Config]
=> HARVESTER: Mutil-cluster import harvester enhancement

components/form/KeyValue.vue
Relates to https://github.com/rancher/dashboard/issues/4198
=> Better detection of appropriate line splitter

plugins/steve/resource-class.js
- https://github.com/harvester/harvester/issues/1571
The resourceMethods property is not found when using spoofedType.
=> HARVESTER: fixed can"t found resourceMethods in spoofedType

edit/persistentvolume/index.vue, edit/persistentvolumeclaim.vue, edit/workload/storage/persistentVolumeClaim/persistentvolumeclaim.vue
I failed to fix two instances of UnitInput in #4542
=> fix pvc unitinput

assets/styles/themes/_light.scss, components/SelectIconGrid.vue
badges in cards hard to read, white across all themes and backgrounds fixes this
=> badges in light card view

edit/provisioning.cattle.io.cluster/ACE.vue, models/management.cattle.io.nodepool.js
- Move ACE configuration up a level (#4410)
- Delete nodepools with norman (#4321)
=> ACE config and RKE1 Nodepool delete

assets/translations/en-us.yaml, detail/provisioning.cattle.io.cluster.vue
=> Cluster provisioning log

middleware/authenticated.js, store/index.js
https://github.com/rancher/dashboard/pull/4635#discussion_r755472424 - yes, it does blow up.
=> 'Fix' auth redirect in SSR mode

pages/auth/setup.vue
- https://github.com/harvester/harvester/issues/1551
**Additional Context**
https://github.com/harvester/harvester/issues/1551#issuecomment-977704203
=> Fix setup page does not load spoofed types

.storybook/main.js, scripts/publish-storybook, stories/global.scss
This PR fixes the storybook build - this was broken by the switch to dart-sass library switch
=> Fix Storybook build

components/nav/NamespaceFilter.vue, store/index.js
https://github.com/rancher/dashboard/issues/4647
=> Fix issue where NamespaceFilter wasn't grouping by projects

pages/c/_cluster/apps/charts/index.vue
=> Updating where we get the linux/windows count.

components/form/ResourceQuota/shared.js
- https://github.com/harvester/harvester/issues/1450
- https://github.com/rancher/dashboard/issues/4412
**Reproduce Steps**
- Install the latest Rancher
- Import a Harvester
- Login Rancher and navigate to "Virtualization Management"
- Navigate to "Projects/Namespaces"
- Create a project, select the "Resource Quota" tab
- Click "Add resources" button
**Result**
Input doesn't show on the page.
**Additional Context**
=> HARVESTER: Fix project resource quota input

assets/translations/en-us.yaml, docs/developer/getting-started/development.md, products/epinio/models/namespaces.js
https://github.com/epinio/ui/issues/50
=> Add custom warning when deleting Epinio namespace

models/management.cattle.io.node.js
Addresses https://github.com/rancher/dashboard/issues/4705
=> Change Node scale down action icon from chevron to minus

store/index.js
=> Ensure `backTo` isn't set on ember log out shenanigans

edit/provisioning.cattle.io.cluster/rke2.vue
- When switching from an addon rich kube type to one with none the config in `spec.rkeConfig.chartValues` wasn't updated
- Now when it changes `chartValues` is updated given new addons
- Changes should behave the same as before, as in on enter `chartValues` contains the entire config, then on edit of config only the diff is kept
- Also ensure we always start editing addon config that's yaml with the default from the chart
#4714
=> Ensure cluster provisioning addon config updates following kube type/version change

assets/styles/themes/_suse.scss
=> Ensure SUSE branded button text is always white and not black

assets/translations/en-us.yaml, edit/provisioning.cattle.io.cluster/rke2.vue
- https://github.com/harvester/harvester/issues/1577
- https://github.com/rancher/dashboard/issues/4754
=> HARVESTER: Bug fix and remove tech preview

assets/translations/en-us.yaml, components/nav/Header.vue, config/settings.js, detail/harvesterhci.io.host/index.vue, edit/harvesterhci.io.host/index.vue, edit/harvesterhci.io.setting/ssl-parameters.vue, edit/kubevirt.io.virtualmachine/VirtualMachineCloudConfig/index.vue, edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue, edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue, edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/volume.vue, list/kubevirt.io.virtualmachine.vue, mixins/harvester-vm/index.js, models/harvester/harvesterhci.io.virtualmachinebackup.js, models/harvester/kubevirt.io.virtualmachine.js, models/harvester/node.js, pages/auth/setup.vue, plugins/steve/resource-class.js
- https://github.com/harvester/harvester/issues/1634   https://github.com/rancher/dashboard/pull/4765/files#diff-6cfd4b4cd9068a78d83408e47d4d0e7083d22d7757a3e02fe6af2e338ac736bbR340-R344
- Add `_remove` method  https://github.com/rancher/dashboard/pull/4765/files#diff-4da29726dac4384f0d9f1f1afba1235e4f4df1398244525279d39a35fa68b8edR844-R848
=> HARVESTER:  bug fix & feat enhancement

assets/translations/en-us.yaml, edit/provisioning.cattle.io.cluster/index.vue, edit/service.vue
- https://github.com/harvester/harvester/issues/1671
- Fix RKE1 cluster does not show add-on config on LB page
=> HARVESTER: Harvester RKE2 node driver is experimental

assets/translations/en-us.yaml, edit/provisioning.cattle.io.cluster/rke2.vue
=> Label experimental k8s versions

content/docs/en-us/whats-new.md
https://github.com/rancher/dashboard/issues/4678 has the details. I'm open to different formatting.
As for 2.6.1 and 2.6.2 content, I don't think we officially got any wording. We can look at adding that later once we get or decide on content.
=> added 2.6.3 content to top

assets/translations/en-us.yaml, components/HarvesterServiceAddOnConfig.vue
- Add health check enabled radio button
**Addictionl Context**
=> HARVESTER: LB add-on config enhancement

edit/provisioning.cattle.io.cluster/rke2.vue
- This is a one way process, so we don't have to worry about storing user changes going back from yaml --> form view
- Any changes to chartValues whilst in `Edit YAML` view are retained (rke2 saveOverride isn't used, it's ResourceYaml save)
=> [Cluster Provisioning] Ensure add-on config makes it to 'Edit YAML' view

assets/translations/zh-hans.yaml
Fix an important translation error
=> fix translation error

docs/developer/getting-started/development.md
- Move `Testing` to the end
- Add info on package management (from sprint retro tasks)
=> Update developer docs

assets/translations/zh-hans.yaml
issue: https://github.com/rancher/rancher/issues/33654
Update Chinese translation error, this error will cause an error on the backup creation page
=> fix(translations): fix zh-hans translation error

components/EmberPage.vue
issue: https://github.com/rancher/dashboard/issues/4838
=> fix(ember-page): sync ember page language if locale change

components/HardwareResourceGauge.vue, components/formatter/HarvesterMemoryUsed.vue, components/formatter/HarvesterStorageUsed.vue, detail/harvesterhci.io.host/HarvesterHostBasic.vue, list/harvesterhci.io.dashboard/index.vue, utils/units.js
- https://github.com/harvester/harvester/issues/1712
- https://github.com/harvester/harvester/issues/1729
=> HARVESTER: Fix memory reserved unit doesn't match with total

edit/monitoring.coreos.com.prometheusrule/AlertingRule.vue, edit/monitoring.coreos.com.prometheusrule/duration.js, edit/monitoring.coreos.com.prometheusrule/index.vue
issue: https://github.com/rancher/dashboard/issues/4851
=> fix(prometheusrule): fix rule duration unit conversion error

assets/translations/en-us.yaml, config/product/legacy.js
=> Add iframing of project-level config maps

components/HarvesterServiceAddOnConfig.vue
- https://github.com/harvester/harvester/issues/1697
**Change**
- Disable IPAM selector when edited.
- Change Port input to the selector.
=> HARVESTER: Optimization for the Harvester load balancer

edit/token.vue, pages/account/index.vue
=> Fix for API Key Expired date doesn't shows right at the first time when login as standard userAdd

machine-config/vmwarevsphere.vue
=> When editing a vsphere cluster ensure that all of the datacenter dependent resources are reloaded when the datacenter changes

docs/developer/machine-drivers.md, layouts/error.vue, models/provisioning.cattle.io.cluster.js, models/rke-machine.cattle.io.amazonec2machinetemplate.js, models/rke-machine.cattle.io.azuremachinetemplate.js, models/rke-machine.cattle.io.digitaloceanmachinetemplate.js, models/rke-machine.cattle.io.linodemachinetemplate.js, models/rke-machine.cattle.io.machinetemplate.js, models/rke-machine.cattle.io.vmwarevspheremachinetemplate.js
And a bit of cleanup so that machine-templates all share a base class instead of repeating some code in every one.
=> Docs for writing custom machine driver components

components/HarvesterServiceAddOnConfig.vue, components/form/WorkloadPorts.vue, config/labels-annotations.js, models/workload.js
- https://github.com/harvester/harvester/issues/1697
=> HARVESTER: Add ipam on create workload page

package.json, yarn.lock
Adds `icon-repository` icon by bumping the icon font reference.
=> Bump icon font to add repository icon

edit/provisioning.cattle.io.cluster/rke2.vue
This is needed because the backend can update the rke-machine-config (for RBAC purposes) which bumps the resourceVersion and prevents the user from saving.
- You'll need the latest rancher instance
- You'll need the latest webhook. (You'll get this automatically if you don't mount a volume after updating your docker image)
rancher/dashboard#4800
=> Ensuring the client version of the rke-machine-config resource is properly syncd with the backend before saving

assets/translations/en-us.yaml, edit/provisioning.cattle.io.cluster/rke2.vue
=> warn if ipv6 CIDR configured

.github/workflows/release-rancher-desktop.yml
This replaces the unverified github action with a simple github cli script to accomplish the same task.
=> Replace unverified action with github cli script 

assets/styles/themes/_light.scss, assets/translations/en-us.yaml, pages/c/_cluster/explorer/index.vue
=> Add component status cards (parity with Cluster Manager)

.github/workflows/scripts/pr.js
One last fix hopefully so that we can start to uses the fixes notation.
=> Fix GitHub Action for fixes notation

assets/translations/en-us.yaml, components/fleet/FleetSummary.vue, detail/namespace.vue
=> namespace detail count breakdown by type

assets/translations/en-us.yaml, edit/provisioning.cattle.io.cluster/MachinePool.vue, edit/provisioning.cattle.io.cluster/rke2.vue
=> prevent etd and controlplane roles for windows machines

docs/developer/build-for-container-registry.md
This gives some insight on how to create an action that will build and push a custom image of the Dashboard as a submodule.
=> Add container registry action documentation

assets/translations/en-us.yaml, detail/policies.kubewarden.io.clusteradmissionpolicy.vue
Add new url for cluster admission policy metrics tab
---
Since this is going into a development branch no review is required.
=> Merge Kubewarden branch from fork

edit/provisioning.cattle.io.cluster/rke2.vue
#4550 - ipv6 checkbox should show if the selected container network is either 'cilium' or 'multus, cilium'
=> show ipv6 checkbox for multus,cilium

assets/translations/en-us.yaml, components/ClusterProviderIcon.vue, components/dialog/AddCustomBadgeDialog.vue, config/labels-annotations.js, models/management.cattle.io.cluster.js, pages/c/_cluster/explorer/ConfigBadge.vue, pages/c/_cluster/explorer/index.vue
#4934 
This PR adds ui/ux functionality in support of PR #4933
=> Add UI support for displaying cluster badges next to cluster name

components/fleet/FleetIntro.vue, components/fleet/FleetRepos.vue
Issue #4830  - Update no git repo landing page.
#5063 - This is the original PR. When rebasing with the master somehow [this was broken](https://github.com/rancher/dashboard/pull/5063/commits/1a5865f8705b990ab5e6dd59e464c43cd533a385). This PR apply the fix again.
1. Navigate to Continuous delivery > Git repos.
2. Ensure there are no repos. 
2. It should display the following view of the content.
3. Note: The header and side menu is out of scope for this PR.
=> Git Repo intro page is not showing - #4952

assets/translations/en-us.yaml, detail/catalog.cattle.io.app.vue
This PR addresses issue #5079 
Added the latest deployment operation status to the Installed App detail page. 
Also added a link to open the container deployment logs window.
=> Helm UI added feedback regarding logs of deployment

machine-config/vmwarevsphere.vue
rancher/dashboard#4971
In the screenshot below you can see the option is now available and the fields that are set when creating the cluster.
=> Enabling content library creation method

pages/c/_cluster/_product/projectsnamespaces.vue
=> Adjusts the permission check to create namespaces against a project

edit/provisioning.cattle.io.cluster/RegistryConfigs.vue
=> Fix for registry configuration being editable in view mode

pages/c/_cluster/explorer/index.vue
This PR fixes an issue where the additional cluster usage stats do no show for the local cluster.
Without this PR, the extra bar lines don't appear for the local cluster, e.g
=> Fix issue where cluster usage stats do not show for local cluster

components/dialog/RollbackWorkloadDialog.vue, models/workload.js
Fixes #4664
Fixes #4636 
Workload rollback always targets the local cluster - this PR fixes this.
=> Fix bug where workload rollback always targets the local cluster

assets/translations/en-us.yaml, models/harvester/kubevirt.io.virtualmachine.js, plugins/steve/resource-class.js
Add a global message for the click action。
=> add notification

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, components/HarvesterServiceAddOnConfig.vue, edit/workload/index.vue
- https://github.com/harvester/harvester/issues/1697
**Reproduce Steps**
1. Install master-head rancher, import a harvester
2. Navigate to the workload page
3. Go to create workload page
4. Refresh the page
5. Check the LB port, the ipam input is missed
**Change**
-  Add a cluster request to make sure `showIpam` work as expect. https://github.com/rancher/dashboard/blob/d4dcb40dce8bf10dd99e9f8ee22cdec06b4bd2cf/components/form/WorkloadPorts.vue#L132-L155
- Remove port tooltip
=> HARVESTER: Fix ipam doesn't show after refresh page

models/rke.cattle.io.etcdsnapshot.js
#5262
Removed delete action from the snapshot list.
=> Remove delete action from snapshot list for RKE2

assets/translations/en-us.yaml, edit/provisioning.cattle.io.cluster/rke2.vue
#5296
Added warning banner for edit view:
=> Add RKE/K3s re-provisioning banner on cluster edit view

list/harvesterhci.io.management.cluster.vue, pages/home.vue
=> Adds a permission check for the associated buttons

assets/translations/en-us.yaml, components/nav/NamespaceFilter.vue
Fixes #5364 
This PR fixes a number of issues with the namespace filter control - some made more obvious by its move to the right hand side.
=> Improve namespace filter

.github/workflows/release-rancher-desktop.yml
supports rancher-sandbox/rancher-desktop#1192
=> Target Steve API as resource base for Rancher Desktop builds

components/PromptRestore.vue
https://github.com/rancher/dashboard/issues/5320#issuecomment-1061864676
=> Corrected the value used for restoreRKEConfig

components/dialog/RotateCertificatesDialog.vue
This PR addresses two errors that Max found when validating https://github.com/rancher/dashboard/issues/4485.
1. When you select **Rotate all service certificates**, the `services` in the request needs to be an empty array. I have made it so that a service is only included in the array when you want to rotate an individual service.
2. The list of services that you can choose from needs to be different than RKE1. For RKE1, Norman provided a hardcoded list of services. In this comment https://github.com/rancher/dashboard/issues/4485#issuecomment-1064411965 Max provided the list of services that should be available for RKE2, so I have hardcoded them as options here if the current cluster is RKE2.
I also tested RKE1 cert rotation to make sure I didn't break it.
I also fixed an undefined error …
=> RKE2 cert rotation applies to correct services

models/rke.cattle.io.etcdsnapshot.js
#5383
Removed further actions for snapshots.
=> Restrict actions for snapshots to restore only

assets/translations/en-us.yaml, components/nav/HarvesterUpgrade.vue, edit/kubevirt.io.virtualmachine/VirtualMachineNetwork/base.vue, mixins/harvester-vm/index.js, models/harvester/harvesterhci.io.upgrade.js, plugins/steve/resource-class.js
Fix a serious harvester bug
https://github.com/harvester/harvester/issues/2006
=> HARVESTER: fix single cluster issue

components/PromptRestore.vue, detail/provisioning.cattle.io.cluster.vue, models/etcdbackup.js, models/rke.cattle.io.etcdsnapshot.js
This PR fixes a number of issues with snapshot restore:
- Does not work for RKE1
- Snapshot list shows `undefined` instead of the name
- Can not restore a snapshot from the list of snapshots for an RKE1 cluster
=> Fix snapshot restore issues

components/GrowlManager.vue, components/nav/NamespaceFilter.vue, layouts/error.vue
- Ensures that they appear over the new namespace filter
- fixes #5415
=> Increase the z-index of 404 (error layout) page and Growls

content/docs/en-us/whats-new.md
=> Updated whats-new.md with k8s 1.22 & 1.23

edit/networking.k8s.io.networkpolicy/PolicyRuleTarget.vue
- Move cidr/s validation messages underneath cidr/s fields
- Fix error thrown when switching from ip block to other rule source options
- fixes #4729
=> Updates to Network Policy Rule Targets component

content/docs/en-us/whats-new.md
=> revised 2.6.4 with k8s 1.23 as experimental

assets/translations/en-us.yaml
advanced settings to settings:
https://github.com/rancher/dashboard/issues/3527
=> minor polish and text edits

edit/provisioning.cattle.io.cluster/index.vue
This PR fixes these two issues:
- https://github.com/rancher/dashboard/issues/5442
- https://github.com/rancher/dashboard/issues/5455
=> More fixes for emberLink

yarn.lock
- Fix deps brought in by https://github.com/rancher/dashboard/pull/3726 
- Tested in Harvester (VM create/edit page Volumes tab)
=> Improve yarn.lock deps

.github/workflows/scripts/publish-storybook, .github/workflows/storybook.yaml
This PR adds a GitHub action - when we merge commits to master, the Storybook will be rebuilt and published to rancher/storybook
=> Storybook: Add GitHub Action to publish Storybook on push to master

edit/provisioning.cattle.io.cluster/index.vue
Same as https://github.com/rancher/dashboard/pull/5494 but going into master
=> More fixes to emberLink logic

edit/workload/index.vue
=> [2.6.4] Fix for can not clone workload

assets/translations/en-us.yaml
- Port of #5519, addresses https://github.com/rancher/dashboard/issues/5518
=> Fix home page getting started card typo

assets/translations/en-us.yaml
=> [2.6.4] Fix home page getting started card typo

assets/styles/global/_resource.scss, components/CruResource.vue, edit/monitoring.coreos.com.receiver/index.vue
This is a re-work of https://github.com/rancher/dashboard/pull/5140 with the latest codebase.
Now looks like this:
=> Update selection grid styling

components/Tabbed/index.vue
Fixes the vertical tab style after merge of changes to tab styling
=> Fix vertical tab styling

middleware/authenticated.js, store/index.js
This backports #5332 into the release v2.6.3-patch3 branch.
Improve handling of errors when logging in
Fixes #5532
See also #5004
=> Backport #5332 into release v2.6.3-patch3

components/fleet/FleetStatus.vue
Addresses Github issue: [#5407](https://github.com/rancher/dashboard/issues/5407)
Addresses Zube issue: [#5433](https://zube.io/rancher/dashboard-ui/c/5433)
- Update hover effects on toggle area for popover in `FleetStatus` component
=> Fleet: UX improvements for ResourceSummary counters in git repo details view

pages/c/_cluster/neuvector/index.vue
Addresses https://github.com/rancher/dashboard/issues/5556
=> NeuVector link uses `cattle-neuvector-system` namespace

config/table-headers.js, list/node.vue, store/type-map.js
Fixes issues with sortable table in SSR mode.
Ensures that the value getters are not used server side and are removed, so that they don't get transferred as empty values that then break the rendering client side.
=> Fix Sortable Tble SSR

components/SortableTable/index.vue
Fixes broken props on the cell slot - so custom slots won't show correctly.
=> Sortable Table: Fix broken props to slot

components/AsyncButton.vue
=> Fix async buton wobble with spinner

edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #5545
This PR changes the way we get the default Kubernetes versions for RKE2 and K3S - we now get them from the new settings in preference to the channels API.
This allows us to have different latest default versions for a given version of Rancher, since the channels API is independent of a given Rancher release.
To Test: Verify that RKE2 and K3S cluster provisioning works as expected and the the default Kubernetes versions are also as expected.
=> Get rke2 and k3s latest versions from settings

plugins/steve/subscribe.js
=> Monitoring v2 Routes and receivers 'cannot watch' console error

config/types.js
- Regression from #5632
- Caused by d62f333ee
- fixes #5594
=> Fix issue where norman cluster type was unknown

config/product/neuvector.js, pages/c/_cluster/neuvector/index.vue, store/type-map.js
- As per request at https://github.com/rancher/dashboard/issues/5556#issuecomment-1098270110
- fixes #5556
- alternative to #5604
=> Hide NeuVector product if `cattle-neuvector-system` does not exist

list/group.principal.vue
Buttons should only show if
- There is a non-local auth provider enabled
- The user has the correct permissions for the relevant action
Fixes #4897
For testing I've been using a local user, the github auth provider and a github user
Local User
- Create a local user the normal way
Github User
- Enable the github auth provider 
- Use a different browser (or somewhere sessions won't mix) and sign in as a github user
At this point the feature can be tested by changing the users global roles (Users --> <user> --> Edit Config) and checking the visibility of the buttons
- Assigning only the `Manage Users` role should mean both users can reach the groups list but cannot see either button
- Assigning only the `Restricted Administrator` role to the local user should mean the user cannot see both …
=> Fix conditional showing of Group `Assign To` and `Refresh` buttons

edit/secret/generic.vue
Addresses Github issue: [#5574](https://github.com/rancher/dashboard/issues/5574)
Addresses Zube issue: [#5602](https://zube.io/rancher/dashboard-ui/c/5602)
- fix issue with Editing Secret object in Rancher UI corrupting binary data
=> Editing Secret object in Rancher UI corrupting binary data

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, components/VMConsoleBar.vue, components/formatter/HarvesterIpAddress.vue, config/product/harvester.js, detail/harvesterhci.io.host/index.vue, edit/harvesterhci.io.host/HarvesterDisk.vue, edit/harvesterhci.io.host/index.vue, edit/harvesterhci.io.managedchart/rancher-monitoring.vue, edit/harvesterhci.io.setting/index.vue, list/harvesterhci.io.setting.vue, mixins/harvester-vm/index.js, models/harvester/harvesterhci.io.blockdevice.js, models/harvester/kubevirt.io.virtualmachine.js, models/harvester/management.cattle.io.managedchart.js, store/index.js
Harvester single cluster feature & bug fix
Fixes #
=> Harvester single cluster feature & bug fix

assets/translations/en-us.yaml
=> Fix two concurrency typos

list/harvesterhci.io.dashboard/index.vue
Due to the following two pr modifications 
1.https://github.com/rancher/dashboard/commit/396906de9e817265173f183b87242bd36b17b4e7#diff-a1f6e5fa2bcaf71933539aed255359b62ad2c9941955eeb5127815527f0c1244R116
2. https://github.com/rancher/dashboard/commit/8d14ea559809b2e4f104f0273aa1379fd71786c1#diff-c51fe6c73618d79dd2703f9433943178955cd94bae9b2df08ed65b33b5f65e68R259
Fix volume statistics and memory spelling errors
=> HARVESTER: fix dashboard page bug

components/SortableTable/index.vue, config/product/monitoring.js
- fixes https://github.com/rancher/dashboard/issues/5693
- first commit resolves the issue on load - https://github.com/rancher/dashboard/issues/5693#issuecomment-1107909073
- second commit resolves the double cells - https://github.com/rancher/dashboard/issues/5693#issuecomment-1107908766
=> Fix dashboard error on load & double up of some table cells

machine-config/linode.vue
- Fixes #5603 (see comment https://github.com/rancher/dashboard/issues/5603#issuecomment-1108777558 for specifics)
- As per DO allow the user to use private networking for their nodes
Note - @thedadams has volunteered to test the functionality
=> Allow user to set createPrivateIp for linode nodes

components/ActionMenu.vue, components/SortableTable/index.vue
Fixes https://github.com/rancher/dashboard/issues/5699
This change https://github.com/rancher/dashboard/pull/5707/files#diff-1a2277d92947d83bba624b418c7879f3fa45d44df0bb93f741aa3ae7c4b7df43L900  also fixes the link to the detail page for receivers within an AlertmanagerConfig, which no longer worked after https://github.com/rancher/dashboard/pull/5696
=> Project alerting fixes - Action menu works in cluster manager

store/index.js
Fixes #
harvester has the same https://github.com/rancher/dashboard/pull/5319 problem, but there is no way to consistently reproduce.
=> fix fetch management.cattle.io.cluster race error

assets/translations/en-us.yaml, assets/translations/zh-hans.yaml, edit/kubevirt.io.virtualmachine/VirtualMachineCpuMemory.vue, edit/kubevirt.io.virtualmachine/index.vue, mixins/harvester-vm/index.js, models/harvester/harvesterhci.io.virtualmachinetemplateversion.js, models/harvester/kubevirt.io.virtualmachine.js
change runStrategy:  `Manual` => `RerunOnFailure`
delete `start vm on creation` checkbox
Fixes # https://github.com/harvester/harvester/issues/2172
=> HARVESTER: change vm runStrategy

models/management.cattle.io.nodepool.js
- use only the node list to create states
- align property names to states
- group `errored and not (active or transitioning)` in the 'unavailable' bucket
- fixes #5443
=> Fix dupe of node's in rke1 node pool states

edit/harvesterhci.io.host/index.vue
Fixes #
- https://github.com/harvester/harvester/issues/2149
Make remove button is disabled on the detail page
=> Harvester: Fix disk detail config can be remove

content/docs/en-us/whats-new.md
Addresses #5638 
Updated What's New section in the UI
Confirm that the What's New page lists the 2.6.5 material properly
=> initial 2.6.5 What's New blurb

.drone.yml, scripts/create-pr-in-rancher
Proposed changes
======
Add a dispatch step in Drone to automatically create a PR in the repository `rancher/rancher` when a new tag is created in this repository. This saves time when creating release (candidates) and avoids manual errors.
Types of changes
======
Add step to Drone when a new tag is created
Linked Issues
======
Further comments
======
@mantis-toboggan-md @rak-phillip Can you check if there is a reason we can't do this? I'm creating it as draft PR as EIO needs to do some work before we can merge. Thanks!
=> Add dispatch step to update tag in rancher/rancher

edit/harvesterhci.io.setting/backup-target.vue, edit/harvesterhci.io.setting/overcommit-config.vue, models/harvester/kubevirt.io.virtualmachine.js
1. Fix jumping link error
2. Enhance VM state judgment logic
Fixes #
=> HARVESTER: fix harvester related issues

components/Questions/index.vue, components/form/NameNsDescription.vue, edit/helm.cattle.io.projecthelmchart.vue
requires additional changes to namespace selector filtering - intermediate changes still included in this PR as it fixes some issues but not all
=> Implements questions.yaml

components/ResourceYaml.vue
=> checks component prop as well as route query

edit/monitoring.coreos.com.alertmanagerconfig/receiverConfig.vue, models/monitoring.coreos.com.alertmanagerconfig.js
https://github.com/rancher/dashboard/issues/5877
=> No longer see blank page after editing receiver as YAML

edit/provisioning.cattle.io.cluster/rke2.vue
=> Cron Job's description added to rke2 cluster config

edit/monitoring.coreos.com.alertmanagerconfig/receiverConfig.vue, pages/c/_cluster/monitoring/alertmanagerconfig/_alertmanagerconfigid/receiver.vue
Addresses https://github.com/rancher/dashboard/issues/5882
=> Redirect to AlertmanagerConfig detail on saving receiver

shell/components/CruResource.vue, shell/components/ResourceYaml.vue, shell/edit/monitoring.coreos.com.alertmanagerconfig/receiverConfig.vue
Forwardport of https://github.com/rancher/dashboard/pull/5908
=> [master] allow doneRoute to be an object

.github/issue_template.md
Fixes issue template for github #
just a template md fix
open issue template after merge to test
=> Fix additional context comment in `.github/issue_template.md` 

pkg/epinio/components/application/AppConfiguration.vue, pkg/epinio/edit/configurations.vue, shell/store/type-map.js
- Fixed issue where packages failed to find custom detail pages
- Some minor epinio changes
=> Fix custom detail components & minor epinio changes

shell/components/PromptRemove.vue
=> Fix HTML escaping in delete dialog

shell/edit/monitoring.coreos.com.alertmanagerconfig/index.vue, shell/edit/monitoring.coreos.com.alertmanagerconfig/receiverConfig.vue, shell/pages/c/_cluster/monitoring/alertmanagerconfig/_alertmanagerconfigid/receiver.vue
I went through the bug fixes in https://github.com/rancher/dashboard/pull/5986/files and validated that they were in master. For the few changes that weren't in master, I added them in this PR because the file structure change was creating merge conflicts in the other PR.
=> Forward port v2.6.5 project alerting bug fixes to master

pkg/epinio/config/epinio.ts, pkg/epinio/edit/bind-apps-mixin.js, pkg/epinio/edit/configurations.vue, pkg/epinio/edit/service-instance.vue, pkg/epinio/l10n/en-us.yaml, pkg/epinio/models/catalog-service.js, pkg/epinio/models/service-instance.js, pkg/epinio/types.ts, shell/plugins/dashboard-store/resource-class.js
**Create/Delete Service Instance**
**When creating a service instance allow user to select apps to bind to it**
- Move common app code in to mixin shared between configurations and service instances
- There's two TODOs in code, both related to blocked backend issues (these will be coming next week)
- edit a service instance to change the bound apps, not implemented yet 
- unable to fetch service instance with generic tooling, currently we just wait until polling is unblocked
**Also fixed some minor issues**
- show namespace column in service instance list when not grouped by namespaces
- change service instance 'service' column title
- fixed service instance state
=> [Epinio] Create/Delete Service Instance

README.md
Fixes the link to plugins documentation.
=> Fix link to plugins documentation

shell/core/plugin.ts, shell/creators/app/init, shell/creators/pkg/tsconfig.json, shell/package.json, shell/scripts/publish-shell.sh
Fixes issues with the shell package file and the init script for the app creation package
=> Fix yarn install with @rancher/shell

shell/assets/styles/base/_variables.scss, shell/components/nav/Header.vue
Addresses Github issue: [#6028](https://github.com/rancher/dashboard/issues/6028)
Addresses Zube issue: [#6057](https://zube.io/rancher/dashboard-ui/c/6057)
- Adjust z-indexes so that position of select dialog is properly calculated
=> Project Member View not rendering search results properly

shell/components/nav/TopLevelMenu.vue
Fixes #6050 
The top-level menu now requires the provisioning clusters, otherwise it will show an empty list.
This PR ensures that these are fetched if needed and also adds guards around that cluster scheme in case there are use cases where this schema is not available (other UIs).
=> Fix side-menu cluster list is empty

docs/developer/helm-chart-apps.md, shell/mixins/chart.js, shell/pages/c/_cluster/apps/charts/install.vue, shell/store/catalog.js, shell/utils/object.js
This PR contains no code changes. It addresses https://github.com/rancher/dashboard/issues/5904 by adding developer docs and comments about Helm chart values in Rancher.
I created this documentation for two reasons:
- As part of the work that needs to be done for project monitoring, Sean needs to create a component that allows users to manipulate values in a `ProjectHelmChart` custom resource. We didn't include that component in Rancher v2.6.5 because we weren't sure how much logic from the regular Helm chart install/upgrade process also applied to what the user experience should be for editing the `ProjectHelmChart`. These docs should help us figure out how to either tailor this component to the needs of the `ProjectHelmChart` or to helm create a much simplified version of the component …
=> Add docs and comments on how Rancher handles Helm chart values

shell/models/provisioning.cattle.io.cluster.js
=> Prevent cluster management from allowing cluster deleting multiple times while cluster is transitioning

pkg/rancher-components/src/components/Banner/Banner.vue, pkg/rancher-components/src/components/Card/Card.vue, pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue, pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue, pkg/rancher-components/src/components/Form/Radio/RadioButton.vue, pkg/rancher-components/src/components/Form/Radio/RadioGroup.vue, pkg/rancher-components/src/components/Form/TextArea/TextAreaAutoGrow.vue, pkg/rancher-components/src/components/LabeledTooltip/LabeledTooltip.vue
This adds JSDoc style comments to `@rancher/components`.
closes #6088 
=> Add JSDoc comments to @rancher/components

shell/components/SortableTable/index.vue
Add cypress data attributes for fast element finding in tables
=> Adding cypress data attributes

scripts/create-pr-in-rancher
Follow up to https://github.com/rancher/dashboard/pull/5849, needs correct inputs to work.
Can this go in before the next 2.6.6 to test?
=> Use correct inputs when creating PR in rancher

shell/assets/translations/en-us.yaml, shell/config/settings.js, shell/middleware/authenticated.js, shell/pages/c/_cluster/settings/brand.vue, shell/utils/favicon.js
=> Allow favicon to be customized via setting

cypress/integration/tests/pages/home.spec.ts
Fixes #6186
Remove flaky test related to homepage and changelog banner.
Issue needs to be reviewed altogether with all the navigation elements, as they share the same type of issue.
=> Skip flaky test

shell/edit/auth/azuread.vue
The updated AzureAD China endpoints were incorrect, see https://github.com/rancher/dashboard/issues/5671#issuecomment-1157799618
=> update azuread china endpoints

shell/assets/translations/en-us.yaml
Addresses feedback from this comment https://github.com/rancher/dashboard/issues/5885#issuecomment-1139027734
Depends on [AlertmanagerConfig detail page renders properly](https://github.com/rancher/dashboard/pull/6047/commits/1fb8fee218178031ee5047e0083992b03d6b633b)
=> Change tooltip for grouping alerts by label

.storybook/main.js, .storybook/preview.js, package.json, stories/BadgeState.stories.js, stories/Banner.stories.js, stories/InputFieldsAdvancedExample.vue, stories/InputFieldsExample.vue
Fixes storybook build/run following plugins and components moves.
=> Fix storybook build and run

shell/assets/translations/zh-hans.yaml
Added Chinese translation to keep up with the English version.
=> Update Chinese translation

shell/scripts/publish-shell.sh
Fixes rancher-component does not pack
- https://github.com/rancher/dashboard/issues/6059
=> Fix rancher-component does not pack into @rancher/shell

shell/components/SortableTable/debug.js, shell/components/SortableTable/index.vue
Code that can be enabled to add watchers to show which computed properties are being re-computed by SortableTable.
=> Add debugging watchers for SortableTable

shell/assets/translations/en-us.yaml, shell/components/auth/AzureWarning.vue, shell/config/labels-annotations.js, shell/edit/auth/azuread.vue
#6236
~~Waiting on https://github.com/rancher/rancher/issues/29306~~
Edit: required for https://github.com/rancher/rancher/pull/38125
=> update azuread endpoint migration check logic

yarn.lock
Bump the caniuselite dependency
Fixes the nag message you get when building telling you to update
=> Bump caniuselite

shell/assets/translations/en-us.yaml
https://github.com/rancher/dashboard/issues/6098#issuecomment-1152653709
=> Updating the messaging for the local cluster member warning

shell/assets/translations/zh-hans.yaml
- Add translation to keep up with the English version.
- Fix https://github.com/rancher/dashboard/issues/6327
=> Add Chinese translation and modify the expression of CPU

shell/pages/c/_cluster/explorer/index.vue
Fixes #6324
Adds a computed method for the cluster spec description to remove error from the console.
This is more of a stop gap measure as alluded to [here](https://github.com/rancher/dashboard/issues/6324#issuecomment-1182010962), but nonetheless a computed method is always welcome in these cases.
=> Add computed method for cluster spec description

.github/workflows/scripts/pr.js
=> Fix CI rancher_zube error

shell/utils/width.js
Addresses Github issue: [#6363](https://github.com/rancher/dashboard/issues/6363)
- fix for broken namespace selector on fleet
**Before**
https://user-images.githubusercontent.com/97888974/179023814-a3e91057-6a5a-4c95-befb-a2efb04ccbe9.mov
**After**
https://user-images.githubusercontent.com/97888974/179023887-16a60f47-e256-4ef4-81ac-709324327a0c.mov
@rak-phillip tested the namespace selector on cluster explorer and it works also... Don't know about any other implications with this 🙏
=> fix for broken namespace selector on fleet

shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml, shell/components/FilterLabel.vue, shell/components/GrowlManager.vue, shell/components/form/ArrayList.vue, shell/components/form/NodeScheduling.vue, shell/components/nav/Header.vue, shell/edit/harvesterhci.io.setting/overcommit-config.vue, shell/edit/harvesterhci.io.virtualmachinetemplateversion.vue, shell/edit/kubevirt.io.virtualmachine/VirtualMachineCloudConfig/DataTemplate.vue, shell/edit/kubevirt.io.virtualmachine/VirtualMachineCloudConfig/index.vue, shell/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue, shell/edit/kubevirt.io.virtualmachine/index.vue, shell/list/harvesterhci.io.virtualmachineimage.vue, shell/machine-config/harvester.vue, shell/mixins/harvester-vm/index.js, shell/mixins/labeled-form-element.ts, shell/models/harvester/kubevirt.io.virtualmachine.js, shell/models/harvester/kubevirt.io.virtualmachineinstance.js, shell/models/harvester/node.js, shell/plugins/steve/subscribe.js, shell/store/growl.js, shell/utils/socket.js, shell/utils/width.js
Fixes Harvester v1.0.3 issues
- https://github.com/harvester/harvester/issues/2416
- https://github.com/harvester/harvester/issues/2438
- https://github.com/harvester/harvester/issues/2451
- https://github.com/harvester/harvester/issues/2471
- https://github.com/harvester/harvester/issues/2474
- https://github.com/harvester/harvester/issues/2475
- https://github.com/harvester/harvester/issues/2488
- Add node scheduling for VM and VM template
- Add label filter for image
[Node scheduling]
[Label filter]
=> Fix Harvester v1.0.3 issues

shell/models/provisioning.cattle.io.cluster.js
Fixes Harvester clusters have no actions
- Fix Harvester clusters have no actions
=> HARVESTER: Fix Harvester clusters have no actions

.github/workflows/check-plugins.yaml, pkg/epinio/detail/applications.vue, shell/components/VMConsoleBar.vue, shell/components/fleet/FleetBundleResources.vue, shell/components/fleet/FleetResources.vue, shell/components/formatter/WorkloadHealthScale.vue, shell/components/novnc/NovncConsoleWrapper.vue, shell/creators/app/init, shell/creators/pkg/tsconfig.json, shell/mixins/form-validation.js, shell/nuxt.config.js, shell/pkg/dynamic-importer.lib.js, shell/pkg/tsconfig.json, shell/pkg/vue.config.js, shell/plugins/dashboard-store/resource-class.js, shell/promptRemove/pod.vue, shell/scripts/build-pkg.sh, shell/scripts/publish-shell.sh, shell/scripts/test-plugins-build.sh, shell/utils/validators/formRules/__tests__/index.test.ts, shell/utils/validators/formRules/index.ts, stories/InputFieldsAdvancedExample.vue, stories/InputFieldsExample.vue
Fixes for the plugins packages.
Added GitHub action to validate the plugin build, shell and creators.
=> Plugins fixes and check GitHub action

shell/assets/translations/en-us.yaml, shell/components/PromptRemove.vue, shell/models/management.cattle.io.project.js, shell/pages/c/_cluster/_product/projectsnamespaces.vue, shell/promptRemove/kubevirt.io.virtualmachine.vue, shell/promptRemove/management.cattle.io.project.vue, shell/utils/string.js
This is a rework of https://github.com/rancher/dashboard/pull/5762
Fixes https://github.com/rancher/dashboard/issues/5624
Adds new custom promptRemove component to handle deleting project as well as associated namespaces
=> Project delete namespaces

shell/components/form/SelectOrCreateAuthSecret.vue, shell/edit/fleet.cattle.io.gitrepo.vue, shell/store/uiplugins.ts
There are some bad imports in master that cause the new GH Action to fail
=> Fix imports that break plugins

shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml, shell/components/form/NodeAffinity.vue, shell/components/form/PodAffinity.vue, shell/config/labels-annotations.js, shell/detail/harvesterhci.io.host/HarvesterHostBasic.vue, shell/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue, shell/list/harvesterhci.io.dashboard/HarvesterUpgrade.vue, shell/list/harvesterhci.io.dashboard/UpgradeInfo.vue, shell/list/harvesterhci.io.dashboard/index.vue, shell/list/harvesterhci.io.host/index.vue, shell/machine-config/harvester.vue, shell/models/harvester/node.js, shell/pages/c/_cluster/harvester/airgapupgrade/index.vue
Fixes Harvester v1.0.3 issues.
- https://github.com/harvester/harvester/issues/2387
- https://github.com/harvester/harvester/issues/2386
- https://github.com/harvester/harvester/issues/2384
- Add a warning banner for the Harvester upgrade
- Fix cluster-member reserved data is incorrect
- Add node scheduling and pool scheduling for machine pool
=> HARVESTER: Fixes v1.0.3 issues

shell/models/management.cattle.io.project.js
This PR is a follow-up to https://github.com/rancher/dashboard/pull/6416 and is meant to capture additional feedback on that PR.
=> Throw error if PSP template action error status is not 409

shell/edit/provisioning.cattle.io.cluster/RegistryConfigs.vue
Fixes #
https://github.com/rancher/dashboard/issues/6472
=> fix(RegistryConfigs): wait for sync registry configs before saving

shell/components/form/ArrayList.vue, shell/edit/networking.k8s.io.ingress/Certificate.vue, shell/edit/networking.k8s.io.ingress/Certificates.vue, shell/edit/networking.k8s.io.ingress/index.vue
Fixes #4575
Adds in rules for certificate host when present, passes down to certificate host input, extends arraylist to allow for rules
=> Passes rules to certificate host field, extends arraylist to use rules

.github/workflows/scripts/pr.js
Fixes broken GitHub action for linked PRs
=> GH Action: Bug fix to PR workflow

shell/edit/workload/mixins/workload.js, shell/edit/workload/types/Deployment.vue, shell/edit/workload/types/Generic.vue
Form validation was lost during a rearrangement of the workloads edit form, this adds it back in. This is not an exhaustive validation of the form, just on a few key fields as part of the initial implementation of the form-validation mixin.
=> Adds form-validation back in after deployments redesign

.drone.yml, .github/workflows/unit-test-lint.yaml, jest.config.js, scripts/standalone/index.js
Fixes #6561
As issue
- Added GitHub Actions on push
- Removed Drone CI
- Collected coverage artifacts
- Set separated jobs for unit and linter
- Allow parallelization (as default in GA)
- Corrected coverage path to include also JS and TS files, including all the packages
- Jobs should be run also on PR
- Check below should be present and be green
-
=> Create unit test and linting jobs with GitHub Actions

shell/components/SortableTable/index.vue
Fixes #6503 
Adds 2 more watchers for state that can change that requires us to update the table's live and delayed columns
=> Fix live and delayed columns not updating

shell/components/ResourceTable.vue, shell/layouts/default.vue, shell/models/management.cattle.io.project.js, shell/pages/c/_cluster/_product/projectsnamespaces.vue, shell/store/index.js
This PR fixes the following issues:
- https://github.com/rancher/dashboard/issues/6525
- https://github.com/rancher/dashboard/issues/6557 
- https://github.com/rancher/dashboard/issues/6577
- https://github.com/rancher/dashboard/issues/6565 - fixes 2/3 bugs in that issue - can the third be tracked in another issue?
The PR fixes these issues primarily by changing how the Project/namespace list page and the ResourceTable interact with the store. It also changes computed properties in the projects/namespaces list so that updates are triggered when namespaces and projects are changed in the store.
1. In Cluster Explorer, go to Pods or another namespaced resource list
2. In the top nav, filter by namespace(s)
3. Refresh
4. Confirm that the rows and counts in the side nav are accurately …
=> Fix multiple related issues surrounding projects/namespace filters and lists updating

shell/mixins/resource-fetch.js
- fix issue for multiple resource counts on `resource-fetch` mixin
=> fix issue for multiple resource counts on resource-fetch mixin

shell/assets/translations/en-us.yaml, shell/components/ResourceList/ResourceLoadingIndicator.vue, shell/config/settings.js, shell/mixins/resource-fetch.js, shell/pages/c/_cluster/settings/performance.vue
- Following UX review this is the first set of changes
- The text on the settings page has been improved
- The background of the incremental loader has been removed
- Fixed a typo (`UI_PERFORNMANCE`)
=> Tweaks to the performance settings & loading indicator

shell/content/docs/en-us/whats-new.md
Fixes https://github.com/rancher/dashboard/issues/6430
Includes 2.6.6 blurb though there was only one bug addressed
Fixes #6430 
Short summary of changes in Rancher 2.6.7 (plus including potential copy for 2.6.6) to be shown in the UI
Verify that What's New shows the expected copy
=> initial content for 2.6.7

.github/pull_request_template.md
Addresses feedback from sprit retrospectives
=> Pull request template has question about browser

shell/content/docs/en-us/whats-new.md
=> reworded 1.24 blurb for 2.6.7

shell/machine-config/harvester.vue
- https://github.com/harvester/harvester/issues/2642
=> Harvester: remove Pod Scheduling on harvester cluster page

shell/machine-config/harvester.vue
Disable Harvester cloud provider option when the credential is external
- https://github.com/harvester/harvester/issues/2605
=> HARVESTER: Disable Harvester cloud provider option when the credential is external

shell/pages/diagnostic.vue
- The download diagnostics button would clean the store before saving
- The issue was it was cleaning the actual store, resulting in all resources being lost
- We now flip the logic to save allowed properties to a new object, so the original store should be untouched
=> Fix error on diagnostic page on navigate away

shell/components/SortableTable/index.vue
- fixes https://github.com/rancher/dashboard/issues/6653
=> Ensure live/delayed column update when user filters list

shell/components/form/ResourceTabs/index.vue
Fixes #6637 
On resource detail pages, we use the `ResourceTabs` component which provides standard tabs, such as the recent events tab. This currently always fetches the events list and then filters for the resource being shown. This causes events to be fetched and watched.
This PR updates this and only fetches the events when the events tab is activated. It also un-watches events when the page is unloaded.
To test:
- Go to a resource detail page for a resource
- Open dev tools and network monitor
- Click on the 'Recent Events' tab
- Observe that events are fetched
- Leave the page
- Repeat above - events are still fetched again as they were un-watched when page was left
=> On Resource Tab, only fetch events when events tab is active

.drone.yml
If this still fails we should ignore results instead of removing entirely, 
- `failure: ignore` (see https://github.com/rancherlabs/eio/issues/1216#issuecomment-1203957485)
=> Re-enable FOSSA check

.drone.yml
- FOSSA checks are still failing with the same error, re-opening https://github.com/rancherlabs/eio/issues/1216
- Instead of removing the check entirely just ignore the failure as per suggested in https://github.com/rancherlabs/eio/issues/1216#issuecomment-1203957485
=> Ingore FOSSA failures

.eslintrc.js, docusaurus/src/components/HomepageFeatures/index.js, docusaurus/src/pages/index.js
After merging https://github.com/rancher/dashboard/pull/6522 PR there was Docusaurus build issue.
Fixes https://github.com/rancher/dashboard/issues/6334
Fixed build issue for Docusaurus.
=> Added React reference in Docusaurus src files

.github/workflows/docusaurus.yaml, docusaurus/docs/style.md, docusaurus/docusaurus.config.js
=> Docusaurus build

docusaurus/docs/fossa.md, docusaurus/docusaurus.config.js, docusaurus/sidebars.js, docusaurus/src/components/HomepageFeatures/index.js, docusaurus/src/css/custom.css, docusaurus/src/pages/index.js
Tweak docs landing page title and tagline
=> Tweak docs landing page

shell/edit/networking.k8s.io.ingress/index.vue
Fixes #
1. check if the ingress class is available before requesting it and give appropriate defaults when not available
https://github.com/rancher/rancher/issues/38695
=> fix(ingress): check if the ingress class is available before requesting it

shell/edit/auth/azuread.vue
Fixes #6271
This makes the reply url label bold to distinguish it from the description.
Added a `reply-url` class to add font-weight and color
AzureAD auth provider view
=> Add bold class to azuread reply url label

shell/models/namespace.js
When creating namespace in a single cluster, the following error occurs
Fixes #
=> Fixed error namespace router

docusaurus/sidebars.js
fixed typo saying getting stated instead of started
=> fixed typo in getting started

shell/edit/workload/index.vue, shell/edit/workload/mixins/workload.js
https://github.com/rancher/dashboard/issues/6725
=> fix(imagePullSecrets): Fix the contents of the drop-down option

shell/edit/workload/index.vue
Fixes #
https://github.com/rancher/dashboard/issues/6837
1. fix `Command`, `Environment Variables`, `Ports`，`Heath Check`，`Lifecycle Hooks` and `Security Context` foms are not updated when switching container tabs
=> fix(workload): fix some forms are not updated when switching container tabs

.drone.yml, shell/scripts/build-pkg.sh, shell/scripts/drone-build-pkg.sh
Automate build of harvester plugin. 
Should output
- releases.rancher.com/harvester-ui/plugin/${PKG_NAME}
- releases.rancher.com/harvester-ui/plugin/${PKG_NAME}.tar.gz
Drone part is untested. This can only happen on merge. Potential issues with env var and duplicate steps (at least name?)
=> Automate build of harvester plugin

shell/scripts/drone-build-pkg.sh
- Relates to https://github.com/rancher/dashboard/pull/6846
- Ensure script marked as such
- Ensure that we correctly source github env vars
=> Fix drone-build-pkg script for `master` branch

pkg/harvester/models/namespace.js
Fixes #
1. We should extend `@shell/models/namespace`
2. Fix error dialog path
=> Fix extend namespace class

shell/assets/translations/en-us.yaml, shell/components/SortableTable/index.vue
Fixes #6847
Related to https://github.com/rancher/dashboard/pull/6796
=> Fix text for list's collapsed bulk action button

shell/config/settings.js, shell/mixins/resource-fetch.js, shell/pages/auth/login.vue, shell/pages/c/_cluster/settings/performance.vue
Fixes #6745 
- Enable incremental loading by default
=> Enable incremental loading by default

shell/components/CruResource.vue
This PR addresses https://github.com/rancher/dashboard/issues/6743 by changing the logic for namespace creation in the resource creation form so that if the namespace already exists, it does not attempt to create the namespace.
To test this PR, I did the same steps as in https://github.com/rancher/dashboard/issues/6743:
- Created a namespace `test1`.
- In the secret creation form, created a Custom secret and selected the service account token as the secret type.
- In the namespace dropdown, I selected Create a new namespace and entered `test1`.
- Attempted to create the secret multiple times.
- Confirmed that the error message was about the secret lacking required fields, not that the namespace already exists. The error was as expected: `Secret "test6" is invalid: …
=> Only attempt to create namespace if it does not already exist

shell/models/harvesterhci.io.management.cluster.js
Fixes #
When the user uses a version of the address that does not match the built-in version, an error will occur
=> fix pkgName

shell/machine-config/harvester.vue
Fixes Harvester node driver namespace options
- https://github.com/harvester/harvester/issues/2485
- Filter by namespace.links.update
=> HARVESTER: Add node driver namespace filter

shell/store/type-map.js
https://github.com/harvester/dashboard/pull/411#issuecomment-1251090350
=> replace the two parameters of Object.assign

shell/components/ResourceTable.vue
- https://github.com/harvester/harvester/issues/2786
=> add ignoreFilter property to avoid filtering resource rows

shell/config/types.js, shell/detail/workload/index.vue, shell/edit/pod.vue, shell/edit/workload/mixins/workload.js, shell/models/workload.js
Fixes #6842 - 
Defining the `WORKLOAD_TYPE.POD` broke the details page.
https://github.com/rancher/dashboard/blob/8943b300b3e5501007da9fa321f8294f87faaa03/shell/config/types.js#L83
1. Create a workload from Cluster explorer > Cluster > Workloads > Deployment
2. From Deployment detail page > Pods List > Click on a pod
3. Correct details should be shown. 
4. Click on config to view the config
5. From the 3 dots on top right click on edit config to edit the pod config. 
https://user-images.githubusercontent.com/1387263/191576255-4e5dec57-957b-4c02-a954-1eee5dc7ad16.mov
=> Fix pod details and edit page.

shell/models/cluster/node.js
Fixes #4956 
EKS nodes which have been migrated from Norman do not have the `metrics.k8s.io.nodemetrics` endpoint which is used to determine the cpu and memory usage of nodes within Steve.
In the Ember UI we are using the annotation `management.cattle.io/pod-requests` to [calculate the usage](https://github.com/rancher/ui/blob/c9a7a9d008278fd1ca2d130ef809db8ee916f16d/lib/monitoring/addon/components/nodes-reservation/component.js#L72-L98).
Added a condition in both the `cpuUsage` and `ramUsage` methods to check for Norman as the creator and EKS as the provider, then parsing the values returned from the `management.cattle.io/pod-requests` annotation.
- An EKS cluster can be created in the Ember UI and the result will be the same regardless of upgrading from a version prior to `v2.6.0`
- …
=> Fix cpu/memory usage calc for eks nodes from norman

.drone.yml, shell/edit/auth/azuread.vue, shell/models/cluster/node.js
Fixes #6428 
This issue would arise regardless of upgrading prior to `v2.6.5` as we were checking _only_ for the `graphEndpoint`, not for the other endpoints.
Added a method to determine if the values for all of the endpoints match the values in the hard coded map. If they don't match, `custom` will be the type.
- Steps to test are in the related issue
- A test environment can be given if needed
=> Azuread custom endpoint radio option

shell/models/harvesterhci.io.management.cluster.js
Fixes #
Wrong address requested
=> fix harvester plugin url path

shell/models/harvesterhci.io.management.cluster.js
Fixes #
Wrong address requested
=> [backport] fix harvester plugin url path

shell/assets/translations/en-us.yaml, shell/config/product/explorer.js
Fixes #6963
- Create of each deployment type from the workload create page
=> Fix text on Workload Create page

.drone.yml, shell/edit/auth/azuread.vue, shell/models/cluster/node.js
Clone of #6929 - needed for merging into `master` branch.
Fixes #6953
Occurred changes and/or fixed issues
This issue would arise regardless of upgrading prior to v2.6.5 as we were checking only for the graphEndpoint, not for the other endpoints.
Added a method to determine if the values for all of the endpoints match the values in the hard coded map. If they don't match, custom will be the type.
Areas or cases that should be tested
- Steps to test are in the related issue
- A test environment can be given if needed
=> [Clone] Set initial endpoint radio group for azuread

shell/config/settings.js, shell/plugins/steve/subscribe.js, shell/utils/socket.js
Backport of https://github.com/rancher/dashboard/pull/6968
=> [2.6.9] Backport bugfix growl setting

shell/components/form/NameNsDescription.vue
Fixes Project Member cannot create resources in harvester-public ns
- https://github.com/harvester/harvester/issues/1986
- Add a product prop: `hideRONamespace`
=> HARVESTER: Hide read only namespaces

shell/components/form/NameNsDescription.vue
Backport of https://github.com/rancher/dashboard/pull/6997
=> [2.6.9] HARVESTER: Hide read only namespaces

shell/assets/translations/en-us.yaml
Fixes #6988 
Fixed typo: "etcd nods is not recommended" -> "etcd nodes is not recommended"
=> Fix typo in rke2 machine config etcd tooltip

pkg/harvester/config/settings.js, shell/assets/translations/en-us.yaml, shell/config/types.js, shell/edit/provisioning.cattle.io.cluster/rke2.vue
Harvester Cloud Provider compatibility check enhancement
- https://github.com/harvester/harvester/issues/2753
=> [WIP] HARVESTER: Harvester Cloud Provider compatibility check enhancement

pkg/harvester/config/settings.js, shell/assets/translations/en-us.yaml, shell/config/types.js, shell/edit/provisioning.cattle.io.cluster/rke2.vue
Backport of https://github.com/rancher/dashboard/pull/6995
=> [WIP] [2.6.9] HARVESTER: Harvester Cloud Provider compatibility check enhancement

shell/edit/auth/azuread.vue
Fixes #6428 
This is a forward port of #7029
=> Forward (#7029) - Rework conditional for correct flow

shell/components/form/NameNsDescription.vue
Fixes namespace filter error
- https://github.com/harvester/harvester/issues/1986
=> HARVESTER: Fix namespace filter error

shell/assets/styles/global/_select.scss, shell/components/form/LabeledSelect.vue
Fixes #
- https://github.com/harvester/dashboard/pull/450
=> [backport]: fix select style

shell/components/form/NameNsDescription.vue
Backport of https://github.com/rancher/dashboard/pull/7053
=> [2.6.9] HARVESTER: Fix namespace filter error

shell/edit/persistentvolume/index.vue
Fixes #6962
- To test Persistent Volume edit page.
- Persistent Volume needs to be bounded to a Persistent Volume Claim.
- Local test was performed on Chrome.
before:
after:
=> ui: fix PVC Summary card height

shell/components/form/ResourceTabs/index.vue, shell/pages/c/_cluster/apps/charts/install.vue, shell/pkg/dynamic-importer.lib.js, shell/store/catalog.js, shell/store/type-map.js, shell/utils/dynamic-importer.js
This adds the ability to use custom charts from within plugin.
=> Plugin updates for custom charts within pkg

shell/assets/translations/en-us.yaml
This PR is a follow-up to https://github.com/rancher/dashboard/pull/6994
I updated the wording match the updated description for the global setting in this comment, which changed after I made the above linked PR. https://github.com/rancher/dashboard/issues/6918#issuecomment-1257954411
=> Update language for global registry setting

shell/edit/auth/azuread.vue
Forward port for #6428 
Original PR #7058
=> [FP] Remove uneeded check - add custom check for old endpoints (#7058)

shell/config/settings.js
Fixes #7078
Extended reset capabilities from configuration to `ui-brand` setting.
- Reset ui-brand from the global settings
-
https://user-images.githubusercontent.com/5009481/194354998-997dbe9c-e73b-43ad-86a6-5047a9849026.mov
=> Allow to reset ui-brand global setting

shell/components/Tabbed/index.vue
Fixes #7106
Remove margin as suggesed
-
See issue details.
Any tabbed content
=> NetworkPolicy PolicyRules checkbox and buttons overlap

package.json
Fixes #7113
Updated version in the command.
Checks below should pass
-
See GH logs.
=> Update script to use newer version of Rancher Docker

shell/assets/translations/en-us.yaml
Fixes #7100 
Changes the text as requested by PM.
Removed the full-stops at the end of the two checkbox lines
Before:
After:
=> Update eula checkbox text

shell/edit/provisioning.cattle.io.cluster/rke2.vue
Show errors when create kubeconfig fail
- https://github.com/harvester/harvester/issues/2889
- https://github.com/rancher/dashboard/issues/7125
=> [2.6.9] HARVESTER: Show errors when create kubeconfig fail

shell/edit/provisioning.cattle.io.cluster/rke2.vue
Show errors when creating kubeconfig fail
- https://github.com/harvester/harvester/issues/2889
- https://github.com/rancher/dashboard/issues/7125
=> HARVESTER: Show errors when creating kubeconfig fail

pkg/harvester/l10n/en-us.yaml, pkg/harvester/l10n/zh-hans.yaml
HARVESTER: Modify the design of some harvester pages
Update Chinese translation
=> Harvester: Update 1.0.3 plugin translation

shell/plugins/plugin.js
Fixes issue where if call to fetch plugins returns 401, the user is logged out.
Should address (some) issues we're seeing with e2e test failures.
=> Fix for user being logged out

pkg/harvester/l10n/zh-hans.yaml, shell/assets/translations/zh-hans.yaml
port of https://github.com/rancher/dashboard/pull/7190
=> move harvester service chinese translation

pkg/harvester/package.json
change v1.0.3 plugin version
Fixes #6856
=> change version to release the harvester v1.0.3 plugin

pkg/epinio/edit/services.vue
Fixes # https://github.com/epinio/ui/issues/155
Adds a new step in the `validationPassed` that checks if a new application binding occured.
Follow https://github.com/epinio/ui/issues/155 to reproduce, it should be working now.
=> Saves configuration when adding new applications

shell/assets/translations/en-us.yaml, shell/components/GrowlManager.vue, shell/components/Import.vue, shell/components/form/MatchExpressions.vue, shell/detail/provisioning.cattle.io.cluster.vue, shell/edit/provisioning.cattle.io.cluster/MachinePool.vue, shell/models/cluster.x-k8s.io.machinedeployment.js
- Adds the remaining shell changes, which are completely isolated from any reference to Elemental, in 2.7.0
=> Remaining shell items for Elemental in 2.7.0

pkg/epinio/models/applications.js
Fixes #https://github.com/epinio/ui/issues/156
- previously filering on service configurations
- these were 1:m service to app, so provided false positives
- we can now just look directly at boundapps on service
Supersedes #https://github.com/rancher/dashboard/pull/6893
=> Ensure correct services are shown bound to apps

shell/assets/translations/en-us.yaml, shell/pages/c/_cluster/uiplugins/InstallDialog.vue, shell/store/type-map.js
Fixes #7208 
PR:
- Prevents rollback or upgrade to the version already installed
- Fixes to 'nor'
- Adds more permissions checks for 'Extensions' to show up which should mean users that can get to do actually have permissions to use it
=> Extensions: Fix minor issues

shell/components/SortableTable/index.vue, shell/detail/cis.cattle.io.clusterscan.vue, shell/list/node.vue
Fixes #7263
- Wire in custom highlighting handler
- Kube Node list
- CIS Benchmark Cluster Scan results table
=> Fix hover state of lists with custom sub-rows

shell/components/SortableTable/index.vue, shell/nuxt.config.js
- Extend `nuxt.config` to allow for passing of proxies as config options 
- fix issue for `label` cols in sortable table for advanced filtering
FYI @richard-cox
=> Minor fixes for Elemental

docusaurus/docs/testing/e2e-test.md
Fixes #7227
Updated documentation.
=> Clarify setup for E2E in documentation

shell/config/private-label.js
=> Update docs base for 2.7

shell/machine-config/harvester.vue
- https://github.com/harvester/harvester/issues/2977
https://github.com/harvester/harvester/issues/2977#issue-1414224517
=> Harvester: exclude the network created by storage-network

pkg/rancher-components/src/components/StringList/StringList.test.ts, pkg/rancher-components/src/components/StringList/StringList.vue, pkg/rancher-components/src/components/StringList/index.ts, pkg/rancher-components/src/index.ts, pkg/rancher-components/types/index.d.ts, shell/assets/translations/en-us.yaml, shell/utils/array.ts
- add StringList.vue
Fixes #7325
This is not a breaking change, so there are no impacts on other functionalities in the Dashboard UI.
List of feature:
- add a new item, by click Add button or db-click on empty space.
- select an item, by mouse-click or up/down arrows.
- remove an item, by select an item and click Remove button.
- inline edit an item, by db-click on existing items.
- scrollbar is visible when the box is full.
- up/down arrows makes scrollbar moves when it is visible.
- Add button is disabled when create/edit mode is active.
- Remove button is disabled when no item is selected or create mode is not active.
List of options:
- `caseSensitive` determines if items with same text will be treated …
=> StringList, new component

pkg/rancher-components/src/components/StringList/StringList.vue
=> StringList.vue, avoid empty items

pkg/rancher-components/package.json
=> Bump @rancher/components version

docusaurus/docs/code-base-works/api-resources-and-schemas.md, docusaurus/docs/code-base-works/customising-how-k8s-resources-are-presented.md, docusaurus/docs/code-base-works/directory-structure.md, docusaurus/docs/plugins/initializing-plugins.md, docusaurus/docs/products-and-navigation.md
Fixes build issues caused by a previous docs change: https://github.com/rancher/dashboard/pull/7162#issuecomment-1307390683
=> fix relative links in docs

shell/edit/persistentvolumeclaim.vue
Forwardport of https://github.com/rancher/dashboard/pull/7370
=> [forwardport] fix pvc creation in downstream clusters for standard users

docusaurus/docs/code-base-works/kubernetes-resources-data-load.md, docusaurus/sidebars.js
- Updating docs for kube resources data loading optimisation on dashboard
FYI @richard-cox @nwmac
=> Updating docs for kube resources data loading optimisation on dashboard

shell/models/management.cattle.io.cluster.js
Fixes #7442 
Backport of #7443
=> Backport #7443

shell/components/form/NameNsDescription.vue
Fixes #7120
When the user picks `Create New Namespace` and then clears it, the option is reset to default.
- Go to cluster Deployment
- Create a new Deployment
- Pick Create New Namespace
- Clear the value
=> Bug fix namespace value

shell/package.json
- Update `shell` package version for a new release
=> bump shell version

package.json, shell/package.json
- bump shell version + bump rancher icons version
=> bump shell version + bump rancher icons version

shell/edit/secret/generic.vue
- add option to parse each line of the file as key-value secret
Fixes #5921
=> Fix Multiline file upload in Secret edit page

shell/components/auth/SelectPrincipal.vue
- fix long text labels overflow
Fixes #6925
`SelectPrincipal` component
`SelectPrincipal` component
=> component: SelectPrincipal

shell/components/SortableTable/THead.vue
=> Sortable Table: prevent sort icons wrap

shell/components/__tests__/NamespaceFilter.test.ts
Fixes #7492
Linted with --fix format issue
=> Fix linting issue after new spacing rule 

pkg/rancher-components/src/components/StringList/StringList.test.ts, pkg/rancher-components/src/components/StringList/StringList.vue
=> StringList, add unit tests

shell/components/Collapse.vue, shell/components/SimpleBox.vue, shell/components/__tests__/Collapse.spec.ts, shell/components/__tests__/SimpleBox.spec.ts
=> unit tests: Collapse, SimpleBox

shell/components/nav/NamespaceFilter.vue
- add Enter key shortcut in case of searching word returns exactly one result.
- fix css
Fixes #5798
- Namespaces Search box
=> NamespaceFilter: add Enter shortcut

pkg/rancher-components/src/components/Utils/DraggableZone/DraggableZone.vue, pkg/rancher-components/src/components/Utils/DraggableZone/index.ts, shell/assets/styles/themes/_dark.scss, shell/assets/styles/themes/_light.scss, shell/assets/translations/en-us.yaml, shell/components/nav/WindowManager/ContainerShell.vue, shell/components/nav/WindowManager/index.vue, shell/layouts/default.vue, shell/store/wm.js
Fixes #4733
Please, feel free to suggest any visual/effect improvement of drag&pin animations
Terminal window
Terminal window
=> Configure Shell/Terminal location

shell/dialog/AddProjectMemberDialog.vue
=> AddProjectMemberDialog: add bottom border

shell/assets/translations/en-us.yaml
Fixes #6832
Changed menu item from `workload` to `workloads`
=> Changed menu item workload to workloads

pkg/rancher-components/src/components/Card/Card.test.ts, pkg/rancher-components/src/components/Card/Card.vue
Fixes #7410
Unit test for card components.
=> Added unit test for card

package.json, scripts/version, shell/assets/translations/en-us.yaml, shell/components/nav/TopLevelMenu.vue, shell/nuxt.config.js, shell/pages/about.vue
- display dashboard version on about page
=> display dashboard version on about page

stories/components/Collapse.stories.mdx, stories/components/StringList.stories.mdx, stories/global.scss
=> String List, add story

pkg/rancher-components/src/components/StringList/StringList.test.ts, pkg/rancher-components/src/components/StringList/StringList.vue
=> StringList, type:item event

shell/components/formatter/LiveDate.vue, shell/components/formatter/__tests__/Date.test.ts, shell/components/formatter/__tests__/LinkDetail.test.ts, shell/components/formatter/__tests__/LiveDate.test.ts, shell/components/formatter/__tests__/Si.test.ts
Fixes #7434 
this pr adds unit tests for LiveDate, Date, LinkDetail, and Si formatters
=> Unit test some table formatters

shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml, shell/pages/c/_cluster/explorer/index.vue
Fixes #
https://github.com/rancher/dashboard/issues/6327
=> fix(explorer/index): add cpu unit to the cores capacity section

README.md
This fixes some broken links to developer docs in README.md
=> Fix broken links to developer docs

pkg/rancher-components/src/components/StringList/StringList.vue
Fixes #https://github.com/rancher-sandbox/rancher-desktop/issues/3456
=> [StringList] delete pattern on editing

shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml, shell/edit/workload/storage/emptyDir.vue, shell/edit/workload/storage/index.vue
Fixes #
1. workload support add emptyDir volume
ref: https://kubernetes.io/docs/concepts/storage/volumes/#emptydir
https://github.com/rancher/rancher/issues/36760
=> feat(workload/storage): support add emptyDir volume

shell/dialog/RollbackWorkloadDialog.vue, shell/models/apps.controllerrevision.js, shell/models/apps.daemonset.js, shell/models/apps.deployment.js, shell/models/apps.replicaset.js, shell/models/apps.statefulset.js, shell/models/workload.js
=> workloads rollback fix

.github/workflows/rancher-components.yaml
=> CI, add steps for rancher-components

shell/components/auth/RoleDetailEdit.vue, shell/components/form/Select.vue, shell/models/management.cattle.io.roletemplate.js
Fixes #7549 
This PR also fixes a bug with the 'resources' select where hitting 'backspace' while the select is focused causes a console error and fails to clear the selected value.
=> Fix role form input event handling

pkg/rancher-components/src/components/Banner/Banner.test.ts, pkg/rancher-components/src/components/Banner/Banner.vue, shell/components/__tests__/CruResource.test.ts, shell/components/form/Error.vue, stories/components/Banner.stories.mdx
Fixes #7583
As in issue
As in issue
Check style guide locally for testing the component.
=> Add icon option to Banner and Error component

shell/components/form/KeyValue.vue, stories/components/form/KeyValue.stories.mdx
Fixes #7584
As defined in issue.
As defined in issue.
As defined in issue.
Run and open Storybook to test functionalities.
https://user-images.githubusercontent.com/5009481/204745048-2bc6a298-d1b1-435a-9711-1f1884f79067.mov
=> Allow KeyValue component to disable defined keys and conditionally filter from the view

cypress.config.ts
=> Remove retry and reduce waiting time for Cypress in local development

.storybook/preview.js
Fixes #7603
Added custom component for existing `<nuxt-link>`
For some reasons the `slot` attribute is not rendered in Storybook, so I kept an hardcoded value for the link.
It can be easily tested within this story (requires rebase or copy/paste) https://github.com/rancher/dashboard/issues/7597
=> Add nuxt-link component to Storybook

shell/edit/workload/index.vue, shell/edit/workload/mixins/workload.js
Fixes #
https://github.com/rancher/dashboard/issues/7398
=> fix(workload): select the newly added sidecar tab

pkg/rancher-components/README.md
This updates the `@rancher/components` readme to include information on
- Porting criteria
- Developing tips
- Porting and publishing
Fixes #5930
=> Update docs for `@rancher/components`

docusaurus/docs/code-base-works/directory-structure.md, shell/chart/monitoring/steps/uninstall-v1.vue, shell/components/PromptModal.vue, shell/components/form/Members/MembershipEditor.vue, shell/dialog/AddClusterMemberDialog.vue, shell/dialog/AddProjectMemberDialog.vue, shell/dialog/DiagnosticTimingsDialog.vue, shell/dialog/DrainNode.vue, shell/dialog/ForceMachineRemoveDialog.vue, shell/dialog/GenericPrompt.vue, shell/dialog/RollbackWorkloadDialog.vue, shell/dialog/RotateCertificatesDialog.vue, shell/dialog/RotateEncryptionKeyDialog.vue, shell/dialog/SaveAsRKETemplateDialog.vue, shell/edit/auth/azuread.vue, shell/models/cluster.x-k8s.io.machine.js, shell/models/cluster/node.js, shell/models/provisioning.cattle.io.cluster.js, shell/models/workload.js, shell/pages/diagnostic.vue
Fixes #6085 
This PR refactors the generic dialog component to allow custom dialog components to use more explicitly defined props.
=> refactor promptModal component props

shell/config/table-headers.js
Fixes #7560
Fixed the header title Age and the age itself to left-aligned.
=> Fixed table alignment in Age column

storybook/stories/Welcome.stories.mdx
Improves the storybook landing page:
- Adds the same graphics we use elsewhere
- Adds a link to the developer documentation
- Adds a note that this is work in progress
Preview:
=> Storybook improve landing page

.github/workflows/docusaurus.yaml
Fixes #7314 
This adds a step in the Docusaurus workflow to run anytime a PR is opened.
=> Add pr to docs workflow trigger

pkg/rancher-components/src/components/Form/Checkbox/Checkbox.test.ts, pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue, pkg/rancher-components/src/components/Form/ToggleSwitch/ToggleSwitch.test.ts, pkg/rancher-components/src/components/StringList/StringList.test.ts, pkg/rancher-components/src/components/StringList/StringList.vue, pkg/rancher-components/src/index.ts
=> [rancher-components] fix lint warnings

shell/mixins/browser-tab-visibility.js
=> fix Delete button when trying to delete users

shell/components/formatter/InternalExternalIP.vue, shell/models/cluster.x-k8s.io.machine.js, shell/models/management.cattle.io.node.js
Addresses https://github.com/rancher/dashboard/issues/6371
RKE1:
RKE2:
=> IP addresses render properly in Cluster Management

README.md
test for tagged version of dashboard in about page
=> test for tagged version of dashboard

pkg/rancher-components/src/components/StringList/StringList.vue
=> String List, remove text wrap

shell/components/ResourceDetail/index.vue, shell/plugins/dashboard-store/actions.js, shell/plugins/dashboard-store/resource-class.js, shell/plugins/steve/actions.js
backport of https://github.com/rancher/dashboard/pull/7670
=> [2.6] clean steve fields from yaml view and download

shell/plugins/steve/subscribe.js
Fixes #7707
Backport of PR https://github.com/rancher/dashboard/pull/7671 (https://github.com/rancher/dashboard/issues/5997)
=> [2.6] Improve handling of steve socket watch timeout

shell/utils/socket.js
Backport of https://github.com/richard-cox/dashboard/pull/new/2.6-improve-socket-logging
=> [2.6] Improve util socket logging

shell/edit/service.vue
Backport of https://github.com/rancher/dashboard/pull/6985
Original issue https://github.com/rancher/dashboard/issues/6984
Fixes https://github.com/rancher/dashboard/issues/7301
=> [Backport for 2.6.x] Fix: service selector preview does not consider namespace

shell/components/auth/SelectPrincipal.vue, shell/components/form/LabeledSelect.vue, shell/components/form/Members/ClusterPermissionsEditor.vue
=> Select Member, add tooltip

shell/components/formatter/LiveDuration.vue, shell/config/table-headers.js, shell/models/batch.job.js, shell/utils/time.js
=> duration field live refresh

shell/models/harvesterhci.io.management.cluster.js
When click the harvester cluster, the icon will not display。
We need to change `goToCluster` to an asynchronous function.
Fixes #
- https://github.com/harvester/harvester/issues/3174
=> show loading icon

shell/components/form/KeyValue.vue
=> Secrets, remove empty rows after a file upload

shell/pages/c/_cluster/apps/charts/index.vue, shell/store/prefs.js
=> Charts, handle chart-mode as a preference

shell/components/nav/WindowManager/index.vue, shell/layouts/default.vue
=> Terminal, limit drag&drop to tabs bar

shell/edit/workload/storage/ContainerMountPaths.vue
Fixes #7550 
- Remove unused `pvcs` request from `ContainerMountPaths`
=> Remove unused pvcs request from ContainerMountPaths

shell/assets/styles/themes/_dark.scss, shell/assets/styles/themes/_light.scss, shell/assets/styles/themes/_suse.scss, shell/components/nav/NamespaceFilter.vue
edit: fixes #7501 
Custom link colors are not applied to dropdowns/action menus because they're using the scss variable. This PR fixes that, along with a couple other tweaks:
* make ns filter border match other input borders (doesn't affect default colors where link and primary match)
* make dropdown selected and hover colors consistent between light and dark themes
* fix typo in SUSE theme
Existing UI with custom primary and link colors:
This pr with custom primary and link colors:
This PR with default colors:
This PR with SUSE theme (custom primary, default link):
=> Fix dropdown styles for custom link and primary colors

.github/workflows/scripts/publish-storybook
Storybook publish is broken - this PR should fix the script.
=> Storybook: Fix publish script

README.md, docusaurus/docs/getting-started/quickstart.md, docusaurus/sidebars.js
Updates our main repo README.
Moves the quick start to Docusaurus.
=> Update repo readme and move quickstart docs to docusaurus

shell/models/apps.deployment.js
Fixes [#37928](https://github.com/rancher/dashboard/issues/7803)
Fixes #7804
=> Fix rollback failure when deploying Deployment through yaml

shell/components/form/Probe.vue
This updates label and placeholder values for probes so that they accurately reflect their respective purpose. 
Fixes #7828 
=> Update probe labels and placeholders

shell/components/formatter/WorkloadHealthScale.vue
Fix alignment of icon following icon size change
Before
After
=> Fix Workload Health column drop down icon

shell/assets/translations/en-us.yaml, shell/cloud-credential/harvester.vue, shell/machine-config/harvester.vue
Backport of https://github.com/rancher/dashboard/pull/7827
Related issue https://github.com/harvester/harvester/issues/3319
=> [2.6.x] HARVESTER: Remove External Harvester Cloud Credentials Support

shell/dialog/GenericPrompt.vue, shell/dialog/ScaleMachineDownDialog.vue
=> fix Scale Down prompt

shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml, shell/chart/monitoring/steps/uninstall-v1.vue, shell/config/home-links.js, shell/config/private-label.js, shell/edit/auth/googleoauth.vue, shell/edit/cis.cattle.io.clusterscan.vue, shell/edit/monitoring.coreos.com.receiver/tls.vue, shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/pages/auth/setup.vue, shell/pages/c/_cluster/explorer/tools/index.vue, shell/plugins/axios.js, shell/plugins/dashboard-store/actions.js, shell/plugins/dashboard-store/getters.js, shell/plugins/dashboard-store/index.js, shell/plugins/dashboard-store/mutations.js, shell/store/i18n.js, shell/store/index.js, shell/utils/version.js
Reverts rancher/dashboard#7436
Reverting due to several issues:
https://github.com/rancher/dashboard/issues/7859
https://github.com/rancher/dashboard/issues/7840
=> Revert "get docs base url version from getVersionInfo"

shell/assets/translations/en-us.yaml, shell/edit/provisioning.cattle.io.cluster/rke2.vue
=> Cloud Provider, fix label for default value

shell/assets/translations/en-us.yaml, shell/cloud-credential/pnap.vue, shell/machine-config/pnap.vue, shell/models/rke-machine.cattle.io.pnapmachinetemplate.js, shell/store/pnap.js
phoenixNAP (pnap) is Rancher node driver which has its own cloud credential type in Rancher. Node provisioning and cluster creation works as expected when RKE1 is used as provisioner. This PR should solve issue to provision new node (through phoenixNAP node driver) and create cluster using RKE2/K3s. Additionally, implementation to dynamically pull locations, types, os is added as part of this PR.
fixes rancher/dashboard#6695
Added cloud credentials, machine config, model, store components for pnap machine driver.
Steps to reproduce: 
Go to Cluster Management, 
Clusters -> Create, 
Provision new nodes and create a cluster using RKE2/K3s -> select phoenixNAP, 
Select pnap cloud credentials. Verify that there is custom UI for pnap which dynamically populates Location Type and OS drop downs, …
=> pnap machine driver implementation

shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml
- Update Chinese translation and fix typo
=> Update Chinese translation and fix typo

shell/cloud-credential/pnap.vue, shell/machine-config/pnap.vue
- the pnap PR was pretty old and gates were last run prior to some lint changes
=> Fix linting after PNAP driver changes

shell/assets/translations/en-us.yaml
Backport of https://github.com/rancher/dashboard/pull/7889
=> [2.6] HARVESTER: Label text change

shell/assets/translations/en-us.yaml
Change Input label `Cluster` to `Imported Harvester Cluster`
- https://github.com/harvester/harvester/issues/3319
=> HARVESTER: Label text change

shell/cloud-credential/azure.vue
Fixes #7909 
Adds parsing of the error response when validating Azure cloud credential during creation.
There are two types of error response - one with a string message and the other with a json blob - this PR attempts to parse either.
With this in place, we now present more helpful messages to users to help them figure out what is not right with the data they have entered.
**Subscription ID problem:**
**Invalid Client ID:**
**Invalid Client Secret:**
Previous to this PR, in all cases you just get a generic message indicating that verification failed.
=> Improve error messages when creating an Azure cloud credential

pkg/harvester/config/harvester.js, pkg/harvester/models/harvesterhci.io.virtualmachineimage.js, shell/components/ExplorerProjectsNamespaces.vue, shell/components/ResourceDetail/Masthead.vue, shell/models/namespace.js, shell/store/type-map.js
Fix go to the namespace details page is not supported in the harvester ui
- https://github.com/harvester/harvester/issues/2916
- Add hideNamespaceLocation for product config
- Not allowing view the namespace detail page in guest Harvester cluster
- Fix can not found `@shell/machine-config/harvester`
=> HARVESTER: Add hideNamespaceLocation for product config

shell/nuxt.config.js
Fixes `RANCHER_ENV=harvester yarn mem-dev` can not found `@pkg/harvester/config/labels-annotations`
=> HARVESTER: Support `@pkg/harvester` in `yarn dev`

shell/components/ResourceDetail/index.vue
Harvester resources may display in other product, we hope user can only create harvester resources via yaml in that case.
Consequently, I exposed the forceYaml property from harvester models.
- https://github.com/harvester/harvester/issues/2184
=> Use property forceYaml to create resources via yaml

shell/assets/translations/en-us.yaml
=> fix: Fixed typo

shell/edit/auth/github.vue, shell/edit/auth/googleoauth.vue, shell/edit/auth/ldap/index.vue, shell/edit/auth/oidc.vue, shell/edit/auth/saml.vue
Fixes #7737
Fixed styling for `code` tag in Auth Provider details pages.
Burger Menu --> Users & Authentication --> Auth Provider --> Github ( also check other Auth Provider pages )
Scroll to bottom
=> Fixed code tab bug in all auth provider types pages

shell/assets/translations/en-us.yaml, shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/edit/storage.k8s.io.storageclass/index.vue, shell/edit/storage.k8s.io.storageclass/provisioners/driver.harvesterhci.io.vue, shell/models/storage.k8s.io.storageclass.js
Storage Tiering support of the Harvester CSI Driver
- https://github.com/rancher/dashboard/issues/7850
- https://github.com/harvester/harvester/issues/3052
- Add hostStorageClass on Harvester provisioner of storageClass page 
- Add a warning when the CSI version is old
**Test Plan 1**
1. Install a Rancher and import a Harvester cluster (host cluster)
2. Create a RKE2 cluster (guest cluster) by Harvester node driver
3. Update the `rke-metadata-config` setting of Rancher, e.g. `{"refresh-interval-minutes":"10","url":"https://harvester-dev.oss-cn-hangzhou.aliyuncs.com/rke-meta-data.json"}`
4. Update the new `rke-meta-data.json`, find the k8s version of the guest cluster and update the CSI version < 0.1.15
5. Check the warning banner (Screenshot 2)
6. Update the CSI version >= 0.1.15
7. Check …
=> HARVESTER: Storage Tiering support of the Harvester CSI Driver

shell/assets/translations/en-us.yaml, shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/edit/storage.k8s.io.storageclass/index.vue, shell/edit/storage.k8s.io.storageclass/provisioners/driver.harvesterhci.io.vue, shell/models/storage.k8s.io.storageclass.js
Backport of https://github.com/rancher/dashboard/pull/7869
=> [2.6.x] HARVESTER: Storage Tiering support of the Harvester CSI Driver

pkg/harvester-manager/machine-config/harvester.vue, shell/assets/translations/en-us.yaml, shell/utils/validators/cidr.js
- https://github.com/harvester/harvester/issues/2426
Fixes #
test step: 
- https://github.com/harvester/docker-machine-driver-harvester/pull/35
=> HARVESTER: support multi nic

shell/utils/string.js
Fixes #7902
Search button; ensure that labels for plural & single objects are correctly calculated.
Search button's results.
=> [type-map.js], fix pluralize function

pkg/rancher-components/src/components/Banner/Banner.vue, shell/pages/c/_cluster/auth/config/index.vue, shell/pages/home.vue
Fixes #7794
Re-worked on home page banner link alignment fix as the current fix was breaking the banner in cluster > auth > config page
**Before**
**c/local/auth/config page** 
**Home page banner**
**c/local/auth/config**
**Home page banner**
=> Re-worked on home page banner link alignment fix

shell/utils/validators/formRules/__tests__/index.test.ts, shell/utils/validators/formRules/index.ts
Fixes #6633
New case with decimal using 0 as value, e.g. 1.0.
=> Allow to change minimum length requirement for user password

shell/assets/translations/en-us.yaml, shell/list/management.cattle.io.podsecurityadmissionconfigurationtemplate.vue
Fixes #8016
As in issue.
Add info banner to PSA template list.
Adding screenshot as it's static.
=> Add banner to PSA list

shell/edit/monitoring.coreos.com.alertmanagerconfig/types/email.vue
Fixes #7973 
Backport of https://github.com/rancher/dashboard/pull/7526
=> [2.6] fix alertmanager receiver requireTLS field casing

shell/assets/translations/en-us.yaml
Fixes #7318 
Backport of: https://github.com/rancher/dashboard/pull/7319
=> [2.6]fix azuread migration warning modal text

shell/components/form/ResourceTabs/index.vue, shell/detail/workload/index.vue
=> [Backport 2.6.x] Add event list to Pod detail page

shell/edit/workload/index.vue
Fixes #8090
- Bring back add container button
- Also fixed text flush to icon
- this was broken via https://github.com/rancher/dashboard/pull/7990 (https://github.com/rancher/dashboard/pull/7990/files#diff-1e8612cdc344c04a806d686e55bd67c1d30eef9cd86bb0f7a9d803fed5cb5f6aL569)
- Each workload type that additional containers can be specified for
- ![image](https://user-images.githubusercontent.com/18697775/216620325-cf91662a-73ea-4199-a614-6e7df377ab76.png)
=> Fix broken workload `Add Container` button

shell/package.json
- Bumping shell package version for a new release
=> bumping shell package version for release

shell/components/ResourceDetail/index.vue, shell/models/harvesterhci.io.management.cluster.js
Backport PRs: 
- https://github.com/rancher/dashboard/pull/7715
- https://github.com/rancher/dashboard/pull/7857
=> [2.6 Backport] Show loading icon & Add forceYaml

shell/edit/provisioning.cattle.io.cluster/rke2.vue
In order to be compatible with the released version of Harvester, when the version of Harvester is less than `v1.2`, we cannot do the compatibility check.
Fixes #
- https://github.com/harvester/harvester/issues/3389
=> HARVESTER: Fix is compatible with rke and csi version range

shell/edit/provisioning.cattle.io.cluster/rke2.vue
This is a backport pr:   https://github.com/rancher/dashboard/pull/8080
Fixes #
- https://github.com/harvester/harvester/issues/3389
=> [backport] HARVESTER: Fix is compatible with rke and csi version range

shell/edit/provisioning.cattle.io.cluster/__tests__/rke2.test.ts, shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #8061
Reset to be handled with https://github.com/rancher/dashboard/issues/8068. Please wait the merge of the other version if you want to test it.
PSA is basically always enabled if version above 1.23, which is the first support for it.
Extended tests.
https://user-images.githubusercontent.com/5009481/217045341-4a97302f-809c-4563-bcc9-bc00f245228b.mov
=> Add support for Pod Security Admission - Cluster K3S

shell/components/ResourceTable.vue
=> ResourceTable, fix Enter shortcut

README.md
=> Update readme copyright year

shell/store/prefs.js
Fix prefs compatibility with Rancher v2.6.x
Reproduce Steps:
1. Install Rancher v2.6.10, and install Harvester v1.1.1
2. Login Rancher and go to the Global setting. Set `ui-dashboard-index` to `https://releases.rancher.com/dashboard/latest/index.html`. Set `ui-offline-preferred` to `Remote`.
3. Login to the Harvester UI, and go to settings. Set `ui-plugin-index` to `https://releases.rancher.com/harvester-ui/plugin/harvester-latest/harvester-latest.umd.min.js`. Set `ui-source` to `External `
4. Login Rancher and import Harvester.
5. Go to the Harvester cluster and then go to VM list page
The related Harvester PR is https://github.com/harvester/dashboard/pull/567
[Error]
=> [2.6] HARVESTER: Fix prefs compatibility with Rancher v2.6.x

shell/package.json
=> Bumping shell pkg version

shell/store/prefs.js
Forwardport of https://github.com/rancher/dashboard/pull/8082
=> [Forwardport 2.7] HARVESTER: Fix compatibility with Rancher v2.6.x

pkg/harvester-manager/machine-config/harvester.vue, shell/config/harvester-manager-types.js, shell/edit/provisioning.cattle.io.cluster/import.vue, shell/package.json
Fixes #8008 
- fix issue with dependency on `@pkg/harvester` on shell
- fix console warning
- add` vue-virtual-scroll-list` as a dependency of shell
=> fix issue with dependency on @pkg/harvester on shell

shell/components/ExplorerProjectsNamespaces.vue, shell/models/namespace.js
Fixes Cannot edit Harvester namespace
Related Harvester PR is https://github.com/harvester/dashboard/pull/577
- https://github.com/harvester/harvester/issues/3435
Edit location has a dependency on the detail location, so add a `hideDetailLocation` without changing the detail location
=> HARVESTER: Fix Cannot edit Harvester namespace

shell/components/ExplorerProjectsNamespaces.vue, shell/components/ResourceTable.vue, shell/components/form/NameNsDescription.vue, shell/components/nav/NamespaceFilter.vue, shell/store/index.js, shell/store/type-map.js
1. Remove the specific code in the shell directory that handles the harvester namespace
2. Added the ability to filter namespaces by page， （For example, in the harvester secret list page, including the secret edit page, we need to display the `cattle-monitor-system` namespace, but we do not need to display the namespace on other pages)
https://github.com/rancher/dashboard/compare/master...WuJun2016:dashboard:rancher-polish-namespace?expand=1#diff-ba839658293b6cda38dc598db958084e9c449da7b72466eb27b55d9203d6c8a2R119
https://github.com/rancher/dashboard/compare/master...WuJun2016:dashboard:rancher-polish-namespace?expand=1#diff-ba839658293b6cda38dc598db958084e9c449da7b72466eb27b55d9203d6c8a2R126
Harvester repo related pr see https://github.com/harvester/dashboard/pull/550
Fixes #
=> polish namespace

shell/assets/translations/en-us.yaml
Fixes #8037
Updated warning as in description.
=> Update warning about PSAC template

shell/assets/translations/en-us.yaml, shell/edit/provisioning.cattle.io.cluster/MachinePool.vue, shell/machine-config/azure.vue
#8014 in conjunction with https://github.com/rancher/ui/pull/4960
This PR adds the field requested in the issue along with some warnings about fields that must be set for the cluster to provision when an AZ is set.
=> Add enablePublicIpStandardSku field to azure rke2 provisioning

shell/components/SingleClusterInfo.vue, shell/edit/storage.k8s.io.storageclass/provisioners/driver.harvesterhci.io.vue, shell/models/management.cattle.io.cluster.js, shell/pages/c/_cluster/explorer/index.vue
Backport of https://github.com/rancher/dashboard/pull/8169
=> [Backport 2.6] Fix kubernetesVersionExtension is '' on the create Harvester storage class page

shell/assets/translations/en-us.yaml
Fixes #8032
Missing requirement: Rename  PSP label in RKE2 cluster editor
=> PSA: Update PSA default

shell/edit/management.cattle.io.podsecurityadmissionconfigurationtemplate.vue, shell/models/management.cattle.io.podsecurityadmissionconfigurationtemplate.js, shell/models/management.cattle.io.podsecurityadmissionconfigurationtemplate.ts
Fixes #8057
Corrected redirection
Added doneRouting attribute and method to the form.
https://user-images.githubusercontent.com/5009481/219354973-ccf65f50-b547-4660-961d-ac70eeed3002.mov
=> When creating a PSACT value as YAML, you are not redirected back to the Pod Security Admissions tab

shell/pages/c/_cluster/monitoring/index.vue
=> Monitoring tab, fix cards layout

shell/assets/translations/en-us.yaml
Fixes #8225 
This nav item links to an Ember page: those translations are updated in this PR: https://github.com/rancher/ui/pull/4969
=> rename pod security policies nav item to pod security policy templates

shell/pages/c/_cluster/uiplugins/InstallDialog.vue, shell/pages/c/_cluster/uiplugins/index.vue
- sneaky fix small issue with extension developer load (bug on check's for the extension version binding)
=> fix small issue with extension developer load

shell/layouts/default.vue, shell/pages/index.vue
Fixes #7835
Reproduction steps in https://github.com/rancher/dashboard/issues/7835#issuecomment-1370715754
1. fix(pages/index): fix repeated redirect to the root path
2. fix(layouts/default): save lastVisited prefs only if params not empty
=> fix(pages/index): fix repeated redirect to the root path

shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #
- https://github.com/harvester/harvester/issues/3506
=> HARVESTER: fix harvester version prerelease compare

docusaurus/docs/extensions/advanced.md, docusaurus/docs/extensions/extension-api-methods/add-action.md, docusaurus/docs/extensions/extension-api-methods/add-card.md, docusaurus/docs/extensions/extension-api-methods/add-panel.md, docusaurus/docs/extensions/extension-api-methods/add-tab.md, docusaurus/docs/extensions/extension-api-methods/add-table-column.md, docusaurus/docs/extensions/extensions-api.md, docusaurus/docs/extensions/extensions-getting-started.md, docusaurus/docs/extensions/initializing-extensions.md, docusaurus/docs/extensions/introduction.md
Tidy up the extension docs:
- fixed a few typos/wording
- added syntax highlighting to code blocks
- added a few links
=> Update extension docs

shell/components/ResourceTable.vue, shell/components/SortableTable/index.vue, shell/list/provisioning.cattle.io.cluster.vue
Fixes #8250
This is a forward port of https://github.com/rancher/dashboard/pull/8249
=> Fix stale RKE1 cluster information in clusters list

shell/models/constraints.gatekeeper.sh.constraint.js
=> fix(constraints.gatekeeper.sh.constraint): fix resourceVersion not updated issue

shell/components/form/SecretSelector.vue, shell/edit/provisioning.cattle.io.cluster/RegistryConfigs.vue
Fixes #8287
fix(RegistryConfigs): fix missing TLS Secret options issue
=> fix(RegistryConfigs): fix missing TLS Secret options issue

shell/content/docs/en-us/whats-new.md
Fixes #8050 
Since PSAs will need some delicate work for users to navigate as they upgrade to Kubernetes 1.25, we're bringing back this file to ensure we warn folks early on that if they use PSPs, they'll need to migrate to PSAs if they go up to 1.25.
=> what's new for 2.7.2

shell/store/index.js, shell/utils/monitoring.js
When in the harvester cluster, we should request `schema` from the harvester store.
Fixes #
- https://github.com/harvester/harvester/issues/3537
=> enhancement use dynamic store

shell/pages/c/_cluster/uiplugins/PluginInfoPanel.vue
- fix issue with plugins panel versions button wrap
_Note: i've duplicated the buttons on the screenshots to better highlight the problem_
**VS**
=> fix issue with plugins panel versions button wrap

docusaurus/docs/extensions/advanced.md, docusaurus/src/pages/index.js
Fix reference to plugins + minor fixes
=> Very minor Extension docs changes

shell/machine-config/azure.vue
Fixes #8283 
- address QA comment https://github.com/rancher/dashboard/issues/8283#issuecomment-1452261743 where form comes mostly empty when adding a new machine pool while editing an Azure cluster
=> address QA concerns for #8283

shell/config/product/explorer.js, shell/store/type-map.js
Backport of https://github.com/rancher/dashboard/pull/8355
=> [2.7.2]Hide PSA CRD in downstream clusters

shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes https://github.com/rancher/dashboard/issues/8369
Backport of https://github.com/rancher/dashboard/pull/8360
=> [2.7.2 ]Add async/await tag to the RKE2 PSP check function

shell/assets/translations/en-us.yaml, shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #8123
Added documentation link as planned.
=> Add documentation link to the CIS hardening banner

shell/assets/translations/en-us.yaml, shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes https://github.com/rancher/dashboard/issues/8123
Backport https://github.com/rancher/dashboard/pull/8396
=> Add documentation link to the CIS hardening banner (#8396)

package.json, pkg/harvester-manager/l10n/en-us.yaml, pkg/harvester-manager/l10n/zh-hans.yaml, pkg/harvester-manager/machine-config/harvester.vue, shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml, yarn.lock
- UI Controls whether to install guest-agent
- Fixed compatibility issues with terrform
Fixes #
- https://github.com/harvester/harvester/issues/3392
- https://github.com/harvester/harvester/issues/3598#event-8675055710
=> [2.7.2] harvester rke2 support control guest agent

shell/edit/networking.k8s.io.networkpolicy/PolicyRuleTarget.vue
=> Network Policies: fix mathing pod and namespaces message, initial values

shell/utils/time.js
=> Jobs, fix Duration field format

pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue, shell/utils/position.js, shell/utils/select.js
`terminal` window, drag &drop function
`ActionMenu` position in each row of our SortableTables
`LabeledSelect.vue`
=> Remove jquery from position.js, select.js

shell/components/LazyImage.vue
=> Remove jquery from LazyImage.vue

shell/assets/translations/en-us.yaml, shell/chart/gatekeeper.vue, shell/mixins/chart.js, shell/pages/c/_cluster/apps/charts/install.vue
Fixes #8382
Backport of https://github.com/rancher/dashboard/pull/8381/
=> [2.7.2]Add enableDefaultSeccompProfile option to the Gatekeeper chart install ui

shell/assets/translations/en-us.yaml
Fixes #8445 
backport of https://github.com/rancher/dashboard/pull/8446
=> [2.7.2] update rke2 psa label

shell/edit/helm.cattle.io.projecthelmchart.vue
Backport of https://github.com/rancher/dashboard/pull/8349
fixes #8366
=> [2.7.2] Fix setting Helm values for ProjectHelmCharts

shell/config/product/auth.js
Fixes https://github.com/rancher/dashboard/issues/8406
Backport of https://github.com/rancher/dashboard/pull/8405/
=> allow users who can view roles to see the users & auth product

shell/components/form/LabeledSelect.vue
Fixes #8324
This appears to be a regression, it was fixed here https://github.com/rancher/dashboard/pull/6302 and re-broken here: https://github.com/rancher/dashboard/pull/7010/files#diff-5316c4da698262a356a5f70f02f4d94b95c66b780cedf9cb04515deb011017d8R281
=> Fix alertmanager receiver secret inputs

shell/assets/translations/en-us.yaml, shell/dialog/GenericPrompt.vue, shell/utils/__tests__/string.test.ts, shell/utils/string.js
Fixes #8481
Backport PR https://github.com/rancher/dashboard/pull/8464
=> Modify PSP deprecation warning message when upgrading a K3s custom cluster to v1.25

shell/components/ButtonDropdown.vue, shell/components/nav/TopLevelMenu.vue
`ButtonDropdown.vue`
`TopLevelMenu.vue`
=> Remove jquery from ButtonDropdown.vue, TopLevelMenu.vue

shell/core/plugin-routes.ts, shell/layouts/default.vue, shell/middleware/authenticated.js
Forward port of https://github.com/rancher/dashboard/pull/8449
=> [2.7] Forward port: Fix route collisions

pkg/harvester-manager/machine-config/harvester.vue
Fixes #
- https://github.com/harvester/harvester/issues/3698
=> HARVESTER: hide macAddress

pkg/harvester-manager/machine-config/harvester.vue
This is a backport pr:  https://github.com/rancher/dashboard/pull/8492
Fixes #
=> [2.7.2] HARVESTER: hide macAddress

shell/edit/provisioning.cattle.io.cluster/rke2.vue
Backport of https://github.com/rancher/dashboard/pull/8504
=> [Backport 2.7.2] HARVESTER: Validate ccm & csi maximum version

shell/edit/provisioning.cattle.io.cluster/rke2.vue
=> [2.7] Forward port #8482

shell/assets/translations/zh-hans.yaml, shell/content/docs/zh-hans/whats-new.md
- Update Chinese translation for Rancher v2.7
=> [v2.7] Update Chinese translation

shell/components/ActionMenu.vue
=> ActionMenu, safe querySelector

shell/assets/translations/en-us.yaml, shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #8511 
backport of https://github.com/rancher/dashboard/pull/8462
=> [2.7.2]fix sort order of rke2/k3s kubernetes version list

shell/edit/namespace.vue
=> fix(edit/namespace): fix not initializing the container resource limit defaults

.vscode/settings.json, shell/chart/gatekeeper.vue, shell/chart/istio.vue, shell/chart/logging/index.vue, shell/chart/monitoring/index.vue, shell/chart/rancher-backup/index.vue, shell/components/ChartPsp.vue, shell/components/__tests__/ChartPsp.test.ts, shell/pages/c/_cluster/apps/charts/__tests__/install.helper.test.ts, shell/pages/c/_cluster/apps/charts/install.helpers.js, shell/pages/c/_cluster/apps/charts/install.vue
=> Custom chart UIs show PSP switch on Kubernetes v1.25 (merge fix)

shell/machine-config/harvester.vue
This is a backport pr: https://github.com/rancher/dashboard/pull/8492
Fixes #
=> [2.6] hide macaddress

shell/components/fleet/FleetIntro.vue
Fixes https://github.com/rancher/dashboard/issues/8467
=> hide create git repo button if user does not have permission to do so

shell/assets/translations/en-us.yaml
Fixes https://github.com/rancher/dashboard/issues/8426
backport of https://github.com/rancher/dashboard/pull/8560
=> [2.7.2]update rke2 provisioning psp deprecation info banner 2 electric bugaloo

shell/assets/translations/en-us.yaml, shell/components/fleet/FleetIntro.vue, shell/edit/management.cattle.io.fleetworkspace.vue, shell/plugins/dashboard-store/actions.js
Fixes #8530 
Backport of https://github.com/rancher/dashboard/pull/8490/
=> Backport bugfix fleet permissions

shell/cloud-credential/generic.vue
Fixes #8563 
backport of https://github.com/rancher/dashboard/pull/8564
=> [2.7.2]fix generic cloud credential key option logic

shell/assets/translations/en-us.yaml
Fixes https://github.com/rancher/dashboard/issues/8426
See comment on backport issue: https://github.com/rancher/dashboard/issues/8445#issuecomment-1487818511
=> update rke2 provisioning psp deprecation info banner 2 electric bugaloo

shell/pages/c/_cluster/apps/charts/install.vue
Fixes https://github.com/rancher/dashboard/issues/8575
backport of https://github.com/rancher/dashboard/pull/8573
=> [2.7.2]Fix overwritten chart global values

shell/pages/c/_cluster/fleet/index.vue
Fixes #8531
backport of https://github.com/rancher/dashboard/pull/8590
=> [2.7.2]hide continuous delivery get started btn if user cant create gitrepos

shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml, shell/content/docs/zh-hans/getting-started.md, shell/content/docs/zh-hans/whats-new.md
- Update Chinese translation for Rancher v2.6
=> [v2.6] Update Chinese translation

shell/chart/gatekeeper.vue, shell/mixins/chart.js, shell/pages/c/_cluster/apps/charts/install.vue
Fixes #https://github.com/rancher/dashboard/issues/8635 
backport of https://github.com/rancher/dashboard/pull/8636
=> [2.7.2]Ensure CRDs are always installed with the same global values as the main chart

shell/detail/fleet.cattle.io.clustergroup.vue
Fixes #8540 
- add missing dispatch to fetch fleet workspaces
Check issue description
=> Fix issue with Fleet clustergroup details view

shell/store/gitlab.js
Fixes https://github.com/epinio/ui/issues/213
=> Application source, fix searching of GitLab orgs

shell/store/github.js, shell/store/gitlab.js
Fixes https://github.com/epinio/ui/issues/214
- fix commits API to get all commits
- cache avatars for each commit's author
=> App creation, fix GitLab `commits` API

shell/assets/styles/global/_button.scss, shell/components/auth/RoleDetailEdit.vue, shell/components/form/HookOption.vue, shell/components/form/MatchExpressions.vue, shell/components/form/Tolerations.vue, shell/components/form/ValueFromResource.vue, shell/components/form/WorkloadPorts.vue, shell/edit/workload/storage/Mount.vue
Fixes #5561
- Fixed active/focus state for `Remove` buttons
- Fixed alignment of the `Remove` button in different forms
Go to any form e.g. in the deployment or Pods creation form. 
- check the `Remove` button alignment in any add/remove element.
=> Fixed remove button style and alignments

shell/assets/translations/en-us.yaml, shell/edit/provisioning.cattle.io.cluster/MachinePool.vue, shell/edit/provisioning.cattle.io.cluster/rke2.vue
=> [Backport v2.6] RKE2 cluster create/edit screen allows saving invalid configuration

pkg/epinio/components/application/AppSource.vue, pkg/epinio/detail/applications.vue
- ensure edit app source vars are fixed for non github/gitlab types
- fix app details page console error for non github/gitlab types
=> Fix two edit app source issues

shell/components/Carousel.vue
Fixes #7624
- Fixed missing right slide in Carousel when the user is on the 2nd slide.
- Also fixed the slide alignment issue.
Nav to Cluster --> Apps --> Charts
Navigate to the second slide - It should show the right side slide.
=> Fixed right side missing slide issue, Fixed styling of Carousel slide

shell/components/nav/NamespaceFilter.vue
Fixes #7757
Fixed focus state of the selected option in the Namespace filter
Check the focus state of the selected option in the Namespace filter, it should be visible.
https://user-images.githubusercontent.com/18264463/222056635-75f7251b-756e-49d7-b842-ca23bb3796e1.mov
=> Fixed focus state for namespace filter

cypress/e2e/po/components/component.po.ts, shell/components/SortableTable/index.vue, shell/components/SortableTable/selection.js, shell/pages/rio/mesh.vue, shell/utils/dom.js
`SortableTable`, selection, selection shortcuts, multiple selections
=> Remove jquery from SortableTable

storybook/yarn.lock
Storybook build fails with following errors:
```
$ build-storybook -o ../storybook-static
info @storybook/vue v6.5.14
info 
info => Cleaning outputDir: /home/francesco/WORK/rancher/test-ci-storybook/dashboard/storybook-static
info => Loading presets
WARN   Failed to load preset: {"type":"presets","name":"/home/francesco/WORK/rancher/test-ci-storybook/dashboard/storybook/node_modules/@storybook/vue/dist/cjs/server/framework-preset-vue.js"} on level 1
ERR! Error: Cannot find module 'vue-loader'
ERR! Require stack:
ERR! - /home/francesco/WORK/rancher/test-ci-storybook/dashboard/storybook/node_modules/@storybook/vue/dist/cjs/server/framework-preset-vue.js
ERR! - /home/francesco/WORK/rancher/test-ci-storybook/dashboard/storybook/node …
```
=> [Dependencies] align `storybook/package.lock`

shell/edit/provisioning.cattle.io.cluster/rke2.vue
This is a backport pr:   https://github.com/rancher/dashboard/pull/8213
Fixes #
=> fix harvester version prerelease compare (#8213)

shell/assets/translations/en-us.yaml, shell/edit/logging.banzaicloud.io.output/index.vue, shell/edit/logging.banzaicloud.io.output/providers/loki.vue
Fixes #7657
Added hint of the expected format in URL input
- Rancher >> Cluster >> Logging >> Outputs/ClusterOutputs >> create >> Give a name >> Select Loki from the Output dropdown
- In the URL textbox, give Loki server name without http/https
- Click Create
=> Added placeholder in url input

shell/pages/diagnostic.vue
Fixes #7634 
The issue was caused by the `topTenForResponse` property being overwritten with each cluster that contained counts. I've fixed the property to contain an array of counts for each cluster, then when gathering the response times to iterate over each cluster and return the top 15 counts for each.
Also changed the property name to match the correct number of counts: `topFifteenForResponse`. 
__First cluster__
__Second cluster___
=> Fix response times for multiple clusters

shell/components/SortableTable/index.vue, shell/components/SortableTable/selection.js
Fixes #8273
Fixed selected row counter
> Go to any table with rows
> Hit shift+j until all rows are selected, the counter should not overflow.
=> Fixed selected rows counter

package.json
Fixes #8746
Issue with memory heap seems to be solved when I push it to my fork: https://github.com/cnotv/dashboard/actions/runs/4817581472/jobs/8578478990
The issue seems really just about memory limitation on build. Still unclear why it increased so much when we actually removed libraries. We do not keep track of the performances so we will never know at this point.
=> Prevent E2E workflow to fail on build phase

shell/components/BrandImage.vue
Fixes #8431
`this.$store.getters['management/all'](MANAGEMENT.SETTING)`  is a synchronous method and does not require asynchronous processing
ref: https://github.com/rancher/dashboard/blob/master/shell/plugins/dashboard-store/getters.js#L50
=> fix(BrandImage): remove async fetch method

package.json, storybook/package.json
Fixes #8758
- Removed lint command on build
=> Prevent E2E to fail on lint issues

shell/utils/grafana.js
Fixes: https://github.com/rancher/dashboard/issues/8725
=> fix(grafana.js):add try-catch block to monitoring version request

pkg/epinio/models/application-action.js
Fixes https://github.com/epinio/ui/issues/231
This will aligns the `deploy` application request's payload with latest back-end changes:
https://github.com/epinio/epinio/blob/a294cb10feb04e87c37b2af41787fbce8a1108c0/docs/references/api/swagger.json#L2384-L2390
=> Fix deploy request payload

shell/components/CruResource.vue, shell/edit/provisioning.cattle.io.cluster/index.vue
=> CruResource, make preventSubmit optional

cypress/e2e/po/pages/login-page.po.ts, cypress/e2e/tests/pages/user_menu/logout.spec.ts, shell/pages/auth/login.vue
Logout functionality test:
1. Logout of Rancher Dashboard
2. Verify user lands on login page after logging out
3. Attempt to navigate to the Home page without logging back in
4. Verify user remains on login page
Note: The logout_test branch (this branch) was create from performance_page branch which has yet to be merged. Will merged that branch and rebase
=> Cypress: Logout test

package.json, shell/core/plugins-loader.js, shell/package.json, shell/pkg/vue.config.js, yarn.lock
Contributes to https://github.com/rancher/dashboard/issues/4534
`UI Extensions`, `shell` package
=> Remove jquery from dependencies

pkg/epinio/l10n/en-us.yaml, pkg/epinio/login/epinio.vue
Fixes https://github.com/epinio/ui/issues/230
=> Fix Epinio log in button's label

package.json, shell/babel.config.js, yarn.lock
Fixes #5631
- Added `babel-plugin-transform-require-context` library
- Converted `babel.config.js` into a function and added conditionally logic if test
Try to remove comment to the example file and error should change (test is still incomplete 😅)
=> Add transformer for require using Babel

pkg/epinio/components/application/AppInfo.vue
Fixes https://github.com/epinio/ui/issues/225
=> Remove capitalization from application variables fields

shell/components/Wizard.vue, shell/pages/c/_cluster/apps/charts/install.vue
Fixed dark theme bug for Helm Chart Install page
https://github.com/rancher/dashboard/assets/18264463/f87e5f89-8a58-4165-9118-bb7546369723
Dark theme:
=> Wizard theme color fix

shell/components/form/KeyValue.vue, shell/components/form/__tests__/KeyValue.test.ts, shell/utils/__tests__/create-yaml.test.ts, shell/utils/array.ts, shell/utils/create-yaml.js
=> Test automation around YAML chomping

shell/pages/c/_cluster/uiplugins/index.vue
Fixes #8332
Fixed empty available list issue immediately after enabling extensions
Go to Extensions > after enabling Extension > available tab should show a list of enabled Extensions
=> Fixed empty available list issue immediately after enabling extensions

package.json
- failure to contact the sorry cypress instance is blocking cypress runs within CI
- sorry cypress dashboard is unreachable via dashboard or DO site's terminal
```
RequestError: Error: connect ECONNREFUSED ....
We encountered an unexpected error talking to our servers.
```
=> Temporarily disable sorry cypress

shell/assets/translations/en-us.yaml
=> Fix project membership typo

pkg/epinio/components/application/AppSource.vue
Fixes https://github.com/epinio/ui/issues/235
Blocked by https://github.com/rancher/dashboard/pull/8797
- To do a re-base once the blocker is merged.
=> [UI] Fix Application creation from manifest

shell/chart/istio.vue
Fixes #8862
Fixed banner alignment in the Istio installation page
###How to test
Go to Cluster > Cluster tool > install Istio > select Customize Helm options before install checkbox > click next button
=> Fixed banner alignment in istio installation page

pkg/epinio/components/application/AppSource.vue, pkg/epinio/detail/applications.vue, shell/components/form/GitPicker.vue
Fixes https://github.com/epinio/ui/issues/216
Applications -> `GitPicker`
=> Application source edit, fix form behavior

shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes Cloud provider should set none when the Harvester cloud provider is disabled
- https://github.com/harvester/harvester/issues/3657
=> HARVESTER: Cloud provider should set none when the Harvester cloud provider is disabled

shell/edit/provisioning.cattle.io.cluster/__tests__/rke2.test.ts, shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #8821
- Cleaned up existing RKE2 tests from default values to make them more readable
- Created test for validation of provided RKE2 clusters without machine pool 
- Ensured validation of machine pool is ignored for K3 clusters
=> Automation: Create tests to ensure presence of pool machines requirements on RKE2 cluster creation

.github/workflows/docusaurus.yaml, .github/workflows/storybook.yaml
This backports changes made to our publish docusaurus step so that it will only run when changes are made to the master branch.
=> Backport/2.7.4 harvester/chore/publish docusaurus

shell/assets/translations/en-us.yaml, shell/components/HarvesterServiceAddOnConfig.vue, shell/components/form/Labels.vue, shell/components/form/WorkloadPorts.vue, shell/config/labels-annotations.js, shell/config/types.js, shell/edit/service.vue, shell/edit/workload/mixins/workload.js, shell/models/workload.service.js, shell/store/type-map.js, shell/utils/selector.js
Cloud provider enhancement
- Remove health check
- Add annotations when create LB
- Harvester PR: https://github.com/harvester/dashboard/pull/309
- https://github.com/harvester/harvester/issues/1580
- https://github.com/harvester/harvester/issues/1458
- https://github.com/harvester/harvester/issues/1762
- https://github.com/harvester/harvester/issues/1834
=> HARVESTER: Cloud provider enhancement

package.json
Reverts rancher/dashboard#8913
=> Revert "Temporarily disable sorry cypress"

pkg/rancher-components/package.json
This bumps `@rancher/components` to v0.1.2 in preparation for publishing a new package.
=> Bump `@rancher/components` to v0.1.2

shell/pages/auth/setup.vue
Fixes #8852
Added BrandImage component in setup page to fix missing image
> Create a fresh cluster
> Enter the password on the creds page
=> Added BrandImage component in setup page

shell/core/types.ts
Found that these types were necessary for some of our docs and example projects
=> Updating the types for extensions

pkg/epinio/components/application/AppConfiguration.vue, pkg/epinio/models/configurations.js
Fixes https://github.com/epinio/ui/issues/219
We also fixed the binding of services and configurations of Application's upload from manifest, though the create & edit area need some regression tests
=> [UI] Fix configuration and services binding

pkg/epinio/components/application/AppSource.vue, pkg/epinio/models/applications.js, pkg/epinio/utils/application.ts
Fixes https://github.com/epinio/ui/issues/227
=> [UI] Export manifest as Yaml file

pkg/harvester-manager/l10n/en-us.yaml, pkg/harvester-manager/machine-config/harvester.vue, shell/assets/translations/en-us.yaml, shell/components/form/PodAffinity.vue
- https://github.com/harvester/harvester/issues/2317
=> HARVESTER: Implement pod affinity in harvester manager

shell/edit/provisioning.cattle.io.cluster/rke2.vue
Using the management/find method here will cause the value in the store to overwrite the value in the machine pool (because the value of `machinePool[*].config` has not been cloned at this point).
Fixes #
- https://github.com/harvester/harvester/issues/3786
=> fix object overwrite & rerender

.vscode/settings.json, package.json, shell/edit/__tests__/management.cattle.io.setting.test.ts, shell/edit/logging.banzaicloud.io.output/__tests__/logging.banzaicloud.io.output.test.ts, shell/edit/logging.banzaicloud.io.output/index.vue, shell/edit/logging.banzaicloud.io.output/providers/__tests__/loki.test.ts, shell/edit/logging.banzaicloud.io.output/providers/loki.vue
Fixes #8782
- Added test validation for URL Banzai cloud
- Verified presence of placeholder for Loki input
- Correct possible undefined objects ([CI error](https://github.com/rancher/dashboard/actions/runs/5191750659/jobs/9359985470#step:5:15771))
- Prevented spam in CI on unit tests warnings ([example CI with 15771 lines of logs](https://github.com/rancher/dashboard/actions/runs/5191820126/jobs/9360159910))
- Prevented issues with `replaceAll()` as support is limited (e.g. no Safari) and has been reported already in other cases ([CI error](https://github.com/rancher/dashboard/actions/runs/5191843930/jobs/9360209824#step:5:206))
=> Automation: Loki Outputs URL can accept invalid input

shell/package.json
- bump shell pkg version for a new release
=> bump shell pkg

cypress/e2e/po/components/labeled-input.po.ts, cypress/e2e/po/pages/explorer/workloads-jobs.po.ts, cypress/e2e/tests/pages/explorer/workloads/jobs.spec.ts
=> Automation: App breaks when creating a new namespace from a workload

shell/edit/__tests__/namespace.test.ts, shell/edit/namespace.vue
Fixes #8786
- Add test to ensure that resource limit configuration is inherited by the project
- Prevent errors in case of missing `annotations`
=> Automation: Namespace cannot inherit the Resource Limit default value from the project

shell/components/form/GitPicker.vue
Fixes https://github.com/epinio/ui/issues/239
=> [UI] Deletion of content in Username / Organization field should empty all previous content

cypress/e2e/blueprints/explorer/workload-pods.ts, cypress/e2e/po/components/sortable-table.po.ts, cypress/e2e/po/pages/explorer/workloads.po.ts, cypress/e2e/po/pages/page.po.ts, cypress/e2e/tests/pages/explorer/workloads/pods.spec.ts, cypress/e2e/tests/pages/explorer/workloads/workloads.spec.ts
Fixes #8802 
- Adds e2e tests for #8802 
- Fixes some tipo's
=> add e2e tests for 8802

pkg/harvester-manager/l10n/en-us.yaml, pkg/harvester-manager/machine-config/harvester.vue
1. Polish the translation of the placeholder
2. Remove `_key` for compatibility.
3. If users didn't edify anything, clusters should not be recreated.
- https://github.com/harvester/harvester/issues/2317
- https://github.com/harvester/harvester/issues/3820
=> HARVESTER: terraform compatible vm scheduling

shell/config/labels-annotations.js, shell/edit/service.vue, shell/models/workload.service.js
The front-end only needs to pass the cluster name, and the backend will take care of everything else.
- https://github.com/harvester/harvester/issues/1458
Fix IP pool selector issue
- Remove annotations `cloudprovider.harvesterhci.io/network` and `cloudprovider.harvesterhci.io/project`
~- Add annotation `cloudprovider.harvesterhci.io/cluster-name`~
=> HARVESTER: Update LB design

shell/components/HarvesterServiceAddOnConfig.vue, shell/components/form/WorkloadPorts.vue
Not support changing the IPAM mode of the harvester load as have the backend issue
- https://github.com/harvester/harvester/issues/1834#issuecomment-1589118612
Revert allowed edit IPAM code in PR https://github.com/rancher/dashboard/pull/8935
=> HARVESTER: Not support changing the ipam mode of the harvester load as have backend issue

shell/pages/c/_cluster/uiplugins/index.vue
Fixes #8712 
- Minor styling
before:
after:
=> 8712 - Fix plugin icons alignment

cypress.config.ts, cypress/e2e/po/pages/page.po.ts, cypress/e2e/po/side-bars/burger-side-menu.po.ts, cypress/e2e/po/side-bars/user-menu.po.ts, cypress/e2e/tests/pages/user_menu/account-api-keys.spec.ts, cypress/e2e/tests/pages/user_menu/logout.spec.ts, cypress/e2e/tests/pages/user_menu/preferences.spec.ts
- reduce compression rate
- only process failed specs
- address flaky tests that use the user avatar menu
=> Reduce impact of cypress recording

pkg/harvester-manager/config/harvester-manager.js, shell/assets/translations/en-us.yaml, shell/components/ClusterProviderIcon.vue, shell/components/LandingPagePreference.vue, shell/components/formatter/ClusterProvider.vue, shell/components/nav/Header.vue, shell/components/nav/TopLevelMenu.vue, shell/config/labels-annotations.js, shell/config/product/explorer.js, shell/edit/namespace.vue, shell/edit/token.vue, shell/layouts/default.vue, shell/list/catalog.cattle.io.clusterrepo.vue, shell/list/management.cattle.io.cluster.vue, shell/list/provisioning.cattle.io.cluster.vue, shell/list/service.vue, shell/middleware/authenticated.js, shell/models/management.cattle.io.cluster.js, shell/models/provisioning.cattle.io.cluster.js, shell/pages/c/_cluster/explorer/index.vue, shell/pages/diagnostic.vue, shell/pages/home.vue, shell/store/catalog.js, shell/store/features.js, shell/store/index.js, shell/store/type-map.js, shell/utils/cluster.js
- https://github.com/rancher/dashboard/issues/8800
change: 
1.  The 'Upgrade Rancher' button will be hidden in the 'Install App' page."
2.  In the 'Cluster Tools' page, hide all action buttons related to Harvester tools (e.g. Longhorn, Monitoring) 
3.   CRDs prefixed with [harvesterhci.io](http://harvesterhci.io/).* and [kubevirt.io](http://kubevirt.io/).* will preferably not be displayed since they are Harvester system-level resources.
4. Editing/upgrading/deleting Harvester managed system services, such as monitoring, logging, and Harvester, will be disabled since these are Harvester system components that should be managed only by Harvester upgrade only.  （Note: 
In order to prevent the user from operating the service related to harvester, we hide the resources belonging to the …
=> HARVESTER: add bare-metal container and mcm support

shell/pages/c/_cluster/uiplugins/index.vue
Fixes #9117 
- fix issue where extension versions appeared as duplicated
=> fix issue where extension versions appeared as duplicated

pkg/epinio/dialog/ExportAppDialog.vue, pkg/epinio/models/applications.js
Fixes https://github.com/epinio/ui/issues/250
Fiexs https://github.com/epinio/ui/issues/251
- Application export function is aligned to current `master` functionality (`GenericPrompt.vue`)
- The manifest file is removed from Chart & image export zip file.
=> Fix Application export

pkg/rancher-components/src/components/Form/TextArea/TextAreaAutoGrow.vue, shell/components/CruResource.vue, shell/components/__tests__/CruResource.test.ts, shell/components/form/KeyValue.vue, shell/components/form/__tests__/KeyValue.test.ts
Fixes #8817
Test a new line is added to the value.
=> Onenter newline textarea

pkg/epinio/detail/applications.vue, pkg/epinio/edit/applications.vue, pkg/epinio/l10n/en-us.yaml
Fixes https://github.com/epinio/ui/issues/197
=> Edit application from commit in App detail tab

shell/components/ExplorerMembers.vue
Fixes https://github.com/rancher/dashboard/issues/9159
- Moved this to a computed property
- Wait until we have users before counting on them to determine if isCurrentUser
=> Optimise locationa and way we determine cluster level scopes for project members page

shell/assets/translations/en-us.yaml
Fixes https://github.com/rancher/dashboard/issues/9158
=> Ensure users with only cluster roles get correct title

shell/components/form/GitPicker.vue
Fixes https://github.com/epinio/ui/issues/221
=> Add configurable debounce time in Git Picker form inputs

pkg/epinio/detail/applications.vue, shell/components/form/GitPicker.vue
Fixes https://github.com/epinio/ui/issues/245
This version handles applications create by CLI where only the `revision` is specified and `branch` name is missing.
The selected branch field is empty but the revision commit is visible.
=> Handle applications created by revision from CLI

cypress/e2e/po/components/ResourceList/resource-list-masthead.po.ts, cypress/e2e/po/pages/users-and-auth/users-and-auth.po.ts, cypress/e2e/tests/pages/users-and-auth/users-and-auth.spec.ts, shell/components/auth/RoleDetailEdit.vue
Fixes #8777 
- Adds e2e test
@richard-cox @scures had to redo the PR as the other one got bricked 🤷 -> https://github.com/rancher/dashboard/pull/9054
Basically it has the fixes suggested by @scures on https://github.com/rancher/dashboard/pull/9069 + the removal of the `wait` as per @richard-cox comment
=> add e2e tests for users/roles list view for standard user

shell/vue.config.js
- caused by yarn link to dashboard
- follows approach in https://github.com/rancher-sandbox/rancher-desktop/pull/4759
=> Fix issue where multiple instances of vue were imported

cypress/e2e/po/components/labeled-select.po.ts, cypress/e2e/po/components/select-principal.po.ts, cypress/e2e/po/pages/explorer/cluster-project-members.po.ts, cypress/e2e/po/pages/page.po.ts, cypress/e2e/po/side-bars/burger-side-menu.po.ts, cypress/e2e/po/side-bars/product-side-nav.po.ts, cypress/e2e/tests/pages/explorer/cluster-project-members.spec.ts, shell/components/form/Members/ClusterPermissionsEditor.vue
Fixes #8804 
- Adds e2e tests
**NOTE:** it's a spinoff of https://github.com/rancher/dashboard/pull/9097, which should be reviewed first
=> Automation: Cluster and Project Members shows "loading..." next to principle name

shell/components/IconOrSvg.vue, shell/utils/color.js
Fixes #9130 
- fix bug with custom svg icon in header action extension point where colors for icon were being grabbed incorrectly
- The problem lies with the component IconOrSvg, where the colors for a custom icon were being grabbed incorrectly (we weren't targeting the correct stylesheet + css rule) on a remote instance (couldn't be reproduced in a local env) causing problems in subsequent functions and crashing the code
Since this is only reproducible in a remote env, a few steps need to be taken in order to reproduce it:
- Access your remote env
- add the `ui-plugin-examples` repo https://github.com/rancher/ui-plugin-examples -> branch `main` in local cluster -> apps -> repositories
- install Extensions-Api-Demo
- go to cluster explorer --> local cluster
**Issue** 
- alternatively you …
=> Using addAction with an svg icon crashes the rancher ui

jest.config.js, shell/tsconfig.default.json, shell/tsconfig.json, tsconfig.json, tsconfig.test.json
Fixes #9149
- Separated TSconfig for tests
- Updated common configuration in tsconfig.default.json and importers
- Unit test run (checked below)
- Project run (checked below)
- Editor linting
=> Exclude Jest unit test from TSConfig

shell/assets/translations/en-us.yaml, shell/components/ExplorerMembers.vue, shell/components/form/Members/ClusterPermissionsEditor.vue, shell/components/form/Members/MembershipEditor.vue, shell/components/form/Members/ProjectMembershipEditor.vue, shell/config/product/explorer.js, shell/models/clusterroletemplatebinding.js, shell/models/management.cattle.io.clusterroletemplatebinding.js, shell/models/projectroletemplatebinding.js, shell/store/type-map.js
Fixes #9199
master version of https://github.com/rancher/dashboard/pull/9197
=> Revert display of Cluster and Projects page for users with project roles and no cluster roles

shell/pages/support/index.vue
issue #8657 
This reverts commit 0c51f6a1af567c512ccddf1cbabd5dec5e86c983, reversing changes made to f64da0e28a569ab90a1eccc1361bd0e9675aa1b8.
=> Revert "Merge pull request #9167 from momesgin/8657-dynamic-support-link

shell/pages/c/_cluster/uiplugins/index.vue
This reverts commit 91b64bdbfe951014221ad5b2dbe79c1cd9a39a1d.
#8712
=> Revert "8712 - fixed plugin icons alignment"

shell/components/form/PodAffinity.vue
Update match expressions manually.
- https://github.com/harvester/harvester/issues/2317#issuecomment-1607255344
https://github.com/harvester/harvester/issues/2317#issuecomment-1607255344
=> HARVESTER: fix podAffinity can not update match expressions

cypress/e2e/tests/pages/users-and-auth/users-and-auth.spec.ts, shell/assets/translations/en-us.yaml, shell/config/product/auth.js, shell/pages/c/_cluster/auth/roles/index.vue
Fixes #8576
Fixed title in Aurth > role template
=> Fix role template title

shell/pages/auth/login.vue
Fixes https://github.com/rancher/dashboard/issues/9252
=> Fix auth provider link position

shell/pages/docs/_doc.vue
Fixes #9211 
https://github.com/rancher/dashboard/assets/135728925/8864cef6-5aa8-47b2-9236-1c48e7f53b35
=> Additional check and optional chaining before accessing properties

shell/pages/auth/login.vue
Contributes to https://github.com/rancher/dashboard/issues/9252
=> Fix auth provider link position, clean code

shell/components/nav/Header.vue
Fixes #
- https://github.com/harvester/harvester/issues/4040
When loading the Harvester plugin, `mounted` methed will not re-execute, we need to load the plugin's header component when the route changes
=> HARVESTER: fix Visual Bug during the Harvester upgrade

shell/pages/c/_cluster/apps/charts/index.vue
`this.currentCluster?.status?.version` may be undefined
Fixes #
- https://github.com/harvester/harvester/issues/4199
=> Fix version rancher

shell/components/SortableTable/index.vue, shell/components/formatter/Image.vue, shell/components/formatter/PodImages.vue, shell/config/table-headers.js
Fixes rancher/dashboard#9235 
https://github.com/rancher/dashboard/assets/135728925/0f753843-8bda-4adb-8866-18478cb04ecd
=> Add wrap styling to image column

docusaurus/docs/code-base-works/machine-drivers.md
- supersedes https://github.com/rancher/dashboard/pull/9250
=> Remove link to code within repo from docs page

shell/detail/pod.vue
- fixes broken pod details page
**Screenshot of the problem**
=> fix broken pod details page

shell/core/plugins.js
https://github.com/harvester/harvester/issues/3895
1. Login Rancher and then go to downstream harvester cluster
2. Log out
3. Log in
4. Go to downstream harvester cluster
=> remove plugin accurately

shell/edit/namespace.vue
- https://github.com/rancher/dashboard/issues/9288
1. Go to Namespace create page.
2. Switch to `Pod Security Admission` tab, and check all.
3. Switch to `Labels & Annotations` tab, add a label.
4. Save.
5. Go to edit the Namespace just created.
6. Switch to `Pod Security Admission` tab, and uncheck all.
7. Switch to `Labels & Annotations` tab, remove the label we added.
8. Save.
9. Go to edit page, the configuration should be updated.
=> Re-render Labels component manually

.github/workflows/check-plugins.yaml
- fixes gating issue with node version (ex: https://github.com/rancher/dashboard/actions/runs/5609178000/jobs/10262526658?pr=9342)
=> fix gating issue with node version

shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fix failed to pass guest cluster name into Harvester cloud provider
- https://github.com/harvester/harvester/issues/4232
=> HARVESTER: Fix failed to pass guest cluster name into Harvester cloud provider

storybook/.storybook/preview.js, storybook/.storybook/store/codeMirror.js, storybook/package.json, storybook/stories/components/CodeMirror.stories.mdx
Fixes #9328
- Added component to the style guide: Yaml and Textarea
- Added vue-client package and setup as for component due SSR logic
- Extended CodeMirror loader
- Created namespaced store module for Code Mirror
=> Add YAML editor to Storybook

shell/components/AsyncButton.vue, shell/package.json, shell/scripts/typegen.sh, shell/utils/validators/formRules/index.ts
Fixes #9242
- beef up typegen script to cover needed definitions
- fix build errors when asyncbutton used in extensions
- fix build errors when using form rules
=> Add additional types for extensions, fix other typing errors

pkg/harvester-manager/config/harvester-manager.js, shell/components/auth/AzureWarning.vue, shell/config/product/manager.js, shell/edit/provisioning.cattle.io.cluster/index.vue, shell/layouts/default.vue, shell/list/group.principal.vue, shell/models/chart.js, shell/pages/c/_cluster/auth/group.principal/assign-edit.vue, shell/pages/c/_cluster/auth/roles/index.vue, shell/pages/home.vue, shell/plugins/steve/subscribe.js, shell/store/index.js, shell/store/store-types.js
When build harvester as a plugin and importing it into rancher, the plugin has problems loading.  
reason:  circular dependency
1. `shell/plugins/steve/subscribe.js`  imported  `shell/store/index.js`
https://github.com/rancher/dashboard/blob/f6b249127b47a61fcdc95cef1a500c8b8b60893f/shell/plugins/steve/subscribe.js#L36
2. `shell/store/index.js`  imported  `shell/steve`
https://github.com/rancher/dashboard/blob/f6b249127b47a61fcdc95cef1a500c8b8b60893f/shell/store/index.js#L15
3. `shell/steve` imported `shell/plugins/steve/subscribe.js`
https://github.com/rancher/dashboard/blob/f6b249127b47a61fcdc95cef1a500c8b8b60893f/shell/plugins/steve/index.js#L7
Fixes #
Steps to Reproduce： 
1.  clone branch https://github.com/wujun2016/dashboard/tree/plugin-error
2. build plugin：   `yarn build-pkg …
=> fix circular dependency

docusaurus/docs/extensions/api/common.md, docusaurus/docs/extensions/api/panels.md, shell/core/plugin-helpers.js
Fixes #9302 
**Preferably, to be reviewed after https://github.com/rancher/dashboard/pull/9385**
- Fixes broken `edit` and `config` modes where they were colliding with `detail`
- Add support for `create` mode
- create a new package `yarn create @rancher/pkg test`
- on the `index.ts` file for the newly created package, replace the code with the following:
```
import { importTypes } from '@rancher/auto-import';
import { IPlugin, PanelLocation } from '@shell/core/types';
// Init the package
export default function(plugin: IPlugin): void {
// Auto-import model, detail, edit from the folders
importTypes(plugin);
// Provide plugin metadata from package.json
plugin.metadata = require('./package.json');
// Load a product
// plugin.addProduct(require('./product'));
plugin.addPanel( …
```
=> Create mode missing from LocationConfig
