- components/SortableTable/actions.js
Reference #4899 
_Issue_
The event listeners on the `window` object are being fired in ssr, which is causing the `window is not defined` error.
_Fix_
Move event listeners into `mounted()` and `beforeDestroyed()` hooks.
> Move window event listeners out of ssr

- components/SortableTable/actions.js
- components/SortableTable/index.vue
- Fix bug where deselecting a row with the action drop down open would result in the drop down not opening again
- Show disabled buttons as such in action drop down
- Fix bug where flicking cursor between actions in action drop down would make whole drop down flicker
- Also react to changes to actions in actions list
> Fix and improve the bulk actions dropdown in list header

- assets/translations/en-us.yaml
- edit/provisioning.cattle.io.cluster/MachinePool.vue
This PR addresses https://github.com/rancher/dashboard/issues/4448 by adding a checkbox to the K3s/RKE2 cluster provisioning forms that allows the 'drain before delete' setting to be configured for RKE2 and K3s machine pools.
To test this PR, I went to the form for RK2 cluster provisioning and confirmed the checkbox was there and that it was modifying the appropriate field in YAML, which is `spec.rkeConfig.machinePools.drainBeforeDelete`. Jake confirmed that YAML value is right.
> Can configure 'drain before delete' for RKE2/K3s machine pools

- assets/translations/en-us.yaml
- assets/translations/zh-hans.yaml
issue: https://github.com/rancher/rancher/issues/34790
Call method `t(labelKey)`：https://github.com/rancher/dashboard/blob/24c58844c8fe2d0679af1048ed9734473f8d234b/store/type-map.js#L940
Unsupported format：
```
host: |-
{count, plural,
one { Host }
other { Hosts }
}
```
> Fix F5 VirtualServer translation bug

- assets/translations/en-us.yaml
- components/FixedBanner.vue
- components/form/BannerSettings.vue
- components/form/ColorInput.vue
- pages/c/_cluster/settings/brand.vue
Addresses #4719 
This PR adds support for configuring and showing the login banner as a dialog that needs to be acknowledged as an alternative to displaying it as a page banner on the login screen.
The configuration page has been updated to include a checkbox and text input - allowing the user to indicate that they want a modal display and for them to be able to set the text that should appear in the button that is shown:
On the login page this is presented as follows when enabled:
> Allow login consent banner to be displayed as a dialog

- components/form/ResourceQuota/NamespaceRow.vue
- utils/units.js
- #4804
- Annotation should not have space between value and unit
- I had a quick look around the usages of `formatSi` and most of them don't include the unit
> Ensure namespace resource quota annotation is set correctly

- assets/translations/en-us.yaml
- cloud-credential/linode.vue
- store/linode.js
- store/plugins.js
Reference #3599 
This adds support for Linode cloud credentials for rke2 clusters
_Note:_ Currently we do not have support for creating the clusters in Linode, that issue is tracked [here](https://github.com/rancher/dashboard/issues/3261).
**To Test**
- Go to Cluster Management => Cloud Credentials
- Add Linode Credentials
> Add support for Linode cloud credentials

- edit/provisioning.cattle.io.cluster/index.vue
This PR addresses https://github.com/rancher/dashboard/issues/4919 by removing the `experimental` tag from the button for Harvester cluster provisioning.
When the experimental tag was removed, a tech preview tag was the fallback, so I removed the code for adding the 'tech preview' tag on the Harvester button as well.
Note: Guangbo said the "External Harvester" part should not be removed. https://github.com/rancher/dashboard/pull/4910#issuecomment-1012662696
> Remove experimental/tech preview tag from Harvester cluster provisioning

- .github/workflows/pr-zube.yaml
- .github/workflows/scripts/pr.js
- .github/workflows/scripts/request.js
This PR adds a GitHub action.
This allows us to use the GH 'fixes' notation in PRs - which will link PRs <> Issues.
Currently, when using this notation, merging a PR will automatically close associated issues. For our workflow, this is not what we want - we want them to stay open but moved to the 'To Test' pipeline in Zube.
The GitHub action introduced by this PR will re-open linked issues and move then to the 'To Test' pipeline automatically.
When a PR is open, it will move any associated issues to the 'Review' pipeline.
It will also:
- Set the assignee to the author if the PR has no assignees
- Set the milestone to the milestone of the linked issues (if no milestone is set). If there are multiple issues associated with multiple milestones, it does nothing.
Note: The GitHub action uses …
> GitHub Issue automation for PRs

- assets/translations/en-us.yaml
- config/settings.js
- pages/account/index.vue
Addresses #4869
This PR adds the API Endpoint to the API Keys (for consistency with the of Ember UI).
The old UI used two URLs - one that was displayed and a 2nd that was copied to the clipboard when clicked. In most cases they would be the same - the display one had extra logic to use the API_HOST setting if set.
I think it makes more sense to only use one URL - the one shown should be the same a the one copied.
I have used the simpler logic that does not use the API_HOST setting - @vincent99 is this still used?
> Add API Endpoint to the API Keys page

- components/FixedBanner.vue
This PR fixes a bug where enabling the consent banner on the login screen hides the header and footer banners.
It also adds text ellipsis when the banner content overflows the horizontal space - addressing https://github.com/rancher/dashboard/issues/4868
> Fix bug with banners when consent banner enabled

- assets/translations/en-us.yaml
- assets/translations/zh-hans.yaml
- components/nav/Header.vue
Addresses Github issue: [#4736](https://github.com/rancher/dashboard/issues/4736)
Addresses Zube issue: [#4754](https://zube.io/rancher/dashboard-ui/c/4754)
Added shortcut to kubectl shell button + information on tooltip
> Add a keyboard shortcut to open the Kubectl shell

- pages/c/_cluster/apps/charts/install.vue
This PR addresses [#4548](https://github.com/rancher/dashboard/issues/4548) by making it so that the same global values used to create the rancher-monitoring chart are also used when creating the rancher-monitoring-crd chart.
1. On a downstream cluster, I went to install the monitoring application
2. I set `values.global.cattle.systemDefaultRegistry` to `docker.io`
3. Looked in network traffic, clicked install, and confirmed that a value is now included in the network request:
4. Confirmed that the chart installed successfully
> Pass global values when creating rancher-monitoring-crd

- assets/translations/en-us.yaml
- assets/translations/zh-hans.yaml
- components/nav/Header.vue
Addresses Github issue: [#4982](https://github.com/rancher/dashboard/issues/4982)
Addresses Zube issue: [#5004](https://zube.io/rancher/dashboard-ui/c/5004)
- Fixes issue with nav.shell being used as string and throwing error on console when no {key} is present
> Bug: Cannot select clusters in the Cluster Management page

- machine-config/vmwarevsphere.vue
- utils/computed.js
- loadAllDatacenterResources wasn't being called on edit when a datacenter was already selected in the config. This resolved that.
- keyValueStrings was failing when the path didn't exist.
rancher/dashboard#4901
> Resolving two vsphere loading issues

- components/ResourceList/Masthead.vue
Reference rancher/dashboard#4995
**Issue**
The `Create from Yaml` button in the Masthead component does not show on certain resources (tested with Network Policies) and any CRDs.
**Fix**
Switch which action the Masthead is using to determine if it should be shown.
With [this PR](https://github.com/rancher/dashboard/pull/4481) we changed the action to look for any `blocked-PUT` permissions on any given resource, but this should only be determined when _editing_ a config with yaml, not creating.
This change will not effect the original issue of disallowing a user from editing certain resources.
> Switch isYamlCreatable action for masthead component

- assets/translations/en-us.yaml
- components/dialog/GenericPrompt.vue
- components/dialog/ScaleMachineDownDialog.vue
- config/labels-annotations.js
- detail/provisioning.cattle.io.cluster.vue
- models/cluster.x-k8s.io.machine.js
- models/cluster.x-k8s.io.machinedeployment.js
- models/provisioning.cattle.io.cluster.js
- Adds the scale down action to an RKE2 machine
- Cater for case where at lease one machine with a role of Control Plane must exist
- rancher/dashboard#4446
- ~~This doesn't actually work yet (annotation might not be correct), seeking clarification on process in original issue~~ Annotation supplied in issue had typo, now fixed
> Scale down specific RKE2 machine

- assets/translations/en-us.yaml
- components/ActionDropdown.vue
- components/SortableTable/actions.js
- components/SortableTable/index.vue
- The row of bulk actions reacts to the selection of rows via the selection text to the right of the row
- Normally this is a small and consistent `x selected` text which is taken into account when working out the row width
- However some tables (workspaces) can have actions that are only applicable to certain rows
- In those cases on mouse over of an action the selected text changes to a much bigger `Available for {actionable} of the {total} selected`
- This is again taken into account for row width which creates a lot of flickering when the cursor moves over/out of an action
- To resolve this move the `x of y` text into a tooltip
- Also removed the source of flickering when moving the cursor between actions
#4873
> Move bulk action `x of y` to avoid extra flicky flicking

- machine-config/linode.vue
- store/linode.js
Reference rancher/dashboard#3261 
This adds the `machine-config` for creating rke2/k3s clusters with Linode as the provider.
**To Test**
- Add API token for Linode in the Cloud Providers section
- Create an rke2/k3s cluster using Linode
> Add support Linode rke2/k3s provisioning

- components/SortableTable/THead.vue
Addresses Github issue: [#4629](https://github.com/rancher/dashboard/issues/4629)
Addresses Zube issue: [#4647](https://zube.io/rancher/dashboard-ui/c/4647)
- Fixes vertical misalignment of table headers
**Result**
> Table column headers aren't vertically aligned

- components/Questions/index.vue
This PR addresses https://github.com/rancher/dashboard/issues/4706 by making it so that Javascript expressions in a legacy app's `Questions.yaml` will be evaluated in the same way in the dashboard as they were in Ember. This makes it so that if answers fields are conditionally rendered based on other answers, they will show and hide correctly.
The linked issue was caused because the dashboard uses the Jexl library to evaluate Javascript expressions and Jexl doesn't support hyphens. This makes sense as Javascript doesn't allow hyphens in variable names either. However, an exception needs be made in this case so that users migrating legacy apps won't have to do manual work to make the app's Questions form work properly.
The Ember UI didn't use Jexl as it had used its own custom-made …
> Use Ember's in-house JS expression evaluation logic for hyphenated variables

- components/DetailTop.vue
- components/ResourceDetail/Masthead.vue
- models/management.cattle.io.globalrole.js
- models/management.cattle.io.roletemplate.js
Addresses Github issue: [#4594](https://github.com/rancher/dashboard/issues/4594)
Addresses Zube issue: [#4612](https://zube.io/rancher/dashboard-ui/c/4612)
- Fix missing/empty fields being shown on the top part of the Global, Cluster and Project Role Detail page detail sections
- Add hifen to separate resourceSubtype from name for the title shown on the top part of the Global, Cluster and Project Role Detail page detail sections
**Before**:
**After**:
> Global, Cluster and Project Role Detail page detail sections show missing info

- config/product/explorer.js
Addresses Github issue: [#4985](https://github.com/rancher/dashboard/issues/4985)
Addresses Zube issue: [#5007](https://zube.io/rancher/dashboard-ui/c/5007)
- Move 'cluster members' config from 'rbac' tab to 'Cluster' tab
**Preview**
> Move `Cluster Members` list out of RBAC

- assets/translations/en-us.yaml
- assets/translations/zh-hans.yaml
- components/form/BannerSettings.vue
- components/form/ColorInput.vue
- config/product/settings.js
- pages/c/_cluster/settings/banners.vue
- pages/c/_cluster/settings/brand.vue
Addresses Github issue: [#4969](https://github.com/rancher/dashboard/issues/4969)
Addresses Zube issue: [#4991](https://zube.io/rancher/dashboard-ui/c/4991)
- Created a section for Banner config on the "Global Settings" area
- Removed any references of Banner config from Branding
- BannerSettings now displays each section by default
- Fixed BannerSettings to disable UI elements when checkbox in section is not selected
**Dark Mode**
**Light Mode**
@lvuch any comments/changes regarding the visual outcome?
> Global Setting: Separate Banners into its own side nav item

- yarn.lock
The commit in yarn.lock points to and old version of Rancher icons (due to updating an existing 2.0.0 version of the icons)
> Fix yarn.lock resolution of Rancher icons

- pages/c/_cluster/explorer/tools/index.vue
There is a minor sizing issue on the cluster tools page - the delete button is a different height to the install button:
> Fix minor issue with icon height on cluster tools page

- models/catalog.cattle.io.app.js
`.spec.values.global` is not present when an app wasn't installed through Rancher.
JS error:
```
fetch.client.js?2293:75 Error in fetch(): TypeError: Cannot read properties of undefined (reading 'clusterName')
at _callee4$ (catalog.cattle.io.app.js?9e85:244:17)
at tryCatch (runtime.js?96cf:45:15)
at Generator.invoke [as _invoke] (runtime.js?96cf:274:1)
at Generator.prototype.<computed> [as next] (runtime.js?96cf:97:1)
at asyncGeneratorStep (asyncToGenerator.js?1da1:3:1)
at _next (asyncToGenerator.js?1da1:25:1)
at eval (asyncToGenerator.js?1da1:32:1)
at new Promise (<anonymous>)
at CatalogApp.eval (asyncToGenerator.js?1da1:21:1)
at _callee$ (install.vue?8e63:107:1)
```
Addresses https://github.com/rancher/dashboard/issues/4959
> Fix JS error when upgrading app that was installed with the helm cli

- components/form/ArrayList.vue
- components/form/ArrayListGrouped.vue
- components/form/EnvVars.vue
- components/form/KeyValue.vue
- components/form/PodAffinity.vue
- components/form/ServiceNameSelect.vue
- types/form.ts
https://github.com/rancher/dashboard/issues/5035
Removed buttons for the following tabs of Demployment/Config viiew:
General
Labels & Annotations
Pod Scheduling
- `KeyValue.vue` 
- As the value `removeAllowed` is not computed nor adopted, it has been replaced by `isView`, which seems to be the reason of this leftover; prop has been removed accordingly
- `ArrayListGrouped.vue `
- `IsDisabled` computation seems not working or not integrated correctly, as the value returns `false` also in case of view mode; therefore it has been replaced with `mode`, while prop is kept to avoid issues
- `CanAdd` has been added to allow enforced cases, default value left to `true` to match existing cases
- ` mode `/`isView` logic has also been added to match other existing cases, as part of the issue …
> Hide buttons in Deployment/Config tabs when in view mode

- assets/translations/en-us.yaml
- assets/translations/zh-hans.yaml
- components/FleetRepos.vue
Addresses Github issue: [#4929](https://github.com/rancher/dashboard/issues/4929)
Addresses Zube issue: [#4949](https://zube.io/rancher/dashboard-ui/c/4949)
- add clusters count to git repo list 
- add warning icon and tooltip with message when cluster count is zero
**Preview**
> Fleet: Show clusters applicable to a git repo

- stories/Icons.stories.mdx
Storybook build was broken by change or icon font being brought in from the rancher/icons repository.
This PR fixes this by removing the reference to the old `selection.json` file that no longer exists - we don't include an index of icons in the Storybook for now - we reference back to the one generated from the rancher icons GitHub repository.
> Fix Storybook build

- components/nav/Header.vue
- nuxt.config.js
This introduces the ability to toggle certain UI elements based on the runtime config. Updates had to be made to the header in order to properly support toggling certain elements. For example, this is a rough outline of the structure for the header before the change:
Removing any given element would still reserve space in the header
After the change, all actions are grouped in an area that is named `rd-header-right`:
Removing elements from `rd-header-right` causes `top` to fill the remaining space and display remaining elements to the right-hand side of the screen
We shouldn't see any observable changes as a result of this PR without making use of the environment variable during development
```
❯ API=https://127.0.0.1:9443 ROUTER_BASE=/dashboard RANCHER_ENV=desktop yarn dev --spa
``` …
> Add support for toggle of UI elements based on runtime config

- components/Questions/index.vue
We were referencing source.chart.name within the questions component even when questions weren't being used for charts.
This change makes it so we only use the chart name if it's present. If it's not present there were already existing fallback mechanisms in place.
rancher/dashboard#5065
> Fixing questions for the generic machine config

- models/rbac.authorization.k8s.io.role.js
Addresses Github issue: [#4858](https://github.com/rancher/dashboard/issues/4858)
Addresses Zube issue: [#4878](https://zube.io/rancher/dashboard-ui/c/4878)
- Added getters and setters for `displayName` so that its binded to `metadata.name`
Notes:
1) The given input reads from the prop `displayName` rather than `name`, but if we changed the input model (file is `RoleDetailEdit.vue`) we would compromise other areas of the code that are working properly.
2) We could also change the validation rules for the element from `name` to`displayName` (check `rbac.authorization.k8s.io.role.js` custom validation rules), but that we be opposite of the server validation, which is using  the `name` prop.
3) Additionally checked the other models for the areas where  `RoleDetailEdit.vue` component is used …
> Adding `Role` via the UI always errors with `"Name" is required`, despite providing one

- mixins/harvester-vm/index.js
- pages/c/_cluster/explorer/tools/index.vue
- plugins/steve/resource-class.js
- Two are harvester related
- @WuJun2016 Could you take a quick look at these? I'm most concerned about the fix to `owners`. From what I can tell this works with `metadata.ownerReferences` which is only used in Harvester land. I couldn't get it to fire though with the Harvester i have running locally. Could you validate this and the other fix works?
- One is v1 legacy chart related
> Fix three of the prominent code typos

- .github/workflows/release-rancher-desktop.yml
This allows us to release dashboard artifacts that are meant to be embedded into Rancher Desktop. My current approach for achieving this goal is to trigger a build when a tag matches the given pattern `v**-desktop*` (e.g. v2.6.3-desktop). 
This build sets the variable `RANCHER_ENV=desktop`, creates archive of the build, generates a checksum, and uploads the artifacts to the release. Rancher Desktop will then be able to download these artifacts at build-time and bundle a customized version of Dashboard into the final product. 
Example release from my fork:
https://github.com/rak-phillip/dashboard/releases/tag/v2.6.3-desktop.11
supports rancher-sandbox/rancher-desktop#1192
> Add build for Rancher Desktop embed of dashboard

- pages/c/_cluster/explorer/index.vue
Fixes #4911 
This PR addresses the issue above - we now use a tabbed view and always show the events tab plus then show the alerts tab when v2 monitoring is installed.
> Don't hide cluster events when v2 monitoring is installed

- assets/translations/en-us.yaml
- assets/translations/zh-hans.yaml
- components/IconMessage.vue
- pages/c/_cluster/explorer/tools/index.vue
Addresses Github issue: [#4988](https://github.com/rancher/dashboard/issues/4988)
Addresses Zube issue: [#5010](https://zube.io/rancher/dashboard-ui/c/5010)
- fixes js error when deleting rancher repo and entering cluster tools 
- adds notification message when no cluster tools are available (when we delete rancher repo on a new cluster)
**Preview empty state**
Note:
1) Had to rename the class of the component `IconMessage` because there is an "automatic" style modifier for `icon-` which "forced" the font style for the whole component to be `icons`, overriding the body font even for the text part (for the whole component)
> JS Error on cluster tools page when Rancher repo was deleted

- models/cluster.x-k8s.io.machinedeployment.js
- plugins/steve/resource-class.js
#4990 - this is dependent on a recent-ish backend change: https://github.com/rancher/rancher/pull/36269
This PR updates the RKE2 scalePool logic to address an issue with long cluster names, outlined [here]. (https://github.com/rancher/rancher/issues/35452#issue-1050296190) 
I'm not sure getting the `type` from `kind` here is the best idea; it worked when I tested with Linode and DO, but I'm open to alternatives:
```
const machineTemplate = await this.$dispatch('find', { type: `rke-machine.cattle.io.${ kind }`, id: `${ namespace }/${ name }` });
```
> re-do machinedeployment to cluster machinepool mapping

- .github/workflows/scripts/pr.js
This PR fixes a bug with the GitHub action for Zube automation - the code to add the label for 'To Test' was not working as it was mixing an array of objects with a string label.
Added a couple of waits just to make sure there is no contention with Zube.
> Fix the GitHub automation for issue linking with Zube

- models/management.cattle.io.cluster.js
This fixes a bug that I've come across where undefined annotations caused the menu to stop working.
closes #5133 
> Assert that annotations is not undefined

- assets/translations/en-us.yaml
- components/form/LabeledInput.vue
- components/form/UnitInput.vue
- edit/provisioning.cattle.io.cluster/MachinePool.vue
- edit/provisioning.cattle.io.cluster/rke2.vue
This PR addresses https://github.com/rancher/dashboard/issues/4449 by adding a node auto-replace option for machine pools in the K3s/RKE2 cluster provisioning form.
Similar to the Ember UI, the input is taken from the user in minutes but sent to the back end in seconds.
Ember UI for reference:
To test this PR, I
1. I created a cluster with two node pools, pool1 and pool2. Pool1 had etcd, controlplane and worker roles. Pool2 had only the worker role. Pool2 had the auto-replace option set to one minute.
2. I confirmed that when the cluster was created, the new `unhealthyNodeTimeout` option was sent in the network request to create the cluster. The timeout is in Kubernetes duration format, so 10 minutes would be the string "10m".
3. Jacob said the fastest way to check that it works is to go …
> Add auto-replace option for K3s/RKE2 machine pools

- components/dialog/RotateCertificatesDialog.vue
- models/provisioning.cattle.io.cluster.js
This PR addresses https://github.com/rancher/dashboard/issues/4485 by adding an action to the context menu for Rancher provisioned RKE2 clusters.
1. I provisioned an RKE2 cluster in Rancher
2. I rotated the certs, trying both options - "rotate all service certificates" and "rotate an individual service"
3. In both cases the cluster went into provisioning state and came back successfully
Notes:
- The Steve API doesn't support actions, so we patch the cluster to update the cert configuration in `cluster.spec.rkeConfig.rotateCertificates`. See https://github.com/rancher/dashboard/issues/4485#issuecomment-1032932115
- For an example of similar logic for handling an action like this for an RKE2 cluster, see the component for restoring clusters from snapshot …
> Rotate certs action is available for RKE2 clusters

- edit/provisioning.cattle.io.cluster/rke2.vue
#5025 
This PR removes the SElinux checkbox input when provisioning the RKE2 node driver AWS cluster
> Remove SElinux input from UI

- components/SelectIconGrid.vue
- edit/provisioning.cattle.io.cluster/index.vue
- nuxt.config.js
Fixes #3124 
This PR fixes the issue where we do not show custom icons for custom node driver (RKE1). Instead, we currently show a default cluster icon.
With this PR, the icon is loaded in the same way as with Cluster Manager.
(To add a custom node driver for testing, see: https://github.com/nwmac/cluster-driver#example-rancher-cluster-icon
Example (see the 'test' driver):
Before this PR, this shows as:
> Show custom icons for custom RKE1 node drivers

- components/nav/WorkspaceSwitcher.vue
Addresses Github issue: [#4907](https://github.com/rancher/dashboard/issues/4907)
Addresses Zube issue: [#4927](https://zube.io/rancher/dashboard-ui/c/4927)
- Add condition to prevent duplication of requests to the server in regards to saving/updating the user preferences for the workspace
Issue was causing the duplication of requests to the server to update the user preferences and 90% of the times one of them was failing...
I believe this was happening because this:
https://github.com/rancher/dashboard/blob/master/components/nav/WorkspaceSwitcher.vue#L18
was doing the state change and then the setter would run again:
https://github.com/rancher/dashboard/blob/master/components/nav/WorkspaceSwitcher.vue#L17
Triggering it again... Why it wasn't stuck on a loop? Not entirely sure, but may …
> Error when switching between fleet-default and fleet-local workspaces in continuous delivery > clusters

- assets/translations/en-us.yaml
- machine-config/vmwarevsphere.vue
rancher/dashboard#4859
I validated the the os property gets saved by the backend.
> Adding an os field to vsphere

- assets/styles/global/_select.scss
- assets/translations/en-us.yaml
- components/form/FileImageSelector.vue
- components/nav/Type.vue
- config/nuxt-paths.js
- config/page-actions.js
- config/schema.js
- edit/ui.cattle.io.navlink.vue
- pages/home.vue
#5047
Added `edit` resource  page `ui.cattle.io.navlink` for link creation, based on provided documentations in the issue.
On create, value is initialized and set default as URL
- Custom target window `value.spec.target`  is mapped and set as follow:
- On page loaded, if not `_blank`, nor `_self` and has value, it's set as named and value injected in the input
- On radio change, option value is set except if named, then it's set from the input
- On input type, value is set
- Link type
- On page loaded is identified if is URL or Service, based on resource data, then passed to UI
- On link type change, respective unchecked values are removed
- Service paired values namespace/name
- On page loaded `value.spec.toService.namespace` and `value.spec.toService.name` are set as current service to …
> Add ability to create/edit nav link

- components/nav/Group.vue
#4368 - we were aborting the function call that selects the first nav item in a group when the group is expanded; that assumes that an expanded group is the active group, which is not necessarily true (see ticket repro steps).
> fix nav Group's groupSelected

- docs/developer/getting-started/development_environment.md
- As title, there was a suggestion for a second `cspell` but that doesn't turn up in vs code extension's marketplace
> Add info on VS Code speller checker extensions to the dev docs

- assets/translations/en-us.yaml
- components/ResourceTable.vue
- config/product/explorer.js
- models/pod.js
- store/type-map.js
Fixes #5073 
This PR adds the ability to group pods by node in the pods list view under workloads.
> Allow pods table to be grouped by node

- assets/translations/en-us.yaml
- edit/networking.k8s.io.networkpolicy/PolicyRule.vue
- edit/networking.k8s.io.networkpolicy/PolicyRulePort.vue
- edit/networking.k8s.io.networkpolicy/PolicyRuleTarget.vue
- edit/networking.k8s.io.networkpolicy/PolicyRules.vue
- edit/networking.k8s.io.networkpolicy/index.vue
- utils/validators/cidr.js
NetworkPolicies are one of the more complex Kubernetes resources. But they are also frequently used in enterprise contexts to restrict incoming and outgoing traffic of pods. A UI would make this much more accessible, especially for Kubernetes beginners.
Some screenshots:
Adresses: #4729
> Add UI for NetworkPolicies

- assets/translations/en-us.yaml
- config/product/explorer.js
- edit/persistentvolumeclaim.vue
The storage size, labels and annotations of a PVC can be edited in Kubernetes. If the PVC's StorageClass does not support Volume Expansion, an error will be shown.
Addresses https://github.com/rancher/dashboard/issues/3115
Create View has now a Labels & Annotations section, but otherwise did not change:
Detail View did not change:
Edit View allows editing the size and labels and annotations:
If the StorageClass does not support VolumeExpansion, an error is shown:
> Allow editing PVC

- assets/translations/en-us.yaml
- edit/fleet.cattle.io.gitrepo.vue
- added banner with appropriate copy to create git repo page when on local workspace
> add banner to create git repo page when on local workspace

- assets/translations/en-us.yaml
- config/labels-annotations.js
- list/catalog.cattle.io.app.vue
- machine-config/vmwarevsphere.vue
- mixins/chart.js
- models/catalog.cattle.io.app.js
- models/chart.js
- models/management.cattle.io.cluster.js
- pages/c/_cluster/apps/charts/chart.vue
- pages/c/_cluster/apps/charts/index.vue
- pages/c/_cluster/explorer/tools/index.vue
- store/catalog.js
#5056 
#5055 
#5057 
#5054 
#4983 
(Gary's in the process of separating out the arch requirements as we wont have backend for that in 2.6.4)
See #5137 for a detailed explanation - currently we're using the `'catalog.cattle.io/os'` annotation to infer if an app is windows or linux only; the windows team has added a `'catalog.cattle.io/permits-os'` annotation to more explicitly define which apps will work on windows, linux or mixed node clusters. Since we have greater confidence in an app's compatibility I made the filtering happen behind the scenes. Additionally there are warnings on app install/upgrade and list views.
The backend team is validating whether these new annotations are accurate, so it's enough on the UI side to spoof a windows/mixed cluster …
> Rke2 windows charts

- assets/translations/en-us.yaml
- components/form/WorkloadPorts.vue
- edit/workload/index.vue
- edit/workload/storage/index.vue
- models/workload.js
Fixes #4867
Users with the Project-level 'Manage Workloads' permission can't access services.
Updated UI for workloads to better check access to resource types (this fixes a few errors in the console log as well).
Dropdown allowing users to change the service type is disabled in this case, as the user can not create services.
> Bug fix for can't create service as a user with Manage Workloads permission

- components/AsyncButton.vue
- components/nav/WindowManager/ContainerLogs.vue
Fixes #5149
This PR moves the 'Show previous log' checkbox out of the cog menu, so that is is more obvious.
Additionally:
- Changes the layout of the buttons area to flex so that it sizes properly
- Added a dropdown arrow to the cog button so it is clearer that it is a popup menu
- Makes the Follow and Clear buttons responsive, so that they reduce to an icon when space is tight
- Gives more space to the status message so that controls don't jiggle when it changes from connected to disconnected
- Fixes a minor styling issue in the AsyncButton control where there is extra margin on the left of the text when there is no icon
Here's how it looks now:
When smaller:
> Move 'previous log' checkbox out of the cog menu

- assets/translations/en-us.yaml
- components/dialog/ScaleMachineDownDialog.vue
- models/cluster.x-k8s.io.machine.js
- Code previously preventing scaling down of only last control plane
- fixes #4446
- follows on from https://github.com/rancher/dashboard/pull/4968
> Prevent scaling down of last etcd machine

- detail/provisioning.cattle.io.cluster.vue
#4990 (comments) - reproing this requires clusters from multiple providers. Make a few clusters, do a hard refresh, and notice that only one provider's clusters will load machine templates in detail views. No need to scale pools to see this; the table group labels will be missing provider, location, and size info for the 'broken' provider types.
> load correct machine template type on provisioning cluster detail page

- assets/translations/en-us.yaml
- components/ContainerResourceLimit.vue
- edit/workload/index.vue
This addresses issue #5005 
To test this PR:
- Workloads > Jobs > Create
- Under Resources tab, a new input NVIDIA GPU Limit/Reservation has been added
- Add a positive integer number
- Inspect the yaml to see the new field
> NVIDIA GPU Limit/Reservation added to Workload form

- components/form/LabeledSelect.vue
- edit/fleet.cattle.io.gitrepo.vue
Issue #5198  - Change fleet add repository TLS certification options to a dropdown
1. Navigate to Continuous delivery > Git repos.
2. Click on `create` or `Add repository` on top right.
3. The option to select TLS certificate now should be dropdown. 
4. There should be no functional change. Behaviour of form creation is the same. Only difference is radio buttons are now a dropdown.
NB: Original issue #5198 shows additional UI changes to the form. Those changes are out of the scope from this PR.
https://user-images.githubusercontent.com/1387263/156330625-af01f40e-8a7a-47d0-9d85-066390704bb8.mov
> Change tls certificate options selection - #5198

- components/nav/Header.vue
- components/nav/TopLevelMenu.vue
Fixes a bug where the cluster name is restricted to the side nav width - width the addition of cluster badges this means the name is easily cropped, e.g.:
This PR changes the header to use flex layout which is a little cleaner.
If also adds a resize handler which ensures that the cluster name div is sized so that the header fits the width of the window, by setting an exact width in which the product info will then be fit.
> Fix bug where cluster name is cropped

- assets/styles/global/_select.scss
**Original issue:** #5215 
This reverts commit b26a88ea4093bf4df59028e257576bccc5ed06de.
Reference #5246 for explanation of reverting
> Revert "Set select always full height to match input container"

- components/Tabbed/Tab.vue
- components/Tabbed/index.vue
- components/fleet/FleetResources.vue
- components/form/ResourceTabs/index.vue
- detail/fleet.cattle.io.gitrepo.vue
Addresses Github issue: [#5218](https://github.com/rancher/dashboard/issues/5218)
Addresses Zube issue: [#5242](https://zube.io/rancher/dashboard-ui/c/5242)
- Adds notification icon to Conditions tab on git repo to alert for an error
- Fixes issue with duplicate keys for Resources table
**Preview**
> Fleet: Add notification icon to Conditions tab on git repo to alert for an error

- edit/provisioning.cattle.io.cluster/CustomCommand.vue
#5150 - previously we were verifying the management cluster came up before allowing windows node registration; per this ticket, that doesn't account for the case where a user has added an etcd/controlplane node but no linux worker.
> check for etcd, controlplane, worker nodes before allowing windows nodes

- assets/translations/en-us.yaml
- detail/fleet.cattle.io.gitrepo.vue
Addresses Github issue: [#1617](https://github.com/rancher/dashboard/issues/1617)
Addresses Zube issue: [#1620](https://zube.io/rancher/dashboard-ui/c/1620)
- Add Banner with info to be displayed instead of resources count when we don't have any clusters associated with the workspace/repo
- Remove unmapped resources count (by default - comes from another PR) such as `Info`, `Warning`, `Error`
Preview:
> When deploying to cluster group with no clusters, still counting resources

- models/chart.js
- The version name query param was the whole version object instead of just the name
- fixes #5248, #5249
> Ensure the correct version is set for the install chart query param

- edit/provisioning.cattle.io.cluster/index.vue
This PR addresses https://github.com/rancher/dashboard/issues/4852 and https://github.com/rancher/dashboard/issues/4919 by removing "Tech Preview" from the cluster provisioning page when RKE2/K3s is selected.
This PR is ready for review, but it should not be merged until the cluster provisioning work for v2.6.4 is complete.
Before:
After:
> Remove 'tech preview' tag from RKE2/K3s cluster provisioning buttons

- config/product/explorer.js
- models/event.js
- pages/c/_cluster/explorer/EventsTable.vue
- pages/c/_cluster/explorer/explorer-utils.js
- pages/c/_cluster/explorer/index.vue
- plugins/steve/mutations.js
The events table on the cluster dashboard has performance issues with large number of events.
This PR mitigates this by restricting the number of events we store to 500:
- Adds an optional limit to the options for a type
- Updates loadAll to restrict the resources to the limit when applicable
- Updates load to ensure that when a new resource is added, an old one is removed if this would take us over the limit
- Sets a limit of 500 on the event type
- Factors the events list into a separate component and makes the resource loading non-blocking with its own loading indicator
- Uses a normal data rather than live date on the events table
- Fixes bug where some events don't have `lastTimestamp` - and adds a fallback to `metadata.creationTimestamp`
> Address performance issues with cluster dashboard events table

- layouts/default.vue
Fixes #5053 
Fixes #5147 
This PR fixes the namespace mode so that we always show cluster-level resources regardless of the namespace selection. Changing the nav as the current behaviour has confused many people.
Note: For 2.6.4, we are leaving the small icons in which indicate if a resource is a cluster-level or namespaced resource, so there is still a visual indicator.
> Always show cluster resources in the side navigation

- edit/policies.kubewarden.io.clusteradmissionpolicy/ClusterAdmissionPolicy.vue
- edit/policies.kubewarden.io.clusteradmissionpolicy/index.vue
[Reference](https://github.com/kubewarden/ui/issues/15)
This fixes the issue of the config not being saved when editing an existing ClusterAdmissionPolicy
**Cause**
1. No action was being called when `Save` was pressed
2. The input fields would change the type from an array of strings to just one string, causing the spec to be incorrect
> Bug fix (Kubewarden): Save on editing cluster admission policy 

- components/SortableTable/THead.vue
This backports an enhancement that was made over on Rancher Desktop to make it more obvious that a column is sortable by changing the mouse cursor to a pointer instead of the I-beam. 
> Update cursor to pointer for sortable column headers

- components/SortableTable/THead.vue
- components/SortableTable/index.vue
- pages/c/_cluster/fleet/index.vue
Addresses Github issue: [#5299](https://github.com/rancher/dashboard/issues/5299)
Addresses Zube issue: [#5324](https://zube.io/rancher/dashboard-ui/c/5324)
- Adds icons to Fleet dashboard badges
- Fixes paddings of tables for first and last elements of each row
**PREVIEW**
> Fleet: add icons to fleet dashboard badges

- detail/provisioning.cattle.io.cluster.vue
This one should be pretty simple:
* create an rke2 cluster with multiple etcd nodes
* take a snapshot
* snapshot names should be a shorter version than the one that is currently in use
There's also an annotation, `etcdsnapshot.rke.io/snapshot-file-name` that produces the same value. `snapshotFile.name` was just easier to access..
closes #5260 
> Shorten snapshot name by using `snapshotFile.name`

- components/PromptRestore.vue
- detail/provisioning.cattle.io.cluster.vue
#5267
Snapshot list is not sorting correctly by age, due a cropped path. Set full path for sorting correctly based on existing util.
> Define correct key path while sorting snapshots list by age

- mixins/create-edit-view/impl.js
- models/cluster.x-k8s.io.machinedeployment.js
- plugins/steve/normalize.js
- When scaling a machine pool there's lots of status updates to the cluster
- This means hitting a 409 conflict error when trying to scale an already scaling pool is likely
- There already exists a way to check for actual conflicts and retrying the save, though this was only for the CreateEditView component
- Also fixed causing this to not to try the second save (`conflict` method is not async) 
- That process has now become generic and is used when scaling pools
- Also fix bug where scale errors weren't caught (errors returned via rejected promise weren't caught)
- fixes #5029
Edit, also fixes #5030
> Fix machine scale conflicts

- components/DetailText.vue
- components/form/KeyValue.vue
- edit/configmap.vue
Fixes #5311
This PR fixes this by allowing the config map edit/view config page to indicate which keys are binary.
After PR: (See issue above for before PR)
> Fix config map binary data bug

- assets/translations/en-us.yaml
- components/form/LabeledSelect.vue
- edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #5318 
This PR fixes the issue above - RKE2 is no longer in tech preview but K3s still is, so we need to indicate that to the user.
In the version dropdown, we now show a tech preview badge next to k3s:
When you select a k3s version we show a warning below the version drop down:
> Show that k3s is in tech preview

- plugins/steve/actions.js
- store/index.js
Fixes #5313 
Fixes #4967 
This PR fixes the issue reported in both the above issues - there is a rare race condition that leads to the fail-whale page being displayed:
Tracing through the code, the problem is that `middleware/authenticated.js` on line 265, we dispatch calls to load the management and cluster stores in parallel. The management store will load all schemas (see `store/index.js` line 538). The cluster store assumes that the schema for the management cluster is avaialable (see `store.js` line 677).
There is a race condition where if the schemas are not loaded, the call to load the cluster will fail and you'll get bumped to the fail-whale page.
This PR fixes this by adding a wait into the `loadCluster` code - we don't want to load the schemas in multiple places - we assume that …
> Fix for race condition loading management.cattle.io.cluster schema

- models/fleet.cattle.io.cluster.js
Renamed prompt menu from `Assign to...` into `Change worspace...`.
Path: `/c/<CLUSTER>/fleet/fleet.cattle.io.cluster`
> Rename Assign to into Change worspace for cluster prompt menu actions

- models/fleet.cattle.io.gitrepo.js
Issue #5326 - Continuous Delivery Dashboard | Incorrect Bundles count
- If 2 git repos have similar names filtering works incorrectly due to `` bundle.name.includes(`${ this.name }-`) `` accounting for substring. For example, if repo 1 has name `test` then another repo has `test1`, in the filtering `test1` will include `test1`
- It also breaks for instances where 2 different workspaces have same repo name
1. Create additional workspace
1. Navigate to Continuous Delivery > Advanced > Workspaces > create
2. Add a git repo to newly created workspace
1. Navigate to Continuous Delivery > Git Repos > Add repository
Name: test
Repository URL: https://github.com/rancher/fleet-examples.git
Path: /simple
Branch: master
3. Add a git repo to Local workspace
1. Navigate to Continuous Delivery > Git …
> Fix gitrepo model bundle getter filter - #5326

- components/Tabbed/index.vue
Addresses Github issue: [#5351](https://github.com/rancher/dashboard/issues/5351)
Addresses Zube issue: [#5376](https://zube.io/rancher/dashboard-ui/c/5376)
- remove underline from conditions tab icon on hover
> Fleet: Remove underline from icon in git repo details -> conditions tab

- edit/provisioning.cattle.io.cluster/rke2.vue
- store/plugins.js
- Only show cloud providers applicable to the type of cluster selected
- If a preferred cloud provider is configured for a cluster type only show the it, 'exteranal' and none/default
- If a preferred cloud provider is not configured show all options
- ~Shows 'default' instead of 'none' to cover case of the basic rancher provider~
- This will be covered in another issue/PR 
- Related #5300
- Fixes #5080
Examples
> Update - `(Default)` has been changed back to the original  `(None)`
> Update rke2 cloud provider selection

- assets/translations/en-us.yaml
Issue #5325 - Apps & Marketplace no charts view missing yaml.
1. Navigate to any cluster via Cluster explorer > Cluster name
2. Click on `charts` tab in Apps and Market Place
3. In the filter text box type in any string so that no charts are shown.
> Fix noCharts Yaml in apps & Market place - #5325

- components/PromptRestore.vue
This PR addresses #5264 by adding the snapshot creation time to the dropdown options.
To test this PR:
Create a cluster
Create a few snapshots
From Cluster Management, select 'Restore Snapshot' from the action menu
The PromptRestore modal should display with a dropdown list of snapshots which now include the creation date and time
> Snapshot creation age and time added to dropdown options

- edit/provisioning.cattle.io.cluster/index.vue
- edit/provisioning.cattle.io.cluster/rke2.vue
fixes #5359 
- Reverts commit to remove RKE2 tech preview
- Disables extra code that marked K3s as tech preview (since now covered by RKE2 tech preview badge)
> Revert rke2 tech preview

- components/nav/NamespaceFilter.vue
Fixes a minor issue where vertical scrollbar can appear:
> Fix minor namespace filter glitch

- assets/translations/en-us.yaml
- components/SelectIconGrid.vue
- mixins/chart.js
- pages/c/_cluster/apps/charts/chart.vue
- pages/c/_cluster/apps/charts/index.vue
- pages/c/_cluster/apps/charts/install.vue
- pages/c/_cluster/explorer/tools/index.vue
- store/catalog.js
#5137 
#4983 
This PR updates the os badges on charts to better distinguish between charts that deploy on windows nodes, and charts that just wont break if there are windows nodes present in the cluster (they have taints to avoid scheduling on those nodes). It also applies these badges to the Cluster Tools page. 
In this PR:
- OS badges are now applied to non-Rancher charts as well
- all charts deploy on Linux so there are no Linux badges anymore, instead there is a user-dismissable warning in the app marketplace, chart overview, chart install page, and cluster tools page if legacy tools are not enabled ('legacy' feature flag)
- charts with the `deploys-on=linux,windows` have a badge indicating they deploy on Windows - currently this is only Logging and Monitoring
- charts without a …
> update charts os badges, remove filtering

- assets/translations/en-us.yaml
- edit/provisioning.cattle.io.cluster/rke2.vue
This PR addresses https://github.com/rancher/dashboard/issues/5294 by making it so that the following values for networking can't change after a K3s/RKE2 cluster is created:
In the basics tab:
- Cloud provider
- Container network
In the networking tab:
- Cluster CIDR
- Service CIDR
- Cluster DNS
- Cluster Domain
Note: NodePort Service Port Range should not be disabled because it's enabled for RKE1 clusters.
To test this PR, I provisioned an RKE2 cluster and confirmed that the above fields were disabled in the form. I also confirmed that when you create a new K3s/RKE2 cluster, the fields are not disabled.
> Networking options for K3s/RKE2 clusters can't change after cluster is created

- components/Banner.vue
Fixes: https://github.com/rancher/dashboard/issues/5213
This PR will fixes it by looking if the `label` objects includes a `message` propriety, if so it will stringify and display the Error message.
Edit any Pod configuration vía YAML and change any boolean value to something invalid like falsea , this will return a 400 Error and you'll be able to preview it.
> Issue with displaying Errors messages

- components/auth/RoleDetailEdit.vue
- components/form/RadioButton.vue
- models/management.cattle.io.globalrole.js
- models/management.cattle.io.globalrolebinding.js
- models/management.cattle.io.roletemplate.js
- plugins/steve/steve-class.js
#4992
Allow users not  to select `New User Default`.
Interested areas:
- `models/management.cattle.io.globalrole.js`
- `models/management.cattle.io.globalrolebinding.js`
- `models/management.cattle.io.roletemplate.js`
https://user-images.githubusercontent.com/5009481/157936423-100e20c1-04a2-4338-8192-585e0ebc9e43.mp4
On resource update and deletion an errors about model `set` missing prevented to modify the value and on list reload it displayed `name` instead of `displayName`. Obviously this also prevented to set the description.
For this purpose the `SteveModel` has been extended to support `set` for description.
https://user-images.githubusercontent.com/5009481/157936997-7202db33-a2ed-4546-8436-cc9d1d39a44d.mp4
Radio buttons now can be clicked from the label as in native HTML 1.0 and …
> New User Default Role Toggle is Broken in Rancher UI

- edit/provisioning.cattle.io.cluster/index.vue
Show 'Tech Preview' and not 'Experimental' for Harvester cluster creation on RKE2 - this makes it consistent with the other RKE2 options.
> Harvester: Rename experimental to tech preview

- edit/provisioning.cattle.io.cluster/MachinePool.vue
- machine-config/harvester.vue
Issue #5373 - Harvester cluster create form error breaks UI
1. Cluster management > Create Cluster 
2. Ensure RKE2 switch is turned on
3. Click on Harvester
4. Try to error the form in Machine pool (e.g. if there is no harvester instance/Images set up you can click on images dropdown)
> Fix harvester cluster create UI visibility when error.

- assets/translations/en-us.yaml
#5296
Updated link to https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/rke-clusters/behavior-differences-between-rke1-and-rke2/ as mentioned in latest comments.
> Uppdate RKE2 cluster banner with new url

- assets/translations/en-us.yaml
- edit/networking.k8s.io.networkpolicy/PolicyRuleTarget.vue
- Split out CIDR and exception error message from a single list to two
- Show `<blank>` in the error message for an empty rule
- This process probably needs a rework, but should be done after https://github.com/rancher/dashboard/pull/4999
- fixes blocking issue from https://github.com/rancher/dashboard/issues/4729#issuecomment-1069589044
> Split Network Policy rule CIDR error message out

- edit/provisioning.cattle.io.cluster/index.vue
- models/management.cattle.io.cluster.js
This PR addresses https://github.com/rancher/dashboard/issues/5395 and https://github.com/rancher/dashboard/issues/5032 by making it so that if you have a cluster that was created from an RKE template, then you go to Edit Config, the Rancher UI now passes the RKE template version into the iFramed Ember page that contains the form. The Ember UI requires the RKE template version to render the form properly.
To test this PR I used Anupama's setup and did this:
1. Using Anupama's setup, logged in as an admin
2. Created an RKE template with no overrides allowed
3. Created another RKE template with a few overrides allowed
4. Added a cluster owner to the new cluster templates so that the cluster owner can use them
5. Logged in as a cluster owner
6. Created two RKE1 clusters, one for each …
> Pass correct props into Ember when editing RKE template clusters

- edit/workload/index.vue
Related to issue #5005 and expands on PR [5237](https://github.com/rancher/dashboard/pull/5237)
This PR adds logic to duplicate `resources.limits.'nvidia.com/gpu'` value to `requests` as well. 
Though setting requests is optional, we are doing so to mirror the existing behavior of the ember ui.
eg:
```
resources:
limits:
nvidia.com/gpu: 1
requests:
nvidia.com/gpu: 1
```
> NVIDIA GPU Limit/Reservation updates limits as well as requests 

- edit/provisioning.cattle.io.cluster/index.vue
This is a stopgap solution for https://github.com/rancher/dashboard/issues/5442
The better solution would be to refactor the `provisioner` computed property so that it doesn't return the wrong type of cluster for cluster owners. This is a workaround in the interest of time. For now, I saw that the cluster model already had an `isRke2` getter that worked for cluster owners, so I just used that instead of the existing method, which had a dependency on the broken `provisioner`.
1. As an admin, I created an RKE2 cluster and a K3s cluster
2. Created a standard user
3. Added the user to each cluster as a cluster owner
4. Logged in as the standard user
5. For each cluster, went to the cluster in Cluster Manager, went to Edit Config and confirmed that the form rendered correctly
> `isRke2` computed property works for cluster owners

- edit/provisioning.cattle.io.cluster/rke2.vue
fixes #5466 - disable s3 backup configuration, which was disabled [here](https://github.com/rancher/dashboard/pull/3993/commits/cd95382289c954dd6f6750aedbc3de9095169460) and re-enabled [here](https://github.com/rancher/dashboard/pull/5196/commits/437286dd1a91ab870e2c35a973895ba3282d29b4)
> re-disable s3 backup

- edit/provisioning.cattle.io.cluster/MachinePool.vue
- edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #5452 - the UI is currently setting `os` on the machine-config but it also needs to set `machineOS` in the rkeConfig.machinePool pool config. These values always need to match.
https://user-images.githubusercontent.com/42977925/159586806-b07e863c-27d2-4035-ba2a-a7e76b5e4ee6.mov
> set machineOS in rkeConfig to match machine-config os

- edit/workload/index.vue
Fixes #5479 
The NVIDIA GPU changes did not take into account workloads where the containers property is undefined.
> Fix for cronjobs can not be created

- assets/styles/base/_helpers.scss
- assets/styles/base/_variables.scss
- assets/styles/global/_labeled-input.scss
- components/CruResource.vue
- edit/autoscaling.horizontalpodautoscaler/index.vue
- edit/cloudcredential.vue
- edit/secret/index.vue
- edit/workload/index.vue
- layouts/default.vue
- models/fleet.cattle.io.cluster.js
#2512
While editing content, the buttons are always hidden at the bottom, while it is convenient to display them always.
- All the `CruResource` components containers have been filled, so the footer will be always pushed to the bottom
- Set `.labeled-input` class z-index to 0 preventing labels to hover other elements
- `.filled-height` utility class has been created to fill vertically the container, in case of empty pages or not overflowing
- Spacing variables have been added to be reuse for consistency in the whole project
- `fleet.cattle.io.cluster.js` action menu has been corrected while reviewing another issue, by removing ellipsis
Any edit view where we want to keep the buttons sticky to the bottom.
Since our layout provides some padding, it has been mandatory to use negative margin …
> Make CRU footer actions stick to the bottom

- components/form/PodAffinity.vue
- edit/workload/index.vue
- utils/__tests__/array.test.ts
- utils/array.ts
When configuring a pod affinity on a workload, you have to enter a topologyKey. This can be any node label key. For more details see https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity.
To make the configuration easier, this PR changes the input field to a select which offers all existing node label keys, with the option to also add keys that are not present as labels yet.
> Add auto complete for affinity topology keys

- docs/developer/stress-test.md
- nuxt.config.js
- plugins/steve/mutations.js
- plugins/steve/performanceTesting.js
This PR adds a simple mechanism for simulating large numbers of resources to help diagnose performance issues in the browser.
The code is currently commented out in `mutations.js` and is intended to be used in development only.
A new `performanceTesting.js` file allows a developer to configure different scales for resources - this is used by the `loadAll` function in the store to scale up from the actual number of resources to the desired.
For any resource type, you can configure how many you'd like to simulate - when loadAll is called, we will use the existing resources of the given type, duplicating each in turn to get to the desired count.
The age for each resource is reset to now (this helps testing live table columns) and you can also configure whether the state for a given resource …
> Add simple mechanism to simulate large numbers of resources

- assets/translations/en-us.yaml
- pages/home.vue
- store/prefs.js
This PR replaces the box for changing landing page prefs on the home page with one that directs the user to the preferences page.
Replaces this:
with this:
The main reason for doing this is to simplify the page and also with the updates to select boxes, the select box will be grey as it is not enabled by default, and this draws the user eye to the box, which we don't want.
> Simplify box on home page that allows user to change landing location

- utils/crypto/index.js
Fixes #5026 
In both the detail view for secrets and the model, we use the base64decode utility - we assume that for secrets like basic auth, that a username and password key are present - if they are not, we pass undefined to the utility which errors.
This PR just ensures that the base64decode function handles undefined correctly.
> Fix base64 decode when string is undefined

- edit/provisioning.cattle.io.cluster/index.vue
- models/management.cattle.io.cluster.js
This PR addresses the following issues:
- https://github.com/rancher/dashboard/issues/5442
- https://github.com/rancher/dashboard/issues/5395
- https://github.com/rancher/dashboard/issues/5455
In my previous PR, I changed the emberLink to a computed property without realizing that that could introduce errors into all the create/edit cluster pages. That was a necessary change to recompute the ember link for clusters created from different RKE template versions. But since the value was being recomputed, the logic for how the link was generated also needed to be revisited.
Previously, for K3s/RKE2 clusters provisioned in Rancher, the "selected" value used in the `emberLink` creation was wrong, pointing to an RKE1/create form instead of an RKE2/edit form:
```json
{
"id":"digitalocean", …
```
> Corrections to the logic for generating an emberLink

- assets/translations/en-us.yaml
- config/product/settings.js
This PR completes the updates of a couple of renames - some of these are done in other styling PRs that are being reapplied to the codebase and split up - this PR covers just the name changes:
Advanced Settings -> Settings
Apps & Marketplace -> Apps
The weight of the settings type is bumped up to ensure it stays first (the rename moves it alphabetically down in the sort order)
> Minor text renames

- assets/translations/en-us.yaml
- components/ResourceTable.vue
- pages/c/_cluster/_product/projectsnamespaces.vue
- When there are no namespaces that are not in a project add a fake namespace that will cause the group to show
- Ensure that when the last namespace in the `Not in a Project` group is removed the list updates
- Note - Users need to be in the 'group' view to see the `Not in a Project` group
- Note - Users can still click on any project's `Create Namespace` button and change the project to `(None)`
- Fixes #5322
> Always show the 'Not in a Project' group in the Project/Namespace list

- assets/styles/base/_mixins.scss
This PR beings in the relevant part from https://github.com/rancher/dashboard/pull/5376/files now that other changes to the controls has been merged.
This is a minor change to the input boxes to show the label in the error color when an error is present, e.g.
> Update error style of input box

- .github/workflows/storybook.yaml
Fixes a typo in the name - doesn't cause any issue in practice, since this is an arbitrary name, but it annoys the vscode spell checker.
> Fix storybook github action job name typo

- chart/monitoring/index.vue
- pages/c/_cluster/apps/charts/install.vue
fixes #5490, #5491, and #5492 
Clarifications from Arvind via slack:
#5492 -  `rkeEtd.enabled` should be set `false` for any cluster that is not rke1
#5490 - `rkeIngress.namespace` does not need to be modified for rke2 clusters.
Testing #5491 is difficult without access to the fremont dc vpn: I've made a cluster with one Windows node and verified that monitoring, and its CRDs, installs with `global.cattle.windows.enabled=true`, and I can screenshare on Teams if necessary
> [master]fix monitoring chart defaults for rke2/windows

- assets/styles/global/_button.scss
This PR brings in the button style changes from this PR: https://github.com/rancher/dashboard/pull/5360/files
Fixes:
- Tertiary button height (was 42px where others are 40px)
- Secondary hover and focus style
- Tertiary hover and focus style
Note: Due to use of !important elsewhere, I've had to use that in this PR as well - generally should be discouraged.
Tertiary height and secondary hover fixes:
Secondary focus:
Tertiary focus:
> Fix secondary and tertiary buttons colors

- components/InfoBox.vue
This PR brings out the changes to InfoBox from PR: https://github.com/rancher/dashboard/issues/5520
The other changes in that PR are already in due to the input and select control styling PR.
I made a slight tweak, but now looks like this:
> Minor styling improvements to info box

- components/SortableTable/filtering.js
We construct a RegExp string via string literal interpolation, then pass it to the RegExp constructor.  This means we need an extra level of backslash escaping to ensure the constructor gets escapes correctly.
> Fix SortableTable filtering regexp for IPs.

- components/SortableTable/index.vue
#5533 
This fixes the expandable sub-row chevron not changing direction when clicked.
https://user-images.githubusercontent.com/40806497/160457547-ae53a277-9d27-4e13-81ab-b5a0c38fccee.mp4
---
There was an existing method that would determine if the row was expanded (`isExpanded`), this method wasn't being used.
> Fix chevron direction on subrow expand

- components/nav/WindowManager/index.vue
This PR addresses #5209 
The test this pr 
- Navigate to a cluster
- Open the shell
- Click on the resize icon
- Shell window should minimize to the bottom of the window
Previous incorrect functionality closed the window
> Cluster shell resize icon click correctly minimizes window instead of closing it

- components/Banner.vue
- components/CruResource.vue
Fixes #5515
Correct issue with the CRU form errors hidden below the action footer.
Editor view forms errors are now stuck to the top and can be dismissed.
Extended `Banner` component capabilities, allowing to stack.
Since it seems like our current configuration does not allow to tests components which use Typescript, this is postponed to another time.
Any editor and YAML editor, e.g. deployments `/c/local/explorer/apps.deployment/create#general`.
Not aware of any collateral side effect.
> Error messages appear below form buttons

- edit/management.cattle.io.project.vue
- models/management.cattle.io.project.js
Addresses Github issue: [#5000](https://github.com/rancher/dashboard/issues/5000)
Addresses Zube issue: [#5022](https://zube.io/rancher/dashboard-ui/c/5022)
- fix issue where clearing up `resourceQuota` props was corrupting the model and creating a blocking error on the interface that prevented the creation of a namespace
> Can't create a new project after not specifying Namespace Default Limit once: error never clears when a value is provided

- components/CruResource.vue
Fixes #5515
With PR https://github.com/rancher/dashboard/pull/5554 the banner errors dismissal causes the app to break. This is aimed to prevent that issue
Changed errors list manipulation with error list emission.
Prop was erroneously modified and caused errors.
As in original ticket. 
As in original ticket.
> Allow to close error banners within resource edit without break

- .drone.yml
- docs/developer/fossa.md
By default, this plugin will run the analyze command per the generic CI documentation for FOSSA.
> Implement drone-plugin-fossa

- components/ResourceSummary.vue
- pages/c/_cluster/explorer/index.vue
Issue #5331 - Total Resources count is wrong 
- Currently list shows only specific resource count list - `["namespace", "networking.k8s.io.ingress", "persistentvolume", "apps.deployment", "apps.statefulset", "batch.job", "apps.daemonset", "service"]`
https://github.com/rancher/dashboard/blob/v2.6.3/pages/c/_cluster/explorer/index.vue#L43
- Instead retrieve all counts associated with the cluster `this.$store.getters[`cluster/all`](COUNT)`. 
- Filter that list by ignored resources types defined here by `ignoreType`
https://github.com/rancher/dashboard/blob/master/config/product/explorer.js#L95-L100
https://github.com/rancher/dashboard/blob/master/config/product/explorer.js#L292-L304
- Following getter `isIgnored` returns a boolean if resource is ignored …
> wrong cluster resources count #5331

- detail/node.vue
Addresses Github issue: [#5408](https://github.com/rancher/dashboard/issues/5408)
Addresses Zube issue: [#5434](https://zube.io/rancher/dashboard-ui/c/5434)
- add fallback for when node image name is not defined
> node details fail if there is an image without a name

- assets/translations/en-us.yaml
Fixes #4962
We show the `k8s.cni.cncf.io.NetworkAttachmentDefintiion` resource as 'Networks' - this PR changes the label we use to the full resource name to avoid confusion.
> Use correct name for Network Attachment Definition Resource

- pages/account/index.vue
This PR brings in the small change from https://github.com/rancher/dashboard/pull/5360/files
This switches h4 to h2 - this is a minor accessibility issue
> Account and Api keys heading levels

- components/SortableTable/index.vue
- components/SortableTable/selection.js
This PR reduces the number of mouse enter/leave handlers in the SortableTable.
Currently we add them to every row - their purpose is to ensure that when there is a sub-row, hovering the row/sub-row highlights both the row and its sub-row.
The highlighting of a sub-row for a row when a users hovers on the row is handled by css via the + operator - so we don't actually need to add mouse handlers to the rows for this behaviour.
This PR ensures we only add mouse enter/leave handlers for sub-rows - this needs to highlight the row above, which can't be done in css.
The handlers are moved to the Vue template rather than using jQuery.
> SortableTable Performance: Optimise row mouse over/leave handlers

- components/FixedBanner.vue
This pr addresses #5333 by removing the css which previously hid text overflow. The full text will now display regardless of banner height.
> Disable consent banner text overflow wrap

- assets/translations/en-us.yaml
- components/form/BannerSettings.vue
- components/form/NotificationSettings.vue
- pages/auth/login.vue
- pages/c/_cluster/settings/banners.vue
Fixes #5401 - Add support for Custom Login Failed Message 
1. Updated the `pages/c/_cluster/settings/banners.vue` section to have extra 2 fields to disable / enable show custom login error message.
2. Created `components/form/NotificationSettings.vue` which include checkbox and input field.
3. Original error message still shown 
4. The `loginError` field is added to `ui-banners` field in the settings and new settings are saved in there.
1. Navigate to Global settings > Brands > Scroll to bottom
5. Select the checkbox to show the message and type in the message in the text box below
6. Logout or open an incognito tag. Type in wrong user/password
1. it should show the error message
7. Un check the checkbox > apply 
1. Refresh the login page and try again. 
2. It should not display the …
> Custom login error messages - #5427

- edit/provisioning.cattle.io.cluster/rke2.vue
Addresses Github issue: [#5112](https://github.com/rancher/dashboard/issues/5112)
Addresses Zube issue: [#5136](https://zube.io/rancher/dashboard-ui/c/5136)
- change rke2 upgradeStrategy to 1 concurrent `controlplane` and `worker`
> Default upgrade strategy for Control plane is should be 1 when provisioning RKE2 clusters

- components/CopyCode.vue
- detail/provisioning.cattle.io.cluster.vue
- edit/provisioning.cattle.io.cluster/CustomCommand.vue
- pages/c/_cluster/apps/charts/index.vue
- store/catalog.js
Fixes #5507 Fixes #5530
This PR hides the wins-upgrader chart for rke2 clusters and adds a warning about updating apps when adding a windows node to a custom rke2 cluster. The original ask in 5530 was to put a warning on the chart overview page, but determining if a given app was installed before or after adding a windows node requires more permissions than a user with access to apps and marketplace necessarily has so the warning is on the provisioning screen instead.
> warn on adding windows node to cutom cluster

- config/labels-annotations.js
- models/catalog.cattle.io.app.js
This prepares for a new annotation that will be added to managed charts in k3s. We'll keep the check for `FLEET.BUNDLE_ID` because new annotation is expected to come at a later date and we don't want to change existing behavior.
Fixes #4442 
See #4621 for previous attempt and more discussion
The new `catalog.cattle.io/managed` annotation will be added to k3s at a later date. Existing behavior should be unchanged for now.
If you go into `Installed Apps` in `Apps and Marketplace`, the upgrade options should be unchanged.
`Installed Apps` in `Apps and Marketplace`
> Add annotation to stop upgrades for managed charts

- assets/translations/en-us.yaml
- components/ResourceDetail/Masthead.vue
- config/table-headers.js
- detail/workload/index.vue
- models/pod.js
- models/workload.js
This PR addresses this issue https://github.com/rancher/dashboard/issues/5086 by adding the Pod restart count to the workload detail page.
In a list of Pods, the restart count is added as another column:
At the top of the workload detail page, the restart count is a sum of the restarts of all the Pods in the workload:
Note: The restart count measures failures of the Pod as a health check. So it won't be incremented if you do a "restart" with kubectl, because that is terminating Pods and creating new ones. For testing, we want to count restarts of the same Pod, which are only caused by failures.
To increment the restarts of a Pod for testing, I went to cluster explorer, went to an example Deployment and caused destruction:
1. I went to one of the Pods in the Deployment and went to three …
> Add Pod restart count to workload detail page

- nuxt.config.js
Fixes #5589
As in issue description.
Nuxt/Webpack configuration is now allowing to debug code.
`yarn dev` using the 2 different source map values:
```bash
✔ Client
Compiled successfully in 28.07s
✔ Server
Compiled successfully in 14.86s
```
```bash
✔ Client
Compiled successfully in 16.86s
✔ Server
Compiled successfully in 23.75s
```
```bash
✔ Client
Compiled successfully in 12.90s
✔ Server
Compiled successfully in 16.61s
```
```bash
✔ Client
Compiled successfully in 18.18s
✔ Server
Compiled successfully in 10.67s
```
None.
None.
https://user-images.githubusercontent.com/5009481/162192132-305f831b-d022-4375-b20d-759acef370e3.mp4
> Enable source map in Nuxt/Webpack configuration for debugging

- components/form/PlusMinus.vue
- detail/workload/index.vue
Addresses https://github.com/rancher/dashboard/issues/5114
New `Scale` buttons:
1. I created a Deployment of `nginx:latest` in the default namespace.
2. I went to the Deployment detail page and scaled it up and down with the plus and minus buttons. The workload state changed and the buttons were disabled while transitioning.
3. I temporarily hardcoded an error just to make sure an error message shows up properly when needed (see screenshot below).
Example of how an error is displayed:
> Can scale workload from workload detail page

- config/table-headers.js
Fixes #5165
This PR fixes the above issue - the RAM, CPU and PODS columns had the wrong value for the sort column, so the sorting was nor working correctly.
To Test: With a cluster with multiple nodes, verify that on the nodes table for the cluster that you can sort by CPU, Memory and Pods in the table
> Fix node table column sorting

- edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #5130 
This PR ensures that the `mode` property is set on the control for the private registry authentication select dropdown so that in view config mode, this control is not editable.
> Fix issue where private registry auth can be changed in view mode

- assets/styles/global/_button.scss
- assets/translations/en-us.yaml
- components/CommunityLinks.vue
Fixes #5461 
This PR changes the title of the support card on the home page to 'Support' instead of 'Community Support' when a custom link is set for the Issue Reporting URL, e.g.
To test, go to Global Settings -> Branding and under Support Links, enter a URL for the  Issue Reporting URL. Click 'Apply'.
On the Home page, the support card now has a title of 'Support' and not 'Community Support'.
Note: This PR also fixes an issue with a recent change to the tertiary button which fixed the line height to 38px - it now only does that for a button usage that is not a small button. This fixes a rendering issue with the cluster count on the home page.
> Change title of support block on home page when custom link set

- components/nav/Header.vue
Fixes #5627 
Adds a visual indication when the kubeconfig copy to clipboard button is pressed.
> Add feedback to the copy kubeconfig header button

- components/SortableTable/index.vue
Fixes a bug in Sortable Table where the delayed columns would not update on scroll if there was no live column in the table.
> Fix bug where delay loading only worked on scroll with live columns

- components/CruResource.vue
- edit/auth/ldap/index.vue
- edit/auth/oidc.vue
- edit/auth/saml.vue
- mixins/auth-config.js
Fixes #5615
Prevent to break application while entering in authentication provider edit view.
In case of authentication, Initialized errors are not defined as list.
It seems like the rendering also differ in case of SSR, so the component is also always loaded.
Auth provider edit view `/c/local/auth/config/github?mode=edit`
Any view containing form which has the errors initialized, which is pretty much anything from the last commit.
> Initialize always auth errors as empty list

- components/formatter/PercentageBar.vue
- components/formatter/PodsUsage.vue
- list/node.vue
- models/cluster/node.js
- pages/home.vue
Addresses Github issue: [#5430](https://github.com/rancher/dashboard/issues/5430)
Addresses Zube issue: [#5456](https://zube.io/rancher/dashboard-ui/c/5456)
- Fix number of PODS on homepage cluster table by displaying the proper PODs usage (`PodsUsage` formatter)
- Fix units for MEM on homepage cluster table to always be GiB (consistent with the rest of the UI)
- Show **total** number of nodes rather that **useful** nodes in cluster dashboard view 
- Remove reserved info for CPU and MEM in cluster table in homepage 
- Fix PODs usage in nodes list view (matches cluster dashboard and cluster table in homepage)
- Display N/A when usage is zero for CPU, MEM, PODS in cluster `nodes list view`
**Preview**
_homepage_
_nodes list view_
_cluster dashboard_
> Inconsistencies with Cluster metrics across the UI

- pages/c/_cluster/_product/projectsnamespaces.vue
Fixes #5626
This PR adds the nameDisplay property to the fake row for an empty project so that it shows up when you filter.
> Enable filtering by project name on project/namespaces page

- assets/translations/en-us.yaml
- config/types.js
- models/catalog.cattle.io.app.js
Fixes #4947
The backport had a number of incompatible commits. I committed the relevant code and added a bit that would fix the issue of apps not being upgradable if they came from the ember side. 
Following the course of action from the previous commits, the "Edit/Upgrade" action is now no longer available for apps which are considered `legacy`.
We are checking for a match of any given app within Norman by the `id` and `url` of the app: 
- `/v3/api/<cluster-name>:<project-name>/apps/<project-name>:<app.metadata.name>`
Also we were checking for multi-cluster apps before, which is unnecessary as the app will appear as legacy regardless.  
- Install an app on the local cluster from the ClusterManager (ember) view
- Navigate to the Cluster Explorer => Apps & Marketplace => Installed Apps
- …
> [2.5.13] Backport #4947

- models/catalog.cattle.io.app.js
FIxes #5639 
Apps installed via helm cli may have `spec.values` defined but no `spec.values.global`
Edit: this was fixed [here](https://github.com/rancher/dashboard/commit/e1cb9a2f6c48d3960aa088c7368c8831705b8bbc) for 2.6: I didn't grab that actual commit since it happened post resource classification
> [2.5.13] Fix Installed Apps list when containing apps from helm cli

- assets/translations/en-us.yaml
- components/DetailTop.vue
- components/formatter/WorkloadDetailEndpoints.vue
- models/workload.js
This PR addresses #5463 by adding additional metadata to workload detail view. 
In addition to the already existing `image`, `labels`, and `annotations` data, this PR aims to also add `endpoints`, `available`, `ready`, and `up-to-date` information. 
To test this PR, navigate to any workload and verify that the new details at the top of each page match the same data from the workload's list view.
> Add additional metadata to workload detail view

- assets/translations/en-us.yaml
- components/LandingPagePreference.vue
- components/formatter/LiveExpiryBadgeState.vue
- components/nav/TopLevelMenu.vue
- config/settings.js
- edit/token.vue
- list/provisioning.cattle.io.cluster.vue
- pages/home.vue
- utils/cluster.js
Fixes #4193
This PR adds support for the setting that allows the local cluster to be hidden - in the old UI we supported this setting but in dashboard we do not - this PR fixes this.
To Test:
Open the shell on the local cluster and run:
```
kubectl patch settings.management.cattle.io hide-local-cluster --type merge -p '{"value":"true"}'
```
Refresh the dashboard UI - the local cluster should no longer be shown:
- On the home screen cluster list
- On the cluster list under Cluster Management
- In the slide-in top-level menu cluster list
> Allow local cluster to be hidden

- assets/styles/global/_resource.scss
- components/CruResource.vue
- components/ResourceDetail/index.vue
- components/ResourceYaml.vue
- edit/constraints.gatekeeper.sh.constraint/index.vue
- edit/management.cattle.io.user.vue
- edit/provisioning.cattle.io.cluster/SelectCredential.vue
- edit/provisioning.cattle.io.cluster/index.vue
- edit/provisioning.cattle.io.cluster/rke2.vue
- pages/c/_cluster/auth/config/_id.vue
- Fixes #5643
- Mostly caused by non-standard ways the CruResource was being used
Effected Areas / Places to test
Note - Only need to visit pages, shouldn't need to make any changes to resources
- Cluster create/import screens (types, credentials (create new / existing), import, rke2)
- Auth providers (shortest form is keycloak saml)
- Create/Edit resource types - project, namespace, some random others
- Create/Edit resource types that have sub-types (secrets, workloads, OPA Gateway / Constraints)
Also Addressed
- Only show top border of the footer if CruResource is in edit view (View a kube resource and go to the `Config` tab)
- Fixed hide of errors (div was shown regardless of number of errors)
> Fix a number of areas where the sticky footer consumes large amounts of space

- components/GrafanaDashboard.vue
Fixes Grafana metrics reload failure
- https://github.com/harvester/harvester/issues/2150
- Fix reload won't show the metrics when the reload is successful.
- Fix injectCss doesn't work after reload because the `window.document` is changed and `graphDocument` didn;t recompute.
Reproduce Steps: https://github.com/harvester/harvester/issues/2150#issuecomment-1099972410
> HARVESTER: Fix Grafana metrics reload failure

- models/management.cattle.io.nodepool.js
fixes #5443
alternative to #5570
- Use node metadata state to summarise `pending` and `ready`
- Add `unavailable` to cover nodes in error state
- All should be mutually exclusive to avoid duplicates
- Use common `nodeSummary` to reduce getter churn
Note 1 - We do this for RKE1 because we don't have the replica set info and we already fetch all nodes. It doesn't make sense to do this also for RKE2 as we have replica sets and fetching all machines is a large overhead.
Note 2 - It would be nice to show actual node state's here instead of `pending`, etc, but that would make the RKE2 stats look out of place
> Use real node state to show machine state summary

- components/form/LabeledInput.vue
- components/form/UnitInput.vue
- components/form/__tests__/LabeledInput.test.ts
- components/form/__tests__/UnitInput.test.ts
Fixes #5186
Prevent to modify input values while typing, in particular for invalid or formatted values, e.g. `096`.
The issue is extended to every input field with unit value validation.
- Added possibility to delay (debounce) input values for LabeledInput components
- Added delay for UnitInput, before parse the value, to avoid issues while typing
As defined in the ticket.
Unit tests have been added and updated.
Every/any Unit Input case.
https://user-images.githubusercontent.com/5009481/164283627-2cae1dd2-95bf-4b51-bf6b-1a13cd6f0ddc.mov
> Prevent UnitInput computation while typing

- components/SortableTable/index.vue
- pages/home.vue
- Fix error in console when lists contain sub rows `Duplicate keys detected: 'undefined-description'. This may cause an update error.`
This occurred on home page when a cluster was in error
- Align clusters table header and buttons (vertically) centrally
Before
After
> Fix two home page bugs

- assets/translations/en-us.yaml
- components/formatter/ClusterLink.vue
- detail/provisioning.cattle.io.cluster.vue
- list/provisioning.cattle.io.cluster.vue
- models/rke.cattle.io.etcdsnapshot.js
- plugins/steve/resource-class.js
Fixes #5651 
According to Chris Kim's comment [here](https://github.com/rancher/dashboard/issues/5651#issuecomment-1099608657) we can pull more detailed status info about snapshots from the `snapshotFile` property.
- add snapshot error info to the cluster error icon in the management cluster list
- use `snapshotFile.status` for the snapshot table state column
- decode and display error messages in the snapshot table
> improve RKE2 snapshot error reporting

- components/dialog/RotateEncryptionKeyDialog.vue
- models/provisioning.cattle.io.cluster.js
This PR addresses https://github.com/rancher/dashboard/issues/4540 by making it so that the context menu for an RKE2 cluster now saves the cluster YAML in order to rotate the encryption keys.
Jake said that in order to trigger a key rotation, all we need to do is update the cluster YAML to increment `spec.rkeConfig.rotateEncryptionKeys.generation`.
1. I provisioned a downstream RKE2 cluster
2. I created a snapshot of the cluster (because the modal for key rotation requires that a snapshot exists before keys can be rotated)
2. I confirmed that the Rotate Encryption Keys action was available in the action menu
3. The modal that appears confirms that I have a snapshot. I clicked **Rotate**
4. I confirmed that the `spec.rkeConfig.rotateEncryptionKeys.generation` value was …
> Rotating encryption keys action is available for RKE2 clusters

- detail/provisioning.cattle.io.cluster.vue
- models/cluster.x-k8s.io.machine.js
- models/cluster.x-k8s.io.machinedeployment.js
Fixes #5454 
The machine pool scale down button is disabled when the pool spec has only one replica defined; the individual pool scale down action menu option was disabled when the machine was the only instance of a controlplane or etcd role. This meant that if a cluster had one pool of workers with one worker machine, the pool couldn't be scaled down but the machine could. 
This PR updates the machine's `canScaleDown` function to prevent scaling down when it's the only machine in a pool. The role-checking logic is removed, since a machine can't be the only instance of a role without also being the only machine in its pool.
> Prevent scaling machine pools to 0 if it also scales down the only etcd or controlplane machine

- edit/provisioning.cattle.io.cluster/index.vue
This removes the Tech Preview label for the Harvester cluster provider.
closes #5700
> Remove 'tech preview' tag from RKE2/K3s Havester provisioning

- models/provisioning.cattle.io.cluster.js
This PR makes it so that the "Rotate Encryption Key" action will not be available for RKE2 clusters in the UI, per Sergey's request here: https://github.com/rancher/dashboard/issues/4540#issuecomment-1109113077
> Turn off rotate encryption key action for RKE2 clusters

- assets/translations/en-us.yaml
- components/form/NameNsDescription.vue
- components/form/ResourceQuota/ProjectRow.vue
- edit/management.cattle.io.project.vue
- models/management.cattle.io.project.js
Addresses Github issue: [#5417](https://github.com/rancher/dashboard/issues/5417)
Addresses Zube issue: [#5443](https://zube.io/rancher/dashboard-ui/c/5443)
- update `project` model to take into account `projectroletemplatebindings` to be able to manage project members 
- update `project` edit view to accomodate `projectroletemplatebindings` permissions and remove areas of the ui which should not be accessed 
- update `NameNsDescription` component to be able to disable description field if needed
- add `Banner` to `project` edit view to display disclaimer to user which are able to manage members but not the project itself
How to test:
1) create two users:
- both standard users, one to be project admin (**padmin**) and another just for testing (**test**)
2) create a new role as **Project …
> RBAC role to provide project-owner permissions while limiting quota management

- components/formatter/LinkName.vue
This fixes a problem where the NODE table header was rendering unusable links in pod tables.
rancher/dashboard#5727
Fixes #
This fixes broken links to Node pages seen on both the Node and Deployments page within the pod table.
- Node and Deployments
The product was undefined even though the prop has a default for EXPLORER. This seems to indicate that vue allows you to override a default value with undefined.
Node and Deployment pages both have a table with node links.
Anywhere with a LinkName but that's very unlikely.
> Resolving an issue where the default product value wasn't being used when a consumer passed undefined

- config/product/explorer.js
- config/types.js
- plugins/steve/actions.js
- store/type-map.js
Fixes #5104
- De-paginate requests for `projectroletemplatebinding` and `management.cattle.io.projectroletemplatebinding`
- Add `depaginate` option for types
- lowercase type `projectroletemplatebinding` to ensure type options can be found
I've tested this manually by applying the `limit` param to both types. The correct calls are made and the Vuex store contains all the required results. I've also tested that updates over the socket to the `projectroletemplatebinding` continue to be received (project members page doesn't update automatically, but clicking away and returning shows those updates).
- Project management (create/edit/delete)
- Project member management specifically (add/remove members)
- Environments with over 1000 project bindings (members of projects)
> De-paginate project bindings

- components/SortableTable/index.vue
Fixes #5721 
The Project Monitoring PR changed the width of the header buttons area - this results in our filter boxes being wider than they were - this PR fixes this and only uses the wider width if a header button slot is present.
It also ensures that the search area is right-aligned.
> Fix table header alignment and size

- detail/provisioning.cattle.io.cluster.vue
- list/provisioning.cattle.io.cluster.vue
Fixes #5725 
Fixes #5711 
Standard user can not access snapshots - the cluster page did not account for this.
Also fixes a bug where on the detail page, we were reusing the same has field (machines) for the snapshots.
> Fix empty cluster list for standard user

- components/formatter/PodsUsage.vue
- components/formatter/__tests__/PodsUsage.test.ts
Addresses Github issue: [#5717](https://github.com/rancher/dashboard/issues/5717)
Addresses Zube issue: [#5746](https://zube.io/rancher/dashboard-ui/c/5746)
- Fixes issue by triggering call to `/counts` endpoint only if cluster is Ready
> Home Page clusters table fetches counts for clusters that are not ready

- assets/translations/en-us.yaml
- components/ActionMenu.vue
- components/ResourceTable.vue
- components/SortableTable/index.vue
- edit/monitoring.coreos.com.alertmanagerconfig/index.vue
- edit/monitoring.coreos.com.alertmanagerconfig/receiverConfig.vue
- edit/monitoring.coreos.com.alertmanagerconfig/routeConfig.vue
- edit/monitoring.coreos.com.receiver/auth.vue
- edit/monitoring.coreos.com.receiver/index.vue
- edit/monitoring.coreos.com.receiver/tls.vue
- edit/monitoring.coreos.com.receiver/types/email.vue
- edit/monitoring.coreos.com.receiver/types/opsgenie.vue
- edit/monitoring.coreos.com.receiver/types/pagerduty.vue
- edit/monitoring.coreos.com.receiver/types/slack.vue
- edit/monitoring.coreos.com.receiver/types/webhook.vue
- edit/monitoring.coreos.com.route.vue
- models/monitoring.coreos.com.alertmanagerconfig.js
- pages/c/_cluster/monitoring/alertmanagerconfig/_alertmanagerconfigid/receiver.vue
- pages/c/_cluster/monitoring/route-receiver/_id.vue
- pages/c/_cluster/monitoring/route-receiver/create.vue
- pages/c/_cluster/monitoring/route-receiver/index.vue
- utils/position.js
Changes in this PR:
New stuff:
- In the receiver list view, the context menus on each table row have "Edit Config," "Edit as Yaml" and "Delete" context menu options.
- Can now select a receiver for your route in the AlertmanagerConfig. (Note: I misread the API docs - it is a single select, not a multiselect. This means the only way you can route the alerts to multiple receivers is by creating child routes in YAML, so I added an info banner to that effect - see screenshot below.)
- Added banner warning that Route and Receiver resources are deprecated.
- When you are creating an AlertmanagerConfig, I have the "Create Receiver" button disabled with the tooltip "The receiver form is available after the AlertmanagerConfig is created." I haven't figured out the best way to handle creating both …
> Second batch of AlertmanagerConfig form changes

- edit/provisioning.cattle.io.cluster/rke2.vue
Addresses Github issue: [#5112](https://github.com/rancher/dashboard/issues/5112)
Addresses Zube issue: [#5136](https://zube.io/rancher/dashboard-ui/c/5136)
- change worker nodes concurrency back to 10%
> change worker nodes concurrency back to 10%

- assets/translations/en-us.yaml
- edit/provisioning.cattle.io.cluster/rke2.vue
Adding a warning banner to the Add-On Config Tab
This warning informs the user that the add-on config tab will have it's values reset if the kubernetes version is changed. 
Fixes #5672 
This occurs because the config is driven by chart/s that are dependent on the kubernetes version.
Any provider that can see the Add-on Config tab should see this banner on the 
Just a visual change
> Adding a warning banner to the Add-On Config Tab

- components/EmberPage.vue
- edit/provisioning.cattle.io.cluster/index.vue
- pages/c/_cluster/legacy/project/pipelines.vue
#5343 - this PR adds a prop to the `EmberPage` component to disable re-using cached pages.
> add prop to force iframed ember pages to reload

- assets/translations/en-us.yaml
- components/AsyncButton.vue
- components/PromptModal.vue
- components/dialog/AddonConfigConfirmationDialog.vue
- edit/provisioning.cattle.io.cluster/rke2.vue
fixes #5672
This tries to go a little further to prevent users from accidentally breaking their clusters when changing kubernetes versions.
This should only show when editing the cluster and when the kubernetes version has changed.
RKE2 Clusters when editing and changing the kubernetes versions
Modals, the save button changing phase.
> Adding a confirmation modal to RKE2 providers when a user selects a new kubernetes version

- components/dialog/AddonConfigConfirmationDialog.vue
- On upgrade of an RKE2 cluster's kube version a new modal is shown warning about addon config (https://github.com/rancher/dashboard/pull/5775)
- This didn't work. The `apply` fn triggers the `closing` fn (via the `close` event and registerBackgroundClosing) which acts like a `cancel`. This happens all before the `apply` fn can send it's success response.
- Fix is to ensure we only send one response and close the modal only once
> Fix RKE2 cluster kube upgrade

- components/CopyCode.vue
- components/CruResource.vue
- components/CruResourceFooter.vue
- components/__tests__/Banner.test.ts
- components/__tests__/CopyCode.test.ts
- components/__tests__/CruResource.test.ts
- components/form/__tests__/ArrayListGrouped.test.ts
- edit/provisioning.cattle.io.cluster/CustomCommand.vue
- edit/provisioning.cattle.io.cluster/__tests__/CustomCommand.tests.ts
- jest.config.js
- jest.setup.js
- package.json
- yarn.lock
Fixes #5610
Allow to create unit tests for Typescript components by correcting the global configuration.
Seems like from Jest 26 to 27, the library used for Vue unit tests is different. Switching to `@vue/vue2-jest` solved the issue.
Note: Seems necessary to delete packages and reinstall them.
Together with this change, there have been introduced also other tests, both to ensure the ability to tests but also to provide examples for other cases. It also included to add global configuration.
- Created Jest global configuration
- Mocked i18n getters and directives in global configurations
- Added tests
- CopyCode, as it included mocks for plugin, global, slots and cases with Promises
- CustomCommand, as it included other components
- Banner, as Typescript component
- CruResource, as very …
> Enable unit tests with Jest for Typescript components

- models/provisioning.cattle.io.cluster.js
Added the maxLength property to the cluster validation.
Fixes #5214
> Giving cluster name a max length of 63 characters

- components/ButtonDropdown.vue
Fixes #5562 
Simple css updates to address svg icon not being centered properly. Kept a limited scope to buttonDropdown component to avoid edge cases issues with other v-select components.
> Button dropdown select icon not centered

- components/HardwareResourceGauge.vue
- config/product/neuvector.js
- pages/c/_cluster/neuvector/index.vue
- utils/install-redirect.js
- Issues were related to refreshing on the neuvector product's page `/c/<clusterid>/neuvector`
- As admin the incorrect `NAME` was causing `allTypes` to fail on `findBy(state.products, 'name', product).inStore`
- As a user who cannot see the `cattle-neuvector-system` namespace
- user could not see ns, so neuvector product was not loaded
- `install-redirect` then tried to redirect user to install neuvector chart but failed to find it (case sensative name)
- now instead we redirect user to cluster home page
Also fixed an issue on the cluster home page where users who could not see any pods saw an empty `Pods` card
Fixes #5770
> Fix bugs when refreshing on `/c/<clusterid>/neuvector`

- components/ResourceDetail/Masthead.vue
It's not meaningful to show the projectHelmChart name in the masthead since it's always going to be "project-monitoring".
> projectHelmChart masthead now shows projectName instead of it's own name

- components/GrafanaDashboard.vue
If a dashboard fails to load and then a user uses the button-group to switch between "Detail" and "Summary" then the page no longer crashes
> Fixes: user switching embedded dashboards when first has already failed

- assets/translations/en-us.yaml
- config/product/monitoring.js
- list/helm.cattle.io.projecthelmchart.vue
Name column should be relabeled as "Project" and should show the project name as a value but link should still point to projectHelmChart detail page.
"namespace" column should be relabeled as "Registration Namespace"
"System Namespace" column should be removed
> Incorporates feedback on headers/columns of the projectHelmChart list

- assets/translations/en-us.yaml
- components/form/LabeledSelect.vue
- components/form/SimpleSecretSelector.vue
- edit/monitoring.coreos.com.alertmanagerconfig/auth.vue
- edit/monitoring.coreos.com.alertmanagerconfig/index.vue
- edit/monitoring.coreos.com.alertmanagerconfig/receiverConfig.vue
- edit/monitoring.coreos.com.alertmanagerconfig/tls.vue
- edit/monitoring.coreos.com.alertmanagerconfig/types/email.vue
- edit/monitoring.coreos.com.alertmanagerconfig/types/opsgenie.vue
- edit/monitoring.coreos.com.alertmanagerconfig/types/pagerduty.vue
- edit/monitoring.coreos.com.alertmanagerconfig/types/slack.vue
- edit/monitoring.coreos.com.alertmanagerconfig/types/webhook.add.vue
- edit/monitoring.coreos.com.alertmanagerconfig/types/webhook.vue
- edit/monitoring.coreos.com.receiver/types/webhook.add.vue
- edit/monitoring.coreos.com.receiver/types/webhook.vue
- models/monitoring.coreos.com.alertmanagerconfig.js
- pages/c/_cluster/monitoring/alertmanagerconfig/_alertmanagerconfigid/receiver.vue
- utils/object.js
This PR adds 6 secret selectors for receiver credentials and API keys:
1. Slack: Need to configure `apiUrl` with secret selector.
2. Webhook: Need to configure `urlSecret` with secret selector.
3 and 4: PagerDuty: `routingKey` and `serviceKey` need to be configured with secret selectors.
5: Opsgenie: `apiKey` needs secret selector.
6: Email: `authPassword` needs to be from secret selector.
There is a bug fix to make sure that when you save a receiver as yaml, the result is not a crash or blank page.
We need to validate that when you change values in the form, it affects the right field in YAML. When values are updated in YAML and then saved, the values should show up the next time the receiver details are loaded.
Basically each field that we expose in form fields for receivers needs to be …
> Add secret selectors for Slack, PagerDuty, OpsGenie, Webhook and Email

- components/SortableTable/index.vue
Fixes rancher/dashboard#5533 
The issue was caused by being passed the incorrect value for `row` to determine if the row is expanded.
Now passing `row.row` to the method `isExpanded`.
https://user-images.githubusercontent.com/40806497/166674695-85d02210-bcaf-40b8-a327-6fd60d502cbd.mp4
> Fix subrow chevron direction when expanded

- edit/provisioning.cattle.io.cluster/DrainOptions.vue
Fixes #5829 
This PR changes back default drain strategy to No.
Before:
After:
I've also improved the styling of the timeout input box so that it has some top margin and is indented to show it related ot the checkbox above:
> Change default cluster upgrade stragetgy to drain = false

- assets/translations/en-us.yaml
- components/formatter/LinkDetail.vue
- components/formatter/ReceiverIcons.vue
- config/product/monitoring.js
- edit/monitoring.coreos.com.alertmanagerconfig/index.vue
- edit/monitoring.coreos.com.alertmanagerconfig/receiverConfig.vue
Fixes #5744 
This PR adds a table formatter for alertmanagerConfigs and their receivers in order to add logos for each receiver type next to the name. I've moved the `getCustomDetailLink` logic from `LinkDetail` to the new formatter because I think it was only being used for receivers, correct me if I'm wrong @catherineluse 
Icons for alertmanagerconfigs:
Icons for individual receivers:
> add icons to name column in alertmanagerConfig and receiver tables

- assets/translations/en-us.yaml
This PR is addresses https://github.com/rancher/dashboard/issues/5818
The problem here is that it can be confusing or counterintuitive that the words "routes" and "receivers" are being used to mean different things. A route can be a Route custom resource, or it can be a configuration block within an AlertmanagerConfig custom resource. We want to avoid setting up the expectation that if you add a route to an AlertmanagerConfig, it will show up on the Routes page. Because the resources and are handled as separate things (and the details of how they are configured are slightly different in spite of having the same names).
I updated the note on the deprecated Routes/Receivers to try to clarify things.
> Clarify that routes/receivers in AlertmanagerConfigs don't show on Routes and Receivers pages

- pages/c/_cluster/apps/charts/install.vue
Fixes #5753 
If systemProjectId is not part of the chart's global.cattle object during chart installation, this will automatically add it to the payload of the post request
All charts will now include systemProjectId in the payload of their post request (during chart installation). Charts that require this value should now work if the value isn't filled out, other charts will ignore the value if it's not used.
added `setIfNotSet(global, 'cattle.systemProjectId', systemProjectId);` to install.vue
Install any chart, check network calls for post request, notice systemProjectId under global>cattle in the payload of the request
This affects all chart installations but shouldn't have any adverse effects
> #5753 Add systemProjectId to global.cattle into payload for chart installation

- assets/translations/en-us.yaml
- edit/monitoring.coreos.com.alertmanagerconfig/routeConfig.vue
This PR addresses https://github.com/rancher/dashboard/issues/5819
The input fields didn't match the required YAML format of the new routes API. So the fix was to add/change the fields for grouping and matching to become compatible with the new API.
I updated two sections of the route form on the Route tab within the AlertmanagerConfig detail page.
The first is the Grouping section, which should now allow you to enter a list of strings that will be used to group alerts by label:
The second is the Matchers section, which now lets you pick names and values of alert labels to use for matching. Each name/value pair comes with a dropdown menu that lets you pick which kind of comparison you want:
The relevant API docs for matchers are here: …
> Can configure AlertmanagerConfig routes with new API

- pages/c/_cluster/apps/charts/install.vue
Fixes #5861 
method used for obtaining systemProjectId on chart installation has clusterId concatenated onto it. Removed the clusterId.
install any chart via apps, inspect payload on post request to API to see that the global.cattle.systemProjectId value now only includes the projectId and not the clusterId prepended to the projectId
none that I'm aware of
> ClusterId is concatenated onto systemProjectId, removed via split

- assets/translations/en-us.yaml
- edit/provisioning.cattle.io.cluster/MachinePool.vue
- edit/provisioning.cattle.io.cluster/rke2.vue
- machine-config/amazonec2.vue
- models/provisioning.cattle.io.cluster.js
fixes #5517
Anywhere that an aws cloud provider could be selected could cause this to happen. I only identified ec2 rke2 as a spot.
Anywhere that an aws cloud provider could be selected could cause this to happen. I only identified ec2 rke2 as a spot.
https://user-images.githubusercontent.com/55104481/167209225-ff870185-6ae1-4e92-a776-ae3cc43d58ea.mp4
> Adding validation for the IAM Instance Profile Name which is required when the amazon cloud provider is selected

- components/form/ArrayList.vue
This fixes an issue where members of `ArrayList.vue` would be removed at the wrong index by reordering the arguments to match the parameter order for `remove`. 
Fixes #5874
Anything that makes use of `ArrayList.vue` but depends on the wrong ordering of arguments; I doubt that this would be the case, as this looks to be a regression introduced in #5629. I expect that other consumers of `ArrayList` regressed and bugs were not reported as of yet.
> Fix arguments for remove on click

- components/auth/Principal.vue
Addresses https://github.com/rancher/dashboard/issues/5876
This PR prevents the 'Unable to fetch principal info' error that is shown when a user tries to add authorized users and groups to the list of users who should be able to log in to Rancher. The error was seen on this page:
In 2.6.4, there was no async call to fetch principal info in this page.
The UI attempts to make an async call to `/v3/principals/<principalId>`. On this page, `principalId` is undefined, so the API call was going to `/v3/principals/undefined`, which causes an error.
Anupama showed that in v2.6.4, there was no async call to get the principal details on this page. So it looks like the bad API call was not needed.
The API call was originally added in https://github.com/rancher/dashboard/pull/3064 to add support for …
> No longer see errors when adding authorized principals

- edit/provisioning.cattle.io.cluster/rke2.vue
On initialization we were setting the s3Backup. This would trigger a watcher which would overwrite the s3 values.
fixes #5865 
Enabling/disabling s3 backups when creating/editing clusters.
Enabling/disabling s3 backups when creating/editing clusters.
> Fixing how we initialize s3 backups in rke2 clusters

- edit/helm.cattle.io.projecthelmchart.vue
Fixes #5897
Bug occurs when project is deleted and one of the orphaned namespaces is still listed as project operated and still has a projectId in it's annotations. 
Fix ensures that the model can still find a project that matches the projectId
> Fixes bug in dropdown when project no longer exists by filtering it out.

- components/CruResource.vue
- components/ResourceYaml.vue
- edit/monitoring.coreos.com.alertmanagerconfig/receiverConfig.vue
#5877 - this PR updates the `doneRoute` used in receivers to be the alertmanagerconfig detail view, and updates ResourceYaml to allow `doneRoute` to be an object. (ResourceYaml already allows route objects via `doneOverride` but the instance used in CruResource sets `doneOverride` to a model property which wont work for this use case)
> allow doneRoute to be an object

- shell/nuxt.config.js
- When using `ui-dashboard-index` `https://releases.rancher.com/dashboard/latest/index.html` naving to 'Create' style pages resulted in page refresh
- Caused by 404 on some files with urls containing `//`
- Fix is to remove `[name]` in prod file names (see https://github.com/nuxt/nuxt.js/issues/8274)
- This also flattens out the folder structure (avoids crazy paths like `_nuxt/pages/account/create-key/pages/c/_cluster/_product/_resource/_id/pages/c/_cluster/_product/_resource`)
- ![image](https://user-images.githubusercontent.com/18697775/167821005-cf84cb2e-2055-409a-bb9a-c0f06658533a.png)
- vs
- ![image](https://user-images.githubusercontent.com/18697775/167819498-a3f388a2-8341-47bb-b7d4-2e79505ff931.png)
> Fix issue where build output would contain invalid urls

- components/form/KeyValue.vue
Addresses Github issue: [#5907](https://github.com/rancher/dashboard/issues/5907)
Addresses Zube issue: [#5936](https://zube.io/rancher/dashboard-ui/c/5936)
- fix issue where user could not create opaque secret from `edit config` interface in `Secrets`
> Can't create an Opaque secret using plain text as value (2.6.5 branch)

- shell/components/form/KeyValue.vue
Addresses Github issue: [#5907](https://github.com/rancher/dashboard/issues/5907)
Addresses Zube issue: [#5936](https://zube.io/rancher/dashboard-ui/c/5936)
- fix issue where user could not create opaque secret from `edit config` interface in `Secrets`
> Can't create an Opaque secret using plain text as value

- shell/store/i18n.js
Addresses Github issue: [#4381](https://github.com/rancher/dashboard/issues/4381)
Addresses Zube issue: [#4399](https://zube.io/rancher/dashboard-ui/c/4399)
- change HTML lang attribute when language changes on the UI
**Comment:**
On Nuxt one can set the `head` attributes either [globally](https://nuxtjs.org/docs/features/meta-tags-seo/#global-settings) (nuxt.config) or [locally](https://nuxtjs.org/docs/features/meta-tags-seo/#local-settings) (per page).
Since changing it locally is not an option (we would have to manually set it for each page), from my investigation I don't think it's possible to set globally in a dynamic fashion.
With that in mind, the solution adopted is to set the `lang` attribute via JS when the language is changed (or initially set) in the UI.
> Accessibility: setting HTML page language

- pkg/epinio/config/epinio.ts
- pkg/epinio/l10n/en-us.yaml
- pkg/epinio/models/applications.js
- pkg/epinio/models/catalog-service.js
- pkg/epinio/models/configurations.js
- pkg/epinio/models/epinio-namespaced-resource.js
- pkg/epinio/models/service-instance.js
- pkg/epinio/store/epinio-store/actions.ts
- pkg/epinio/types.ts
- shell/components/form/NameNsDescription.vue
- includes fix to NameNsDescription `namespacesOverride` (everything else is epinio pkg specific)
- Implements basic fetch, models and lists of catalog services and service instances
- Everything else blocked on UX decisions / backend changes (see https://github.com/epinio/ui/issues/97)
Note - To test Epinio remove the `epinio` entry from the `excludes` list in `nuxt.config.js`
> Initial support for epinio services

- shell/assets/translations/en-us.yaml
- shell/components/form/ResourceQuota/NamespaceRow.vue
Fixes #5807 
Adds hover tooltip similar to previous behavior seen in ember ui to show project resource quotas.
> Add tooltip for Project Namespace Resource Quotas

- package.json
- pkg/epinio/package.json
- shell/creators/app/app.package.json
- shell/creators/app/package.json
- shell/creators/pkg/package.json
- shell/creators/pkg/pkg.package.json
- shell/package.json
- shell/scripts/publish-shell.sh
Update package files and improve script to publish shell and creators to npm.
Removes `publishConfig` localhost registry configuration in some of the package files that was only for local testing during development.
> Update package versions and update publishing script

- shell/assets/translations/en-us.yaml
- shell/config/product/manager.js
- shell/models/management.cattle.io.cluster.js
- shell/models/provisioning.cattle.io.cluster.js
Fixes #5839
See issue for details - simple fix.
I noticed that the mgmt resource allows copy to clipboard of kubeconfig where as the provisioning does not - this PR fixes that as well.
> Hide Mgmt Cluster type in Cluster Management Advanced group

- shell/components/CopyToClipboardText.vue
Fixes #5688
Adds feedback when you copy on a text link that can be copied - turns green for a half a second and the icon changes to a tick rather than the copy icon.
> Add feedback to the CopyToClipboardText component

- shell/assets/translations/en-us.yaml
- shell/edit/monitoring.coreos.com.alertmanagerconfig/routeConfig.vue
Addresses https://github.com/rancher/dashboard/issues/5885 by adding this tooltip:
> Add tooltip for groupBy field in AlertmanagerConfig route

- .drone.yml
- scripts/create-pr-in-rancher
Follow-up to https://github.com/rancher/dashboard/pull/5737 which was reverted because it broke the build. I think because this step introduces `depends_on`, it causes the other steps to be executed in parallel causing ordering problems. This PR has the same changes without `depends_on`.
> Add dispatch step to update tag in rancher/rancher

- shell/detail/provisioning.cattle.io.cluster.vue
- shell/list/provisioning.cattle.io.cluster.vue
- shell/models/provisioning.cattle.io.cluster.js
Addresses Github issue: [#5787](https://github.com/rancher/dashboard/issues/5787)
Addresses Zube issue: [#5816](https://zube.io/rancher/dashboard-ui/c/5816)
- update permissions check for action 'save RKE template' on cluster provisioning list view
> `Save RKE Template` option is seen for a Std user who is cluster owner

- shell/components/nav/TopLevelMenu.vue
- tsconfig.json
Hides plugins in the top-level nav for now, since they are still in development
Adds `dist-pkg` folder to the tsconfig excludes, to avoid errors when packages have been built and are in this folder.
> Hide plugins nav unless running in dev mode

- shell/components/nav/TopLevelMenu.vue
- shell/pages/home.vue
Fixes #4355 
Currently the side nav and home page show the list of clusters using the management cluster resource where as the cluster management page uses the provisioning cluster resource - this leads to inconsistencies - e.g. as described in the issue above.
This PR changes the side nav and home page to use the provisioning resource.
It also uses the ClusterProvider formatter so that that provider presentation on the home page is consistent with the cluster list in cluster management.
> Make side nav and home page cluster lists be consistent with provisioning list

- shell/edit/management.cattle.io.project.vue
- shell/models/management.cattle.io.project.js
- shell/plugins/dashboard-store/resource-class.js
- shell/plugins/steve/norman-class.js
Addresses Github issue: [#5173](https://github.com/rancher/dashboard/issues/5173)
Addresses Zube issue: [#5197](https://zube.io/rancher/dashboard-ui/c/5197)
- add `_replace=true` query param to `projects` `PUT` request in order to update nested object properties of the object correctly on the database (check comment of BE dev [here](https://github.com/rancher/rancher/issues/35688#issuecomment-1130046378) in regards to the issue reported to the BE regarding the `Project` `resourceQuotas` update)
> resourceQuota: Address issue where removing existing quotas wasn't being reflected on the saved obj

- shell/components/form/LabeledSelect.vue
- shell/components/form/SimpleSecretSelector.vue
Addresses https://github.com/rancher/dashboard/issues/5984
Follow-up to https://github.com/rancher/dashboard/pull/5989
In this PR https://github.com/rancher/dashboard/pull/5850 I modified the LabeledInput component to make it emit an event that I needed for the new SimpleSecretSelector component, which is used only by AlertmanagerConfig receivers. The event could have been named anything. So I could have called it 'eventSpecificallyForSelectingReceiverSecret', but instead I went with the name 'input' because the component was supposed to be generic.
But it turns out the former name would have been better, because emitting the 'input' event more times has created this bug. https://github.com/rancher/dashboard/issues/5984
So I renamed the event to "selecting", which still sounds generic but …
> Change name of event emitted for secret selector

- package.json
Looks like with the plugin work, we lost the storybook scripts in the package file.
This PR brings them back.
> Add back storybook scripts to the package file

- pkg/rancher-components/package.json
- pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue
- pkg/rancher-components/src/components/Form/TextArea/TextAreaAutoGrow.vue
- yarn.lock
This removes the JQuery dependency from `TextAreaAutoGrow.vue` and `Checkbox.vue` by replacing jquery implementations with browser api implementations. 
- Triggering Custom Events 
- Replace `$(this.$el).trigger(click);` with `this.$el.dispatchEvent(click);` 
- See MDN docs for [creating a custom event](https://developer.mozilla.org/en-US/docs/Web/Events/Creating_and_triggering_events#adding_custom_data_%E2%80%93_customevent) 
- Setting Styles
- Replaces ```$(this.$refs.ta).css('height', `${ this.curHeight }px`);``` with ```this.$refs.ta.style.height = `${ this.curHeight }px`;```
- See MDN docs for [HTMLElement.style](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style)
- Getting Styles
- Replaces `$el.css('borderTopWidth')` with …
> Replace JQuery in TextAreaAutoGrow and Checkbox

- shell/assets/translations/en-us.yaml
- shell/models/storage.k8s.io.storageclass.js
- shell/plugins/dashboard-store/resource-class.js
Fixes #5831 
Need to patch the storage class rather than save to set default status - with some storage providers, doing a full save is rejected after creation.
> Use patch when updating storage class default

- shell/assets/translations/en-us.yaml
- shell/mixins/brand.js
- shell/pages/support/index.vue
#4916 - this PR adds UI support for Rancher support purchased through AWS: see [this comment](https://github.com/rancher/dashboard/issues/4916#issuecomment-1106741816) to set up the dev environment.
The support page watches for the existence of the `csp-adapter` helm app and shows the option to download a support config file when it exists. The brand mixin also checks for the `csp-adapter` app and sets the theme to (supported) SUSE green by changing the `brand` global setting.
> AWS Marketplace Integration: generate support config 

- shell/components/AwsComplianceBanner.vue
- shell/config/types.js
- shell/layouts/default.vue
- shell/layouts/home.vue
- shell/layouts/plain.vue
Fixes #5616 
This PR adds a banner component that will display a warning when a Rancher instance with support purchased through the AWS Marketplace has more nodes than they've purchased support for. 
I created `rancherUserNotifications` through the Norman API to test this. I have a cluster with some I can share access to for testing porpoises.
Some notes about the rancherUserNotification object: 
- the relevant notfication will always come from csp-adapter
- there will never be more than one notification
- the notification object will be removed by backend when the Rancher instance is no longer out of compliance
- any user who can see the rancherUserNotification should be warned about compliance
> aws compliance banner

- shell/assets/translations/en-us.yaml
- shell/components/form/UnitInput.vue
- shell/config/query-params.js
- shell/edit/persistentvolumeclaim.vue
- shell/list/persistentvolumeclaim.vue
- shell/models/persistentvolumeclaim.js
Fixes #5543 
This PR updates the PVC edit page so that it correctly allows volume expansion based on the underlying storage class and also the bound status of the PVC.
Also added a 'Resize' option to the action menu for a PVC that goes to the edit page with the size field focused.
The model requires that the storage classes have been retrieved in order to determine if a PVC can be resized, so a custom list for pvcs was added that ensures that these are fetched.
> Fix PVC expansion and add to action menu

- shell/components/form/ResourceTabs/index.vue
- shell/detail/workload/index.vue
- shell/models/event.js
Fixes #6057 
For workload types, always show the recent event tabs. Since these are schedulable resources, it is useful to see the tab - this gives parity with the Ember UI.
I did not show the tab in all cases, as for other resource types it may lead to lots of tabs - this is generally less relevant, so can be shown only when there are recent events.
Also added the event type column, so that the view shows the same data as the Ember UI.
> Workload events tab

- shell/components/ResourceDetail/Masthead.vue
- shell/config/product/manager.js
- shell/config/table-headers.js
- shell/models/provisioning.cattle.io.cluster.js
- shell/plugins/dashboard-store/resource-class.js
Addresses Github issue: [#4966](https://github.com/rancher/dashboard/issues/4966)
Addresses Zube issue: [#4988](https://zube.io/rancher/dashboard-ui/c/4988)
- Create custom model prop for `provisioning.cluster` in order to display correct age of a cluster in the case of an upgrade in Rancher version
**New date prop for list view table headers for `prov.cluster` _(hacked the date itself to make sure it worked where I wanted)_**
**New date prop for detail view in `prov.cluster`**
**Cluster Dashboard view remains with `mgmt cluster` date**
> Cluster Manager and Cluster Dashboard show different age for same cluster

- shell/config/product/explorer.js
- shell/config/types.js
Addresses Github issue: [#4792](https://github.com/rancher/dashboard/issues/4792)
Addresses Zube issue: [#4811](https://zube.io/rancher/dashboard-ui/c/4811)
- remove `globalDnsProvider` from `more resources` in side menu
**Menu entry in `Multi-cluster-apps`**
**Menu entry removed from `More Resources` - `Rancher`**
> `Steve` DNS related resource types can cause confusion

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
Fixes #6012 
There was no product label set for `neuvector` to it was giving the default capitalisation.
After fix:
> Fix NeuVector casing in side nav

- shell/config/table-headers.js
Fixes #6097 
Fixes #5944 
A row value getter was added to the AGE column definition. The Norman AGE column definition inherits from this but did not override the new  getter, so it was using the Steve getter and getting an empty value.
> Fix age column for Norman resources

- .vscode/settings.json
- README.md
- docs/developer/PLUGINS.md
- env.template
- nuxt.config.js
Fixes #https://github.com/rancher/dashboard/issues/6074
Changes the excludes pkg from nuxt.config.js to `.env` with a default behaviour for when we don't have an .env file.
> Excludes packages from .env file instead of hardcoded

- shell/models/fleet.cattle.io.bundle.js
- shell/pages/c/_cluster/fleet/GitRepoGraphConfig.js
- shell/plugins/dashboard-store/resource-class.js
Addresses Github issue: [#6007](https://github.com/rancher/dashboard/issues/6007)
Addresses Zube issue: [#6036](https://zube.io/rancher/dashboard-ui/c/6036)
- add missing prop check for `stateObj` in `FleetBundle` model
- add missing prop check for `color` when state is not defined as ENUM in `gitRepoChartConfig`
- add missing state `deploying` to state ENUM
> Multiple issues in Fleet (Dashboard and gitRepo Graph views)

- shell/assets/translations/en-us.yaml
- shell/models/provisioning.cattle.io.cluster.js
The error was occurring because we were hitting a timeout when waiting for the management cluster to become available. I doubled the timeout time to reduce the likelihood of this happening and made the error message more clear.
rancher/dashboard#6010
Any rke2, harvester or import provisioning.
> Increase the timeout and provide better messaging for the timeout when creating clusters

- shell/mixins/brand.js
- caused by bad merge from epinio-dev --> master
- globalSetting was moved to a `computed` property but wasn't removed from `data`
> Fix `globalSettings` error in console

- shell/components/nav/WindowManager/ContainerLogs.vue
- No.1
- validate and fix bad LOGS_RANGE preference
- at some point this became polluted and now breaks streaming of logs
- fixes https://github.com/rancher/dashboard/issues/6122
- No.2
- Ensure the `Everything` log range option is correctly selected when the value is `all`
- Previously it would just show as an option underneath `Everything`
> Address two container log streaming issues

- shell/components/CruResource.vue
- shell/edit/management.cattle.io.clusterroletemplatebinding.vue
Addresses https://github.com/rancher/dashboard/issues/6153
The root cause is that in a PR that modified the CruResource component, I accidentally removed the data that had previously been passed when emitting the `finish` event. https://github.com/rancher/dashboard/pull/6084/files#diff-3949ec5a78c462b58bebb75bc06ccea895056a12129a9a8b8841dac3dd6b07d0R283
I created a PR https://github.com/rancher/dashboard/pull/6156 that passes event data when emitting the `finish` event:
https://github.com/rancher/dashboard/compare/fix-cruresource?expand=1#diff-3949ec5a78c462b58bebb75bc06ccea895056a12129a9a8b8841dac3dd6b07d0R283
This is what the CruResource component had already been doing before my PR accidentally removed it: 
https://github.com/rancher/dashboard/pull/6084/files#diff-3949ec5a78c462b58bebb7 …
> Pass data when emitting finish event

- shell/components/CruResource.vue
- shell/components/form/NameNsDescription.vue
- shell/edit/workload/index.vue
UX Changes
- Cancel cross should be a standard colour rather than red
vs
- Align cancel `x` with select container drop down's arrow (not shown above)
- When choosing to create a namespace set the focus to newly exposed input field (avoids user having to click again)
- Align additional fields for deployment types with fields above (previously fields below were much bigger than above)
- Align margin bottom of NameNsDescription and workload specific field row
- Also ensure row (with margin) only shows when it has to
UX Questions
- The container selector is now dangling on the end of a row of input fields. I thought to move it to the start, however then the selector is in the middle (reading left to right over rows) of input fields. Not sure where the selector should ultimately end up …
> NameNsDescription Updates

- shell/edit/provisioning.cattle.io.cluster/MachinePool.vue
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
- shell/machine-config/harvester.vue
Limit all VMs of the Harvester guest cluster in the same namespace
- https://github.com/harvester/harvester/issues/2354
As the virtual machines are in the same namespace, we added a limitation for the cluster created. Only the first pool can select the namespace, the other pool is disabled and will sync with the first node pool namespace. 
Harvester node driver 
Harvester node driver
> HARVESTER: Limit all VMs of the Harvester guest cluster in the same namespace

- shell/components/SortableTable/paging.js
- shell/components/SortableTable/sorting.js
Fixes #6138 
There is a watch for the sort fields changing - this always returns to the first page.
For some reason, this is getting called and the page is being reset.
This PR fixes the issue and tidies up the code.
> Fix bug where table can jump back to page 1 after page change

- shell/components/SortableTable/index.vue
- shell/components/SortableTable/paging.js
- shell/components/SortableTable/sorting.js
- shell/components/formatter/DelayedValue.vue
- shell/config/table-headers.js
- shell/plugins/steve/mutations.js
- shell/plugins/steve/performanceTesting.js
Fixes #6140 
Includes PR: #6139
This PR adds a new formatter - `DelayedValue` and uses that for the pod restarts column.
It also adds value getters for two more columns and makes a minor tweak to the sortable table so that column IDs are calculated once up-front rather than every time for each row (a small optimisation to reduce calls to the `dasherize` function).
We also optimise slightly so that we don't get values for delayed columns in `displayRows` - since the delayed loading formatter will do this when it is ready to display the column.
> Use a delayed loading column for Pod Restarts

- docs/developer/style.md
- shell/layouts/default.vue
- Currently the default layout does not expose an outlet if there is no ready cluster
- This means unknown routes like `/aaa` cannot show the error page
- A header and blank page is shown instead
- ![image](https://user-images.githubusercontent.com/18697775/173404234-bf3b83f9-5d23-4562-b3e2-fc8a0017e8dd.png)
- Fix is to add the outlet when we don't have a cluster id
- ![image](https://user-images.githubusercontent.com/18697775/173404395-ae0bbae1-5503-46fc-a80a-708264d2a3bc.png)
- The default layout shouldn't be used when there is no cluster (see `plain` layout), so this should be safe
Additionally remove some legacy references to `design-system` - fixes https://github.com/rancher/dashboard/issues/5613
> Fix 404/error page

- shell/components/formatter/Endpoints.vue
- In the workloads list the Endpoints column can show multiple endpoints
- These are `key`ed by `endpoint.link`
- Endpoint links are not guaranteed to be unique (I've got a system that shows this, available on request)
> Fix `Duplicate keys detected` in endpoint formatter

- shell/config/roles.ts
- shell/edit/helm.cattle.io.projecthelmchart.vue
This PR addresses https://github.com/rancher/dashboard/issues/5747 by adding the ProjectHelmChart resource to the list of resources available to choose from when you create a custom role.
1. I went to Users & Authentication > Roles.
2. Created a project role and confirmed that you can select `ProjectHelmCharts` from the `helm.cattle.io` API group.
3. Confirmed that when you select `ProjectHelmCharts`, the `helm.cattle.io` API group is automatically populated in the API Groups field.
4. Gave all verbs to the role and named it `test-project-helm-chart`. Finished creating the role.
Then I confirmed that the role gives a standard user sufficient permissions by doing the following:
5. Installed the monitoring app in the `system` project on a downstream RKE2 cluster.
6. …
> Can add ProjectHelmChart resource to custom roles

- shell/config/product/explorer.js
This PR addresses https://github.com/rancher/dashboard/issues/5746 by changing how resource type names are mapped to group names in the side nav of cluster explorer.
Previously, both `helm` and `k3s` in the type name mapped to the K3s group name. Now `k3s` maps to K3s and `helm` maps to Helm.
1. I installed the monitoring app and the Prometheus Federator app in a downstream RKE2 cluster.
2. Went to cluster explorer in the downstream cluster. In the top nav, clicked the magnifying glass. Confirmed that when searching for `proj...` you can see Project Monitors grouped under Helm.
3. In the side nav of cluster explorer, you can also see Project Monitors grouped under Helm.
> Group ProjectHelmChart resources under Helm, not K3s

- shell/pages/c/_cluster/monitoring/alertmanagerconfig/_alertmanagerconfigid/receiver.vue
Addresses https://github.com/rancher/dashboard/issues/5879
Depends on https://github.com/rancher/dashboard/commit/1fb8fee218178031ee5047e0083992b03d6b633b to be merged first
Here is the edit receiver form:
When you click Edit As YAML, the header now changes to Edit AlertmanagerConfig:
> Change header when navigating from receiver form to YAML

- pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue
This explicitly returns false if no conditions can satisfy `value.find()` instead of throwing a type error if `undefined`. This still satisfies the `isChecked` computed prop in the same way that it behaved before the typescript conversion.
See also [PR #6073](https://github.com/rancher/dashboard/pull/6073/files#diff-06c482d4d2e8220ab950839aa5aca4dd6a6101f7b94f38c293e559c48049295d)
Fixes #6137 
Testing notes in issue.
[Array.prototype.find() returns `undefined` if no conditions satisfy the testing function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find).
> Explicitly return false if `findTrueValues` is falsy

- shell/layouts/error.vue
- shell/layouts/unauthenticated.vue
- shell/middleware/authenticated.js
- shell/middleware/unauthenticated.js
- shell/mixins/brand.js
- shell/pages/c/_cluster/settings/brand.vue
- shell/utils/favicon.js
Follow-on fixes for adding custom fav icon.
- Don't force light theme in the settings page
- Ensure the icon is set for all page layouts - previously this was only for those that included the `authenticated` middleware
> Fixes for setting custom favicon

- shell/assets/translations/en-us.yaml
- shell/detail/pod.vue
Add containerStatus lastState information to Pod detail page
The containerStatus object (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#containerstatus-v1-core) also contains a lastState field which gives you details about the container's last termination condition.
If there's a lastState in the containerStatus, this should also be displayed in the container list.
This is especially useful when you need to debug why a container restarted, because it gives you the exit code, potential error message and reason as well as the time when the container terminated.
Fixes #6189
If there is a `containerStatus.lastState` for a container, this information will be added to the containers stateDescription field.
In order to test, you need check a pod that has restarts.
If you …
> Add containerStatus lastState information to Pod detail page

- shell/list/provisioning.cattle.io.cluster.vue
Adds loading indicator the cluster list page in Cluster Management - currently the table shows 'no rows' message before then showing the clusters - this PR fixes that so that it shows the loading indicator instead of the 'no rows' message.
> Add loading indicator to clusters list page

- shell/layouts/default.vue
- shell/layouts/home.vue
- shell/layouts/plain.vue
- shell/mixins/browser-tab-visibility.js
- shell/store/index.js
Addresses Github issue: [#5418](https://github.com/rancher/dashboard/issues/5418)
Addresses Zube issue: [#5444](https://zube.io/rancher/dashboard-ui/c/5444)
- add logic to handle expired sessions by redirecting user to login page
**Repro steps**
- Login to Rancher UI
- Open up another tab (can be blank) on the same browser instance
- Click between tabs
- Check if the "ping" is being done to fetch the user
**Other scenarios**
- Lock your mac and then log back in your mac. Go to the tab. "ping" on Network should have occurred
- Remove session token, click on another tab, then go back to rancher tab (it should log out the user after "ping" fails)
> UI expired session doesn't redirect us to the login page

- shell/detail/networking.k8s.io.ingress.vue
Add link to certificate secrets on ingress detail page
Fixes #6177
The ingress detail page now filters the already loaded secrets for certificate secrets in the ingress' namespace and passes them to the Rules component. The Rules component already had logic to create a link to the secret in the certificates column.
The ingress detail page
The ingress detail page
Before
After
> Add link to certificate secrets on ingress detail page

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/pages/auth/setup.vue
With custom branding [0]  telemetry sentence mentions custom company name instead of Rancher.
[0] https://rancher.com/docs/rancher/v2.6/en/admin-settings/branding/
> translations: Replace vendor tag with name tag

- shell/edit/monitoring.coreos.com.alertmanagerconfig/types/email.vue
- shell/edit/monitoring.coreos.com.alertmanagerconfig/types/opsgenie.vue
- shell/edit/monitoring.coreos.com.alertmanagerconfig/types/pagerduty.vue
- shell/edit/monitoring.coreos.com.alertmanagerconfig/types/slack.vue
Addresses https://github.com/rancher/dashboard/issues/5875
The affected secrets are:
- email 
- auth password secret
- opsgenie
- API key secret
- pagerduty
- routing key secret
- service key secret
- slack
- API URL secret
- webhook
- URL secret - not in this PR because it was already done.
To test this PR, I validated that if you set and unset a secret for the above values, the secret is deleted and you can save the resource without any backend validation errors.
PR in draft because I think master needs some bug fixes from the 2.6.5 release branch before I can test this. https://github.com/rancher/dashboard/pull/5986
> Receiver credential secrets are deleted when secret is set to none

- .gitignore
- shell/components/form/Footer.vue
- shell/creators/pkg/tsconfig.json
- shell/edit/management.cattle.io.clusterroletemplatebinding.vue
- shell/edit/workload/__tests__/Job.test.ts
- shell/nuxt.config.js
- shell/scripts/publish-shell.sh
Fixes shell package given recent components changes.
For now, the components are copied into the shell package when published - this ensures when the shell is used as an npm package that it can still compile.
> Fix shell package with rancher components

- shell/detail/workload/index.vue
- Customers have stated the AGE column was missing from this view
- Request came from a customer interview
- Go one step further and ensure that all columns (minus namespace) are shown
- Changes
- This contributes to SURE-4759 but does not fully resolve it
- SURE-4759 is for a different customer who has asked for more
- See issue for screenshots of this change and existing cluster manager changes
> Show more headers in workload pods list (including age)

- shell/components/nav/TopLevelMenu.vue
It is confusing for users who enable the developer preference to then see the `None` locale in the locale chooser:
This PR updates so that we only show the None locale if you're running as a developer with `yarn dev` - it won't appear in a production build.
> Only show none locale when dev pref is set and running in dev

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/edit/storage.k8s.io.storageclass/provisioners/kubernetes.io/aws-ebs.vue
Add GP3 option for volume type when provisioning AWS EBS storage class
> Support for gp3 for Amazon EBS provisioner

- shell/assets/translations/en-us.yaml
- shell/models/service.js
Service detail page: Show loadbalancer ip or hostname from the service status, if the spec field is empty
Fixes #6245
Currently the external IP is only shown, if it was defined in the Service spec. In most cases the external IP or hostname of a LoadBalancer Service is automatically assigned by the cloud provider though. In that case `spec.loadBalancerIP` is empty. But you can see the assigned information in `status.loadBalancer.ingress`.
This PR shows the information from the status if the spec field is empty.
A lot of cloud providers assign a IP address to a load balancer service (e.g. AKS), but some assign a hostname (e.g. EKS).
Service detail page for services of type LoadBalancer, e.g. in an AKS, EKS or GKE cluster.
Service detail page.
Example on AKS
Example on EKS
> Service detail page: Show loadbalancer ip or hostname from the service status

- shell/edit/storage.k8s.io.storageclass/provisioners/kubernetes.io/aws-ebs.vue
See https://github.com/rancher/dashboard/pull/6243, GP3 should show the Provisioned IOPs field.
From AWS console create volume UI:
> Display provisioned IOPs for GP3 volumes

- shell/components/SortableTable/index.vue
Increase debounce time for the search filter box on the sortable table.
100ms is too small, so we don't actually debounce.
> Increase debounce time for table filter box

- shell/components/form/SelectOrCreateAuthSecret.vue
This PR adds additional details to the auth secret drop down, used for example in the git repo ui of continuous delivery
This makes it easier to pick the right secret if there are multiple ones. 
Fixes #6239
Adds additional, already existing `dataPreview` details to the `SelectOrCreateAuthSecret` component. The `dataPreview` are already displayed as a column in the secrets list.
The component is used in
* Git Repo creation
* RKE2 Cluster creation, etcd S3 backup configuration
* RKE2 Cluster creation, private registry configuration
* RKE2 Cluster creation, advanced registry configuration
* Marketplace repository creation
Areas see above. There should be no regression, because the PR only changes the content of a label.
Screenshot example before
Screenshot examples after in the places where …
> Add more details to auth secret dropdown

- cypress.json
Fixes #6264
Solve timeout related fails on E2E in CI.
Increased default timeout in Cypress config.
As quick solution to unblock current [failing test ](https://github.com/rancher/dashboard/actions/workflows/e2e.yaml)in [other PR](https://github.com/rancher/dashboard/pulls), the timeout is increased.
Issue will be tackled down with https://github.com/rancher/dashboard/issues/5966
Most of the complained errors are now related to [slow authentication process](https://github.com/rancher/dashboard/runs/7177526759?check_suite_focus=true) which is not related to #5966.
-
-
CI process.
> Increase Cypress timeout

- shell/store/i18n.js
- shell/store/type-map.js
Fixes #5913
Switch to simplified Chinese, and the resource search function supports English keyword query. If English matches the result, the content will be highlighted after simplified Chinese.
> Resource search always supports English search

- shell/components/nav/Header.vue
Fixes #6204 
Removed the icons - they don't add any value.
Here's how it looks now:
> Remove icons from the user drop down menu

- .eslintignore
- shell/core/plugin.ts
Fixes #6148
Updated .eslintignore to exclude rancher components folder that exists when the shell package is published
Updated register method to take into account component with index.vue in a folder.
> Add support for nested dynamic components

- docs/developer/forms-and-validation.md
- pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.test.ts
- pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue
- pkg/rancher-components/src/components/LabeledTooltip/LabeledTooltip.vue
- shell/assets/styles/global/_labeled-input.scss
- shell/assets/styles/global/_select.scss
- shell/assets/translations/en-us.yaml
- shell/components/Tabbed/Tab.vue
- shell/components/Tabbed/index.vue
- shell/components/form/Error.vue
- shell/components/form/InputWithSelect.vue
- shell/components/form/LabeledSelect.vue
- shell/components/form/NameNsDescription.vue
- shell/components/form/ServicePorts.vue
- shell/components/form/__tests__/Error.test.ts
- shell/edit/management.cattle.io.project.vue
- shell/edit/service.vue
- shell/edit/workload/index.vue
- shell/mixins/form-validation.js
- shell/mixins/labeled-form-element.ts
- shell/models/workload.js
- shell/plugins/dashboard-store/resource-class.js
- shell/utils/object.js
- shell/utils/validators/formRules/__tests__/index.test.ts
- shell/utils/validators/formRules/index.ts
Adds in form validation mixin for use with cru-resource mixin to validate values in form payload and provide feedback to the user.
Also adds in rule based validation to labeled input fields, fields will display error messages in a rule returns a message, validated in real time.
Specific instructions for both included in developer docs, a few example forms have implemented the mixin and field "rules" property as an example, and a couple additional components have been implemented and/or extended to allow for more robust error messaging to users.
> Adds in form validation mixin, error reporting on inputs, and a few examples

- shell/assets/translations/en-us.yaml
- shell/detail/provisioning.cattle.io.cluster.vue
- shell/models/etcdbackup.js
- shell/models/rke.cattle.io.etcdsnapshot.js
Fixes #5706 
Note the age column problem mentioned in that issue has already been fixed.
For an RKE1 cluster, the snapshots list shows an empty location - this is shown in the group tab (Location: ) with the table: 
How it looks now:
and still works for RKE2 clusters:
For an RKE1 cluster, we determine the location from the presence of an object in `backupConfig.s3BackupConfig` - there are only two possible backup locations: s3 or local.
For RKE2, there is an annotation on the snapshot indicating s3 or local for the location.
This PR moves the logic for the group label (used to group by location) into the models for the RKE1 and RKE2 snapshots. The cluster detail view now uses this property on the model to group by.
To Test:
- Spin up RKE1 and RKE2 clusters and create a snapshot in both
- …
> Fix snapshot location for rke1 clusters being empty

- shell/models/management.cattle.io.project.js
This is a rework of PR: https://github.com/rancher/dashboard/pull/6166
Fixes https://github.com/rancher/dashboard/issues/5964
Update save logic to catch promise errors and pass to CRU form if found
To test:
- Create RKE Cluster
- Create new user (member)
- Enable Pod Security Policy at cluster level
- Add new user to cluster and project
- Log in as new user
- Create new project in cluster and select a pod security policy (eg Restricted)
- Error message should display as banner at top of page
> Errors are not displaying when standard user attempts to create a project with non-default Pod Security Policy

- shell/components/SortableTable/index.vue
- shell/pkg/auto-import.js
Fixes #6147 
Adds support for a `formatters` folder.
SortableTable will look for formatters provided by plugins in this way - also avoids having to make formatters global components.
You can test by creating a plugin, creating a `formatters` folder and copying an existing formatter there (rename it) and then updating a list for a resource type to use this new formatter name.
> Add support for formatters in plugins

- shell/assets/translations/en-us.yaml
- shell/chart/rancher-backup/S3.vue
Fixes #4903 
When using a CA cert for s3 location for Rancher Backup install, reading from file should bas64 encode the certificate.
> Fix Rancher Backup S3 CA field should be base64 encoded

- shell/components/form/LabeledSelect.vue
Addresses a bug which caused https://github.com/rancher/dashboard/issues/5875 to be reopened by QA.
The TL;DR was that after https://github.com/rancher/dashboard/issues/5875 was reviewed and merged, I made another change https://github.com/rancher/dashboard/pull/5999 that broke the secret selector for the AlertmanagerConfig receivers. This PR fixes that.
The more detailed reason for this PR is that the original event listener that I had, which is `option:selecting`, never actually worked:
```
@option:selecting="$emit('input', $event)"
```
I just thought it worked because the `input` event was being emitted by something else anyway. So when I started listening for an event with a different name in this PR https://github.com/rancher/dashboard/pull/5999, the event that I wanted was not …
> Can select secrets for receivers in AlertmanagerConfig

- shell/components/dialog/RotateEncryptionKeyDialog.vue
Fixes #6123 
Simple fix - the close method is wired into the cancel button - it has logic to call the buttonDone function - but in the case of the cancel button, the argument that gets passed to the close method is the click event object - the close method then tries to treat that as the buttonDone function.
Updated to check that buttonDone is a function before it is used.
To test:
- Provision an RKE2 cluster
- Go to the cluster management list and from the action menu for the cluster, choose 'Rotate Encryption Keys'
- Verify that pressing the Cancel button in the dialog now closes it
> Fix can not cancel from rotate encryption keys dialog

- pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue
- shell/assets/translations/en-us.yaml
- shell/layouts/plain.vue
- shell/pages/prefs.vue
This PR fixes https://github.com/rancher/dashboard/issues/5370 by adding an additional description to the 'enable developer tools & features' user preference.
Also:
- Updated the font size of the checkbox description, so that it is readable
- Updated margin of checkbox description, so it aligns with the label
- Added ability to toggle theme with the keyboard shortcut on the prefs page - since the description describes this shortcut, which previously did not work on that screen (plain layout)
> Add description to advanced developer preference

- shell/promptRemove/pod.vue
Fixes #5549 - https://github.com/rancher/dashboard/issues/5549#issuecomment-1181195338
1. Navigate to `Cluster Explorer > Cluster > Deployments > Pod >`
2. Select three dots on the right and select `Delete`
3. Select the force deletion and submit
4. Delete request should have payload `{"gracePeriod":0,"force":true}` 
5. If unticked there should not be a payload
1. Navigate to `Cluster Explorer > Cluster > Deployments > Pod >`
2. From checkboxes on the left select multiple pods and select `Delete`
3. Select the force deletion and submit
4. All Delete requests should have payload `{"gracePeriod":0,"force":true}` 
5. If unticked there should not be a payload
> Set pod forceDelete false by default - #5549.

- shell/pages/c/_cluster/_product/projectsnamespaces.vue
- shell/store/index.js
This PR addresses https://github.com/rancher/dashboard/issues/5088 by making it so that you select projects or namespaces in the top nav of Cluster Explorer, the projects/namespaces list view is updated accordingly. This should avoid a disconcerting experience for users who don't want to see things that are outside of their active filters.
Example of filtering by a namespace:
Example of filtering by a project:
Added filters to the Projects/Namespaces list view
Should try all the namespace/project filtering options in the top nav and make sure they work as expected.
I would expect that the Projects/Namespaces page is the only page that could be affected.
Note: There is a related design issue about reminding users that filters are being applied, but that can be addressed in a separate PR. …
> List of projects/namespaces respects filters in top nav

- shell/machine-config/amazonec2.vue
Fixes #6155 
Updates the presentation of VPC/subnets to be consistent with the old UI and show the names.
Now looks like this:
We now show the names and not the CIDRs are available number of addresses.
To test:
- Go to create an AWS cluster
- Select/create a credential
- Validate the VPC display by clicking on the VPC/subnet drop down
> Improve presentation of VPC/Subnets for AWS cluster creation

- shell/assets/translations/en-us.yaml
- shell/detail/workload/index.vue
This PR addresses https://github.com/rancher/dashboard/issues/4845 by adding two tabs to the workload detail page - one for Ingresses and one for Services.
This change is intended to help users more quickly locate Services and Ingresses that are involved in routing traffic to a given workload.
In the workload detail page (this page is reused for Deployments, StatefulSets, DaemonSets and ReplicaSets), the Services tab now lists all the Services that select Pods in the workload, while the Ingresses tab lists any Ingresses that would direct traffic to one of those Services.
To test this PR, this is what I did. I tested it on a downstream RKE2 cluster on EC2 with the Amazon cloud provider enabled.
1. Created this example Deployment, taken from the upstream Kubernetes docs.
```yaml
apiVersion: …
```
> Add Ingress and Service tabs to workload detail page

- .github/workflows/scripts/pr.js
This PR fixes an issue with the PR automation GitHub action.
It will now ignore fixed issues that are labeled with the technical debt or dev validate labels - these both indicate that the issues does not to be validated/tested by QA, so we should not move it to 'To test'.
> Don't move tech debt/dev-validate issues to test

- shell/middleware/authenticated.js
- shell/store/index.js
- shell/store/type-map.js
This fixes an issue of unsubscribing and resetting the cluster for products that only exist within the explorer for a given cluster.
While a package is strictly scoped to the explorer of a cluster and not accessible from management, any navigation to/from the package would cause the [cluster subscription to be unsubscribed and reset](https://github.com/rancher/dashboard/blob/7145f349ffcc5210aeeab653964814a7c84140e3/shell/store/index.js#L659-L683). This resulted in a timing issue that would cause the cluster to be undefined before the package is loaded.
To fix this issue I added `inExplorer` to the `product` object of DSL to determine if the product is to be scoped to the explorer. If this prop is true, any navigation to/from the product will bypass the `cluster/unsubscribe` dispatch. …
> Plugin in explorer scoped

- package.json
- scripts/ci
- yarn.lock
Fixes #2823 
Use yaml linter for localisation files.
Add this to the ci script that runs on PRs.
Note: This PR does not require QA validation.
> Add support for linting l10n files

- shell/components/formatter/PodsUsage.vue
- shell/models/provisioning.cattle.io.cluster.js
Fixes #6292 
I broke this when I changed the home page to show provisioning cluster objects not mgmt clusters.
This PR fixes that.
> Fix cluster pod count on  home page

- shell/assets/translations/en-us.yaml
- shell/components/fleet/FleetClusters.vue
- shell/config/product/manager.js
- shell/config/table-headers.js
- shell/list/provisioning.cattle.io.cluster.vue
- shell/models/provisioning.cattle.io.cluster.js
Fixes  #2957 - Display nodes' IPs to be displayed from the cluster management --> cluster page
- add getter `get ipaddress` to  `shell/models/provisioning.cattle.io.cluster.js`
- Update the list view `shell/list/provisioning.cattle.io.cluster.vue` to display the nodes' IPs
1. From the navigation Global apps > Cluster Management
2. List view should show list of all the IP addresses of the the nodes associated with a cluster
> Display node IPs in cluster management list view -  #2957

- shell/assets/translations/en-us.yaml
- shell/components/form/Labels.vue
- shell/edit/fleet.cattle.io.cluster.vue
Addresses Github issue: [#6014](https://github.com/rancher/dashboard/issues/6014)
From the interpretation of the issue, the client is trying to reverse-engineer the API used for Rancher to automate some 
tasks, so the goal here is to provide additional information in the form of a tooltip so that the user knows how the relationship between Fleet Clusters and Management Clusters work.
- Add tooltip to fleet cluster labels editor title with appropriate copy
> add tooltip to fleet cluster labels editor title with appropriate copy

- shell/assets/translations/en-us.yaml
- shell/edit/secret/index.vue
Fixes #6076 
This PR adds support for creating a secret with an arbitrary type.
Note: The type of a secret can only be set when creating the secret - it can not be changed once created.
This PR adds another type to the selector screen presented when creating a secret - Custom Type:
When the Custom Type is selected, we now show a drop down and an input box:
This allows the user to enter a custom type name or to select one of the standard types from the drop-down.
> Allow secret type to be set when creating a secret

- jest.config.js
Fixes coverage reports for unit tests.
- Corrects the folder for components (was not updated when plugins changes made)
- Adds utils folder, so that these tests are included in coverage report
> Unit tests: Collect coverage for unit tests and components

- shell/assets/translations/en-us.yaml
- shell/components/Tabbed/index.vue
- shell/components/fleet/FleetClusters.vue
- shell/components/formatter/ClusterLink.vue
- shell/config/product/manager.js
- shell/config/table-headers.js
- shell/list/provisioning.cattle.io.cluster.vue
- shell/models/provisioning.cattle.io.cluster.js
- Fixes #2957 (reverts https://github.com/rancher/dashboard/pull/6320 following discussions between QA and UX)
- Following discussions with UX also make improvements to cluster list and condition warnings
- Cluster list - Make `Explore` button role-secondary
- Cluster list - Better vertical alignment of cluster list conditions fail icon
- Cluster list & detail - Align spacing and icon type of cluster list and detail condition icons
Before
After
> Remove node ip from cluster's list & UX tweaks to cluster list/detail pages

- shell/assets/translations/en-us.yaml
- shell/config/settings.js
This PR addresses https://github.com/rancher/dashboard/issues/6120 by updating the three global setting descriptions:
For the descriptions with 0 values, I also added `When set to 0, the token never expires.` Just in case someone doesn't know what 0 means.
It also adds the global setting `kubeconfig-token-ttl-minutes`.
> Update global token settings

- shell/mixins/form-validation.js
Fixes #6378
Removed errors returned from server from error list that disables "save" button on forms. Should affect all forms currently using the new form-validation (currently just the workload, project, and service forms).
There are two computed properties that aggregate forms errors. Unreported validation errors which are tied into the "errors" prop for CruResource (these are the ones that show up at the top of the form) and Validation errors which are used to disable the "save" button. I simply pulled the errors that the server returned out of the latter computed property.
Repro steps in corresponding issue should be sufficient.
N/A as far as I know.
> Server errors should no longer disable save functionality on forms

- shell/utils/object.js
Fixes #6223 
This PR fixes some over-zealous code in the cleanup function.
To reproduce:
- Go to a cluster, click on the 'search' icon, and go to 'ClusterRole'
- Find a cluster role (e.g. admin) and click 'Edit Config'
- Click 'Edit as YAML'
- Verify that you see :
```
- apiGroups:
- ''
```
The problem is when you switch to 'Edit as YAML' from the from, we clone the resource and run it through the `cleanup` function. This was removing empty values - it was going through Arrays and removing falseys - this seems problematic, as a. valid array like this:
```
test:
- false
```
would be removed.
This PR removes the cleaning up of arrays like this - we no longer remove falsey values and we don't cleanup the values themselves.
> Fix empty API Group when edit as yaml for role

- shell/assets/translations/en-us.yaml
- shell/edit/management.cattle.io.node.vue
- shell/models/management.cattle.io.node.js
Addresses Github issue: [#5951](https://github.com/rancher/dashboard/issues/5951)
- provide interface to edit node name (custom name) for RKE1 nodes
> provide interface to edit node name (custom name) for RKE1 nodes

- shell/layouts/default.vue
- shell/list/management.cattle.io.setting.vue
Fix cluster to cluster nav issue
- the outlet was showing prematurely
- now we only show the backup outlet for 404 errors if there's a 404 situation
Fix settings page when there are unknown resource setting
- https://github.com/rancher/dashboard/pull/6351 added additional `ALLOWED_SETTINGS` to the UI
- in older systems this resource setting does not exist
- the settings page `fetch` would return early if it encounters settings that do not exist, leaving the `settings` array un-initialised
- fix is to `continue` instead of `return`
> Fix two navigation issues

- shell/config/table-headers.js
- shell/list/node.vue
Fixes #6403
This PR improves the performance of the Nodes list by not waiting for pods to load before showing the node detail.
Once pods load, the pods usage column will update.
On systems with large number of pods, the user had to wait until all of the pods loaded before they could view the nodes.
> Performance: Don't block nodes table on fetching pods

- shell/plugins/steve/subscribe.js
- shell/utils/socket.js
Fixes #5093 
The socket disconnect notification wont be dispatched until the socket is disconnected for 10 seconds. Notifications wont be removed until they have been visible for at least 3 seconds. These numbers are arbitrary; we can be even more conservative about sending growls if they still seem excessive.
I tested this by upgrading my rancher instance and watching both the locally-running and its actual ui side by side.
> delay showing and removing socket disconnects

- shell/edit/auth/azuread.vue
Fixes  #6236
The migration annotation lives on the norman authconfig object, which is `model` not `value` in the azuread edit component - https://github.com/rancher/dashboard/blob/master/shell/mixins/auth-config.js#L83-L87
> fix azuread update btn

- shell/assets/translations/en-us.yaml
- shell/edit/resources.cattle.io.backup.vue
- shell/utils/validators/formRules/index.ts
Add in form validation on "name" field when creating and editing backups. Checks if name conforms to dnsLabel and noUpperCase validation.
Fixes #5903 
should provide live user feedback to user if the "name" field in the rancher-backup form is out of spec.
* If the field contains upper-case letters
* If the field contains invalid characters such as "_"
Standard implementation of form-validation
> Fixes #5903

- shell/detail/provisioning.cattle.io.cluster.vue
- shell/models/cluster.x-k8s.io.machine.js
Fixes #5773
For RKE2, when you scale down a machine pool, there are no machine deployments in that pool, so we don't show the machine pool.
This PR fixes this - fakeMachines has been updated to work correctly when there are no machine deployments in a pool
To test:
- Bring up an RKE2 cluster with 2 machine pools.
- In the 2nd pool, scale down the pool to 0
- Verify that the pool is still shown as empty
- Verify that you scan scale the pool back to 1
Note: There is a slight issue when scaling that the pool ordering changes briefly - I think this is minor and we can live with this.
> Ensure that we show empty machine pools

- shell/assets/translations/en-us.yaml
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
This PR addresses https://github.com/rancher/dashboard/issues/6376 by allowing a user to reveal deprecated Kubernetes patch versions when provisioning RKE2/K3s clusters, which can be useful when migrating from another Kubernetes distro.
When you go to provision an RKE2/K3s cluster, the default Kubernetes version dropdown menu is unchanged:
Below the dropdown, there is a new checkbox to reveal deprecated patch versions:
There is a tooltip that explains that the deprecated versions are a bad idea unless you are migrating:
When the box is checked, all but the most recent minor versions are marked as deprecated:
I confirmed that I could successfully provision a v1.21.12 cluster, whereas our supported version is v1.21.14:
> Allow user to select deprecated K8s patch versions

- shell/pages/c/_cluster/_product/projectsnamespaces.vue
https://github.com/rancher/dashboard/issues/5088
This PR addresses feedback from QA that the namespace list was inconsistent between the top nav and the Projects/Namespaces page in Cluster Explorer. https://github.com/rancher/dashboard/issues/5088#issuecomment-1184915725 It changes the table to match the top nav instead of the other way around because Nancy explained that the top nav is more accurate: https://github.com/rancher/dashboard/issues/5088#issuecomment-1184933250
To test this PR, I filtered the top nav to show "Not in a project" namespaces and confirmed that the list items to choose from in the top nav matched the results in the tables.
This PR also:
- Fixes an undocumented bug in which, if you filter by a specific namespace, you would see empty projects on the page. For …
> Namespace results are consistent in top nav and Projects/namespace page

- shell/assets/translations/en-us.yaml
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
- shell/utils/validators/formRules/index.ts
#5927 - this came through from Harvester but appears to apply to provisioning.cattle.io.clusters generally. The error returned for a DO rke2 cluster is `Cluster.provisioning.cattle.io "BAD" is invalid: metadata.name: Invalid value: "BAD": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`
> add subdomain validator to prov cluster metadata.name

- shell/assets/translations/en-us.yaml
- shell/edit/monitoring.coreos.com.prometheusrule/index.vue
- shell/models/monitoring.coreos.com.prometheusrule.js
- shell/utils/validators/prometheusrule.js
Fixes #5820 
Added in form validation for relevant form. This surfaced a bug in the customValidationRules getter in the model which was fixed by adding a default value to the customValidatorFunction. Also removed edit and clone options from action menu for prometheusRules that can't be edited because the helm-created rules have an invalid name that can't be changed.
> Add in form validation to prometheus rule. Fix model validation error.

- shell/models/management.cattle.io.globalrole.js
- shell/models/management.cattle.io.roletemplate.js
Fixes #6212
The main issue of not being able to update roles was actually due to the role being `builtin`, as in this is a Rancher specific role that ***cannot*** be updated or deleted. In the old UI we actually prevent the user from being able to update or delete a role by disabling the inputs.
Instead of disabling all of the inputs, a quick fix here would be to disable the actions for editing/deleting from the resource itself.
If the role has `builtin: true` we will disable the `goToEdit` and `promptRemove` actions. 
You should be able to create a role and still have the ability to edit/delete.
_`builtin` role has no edit/delete action_
_The old UI for reference_
> Edit actions for builtin roletemplates and global roles

- shell/chart/rancher-alerting-drivers.vue
Provide extra feedback to the user until form-validation can be added and also adds in a default value for "Enable SMS" so we're not loading the form in an invalid state.
Fixes #5924 
Provide extra feedback to the user until form-validation can be added and also adds in a default value for "Enable SMS" so we're not loading the form in an invalid state.
Greying out the "Install" button will have to be part of a larger effort after technical evaluation. Providing more clear user feedback should prevent the user from installing this chart with invalid values in the interim.
* Values step should load with "Enable SMS" preselected. When installed without touching the form, payload should include "sachet.enabled" as being true.
* Banner informing the user that they must select at least one of …
> Provide extra feedback to the user until form-validation can be added

- shell/assets/translations/en-us.yaml
- shell/components/form/ServicePorts.vue
- shell/utils/validators/formRules/index.ts
Fixes #4238
Some small issues arose during testing of serviceports
* Node Port and Listening Port now report errors when outside of port ranges
* Node Port and Target Port no longer allow extra characters (note that decimal points with no numbers and/or 0s following them are simply trimmed by the input instead of caught by validation
Reworked Serviceport validation. Potentially worth breaking up into several smaller validators in the future
> Resolves issues with ServicePort validation

- shell/components/formatter/ClusterProvider.vue
- shell/models/management.cattle.io.cluster.js
- shell/models/provisioning.cattle.io.cluster.js
This PR addresses https://github.com/rancher/dashboard/issues/6352 by making it so that the **Provider** column in the list of clusters labels ONLY imported clusters as imported, while hosted Kubernetes clusters do not get a label in that column:
Previously, the imported label was added by default. I changed it so that now we check to see if the cluster is imported before adding the label.
Normally I would have used the `isImported` getter on the provisioning cluster model to check if a cluster is imported. However, the `isImported` getter is broken - it returns `k3s` instead of `import` as the provisioner for an imported K3s cluster. I was afraid to fix the getter because I thought that changing its output could introduce bugs close to the 2.6.7 release, so I used a workaround. The …
> Only label imported clusters as imported

- shell/promptRemove/management.cattle.io.project.vue
Fixes bug where you can't delete a project without deleting the namespaces in it - dialog stays open with the button greyed out.
Addresses re-opened #5624
> FIx bug where deleting project on its own did not work

- shell/pages/prefs.vue
- minor fix to prevent Vue warning on console due to undefined variable `isSingleVirtualCluster`
@nwmac quick fix for that issue we talked about yesterday 🙏
> minor fix to prevent Vue warning on console on User Preferences

- shell/components/SortableTable/index.vue
- shell/components/formatter/LivePodRestarts.vue
- shell/components/formatter/WorkloadHealthScale.vue
- shell/config/table-headers.js
Addresses #6457
This PR improves performance of the workload view significantly.
Currently, the live and delayed columns update almost every second on a system where there is activity.
This PR changes the restarts and workload health columns to be live columns that only update every 5 seconds.
It also fixes an issue in the way these are updated - the `updated` lifecycle hook was being used, but this is triggered when anything on the component changes, which leads to the live and delayed columns updating a lot. We now do an initial trigger and then trigger when the page is changed by the user.
To Test:
Verify that the on the workload page, the Restart Count and Health columns still show and update correctly as you change pages and enter the page. Also check that you can add new …
> Performance: Fix issues with live and delayed columns

- shell/models/workload.js
- shell/plugins/dashboard-store/mutations.js
- shell/plugins/steve/getters.js
- shell/plugins/steve/index.js
- shell/plugins/steve/mutations.js
Caches the pods in each namespace and uses this in the workload model so that it is only filtering over the number in a given namespace, not the entire list of pods.
Helps to address #6457
> Performance: Cache pods by namespace

- shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes Harvester CPI does not work after upgrade RKE2 version
- https://github.com/harvester/harvester/issues/2546
- https://github.com/rancher/rancher/issues/38336
1. Upgrade the RKE2 version 
2. Check the CPI whether work
> HARVESTER: Fix Harvester CPI does not work after upgrade RKE2 version

- shell/models/management.cattle.io.clusterroletemplatebinding.js
- shell/models/projectroletemplatebinding.js
Fixes #6442 
This seems to be a pretty straightforward fix: If a `roleTemplate` is deleted some template binding getters throw an error. There's a harvester resource in the screenshotted stack trace but I looked through cluster/project role template/role template binding code and couldn't find any harvester references, so I think these getters are all that need to be fixed here.
> fix roletemplatebinding models

- assets/translations/en-us.yaml
- components/auth/AuthBanner.vue
- components/auth/AzureWarning.vue
- config/labels-annotations.js
- edit/auth/azuread.vue
- layouts/default.vue
- layouts/plain.vue
- store/auth.js
#6316 - in 2.5 it's possible to set your after-login route to the dashboard, in which case you wouldn't see the warning added in Ember (https://github.com/rancher/ui/pull/4873) so I've ported that over and updated the hardcoded endpoints. Unlike 2.6, I've opted to link out to the ember auth page from the warning banner: dashboard auth (including azuread) had fixes in 2.6 so it would be better for users to re-configure auth through the Ember UI.
Waiting on https://github.com/rancher/rancher/issues/37228
> [2.5]backport azuread endpoint migration

- shell/models/management.cattle.io.project.js
This PR addresses https://github.com/rancher/dashboard/issues/6377 by changing the order of what happens when we save a new project. If we fetch projects before updating the podsecuritytemplate, we avoid a version conflict.
I also removed the `forceReplaceOnReq` variable because it was always undefined and a search revealed that it was not being passed in by anything.
To test the PR, I created a bunch of projects, waited until I saw the 409 error in the console, and confirmed that the project was successfully created with no errors in the UI.
> Retry project creation after 409 error

- shell/list/node.vue
- shell/pages/c/_cluster/explorer/index.vue
- shell/plugins/dashboard-store/actions.js
- shell/plugins/steve/mutations.js
Fixes #6431
This PR exposes forgetType as an action and adds in un-watching of the type as well.
It wires this into the cluster dashboard and nodes page, un-watching Steve types that are used in those pages.
In particular, the cluster dashboard page watches events - which can be changing quite regularly, so if you then change to another page, we still get event messages, even though  we're not showing them anywhere.
On the nodes page, we fetch pods, which can also be changing a lot. These will now also be un-watched. Other pages do use pods, so the downside is that if you are looking at deployments and go to nodes, when you go back, the pods will have to re-load - but this should not block the page, just the time taken for certain columns to have the pod data to be able to update. …
> Performance: Unwatch some resource types on cluster dashboard and nodes pages

- shell/assets/translations/en-us.yaml
- shell/components/nav/NamespaceFilter.vue
- shell/models/namespace.js
- shell/pages/c/_cluster/_product/projectsnamespaces.vue
- shell/pages/prefs.vue
This PR addresses https://github.com/rancher/dashboard/issues/6465 by hiding auto-created RBAC namespaces starting with `p-`. After this change, you should only be able to see the namespaces beginning with `p-` by going to the user preferences and turning on the developer tools.
I've updated the description of the developer tools to explain that it changes what namespaces you see:
This PR updates the namespace filtering logic in the top nav to make it consistent with the list view. The top nav now also shows the RBAC namespaces based on the user preference set in the developer tools.
With the developer tools turned off:
With the developer tools turned on:
1. I created a project and namespace in a downstream cluster
2. Got the project ID from the project's YAML
3. Went to …
> Hide auto-created RBAC namespaces

- shell/edit/provisioning.cattle.io.cluster/index.vue
This PR addresses https://github.com/rancher/dashboard/issues/5922 by updating the conditional logic that renders the read-only config form for custom K3s/RKE2 clusters.
The route of this read-only form is `rancherServerUrl/c/c-m-4brtk95v/manager/provisioning.cattle.io.cluster/fleet-default/catherine-test-custom?as=config`. This PR makes it so that now we render the custom cluster form using the `as=config` query param.
Previously, you could still get to the correct form by going to the context menu and clicking Edit Config. This PR only affects the Config view that you can get to from the cluster detail page in Cluster Management:
When the Config button is clicked, it now shows the correct config form in read-only mode:
> Render the correct form for imported RKE2 clusters

- shell/edit/provisioning.cattle.io.cluster/index.vue
Fix related to changes here: https://github.com/rancher/dashboard/pull/6467
On create, `value.isCustom` is briefly true because no `machinePools` have been added to the spec. This causes `this.selectType('custom', false);` to be called, preventing any custom driver components from rendering.
> do not set driver type using isCustom on create

- shell/edit/service.vue
- shell/utils/validators/formRules/index.ts
Fixes #6511 
regex being used to test if string was a valid number was incorrect, refactors to use the same port class that validation uses to determine if a port is an integer or not and correct the payload accordingly.
> Fixed issue where willSave() was not detecting if targetPort was number

- shell/pages/c/_cluster/explorer/index.vue
This PR makes a minor improvement to the cluster dashboard page:
- Un-watches the ENDPOINT type that is used by the alerts table when v2 monitoring is installed
- Only renders the alerts table when its tab is active - prevents background polling when not active
> Minor improvement to cluster dashboard page for alerts tab

- shell/components/nav/HarvesterUpgrade.vue
- shell/middleware/authenticated.js
Fixes namespace filter wrong on Harvester page
- https://github.com/harvester/harvester/issues/2578
- https://github.com/harvester/harvester/issues/2587
- When load harvester store(`loadVirtual`), the product id is `harvesterManager`, thus the store will be 'management', which causes the namespace to be obtained from the management store instead of the harvester store. 
https://github.com/rancher/dashboard/blob/647b917ed34c6cc09eea21a40fd9fb7ffd8ef95d/shell/store/index.js#L82-L84
- Check schema in case of throw console error in `loadVirtual`.
> HARVESTER: Fix namespace filter wrong on Harvester page

- shell/components/ResourceTable.vue
- shell/components/nav/Jump.vue
- shell/components/nav/WorkspaceSwitcher.vue
- shell/layouts/default.vue
- shell/middleware/authenticated.js
- shell/pages/c/_cluster/_product/projectsnamespaces.vue
- shell/pages/c/_cluster/explorer/tools/index.vue
- shell/pages/c/_cluster/fleet/index.vue
- shell/store/index.js
Part 1
- This was broken by https://github.com/rancher/dashboard/pull/6261
- The `activeNamespaceCache` depends on the product (fleet requires workspaces, everything else namespaces)
- This needs updating when going to or from fleet
Part 2
- When changing the filter (workspace or namespace) switching between selections that contain the same number of results/rows wouldn't change the rows. 
- This is more obvious on the fleet/workspace world where the filter switches between two values, rather than the explorer/namespace filter which toggles values on or off  (making it unlikely to go from one state to another with the same amount of rows)
- The fix is to ensure the lists take into account the ns filter, alongside things like row count, sort settings, etc)
NOTE - On `head` (but not …
> Fix workspace filtering

- pkg/rancher-components/src/components/Card/Card.vue
- shell/components/PromptModal.vue
- shell/components/dialog/AddProjectMemberDialog.vue
- shell/components/form/Members/MembershipEditor.vue
- shell/components/form/Members/ProjectMembershipEditor.vue
Fixes #6499 
This PR:
- Adds 'sticky' property so that a dialog can support content where header and footer are sticky
- Wires this into add members dialog
Result:
To Test:
- Create a few project roles
- Go to the local cluster -> Cluster -> Projects/Namespaces.
- Choose a project and from the three dots, choose 'Edit Config'. Click 'Add' beneath members.
- Shrink the height of the browser window
- Verify that the middle content of the dialog scrolls - as shown above
> Improve presentation of add Member dialog

- shell/edit/monitoring.coreos.com.alertmanagerconfig/types/webhook.vue
This PR fixes https://github.com/rancher/dashboard/issues/6526 by making it so that the webhook type is correctly persisted after a receiver of type webhook is configured. To test, I did the same steps as the steps to reproduce in the issue description. Alibaba SMS, MS Team, and Generic types should all be persisted when coming back to the config form.
> Selected webhook type is persisted in UI

- components/auth/AzureWarning.vue
#6516 - I thought I saw this issue in Ember yesterday but can't repro so I guess I was mistaken. Anyway the issue here is that norman annotations are mapped to _annotations:
https://github.com/rancher/dashboard/blob/a2755a358159343aa78c0c96b3325cce7ccb3873/plugins/steve/resource-proxy.js#L113-L116
> [2.5] fix annotation path in azuread warning banner

- .gitignore
- scripts/standalone/dashboard
- scripts/standalone/index.js
- scripts/standalone/package.json
- scripts/standalone/package.sh
- shell/nuxt.config.js
This PR adds a script in `shell/scripts/standalone/package.sh` - this when run from its parent folder will generate `dashboard.tar.gz` - a standalone package which can then be installed on a machine and browsed to test out the latest UI against an existing backend.
You need to run this on the same target platform as you intend to run it on (e.g. linux etc).
This bundles in the node executable as well from the host machine.
> Script to create standalone build for testing

- shell/components/auth/AzureWarning.vue
Fixes #6528 - this bug isn't related to backups specifically. The (unnecessary) blank cluster param in the azuread update link causes `loadCluster` to run and 'reset' the store then trigger a nav re-calculation when schemas are not loaded.
> fix azure warning banner link

- shell/machine-config/amazonec2.vue
Fixes #6566
I didn't see this bug until I switched the machine pool's zone from us-west-1 to us-east-2. Using the fallback for un-named vpcs already in place, `SubnetId`, caused duplicate key errors. Setting `optionKey` on the select resolves this without otherwise altering functionality.
> do not assume ec2 vpc obj have Tags

- plugins/steve/mutations.js
Fixes #6516  
https://github.com/rancher/dashboard/issues/6516#issuecomment-1200473823
The AzureAD upgrade warning banner re-appears when a user visits the auth provider detail page. When the config view for a specific auth prover is loaded the authConfig mixin will always send an api request for the norman config object by using the `force` option.
If a resource being loaded from a network request is already in the store, the steve plugin `load` mutation overwrites the existing object in the store key by key. Because this overwrite data is never run through `proxyFor`, `remapSpecialKeys` is not called on it, and the norman keys that intersect with resource-class methods are not properly remapped. In this case, `value.annotations` needs to be mapped to `value._annotations`. 
As far as I …
> [2.5] fix issue with force-reloading norman objects

- shell/edit/monitoring.coreos.com.prometheusrule/GroupRules.vue
This PR addresses https://github.com/rancher/dashboard/issues/6478 by modifying the default values for a new alerting rule so that it now creates a new label for `namespace=default`.
1. I installed monitoring.
2. In the side nav of Cluster Explorer, I went to **Monitoring > Advanced > PrometheusRules**.
3. Clicked **Add Alert**.
4. Confirmed that in the form that appears, a default `namespace=default` label is there.
5. Created the resource and confirmed the YAML was saved properly:
```yaml
spec:
groups:
- name: rancher-qa
rules:
- alert: rancher-qa
expr: vector(1)
for: 0s
labels:
severity: none
```
6. Confirmed the saved value renders correctly in the detail view
> When adding alerting rule, provide a default namespace label

- shell/middleware/authenticated.js
Fixes #6572 
- fix issue when on first login we were setting an empty value to `state.workspace` because user doesn't have an prefs set at that point in time
How to test:
- spin up a new system (rancher backend + rancher dashboard on head)
- enter `continuous delivery` (Fleet) right after first login
- make sure `workspace` filter has a first value set (defaults to `fleet-default` workspace)
**Before**
**After**
> Fleet: Fix empty workspace filter on first login

- shell/models/management.cattle.io.project.js
I was able to debug https://github.com/rancher/dashboard/issues/6464 after logging into Anu's setup.
The error was caused by the fact that the cluster member did not have permission to list projects using the Steve API:
```
projects.management.cattle.io "p-6rkkp" is forbidden: User "u-w9kcq" cannot get resource "projects" in API group "management.cattle.io" in the namespace "c-6jf6l"
```
The culprit was this line of code, which attempts to refetch all projects immediately after creating a project. It requires admin access to be able to list resources in the local cluster:
```
await this.$dispatch('management/findAll', { type: MANAGEMENT.PROJECT, opt: { force: true } }, { root: true });
```
I believe the line is unnecessary because I created several projects as the cluster member and the …
> Remove unneeded API call to get projects from local cluster

- shell/components/form/PodAffinity.vue
- shell/edit/harvesterhci.io.virtualmachinetemplateversion.vue
- shell/edit/kubevirt.io.virtualmachine/VirtualMachineReserved.vue
- shell/edit/kubevirt.io.virtualmachine/index.vue
- shell/machine-config/harvester.vue
- shell/mixins/harvester-vm/index.js
Fixes VM issues
- https://github.com/harvester/harvester/issues/2593
- https://github.com/harvester/harvester/issues/2589
- https://github.com/harvester/harvester/issues/2577
- https://github.com/harvester/harvester/issues/2598
- https://github.com/harvester/harvester/issues/2567
- `cloneValue` is a steve model and loss most of the spec property, need to `cloneSpec` to clone the real spec.
- Wrap reservedMemory as a component is a workaround for avoiding `$attrs` changed every time when the resource is updated by the Websocket. 
https://github.com/rancher/dashboard/blob/5d4e32e85545eeb3ff35258db4eda3063cc3a4ba/shell/components/form/UnitInput.vue#L215
> HARVESTER: Fix HARVESTER v1.0.3 VM issues

- shell/components/ResourceTable.vue
fixes #6596 
If this is not true, resource table filters its rows wrt the namespace filter (and calculates active namespaces to do so):
`if ( (!this.isNamespaced || isAll) && !isVirtualProduct)` 
The logic here is a little off. We don't want to attempt to filter by ns if the resource is not namespaced, regardless of whether it's a harvester resource or not. "Why does this cause an infinite loop in the project/namespace list specifically?" You may ask. Good question. I think this is because the project/namespace list component also retrieves namespaces via getter and these two calls are causing each other to re-calculate. Regardless, that `if` block is wrong and fixing it fixes the bug.
> do not attempt to filter by namespace for any unnamespaced resource

- cypress/support/commands.ts
- cypress/support/e2e.ts
- cypress/tsconfig.json
- types/userPreferences.d.ts
Fixes #6300
As in issue description.
None.
- #6537
- Added `userPreferences` command to reset or override values
- Added UserPreferences interfaces with the keys, not values as are unknown
- Added global types folder to Cypress tsconfig.json, for distributed types
Add `cy.userPreferences({ theme: '\"ui-dark\"' });` to test changes in the UI, based on this configuration. E.g. theme.
None.
> Reset user preferences on E2E start or requests

- shell/layouts/default.vue
- shell/middleware/authenticated.js
- shell/pages/c/_cluster/explorer/EventsTable.vue
- shell/pages/c/_cluster/explorer/index.vue
- shell/pages/home.vue
- shell/utils/promise.js
Fixes #6504
This improves first load experience of the dashboard's home and cluster dashboard pages. On fast systems there won't be much difference, but on slow rancher instances, slow clusters and/or slow host machines this PR should speed up the time the pages show. Content that was blocking these pages should either show a loading indicator or show eventual (some areas are conditional, not just waiting to be loaded).
Home Page
- Don't block whole page on loading of mgmt and prov clusters
- Use table `loading` indicator when clusters are loading
- Use correct cluster count (with harv cluster filter)
Cluster Dashboard
- EventsTable - use standard table loading indicator
- Don't block on fetch at all (or show page loading indicator)
- Remove fetch for nodeTemplates and rke1NodePools. I …
> Improve initial load of Home and Cluster Dashboard pages

- shell/assets/translations/en-us.yaml
- shell/nuxt.config.js
- shell/pages/about.vue
- shell/pages/diagnostic.vue
- shell/plugins/console.js
Fixes #6544 
- Adds `diagnostic` page, accessible via the `about` page
_Firefox, Safari_
_Chrome, Edge_
_Dark mode_
> Create `diagnostic` page

- shell/components/form/NameNsDescription.vue
- shell/pages/c/_cluster/_product/projectsnamespaces.vue
Fixes #6594
Users who have no overarching view of the cluster (non-rancher admins, non-cluster owners)
- shouldn't see namespaces outside of their projects
- shouldn't be able to create namespaces outside of their projects (specifically not in a project)
The original issue talks about project owners and members. However those can be tricky to work due to cross over with rancher admins and cluster owners (they can use feature but may or may not have any of the project roles). 
So to make it simpler i thought this should be restricted to rancher admins and cluster owners. To determine this though global and cluster roles have to be fetched, with are resource hungry. Given this will be used in many places opted for something simpler.
In the end choice if the user can `update` the management …
> For certain roles hide concept of namespace outside of groups

- shell/layouts/default.vue
- shell/store/index.js
- fixes #6609
- Caused by `filteredRows` running causing `getActiveNamespaces` to run.. which in tern triggers other table's `filteredRows`, etc
- Fix is to only update `activeNamespaceCache` if there were actual changes
- Tested
- ns detail page
- project/namespaces list
- fleet resources
- fleet resources where there are only 1 entry in two workspaces
This also fixes an issue where the resource counts in the side nav bar failed to update. This fix is dependent on changes in this PR
> Fix namespace detail page when a namespace filter is applied

- shell/assets/translations/en-us.yaml
- shell/pages/c/_cluster/_product/projectsnamespaces.vue
- shell/promptRemove/management.cattle.io.project.vue
fixes #6594 
#6599 is incomplete; users who shouldn't be able to see namespaces outside projects can still create them with a little chicanery: 
https://user-images.githubusercontent.com/42977925/183220653-05030b58-5ca9-4bf0-9d9a-c6cb3cbbf3ba.mov
With this PR: 
https://user-images.githubusercontent.com/42977925/183220913-a68fda15-7695-4a28-b474-b8cd3e669800.mov
This PR aims to resolve that by:
-  forcing users who can't see project-less namespaces to delete their namespaces with project deletion
- hiding the 'create namespace' button on the 'Not in a Project' group if the user shouldn't be able to create ns outside of projects.
I wasn't able to reproduce that creation error-but-it-actually-worked bug in the first vid.
> prevent creation of ns outside of projects for certain roles

- .github/workflows/check-plugins.yaml
- .github/workflows/test.yaml
- pkg/epinio/models/applications.js
- shell/components/PromptRemove.vue
Fixes # https://github.com/epinio/ui/issues/134
Added a new method to `EpinioApplicationModel` to be used on `PromptRemove` component.
1. Create a new APP under https://localhost:8005/epinio/c/default/applications/createapp
2. Open the interactive menu (3 dots, top right) and click Delete
3. Confirm the action
Expected behavior:
- You should get redirected to  https://localhost:8005/epinio/c/default/applications & the create button should take you to the Create App wizard.
> [Epinio] Redirects to the correct route after removing an application

- pkg/epinio/components/application/AppSource.vue
- shell/components/form/FileSelector.vue
Fixes # https://github.com/epinio/ui/issues/143
Added a new prop to `FileSelector` component, 
Added a new prop called `accept` to `FileSelector` component (default allows all) which takes file formats that we want to allow.
Uses HTML Attribute :accept , supported as Chrome 16 +, Safari 6 +, Firefox 9+ , IE 10 +,  Opera 11 +
> [Epinio] Limits the files format of the file allowed to be uploaded

- shell/assets/translations/en-us.yaml
- shell/edit/provisioning.cattle.io.cluster/CustomCommand.vue
https://github.com/rancher/dashboard/issues/5995#issuecomment-1206817132
- Create an RKE1 custom cluser
- Select these options to make it a windows cluster 
- View the Cluster Mangement detail view of the cluster to see the message
Windows rke1:
Not-windows rke1:
> Adding a windows deprecation banner to the registration command of rke1 clusters

- pkg/epinio/windowComponents/ApplicationLogs.vue
- shell/utils/socket.js
- epinio uses a token in url for auth
- on socket re-connect we need to re-fetch the token
- partially addresses https://github.com/epinio/ui/issues/148 (specifically https://github.com/epinio/ui/issues/148#issuecomment-1209223473)
> [Epinio] Allow app logs to re-supply socket url on re-connect

- scripts/standalone/package.sh
- shell/components/ResourceList/index.vue
- shell/nuxt.config.js
- tsconfig.json
Script Changes
- fixed `require` errors
- ensure dashboard ignores output of scripts (useful for local dev)
Dashboard Changes
- only show the resource loading indicator if incremental loading is enabled
> Fix package script and visibility of incremental loading indicator

- shell/components/SortableTable/paging.js
- run condition to set page if the total pages are at least 1 in order to prevent resetting the current page when there are no results on the list
> Fix pagination with manual refresh

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
Updates the issue template and splits out into 3 templates, each of which sets the appropriate `kind` label.
> Add issues templates that set labels

- shell/assets/translations/en-us.yaml
- shell/components/GrowlManager.vue
- shell/models/provisioning.cattle.io.cluster.js
Fixes #6623 
Adds a growl for the copy to clipboard for the kube config from the cluster management list.
This PR also tidies up the notification, so that when it does not have a message, it looks a bit nicer:
To test:
- Go to the cluster management page
- For any cluster, open the action menu from the three dots on the right
- Choose the 'Copy KubeConfig to Clipboard' option
- Verify that you see a notification like the one in the image above
> Add feedback that kube config has been copied to clipboard

- shell/models/service.js
- shell/plugins/dashboard-store/actions.js
- shell/plugins/dashboard-store/getters.js
Fixes #6619 
PR ensures we filter the pods by namespace.
Steps to test are in the linked issue.
Before: Service shows pods from other namespace
After: Services shows pods only form the namespace it is in
> Fix service shows pods from other namespaces

- shell/edit/cloudcredential.vue
Fixes #6584 
Simple fix for bug above.
The Cloud Credential is a Norman resource, so we need to se4t the description key for the NSNameDescription component.
To Test:
- Create a Digital Ocean Cloud Credential with a description
- Edit the credential and change the description (note you need to provide the token again)
- Verify that the new description shows in the list
> Bug fix for can not edit cloud credential description

- shell/edit/workload/types/Deployment.vue
- shell/edit/workload/types/Generic.vue
Fixes #6443 
Simple fix - the case of the `priorityClassName` was incorrect.
To test:
- Create a new deployment
- Edit the deployment, go to pod and resources and enter a name in the Priority Class Name field
- Validate that this field is stored by editing the deployment again
> Fix pod priority class name field

- shell/assets/translations/en-us.yaml
- shell/edit/persistentvolumeclaim.vue
Fixes #6444
This PR fixes the above issue.
The problem is that we don't check if the user has permission to list storage classes or persistent volumes and this causes the fetch code path to break.
This PR updates this to check permissions and to use input boxes rather than select components - the user still has permission to create a PVC, so we don't block, we just aren't able to show them the existing options.
It also adds a tooltip explaining this.
Issue #6444 was about persistent volumes, but the bug was also there if the user did not have permission to list storage classes - this PR fixes both.
The linked issue describes steps to reproduce, but to test:
- As Admin, create a new Standard User
- Create a new Cluster Role named 'Custom Storage' and add Verbs '*' and Resource …
> Fix RBAC issues with PVC creation

- shell/components/formatter/PodImages.vue
Fixes #6293 
This PR tries to avoid showing the istio sidecar container image for a pod as the main image - so that it is more likely that the user sees the main pod rather than the istio one.
To test, you don't need to install Istio:
- Create a deployment with two containers, the first should use the image `istio/proxy` and the second `nginx`
- Before this PR you'll see that the istio image is shown as the main image
- After this PR you should see nginx as the main image show
- Verify that hovering over the image name still shows the list of all images
- Change the image of the first container to 'gcr.io/istio-release/proxy' and then 'rancher/mirrored-istio-proxy' and after doing so, verify that nginx is still shown as the main image
> Prefer non-istio image when showing main image for a workload

- .github/workflows/release-rancher-components.yml
- package.json
- pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.test.ts
- pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue
This introduces a github action for publishing @rancher/components to npm. I considered automating this process a little bit by automatically creating release when merging into a release branch, but I decided to walk things back a little bit and keep the release process relatively similar to what we already do today with our other releases. 
For this release, we explicitly choose to only lint, test, and build anything located under `pkg/rancher-components`. I think it might make sense to publish storybook along with releases of the Rancher Component framework, but we already publish changes to storybook on a much more frequent basis than we would with our releases. For this reason, it makes sense to follow up in a separate PR if we think this is needed.
It might make sense to publish a …
> Create github action for publishing @rancher/components to npm

- pkg/rancher-components/types/index.d.ts
This updates the name of the `BadgeState` so that it accurately reflects the source. Doing this will fix an issue where tsc will display an error when attempting to import `import { BadgeState } from '@rancher/components';`
```
import BadgeState
Module '"@rancher/components"' has no exported member 'BadgeState'.
```
Fixes #6655
> Update the name for BadgeState type export

- pkg/rancher-components/src/components/Form/Radio/RadioButton.vue
This change upstreams the inclusion of the description slot for `RadioButton.vue`. 
This slot was a customization used by Rancher Desktop to provide arbitrary content to a radio button's description. For example, using code blocks in the description:
`descriptionKey` & `description` props should take priority over the slot in order to preserve backward compatibility. 
We need to look out for regressions in `RadioButton` usage. Performing a search for `RadioButton` should provide a wide array of examples to test. Since this slot is optional, there should be no change to the existing radio button implementations. Any observed change in output is to be considered a regression. 
closes #6649 
> Add a description slot to RadioButton

- shell/package.json
Fixes PRs failing the plugin gate check.
Will need to fix a different way, but this will unblock things for now.
> Bump shell package version

- shell/models/cluster/node.js
Fixes #6641
- We determine the cluster id via the node's `self` link
- Normally this is something like `k8s/clusters/c-m-274kcrc4/v1/nodes/nodeid`. However for the local cluster this is only `v1/nodes/nodeid`
- This meant that for local cluster nodes it's norman and mgmt nodes were unavailable
- From what i can this only affected it's ability to
- determine it's role (though this had a working fallback)
- determine if some actions were shown (and also execute them)
As per issue. Note - I think only worker nodes can be cordoned, drained, etc, so Rancher would need to be installed on a RKE multi-node environment with at least one worker node
- upstream/downstream cluster kube node page
- cluster management cluster's Machine Pools list
> Ensure local cluster kube node's can determine their cluster id

- shell/assets/translations/en-us.yaml
- shell/components/formatter/ClusterLink.vue
- shell/components/formatter/RKETemplateName.vue
- shell/config/types.js
- shell/detail/provisioning.cattle.io.cluster.vue
- shell/list/provisioning.cattle.io.cluster.vue
- shell/models/provisioning.cattle.io.cluster.js
Fixes #6580
This PR fixes a gap between the old and new UIs - when an RKE1 cluster has been created from an RKE template, if the template has been updated, we now show this on the cluster list page:
Additionally, we also show the template name and version and the upgrade icon on the detail page, just as we do in the Ember UI:
To test:
- Create an RKE1 Template
- Create a 1-node RKE1 cluster from this template
- Go to the cluster list page and validate that there is no upgrade icon
- Go to the cluster details page and validate that there is not an upgrade icon 
- Add a new version to the RKE Template
- Go to the cluster list page and validate that there is an upgrade icon
- Go to the cluster details page and validate that there is an upgrade icon 
- Edit the cluster and update it to the …
> Show if there is an updated RKE Template available for a cluster

- shell/models/management.cattle.io.roletemplate.js
- shell/plugins/steve/steve-description-class.js
Fixes #6585
Resources that have a `description` stored at the top level of the resource object and that use the Steve model don't work - this PR adds a new Model that supports this pattern and uses it for the role template resource.
To Test:
- Create a new Role Template and set a description
- Reload the dashboard in the browser
- Click on the name of the new role template in the list and verify that the description is shown in the detail masthead
- From the action menu, edit the config and verify that the description is populated
- Change the description and save the resource
- View the resource again and verify that the description is correct
- Refresh the browser and verify that the description is still correct
> Fix for 'Description' field for Rancher roles not editable or 'viewable'

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
Update issue templates to hopefully make it clearer that issue titles don't need to keep `[BUG]` etc at the start - just enter a clear title.
> Issue template updates

- shell/nuxt.config.js
Fixes #6697
- prevent links prefetch on `nuxt-link`
I did run some tests to see if content loaded quickly with the prefetch disabled (and comparing with it enabled)  on the home screen and on a local cluster explorer page, but for both I didn't notice any difference
> prevent links prefetch on nuxt-link

- shell/plugins/console.js
Fixes #6699
- allow for `console.log` and `console.info` to have correct traceability on dev mode
> allow for console.log and console.info to have correct traceability on dev mode

- pkg/rancher-components/src/components/Form/ToggleSwitch/ToggleSwitch.test.ts
- pkg/rancher-components/src/components/Form/ToggleSwitch/ToggleSwitch.vue
This adds a watch to the `value` prop so that changes will be reflected locally in the `state` data prop when changes come through.
The current behavior subverts expectations by only using the `value` prop to set an initial value. This pattern of managing state internally doesn't align with how I would expect a base component to behave.  
Fixes #6741 
* Makes `value` prop reactive
* Adds unit tests for `ToggleSwitch`
`provisioning.cattle.io.cluster` makes use of the toggle switch for switching between RKE and RKE2. Behavior on this page should not regress.
> Make `ToggleSwitch` state react to changes from parent

- .github/workflows/release-rancher-components.yml
- pkg/rancher-components/package.json
This fixes an issue with npm authenticating before publishing @rancher/components by updating the github action to more closely resemble examples provided by github docs. 
I have tested this release in my fork and it appears to be working so I've bumped the version number so that we could test in the `rancher/dashboard` repo after merging.
* https://github.com/rancher/dashboard/runs/7959900154?check_suite_focus=true
* https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
> Update @rancher/components github action 

- shell/mixins/brand.js
Fixes #6704
- `mixins/brand.js` handle the application of some settings in watchers on them
- The watchers weren't triggering as they never changed from the initial value
- Caused by https://github.com/rancher/dashboard/commit/771f168a5b33f970f47bcefb272cfa199b3d10be
- Revert to the initial way. This may break epinio but that can be fixed later on
Global Settings / Banners (all features)
Global Settings / Branding (all features)
Burger Menu --> Support --> Add a Sub ID  (custom colours should be removed, suse green colours should then be used by UI)
Note - Importantly the settings should apply after refreshing the browser
> Fix application of branding, color and theme from settings

- shell/components/auth/RoleDetailEdit.vue
- shell/models/management.cattle.io.globalrole.js
- shell/models/management.cattle.io.roletemplate.js
Fixes #6737 
This will restore the Edit Config action for all builtin role templates and will instead disable the inputs which govern the rules for those templates. The original PR #6429 removed the ability to edit the config of role templates, which in consequence removed the ability to change the `Locked` and `Default` fields for Global, Cluster, and Project/Namespace Roles that were builtin with Rancher.
Removed the `availableActions` conditional from both `management.cattle.io.globalrole` and `management.cattle.io.roletemplate` models.
Added a computed property to check for `builtin: true` on the resource, and disabling the inputs for rules. 
These Role types should be tested:
1. Global Roles
2. Cluster Roles
3. Project/Namespace Roles
For each Role type, a builtin and non-builtin …
> Restore builtin role actions - disable rules for builtin roles

- shell/models/chart.js
Fixes #6195 
If the `currentCluster` was not already in the store a custom cluster template could not be loaded.
This was a simple fix with a conditional added to return `null` rather than `undefined` for the `currentCluster`, which will allow the cluster template to be loaded with a "blank" cluster in it's place.
Added an optional chaining operator to return `null` for the `currentCluster.workerOSs` property.
- Steps to test are in the issue listed above
https://user-images.githubusercontent.com/40806497/187704268-72ceeb62-5aab-44ed-8c82-b9397f8b2167.mp4
> Fix undefined currentCluster for cluster templates

- scripts/standalone/index.js
- scripts/standalone/package.sh
Fixes the standalone script so that you can refresh on a dynamic route.
Also fixes a small bug in the publish script that leads to an error message.
> Standalone script - allow refresh on dynamic pages

- .gitignore
- shell/scripts/test-plugins-build.sh
Fixes issue with plugin test script - if the version number is not updated in the package.json, the test script will attempt to publish to the same version as was already pulled down and cached from npm - this will fail.
This script patches in a new version number to prevent this.
> Plugins: Ensure we use a new version number

- pkg/harvester/models/harvester/configmap.js
- pkg/harvester/models/harvester/k8s.cni.cncf.io.networkattachmentdefinition.js
- pkg/harvester/models/harvester/management.cattle.io.managedchart.js
- pkg/harvester/models/harvester/management.cattle.io.setting.js
- pkg/harvester/models/harvester/node.js
- pkg/harvester/models/harvester/persistentvolumeclaim.js
- pkg/harvester/models/harvester/pod.js
- shell/core/plugin.ts
Fixes #6797 
Harvester models were superseding shell models of the same name.
This PR fixes the issue by 1) moving duplicated harvester models into a subfolder with the name of the store they're used in ('harvester') and 2) allowing the dynamic registration of models in subfolders. 
When classifying a new object, the harvester store will first look for a model registered as 'harvester/type' and fall back to one registered as 'type':
https://github.com/rancher/dashboard/blob/16e1c2e29d35a27e4448d3cfc2713688b7bf5d21/shell/plugins/dashboard-store/model-loader.js#L51-L68
Clicking detail links for the moved harvester types in both their harvester ui view and the explorer view should be enough to determine if the correct model is being used. (harvester types overwrite the stevemodel detail …
> allow plugins to register models in subfolders

- pkg/epinio/components/application/AppSource.vue
- pkg/epinio/pages/c/_cluster/applications/createapp/index.vue
- pkg/epinio/types.ts
Fixes #https://github.com/epinio/ui/issues/154
1. We now fetch the default paketo packager from the `/info` endpoint instead of hardcoding it.
2. There was an issue where if you manually set another package, it would not respect it and it will use the default value.
1. From the UI, create a new Application from git (`https://github.com/scures/epinio-sample-app` and `master` branch is a good example). 
2. In advance settings for the paketo image, select custom and type `paketobuildpacks/builder:tiny`
3. Follow the rest of the steps.
This app won't deploy with the tiny version, it's fine. We need to validate that the package used for the build was actually the `builder:tiny` and not `builder:full`. To do so, one handy command would be:
`kubectl  get apps.application.epinio.io -n …
> Shows fetched value for the default builder

- shell/edit/auth/azuread.vue
Fixes #6428 
There was no functionality that set the radio group button to the correct endpoint option, it would always default to `standard`.
Added a method that will find the appropriate endpoint option depending on the `graphEndpoint`, and if not found it will default to `custom`.
- Steps to reproduce are in the issue listed
- If no China endpoint is available you can switch the [key names](https://github.com/rancher/dashboard/blob/43d338fac2cc87bf9c0cda6ac5d38fb2c4c7d96d/shell/edit/auth/azuread.vue#L32-L51) in `ENDPOINT_MAPPING` to spoof a different endpoint
> Set initial endpoint radio group for azuread

- shell/components/auth/AzureWarning.vue
Fixes #6752 
The azuread config view is technically nested within a cluster. Navigating from a page outside a cluster (home, support, and user prefs) requires explicitly defining a cluster param. Previously I had the blank cluster param in all the time; this caused an (obscure) issue when navigating from a product within the explorer.
* clicking the link from an explorer page
* clicking the link from a product within explorer (cis scans, backups, monitoring, etc)
* clicking the link from a page outside clusters (home, support, user prefs)
> fix azuread banner link

- shell/edit/workload/mixins/workload.js
Fixes #6454 
The `nvidia.com/gpu` resource limit was being deleted from the container resources object as the input is a string when fetched from the `podTemplateSpec`.
Added a method to parse the string as an integer, which will keep the initial functionality and will only pass if the string is indeed a number.  
- Steps to test are in the issue above
- Cluster creation/cloning/editing should be tested
> Add parseInt to nvidiaGpuLimit input conditional

- shell/assets/translations/en-us.yaml
- shell/pages/c/_cluster/settings/performance.vue
- shell/plugins/steve/subscribe.js
Fixes #6793 
This will add a global setting in the Performance tab to disable the websocket disconnection growls/notifications from appearing.  Also moved the banner and descriptions around within the performance tab.
For the sake of simplicity, this setting has been added to the json blob value of `/v1/management.cattle.io.settings/ui-performance`. As this is set by an admin, the setting will persist for all users.
To test you can block any websocket requests made to `v1/subscribe`.
Steps:
- Within the network tab of the browser dev tools - add `wss://<cluster-ip>/k8s/clusters/<cluster-id>/v1/subscribe` to the blocked requests list
- Navigate to your cluster and notice the blocked requests and the "Websocket Disconnected" growl
- Then navigate to the Performance tab within the Global …
> Add global setting to disable websocket notification growls

- shell/components/PromptModal.vue
- shell/store/type-map.js
Fixes plugin overrides for 
- generic prompts (`dialog`s)
- remove prompts (`promptRemove`s)
Relates to https://github.com/rancher/dashboard/pull/6815
This fixes 
- `pkg/harvester/dialog` (for instance enabling maintenance mode of a harvester host)
- `pkg/harvester/promptRemove` (for instance custom modal when deleting a harvester vm)
> Fix generic prompt and prompt remove plugin overrides

- pkg/rancher-components/src/components/Form/Checkbox/Checkbox.test.ts
- pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue
- shell/machine-config/amazonec2.vue
Fixes #6573 
This will change the `Checkbox` component to accept strings for the `valueWhenTrue` property, and converts ec2 `httpEndpoint` and `httpTokens` checkboxes to string values.
According to [the spec](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-options.html) of an ec2 instance, `httpEndpoint` can have a value of `enabled` or `disabled`, and `httpTokens` can have a value of `required` or `optional`. In our case, if the checkbox for either is unchecked the value with return to `undefined`.
In order to supply a string for each value the `Checkbox` component needed some logic to allow this behavior, along with the added `valueWhenTrue` prop.
`Checkbox` will now accept a string as the value when passed the `valueWhenTrue` prop. If a checkbox is …
> Checkbox to accept strings for valueWhenTrue - ec2 httpEndpoint, httpTokens to string values

- shell/store/catalog.js
Fixes #6823 
See issue above for steps to reproduce.
Simple fix to ensure we don't match charts that do not have a description.
> Fixes chart filtering when chart has no description

- shell/edit/provisioning.cattle.io.cluster/MachinePool.vue
Fixes #6275
When a cluster has been defined with an `unhealthyNodeTimeout` greater than `1m` prior to this version, the value would appear as seconds (i.e. `1 seconds`).
Added some logic to the `parseDuration` method to return the full amount of Duration time in seconds.
- Creating/Editing clusters with a different `unhealthyNodeTimeout` duration.
> Update parsing for nodeTimeout durations

- shell/config/table-headers.js
- the feature flag names are small compared to the description
- ensure that the description consumes the horizontal width rather than the name
> Ensure Feature Flag table description column consumes space rather than name

- shell/layouts/default.vue
Fixes #6719
- BUG
- there is no getter for `managementReady` so it was always undefined
- this means both computed properties for counts and schemas always returned an empty object/array
- when the getter returns the empty objects/arrays the watchers ALWAYS fired which then updated the side nav
- HOWEVER - it seems vue fails to trigger changes to computed properties which contains getters that were never hit (aka we never called the getters to fetch counts/schemas... so changes to them didn't trigger updates to the computed property). 
- FIX
- Ensure we get the correct `managementReady`... so the computed properties both return the correct count/schema and trigger when that value changes
- HOWEVER - this means we'll trigger the side nav update more. So guard against some of the simpler …
> Fix update of side nav given changes to counts and schemas

- shell/components/auth/Principal.vue
Fixes #5283 
This issue can occur regardless of the auth provider. When a display name is larger than the grid column the text will be folded over the element below. I replaced the static sizing on the member name column with `auto`.
To test you can simply add a test user with a long display name, then attempt to add the user to a project within a cluster.
**Before**
**After**
> Fix Principal member/user name overlap

- .drone.yml
- scripts/build-embedded
- The harvester plugin to support legacy harvester clusters is now available
- Update the env var to ensure it's included in the dashboard
> Enable embedding of legacy harvester plugin

- shell/nuxt.config.js
- Noticed this when investigating l10n issues
- autoImportTypes contains excluded packages
- autoImportTypes is brought in as a plugin with `new VirtualModulesPlugin(autoImportTypes)`
- I couldn't tell any functional difference after making the change. From my understanding, if tree shacking doesn't occur in dev land, it'll just reduce the count of files watched
> Ensure artefacts from excluded plugins aren't brought in via auto-imports

- shell/models/management.cattle.io.project.js
Fixes #6861 
This issue was difficult to duplicate as the errors were inconsistent, in some instances the action `setpodsecuritypolicytemplate` would cause a `403` error to be returned, but not always. [This comment](https://github.com/rancher/dashboard/issues/6377#issuecomment-1185369752) led me to believe this was a case of the backend not updating correctly or quickly enough which may cause this error to appear. 
I added an additional check for the `403` error alongside the conditional for a `409` error. This allows the action to be called once more, which if the user is truly able to will allow for the project to be created and fixes the error from being thrown.
- Steps to test are in the referenced issue.
> Add check for 403 to project creation action

- shell/components/SortableTable/index.vue
Fixes #6888 
- update `initialLoad` flag watcher in order to be properly triggered when data is already on the store for a given resource
> Pods count delayed column on homepage table not loading correctly

- shell/edit/provisioning.cattle.io.cluster/CustomCommand.vue
This PR addresses https://github.com/rancher/dashboard/issues/6827 and https://github.com/rancher/rancher/issues/36131#issuecomment-1245216251 by correcting the flag for adding taints to a custom cluster registration command.
1. In cluster management, I went to Clusters and clicked Create
2. Made sure the toggle for K3s/RKE2 was selected
3. Clicked **Custom** under **Use existing nodes and create a cluster using RKE2/K3s**
4. Entered a name for the cluster and clicked Create
5. Still in cluster management, in the cluster detail page, on the Registration tab, I clicked **Show Advanced**.
6. Clicked Add Taint. Added two taints that way.
7. Confirmed that in the cluster registration command below, each taint was included in the command with the `--taints` flag:
Note: The …
> Use correct taints flag in RKE2 custom cluster registration command

- shell/assets/translations/en-us.yaml
- shell/pages/prefs.vue
Fixes #6672
Updated the 'Formatting' Section with new changes on the User preference page.
Go to the user preference page :
> It should have a `Display Settings` section 
>  `Table Rows per Page` and `Number of clusters to show in side menu` selector should be on the same row
> Improve user profile page

- shell/assets/translations/en-us.yaml
- shell/detail/provisioning.cattle.io.cluster.vue
- shell/models/provisioning.cattle.io.cluster.js
Fixes #6808 
Added a banner to the resource detail page that will warn the user that the Cluster will not become active until at least one node is available.
Created a method in the `provisioning.cattle.cluster.io` model to return all of the `nodeGroups` within an `eksConfig`, then searching for a `desiredSize` equal to `0` across of the node groups.
- Steps for testing can be found in this issue: https://github.com/rancher/rancher/issues/38698
> Add warning banner for zero desired nodes in eks

- shell/list/harvesterhci.io.management.cluster.vue
- clicking on a harvester cluster name will make a http request for `ui-info` and then depending on result inject script in to the dom
- these can take some time, the user is left on the cluster list page with no visual indication anything is happening
- to provide this, and prevent multiple clicks, when waiting show a loading indicator and disable all cluster links
> Show a loading indicator when the harvester plugin loads slowly

- shell/components/auth/RoleDetailEdit.vue
Fixes #6885
For roles that inherit from 1000s of roles the general view/edit experience is impeded 
- Getting to the detail/edit page of the role is a bit sluggish
- Viewing the 'inherit from' tab in edit view is sluggish
- Leaving the page after viewing `inherit from` tab causes dashboard to hang
- Root issue addressed in this commit is performance of the inherit from tab, specifically the tab hang one
- On a system with a cluster role that inherits from 1100 other roles
- Tab shows one drop down for every role it inherits (1100)
- Each drop down contains 1100 entries
- Each slot that shows the drop down is passed 1100 roles as well
- To Address
- Fix the primary issue of 1000s of selects with 1000s of entries
- Reduce this to 1000s selects with 1 entry.... except when the user clicks on …
> Ensure roles that inherit from many many other roles can be edited

- shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #5866 
Ensures we only show the Advanced tab if it will contain content.
See linked issue for steps to reproduce/validate.
> Fix empty advanced tab shown on edit cluster page

- README.md
This updates the path to the plugins page in `README.md`
It looks like 11cd95d5b3591be33de4acec5b61af70bea1c04d changed the location but didn't update this link alongside the change.
> Fix broken link to plugins documentation

- shell/edit/auth/azuread.vue
Fixes #6868 - Fixes #6428 
If the azuread auth has been configured prior to 2.6.7 and the endpoints have not been updated, the deprecated endpoints ( e.g. `https://graph.windows.net/` ) should be respected when editing the config. Also, when setting the initial endpoint option we were not checking for the old endpoints, thus setting the endpoint radio option to `custom`.
Added a check for a `graphEndpoint` in the config to match one of the old endpoints. When `setEndpoints` is called it use the appropriate endpoint map to update the model.
Also removed the unnecessary call to `setEndpoints` when the model as this was causing the endpoint to be reset to the new set of endpoints regardless of the original value.
- Editing the config of an existing azuread auth after upgrading to `v2.6-head` …
> Add check for azuread endpoint type

- shell/components/auth/Principal.vue
Fixes #5283 
The original pr https://github.com/rancher/dashboard/pull/6831 did not take into account the username/loginName wrapping, only the display name. Added an overflow wrap to fold the text to ensure no overlapping will occur with either the user name or display name.
`overflow-wrap: anywhere` has been added to the `.name` class which will fold the text when it reaches the end of it's container.
- To test you can add a test user with a long user name **&** display name, then attempt to add the user to a project within a cluster. For example:
user: `long-username-hyz8ql12oa-0b2ewxkh29-vjnzbyqcmd-ohydd9bi3x-7rcje6k5hp-kr9ld7r1si`
display name: `long-displayname-e422ilkhqj-y4rzk02abt-c8m0scwcwl-reliod8oja-hj1jvu31mm-k28d9zppm1`
**Before**
**After**
> Add overflow-wrap to principle member name/loginName

- shell/assets/translations/en-us.yaml
- shell/plugins/steve/subscribe.js
- shell/utils/socket.js
Fixes #6785
Some sockets close quickly, given that we growl on every socket closing, this can lead to flooding the UI with growl notifications. Growl notifications were added to the dashboard because if a websocket cannot connect, that's something a user should know about.
* We don't consider ourselves actually disconnected until the reconnect attempts have failed.
* We only attempt to reconnect 3 times before declaring the socket disconnected and telling the user to reload the page (maybe later, I'll figure out how to add a "try again" button to the growl to bump the maxTries and attempt to connect again.
* Subscribe.js doesn't have any setTimeouts for displaying growls, all the timing is handled by when we dispatch the events in socket.js, keeping the timeline in my head was driving me …
> Adjusts timing, messaging, control, etc of websocket growls.

- shell/edit/workload/mixins/workload.js
Fixes #6644 - On workload screens make container tab default tab
1. Navigate to Cluster Explorer > Cluster > Workload > Deployment
2. Click on Create 
3. When the screen loads it should have `container-0` already selected
4. If a workload is already created, going to `view` or `edit` should highlight the first container regardless of the name given
> Set container to be the default tab in workload screens.

- shell/config/settings.js
- shell/plugins/steve/subscribe.js
Fixes #6960
* disconnect and reconnect growls should be disabled if the user has never touched performance prefs
* disconnect and reconnect growls should be disabled if the user turns them off
* disconnect and reconnect growls should be shown if the user has turned them on
> fix disable growl notification and default to true

- shell/assets/translations/en-us.yaml
- shell/config/product/multi-cluster-apps.js
- shell/pages/c/_cluster/apps/charts/install.vue
- shell/pages/c/_cluster/mcapps/index.vue
Fixes #6970 
- Renames 'Multi-cluster Apps' in the top-level menu to 'Global Configuration' (since apps are removed)
- Removed Apps from Global Configuration
- Updated the installs screen that used to link to MCM Apps to instead say that they can not be managed through the UI 
Note: For simplicity, I did not rename the product definition, so this stays as `mcapps`.
> Remove deprecated v1 multi-cluster apps

- shell/assets/translations/en-us.yaml
- shell/config/product/explorer.js
- shell/pages/c/_cluster/explorer/index.vue
Fixes #5816 
- add `event` resource type on cluster tab in side menu 
- add link to events list on the events overview in cluster dashboard
> UI 2.6.x 'events' view is confusing and 'hidden' by default

- shell/components/SortableTable/index.vue
- shell/nuxt.config.js
- shell/plugins/formatters.js
Reduces size of plugin packages significantly.
Advis, if a plug-in uses sortable table, it pulls in all formatters.
This PR moved the formatted cache initialisation to a plug-in that runs once.
> Plugins: Move formatter cache loading out of Sortable Table

- shell/assets/translations/en-us.yaml
- shell/pages/c/_cluster/explorer/index.vue
- shell/pages/home.vue
Fixes #6873 
- add deprecation banner for PSPs on cluster dashboard page to be displayed only if the user has any PSPs and if kubernetes version is 1.21 or higher
**Screenshot**
**Test**
- Create a `PodSecurityPolicy`
- Make sure cluster is running kubernetes version 1.21 or higher
- Check if warning Banner appears on the cluster dashboard page
> Add PSP Removal banners

- shell/components/nav/TopLevelMenu.vue
Fixes #6708 
The cluster order on the mgmt and home pages sort clusters by name, this will change the order within the side-nav to change the sorting from `ready` status to `name`. 
The order for listed clusters on the mgmt and home page are sorted by name which is from the backend. 
- Steps to test are in the referenced issue
**Side nav**
**Home page**
**Cluster management page**
> Change side-nav cluster order to sort by name

- shell/assets/translations/en-us.yaml
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #5105 
This adds an info banner in the rke2 cluster configuration under the `Project network isolation` checkbox when the Container Network is `cilium` and the Project network isolation checkbox is enabled. The info will read "Per default the ingress controller will not be able to route requests to pods on other nodes."
- Creating/editing an rke2 cluster
> Add info banner for rke2 cni and network policy conflict

- shell/models/workload.js
If a cluster contains two workloads (e.g. deployments) with the same spec.selector, the button to open a container shell from the workload page or list always picks the first pod that matches this selector without taking namespaces into account.
Fixes https://github.com/rancher/dashboard/issues/6982
Fixes https://github.com/rancher/dashboard/issues/6983
This adds a namespace filter to the function that matches the pod for the workload.
Opening a shell from a workload (e.g. deployment) page or list
I added this deployment
```
metadata:
name: nginx
spec:
selector:
matchLabels:
app: nginx
template:
metadata:
labels:
app: nginx
spec:
containers:
- image: nginx
name: container-0
```
in the namespaces `default` and `shop`. Note that `spec.selector` is the …
> Fix: Open shell from workload pages may pick wrong pod

- pkg/harvester/list/harvesterhci.io.setting.vue
- shell/assets/translations/en-us.yaml
- shell/components/ExplorerProjectsNamespaces.vue
- shell/components/nav/NamespaceFilter.vue
- shell/components/nav/TopLevelMenu.vue
- shell/layouts/default.vue
- shell/layouts/home.vue
- shell/layouts/plain.vue
- shell/list/management.cattle.io.setting.vue
- shell/pages/prefs.vue
- shell/plugins/dashboard-store/resource-class.js
- shell/store/prefs.js
- shell/store/type-map.js
Fixes #6289 
- splitting up user preferences belonging to `DEV` key and updating references throughout rancher 
- update user preferences page to individually control each one of them
**Before**
**After**
> 'View in API' preference is not obvious

- shell/components/ExplorerMembers.vue
- shell/components/ExplorerProjectsNamespaces.vue
Fixes #6976 
Small fix - but makes these 2 pages appear to load more quickly - user is not blocked from interacting with the UI for the data to load - so can use create etc.
> Project & Cluster Members: Move loading indicators to tables

- shell/config/labels-annotations.js
- shell/store/catalog.js
Add `Featured` annotation Featured charts. 
Fixes #6664
Added `featured` label in `labels-annotations.js` and in `catalog` files
> Added annotations for featured chart

- shell/assets/translations/en-us.yaml
- shell/layouts/default.vue
- shell/layouts/home.vue
- shell/layouts/plain.vue
- shell/pages/prefs.vue
- shell/store/prefs.js
- Removed the user preference `Enable Language Selection keyboard shortcut toggle (shift+L)` as it's only meant to be used by developers and gate it to be available on DEV builds only, as agreed with @nwmac 
**Test**
- Go to user preferences and check if option is no longer there
- make sure shortcut `SHIFT+L` still works on DEV builds
> remove the user preference for language toggle

- shell/assets/translations/en-us.yaml
Addresses https://github.com/rancher/dashboard/issues/6920 by updating the description of `system-default-registry` in the global settings to:
> Global container registry for Rancher system images. If no value is specified, the default registry for the container runtime is used. For Docker and containerd, the default is `docker.io`.
> Change description of global container registry setting

- shell/assets/translations/en-us.yaml
Fixes #6987 
This changes the label for Windows in the cluster provider option to describe that the Windows provider is for RKE1 only.
> Add rke requirement to windows cluster type provider option label

- shell/assets/translations/en-us.yaml
Fixes #6989 
Fixes typo in amazon credential creation screen for the `SecretKey` input: "SecretKey" -> "Secret Key"
> Fix typo in Amazon cloud credential input

- shell/config/settings.js
- shell/plugins/steve/subscribe.js
- shell/utils/socket.js
…factor performance setting getting logic
fixes #6972, #6992
related 2.6.9 issue: https://github.com/rancher/dashboard/issues/6960
This is partly addressed in a previous PR here https://github.com/rancher/dashboard/pull/6968 but per slack convo w/ Neil we should not be giving up on reconnect attempts if we're not visualizing the failure prominently. (eg when growls are disabled). I snuck in #6972 given that the request stems from code duplication and _not_ tacking it on would just be more code duplication.
> [2.7] adjust socket reconnect logic

- shell/edit/workload/storage/awsElasticBlockStore.vue
- shell/edit/workload/storage/azureDisk.vue
- shell/edit/workload/storage/azureFile.vue
- shell/edit/workload/storage/csi/index.vue
- shell/edit/workload/storage/gcePersistentDisk.vue
- shell/edit/workload/storage/vsphereVolume.vue
Fixes #7021 - Allow user to change the volume name when creating a workload
Following new fields were added based on the API https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#volume-v1-core
| Volume Type                             | Name               | readOnly |
| -------------                    | -------------      | ------------- |
| AWSElasticBlockStoreVolumeSource | :heavy_check_mark: | :heavy_check_mark: 
| AzureDiskVolumeSource            | :heavy_check_mark: | :heavy_check_mark: 
| AzureFileVolumeSource            | :heavy_check_mark: | :heavy_check_mark: 
| CSIVolumeSource                  | :heavy_check_mark: | :heavy_check_mark: 
| GCEPersistentDiskVolumeSource    | :heavy_check_mark: | :heavy_check_mark: 
| VsphereVirtualDiskVolumeSource   | …
> Add name and readOnly fields to the Volume types

- shell/edit/auth/azuread.vue
Fixes #6428 
The conditional that would determine if the initial endpoint radio option had the incorrect use case flow. It would choose a `custom` option regardless if the endpoint matched that of the `OLD_ENDPOINT` as it would first check for a `newEndpointKey` that is always returning `custom`.
Switched the conditional around to first check for an `oldEndpointKey`.
> Azuread old endpoint config initial radio option

- shell/machine-config/harvester.vue
Fixes #6764
The image form field of a harvester machine pool is now editable.
Editing the image of an RKE2 cluster that was provisioned from Rancher on Harvester.
> RKE2 Cluster provisioning on Harvester: Make image form field editable

- shell/dialog/RotateCertificatesDialog.vue
- shell/models/provisioning.cattle.io.cluster.js
Fixes #6926 
This adds `k3s-controller` and `k3s-server` to rotating individual service options if the provider is `k3s`.
Added a method to the `provisioning.cattle.io.cluster` model for determining the `k3s` provider. For the options, `rke2` will be the fallback.
- Rotating both `k3s-controller` and `k3s-server` certificates individually.
- The same goes for `rke2` clusters
**K3s options**
**RKE2 options**
**Logs after rotating k3s certs**
> Add k3s clusters to cert rotation options

- shell/promptRemove/mixin/roleDeletionCheck.js
Fixes #7046
The count of unique users bound to multiple roles would stack regardless if they were unique. This changes the number of unique users to a set, which will remove the duplicate user names from the count.
Converted the `numberUniqueUsersWithBinds` variable to a Set, adding the unique users from each role checked, then returning the size of the set as the user count.
- Removing multiple cluster member roles that are bound to multiple users
- The same should be done with project roles
https://user-images.githubusercontent.com/40806497/193354591-9013c073-83e8-4cb5-829b-2ad77bbe0eac.mp4
> Fix unique user count on bound user role deletion

- shell/components/CommunityLinks.vue
- shell/pages/c/_cluster/explorer/index.vue
Fixes #5816 
Addresses 2 problems when clicking on the 'Show all events' link on the cluster dashboard page.
- Error parsing community links when it is set to `{}` - which can happen
- Error on the link used for the event resource page
> Fix all events link

- scripts/e2e
Fixes #7056
For some reasons the bash script does not work on master only. It is unclear why Docker logs is then collected while using evals command, therefore is simply reverted.
This issue does not seems to happen in any fork as well.
Reverted use of eval in bash.
GH Actions.
-
E2E Test passing correctly on the fork using the previous command: https://github.com/cnotv/dashboard/actions/runs/3160200703
> Correct syntax error in E2E script statement

- shell/plugins/steve/subscribe.js
Fixes #
Issue relating to e2e test failing on destroyWorker.
> Incorrectly referencing workers when destroying workers

- shell/assets/styles/global/_select.scss
- shell/components/form/LabeledSelect.vue
Reverts rancher/dashboard#7055 - this PR causes display issues on the apps/charts page:
> Revert "[backport]: fix select style"

- shell/detail/provisioning.cattle.io.cluster.vue
- shell/models/provisioning.cattle.io.cluster.js
Fixes #6838 
Similar to https://github.com/rancher/dashboard/issues/6036 where the cluster token was not being generated for a GKE hosted cluster, which would result in the registration tab not showing.
Reworked how we were determining if a cluster was from a hosted k8s provider into one method (`isHostedKuberenetesProvider`). Also changed the conditional in `showEksNodeGroupWarning` to check directly for `this.value.provisioner === 'EKS'` since I merged the original `isEKS` into the new method.
- Creating a GKE cluster with a private endpoint
> Add gke hosted provider to token creation

- shell/assets/translations/en-us.yaml
- shell/dialog/DiagnosticTimingsDialog.vue
- shell/pages/diagnostic.vue
Fixes #6739 
- Moved the latest logs to the bottom of the page
- Compacted the system info table into 3 groups:
1. Browser
2. System
3. Javascript memory (doesn't show if not permitted)
- Resource counts table
- Collapsed by default if more than one cluster
- Ignored `0` count resources
- Added to table headers:
- Total resource counts
- Total number of nodes
- Split cluster name and namespace
- Added column for timings when generated
- Fixed coloring to match standard table colors
- Converted checkbox into async button for generating timings
- Added dialog when users attempt to download data before generating response times
When the `Download Diagnostic Package` button is clicked it will check for response times with `promptDownload`, if the user has already generated the timings it will …
> Enhancements for diagnostic page

- shell/edit/auth/azuread.vue
Fixes #6428
If the `graphEndpoint` matches the old version (`https://graph.windows.net/`), the conditional will now return the proper endpoint option.
A way of testing a custom endpoint while using the standard set of URIs ( e.g. Graph Endpoint: `https://graph.windows.net/`, Token Endpoint: `https://login.microsoftonline.com/${ TENANT_ID_TOKEN }/oauth2/token` ) would be to change the Token or Auth endpoint property in `OLD_ENDPOINTS` to an arbitrary string.
> Remove uneeded check - add custom check for old endpoints

- shell/components/formatter/ClusterLink.vue
- shell/components/nav/TopLevelMenu.vue
- shell/list/provisioning.cattle.io.cluster.vue
- shell/models/provisioning.cattle.io.cluster.js
- shell/pages/home.vue
Fixes rancher/dashboard#7036
This should be isolated to the top level menu where the clusters are listed
Broken and healthy clusters
A simpler way to reproduce:
- Create a cluster with a single node
- Edit yaml of cluster
- Change `cloudCredentialSecretName: cattle-global-data:cc-4twkpo` to be a secret that doesn't exist.
This should be isolated only to the top level menu where the clusters are listed
> Disabling clusters in the top level menu if the cluster is in an error state

- shell/pages/prefs.vue
Fixes #6958
Fixed escape characters are shown on the user preferences screen
Note: After discussing with [@aalves08](https://github.com/aalves08), I have fixed this issue only for release 2.6.9. He said he will fix this issue for 2.7.0.
Go to the user preferences page => Advance section details should not have escape characters.
> Fixed Escape characters shown on user preferences screen

- shell/content/docs/en-us/getting-started.md
- shell/pages/docs/_doc.vue
Fixes #7086 
- Update getting started page
- Fix styling issues on the table to better show the groups in the table
> Remove v1 tools from getting started document

- shell/edit/service.vue
This fixes the selector preview box on the service create and edit form to only show selected pods from the same namespace
Fixes https://github.com/rancher/dashboard/issues/6984
The matching function was missing a filter to only show pods of the namespace of the service and to update itself when the namespace changes.
Preview box when creating or editing services
With this deployment:
```
metadata:
name: nginx
spec:
selector:
matchLabels:
app: nginx
template:
metadata:
labels:
app: nginx
spec:
containers:
- image: nginx
name: container-0
```
Before the patch, there is no namespace filter:
After, the namespace filtering now works correctly:
> Fix: Service selector preview does not consider namespace

- shell/assets/translations/en-us.yaml
This PR addresses https://github.com/rancher/dashboard/issues/6920 and partly addresses https://github.com/rancher/dashboard/issues/6918 by updating the language on the Registries tab on the form for creating/editing RKE2/K3s clusters.
Before:
After:
> Update registry config option descriptions for RKE2/K3s clusters

- shell/edit/networking.k8s.io.ingress/index.vue
- shell/utils/validators/formRules/__tests__/index.test.ts
- shell/utils/validators/formRules/index.ts
Wildcards like `*.example.com` are allowed in ingress hostnames since Kubernetes 1.18: https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#support-for-hostname-wildcards.
Fixes #6957
This adds a new validation rule `wildcardHostname` including tests, which extends the `hostname` rule to also allow a wildcard in the first part of the hostname:
* `*.foo.example.com` is valid
* `foo.*.example.com` is not valid
* `foo.*example.com` is not valid
* `*foo.example.com` is not valid
Allowing wildcards was added in https://github.com/kubernetes/kubernetes/pull/29204.
Creating and editing ingresses.
The hostname and tls hostname fields.
Working validations:
> Allow wildcards in ingress hostnames

- shell/config/types.js
- shell/pages/c/_cluster/explorer/index.vue
Fixes #7096
Previously...
- a new request for PSPs was made on each page visit
- the request would fail for users without access to PSPs
- failed requests equated to white page dev error (fine in prod)
Now...
- use the `counts` resource to determine if the user can see any PSPs
- move logic to a computed property
> Improve PSP deprecated banner

- shell/pages/c/_cluster/apps/charts/index.vue
Fixes #7121
On the charts page Show `Browse/Featured` toggle buttons should be visible only when there is data for featured charts.
- To test you can add a new repository with this HTTP URL: https://nwmac.github.io/rancher-charts
- Go to page:  https://192.168.1.11:8005/c/local/apps/charts
Select newly added charts in the dropdown and It should show `Browse/Featured` toggle buttons for the test-charts.
> Show browse-featured-toggle button when there is featured chart data

- shell/components/Tabbed/index.vue
- shell/edit/workload/index.vue
Fixes #7124
As in issue.
Removed unnecessary padding.
Added prop to the `Tabbed` component and pointed class for active property.
- `NetworkPolicy`, `/c/local/explorer/networking.k8s.io.networkpolicy
- `Workload` creation
Based on what defined in the issue, no other view has nested tabs cases.
> Nested tabs should not contain padding

- shell/models/provisioning.cattle.io.cluster.js
Fixes rancher/dashboard#7126
It looks like we determine the provisioner is k3s in a couple different ways.
Anywhere that requires windows support to be show or used could be affected but it's unlikely.
Anywhere that requires windows support to be show or used could be affected but it's unlikely.
> Hide the windows command from k3s cluster

- shell/components/Tabbed/index.vue
- shell/edit/workload/index.vue
Fixes #7115 
As in issue.
Removed unnecessary padding and margin.
Added prop to the `Tabbed` component and pointed class for active property.
- `NetworkPolicy`, `/c/local/explorer/networking.k8s.io.networkpolicy
- `Workload` creation
Based on what defined in the issue, no other view has nested tabs cases.
> [backport v2.6.9] NetworkPolicy PolicyRules checkbox and buttons overlap

- shell/components/Tabbed/index.vue
Fixes #7124
Removed box shadow previously defined in child element.
/
/
/
> Remove box shadow for nested tabs

- shell/components/PromptRemove.vue
Fixes #7138 
This fixes the error message when deleting cloud credentials that are in use to return the `error.message` rather than the entire error object.
> Fix error response to return message string

- shell/assets/styles/global/_button.scss
- shell/assets/translations/en-us.yaml
- shell/config/product/settings.js
- shell/config/product/uiplugins.js
- shell/config/uiplugins.js
- shell/pages/c/_cluster/uiplugins/InstallDialog.vue
- shell/pages/c/_cluster/uiplugins/PluginInfoPanel.vue
- shell/pages/c/_cluster/uiplugins/UninstallDialog.vue
- shell/pages/c/_cluster/uiplugins/index.vue
A few minor tweaks:
- Fixed presentation of the 'reload required' for plugins that are in error or are built-in
- Fixed annoying blue border on the disabled button - seen on the cancel button on the plugin uninstall dialog
- Improved the presentation of 'built-in' metadata for a built-in plugin
- Changed order of configuration items, so Extensions is in the middle
- Show icon from package metadata for plugins without a corresponding chart
- Added 'Manage Repositories' to the action menu to make it easier to get to this page from extensions
- Added support for the display name override to give plugins a custom title
> Minor plugin tweaks

- shell/detail/provisioning.cattle.io.cluster.vue
Fixes #7171 
This removes the registration warning banner for custom rke and k3s clusters. Works for both rke1 and rke2.
_rke2_
_rke1_
> Remove registration warning banner for custom clusters

- shell/assets/translations/en-us.yaml
- shell/models/management.cattle.io.cluster.js
- shell/pages/c/_cluster/apps/charts/install.vue
https://github.com/rancher/dashboard/issues/6910
To test:
1. Provision two downstream RKE2 clusters, one with a private registry in the cluster config and one without.
2. In the cluster that has a registry, install a helm chart with the default settings. (I used Rancher alerting drivers) Confirm that the cluster registry from the cluster config is used in the values.yaml under `values.global.cattle.systemDefaultRegistry`. 
3. In the cluster that does not have a registry, install a helm chart with the default settings. The `values.global.cattle.systemDefaultRegistry` should be an empty string because the global default registry in the settings is also an empty string.
4. In the global settings of Rancher, change `system-default-registry` to a different string. It can be any string.
5. In …
> Can pull Helm chart app images from cluster registry or custom registry

- pkg/harvester/l10n/en-us.yaml
- shell/assets/translations/en-us.yaml
- shell/components/HarvesterServiceAddOnConfig.vue
- shell/components/form/WorkloadPorts.vue
- shell/edit/service.vue
This fixes a problem with the harvester-specific section of loadbalancers: https://github.com/harvester/harvester/issues/2929
There is a harvester component still in `shell` that adds some UI when creating loadbalancers in an rke2 cluster provisioned with harvester. There's also a related bit in workload creation port config (which can create services) During the pluginization process, we accidentally moved the translations for this component into the harvester pkg; they need to stay in `shell` where the component is used.
The easiest way to test this is to alter the service edit component's `showHarvesterAddOnConfig` computed prop and WorkloadPort's `showIpam` computed prop to always return `true`.
forwardport: https://github.com/rancher/dashboard/pull/7189
> move harvester service add on translations back into shell

- pkg/harvester/l10n/en-us.yaml
- shell/assets/translations/en-us.yaml
- shell/components/HarvesterServiceAddOnConfig.vue
- shell/components/form/WorkloadPorts.vue
- shell/edit/service.vue
2.6.9 issue:  https://github.com/rancher/dashboard/pull/7187 - this is a fix for UI that only appears for harvester-provisioned clusters
> [forwardport] move harvester service add on translations back into shell

- pkg/harvester/l10n/zh-hans.yaml
- shell/assets/translations/zh-hans.yaml
Follow-up of https://github.com/rancher/dashboard/pull/7187, I forgot to move over the equivalent zh-hans translation strings.
> move harvester service chinese translation

- shell/promptRemove/mixin/roleDeletionCheck.js
Fixes #7046 
This fixes the issue of counting Global Roles with the Standard User option.
The Standard User global role binding includes not only the standard users, but also duplicates of the admin accounts. So to fix this we now fetch the users to filter against the count of role bindings found.
- Create a few standard users and admin users
- Attempt to delete the Administrator and Standard User global roles
- Notice the count will contain the exact number of actual users  
__6 Users__
__Before - 8 users total__
__After - 6 users total__
> Fix global role count with standard and admin users

- yarn.lock
Rancher icons was updated in package.json for the 2.0.6 version that has the extension icon, but this was not reflected in the package.lock file
> Update yarn.lock for updating rancher icons

- shell/package.json
Minor update to bump the version number of the shell to match has been published
> Bump shell version number to reflect latest published version

- pkg/epinio/components/application/AppSource.vue
- shell/components/form/GithubPicker.vue
Fixes  https://github.com/epinio/ui/issues/153
Small state resets when navigating between steps.
The issue was,  once we send data with `$emit('githubData')`, the state & step inside parent component `AppSource` will be valid. to fix this, when we reset an input field we also emit the event with the current `githubData` so the parent component can re-validate the step.  Added the revalidation for when the `GithubPicker` is mounted (so its resets on the `back` button) and for each input event for each step in the Picker.
The mentioned issue explains how to reproduce it, now it should be fixed.
> Handle rests of the state when moving between steps

- shell/components/BackLink.vue
Fixes # https://github.com/epinio/ui/issues/159
The current `back-button` component works when a route history is presented (from where you landed there)
If none is found, it would not render.
With the change, we have a generic return to Home (`/`) button.
Normal scenario:
1. Click on the `dev` link at the bottom of the footer.
2. You should see the `< Back` button at the top of the new page.
No history scenario:
1. Refresh the page
2. You should see the `< Home` button at the top of the new page.
> Adds a default return to home when no route history

- shell/edit/provisioning.cattle.io.cluster/ACE.vue
- shell/utils/create-yaml.js
Fixes #6881
The remaining issue was specifically caused by using the 'view as yaml' option in the edit form then saving, then editing again without using that option before saving, and vice versa. In other words, clicking 'view as yaml' from the form changed the cluster spec. 
The problem was in `createYaml` and therefore not specific to cluster provisioning. I previously mentioned that I thought the problem was the use of the `cleanUp` function in `createYaml` but it was more subtle. `createYaml` uses schemas' `resourceFields` to generate commented out fields: if the schema for a given type had no properties defined in `resourceFields`, `createYaml` would obliterate any existing data for that type and set the field to `null`.  An example of such a schema is …
> Fix createYaml data deletion

- shell/store/index.js
Fixes #https://github.com/epinio/ui/issues/164
Both issues revolve around `getActiveNamespaces`
1) the getter of currentCluster will always be undefined in epinio (it has no current prov cluster, but it does have a clusterId), this was blocking updating the ns cache
2) getter passed in was incorrect when called by updateNamespaces, brought in by bad merge https://github.com/rancher/dashboard/commit/b3f13843dda3450d218
- spent a lot of time working out why this wasn't causing issues in master, but given where/when it's called it doesn't currently make any different. once upon a time if the cache stuff was fully used it probably would have broken switching between clusters
Note  - This will be merged in to `master` in the 2.7.1 timeframe
> [Epinio] Fix Namespace Filter

- shell/mixins/resource-manager.js
Fixes #7220 
- store `type` prop on requested data before overwriting it for `classify`
https://github.com/rancher/dashboard/blob/master/shell/edit/workload/mixins/workload.js#L221-L226 uses `_type` (which was not found - diferences between steve and k8s API -> here the prop is `type`)  which was being overwritten on the code because of the `classify` operation.
We need to make sure we store this object prop, if it exists, before overwriting it.
Also checked the code where `secondary resource data` is loaded and there is no conflict (at least in terms of the parsing functions) with `type`.
> Registry secrets are not available in the UI when creating a deployment

- shell/assets/translations/en-us.yaml
- shell/components/Carousel.vue
- shell/pages/c/_cluster/apps/charts/index.vue
Fixes #7241
- Ensure scroll timer is cleared when we leave the page (#7241)
- Don't scroll on return to charts page of same cluster
- The scroll will only be enabled if 
- Charts page has not been visited since the tab was opened
- User previously visited the Charts page of another cluster
- This works on sessionStorage, so is persisted over tab refresh
- Increase time spent on each carousel section from 2 to 5 seconds
- l10n for header
> Bug fix and Improvements to Carousel

- shell/assets/translations/en-us.yaml
- shell/models/management.cattle.io.cluster.js
- shell/pages/c/_cluster/apps/charts/install.vue
Fixes #7233, https://github.com/rancher/dashboard/issues/7232
Last week, we changed the Helm chart install page so that it would check for the existence of a cluster scoped private registry, then add that value into the values.yaml. https://github.com/rancher/dashboard/issues/6910 However, this only worked for K3s/RKE2.
Some additional code still needed to be written for RKE1 because the cluster registry needed to be taken from the cluster management resource for RKE1, as opposed to the provisioning cluster resource for RKE2.
- Fixed a bug in the `provClusterId` getter on the management cluster model in which it returned undefined for RKE1 clusters. (Because RKE1 clusters are not created with CAPI resources, they don't have the same relationship to CAPI resources as RKE2/K3s.)
- The Helm …
> Can use RKE1 cluster scoped registry for Helm chart installs

- shell/pages/c/_cluster/apps/charts/install.vue
Fixes https://github.com/rancher/dashboard/issues/7246
- Partial implementation brought in by https://github.com/rancher/dashboard/issues/6910
- However that assumed an empty string meant the global registry was used when in fact it falls back on docker.io
- So always pass through the registry if one exists (cluster > global)
- Installing a helm app in a downstream cluster with neither global or cluster registry
- Installing a helm app in a downstream cluster with a global registry
> Remove override for chart container registry when it matches the global container registry

- shell/assets/translations/en-us.yaml
- shell/pages/c/_cluster/uiplugins/RemoveUIPlugins.vue
- shell/pages/c/_cluster/uiplugins/index.vue
Fixes #7239
A couple of updates:
- Don't show version number when installing - we don't know the version until install has completed
- Allow the user not to uninstall the plugin CRD
> Extensions: Don't show version when installing

- shell/pages/c/_cluster/apps/charts/install.vue
Fixes #7260
- This was the default behaviour from before, we switched to conditionally write them out if the values weren't specified in the chart `values.yaml`
- Seems a lot of rancher charts don't manually specify them though, but reference them in templates
- Airgapped environment with custom system registry
- Environment where there's no custom registries used
> Always write out the `systemDefaultRegistry` values when installing helm charts

- pkg/epinio/models/applications.js
Fixes #https://github.com/epinio/ui/issues/169
if no custom route is assigned, it will default to `routes: null`, if any, it will send the array.
> fix: handles default & custom routes

- cypress.config.ts
Fixes #7281
Added [`retry`](https://docs.cypress.io/guides/guides/test-retries) option in the Cypress config.
The retry will generate multiple attempts to a total of 3, if any error occurs, which can be inspected separately and will have separated screenshots.
Retrying 3 times with a long waiting time in case of error may eventually have a very length test, in case everything fails.
> Add retry option for E2E tests

- shell/pages/diagnostic.vue
Fixes #6739 
This adds a step in fetching the clusters to show within the table in-order to retrieve the `displayName` for clusters created by Norman (rke1, gke, ake, eks).
The `displayName` does not exist on the schema for `capi` clusters, for any legacy clusters the name is shown as the ID.
- Viewing legacy clusters from the diagnostic page
> Use display name of cluster for diagnostic page

- shell/mixins/brand.js
Fixes #7305 
When not authenticated, call to fetch settings failed - this PR changes this to use the same pattern elsewhere that ensures this can read the settings that an unauthenticated user is allowed to retrieve.
> Fix issue where brand is not set on authenticated pages

- shell/assets/translations/en-us.yaml
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes https://github.com/rancher/dashboard/issues/7334
To test this PR, I went to provision a RKE2/K3s cluster, then selected a K3s Kubernetes version. Confirmed the tech preview was gone.
> Remove message saying K3s provisioning is in tech preview

- shell/edit/persistentvolumeclaim.vue
Fixes #7332 
When a PV is assigned to a storage class (has `spec.storageClassName` set) PVC's created from that PV also need `spec.storageClassName` set.
A note about the repro step [here](https://github.com/rancher/dashboard/issues/7332#issuecomment-1302586528) : when creating your PV you need to go to the customize tab and choose 'longhorn' in the 'assign to storage class' dropdown, not just select 'longhorn' as the volume plugin (I made this mistake initially)
> when using pv to make pvc set storageClassName if present on pv

- docusaurus/docs/getting-started/development_environment.md
- scripts/update-docker-image
Fixes #6602
This script will update a running instance of Rancher in Docker to a specified image and will create a backup of the original image.
The script needs 2 arguments:
- A container name to be updated
- An image tag for which to update the container with  
Run the script:
```console
./scripts/update-docker-image <container-name> <image-tag>
```
> Add script to update docker image

- shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #7334 
there was still text for `tech preview` in the dropdown section of kubernetes version selection. 
This was found through QA, by grepping for `tech preview` in the code base and observing what was still tech preview for k3s.
> remove tech preview message from k3s kubernetes version dropdown

- shell/assets/translations/en-us.yaml
- shell/content/docs/en-us/whats-new.md
Fixes #7361 
What's New for 2.7.0 now includes mention of k3s provisioning being GA
Load What's New and ensure that k3s provisioning as GA appears.
> add k3s provisioning as GA in 2.7.0

- shell/edit/persistentvolumeclaim.vue
Fixes [#7369 ](https://github.com/rancher/dashboard/issues/7369#issuecomment-1307658187)
edit: this also addresses a lingering issue in https://github.com/rancher/dashboard/issues/6444
We're checking the availability of storage classes and pvs using the management store: this seems to work fine for the local cluster, but standard user cluster owners encounter this bug on downstream clusters.
forwardport: https://github.com/rancher/dashboard/pull/7371
> [2.7.0] fix pvc creation in downstream clusters for standard users

- shell/components/form/Select.vue
- shell/components/form/__tests__/MatchExpressions.test.ts
Fixes #6167 
- remove `@input` event from `v-select` as event is already sent by default by `v-select`
https://vue-select.org/guide/values.html#event-input
Confirmed via testing on interface and through documentation.
**QA testing**
Generally make sure <Select> component is working properly. Ex: Creating a new role for user (selecting verbs)
> remove @input event from v-select

- shell/dialog/RollbackWorkloadDialog.vue
Fixes https://github.com/rancher/dashboard/issues/6022
This PR adds the exact time of the revision creation to the dropdown menu for rolling back a workload.
1. I created a Deployment
2. Went to Edit Config on the Deployment, changed the image pull policy, saved, and changed it back to create new revisions of the workload
3. From the Deployment list view, I went to the new Deployment and clicked **⋮ > Rollback**
4. Confirmed that the timestamp of each workload was in the format in the user preferences
6. Went to the user preferences
7. Changed the time format
8. Went back to rollback the workload again
9. Confirmed that the timestamps were updated to the new format in the user preferences
> Rollback options are timestamped in format from user preferences

- shell/config/roles.ts
This PR addresses https://github.com/rancher/dashboard/issues/7035 by adding ClusterScanReports to the role creation form in the resource dropdown:
After role creation, the lowercased `clusterscanreports` is in the role yaml:
> Add ClusterScanReports to list of options in RBAC dropdown

- shell/components/auth/SelectPrincipal.vue
- shell/list/group.principal.vue
- shell/pages/c/_cluster/auth/group.principal/assign-edit.vue
Fixes #3182
- Ensure invalid principals aren't selected on press of `return`
- Most evident on `Users & Authentication` --> `Auth Provider` (after enabling a provider like github and changing from the default value for `Configure who should be able to login and use Rancher - see issue for screenshots)
- On `Users & Authentication` --> `Groups` --> `Create` page ensure page doesn't reload on press of `return`
Also fixed spacing of `Refresh Group Memberships` and `Assign Global Roles` buttons on `Groups` page
- Principals can be tested by configuring the github auth provider (they map to github groups)
- `Users & Authentication` --> `Groups` --> `Create`
- Anywhere groups can be assigned to roles (cluster members, project members, global roles and auth provider config from above)
> Two Select Principal Fixes

- shell/detail/namespace.vue
- shell/edit/autoscaling.horizontalpodautoscaler/index.vue
- shell/list/workload.vue
- shell/models/workload.js
Fixes #2372
- This ensures ReplicaSets with owners are hidden
- For example ReplicaSets can be associated with a HPA (https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/#replicaset-as-a-horizontal-pod-autoscaler-target) but wouldn't make sense if it's owned by a deployment
- If the HPA has an invalid entry we still show it to the user but won't let them set it in the form (they're ofc free to enter whatever via YAML)
> Ensure HPA cannot be associated with workloads owned by others

- pkg/rancher-components/src/components/StringList/StringList.vue
Fixes [#3369](https://github.com/rancher-sandbox/rancher-desktop/issues/3369)
Fixes #7392
Fixes https://github.com/rancher-sandbox/rancher-desktop/issues/3373 (duplicate)
The list of items editing has changed (both create and edit mode):
- Items are saved when losing focus or when pressing Enter key.
- when there is a duplicate and focus is lost, input field is closed and the item is not saved.
- when there is a duplicate and Enter key is pressed, nothing happens.
- a new event `errors` is emitted when there is an error. We have only a `duplicate` error for the moment.
- duplicate error messages are displayed during user's typing.
StringList
> StringList - Commit changes when losing focus

- shell/components/SortableTable/index.vue
- fix height of applied filters in advanced filtering feature
> fix height of applied filters in advanced filtering

- shell/models/management.cattle.io.cluster.js
Fixes #7442 
The issue effects `AKS`, `GKE`, and `EKS` clusters which prevents the installation of any chart from within that cluster, the main cause was not being able to determine the correct Cluster ID. This PR adds the hosted kubernetes providers to determine the related cluster ID.
Added a method to determine if the cluster is from a hosted kubernetes provider, and based off of this the Cluster ID can be found.
- Installing charts on AKS, EKS, and GKE clusters
- Installing charts on rke1 clusters
___Note:___ Can provide a testing environment if needed.
> Add hosted k8s provider to provClusterId condition

- shell/pages/fail-whale.vue
Fixes #7099
Changes vertical alignment of fail whale page so that it is vertically centered:
> Fix vertical alignment of fail-whale page

- .github/workflows/scripts/pr.js
Fixes #7167 
Updates PR script to not change Zube status of draft PRs.
> Don't change zube status for draft PRs

- shell/assets/translations/en-us.yaml
Fixes #4119
Image size already fixed.
This PR just adds text to indicate supported image formats for the logo.
> Brand logo: indicate accepted formats

- shell/pages/home.vue
Fixes #7042
The buttons on the home page should have the same height, width, margin, and padding as buttons on other pages.
- Removed `btn-sm` class to fix this issue
> Removed btn-sm class to make button size nomal

- shell/assets/translations/en-us.yaml
- shell/chart/monitoring/prometheus/index.vue
Monitoring Installation: Remove Prometheus storage volumeMode form field
Prometheus needs a formatted filesystem for its persistent volume. Setting the volumeMode to anything else but `Filesystem` (default) does not work.
Fixes #6600
Form field is removed.
The default value in the monitoring helm chart and in Kubernetes for the volumMode is `Filesystem`. The form field is also not present for the Grafana volume configuration.
Monitoring installation and upgrades/reconfiguration, with a persistent volume configured for Prometheus.
I tested installing and upgrading Monitoring with out the field, and the installation succeeds and Prometheus gets a correctly configured persistent volume.
After the removal:
> Monitoring Installation: Remove Prometheus storage volumeMode

- shell/nuxt.config.js
Fixes #6721
Adds support for a `SKIP_ESLINT` env var which will skip eslint check that blocks developing the UI when you have lint errors.
> Allow eslint check to be disabled

- shell/models/secret.js
Fixes #7081
Fixed Wrong Certificate Information Showing
- Go to local > Storage > Secrets
- Click on any `TLS Certificate` it should show the correct Expires  date
> Fixed wrong certificate expires date issue

- package.json
- shell/components/SortableTable/filtering.js
- shell/package.json
Fixes #7452 
- fix advanced filtering issue where we were trying to search for a specific value in all cols (including labels) and some items to be searched don't even have `metadata.labels`
- bump rancher icons version
**QA Testing**
**NOTE: This is dependent on republishing the `elemental-ui` extension! will move to testing once it's published.**
- Test on `rancher/dashboard`, `OS management` (elemental) product
- Add the `elemental-ui` repo to `Apps/repositories` so that `elemental-ui` extension becomes available to install
- Install the `elemental-ui` on `extensions` in `rancher/dashboard`
- Install `elemental-operator`
Go to Local cluster -> open kubectl shell -> install helm chart:
```
helm install --create-namespace -n cattle-elemental-system elemental-operator \ …
```
> fix advanced filtering issue 

- shell/components/nav/WindowManager/ContainerLogs.vue
This PR addresses https://github.com/rancher/dashboard/issues/4950 by making a minor CSS fix.
1. I created a Deployment named `test` of a sample application that has the same Spring Boot logs as the original issue. I used this container image that I found by googling: `springio/gs-spring-boot-docker:latest`
2. Go to the Deployment detail page for `test`
3. On the Pods tab, go to a pod and click the *⋮ > View Logs*
4. Confirm that the "Spring Boot" is formatted properly
Before:
After:
> Minor log styling fix

- .vscode/settings.json
- docusaurus/docs/testing/unit-test.md
- jest.setup.js
- shell/components/__tests__/NamespaceFilter.test.ts
- shell/components/nav/NamespaceFilter.vue
- shell/list/__tests__/workload.test.ts
Fixes #7391
These tests are aimed to ensure the functionalities of the namespace filter an part of the Workload fetching data capabilities.
- Prevented issues in `NamespaceFilter` component in case of missing props or data, e.g. `currentProduct`
- Added `data-testid` attributes for selecting component.
- Added  [jest.restoreAllMocks()](https://jestjs.io/docs/jest-object#jestrestoreallmocks) globally for jest setup
- Added information related on global configuration for the unit tests in the documentation
> Add unit tests for Namespace filtering in resources

- shell/nuxt.config.js
This attempts to produce consistent results when working with `dir` paths on Windows, Linux, and macOS by using `path.posix` for all values specified for `dir`. 
The Nuxt documentation doesn't specify much regarding formatting for `dir` values but I was able to identify an issue with imports repeating (e.g. `require('..\\shell\\store\\shell\\store\\index.js')`) in the generated Nuxt output when `dir` has paths specified in the Windows-style. Always deferring to the posix-style resolves this issue allows for building Dashboard on Windows.
> Fix windows builds by using posix path for all dirs in nuxt.config

- shell/models/namespace.js
Fixes #7231 
The label that indicates the project for a namespace was not being preserved when cloning - this PR fixes this, so cloning a namespace will ensure the clone is in the same project as the one being cloned.
> Fix for cloning namespace in a project

- shell/components/CruResource.vue
- disable Enter key to submit form
Fixes #7112
IMO Submit action through keyboard should already have been disabled by design:
https://github.com/rancher/dashboard/blob/a07cf762249c167ff326bd477f74ec96fca58e8f/shell/components/CruResource.vue#L364
CruResource.vuew component.
> component: CruResource

- shell/components/nav/NamespaceFilter.vue
Fixes https://github.com/rancher/dashboard/issues/7495
If a preferences object exists, the code checks that object for the namespace filtering preference for the active cluster. But sometimes, the user does not have any preexisting preferences for the cluster, in which case the UI crashes. This fix makes it so the default is used if the user has no preference set for namespace filtering for the active cluster.
> Cluster explorer no longer crashes

- shell/components/SortableTable/actions.js
- shell/components/SortableTable/selection.js
Fixes #7421
Issue 1
- When there are multiple instances of the table the bulk actions weren't initially visible
- Caused by the `debounce` definition shared between different instances of the table 
Takeaway - `debounce` should not be used on Vue component methods (but created as part of the `data` method)
Issue 2
- K3s cluster nodes list would initially show 'delete' action and then magically disappear
- Caused by mgmt node model canDelete returning undefined instead of false (due to missing norman node which is letter there)
- The check to then show the actions only checked for `false` rather than a falsey
- Once the norman node was supplied undefined became false, so was correctly excluded
- This would affect anywhere canDelete/canUpdate returns an undefined instead of false (happens a …
> Fix initial display of table bulk actions

- shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes https://github.com/rancher/dashboard/issues/6631
This PR adds a minimum height to the RKE2/K3s cluster config form to stop it from wiggling when tabs are clicked.
> Stop cluster config from jumping up and down when navigating between tabs

- shell/list/helm.cattle.io.projecthelmchart.vue
Fixes #6042 , not the first customer issue quoted (confirmed fixed already) but specifically [SURE-4692](https://github.com/rancher/dashboard/issues/6042#issuecomment-1142588601)
Project members appear to have the ability enable project monitoring (create a `projecthelmchart`) but they do not. This PR makes that 'create' button dependent on the `projecthelmchart` schema methods including `POST`.
> Fix project monitor create button visibility

- shell/assets/translations/en-us.yaml
- shell/edit/logging.banzaicloud.io.output/providers/opensearch.vue
- shell/edit/logging.banzaicloud.io.output/providers/redis.vue
- shell/models/logging.banzaicloud.io.output.js
This adds the new OpenSearch and Redis output plugins to the logging ClusterOutput and Output forms.
Fixes #6701
Fixes #6702
The output plugins are available starting with rancher-logging 100.1.3+up3.17.7 in Rancher 2.6.7.
References for the output plugins:
https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/opensearch/
https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/redis/
Output and ClusterOutput forms
> Add logging output forms for OpenSearch and Redis

- shell/pages/auth/login.vue
Fixes #4202
- After logging out / timeout and then entering bad creds there's now no vertical wiggle
- I gave a quick look at resolving the wiggle when there's no intial error, but it left too much space to look pleasing
- Improved the general vertical spacing
- Local Auth Provider
- Other auth provider (such as Github)
> Improve spacing/wiggle on Login Page

- shell/components/auth/RoleDetailEdit.vue
- shell/components/form/Select.vue
- shell/models/management.cattle.io.globalrole.js
- shell/models/management.cattle.io.roletemplate.js
- shell/pages/c/_cluster/auth/roles/index.vue
Fixes #6956 #7204
This PR adds the ability to clone global/cluster/namespace roles and fixes a couple style issues in the role form:
> allow cloning roles; fix unlabeled multi-select style

- docusaurus/docs/plugins/plugins-getting-started.md
This replaces the initial use of Verdaccio when creating plugins/pkgs as we can leverage the published npm packages. For the "Use Case: Publish a package to NPM" section I have added the info on using Verdaccio to publish locally.
> Replace initial Verdaccio guide with published npm packages

- shell/detail/provisioning.cattle.io.cluster.vue
Fixes #6878 
The related resources tab shown on the details page for a cluster will always show related resources in the local mgmt cluster. A user might not have access to this cluster, so clicking one leads to an error.
This PR hides the related resources tab if the user does not have access to the local cluster.
> Cluster Mgmt: Hide related resources if user can not acces local cluster

- shell/components/auth/login/ldap.vue
- shell/pages/auth/login.vue
Fixes #7292 
- fix issue where LDAP Active Directory login errors aren't being displayed on the UI
**Testing**
[Create a new OpenLDAP Auth Provider](https://confluence.suse.com/display/CU/Setting+up+an+OpenLDAP+Auth+Provider+on+Rancher+Dashboard+for+testing)
try to login with user and pass defined on the above link (to reproduce the fix, just get the username or pass wrong)
> Login errors not being displayed for LDAP Active Directory login

- shell/store/prefs.js
Quick partial fix for: #7202 
With this change, we only update the user pref if the user has their preference set to visited the last area accessed on login.
> Only set last visited page if needed

- shell/edit/persistentvolume/index.vue
- shell/edit/persistentvolumeclaim.vue
- shell/edit/workload/mixins/workload.js
Fixes #7109 
- remove secondary data config from the data prop so that we don't have a huge config hindering code readability
@richard-cox I don't know how to improve this further, since moving it to a method. It cannot be a `const` because it needs to access `this` values. Wasn't able to create a custom method and access it from the mixin, also. If you have a further idea, please let me know. 🙏 
**QA testing**
No major changes were done, just moving stuff around to improve code readability. Generally just check if `PV`, `PVC` and `Workloads` `create` + `edit` views are working properly and loading data to select inputs.
> remove secondary data config from the data prop

- pkg/rancher-components/src/components/Banner/Banner.vue
Part of #7496 
Fixes banner close icons size - now looks like this:
> Fix banner close icon size

- docusaurus/docs/code-base-works/sortable-table.md
Fixes #7283
Added some info in the sortable-table page about the table header
- Start docusaurus
- Go to page http://localhost:3000/dashboard/code-base-works/sortable-table
It should have info about how table headers are populated
> Added info about how table headers are populated

- shell/edit/workload/storage/persistentVolumeClaim/index.vue
- shell/mixins/resource-manager.js
Fixes #7255 
- update url for namespaced requests for secondary data
NOTE: I have checked the original PR for changes/adaptations for k8s api data format and I cannot seem to find any changes to be reverted here. The ones I found are related to the fact that we don't `classify` the data by default, which, imo, we shouldn't. 🙏 
Original PR here: https://github.com/rancher/dashboard/pull/6860/files
> update url for namespaced requests for secondary data

- shell/assets/translations/en-us.yaml
- shell/components/formatter/ClusterLink.vue
- shell/config/home-links.js
- shell/list/provisioning.cattle.io.cluster.vue
- shell/models/provisioning.cattle.io.cluster.js
- shell/pages/home.vue
Fixes #7544 
Adds parity with Cluster Manager UI.
Adds non-active indicator to Cluster list on management list and home page.
Home Page:
Cluster Management Cluster List:
Works for both RKE1 and RKE2.
This PR also fixes minor issue on home page where we tried to parse empty string as JSON for the home page links which leads to a browser console warning. A check is now added.
**To Test:**
**RKE1:**
- Create an RKE1 Cluster (e.g. in DO) with two node pools. 2nd pool should just have one worker node.
- Wait for cluster to be ready
- Stop docker on the 2nd node.(e.g. in DO, use the web console to get a terminal on the machine and run `systemctl stop docker`
- Wait 30 seconds or so
- Go to both the Cluster Management cluster list and home pages and check that that the warning icon appears and …
> Add node inactive warning indicator

- shell/pages/c/_cluster/apps/charts/install.vue
Fixes #7502 
- fix issue with "compare changes" not setting YAML changes on the payload sent to the server after editing the app YAML
**To test**
- install `rancher-alerting-drivers`app from app/marketplace
- go to `apps` side-menu
- edit the `rancher-alerting-drivers`app
- edit via YAML
- click on `compare changes` tab/button (make sure changes are there)
- hit `Update` to save (make sure you were on the `compare changes` tab/button before hitting the save)
Check on Network the payload sent and payload received to make sure changes are there OR edit the app again and check if changes persisted
> fix issue with "compare changes"

- pkg/epinio/pages/about.vue
Fixes # https://github.com/epinio/ui/issues/166
Changes the download packages for MacOS & Linux to the `x86_64` instead of `arm64`
> Adds most common architecture for macOS & linux

- shell/components/form/ResourceTabs/index.vue
- shell/detail/workload/index.vue
Fixes #7374 
Richard summarized this well in the original issue:
> Think this is a regression brought in by #6683 and applies to ALL resources where we don't force the visibility of events. We gated the visibility of the events tab on if we have events OR we're manually forcing it. If we're not forcing it we fetch the events when we visit the tab (which we can't do because it's never visible).
We can't conditionally render the Events tab off the presence of events if we do not retrieve events until we visit the Events tab. The change in this PR means that every resource detail view will have a 'recent events' tab now regardless of whether there are recent events, but I think our only other option would be to revert the performance-improving event loading change.
> do not attempt to conditionally render the recent events tab off the presence of events

- shell/components/form/Security.vue
- shell/edit/workload/mixins/workload.js
- shell/models/workload.js
Fixes #7165 
The ask was to change the default for `allowPrivilegeEscalation` but the ticket also mentions that these securityContext defaults are only set when a value on the tab is changed. We can avoid that by setting them when the container is initialized. I also noticed we were trying to set `runAsRoot` when the correct field is `runAsNonRoot` https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#securitycontext-v1-core
> Change the default value for 'Allow Privilege Escalation' in container security context

- shell/assets/translations/en-us.yaml
- shell/list/provisioning.cattle.io.cluster.vue
- shell/pages/home.vue
Fixes #7547
This PR adds a manage button to the home page - this reduces the clicks required to go to Cluster Management from there:
It also adds responsiveness, so when the screen is smaller, we hide the doc links panel:
Lastly, on the Cluster Management page, this PR fixes the spacing between the "Import Existing" and "Create" buttons:
> Add manage button to home page

- shell/components/DetailTop.vue
- stories/components/DetailTop.stories.mdx
Fixes #7597
As defined in the issue.
- Added icons dictionary, e.g. `{ 'labelKey': 'icon-rancher-icon' }`
- Added tooltips dictionary to replace content, e.g. `{ 'labelKey': 'literaly any type of text' }`
- Created story for the component
> Extend DetailTop component to have icon and tooltip

- pkg/rancher-components/package.json
- pkg/rancher-components/src/index.ts
- shell/scripts/test-plugins-build.sh
This exports `DraggableZone` so that it can be imported via `import { DraggableZone } from '@rancher/components';`.
This also removes that `alpha` flag from published versions of `@rancher/components`
Fixes #7567
> Add export for DraggableZone

- package.json
- shell/components/LogItem.vue
- shell/components/nav/WindowManager/ContainerLogs.vue
- yarn.lock
Fixes #7156 
This PR updates the `ContainerLogs` component to use a virtual list- only the log lines visible on the page (plus a few more for padding) are rendered. The component will also only store the last x lines when that range option is selected, eg if the user has selected "show the last 10,000 lines" the containerlogs component only retains the latest 10,000 lines - previously we retrieved the last 10K then continuously appended new logs. 
I used chrome's performance monitor to test this, which you can find in the chrome devtool's kebab menu:
* Containers with various log activity should be tested. I used a deployment with 3 containers each logging something in a different interval (pasted below) 
* Various log range options 
* Resizing and moving the container between the bottom …
> Improve performance of pod logs

- .github/workflows/storybook-check.yaml
Fixes #7625
Adds a PR workflow to check that the Storybook build is not broken.
No QA need on this PR
Example run when the Storybook build is broken: https://github.com/rancher/dashboard/actions/runs/3628973233/jobs/6120627914
Successful run:
https://github.com/rancher/dashboard/actions/runs/3629249408/jobs/6121221579
> Add a GH PR Workflow to build Storybook on PR

- .storybook/main.js
- .storybook/package.json
- .storybook/preview.js
Logo is broken when published:
This PR fixes this by using a relative link for the image rather than an absolute one.
> Fix storybook rancher logo

- shell/assets/translations/en-us.yaml
- shell/components/AdvancedSection.vue
- shell/components/form/ArrayListGrouped.vue
- shell/components/form/SelectOrCreateAuthSecret.vue
- shell/edit/provisioning.cattle.io.cluster/RegistryConfigs.vue
- shell/edit/provisioning.cattle.io.cluster/RegistryMirrors.vue
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
Addresses these issues:
- https://github.com/rancher/dashboard/issues/6919
- https://github.com/rancher/dashboard/issues/5146
- https://github.com/rancher/dashboard/issues/6875
Previously, we showed private registry options with three radio buttons in the cluster edit form for RKE2/K3s. We got reports that this form was confusing to users:
To improve clarity, this PR replaces the radio buttons with a checkbox and explains what the default option is above the checkbox.
If the checkbox is selected, the basic registry config options are displayed. If "Show Advanced" is clicked, the mirroring and advanced auth options are displayed. I have also added more UI text and docs links to help tamp down on the confusion.
Default view: 
If cluster registry is enabled:
If advanced options are expanded …
> Improve UX for cluster scoped private registry config

- shell/assets/translations/en-us.yaml
- shell/components/formatter/InternalExternalIP.vue
- shell/config/table-headers.js
- shell/config/types.js
- shell/detail/provisioning.cattle.io.cluster.vue
- shell/models/cluster.x-k8s.io.machine.js
- shell/models/management.cattle.io.node.js
Fixes https://github.com/rancher/dashboard/issues/6371
This PR changes the "IP Address" column in the list of nodes for a cluster in Cluster Management.
Previously, it only checked for internal IPs. Now it uses the existing table header for showing both internal and external IPs, which matches the UX in Cluster Explorer on the Nodes page.
1. I provisioned a single-node EC2 cluster
2. Logged into the EC2 console and checked the external IP of the new node
3. Confirmed that the external IP was shown in the list of cluster nodes
Then to make sure I didn't mess up the internal IP display,
1. I provisioned a single-node Digital Ocean cluster, for which an external IP is not available out-of-the-box
2. Confirmed that the internal IP was shown in the list of cluster nodes
> Show both internal and external IP in list of nodes

- shell/detail/catalog.cattle.io.app.vue
- shell/mixins/chart.js
- shell/pages/c/_cluster/apps/charts/index.vue
- shell/utils/install-redirect.js
The catalog.cattle.io.clusterrepos/{repo} resource doesn't subscribe to updates. We now force a full request in the areas where it's appropriate to do so.
fixes rancher/dashboard#7668
If you want me to modify the repo for you just let me know. If you want to test it yourself the following notes should be helpful.
To test this you'll need a chart repo that you can modify. I created a simple repo at `https://github.com/CodyrancherTest/charts/tree/master`.  
To modify do the following:
- fork that repo
- modify the values.yaml (I just change the logLevel)
- run `helm package  .` within the root of the directory
- Add, commit and push all of the changes to your github repo
> This fixes an issue where catalog/charts were stale after a repo was updated

- shell/machine-config/azure.vue
This PR partly addresses https://github.com/rancher/dashboard/issues/7177 by adding StandardSSD to Azure storage options.
Edit: Changed the PR to a draft because based on this comment (https://github.com/rancher/ui/pull/4905#issuecomment-1287075886) it needs these changes:
- when StandardSSD_LRS is selected, the managed disk dropdown becomes disabled and its value becomes enabled
- managed disk dropdown has tooltip that says StandardSSD_LRS requires managed disk to be enabled
1. Went to Cluster Management > Clusters
2. Clicked Create
3. Selected RKE2/K3s and Azure
4. In the Machine Pools section, clicked Show Advanced
5. For Storage Type, selected Standard SSD LRS, the new storage option
6. Added a name for the cluster
7. Clicked Create
8. Confirmed that the cluster came …
> Add StandardSSD as a storage option for Azure cluster provisioning

- shell/utils/socket.js
Improve util/socket.js logging
- Ensure error exceptions are logged (`JSON.stringify(new Error('dsf'))` returns empty object)
- Ensure details of closed sockets are printed (code, reason, wasClean)
- Use a base level logging method to ensure consistent output
- used where we might not know some basic info like socket id
- Use a top level logging method to add common socket info
- Basic socket events (connect, disconnect, etc)
- I've tested the core ones connecting, opened, closing, closed, error, exception (mocked in screenshot below)
> Improve util socket logging

- shell/plugins/steve/subscribe.js
- Steve socket times out watches every 30 minues and we get a `resource.stop` event
- Previously we attempted to re-watch with a dodgy revision causing a `too old` error and the dashboard then fetching all resources for that type
- Avoid this by tracking latest revision which we should be up to date with
Fixes #5997
Problem - Every 30 minutes...
- Rancher `/v1` socket will stop watching a resource type and send a `resource.stop` socket message to the dashboard. 
- The dashboard will then try to re-watch the resource from a specific revision. It gets this from a dodgy source, so this can SOMETIMES be invalid (too old)
There's been a BE fix already
- Previously the BE failed to send the `too old` error, just the `resource.stop`. This would lead to the dashboard attempting the same again. …
> Improve handling of steve socket watch timeout

- shell/config/product/manager.js
Fixes #7621 
Move PSP to the advanced section, since they are deprecated and now removed in 1.25 (obviously nav only shows if the schema is present)
Now looks like this:
> Move PSPs to advanced section

- package.json
- scripts/version
- shell/assets/translations/en-us.yaml
- shell/components/nav/TopLevelMenu.vue
- shell/nuxt.config.js
- shell/pages/about.vue
Fixes #4217 
- Add rancher dashboard version to "About" page
- Replace copy of "backend version" link to just "About"
- Remove unused code from `TopLevelMenu` component
> Add rancher dashboard version to "About" page

- shell/components/nav/WindowManager/ContainerLogs.vue
- shell/components/nav/WindowManager/Window.vue
Fixes #4733
Terminal Windows where bottom actions are displayed, example: Job's logs
> Window Manager, fix bottom actions layout

- shell/components/ResourceDetail/index.vue
- shell/plugins/dashboard-store/actions.js
- shell/plugins/dashboard-store/resource-class.js
- shell/plugins/steve/actions.js
This PR updates yaml viewing and downloading across the board, so it's worth checking a few different resources. It should also be tested as both an admin and a standard user with access to only downstream clusters. The following actions are potentially impacted:
* view yaml
* edit yaml (note that edit config->as yaml is different)
* download yaml
* download yaml in bulk
> clean steve fields from yaml view and download

- shell/components/ResourceDetail/Masthead.vue
- shell/config/product/manager.js
- shell/models/provisioning.cattle.io.cluster.js
Fixes #7694
This PR:
- Extends the detail masthead to support a single action that can be provided by the resource model to be shown as a button in the detail masthead
- Updates the cluster model to provide an action to be shown in the masthead which will take the user to the cluster
> Add explore button to cluster detail view

- shell/components/PromptRemove.vue
* Fix error response to return message string
* Also apply to serialRemove
Co-authored-by: Richard Cox <richard.cox@suse.com>
Fixes #7630 
Backport of https://github.com/rancher/dashboard/pull/7157
> [Backport] Fix error response to return message string (#7157)

- shell/cloud-credential/harvester.vue
Fixes Cluster field is not really *required* when creating RKE2/K3s Harvester
- https://github.com/harvester/harvester/issues/3165
> HARVESTER: Cluster field is not really *required* when creating RKE2/K3s Harvester

- shell/models/workload.js
Backport https://github.com/rancher/dashboard/pull/6981
Original issue https://github.com/rancher/dashboard/issues/6982
Fixes https://github.com/rancher/dashboard/issues/7274
> [Backport for 2.6.x] Fix: Open shell from workload pages may pick wrong pod

- shell/edit/management.cattle.io.project.vue
- shell/models/management.cattle.io.project.js
Fixes #7179 
Original fix did not set the name, so I don't know how that every worked or was tested? @Shavindra 
This PR:
- Ensures the name is updated
- Forces a fetch of the updated resource, to avoid an issue where we update the Norman resource and when you return to the list page, the name does not reflect the change made - we force a fetch of the corresponding Steve resource
> Fix issue with project name not editable

- shell/edit/management.cattle.io.project.vue
- shell/models/management.cattle.io.globalrole.js
- shell/models/management.cattle.io.project.js
Fixes #7635 
Need to use the different base model that respects the description field for the cases like this where description is on the top-level object.
Applies fix from: https://github.com/rancher/dashboard/pull/6676/files to global roles
> Fix global role description

- shell/assets/translations/en-us.yaml
- shell/machine-config/azure.vue
This PR addresses the RKE2/K3s machine pool part of https://github.com/rancher/dashboard/issues/7164 by adding a new input for tags in the form for Azure machine pools, under advanced options:
To test this PR, I made sure the tags were persisted when creating or editing an Azure cluster.
> Add tags to Azure machine pool config

- shell/assets/translations/en-us.yaml
- shell/machine-config/azure.vue
Addresses https://github.com/rancher/dashboard/issues/7744
The StandardSSD_LRS storage option requires managed disks to work. So if StandardSSD_LRS is selected, and managed disks are not selected, there should now be an error message:
If managed disks are enabled, the error message disappears:
> If Azure storage type StandardSSD_LRS is selected, show managed disks warning

- shell/assets/translations/en-us.yaml
- shell/machine-config/azure.vue
Addresses https://github.com/rancher/dashboard/issues/7182 and https://github.com/rancher/dashboard/issues/7180
Combining the two options into one PR to avoid merge conflicts
Summary:
- Added  accelerated networking (AN) to Azure node options in the Advanced section for RKE2/K3s cluster provisioning
- Added an Availability Zone option for Azure nodes
- You can have an Availability Set or Availability Zone, but not both
- The Availability Zone dropdown menu may or may not have any options, depending on the selected region. For example, if you select `westus` as the location, the Availability Zone dropdown should be disabled and you should see a warning because that region doesn't support AZs. If you select `westus2` as the location, the Availability Zone dropdown should have 1, 2 and 3 as …
> Add accelerated networking and availability zones to RKE2/K3s machine pools

- shell/assets/translations/en-us.yaml
- shell/components/form/Select.vue
- shell/edit/logging-flow/Match.vue
- shell/edit/logging-flow/index.vue
- shell/models/logging.banzaicloud.io.flow.js
This adds an additional namespaces selector to the match section of the logging ClusterFlow form.
See also https://banzaicloud.com/docs/one-eye/logging-operator/configuration/crds/v1beta1/clusterflow_types/#clusterselect-namespaces
Fixes #6687
The additional field is only added for ClusterFlows and not for namespaces Flows. Flows don't have a namespaces selector.
There was also a small styling issue in the Select fields on this page, which I fixed as well. Before:
Creating and editing ClusterFlows.
Creating and editing namespaced Flows.
> Add additional namespaces match field to logging ClusterFlow page

- shell/pages/c/_cluster/uiplugins/PluginInfoPanel.vue
- shell/pages/c/_cluster/uiplugins/index.vue
Fixes https://github.com/rancher/elemental-ui/issues/61
- Capitalise extension titles
- Add white bg to extension icons on dark mode
FYI @nwmac
> capitalise extension titles

- shell/components/nav/NamespaceFilter.vue
> Namespaces filter, select on keydown Enter

- shell/assets/translations/en-us.yaml
- shell/list/provisioning.cattle.io.cluster.vue
Fixes #7763
We lost the `cluster.explore` translation string recently. Interestingly, the disabled button shown while a cluster is not ready was referencing a different key than the n-link used when the cluster can be explored. I opted to remove the `exploreHarvester` version because it's misleading when it is only applied to non-harvester clusters.
> re-add lost cluster.explore translation

- cypress/e2e/po/components/action-menu.po.ts
- cypress/e2e/tests/pages/cluster-manager.spec.ts
- shell/models/provisioning.cattle.io.cluster.js
Fixes #7080
The check for enabling the download and copy for kubeconfig was checking the cluster was ready - we should allow the user to download/copy it if the action to generate it is available.
> Allow kubeconfig to be downloaded/copied when cluster is not ready

- shell/assets/styles/global/_button.scss
Fixes #7727 
Addresses minor issue with the height and style of small buttons with secondary styling:
Before:
After PR:
> Fix secondary style small button height

- shell/edit/provisioning.cattle.io.cluster/index.vue
This fixes the cluster creation page to also show a RKE1/RKE2 toggle if all node drivers are deactivated.
Fixes #7705
This changes the `v-if` to decide if the toggle is shown on one of the headlines, to either show it at the 2nd item (node driver clusters or custom clusters) or at the 1st item (custom clusters, if both all node drivers and cluster drivers are deactivated).
Cluster creation screen with different variants of having cluster or node drivers activated. The toggle should always be visible.
Cluster creation screen.
> Fix: Also show RKE1/RKE2 toggle on cluster creation screen if all node drivers are deactivated

- shell/cloud-credential/harvester.vue
Backport https://github.com/rancher/dashboard/pull/7701
> [2.6.x] HARVESTER: Cluster field is not really *required* when creating RKE2/K3s Harvester

- pkg/harvester/store/harvester-store/actions.ts
- shell/store/index.js
1. There is no parameter to receive `getters` in mutations (`updateNamespaces`).  I think it may be unnecessary.
2. In `getActiveNamespaces`, I wonder if we should filter based on `allNamespaces`.    
Fixes #
> fix filter namespace

- shell/config/product/explorer.js
Fixes #7792 
We're missing some resources in the cluster provisioning section; the issue has repro steps.
> add rke-machine.cattle.io resources to explorer nav

- shell/assets/translations/en-us.yaml
- shell/components/DisableAuthProviderModal.vue
- shell/components/auth/AuthBanner.vue
- shell/mixins/auth-config.js
Fixes #7525 
- add disable auth provider prompt modal
**Test**
- Go to `Users & Authentication` -> `Auth Provider`
- Provision an `Auth Provider` such as `OpenLDAP` (https://confluence.suse.com/display/CU/Setting+up+an+OpenLDAP+Auth+Provider+on+Rancher+Dashboard+for+testing)
- After `OpenLDAP` is active, press `disable`
- Modal should appear and work as expected (copy is according #7525 )
> add disable auth provider prompt modal

- shell/components/ResourceDetail/Masthead.vue
Bug fix for #7695
Made spacing consistent:
or:
> Only show explore button when in detail view

- shell/config/product/explorer.js
Fixes #7786
Fixed localization bug for ‘EXPLORE CLUSTER’ menu in the sidebar 
- Open the 'Preferences' and change the language to '简体中文'(Chinese)
- Navigate to the ‘EXPLORE CLUSTER’
- It should show all sidebar menus in the Chinese language
> Fixed local string for cluster-membership page

- shell/components/ExplorerMembers.vue
This updates the import for the `ProjectMembershipEditor.vue` import to make use of the `@shell` alias.
We want to use the `@shell` alias to
- Maintain consistency with other imports throughout our app
- Allow linking `@rancher/shell` without errors (e.g. `Module not found: Error: Can't resolve '~/shell/components/form/Members/ProjectMembershipEditor.vue' in '/home/phillip/Development/rancher-desktop/node_modules/@rancher/shell/components'`)
> Update alias for ProjectMembershipEditor import

- shell/assets/translations/en-us.yaml
- shell/cloud-credential/harvester.vue
- shell/machine-config/harvester.vue
Remove External Harvester Cloud Credentials Support
- https://github.com/harvester/harvester/issues/3319
- Remove `clusterType` radio button
- Remove `kubeconfig content` textarea
- Cluster Management -> Cloud Credentials
- Cluster Management -> Create Harvester -> Machine Pools
> [2.7.x] HARVESTER: Remove External Harvester Cloud Credentials Support

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/chart/monitoring/steps/uninstall-v1.vue
- shell/config/home-links.js
- shell/config/private-label.js
- shell/edit/auth/googleoauth.vue
- shell/edit/cis.cattle.io.clusterscan.vue
- shell/edit/monitoring.coreos.com.receiver/tls.vue
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
- shell/pages/auth/setup.vue
- shell/pages/c/_cluster/explorer/tools/index.vue
- shell/plugins/axios.js
- shell/plugins/dashboard-store/actions.js
- shell/plugins/dashboard-store/getters.js
- shell/plugins/dashboard-store/index.js
- shell/plugins/dashboard-store/mutations.js
- shell/store/i18n.js
- shell/store/index.js
- shell/utils/version.js
Fixes #7308 - rather than using the /rancherVersion endpoint suggested in the issue I've used the existing getVersionInfo getter, so this update will work for older cluster versions.
> get docs base url version from getVersionInfo

- cypress.config.ts
- package.json
This PR adds logging to the Cypress config file that should notify users when they don't have the env vars set up for E2E tests correctly.
It also adds a convenience `cy:e2e` script that will open Cypress on the e2e tests, to save having to click each time - I'll update the docs for this in a later PR.
It also defaults the username to `admin` - which is what our docs say is the default, but we don't default to this (I think the docs mean that admin is the typical default name, rather than if you don't supply, we'll assume admin).
> E2E Tests: Add logging for env vars

- pkg/epinio/windowComponents/ApplicationShell.vue
- shell/components/nav/WindowManager/ContainerShell.vue
Fixes #7820
dark & light mode, selection background restored to `rgba(#3D98D3, 0.5)`
> xterm, align theme properties to version 5.x

- shell/components/ResourceTable.vue
Fixes #7048
`Enter` shortcut is implemented in `SortableTable` component using the `v-shortkey` library.
Having a quick look to the library code, the event propagation is blocked.
This means when users navigate in a tab where the table is used, for example `Jobs` view, the event is captured by the table's shortcuts and it is not propagated to the Namespace's filter on the top.
Go to any tab with SortableTable inside, for example `Jobs` and try to use the Enter shortcut to select a namespace.
> ResourceTable, allow Enter event to be propagated

- shell/static/loading-indicator.html
Fixes: https://github.com/rancher/dashboard/issues/7805
Signed-off-by: Volker Theile <vtheile@suse.com>
> The inner of the loading spinner uses different color than body.

- shell/components/__tests__/NamespaceFilter.test.ts
- shell/components/nav/NamespaceFilter.vue
- tsconfig.json
Fixes #7775
- When there are thousands of entries certain actions (drop down opened, selection changed, etc) take a long time to complete (upwards of 5 seconds)
- This is caused by churn of the filtered and options computed properties causing multiple renders for each action.
- To break this multiple-render per cycle behaviour detach `filtered` from the value used in `v-for`.
- This knocks off 2/3 of the time taken for the actions. 
- This is a lo-bar fix to address in the 2.7.next1 timeframe. In the future we should consider
- only rendering what's in view 
- not including whole model in options
- Cluster Explorer view - Namespace Filter (opening, listing projects/namespaces, selecting projects/namespaces)
Process - Open up NS filter and change from user to system namespaces
**Before …
> Improve performance of NamespaceFilter when there are thousands of entries

- shell/plugins/steve/subscribe.js
Workaround for a backend issue where we are sent `ws.resource.error` messages as `ws.resource.change` - we try and process these and this breaks the UI in many places.
This was picked up from our e2e tests - one of the breakages was that deleting a cluster would not then cause the list to update.
The workaround is to check for an id and ignore them if not present.
We should revert this when the backend fixes this issue.
> Workaround for backend issue where ws.resource.error is sent as ws.resource.change

- shell/assets/translations/en-us.yaml
- shell/detail/provisioning.cattle.io.cluster.vue
- shell/dialog/ScalePoolDownDialog.vue
- shell/models/cluster.x-k8s.io.machinedeployment.js
- shell/pages/prefs.vue
- shell/store/prefs.js
Fixes #6961
Added a confirmation dialog when the user pressed the minus icon on a cluster detail page 
Go to Cluster Management -> [cluster] 
- When the user clicks on the minus icon, it should show a confirmation dialog.
- The dialog should also show a checkbox below the first line and it should be checked by default we need to remember this (only within the user's browser session ) 
- If the checkbox is checked by default, the next time when the user scales it down, the confirmation dialog will NOT prompt again.
- If the checkbox is not checked, the confirmation dialog will prompt again.
- Added confirmation prompt setting in pref page
> Prompt node pool

- shell/pages/c/_cluster/apps/charts/install.vue
This PR addresses https://github.com/rancher/dashboard/issues/7766 by conditionally showing the option to configure a private registry for Rancher system images based on the presence of `global.cattle.systemDefaultRegistry` in a chart's `values.yaml`
These changes are mostly reversing the changes from this PR https://github.com/rancher/dashboard/pull/7273 , which is no longer needed because the NeuVector chart has been updated to use the `global.cattle.systemDefaultRegistry` value for pulling Rancher system images. In pre-Rancher-2.7.0 releases of the NeuVector chart, it used to be possible to configure the value at `registry` in the values.yaml, but that value is no longer used in the template. In the latest chart version released with Rancher v2.7.0, the NeuVector Helm chart template …
> Allow configuring system image registry only for charts that support it

- pkg/epinio/windowComponents/ApplicationLogs.vue
- pkg/epinio/windowComponents/ApplicationShell.vue
- shell/assets/styles/global/_select.scss
- shell/components/nav/WindowManager/ContainerLogs.vue
- shell/components/nav/WindowManager/ContainerShell.vue
Fix multi select styling so that the form field expands if not all items fit into a single line anymore.
Fixes #7842
Instead of fixing the height of the select form field, the form field now has a `min-height` which allows the field to expand if necessary.
Create a Logging ClusterFlow and pick a lot of containers or namespaces.
Form fields that use the Select component.
Before
After
> Fix multi select styling

- shell/pages/c/_cluster/auth/config/_id.vue
Fixes #7818 
The Nuxt loading indicator does not get removed when we prevent the navigation in this use case - this PR forces the loading indicator to be removed.
> Fix stuck loading indicator (auth)

- pkg/rancher-components/src/components/Banner/Banner.vue
- shell/pages/home.vue
Fixes #7794
Fixed `What's new in 2.7` and `Preferences` hyperlinks alignment
Go to the home page:
`What's new in 2.7` and `Preferences` hyperlinks should be aligned to the right side.
> Fixed link alignment in home page whats new section

- shell/assets/styles/themes/_light.scss
- shell/components/IconOrSvg.vue
- shell/components/nav/Header.vue
- shell/components/nav/TopLevelMenu.vue
- shell/utils/color.js
- shell/utils/svg-filter.js
This PR adds support for svg icons.
It wires these into the product config - an extension can now supply an svg icon in a product definition via the `svg` field.
Also added support for using this in the page header - you will need to use the `IconOrSvg` component with the pop `color="header"`.
The tricky part of this PR is modifying the colors of SVGs to support the theme - there is no "easy" way to modify the colors of an SVG brought in via the img tag... this PR uses an approach that uses a generated CSS filter to adjust the color.
Uses technique from here: https://stackoverflow.com/questions/42966641/how-to-transform-black-into-any-given-color-using-only-css-filters/43960991#43960991
> Add support for svg icons

- shell/edit/management.cattle.io.user.vue
- shell/models/management.cattle.io.user.js
- shell/plugins/steve/getters.js
Fixes #7839 
This is similar to other Norman-style resources where the description was lost (e.g. Role) - see https://github.com/rancher/dashboard/pull/7738 and https://github.com/rancher/dashboard/pull/6676.
This is slightly different as User inherits form HybridModel, so we can't use the extra class that was created - the changes are applied here to the user model.
Also note, that because the user model inherits from HybridModel, we need to add a hook to allow it NOT to clean the description field.
> Fix description not working for user resources

- .github/workflows/scripts/publish-storybook
The Storybook publish task is broken at the moment - it references the `DIR` env var which is not set, so it thinks that the Storybook has not been built.
This PR fixes this - the script runs in the top-level folder by default, so we can just remove the `DIR` env var.
> Fix storybook publish error

- shell/models/management.cattle.io.project.js
This PR addresses this reopened issue https://github.com/rancher/dashboard/issues/6464#issuecomment-1378002783
The issue is only intermittently reproducible, and I believe the reason is that it depends on how many users and rolebindings are in your setup. With more users and rolebindings, it takes more time for a user to get permission to see a new project that they just created. So I was able to repro the issue more easily in Anu's setup than in my own setup.
To test this PR, I confirmed that project creation was successful even after it had to retry. I believe that the reason it didn't work before this PR was that it was failing after trying twice and needed to keep trying.
> Allow more retries to finish project creation

- shell/config/secret.js
Fixes #6913
Remove the legacy docker secret type from the dropdown:
> Remove the legacy docker secret type from creation screen

- shell/assets/styles/global/_layout.scss
- shell/components/ResourceDetail/Masthead.vue
- shell/components/ResourceList/Masthead.vue
- shell/pages/c/_cluster/apps/charts/index.vue
- shell/pages/c/_cluster/auth/group.principal/assign-edit.vue
- shell/pages/c/_cluster/auth/roles/index.vue
- shell/pages/c/_cluster/explorer/index.vue
- shell/pages/c/_cluster/longhorn/index.vue
- shell/pages/c/_cluster/monitoring/alertmanagerconfig/_alertmanagerconfigid/receiver.vue
- shell/pages/c/_cluster/monitoring/index.vue
- shell/pages/c/_cluster/neuvector/index.vue
- shell/pages/rio/mesh.vue
Fixes #7942 and re-opens https://github.com/rancher/dashboard/issues/7341 ... #7942 is a high priority for Harvester and #7341 is a tech debt issue so I think this is a fair trade.
Components in pre-existing Harvester extensions don't have the `header-layout` class and consequently the styles formerly applied to header tags are lost within those extensions. I think https://github.com/rancher/dashboard/issues/7341, the request to remove global styling of tags, will be more tricky to resolve with this limitation in mind. Honestly I can't think of a good solution and am open to suggestions. The only thing I thought of was using a selector like `HEADER:not([class])` in `__layout.scss` which would let us use header tags without those styles applied by adding any class, but it feels pretty …
> re-add header tag global style to accommodate pre-existing extensions

- shell/pages/c/_cluster/apps/charts/install.vue
Fixes #7808 
Fixes #7833 
These two issues are caused by the same underlying problem.
For some imported clusters, there is no `provClusterId` property, which causes the code to fail during the `fetch` method, which is why we get a blank screen.
I have observed the 2 issues on a system and verified that this fix addresses them.
I have been unable to create my own test system which exhibits the error behaviour.
The system I saw had an Azure AKS cluster that had been imported as a generic cluster.
> Fix blank chart install page

- shell/assets/translations/en-us.yaml
- shell/detail/provisioning.cattle.io.cluster.vue
- shell/dialog/ScalePoolDownDialog.vue
- shell/models/cluster.x-k8s.io.machinedeployment.js
- shell/models/management.cattle.io.nodepool.js
- shell/store/prefs.js
Fixes #6961
- Added confirmation prompt displayed to the user to prevent accidental deletion of nodes - RKE clusters.
- Set the initial state of prompt confirmation from `empty string` to `null` so the pref page will show an unchecked checkbox for prompt confirmation setting,
- The code only works for RKE2 clusters and not RKE clusters - you need to wire the confirmation into management.cattle.io.nodepool as well - **Fixed**
- The preference does not work correctly - I think it would be better to change the meaning from Show to Don't show - i.e the preference would be "Don't ask for confirmation when scaling down node pools" - I think the problem is due to the preference defaulting to empty string. Currently, on a fresh system where the preference is new, if you go to preferences, the …
> Added scale down promt confirmation on RKE clusters

- shell/detail/catalog.cattle.io.app.vue
- shell/mixins/chart.js
- shell/pages/c/_cluster/apps/charts/index.vue
This PR addresses https://github.com/rancher/dashboard/issues/7826
To test it, I did this:
1. Refreshed Rancher to start with a clean store
2. Went to a helm chart app detail page
3. Navigated away from the page
4. Navigated back to the helm chart app detail page
5. Confirmed there were no duplicate chart versions
I opened a related tech debt issue about later improving performance by loading less helm chart data https://github.com/rancher/dashboard/issues/7963
> Avoid saving duplicate Helm chart versions

- shell/machine-config/azure.vue
This PR addresses the RKE2 portion of https://github.com/rancher/dashboard/issues/7877
The AZs should always be in order now:
> Availability zones are in order

- shell/assets/translations/en-us.yaml
- shell/components/CruResource.vue
- shell/config/types.js
- shell/edit/provisioning.cattle.io.cluster/__tests__/rke2.test.ts
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
- shell/edit/workload/index.vue
Fixes #7628,
- Navigation
- Hidden PSP resource link in cluster manager
- Added PSA resource link in cluster manager
- RKE2 cluster editor
- Added dropdown for PSA for k8s 1.23+
- Hidden PSP dropdown for k8s 1.25+
- ~Replaced the label `RKE Default` with `(None)`~ Used `(None)` if no PSA is selected
- Corrected reprovisioning banner hyperlink
- Workloads
- Added Banner with icon for PSA errors, removed stacked view to balance with case lacking it
- RKE2 cluster editor
- Retrieved PSA templates and added in the select input
- Added initial tests for RKE2 cluster editor
- Added comments for each tab due collapse view
- Added `haveArgInfo` i18n text
- Workloads
- Extended `CruResource` component to map errors into objects with messages and icons
- Added PSA RegEx computation to replace …
> Add support for Pod Security Admission in the Clusters and Workloads

- shell/edit/monitoring.coreos.com.prometheusrule/GroupRules.vue
This PR addresses https://github.com/rancher/dashboard/issues/7513 by adding the cluster ID to the default labels for new PrometheusRules. It applies to both Recording Rules and Alerting Rules within the PrometheusRule form.
The default alerting rule fields now include cluster ID in the labels:
1. I installed monitoring on a downstream cluster.
2. Went to the form to create a Prometheus rule
3. Within that form, clicked Add Record
4. Confirmed that the cluster ID label was there by default for the new rule
5. Deleted the recording rule
6. Clicked Add Alert
7. Confirmed that the cluster ID label was there by default for the new rule
> Add cluster ID label to new alerting rules & recording rules

- shell/assets/translations/en-us.yaml
- shell/edit/provisioning.cattle.io.cluster/RegistryMirrors.vue
This adds form field to configure registry mirror rewrites in the RKE2 cluster provisioning form.
Fixes #7939
The second issue fixes also an issue that the mirror settings are being removed when the cluster is edited without touching the mirroring configuration.
The backend already supports the rewrites field: https://github.com/rancher/rancher/blob/release/v2.7/pkg/apis/rke.cattle.io/v1/registries.go#L4-L15.
The feature is documented here https://docs.rke2.io/install/containerd_registry_configuration#rewrites.
Creating and editing clusters with registry mirrors and registry mirror rewrites.
Creating and editing clusters with registry mirrors and registry mirror rewrites.
> Registry mirrors

- shell/assets/translations/en-us.yaml
- shell/edit/monitoring.coreos.com.alertmanagerconfig/receiverConfig.vue
- shell/pages/c/_cluster/monitoring/alertmanagerconfig/_alertmanagerconfigid/receiver.vue
Fixes #7517 
The issue with disabled controls was fixed.
The remaining issue fixed by this PR is that any errors in the saving of a receiver are not shown and do not block the UI returning back to the main page - if you don't enter a name, this happens and the user goes back to the main page and sees that their new receiver has not been saved.
This PR fixes this, shows the error and prevents returning to the main screen.
It also marks the name field as required and adds form validation - so you can't create without entering a name.
> Fix alert manager receiver name

- shell/pages/home.vue
Fixes #7994
Fixed Home page card alignment 
Go to the home page > The banner to set login preferences and the side links panel should have their tops aligned.
> Fixed preferences banner top margin

- shell/assets/translations/en-us.yaml
- shell/edit/provisioning.cattle.io.cluster/index.vue
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #7791
This PR refines the banners displayed in RKE2 cluster creation/edit. It also tweaks some of the interactions between the two:
Changes:
- PSAs and PSPs can be used independently, so this PR removes the logic of resetting one when you use the other - users should be able to configure both if they wish
- Moved the PSP deprecation banner shown at the top of the page to the Security section - otherwise it can not be seen as the user changes settings
Improvements:
When creating a new RKE2 cluster, we now show a banner in the security section:
When selected version is >= 1.25
otherwise we show:
When editing an existing RKE2 cluster, we will not show either of the above banners, however, if the user changes the Kubernetes version to >= 1.5, we show:
When we do this, we will hide the …
> Update and refine PSP banners (RKE2)

- shell/assets/translations/en-us.yaml
- shell/components/DetailTop.vue
- shell/components/ExplorerProjectsNamespaces.vue
- shell/components/PodSecurityAdmission.vue
- shell/components/__tests__/PodSecurityAdmission.test.ts
- shell/components/form/Labels.vue
- shell/config/product/manager.js
- shell/edit/management.cattle.io.podsecurityadmissionconfigurationtemplate.vue
- shell/edit/namespace.vue
- shell/models/pod.js
Fixes #7999
- PSA position is now under Advance with a new name
- PSA edit/list is not added as i18n term and shortened
- PSA form labels are now i18n and capitalized
- Restored original text size in PSA Edit descriptions
- Replaced checkboxes for PSA template edit, while kept in the Namespace tab, updating related logic
- Added tooltip title in Namespace list resource which contain PSA labels
- Updated detail page label to toggle between concise and verbose version
- Increased growl timeout to 5 seconds on Pod creation with warn/restricted
Updated and added tests related to PSA:
- Creation in case of no checkboxes
- Input disabled
Namespace details
https://user-images.githubusercontent.com/5009481/214538184-d7cbd9ab-ceb1-439c-9894-65656984d292.mov
PSA form and sidebar …
> PSA minor changes

- shell/assets/translations/en-us.yaml
Fixes #7950
Renamed `Worker CIS Profile` to `CIS Profile`
- Navigate to Add Cluster -> RKE2 -> Custom
- Check 'Worker CIS Profile' dropdown under the Security section should be `CIS Profile`
> Renamed Worker CIS Profile to CIS Profile

- shell/edit/workload/__tests__/index.test.ts
- shell/edit/workload/index.vue
Fixes #8023
As mentioned in the issue, it's not possible to load the page with current regular expression, as positive lookbehind is not supported in Safari.
Changed regular expression.
Created very cumbersome sized unit test for the mapping method.
> Home page not load in safari: positive lookhead unsupported

- shell/models/secret.js
Fixes #7956
[Backport 2.6.x] Fix Wrong Certificate Information Showing
Go to local > Storage > Secrets
Click on any TLS Certificate it should show the correct Expires date
> Backport: Wrong Certificate Information Showing fix

- shell/components/CruResource.vue
This PR addresses this bug https://github.com/rancher/dashboard/issues/7876 by only rendering the `ResourceYaml` component if `showYaml` is true.
I followed these steps both to reproduce the bug and to test that it was fixed:
1. Went to list of clusters in Cluster Management
2. Clicked Create
3. Clicked Azure
4. Clicked Edit as YAML
5. Changed `spec.rkeConfig.etcd.snapshotRetention` from 5 to 6
6. Clicked Back to Form
7. Clicked OK
Confirmed that this error is no longer seen:
> In RKE2 cluster edit form, avoid showing YAML in form mode

- shell/components/SortableTable/index.vue
- shell/list/fleet.cattle.io.bundle.vue
- shell/list/fleet.cattle.io.cluster.vue
- shell/list/fleet.cattle.io.clusterregistrationtoken.vue
- shell/list/fleet.cattle.io.gitrepo.vue
- shell/list/logging.banzaicloud.io.clusterflow.vue
- shell/list/logging.banzaicloud.io.flow.vue
- shell/list/monitoring.coreos.com.alertmanagerconfig.vue
- shell/list/node.vue
- shell/list/persistentvolume.vue
- shell/list/persistentvolumeclaim.vue
- shell/list/provisioning.cattle.io.cluster.vue
- shell/list/service.vue
- shell/list/workload.vue
- shell/mixins/resource-fetch-namespaced.js
- shell/mixins/resource-fetch.js
- shell/plugins/dashboard-store/actions.js
- shell/plugins/dashboard-store/mutations.js
Fixes #7580 
- Update `resource-fetch` logic to take into consideration the `storeType` for each individual request
- Update `resource-fetch` logic so that we can initialise the mixin data with the main resource (list view resource) before we start actual fetches
- Update all custom list views that load "secondary resources" so that they are manual refreshed if the list view main resource has manual refresh
> Manual Refresh Performance Option

- shell/pages/c/_cluster/apps/charts/install.vue
Fixes #7977 
This PR:
- Fixes the top banner overlap rendering
- Fixes namespace banner at the bottom when creating a new namespace
- Only shows new namespace banner when the namespace has contents
After this PR:
Before this PR, top banner is not rendered correctly:
Before this PR, when selecting 'Create a new namespace', the banner would show for an empty namespace:
> Fix rendering issues on Helm Install page

- shell/assets/translations/en-us.yaml
- shell/components/CruResource.vue
- shell/components/form/ServicePorts.vue
- shell/components/form/WorkloadPorts.vue
- shell/edit/networking.k8s.io.ingress/RulePath.vue
- shell/edit/networking.k8s.io.ingress/index.vue
- shell/edit/service.vue
- shell/edit/workload/index.vue
This PR addresses https://github.com/rancher/dashboard/issues/5441 by adding some explanatory descriptions and tooltips around services and ingresses.
In the Ports section,
- Change "Ports" to "Networking" because that section can create a Service in addition to defining a port.
- Add a tooltip that says "For help exposing workloads on Kubernetes, see the official Kubernetes documentation on Services. You can also manually create a Service to expose Pods by selecting their labels, and you can use an Ingress to map HTTP routes to Services."
- Add a description that says "Define a Service to expose the container, or define a non-functional, named port so that humans will know where the app within the container is expected to run." (If a port is defined, it updates the YAML on the workload …
> Add text to help with Services and Ingresses

- shell/assets/translations/en-us.yaml
- shell/components/DisableAuthProviderModal.vue
- shell/components/auth/AuthBanner.vue
- shell/mixins/auth-config.js
Fixes #8005
Backport: Show confirmation modal when trying to disable auth provider
- Go to Users & Authentication -> Auth Provider
- Provision an Auth Provider such as OpenLDAP 
- After OpenLDAP is active, press disable
- Modal should appear and work as expected (copy is according https://github.com/rancher/dashboard/issues/7525 )
> Backport: Modal warning disable auth provider

- shell/edit/workload/index.vue
Fixes #7505
I think this fix makes sense: if the tab is keyed off the container name, every time the container name is changed the tab is re-rendered, its `active` property is re-set to `null`, the `Tabbed` component detects that tabs have changed, looks for a tab with `active === true`, doesn't find one, and defaults to the first tab (deployment labels). 
Do you remember what happned here @Shavindra ? The introduction of this bug in 2.6 and resolution in 2.7 is less unclear to me, which is why this PR isn't just a cherry-pick of a fix from 2.7... The bug was introduced by [this PR, 6841 ](https://github.com/rancher/dashboard/pull/6841/commits/eb0c53e9417bbf21eadc5c94a8bf5b848ea176f8) which claimed to fix [this issue, 6837](https://github.com/rancher/dashboard/issues/6837), but I can't …
> [2.6 backport] Fix Changing a Container Name highlights the Deployment tab when creating a Deployment

- shell/components/SortableTable/THead.vue
Fixes rancher/elemental-ui#71 
- fix styling of visible cols in advanced filtering
Before:
After:
To test:
- Check the inventory of machines in Elemental as it's where the advanced filtering is activated
> fix styling of visible cols in advanced filtering

- shell/assets/translations/en-us.yaml
- shell/pages/c/_cluster/apps/charts/index.vue
Fixes #8051
Displayed banner for legacy in case of k8s version RKE2 below 1.25.
`/c/<CLUSTER-ID>/apps/charts`
- Create cluster with RKE2 version 1.23 or 1.24
- Navigate to the App/Charts
- Banner should be displayed
> PSP Removal: Add banner to application list page

- shell/assets/translations/en-us.yaml
- shell/edit/monitoring.coreos.com.alertmanagerconfig/receiverConfig.vue
The receiver with empty name or the receiver with duplicated name is invalid now.
- https://github.com/harvester/harvester/issues/2798
> HARVESTER: duplicate receiver name is invalid now

- shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #8068
As request
@nwmac 
- Reset PSP ~and PSA~ if K3
- Restore ~PSA if RKE2 and also PSP if k8s version above or equal 1.25~ PSP if RKE2 and k8s version above or equal 1.25
Note: Please mind requirement in https://github.com/rancher/dashboard/issues/8061
Cluster creation as in issue definition.
https://user-images.githubusercontent.com/5009481/217036968-2cf0ff47-e22f-4b96-9c32-ba777399d448.mov
> Selection for PSA is cleared after changing the RKE2/K3S cluster version

- package.json
- shell/components/LogItem.vue
- shell/components/nav/WindowManager/ContainerLogs.vue
- yarn.lock
Fixes #8135 
Backport of https://github.com/rancher/dashboard/pull/7511
1. Create the deployment listed below
2. Go to the detail view for the deployment
3. For the pod listed, click kebab menu->view logs
4. Allow the logs to stream in for ~15-20min 
5. Watch the memory tab in browser dev tools and verify that memory use is <1gb
```
metadata:
labels:
workload.user.cattle.io/workloadselector: apps.deployment-default-test-logs
name: test-logs
spec:
progressDeadlineSeconds: 600
replicas: 1
revisionHistoryLimit: 10
selector:
matchLabels:
workload.user.cattle.io/workloadselector: apps.deployment-default-test-logs
strategy:
rollingUpdate:
maxSurge: 25%
maxUnavailable: 25%
type: RollingUpdate
template:
metadata:
labels: …
```
> [2.6 backport] improve performance of pod logs

- shell/components/form/LabeledSelect.vue
- shell/components/form/__tests__/LabeledSelect.test.ts
Fixes #8149
As in issue description.
To reproduce create/extend in the UI something like:
```ts
// ...
data: () {
return {
// ...
toggleLabel:           false,
myValue:               '',
}
},
computed: {
// ...
myOptions() {
return this.toggleLabel 
? [{ label: 'Old Label', value: '' }] 
: [{ label: 'New Label', value: '' }];
},
}
// ...
``` 
```html
<LabeledSelect
v-model="myValue"
:options="myOptions"
/>
<Checkbox
v-model="toggleLabel"
label="Toggle my label"
/>
```
- Added unit tests for ensuring label updates
- Forced displayed label to match existing options with the same value
Any dropdown as we have no story nor tests.
Any dropdown as we have no story nor tests.
https://user-images.githubusercontent.com/5009481/218513012-fa6f3a03-8f89-4fee-80d5-7951aa01da7d.mov
> LabeledSelect: Displayed label does not update with options

- shell/components/formatter/InternalExternalIP.vue
Fixes #8045 
- Fix margin for copy icon on `nodes` list view
> fix css icon margin

- shell/detail/provisioning.cattle.io.cluster.vue
Fixes #8033 
- update `fakeMachines` naming matching function
Follow steps of #8033 
_Before_
_After_
> Node Pool fake machines bug

- shell/components/form/LabeledSelect.vue
- shell/components/form/__tests__/LabeledSelect.test.ts
Fixes #8173, #8175
The changes introduced here in #8154 have caused some issues in other LabeledSelect implementations. The root of the problem seems to be that the code that runs when options update is using `optionKey`, which is defaulted to `null`. Sorry for the misinformation @cnotv my suggestion on your PR was way off. `optionKey` is used with [getOptionKey](https://vue-select.org/api/props.html#getoptionkey) to generate unique ids for the dropdown option elements. The customization of how the selected option is mutated to the `value` that is emitted is controlled by the `reduce` prop.
I went to update the associated tests and, frustratingly, couldn't write a valid test case where the existing code around `isOutdated` fails.  From what I could see that `isOutdated` is never `true` in …
> fix labeledselect getOptionLabel to use reduce prop when labels change

- shell/components/SingleClusterInfo.vue
- shell/edit/storage.k8s.io.storageclass/provisioners/driver.harvesterhci.io.vue
- shell/models/management.cattle.io.cluster.js
- shell/pages/c/_cluster/explorer/index.vue
Fix kubernetesVersionExtension is '' on the create Harvester storage class page
- https://github.com/harvester/harvester/issues/3052
The kubernetesVersionExtension in `/models/management.cattle.io.cluster.js` always returns `''`. Considering there have some styles depending on kubernetesVersionExtension. I just fix the issue on the create Harvester storage class page.
> HARVESTER: Fix kubernetesVersionExtension is '' on the create Harvester storage class page

- shell/nuxt.config.js
- shell/plugins/steve-create-worker.js
- shell/plugins/steve/subscribe.js
Fixes - Alt fix for https://github.com/rancher/dashboard/pull/8064
- `yarn build-pkg harvester` fails due to import of web workers
- import fails due to the build process missing web worker build config
- Fix is to disassociate the import chain for the web worker creator 
- Assign the steve worker creator to the store via plugin
- On the downside this means rancher/steve specific stuff is applied at a more global level
- Web socket updates work correctly when advanced worker setting is enabled and not enabled
- When enabled the cluster socket should be 'advanced' 
- ![image](https://user-images.githubusercontent.com/18697775/218754690-3420fb91-43b6-4435-8d1c-4e9d7c68897b.png)
> Disassociate the steve worker creator from the steve store

- shell/scripts/test-plugins-build.sh
Fixes #8179 
To improve logging, we pipe the output of some commands into `cat`. Unfortunately, this means if the command fails, the error does not cause the script to fail - we do `set -e` which does this, but this does not catch the errors lost in the pipe.
To fix this, we need to add:
```
set -o pipefail
```
so that errors in the pipe fail the script via `set -e`.
> Extensions test script: ensure build fails when one of the build steps fails

- pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue
- shell/assets/translations/en-us.yaml
- shell/chart/gatekeeper.vue
- shell/chart/istio.vue
- shell/chart/logging/index.vue
- shell/chart/monitoring/index.vue
- shell/chart/rancher-backup/index.vue
- shell/components/ChartPsp.vue
- shell/components/__tests__/ChartPsp.test.ts
Fixes #8053 
This PR adds a component to toggle `<chartvalues>.global.cattle.psp.enabled`, and define it if missing from chart values. It also removes the alerting-drivers custom UI since that app is using a questions.yaml now. 
The big diff from the istio component is because I remove the tabs; there wasn't enough content to justify them.
> add enable psp checkbox to custom chart uis

- shell/detail/provisioning.cattle.io.cluster.vue
- shell/models/provisioning.cattle.io.cluster.js
Fixes #8186 
Handle `eksNodeGroups` being null / undefined.
1. Create an EKS cluster in the AWS console, kube version 1.23/1.24.
2. Import this cluster into Rancher.
3. Go to the cluster information page.
Previously, cluster detail page failed to load with an error about undefined filter.
> [2.6.11] Handle nodeGroups undefined for  imported EKS cluster

- .vscode/settings.json
- shell/assets/translations/en-us.yaml
- shell/dialog/AddonConfigConfirmationDialog.vue
- shell/dialog/GenericPrompt.vue
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #8125
Displayed dialog as indicated in the issue.
- Extended `GeneralPrompt` component to allow use of callback, to make the dialog `async`
- Corrected styling of existing dialog for add-on case due style clashes
To summarize what is defined in all the comments, these are the steps:
- Start creating a K3S cluster with 1.24.x or 1.23.x
- In the `Advanced` tab add under `Additional API Server Args` the value `enable-admission-plugins=NodeRestriction,PodSecurityPolicy`, as defined in [this comment](https://github.com/rancher/dashboard/issues/8125#issuecomment-1438931325)
- Complete the creation
- Edit and try to update the cluster to version 1.25.x
https://user-images.githubusercontent.com/5009481/220091324-1e977ecd-df40-4bca-acdf-680ebb162cf0.mov
> Alert users when upgrading provisioned k3s cluster from k8s <1.25 to >=1.25 if PSP enabled

- shell/detail/provisioning.cattle.io.cluster.vue
- shell/models/provisioning.cattle.io.cluster.js
- shell/plugins/dashboard-store/actions.js
- shell/plugins/steve/subscribe.js
- shell/utils/socket.js
Fixes #7819
Fixes #7815
There's a number of 'stale' screen content when creating an RKE2 DO cluster, adding/removing machine pools (deployments) and scaling up/down a pool (deployment). Stale content covers
- Cluster overall State
- Freshly created pool does not show new machine
- Machine from a removed pool remained
- Pool's Machine summary bar graph not updating
- Pool scaled down still shows removed machine
- Created cluster shows empty pools without deployments
The only consistent way to reproduce any of these, is to scale down the last remaining machine in a second pool (deleted machine stays in second pool) and from the same cluster state edit the cluster to have one in the second pool and nav quickly to the cluster detail page (new machine does not show in pool two). For the …
> Fix stale management cluster resources

- shell/pages/c/_cluster/apps/charts/install.vue
Fixes #8241
- issue caused by the prov cluster missing a spec.rkeConfig.machineSelectorConfig causing helm install getClusterRegistry to silently fail
- solution is to make helm install getClusterRegistry even more hardended to strange scenarios
- Note there were other issues caused by the same function that have the same outcome, that PR was https://github.com/rancher/dashboard/pull/7952
- the provisioning cluster spec.rkeConfig.machineSelectorConfig MUST be `null`
- the chart MUST be one from rancher (we optimised in 2.7.2 to avoid the function for non-rancher charts)
- try to install the chart
> Ensure that the helm install getClusterRegistry process handles missing machineSelectorConfig

- shell/creators/app/app.package.json
`@types/node` got bumped today - this gets picked up by the extensions build which breaks it.
This PR pins it do the v6 node types.
> Fix broken extensions check

- shell/models/clusterroletemplatebinding.js
Fix Harvester v1.1.1 cluster members page is unavailable
- https://github.com/rancher/rancher/issues/40663
- https://github.com/harvester/harvester/issues/3515
The root cause is [here](https://github.com/rancher/dashboard/pull/7245/files#diff-dd84197114a85e2c4f6c8f3af7938f1c603d9d82162f7aa6595c76a0437fc400), `steve` change to `clusterroletemplatebinding`, that makes v1.1.1 Harvester cannot obtain cluster RTB as expected. 
For v1.1.1 Harvester is 
```
const steveBindings = await Promise.all(
clusterRoleTemplateBindings.map(b => b.steve)
);
```
For v2.7-head Rancher is
```
clusterRoleTemplateBindings() {
return this.normanClusterRoleTemplateBindings.map(b => b.clusterroletemplatebinding) ;
},
```
> HARVESTER: Fix Harvester v1.1.1 cluster members page is unavailable

- shell/components/ResourceTable.vue
- shell/components/SortableTable/index.vue
- shell/list/provisioning.cattle.io.cluster.vue
Fixes #8237
- This is a quick fix
- For RKE1 clusters we use the mgmt cluster state instead of row's prov cluster state
- This should all work generically underpinned by using the prov clusters stateObj
- However this does not work, updates sometimes bubble to the prov cluster level and when they do sometimes they even make it to the list. The updates are always received correctly over the socket
- Workaround is to convert the state column and sub row into custom cell and sub row slots
- These update correctly given changes to the mgmt object
Note - I haven't touched the machine summary column, a similar fix might be needed there. I didn't see this testing locally but have in other worlds. Keeping this PR targeted at the specific errors though
- Clusters list open in browser A, changes …
> Fix stale RKE1 cluster info in clusters list

- pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue
Our own lint does not complain, but GitHub complains on PRs:
This PR removes the trailing space.
> Fix lint issue in Checkbox

- shell/models/clusterroletemplatebinding.js
Fix Harvester add cluster member error
- https://github.com/harvester/harvester/issues/3515
The PR [8244](https://github.com/rancher/dashboard/pull/8244) only fixed the error on the cluster member list page, there is still an error when adding cluster members. I update `get steve() {}` to use `dispatch` instead of `getter` because the plugin is using `Promise.all` to get the list of roles.
> HARVESTER: Fix Harvester add member error

- shell/plugins/steve/subscribe.js
- when we receive a `too old` socket watch error we kick off a resync which will watch with a valid revision
- we'll get a resource.stop event following the previous error. socket is in error though so we correctly abort
- the error for this was misleading
- Connected to https://github.com/rancher/dashboard/pull/8224
Can be trigger with a fake revision on cluster list in subscription's `watch`
```
if (!trigger && type === 'management.cattle.io.fleetworkspace') {
trigger = true;
revision = 1;
}
```
> Avoid spurious console.error

- shell/mixins/resource-fetch.js
- shell/plugins/dashboard-store/actions.js
- shell/plugins/steve/subscribe.js
Fixes #7919 
Namespaces can be fed into subscriptions using either `watchNamespace` or the `namespaced` watch option, also the `unwatch` action didn't accept `id`, `namespace`, or `selector` filter parameters so it wasn't possible to unwatch subscriptions that had those criteria.
when the `watch` action is dispatched in findall now we pass in the namespace as either the `watchNamespace` or the `namespaced` option. The other major change here is that we now can unsubscribe with specific filter options so that when the `namespace` option changes we will unwatch any watches using a different namespace.
We should be able to test this by observing socket messages and responses in browser dev tools and if Vue dev tools are available it should be observable that the "started" property in the …
> Sockets subscribe with namespaces and other filters and also unsubscribe

- shell/plugins/dashboard-store/actions.js
- shell/plugins/dashboard-store/mutations.js
- shell/plugins/steve/mutations.js
- Normally we fetch resources and then watch using the revision in that response
- If we get a resource.stop event we'll then try to find the current revision from the store
- This looks at the type cache's revision and revisions in each resource
- Bug
- the type cache's revision is not updated, which leads to very old revisions from a resource being used
- This can cause a `too old` error... which is handled by re-fetching the whole list
- Fix
- Ensure we set the collection's revision when we're likely to need it again
- Tested
- the different find/load store actions/mutations
- this includes incremental loading
- Connected to https://github.com/rancher/dashboard/pull/8224 
- that change basically reverted the code back to a previous state
- this bug is related to that previous state, …
> Persist http response collection revision

- shell/list/provisioning.cattle.io.cluster.vue
Fixes #8292
- RKE2 clusters were using the mgmt cluster instead of provisioning cluster for status
- Only RKE1 clusters should use the mgmt cluster
- Bug was introduced in https://github.com/rancher/dashboard/pull/8249
- Fix is to use the generic state getters that handles the mgmt/prov state split in models
- RKE1 / RKE2 provisioning
> Ensure the correct input is given the the Cluster list BadgeState component

- shell/machine-config/azure.vue
Fixes #8283 
- fix bug where location wasn't being populated before fetching vmSizes on async fetch when adding a new machine pool for azure after cluster creation
- Provision an `Azure` cluster
- Edit that provisioned cluster
- Add a new machine pool to the provisioned cluster
- Make sure UI doesn't crash as before
> fix azure machine pool bug

- .vscode/settings.json
- shell/assets/translations/en-us.yaml
- shell/config/types.js
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
- shell/models/provisioning.cattle.io.cluster.js
Fixes #7553
- Added requirement to have PSPs enabled for the current management cluster
- Check is done only for RKE2, editing mode of provisioned clusters (no `reconciling`)
- Added PSPS type
- Corrected with optional chaining for provisioned cluster model while retrieving `mgmtClusterId`
- Create and complete provisioning of RKE2 cluster with version 1.23.x or 1.24.x
- PSP will be created within the cluster, you can explore it and search Pod Security Policies to ensure it
- Edit cluster configuration and select higher K8S version 1.25.x
- A banner will appear communicating the removal of PSPs
Note: It is NOT possible to create a cluster RKE2 without PSPs from the UI.
https://user-images.githubusercontent.com/5009481/220956862-de3414ca-aeca-4fdf-aac6-45af5924c715.mov
> Add a warning alert when migrating to 1.25 if they have PSPs. 

- shell/pages/c/_cluster/uiplugins/index.vue
- update icon logic on extensions to show the icon of the latest compatible version and not the chart icon
Note: Elemental will use a new icon on `v1.1.0` and it uses rancher `v2.7.2`. If we were on a `v2.7.1` system (or even earlier) it would get the chart icon from Elemental `v1.1.0` (old logic - get's the icon from the latest existing version), which might not even be available for use, therefore breaking the card icon.
> update icon logic on extensions

- shell/config/uiplugins.js
- shell/pages/c/_cluster/uiplugins/index.vue
This PR addresses an issue with `v2.7.2-rc5` where for Elemental all versions of the extension were not available due to the presence of `catalog.cattle.io/ui-version` annotation (for rc version, `semver` comparison was always returning `false`).
- fix issue when all versions of an extension are not available (ui was crashing - not double-checking the `installableVersions` array)
- support `semver` comparison for `rc` versions of Rancher by getting only the version part (string split)
> fix issue when all extensions versions not available

- shell/config/product/explorer.js
- shell/store/type-map.js
Fixes #8274 
This PR hides the PSA resource in downstream clusters, because while the CRD needs to be installed, PSAs in downstream clusters can't be used for anything: they need to be configured in the local cluster.
As explained in the original issue:
https://github.com/rancher/dashboard/issues/8274#issuecomment-1449045952
>Some technical background information about the PodSecurityAdmissionConfigurationTemplate(PSACT) CRD in the downstream cluster:
The CRD exists in the downstream cluster but never be used. We have it due to a limitation in rancher-webhook: because the same rancher-webhook app is installed in both the local and downstream cluster(with different values, of course), and the app requires the PodSecurityAdmissionConfigurationTemplate CRD to exist in the cluster, therefore …
> Hide PSA CRD in downstream clusters

- README.md
This fixes broken links to the extensions developer docs in `README.md`
Fixes #8352
> Fix links to extensions developer docs

- shell/assets/translations/en-us.yaml
- shell/config/table-headers.js
- shell/detail/constraints.gatekeeper.sh.constraint.vue
- shell/models/constraints.gatekeeper.sh.constraint.js
- shell/pages/c/_cluster/gatekeeper/index.vue
Fixes #7853 
This PR Fixes an inconsistency in the OPA Gatekeeper violations view - on one page we show the count being the number of violations listed in the constraint resource, where as on the other we show the total violations form the count.
The correct value to use if from the `totalViolations` property - see: https://open-policy-agent.github.io/gatekeeper/website/docs/audit/#constraint-status - the constraint is limited to a number of violations that it will store detail for (default seems to be 20).
Also:
- Improved padding slightly to reduce it down
- Added a banner when the number shown is not the same as the number with detail
- Pulled out one more hard-coded string
- Fixed a bug where the kind in the constraint violations list was empty
- Added the count of violations to the …
> Fix OPA Gatekeeper constraint inconsistencies

- scripts/build-hosted
The missing ending '/' was causing the router to parse routes incorrectly
Verified using this build `https://releases.rancher.com/dashboard/prod-dashboard-dev/index.html`
> Add missing '/' to the ROUTER_BASE in build-hosted

- shell/assets/translations/en-us.yaml
- shell/chart/gatekeeper.vue
- shell/mixins/chart.js
- shell/pages/c/_cluster/apps/charts/install.vue
Fixes # https://github.com/rancher/dashboard/issues/8238, specifically the requirement from [this comment](https://github.com/rancher/dashboard/issues/8238#issuecomment-1453456555)
This PR allows custom chart ui components to edit crd values, specifically `enableDefaultSeccompProfile` for Gatekeeper - see comment [here](https://github.com/rancher/dashboard/issues/8238#issuecomment-1453456555)
Code in the chart install page has been shuffled around a bit to fetch crd version info upfront rather than during the 'save' process, and pass that info to custom ui components. The original issue is very general in its title but the problem being solved is specifically around OPA gatekeeper...I've written this PR in such a way that we should be able to expand editing CRD values to other charts if …
> Add enableDefaultSeccompProfile option to the Gatekeeper chart install ui

- shell/models/provisioning.cattle.io.cluster.js
Fixes #8393 
- add check to `resourceMethods` property so that UI doesn't fail when `clusterTemplatesSchema` is empty due to restricted access by the user
- Provision a `rancher - 2.7-head commit id: 70455b1 ` system
- As an admin, create a `base user` and add `Create new Cluster` role and `Create new RKE Cluster Templates` role.
- Login as the user just created
- Create an RKE1 cluster (use Digital Ocean, for example)
- Check that the `Cluster Management` page or the `homepage` doesn't break when displaying the list of clusters
> Fix error listing clusters for a base user (release 2.7.2 branch)
