rancher/dashboard

- config/demo-stacks.js
demo repo is now emoji photo demo: https://github.com/daxmc99/rio-demo/tree/03094af324bb8e8a72e34394089ab796692a9358
> Change 'deploy stack' demo repo

- assets/styles/global/_tooltip.scss
- pages/auth/setup.vue
#74 - click-to-open tooltip in auth setup step-2 swapped out for a popover that closes on click away
> setup tooltip close on clickaway

- components/cru/rio.cattle.io.v1.router/Destination.vue
- components/cru/rio.cattle.io.v1.router/Rule.vue
#134 
* router destination dropdown shows unique apps, not services 
* dropdown only shows apps within router namespace
* no placeholders
* rule only has two modes for destination: forward to service and redirect
* destination weight input and 'remove' button only appear when more than one destination is present
> router destination dropdown

- layouts/default.vue
> opening action menu no longer shifts up page footer

- .storybook/.babelrc
- .storybook/webpack.config.js
- components/form/LabeledInput.stories.js
* added webpack config for storybook so all the nuxt-aliased paths involving '@' work
> storybook webpack config for aliased paths

- components/form/Checkbox.vue
- models/user.js
- plugins/norman/resource-instance.js
#293 
- revert prior change: state column in list view defaults to 'active' if resource has no computed state prop
- users state column is based off 'enabled' prop
- minor change to checkbox styling so table header underline is even
> move enabled/disabled badge state func to users model

- config/table-headers.js
- detail/core.v1.secret.vue
- edit/core.v1.secret.vue
- plugins/norman/resource-instance.js
Create kubernetes resources with 'type' field populated correctly (from _type)
If a reg secret has multiple auths, list them (but don't show for editing)
> POST secret type correctly

- assets/styles/global/_form.scss
- components/ResourceDetail.vue
- components/ResourceYaml.vue
- components/form/ArrayList.vue
- components/form/InputWithSelect.vue
- components/form/KeyValue.vue
- components/form/LabelSelector.vue
- components/form/LabeledInput.vue
- components/form/MatchKinds.vue
- components/form/NameNsDescription.vue
- components/form/NamespaceList.vue
- components/form/NamespaceSelector.vue
- components/form/RuleSelector.vue
- components/formatter/LinkDetail.vue
- components/formatter/LinkNode.vue
- config/type-config.js
- detail/gatekeeper-constraint.vue
- edit/gatekeeper-constraint.vue
- edit/workload/Job.vue
- edit/workload/ValueFromResource.vue
- edit/workload/index.vue
- shared/gatekeeper-constraint.vue
- utils/customized.js
This implementst the view, create and edit pages for the
gatekeeper constraints. The constraint templates weren't
touched since we intend to only use the yaml editor.
rancher/dashboard#307
> Implement the view, create and edit pages for constraints

- assets/styles/global/_form.scss
- components/form/LabeledInput.vue
Fixes the issue where the number inputs are larger on workload pages.
rancher/dashboard#321
> Fix padding for labeled input with type number

- config/type-config.js
- layouts/default.vue
- middleware/authenticated.js
- store/type-map.js
This ensures that the type configuration is available before resourceDetail looks up custom edits or details.
> Ensure typeconfigs are applied before type-map getters are used

- shared/gatekeeper-constraint.vue
**This should be merged after https://github.com/rancher/dashboard/pull/430**
There's an upstream issue which prevents gatekeeper from processing
namespaces with empty lists incorrectly. We need to remove the
namespaces field if it's empty.
open-policy-agent/gatekeeper#508
> Removing namespaces from match when empty

- components/GatekeeperViolationsTable.vue
- components/SortableTable/index.vue
- components/SortableTable/paging.js
We don't want the number of violations to flood the entire page.
rancher/dashboard#386
> Add paging to the constraints violation table

- pages/c/_cluster/gatekeeper/constraints/index.vue
This ensures we don't attempt to access the description annotation
from the constraints page unless the annotations are present.
rancher/dashboard#383
> Ensure a lack of annotations doesn't prevent constraints from rendering

- components/GatekeeperViolationsTable.vue
We want to prevent wrapping on commonly sized names.
rancher/dashboard#386
> Increasing the size of the name column of the constraint violations table

- components/GatekeeperConfig.vue
- pages/c/_cluster/gatekeeper/index.vue
so you can re-enable without having to refresh the page
rancher/dashboard#394
> Handle disable at the route level and recreate a new gatekeeper app

- components/ResourceYaml.vue
This is a temporary fix until we get new mocks from design for the
diff view.
rancher/dashboard#379
> Prevent the edit and diff buttons from overlapping

- components/ResourceDetail.vue
- components/ResourceYaml.vue
Cloning didn't provide the create or preview buttons and when displayed attempted to update a resource instead of create a
new one.
This will add the buttons and will allow the new resource to be created.
rancher/dashboard#374
> Improving the functionality of YAML clone

- components/PromptRemove.vue
- models/templates.gatekeeper.sh.constrainttemplate.js
- pages/c/_cluster/gatekeeper/templates/index.vue
We don't want the user to delete constraint templates if the templates
are being used by existing constraints. This provides a message and
disables the delete button if the user attempts to delete a template
that's currently in use.
rancher/dashboard#375
> Adding a messaging to constraint template deletion

- components/form/Labels.vue
- components/form/Taints.vue
- config/labels-annotations.js
- config/type-config.js
- detail/node.vue
- edit/node.vue
Added a custom edit
Made a few modifications to the detail
Converted into a virtualType to remove import and create from the list page
rancher/dashboard#241
**The spec.displayName for custom name and kubernetes.io/hostname for hostname are both going to need to be looked into further (I believe by the backend).**
**displayName is not getting returned by steve and I don't believe rancher currently uses kubernetes.io/hostname even though it appears to be the appropriate annotation.**
> Making updates to the node resource

- config/type-config.js
- pages/c/_cluster/_resource/index.vue
- plugins/steve/resource-instance.js
- store/type-map.js
This is to support special types like Node where the user shouldn't be able
to create the resource through normal means.
rancher/dashboard#507
> Enabling the ability to mark types and both immutable and unCreatable

- components/ConsumptionGauge.vue
- components/PercentageBar.vue
- plugins/steve/resource-instance.js
Switched the percentage circle over to the percentage bar to fit the new
design.
Also decoupling the Delete option from type-map/isEditable
rancher/dashboard#415
> Switch consumption gauge percentage graphic

- components/ResourceYaml.vue
- components/form/LabeledSelect.vue
- components/form/NameNsDescription.vue
- package.json
This fixes runtime and lint warnings. It also makes the linter
treat warnings as errors now so we'll stop checking in code that has
warnings.
If you want to avoid prs with warnings consider adding a
'yarn lint' or 'yarn build' to .git/hooks/pre-push.
> Fixing warnings

- models/app.js
- models/apps/rancher-gatekeeper-operator.js
- plugins/steve/model-loader.js
- plugins/steve/resource-proxy.js
When working on adding 'Add Constraint' and 'Add Template' to the
OPA Gatekeeper page I noticed that there wasn't a good way to
create custom models for specific chart app types. To fix this I went
ahead and made it so that we can load app models from the
'models/apps' directory and merge that with the 'models/app' model.
I think this will be useful for future apps like istio.
rancher/dashboard#391
> App model specialization and OPA Gatekeeper menu items

- assets/translations/en-us.yaml
- models/management.cattle.io.cluster.js
Local k8s clusters do not have a key with `config` so the method to display provider would fail with an `undefined` error. Instead we should mimic the logic of classic rancher ui and display the imported provider info. Additionally we'd have a similar issue with k8s version so we should display something, in this case I've chosen `unknown`. 
rancher/dashboard#529
> Local k8s cluster issues

- models/apps/rancher-gatekeeper-operator.js
- pages/prefs.vue
Adds action for downloading the gatekeeper app spec as yaml.
Also fixes `viewInApi` button that was tweaked and broke in a previous commit.
> Gatekeeper Download Yaml

- components/form/ResourceTabs.vue
- detail/namespace.vue
- detail/pod.vue
- detail/rbac.authorization.k8s.io.clusterrole.vue
- detail/rbac.authorization.k8s.io.role.vue
- detail/secret.vue
- edit/namespace/index.vue
- edit/rbac.authorization.k8s.io.clusterrole.vue
- edit/rbac.authorization.k8s.io.role.vue
- edit/secret.vue
- edit/workload/index.vue
- shared/gatekeeper-constraint.vue
Since every create/detail page will have labels and annotations in tabs, I've added a ResourceTabs component with those two tabs and slots for more before and after
> labels and annotations consistent on every create/detail page

- models/management.cattle.io.cluster.js
- plugins/steve/resource-instance.js
Prevents the local cluster from being deleted by adding can check on the cluster model and looking for internal on the cluster spec.
Also refactored the `can*` checks into methods on the resource instance so they can be overridden in the future if need be. Also refactored the checks that were manually checking the links object to use the `hasLink` method. 
rancher/dashboard#530
> Prevent Local Cluster Delete

- components/AsyncButton.vue
- components/GatekeeperConfig.vue
- components/form/Footer.vue
When enabling gatekeeper I used to watch the state but that doesn't seem to be present any longer or it never was. The way that the config observer was working hid the state watcher failure. Rather than watch the state I've refactored to watch the condition `Deployed`. I've also refactored the config observer so that it won't mask the failure of wait for condition if takes too long but it also wont disguise the app never deploying scenario. 
Additionally I exposed the async button label params in the form/footer component so when we're in the customize view it doesn't say create but enable like it does when just configuring it. 
rancher/dashboard#371
> Gatekeeper Config Bugs

- assets/translations/en-us.yaml
- components/ClusterDisplayProvider.vue
- components/GatekeeperConfig.vue
- components/InfoBoxCluster.vue
- config/types.js
- models/management.cattle.io.cluster.js
- pages/c/_cluster/index.vue
I chose to make the display provider a component rather than a computed property on the model for a couple reasons.
1. Given we have to traverse 3 apis (cluster->node pools->node templates) to get the provider info for an RKE based cluster and we dont `Load All The Things ™️` or have the convenience methods of `hasMany`, `reference` etc that ember-api-store has, it makes more sense to pass the data down rather than place it on the cluster model and hope we loaded everything before we need the property. 
2. We'll need this info in the future in other places. 
rancher/dashboard#478
I also put in a fix for OPA to even out the 4vs3 items in the info
rancher/dashboard#392
Additionally this also fixes where we grab the cluster k8s version from.
https://github.com/rancher/dashboard/issues/534
> Better parsing for a cluster provider info

- detail/secret.vue
- edit/secret.vue
- mixins/create-edit-view.js
* repopulate registry provider radio group (at least default to custom, not dockerhub)
* repopulate key, crt fields
* disable type dropdown on edit as it is immutable 
* fix bug with description not being saved
> populate edit correctly

- assets/styles/base/_variables.scss
- assets/styles/fonts/_icons.scss
- assets/styles/global/_columns.scss
- assets/styles/vendor/vue-js-modal.scss
- assets/translations/en-us.yaml
- components/ActionMenu.vue
- components/DetailTop.vue
- components/InfoBoxCluster.vue
- components/Loading.vue
- components/PercentageBar.vue
- components/ResourceYaml.vue
- components/SortableTable/index.vue
- components/formatter/BadgeState.vue
- nuxt.config.js
- package.json
- pages/c/_cluster/index.vue
- yarn.lock
There was more feedback on the cluster overview page [here](https://github.com/rancher/dashboard/issues/580).
This PR also adds a dependency `nuxtjs/style-resources` which allows us to push scss resources into a global space that nuxt is aware of which nigates the need to import any functions/mixins/variables in to the individual Vue components (I did not go back and remove imports that were already present, I can do this if we'd like though). 
Also changes the styles of detail top to use css grid instead of flex box. Grid allows for a more uniform alignment when wrapping elements whereas flexbox will just wrap on what ever. The col/rows were buggy and had alignment issues on different widths. IMO the styles and markup are much easier to reason about here when using grid. 
Additionally I …
> Cluster Overview UI/UX Changes

- assets/translations/en-us.yaml
- detail/configmap.vue
- edit/configmap.vue
- plugins/i18n.js
Similar to ember I want to be able to use the same method for
translating within templates and code. If we like this we
could replace the component and the directive since this can
easily be used in place of both of those.
> Adding t() translation as a Vue instance method

- assets/styles/base/_helpers.scss
- assets/styles/global/_labeled-input.scss
- assets/translations/en-us.yaml
- components/ContainerResourceLimit.vue
- components/InfoBoxCluster.vue
- components/Tabbed/index.vue
- components/TabbedLinks/index.vue
- components/form/LabeledInput.vue
- components/form/UnitInput.vue
- config/labels-annotations.js
- detail/namespace.vue
- edit/namespace/ResourceQuota.vue
- edit/namespace/index.vue
- utils/units.js
Feedback from UX Review for Namespace Create/Edit/Detail
Add detail top to namespace pages.
Remove resource quota, Add Container Resource Limits component. I did not reuse the resource quota component because they do not deal with the same data. It is similar but the Container Resource Limits exist as a annotation on the namespace itself. Container Limits is also a set json map of 4 targets while Quotas can target many different items. Our resource quota component should be updated to allow that as we do on the ember side. 
Various small updates and tweaks to styles and minor bug fixes.
rancher/dashboard#568
rancher/dashboard#569
rancher/dashboard#594
> Namespace Updates

- components/formatter/IngressTarget.vue
- components/formatter/LinkDetail.vue
- components/formatter/LinkDetailImage.vue
- components/formatter/SecretType.vue
- models/app.js
- models/apps/rancher-gatekeeper-operator.js
- models/rio.cattle.io.service.js
- plugins/extend-router.js
- plugins/steve/resource-instance.js
replace and push both work  as intended. You can
specify a a full url  if you don't want to have the baseUrl
prepended. Better yet, if you're navigating within
the app it's better to specify a location.
The custom resolve was actually breakinging a huge
amount of links in the app which was caused 404s if a
user attempted to open a link in a new tab. Most things appeared to work presumably because vue-router
was handling the page switches instead of the browser.
rancher/dashboard#643
> Remove custom VueRouter.resolve

- assets/styles/vendor/vue-select.scss
- assets/translations/en-us.yaml
- components/Tabbed/index.vue
- components/form/LabeledSelect.vue
- components/form/ServicePorts.vue
- edit/service.vue
This PR adds the Create and Edit page for the Service resource. 
rancher/dashboard#583
Added some updates to the Tabbed component to handle selecting a tab when an active tab is dynamically removed from the slot as is the case for services where we need to hide certain tabs based on the service type.
Added logic to labeled input to take a localized label.
> Services - Create & Edit

- edit/secret.vue
#616 
hide tls.key on cert edit page; preserve key on save if a new one isn't provided
> hide private key on edit cert page

- plugins/steve/actions.js
- plugins/steve/mutations.js
- plugins/steve/resource-instance.js
- plugins/steve/subscribe.js
- For the creating a new resource -> save() case, add the `existing` model to the array instead of just the map
- Apply all the queued changes together once a second instead of continuously so that there's not constant recomputes and rereneders under heavy change rates.
- Combine consecutive `load`s of new data into one mutation instead of many when possible
- This also indirectly addresses the problem of a `resource.create` event coming in for a resource that's being `save()`d and being added to the store from that before save has a chance to put in the `existing` entry first.
> Queue updates from subscribe and apply once per second

- components/formatter/LinkNode.vue
- detail/networking.k8s.io.ingress.vue
- pages/c/_cluster/_resource/index.vue
Create buttons were still using a relative url instead of a location.
This switches over to locations so we don't get end up with
/dashboard/dashboard/
rancher/dashboard#657
> Fix create buttons

- pages/c/_cluster/_resource/index.vue
The routes were erroneously being wrapped in an object.
> Fixing generic list page use of masthead

- components/ResourceDetail/index.vue
- plugins/steve/actions.js
There were two issues that were causing the 409s.
1. When using cluster/find the resource wasn't being watched
so the resource was out of date.
2. Cloned resources don't get the updates either.
This change provides an option to to allow cluster/find to
watch the resource and when in VIEW mode the resource isn't
cloned so it can receive updates.
rancher/dashboard#679
> Fixing cordon/uncordon on the detail page

- components/ResourceDetail/index.vue
Switching masthead over to use originalModel broke create
pages because originalModel was null. This ensures that
originalModel is defined.
> Ensure originalModel is defined for create in ResourceDetail

- components/form/NameNsDescription.vue
- shared/gatekeeper-constraint.vue
Making the detail-top consistent with all the other pages and
removing the name from the constraints detail page.
rancher/dashboard#695
> Removing the name from the constraints detail page

- components/ResourceDetail/index.vue
- components/ResourceYaml.vue
- plugins/steve/resource-instance.js
`cleanYaml` was being called on—and obliviating commented tips from—yamls in create-from-yaml pages
this PR ensures `cleanYaml` is only called to: 
* re-map `_type` to `type` for editing
* apply `cleanForNew` logic and remap `_type` to `type` for cloning
> do not clean yamls for create

- edit/networking.k8s.io.ingress/Certificates.vue
It looks like a failed merge removed the TLS_CERT. This resulted
in all of the certs getting filtered out and not displayed as options.
rancher/dashboard#753
> Fix tls cert options on the ingress pages

- shared/gatekeeper-constraint.vue
OPA Constraints don't work unless there's an apiGroup present
even if it's empty. This ensures that the empty apiGroup is present
if no apiGroups were specified.
rancher/dashboard#764
> Ensuring apiGroups have an empty value

- shared/gatekeeper-constraint.vue
OPA Constraints don't work unless there's an apiGroup present
even if it's empty. This ensures that the empty apiGroup is present
if no apiGroups were specified.
rancher/dashboard#764
> [backport] Ensuring apiGroups have an empty value

- components/ClusterDisplayProvider.vue
We should be displaying the first node pool that matches our cluster id not only the first node pool. Got the stores conflated going back and forth. I forgot that we were getting all node pools not all node pools for this cluster. 
rancher/dashboard#702
> select correct node pool for display info

- assets/styles/base/_helpers.scss
- assets/styles/global/_labeled-input.scss
- assets/translations/en-us.yaml
- components/ContainerResourceLimit.vue
- components/form/ArrayList.vue
- components/form/Command.vue
- components/form/Container.vue
- components/form/HealthCheck.vue
- components/form/KeyValue.vue
- components/form/LabeledInput.vue
- components/form/LabeledSelect.vue
- components/form/MatchExpressions.vue
- components/form/Networking.vue
- components/form/NodeAffinity.vue
- components/form/PodAffinity.vue
- components/form/PodSecurity.vue
- components/form/Probe.vue
- components/form/RadioButton.vue
- components/form/RadioGroup.vue
- components/form/Scheduling.vue
- components/form/Security.vue
- components/form/Tolerations.vue
- detail/pod/index.vue
- edit/rbac.authorization.k8s.io.clusterrole.vue
- edit/rbac.authorization.k8s.io.role.vue
- edit/secret.vue
per https://github.com/rancher/dashboard/issues/685#issuecomment-642424214
link to node detail in detailTop
update networking nameservers and and search domain labels
Show 'none configured' messages for healthcheck, resource limits, and pod affinity/anti affinity
Add namespaces to pod affinity
Additionally, I noticed that pod affinity/anti-affinity requires a [topologyKey](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#an-example-of-a-pod-that-uses-pod-affinity) and added a field below 'namespaces'
> Pod detail feedback

- assets/translations/en-us.yaml
- components/Tabbed/Tab.vue
- components/Tabbed/index.vue
- components/form/ResourceTabs/index.vue
- edit/service.vue
The main drive behind the refactor was dynamic tabs. `vm.$children` does not return an ordered list. When tabs were added or removed dynamically the order would get funky. Rather than refactor the component, and thus its implementations, to take a list of tabs and their data I built on the `vm.$children` concept.  `filteredTabs` now runs the show and maintains a list of the initial tab order (which is the order on render). The method returns an re-ordered list that matches the initial order. rancher/dashboard#716
I refactored out the window `hashChange` events we were setting up in favor of Vue's built-in watching the `$route`s hash. Other window hash references changed in favor of Vue built-in's.
Refactored a nested ternary in favor of a functional check, it's more verbose but easier to …
> Refactor Tabbed Component

- components/Tabbed/index.vue
`$router.replace` isn't working quite right for all page modes (create/edit/view).
> revert tabbed router hash update to use window

- assets/styles/vendor/vue-select.scss
- components/form/LabeledSelect.vue
- components/form/Security.vue
The Security component didn't use the LabelSelect view mode so I didn't touch the view mode yet. We may want to update the multi-selection LabelSelect to support a view like what we have here. What do you think?
rancher/dashboard#661
**Single selection without label**
**Single selection with label**
**Multiple rows without label**
**Multiple rows with label**
**Single row with label**
**Single row without label**
**Empty without label**
**Empty with label**
**Multi-selection view for Security**
> Adding label support to multi-selection LabelSelect

- pages/c/_cluster/_resource/index.vue
If a user edited a resource and then attempted to create a new
resource they would be taken to the view page of the previously
edited resource.
This was being caused by adding the existing route params to the
location used by the create button. More specifically the existing
params contained an id which caused the mode to be computed
incorrectly.
By removing all of the existing params the create, createAsYaml, 
edit, editAsYaml, clone and view pages all appear to work.
rancher/dashboard#758
> Fixing the create button

- components/ResourceDetail/index.vue
- mixins/create-edit-view.js
- pages/c/_cluster/_resource/index.vue
Removing `$route.params` from the list page was causing all the data in that page dependent on params to be computed incorrectly e.g. `hasCustomListComponent` always returns `false`
The create/edit routing bug appears to be from `doneParams` in `ResourceDetail` — used to redirect after cancel/create/save in `create-edit-view` —  which was computed using the current page's route params, including `namespace` and `id`. Filtering these out ensures that the router action to return to list view does not include any create/edit/view-specific params
> fix resourcedetail params

- assets/translations/en-us.yaml
- components/SortableTable/index.vue
- components/SortableTable/selection.js
- components/SortableTable/selectionStore.js
- We now enable bulk actions even if only some of the selected
items can perform the action.
- We inform the user that only some of the selection can be acted
upon and we indicate which of the selection can be acted upon.
rancher/dashboard#597
**Notes:**
- I changed the language used to "Available for {available} of the {total} selected" and "Available for all of the selected". I'll change it back to the mock if we prefer that.
- I also added the slide-right animation because it was there by default when hovering over the delete button and I liked it. I'll remove it if we prefer to it without.
**Demo:**
> Updating sortable table bulk actions

- components/ResourceDetail/index.vue
When I (attempted to) fix `doneParams()` previously I changed the function to return an array instead of an object.
:(
> fix fixing of doneParams in ResourceDetail

- edit/networking.k8s.io.ingress/index.vue
We should only show the service targets that are in the current resource's namespace.
rancher/dashboard#757
> Appropriately filter serviceTargets for ingress page

- assets/styles/themes/_dark.scss
- assets/styles/themes/_light.scss
- assets/translations/en-us.yaml
- components/CodeMirror.vue
- components/Tabbed/index.vue
- components/YamlEditor.vue
- components/chart/gatekeeper/Config.vue
- components/form/KeyValue.vue
- components/formatter/ClickExpand.vue
- detail/secret.vue
- plugins/codemirror.js
Per @deniseschannon request, this PR un-hides the cert data in the secret detail view of service acct tokens (and other secrets with long data values). `KeyValue` view-mode styling truncates all long `key` and `value` cells, but I think it makes sense for multiline inputs to remain multiline in view mode.
> do not truncate multiline key/value in view

- assets/translations/en-us.yaml
- components/ResourceDetail/Masthead.vue
- layouts/default.vue
If the resource is in error or transitioning display a banner with a
message provided by the backend.
rancher/dashboard#628
> Adding a state banner to the mastehead

- assets/styles/vendor/vue-select.scss
- components/form/ServicePorts.vue
- edit/service.vue
- package.json
Services Port Rules contains a param `targetPort` that can be string or int types. I updated the logic there to parse into an int if it can be, other wise we leave it as is. 
Additionally I slipped in a couple smaller fixes:
Swap v-select with Labeled Select
Drop dotenv package as NuxtJS >=2.13.0 includes this as a dependency now.
Wonky styling on port protocol rule row
Prior:
Now:
> Service TargetPort Accept Multiple Types

- components/DetailTop.vue
- components/ResourceDetail/index.vue
It looks like the nuxt changes caused the use of href="#" to navigate away from the current page. This change prevents the default action and keeps the user on the page when clicking Show # Annotations.
We also wanted to hide DetailTop on the yaml page.
rancher/dashboard#867
> Hide DetailTop on yaml view and prevent Show # Annotations from navigating away from the page

- edit/networking.k8s.io.ingress/RulePath.vue
- edit/networking.k8s.io.ingress/index.vue
Path could be created but not edited. update() wasn't being called from the path input field.
There was also an issue with calling Object.keys on a potentially undefined object that was resolved.
rancher/dashboard#756
> Making ingress path editable

- models/node.js
- pages/c/_cluster/explorer/index.vue
We only show the live metrics for worker nodes. The HA cluster that I created on GKE doesn't add the 'node-role.kubernetes.io/...' label. The lack of this label causes us to filter out all nodes since we don't consider them to be workers.
This makes better checks to ensure we only show the metrics when they're present.
rancher/dashboard#776
> Updating when we display metrics for HA Local clusters

- assets/translations/en-us.yaml
- pages/c/_cluster/explorer/HardwareResourceGauge.vue
- pages/c/_cluster/explorer/index.vue
- Replaced naked strings with translations
- Removed the suffix prop and just use name since both are the same for each of our cases.
rancher/dashboard#885
> Updated Ram to Memory

- pages/c/_cluster/explorer/Glance.vue
- pages/c/_cluster/explorer/HardwareResourceGauge.vue
- pages/c/_cluster/explorer/ResourceGauge.vue
- pages/c/_cluster/explorer/index.vue
This uses already established breakpoints and makes reasonable looking
renders past the point of the navigation header breaking.
Depending on how navigation is updated we may need to make one more 
breakpoint at a smaller resolution.
rancher/dashboard#892
> Made the cluster overview page more responsive

- edit/namespace/index.vue
The project field was only being added to the label and not to the annotation. 
Because it wasn't added to the annotation it wasn't showing up in ember.
I also noticed the watch method wasn't getting called everytime so I
moved the logic to a willSave method.
rancher/dashboard#878
> Fixing namespace project assignment

- components/Wizard.vue
- components/form/NodeScheduling.vue
- edit/workload/index.vue
The wizard was obliterating other query params on initial load, which prevented going to edit/clone views.
Also, I included `spec.replicas` and `spec.schedule` as necessary to advance beyond the first step where applicable. Checking for `metadata.name` needs more work as it isn't being assigned a value reactively, but I'd like to hold off on going down that road until we have clearer goals for workload creation & wizards in general.
> fix wizard nav

- components/ActionMenu.vue
- components/PromptRemove.vue
- components/SortableTable/index.vue
- components/SortableTable/selection.js
- components/SortableTable/selectionStore.js
- store/action-menu.js
The alt action (skip prompt) for delete was only working on single resources because of the spread operator used in the bulk action `.call()`.  Every other use of `_execute` appears unaffected by this change. I couldn't find anywhere else `args` were potentially used in an action and I'm not really sure why they were being spread on [bulk actions](https://github.com/rancher/dashboard/blob/cb883b69c9242ff531a0f15fbd083aa1f24ef7aa/components/SortableTable/selectionStore.js#L256) and not [regular actions](https://github.com/rancher/dashboard/blob/cb883b69c9242ff531a0f15fbd083aa1f24ef7aa/components/SortableTable/selectionStore.js#L272).
It's worth noting that while this fixes the delete functionality, the resource list might not reflect that still.
> Bugfix delete alt action

- assets/styles/base/_variables.scss
- assets/styles/global/_columns.scss
- assets/styles/global/_tooltip.scss
- components/form/Footer.vue
- components/form/KeyValue.vue
- components/form/Tolerations.vue
The sortabletable component used here seemed to be breaking my Istio page and rather than investigating that further I figured I would just replace it since it's part of this issue anyway: https://github.com/rancher/dashboard/issues/669#issuecomment-665317359
I kept the behavior when there's no data in create/edit and view mode consistent with the SortableTable implementation. I also changed the add/read from file buttons to ButtonDropdown
`removeAllowed = false`
`readAllowed = false`
`readAllowed = true; addAllowed=false`
`valueBinary=true`
> remove sortabletable from keyvalue in favor of css grid

- assets/translations/en-us.yaml
- components/CruResource.vue
- components/ResourceYaml.vue
- components/form/Labels.vue
- edit/service.vue
- models/service.js
Adds a generic `CruResource` component. 
`CruResource` has 3 states:
Subtype selection: If the resource has subtypes that can be selected, e.g. service cluster ip/external name/ etc, it will show this on create. On edit the user will bypass subtype selection and proceed directly to the form view.
Form Editor: Exposes a define slot which allows the consumer to pass in the form. This was made to be as generic as possible but this could be updated to include the tabbed/tab and build the forms but imo would make the component much less dynamic so I opted for using a slot here where we can pass tabbed/tab down.
Yaml Editor: Exposes a yaml-review action where the user can further modify the resources yaml. Cancelling/back from this state will trigger confirmation modals.
Screens:
Initial State: …
> Feature - Generic Create Component

- assets/translations/en-us.yaml
- chart/logging/index.vue
- chart/logging/providers/elasticsearch.vue
- edit/chartInstallAction.vue
rancher/dashboard#895
Notes:
- I added a stopgap to chartInstallAction to account for the wrong annotation but we should be able to remove that shortly.
- It looks like the modifications to `values` isn't getting saved. I checked istio and it seemed to be the same over there so I left it for now since I think the chart framework is still being worked on. I poked around a little and I think we're overwriting the `values` with the `valuesYaml`.
> Adding a custom page for the logging chart

- components/CruResource.vue
- components/ResourceYaml.vue
- edit/service.vue
Refactor `canCreate` to `validationPassed` to make variable intention clear.
Refactor markup so subtype selection is not limited to form only view.
Refactor to offer Yaml preview on edit.
> Generic Cru Component - PR feedback items

- assets/translations/en-us.yaml
- components/CruResource.vue
- components/ResourceDetail/index.vue
- components/ResourceYaml.vue
- components/Tabbed/Tab.vue
- components/Tabbed/index.vue
- edit/service.vue
- edit/workload/index.vue
- mixins/create-edit-view.js
- models/workload.js
- pages/c/_cluster/_product/_resource/_id.vue
#964 
Implemented `CruResource` in workload create instead of `Wizard`, and added toggle-able tabs:
Changes to CruResource:
* Allow anchor tags in subType description
* Do not abbreviate `bannerAbbrv`
* Cancel button shows confirmation modal on both yaml and form view
* Yaml and form view both use AsyncButton with correct mode (create/save)
* AsyncButton shows error state instead of returning to list view
* Display save errors from yaml and form view in CruResource
* ShowDiff button is hidden when diff is showing
* kebab-case `select-type` event (lint complained)
> Update workload create flow

- assets/styles/global/_tooltip.scss
- assets/translations/en-us.yaml
- pages/c/_cluster/explorer/Glance.vue
- pages/c/_cluster/explorer/ResourceGauge.vue
- pages/c/_cluster/explorer/index.vue
- Increased alert text size by 2px
- Hide alerts if there aren't any
- Switched from created to age
- Adjusted event column widths
- Fixed a tooltip position bug
rancher/dashboard#925
> Visual updates to the cluster overview page

- components/CruResource.vue
- edit/service.vue
- package.json
- utils/create-yaml.js
- utils/object.js
- yarn.lock
Updates the yaml editor component to seed  the content of yaml with data from the form if it exists. This is needed for the preview yaml functionality. 
Revives `nonEmptyValueKeys` function but I do not use it in this PR. I think we should leave this function around though as getting the dot paths of an objects keys can come in handy and this function supports quoted paths as well which the alternatives I've found do not. 
Exposes applyHooks to the CruResource Yaml preview.
Also fixes  a small translation error I found while deving.
Removes yaml-js dependency we were not using. 
This does not expose the YAML editor on the Chart yet. These changes felt distinct enough to warrant its own PR.
> Seed Yaml Editor Content

- assets/translations/en-us.yaml
- chart/monitoring/grafana/index.vue
- chart/monitoring/index.vue
There were a couple fields int he ticket that were not available yet but I've exposed them and the object the require on create so the options are available now. These fields defaults will be in [with this pr](https://github.com/rancher/charts/pull/507/commits/28977f3869bd23fdfe7217fa53eb994dca0b36aa#diff-ed5b5b87cf149adc6a6408bf81993efdR1331-R1335).
Also moves the PVC Annotations and Finalizers input locations. 
rancher/dashboard#908
> Monitoring V2 Missing Options

- components/Tabbed/index.vue
- components/form/ServicePorts.vue
- edit/service.vue
Updated the path to value in Service create to use the correct value path for the Labels component.
rancher/dashboard#985
Remove headless check on target port input
rancher/dashboard#1028
Update Tabbed component to use the history replace state rather than push state by default with an option to revert back to old design if desired. This one is not necessarily related to services, the bug calls out services though so that why i've slipped it into this PR. 
rancher/dashboard#820
> Service Bugs

- edit/service.vue
Wrong value for Session Affinity on the service page. Changes from `ClusterIP` to `ClientIP`. Also exposes session affinity tab on node port services which is valid.
rancher/dashboard#804
> Services Session Affinity Bug

- components/form/Labels.vue
- config/labels-annotations.js
- mixins/create-edit-view.js
- plugins/steve/resource-instance.js
- utils/string.js
- Replace prefix and contain lists with regex lists
- Allow each resource to override the filtering by overriding labelsToIgnoreRegexes/annotationsToIgnoreRegexes
- Hide the labels and annotations both from the view and edit of Labels and DetailTop components
- Allow users to modify filtered labels and annotations by entering them manually
rancher/dashboard#556
rancher/dashboard#876
> Updating how we filter labels and annotations

- config/labels-annotations.js
The regex expected there to be a prefix i.e. field.cattle.io/description
and wouldn't ignore something like cattle.io/something
> Updating label/annotation ignore regex

- components/form/KeyValue.vue
- The KeyValue component was adding an initial empty row even when the mode was view so this is now only done when it's not view.
- I also noticed it's possible to have empty binary data so I fixed the download button to download an empty file and prevented it from navigating away from the page
rancher/dashboard#1068
I don't think this had anything to do with my previous length changes but I think this fix is reasonable. Let me know if you would like to see something different.
> Fixing the presentation of keyValue in view mode

- components/Tag.vue
- edit/namespace.vue
I updated the Tag spacing here because I noticed the vertical spacing wasn't
equal between the top and bottom while making this change.
https://github.com/rancher/dashboard/issues/843#issuecomment-677934988
> Updating the Namespace and Tag spacing

- assets/translations/en-us.yaml
- components/CruResource.vue
- components/CruResourceFooter.vue
- components/ResourceYaml.vue
- components/Tabbed/index.vue
- components/YamlEditor.vue
- edit/workload/index.vue
- pages/c/_cluster/apps/install.vue
- plugins/extend-router.js
- utils/create-yaml.js
This PR exposes the `Preview Yaml` functionality on the `apps/install` page. 
While I was working on adding the yaml preview functionality it became pretty clear that CruResource doesn't really work with the chart resource. The main reason being, CruResource expects a standard resource where its fields exist on a schema for ResourceYaml to work correctly. In this respect a chart doesn't fit the expectations of CruResource as resource values are derived from the chart values which have a schema of sorts but a schema not in the manner CruResource expects. I also found that the install page is not using the other major feature of CruResource, the subtype picker. Additionally the logic for parsing and saving a chart as yaml already exists in the install page. 
Rather than try to shoehorn the …
> Chart Install Yaml Refactor

- assets/styles/base/_helpers.scss
- assets/styles/themes/_dark.scss
- assets/styles/themes/_light.scss
- assets/translations/en-us.yaml
- components/ChartHeading.vue
- components/CountGauge.vue
- components/ResourceGauge.vue
- components/formatter/ListLink.vue
- config/product/logging.js
- config/table-headers.js
- config/types.js
- pages/c/_cluster/explorer/index.vue
- pages/c/_cluster/logging/index.vue
- Made a generic CountGauge
- Made ResourceGauge a specialization of CountGauge
- Swapped the cluster overview page to using the counts instead of requesting the resources
rancher/dashboard#1089
> Implementing logging overview

- assets/translations/en-us.yaml
- chart/monitoring/ClusterSelector.vue
Makes the best effort to auto select the users cluster but still allows them to select a type if they want. The accounts for `kubeadm` missing from the cluster provider types. Also handles the default cases better. Fixes a small bug in the RKE2 display as well.
> Monitoring - Auto Select Cluster Type

- assets/translations/en-us.yaml
- components/SortableTable/sorting.js
- components/form/NameNsDescription.vue
- components/formatter/Link.vue
- config/product/rancher-cis-benchmark.js
- detail/cis.cattle.io.clusterscan.vue
- edit/cis.cattle.io.clusterscan.vue
- edit/cis.cattle.io.clusterscanprofile.vue
- models/cis.cattle.io.clusterscan.js
- models/cis.cattle.io.clusterscanreport.js
- package.json
- yarn.lock
#1035 #1036 
- fixed clusterscanprofile skipTests in yaml view
- fixed clusterscanprofile selected in the clusterscan create page
- fixed clusterscan table formatters 
- 'download report' downloads a csv
- hid download report when there's no report generated
- hid various yaml options as they aren't useful here
The issue of state not updating without a page refresh doesn't appear specific to CIS.
> cis pr feedback

- assets/translations/en-us.yaml
- edit/service.vue
The check seems to have been conflated between ClusterIp & ClientIp
rancher/dashboard#1305
> Update session affinity checks to use ClientIp

- utils/create-yaml.js
I updated `create-yaml` to return "Error loading schema for <type>" so the whole page doesn't break if part of it fails to load:
This will allow the Statefulset forms to load correctly #921 but doesn't address whatever underlying issue there is with the schema.
> statefulset create-yaml error

- assets/translations/en-us.yaml
- edit/networking.k8s.io.ingress/Certificate.vue
- edit/networking.k8s.io.ingress/DefaultBackend.vue
- edit/networking.k8s.io.ingress/index.vue
- models/networking.k8s.io.ingress.js
- The namespace label was removed so it uses the default
- Added a 'None' option to the service target of the default backend
- Corrected the sizine of the certificate remove buttons so they don't iterfere with one another
rancher/dashboard#1299
rancher/dashboard#1300
I didn't add the 'None' option to the rule service targets because it's not a valid option.
> Resolved several ingress issues

- config/product/logging.js
rancher/dashboard#1345
I couldn't validate this. The redirect appeared to work with or without CHART_NAME. I was visiting https://localhost:8000/dashboard/c/local/logging and I was taken to the Logging overview page with and without.
> Add logging CHART_NAME

- assets/translations/en-us.yaml
- chart/monitoring/index.vue
- chart/monitoring/prometheus/index.vue
- config/product/monitoring.js
- config/types.js
- pages/c/_cluster/monitoring/index.vue
- utils/create-yaml.js
This PR contains fixes for a few different issues
Hides the external Monitoring links on overview page when the endpoints don't exist.
Slips a fix for create yaml where we do not want to process always add for array types.
Expose the Prometheus pods in the warning on Monitoring Config. This was a request from @aiyengar2.
Tooltips on each external link was a bit awkward. Dropped tooltips and moved abbreviated content inline with link.
@vincent99 sorry about the extra white space changes in the translations. For some reason VS code is ignoring the workspace setting to NOT trip white space for YAML only even though my user setting doesn't trim it as well. I can fix it if you want but I keep battling with it so I figured I might as well strip them all now.
> Monitoring/Alerting V2 Bugs

- chart/backup-restore-operator/S3.vue
https://github.com/rancher/dashboard/issues/1019#issuecomment-697749376
Fixed an issue where credentialsecretnamespace wasn't being set when the secret name matched the default value ('creds')
> fix backup/restore deployment s3 config

- config/product/monitoring.js
I thought `ifHaveType` could take arrays, I was obviously wrong. Updated the product reg to only looking for `PODMONITOR` CRD's as this is a unique type to Monitoring V2. Formatting.
> Monitoring Product Link Update

- components/BadgeState.vue
- components/ResourceList/Masthead.vue
- components/SortableTable/sorting.js
- components/formatter/BadgeStateFormatter.vue
- components/nav/Header.vue
- config/product/cis.js
- detail/cis.cattle.io.clusterscan.vue
- edit/catalog.cattle.io.repo.vue
- edit/configmap.vue
- edit/gatekeeper-constraint.vue
- edit/logging.banzaicloud.io.flow.vue
- edit/logging.banzaicloud.io.output/index.vue
- edit/namespace.vue
- edit/networking.k8s.io.ingress/index.vue
- edit/service.vue
- layouts/default.vue
- models/cis.cattle.io.clusterscan.js
- plugins/steve/mutations.js
- plugins/steve/resource-instance.js
- plugins/steve/subscribe.js
- Subscribe preserve namespace
- Flip weights
- Move type description to the top
- Wait for store updates to finish, ensure only one flush at a time
- Remove consecutive action dividers
- Only ask the server for relationships if we don't already have it
- Fleet states
- CIS bugs
- Fix default table sort
- Guard against product/cluster not being set
- Badge state standalone
- More reactive store updates
> Subscribe & CIS Bugs

- components/formatter/ListLink.vue
- config/table-headers.js
- pages/c/_cluster/logging/index.vue
Link formatter had the way options should be passed 
changed which broke the existing links. This changes
how we pass the options for outputs and flows.
I also fixed a missing 'row' warning.
rancher/dashboard#1422
> Fixing logging overview broken links

- components/form/ArrayList.vue
NamespaceList relied upon getting the updates when a default value was specified.
rancher/dashboard#1229
I spoke with @mantis-toboggan-md  about this several weeks ago but somehow never got this change in. The reason this was commented out was because
> It was causing an error in pod affinity; if a user adds a namespace field and doesn't use it, then the pod affinity spec doesn't pass validation because it has [""] listed for namespaces...ArrayList should now update only when there's a value beyond the default added/removed
I attempted to verify this change against PodAffinity but with or without this change I didn't see any namespaces getting added. If this reintroduces a problem I think that this should either be resolved with a custom @input in PodAffinity/MatchExpressions or within a …
> Allowing arraylist to update when there's a defaultAddValue

- config/product/gatekeeper.js
> Making the Gatekeeper Overview page only active when on the overview page

- assets/translations/en-us.yaml
- components/ResourceDetail/index.vue
- components/formatter/ServiceTargets.vue
- config/labels-annotations.js
Add a managed by warning when editing resources with matching labels
rancher/dashboard#992
Removes link functionality for service targets. There is a plan to revisit this post 2.5.0 so I only commented out the link logic for  now. I would think certain cases would call for it to still be present. 
rancher/dashboard#1513
> 2.5 Alpha Bugs

- models/node.js
Links still contain 'update' even if saving is forbidden. I noticed that the PUT resource method isn't present on the schema if the user can't save so I added a canSave() method to the resource-instance that queries for the PUT method and use that to enable/disable the cordon/uncordon actions.
rancher/dashboard#1411
> Hiding Node Cordon/Uncordon if rbac prevents saving

- chart/monitoring/grafana/index.vue
- chart/monitoring/prometheus/index.vue
Updated the check to show/hide storage class name input to computed property and wrapped in a div as it wasn't hiding properly otherwise.
Ive adjusted the markup a little for the storage configuration sections so they are all consistent with eachother. This doesn't change functionality, only layout.
| size | storage class (if shown) |
| access modes | volume mode (only prometheus) |
With storage classes:
Without:
> Monitoring Config Updates

- config/table-headers.js
- edit/logging-flow/index.vue
- models/logging.banzaicloud.io.flow.js
- pages/c/_cluster/logging/index.vue
Check to see if the resources are available before requesting them
and give appropriate defaults when not available
rancher/dashboard#1524
Notes:
While working on the flow page I noticed that there were a few problems with the overview page that I resolved.
- It was failing due to some resources not being available because of rbac
- We weren't using the new local/globalOutputRefs for the flows 
- We weren't showing the globalOutputRefs so I added a Cluster Output column. _We may want to add a separate column for the cluster providers too but I'll leave that for later_
- I decided to hide the cluster level table if the user didn't have access to cluster flows.
> Improving rbac of Logging overview and flow pages

- edit/workload/index.vue
Also updated the style to be more consistent with the existing Labels component.
rancher/dashboard#1394
> Adding pod annotations back to workloads

- edit/cis.cattle.io.clusterscan.vue
#1521 #1583 
Per the original issue #1036 there is a 'Default' option in the profile dropdown that selects a clusterscanprofile id based off the configmap `cis-operator-system/default-clusterscanprofiles` 
This looks confusing when that profile id is also available in the dropdown. I've updated the page to remove the 'Default' option and select appropriate the profile id by default instead.
> Clarify custerscan's default profile in dropdown

- assets/translations/en-us.yaml
- components/ResourceDetail/Masthead.vue
- components/ResourceDetail/index.vue
- edit/service.vue
Weirdness with the old PR made me close that but for ref [here it is](https://github.com/rancher/dashboard/pull/1649)
Some resources like Service and Secret have a type (`service`) but also a Subtype (`ClusterIP`). This exposes the mechanism to set that from the resource.
@vincent99 @lvuch Would it make sense to change create to match edit now?
rancher/dashboard#1073
> Add resource subtype to masthead v2

- assets/styles/global/_cards.scss
- assets/translations/en-us.yaml
- chart/istio.vue
- pages/c/_cluster/istio/index.vue
#1170 #1646 
* removed monitoring warning from the Istio install page
* added note about monitoring and link to rancher monitoring to the Istio overview page:
> Remove Istio monitoring warning

- components/form/LabeledSelect.vue
- components/form/ServicePorts.vue
- edit/resources.cattle.io.restore.vue
#1647 #1303 #1442 
* fixed bug where `LabeledSelect` displayed the placeholder and option label if option value is `false`
* removed warning about encryption config secrets from restore view page
* converted serviceports to use grid
> convert serviceport to grid from table

- components/PromptRemove.vue
Change delete modal resource link from non-nuxt link out of dashboard to the api ui to a nuxt-link that goes to the resource detail page.
rancher/dashboard#1405
> Delete Modal Resource Link 

- assets/styles/global/_tooltip.scss
- assets/translations/en-us.yaml
- chart/monitoring/prometheus/index.vue
Exposes the `ignoreNamespaceSelectors` field to the prometheus config.
Additionally this sets max-width on our tooltips. I find long tooltips on a wide screen hard to read and super obtrusive. 50vw sets a nice middle ground. This can be backed out though if we'd like to discuss it further. 
rancher/dashboard#1129
> [2.5.2] Monitoring ignoreNamespaceSelectors

- assets/translations/en-us.yaml
- edit/networking.k8s.io.ingress/DefaultBackend.vue
- edit/networking.k8s.io.ingress/Rule.vue
- edit/networking.k8s.io.ingress/RulePath.vue
- edit/networking.k8s.io.ingress/Rules.vue
- models/networking.k8s.io.ingress.js
Creating an ingress in k8s 1.19 was failing because we didn't
have pathType. This adds the new option as an InputWithSelect.
Because this field is present in 1.18 I'm showing this field for
all implementations.
I also fixed a small issue under DefaultBackend where
selecing a TargetService was removing the port label. The
label field was just missing from the LabeledSelect component.
rancher/dashboard#1634
https://github.com/rancher/dashboard/issues/1301#issuecomment-705052366
> Adding pathType to ingress rules

- edit/gatekeeper-constraint.vue
- models/gatekeeper-constraint.js
We weren't creating good defaults for selectors and enforcementAction.
I also noticed that the parameters yaml editor wasn't showing the value until clicked so I resolved that as well.
rancher/dashboard#1194
> Fixing a constraint editing crash

- assets/translations/en-us.yaml
- components/Tabbed/index.vue
- components/form/RadioButton.vue
- edit/monitoring.coreos.com.prometheusrule/AlertingRule.vue
- edit/monitoring.coreos.com.prometheusrule/GroupRules.vue
- edit/monitoring.coreos.com.prometheusrule/RecordingRule.vue
- edit/monitoring.coreos.com.prometheusrule/index.vue
- models/monitoring.coreos.com.prometheusrule.js
- utils/custom-validators.js
- utils/validators/prometheusrule.js
Adds the custom UI for the Prometheus Rules. 
I left out the custom redirect to yaml requirement at the bottom of the ticket though. I am having trouble making the redirect happen. In every lifecycle hook i tried I first had to let the route fully load then replace to the yaml view for it to work. This looks ugly. But as I was attempting to get this working I started to find it really odd that we'd redirect a user to the yaml view with out notifying them why. As this would only happen on edit and from my understanding of the requirements, I don't think it would hurt to allow the user to view the form in this case.
@vincent99 I wasn't quite sure if the add group button was quite what you wanted (see pic below)? Let me know if we want to implement a different design. 
rancher/dashboard#811
> [2.5.2] Prometheus Rules Custom UI

- assets/translations/en-us.yaml
- chart/monitoring/prometheus/index.vue
- components/ResourceDetail/Masthead.vue
- components/form/RadioButton.vue
- mixins/create-edit-view.js
Updates the `ignoreNamespaceSelector` radio group on install chart page for Monitoring v2. 
rancher/dashboard#1129
Also added a fix for the radio group "radio" span. I noticed certain screens the size would squish up causing lopsided radios. 
Also fixed a small bug in masthead that denise found. 
Also fixed the console error being thrown by Vue in dev mode for the moreDetails prop, changed the mixin that declared it as a data prop to make it a vue prop on the mixin.
> Update Namespace Selector Defaults

- components/form/ServicePorts.vue
- edit/service.vue
Added logic to cast the target port on a service port resource to a int if the string contains all numeric values else it leaves the value as a string. 
also changed the min max on nodePorts as the range was not valid before
rancher/dashboard#1694
> Service Port Validation Fixes

- assets/translations/en-us.yaml
- config/product/monitoring.js
- config/types.js
- edit/monitoring.coreos.com.route.vue
- list/monitoring.coreos.com.route.vue
- models/monitoring.coreos.com.receiver.js
- models/monitoring.coreos.com.route.js
- plugins/steve/resource-instance.js
- store/type-map.js
- utils/alertmanagerconfig.js
- utils/custom-validators.js
- utils/validators/monitoring-route.js
- Extracted code that could be shared between route and receiver into an alertmanagerconfig util
- Added some more support code to allow users to dynamically add/remove uncreatableTypes
rancher/dashboard#1239
Note:
- This doesn't match the mock. I asked for some feedback here https://github.com/rancher/dashboard/issues/1239#issuecomment-716742191 but didn't hear anything so I went ahead with this. Let me know if you want it to be changed.
> Adding the route alertmanager route type

- components/ActionMenu.vue
When the user clicks on the menu and leaves the current route, the menu will not disappear
> fix: actionMenu doesn't disappear

- edit/gatekeeper-constraint.vue
- models/gatekeeper-constraint.js
- Removed applyDefaults in favor of using the existing empty spec. I don't think the intended purpose of applyDefaults is really to hydrate the object with empty structures just to support the components. I think it's really intended to provide the default values we want to display when creating a new resource.
- Fixed an issues with parameters not resizing due to a misplaced &.
rancher/dashboard#1194
> Changing how we set empty defaults

- assets/translations/en-us.yaml
- models/workload.js
- plugins/steve/resource-instance.js
- utils/custom-validators.js
- utils/validators/container-images.js
- utils/validators/cron-schedule.js
- utils/validators/index.js
To start addressing #1286 I've added some `customValidationRules` for workloads. I'm not how practical it is to validate all workload types with the granularity implied in the issue this way; I think some more programatic (schema-based) validation would be worth implementing here, but it's not something I can get done today (before my pto begins).
The other aspect of this work that's in-progress is how/when we want to show validation errors. Right now they appear instead of sending a bad create/save request, but I think there was some conversation around showing which fields are a problem more clearly and it's still unclear what the plan is there.
> workload validation

- chart/monitoring/grafana/index.vue
https://github.com/rancher/dashboard/issues/1689#issuecomment-718936362
Updated `Grafana` component to determine if persistent storage is enabled and which variety rather than always initializing as 'disabled'
> repopulate grafana persistence correctly on edit

- utils/alertmanagerconfig.js
The utility was broken in prod due to the function names changing. Instead of trying to differentiate the dispatch method being used we just set the { root:true } config so we can always use the 'cluster/action'.
https://github.com/rancher/dashboard/issues/1238#issuecomment-719730626
> Switch alertmanagerconfig to use dispatch with { root:true }

- assets/translations/en-us.yaml
- chart/monitoring/index.vue
- chart/monitoring/prometheus/index.vue
- edit/monitoring.coreos.com.prometheusrule/AlertingRule.vue
- edit/monitoring.coreos.com.prometheusrule/GroupRules.vue
- edit/monitoring.coreos.com.prometheusrule/index.vue
The PR addresses a few Monitoring V2 bugs:
Changes default severity label to `none`
On save of a Prometheus rule, the group override interval will be converted to string.
Hides the side tabs add/remove buttons on `view` mode.
Additionally this adds one fix for Prometheus rules: 
When installing the chart, if the user has not input storage selectors for the Prometheus storage option, we will drop the values from the data.
rancher/dashboard#811
rancher/dashboard#1757
> Monitoring Fixes

- chart/monitoring/prometheus/index.vue
- edit/monitoring.coreos.com.prometheusrule/index.vue
Set persistence enabled on upgrade/edit if set on the chart so the options show up correctly in the form.
Also make sure the selector warning shows the escaped translation.
rancher/dashboard#1764
rancher/dashboard#1757
Additionally I want to slip in a small change for Prometheus rules. Ensure that we append the unit to the string before we send. 
rancher/dashboard#811
> Repopulate Prometheus Storage Spec on Edit

- models/templates.gatekeeper.sh.constrainttemplate.js
The route is no longer correct and redirects the user to a 404.
rancher/dashboard#1778
> Removing the doneOverride from constraint templates

- components/CruResource.vue
- edit/monitoring.coreos.com.receiver/index.vue
- edit/monitoring.coreos.com.receiver/types/email.vue
- edit/monitoring.coreos.com.receiver/types/webhook.vue
- edit/monitoring.coreos.com.route.vue
- models/monitoring.coreos.com.receiver.js
- models/monitoring.coreos.com.route.js
- utils/alertmanagerconfig.js
Change how we handle nameless routes and how we save yaml
- We just filtered out nameless routes which caused problems with default routes and manually created routes. This now gives a default name of `route-${i}` which if saved will add the name to the route.
- Verified that editing and deleting still works when order has changed and new routes are present.
- Made the yamlSaveOverride consistent with receivers since it wasn't working when going to edit as yaml from the create page.
Resolving receiver issues    
- Edit as yaml on a created resource wasn't calling the yamlSaveOverride
- Erroneously set required_tls default for webhooks
- camel cased a field that wasn't supposed to be
rancher/dsahboard#1239
rancher/dashboard#1238
> Receiver and Route fixes

- assets/translations/en-us.yaml
- models/workload.js
- utils/custom-validators.js
- utils/validators/pod-affinity.js
#1286 - adds some validation to pod affinity:
* `topologyKey` must be defined and a valid label
* matchExpression `operator` must be one of In, NotIn, Exists, DoesNotExist
* `weight` must be integer between 1-100
* `matchExpression.values` must be a non-empty array if `operator` is In or NotIn
* `matchExpression.values` must be an empty array if `operator` is Exists or DoesNotExist
> validate pod affinity/antiafiinity

- assets/translations/en-us.yaml
- components/formatter/IngressFullPath.vue
- components/formatter/IngressTarget.vue
- components/formatter/Link.vue
- components/formatter/ListLink.vue
- components/formatter/ListLinkDetail.vue
- config/product/cis.js
- config/table-headers.js
- edit/networking.k8s.io.ingress/Certificate.vue
- edit/networking.k8s.io.ingress/Rule.vue
- edit/networking.k8s.io.ingress/RulePath.vue
- edit/networking.k8s.io.ingress/Rules.vue
- edit/networking.k8s.io.ingress/index.vue
- models/networking.k8s.io.ingress.js
- Move the default backend tab to be after rule
- Validation of the "target service" should be a tool tip and color
- Putting a "/" de-focuses
- Combine the rule and certs into one table instead of multiple boxes, need a name
rancher/dashboard#1755
> Improving the edit and view pages of ingress

- components/form/ValueFromResource.vue
- edit/workload/storage/awsElasticBlockStore.vue
- edit/workload/storage/azureDisk.vue
- edit/workload/storage/azureFile.vue
- edit/workload/storage/gcePersistentDisk.vue
- edit/workload/storage/vsphereVolume.vue
#1404 #1687 
* added missing `fsType` field to some workload volume types
* changed environment variable 'key' (`valueFrom.resourceFieldRef.resource`) to dropdown
- there are more changes to be to this area, tracked here: #1769
> Bugfix workload storage

- pages/c/_cluster/istio/index.vue
#1820 - The Kiali description box on the Istio overview page has a click event listener on the whole description and an `<a>` tag; this prevents both from firing when the link is clicked.
> prevent 2 kiali tabs opening

- components/form/ArrayListGrouped.vue
Increased the specificity of the scss selectors so it wouldn't style sublists.
> Making the style of the ArrayListGroup more targeted

- assets/translations/en-us.yaml
- components/form/ArrayList.vue
- components/form/Command.vue
- components/form/EnvVars.vue
- components/form/ValueFromResource.vue
- edit/workload/index.vue
#1808 #1813 
I don't see an issue for it, but in addition to the above bugs, this PR also gets rid of the add/add from resource dual list that was present previously so the order of variables can be set as desired now.
> Container environment variables

- components/PromptRemove.vue
`PromptRemove` contents disappeared when it switched from `Card` to `InfoBox` because InfoBox doesn't have the same named slots.
before/after:
> fix PromptRemove slot names

- components/form/Command.vue
- components/form/ShellInput.vue
- edit/workload/Job.vue
- edit/workload/index.vue
#1816 - `terminationGracePeriodSeconds` field was missing from cronjob/job workloads, which have different scaling/upgrading tab content. 
#1841 - fixed change detection in `Command` component
#1880 - updated workload creation to always set container name to workload name on initial create
#1832 - updated `ShellInput` component so that it doesn't split the input string on spaces contained in quotes. eg previously we had:
`-c "sleep 3600" -> ['-c', '"sleep', '3600"']`
Now we have:
`-c "sleep 3600" -> ['-c', 'sleep 3600']`
> various workload bug fixes

- assets/styles/global/_form.scss
While testing rancher/dashboard#1836 I noticed the `<InputSelect>'s` `<input>` wasn't  the appropriate height.
> Making the rest of input elements 100% height to match Labeled/Select

- components/Card.vue
- components/PromptRemove.vue
- edit/monitoring.coreos.com.receiver/index.vue
- list/monitoring.coreos.com.receiver.vue
- models/monitoring.coreos.com.receiver.js
- Updated some of the styling on the PromprRemove with help of Lauren.
- Added spacing between sections
- Removed the warning styling
- Added spacing between the action buttons
- Aligned the action buttons to the right
- Fixed a problem where preventDelete was never reset so if it got set to true no other resources could be deleted.
rancher/dashboard#1707
> Preventing receiver deletion when a route depends on the receiver

- assets/styles/global/_select.scss
- assets/styles/vendor/vue-select.scss
- components/form/LabeledSelect.vue
- edit/constraints.gatekeeper.sh.constraint/NamespaceList.vue
- edit/constraints.gatekeeper.sh.constraint/Scope.vue
- edit/constraints.gatekeeper.sh.constraint/index.vue
- Switched the LabeledSelects to use the tooltip rather than having a separate header and `<v-tooltip>` now that it's supported.
- Fixed an issue with `<Select>` not having a min-height.
- Fixed an issue where `<LabeledSelect>` hover tooltips caused the menu to go behind the :multiple selection of other LabeledSelect
rancher/dashboard#1892
> Only disable namespace lists for cluster scope in constraints

- components/ContainerResourceLimit.vue
- edit/namespace.vue
Need to fire the hooks before we switch from form to yaml editor on namespaces.
Move viewMode to correct object so Vue stops complaining about a non-reactive property (i think its just a dev build complaint but still, its annoying).
> Namespace Yaml Editor Bug

- assets/translations/en-us.yaml
- chart/logging/index.vue
> Allowing users to configure additionalLoggingSources on the logging chart

- assets/translations/en-us.yaml
- edit/logging.banzaicloud.io.output/providers/splunkHec.vue
rancher/dashboard#1703
The view mode doesn't work for any of the providers anymore. I'll be addressing that as part of the Logging Polishing issue.
> Adding the index and source fields to the splunk output provider

- components/ResourceDetail/index.vue
#1938 - move `applyDefaults` to run after value is set in fetch, not data
> call applyDefaults in ResourceDetail

- detail/workload/index.vue
- models/workload.js
#1940 
#1922 - this was a problem with how workloads are being made in the UI (the `workload.user.cattle.io/workloadselector` label used to find pods wasn't specific enough) so it wont be applied retroactively
> workload detail fixes

- components/PromptRemove.vue
#1886 - I added `AsyncButton` to the deletion prompt so there's a visual indication that something is happening when delete/uninstalls take time:
> add asyncButton to promptRemove

- assets/translations/en-us.yaml
- detail/secret.vue
- edit/secret.vue
#1891 - @lvuch I'm not sure what exact styling is desired for the first checkbox, the secret subtype in header; I implemented it the same way as service subtype headers.
> secrets tab headers

- assets/translations/en-us.yaml
- components/formatter/IconText.vue
- config/product/cis.js
- detail/cis.cattle.io.clusterscan.vue
- edit/cis.cattle.io.clusterscan.vue
- edit/cis.cattle.io.clusterscanbenchmark.vue
- list/cis.cattle.io.clusterscan.vue
- models/cis.cattle.io.clusterscan.js
- models/cis.cattle.io.clusterscanreport.js
#1037 #1828 - added radio groups for enabling scheduling and alerting in a scan
#1173 - ui for custom benchmark form + list
Fixes in this PR: #1924 #1901 #1883 #1895
> cis benchmark form

- components/ResourceDetail/index.vue
#1988 - call `cleanForNew` in clone/stage mode regardless of `as` value
> ResourceDetail clone fix

- utils/alertmanagerconfig.js
When alertManager.spec.configSecret was present it didn't include the namespace which caused subsequent lookups of the secret to fail. This corrects the id by prefixing the namespace to it.
rancher/dashboard#1845
rancher/dashboard#1805
> Prefixing the alertmanager secretId with the appropriate namespace

- assets/translations/en-us.yaml
- components/ResourceDetail/index.vue
- detail/cis.cattle.io.clusterscan.vue
- edit/cis.cattle.io.clusterscan.vue
- models/cis.cattle.io.clusterscan.js
- models/cis.cattle.io.clusterscanbenchmark.js
#1995 - fix order of reports in scheduled scan detail page; use scan name and timestamp to generate report .csv file names
#2003 #1996 #1997  - Fix scan create/edit form repopulating
#2005 Add warning message to benchmark deletion prompt
#1998 - give some indication that the report resource couldn't be found
> scheduled scan bugs

- components/formatter/ServiceTargets.vue
- config/labels-annotations.js
Additionally I have left the previous logic in the cases where a service does not have the public endpoints annotation to not break the previous functionality.
rancher/dashboard#1471
> Add endpoints links to Service Targets formatter

- components/form/ArrayList.vue
- components/form/ArrayListGrouped.vue
- edit/networking.k8s.io.ingress/Rule.vue
- edit/networking.k8s.io.ingress/RulePath.vue
- edit/networking.k8s.io.ingress/Rules.vue
- models/networking.k8s.io.ingress.js
- showPathType/useNestedBackendField was getting called frequently so I cached/memoized the response since it's a somewhat expensive call.
- Made it so when adding a path or adding a rule it focuses the appropriate input.
rancher/dashboard#1980
Notes:
- I debated whether or not to memoize the pathExistsInSchema getter but I was concerned with the getter making a stateful change and how it would interact with ssr. If you'd prefer me to memoize there do you have any thoughts on my concern?
- The issue specifically calls out add path as the event we want to focus on but I figured we'd want the same for add rule so I added it there as well. If we don't want it there let me know and I'll remove it.
> Fixed an ingress performance issue and added focus UX

- components/form/KeyValue.vue
- components/form/LabeledTooltip.vue
- components/form/TextAreaAutoGrow.vue
- edit/monitoring.coreos.com.prometheusrule/GroupRules.vue
- edit/workload/Job.vue
@vincent99 moved tooltips to right of inputs, ideally they should be right of the labels but so far that hasn't been able to work without significantly affecting other areas
https://github.com/rancher/dashboard/issues/1724
> input selects tooltips height and placements

- assets/styles/global/_labeled-input.scss
- assets/translations/en-us.yaml
- components/form/LabeledInput.vue
- config/product/cis.js
- detail/cis.cattle.io.clusterscan.vue
- edit/cis.cattle.io.clusterscan.vue
- edit/workload/index.vue
- list/cis.cattle.io.clusterscan.vue
- models/cis.cattle.io.clusterscan.js
- models/cis.cattle.io.clusterscanreport.js
Added a 'cron' type input with human-readable label:
#1995 - updated report names to be more consistent between ui and file names
#2054, #2052 - per conversation with @sowmyav27, the scheduling/alerting fields and anything related to 'warn' test results shouldn't be available if the installed version of cis doesn't support scheduling. I added some of this functionality earlier this week but it was dependent on access to the cis app resource, which the cis-admin role doesn't have. This updated version should work for all users with permission to view scans.
Other fixes: #2057 #2042 #2036
> cis fixes, cron input type

- pages/c/_cluster/apps/charts.vue
I renamed the label constant for catalog os from OS to SUPPORTED_OS and missed the implementation.
rancher/dashboard#1952
> Fix renamed variable reference Windows Apps

- edit/workload/index.vue
- models/workload.js
#2041 
```
if (!spec.replicas) {
spec.replicas = 1;
}
```
changed the above  logic to account for replicas=0, and moved it into `applyDefaults` because it shoulda been there already.
> fix replica display in config

- assets/translations/en-us.yaml
- components/form/LabeledSelect.vue
- models/catalog.cattle.io.app.js
- pages/c/_cluster/apps/charts.vue
- pages/c/_cluster/apps/install.vue
My previous change assumed that the new annotation was on the chart itself but the annotation exists on a charts different versions. I updated the logic to add the following filtering:
Apps List Page: 
- Chart will only be filtered from the view if all versions of the chart have the `catalog.cattle.io/os` annotation set and all versions are either linux or windows.
- Selecting Charts will take the user to the highest version chart that either lacks the `catalog.cattle.io/os` annotation (assumed to work on any os) or has the `catalog.cattle.io/os` annotation set to the correct os provider for the cluster.
App Install/Upgrade Page:
- Version list will list all versions of a chart, but if a particular version of the chart is incompatible with the current clusters os  the user will not be …
> Chart Filtering Cluster OS Types

- assets/translations/en-us.yaml
- components/formatter/ScanResult.vue
- edit/cis.cattle.io.clusterscan.vue
- models/cis.cattle.io.clusterscan.js
#2088 #2092 
* fall back to cis-1.5 or cis-1.6 scan profiles if the default profile specified in the configmap isn't valid
* Warn that alerting needs to be configured on CIS install/upgrade as well as in the monitoring/alerting app
> default scan profile fallback

- assets/styles/global/_select.scss
- assets/styles/themes/_dark.scss
- components/form/Checkbox.vue
In light mode disabled options we're not visible because the text was too light. Additionally no background was set on the dd so the hover background of the select input was showing through making it even worse. 
In dark mode dropdowns didn't have a disabled text var so the text was white and not really distinguishable from enabled options until hover. 
rancher/dashboard#2101
Also threw in a small change for the checkbox tooltip property. Since this property is essentially just passed through to v-select the property signature needed to be able to accept objects which v-select accepts. This was manifesting as a prop type check error on the Monitoring config page for aggregate roles.
> Dropdown Dark/Light Theme Bug 

- components/ResourceYaml.vue
- plugins/steve/resource-instance.js
#2100 
Two parts to this bug, neither CIS specific: 
1) 'view config' action menu item was calling 'goToEdit' and therefore showing cancel/yaml/save buttons to users without permission to edit the resource 
2) the edit-as-yaml save button wasn't waiting for & showing errors
> yaml save button error display

- components/form/ServicePorts.vue
When adding a new service port row we'll now focus the port name field instead of the port input.
Also change the way we focus when the user has removed all rows then adds a new row. 
rancher/dashboard#1732
> Service Ports Focus in

- utils/create-yaml.js
This particular property contains a cyclical reference in the allOf property which is of the type io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps and has its own allOf property of the same type. Adding this prop to the never add list felt more appropriate than adding an arbitrary depth check.
rancher/dashboard#1843
> Add new prop to createYaml NEVER_ADD

- edit/cis.cattle.io.clusterscan.vue
Related to this PR https://github.com/rancher/cis-operator/pull/85
Updates the UI to read default profile values in the format `"<version range>: <profile name> \n <version range>: <profile name>"` if present.
> rke default scan profile update

- models/catalog.cattle.io.clusterrepo.js
- pages/c/_cluster/apps/install.vue
- store/catalog.js
- Show hidden charts which match the name of the expected repo
- Add support for `hidden` and `deprecated` query params on edit
> Group charts by repo in install

- components/ButtonDropdown.vue
- components/form/LabeledSelect.vue
- components/form/Select.vue
- components/nav/ClusterSwitcher.vue
- components/nav/NamespaceFilter.vue
- components/nav/WorkspaceSwitcher.vue
- mixins/labeled-form-element.js
- mixins/vue-select-overrides.js
- package.json
- yarn.lock
Updates the mapped keys handlers to deal with focus lost issues. 
Adds fixes to prevent the dropdown from growing the page height if dropdown would overflow.
Adds fixes for the dropdown width being smaller than the select. Now dropdown will be at min the width of the select and if content in dropdown is larger the dropdown will grow to fit the content.
Updates v-select dep to latest version.
Updates `can-i-use` to latest version. 
Tracked Issues:
https://github.com/rancher/dashboard/issues/2008
https://github.com/rancher/dashboard/issues/2009
https://github.com/rancher/dashboard/issues/2031
> Dropdown Bugs

- components/nav/WindowManager/index.vue
> always show close 'x' in logs tabs

- assets/translations/en-us.yaml
- components/FleetSummary.vue
- detail/namespace.vue
- plugins/steve/resource-instance.js
Adds the Namespace detail page.
Updates Fleetsummary component logic to use the real state colors from the resource instance.
Adds a new `getStatesByType` which returns a map of the 4 + 1 (unknown) basic types to facilitate looking up a random statename from the collection of states we keep. 
rancher/dashboard#1784
rancher/dashboard#1870
> Namespace polish and details page

- assets/translations/en-us.yaml
- edit/service.vue
Adds a banner message similar to Fleet Cluster Groups that shows the live pod count for the selectors section of service create.
Adds required to External Name input.
rancher/dashboard#717
rancher/dashboard#2179
> Service Create Selectors - Show Target Pods Real Time

- components/Questions/index.vue
#2107 - updated the tab order so 'other settings' is last, and tabs that appear conditionally show up below the current tab (images settings and csi driver settings)
> update tab order

- components/form/RadioGroup.vue
When using <RadioGroup row>, we need the CSS to match on `.radio-group.row` (that is, one element with both classes) rather than matching on `.radio-group .row` (an element that is the descendant of another).
Found this while attempting to reuse the component.  I didn't see relevant tests; if there are any, please point me at them and I'll happily adjust.
> components/form/RadioGroup.vue: fix row mode

- assets/styles/base/_color.scss
```
error  in ./src/App.vue?vue&type=style&index=0&lang=scss&
Syntax Error: SassError: (default-text: #3D98D3, hover-text: #badaef, active-text: #1b5276, default: transparent, hover-bg: transparent, active-bg: transparent) isn't a valid CSS value.
╷
26 │     --#{$name}-border:      #{$border};
│                               ^^^^^^^
╵
src/assets/styles/base/_color.scss 26:31   color-variables()
src/assets/styles/themes/_light.scss 40:3  @import
src/assets/styles/app.scss 16:9            @import
src/App.vue 30:9                           root stylesheet
@ ./node_modules/vue-style-loader??ref--8-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--8-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-1-2!./node_modules/sass-load …
```
> Fix this error at startup:

- components/ResourceList/Masthead.vue
- components/ResourceList/index.vue
- config/product/auth.js
- list/management.cattle.io.user.vue
- Allow custom lists to provide their own masthead via configeType showListMasthead
- Add additional buttons to list Masthead
- Prove out with users (to be populated later). This should also replace the extraAction change (couldn't do this, had trouble accessing the cluster user case)
> Add custom buttons to lists

- assets/translations/en-us.yaml
- components/PromptChangePassword.vue
- components/form/ChangePassword.vue
- components/form/LabeledInput.vue
- components/form/Password.vue
- components/nav/Header.vue
- config/types.js
- pages/account/index.vue
- pages/prefs.vue
- plugins/steve/index.js
- Add a new Accounts and API Keys page accessible via user avatar drop down
- Add new change password feature to Accounts page
- This contains a placeholder for the API Keys table which will be populated via rancher/dashboard#2214
> Add new Accounts & API Keys Page containing new change password feature

- components/nav/Header.vue
This PR adds a disabled state for buttons in the Header bar - I was seeing this with the import yaml button - this won't be the case if your backend is up to date, but adding this style anyway in case we encounter the need to disable buttons in the header in the future.
Before:
After:
> Add disabled state for buttons in the Header

- components/form/ChangePassword.vue
- This is a fix for a very minor visual bug (checkbox position is too high)
- Think this came in after the styles update
- I'll be updated this area in the create/edit user pr, will be sure to make it less brittle
> Add a temporary fix for positioning issue in Change Password prompt

- detail/workload/index.vue
- models/workload.js
#2283 
* filter workload pod method
* use SortableTable instead of ResourceTable so the results are not filtered by the top-level namespace dropdown
> namespace workload pods method

- store/type-map.js
- Made it so we add spoofed types as a part of the virtual type loop.
Previously we were adding the types to all modes without appropriate filtering
- Made it so spoofed types can have the nav icons
- There was also a problem where the virtual/spoofed types were expected to have a name so I copied the type over to the name of spoofed types.
> Making several fixes to spoofed types

- edit/secret.vue
The edit/create secret page was blowing up due to the recent loss of `DISPLAY_TYPES` from the secret model. This PR updates the page to use the `secret.types` translations instead.
> fix edit secret type display

- detail/cis.cattle.io.clusterscan.vue
https://github.com/rancher/dashboard/issues/2207#issuecomment-773494686
- per slack convo with Rajashree, the remediation field should only be shown if scan results are fail or warn
> only show remediation for fail/warn cis scan results

- assets/translations/en-us.yaml
- components/GlobalRoleBindings.vue
- components/PromptRemove.vue
- components/auth/SelectPrincipal.vue
- components/form/Checkbox.vue
- components/formatter/Principal.vue
- components/formatter/PrincipalGroupBindings.vue
- config/product/auth.js
- config/table-headers.js
- config/types.js
- edit/group.principal.vue
- list/group.principal.vue
- models/group.principal.js
- models/management.cattle.io.globalrolebinding.js
- pages/c/_cluster/auth/group.principal/assign-edit.vue
- plugins/steve/actions.js
- Add groups page with table to the auth product
- Allow user to assign roles to groups previously without roles or edit groups with existing roles
Comments
- I haven't added any special ux for the case where there's no auth provider and therefore no groups
- ./components/GlobalRoleBindings.vue will be updated when the same  component is used for assign global roles to a user principal
- ~~./components/GlobalRoleBindings.vue ln 139 Couldn't create a binding without the generateName metadata property. Have given this a `ui-` prefix. Is this correct?~~ updated to `grb-`
- In order to determine which global roles are bound to each principal (so we can filter by principals that have them).. we go out and fetch ALL role bindings. Is this too costly?
- On the groups page the 'refresh' button is …
> Add Users & Auth / Groups page, assign Global Roles to Groups

- edit/auth/ldap/config.vue
Addresses #2251 
This is a simple fix for the issue above. When the user changes the TLS checkbox, the port field will be updated with the correct default depending on the TLS setting. It will ONLY do this if the user has not edited the contents of the port field.
> LDAP Auth: Change the port number when the user changes the TLS setting

- assets/translations/en-us.yaml
- chart/logging/index.vue
This is to support a backend interface change.
rancher/dashboard#2199
switching from:
```
additionalLoggingSources:
k3s:
fluentbit:
mountPath: path
```
To:
```
global:
dockerRootDirectory: path
```
> Moving the fluentbit mountpath to global.dockerRootDirectory

- scripts/build-embedded
Only generate one top-level index.html file for the embedded build, so that the API doesn't find nested ones and try to serve that as the index for master builds.
> Strip nested static index.html files out of embedded builds

- components/form/LabeledSelect.vue
- components/form/PodAffinity.vue
- The first issue was caused by the introductions of ArrayListGrouped and not updating all references appropriately
- The other was caused by LabeledSelect calling the @input handler twice for every selection. The handler was toggling which caused the value to always reset. It looks like the reason LabeledSelect was calling the handler twice was because of having both v-bind="$attrs" and @input="...". So i removed @input and verified that LabeledSelect still works for both v-model and value/@input.
rancher/dashboard#2211
> Fixing two issues that showed up in pod scheduling

- detail/service.vue
This is a trivial fix for the issue #2201 
Turns on the table header and leaves the labels as their defaults.
> Fix for service detail selector table not having table header

- components/formatter/ServiceType.vue
See #2201 
This PR is a trivial fix - the code was looking up 'translationLabel' when the field is simply 'label' - se DEFAULT_SERVICE_TYPES in service.js model.
> Fix for headless services showing as type ClusterIP in the Service list

- nuxt.config.js
- plugins/replaceall.js
#2326 
This PR fixes the issue creating certain logging resource types - this code uses String.replaceAll, which was only added to Chrome in version 85 (Aug 2020).
I've brought in a polyfill for String.replaceAll to use for older browsers which don't support this natively.
> Add polyfill for String.replaceAll

- components/nav/Footer.vue
This PR improves the presentation of the locale selector menu, making it more consistent with the UI, specifically:
- Add pointer cursor when hovering over the locale in the right of the footer
- Remove the arrow in the dropdown (which was the wrong colour)
- Apply a hover state to menu items that is consistent with other menus
- Close the menu when an option is selected
> Improve presentation of locale menu

- assets/styles/vendor/vue-select.scss
- components/form/Select.vue
- components/nav/ProductSwitcher.vue
This PR tweaks the product menu:
- Removes the drop-shadow which currently causes a misaligned grey border when the dropdown is open:
- Updates the behaviour, so that clicking on the select, correctly toggles the display of the dropdown - currently when the dropdown is visible, clicking on the select again, causes the menu to hide then show again - this PR changes that so it will hide when clicked subsequently.
> Improve product menu drop down behaviour

- components/ResourceDetail/index.vue
- models/constraints.gatekeeper.sh.constraint.js
- plugins/steve/resource-instance.js
Constraints were failing to clone because cleanForNew didn't remove `this.constraint` which casued the save method to attempt to save the existing constraint instead of creating a new constraint.
This enables models to be able to create their own cleanForNew method to remove custom props if necessary.
rancher/dashboard#2341
> Enable models to override their cleanForNew method

- detail/node.vue
#2350 
It looks like a node with no images (e.g. the local node on fresh install) causes the node detail page not to load - we try and map an undefined - this PR is a trivial fix for this case.
> Fix for bug where node with no images shows error page

- components/formatter/CopyToClipboard.vue
- models/node.js
#2352 
We have a formatter 'CopyToClipboardText' that does not exist, leading to the console error message and also to the missing internal and external IPs from the node detail view.
This PR adds a formatter that wraps the CopyToClipboardText component and fixes this issue.
> Fix for missing Internal and External IPs on node detail page

- assets/translations/en-us.yaml
- components/auth/AuthBanner.vue
- edit/auth/azuread.vue
- edit/auth/github.vue
- edit/auth/googleoauth.vue
- edit/auth/ldap/index.vue
- edit/auth/saml.vue
- Make a common component used by all auth providers
- Component contains
- enabled/disabled banner
- settings which are now aligned in a table
Addresses #2274
~~Blocked on #2309~~
Notes for QA
- This effects all five types of provider (Github, SAML based, Google Auth, LDAP based and AzureAD)
> Improve display of Auth Provider settings

- edit/cis.cattle.io.clusterscan.vue
#2348 
This PR is a simple fix for this issue - the Kubernetes version for the cluster was not using the correct property name.
I've validated using a local RKE cluster that this is an issue and that this PR fixes it.
> Fix issue where default scan profile not set for rke cluster

- assets/translations/en-us.yaml
- edit/autoscaling.horizontalpodautoscaler/index.vue
- edit/autoscaling.horizontalpodautoscaler/resource-metric.vue
The scaleTargetRef object on the HPA was incorrect. I didn't understand that the `apiVersion` is the actual api version of the referent object and that `kind` had to match the referent kind. The Ember UI only sets it statically I believe and this goofed me up.  
Also changed the default value for resource.name in `DEFAULT_RESOURCE_METRIC` to lower cased as is expected by the API. I doubled checked the other types of metric types and those defaults all seem to be okay based on my understanding of the docs. 
Made a minor change to the translation so it doesn't reference `Target Workload` as we can have multiple types of targets. Trimmed some spaces on translations. 
rancher/dashboard#2187
Easy way to test is to run the `rancher/hello-world` app as deployment. When that is up, create an HPA …
> Fix incorrect scaleTargetRef in HPAs

- assets/translations/en-us.yaml
- config/labels-annotations.js
- models/management.cattle.io.cluster.js
- pages/c/_cluster/apps/install.vue
#1849 
Support looking for the `catalog.cattle.io/requests-cpu` and `-memory` annotations on charts and prevent installation if there is less than that much available on the cluster.
> Support requests-cpu & memory chart annotations (#1849)

- list/workload.vue
- models/workload.js
This helps fix part of https://github.com/rancher/rancher/issues/31286
This allows ReplicaSets controlled by Argo rollouts to appear in the Overview section
> Filter ownerReferences to standard kinds

- components/form/WorkloadPorts.vue
- models/workload.js
[1728](https://github.com/rancher/dashboard/issues/1728#issuecomment-777921220) - updated workload container port NodePort type rows to be more consistent with the Ember UI, where nodeport rows have a 'listening port' input which corresponds to the services ports' nodePort field:
> use listening port field for nodeport

- edit/service.vue
On service edit, after we fetch all the pods we should have been calling the update function to initialize the matching pods correctly rather than rely on the observer. 
rancher/dashboard#717
> Init Service Selector Matching Pods

- assets/translations/en-us.yaml
- components/auth/AllowedPrincipals.vue
#2384 
This PR fixes the typo 'auhorized' and adds a title about the chooser for user & groups.
> Fix for typo in auth config and add header label for users/groups

- components/RelatedWorkloadsTable.vue
- components/ResourceTable.vue
- nav to pvc list, click on a pvc, white page error shown
- caused by new code in ResourceTable requiring the schema & pvc supplies a junk one
> Fix: Clicking on a PVC results in page error

- edit/persistentvolumeclaim.vue
- models/persistentvolumeclaim.js
- these were overwritten by the model's applyDefaults and a default component value
- we now handle clone in both cases
- addresses #2382
> Ensure PVC clone retains Request Storage & Access Modes values

- edit/auth/azuread.vue
setEndpoints() was getting called for every keystroke which effectively overwrote what was entered.
rancher/dashboard#2349
> Resolving an issue where endpoints werent editable in azure ad auth config

- detail/workload/index.vue
- models/workload.js
- plugins/steve/subscribe.js
#1940 - updating the logic around cron job details to get jobs from `metadata.relationships` rather than `status` + fetching jobs on initial page load seems to address this 
#2218 - Switching to a 'matching' getter in computed prop instead of 'findMatching' action in a resource instance method returns a live list of pods here
This PR also addresses a couple issues around editing/cloning cron jobs I encountered in the process.
> workload details pod list update

- assets/styles/base/_typography.scss
- components/nav/Type.vue
- layouts/default.vue
- Rely on inheriting parent's (`.child A`) line-height for both label and count
- This removes the different line-height approach between root (user & auth / users) and resource type (cluster explorer / any) side nav items
- This also fixes the `jump to..` list
> Fix alignment of cluster count in cluster explorer

- pages/auth/verify.vue
- store/auth.js
#2340 - This ended up being pretty small, moving the addition of azureAD's redirect url query params response_type and response_mode to `auth/redictTo` (called on enable and login) instead of `auth/test`(only called on enable) + specifying the correct provider in `auth/verifyOAuth` fixes the problem.
> fix azureAD login action

- chart/rancher-backup/index.vue
- I missed this when making changes in the area and it was spotted by Neil
- Currently the persistence size field is shown when both creating a PV and selecting an existing one
- This PR ensures it's only shown for the former
> Only show PV size field in deploy Dashboard Backup app when creating a PV

- assets/styles/global/_button.scss
- components/auth/AllowedPrincipals.vue
- components/nav/Header.vue
#2374 - the Ember UI disables the 'remove' button for a user/group if it is the only one in the list; this PR updates the dashboard ui to do the same. 
@lvuch  I also made a change to `.role-link` disabled button styling because the alignment is always weird compared to the borderess enabled link/button, before/after:
> do not allow removing sole allowed user/group

- edit/persistentvolume/plugins/awsElasticBlockStore.vue
- edit/persistentvolume/plugins/gcePersistentDisk.vue
While trying to reproduce another issue I noticed that partitions were of the wrong type when saving. This now converts partition to a number before setting the value.
> Fixing the type for partitions in two persistent volume providers

- assets/styles/themes/_light.scss
- components/form/RadioButton.vue
#2410 
In light mode, the `text-muted` style is too light and hard to read against the background - this PR uses a darker color. I added a style override, as I couldn't find an easy way to do this with the way the colors are generated, without affecting more colors used elsewhere.
For Radio Buttons, this PR also changes the style so that the label for a checked radio button in view mode uses the normal color and does not use the disable color - this helps make it much clearer to see which radio button is checked:
> Improve styling of radio buttons in view mode

- config/product/auth.js
- utils/auth.js
Per slack convo with @vincent99 and @codyrancher it is currently not possible to enable azure AD auth through one UI and login through the other. Given the potential for azureAD as it is now to possibly direct users to misconfigure their auth setup, and the time constraints we are currently under, this PR is to hide azure AD config from the UI for this release. 
- hide the custom edit component
- hide the azureAD option from the auth provider select screen
> hide azuread

- assets/translations/en-us.yaml
- config/product/explorer.js
- config/table-headers.js
- edit/admin.rio.cattle.io.publicdomain.vue
- models/secret.js
#2379
Avoid overwriting typeDisplay on secrets with the subtype so that the regular type is shown on import.
> Separate type vs subtype display for Secrets

- edit/persistentvolume/index.vue
- models/persistentvolume.js
- The checkboxSetter for access mode was just wrong and didn't handle the index properly
- Passed mode to checkboxes so they're disabled in view
- Made deletion action dependent on not being in a 'bound' state
rancher/dashboard#2409
> Resolving several minor bugs around persistent volumes

- list/management.cattle.io.setting.vue
#2418 
This PR fixes the above issue. CACerts is a readonly setting, so we should not show the modified tag.
> Fix: don't show modified tag for ca certs

- models/persistentvolume.js
When creating a PV the name is undefined and that allowed it to find PVCs that had
volumeName undefined.
rancher/dashboard#2431
> Resolving an issue around claims showing up when creating a pv

- assets/translations/en-us.yaml
- edit/persistentvolumeclaim.vue
This resolved an issue where some events were missed.
rancher/dashboard#2430
> Replacing the custom related workloads and events tabs on the PVC page

- edit/persistentvolume/plugins/csi.vue
- edit/persistentvolumeclaim.vue
- edit/storage.k8s.io.storageclass/index.vue
- edit/storage.k8s.io.storageclass/provisioners/driver.longhorn.io.vue
- There was a problem with the longhorn driver not being set so this is
now set
- In some versions of the rancher backend a pvc couldn't be bound to a
pv because the storageClassName was expected to be empty
- The wrong storage class name was being shown when a persistent volume
was bound also caused by storageClassName not being empty
- A field should've been marked as required
- Change default values for longhorn
- Clear unset parameters for storage classes
rancher/dashboard#2415
rancher/dashboard#2416
rancher/dashboard#2380
rancher/dashboard#2420
rancher/dashboard#2429
> Resolving a number of issues around pv/pvc/storageclass regarding longhorn

- assets/translations/en-us.yaml
- config/query-params.js
- pages/c/_cluster/apps/charts.vue
- pages/c/_cluster/apps/install.vue
#1849
Ignore the chart's cpu/memory requirements on upgrade.  Also added a `force` query param you can add to bypass the check for install.
> Only check app resource requirements on install, not upgrade

- models/management.cattle.io.setting.js
- previously admin showed `edit` and standard user showed `view config` & `view yaml`
- neither 'view' action should be visible
- this makes use of empty action menu feature in #2440
> Fix disparity between admin and standard user global settings actions

- components/form/ResourceTabs/index.vue
- Addresses #2453
- ResourceTabs were previously exclusively used in detail pages which are always `view` (there's some checks for view in there already, so this might not have always been the case).
- PVC _edit_ component now uses ResourceTabs, so ResourceTab needs to take into account view mode
> Ensure ResourceTab's `Related Resources` tab only shows when in view mode

- assets/translations/en-us.yaml
- components/form/UnitInput.vue
- edit/autoscaling.horizontalpodautoscaler/external-metric.vue
- edit/autoscaling.horizontalpodautoscaler/metric-target.vue
- edit/autoscaling.horizontalpodautoscaler/object-metric.vue
- edit/autoscaling.horizontalpodautoscaler/pod-metric.vue
- edit/autoscaling.horizontalpodautoscaler/resource-metric.vue
This PR adds the functionality to support SI values in Resource metrics. Additionally its adds the input addons for the CPU and Memory metric types in a Resource metric. When porting over I missed this. This required a bit of a rework in the logic that updated the values on the various metrics, and changing the input from a two-way binding to a one way with an update event. This also allowed me to reset the values fields when either the metric type or resource name changes. This prevents a user from changing types from something like Average Value (quantity + si suffix - `300m or 300Mib`) to Utilization (int w/o si suffix - `80`) have having an incorrect value type in the input.
Additional changes include a typo in the translations and adding the required flag to the Unit Input component. …
> Support HPA Quantity Values with SI suffix

- README.md
- components/nav/Header.vue
- components/nav/NamespaceFilter.vue
- edit/namespace.vue
- layouts/default.vue
- middleware/authenticated.js
- models/management.cattle.io.project.js
- models/namespace.js
- pages/c/_cluster/apps/install.vue
- store/index.js
- Separate out isMultiCluster from isRancher on various features, because Steve supports multiple clusters without other Rancher CRDs being present
- Avoid loading rancher store stuff when running in standalone steve
- Hide import & shell buttons if link isn't present instead of disabling, because the only time they should be missing now is if unsupported.
> Support standalone steve

- components/ResourceDetail/index.vue
- On pressing `Create` on, for example, a new HPA, get 'not a function' error
- Only an issue for create (not edit), with SSR and on refresh (nav to create page works fine, think this bypasses ssr)
- Caused by ResourceDetail `value` object not being a proxy
- Looks like `__rehydrate` was stripped from both `originalModel` and `value` by delete obj.__rehydrate in `plugins/steve/index.js`
- These were previously the same instance, the fix is to help break this (as per edit mode) with a `clone`
- Not sure how this reference is carried across server/client boundary. Possibly a case of cached with the same key
- Addresses rancher/dashboard#2369
> Note for QA - SSR is not enabled in production and therefore this would not be reproducible. Would suggest testing that the change has not broken …
> Fix `Create` on custom create resource pages after page refresh

- chart/monitoring/alerting/index.vue
If we have the existing alertmanager secret, regardless of upgrade status, we should at least default to using that secret. 
rancher/rancher#2225
> Existing AlertManager Secret

- assets/styles/global/_select.scss
- assets/styles/vendor/vue-select.scss
- assets/translations/en-us.yaml
- components/nav/ClusterSwitcher.vue
Fixes a light theme issue with the cluster switcher drop down and the no results option where the text color was white on white.
Fixes an issue where a cluster with an extra long name (helps if on a small screen as well) would cause the content of the dropdown to flow off screen. 
Fixes some bare strings in cluster switcher.
Formatted the file. 
rancher/dashboard#2329
> Cluster Switcher Bugs

- assets/translations/en-us.yaml
- config/product/auth.js
- edit/auth/azuread.vue
- edit/auth/saml.vue
- pages/auth/verify.vue
- server/server-middleware.js
- store/auth.js
- utils/auth.js
- utils/crypto/index.js
1. change redirect_uri for googleoauth and azureAD to match Ember UI instructions: `<window.location.origin>/verify-auth` and `<window.location.origin>/verify-auth-azure` respectively
2. Use a JSON object for `rc_nonce` cookie, with keys: nonce, provider, to, test
included #2422 - entityID field should only be visible for keycloak and ping
> auth nonce as json

- assets/translations/en-us.yaml
- components/Loading.vue
- components/nav/GlobalLoading.vue
Most of the time when you navigate around the UI, a loading indicator is shown on page changes as data is fetched - this currently overlays the entire browser view, which is quite jarring.
This PR changes this behaviour - page views will now only show the loading indicator over the content area (not the side nav or header).
I've added a mode to the Loading component to allow configurability of what portion of the window should be covered for the indicator.
The Global Loading component uses the 'full' mode - so when you log in, the Loading indicator still appears over the entire browser view.
I think this overall gives a better user experience.
> Tweak the loading indicator so its less jarring when changing views

- components/nav/ClusterSwitcher.vue
Changes the text color from var input-color to header-btn-text (black -> white)
rancher/dashboard#2329
> fix up cluster switcher text color

- assets/styles/global/_select.scss
- assets/translations/en-us.yaml
- detail/autoscaling.horizontalpodautoscaler/index.vue
- edit/autoscaling.horizontalpodautoscaler/index.vue
- edit/autoscaling.horizontalpodautoscaler/metrics-row.vue
- edit/autoscaling.horizontalpodautoscaler/resource-metric.vue
- models/autoscaling.horizontalpodautoscaler.js
PR contains multiple fixes for a bigger collected enhancement ticket:
Adds warning banners to custom metrics (missed this in the port).
Refactor the metric list details (see pics below) to match the Ember Ux more closely.
Hide the remove metric row button when creating and only one metric row exists. Didn't make this a validation error as its technically not invalid.
Adds warning when target ref does not include any Resource Requests that the metric will be ignored. Again not a validation issue as it is valid.
rancher/dashboard#2444
New Details:
> HPA Enhancements

- assets/styles/global/_tooltip.scss
- components/form/LabeledSelect.vue
Fixes issue where the tooltip is not correctly positioned/aligned for the header buttons (import, shell.
Also fixes the LabeledSelect control so that the tooltip is only shown when hovered by default (you can see the current behaviour on the form-controls page of deisng-system)
@lvuch It looks like your PR that changed buttons etc changed the css that affected the tooltip alignment - I can't see anything broken with the change back in this PR - can you recall why that change was necessary?
> Fix tooltip positionning on buttons in header

- components/form/LabeledSelect.vue
- components/form/Select.vue
- utils/select.js
This was more involved than initially anticipated because of a few choices made by vue-select.
1. Vue select prevents event bubbling by watching the mouse-down event instead of the click event which preempted any clicks that you added in the #options slot.
2. optionKey and valueNormalization changes the shape of the options and the values so I needed to make sure we retrieved the values and selected options appropriately.
3. When updating the values to remove the selectedOption vue-select kept overriding my value because in it's updateValue would be called if the values were changed. So strangely if I emitted input it would reset the value but if I didn't emit input it wouldn't update the value even though it was going through the same control flow.
rancher/dashboard#2357
Verified these …
> Adding support to deselect options in Labeled/Select by clicking on the options in the dropdown

- assets/translations/en-us.yaml
- edit/persistentvolume/index.vue
- edit/persistentvolume/plugins/azureDisk.vue
- edit/persistentvolume/plugins/cephfs.vue
- edit/persistentvolume/plugins/cinder.vue
- edit/persistentvolume/plugins/csi.vue
- edit/persistentvolume/plugins/fc.vue
- edit/persistentvolume/plugins/flexVolume.vue
- edit/persistentvolume/plugins/flocker.vue
- edit/persistentvolume/plugins/glusterfs.vue
- edit/persistentvolume/plugins/iscsi.vue
- edit/persistentvolume/plugins/longhorn.vue
- edit/persistentvolume/plugins/photonPersistentDisk.vue
- edit/persistentvolume/plugins/portworxVolume.vue
- edit/persistentvolume/plugins/quobyte.vue
- edit/persistentvolume/plugins/rbd.vue
- edit/persistentvolume/plugins/scaleIO.vue
- edit/persistentvolume/plugins/storageos.vue
- edit/storage.k8s.io.storageclass/index.vue
- edit/storage.k8s.io.storageclass/provisioners/kubernetes.io/cinder.vue
- edit/storage.k8s.io.storageclass/provisioners/kubernetes.io/glusterfs.vue
- edit/storage.k8s.io.storageclass/provisioners/kubernetes.io/no-provisioner.vue
- edit/storage.k8s.io.storageclass/provisioners/kubernetes.io/portworx-volume.vue
- edit/storage.k8s.io.storageclass/provisioners/kubernetes.io/quobyte.vue
- edit/storage.k8s.io.storageclass/provisioners/kubernetes.io/rbd.vue
- edit/storage.k8s.io.storageclass/provisioners/kubernetes.io/scaleio.vue
- edit/storage.k8s.io.storageclass/provisioners/kubernetes.io/storageos.vue
- models/persistentvolume.js
- models/storage.k8s.io.storageclass.js
- utils/feature-flag.js
- Adding unsupported storageclasses
- Adding unsupported persistent
rancher/dashboard#2284
Adding the persistent volume plugins that are gated by the `unsupported-storage-drivers` feature flag.
> Adding support for `unsupported-storage-drivers`

- assets/translations/en-us.yaml
- components/PromptRemove.vue
- models/management.cattle.io.user.js
- models/namespace.js
- models/node.js
- models/rio.cattle.io.stack.js
- plugins/steve/resource-instance.js
- when deleting multiple resources, and confirm is enabled, prompt for a random resource name for confirmation
- the random resource name will always be visible in the list shown to the user (given that this list is sometimes truncated)
- Improved process to declare which resource requires confirmation
- i10n'd some text
- addresses #2175
~~Q - The wording when deleting the random resource doesn't quite sit right given the resource to enter is from the list above and the box it has to go in is below. Open to suggestions on rewording~~
> Request typed confirmation when deleting multiple resources

- config/product/settings.js
- detail/management.cattle.io.user.vue
- list/management.cattle.io.user.vue
- models/management.cattle.io.user.js
- pages/c/_cluster/settings/index.vue
- Users
- users list does not fail, only signed in user visible (returned via api)
- user 'activate/deactive' now respects api put flag (previously could attempt to deactivate self)
- user details page (of signed in user) better handles case when role schemas are inaccessible
- Settings
- Only show settings/feature flag when settings/feature flag schemas are avaiable
- Only show setting product when either settings or feature flags are available
> Fix User type and Settings Product when user is non-admin in non-local cluster

- components/nav/ClusterSwitcher.vue
Cluster switcher handles its own positioning because the default positioning would flow the dd off the right side of the window with how our styles are setup. 
A unique edge case presented itself: 
User has at least one cluster with a very long name (I used a 62 char string)
User searches for something that returns no results
User executes a `CMD+A` (or your os equiv) and `backspace/delete` key press
The dropdown would not recompute the size as one would expect and the dropdown would overflow off the screen until the user typed another character or left the dd and came back.
This was a tricky solve that I tracked down to the dropdown repositioning not firing because of the way that v-select handles the keydown event. I tried overriding the backspace key in `vue-select-overrides` but …
> Add key up handler to cluster ClusterSwitcher

- plugins/steve/resource-instance.js
- #2561
- Ensure contents of files is correct
- Accessing `.data` matches, roughly, what happens in download() action
- fallback on previous way just in case
> Fix Download YAML list action when multiple resources are selected

- edit/auth/azuread.vue
- store/auth.js
As part of this https://github.com/rancher/rancher/issues/31562 I changed azure auth to use the same redirect url as other auth types, `/verify-auth`. This works as expected for new setups, but while looking at a different azuread issue I realized it was a poor decision, and will break preexisting  azuread configs that use `/verify-auth-azure`. Both ui's should use `/verify-auth-azure` for azuread, which leverages the same redirect logic as` /verify-auth`. Related UI PR: https://github.com/rancher/ui/pull/4507
> Fix azuread auth route

- models/management.cattle.io.user.js
- plugins/steve/resource-instance.js
- #2527
- the api does not allow the signed in user to deactivate/delete themselves
- ensure that we don't show these options by checking user isn't the signed in one
- ideally this should be done via the api by removing the 'remove' link for the signed in user
> Ensure current user cannot deactivate or delete themselves

- assets/translations/en-us.yaml
- edit/monitoring.coreos.com.receiver/tls.vue
> Adding helper info to the SSL portions of the email and webhook monitoring receivers

- assets/styles/themes/_dark.scss
- assets/styles/themes/_light.scss
- assets/translations/en-us.yaml
- components/GlobalRoleBindings.vue
- components/form/Checkbox.vue
- config/product/auth.js
- config/product/explorer.js
- edit/management.cattle.io.user.vue
- models/management.cattle.io.user.js
- plugins/steve/resource-proxy.js
- #2524
- Create user via norman rather than steve
- Code changes for #2525
- Updates checkbox label and description colour (move description into checkbox component, make label stand out more via slot)
- Make tick in disabled checkboxes clearer
- Add copy button to user details username field (at top)
- ~~Fix download of yaml for multiple resources (bug covers batch yaml download).~~ Split out in to #2562
- #2526
- Remove confusion between Auth products Users list and Cluster Explorers Users list by removing the latter. This is the same approach used by some of the other resources in product views
- Also fixed a bug where resources with a description that didn't have a custom model failed to report the correct description value
> Multiple fixes to Users

- assets/translations/en-us.yaml
- components/Card.vue
- components/GlobalRoleBindings.vue
- components/auth/SelectPrincipal.vue
- components/form/Footer.vue
- list/group.principal.vue
- models/group.principal.js
- pages/c/_cluster/auth/group.principal/assign-edit.vue
This PR contains fixes to the groups list and assign/edit group page. This involves changing the GlobalRoleBinding component which handles group assign/edit of global roles and new/existing users view/edit/initial global roles 
- #2540 UI Issues
- Issue 3 - GlobalRoleBinding - Built-in and custom roles are now sorted alphabetically
- Issue 4 - GlobalRoleBinding - Role types are now encapsulated in cards
- Improvement - Assign Global Roles - Ensure only assign is possible
- In Ember this was a pure assign page, any existing roles were disregarded (this meant there could be multiple bindings to the same role)
- In the Dashboard we now take into account the groups existing roles. Previously to this PR these existing roles could be removed via the assign page, this is now not possible. 
- The …
> Multiple Groups Fixes

- edit/auth/ldap/config.vue
- edit/auth/saml.vue
- mixins/auth-config.js
#2545 #2548 #2547 - these are resolved by ensuring that `model.openLdapConfig` is defined and has defaults set any time the ldap section is shown.
#2546 - also in this PR
> ldap defaults for shibboleth

- components/PercentageBar.vue
#2592 
This PR ensures that the text value in the percentage bar component does not word wrap - fixes issue where the value and the % units would be split on different lines
> Fix line break in % value on percentage bar component

- list/management.cattle.io.setting.vue
#2471 
Small fix to change the color of the settings titles so that they are not confused with links.
> Settings: Change text color of heading so as not to confuse with a link

- components/form/LabeledSelect.vue
Some LabeledSelects that use get-option-label do not populate the LabeledSelect slot correctly and make the dropdown appear empty: 
(workload env vars)
> use option-label-getting func instead of option.label

- config/product/auth.js
- list/group.principal.vue
- Groups list shows principals that have global role bindings
- Some global role bindings pointed to principals that weren't returned when fetching all principals
- This meant they were skipped from the list
- Solution is to flip the logic from principals that have grbs... to unique grbs principals
- Seen on a QA system with a AD auth provider
- Address #2568
> Groups List: Ensure all groups are shown

- .drone.yml
- scripts/build-upload-gate
- Reduce the impact of concurrent drone builds, specifically avoid overwritting newer builds that were quicker by older builds that were slower.
- hosted and embedded builds will only get uploaded if they're built from the same commit as head of their branch
- docker builds however still might get uploaded, there's no intermediate step between build and upload to docker. Not quite sure how this doesn't fail as the drone plugin `force_tag` uses default false (doesn't overwrite - http://plugins.drone.io/drone-plugins/drone-docker/)
> Improve drone build

- pages/prefs.vue
- `v-model.number` was converting the option `1,000` to `1`
- Fixed by setting explicit label/value properties in options
- Addresses #2594
> Fix setting of page size to 1000

- components/ResourceDetail/index.vue
- components/SortableTable/THead.vue
- components/SortableTable/paging.js
- components/SortableTable/sorting.js
#2327 - This issue was happening because both Tabs and SortableTable were using route query params to track their state state (active tab, table sort order and page). Updating SortableTable to track column sorting and page number only in local state (`this.sortBy this.descending; this.currentPage`) instead of query params avoids the problem.
> table sort/active tab conflict

- components/form/NodeScheduling.vue
- edit/workload/index.vue
#2577 - actually delete `affinity.nodeAffinity` when 'run pods on any node' is selected
#2553 - this PR marks the service dropdown as required, but no changes to how that dropdown is populated. That actually appears to be the result of a broader dropdown bug which was addressed here: https://github.com/rancher/dashboard/pull/2603
> fix node affinity radio

- components/auth/login/ldap.vue
- pages/auth/login.vue
#2596 - in addition to addressing the problem outlined here, I made a minor change to the ldap component so its inputs aren't shown if there are multiple providers present. I don't think that scenario is particularly common and the UI is structured to discourage it anyway, but this change makes it clearer which provider the inputs are for. If I didn't know the other two providers opened a popup I would find this somewhat ambiguous (and it's a bit ugly):
changes in this pr:
no third party provider:
one ldap provider:
multiple providers:
ldap/local input toggle behavior:
https://user-images.githubusercontent.com/42977925/113458599-aa4ed480-93c7-11eb-904f-9a9213b1add3.mov
> fix log in provider buttons

- components/CruResource.vue
#2595 
The more info link on the CruResource component is not wired up - we show the link, but the link is always empty.
I have hidden the links for now - I see no evidence that there was ever any docs for these. They are gated on a docLink property that is not currently set, so they never show.
We should revisit - I assume the intent was that these linked to the k9s docs
> Hide More Info links on CRU Resource

- list/group.principal.vue
- Only an issue when using SSR & on refresh of groups list page
- caused by getSpoofedInstances failing to find principal groups getInstances due to type-map's instanceMethods being empty
- addresses rancher/dashboard#2606
> Fix SSR issue where unassigning a group's roles wiped the groups list

- .github/workflows/pr-zube.yaml
- .github/workflows/scripts/pr.js
- .github/workflows/scripts/request.js
This PR adds a GitHub action that triggers when PRs are opened, re-opened, edited or closed.
This allows us to use GitHub linked issues with out workflow, where merging a PR should move the issues it fixes to the Test, rather than closing them.
Details for GitHub linked issues are here: https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
For the open case, for all linked issues, it will:
- Set the assignee to the person creating the PR (if no assignees were added)
- Add the Zube 'In Review' label and remove any other Zube labels
For the edited/re-opened case, for all linked issues, it will:
- Add the Zube 'In Review' label and remove any other Zube labels
For the closed case, for all linked …
> Add GitHub Actions to support using GitHub linked issues with Zube

- assets/translations/en-us.yaml
- components/form/SelectOrCreateAuthSecret.vue
- config/cookies.js
- models/catalog.cattle.io.app.js
- pages/c/_cluster/apps/charts.vue
- pages/c/_cluster/apps/install.vue
- plugins/axios.js
- Fix rare CSRF mismatch caused by parsing as scientific notation JSON (Fixes #2432)
- Add windows.enabled and server url global chart defaults (Fixes #2613, Fixes #2626)
- Add button to ignore chart cpu/memory warning (Fixes #2565)
- Load existing gitrepo secrets correctly (Fixes #2503)
> 2.5.8 Bugs

- assets/translations/en-us.yaml
- pages/c/_cluster/apps/install.vue
#2222 - currently the project dropdown is hidden entirely if the app's target namespace already exists, because that namespace can't be added to/remade in a different project. This PR makes that limitation clearer by still showing the dropdown (with relevant project), but disabled with a tooltip explaining why.
> show warning if app is installing into project

- components/form/WorkloadPorts.vue
- edit/workload/index.vue
- models/workload.js
Switching from editing workloads via form to editing via yaml breaks the page if the workload doesn't pass validation because `BEFORE_SAVE_HOOKS` are applied when 'Edit as YAML' is clicked, and the service-creation logic in workloads' `BEFORE_SAVE_HOOKS` runs workload validation. It's necessary for another workload `BEFORE_SAVE_HOOK` to run prior to yamlizing the workload, but I think it's pretty undesirable to create services upon switching from form to yaml view; it really shouldn't happen until the user is really done defining the workload. 
In light of that, I moved service creation to after the workload is made. This has the added benefit of simplifying the process of attaching ownerRefs to the services.
> fix workload config->yaml edit breaking

- assets/translations/en-us.yaml
- edit/auth/googleoauth.vue
- edit/auth/ldap/config.vue
- utils/crypto/index.js
#2116 - This is happening because the `state` query param (used to determine which ui to route to) is malformed. The url-safe base64 encoding in dashboard is only removing at most 1 padding `=` when there can be up to 2. eg
` {"nonce":"OqO3ozOqPsnPeQKJ","to":"vue","test":true,"provider":"googleoauth"}` 
becomes 
`eyJub25jZSI6Ik9xTzNvek9xUHNuUGVRS0oiLCJ0byI6InZ1ZSIsInRlc3QiOnRydWUsInByb3ZpZGVyIjoiZ29vZ2xlb2F1dGgifQ==`
#2627 #2628  also in this pr
> Auth fixes

- components/form/UnitInput.vue
- edit/persistentvolumeclaim.vue
- Fix exception thrown when UnitInput converts duff (`nullGi`) value into correct format (before min handler kicks in)
- Also wire in a min prop to UnitInput & set Request Storage min to 1 (min supported by API)
- Addresses #2591
> PVC Request Storage UnitInput: Handle falsy values, set min value

- chart/monitoring/index.vue
only sets the default if the provider is rke or rke2.
rancher/dashboard#2485
> Enabling ingressNginx by default when installing a monitoring chart

- assets/translations/en-us.yaml
- components/auth/RoleDetailEdit.vue
- detail/rbac.authorization.k8s.io.clusterrole.vue
- detail/rbac.authorization.k8s.io.role.vue
- edit/rbac.authorization.k8s.io.clusterrole.vue
- edit/rbac.authorization.k8s.io.role.vue
- models/management.cattle.io.globalrole.js
- models/management.cattle.io.roletemplate.js
- models/rbac.authorization.k8s.io.clusterrole.js
- models/rbac.authorization.k8s.io.role.js
- Uses same generic way to handle roles as Management Global Roles and Role Templates
- Applies to `rbac.authorization.k8s.io.role` and `rbac.authorization.k8s.io.clusterrole`
- Addresses #2663
> Add Create/Edit/View/Detail Pages for RBAC Role and ClusterRole

- pages/c/_cluster/apps/install.vue
Simple fix to bring dropdown label text back into window. 
A more elegant solution probably exists but would affect all dropdown cmps, and is likely out of the scope of this ticket.
> adjusted spacing to bring text back into view

- components/SortableTable/selection.js
- components/form/Checkbox.vue
This PR fixes the issue where the table select highlight has disappeared.
The problem was caused by changes to the checkbox control and the fact that the table select relies on the dom structure of the checkbox control, so changing one broke the other.
> Fix table selection no longer showing

- components/PromptRemove.vue
- store/action-menu.js
#2328 - this PR just implements the changes outlined in the issue; add an event listener to the modal to set `showPromptRemove` to false and empty the `toRemove` array when the modal is closed.
> clear promptremove store when modal closed

- assets/styles/themes/_light.scss
- assets/styles/vendor/vue-select.scss
- components/nav/ClusterSwitcher.vue
- components/nav/NamespaceFilter.vue
- components/nav/WorkspaceSwitcher.vue
- Overwrote 2520 and elevated from component level to global dropdown styling
- Added css var for future ease in themes
- Fixed typo, `<style type="scss" scoped>` should be `<style lang="scss" scoped>`
> css fixes for header input fields

- chart/monitoring/ClusterSelector.vue
#2537 - adds rke windows cluster type, which sets all the same default config values as rke, plus `windowsExporter`
> add rke windows as monitoring cluster type

- assets/translations/en-us.yaml
- components/CopyToClipboardText.vue
- edit/auth/azuread.vue
- edit/auth/github.vue
- edit/auth/googleoauth.vue
- mixins/auth-config.js
This PR fixes a few auth presentation issues:
- Ensures URLs that the user should use when configuring are not shown as links
- Fixes the serverURL so it correctly uses the window origin when rendering client-side (this is consistent with the Ember UI)
- Improved the spacing of the list item steps in a couple of places
- Fixed a typo in 'Congiure'
- Uses bold text in the same way the Ember UI does for labels for URLs that the user is expected to copy and use for configuration
- Fixed issue with labels on GitHub auth 
This addresses #2628, #2116 and #2690
> Fix a few auth presentation issues

- assets/translations/en-us.yaml
- components/ResourceYaml.vue
- components/auth/RoleDetailEdit.vue
- components/form/RadioButton.vue
- config/product/auth.js
- config/product/explorer.js
- models/management.cattle.io.globalrole.js
- models/management.cattle.io.roletemplate.js
- pages/c/_cluster/auth/roles/index.vue
- plugins/steve/resource-instance.js
- Address majority of points from #2675
- Ensure form/yaml cancel/done return to auth roles page
- Previously yaml version returned to cluster explorer
- This also removes the management global role and role template resource types from the cluster explorer (as per other types served by the auth section)
- Roles Tables: Apply better labels to 'default' role table column
- Previously these were all labelled as 'Default'
- Now they're New User Default, Cluster Creator Default and Project Creator Default
- Grant Resources Tab: Remove required indicator for role rules
- These aren't required by the API and were causing confusion
- Fixed Visual bugs
- Grant Resources Tab: Change Rule 'Resources' label to 'Resource`
- Radio Button Disabled State: Don't show standard grey colour for radio blob, …
> Users & Auth: Roles Fixes

- edit/auth/googleoauth.vue
- utils/crypto/index.js
#2116 - I failed at addressing this bug with the state query param previously and introduced a different issue with url-safe base64 encoding. 
#2667 - adds nestedGroupMembership field to google oauth enabled view:
related ember pr: https://github.com/rancher/ui/pull/4537
> fix base64 url-safe and add nestedGroup to google auth view

- components/PromptRemove.vue
- plugins/steve/actions.js
- store/action-menu.js
#2699 - this issue is caused by some changes to promptRemove that were made and then reverted in workload sidecars...I think this actually *was* fixed in the sidecar PR, but I must have clobbered the fix while correcting merge conflicts or something.
> fix togglePromptRemove 

- components/auth/RoleDetailEdit.vue
- models/rbac.authorization.k8s.io.role.js
- Addresses #2693
- Removed unused code (setVerb/getVerb)
- Improve handling of empty strings when setting arrays in a rule
- Remove required field for api groups for non-rancher types (rbac role/cluster role)
- There's a lot of validation for these types in the backend that would be tricky to do with the current mechanism up front
- Namespaced roles cannot use non-resource urls
- Rules with resources must have api groups (and vice versa)
- Roles with no rules are ok (guessing this is because there's no validation of the inherit role side)
- So let the api validation do it's thing for the complex cases on submit
- Apply basic rule validation to non-rancher role types
> Improve validation for Roles, Fix empty Rule property bug

- chart/monitoring/index.vue
rke2 has the nginx-ingress installed in kube-system so we're modifying the default namespace in the monitoring configuration.
https://github.com/rancher/dashboard/issues/2728
> Changing the namespace configuration for rke2 monitoring installs

- pages/c/_cluster/explorer/index.vue
etcd metrics had an info box that needed to be accounted for.
https://github.com/rancher/dashboard/issues/2704#issuecomment-822707996
> Fixing the grafana link for etcd metrics

- components/nav/WindowManager/index.vue
#2403 
Added .stop event modifier to prevent action being fired twice
> added .stop event modifier to prevent propagation

- assets/translations/en-us.yaml
- components/TypeDescription.vue
- components/formatter/AppSummaryGraph.vue
- components/nav/Group.vue
- components/nav/ProductSwitcher.vue
- config/product/auth.js
- config/product/explorer.js
- config/product/fleet.js
- config/product/manager.js
- config/product/settings.js
- config/query-params.js
- layouts/default.vue
- models/catalog.cattle.io.app.js
- models/chart.js
- pages/c/_cluster/apps/charts.vue
- pages/c/_cluster/apps/install.vue
- pages/c/_cluster/explorer/tools.vue
- store/catalog.js
- store/index.js
- store/type-map.js
- utils/dynamic-importer.js
#2509 - Cluster tools at the bottom listing only the Rancher charts and showing the installed status
#2578 - Show cluster-level products inline in the Explorer left nav instead of as separte options in the Product dropdown
> [2.6] Cluster Tools & inline cluster product nav

- components/SelectIconGrid.vue
This PR updates the presentation of the SelectIconGrid component.
This component is currently used in two places:
(1) Chart list page
(2) Auth provider page
Styling changes:
- Remove gradient background
- Move side label to the top right when there is label text (auth provider)
- Show side label as a top color bar when there is no text (chart list)
- Use border color on hover, not background change
The styles changes in this PR bring this control in line with the overall changes we want to make in 2.6.
> [2.6] Update style of SelectIconGrid

- assets/styles/base/_helpers.scss
- assets/translations/en-us.yaml
- components/formatter/RouterDestination.vue
- components/formatter/RouterMatch.vue
- Seen in Deployment list Images column (`components/formatter/PodImages.vue`), translation was missing, so only ever showed a single image
- Also
- Moved global scoped `plus-more` to a more fitting place
- Ensure + more translation is used in other places
> [2.6] Fix 'plus more' text

- pages/c/_cluster/explorer/index.vue
This was just changed as part of a merge to not search for the rke prefix. This corrects the behavior.
rancher/dashboard#2759
> Including rke2 for the isRKE check when displaying the etcd metrics

- components/nav/Group.vue
- components/nav/TopLevelMenu.vue
- layouts/default.vue
- models/management.cattle.io.cluster.js
This PR addresses a few issues in the side nav:
- Fixes font size for group headers
- Fixes provider icons
- Ensures nav is collapsed when Cluster Tools is invoked
- Fixed error navigating to some groups after going to Cluster Tools
- Made presentation of Cluster Tools consistent with the rest of the side navigation
> [2.6] Tweak navigation UI presentation

- assets/translations/en-us.yaml
- edit/workload/index.vue
- edit/workload/storage/index.vue
- utils/validators/container-images.js
#2722 - this isn't called out in the issue, but I noticed the container image validator wasn't updated to account for multiple containers so I went ahead and added that functionality as well
#2709 #2722 - both of these are related to some lingering code in the workload save function no longer relevant with the switch to sidecars-in-config-page
#2716 - moved PVC filtering (by namespace) to a computed prop to make it reactive
This should go in 2.6 as well. Related PR: https://github.com/rancher/dashboard/pull/2740
> [2.5.8] fix sidecar indexing, container image validation, workload storage pvc namespacing

- assets/translations/en-us.yaml
- components/auth/RoleDetailEdit.vue
- models/management.cattle.io.globalrole.js
- models/management.cattle.io.roletemplate.js
- models/rbac.authorization.k8s.io.role.js
- utils/validators/role-template.js
- RBAC Role type improvements
- Remove rule 'Non-Resource URL' field. RBAC role type is namespaced, non-resource url's are not. 
- Apply additional validation
- rule resource AND api group required, rather than default rule resource, non-resource url or api group required
- name is required
- Show Required indicator for all fields (reflecting validation)
- Other Role type improvements
- Show Required indicator for rule Verbs field
- name is required
Note - Showing rule required indicators means that when the page initially loads it appears like the user needs to enter values for the default/empty rule row ... but user can ignore this and successfully save the role anyway. The alternative is to not show an empty rule to begin with... but this forces the user to `Add Resource`. I feel the …
> [2.5.8] Improve Role Required Indicators/Validation

- assets/translations/en-us.yaml
- components/auth/RoleDetailEdit.vue
- models/management.cattle.io.globalrole.js
- models/management.cattle.io.roletemplate.js
- models/rbac.authorization.k8s.io.role.js
- utils/validators/role-template.js
- RBAC Role type improvements
- Remove rule 'Non-Resource URL' field. RBAC role type is namespaced, non-resource url's are not. 
- Apply additional validation
- rule resource AND api group required, rather than default rule resource, non-resource url or api group required
- name is required
- Show Required indicator for all fields (reflecting validation)
- Other Role type improvements
- Show Required indicator for rule Verbs field
- name is required
Note - Showing rule required indicators means that when the page initially loads it appears like the user needs to enter values for the default/empty rule row ... but user can ignore this and successfully save the role anyway. The alternative is to not show an empty rule to begin with... but this forces the user to `Add Resource`. I feel the …
> [2.6] Improve Role Required Indicators/Validation

- models/secret.js
This fixes an issue where going to the Secrets List gave an error - this.certInfo?.sans.filter is not a function.
This may be a mismatch between the backend and frontend versions (?) - but this PR guards against filter being undefined.
> Fix issues viewing secrets list

- chart/monitoring/ClusterSelector.vue
#2537 
Related 2.6 PR: https://github.com/rancher/dashboard/pull/2743
> [2.5.8] monitoring - use global.cattle.windows.enabled instead of windowsExporter.enabled

- chart/monitoring/ClusterSelector.vue
Related 2.5.8 PR: https://github.com/rancher/dashboard/pull/2742
> [2.6] monitoring - use global.cattle.windows.enabled instead of windowsExporter.enabled

- components/form/KeyValue.vue
- components/form/Security.vue
- edit/workload/index.vue
#2804  - This is happening because of [this](https://github.com/rancher/dashboard/pull/2740/files#diff-d9e05a5df9a8de1f810e516fb295a3217ccf413a0a8fa868c36ff881dc58cc2cL528-L538) change; I thought with the sidecar-picker-in-form change this code was unnecessary and edits to the `container` data prop were being properly reflected in the `podTemplate` but that isn't the case for every container sub-component. Adding that code back to `saveWorkload` is insufficient because it'd only ensure the current container's spec is reflected in the `podTemplate` correctly so I added a watcher instead. 
#2807 - updated `saveWorkload` to not attempt to set a pod selector on edit/clone. In the process I noticed creation via Ember doesn't set one for cron jobs so I replicated that behavior here.
I found a …
> [2.5.8] workload sidecar fixes

- components/nav/Group.vue
This PR fixes an issue where items in a root nav group can disappear when another group is expanded.
For example, explore a cluster, then go to Continuous Delivery and then click on 'Advanced'. The two three items will vanish.
> Fix issue where root nav group can disappear

- pages/auth/login.vue
- store/index.js
This PR fixes an issue where the query param can get changed from logged-out to timed-out, leading to the red text on the login page after a successful logout.
I also changed the font size of the button text back to the default button text size.
> Fix issue where logging out shows the red text for session timeout

- edit/auth/googleoauth.vue
- mixins/auth-config.js
- plugins/steve/resource-instance.js
#2824  Per Dan's comment [here](https://github.com/rancher/dashboard/issues/2824#issuecomment-825999391), the dashboard shouldn't set `oauthCredential` or `serviceAccountCredential` fields before saving the config; omitting these results in a UI validation error so I added exceptions for those two fields when saving the model to edit allowed users/groups
2.6 PR: https://github.com/rancher/dashboard/pull/2833
> [2.5.8] Google Ouath edit

- store/index.js
This PR fixes a bug where you can't access a cluster after logging in again following a logout.
Currently doing so gives an empty screen instead of the cluster navigation and pages.
> Fix issue accessing a cluster after logging in again

- config/product/monitoring.js
Monitoring doesn't appear correctly in the side nav - the Advanced section is lost and the Monitoring items appear under the Monitoring header in a 2nd-level Monitoring group rather than at the top level.
> Fix monitoring side navigation

- components/SortableTable/THead.vue
- components/SortableTable/index.vue
- components/form/Checkbox.vue
This PR adjusts the styling of tables:
- Fixes an issue where the padding get increased, leading to wide checkbox column and additional spacing
- Checkbox column is now sized minimally
- Changed styling of actions button to remove pastel color in light mode
> Improve styling of tables

- chart/monitoring/ClusterSelector.vue
The provider name is rke.windows so we needed to switch these over so things would work as expected for windows.
rancher/dashboard#2838
> [backport] Updating the usage of rke-windows to rke.windows in the ClusterSelector

- pages/c/_cluster/explorer/index.vue
Currently, the cluster dash breaks if the user viewing it doesn't have permission to count info for nodes or deployments.
> Fix cluster dashboard for users with restricted access

- utils/install-redirect.js
This PR fixes a bug where navigating from the home page to Fleet, without first going via a cluster, fails.
> Fix navigation issue with Fleet from home page

- components/nav/TopLevelMenu.vue
- layouts/default.vue
- pages/c/_cluster/explorer/tools.vue
- utils/version.js
Following feedback:
- Make the Cluster Tools button more prominent
- Add icon
- Add version number at bottom - (a) so it is there, (b) raise the Cluster Tools button up
> Make Cluster Tools button more prominent

- chart/monitoring/ClusterSelector.vue
The provider name is rke.windows so we needed to switch these over so things would work as expected for windows.
rancher/dashboard#2838
> Updating the usage of rke-windows to rke.windows in the ClusterSelector

- nuxt.config.js
- prism theme borks our code block styles
- see https://content.nuxtjs.org/configuration/#markdownprismtheme
- the docs pages look fine without, but we may need to investigate when those use cases grow
- addresses #2867
> Disable prism theme brought in via Nuxt Content

- assets/translations/en-us.yaml
- components/nav/Group.vue
- components/nav/Header.vue
- config/product/apps.js
- config/product/explorer.js
- config/product/gatekeeper.js
- config/product/istio.js
- config/product/logging.js
- config/product/longhorn.js
- config/product/monitoring.js
- layouts/default.vue
#2847 
This PR makes a number of improvements to the side navigation:
- Ensures the weight of products is used to sort the side items in explorer
- Updates the weights, so Apps & Marketplace is under Workloads
- Adds weights top Monitoring and Logging to move them up
- Fixes issues with Longhorn - where an item with only a single overview child still shows the expander icon
- Converts first-child Overview pages to overviews that are accessed from the top-level nav item for the appropriate products
- Updates the tooltip for the Resource Search icon to include the keyboard shortcut
> Side navigation updates

- pages/home/index.vue
This PR reverts the extra Explorer button on the Home Page clusters table and changes the name link back to take the user to explore the cluster.
The name link will now now be active if the cluster is not ready.
I'll discuss with Lauren how to bring the link for going to the cluster yaml, but for the home page use case, it feels better if the link takes you to explore the cluster.
The Explore button was also too prominent with respect to the rest of the page.
> Change presentation of cluster table on the home page

- components/ConsumptionGauge.vue
- pages/c/_cluster/explorer/HardwareResourceGauge.vue
- pages/c/_cluster/explorer/ResourceSummary.vue
- pages/c/_cluster/explorer/index.vue
This PR:
- Removes text-muted to make text easier to read
- Fixes alignment of error/warnings on card when there is only one shown
- Fixes Nodes and Deployment boxes not showing
- Adds back the usage for pods, cpu and memory (in addition to percentage)
- Sets cursor and hover for cards that can navigate you to nodes or deployments
> Cluster Dashboard page tweaks

- assets/styles/themes/_light.scss
- components/nav/NamespaceFilter.vue
For light mode, use the same primary colour for hover
Also, for the Cluster Selection control, add small padding to the menu items
> Change colours for dropdown select on light theme

- components/form/ShellInput.vue
- edit/workload/index.vue
- models/workload.js
#2860 - defining `initContainers` in the pod spec during `applyDefaults` ensures the UI updates when the list changes (eg when removing an init container)
#2708 - remove `_init` property on container when init/standard radio group is toggled to standard
#2857 - ensure arrays of arguments passed to ShellInput get quotes around space-containing elements so they can be correctly parsed back into an array
related 2.6 PR: https://github.com/rancher/dashboard/pull/2862
> [2.5.8] fix init container updating, command args formatting

- components/ContainerResourceLimit.vue
- Think this covers workloads, container and namespaces
- when no limits were set we were still appending the unit, leading to values like `nullMi`
- we now overwrite all limits every time, keeping only those with new values
- Addresses #2878
> Fix create/edit of resources that use ContainerResourceLimit

- components/form/ShellInput.vue
#2857 -updates the ShellInput input-parsing regex to handle single quotes correctly
> [2.5.8] fix shellinput string parsing regex

- store/index.js
- getter is `isRancher === true`
- value of isRancher was a truthy (a schema obj) rather than boolean, so getter was always false
- this was the cause of the missing `Accounts & API Keys` menu item in the user avatar menu
> Fix isRancher getter

- config/product/monitoring.js
There is an extra sub-nav 'monitoring' - these items should be under the main 'Monitoring" header.
> Fix monitoring navigation

- package.json
- Seeing some heap crashes after running the app for a while
- Added a target to increase the available mem to work around this
- Ideally need to find the underlying issue
- I had a quick look, but requires more time to investigate (we already have some fixes for common causes like missing `require('dotenv').config()`)
> Add dev target with increased memory

- utils/create-yaml.js
- This bug exists for any schema where `resourceFields` is null (like management.cattle.io.roletemplate)
- Before we didn't hit `stringifyField` as `regularFields` was empty for these types, i haven't delved into why it's populated now... but the fix seems safe
- Addresses #2926
> Fix create/edit cluster & project roles

- components/EmberPage.vue
Local UI development (running dashboard and ui on your laptop) is the only time the two UIs are served up by a different process and one might be down while the other is up.
So changing this check to only happen in dashboard dev mode (`yarn run dev`).
For the backend people's local dev they have no copy of the assets, so this currently always fails.
Non-releases (*-head and *-rcX) load the UIs from CDN instead of from the server, so asking the server doesn't tell you much (a version of the assets is available from the server, but not an up-to-date one)..
> Only check for ember availability in dev

- assets/translations/en-us.yaml
- components/nav/Group.vue
- components/nav/Header.vue
- components/nav/TopLevelMenu.vue
- config/settings.js
- pages/about.vue
- pages/c/_cluster/explorer/index.vue
- pages/home/index.vue
- pages/support/index.vue
Port the Ember Version Modal
- Previously this was reached via clicking on the version text in the footer, now it's reached via the user menu top right
- This also previously was a modal whereas now it's a page as per other user menu items
- At the moment it looks pretty stark. As it's a page it lacks the modal header with the snazzy logo 
- There's still the same list of versions, the ui one might be handy for QA
- Addresses #2903
Minor Changes
- i10n - User menu text
- Fix - Vertical size of side menu's group menu down arrow now fills menu hover area (no more thin hover colour below down arrow when in dark mode) 
vs 
- Fix - Cluster Dashboard - Hide metrics Tabbed element if there are no Tabs (no more empty faded square at bottom when no metrics)
- Update support links
- Home Page - …
> Port Ember Version Modal & Minor Changes

- assets/translations/en-us.yaml
- chart/monitoring/ClusterSelector.vue
- chart/monitoring/index.vue
> [2.6] Adding a prometheusOperator hostNetwork option to chart installation

- assets/translations/en-us.yaml
#2914 
Git was unable to find a difference between existing character and new character.
Changed wording instead to circumvent issue
> yaml apostrophe change

- assets/styles/global/_button.scss
- assets/translations/en-us.yaml
- chart/monitoring/index.vue
- components/Banner.vue
- components/ButtonGroup.vue
- components/ChartReadme.vue
- components/CruResourceFooter.vue
- components/Loading.vue
- components/Markdown.vue
- components/ResourceCancelModal.vue
- components/SimpleBox.vue
- components/Wizard.vue
- components/YamlEditor.vue
- components/formatter/Date.vue
- components/nav/GlobalLoading.vue
- components/nav/WindowManager/ChartReadme.vue
- components/nav/WindowManager/Window.vue
- config/query-params.js
- models/chart.js
- pages/c/_cluster/apps/chart.vue
- pages/c/_cluster/apps/chart_mixin.js
- pages/c/_cluster/apps/charts.vue
- pages/c/_cluster/apps/install.vue
- pages/c/_cluster/explorer/tools.vue
- utils/install-redirect.js
- Replaces old edit/install page, which is split out in to Chart Details page and Chart Install page
- Two pages share common mixin
- Updated existing Wizard component for stepper
- Wizard header greatly updated
- Step indicator no longer uses query param
- To Review
- ~~Still not sure i've got the step names and descriptions correct~~
- ~~The side stepper slide isn't quite right~~
Addresses both of #2669 and #2670 (contains https://github.com/rancher/dashboard/pull/2710)
Other bits
- Cancel modal used when cancelling editing yaml tab in a CruResource has been broken out into it's own component and used in stepper
- ~~Tweaked loading component to (conceptually) handle living in a relative element (by not applying offset)~~
- Updated Date component to optionally show just date and no time …
> Add Helm Chart Install Stepper

- assets/styles/themes/_dark.scss
- assets/styles/themes/_light.scss
- assets/styles/vendor/vue-js-modal.scss
Improved mainly for light mode, but slightly tweaked for dark mode to make it look less washed out around the modal dialogs.
Was:
Now:
> Improve modal dialog border and box shadow

- assets/translations/en-us.yaml
- button to remove workload container was missing due to a misplaced translation (not sure why i10n string wasn't shown)
- text for `general` was also missing
- these were both fine at one point
- addresses #2983
> Workload: Fix missing `Remove Container` button & incorrect `general` Tab name

- assets/styles/themes/_light.scss
- assets/styles/themes/_suse.scss
- components/nav/TopLevelMenu.vue
This PR changes back the dropdown colors to what they were before the SUSE theme changes.
It also fixes a bug in the top level menu where it does not close it you select the currently active page for global or configuration apps.
> Drop down menu color changes

- config/product/monitoring.js
- edit/monitoring.coreos.com.receiver/index.vue
- edit/monitoring.coreos.com.route.vue
- mixins/create-edit-view/impl.js
- models/monitoring.coreos.com.podmonitor.js
- models/monitoring.coreos.com.receiver.js
- models/monitoring.coreos.com.route.js
- models/monitoring.coreos.com.servicemonitor.js
- pages/c/_cluster/monitoring/monitor/_id.vue
- pages/c/_cluster/monitoring/monitor/create.vue
- pages/c/_cluster/monitoring/monitor/index.vue
- pages/c/_cluster/monitoring/route-receiver/_id.vue
- pages/c/_cluster/monitoring/route-receiver/create.vue
- pages/c/_cluster/monitoring/route-receiver/index.vue
#2510 - I didn't implement this very completely previously; I added list views but didn't fix the create/detail pages to properly exist on that route and navigate back to it after save or cancel. This pr moves route, receiver, pod monitor, and service monitor creation/viewing under their list view route.
> fix monitoring route/receiver and pod/service monitor routing 

- detail/node.vue
- list/node.vue
- mixins/metric-poller.js
- pages/c/_cluster/explorer/index.vue
- match fix that had been applied to cluster home page
- move out common Poll code into mixin
- note - in cluster home page poll was being stopped via beforeRouteLeave, whereas others were in beforeDestroy. I've tested this in both modes and it still works ok
- addresses #2984
> Fix refresh on node detail and list pages with SSR enabled

- components/form/Command.vue
- edit/workload/index.vue
- pages/c/_cluster/apps/charts.vue
- Fix refresh with SSR switched on
- Fix issue where entering text in the General tab's Command fields loses focus
- This was interesting to hunt down
- Revolved around the change to `container` re-rendering the Tab component due to it's key 'changing'
- This issue isn't helped by the jumble of workload and container fields in the same context (covered by #2683)
- Now uses containers name, which cannot change and is unique to the namespace
- Addresses #2723
> Workloads: Fix two minor form issues 

- edit/configmap.vue
- edit/logging.banzaicloud.io.output/index.vue
- edit/management.cattle.io.project.vue
- edit/namespace.vue
- edit/networking.k8s.io.ingress/index.vue
- edit/secret/index.vue
- edit/workload/index.vue
- Use simpler :label-key instead of :label
- Actual issue was that..
- some components used Vue.prototype.t ... which did the escaping of some characters like `&`
- others used `...mapGetters({ t: 'i18n/t' })` ... which didn't do the escaping and looked fine
- Guessing this might have been caused by a change in CreateEditView
- Addresses #2943
> Fix `Labels &amp Annotations` tab label

- components/SortableTable/THead.vue
- components/SortableTable/index.vue
- Hover state is overridden
- Select all checkbox in header is disabled
- Applies to tables where there are no rows at all or when they're all filtered out
- addresses #2946
> Ensure table row hover and 'select all' rows respect empty table scenarios

- assets/translations/en-us.yaml
- edit/auth/github.vue
- pages/c/_cluster/auth/config/index.vue
#2655 
#2654 - This PR includes changes for the first and third issue described in the comment here; neither Anupama nor I were able to reproduce the second issue:
> While we enable the auth provider, the following note is displayed for the users with "currently logged in as" empty which should be user ID of the admin.
> github style, detailed authz message

- components/nav/Group.vue
Removes debug json shown for overview groups:
> Remove debug json in side navigation

- assets/translations/en-us.yaml
- components/InfoBox.vue
- components/auth/Principal.vue
- components/auth/login/oidc.vue
- config/product/auth.js
- docs/developer/auth-providers.md
- edit/auth/oidc.vue
- mixins/auth-config.js
- models/management.cattle.io.authconfig.js
- pages/account/index.vue
- pages/auth/verify.vue
- pages/c/_cluster/auth/config/index.vue
- plugins/steve/actions.js
- plugins/steve/resource-instance.js
- store/auth.js
- utils/auth.js
- utils/error.js
- Much of the grunt work is generic OIDC
- ~~https://github.com/rancher/rancher/pull/31572 needs to merge, otherwise visiting auth providers page will error~~ only an issue the other way around (other PR merges before this one)
Also fixed
- store's principalId was not updated after user enables any auth provider
- Colour of InfoBox title in dark mode
- Issue where some kind of errors when enabling provider were shown as an empty box (exceptionToErrorsArray is now used, which also uses a better catch all stringify)
- An issue where enabling and disabling a provider in the same visit meant lost defaults
- An issue where Auth / Groups would not display (async part had been removed)
- Resource instance validation would show all fields as invalid once one field had failed
> Add Keycloak OIDC provider

- assets/styles/themes/_light.scss
- components/nav/WindowManager/ContainerShell.vue
#2360 
Minor style changes to bring the `wm.connection` status into view
> kubectl shell connection status update

- detail/workload/index.vue
- models/management.cattle.io.project.js
- plugins/steve/resource-instance.js
- We were using the id which had the namespace as a prefix so I switched to shortId
- The metrics currently only have data for 4 of the types so I'm only showing the tab for those 4
https://github.com/rancher/dashboard/issues/2678#issuecomment-841499076
> Correcting the workload metrics

- assets/translations/en-us.yaml
- config/settings.js
- For `ui-offline-preferred` usage see
- https://github.com/rancher/rancher/blob/692a9507ebeec70118aa8496999e89d0dfa1cc18/pkg/ui/handler.go#L34
- https://github.com/rancher/steve/blob/0a9ab631701fef3d3d7a839253902d896fe018ff/pkg/ui/handler.go#L118
- From what I can determine `ui-offline-preferred` settings are
- 'dynamic'
- If server version is not head use LOCAL
- else if remote available use REMOTE <-- doesn't seem to fail over if assets aren't available
- otherwise LOCAL
- 'true'
- LOCAL
- 'false'
- REMOTE
> Add `ui-dashboard-index` and `ui-offline-preferred` settings

- mixins/brand.js
#3088 - use the `prefs/theme` getter rather than generic `mapPref` getter to check prefers-color-scheme for a theme (https://github.com/rancher/dashboard/blob/master/store/prefs.js#L166)
> fix auto-theme in brand mixin

- models/namespace.js
- pages/c/_cluster/_product/projectsnamespaces.vue
This was being caused because we were failing to retrieve the namespaces's project (projectId) in downstream clusters.
- The projectId only comes back on the annotation in downstream clusters whereas it comes back as both a label
and annotation in the local cluster. This now retrieves the id from the appropriate location and formats it to be
consistent with the existing usage.
- I also noticed that in the local cluster we werent filtering namesapces that are generated by the backend when creating new clusters and projects in downstream clusters. These were prefixed with 'c-' and 'p-' so we filter them as long as they're a system namespace
https://github.com/rancher/dashboard/issues/2500#issuecomment-848267026
> Fixing a grouping and filtering issue for projects/namespaces in downstream clusters

- components/nav/Header.vue
- components/nav/TopLevelMenu.vue
This PR:
- Changes the color of the home icon in the slide-in to match the link color used elsewhere
- Changes the position of the logo in the header to match the position of the logo in the slide-in menu
> Minor visual tweaks to top menu/header

- components/InfoBox.vue
- components/auth/login/ldap.vue
- mixins/auth-config.js
- pages/auth/login.vue
#2654 - refresh principal information when an auth provider is enabled/disabled
#2655 - lighten step number text color
#2949 - hide ldap username/password inputs when local inputs are shown, and vice versa
> reload principal when auth provider enabled/disabled

- mixins/auth-config.js
- When enabling oidc the principal tagged with me should be added to the providers `allowedPrincipalIds` collection
- This wasn't happenening due to a code change (`me` --> `principal`)
> Fix association of 'me' principal to OIDC provider

- pages/c/_cluster/apps/install.vue
- when the window was super wide the slide in would sneak in from the right
- slide-in is now a more sensible width
> Fix issue where sneaky slide-in would show in install chart wizard

- assets/translations/en-us.yaml
- pages/support/index.vue
A couple of minor fixes to the support page:
- Fix type 'effects' -> 'affects'
- Add label to the subscription ID dialog
- Auto-focus the input box in the modal
> Minor fixes to the support page

- assets/translations/en-us.yaml
- chart/monitoring/index.vue
- chart/monitoring/steps/uninstall-v1.vue
- components/IconMessage.vue
- components/Wizard.vue
- pages/c/_cluster/apps/install.vue
- pages/c/_cluster/monitoring/index.vue
- store/catalog.js
- utils/dynamic-importer.js
- utils/monitoring.js
- Add ability to dynamically include additional steps when installing charts
- Works in a similar way to custom values components (discoverable via component files)
- Step component will report if it's loaded and if it's hidden
- Add dynamic step to v2 monitoring that is shown if v1 monitoring is installed
- User is able to uninstall v1 from step
- step blocks wizard until uninstall occurs
> Add dynamic 'Uninstall V1' step to Monitoring V2 wizard

- mixins/auth-config.js
- url part of `management/find` was incorrect
- url was never used as we normally have the resource, however there's some kind of log in bug #3160 where settings are missing, including server-url
- so server-url was never fetched... dodgy url threw exception... model was never fetched
- we don't have a pattern for $fetchState.error anywhere, which we could use here when fetch failed instead of continuing
- addresses #3137
> Ensure we fetch `server-url` in auth-config correctly

- assets/styles/global/_button.scss
- assets/translations/en-us.yaml
- components/nav/TopLevelMenu.vue
Fixes height of cluster options to be consistent with other options - they are all 32px high - this fixes issue with extra spacing at bottom of cluster list.
Changes text for pref for cluster size to say 'side menu' rather than 'top menu'.
Reverted change to role-tertiary which caused issues on the home page
> Address minor issues in side menu

- assets/translations/en-us.yaml
- components/ResourceDetail/Masthead.vue
- components/Wizard.vue
- components/form/NameNsDescription.vue
- pages/c/_cluster/apps/charts/install.vue
- store/prefs.js
- Step descriptions are now info banners
- Added guide to creating new ns in description
- Added and used vertical layout to NameNSDescription component
- Changed 'new ns' message to banner and moved to bottom (to discuss)
- addresses #3060
Also
- Brought back margin/padding bottom sizing. This was important for pages with no detailtop or banner
- Fixed an issue where getLoginRoute would fail where there was no recognised route
> Update helm chart install step 1

- assets/translations/en-us.yaml
- components/form/MatchExpressions.vue
Switched to:
- is set
- is not set
- in list
- not in list
rancher/dashboard#2449
> Making node selector operators more consistent with ember

- models/management.cattle.io.cluster.js
@nwmac The root cause of the referenced issue is that the `management.cattle.io.cluster` resource doesn't have `driver` on it so we are hitting the edit route for the import provider on the ember side. In dashboard I tested a few different clusters and found none of the resources had a `driver` property so I am not sure we'd ever actually fall into the branch on line 100? I tested editing a new v2 cluster, rke2 clusters, and rke1 clusters and did not find any issues with the redirect after this change. Let me know if you'd like me to remove the lines above my change. 
rancher/dashboard#3006
> Cluster Edit Redirect Bug

- pages/support/index.vue
Small fix - this PR clears the support key in the add dialog - on the support page, if you add key then remove, then click to add again, you see the pervious key. We now clear the key before showing the add dialog.
> Clear the support key in the add dialog

- assets/styles/global/_button.scss
- pages/c/_cluster/explorer/tools/index.vue
Prevents installation of V1 tools when v2 installed
Also fixes sizing of the smaller buttons on the cards
> Cluster Tools: Don't allow v1 to be installed when v2 is already installed

- assets/translations/en-us.yaml
- cloud-credential/azure.vue
- edit/provisioning.cattle.io.cluster/SelectCredential.vue
- machine-config/azure.vue
- store/plugins.js
The PR adds the Azure provider cloud credential and RKE2 Cluster/Node Provisioning using the cloud credentials.
For node provisioning I've left out a few things from the Ember UI that I think go against the more hands off approach the new UI takes. 
Public IP options is no longer a dropdown with 3 arbitrary dropdown options that don't translate into what the actual fields on the resource, instead we expose the public IP options.
Environments is a static list because there is no API available to fetch this data. In the Ember UI we kept a static list of locations available in each Environment. Here rather than try to maintain a static list of Environs/Locations we're fetching the locations dynamically (probably more likely to change then new environs) and keeping a static list of environs. …
> Azure cloud credentials and RKE2 Cluster Provisioning

- components/EmberPage.vue
This PR updates the iframe embedding such that we will not reuse an existing iframe if the last page load failed.
This hardens the UI against issues where an embedded page does not load - currently, this causes future page loads to fail.
> Don't reuse embedded iframe if last page load did not complete

- components/ResourceDetail/Masthead.vue
- components/SortableTable/index.vue
- components/SortableTable/selection.js
- components/nav/TopLevelMenu.vue
- detail/cis.cattle.io.clusterscan.vue
- models/provisioning.cattle.io.cluster.js
- plugins/steve/resource-instance.js
- for resources in error or transitioning states show the associated message
- message is shown in resource detail masthead (in place of current messages)
- message is also shown in lists as text under affected row
Used predominantly in cluster lists where a cluster is transitioning (provisioning cluster uses management cluster message). I've tested with single use of sub-row feature used in CIS scans.
Also fixed indentation of unconnected clusters in side nav
addresses #3111
> Show error/transition description in resource lists and resource detail

- assets/translations/en-us.yaml
- pages/auth/login.vue
Addresses #2949 
Updates the login screen when a provider has been configured to make the choice between local and provider login similar to what we did in the Ember UI.
> Login: Tweak the switch between a provider and local user login

- components/nav/Group.vue
- config/product/explorer.js
- store/type-map.js
Addresses #3191 
This PR provides a mechanism to change the default type that is selected when you expand a group that does not have an overview. The default is to select the first child type - you can now configure which child should be selected.
'Service Discovery' is updated to select 'Services' rather than the first child 'Horizontal Pod Autoscalers'
> Navigation: Allow default child for a group to be configured

- components/nav/WindowManager/ContainerShell.vue
- components/nav/WindowManager/KubectlShell.vue
I don't have any windows clusters to test this on, I used similar logic from the Ember side and made the assumption that the command would also be the same. Let me know if it needs to change. 
rancher/dashboard#3157
> change shell command for windows clusters

- components/EmberPage.vue
This PR fixes a minor bug where navigating in an embedded page to the dashboard via a link and then going back to the same embedded page results in the page being stuck on loading.
> Ember Embedding: Fix issue with page not showing

- assets/translations/en-us.yaml
- pages/auth/login.vue
- store/auth.js
- Beef up error message
- Previosuly just showed 'client' or 'server', now show existing error message and one specificaly for 401's
- Clear out loggedOut & timedOut messages on log in attempt (so text doesn't flash up when attempting to log in after a failed attempt)
- Avoid vertical bobble of content when error message is shown/hidden
- Ensure 'log in' button doesn't report success to avoid confusing 'Logged In' and, if login takes a while, 'Log in with Local User' button text (on login success we're changing page with a page 'loading' overlay)
> Login Page Tweaks

- pages/auth/login.vue
- pages/auth/verify.vue
- plugins/steve/mutations.js
- ~~Blocked on #3221~~
- Fix issue where searching the second time for principals resulted in missing principal resource names
- 1st call to v3/principals?action=search --> rancher/loadMulti - new principals for store, new proxy objects
- 2nd call to v3/principals?action=search --> rancher/loadMulti - existing principals in store, load updates object by deleting all existing props (like _name) and applying new (that didn't contain _name)
-  Handle errors when verifying auth
- seen as part of #3234 (does not solve entirely, backend changes needed)
> Fix two OIDC issues - second princpal search and better handle failed verify auth

- assets/translations/en-us.yaml
- components/form/Select.vue
- pages/c/_cluster/apps/charts/index.vue
- store/catalog.js
- Change title from `Deploy Chart` to `Charts`
- Avoid using rancher and partner repo colours for non rancher/partner repos (visible on 4th and 5th repos)
- Repeat colours when number of repo's exceed 6
- Fix issue where repo colour 5 had the wrong dot colour
- When all repos are selected, show 'All'. When none are selected show 'None'
- Fix height of repo drop down
- When searching charts search by chart display name rather than chart id-ish name
- addresses some of the points raised in #2668
Note - For test repos see those listed in https://artifacthub.io/packages/search?kind=0&page=1 (click on a chart and the repo is normally listed in the `helm repo add` command)
> Charts Page Tweaks/Fixes

- edit/workload/VolumeClaimTemplate.vue
The <Mount> component wasn't passed the container required field which was causing it to fail to render.
rancher/dashboard#3171
> Fixing workload volumeClaimTemplates

- components/ResourceYaml.vue
Address #3196
To reproduce
1) Nav to a DaemonSet's `Edit Yaml` page (ensure that the `annotations` section is initially collapsed)
2) Edit any of the yaml (for instance add a new property at the top)
3) Try to expand the `annotations` section, which fails and section remains collapsed
Under the hood
- ResourceYaml component automatically (ish) collapsed status, annotations, managedFields resource sections when codemirror emits 'onReady'
- the 'onReady' event emits in many different scenarios, like edit
- repeatedly handling the onReady event meant codemirror's `foldCode` called often on the same lines
- this somehow broke how folded lines are tracked. as far as i can tell it's something to do with tracking gutter state and marked lines
  - if no edits are made collapsing and uncollapsing …
> Fix issue where editing resource yaml resulted in un-expandable sections

- chart/rancher-backup/index.vue
- Ensure that when we load the form component the storage class type from existing value is respected
- This fixes the situation when switching between form and yaml and the selection is lost
- Don't attempt to use the default storage class if we don't have it
- This fixes a issue where the yaml became invalid after selecting storage class as the type
Addresses #3215
> Fix two rancher backup form bugs

- edit/management.cattle.io.project.vue
- models/management.cattle.io.project.js
- pages/c/_cluster/_product/projectsnamespaces.vue
The management projects weren't consistently being updated when modifying norman projects. Now when
saving or removing norman projects we refresh the management projects to make sure the list is up to date.
I also moved accessing the norman project into the project model to clean up some of the mess in the project component.
https://github.com/rancher/dashboard/issues/3175
> Simplified project norman acccess and now refresh management projects when modifying norman projects

- components/nav/Group.vue
- layouts/default.vue
This PR fixes an issue where the side-nav does not auto expand the top-level item when a child's child is active - this is most notable on a page reload.
A good example if the Legacy nav item - go to the project item within it, choose a project and you will be on Project Apps - refresh the window and the nav will not auto-expand to show you the active nav item.
This PR also fixes the color of the 2nd level nav headers, so that they are the same as the rest of the nav rather tyhan --input-label
> Ensure top-level navigation is expanded if a child is active

- assets/translations/en-us.yaml
- components/ConsumptionGauge.vue
- models/management.cattle.io.cluster.js
- pages/c/_cluster/explorer/index.vue
- pages/home.vue
- utils/units.js
#2795 - this PR updates the home page so that when multi-cluster management is disabled, rather than a table of clusters (with 1 row) the page shows a brief cluster summary similar to the cluster dashboard view:
> Single-Cluster home page tweak

- config/features.js
- models/management.cattle.io.feature.js
#3312 - MCM can be enabled from the UI, but can only be set to false during installation. Similarly, token hashing cannot be disabled once enabled. This PR removes the 'deactivate' action for both feature flags.
> hide disable action for one-way feature flags

- store/auth.js
- store/index.js
- store/prefs.js
#3282 - This is happening because the `prefs` store data isn't re-loaded when the user changes. Dispatching `prefs/loadServer` on login should ensure the correct user's preferences are available before the index page redirects based off `afterLoginRoute`.
> re-load user prefs on login

- assets/translations/en-us.yaml
These strings got lost somehow - adding them back - otherwise the dialog to enable/disable a feature flag does not show a message.
> Add back in missing feature flag prompt translations

- models/provisioning.cattle.io.cluster.js
https://github.com/rancher/dashboard/issues/3080#issuecomment-866823823 - small change here; looks like the `enabled` check for rotate certs and rotate encryption key got swapped.
> fix visibility of rotate certs and rotate encryption key actions

- edit/workload/storage/Mount.vue
- edit/workload/storage/hostPath.vue
- edit/workload/storage/index.vue
- edit/workload/storage/nfs.vue
- edit/workload/storage/persistentVolumeClaim/index.vue
- edit/workload/storage/secret.vue
#3313 In addition to the two problems outlined in this ticket, I noticed the Mount components weren't updating correctly when multiple volumes are defined and one is removed. Addressed by these changes:
- track subset of volumes mounted in current container in data + watcher instead of a computed prop
- remove outdated call to `updateMountNames` when a volume name changes (this is handled within the Mount component)
- add a key to Mount components to force updating when a volume is removed
> fix volume re-name

- assets/translations/en-us.yaml
- components/EmberPage.vue
- components/Tabbed/index.vue
- components/nav/Group.vue
- components/nav/TopLevelMenu.vue
- components/nav/Type.vue
- config/product/legacy.js
- pages/c/_cluster/explorer/tools/index.vue
- pages/c/_cluster/legacy/pipelines.vue
- pages/c/_cluster/legacy/project/_page.vue
This PR:
- Embeds the remaining pages that we originally planned to leave in Cluster Manager
- CIS Scans, Istio, Pipelines and Pipeline configuration are now available under Legacy
- Removes the link to Cluster Manager in the slide-in menu
- Fixes some styling issues with the 2nd-level navigation
> Remove Cluster Manager

- assets/translations/en-us.yaml
- components/ResourceTable.vue
- components/SortableTable/index.vue
- config/labels-annotations.js
- detail/provisioning.cattle.io.cluster.vue
- list/node.vue
- models/cluster.x-k8s.io.machine.js
- models/cluster.x-k8s.io.machinedeployment.js
- models/cluster/node.js
- models/management.cattle.io.node.js
- models/management.cattle.io.nodepool.js
- models/provisioning.cattle.io.cluster.js
- models/rke-machine.cattle.io.amazonec2machinetemplate.js
- models/rke-machine.cattle.io.azuremachinetemplate.js
- models/rke-machine.cattle.io.digitaloceanmachinetemplate.js
- models/rke-machine.cattle.io.linodemachinetemplate.js
- models/rke-machine.cattle.io.vmwarevspheremachinetemplate.js
- Add a Node list grouped by Node Pools
- Both Node/Node Pools are of type 'management'
- For pools...
- Show node count next to pool label
- Show description of pool underneath pool label
- Show convenience scale down/up buttons (normally scale by cluster config)
- Show node pool action menu
- For nodes
- Link to kube node
- Show node role/s
- Update Machine/Machine Pool List
- For pools
- Like Node Pools add a description of machine pool underneath label
- Like Node Pools Show convenience scale down/up buttons (normally scale by cluster config)
- For machines
- Like Nodes link to kube node
- Like Nodes show node machine role/s
- Add resource descriptions (shown on lists) for machine, machine deployment and machine set
- Addresses #3291
- Includes #3016, #493
> Update Cluster Manager Node/Machine Lists

- components/FixedBanner.vue
- pages/c/_cluster/settings/brand.vue
Updates the banner parsers to handle a new `ui-banners` data structure to enable setting header and footer banners separately. The old structure used a single banner param to hold the text, text-color, and background-color for both header and footer banners. Updated the logic to handle a new blob with separate `bannerHeader` and `bannerFooter` params. If the user has an existing, and now legacy, `ui-banners` settings, I migrate it to the new structure when they land on the brand settings page populating the header and footer objects with the content of the current `banner` object. I know we typically do not like to change a users setting without notifying them but in this case it feels okay since I am migrating the old content to a new structure the end result for the user is the same if …
> ui-banners enhancements

- assets/translations/en-us.yaml
- config/product/manager.js
- list/provisioning.cattle.io.cluster.vue
- models/management.cattle.io.nodepool.js
- models/provisioning.cattle.io.cluster.js
- counts are shown (ready, pending,etc) are already shown for RKE2 machines
- show restricted set of counts for RKE1 nodes
- show basic total node count for non-RKE clusters
- #3028
- ![image](https://user-images.githubusercontent.com/18697775/123821820-a281cc00-d8f3-11eb-8bce-b5289ba2b2c8.png)
> Show Node counts in Cluster Management's cluster list

- edit/provisioning.cattle.io.cluster/index.vue
When on the cluster creation page and with the toggle set to RKE1, selecting a cluster type will load the embedded IFRAME for that type. Hitting refresh will always load the RKE2 create view, not the RKE1 view.
This PR fixes this bug.
> Cluster create: Fix issue with refresh always going to RKE2 create

- assets/translations/en-us.yaml
- components/Wizard.vue
- pages/c/_cluster/apps/charts/install.vue
- Only show if there are multiple versions associated with the chart
- #3285
Also
- Improved generic step 2 text to be more fitting for clusters (instead of apps)
For whoever reviews steps to reproduce ..
1. Nav to Local cluster --> Apps & Marketplace --> Chart Repo and add a repo of type `git` `https://github.com/slickwarren/cluster-template-examples` branch `v2charts-template`
2. Nav to Cluster Manager --> Create
3. Select `qa-v2charts-template` for a chart with multiple versions, any other for single version
> Add Version step when installing a cluster from a template

- assets/translations/en-us.yaml
- chart/monitoring/index.vue
- chart/monitoring/steps/uninstall-v1.vue
- components/PromptRemove.vue
- components/Wizard.vue
- components/dialog/GenericPrompt.vue
- Use a new generic prompt (displays customisable text and provides action to execute)
- Also fixed an issue where previous button was shown after uninstalling v1
- ~blocked on #3364 (heavily tested with those changes)~
- Addresses blocking issues in #2967
> Warn before uninstall v1 monitoring when installing v2 monitoring

- models/management.cattle.io.cluster.js
- models/provisioning.cattle.io.cluster.js
aks, eks, and gke v2 providers do not have a machine provider so lets drop it from the details.
@vincent99 I was not 100% sure about adding this to the management model. If I understand correctly the management cluster is always going to be the local cluster but I wasn't sure if that could also be one of these clusters? I added the check to the details to be on the safe side, I can remove it if its not needed. 
rancher/dashboard#2985
> remove machine provider detail header for v2 cloud provider

- pages/c/_cluster/mcapps/index.vue
https://github.com/rancherlabs/rancher-security/issues/828 - restricted admins don't have access to the local cluster and thus can't access routes nested beneath it.
> do not force mcapps under local cluster

- components/RelatedResources.vue
Before:
After:
Issue: https://github.com/rancher/dashboard/issues/3388
> Add missing namespace to related resources list

- detail/provisioning.cattle.io.cluster.vue
Before:
After:
Other cluster options also still work correctly with this change.
Imported:
Custom RKE1:
RKE2 with node driver:
Issue: https://github.com/rancher/dashboard/issues/3393
> Fix missing nodes on Cluster detail page for RKE2 custom clusters

- detail/provisioning.cattle.io.cluster.vue
- models/provisioning.cattle.io.cluster.js
When you import an existing cluster, you are redirected to the cluster detail page in the 2nd step. Due to a race condition, this page often does not show the registration tab with the kubectl apply command.
Debugging showed, that the problem is, that `provisioner` (https://github.com/rancher/dashboard/blob/master/models/provisioning.cattle.io.cluster.js#L142-L157) is not set, because `mgmt` is not set yet.
Because of that `isImported` is set to `false` https://github.com/rancher/dashboard/blob/master/models/provisioning.cattle.io.cluster.js#L92-L94.
Waiting at the beginning of `fetch` for provisioner to be set, fixes the issue for me. If there is a better way to handle this, I'm happy to change it.
Issue: https://github.com/rancher/dashboard/issues/3398
> Fix race condition when showing the registration tab while importing a new cluster

- assets/translations/en-us.yaml
- list/node.vue
- Make type node seen in explorer / node list clearer
- change resource label
- add a resource description  (also mention where lifecycle management can be done)
- Remove node pool groups for rke1, so there are no pools at all in this view
- Also addresses #3355
> Changes to kube node list

- assets/translations/en-us.yaml
- middleware/authenticated.js
- pages/auth/login.vue
- store/auth.js
#3408 - this pr clarifies the message shown when the UI can't login on initial setup using `admin/admin`. I also tweaked the logic around that message so it isn't dependent on a query string; the message is relevant any time a user is on this page and `first-login` is true, and I don't think presenting it as an error is accurate if this (random passwords) is expected behavior going forward.
> update default admin password message for initial setup

- pages/auth/verify.vue
- store/auth.js
Change one - `pages/auth/verify.vue`
- When configuring an auth provider we prompt user for creds
- Once user has successfully authed with keycloak it redirects back to our `veritfy-auth` page
- Here normally we're all good and we extract the `code` and close the popup
- However keycloak can error, with for instance `Invalid scopes: profile,email`, which were previously ignored and sent back an undefined code
- Now we handle errors (these may be in a different format for other providers) and no auth codes
- This was the cause for the generic error in #3406, which hid the actual error
Change two  - `store/auth.js`
- Actual fix for #3406 
- Updated keycloak scopes which were treated differently in newer versions (fix also works with older keycloak versions)
- Note - requires changes from …
> Pass through errors received from keycloak redirect when configuring auth provider

- assets/translations/en-us.yaml
- pages/c/_cluster/apps/charts/install.vue
- The description was previously part of the common NameNSDescription field, implying it applied to the application
- Given discussion in #3038 the description is only linked to the execution of the helm command and could change every run through
- So moving field into the helm command section
> Move Helm Chart Install 'description' field into more fitting cmd options section

- components/CodeMirror.vue
- components/Import.vue
- components/YamlEditor.vue
- components/form/FileSelector.vue
Addresses #3307 
This PR addresses the issue above and a couple of others with the import yaml dialog:
- You can now reselect a file (we clear the previous file name before opening)
- Added margin between the cancel and import buttons
- Fixes issue where YAML is now shown when a file is selected
- Clear errors when a new file is selected
> Fix issues with import yaml

- assets/translations/en-us.yaml
- components/CommunityLinks.vue
- components/nav/TopLevelMenu.vue
- config/footer.js
- pages/home.vue
- pages/support/index.vue
This pr addresses remaining issues in #3029 with the exception of the 'Get Support' link visibility; there are conflicting requirements in https://github.com/rancher/dashboard/issues/2895. As per discussion with @nwmac this PR hides the support link for non-admins regardless of subscription status, and changes the label from 'Get Support' to 'Support' when a subscription key has been added. We've opted not to hide the link entirely in supported mode because the page still has utility. Other issues from #3029 :
> The Community Support Box in the Dashboard Home is visible always even if we uncheck the Show Rancher community support links in Branding (See screenshot)
This should work correctly now, *but* if a custom issue-reporting url has been provided, it will be shown in the box …
> ui branding issues

- components/form/Members/MembershipEditor.vue
- config/labels-annotations.js
- models/management.cattle.io.clusterroletemplatebinding.js
- models/management.cattle.io.projectroletemplatebinding.js
Turns out `authz.management.cattle.io/creator-owner-binding` is more a reflection on the current state of something rather than the origin of something.
rancher/dashboard#3296
rancher/dashboard#3413
> Updating how we check if a cluster/projectRoleTemplateBinding isSystem

- components/ResourceDetail/index.vue
- components/nav/Header.vue
- edit/provisioning.cattle.io.cluster/index.vue
- edit/provisioning.cattle.io.cluster/rke2.vue
- pages/home.vue
- store/index.js
- Working on top of changes in #3440
- Still need to 
- check places where we assume 'local' cluster, including in routes,
- ~~where we should use the new blank cluster~~
- ~~pages/components that assume we have a currentCluster~~
Currently tracked issues when creating a cluster as standard user with no clusters (using latest dev build)
- `provisioning.cattle.io.cluster` isn't in the response to `v1/schemas` (but is reachable by `v1/schemas/provisioning.cattle.io.cluster`)
- `v1/provisioning.cattle.io.cluster` GET gives a 403 error. causes issues with our breadcrumbs
- `v1/secret` GET gives a 403 error. causes issues when create a rke2 cluster ('custom' option)
- `catalog.cattle.io.clusterrepos` schema/resources 404, so cannot fetch charts to use when deploying via cluster template. …
> Fix issues when creating clusters as non-admin

- store/index.js
#3352 The [namespace filtering performed in getTree](https://github.com/rancher/dashboard/blob/master/store/type-map.js#L508) was using all namespaces when Apps & Marketplace was selected because [isAllNamespaces](https://github.com/rancher/dashboard/blob/master/store/index.js#L145) returns true when `showNamespaceFilter` is false for the current product (the default)
> make apps marketplace product account for ns filter in header

- edit/provisioning.cattle.io.cluster/SelectCredential.vue
- edit/provisioning.cattle.io.cluster/rke2.vue
- This will help the backend team to continue permissions work in the create cluster flow
- For some resources, like secrets and clusters, users may not end up having access to the schema or collection `get` if they haven't yet created a resource of that type
- Applies to users and restricted-admins who aren't a member of any cluster
- These changes safeguard against these scenarios and match how things worked in ember (ish)
- Safeguard fetch of secrets in SelectCredential component
- Remove unused fetch of secrets in RKE2 create cluster flow
> Handle situations in create cluster flow where user cannot fetch `secrets`

- assets/translations/en-us.yaml
- components/CruResource.vue
- components/form/Members/MembershipEditor.vue
- components/nav/WindowManager/ContainerShell.vue
- components/nav/WindowManager/KubectlShell.vue
- detail/provisioning.cattle.io.cluster.vue
- edit/provisioning.cattle.io.cluster/CustomCommand.vue
- edit/provisioning.cattle.io.cluster/index.vue
- edit/provisioning.cattle.io.cluster/rke2.vue
- mixins/create-edit-view/impl.js
- models/provisioning.cattle.io.cluster.js
- Show Machines instead of Pools for custom
- Fix cluster PSP selection
- Disable some actions on unready clusters (#3490)
- RKE1 custom command (#3145)
- Fix shell when nodes aren't readable (#3498)
- Use ember for imported cluster edit (#3015)
- Call save in the right order so members get added
> Cluster bugs

- store/index.js
- store/type-map.js
- see https://github.com/rancher/rancher/pull/33663
- some schema's returned by `v1/schemas` cannot be fetched by collection
- ensure we respect the missing collection link when starting the dashboard
> Fix log in for non-admin users given latest backend schema changes

- components/form/ValueFromResource.vue
#3455 
I also noticed this page exploded on edit if the secret or configmap referenced had no data property.
> fix workload environment variables on edit

- assets/translations/en-us.yaml
- edit/auth/oidc.vue
- see #3516
- ensures that when when keycloak log in is restricted to a group, users of child groups of that group can still log in
- does so by using the supplied service account to fetch groups to work out nesting
Note - This change is unverified but will aid backend team to test real-world scenario. The fields aren't required so leaving them blank will result in same auth config as we currently post.
> Optionally supply 'service' account to keycloak auth config

- edit/logging-flow/Match.vue
#3447 
Simple fix to prevent dropdown from displaying off screen. Change default direction from 'bottom' to 'top'
> Cluster Logging list of containers overflows off visible screen

- README.md
- content/docs/en-us/getting-started.md
- docs/developer/getting-started/development.md
- docs/developer/getting-started/development_environment.md
This corrects a few typos that I encountered while reviewing the docs. This also updates grammar in a few places where possessive nouns were in use when it looked like they were meant to be plural.
> Update grammar and fix typos

- assets/translations/en-us.yaml
- chart/monitoring/prometheus/index.vue
- components/CopyCode.vue
- components/InfoBox.vue
- components/form/ArrayList.vue
- components/form/ArrayListGrouped.vue
- components/form/FileSelector.vue
- components/form/MatchExpressions.vue
- components/form/NodeAffinity.vue
- config/labels-annotations.js
- edit/autoscaling.horizontalpodautoscaler/metric-identifier.vue
- edit/fleet.cattle.io.clustergroup.vue
- edit/persistentvolume/index.vue
- edit/provisioning.cattle.io.cluster/ACE.vue
- edit/provisioning.cattle.io.cluster/RegistryMirrors.vue
- edit/provisioning.cattle.io.cluster/index.vue
- edit/provisioning.cattle.io.cluster/rke2.vue
- pages/auth/login.vue
- pages/c/_cluster/apps/charts/index.vue
- pages/c/_cluster/explorer/tools/index.vue
- Only show charts with catalog.cattle.io/type=cluster-tool as tools (rancher/rancher#33841)
- Mark RKE2 as tech preview
- Call null PSP the RKE2 Default
- Templates available only if feature flag is enabled
- Show CIS Profile only for Custom
- Reorganize tabs and options
- Additional Kubelet Args
> [Master] Kubelet args, reorganize options

- components/form/Command.vue
- Ensure we don't clean out non-command properties from container after saving command (#3379)
- Ensure the container reference isn't broken (fixes change of container image after changing command)
> [2.6] Fix updates to workload container given changes to command

- components/form/Command.vue
- Ensure we don't clean out non-command properties from container after saving command (#3379)
- Ensure the container reference isn't broken (fixes change of container image after changing command)
> [master] Fix updates to workload container given changes to command

- components/BrandImage.vue
- mixins/brand.js
- Partial settings are loaded before logging in via the `_ALL_IF_AUTHED` flag
- Any other attempt to findAll without flag will result in list marked as `haveAll` with the set of results
- Any attempt afterward that to findAll would just return the partial list and not refetch
- There were a couple of places this happened pre-log in, resulting in partial list of settings after log in
- This was needed to show version info (and to populate settings page)
- #3596
> [2.6] Ensure we don't generically `management/findAll` settings type before logging in

- list/group.principal.vue
- #3496
- The group list component fires off a couple of things when a group is removed (all at top level, not per group)
- This used to work fine piggybacking on `showPromptRemove` but was updated to supported the alt action where no prompt was shown
- So whenever a group is unassigned it updates the list by watching `toRemove`
- This was always triggered on initial load, now we work around this
- Was searching for a better way, but the newVal/oldVal reported same array for both initial load and after removing groups (need to ignore first and work thereafter)
> [2.6] Fix groups list refresh on enter

- list/group.principal.vue
- Port of #3543 to master
- The group list component fires off a couple of things when a group is removed (all at top level, not per group)
- This used to work fine piggybacking on `showPromptRemove` but was updated to supported the alt action where no prompt was shown
- So whenever a group is unassigned it updates the list by watching `toRemove`
- This was always triggered on initial load, now we work around this
- Was searching for a better way, but the newVal/oldVal reported same array for both initial load and after removing groups (need to ignore first and work thereafter)
> [master] Fix groups list refresh on enter

- detail/provisioning.cattle.io.cluster.vue
This disables the snapshot button when the cluster state is not equal to "active". 
#3547
> [master] Disable snapshot button when cluster is not active

- assets/translations/en-us.yaml
This updates some wording regarding registration of Windows nodes in a custom cluster. 
Backport PR #3621 to release-2.6
#3580
> [2.6] Update wording for registering Windows nodes

- edit/provisioning.cattle.io.cluster/rke2.vue
This adds update functionality for machine pools configuration. 
It should be safe to invoke `entry.config.save()` because our HTTP action will be set to PUT when when an id exists on a resource. 
This also adds  an update property to `machinePools`, which can be used this in the future to to conditionally update any given pool only when configuration has changed. For now, this property is always set to `true` when machine pools are initialized and `false` when adding a new machine pool. Checking for the existence of an machine pool id could also work in place of the update property. 
#3553
> [master] Update machine pools when editing RKE2 cluster

- edit/provisioning.cattle.io.cluster/rke2.vue
This adds update functionality for machine pools configuration. 
It should be safe to invoke `entry.config.save()` because our HTTP action will be set to PUT when when an id exists on a resource. 
This also adds  an update property to `machinePools`, which can be used this in the future to to conditionally update any given pool only when configuration has changed. For now, this property is always set to `true` when machine pools are initialized and `false` when adding a new machine pool. Checking for the existence of an machine pool id could also work in place of the update property. 
Backport of PR #3629 into release-2.6
#3553
> [2.6] Update machine pools when editing RKE2 cluster

- cloud-credential/gcp.vue
- edit/provisioning.cattle.io.cluster/rke2.vue
#3093 - this bug only shows up when a user switches from the config view to yaml view, not when navigating there via 'edit as yaml' from the kebab menu....I think it'd be worthwhile to look into the after-save behavior in `CruResource` and `ResourceYaml` and refactor them to be more consistent (and deal with `doneRoute`/`doneOverride` better), but not something we need to do for this release.
> [master]fix rke2 edit done route

- models/management.cattle.io.cluster.js
#3625
`generateKubeConfig()` passed to `doAction()` to hit correct endpoint as opposed to statically hitting /v3/
> [master] Download KubeConfig fails to download when MCM feature flag is disabled

- models/management.cattle.io.cluster.js
#3625 
`generateKubeConfig()` passed to `doAction()` to hit correct endpoint as opposed to statically hitting /v3/
> [2.6] Download KubeConfig fails to download when MCM feature flag is disabled

- edit/provisioning.cattle.io.cluster/CustomCommand.vue
This adds an insecure command to Windows cluster registration by adding a checkbox that updates the code snippet when checked. This is made possible by recent changes on the backend that introduces an insecure Windows command by updating from `iwr` to `curl.exe`.
#3580
> [master] Add insecure command to Windows cluster registration

- edit/provisioning.cattle.io.cluster/CustomCommand.vue
This adds an insecure command to Windows cluster registration by adding a checkbox that updates the code snippet when checked. This is made possible by recent changes on the backend that introduces an insecure Windows command by updating from `iwr` to `curl.exe`.
#3580 
Backports PR #3646 into release-2.6
> [2.6] Add insecure command to Windows cluster registration

- edit/provisioning.cattle.io.cluster/rke2.vue
As of this pr https://github.com/rancher/dashboard/pull/3658, some default rke2 config values are missing, looks like there was a mix-up in these two turnery statements that's setting config values to `undefined` even if a default is found
> fix rke2 defaults

- components/dialog/AddProjectMemberDialog.vue
- components/form/Members/ClusterMembershipEditor.vue
- components/form/Members/ClusterPermissionsEditor.vue
- components/form/Members/MembershipEditor.vue
- components/form/Members/ProjectMembershipEditor.vue
- components/form/ProjectMemberEditor.vue
- config/table-headers.js
- edit/management.cattle.io.projectroletemplatebinding.vue
- models/management.cattle.io.clusterroletemplatebinding.js
- models/management.cattle.io.projectroletemplatebinding.js
- make userPrincipal id/name properties generic in mgnt binding types
- userPrincipalName becomes principalName
- principalId comes from this.principalName || this.userPrincipalName || this.groupPrincipalName
- use principal to determine user/group and properties in norman to save
- removed properties in norman save bindings that weren't needed
- #3643
> [2.6] Fix creation of group cluster and project template bindings

- components/dialog/AddProjectMemberDialog.vue
- components/form/Members/ClusterMembershipEditor.vue
- components/form/Members/ClusterPermissionsEditor.vue
- components/form/Members/MembershipEditor.vue
- components/form/Members/ProjectMembershipEditor.vue
- components/form/ProjectMemberEditor.vue
- config/table-headers.js
- edit/management.cattle.io.projectroletemplatebinding.vue
- models/management.cattle.io.clusterroletemplatebinding.js
- models/management.cattle.io.projectroletemplatebinding.js
- make userPrincipal id/name properties generic in mgnt binding types
- userPrincipalName becomes principalName
- principalId comes from this.principalName || this.userPrincipalName || this.groupPrincipalName
- use principal to determine user/group and properties in norman to save
- removed properties in norman save bindings that weren't needed
- #3643, #3672
> [master] Fix creation of group cluster and project template bindings

- assets/translations/en-us.yaml
- components/EmberPage.vue
- components/form/ToggleSwitch.vue
- Log out from Ember should log out Vue (#3704)
- You should be able to click the labels
> [Master] Ember logout

- assets/translations/en-us.yaml
- components/EmberPage.vue
- components/form/ToggleSwitch.vue
- Log out from Ember should log out Vue (#3704)
- You should be able to click the labels
> [2.6] Ember logout

- components/form/Members/MembershipEditor.vue
- edit/provisioning.cattle.io.cluster/import.vue
- edit/provisioning.cattle.io.cluster/rke2.vue
- models/provisioning.cattle.io.cluster.js
- Previously nav away was occurring inside `this.save` before we could wait for the mgmt cluster
- This meant some info was missing when we arrived at the next page
- So move wait and role change into after hook and rely on native nav in this.save again
This should resolve #3396 and most of #3677
> [2.6] Ensure we wait for required resources before leaving cluster import / create rke2

- components/IndentedPanel.vue
- components/ResourceDetail/index.vue
- components/nav/TopLevelMenu.vue
- config/query-params.js
- edit/provisioning.cattle.io.cluster/import.vue
- edit/provisioning.cattle.io.cluster/index.vue
- edit/provisioning.cattle.io.cluster/rke2.vue
- layouts/plain.vue
- list/management.cattle.io.setting.vue
- list/provisioning.cattle.io.cluster.vue
- mixins/chart.js
- models/chart.js
- models/provisioning.cattle.io.cluster.js
- pages/c/_cluster/apps/charts/install.vue
- pages/c/_cluster/settings/brand.vue
- store/catalog.js
- store/index.js
_This is a fix of #3554 (managed to push master changes to 2.6 branch). Comments have been lost on that PR, but all have either had their code fixed as per first comments or moved to another PR._
Along with recent updates to the backend (https://github.com/rancher/rancher/pull/33791) this fixes all but a few issues in #3416. Remaining...
- Standard User, member of a single non-local cluster - Feature Flags - Action buttons shown with 'no actions available' text
Other RBAC Fixes
- Standard User, member of no clusters
- Fixed multiple bugs when installing a cluster from a template (missing currentCluster, display of helm install stepper, catalog requests `inStore` fixed when there's no cluster)
Other Fixes
- Add error handling to cluster save fn
- Fixed error in console due dispatching old …
> [2.6] Non-admin permissions based errors

- assets/translations/en-us.yaml
- components/Questions/Array.vue
- components/Questions/Boolean.vue
- components/Questions/CloudCredential.vue
- components/Questions/Enum.vue
- components/Questions/Float.vue
- components/Questions/Int.vue
- components/Questions/Map.vue
- components/Questions/Question.js
- components/Questions/Reference.vue
- components/Questions/String.vue
- components/Questions/index.vue
- components/form/ArrayList.vue
- edit/provisioning.cattle.io.cluster/MachinePool.vue
- edit/provisioning.cattle.io.cluster/rke2.vue
- machine-config/amazonec2.vue
- machine-config/azure.vue
- machine-config/digitalocean.vue
- machine-config/generic.vue
- machine-config/harvester.vue
- machine-config/vmwarevsphere.vue
This disables editing for all RKE2 machine pool configs by adding a disabled prop to each machine pool config component and any children fields. A new banner has been added to notify the user that they will need to create a new pool if they wish to edit any config values. 
This also reverts changes introduced by PR #3629, but we keep the update prop as an easy way to determine if any machine configs should be in a disabled state.
#3553
Backports PR #3735 into release-2.6
> [2.6] Disable editing RKE2 machine pool configs after creation

- assets/translations/en-us.yaml
- components/Questions/Array.vue
- components/Questions/Boolean.vue
- components/Questions/CloudCredential.vue
- components/Questions/Enum.vue
- components/Questions/Float.vue
- components/Questions/Int.vue
- components/Questions/Map.vue
- components/Questions/Question.js
- components/Questions/Reference.vue
- components/Questions/String.vue
- components/Questions/index.vue
- components/form/ArrayList.vue
- edit/provisioning.cattle.io.cluster/MachinePool.vue
- edit/provisioning.cattle.io.cluster/rke2.vue
- machine-config/amazonec2.vue
- machine-config/azure.vue
- machine-config/digitalocean.vue
- machine-config/generic.vue
- machine-config/harvester.vue
- machine-config/vmwarevsphere.vue
This disables editing for all RKE2 machine pool configs by adding a disabled prop to each machine pool config component and any children fields. A new banner has been added to notify the user that they will need to create a new pool if they wish to edit any config values. 
This also reverts changes introduced by PR #3629, but we keep the update prop as an easy way to determine if any machine configs should be in a disabled state.
#3553
> [master] Disable editing RKE2 machine pool configs after creation

- components/form/ServicePorts.vue
#3701 - This value _can_ be a string but needs to be an integer if it doesn't contain letters; using the `.number` modifier on an input that otherwise accepts strings enforces this.
> [master]fix service targetport type

- assets/translations/en-us.yaml
- The cluster management / cluster detail / tab for nodes/machines is now always labelled as machines. 
- Ensure all references to cluster detail machines tab align
- cluster management / cluster List `Machines/Nodes` --> `Machines` (these are counts/state of items from that detail machines tab type)
- There's only one concept of nodes now (to the user), so remove any previous attempts to differentiate node / mgmt node 
- explorer / cluster / `Kube Node` --> `Node`
- cluster management / cluster List/ machines list `K8s Nodes` --> `Node`
Master PR #3779
> [2.6] Tidy management node terminology

- assets/translations/en-us.yaml
- The cluster management / cluster detail / tab for nodes/machines is now always labelled as machines. 
- Ensure all references to cluster detail machines tab align
- cluster management / cluster List `Machines/Nodes` --> `Machines` (these are counts/state of items from that detail machines tab type)
- There's only one concept of nodes now (to the user), so remove any previous attempts to differentiate node / mgmt node 
- explorer / cluster / `Kube Node` --> `Node`
- cluster management / cluster List `K8s Nodes` --> `Node`
> [master] Tidy management node terminology

- edit/provisioning.cattle.io.cluster/index.vue
- models/provisioning.cattle.io.cluster.js
- This will unblock some QA use cases when creating as admin (non-admins will still be in same broken state)
- Ensure that if we have access to the local cluster use it
- For non-admins they're still in a broken state, this is tracked in another issue
Also fixed issue where returning to the provisioning cluster too early would fail
master PR #3782
> [2.6] Fix create cluster by template for admins

- edit/provisioning.cattle.io.cluster/index.vue
- models/provisioning.cattle.io.cluster.js
- This will unblock some QA use cases when creating as admin (non-admins will still be in same broken state)
- Ensure that if we have access to the local cluster use it
- For non-admins they're still in a broken state, this is tracked in another issue
Also fixed issue where returning to the provisioning cluster too early would fail
> [master] Fix create cluster by template for admins

- components/form/Members/MembershipEditor.vue
- edit/management.cattle.io.project.vue
- For non-admin's, who didn't have access to an existing project, couldn't create one (create button disabled) given their lack of rights to the binding type
- When non-admins create their project they get this binding automatically, so count case as valid
Also
- Disable remove of a member binding if there is only one user
- covers case where a non-admin can remove themselves when editing their project and not re-add
#3756
> [master] Allow non-admins to create projects without supplying members

- assets/translations/en-us.yaml
- components/form/Members/MembershipEditor.vue
#3790 - this bug is happening because standard users with the cluster owner role can't list users other than themselves. Initially I thought this was a permission issue, but on closer inspection there's no real need for a user to access that resource to edit project membership: the MembershipEditor component was using the list of users to disable the 'add' button when there are no potential members to add. Since we can't assume the user editing the project has access to `/v1/users` (other than themselves), and we can't just list all `/v3/principals`, I don't see a good alternative of calculating `isOnlyRegisteredUser` and ended up removing that functionality entirely.
> [master]remove references to /v1/users in membershipeditor

- assets/styles/global/_select.scss
This defines some disabled styles for labeled selects by creating a new selector list that handles disabled styles for both `.labeled-select` and `.unlabeled-select`.
#3553
Backports PR #3775 to release-2.6
> [2.6] Provide styles for disabled labeled selects

- assets/styles/global/_select.scss
This defines some disabled styles for labeled selects by creating a new selector list that handles disabled styles for both `.labeled-select` and `.unlabeled-select`.
#3553
> [master] Provide disabled styles for labeled selects

- models/management.cattle.io.nodetemplate.js
This fixes an issue where incorrect providers could be displayed by filtering out any node template keys that contain a `null` value. 
There were some cases (observed when creating an EC1 cluster for Digital Ocean and vSphere) where the node template contained config keys for both `amazonec2` and `vmwarevsphere`. The `amazonec2` config was always `null`, but simply finding the first config could generate the wrong provider for display. 
#3731
> [master] Fix issue with provider display displaying wrong value

- components/PromptRestore.vue
- models/management.cattle.io.nodetemplate.js
This fixes an issue where incorrect providers could be displayed by filtering out any node template keys that contain a `null` value. 
There were some cases (observed when creating an EC1 cluster for Digital Ocean and vSphere) where the node template contained config keys for both `amazonec2` and `vmwarevsphere`. The `amazonec2` config was always `null`, but simply finding the first config could generate the wrong provider for display. 
#3731
Backports PR #3830 into release-2.6
> [2.6] Fix issue with provider display displaying wrong value

- edit/provisioning.cattle.io.cluster/rke2.vue
#3805 
Updated `profileOptions` computed function  `null` value to `''` to avoid Select component truthiness override
> Worker CIS Profile - Default is blank instead of (None) #3805

- models/management.cattle.io.cluster.js
Searching the specs keys for a config wasn't as reliable as checking the status.driver field.
https://github.com/rancher/dashboard/issues/3714
> Changing the source of the cluster provisioner

- models/management.cattle.io.cluster.js
Searching the specs keys for a config wasn't as reliable as checking the status.driver field.
https://github.com/rancher/dashboard/issues/3714
forwardport of https://github.com/rancher/dashboard/pull/3771
> [forwardport] Changing the source of the cluster provisioner

- list/node.vue
- Both actions require `provisionedMachine` in `/models/cluster/node.js`
- #3699
> [master] Ensure we pre-fetch machines to show node ssh & download key actions

- components/PromptRestore.vue
- list/node.vue
- Both actions require `provisionedMachine` in `/models/cluster/node.js`
- #3699
> [2.6] Ensure we pre-fetch machines to show node ssh & download key actions

- models/management.cattle.io.authconfig.js
- models/management.cattle.io.user.js
- Removed auth config `disable` (not used and is now misleading)
- Added mgmt user 'remove' (create/edit by-passes mgmt user type entirely)
#3865
> [2.6] Handle Mgmt AuthConfig & User Remove

- models/management.cattle.io.authconfig.js
- models/management.cattle.io.user.js
- Removed auth config `disable` (not used and is now misleading)
- Added mgmt user 'remove' (create/edit by-passes mgmt user type entirely)
#3864
> [master] Handle Mgmt AuthConfig & User Remove

- assets/translations/en-us.yaml
- models/management.cattle.io.setting.js
- utils/custom-validators.js
- utils/validators/setting.js
This adds a custom validation rule to management settings to check if `server-url` starts with `https://`.
I took the simple path of checking if the string literally starts with `https://` because I felt that satisfies the conditions in the issue, but we can easily modify this one to use some sort of regex that will check for a fully qualified url if that makes more sense.
#3832
> [master] Add custom validation rule for server url in management settings

- assets/translations/en-us.yaml
- models/management.cattle.io.setting.js
- utils/custom-validators.js
- utils/validators/setting.js
This adds a custom validation rule to management settings to check if `server-url` starts with `https://`.
I took the simple path of checking if the string literally starts with `https://` because I felt that satisfies the conditions in the issue, but we can easily modify this one to use some sort of regex that will check for a fully qualified url if that makes more sense.
#3832 
Backports PR #3871 into release-2.6
> [2.6] Add custom validation rule for server url in management settings

- nuxt.config.js
- pages/docs/_doc.vue
Addresses #3462 
Note: The styling fixes aren't as bad as they look - I had to remove the .nuxt-content and a I renamed the parent.
The nuxt-content component allows live editing in dev, which has slightly different styling, which is why it looked okay in dev but not production. I have turned off live editing to avoid and issues down the line.
> [master] Fix formatting on release notes page

- edit/catalog.cattle.io.clusterrepo.vue
This trims leading and trailing spaces for the index url when creating a new chart repository. The presence of leading/trailing spaces has lead to hard to understand errors where the user might not be able to easily see the offending space in an error message.
#3794
Backports PR #3878 into release-2.6
> [2.6] Trim leading and trailing spaces when entering cluster url

- edit/catalog.cattle.io.clusterrepo.vue
This trims leading and trailing spaces for the index url when creating a new chart repository. The presence of leading/trailing spaces has lead to hard to understand errors where the user might not be able to easily see the offending space in an error message.
#3794
> [master] Trim leading and trailing spaces when entering cluster url

- edit/provisioning.cattle.io.cluster/rke2.vue
#3805 
Updated `profileOptions` computed function  `null` value to `''` to avoid Select component truthiness override
> [2.6] Worker CIS Profile - Default is blank instead of (None)

- components/form/Members/ClusterMembershipEditor.vue
- components/form/Members/ClusterPermissionsEditor.vue
- components/form/Members/MembershipEditor.vue
- components/form/Members/ProjectMembershipEditor.vue
- edit/management.cattle.io.project.vue
- edit/provisioning.cattle.io.cluster/import.vue
- edit/provisioning.cattle.io.cluster/rke2.vue
- pages/c/_cluster/explorer/members/index.vue
- Ensure users can only see cluster/project membership details if they have perms to
Address #3780, part of #3721
Master port - #3838
~Currently blocked on backend work - https://github.com/rancher/dashboard/issues/3780#issuecomment-897599519~
> [2.6] Ensure base users with create cluster rights can create / manage cluster

- components/Markdown.vue
Addresses #3763 
We don't have the base URL where the chart came from, so we can't render relative links.
> [master] Markdown: Don't render relative links as anchors

- detail/management.cattle.io.user.vue
- models/management.cattle.io.clusterroletemplatebinding.js
- models/management.cattle.io.projectroletemplatebinding.js
- Ensure `Cluster Roles` and `Project Roles` tables update on change (specifically delete of a role binding)
- Better error handling
- A `Global Permission` is ticked if the user is of a certain type (admin, standard user, etc) that has a role that contains all the rules in the permission. If the role contains no rules then previously the permission was ticked. This is slightly confusing, so flipped the logic and now empty roles are not ticked by default.
- When saving/remove a cluster/project binding we check the principal to determine if it's a user or group. The principals may not have been fetched when listing (fetch all principals does not guarantee all are fetched), so reach out directly to get the required one.
Addresses #3840
Master PR #3870
> [2.6] Multiple fixes to User Detail page

- detail/management.cattle.io.user.vue
- models/management.cattle.io.clusterroletemplatebinding.js
- models/management.cattle.io.projectroletemplatebinding.js
- Ensure `Cluster Roles` and `Project Roles` tables update on change (specifically delete of a role binding)
- Better error handling
- A `Global Permission` is ticked if the user is of a certain type (admin, standard user, etc) that has a role that contains all the rules in the permission. If the role contains no rules then previously the permission was ticked. This is slightly confusing, so flipped the logic and now empty roles are not ticked by default.
- When saving/remove a cluster/project binding we check the principal to determine if it's a user or group. The principals may not have been fetched when listing (fetch all principals does not guarantee all are fetched), so reach out directly to get the required one.
Addresses #3840
2.6 PR #3869
> [master] Multiple fixes to User Detail page

- models/catalog.cattle.io.clusterrepo.js
- pages/c/_cluster/apps/charts/install.vue
- Non-admins without a cluster won't be able to fetch operations immediately
Addresses (front end of) #3721
2.6 PR #3885
Issues
- Operation type only becomes available when provisioning cluster is created. If the install fails before this the user can never get the operation (and thus logs) to see why (see comment - https://github.com/rancher/dashboard/issues/3721#issuecomment-898592109, have also pinged Dan on slack)
> [master] Cluster Template Install: Wait for operations to become available

- models/catalog.cattle.io.clusterrepo.js
- pages/c/_cluster/apps/charts/install.vue
- Non-admins without a cluster won't be able to fetch operations immediately
Addresses (front end of) #3721
Master PR: #3893
Issues
- Operation type only becomes available when provisioning cluster is created. If the install fails before this the user can never get the operation (and thus logs) to see why (see comment - https://github.com/rancher/dashboard/issues/3721#issuecomment-898592109, have also pinged Dan on slack)
> [2.6] Cluster Template Install: Wait for operations to become available

- docs/developer/getting-started/development_environment.md
This adds a little recommendation to our development environment docs for when it's safe to toggle recording Vuex state in Vue devtools.
> [master] Update snippet about disabling recording for Vue devtools

- components/form/WorkloadPorts.vue
This adds a little more spacing to the protocol column by increasing the width to 90px. This also adds the `col` class to the labeled selects in order to satisfy the requirements for the style that defines minimum height. 
#3662
> [master] Add more width to protocols dropdown

- components/form/WorkloadPorts.vue
This adds a little more spacing to the protocol column by increasing the width to 90px. This also adds the `col` class to the labeled selects in order to satisfy the requirements for the style that defines minimum height. 
#3662
Backports PR #3897 into release-2.6
> [2.6] Add more width to protocols dropdown

- components/form/Members/ClusterPermissionsEditor.vue
- components/form/Members/MembershipEditor.vue
- components/form/Members/ProjectMembershipEditor.vue
- edit/management.cattle.io.clusterroletemplatebinding.vue
#3907 - I found two issues when looking into this:
- The visibility of the member roles tab is dependent on `canViewMembershipEditor` but as far as I can tell a user doesn't need to be able to access project role template bindings to create/edit cluster role template bindings. So a standard user who should see this tab doesn't. This is caused by changes merged yesterday, hence not in the linked ticket. 
- new cluster role template bindings are being defined initially with the current cluster's id; standard users don't necessarily have access to any clusters so `this.$store.getters['currentCluster'].id` was causing an error. 
@codyrancher we both have PRs that touch `MembershipEditor` now. Our actual work doesn't conflict but git may think otherwise. You're welcome to get yours in first; I …
> [master] fix clusterrolebinding creation for standard user

- mixins/brand.js
#3861 - the `head` function setting the title wasn't using `getVendor` with the SUSE brand enabled so I rectified that here. I thought that `getVendor` returned 'SUSE Rancher' or something similar with the subscription key provided, but I don't see any code for that hanging around... @nwmac do you know if that was intentionally removed?
> [master]fix custom brand when subscription enabled

- assets/translations/en-us.yaml
This updates the custom cluster registration windows not ready message to mention linux worker nodes.
#3580
> [master] Update windows not ready warning

- assets/translations/en-us.yaml
This updates the custom cluster registration windows not ready message to mention linux worker nodes.
#3580
Backports PR #3928 into release-2.6
> [2.6] Update windows not ready warning

- models/workload.js
This sets template, if it doesn't exist, to the spec for a workload before attempting to set metadata.
This seems like a straightforward solution to resolve the error, but I wonder if there's some underlying problem that needs to be addressed that might explain why template is undefined at this point. 
#3835
Backports PR #3917 into release-2.6
> [2.6] Check for template before attempting to assign metadata

- models/workload.js
This sets template, if it doesn't exist, to the spec for a workload before attempting to set metadata.
This seems like a straightforward solution to resolve the error, but I wonder if there's some underlying problem that needs to be addressed that might explain why template is undefined at this point. 
#3835
> [master] Check for template before attempting to assign metadata

- assets/translations/en-us.yaml
- pages/fail-whale.vue
- store/index.js
This adds a button to the fail whale page to allow the user to "refresh" the page on error by attempting to navigate back one step in the router history. 
I attempted another approach to display the fail whale page without modifying the url by introducing a named catch-all route, similar to instructions detailed in [NUXT](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router#extendroutes) and [Vue Router](https://next.router.vuejs.org/guide/essentials/dynamic-matching.html#catch-all-404-not-found-route), but I think the functionality that I was looking for is only available in Vue Router 4.x. I'm open to other potential solutions to resolve this issue.
#3421
> [master] Add reload button to fail whale

- assets/translations/en-us.yaml
- pages/fail-whale.vue
- store/index.js
This adds a button to the fail whale page to allow the user to "refresh" the page on error by attempting to navigate back one step in the router history. 
I attempted another approach to display the fail whale page without modifying the url by introducing a named catch-all route, similar to instructions detailed in [NUXT](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router#extendroutes) and [Vue Router](https://next.router.vuejs.org/guide/essentials/dynamic-matching.html#catch-all-404-not-found-route), but I think the functionality that I was looking for is only available in Vue Router 4.x. I'm open to other potential solutions to resolve this issue.
#3421 
Backports PR #3926 into release-2.6
> [2.6] Add reload button to fail whale

- assets/translations/en-us.yaml
- edit/provisioning.cattle.io.cluster/CustomCommand.vue
- list/node.vue
- models/management.cattle.io.cluster.js
This displays warning to the user, notifying them that workloads will deploy to both windows and linux nodes. This warning is displayed while registering windows nodes or viewing a collection of nodes for a cluster that contains windows nodes. 
#3921 
Backports PR #3946 into release-2.6
> [2.6] Warn users about adding windows and linux nodes

- components/form/LabeledSelect.vue
- mixins/labeled-form-element.js
- This also fixes the blip when drop down is open and the selected value is clicked on again
- Investigated other fixes...
- slot'ing a new open indicator in (doesn't handle clickes)
- using document.activeElement (already set away from drop down)
- this.raised (not applicable in some cases)
Issue: #3961
Master: #3965
> [2.6] Fix issue where drop down re-opens when clicking on collapse button

- components/form/LabeledSelect.vue
- mixins/labeled-form-element.js
- This also fixes the blip when drop down is open and the selected value is clicked on again
- Investigated other fixes...
- slot'ing a new open indicator in (doesn't handle clickes)
- using document.activeElement (already set away from drop down)
- this.raised (not applicable in some cases)
Issue: #3961
2.6: #3964
> [master] Fix issue where drop down re-opens when clicking on collapse button

- assets/translations/en-us.yaml
- components/FixedBanner.vue
- pages/c/_cluster/settings/brand.vue
#3906 
Added two sections for customizing the header and footer banners which allows alignment (left, center, right) and text styling (bold, italic, underline).
Tested locally. Looks decent but could use some proper styling/icons.
> #3906 - Add basic formatting support to the custom banners

- models/management.cattle.io.project.js
This PR reverts a change made I here https://github.com/rancher/dashboard/pull/3489 -- deleting projects is no longer allowed through steve. I originally made that change in an effort to fix the same issue described here: #3828 
Previously we were deleting through norman then calling 
`$dispatch('management/findAll', { type: MANAGEMENT.PROJECT, opt: { force: true } }, { root: true });` 
to refresh the project list but #3828 still happens some of the time. Here I've opted to remove the project object from the management/steve store once the norman delete runs so the project is consistently removed from the list view.
> [master]revert to using norman to delete projects

- pages/c/_cluster/apps/charts/install.vue
- store/catalog.js
- for standard users creating their first cluster (by template) there's no `cluster` available
- so for those scenarios the catalog entities are stored in the management store
- ensure then when we fetch the catalog operation after installing we respect the original store
Issue: #3721
Master: #3986
> [2.6] Ensure we use the correct store when checking for catalog operation

- components/nav/Group.vue
- Core Problem
- Type component selects an item in the side menu... which then fires off groupSelected in Groups component
- Group component groupSelected then replaces route with first item in group, regardless of the route Type that was just selected
- Page however still stays on the Type's route and not what the $route now thinks is the current one
- This leads to all sorts of errors when clicking around types in a group
- Problem from Issue #3989
- There is a guard in Type that normally prevents the groupSelected from firing if you're on the same page
- However for the auth provider, where we change the route to a configured provider on click, this compares '/c/local/auth/config' to '/c/local/auth/config/github'
- This means we try to change the page and GlobalLoading somehow gets …
> Fix mighty confused routing

- edit/catalog.cattle.io.clusterrepo.vue
This trims both the git repo and branch when creating a chart repository.
#3794
#3706
> Trim git repo and branch when creating chart repo

- detail/pod.vue
This adds `initContainers` to pod containers by merging `containers` and `initContainers`, as well as associated statuses, into respective collections for each.
An alternative approach might be to create an additional tab that only displays when `initContainers` exist for a pod.  
#3508
> Add initContainers to the collection of pod containers

- assets/translations/en-us.yaml
- models/management.cattle.io.cluster.js
#3997  Update to yaml translation to be consistent with other fields
> k8s version update when a GKEv2 cluster is provisioning

- .github/issue_template.md
- Balanced asking too little info with wall of text that would probably be ignored
- Kept this simple, so clicking new issue takes user directly to template
- Alternative is to have specific bug and feature request templates that user has to choose from first (see rancher/rancher)
- Could consider making this into a github form
> Add Github Issue Template

- layouts/unauthenticated.vue
https://github.com/rancher/dashboard/issues/4091
After enabling a custom header and footer, they both now show when you log in and log out.
> Classification banners show on login screen

- assets/translations/en-us.yaml
- assets/translations/zh-hans.yaml
- config/footer.js
- config/private-label.js
- docs/developer/auth-providers.md
- docs/developer/getting-started/development_environment.md
- store/i18n.js
Addresses https://github.com/rancher/dashboard/issues/3279
This PR removes all links to the non-versioned Rancher v2.x docs, which are not up-to-date for v2.6. It also stores the versioned part of the URL as a constant which is used by all of the docs links.
When changing 2.x links to 2.6 links, I validated them and updated them if applicable.
> Replace non-versioned documentation links

- assets/translations/en-us.yaml
- edit/secret/index.vue
https://github.com/rancher/dashboard/issues/2644
This PR adds descriptions and Kubernetes docs links to each type of secret you can create on this page:
The part about adding similar descriptions for role types isn't applicable because the page was removed.
> Describe secrets and link to Kubernetes docs

- components/form/KeyValue.vue
This PR addresses https://github.com/rancher/dashboard/issues/3724. The tooltip suggesting hints for entering multiple values no longer shows when only one key-value pair is allowed:
> Disable tooltip for multiple values when only one value is allowed

- components/EmberPage.vue
Addresses https://github.com/rancher/dashboard/issues/3939
The code to detect if the previous iframe had loaded did not check for null - so null was treated as true, which was not the case.
> Fix IFRAME issue loading

- assets/translations/en-us.yaml
- components/auth/SelectPrincipal.vue
- components/form/LabeledSelect.vue
- components/form/Members/ClusterPermissionsEditor.vue
- nuxt.config.js
- package.json
- plugins/directives.js
- yarn.lock
This adds focus to the member select when the component loads by creating a new `v-focus` directive. This directive provides focus to a `LabeledInput` or `LabeledSelect` by attempting to locate the focus-able element in the component instance. If the correct component can't be located, `v-focus` won't attempt to provide focus to any component.
Ideally, more focus-able components can be added to the directive as we identify components throughout Rancher that need support for this directive.
This also adds translations to the labeled select when adding cluster members.
#4026
> Focus on Select Member when adding a cluster member

- docs/developer/getting-started/development.md
This adds a new section to the docs for form ux with some guidance on auto-focusing elements in a form.
#4026
> Add guidance for focusing form elements

- assets/translations/en-us.yaml
- pages/auth/login.vue
- pages/auth/verify.vue
https://github.com/rancher/dashboard/issues/3841
This issue arose from https://github.com/rancher/rancher/issues/13666 and it's specifically about errors the backend is returning on the redirect to `/auth/verify ` .  Some auth types return an `error_description` query param and some an `errorMsg`; the Ember code equivalent is [here](https://github.com/rancher/ui/blob/8e07c492673171731f3b26af14c978bc103d1828/app/verify/route.js#L54) and [here](https://github.com/rancher/ui/blob/8e07c492673171731f3b26af14c978bc103d1828/app/verify/route.js#L121) for saml and oauth respectively.
> pass external auth errors from auth/verify redirects back to main window

- utils/create-yaml.js
This removes the duplicated  `type` key that show up when modifying YAML for services by only inserting `_type` at a depth of 0. Both keys `_type` and `type` were present in the schema and `_type` was getting transformed into `type`, generating the duplicate key.
#4042
#4136
> Remove duplicate type keys from YAML

- assets/styles/global/_resource.scss
This PR addresses https://github.com/rancher/dashboard/issues/4108
When you create a new Secret, the subresource types now display the More Info links with proper alignment:
> More info links are shown in top right corner

- assets/translations/zh-hans.yaml
This issue addresses https://github.com/rancher/dashboard/issues/4102. It removes the variable that wasn't supposed to be there and replaces it with the equivalent of the English translation string `backupRestoreOperator.encryption`, which is just "Encryption."
To test this fix, 
1. I installed the backup application on the local cluster.
2. I switched the language to Chinese.
3. I went to the page for the Backup custom resource and clicked the create button.
Those steps resulted in a normal form without any errors.
> Replace incorrect translation of 'Encryption'

- components/nav/WindowManager/ContainerLogs.vue
This PR addresses https://github.com/rancher/dashboard/issues/4032
To test this PR, I deployed a Pod on the `local` cluster from YAML. I used this YAML, taken mainly from the upstream [Kubernetes docs about initContainers](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-initialization/#create-a-pod-that-has-an-init-container). I created two initContainers named `install` and `install2` so show that you can switch between viewing logs for both of them.
```
apiVersion: v1
kind: Pod
metadata:
name: init-demo
spec:
containers:
- name: nginx
image: nginx
ports:
- containerPort: 80
volumeMounts:
- name: workdir
mountPath: /usr/share/nginx/html
initContainers:
- name: install
image: busybox
command:
- wget
- "-O"
- "/work-dir/index.html"
- …
```
> Can see logs from init containers

- assets/translations/en-us.yaml
- edit/logging.banzaicloud.io.output/providers/cloudwatch.vue
This PR addresses https://github.com/rancher/dashboard/issues/3988 by adding the `log_group_name` and `log_stream_name` fields to the form for creating logging Outputs.
To test the Cloudwatch Output form,
1. I installed the logging operator
2. I went to form to create logging Outputs and created an Output with a `name`, `region`, `log_group_name` and `log_stream_name`
The Output was successfully created and I confirmed that the resulting YAML for the new fields matched the YAML for the Cloudwatch example in the Banzai Cloud documentation. https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/cloudwatch/#example-output-configurations
Bastian said the `log_group_name` is required, so it looks like the Banzai Cloud docs incorrectly stated that the field is optional. I created …
> Add inputs to Output form for Cloudwatch logging

- assets/translations/en-us.yaml
- components/form/PodAffinity.vue
#1815 
Added an input to select the weight for a pod when configuring preferred affinities.
> Add pod affinity weight input to pod scheduling tab

- components/nav/TopLevelMenu.vue
- addresses #4128
- also fixes misaligned cross arrow in cluster filter search box
> Ensure side nav cluster section shows after filtering out all clusters

- assets/translations/en-us.yaml
- machine-config/amazonec2.vue
This resolves an issue where a pool for Amazon EC2 could go into an unrecoverable error state by performing a simple action like selecting a region that a user might not have authorization to access. We resolve this issue by opting to display both the error message and form at the same time. 
An alternative approach might be to introduce a button that will reset the machine config state and clear the error if we want to keep to current behavior or only displaying either the machine config or error.
This also fills in some gaps in translations that I encountered throughout the component.
#4071
> Display both error message and Amazon EC2 machine config form 

- components/auth/SelectPrincipal.vue
- addresses part of #4004 (should increase number of suggested options)
- Worked together with @jordojordo on this
- We've left the rather confusing `showMyGroupTypes` and `searchGroupTypes` prop names for the moment
> Suggest users and well as groups in the select principal component

- pages/auth/verify.vue
#3841 - my previous PR for this (#4144) wasn't checking for errors early enough (ie before looking for a github nonce code) in the `/auth/verify` page load and consequently missing some errors for some providers.
> check for auth verification errors sooner in page load

- components/nav/NamespaceFilter.vue
- edit/constraints.gatekeeper.sh.constraint/NamespaceList.vue
- edit/constraints.gatekeeper.sh.constraint/index.vue
- store/index.js
- store/prefs.js
- Previously there was one value for all clusters
- Now
- prefs NAMESPACE_FILTERS stores values keyed by cluster
- when accessing prefs NS the specific cluster is extracted and everything behaves as before
- On switch of cluster any pref for an unknown cluster is removed
- addresses #3858
Also changed name of clashing NAMESPACE_FILTERS object
> Store ns/project filter per cluster

- edit/networking.k8s.io.ingress/index.vue
This PR addresses https://github.com/rancher/dashboard/issues/4125 by limiting the Secret options for Ingress configuration to only the Secrets that are in the same namespace as the Ingress.
The problem was that the secret options was based on what was selected in the top nav instead of the namespace selected in the Ingress creation form. So if you selected two namespaces in the top nav, you would see secrets from both namespaces as options when configuring the Ingress, even if the Ingress has a single namespace already configured.
1. I created a namespace for the Ingress - `ingress-namespace`.
2. I created two Secrets of type Certificate - one in `ingress-namespace` named `correct-secret` and one in `default` named `incorrect-secret`:
```
apiVersion: v1
data:
tls.crt: …
```
> Limit Secret options for Ingress to same namespace as Ingress

- .vscode/launch.json
- components/SortableTable/filtering.js
- components/SortableTable/grouping.js
- components/SortableTable/index.vue
- components/SortableTable/paging.js
- components/SortableTable/sorting.js
- components/formatter/ServiceType.vue
- utils/object.js
- Faster utils/object get()
- A surprising amount of time everywhere in tables goes into get(), but get(obj, 'simpleField') can bypass most of the code that supports json-path, nested.fields, nested."quoted.fields", etc.
- Regex is slower than simple string operations
- Faster SortableTable search (#4174)
- Sort first, then filter, because the sorting doesn't change as you type.
- As you filter each additional keystroke can only remove more entries, so remember the previous filter+result and start from there when possible instead of searching everything again.
- Debounce the user input field from the actual filtering operation so that the user's typing shows up normally instead of 'hanging'
Bonus:
- Chrome debugger launch.json
> Faster table filtering

- plugins/steve/mutations.js
- plugins/steve/resource-instance.js
- plugins/steve/resource-proxy.js
- plugins/steve/steve-class.js
- plugins/steve/subscribe.js
Should fix issues with some names appearing incorrectly.
_description was also missing in the resource-instance, which meant descriptions did not show for API Keys
> Reinstate special key mapping for proxies

- assets/translations/en-us.yaml
- components/LandingPagePreference.vue
- components/ResourceTable.vue
- components/nav/TopLevelMenu.vue
- config/product/harvester-manager.js
- edit/token.vue
- list/fleet.cattle.io.cluster.vue
- list/management.cattle.io.cluster.vue
- list/provisioning.cattle.io.cluster.vue
- models/harvesterhci.io.management.cluster.js
- models/management.cattle.io.cluster.js
- models/provisioning.cattle.io.cluster.js
- pages/home.vue
- utils/cluster.js
Addresses https://github.com/rancher/dashboard/issues/3467
Also contains bug fix for ResouceTable if you go to view a list for user preferences - the object returned is null, not an empty array, so this is now handled.
> Filter out Harvester clusters from the various cluster lists

- list/harvesterhci.io.management.cluster.vue
- uses new slot in Masthead
- moves from underneath `Clusters` title row
> Tweak the location of the harvester cluster tech preview notice

- components/DetailTop.vue
- Fixed places like namespace (only shows 'detail' sections) and cluster  (only shows 'tags' section) detail pages 
- Still looks ok in places like node detail page (show's different types of sections)
Example
Old
vs
New
> Fix resource detail's detail values spacing

- edit/auth/azuread.vue
This prevents us from overwriting the applicationSecret with a secretId.
https://github.com/rancher/rancher/issues/34756
> Omit the AzureAD applicationSecret if the current secret is just an id.

- components/nav/WindowManager/ContainerLogs.vue
#4220 - `pod.spec.initContainers` is not necessarily defined so this `.map()` was throwing an error for some pods.
> account for undefined pod initContainers in view logs

- assets/translations/en-us.yaml
#4222 -  translation keys used [here](https://github.com/rancher/dashboard/blob/master/edit/provisioning.cattle.io.cluster/rke2.vue#L1173) were accidentally shuffled around recently
> fix cluster.description translation path

- assets/translations/en-us.yaml
- components/PromptRemove.vue
- models/workload.class.js
#4212 - This PR adds a warning to the PromptRemove dialogue for workloads created in ember (workloads with the 'norman' cattlio.io/creator label)
Neil and I discussed this offline and it seemed safer to warn users they'd have to go delete services than attempt to delete them through the UI.
> delete warning for norman-made workloads

- models/fleet.cattle.io.cluster.js
- blocked on availability of model's mgmt
- switch mgmt getter id from metadata.label to FLEET_LABELS.CLUSTER_NAME
- #4224
> Show fleet cluster assign to action

- middleware/authenticated.js
- store/index.js
- On every route transition either the `cluster` or `harvester` store was reset (`unsubscribe` + `reset`)
- Cause of lots of the following in log
```
Reset Harvester
All of schema is not loaded yet
```
- Now conditionally reset stores - `cluster` in `loadVirtual`, `harvester` in `loadCluster`
- Also removed odd check gating check for no-op route changes
> Improve dashboard performance

- layouts/default.vue
- models/schema.class.js
- models/schema.js
- plugins/steve/getters.js
- plugins/steve/mutations.js
- plugins/steve/resource-proxy.js
- utils/object.js
- utils/string.js
- Faster getters.pathExistsInSchema
- Don't overlap getGroups calls
- Only remapSpecialKeys for old Proxies
> More faster

- assets/translations/en-us.yaml
- components/PromptModal.vue
- components/dialog/RollbackWorkloadDialog.vue
- components/formatter/PodImages.vue
- models/workload.class.js
- plugins/steve/resource-class.js
- utils/time.js
This PR addresses this issue https://github.com/rancher/dashboard/issues/4149#issue-995320370 by forward porting the rollback button for each workload so that a user can easily roll back a workload to a previous revision.
1. In the `local` cluster, I created a Deployment named `test` in the `default`namespace with the `nginx:1.21` image.
2. I created a new version by editing the Deployment to make its image `nginx:1.21.3`.
2. In the cluster explorer I clicked **Workload > Deployments**, then went to `test` and clicked **⋮ Rollback.**
3. I clicked the new revision and clicked **Roll Back**.
4. Confirmed that the image name in the list view reverted to `nginx:1.21`. (Nancy explained that to make the image update in the list view, the `images` in …
> Forward port rollback workload feature

- components/form/Password.vue
- edit/auth/ldap/index.vue
- pages/auth/setup.vue
- plugins/directives.js
Updated `tabindex` in Password component to remove 'show' tag from tab order
Used password component in place of labeledinput in other `edit/auth/ldap/index.vue` and `pages/auth/setup.vue`
#4200 
s
> 'Show' button in password boxes removed from tab order

- assets/translations/en-us.yaml
- edit/provisioning.cattle.io.cluster/rke2.vue
This adds some missing translations for the tabs in the RKE2 edit component. Tabs that were missing translations were Add Ons and Advanced.
> Add missing translations for Edit RKE2 tabs

- components/form/Members/ClusterPermissionsEditor.vue
#4248 - this bug is seen if you toggle the radio buttons without having selected a user/group from the dropdown. It happens because principal is undefined on [this](https://github.com/rancher/dashboard/blob/master/components/form/Members/ClusterPermissionsEditor.vue#L188) line but I think the right solution here is to ensure we're not trying to create bindings before a principal has been selected.
> fix cluster permissions editor radio when no principal selected

- detail/pod.vue
- models/pod.class.js
This PR addresses https://github.com/rancher/dashboard/issues/3100 by making it so that for each container listed on the Pod detail page, you have a menu that lets you directly open the shell and logs for each container. (Previously, to open logs or shell for a non-default container, you had to open the menu at the Pod level and then switch containers from there.)
1. I created a Deployment named `test` with two containers (`nginx` and `debian`) to allow testing the action menu for both default and non-default containers:
```
metadata:
name: test
annotations:
{}
labels:
{}
spec:
selector:
matchLabels:
workload.user.cattle.io/workloadselector: apps.deployment-default-undefined
template:
metadata:
labels: …
```
> Add menu to open shell and logs for each container

- config/table-headers.js
- detail/provisioning.cattle.io.cluster.vue
- models/cluster.x-k8s.io.machine.js
This add an OS column to Machine Pools tab by lookup up `metadata?.labels['cattle.io/os']` (RKE2, Custom Cluster), or `status.internalNodeStatus.nodeInfo.operatingSystem` (non RKE2).
Since the OS can only be Windows or Linux and we only support Windows nodes in custom clusters, we check for the presence of a `cattle.io/os` label to display the OS; Linux is assumed if the label does not exist. 
#4240
#3222
> Add OS column to Machine Pools tab

- assets/translations/en-us.yaml
- cloud-credential/harvester.vue
- edit/provisioning.cattle.io.cluster/rke2.vue
- machine-config/harvester.vue
- models/namespace.js
- models/provisioning.cattle.io.cluster.js
- models/rke-machine-config.cattle.io.harvesterconfig.js
- plugins/steve/subscribe.js
- store/plugins.js
Related issues:
- https://github.com/harvester/harvester/issues/1019
- https://github.com/harvester/harvester/issues/1105
- https://github.com/rancher/dashboard/issues/3905
Desciption:
- Add harvester cloud provider, we will get kubeconfig and set it to `cloud-provider-config` before creating a cluster.
- Use `harvestercredentialConfig.clusterId` insteadof annotation to fix clusterId is undefined.
Validation Steps:
- Import a harvester cluster
- Go to the cluster management, Click create and select harvester cluster.
- Create a new credential by imported harvester cluster
- Click continue
- Select namespace: default, image: ubuntu, and network: 'vlan'
- Select cloud provider to `harvester`
- Click create
- Wait for the new cluster ready
> Add harvester cloud provider and Fix credential lack of clusterId

- assets/translations/en-us.yaml
- components/form/HookOption.vue
- components/form/LifecycleHooks.vue
- edit/workload/index.vue
This PR is in reference to #1817 which gives the ability to configure lifecycle hooks when creating containers.
There are two lifecycle hooks `postStart` and `preStop` that can be added. Each can only have 1 handler at a time.
Process: workload >  create > general tab > lifecycle hooks
> Add ability to configure a container lifecycle

- models/management.cattle.io.clusterroletemplatebinding.js
#4263 #4271 - both bugs are happening because the clusterroletemplatebinding model's `nameDisplay` function is returning undefined and breaking resource-instance `nameSort` (used to sort table columns). They have slightly different underlying causes:
#4263 - `this.user` is undefined when a standard user tries to load a clusterroletemplatebinding for another user
#4271 - `this.user` is undefined because `this.userName` doesn't exist for auth group clusterroletemplatebindings
> fix clusterroletemplatebinding nameDisplay

- components/form/NodeAffinity.vue
#4145 
`NodeAffinity` component's `update` function should fire on form input, including the `LabeledSelect` value change from 'required' to 'preferred'. 
Updated `changePriority` function, which does fire correctly, to run the `update` function as well.
> NodeAffinity scheduling update

- assets/translations/en-us.yaml
- edit/provisioning.cattle.io.cluster/import.vue
- only shown in specific scenarios (is create, not previously hidden and harvester feature flag is enabled)
- part of proposed solution to #4244, awaiting OK to merge
> Show a notice to import harvester clusters via virtualization management

- assets/translations/en-us.yaml
- components/SelectIconGrid.vue
- edit/provisioning.cattle.io.cluster/index.vue
- #4249
- Use card side labels to denote tech preview, removes confusion from previous solution (see bottom two screenshots), can easily switch off global handling and apply on a per provider basis
------
**Previous solution**
> Add tech preview noticed for rke1 harvester node driver

- assets/translations/en-us.yaml
- list/provisioning.cattle.io.cluster.vue
Addresses #4251 
This PR:
- Adds a banner when that are Harvester clusters that are being filtered out - it only does this for the cluster page when viewed in explorer, not when viewed in Cluster Management.
> Harvester: Add banner to cluster page when viewed from cluster explorer

- assets/translations/en-us.yaml
- list/fleet.cattle.io.cluster.vue
- list/fleet.cattle.io.clusterregistrationtoken.vue
Addresses #4250 
This PR:
- Adds a banner to the Fleet clusters page when there are Harvester clusters that have been hidden - this helps the user understand why the count in the nav differs from the items in the list
- Updates the Fleet tokens page to filter out tokens that belong to Harvester Clusters
- Adds a banner to the Fleet tokens page when there are tokens that have been hidden because they belong to Harvester clusters - this helps the user understand why the count in the nav differs from the items in the list
> Add banners to Fleet for Harvester clusters that are filtered out

- store/index.js
When switching between Explorer and harvester in the same cluster, the scheme needs to be reloaded, so we also need to use the product to determine
**Related issue:**
https://github.com/rancher/dashboard/issues/3894
> HARVESTER: fix resource loading logic

- utils/cluster.js
As requested by the Harvester team - only look at the label if the provider is not set.
> Tweak function to determine if a cluster is a Harvester cluster

- pages/c/_cluster/apps/charts/install.vue
> Skip auto-install constraints if upgrading and the version isn't readable

- components/form/HookOption.vue
This is an update to #4247 which changes the default hook option from `null` to `none`.
To see the change: Workload > Creation > General Tab > Lifecycle Hooks
> Change default HookOption to None in Workload Creation

- components/form/HookOption.vue
- components/form/LifecycleHooks.vue
This is in relation to #1817 
The tcpSocket option in a lifecycle hook has been removed due to being unsupported https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#handler-v1-core
Fixed bug where the values in a hook option couldn't be edited/updated after the container has been created.
https://user-images.githubusercontent.com/40806497/135865106-b72c322a-8b7f-4508-bcae-05da57716ca4.mp4
To recreate:
1. Cluster > Workload > Deployment > Create
2. Add lifecycle hooks
3. Create deployment
4. Edit config of deployment
5. Update values in lifecycle hooks
> Remove tcpSocket option, fix inability to edit config after creation

- models/management.cattle.io.authconfig.js
- utils/auth.js
#4453 - this PR hides the local auth config so users can configure third party auth. A separate (security) ticket is tracking ui changes needed once it is possible to disable/re-enable local auth.
> filter local auth when searching for enabled provider

- plugins/extend-router.js
Reference #4475 
The error ` TypeError: Cannot read properties of undefined (reading 'catch')` is caused by not properly rejecting the `Promise` Navigation Error created by VueRouter. This would cause other issues in the dashboard where `Navigation Failures` would not be consumed correctly.
For VueRouter reference: 
- https://router.vuejs.org/guide/advanced/navigation-failures.html
- https://github.com/vuejs/vue-router/issues/2881#issuecomment-520554378
> Fix navigation error promise not being rejected

- components/form/WorkloadPorts.vue
Reference #4398 
**Issue**
When editing container ports for an existing workload, new `serviceTypes` would not be saved to the config unless the name was updated.
**Fix**
After selecting a `Service Type` the name and `Listening Port` (if listed) will be deleted which allows the creation of a new `serviceType`.
https://user-images.githubusercontent.com/40806497/139285160-cf050afe-2db5-4b6e-8cb8-39a05fb9f06b.mp4
**To Test**
1. Create a new workload: `cluster` =>  Workload => Create => General Tab
2. Add a container `Port`, then Create the workload
3. Edit the workload config container `Port`
4. Select a new `Service Type` and add the necessary ports while omitting the `Name` input
5. Save config and verify new conditions are present.
> Edit workload config ports - delete name upon type selection

- list/catalog.cattle.io.clusterrepo.vue
This is in reference to #4359 where the info banner on the cluster repo list page would not close.
Added the `hideTypeDescription` method to update the `typeDescriptionKey` property which will allow the banner to be closed properly. This also removes the errors in the console.
To test:
1. Navigate to _cluster_ => Apps & Marketplace => Repositories
2. Close the info banner above the list
> Add hideTypeDescription method on close of banner for clusterrepo list

- layouts/default.vue
In reference to #4423 which highlights an issue of setting the login screen only maintaining the `cluster` main page and not the sub-pages within.
This PR changes the `getLoginRoute` to set the path based on the `$route` store parameters rather than the base level `cluster` explorer.
**To Test**
1. Navigate to a page which allows setting the login page
2. Set the login page by the 3 dots in Header Nav
3. Logout and log back in to be redirected to the page that was set.
> Change getLoginRoute to accept $route parameters

- cypress.json
- cypress/integration/home.spec.ts
- cypress/integration/login.spec.ts
- cypress/integration/toplevelmenu.spec.ts
- cypress/plugins/index.ts
- cypress/support/commands.ts
- cypress/support/index.ts
- docs/developer/getting-started/development.md
- package.json
- yarn.lock
This PR upgrades cypress to enable us to leverage the new-ish sessions API, and adds some minimal documentation to help others get started.
> upgrade cypress and use login sessions

- components/nav/Group.vue
- components/nav/TopLevelMenu.vue
- cypress/integration/home.spec.ts
- cypress/integration/inappmenu.spec.ts
- cypress/integration/login.spec.ts
- cypress/integration/toplevelmenu.spec.ts
- cypress/integration/util/defaultnav.ts
- cypress/integration/util/toplevelmenu.ts
- cypress/plugins/index.ts
- cypress/support/commands.ts
- package.json
#4182 - this pr adds tests to both side navs, and updates the login command to use the new(ish) Cypress [sessions](https://docs.cypress.io/api/commands/session) functionality. I also found/addressed a small bug with overview pages not being highlighted in the nav while active, caused by the `/dashboard` prefix making this always false: `this.$route.fullPath === route.href`
> e2e nav tests

- products/epinio/list/namespaces.vue
Follow up to https://github.com/rancher/dashboard/pull/4450#discussion_r736513950
Should be merged after https://github.com/rancher/dashboard/commit/7691f0e0d982b6529adf58fa26ba8e49ba74dfa0, which creates the list component that the new watcher is on.
https://github.com/epinio/ui/issues/23#issuecomment-950982352
> Refetch app list when Epinio namespace is deleted

- edit/workload/index.vue
This pr addresses issue #4317 by using vue's trim modifier on the input field.
> Create/Edit Workloads | remove white-spaces in the "Container Image" field

- assets/translations/en-us.yaml
#4505 
Updates lifecycle hook placeholder for Exec command from `sh -c sleep 10` to `sh -c 'sleep 10'`
> Update lifecycle hook placeholder for exec command

- list/management.cattle.io.user.vue
- middleware/authenticated.js
- mixins/brand.js
- nuxt.config.js
- pages/auth/logout.vue
- plugins/steve/actions.js
- plugins/steve/mutations.js
- plugins/steve/rehydrate-all.js
- plugins/steve/resource-class.js
- store/index.js
- store/prefs.js
- utils/error.js
- utils/stream.js
#4512 
Send `Accept: application/jsonl` for `findAll()` for requests by default.  This causes the response to be sent as many separate JSON documents (separated by newlines, with the first line being the collection object sans `data` field).  The server can then start streaming out response objects as it receives them instead of buffering all in memory to produce one giant `{type: 'collection' data: [...many resources...]}` blob.  Similarly the client can start parsing the individual smaller lines as they come in instead of waiting for the entire blob to be downloaded and parsed.
In practice the total response time is still about the same from the server, but the TTFB (time to first byte) can be much sooner for slow requests.  And by the time the last byte arrives most of the parsing and …
> Parse API list responses as a application/jsonl stream

- pages/auth/logout.vue
- plugins/steve/actions.js
- plugins/steve/mutations.js
- plugins/steve/subscribe.js
- store/prefs.js
#4519 #4521
Hosted for dev vs production builds behave differently, and the UI tries to get the ui-brand setting but it's not marked as available for unauthenticated requests.
> Fix login catching errors from missing settings

- edit/logging-flow/index.vue
This resolves a an issue where typing invalid YAML for Logging Cluster Flow filters would fail unexpectedly in dev. 
To resolve the issue, we wrap `jsyaml.load` in a `try...catch` block and display any errors that might arise.
> Catch error when failing to load YAML in Logging Flow

- plugins/steve/actions.js
- plugins/steve/index.js
- utils/stream.js
Look for TextDecoder instead of TextDecoderStream.  Also adds a `[store].state.allowStreaming` flag to disable at runtime for debugging/performance testing.
> Support streaming repsonses in Firefox

- assets/translations/en-us.yaml
- components/ResourceDetail/Masthead.vue
- models/workload.js
This WIP addresses https://github.com/rancher/dashboard/issues/4331
When a workload is running normally, the pause orchestration button is available from the actions:
When orchestration is paused, an info message appears on the detail page that lets you know what happened and how to undo it:
When orchestration is paused, the pause orchestration button is no longer available, and it has been replaced by the resume orchestration button:
I made it so the list view shows the workload's status as "paused" instead of "inactive," as it used to be in Ember. I believe the 'paused' is the expected behavior because this way it is consistent with what happens when you pause and unpause a Fleet cluster.
To test this PR, 
1. I created an nginx deployment in the default namespace of the local cluster …
> Add pause orchestration button for workloads

- assets/translations/en-us.yaml
- edit/logging.banzaicloud.io.output/index.vue
Since there are a lot of different possible values, I added a YAML editor similar to the flow filters.
Addresses https://github.com/rancher/dashboard/issues/4421
> rancher-logging: Add UI for output buffers

- edit/logging-flow/index.vue
If they are created somewhere else, they won't be picked up by rancher-logging
Addresses https://github.com/rancher/dashboard/issues/4413
> rancher-logging: Always create ClusterFlows in cattle-logging-system

- components/form/SecretSelector.vue
- edit/logging.banzaicloud.io.output/providers/elasticsearch.vue
- edit/logging.banzaicloud.io.output/providers/forward.vue
- edit/logging.banzaicloud.io.output/providers/kafka.vue
- edit/logging.banzaicloud.io.output/providers/loki.vue
- edit/logging.banzaicloud.io.output/providers/splunkHec.vue
- edit/logging.banzaicloud.io.output/providers/syslog.vue
Several logging output fields for ca and client certificates need to be provied as a file path in the fluentd config. For this, the secret which contains the value must be referenced in the output yaml with mountFrom instead of valueFrom. See https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/secret/.
Addresses https://github.com/rancher/rancher/issues/31810
> rancher-logging: Fix generated YAML for logging output fields referencing file paths

- assets/translations/en-us.yaml
- edit/logging.banzaicloud.io.output/providers/gelf.vue
- models/logging.banzaicloud.io.output.js
Adds support for the GELF output plugin in rancher-logging. GELF support was added upstream with https://github.com/banzaicloud/logging-operator/pull/705 and is included in the current rancher-logging version (see https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-logging/rancher-logging-crd/100.0.0%2Bup3.12.0/templates/logging.banzaicloud.io_clusteroutputs.yaml#L1995)
Addresses https://github.com/rancher/rancher/issues/14062
> rancher-logging: UI for GELF output plugin

- assets/translations/en-us.yaml
- components/form/HookOption.vue
- components/form/Probe.vue
Reference #4505 
Fix localization input for lifecycle `exec` command input.
---
**_Unrelated but found during testing_**
Fixed incorrect `label` and `placeholder` for Health check readiness probe `Command To Run`.
> Fix placeholders and labels for lifecycle hooks exec command and readiness probe command

- models/app.js
- pages/c/_cluster/explorer/tools/index.vue
- utils/parse-externalid.js
#3825 
Bugfix for legacy charts always displaying latest app version, regardless of actual installed version.
Imported and updated ember/ui files `/addon/utils/parse-externalid.js` and `/addon/utils/constants.js` to be able to use `currentVersion()` in `pages/c/_cluster/explorer/tools/index.vue`
> Cluster Tools is display incorrect version for legacy apps after upgrading rancher to 2.6.0

- assets/translations/en-us.yaml
- components/FixedBanner.vue
- pages/c/_cluster/settings/brand.vue
Issue #4502 Customizable branding - Branding Config: Allow header/footer text size to be configured
- Add select dropdown with following options Extra Small (10px), Small (12px), Medium (14px), Large (16px), Extra Large (18px), Largest (20px)
1. Header Font size
1. Navigate to Configuration > Global Settings > Branding
2. Under **show banner in header** default font size should already be `14px`
3. Select a `Font Size` from drop down.
4. Apply the changes.
5. Header font size should change accordingly.
1. Footer Font size
1. Navigate to Configuration > Global Settings > Branding
2. Under **show banner in footer** default font size should already be `14px`
3. Select a `Font Size` from drop down.
4. Apply the changes.
5. Footer font size should change accordingly. …
> Allow header & footer banner font size configuration #4502

- components/nav/Header.vue
- config/product/apps.js
- layouts/default.vue
- store/index.js
This resolves the navigation behavior described in #4428 by returning `BOTH` where we would normally return `NAMESPACED`. I don't necessarily think that this is the optimal approach, but it does look to be the most straightforward for right now. To better understand why I'm proposing this change, here's a quick rundown of the issue as I see it:
* We make a decision on which menu items should be displayed based on multiple factors, the two most relevant ones for this issue are Product ID and Namespace
* Product ID is able to override namespace when defining top-level menu structure, causing items like `Cluster` to conditionally render based on route (Apps & Marketplace shows `Cluster` while Workload does not)
* Navigating to Workload after setting a namespace filter while Apps & …
> Filter Apps & Marketplace when a namespace filter is active

- components/SortableTable/index.vue
Issue #4504 - When creating new cluster flow, getting an error: TypeError: this.value.join is not a function.
- Column values can be any type. e.g. String, array etc.
- Usually the col.formatter define the component dynamically which would use to render the values. 
- In a previous commit following change was introduced that handles situations where `col.formatter` doesn't exist and has a single value and returns a string.
https://github.com/rancher/dashboard/commit/1208725f6af71e50ba3d8ff35458d54cbe4f840b#diff-1a2277d92947d83bba624b418c7879f3fa45d44df0bb93f741aa3ae7c4b7df43R421-R424
- This means that now when `col.formatter` is `LIST` component and it throws an exception because it's expecting an array, instead of a string.
- Therefore new function `formatValue()` was added to handle …
> Handle non string values in tables - #4504

- components/form/InputWithSelect.vue
- components/form/NameNsDescription.vue
- products/epinio/edit/services.vue
This PR validates that service names fulfill Kubernetes name requirements:
There is not yet validation to make sure the service has at least one key-value pair, which is required on the back end. That can be in a separate PR.
The generic key-value pair component also doesn't validate that there are no duplicate keys because its underlying data structure is an array. But the value passed into the `v-model` for that component is an object, so when you try to create pairs with duplicate keys, it just drops all duplicates except for the last one. Before changing that I'd like to ask around and verify that there are no valid use cases for duplicated keys.
> Validate Epinio service names

- store/index.js
QA has reported cases in Chrome where streaming becomes much slower than regular json after a while that I haven't been able to track down or reproduce, so disabling streaming for now.  #4512
> Disable jsonl streaming for now

- assets/translations/en-us.yaml
- components/Banner.vue
- components/ResourceDetail/index.vue
- edit/fleet.cattle.io.gitrepo.vue
- edit/management.cattle.io.user.vue
- edit/namespace.vue
- edit/provisioning.cattle.io.cluster/index.vue
- edit/provisioning.cattle.io.cluster/rke2.vue
- edit/resources.cattle.io.restore.vue
- edit/secret/index.vue
- edit/workload/index.vue
- edit/workload/storage/persistentVolumeClaim/index.vue
- mixins/create-edit-view/impl.js
- mixins/create-edit-view/index.js
- plugins/steve/actions.js
- plugins/steve/normalize.js
- plugins/steve/resource-class.js
- utils/object.js
- utils/string.js
#1324
If a save PUT returns a 409 conflict error, something has changed on the server side (/ liveValue) since they started editing and the resourceVersion submitted is too old.  This does not necessarily mean that any changes requested _actually_ conflict.  For example you might be editing the image name and someone changed the scale while you were editing.
This changes the edit flow to keep track of 3 copies of the target resource.
- value: The clone created at the time the user clicks edit that they are manipulating
- liveValue: The 'live' object still in the store (previously "originalModel")
- initialValue: A new clone created at the time the user clicks edit.  This doesn't get written to but is used to tell what the user has changed.
Then we generate a list of the changes made …
> Automatically handle conflicts on resource edit

- components/CruResource.vue
- components/ResourceList/Masthead.vue
- plugins/steve/resource-class.js
Reference #4265 
**Original Issue**
When editing a `Global Role` as Yaml, the save would fail due to `PUT` permissions being `blocked`.
---
After investigating where else this issue was happening, at least 27 different instances had `blocked-PUT` permissions and would cause the `Edit as Yaml` to fail.
This PR removes `Edit Yaml` from a resource's `availableActions`, as well as the `Edit as Yaml` button in the `CruResource` component.
---
_List of known areas with `blocked-PUT` permissions:_
`cluster`
- Project/Namespaces 
- Edit Project
- More Resources
- Cluster Provisioning 
- Mgmt Cluster
- Rancher
- APIServices
- Auth Providers
- Catalogs
- DynamicSchemas
- GlobalRoleBindings
- KontainerDrivers
- Mgmt Clusters
- NodeDrivers
- UserAttributes
- Workspaces
- CatalogTemplates
- …
> Remove Edit as Yaml button for blocked-PUT resource methods

- assets/styles/base/_variables.scss
- assets/styles/global/_columns.scss
- assets/translations/en-us.yaml
- components/ActionMenu.vue
- components/NavDropdown.vue
- components/SortableTable/index.vue
- components/nav/Header.vue
- components/nav/TopLevelMenu.vue
- components/nav/Type.vue
- detail/workload/index.vue
- layouts/default.vue
- pages/auth/login.vue
- pages/c/_cluster/explorer/index.vue
- pages/home.vue
- utils/position.js
* Adds screensizes to be used as shorthand in class-names
* Smaller screens will shift from row to column flex directions
* Size-specific span classes for explicit responsive columns
* Action menu on tables now works regardless of scroll position
* Dashboard header scrolls horizontally rather than growing the width of the whole page
* TopLevelMenu spans full width of viewport on mobile now
* Secondary side-bar is now a dropdown on mobile
* Tables scroll internally so that they don't break the page layout
* Login page is now a single column with no image
> Addresses #4215 - Mobile UI/UX

- components/ContainerResourceLimit.vue
- components/form/ResourceQuota/Row.vue
- components/form/UnitInput.vue
- edit/autoscaling.horizontalpodautoscaler/metric-target.vue
- edit/harvesterhci.io.volume.vue
- edit/kubevirt.io.virtualmachine/VirtualMachineCpuMemory.vue
- edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/existing.vue
- edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue
- edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/volume.vue
- utils/units.js
#4417 - this PR fixes/simplifies/clarifies UnitInput's ability to parse and format SI values. There are some kubernetes resources with fields that accept either an integer base unit or a string with an exponential modifier; eg ResourceQuota memory reservation can be specified as an integer 524288 (Bytes) or string "0.5Mi" (Bytes) or "512Ki". UnitInput had some code that looked intended to deal with these type of values but it wasn't quite working, and was hard to follow...
Namespace/workload resource limits used a different component to parse SI values, Projects used the vanilla UnitInput (simply doesn't work right in that case, hence the bug report), and the Harvester team added two more props to UnitInput to deal with it in a different way. All that now works in the same way with this …
> Bugfix UnitInput being used for SI units

- components/form/ChangePassword.vue
- edit/management.cattle.io.user.vue
Wait for the change password response and show the error it contains on the edit screen, instead of blindly continuing.
> Show change password errors on edit

- assets/translations/en-us.yaml
Issue:
- https://github.com/rancher/rancher/issues/34592
The global `catalogs-manage` role grants the following permissions:
```yaml
rules:
- apiGroups:
- management.cattle.io
resources:
- catalogs
- templates
- templateversions
verbs:
- '*'
```
which don't apply to `catalog.cattle.io` resources, so change name to `Legacy Configure Catalogs` to indicate this
> catalogs-manage display name

- pages/c/_cluster/_product/projectsnamespaces.vue
Issue #4455 - Projects in "Group by Project" view are duplicated
- `/v1/namespaces` contains properties `field.cattle.io/projectId: p-b8pkf` or  `local:p-b8pkf`.
- `/v1/management.cattle.io.projects` has  `id:"local/p-b8pkf"`.
- This discrepancy in the properties cause the filter to break.
https://github.com/rancher/dashboard/blob/a17c7de013b524e970377b266fa15b95b45f0308/pages/c/_cluster/_product/projectsnamespaces.vue#L80-L83
- Fix was applied on UI iterate over the projects and match the IDs, instead of API to compensate for this discrepancy.
1. Navigate to Explore Cluster > Local -> Projects/Namespaces
2. Scroll down and you should now only see 1 project view
> Fix duplicate "Group by Project" views in Groups/Namespace - #4455

- edit/fleet.cattle.io.cluster.vue
This resolves an issue with Fleet Cluster labels that were not saving through the UI by removing the metadata assignment and just invoking `this.normanCluster.save()`.
Two things were uncovered while investigating this one:
1. `NormanModel` doesn't contain `_labels` or `_annotation` properties. This is a concern of mine, because there was an update from not too long ago that explicitly makes use of these properties and I don't believe that to be a mistake. This leads me to believe something has changed, but I don't know what
2. Assigning metadata values to the `labels` and `annotations` properties in `NormanModel` doesn't seem to make sense before saving. The labels component invokes `value.setLabels()` on `input`; `plugins/steve/norman-class.js` simply updates `this.labels` when …
> Resolve fleet cluster label saving issue

- assets/translations/en-us.yaml
- components/form/WorkloadPorts.vue
- models/workload.js
Reference #4398 
**Original issue**
When editing a workload's service ports, if you change the `serviceType` and use the original name the config will not be saved.
**Cause**
This bug is caused by Kubernetes attempting to create a new service with a name that is being used by an existing service. 
According to the [Kubernetes docs](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types) a `ClusterIP` is necessary for both `NodePort` and `LoadBalancer` service types.
>ClusterIP: Exposes the Service on a cluster-internal IP. Choosing this value makes the Service only reachable from within the cluster. This is the default ServiceType.
NodePort: Exposes the Service on each Node's IP at a static port (the NodePort). A ClusterIP Service, to which the …
> Add warning banner for existing workload port service names

- assets/translations/en-us.yaml
- components/nav/Header.vue
- models/management.cattle.io.cluster.js
- models/namespace.js
This PR is in reference to #4270 to bring back the ability to copy the kubeconfig for clusters.
Converted the button in the navigation header for downloading the kubeconfig yaml of the current cluster into a dropdown which consists of two options: `Download KubeConfig` and `Copy KubeConfig to Clipboard`
Also added an option in the action-menu of each project/namespace to copy the config to the clipboard.
https://user-images.githubusercontent.com/40806497/135504487-4a71ee75-b92d-4bcf-8c4c-734c870ca754.mp4
> Add ability to copy kubeConfig of current cluster and projects/namespaces to clipboard

- models/management.cattle.io.cluster.js
- models/provisioning.cattle.io.cluster.js
Addresses #4007 
This PR fixes the visibility of 2 cluster actions in Cluster Management:
- Snapshot - for RKE1 clusters we check for the backupEtcd action
- Download Kubeconfig - we check for the generateConfig action
This should ensure that these actions appear correctly based on the user's permissions.
> Fix visibility of some cluster actions

- components/CruResource.vue
- store/type-map.js
Addresses #4581 
resourceMethods might not exist in the schema - which it does not on the monitoring route, leading to an error.
This PR fixes this bug.
> Fix can't create monitoring route

- detail/namespace.vue
- pages/c/_cluster/_product/projectsnamespaces.vue
- https://github.com/harvester/harvester/issues/1574
For projects without namespace we should also show them in the list, otherwise there is no way to create namespace in the project
> HARVESTER: fixed multi-cluster projectNamespace error

- plugins/steve/subscribe.js
- utils/socket.js
- https://github.com/harvester/harvester/issues/1377
- https://github.com/rancher/dashboard/issues/4347
**Verify Steps**
- Login Rancher, and check `window.s.state.rancher.socket.autoReconnect` in chrome dev console, That would be "true"
- Logout and Login again, check `autoReconnect`, the value should be "true".
**Addictionl Context**
https://github.com/harvester/harvester/issues/1377#issuecomment-971382356
> Fix ws won't reconnect after user logout and then login

- models/provisioning.cattle.io.cluster.js
- Cluster Management --> Clusters list --> second(ish) action
> Fix missing action label for download kubeconfig

- edit/provisioning.cattle.io.cluster/RegistryConfigs.vue
- edit/provisioning.cattle.io.cluster/rke2.vue
This PR addresses https://github.com/rancher/dashboard/issues/4137
1. I set up a private registry
2. Provisioned a K3s cluster, and in the **Registries** tab I went to **configure advanced containerd mirroring and registry authentication options**
3. Clicked **Add registry** and entered hostname
4. In the authentication section, created an HTTP basic auth secret for the private registry credentials
5. Clicked **Create** and saw that the cluster was successfully provisioned using the private registry
I tested it on RKE2 as well and it worked.
Initially the private registry didn't work with the RKE2 cluster, but it worked after I made sure that the registry included all the images for the specific RKE2 version (rke2-images-all.linux-amd64.txt). …
> Save secret when provisioning cluster with registry

- pages/c/_cluster/explorer/tools/index.vue
Addresses #3825 
Version numbers looked fine for me - but there was an issue where with the v1 app installed, the v2 app was showing as being installed - this PR updates the logic for this in Cluster Tools.
> Fix logic for enabling/disabling legacy v1 cluster tools

- assets/translations/en-us.yaml
- components/dialog/ForceMachineRemoveDialog.vue
- config/labels-annotations.js
- models/cluster.x-k8s.io.machine.js
Reference #4538 
This adds support for force removing a RKE2 pool in a cluster that is stuck in deleting state.
https://user-images.githubusercontent.com/40806497/142700416-49c0ea41-f517-491b-973d-b794b2f15330.mp4
**To Test**
On 2.6-head commit id: 78b25c3
- Deploy an RKE2 cluster with 2 nodes
- Invalidate the cloud credentials used to provision the cluster by deleting the access token on the cloud provider side (e.g. Digital Ocean / AWS API token).
- Delete the cluster
- The cluster is stuck in deleting state
- Select `Force Delete` from action menu for a node
- The node get removed and the cluster gets deleted from rancher
> Add action for node force-machine-remove

- components/HardwareResourceGauge.vue
- pages/c/_cluster/explorer/index.vue
Addresses #4609 
- Pod used count was coming from the reserved metric and was 0, leading to the gauge being hidden. Fixed to use the pod count
- Also fixed alignment issue between the used and reserved gauges
> Fix pod count gauge

- components/form/KeyValue.vue
Addresses #4619 
Simple fix to ignore blank lines when parsing key/values from file
> Fix env var import extra empty value

- components/nav/Group.vue
- layouts/default.vue
- models/provisioning.cattle.io.cluster.js
#4051 - This PR disables the yaml-editing view for RKE1 provisioning clusters because they can only be edited through the iFramed ember ('config' views). This PR also fixes a more general nav bug outlined in the comments that still applies to the 'view yaml' action for rke1 clusters.
> Prevent edit-as-yaml for RKE1 clusters

- components/form/KeyValue.vue
- components/form/Taints.vue
Addresses #4371 
This is a specific fix for the KeyValue alignment issue.
I've reduced the height of the controls - I think this looks better as well as fixing the alignment issue.
I can review the controls after 2.6.3
> Fix alignment of KeyValue control

- assets/translations/en-us.yaml
- config/types.js
- models/catalog.cattle.io.app.js
- pages/c/_cluster/apps/charts/install.vue
This is in reference to rancher/dashboard#4120 where an App created with the old UI would send an error when trying to edit/update: `Cannot read property 'annotations' of undefined`.
According to https://rancher.com/docs/rancher/v2.6/en/helm-charts/ , any App that has been managed by the Cluster Manager (old UI) should continue to be managed only by the Cluster Manager. 
The actual error in this case with OpenEBS was caused by the App utilizing a chart (`2.5.1`) that no longer exists in the default repositories. This PR will check if an App has a chart that is not within the repositories and will disable the `Edit/Upgrade` option from the action menu.
To reproduce:
1. Navigate to `localhost/g/apps` and launch OpenEBS.
2. Navigate to Cluster > Apps & Marketplace > Installed Apps
3. Then …
> Remove edit/upgrade action from Apps with no chart

- assets/translations/en-us.yaml
- components/PromptModal.vue
- components/dialog/RollbackWorkloadDialog.vue
- models/workload.js
This pr addresses issue #4229 by adding a code diff modal to the workload deployment rollback process.
To test this PR:
1. Create a Deployment under Workloads using a specific nginix Image of your choosing. (eg 1.21.1)
2. Edit Config the newly created deployment and change the nginix Image to another version (eg 1.21.2)
3. Now that you have an multiple revisions you can select the Rollback menu option for the deployment
4. When the modal displays, select your previous revision and click the Show Diff button to display the yaml code diff
> Forward port feature to see difference when rolling back a workload

- config/local-storage.js
- middleware/authenticated.js
- store/index.js
#4478 - this PR ports the URL-preservation logic from the Ember UI to the dashboard. The URL is saved the same way a the [old ui ](https://github.com/rancher/ui/blob/98c658f5eb2a3e5a139fa9cfc76ee7810cb67526/app/application/route.js#L171) so if a user gets booted to the dashboard login from an Ember route they'll be redirected back to that page.
> Auth redirect preserve destination URL

- components/SortableTable/index.vue
This resolves and issue with long contiguous strings of text would cause table contents to extend outside their container.
> Overflow wrap long text for state description

- components/nav/NamespaceFilter.vue
- store/index.js
- store/prefs.js
#3523
[This change](https://github.com/rancher/dashboard/commit/ad83a8fd970488dc1d3e5948fcd20db774645617#diff-2886ae8dc0ffc0d351cc2e75fe977ac32d0067891113a6ec3c25c3761edb9633R613 ) caused the immediate complaint.. the default for actual filtering changed to be `[]` (== All Namespaces) while the dropdown still defaulted to `['all://user']` (== All User), so the dropdown showed all user but the ui applied all namespaces.
This is not the original issue's problem, since this didn't exist yet, but the original was also not reproducible anyway...
- Fix defaults to match (above)
- Use constants everywhere instead of strings that have to match spread around
- Fix `cleanNamespaces` always clearing all the saved values so that it will actually remember multiple namespaces
- Use `getters.byId` …
> Namespace filter fixes

- assets/translations/en-us.yaml
- config/query-params.js
- pages/c/_cluster/apps/charts/index.vue
- store/catalog.js
rancher/dashboard#4223
- The options will show if there is at least 1 linux and windows worker node.
- The option will be defaulted to the OS with the most worker nodes or to All OSs if there are equal nodes. 
- The page will only show windows charts if theres at least 1 windows worker node and 0 linux worker nodes.
- The page will only show linux charts if theres at least 1 linux worker node and 0 windows worker nodes.
If you don't have access to windows nodes I tested this by just modifying the count at the top of the fetch method:
> Adding operating system filtering tot he charts page

- components/nav/Group.vue
- cypress.json
- layouts/default.vue
As part of this pr #4617 I attempted to make nav groups re-sync when the route changes, so the correct group is expanded when navigating directly to a resource per [this](https://github.com/rancher/dashboard/issues/4051#issuecomment-974306842) comment, but this change borks group expansion for a few resources with a different route structure, like projects/namespaces. This PR updates the nav logic so that:
- a nav item is considered active if the current route's cluster, product, and resource params match if defined, or if the full path is exactly the same
- if the currently expanded group contains an active nav item, the nav tree wont expand other groups
You can see how it was broken/is fixed by running the e2e `inappmenu.spec.ts` tests
> fix default nav group expansion

- components/form/WorkloadPorts.vue
- models/workload.js
https://github.com/rancher/dashboard/issues/4398#issuecomment-977689584 - I figured this was related to the solution I suggested to Jordon so I picked up this ticket. I found two underlying problems going through the repro steps outlined in that comment. 
One is that in the process of updating `getPortsWithServiceType` to not overwrite a workload port's `_serviceType` we inadvertently stopped auto-assigning names to unnamed ports prior to saving. The name is used to map between services' ports and ports as they're defined in the workload spec so that was breaking the edit page - both the ability to change an existing listening port and to change the service type associated with a port. 
The other issue I found was that the 'Listening Port' input change's weren't being tracked. This took …
> Fix listeningPort reactivity, workload port service type editing #4508

- models/cluster.x-k8s.io.machine.js
Reference #4538 
This is an update to this PR that has been merged (#4592). The new condition for determining if a machine can be removed by force is now the `InfrastructureCondition.reason` equal to `DeleteError` instead of `DeletionFailed`.
---
**`InfrastructureReady` condition example**
---
https://user-images.githubusercontent.com/40806497/143927321-7febac0f-527f-4d43-83c7-f0ee40e8a3fa.mp4
---
**Version used**
> Update isRemoveForceable return message condition

- components/form/SecretSelector.vue
- edit/logging.banzaicloud.io.output/providers/elasticsearch.vue
- edit/logging.banzaicloud.io.output/providers/forward.vue
- edit/logging.banzaicloud.io.output/providers/kafka.vue
- edit/logging.banzaicloud.io.output/providers/loki.vue
- edit/logging.banzaicloud.io.output/providers/splunkHec.vue
- edit/logging.banzaicloud.io.output/providers/syslog.vue
Several logging output fields for ca and client certificates need to be provied as a file path in the fluentd config. For this, the secret which contains the value must be referenced in the output yaml with mountFrom instead of valueFrom. See https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/secret/.
Addresses https://github.com/rancher/rancher/issues/31810
Backports #4406 into release-2.5
#4578
> [2.5.12] rancher-logging: Fix generated YAML for logging output fields referencing file paths

- components/form/KeyValue.vue
- edit/provisioning.cattle.io.cluster/RegistryMirrors.vue
This PR addresses https://github.com/rancher/dashboard/issues/4701. 
This fix makes it so that if you provision an RKE2 cluster with a private registry with a mirror, the mirror will render properly in the edit config form. The relevant cluster YAML is as follows:
```
registries:
mirrors:
registry1.com:
endpoint:
- registry2.com
```
Before:
After:
> Private registry mirrors in YAML are properly displayed in form

- components/form/KeyValue.vue
- components/form/SelectOrCreateAuthSecret.vue
- edit/provisioning.cattle.io.cluster/RegistryConfigs.vue
- edit/provisioning.cattle.io.cluster/RegistryMirrors.vue
https://github.com/rancher/dashboard/issues/4137
This PR solves a problem where if you create multiple secrets at once, only the last secret was created. The cause was that each secret used the same beforeSaveHook with the same name as all the others, so the last one would override the others. This PR gives a unique ID to the hooks so that multiple secrets can be created at once.
To test this PR, I created an RKE2 cluster with the private registry values in the section called `Configure advanced containerd and registry authentication options`:
- registry hostname for Rancher images: registry1.com
- mirrors: registry1.com => registry2.com
- registry authentication:
- registry1.com: Create a HTTP Basic Auth Secret (used random inputs)
- registry2.com: Create a HTTP Basic Auth Secret (used …
> Prevent registry secrets from overriding each other

- assets/translations/en-us.yaml
@n313893254 I think I previously recommended the older text during a PR review, however in hindsight the instructions refer to the `Settings` location in a multi-cluster environment instead of the target harvester cluster's single cluster `Settings` location. Is this new change correct?
> Update import a Harvester Cluster instructions

- components/nav/Group.vue
Addresses #4695 
We were only removing the URL hash when comparing - this PR updates to remove the query string as well
> Fix minor issue where changing filter collapsed side nav

- detail/provisioning.cattle.io.cluster.vue
- Looks like the `provisioning.cattle.io.cluster` `provisioner` property now changes from `imported` to `<detected type>` on successful import.
- This causes the node/node pool tab in the cluster management cluster page to be hidden (gates fetching nodes on   `this.value.isImported || this.value.isRke1`).
- We now always try to show machines pools / machines first and if not available fall back on node pools / nodes.
- This does lead to a longer load time, but removes any imported/rke1 shenanigans
Addresses https://github.com/rancher/dashboard/issues/4711
> Ensure node pool / nodes are shown for imported clusters

- components/nav/Header.vue
- pages/auth/login.vue
- pages/auth/logout.vue
- store/index.js
Fix issue of double log in #4716
- Only happened after logging out
- On log out flow goes Header logout button link --> logout.vue page --> auth/logout action --> onLogout action
- in onLogout a `backTo` was being set to the logout page
- when the user then logged in ui redirected to the `backTo` location, which was the logout page
Improvements to the logout process 
- in logout page remove duplicated redirect to login page (always happens in onLogout)
- ensure the login and logout pages are never saved as the backTo location (not just checking a param)
Remove wiggle of login page components #4202
- If an error banner or message is shown avoid the content jiggling when the user attempts to log in again
> Fix double log in and other log in fixes/improvements

- list/management.cattle.io.cluster.vue
This fixes an issue where all the management clusters are listed while exploring a downstream cluster by getting a list of management clusters for the current product. This means that Cluster Management => Advanced => Mgmt Clusters should remain unchanged, as the product is still `management`, while Cluster Management => { downstreamCluster } Explore => More Resources => Rancher => Mgmt Clusters should only list the management clusters for the given product. 
#4667
> Get list of management clusters for the current product

- models/catalog.cattle.io.app.js
Addresses #4402 
When an app is migrated, the /v3/project resource is deleted, so the API call we do fails and this breaks the UI.
This PR wraps this in a try/catch, so we don't fail if the legacy app can not be found.
> Fix issue where app upgrade fails is no v3 project resource

- pages/c/_cluster/explorer/tools/index.vue
Addresses #3825 
This PR adds version upgrade info to the Cluster Tools page for V legacy apps.
Previously we did not show this for v1 apps - since this keeps coming up, I've added this.
> Show upgrade info for legacy apps on cluster tools

- components/form/ResourceQuota/Namespace.vue
- components/form/ResourceQuota/NamespaceRow.vue
- components/graph/Bar.vue
- edit/namespace.vue
- The default value was overwriting the already set value when editing a namespace
- Editing wasn't working when the user switched projects in the middle of editing resource quotas
- Now hide the resource quota tab if there aren't any resources the namesapce should set
- Fixed two warnings related to the keys that we being used
https://github.com/rancher/dashboard/issues/4412#issuecomment-986487125
> Fixing several ResourceQuota issues

- models/catalog.cattle.io.app.js
Reference #4676 
**Original Issue**
If an app was launched using the old UI (prior to v2.6.3) it should no longer be upgrade-able from the dashboard. The `Upgrade Available` button is still showing, although the user will not be able to upgrade the app.
**Fix**
This will remove the upgrade available button from the list view for an app that is considered `legacy` or `multi-cluster`.
**To Test**
- `rancher:v2.6.2` is required to install an app using the Ember UI.
- Follow the instructions [here](https://github.com/rancher/dashboard/issues/4121#issuecomment-983813921) to install the app.
- Check the `Installed Apps` page to see upgrade icon is removed.
> Add check for legacy or mcapp to remove upgrade button

- components/form/ResourceQuota/ProjectRow.vue
This fixes a bug where the Project Limit display unit for the Memory Limit resource quota was `MB` instead of `MiB` by adding an increment to the field in question. 
The display unit was displaying as `MB` because `components/form/UnitInput.vue` has a default value of `1000` for increment and will only format as `MiB` if the increment is 1024.
#4742
> Add increment to Project Limit unit input

- edit/workload/index.vue
[Reference](https://github.com/rancher/rancher/issues/35690)
**Original error**
After editing a Node Port for a deployment workload, the `publicEndpoint` is not updated accordingly. The UI would show the original endpoint when in fact the endpoint had been updated to the intended port.
**Cause**
The `workloadSelector` label was not being set on the deployment metadata, and therefore wouldn't update the `publicEndpoint` route. See [this comment](https://github.com/rancher/rancher/issues/35690#issuecomment-988342391).
**Fix**
This will add the correct `workloadSelector` label to the deployment's `metadata.labels`.
https://user-images.githubusercontent.com/40806497/145477646-8cb63b33-95cb-497b-8be0-978a4c163528.mp4
> Add workloadSelector to deployment metadata labels

- edit/provisioning.cattle.io.cluster/rke2.vue
- https://github.com/harvester/harvester/issues/1658
- should set RKE2 default cloud config path to  `/var/lib/rancher/rke2/etc/config-files/cloud-provider-config` via `helmChartConfig` as the default path of chart is updated via https://github.com/harvester/charts/pull/58/files#diff-00e1ad718da686a8dd7b7dd718d74b46cbf640b160fcd09e51e4ef5edcb59922R14
> HARVESTER: Update RKE2 default cloud config path

- models/catalog.cattle.io.app.js
- plugins/steve/getters.js
This PR addresses https://github.com/rancher/dashboard/issues/4720 by adding some error handling to the app install/upgrade page.
Specifically, when we check to see if an app is a multi-cluster app, we fetch all multi-cluster apps, then check to see if the current app is named in the results. If we don't have permission to fetch all multi-cluster apps, we assume the current app is not a multi-cluster app. Vince said this may not always be a safe assumption, but it is the best solution for now. In the future if we keep having issues, we can request the backend to add an annotation to apps to make it easier for the UI to determine which type of app it is.
1. I created a standard user
2. While logged in as the standard user, I created a downstream cluster
3. I installed a v2 …
> Standard user can upgrade apps

- assets/translations/en-us.yaml
- components/CountGauge.vue
- components/form/PlusMinus.vue
- components/formatter/WorkloadHealthScale.vue
- detail/workload/index.vue
- models/workload.js
- previously workload list and detail used pod status phase
- pod status phase can sometimes appear contradictory to pod state (#4745)
- so show the same in all three locations
- Note - Job related workloads remain unchanged
Also
- Workload detail count gauges... don't show percentage doughnut if they're
all just circles (all in one state). Without variance these are confusing
> Use same metric for pod state in workload list, workload detail and pod lists

- components/form/ResourceQuota/NamespaceRow.vue
This adds a suffix of `i` if the increment is `1024` when trying to parse values for the namespace row resource quota. Similar to what we do with `components/form/UnitInput.vue`, we want to make sure that we're making use of the binary modifier when working with unit conversions.
This is a quick-fix that works for the namespace row, but I'm thinking that we might want to review a better place to handle this directly in `utils/units.js`.. I didn't want to make that change today and risk breaking something elsewhere without more thorough testing.
See https://github.com/rancher/dashboard/issues/4412#issuecomment-994876515 for testing instructions
#4412
> Add a suffix of 'i' to when increment is 1024

- pages/auth/setup.vue
- `.eula span` was previously not applied due to scoping, but a recent change meant it then did
- this caused the T&C checkbox label to have a double margin, so removed the style to fix
- ![image](https://user-images.githubusercontent.com/18697775/146347124-a6076d06-0cc6-44c5-a6dc-8be1b0eeab79.png)
- also removed the parent `.eula` link as this isn't required
> Remove unrequired & unused styling

- models/catalog.cattle.io.app.js
- This ensures standard apps show the upgrade
- It will also show an upgrade button for legacy / multi-cluster apps
- Legacy / mcapps button will take user to non legacy / mcapps install page
which guides user to legacy install world
- This needs updating post-2.6.3, it's not a great solution but removes a blocking issue in a safe way. See https://github.com/rancher/dashboard/pull/4795#pullrequestreview-835364056 for more context
- #4786
> Ensure apps and marketplace app upgrade button shows

- models/fleet.cattle.io.cluster.js
- models/management.cattle.io.fleetworkspace.js
https://github.com/rancher/dashboard/issues/4798
- Caused by the `CreateEditView` component's `actuallySave` trying to `assign` annotations when no set'er exist in the root resource
- The steve workspace uses a norman.save()... and returns itself a norman object which is assigned to the initial steve object
- short term fix - skip this assign step
- long term - ensure we return the updated steve object. also need to investigate other `return norman.save()` uses
https://github.com/rancher/dashboard/issues/4799
- The assignTo modal tries to clone the norman cluster, this fails as the steve fleet cluster is looking for the norman cluster using the wrong id (metadata.name --> mgmt.id)
- long term - we need to also investigate if the labels are correctly assigned
> Fix two fleet issues

- config/labels-annotations.js
- pages/c/_cluster/apps/install.vue
Backport reference #4812 - Addresses #4402
This PR checks for the presence of the migrated app annotation and when present will also send that annotation when performing an upgrade.
> [2.5.12] Pass migrated annotation for apps 

- models/fleet.cattle.io.cluster.js
- Follows on from https://github.com/rancher/dashboard/pull/4801
- edit/fleet.cattle.io.cluster uses `labels?.[FLEET_LABELS.CLUSTER_NAME]`
- this change simply matches that
> Ensure fleet cluster fetches norman cluster in a consistent way

- components/dialog/RollbackWorkloadDialog.vue
This pr addresses issue #4636 by adding 1) yamleditor diff types 'Unified/Split' and 2) filtering out unnecessary yaml diff fields
To test this PR:
1. Create a Deployment under Workloads using a specific nginix Image of your choosing. (eg nginix:1.21.3)
2. Edit Config the newly created deployment and change the nginix Image to another version (eg nginix:latest)
3. Now that you have an multiple revisions you can select the Rollback menu option for the deployment
4. When the modal displays, select your previous revision and click the Show Diff button to display the yaml code diff
5. Unnecessary yaml keys such as apiVersion, kind, metadata, etc are no longer shown in the code diff
> Code diff for rolling back a workload improvements

- yarn.lock
Update caniuse-lite to avoid the console messsages:
Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
NOTE: I did this manually, since using the command `npx browserslist@latest --update-db` updated yarn.lock to use`registry.npmjs.org`for this package.
> Upcate caniuse-lite

- assets/translations/en-us.yaml
- components/PromptRestore.vue
- models/provisioning.cattle.io.cluster.js
This PR aims to add the Restore Snapshot functionality to the Cluster Management view. 
Currently you are able to Take Snapshot from cluster view, but need to enter the cluster detail view in order to restore a snapshot. 
To test this PR: 
1. Create an RKE1 cluster
2. Create a few snapshots
2. From Cluster Management, select 'Restore Snapshot' from the action menu
3. The PromptRestore modal should display with a dropdown list of the newly created snapshots
https://github.com/rancher/dashboard/issues/4606
> "Restore snapshot" action is not available in Cluster management page

- edit/monitoring.coreos.com.prometheusrule/AlertingRule.vue
issue: https://github.com/rancher/rancher/issues/35331
fix(alerting-rule): fix prometheus alerting rule unit conversion error
Refer to the following website to convert `wait fire for` duration to seconds
https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/#rule
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#duration
> fix(alerting-rule): fix prometheus alerting rule unit conversion error

- pages/c/_cluster/apps/install.vue
This PR addresses https://github.com/rancher/dashboard/issues/4812 by moving the code that checks if an app is migrated to a different context where it has access to the app data. Previously it was returning false for the app migrated status because it didn't have access to the data, so migrated app upgrades were failing on the first attempt.
This PR can't be merged yet because apps still aren't upgradeable because when the app is upgraded, the UI is replacing the existing values of the app with null values. The null values cause the app to get stuck in a pending state and give the error that its image is invalid. Edit: Now it works due to Neil's fix
I tried capturing the helm chart values in different scenarios. For an app with the migrated annotation that was upgraded first …
> Include migration annotation when upgrading apps in v2.5

- edit/auth/github.vue
- mixins/auth-config.js
- When configuring the github auth provider we show a notice at the bottom regarding the local user that will be paired with the github user
- This was empty as it relied on `principal`s being fetched in a mixin's fetch
- As the github component had it's own fetch the mixin fetch wasn't called
-  https://nuxtjs.org/docs/features/data-fetching/
- Now we can call the underlying mixin's fetch from a parent component
> Fix display of username in Github auth note

- models/fleet.cattle.io.gitrepo.js
- `fleet.cattle.io.GitRepo` `spec.targets` can contain multiple selectors per target
- https://fleet.rancher.io/gitrepo-targets/#target-matching
- (WIP - Just waiting on more feedback from fleet team)
- The UI only shows form components for single selector targets, anything else is an 'advanced' mode where user can enter free text/yaml 
- When attempting to edit a GitRepo that has a multi-selector target we previously weren't detecting this and forcing the user to use a single target mode (thus removing anything else in that target on save)
- We now correctly identify this case and start in the correct 'advanced' mode
- Addresses #4788
> Fix edit Fleet GitRepo initial target mode

- edit/workload/index.vue
This PR addresses issue #4811 by making 'Service Name' a required field when creating a StatefulSet
To test this pr
1. From your cluster navigate to Workload > StatefulSets
2. Click the Create button
3. The 'Service Name' field should now have a red 'required' asterisk
> StatefulSet "Service Name" required, but not marked

- edit/group.principal.vue
- list/group.principal.vue
- pages/c/_cluster/auth/group.principal/assign-edit.vue
- Correctly gate the visibility of the button on roles rather than if principal list contains a group
- principal list can contain some groups ... or none at all (an auth provider can return many many principals so list is trimmed)
- Ensure fetching spoofed group.principal uses correct store (auth product uses management store)
- Ensure navigation to and from assign roles page uses the blank cluster in routes (restricted user does not have access to local)
- Addresses #4834
> Fix assign global roles as Restricted Admin

- components/auth/SelectPrincipal.vue
- name is normally used as a primary label, so sort on that
- only sort the initial suggestion, not the response of a search
- search response should hopefully be sorted with respect to proximity to the query
- Addresses #4685
- This effects anywhere we show the option to select a principal, for instance in the Groups --> Assign Roles page 
- ![image](https://user-images.githubusercontent.com/18697775/148519862-a6c3bb46-956b-4a14-911d-fde988da7914.png)
- As per above this PR does not sort the principals shown after the user has searched for one, the result set that comes from the backend should be sorted given the proximity to the search 
Note - If there's any strangeness with the visibility of the groups assign button I'll update this PR with #4880
> Sort initial suggestion of options in the select principal drop down

- components/ActionDropdown.vue
- components/SortableTable/actions.js
- components/SortableTable/index.vue
- models/harvester/kubevirt.io.virtualmachine.js
- Move actions that wrap into the existing actions drop down (redesign todo)
- Remove the hard-coded action 'external' property which was previously determining actions drop down
- This was only used in one place (see screenshots below) 
- Also moved list bulk action code out from SotableTable and into their own mixin
- Addresses #4873
> Dynamically group list bulk actions into dropdown given available width

- components/dialog/RollbackWorkloadDialog.vue
This sorts the list of revisions by the revision number. It looks like there are some scenarios where revisions can be received out of order, so we make use the revision number to sort revisions in descending order.
#4842
> Sort revisions by revision number

- assets/translations/en-us.yaml
- edit/logging.banzaicloud.io.output/providers/elasticsearch.vue
- edit/logging.banzaicloud.io.output/providers/utils.js
This PR addresses https://github.com/rancher/dashboard/issues/4753 by adding two fields to the logging output form for Elasticsearch. These fields allow you to configure the YAML directives `ssl_version` and `ssl_verify`.
The Ember equivalent is in the above linked issue. In the internal ticket for this issue, it said we should make `ssl_verify` true by default.
1. I installed the logging application on a downstream cluster
2. Went to the downstream cluster's dashboard and clicked **Logging > Outputs**
3. In the **Output** type dropdown, selected Elasticsearch (not AWS Elasticsearch)
4. In the Connection section, verified that the new **SSL Version** dropdown has the same options as Ember did (TLSv1_2, TLSv1_1, SSLv23 and TLSv1). Source: …
> [Forward port] Can configure SSL version, SSL verify in Elasticsearch Output form
