- shell/models/provisioning.cattle.io.cluster.js
**Updating master with the fix**
Fixes #8393 
- add check to `resourceMethods` property so that UI doesn't fail when `clusterTemplatesSchema` is empty due to restricted access by the user
- Provision a `rancher - 2.7-head commit id: 70455b1 ` system
- As an admin, create a `base user` and add `Create new Cluster` role and `Create new RKE Cluster Templates` role.
- Login as the user just created
- Create an RKE1 cluster (use Digital Ocean, for example)
- Check that the `Cluster Management` page or the `homepage` doesn't break when displaying the list of clusters
> Fix error listing clusters for a base user (fix for master branch)

- shell/assets/translations/en-us.yaml
- shell/components/form/MatchExpressions.vue
- shell/edit/networking.k8s.io.networkpolicy/PolicyRuleTarget.vue
Fixes #7660
This PR will introduce the possibility to define a single `to/from` entry that specifies both `namespaceSelector` _and_ `podSelector` that selects particular Pods within particular namespaces.
see k8s doc: https://kubernetes.io/docs/concepts/services-networking/network-policies/#behavior-of-to-and-from-selectors
> Network Policy, combine `podSelector` and `namespaceSelector` in the same rule

- shell/assets/translations/en-us.yaml
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #8123
- Corrected URL with full path as documentation is located outside of Rancher official documentation
- Prevent to display banner on creation
https://user-images.githubusercontent.com/5009481/224400541-4d7bdd68-2cb1-40fd-b36d-8cb441c4c704.mov
> Correct base path with absolute value for RKE2 CIS hardening documentation and avoid banner on creation

- shell/assets/translations/en-us.yaml
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes https://github.com/rancher/dashboard/issues/8123
Backport https://github.com/rancher/dashboard/pull/8396
> [2.7.2] Correct base path with absolute value for RKE2 CIS hardening documentation and avoid banner on creation

- shell/assets/translations/en-us.yaml
Fixes https://github.com/rancher/dashboard/issues/8426
Also made a grammatical adjustment to the checkbox label so we can use precisely the same name for the psact:
> update rke2 psa dropdown label

- docusaurus/docs/code-base-works/on-screen-text-and-translations.md
- docusaurus/docs/extensions/advanced.md
Reference #8310 
This adds information for extensions regarding translations. Since the existing documentation for localization is rather extensive and applies, I felt we could reuse this as much as possible.
Also updated the title for Localization to `l10n` from `i10n`.
> Add extension translation docs

- shell/config/product/auth.js
Fixes #8344
This PR updates the Users & Auth product to better accomodate custom roles. Previously the product was only visible to users who can edit users and/or auth configs.
The auth config pages are created with the assumption that anyone viewing them can edit authconfigs. I did look into making this work with view-only permissions but it would require fairly substantial changes to look and behave correctly for users who can only view authconfigs. That would require re-verifying enabling, disabling, and editing every supported auth provider which is quite a lot to dump on QA for such an unlikely use-case; consequently, this PR keeps those pages hidden from users who only have get/list permissions for authconfigs. 
1. Standard users with a custom role to get/list global roles should be …
> allow users who can view roles to see the users & auth product

- shell/package.json
It turns out the dependency changes that were made from Nuxt removal were causing problems with create app and this just reverts those changes.
I've verified each of these commands work:
- `yarn build`
- `yarn dev`
- `./shell/scripts/test-plugins-build.sh`
- `docker build --no-cache -t "test:Dockerfile" .`
fixes rancher/dashboard#8376
- I will turn the workflow back on and notify our dev channel once this gets merged
- I attempted to switch back to Typescript but still no luck yet so I've opened this https://github.com/rancher/dashboard/issues/8428
> Fixing the create app files

- shell/edit/helm.cattle.io.projecthelmchart.vue
Fix setting Helm values for ProjectHelmCharts.
Fixes https://github.com/rancher/dashboard/issues/8366
The values must be stored into `spec.values` and not top-level in the resource.
Creating/Editing ProjectHelmCharts such as Project Monitors.
Before:
After:
> [2.7.2] Fix setting Helm values for ProjectHelmCharts

- shell/components/form/SimpleSecretSelector.vue
This improves the design of `SimpleSecretSelector.vue` by consuming values emitted by `LabeledSelect.vue` instead of data props that can be mutated at different times depending on the underlying usage of `selected`/`selecting` events in `LabeledSelect.vue`.
We should be able to follow-up in a another PR to revert #6302 and properly emit the `selecting` event.  
Fixes #8342
This PR better adheres the principle of uni-directional data flow by implementing the props-down, events-up pattern. 
Alertmanager Configuration: See testing notes in #8324
Alertmanager Configuration: See testing notes in #8324
> SimpleSecretSelector: Consume emitted values from `LabeledSelect`

- shell/detail/workload/index.vue
- shell/models/workload.js
Fixes #8215 
- change condition to check if buttons for scale up/scale down on deployment details are enabled
Note: Also checked the formatter WorkloadHealthScale and the condition for it to work was:
1- It's a scalable type
2- Model returns a true `canUpdate` 
So I went for that approach as well.
> Fix scaling of deployment in bad state

- shell/components/ActionMenu.vue
- shell/components/FileDiff.vue
`ActionMenu` in each row of our SortableTables
file diff function in `edit yaml` views
> Remove jquery from ActionMenu.vue, FileDiff.vue

- shell/assets/translations/en-us.yaml
- shell/dialog/GenericPrompt.vue
- shell/utils/__tests__/string.test.ts
- shell/utils/string.js
Fixes #8384
Updated text as indicated in the issue
- Enabled HTML injection within modal content
- Created test and utility to decode encoded HTML using DOM APIs
Note: [VueJS automatically escapes](https://vuejs.org/guide/best-practices/security.html#best-practices) all the strings passed as props to the components for XSS.
Since we systematically already pass HTML for i18n values, we can as well for this component.
https://user-images.githubusercontent.com/5009481/225973186-ad5322e8-9f1d-4965-b185-f3a55f7303a1.mov
> Modify PSP deprecation warning message when upgrading a K3s custom cluster to v1.25

- shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #8480 
Removed the `profile` key if it is null.
Request now looks like this:
> Fix null profile in custom cluster creation

- shell/config/router.js
Loading the dash from `https://releases.rancher.com/dashboard/latest/index.html` is broken due to malformed webpackChunkName:
I verified this fix by pushing to a `-dev` branch and updating my ui-dashboard-index setting to use that build
> fix pages/c/_cluster/auth/roles/_resource/_id webpackchunkname

- .vscode/settings.json
- shell/components/form/NameNsDescription.vue
- shell/components/form/__tests__/NameNsDescription.ts
- shell/store/__tests__/index.test.ts
- shell/store/index.js
Fixes #6094
Filtered NS options inside resource form, based on selection from top navigation filter.
- Replaced component filtering logic with state getter
- Added comments to existing logic
- Added unit tests for the component and state
- Moved logic for other filters
- Split function used by getters in more understandable bits
In resource NS filter inspect the list of the available values based on the conditions:
- Filter by user NS
- Display all NS
- Filter by NS inside projects
- Filter by single NS
- Hide/show Rancher system NS
- Local and provisioned clusters
- Filter NS which are readonly as the user has no rights to create resources ([follow these steps to reproduce](https://github.com/harvester/harvester/issues/1986#issuecomment-1261745712))
- Filter NS for products (e.g. …
> When creating a resource, limit the namespace options based on filters in top nav

- shell/edit/provisioning.cattle.io.cluster/rke2.vue
According to https://github.com/harvester/harvester/issues/3404#issue-1567534567 describe:  remove `do not check when the Harvester version is <v1.2` constrain on the upstream Rancher UI (starting from v2.7.2), we still need to validate ccm & csi maximum version, so revert PR https://github.com/rancher/dashboard/pull/8080
- https://github.com/harvester/harvester/issues/3404
**Case 1**
1. Import an existing Harvester cluster(e.g., v1.1.2-rc3) into a Rancher server
2. Spin up a guest RKE2 k8s cluster(>= v1.24.10); its built-in Harvester CCM chart version is v0.1.14
3. The Harvester cloud provider can not be selected.
**Case 2**
1. Import an existing Harvester cluster(e.g., v1.1.2-rc3) into a Rancher server
2. Change the Harvester `harvester-csi-ccm-versions` setting to …
> HARVESTER: Validate ccm & csi maximum version

- .vscode/settings.json
- shell/chart/gatekeeper.vue
- shell/chart/istio.vue
- shell/chart/logging/index.vue
- shell/chart/monitoring/index.vue
- shell/chart/rancher-backup/index.vue
- shell/components/ChartPsp.vue
- shell/components/__tests__/ChartPsp.test.ts
- shell/pages/c/_cluster/apps/charts/__tests__/install.helper.test.ts
- shell/pages/c/_cluster/apps/charts/install.helpers.js
- shell/pages/c/_cluster/apps/charts/install.vue
Fixes #8434
PSP checkbox to be displayed if K8S < 1.25 or PSP is already enabled.
This is applied for the charts:
- OPA Gatekeeper
- Istio
- Logging
- Monitoring
- Rancher Backup
- Alerting
- Epinio
- Longhorn
- NeuVector
- Prometheus Federator
- Moved markup within the component to avoid empty spaces
- Allowed to pass title for areas which require one
- Passed cluster object to parse version
- Extended tests
- Created helper to get ignored questions with variables matching the path of the current cluster (ignore logic already existed) for same condition
- Added tests to the helper, created separately due high complexity of the component (2500+ lines)
All the charts above for clusters with K3/RKE2 and K8S < v1.25 or >= 1.25 and PSP disabled/enabled
Same as above.
PSP checkbox present in …
> Custom chart UIs show PSP switch on Kubernetes v1.25

- shell/mixins/chart.js
Fixes #8491 
Two problems:
1. The `cancel` method during chart installation wasn't retaining the version selected because `versionName` is not a property on `chart`; that resource has an array of possible versions
2. If there's no version present in the route query,  we select the latest version present without filtering prereleases out when the relevant user pref is configured to hide them
* The selected chart version should be remembered when cancelling a chart install
* If the user loads the chart page w/ no version in the query, the one automatically selected shouldn't be a pre-release if there's a user pref set to hide them
> remember the chosen chart version when installation is cancelled

- shell/vue.config.js
Similar to the fix here: https://github.com/rancher/dashboard/pull/8386/commits/724d952e962243b1d663dd2f34b0c89ad88b5d71 I'm seeing requests to cloud providers eg  `.../meta/proxy/api.digitalocean.com/v2/regions?per_page=1000` fail when running the dash locally. Given that no one else has brought this up I have to think that like the other issue this isn't happening on all rancher instances; I can share my setup to repro if needed.
> fix /meta/proxy requests when running locally

- package.json
- Note - this is only required for pre 2.7 next2 due to nuxt removal
- Memory available to node can be tested with targets like
```
"e2e:debug1": "yarn run e2e:debug2 --max-old-space-size=2000",
"e2e:debug2": "node -e 'console.log(v8.getHeapStatistics().heap_size_limit/(1024*1024))'",
```
> Increase build memory for e2e tests

- shell/mixins/chart.js
Fixes #8529 
backport of https://github.com/rancher/dashboard/pull/8514
> [2.7.2] remember the chosen chart version when installation is cancelled

- shell/assets/translations/en-us.yaml
- shell/components/fleet/FleetIntro.vue
- shell/edit/management.cattle.io.fleetworkspace.vue
- shell/plugins/dashboard-store/actions.js
Fixes  https://github.com/rancher/dashboard/issues/8468
~This PR updates the workspace create/edit form to make sense for users who do not have permission to create reporestrictions and gitrepo repo-less list view for users who don't have permission to create repos.~ 
The Continuous Delivery ui is only visible to users who can view git repos. I opted not to change this because from what I understand there isn't much a user could do in the fleet ui if they can't even view repos.
~1. The workspace create/edit/detail pages should be tested by users who can:~
~a. Get/list git repos and get/list/create/edit workspaces but nothing else in fleet~
~b. Get/list git repos and repo restrictions, and get/list/create/edit workspaces~
~2. The git repo list view when no repos are present should only …
> Update fleet ui for users with fewer permissions

- shell/components/fleet/FleetIntro.vue
This PR (should) fix failing storybook builds:
```
ERR! resolve 'config/types' in '/home/runner/work/dashboard/dashboard/shell/components/fleet'
ERR!   Parsed request is a module
ERR!   using description file: /home/runner/work/dashboard/dashboard/shell/package.json (relative path: ./components/fleet)
ERR!     Field 'browser' doesn't contain a valid alias configuration
ERR!     resolve as module
```
> fix config/types import path in fleetintro

- shell/cloud-credential/generic.vue
Fixes #8523 
See comment [here](https://github.com/rancher/dashboard/issues/8523#issuecomment-1485581660) - there is an open backend issue related to this area, and this PR only fixes the messed up key/value component.
Cloud credential creation for custom cloud drivers that do not provide `<cloudconfig schema>.resourceFields`, eg cloud.ca, should show a keyvalue component with `apiKey` selected in a key dropdown.
Cloud credential creation for custom cloud drivers that _do_ provide resourceFields, eg Open Telekom Cloud, should show a keyvalue component with prepopulated, uneditable keys.
> fix generic cloud credential key option logic

- shell/pages/c/_cluster/apps/charts/install.vue
Fixes #8566
The bug was introduced here: https://github.com/rancher/dashboard/compare/v2.7.2-rc4...v2.7.2-rc7#diff-39e1e049c631a635017305ddbeb1944cff1559d39f32b31efea2e38cd142d611R1196
In the above, `versionInfo.values === crd chart values` and `values === chart values`
This was meant to allow custom chart UIs to modify crd chart values not found in the main chart, specifically OPA gatekeeper crd enableRuntimeDefaultSeccompProfile : https://github.com/rancher/dashboard/issues/8238. Previously, CRD charts were installed with _only_ the values of the main chart. The change I linked above was intended to install CRD charts with their own values plus whatever chart values were customized in the UI. Problem appears to be that I merged crd chart values w/ main chart values the wrong direction. …
> Fix overwritten chart global values

- shell/components/ChartPsp.vue
- shell/components/__tests__/ChartPsp.test.ts
- shell/pages/c/_cluster/apps/charts/__tests__/install.helper.test.ts
- shell/pages/c/_cluster/apps/charts/install.helpers.js
Fixes #8434
Remove previous implementation of hiding PSP check for clusters with K8S 1.25 even if PSP is enabled in charts installation/update
Reversing change related to the presence of a checkbox to disable the PSP.
Updated tests
> Remove previous implementation of hiding PSP check for clusters with K8S 1.25 even if PSP is enabled in charts installation/update

- shell/components/ChartPsp.vue
- shell/components/__tests__/ChartPsp.test.ts
- shell/pages/c/_cluster/apps/charts/__tests__/install.helper.test.ts
- shell/pages/c/_cluster/apps/charts/install.helpers.js
Fixes #8528
Backport https://github.com/rancher/dashboard/pull/8553
> [2.7.2] Remove previous implementation of hiding PSP check for clusters with K8S 1.25 even if PSP is enabled in charts installation/update

- shell/edit/fleet.cattle.io.gitrepo.vue
Fixes #8592 
backport of https://github.com/rancher/dashboard/pull/8591
> [2.7.2]use secret name not id for git repo clientSecretName and helmSecretName

- shell/pages/c/_cluster/fleet/index.vue
Fixes #8467 see comment on backport [here](https://github.com/rancher/dashboard/issues/8531#issuecomment-1492112791)
Updated the fleet landing page shown when a user has no git repos to hide the 'get started' button when the user can't create git repos.
I've updated the `permissions` property to check available methods on the git repo schema rather than just checking for its existence - though git repos were added to this permission check previously, I don't see them used in the component elsewhere, so this change looks fine to me. 
1. Users with permission to list but not create/edit gitrepos should not see 'get started' button on the fleet landing page
> hide continuous delivery get started btn if user cant create gitrepos

- pkg/rancher-components/package.json
- pkg/rancher-components/src/components/Banner/Banner.test.ts
- pkg/rancher-components/src/components/Form/Radio/RadioButton.test.ts
- pkg/rancher-components/src/components/Form/Radio/RadioButton.vue
This separates `label` slot from the `label` prop content in `RadioButton.vue`. Doing this will allow developers to provide custom content to the `label` slot that would otherwise get overwritten by the `v-html` directive. 
Fixes #8619
I did a search for existing `RadioButton` instances that make used of the `label` slot an none came up. Please double-check that this is the case. 
I suspect that we won't find any instances in our code because this use case was never supported with the existing implementation.
Anything that uses a radio button.
Anything that uses a radio button.
> Separate label slot in `RadioButton.vue`

- shell/plugins/clean-html-directive.js
Fixes #8615 
The `v-clean-html` directive does not work when used inside a `<template>` section.
Looking at https://github.com/LeSuisse/vue-dompurify-html/blob/main/packages/vue-dompurify-html/src/dompurify-html.ts the trick seems to be to add an `unbind` to the directive.
This PR updates our directive to do this - this resolves the original issue.
> Fix the v-clean-html directive

- shell/assets/translations/en-us.yaml
- shell/chart/istio.vue
Fixes #7970 
This PR updates the Istio install page so that you can't enabled Kiali without enabling Pilot.
It also increases the vertical spacing between checkboxes for better presentation.
When Kiali is enabled, pilot will automatically be enabled and the checkbox will be disabled and we will also show a banner - as shown above.
> Istio install : Fix issue where Kiali requires Pilot

- shell/chart/istio.vue
Fixes lint issue on master.
v-html was used in PR that had been approved and then merged after the lint rules were updated.
This PR updates to use the new `v-clean-html` directive.
> Update v-html to v-clean-html

- shell/chart/gatekeeper.vue
- shell/mixins/chart.js
- shell/pages/c/_cluster/apps/charts/install.vue
This PR addresses the bug described here specifically: https://github.com/rancher/dashboard/issues/8612#issuecomment-1496222854
This PR updates the logic around CRD chart values in a few ways. There are two requests for 2.7.2 we need to accomodate in this area:
* CRDs should be installed with the same global values as the main chart https://github.com/rancher/dashboard/issues/8062
* Custom UIs should be able to configure CRD chart values: https://github.com/rancher/dashboard/issues/8238
In the install/upgrade request the UI passes only values that differ from the chart's default values. This means that when looking at the API call made,  if 'enable PSPs' is not checked, we shouldn't see `values.global.cattle.psp.enabled` in the request body of either chart at all. When it is checked, it …
> Ensure CRDs are always installed with the same global values as the main chart

- shell/store/type-map.js
There is a copy and paste error that means custom cloud credentials in extensions don't work.
We should probably back-port this to 2.7.2.
> Bug fix for custom cloud credentials from extensions

- .github/workflows/docusaurus.yaml
Removes the file `.github` from `exclude_assets` environment variable in the publish Publish Docusaurus workflow.
> Remove .gitignore from exlude assets for publish action

- pkg/epinio/promptRemove/services.vue
Test cases:
Fixes https://github.com/epinio/ui/issues/208
> Services, fix apps count in warning message

- shell/components/form/NameNsDescription.vue
- shell/components/form/__tests__/NameNsDescription.ts
Fixes #8632
Prevented reported break.
Reference to the variable was not updated, previously `this.namespace`, while we are checking the presence of `this.options`
As in issue.
None.
https://user-images.githubusercontent.com/5009481/230189419-e9ad302b-2851-4477-bbeb-c182c9ab1f0c.mp4
> App breaks when creating a new namespace from a workload

- shell/assets/translations/en-us.yaml
- shell/components/form/Members/ClusterPermissionsEditor.vue
- shell/components/form/ProjectMemberEditor.vue
Fixes #5952
User should not be able to use Disabled/Locked Project Roles after the upgrade
- Go to users and auth, > roles and cluster roles.
- Pick a role e.g. `Manage Cluster Backups` and select Edit Config from the action menu for it. Set 'Locked` to yes
- Go to the Cluster and Project Members and click Add > custom you'll get a list of custom roles
-  `Manage Cluster Backups` should be disabled
> Fix locked project roles

- shell/assets/translations/en-us.yaml
- shell/components/ExplorerProjectsNamespaces.vue
- shell/config/query-params.js
- shell/edit/namespace.vue
Fixes #8216
Create Namespaces Button is not visible when using the "Flat List" view
> Go to local cluster > Projects/Namespaces > click on `Flat list` view
> Create Namespaces Button should be there > click on `Create Namespaces Button`
> Create screen should have a dropdown of projects.
> Added create name space button on flat list view

- shell/assets/styles/base/_basic.scss
- shell/assets/styles/base/_mixins.scss
- shell/assets/styles/base/_variables.scss
Fixes #8663 
This PR fixes an issue with our CSS.
`_mixins.scss` defines not only mixins but also a few styles. This file in included in every Vue component's styles, so that they can access the mixins. This results in the styles be defined within every component.
This PR moves the style declrations out of `_mixins.css`, so that they are only delcared once. Mixins now only declares actual scss mixins.
Also changed the comment in `_variables.scss` to use `//`, so that it is removed - the `/*` style of comments is preserved - meaning we get the comment included at the top of every style generated for every Vue component.
> Fix repeated style definitions from _mixins.scss

- pkg/epinio/components/application/AppInfo.vue
- pkg/epinio/components/application/AppSource.vue
- pkg/epinio/detail/applications.vue
- pkg/epinio/models/applications.js
- App create/edit pages should hide the EPINIO_APP_DATA env var
- fix edit of apps from non-git sources
- fixes https://github.com/epinio/ui/issues/220
> Hide `EPINIO_APP_DATA` from user, fix edit of source from non-git sources

- shell/vue.config.js
For `yarn dev`, this PR:
Adds a CTRL+C handler to shut down the dev server and exit the process - this fixes and issue where once the build starts, you can not CTRL+C out of it.
Hides the logging that we get for the proxies being set up - we currently get multiple lines of the form '[HPM] Creating proxy"
> Dev server: Improve ctrl+c handling and suppress proxy setup messages

- shell/components/EtcdInfoBanner.vue
- shell/components/GrafanaDashboard.vue
- shell/utils/__tests__/grafana.test.ts
- shell/utils/grafana.js
Fixes https://github.com/rancher/dashboard/issues/8346
With the new version of Rancher-Monitoring, the embedded Grafana dashboards and links in the local cluster do not work anymore, but return a 404 from Grafana.
In all other clusters the links are correct.
This changes an exception in the creation of these links for the local cluster, which is not needed anymore in the new monitoring version >=102.0.0+up40.1.2.
Embedded Grafana dashboards and Grafana links in the local cluster.
* Cluster Overview page
* Workload detail page
* Pod detail page
* Node detail page
* Grafana link on Monitoring detail page
> Fix Grafana URLs in local cluster for new monitoring version

- shell/assets/translations/en-us.yaml
- shell/edit/provisioning.cattle.io.cluster/MachinePool.vue
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #8223
Checkbox added to the right of 'NodePort Service Port Range' in the 'Networking' tab for hostnames Truncate
As of now the new param per machine pool named `instanceNameLimit`  is not available from the backend, so for the testing plead add this code:
out.find((pool) => {
pool.pool.instanceNameLimit = 15;
});
> Go to Cluster management > create > select DO 
> In Cluster Configuration section > click 'Networking' tab 
> It should have a check box with a label for hostnames Truncate
**Some other use cases to test**
> Checkbox can ONLY be set on create - it should be disabled on edit
> On edit, ONLY if the value is 15, should we show the checkbox as checked
> On edit, if the value is present but NOT 15, we should show an info banner beneath the checkbox
> Show banner per-machine …
> Added check box for truncate Hostnames

- .github/workflows/scripts/pr.js
Adds support for QA/None, so linked issues with this label will not be moved to 'To Test' automatically - same as dev-vadlidate.
> PR Automation: Add support for QA/None

- shell/edit/provisioning.cattle.io.cluster/rke2.vue
Updates the truncation code so it only shows if the backend support is available.
QA not needed - should be done as part of main ticket.
> Added code to support truncation

- docusaurus/docs/extensions/extensions-getting-started.md
- docusaurus/docs/getting-started/development_environment.md
Fixes #7759
Fixes #8178
Adds to the two docs for dashboard and extensions to be clear Windows is not supported as a development environment.
> Update docs to indicate Windows is not support as a dev environment

- cypress/e2e/po/components/action-menu.po.ts
- cypress/e2e/po/components/component.po.ts
- cypress/e2e/po/components/labeled-select.po.ts
- cypress/e2e/po/components/tab.po.ts
- cypress/e2e/po/components/tabbed.po.ts
- cypress/e2e/po/edit/catalog.cattle.io.clusterrepo.po.ts
- cypress/e2e/po/lists/base-resource-list.po.ts
- cypress/e2e/po/lists/catalog.cattle.io.clusterrepo.po.ts
- cypress/e2e/po/lists/provisioning.cattle.io.cluster.po.ts
- cypress/e2e/po/pages/apps/app-repos.po.ts
- cypress/e2e/po/pages/extensions.po.ts
- cypress/e2e/tests/pages/extensions.spec.ts
- shell/list/catalog.cattle.io.clusterrepo.vue
Fixes #8119 
Create basic test suite of e2e tests for Extensions mechanism:
- enable/disable extensions in general
- clicking on extension card toggles details side-panel
- install an extension
- upgrade an extension
- rollback an extension
- uninstall an extension
> e2e tests for Extensions

- shell/components/formatter/WorkloadHealthScale.vue
- shell/config/types.js
- shell/edit/workload/mixins/workload.js
- shell/list/workload.vue
- shell/models/pod.js
Fixes https://github.com/rancher/dashboard/issues/7506
- Show pods that aren't owned by another workload in the workload list
- Allow user to create PODS from the workload list
- This is done in a very targeted way 
- Only replaces `WORKLOAD_TYPES` in two specific places
- This should avoid issues where `WORKLOAD_TYPES` is used in other contexts
- Both Workloads List and Workloads --> Pods Lists
- Create/Edit
- `Health` column should not show for non-pod workloads (and vice-versa)
- Other area's that show lists of workload like resources (for example deployment detail page Pods list)
> Note that the pod for the deployment is not shown
> Include oprhaned `POD`s in Workload list

- shell/plugins/dashboard-store/index.js
Fixes #
It doesn't look like window.__NUXT__ actually exists anymore which makes sense since we removed NUXT but there's still a lot of references for it in code.
Removed a check for the window.__NUXT__ object which caused store initialization to return early.
I didn't remove all references to the window.__NUXT__ object in code since that'd require pretty exhaustive testing but that's something we should look at in the near future.
Tested on chrome latest
Tester should see that with the advanced webworker enabled, the cluster socket never appears in the "ws" tab of chrome's dev tools indicating that either the socket was never created or the worker was never created (the latter being the actual cause).
Unknown
> Fixes Advanced Socket Worker after Nuxt removal

- shell/components/Wizard.vue
- shell/pages/c/_cluster/apps/charts/install.vue
Fixes #7975
Fixed sticky footer in Helm Chart Install Yaml Values editor
Go to cluster tools, OPA Gatekeeper and install, click next to get the Values step.
The footer container the wizard buttons should be sticky as in the previous step:
> Fixed sticky footer in Helm Chart Install Yaml

- shell/plugins/clean-html-directive.js
Fixes #8615 
The `v-clean-html` directive does not work when used inside a `<template>` section.
Looking at https://github.com/LeSuisse/vue-dompurify-html/blob/main/packages/vue-dompurify-html/src/dompurify-html.ts the trick seems to be to add an `unbind` to the directive.
This PR updates our directive to do this - this resolves the original issue.
backports #8617
> Backport 2.6: Fix the v-clean-html directive (#8617)

- shell/plugins/clean-html-directive.js
Fixes #8615 
The `v-clean-html` directive does not work when used inside a `<template>` section.
Looking at https://github.com/LeSuisse/vue-dompurify-html/blob/main/packages/vue-dompurify-html/src/dompurify-html.ts the trick seems to be to add an `unbind` to the directive.
This PR updates our directive to do this - this resolves the original issue.
backports #8617
> Backport 2.7.4: Fix the v-clean-html directive (#8617)

- shell/vue.config.js
Addresses #8389
This PR fixes an issue with Nuxt removal where whitespace is not preserved.
This PR updates the webpack configuration to set whitespace to 'preserve' - in Vue it defaults to 'compact'.
> Update vue options to preserve whitespace

- shell/creators/pkg/files/.github/workflows/build-extension.yml
- shell/scripts/extension/publish
Fixes #8313 
This updates the workflow and publish script for extensions to push build assets into the `gh-pages` branch if applicable. If the `gh-pages` branch does not exist the `main` branch will be used. The user will still be able to supply a specific branch if desired.
> Update extensions publish workflow for assets in gh-pages branch

- shell/edit/provisioning.cattle.io.cluster/import.vue
Fixes #8106
- Fixed space between via and Virtualization Management
- Excess space above banner
I checked the change history and the generic component from the start had the `mt-20` class, having some extra space on top, which is not required.
For the space between via and Virtualization Management in the banner - I have created a new issue to fix banner components to take care of different use cases.
Go to
Cluster Management --> Import Cluster --> Generic, this fix should solve the bugs
> Fixed extra space bug in the generic cluster-page

- shell/assets/translations/en-us.yaml
- shell/config/table-headers.js
- shell/detail/constraints.gatekeeper.sh.constraint.vue
- shell/models/constraints.gatekeeper.sh.constraint.js
This adds the following functionality to the violations list on the OPA Gatekeeper constraint detail page:
* Add a namespace column to the violations
* Make the violations list searchable
* Allow to download the violations as a CSV, similar to CIS scanner violations
Fixes #8585
A constraint to use for testing could be:
```
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
name: all-must-have-owner
spec:
match:
kinds:
- apiGroups: [""]
kinds: ["Pod"]
parameters:
message: "All pods must have an `owner` label that points to your company username"
labels:
- key: owner
allowedRegex: "^[a-zA-Z]+.agilebank.demo$"
```
Constraint detail page with violations
Constraint detail page
Example for generated CSV
[violations-all-must-have-owner.csv](https://github.com/rancher/ …
> Improve OPA Gatekeeper constraint detail page

- shell/components/SortableTable/index.vue
Fixes #8273
After merging #8419 PR in the master, there was an issue with the 'hasClass`method. This PR is to fix it when you select rows in a table by pressing 'shift+j' or 'shift+k
> Removed hasClass method

- docusaurus/docs/extensions/api/nav/custom-page.md
- docusaurus/docs/extensions/api/nav/products.md
- docusaurus/docs/extensions/api/nav/resource-page.md
- docusaurus/docs/extensions/api/nav/routing.md
- docusaurus/docs/extensions/api/nav/side-menu.md
- docusaurus/docs/extensions/extensions-getting-started.md
- docusaurus/docs/extensions/usecases/top-level-product.md
- shell/core/plugin.ts
- shell/core/types.ts
- shell/types/rancher/index.d.ts
https://github.com/rancher/dashboard/issues/8744 - `Fix the TS error regarding implicit any on the $plugin and store arguments`
The `Leaving these here for completeness but I don't think these should be advertised as usable to plugin creators.` comment sections should probably be removed. I just wanted the both of you to get a chance to comment if you think they should be a part of the interfaces or not.
> Provide the relevant types for the product.ts and update the appropriate docs

- .github/ISSUE_TEMPLATE/bug_report.md
Not all users may be able to provide this (page is only available to admins). We might want to add extensions list to the diagnostics page?
> Add `Rancher UI Extensions` to setup info in github issue bug report template

- shell/components/SortableTable/index.vue
- shell/initialize/App.js
- shell/layouts/standalone.vue
Adding the necessary support for standalone extensions. Specifically the changes needed to allow the opni extension to function without rancher.
1. Added the standalone layout which uses the unauthenticated middleware.
2. Fixed an issue where SortableTable expected a `main` component to exist on the page for scrollbars. This check was already done on line 360 so I think it should be fine and seems to work in opni.
> Adding standalone layout for use with standalone extensions

- shell/scripts/serve-pkgs
https://github.com/rancher/dashboard/issues/8744
https://rancher.github.io/dashboard/extensions/extensions-getting-started#loading-into-another-rancher-instance
- Give a friendly error message when running yarn serve-pkgs if yarn build-pkg test wasn't run? Or maybe run it for them?
> Adding a descriptive error message to the serve-pkgs script

- shell/assets/translations/en-us.yaml
- shell/components/auth/AuthBanner.vue
- shell/edit/auth/ldap/config.vue
- shell/edit/auth/saml.vue
- shell/utils/gc/gc.ts
Fixes #8675 
Adds the option to the OKTA Auth Provider to specify LDAP configuration for advanced group search. This follow the same pattern as the Shibboleth auth provider.
> Auth Provider: Support Okta with LDAP search

- shell/edit/provisioning.cattle.io.cluster/rke2.vue
- shell/models/provisioning.cattle.io.cluster.js
Updates so property matches backend - machinePools was under spec.rk3eConfig, not at the top level
Removed check for schema, as property will always be in backend now.
> Hostname truncation: Update to sync with backend

- package.json
- shell/package.json
- yarn.lock
This updates `dompurify` to version 2.4.5. 
[Changelog for 2.0.12...2.4.5
](https://github.com/cure53/DOMPurify/compare/2.0.12...2.4.5)
Basic smoke testing should suffice with this change. We need to ensure anything that relies on `dompurify` still renders content properly and without error.
> Update `dompurify` to 2.4.5

- shell/public/index.html
- shell/vue.config.js
The release version of rancher appears to expect the favicon at the root directory. Dev expected it to be under the public directory. I changed dev to use the root directory as well
https://github.com/rancher/dashboard/issues/8794
Locally I verified the default and branded icon both load.
> Changing how we serve the favicon

- shell/components/ExplorerProjectsNamespaces.vue
This removes the need to use `v-html` when displaying project labels by shifting the `span` tag outside of the translations inside of `en-us.yaml` and into the vue template.
Listing projects and namespaces.
> Sanitize project label `v-html`

- package.json
- shell/package.json
- yarn.lock
This updates `dompurify` to version 2.4.5. 
[Changelog for 2.0.12...2.4.5
](https://github.com/cure53/DOMPurify/compare/2.0.12...2.4.5)
Basic smoke testing should suffice with this change. We need to ensure anything that relies on `dompurify` still renders content properly and without error.  
backports #8816 into `release-2.6`
> Backport 2.6: Update `dompurify` to 2.4.5

- package.json
- shell/package.json
- yarn.lock
This updates `dompurify` to version 2.4.5. 
[Changelog for 2.0.12...2.4.5
](https://github.com/cure53/DOMPurify/compare/2.0.12...2.4.5)
Basic smoke testing should suffice with this change. We need to ensure anything that relies on `dompurify` still renders content properly and without error.  
backports #8816 into `release-2.7.4`
> Backport 2.7.4: Update `dompurify` to 2.4.5

- shell/components/ExplorerProjectsNamespaces.vue
This removes the need to use `v-html` when displaying project labels by shifting the `span` tag outside of the translations inside of `en-us.yaml` and into the vue template.
Listing projects and namespaces.
backports #8832 into `release-2.7.4`
> Backport 2.7.4: Sanitize project label `v-html`

- shell/components/ExplorerProjectsNamespaces.vue
This removes the need to use `v-html` when displaying project labels by shifting the `span` tag outside of the translations inside of `en-us.yaml` and into the vue template.
Listing projects and namespaces.
backports #8832 into `release-2.6`
> Backport 2.6: Sanitize project label `v-html`

- package.json
- shell/package.json
- yarn.lock
This updates `dompurify` to version 2.4.5. 
[Changelog for 2.0.12...2.4.5
](https://github.com/cure53/DOMPurify/compare/2.0.12...2.4.5)
Basic smoke testing should suffice with this change. We need to ensure anything that relies on `dompurify` still renders content properly and without error.  
backports #8816 into `release-2.6.13`
> Backport 2.6.13: Update `dompurify` to 2.4.5

- shell/components/ExplorerProjectsNamespaces.vue
This removes the need to use `v-html` when displaying project labels by shifting the `span` tag outside of the translations inside of `en-us.yaml` and into the vue template.
Listing projects and namespaces.
backports #8832 into `release-2.6.13`
> Backport 2.6.13: Sanitize project label `v-html`

- shell/models/batch.cronjob.js
- shell/models/workload.js
Fixes #8683
1. Add ownerReferences property to the cron job `runNow` request body，so that the cron job details page can look up the associated job
2. Update the endpoint get method of the workload model, because deleting a job from the cronjob details page will report an error
1. CronJob detail page
5. DaemonSet detail page
6. Deployment detail page
7. Job detail page
8. StatefulSet detail page
9. Pod detail page
> fix missing job/pod resources on CronJobs/Jobs detail page

- shell/mixins/chart.js
- shell/package.json
This fixes the import for the `clone` method as this is causing build failures with extensions using the chart mixin. Example [here](https://github.com/kubewarden/ui/actions/runs/4938978264/jobs/8829388513#step:9:145)
Also bumps `0.3.9` of `@rancher/shell`
> Fix import for clone from utils/object - Bump 0.3.9 

- shell/plugins/plugin.js
Fixes #8253 
This PR updates the extensions load logic, so if the error is 404, we only show an info message and we don't show the error detail - this gives a better experience in the browser console for the case when the extensions operator is not installed.
> Extensions: Reduce error logging when operator not installed

- package.json
- shell/core/plugins-loader.js
- shell/package.json
- shell/pkg/vue.config.js
- yarn.lock
Reverts rancher/dashboard#8272
Seen as part of: https://github.com/rancher/dashboard/issues/8686
Removing jQuery has broken some extensions: I tried harvester 1.0.3, harvester 1.1.0, elemental 1.0.0 and elemental 1.1.0...it's likely others are broken too.
> Revert "Remove jquery from dependencies"

- shell/edit/workload/storage/__tests__/Storage.test.ts
Fixes #8772
Tested all the volumes cases from the Storage wrapper to:
- Display volume name field
- Recognize volume name change
> Automation: Allow user to change the volume name when creating a workload

- shell/components/form/ProjectMemberEditor.vue
This utilizes `DOMPurify` to sanitize custom roles displayed in the Add Project Member dialog. 
- The add project member dialog
backports #8883
> Backport 2.7.4: Sanitize custom roles in `ProjectMemberEditor`

- shell/components/form/ProjectMemberEditor.vue
This utilizes `DOMPurify` to sanitize custom roles displayed in the Add Project Member dialog. 
- The add project member dialog
backports #8883
> Backport 2.6: Sanitize custom roles in `ProjectMemberEditor`

- shell/components/form/ProjectMemberEditor.vue
This utilizes `DOMPurify` to sanitize custom roles displayed in the Add Project Member dialog. 
- The add project member dialog
backports #8883
> Backport 2.6.13: Sanitize custom roles in `ProjectMemberEditor`

- shell/config/types.js
- shell/edit/management.cattle.io.project.vue
- shell/models/management.cattle.io.project.js
Fixes #8508 
This PR addresses the issue above.
Detailed steps to test are in the issue.
This PR:
- Disables the editing of the PSP on a project if the user does not have permissions to access PSP template bindings
- Updates the model so we only attempt to save the PSP Template binding if the value changes
UI when the user does not have permissions:
> Fix issue where project owner does not have permission to update PSP template bindings for a project

- package.json
- shell/package.json
- yarn.lock
Contributes to #4534
- ejs to ^3.1.7,
- json5 to >=2.2.2
- d3-color to >=3.1.0
- glob-parent to >=5.1.2
- node-forge to >=1.3.0
- qs to >=6.7.3
- nth-check to >=2.0.1
- follow-redirects to >=1.14.7
- merge to >=2.1.1
Fixes `critical` and `high` vulnerabilities; `axios` and `loader-utils` are not updated at the moment.
> Bump resolutions dependencies

- cypress/e2e/tests/pages/data/agent-configuration-rke2-payload.ts
- shell/assets/translations/en-us.yaml
- shell/components/form/Tolerations.vue
- shell/edit/provisioning.cattle.io.cluster/AgentConfiguration.vue
Fixes #8886 
- fixes issue with `Tolerations` component not covering the spec correct correctly when talking about effect `All`. It should not send string `effect: All`, but `effect: null` as per the kubernetes spec https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#toleration-v1-core
Fixes #8910 
- Change label in Tolerations from `Label Key` to `Key`
Follow reproduction steps on issue
> fix issue with Tolerations component

- shell/edit/storage.k8s.io.storageclass/index.vue
- shell/models/persistentvolume.js
Fixes #8820 
The issue is caused by an incorrect 18n key.
`persistentVolume.csi.drivers.suffix` should be `persistentVolume.csi.suffix`
After this fix:
Note: You can test this without EKS by finding the CSI Driver resource and creating a new one - just supply a name for the resource - you'll then see this when you try to create a Storage class
Manual QA by dev team should be fine for this
> Fix incorrect i18n string for CSI suffix

- shell/pages/auth/login.vue
- Setup page consists of
- Welcome message
- First login message
- Local log in form
- Align first log in message mt with log in local login form mt
- Remove first log in message bottom (spacing handled by log in mt)
- Remove InfoBox (border around first login message
- Display of incorrect password in setup pages
- Display of normal log in page & errors
> Fix spacing in setup page, remove border

- shell/edit/monitoring.coreos.com.prometheusrule/GroupRules.vue
Fixes #8902 
This PR adds another default label to prometheus alerting rules, as we do with the cluster id (#7935):
> add cluster-name label to prometheus recording and alerting rules

- cypress/e2e/po/components/sortable-table.po.ts
- cypress/e2e/po/lists/account-api-keys-list.po.ts
- cypress/e2e/po/pages/account-api-keys-create_key.po.ts
- cypress/e2e/po/pages/account-api-keys.po.ts
- cypress/e2e/tests/pages/user_menu/account-api-keys.spec.ts
- shell/components/DetailText.vue
- shell/components/SortableTable/THead.vue
- shell/components/form/ChangePassword.vue
- shell/edit/token.vue
- shell/pages/account/index.vue
Added test for the Account & API Keys page which are:
- User can navigate to Account and API Keys page
- User can change their password
- User can create and delete API keys
> cypress UI automation: account and api keys tests

- shell/detail/helm.cattle.io.projecthelmchart.vue
If alertmanager is deactivated, the prometheus links should not be disabled. Previously all links were disabled as soon as the alertmanager was disabled, because it picked the namespace from the alertmanager url, which is empty if disabled.
Fixes https://github.com/rancher/dashboard/issues/8350
Project monitor detail page
Project monitor detail page
Before:
After:
> Fix prometheus links on project monitor detail page

- pkg/rancher-components/src/components/Form/Radio/RadioGroup.vue
This PR exposes the `isDisabled` slot prop in the indexed slots of the `RadioGroup` component. This is particularly useful when creating customized radio button groups. 
By providing the `isDisabled` slot prop, consumers can relay the disabled state information from the `RadioGroup` component to their custom radio button compositions.
Fixes #8977
Example usage rancher-sandbox/rancher-desktop#4758
> RadioGroup: Expose `isDisabled` slot prop

- shell/vue.config.js
Fixes #8979
- Remove clash of `test: /\.md$/,` entries
- the wrong loader `url-loader` was used instead of `frontmatter-markdown-loader`
- this resulted in the `require` for the md just returning a string
- The removed entry might be a copy and paste error. Going back to pre-nuxt removal the `url-loader` was associated with loading images
- https://github.com/rancher/dashboard/blob/v2.7.2/shell/nuxt.config.js#L492
- i'm not sure if we don't need the custom loader now, images do seem to work
> Clicking on whats new will remove the banner with the link, it can be shown again by nav'ing to `<rancher url>v3/preferences/read-whatsnew` and deleting the resource
> Fix 'What's New' page

- pkg/rancher-components/package.json
This PR updates the peer dependency for `vue` in `@rancher/components`. This change ensures compatibility with a wider range of `vue` versions, specifically for Rancher Desktop, which is still on vue `2.6.14`.
> Update `vue` peer dependency for `@rancher/components`

- shell/config/product/monitoring.js
- shell/edit/monitoring.coreos.com.receiver/index.vue
- shell/edit/monitoring.coreos.com.receiver/types/email.vue
- shell/models/monitoring.coreos.com.receiver.js
Fixes #5453
Added port input in receiver email form
- Goto > cluster > monitoring > route-receiver
- Click on `Create` > select Email tab > click on `Add email`, form should have a Port field
> Added port input in receiver email form

- shell/components/nav/WindowManager/ContainerShell.vue
Example usage:
Note:
I'm using `paste` instead of `write` because `write` either wasn't getting a response or wasn't processing the response. It would just render a message in the terminal.
> Add the ability to execute a container shell command immediately after the shell connects.

- shell/pages/__tests__/prefs.test.ts
- shell/pages/prefs.vue
Fixes #8801
Fixed bug for date format preference when the user selects date format (M/D/YYYY or D/M/YYYY) on a day where the month and day are the same values (e.g. 5/5/2023).
https://github.com/rancher/dashboard/assets/18264463/f82585db-0e6f-4b1c-a01e-00c3a08e6d44
Added visual cue for date formats
> Added value to select key

- cypress.config.ts
- cypress/e2e/tests/pages/data/agent-configuration-rke2-payload.ts
- shell/components/form/NodeAffinity.vue
- shell/components/form/PodAffinity.vue
Fixes https://github.com/rancher/dashboard/issues/9012 - this PR is for specifically the first issue described in this comment https://github.com/rancher/dashboard/issues/9012#issuecomment-1569155864 . As noted in slack discussion, the other two potential causes of the 502 error may be more complex to address so we're starting here.
The dashboard is sending an extra weight field within node/pod preferred terms,  `nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[].preference.weight` we should only be sending `nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[].weight` Similarly the UI is sending `podAffinity.preferredDuringSchedulingIgnoredDuringExecution[].podAffinityTerm.weight` and should only send `podAffinity.preferredDuringSchedulingIgnoredDuringExecution[].weig …
> Fix malformed pod affinity and node affinity terms

- scripts/build-embedded
- Apply build-hosted resource base ending `/` (https://github.com/rancher/dashboard/pull/8401)
- Ensure resource links in index.html match that of previous releases
- These all started with `/dashboard` and had `<base href='/dashboard/'`
- Note - base is still missing (everything still seems to work)
- Note - base is ignored for href's starting `/` anyway
- It's assumed nuxt added this resource prefix via nuxt.config.js build publicPath
> Two RC related build fixes

- shell/public/index.html
- theme comes from preference `theme` cookie
- when theme is auto `pcs` cookie is used instead
- `pcs` is set to the OS theme, or failing that based on time of day
> Align theme of loading indicator page with dashboard theme

- shell/config/router.js
- shell/vue.config.js
- Fix chunking for `pages/c/_cluster/settings/DefaultLinksEditor.vue`
- bundle css with pages, instead of as prefetched links in index.html
> Two Build Related Tweaks

- shell/components/GrafanaDashboard.vue
- shell/pages/c/_cluster/monitoring/index.vue
- shell/utils/__tests__/grafana.test.ts
- shell/utils/grafana.js
Fixes #https://github.com/rancher/dashboard/issues/8885
* updated grafana url-construction utility to only apply the `/k8s/clusters/${ clusterId }` prefix for monitoring versions `100.2.0+up40.1.2` and `102.0.0+up40.1.2`
* updated the grafana link on the monitoring index page to use the above utility
* updated the embedded grafana dashboard component to use the correct url for iframe src
The GrafanaDashboard component was using a url generated before fetching the installed monitoring version, so it was wrong some of the time. I've updated it to use the `currentUrl` computed property which properly accounts for the monitoring version.
Test both `100.2.0+up40.1.2` and `102.0.0+up40.1.2` monitoring each on a local and downstream cluster. Verify that the embedded grafana views and grafana …
> fix grafana url prefix for local clusters

- shell/components/DetailTop.vue
- shell/config/workload.ts
- shell/detail/workload/index.vue
- shell/models/__tests__/batch.cronjob.test.ts
- shell/models/workload.js
Fixes #8829
- Added tests to ensure
- ownership data inheritance from CronJob
- redirection to default value
- Moved `SEPARATOR` into a new config file
- Corrected import complained by linter
> Automation: Cronjob Run Now does generate resources in Jobs Detail page

- cypress/e2e/po/pages/explorer/projects-namespaces.po.ts
- cypress/e2e/tests/pages/project-namespace.spec.ts
- shell/components/ExplorerProjectsNamespaces.vue
- shell/edit/namespace.vue
Fixes #8784
Automation: Create Namespaces Button is not visible when using the "Flat List" view
When a user is on Projects/Namespaces Flat list view > `create Namespaces` Button should be there
When a user clicks on Create Namespaces Button > Create screen should have a projects dropdown.
> Automation namespaces button flatlist

- shell/package.json
- shell/scripts/extension/publish
This fixes an issue where initial extension packages will have a duplicated folder name in the `url` path for the package chart. Also removed unnecessary directory lingering in artifact build.
Bumps shell to `0.3.13`
> Bump shell - Clean up temporary charts - fix chart url path

- shell/creators/app/files/.gitignore
This fixes an issue with the extension which caused any `tgz` files to not be committed - During the release process `./assets` must be pushed with with the packages asset file which was being ignored.
> Remove *.tgz from extension .gitignore

- pkg/epinio/l10n/en-us.yaml
Fixes https://github.com/epinio/ui/issues/240
- Replace both old `Dex` (specific auth provider) and new `SSO` (technical acronym) references with a more non-technical `Auth Provider` string
This does introduce some odd verbage, but the local provider should rarely be used in production and the fix avoids adding additional plumbing around the core dashboard screens
> Replace dex/sso terminology with Auth Provider

- shell/components/form/NameNsDescription.vue
Fixes https://github.com/epinio/ui/issues/205
- In epinio world defaultNamespace isn't valid
- This would be undefined, which was probably handled as a falsy which matched the 'create a ns' option
- So fall back on something sensible
Supersedes https://github.com/rancher/dashboard/pull/9065
> Ensure cancel when creating a NS sets valid selected option

- shell/components/Wizard.vue
- shell/pages/c/_cluster/apps/charts/install.vue
Fix issue where app chart wizard header alignment was off
- Ensure step vertical bar is aligned correctly
- For App Chart Install ensure the os warning tag is placed correctly WITHOUT borking the alignment of the header or changing wizard classes
- Tested
- Wizard in app chart install - linux only warning and no warning
- Wizard in cru resource (fleet git repo)
- Will also validate in epinio wizard later on
Supersede https://github.com/rancher/dashboard/pull/9079
> Align wizard title row

- shell/components/CruResource.vue
- shell/components/__tests__/CruResource.test.ts
Fixes #8817
Automation:  should prevent default events on keypress Enter if the `preventEnterSubmit` property is false
> Automation preventdefault on press enter

- cypress/e2e/po/pages/global-settings/branding.po.ts
- cypress/e2e/po/pages/repositories.po.ts
- cypress/e2e/tests/pages/global-settings/branding.spec.ts
This pr addresses the flaky branding and preferences tests which both seem to be related to timing issues. 
- Branding test fix: Added intercept logic to wait for http response to occur after clicking the 'apply' button.
- Preferences test fix: Increase timeout by 5 seconds to wait for catalog.cattle.io.clusterrepos page to load.
> ui automation: fix flaky branding and preferences tests

- cypress/e2e/po/pages/home.po.ts
- cypress/e2e/po/pages/page.po.ts
- cypress/e2e/tests/pages/user_menu/account-api-keys.spec.ts
- cypress/e2e/tests/pages/user_menu/logout.spec.ts
- cypress/e2e/tests/pages/user_menu/preferences.spec.ts
- shell/components/ExplorerMembers.vue
- Clicking on `x` to remove a role tries to find the associated binding by only looks for matching role and user
- If the user has the same role in another project it selected whichever it found first
- This results in the intended role remaining and another mysteriously being removed
> Fix remove of project role via role tag

- shell/assets/translations/en-us.yaml
- shell/components/ExplorerMembers.vue
- shell/components/form/Members/ClusterPermissionsEditor.vue
- shell/components/form/Members/MembershipEditor.vue
- shell/components/form/Members/ProjectMembershipEditor.vue
- shell/config/product/explorer.js
- shell/models/clusterroletemplatebinding.js
- shell/models/management.cattle.io.clusterroletemplatebinding.js
- shell/models/projectroletemplatebinding.js
- shell/store/type-map.js
Fixes #9049
The issue originates from the "Project and Cluster Members" option in the nav menu only checking for cluster member schemas which means that project member admins will never see the link
Added functionality for "ifHaveSubTypes" on virtualTypes to accept an object like the "ifHaveType" parameter option
Ensure that the correct tabs "Cluster", "Project", or both are shown for the appropriate permissions of the logged in user.
Ensure that the "Cluster and Project Members" option in the nav menu does not appear if users should not be able to use either.
A simple Project admin who manages project members will need the appropriate project permissions as well as a global role with the following rules:
Note: This can only be accomplished for a custom role by either creating the role …
> Add additional permission check for cluster and project member admin

- shell/pages/support/index.vue
This PR adds the functionality to have dynamic support links. In result, based on the Rancher version you have installed it'll redirect you to the related version of the support link.
Place you see the link:
Rancher Home -> Commercial Support -> Find out more about SUSE Rancher Support
Fixes rancher/dashboard#8657 
If the build is in dev mode, the support link will go to the latest version support. `https://rancher.com/support-maintenance-terms`
https://github.com/rancher/dashboard/assets/135728925/b3f46215-1b28-4ebe-ab0b-ba1b33e55f56
> 8657 - dynamic versions for support link

- shell/components/DashboardMetrics.vue
- shell/components/GrafanaDashboard.vue
- shell/detail/helm.cattle.io.projecthelmchart.vue
- shell/utils/grafana.js
Fixes #9099 
On most page that the component for embedded grafana dashboards is used, a hardcoded url is passed in, which is then modified to apply a cluster id for downstream clusters, and sometimes the local cluster depending on the version of monitoring installed. The project monitoring detail page, however, does not use hardcoded urls: the urls are pulled from `<projecthelmchart>.status.dashboardValues`. Previously we accounted for the url prefixing the `GrafanaDashboard` component performs by stripping those prefixes from the url that the project monitoring page passes in. This was ..._okay_, until the logic for project monitoring diverged from other monitoring grafana dashboards. 
The solution implemented here is to just trust that the url the backend has provided in the …
> use projecthelmchart dashboardValues for grafana url

- shell/assets/translations/en-us.yaml
- shell/config/uiplugins.js
- shell/plugins/plugin.js
Fixes #9013 
Tackles item  `Better experience when developing against a rancher instance that already has your extension installed.`
- improve developer experience on extensions where builtin extensions will prevent external extension with the same name to load
**To test**
- Have an "external" version extension installed (ex: Elemental)
- Create a new `pkg`/extension on Dashboard named Elemental
- Check that while on local environment, the `pkg`/extension loads instead of the external version
**Screenshots/video**
https://github.com/rancher/dashboard/assets/97888974/a7ef7499-1b75-45eb-9f24-b671f1dece50
> improve developer experience on extensions

- shell/assets/translations/en-us.yaml
- shell/components/ExplorerMembers.vue
- shell/components/form/Members/ClusterPermissionsEditor.vue
- shell/components/form/Members/MembershipEditor.vue
- shell/components/form/Members/ProjectMembershipEditor.vue
- shell/config/product/explorer.js
- shell/models/clusterroletemplatebinding.js
- shell/models/management.cattle.io.clusterroletemplatebinding.js
- shell/models/projectroletemplatebinding.js
- shell/store/type-map.js
Fixes https://github.com/rancher/dashboard/issues/9198
The requirement to work out permissions per project UI side have caused a number of issues. 
Given
- How close we are to release
- The nature of the obscure bugs that have arisen
- The remaining work to address scaling issues with grb and general scaling testing
- The lack of support for admins who gain role via a group
The changes related to https://github.com/rancher/dashboard/issues/9049 will be reverted
Obsoletes
- https://github.com/rancher/dashboard/issues/9159
- https://github.com/rancher/dashboard/issues/9195
- https://github.com/rancher/dashboard/pull/9184
Reverts
- https://github.com/rancher/dashboard/pull/9100
- https://github.com/rancher/dashboard/pull/9166
- https://github.com/rancher/dashboard/pull/9160
This means we go …
> Revert display of Cluster and Projects page for users with project roles and no cluster roles

- .github/workflows/add-to-triage-label.yaml
Updates the auto-labelling GH Action workflow to ignore all labels starting `[zube]:` when deciding whether to auto-label an issue with the `Triage` label.
Have to do a bit of work to check the labels - ended up using a small bash script to do this.
> Modify zube auto-labelling action

- shell/cloud-credential/generic.vue
Relates to https://github.com/rancher/dashboard/issues/8523
- For CloudCA NodeDriver a cloudcredential schema is created (cloudcacredentialconfig)
- This does not contain resourceFields
- In https://github.com/rancher/dashboard/pull/8564/files we changed the logic in one place to look at the resourceFields collection instead of itself
- Need to make a similar change in code below
- This fix aligns what we show in dashboard with ember
> Treat no cloudcredential schema resourceFields as having no schema

- shell/plugins/steve/actions.js
- on by default in 1.25
- in dev world these are warnings, in prod they're debug
- debatable that we output anything in prod, and downgrade dev warnings to debug
- see https://kubernetes.io/docs/reference/using-api/api-concepts/#validation-for-unrecognized-or-duplicate-fields-setting-the-field-validation-level
> Log validation warnings when creating/editing resources

- scripts/build-e2e
- scripts/e2e-docker-start
Fixes https://github.com/rancher/dashboard/issues/9217
- given we now serve the (built) dashboard files we set CATTLE_UI_OFFLINE_PREFERRED=true
- this means the embedded rancher/ui is used
- so now we do something similar to ensure the latest rancher/ui is used
> Use the latest rancher/ui build in e2e tests

- shell/components/GrafanaDashboard.vue
In the imported Harvester clusters, it is necessary to include the parameter referer when accessing the Grafana page. This parameter is required by the backend to identify the origin of the request from which cluster. 
- https://github.com/harvester/harvester/issues/4087
https://github.com/harvester/harvester-installer/pull/512#issue-1759490781
> HARVESTER: keep the param referer on the newly opened grafana page.

- shell/detail/catalog.cattle.io.clusterrepo.vue
ClusterRepo detail page: Add git commit hash for git repos
Fixes #8983
App repository detail page for git repos and http repos should still work.
App repository detail page
> ClusterRepo detail page: Add git commit hash for git repos

- cypress/e2e/po/components/banner-graphic.po.ts
- cypress/e2e/po/components/banners.po.ts
- cypress/e2e/po/components/simple-box.po.ts
- cypress/e2e/po/components/sortable-table.po.ts
- cypress/e2e/po/edit/provisioning.cattle.io.cluster/import/cluster-import.po.ts
- cypress/e2e/po/lists/home-cluster-list.po.ts
- cypress/e2e/po/lists/provisioning.cattle.io.cluster.po.ts
- cypress/e2e/po/pages/docs/whats-new.po.ts
- cypress/e2e/po/pages/home.po.ts
- cypress/e2e/po/side-bars/page-actions.po.ts
- cypress/e2e/tests/pages/cluster-manager.spec.ts
- cypress/e2e/tests/pages/home.spec.ts
- shell/components/BannerGraphic.vue
- shell/components/SimpleBox.vue
- shell/components/SortableTable/index.vue
- shell/pages/home.vue
Added test for the Home page which are:
- User can navigate to What\'s new page
- User can navigate to Preferences page
- User can restore hidden cards
- User can see that cluster details match those in Cluster Management page
- User can use the Manage, Import Existing, and Create buttons 
- User can filter rows in the cluster list
- User can click on support links
1. Under the "Can click on support links" it block, I have commented out the "click Forums link" test because it is failing with a timeout error. Although the Forums page contents load, Cypress does not recognize it (probably because it's an iframe). Cypress' event listener is waiting for the page load event to occur before moving to the next step and because that event is not returned the test fails with time out error. Need …
> ui automation: home page automation

- cypress.config.ts
updated api env variable:
- handles cases where TEST_BASE_URL may or may not contain `/dashboard` suffix.
- this is done by checking if '/dashboard' exists in baseUrl, if so remove it, else do nothing. that way if `localhost:8005` is used as TEST_BASE_URL we will still be able to send api requests.
> ui automation: update api env variable

- shell/components/form/NodeAffinity.vue
- shell/components/form/PodAffinity.vue
- shell/components/form/__tests__/NodeAffinity.test.ts
- shell/components/form/__tests__/PodAffinity.test.ts
Accroding to the comment https://github.com/harvester/harvester/issues/2317#issuecomment-1617940290, we would like to keep the weight input component when we edit it.
- https://github.com/harvester/harvester/issues/2317#issuecomment-1617940290
> HARVESTER: only change priority by select component

- cypress/e2e/po/components/banners.po.ts
- cypress/e2e/po/components/component.po.ts
- cypress/e2e/po/pages/home.po.ts
- cypress/e2e/po/side-bars/user-menu.po.ts
- cypress/e2e/tests/pages/home.spec.ts
- many improvements to user menu po
- take into account the v-popover container which can hide child menu content
- fix selector of component that we click on to open menu
- add naughty ensureOpen (as it contains an anti pattern...but included due to issues we've had with this component)
- tidied up names
- adding some logging
- move home page specific banner components in to home page po
- also ensure these return an instance of the banner po
- Testing locally with chrome never showed the issue that ci had (CI uses chrome as well)
- Switching to test locally with electron meant there was about a 30% chance of seeing the issue
> Improvements to flaky user avatar tests

- docusaurus/docs/extensions/api/actions.md
- shell/core/plugin-helpers.js
- shell/core/types.ts
Fixes #8117 
- add support for enabled as a function in table action extension point + update extension docs
- create a new extension/package on rancher dashboard by running the following command: `yarn create @rancher/pkg test`
- edit the `index.ts file` of the newly added test extension/package with the following code:
```
import { importTypes } from '@rancher/auto-import';
import { IPlugin, ActionLocation, ActionOpts } from '@shell/core/types';
// Init the package
export default function(plugin: IPlugin) {
// Auto-import model, detail, edit from the folders
importTypes(plugin);
// Provide plugin metadata from package.json
plugin.metadata = require('./package.json');
// Load a product
// plugin.addProduct(require('./product'));
plugin.addAction(
ActionLocation.TABLE,
{ resource: …
```
> Handle enabled flag per row for table actions properly (as a function) on extension API

- shell/detail/pod.vue
The overlay loading was only used to show/hide one of the tabs(pod-metrics) in the pod details page. After discussing this with the UX/UI team the final decision was to remove the loading.
Fixes #9236
> Remove overlay loading from pod details

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/pages/c/_cluster/explorer/index.vue
- shell/store/prefs.js
Fixes #9229
Removed new cluster tools banner from the dashboard page
Go to cluster dashboard > cluster tools banner should not be there
> Removed cluster tools banner from dashboard page

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/config/uiplugins.js
- shell/pages/c/_cluster/uiplugins/PluginInfoPanel.vue
- shell/pages/c/_cluster/uiplugins/index.vue
Fixes #9113 
- add logic to display message on installed extension card to warn user when kubernetes version for installed extension is not met 
- add logic to disable version buttons on info side panel
- Improve display of incompatibility messages
- code cleanup
> Handle extensions that are already installed and shouldn't run in a particular kube version

- shell/core/plugin.ts
- shell/initialize/App.js
- shell/initialize/layouts.ts
- shell/pkg/auto-import.js
- shell/utils/settings.ts
This allows extensions to create a layouts directly which will then be auto-imported and made available as nuxt style layouts.
Addresses one facet of https://github.com/rancher/dashboard/issues/9216
> Add the ability to import layouts from extensions

- shell/chart/__tests__/S3.test.ts
- shell/chart/rancher-backup/S3.vue
- shell/chart/rancher-backup/index.vue
- shell/pages/c/_cluster/apps/charts/install.vue
Fixes #6181
Marked bucket name and endpoint fields as required and disabled "install" and "update" buttons if these fields are empty.
- Marked fields as "required"
- Disabled default behaviour for "values" step for backup chart
No default behaviour has changed. Added a "valid" event listener to chart installer that should be used by other charts if fields require validation.
Tested in Chrome
1. Go to "Apps"-> "Charts"
2. Select "Rancher backups"
3. There are 2 scenarios here. New chart creation and updating already existing chart. This fix applies to both.
4. Click "Install" (for new) or "Update" (for existing)
5. Click "Next"
6. Select "Use an S3-compatible object store"
7. Validate that "Bucket Name" and "Endpoint" fields are marked as required
8. Validate that "Install" or "Update" …
> Added validation to 'Rancher backups' chart installer

- docusaurus/docs/extensions/advanced/provisioning.md
- docusaurus/docs/extensions/api/common.md
- docusaurus/docs/extensions/api/components/node-drivers.md
- docusaurus/docs/extensions/api/provisioning.md
- docusaurus/docs/extensions/home.md
- docusaurus/docs/guide/custom-dev-build.md
- docusaurus/sidebars.js
- shell/components/form/NameNsDescription.vue
- shell/components/form/ResourceTabs/index.vue
- shell/config/labels-annotations.js
- shell/core/plugin-helpers.js
- shell/core/types-provisioning.ts
- shell/core/types.ts
- shell/detail/provisioning.cattle.io.cluster.vue
- shell/edit/provisioning.cattle.io.cluster/index.vue
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
- shell/edit/ui.cattle.io.navlink.vue
- shell/list/provisioning.cattle.io.cluster.vue
- shell/mixins/child-hook.js
- shell/mixins/create-edit-view/impl.js
- shell/models/provisioning.cattle.io.cluster.js
- shell/scripts/typegen.sh
- shell/store/plugins.js
- shell/utils/kube.js
- shell/utils/object.js
This is work-in-progress changes to allow Extensions to add custom provisioning UI into Dashboard without needing to use the NodeDriver approach.
See https://github.com/nwmac/provisioning for more information
Changes in this PR:
- Update `NameNsDescription` component so that it can be supplied with a list of namespaces that the user can select from - custom provisioning might want to allow the user to choose a namespace - the current provisioning always creates resources in `fleet-default`
- Updates `ResourceTabs` to add `extensionParams` to allow custom tabs to be targeted to a specific context based on some arbitrary parameters - in the case of provisioning, we want to only show a custom tab for a specific provisioner
- Adds an annotation `ui.rancher/provider` that can be used to …
> Extension support for custom provisioning

- shell/components/ResourceTable.vue
- shell/detail/node.vue
- shell/detail/workload/index.vue
- shell/store/type-map.js
Fixes #8674 
- add logic to support new table cols via extensions hook on `resource table` instead of `type-map` so that we can capture tables/resources with locally defined headers like the `nodes` list
- create a new extension/package on rancher dashboard by running the following command: `yarn create @rancher/pkg test`
- edit the `index.ts` file of the newly added test extension/package with the following code:
```
import { importTypes } from '@rancher/auto-import';
import { IPlugin, TableColumnLocation } from '@shell/core/types';
// Init the package
export default function(plugin: IPlugin) {
// Auto-import model, detail, edit from the folders
importTypes(plugin);
// Provide plugin metadata from package.json
plugin.metadata = require('./package.json');
// Load a product
// …
```
> Wire in extension table column feature to cluster `node` list and other hardcoded places

- cypress/e2e/po/pages/extensions.po.ts
- cypress/e2e/po/pages/extensions/kubewarden.po.ts
- cypress/e2e/tests/pages/extensions.spec.ts
- cypress/e2e/tests/pages/extensions/kubewarden.spec.ts
- shell/pages/c/_cluster/apps/charts/index.vue
Fixes #9231 
This adds e2e tests for installing the Kubewarden extension. Includes:
- Enabling extensions
- Installing the Kubewarden extension
- Checking for route collisions with the Apps/Charts and Apps/Repositories pages
- Checks that 'Kubewarden' is shown in the side-navigation
- Checks that the Kubewarden dashboard page loads correctly.
> Add e2e tests for Kubewarden extension installation

- shell/assets/translations/en-us.yaml
- shell/mixins/brand.js
- shell/pages/auth/logout.vue
Fixes #9270
- Green branding should be applied when the `rancher-csp-adapter` app is installed (https://github.com/rancher/csp-adapter)
- This was not happening, fix is to ensure the reactive parts fire correctly again
- I'm not sure when this came in, possibly 2.7.5
- ui-brand setting comes from the existence of a helm app
- this was broken for the initial case
-  cause by a computed property not re-running given change after `fetch`
- fixing this reactivity exposed some other scenarios where we need to be safe
- for instance when logged out, or in the process thereof
> Also fixed the position of the `Logging Out...` text. Previously this was at the top of the page, it's now in the centre
To Test in Dev
- Update `return this.apps.find((a) => a.metadata.name === 'rancher-csp-adapter');` …
> Fix initialisation of `ui-brand` setting

- shell/assets/translations/en-us.yaml
- shell/detail/autoscaling.horizontalpodautoscaler/index.vue
- shell/edit/autoscaling.horizontalpodautoscaler/hpa-scaling-rule.vue
- shell/edit/autoscaling.horizontalpodautoscaler/index.vue
Kubernetes added additional functionality to HorizontalPodAutoscalers to configure the autoscaling behavior. This has been stable since Kubernetes 1.23.
Documentation https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#configurable-scaling-behavior
API Reference https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/#HorizontalPodAutoscalerSpec
Fixes #9032
* Adds form fields to edit the autoscaling behavior in the HPA edit form
* Adds autoscaling behavior information on the HPA detail page
HPA creation/edit form, HPA detail page.
HPA creation/edit form, HPA detail page.
> Add HorizontalPodAutoscaler scaling behavior support

- shell/assets/translations/en-us.yaml
- shell/edit/__tests__/fleet.cattle.io.gitrepo.test.ts
- shell/edit/fleet.cattle.io.gitrepo.vue
- shell/models/fleet.cattle.io.gitrepo.js
Fixes #9223 
Added a checkbox to enable self-healing feature for the Drift.
Added a checkbox.
Added a checkbox corresponding to spec.correctDrift.enabled.
It is disabled by default.
Go to "Continuous delivery" -> "Git repos" -> "Add repository"
Step 1 should have "Enable Self-healing checkbox"
After creation, created resource should have "spec.correctDrift.enabled" set to the value of the checkbox.
"Add repository" wizard and edit views
> Added UI to enable Fleet self-healing

- package.json
- shell/components/FileDiff.vue
- shell/components/YamlEditor.vue
- shell/package.json
- yarn.lock
Fixes #9313
- FileDiff component used in the YAML editor
- Seen when Editing by YAML, or Editing by Config and switching to YAML. Then press show diff button at bottom
- Rendering was completely off in the old version of diff2html, so use latest
- Latest version of diff2html requires use of new component to render component same as before
- This has a slightly different implementation
- Bonus point - Fixed a rendering issue when editing yaml --> switch to diff --> resize. the bottom bar action buttons disappeared off screen. Now fixed
Component is used in two contexts
1. Resource --> Edit YAML --> (make change) --> Show Diff
2. Resource --> Edit Config --> Edit as YAML --> Show Diff
Component should render ok in light and dark modes
Both unified and split modes should render ok
> Fix broken YAML File Diff

- shell/components/auth/RoleDetailEdit.vue
- shell/components/form/Select.vue
- shell/edit/networking.k8s.io.ingress/RulePath.vue
Fixes #9209 
- Fix issue with Select `resources` in GlobalRoles edit/create view where selecting an item with duplicate labels caused the Select to become unusable
- update `getOptionKey` in `Select` component to match the same code as in `LabeledSelect` (since it's the same usage of `v-select`, don't understand the particularity of the code before, also given the fact that `LabeledSelect` works fine)
- Remove `option-key` and `option-label` from the only place where the usage of the component `Select` had it defined in Dashboard, since it's the default for components that use `v-select`
Notes:
- Both Kubewarden and Elemental don't make use of `Select` component - checked it
- Cannot fix the `Select` pointing to `apps` in `project.cattle.io`, since both have the exact same label. In this …
> fix issue with Resources Select in globalRoles edit/create interface

- shell/scripts/extension/publish
Fixes #9277 
The `urls` property was being correctly populated with the `BASE_URL` (`assets/`) directory initially but was being overwritten when the script reached lines 302 or 307.  This would only occur if the Root index existed, so in the case of the issue, the `index.yaml` was found and placed at the root level - As it existed the index was being updated with the assets within the `./assets` directory while not specifying the `--url` property, thus overwriting what had been previously applied on line 293.
These conditions exist for container image build, as this could be an initial build (i.e. no root index.yaml exists yet) or it could be an updated build where the index.yaml would most likely exist.
Added two conditions:
1. If the root index.yaml exists && the build is not …
> Add conditions for updating root index of extension

- cypress/e2e/po/pages/explorer/workloads.po.ts
- cypress/e2e/po/pages/page.po.ts
- cypress/e2e/po/side-bars/product-side-nav.po.ts
- cypress/e2e/tests/navigation/not-found-page.spec.ts
- cypress/e2e/tests/pages/explorer/api/api-services.spec.ts
- cypress/e2e/tests/pages/explorer/cluster-project-members.spec.ts
- cypress/e2e/tests/pages/explorer/workloads/workloads.spec.ts
- shell/components/ResourceDetail/index.vue
- shell/middleware/authenticated.js
- shell/store/type-map.js
Fixes #9336
This PR updates the schema check in auth middleware to also look in the current store. The problem described in #9336 seems to be happening because the standard user can't see pods in the management store, as they only have access to pods in the downstream cluster.
Pages generated by dynamic routes in downstream clusters as a user with limited access to the local cluster; bogus routes should still fail
> Fix authenticated middleware schema check for users who cant access the local cluster

- cypress/e2e/po/pages/extensions.po.ts
- cypress/e2e/tests/pages/extensions.spec.ts
- shell/assets/translations/en-us.yaml
- shell/pages/c/_cluster/uiplugins/index.vue
Fixes #9214 
- sneaky-fix to address misformatted banner on extensions for partners repo
**Before**
**After**
> address misformatted banner on extensions por partners repo

- cypress/e2e/tests/navigation/not-found-page.spec.ts
- shell/components/ResourceDetail/index.vue
- shell/config/product/manager.js
- shell/middleware/authenticated.js
- shell/pages/c/_cluster/manager/cloudCredential/_id.vue
- shell/pages/c/_cluster/manager/cloudCredential/create.vue
Fixes #9377
This PR also prevents the same 'resource not found' error from being shown on the cloud credential creation screen.
Currently we're checking the current cluster's store for the existence of a given resource - in downstream clusters, this store wont include management resources that appear on eg cluster membership list view and project creation. I looked around and found one page that references a norman type in the url, cloud creds, so I added the rancher store to the schema check as well.
I didn't add a test for the cluster membership view as I think we need a downstream cluster present to catch the error reported in 9377. I'm leaving the tags in the test I did add to verify that CI passes - when https://github.com/rancher/dashboard/pull/9360 is merged this PR should be …
> check mgmt store and norman store before throwing resource not found

- .github/workflows/test.yaml
- cypress/e2e/po/components/sortable-table.po.ts
- cypress/e2e/po/pages/extensions.po.ts
- cypress/e2e/po/pages/extensions/kubewarden.po.ts
- cypress/e2e/po/pages/home.po.ts
- cypress/e2e/po/side-bars/user-menu.po.ts
- cypress/e2e/tests/navigation/not-found-page.spec.ts
- cypress/e2e/tests/pages/cluster-manager.spec.ts
- cypress/e2e/tests/pages/explorer/api/api-services.spec.ts
- cypress/e2e/tests/pages/extensions.spec.ts
- cypress/e2e/tests/pages/extensions/kubewarden.spec.ts
- cypress/e2e/tests/pages/home.spec.ts
- cypress/e2e/tests/pages/login.spec.ts
- cypress/e2e/tests/setup/rancher-setup.spec.ts
- cypress/globals.d.ts
- cypress/support/commands.ts
- cypress/support/commands/commands.ts
- cypress/support/commands/rancher-api-commands.ts
- cypress/support/e2e.ts
- shell/pages/c/_cluster/explorer/index.vue
- shell/types/userPreferences.d.ts
- Following on from https://github.com/rancher/dashboard/pull/9338
- Add standard user to project in local cluster, which gives pods visibility,
- new commands to add cluster and project roles. also to find a project
- We should make a helper functions / framework for making http requests to rancher in cypress
- Run not found tests as both admin and non-admin
Also
- Fixed issue where user's who can get to the 'local' cluster dashboard page but do not have access to mgmt nodes won't see a warning of failure to fetch mgmt nodes
- Possibly fixed an issue where failures when running the standard users tests did not result in the gh workflow to fail
- "Improve" user avatar open yet again
- Improve flaky `New repos banner should only appear once (after dismiss should NOT appear again)` test …
> Re-enable standard user page not found tests

- shell/models/management.cattle.io.kontainerdriver.js
Fixes https://github.com/rancher/dashboard/issues/6810
- the dashboard uses the kontainerdriver id for things like images, text and also to provide embedded ember with a key to identify the cluster ... and which custom ui to use
- this works fine when the id is the type of kontainerdriver
- this doesn't if the kontainerdriver is custom and has a random id
- for these cases use the status.displayName 
- everything is done via the driverName (id, and also ember key) so fix it there
> The localised name and logo for the custom driver card come from the dashboard. creators of custom cluster drivers will need to create an extension with those in. 
See repo steps in https://github.com/rancher/dashboard/issues/6810
- provisioning different types of cluster drivers
- i've tested EKS, other built …
> Fix how custom cluster drivers identify themselves

- cypress/e2e/tests/pages/home.spec.ts
- package.json
- yarn.lock
Hopefully will resolve. 
```
Cannot read properties of undefined (reading 'isServer')
TypeError: Cannot read properties of undefined (reading 'isServer')
at TLSWrap.onerror (node:_tls_wrap:411:27)
```
There's more to this story, see https://github.com/cypress-io/cypress/issues/22291 for additional information
> Three checks for navigating to pages outside of the dashboard have been disabled - https://github.com/rancher/dashboard/issues/9417
> Bump version of cypress to latest 10.x

- docusaurus/docs/extensions/api/common.md
- shell/core/plugin-helpers.js
- shell/core/types.ts
Fixes #9384 
- Update `locationConfig` cross-check to use a new `path` param when using extensions API
- create a new package `yarn create @rancher/pkg test`
- try and add a new table col with `path` to `projectnamespaces` page
> improve location config cross-check with path param

- docusaurus/docs/code-base-works/forms-and-validation.md
- jest.config.js
- shell/assets/translations/en-us.yaml
- shell/components/LazyImage.vue
- shell/components/form/FileImageSelector.vue
- shell/components/form/FileSelector.vue
- shell/components/form/__tests__/FileImageSelector.test.ts
- shell/components/form/__tests__/FileSelector.test.ts
- shell/edit/__tests__/ui.cattle.io.navlink.test.ts
- shell/edit/ui.cattle.io.navlink.vue
- shell/pages/c/_cluster/settings/brand.vue
- shell/utils/fileTypes.js
- svgTransform.js
Fixes #9348
Fixes #5184 
Changed "Navlinks" page from tabular to regular page, added validation to it and error message on file upload. Changed FileSelector to FileImageSelector on "Branding" page.
For Branding page:
- Changed all occurrences of FileSelector to FileImageSelector
For Navlinks page:
- Disabled  "Create" button if required fields are not filled in
- Removed tabs
- Added error on file upload
For FileSelector:
- Added type validation if expected type is image
Added MIME byte checking to validate that uploaded file is an image (https://mimesniff.spec.whatwg.org/#matching-an-image-type-pattern) 
Used Chrome for local testing.
Open "Local" -> "NavLinks" -> "Create"
- Tabs should be removed
- "Create" button should be disabled
- Validate that filling in required fields enables …
> Changed navlink page and improved error handling for FileImageUpload

- docusaurus/docs/code-base-works/directory-structure.md
Added documentation on the layouts directory since it was mentioned in the discuss-extensions slack channel
> Adding documentation for the layouts directory

- shell/components/form/MatchExpressions.vue
- shell/edit/fleet.cattle.io.clustergroup.vue
- shell/utils/selector.js
Fixes #9256 
Notes: when creating via YAML a label with value `null`, the server returns it as an empty string, which falls in place with the usecase of this issue
- Fix issue where matching rules (for `Banner` string saying X matching ....) weren't accounting for an empty string value
- Fix issue in `MatchExpressions` where we were ignoring an expression value if it was an empty string, therefore removing that whole expression from the payload without considering it could be an empty string.
- Add missing dispatch to `FLEET.CLUSTER` on `edit/fleet.cattle.io.clustergroup.vue` so that page can work properly on hard refresh
> UI says "Matches no existing clusters" when there is a null value for cluster selector in cluster groups

- shell/components/nav/WindowManager/ContainerShell.vue
Fixes #9422 
- Update `height` prop definition to not be required, like `width` in `ContainerShell`
- Update `proposeDimensions` return to be empty object in the case it can return `undefined`
**NOTE:** with UI 2.7.5 (remote instance) I couldn't reproduce the bug
- run latest UI code
- go to `local` cluster explorer
- Open a shell (header button)
- Go to `profile` -> `Account & api keys`
- Navigate back to local cluster explorer (back button on `Account & api keys` page)
- Check that there are no logs on the console
> fix issue with height on containerShell

- cypress/e2e/po/components/ember/ember-input.po.ts
- caused by change in rancher/ui to data-testid for ember input component
- matches incoming fix from https://github.com/rancher/dashboard/pull/9247/files#diff-a28e7dd962b16d8e0570014b50460e8d8fbc8b47e72bd58c6d272e75bb821e49R27
> Fix broken rke1 e2e tests

- shell/edit/ui.cattle.io.navlink.vue
Fixed compilation warning because of the wrong import in ui.cattle.io.navlink.vue
> fixed bad import in NavLinks

- cypress/e2e/po/pages/page.po.ts
- cypress/e2e/po/pages/users-and-auth/users.po.ts
[One of the roles e2e test intermittently fails](http://139.59.134.103/instance/6cc9a893-c1ed-4177-b11e-af3e5a494b10/test/r8 ) with a timeout error when navigating to the Users page. This seems to be a scenario-specific issue; the admin user logs out, then the standard user logs in and navigates to the Users page. In this scenario, the Users page sometimes takes more than 10 seconds to load which is greater than the 10-second timeout set in the test.
Fix:
- Add `timeout` as an argument in the goToAndWaitForGet() function (default value of 10 sec)
- Increase timeout in users.po when navigating to the Users page (from 10 sec to 15 sec)
Failing test: http://139.59.134.103/instance/6cc9a893-c1ed-4177-b11e-af3e5a494b10/test/r8 (**see error on the first attempt - that's the relevant one**)
> fix e2e test in roles.spec

- cypress/e2e/po/components/ember/ember-input.po.ts
- shell/models/management.cattle.io.cluster.js
- shell/pages/c/_cluster/apps/charts/install.vue
Contributes to https://github.com/rancher/dashboard/issues/8841
- Any exception thrown prior to `this.value` being set will result in an empty page
- These changes might solve some issues with blank pages, 
- For cases where the exception thrown is something that we latter depend on causing other issues.... we at least know where to start looking
- I also moved `this.error = []` up to the start, as one of the functions adds an entry to it
- Installing a chart
- Installing a chart where there is a global or cluster registry
- Installing a chart
- Installing a chart where there is a global or cluster registry
> Add additional error handling to install chart page

- shell/assets/translations/en-us.yaml
- shell/pages/auth/login.vue
- shell/store/auth.js
Fixes #9482
Currently when a login request fails we show one of two generic error messages. This PR updates the error-catching behavior to show a specific error message when one has been provided, except 401 errors, which still show `Invalid username or password. Please try again.`
> Show ad migration login error message

- cypress/e2e/tests/pages/extensions.spec.ts
- docusaurus/docs/extensions/extensions-configuration.md
- pkg/harvester-manager/package.json
- shell/pages/c/_cluster/uiplugins/index.vue
Fixes #9501 Fixes #9318
The issues mentioned by @jtomasek about how we displayed the `catalog.cattle.io/display-name` for an extension was different depending on the existence of an extension chart. Also we were not searching for the correct property (`rancher.annotations`) for this annotation. Enforcing the "annotations" property within the `package.json` should be the correct approach.
There was also an issue in how we were determining if an extension was installed by comparing the `plugin.name` with the `chart.name` - However, the `chart.name` was determined by the `chartDisplayName` rather than the actual chart name. So when the `catalog.cattle.io/display-name` was declared, the `chartNameDisplay`, which did not match the name of the installed extension, was being used to filter all …
> Fix extension displayName annotation conditions - add configuration docs

- pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue
- shell/components/form/UnitInput.vue
- shell/components/form/__tests__/UnitInput.test.ts
Fixes #9467 
- add @change event to capture arrow presses for `UnitInput` on firefox (is sent still as an `input` event, so that it won't break the current usage of `UnitInput` throughout the UI)
Follow repro steps on https://github.com/rancher/dashboard/issues/9467 (issue was found on Firefox 116)
> Resource Quota up-and-down input doesn't update the value on the request quota object to be sent

- docusaurus/docs/extensions/api/common.md
- docusaurus/docs/extensions/api/table-columns.md
- shell/components/ResourceTable.vue
- shell/core/plugin-helpers.js
- shell/core/types.ts
- shell/package.json
Fixes #9511 
- add hash param to `locationConfig` object in extensions to allow fine-tune of application of an extension point 
- **Sneaky fix**: change logic around extension table cols to better reflect col location based on page user is browsing and not just resource, because same resource can be in multiple pages, but extra table col may only be meaningful in a specific page **->** 
_this will introduce breaking change as target is now different. I believe it's for the best as this allows us to selectively target tables inside resource detail page, which combined with the new `hash` parameter, allows for a finer control of the application of any extension enhancement._
- create a new package `yarn create @rancher/pkg test`
- on the `index.ts` file for the newly created package, …
> locationConfig hash param

- shell/creators/pkg/init
Fixes #9418 
This adds the annotation `catalog.cattle.io/rancher-version` to newly created extension packages by default. When running `yarn create @rancher/pkg <pkg>`, the init script will fetch the latest Rancher version from: https://api.github.com/repos/rancher/rancher/releases/latest
> Add latest rancher version annotation to extension pkg package.json

- shell/assets/translations/en-us.yaml
- shell/components/GrowlManager.vue
- shell/config/settings.ts
- shell/plugins/steve/__tests__/header-warnings.spec.ts
- shell/plugins/steve/actions.js
- shell/plugins/steve/header-warnings.ts
- shell/utils/settings.ts
Fixes #8502 
- add growl message to display warning messages from response headers
- update growl styling based on feedback from @edenhernandez-suse 
- This was the only mechanism that we have of "easy access" to display warnings from response headers. Also, these types of warnings are non-persistent (they don't exist on the object resource), so we can't show them on the details screen (ex: in this particular case `DaemonSets`, but you have the related events).
- Test scenario of the above mentioned issue #8502 to check that the mechanism works as expected
- Took the time creating a few different resource instances (clusters, global role, pod, persistent volume, some things in fleet, etc) just to check if there were any additional growls that we didn't know about (we don't want to flood …
> add growl message to display warning messages from response headers

- cypress.config.ts
- cypress/e2e/po/pages/home.po.ts
- cypress/e2e/tests/pages/home.spec.ts
- package.json
- yarn.lock
Handles https://github.com/rancher/dashboard/issues/9417
- 'Docs' link test: 
- I've added `.skip` on the test which simply skips the test until we have a fix for the root of the issue. The actual fix will need to come from resolving the uncaught exception (err message: MktoForms2 is not defined) which I've reported [here](https://github.com/rancher/rancher-docs/issues/727). 
- I've tried adding exception handling as a temporary workaround but no dice.
- 'Forums', 'Slack', and 'File an Issue' link tests: 
- re-enabled tests
- added `chromeWebSecurity: false` to cypress.config file which disables web security. This allows us to access cross-origin iframes that are embedded in our application and navigate to any superdomain without cross-origin errors.
- see …
> fix support links tests

- shell/components/formatter/ClusterProvider.vue
- shell/components/formatter/__tests__/ClusterProvider.test.ts
Additional checks for covering imported AKS/EKS clusters.
Fixes #9519
> Fixed 'imported' label not showing up for imported AKS/EKS clusters

- shell/vue-config-helper.js
- shell/vue.config.js
Fixes #9615 
- Update shell vue.config to allow the passing of a proxy configuration
- Clone the SUMA POC extension https://github.com/aalves08/suma-extension
- update the `vue.config` in SUMA extension to:
```
const config = require('@rancher/shell/vue.config');
const configHelper = require('@rancher/shell/vue-config-helper.js');
module.exports = config(__dirname, {
excludes: [],
proxies:  { '/rhn/manager': configHelper.proxyOpts('https://ec2-52-206-103-214.compute-1.amazonaws.com') }
});
```
- run the project with `API=https://ec2-54-205-80-46.compute-1.amazonaws.com:8443 yarn dev`
- ping me for user credentials
- Go to Clusters -> Cluster management -> and click on the cluster `one` to view it's details
- make sure the col `SUMA patches` appears populated on the `machine pools` tab
- …
> Recover proxy config mechanism

- shell/edit/provisioning.cattle.io.cluster/index.vue
- shell/models/catalog.cattle.io.clusterrepo.js
Fixes #9510 
- force fetch and reset of catalog/load in order to get updated cluster templates every time we hit refresh on the cluster repo
- Fork https://github.com/susesgartner/cluster-template-examples so that you can edit it
- **NOTE:** The below sequence should be without any browser refresh of the tab that shows your Dashboard
- Go to `Cluster Management` -> `Advanced` -> `Repositories` and add your fork as a repo (branch main)
- Go `Cluster Management` -> `Clusters` and hit `Create`
- Check that on the options for cluster creation you have 2 cluster templates (if you haven't modified your forked repo)
- Go to `Cluster Management` -> `Advanced` -> `Repositories` and stay on that screen
- In a new tab, go to your fork of https://github.com/susesgartner/cluster-template-examples and …
> New cluster template isn't displayed after repository refresh

- shell/components/formatter/PrincipalGroupBindings.vue
Fixes #9633 
When displaying the global role bindings, we were checking for any bound roles that were tied to a `principal.id`. If the `principal` was undefined the `boundRoles` computed property would cause an error.
Added a null coalescing operator to catch undefined principals.
***Groups error before***
https://github.com/rancher/dashboard/assets/40806497/5f0d45a0-6a90-4ca4-adb9-8ec99cb9e2e1
***Groups error after***
https://github.com/rancher/dashboard/assets/40806497/9447a76c-8345-4906-90bf-5a1a8fd79319
> Fix boundRoles for undefined principals

- shell/edit/resources.cattle.io.backup.vue
- shell/edit/resources.cattle.io.restore.vue
- shell/utils/__tests__/formatter.test.ts
- shell/utils/formatter.js
Fixes #2405 
Dropdown is already only showing secrets that belongs to the current namespace.
Sorted and filtered out non-opaque secrets in "Encryption config secret" drop down in "Backup" and "Restore" wizards
Go to the cluster -> "Rancher backups" -> "Backups"/"Restores" -> Create backup/restore
Select "Encrypt backups using an Encryption Config secret (Recommended)"
"Encryption config secret" dropdown should only contain Opaque secrets and they should be sorted alphabetically
> Filtered out non-opaque secrets in backup/restore

- cypress/jenkins/Jenkinsfile
- cypress/jenkins/cypress.sh
- cypress/jenkins/init.sh
- cypress/jenkins/reporter-options.json
- cypress/jenkins/scpget.sh
This is for executing the UI tests in Jenkins UI
The logic starts in `init.sh` which prepares the Jenkins executor with the software dependencies and an external node for test execution using [a corral package.](https://github.com/rancherlabs/corral-packages/pull/17). The execution logic is then done by the corral script executed. See the package PR.
The variables values come from the Jenkins job. That's a separate PR in a private repo. The Jenkinsfile is also included in this PR. It gets pulled by the Jenkins pipeline.
This makes use of the official Cypress' [Docker images](https://github.com/cypress-io/cypress-docker-images). The included one. The image version and type is included as variables in Jenkins.
Cypress reporter modules is installed in the Cypress docker image and the report …
> Initial work for integrating the UI tests with Jenkins

- shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #9520 (ish, see below and https://github.com/rancher/dashboard/issues/9520#issuecomment-1702869821)
Overview
- Addons are helm charts installed into the provisioned cluster
- Addons to install are determined by kube version and cloud provider
- Addons have values/config that can be provided when provisioning
Bug
- Previously we were looking for the helm chart associated with the addon in the chart cache
- The cached charts are specific to the kube version of the host. If the chart is invalid due to kube version of host, it's not supplied to us thus not in cache
- If a user wants to install a valid chart in the provisioned cluster which was invalid for the local cluster, we would fail to find the chart
Fix
- In all worlds, regardless of global cache state, we need to fetch the full …
> Ensure we always fetch rke2 cluster addon charts

- shell/edit/logging.banzaicloud.io.output/index.vue
Fixes #7978
fixed sticky footer in Logging `Cluster Outputs` and `Outputs` create forms
- install logging cluster tool
- navigate to either of the two resources
- click create
- the footer isn't stuck to the bottom
> Outputs form sticky footer

- shell/edit/workload/storage/ContainerMountPaths.vue
Fixes #9607 
The `volumeMounts` for a pod template spec were being overwritten if there was not a defined `volume` for the mount. In this case the `volumeMount` was referencing a `volumeClaimTemplate`, as the claim was not determined in the `volumes` property, this mount was being overwritten when filtering for volumes matching a `volumeMount` name.
Where the volumes are fetched, those methods are now returning a clone of the value rather than the filtered value itself.
https://github.com/rancher/dashboard/assets/40806497/a13415d9-3ae4-44e7-acf6-259302c5b2a7
> Fix volumeMounts from being overwritten

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
Added a paragraph tag as a wrapper for the message so the parent's flexbox styling doesn't break the message because of having italics tags `<i>` in it.
Fixes #9593 
Before:
After:
> Fixed broken paragraph message for psp warning

- shell/assets/translations/en-us.yaml
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #9110 
Fixes #9204 
Create an AWS cluster and select the AWS Cloud Provider.
Edit the cluster and change the k8s version to 1.27 - we now change the provider to 'External' and show a banner. If you change back to 1.26, we revert to the AWS Cloud provider.
Note: Added some test code (commented out) that can be un-commented to add a fake 1.27 version for dev/testing.
> Aws In-tree support

- shell/public/index.html
- previously we would wait till the user sets a theme to either auto or dark for the initial loading indicator to be dark
- this change means we treat no theme set as auto (aka pick up from OS)
- this will be the case for most users
- as soon as the user sets a theme the code should continue as before
- follows on from https://github.com/rancher/dashboard/pull/9022
> Fix theme of initial loading page when user hasn't previously selected a theme

- shell/initialize/App.js
- shell/initialize/client.js
- shell/initialize/index.js
- shell/mixins/fetch.client.js
- shell/vue.config.js
Fixes #9542
- white page errors should not be visible in prod
- these were enabled in all envs via the port of shell/initialize/client.js after nuxt
- that file came from the output of a rendered template
- the rendered template has features enabled only when debug/isDev process envs are on
- the rendered file had these on, so features were on in prod
- fix is to at run time disable these features
- Additionally..
- set some process values that were being skipped but still used
- always log uncaught errors in `fetch`s. in theory we should be monitoring $fetchState.error but we never do. this has led to some painful debugging with customers
- anywhere an error might occur
- see issue description, the easiest way is to edit code
> Fix white page errors in prod

- shell/utils/__tests__/sort.test.ts
- Following on from a discussion regarding the app bar i was investigating the `sortBy` function
- Realised this might as well take the form of unit tests
- There's more angles we could take on this, but it covers the basic set of a single sort property, two sort properties and descending features
> Add unit tests for sortBy

- shell/machine-config/amazonec2.vue
Fixes #9636 
The `value.subnetId`, `value.vpcId`, and `selectedNetwork` properties were not being updated/reset when the region was updated. 
Added a call to the `updateNetwork` method within the `watch` for `value.regions`, this will reset the `value.subnetId`, `value.vpcId`, and `selectedNetwork` properties to the original `null` value.
I decided adding in the form validation as suggested in the original issue would over-complicate the machine-config when simply resetting the value would suffice.
> Reset network property when region is updated

- shell/components/form/LabeledSelect.vue
- shell/components/form/__tests__/LabeledSelect.test.ts
Fixes #9668 
Two things contributing to this:
1. `getOptionLabel` iterates over every option for each option, to address https://github.com/rancher/dashboard/issues/8149
2. `getOptionLabel` is called _a lot_ 
By adding a console.log to `getOptionLabel` I can see that the function re-runs for each option when the user mouses over options. Even providing the minimum necessary configuration to v-select I see this happening, which makes me think it is baked into the component library we are using.
This PR updates `getOptionLabel` to skip the label-checking logic when options don't have separate labels and values. This means that the LabeledSelect performance with very long lists of options is _only_ fixed if the options prop is an array of strings or numbers. I couldn't work out how else to …
> Reduce performance impact of LabeledSelect getOptionLabel

- shell/components/nav/Header.vue
Fix the alignment of the header icon when in standalone mode
- Screenshot is of epinio. This will also fix harvester standalone world
Before
After
> Fix the header icon alignment in Standalone mode

- shell/components/nav/TopLevelMenu.vue
The following is spammed to console when cluster name tooltips are shown
Needed `hide` - https://popper.js.org/docs/v2/modifiers/hide/
> Fix issue where popperjs spammed console warnings

- shell/assets/translations/en-us.yaml
- shell/config/table-headers.js
- shell/pages/c/_cluster/uiplugins/CatalogList/CatalogLoadDialog.vue
- shell/pages/c/_cluster/uiplugins/CatalogList/CatalogUninstallDialog.vue
- shell/pages/c/_cluster/uiplugins/CatalogList/index.vue
- shell/pages/c/_cluster/uiplugins/UninstallDialog.vue
- shell/pages/c/_cluster/uiplugins/index.vue
Reconfigured the deployment of an extension catalog image to not create a `UIPlugin` resource as it is unnecessary for the `ui-plugin-operator` to cache the extension files before installation of an extension.
Now when importing a catalog image, there will only be the deployment, service, and helm repository created - which will serve the extension charts and display them within the "Available" tab.
> Reconfigure extension catalog deployment - remove UIPlugin resource

- shell/components/nav/TopLevelMenu.vue
Fixes #9683
Fixed condition for `No matching clusters` text
==== No cluster pin  ======
==== All clusters are pinned ======
> No matching clusters msg fix

- shell/edit/__tests__/management.cattle.io.clusterroletemplatebinding.test.ts
- shell/edit/management.cattle.io.clusterroletemplatebinding.vue
Fixes #8593
management.cattle.io.clusterroletemplatebinding had an error banner,however it is using CruResource that already handles errors. Duplicated banner was redundant since they display the same array of errors.
Removed banner from management.cattle.io.clusterroletemplatebinding component
N/A
Test that the error is still displayed when adding user fails.
N/A
> Removed duplicted error banner when adding user to the cluster

- cypress/globals.d.ts
Removed legacy code - getUserPreferences() is no longer in use. removed from global.d.ts file
> remove getUserPreferences()

- .github/workflows/test.yaml
Fixes #9755
Chrome 117 introduced a bug with headless mode that is not fixed until version 119.
This PR installs version 116 so that the e2e tests run.
> Use Chrome 116 for e2e tests

- shell/list/management.cattle.io.feature.vue
Fixes [rancherlabs/ranchersecurity/1205](https://github.com/rancherlabs/rancher-security/issues/1205)
It looks like the code that should've enabled the row actions on the features list was looking at the `setting` schema instead of the `feature` schema in the management store like it should've been.
Just changed the type we're looking for on the features list to enable row actions on the features list.
When a user has minimal permissions to change features (presumably uncommon, the user will usually be an admin of some type), it's critical that we validate permissions against the correct schema until a more robust permission checking method can be implemented.
Should be able to just test the rowActions on the table at `/c/_/settings/management.cattle.io.feature` to make sure they appear …
> enableRowActions looking at the wrong schema

- shell/config/product/istio.js
Fixes #9739 
This PR:
- Ensures that the namespace selector drop down is shown for the Istio product
- Adds 6 missing types for Istio to the Istio product (1 was there but spelt incorrectly)
- Adds the namespace column to the Virtual Services type, since this uses a custom table definition and the namespace column was missing
To test:
- On the local or downstream cluster, install Istio using cluster tools
- Explore the cluster where you installed Istio
- Go to the Istio section in the side nav and verify that the namespace choose appears in the header bar at the top right
- Go to Virtual Services and verify that the table now contains the Namespace column:
- Check that the Istio side nav includes a new Advanced section and looks like this:
> Fix issues with Namespace filter and missing types in Istio view

- shell/components/form/Members/MembershipEditor.vue
- shell/plugins/steve/__tests__/getters.spec.ts
- shell/plugins/steve/getters.js
Fixes #8574 
Progresses #9341
This looks to be primarily a performance issue wherein loading a project edit page with a 'members' list (actually the `projectRoleTemplateBindings` resource) can either simply fail or get stuck in a repeating pattern at scale due to the way that `projectRoleTemplateBindings` scales across projects and clusters. Adding a project filter to the `projectRoleTemplateBindings` should cut down on the cost of this API call significantly.
The membership editor will now check if it's type is set to Norman's `projectRoleTemplateBindings` and will append a `projectId` field (Norman specific, Steve's `management.cattle.io.projectRoleTemplateBindings` uses `projectName` but is not used on this page.
While not strictly required by this PR, changes have been added to better …
> checks to see if membership editor is project and adds a project filter

- shell/assets/translations/en-us.yaml
- shell/components/auth/RoleDetailEdit.vue
- shell/models/management.cattle.io.globalrole.js
- shell/models/management.cattle.io.roletemplate.js
- shell/utils/validators/formRules/__tests__/index.test.ts
- shell/utils/validators/formRules/index.ts
- shell/utils/validators/role-template.js
Fixes #9078 
Implemented form validation to provide user feedback when they have an invalid rule in their roletemplate. customValidationRules in `management.cattle.io.roletemplate` and `management.cattle.io.globalrole` looked to be broken as they were referencing a non-static method on another model which doesn't work. Changed them to what they had been prior to that breaking change and it seems to work now.
Add a global role and a cluster role
On both, fill out both Resource and Non-Resource URLs
Notice validation message
Notice "Create" button is disabled
None that I can think of, the only orthogonal code change made here was to code that was in a broken state.
> save method in model fixes payload, validator catches the rest

- shell/components/SortableTable/index.vue
Fixes #9779 
When removing a namespace from the "Not in a Project" group, this group would still be ran within a method looking for `availableActions`. With the project not being a real resource (or "Project"), it would not have any available actions and would cause the computed method `canRunBulkActionOfInterest` to fail.
Added to the first condition to also check for the existence of a resource's `availableActions`.
https://github.com/rancher/dashboard/assets/40806497/c3799716-c52a-418c-b8d1-02b55a297e4e
> Update bulk action condition to check for empty resource actions

- shell/components/ExplorerProjectsNamespaces.vue
- shell/package.json
This adds the `ExtensionPanel` component to the Projects/Namespaces resource list. As this list was a custom component, it does not use the standard `ResourceList` component which already contains the `ExtensionPanel`
Also bumped the shell package version to `0.3.25` to allow extensions to utilize this feature.
> Projects ns extension point

- shell/initialize/index.js
- shell/plugins/positive-int-number.js
https://github.com/harvester/harvester/issues/3977
Add `v-positive-number` directive for the input which is the number type.
@WuJun2016 Please take a look, thanks!
> Implement the directive of positive number

- jest.setup.js
- shell/assets/translations/en-us.yaml
- shell/edit/provisioning.cattle.io.cluster/DrainOptions.vue
- shell/edit/provisioning.cattle.io.cluster/__tests__/DrainOptions.test.ts
- shell/edit/provisioning.cattle.io.cluster/__tests__/rke2.test.ts
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #9108 
Per internal ref, this requested change is for provisioned clusters - see comment on original issue re: imported cluster UI
* updated the rke2/k3s upgrade strategy configuration to default to drain nodes 'yes'
* updated DrainOptions component to use i18n
* added unit tests for DrainOptions
* added v-clean-tooltip support to jest config (I was getting `Failed to resolve directive: v-clean-tooltip`)
> update rke2 node drain default value

- shell/assets/styles/base/_variables.scss
- shell/components/nav/TopLevelMenu.vue
Fixes #9752 
Go to https://localhost:8005/c/local/settings/banners and enable the Header Banner, it should now take the whole width on the top of the page. Do the same for the Footer or both, same behavior is expected.
> fix: Adds margins to the app-bar when the global banner is enabled

- shell/components/formatter/PodsUsage.vue
- shell/components/formatter/__tests__/PodsUsage.test.ts
- shell/pages/home.vue
Fixes #9363
There was a similar fix for #8543 [PR](https://github.com/rancher/dashboard/pull/8756/files) and it looks like we didn't fix the formatter for the cluster list so there was a mismatch. This basically just makes the same change in the column Formatter so everything lines up again.
The cluster list shouldn't need to delay on loading pods capacity anymore and we've reduced subsequent api calls as well.
used pods in the `cluster.status.requested.pods` is accurate for pods capacity, removed subsequent API calls and just using that to create the capacity string.
Cluster home page pod capacity and cluster list pod capacities should always match per cluster
> Now uses the same data as the cluster homepage, delayed load not needed.

- shell/mixins/brand.js
Fixes #9551
This PR fixes the above issue - as is the brand setting is reset if the CSP adapter is removed but the code for this also is called first time around if there is no CSP adapter, causing the reset.
This PR removes the reset - the only downside is if the CSP adapter is removed, the brand is not reset - but I think that is a fair compromise.
> Fixed ui-brand value automatically reverted issue

- shell/assets/translations/en-us.yaml
- shell/edit/provisioning.cattle.io.cluster/CustomCommand.vue
- shell/edit/provisioning.cattle.io.cluster/__tests__/CustomCommand.tests.ts
Fixes #9609
The warning message should be displayed only for `custom` RKE2 clusters.
- Create a new Cluster
- Check Registration tab -> Step 1 card -> warning message on bottom of the card
> Warning for RKE2 custom clusters when setting node roles

- scripts/e2e-docker-start
bump from 2.7-head to 2.8-head
> Bump the rancher version used in e2e tests to 2.8

- .github/workflows/notify-docs-team.yml
This is a clean version of #9767 
This solely pertains to the Github repo and internal processes.  It adds a Github action that automatically emails the docs team about release notes.
---
We use the `release-note` label to indicate issues that should be added to the release notes. However, unless an engineer or manager alerts the docs team, the docs team receives no notice that the issue needs to be added. Docs writers need to manually check the repo frequently to make sure they don't miss any issues during the release cycle. This can be especially hectic and failure-prone towards the end of a release.
This PR adds a brief (10-14 second) Github action that automatically adds a comment to issues labeled with `release-note`. The comment pings the docs team recipients listed in the .yml, …
> Automate docs team notification for release notes

- shell/components/__tests__/ProjectRow.test.ts
- shell/components/form/ResourceQuota/ProjectRow.vue
Fixes #9795 
- Use `Vue.set` on `ProjectRow` component `updateQuotaLimit` method so that values aren't cleared from the inputs (they weren't being properly set)
- Add unit tests
- Create a project under your `local` cluster (no other configs other than `name`)
- Edit the above created project using `Edit config`
- Click >>> `Resource Qoutas` >>> `Add Resource` >>> `Config Maps` >>>
- set `Project Limit` to 200
- set `Namespace Default Limit` to 20
- Check that on blur, the fields remain with the correct value
- Click `Save` and check that the project `Resource Quotas` contains the correct values after save
https://github.com/rancher/dashboard/assets/97888974/00fe3a08-a167-4dd1-a4b0-9d99be25936b
> fix Project Resource Quotas Fields Appear to Clear Once Focus has Moved

- shell/components/auth/RoleDetailEdit.vue
- shell/components/auth/__tests__/RoleDetailEdit.test.ts
- shell/models/management.cattle.io.globalrole.js
- shell/models/management.cattle.io.roletemplate.js
Fixes #9802 
In this form NameNsDescription uses `displayName` instead of `metadata.name` - this PR updates the form to set `displayName` if its not defined and `metadata.name` is. I hit another issue editing the example role provided in the issue where the save function fails because `nonResourceURLs` is undefined.
* editing a custom role without displayName as outlined in the issue
* editing a custom role _with_ displayName
* creating a custom role through the ui
> allow saving global roles with no displayName

- shell/package.json
- shell/scripts/extension/helm/charts/ui-plugin-server/Chart.yaml
Ensures charts that build from 2.8 code have a max version that includes 2.8
> Bump extension max versions

- docusaurus/docs/code-base-works/auth-providers.md
- docusaurus/docs/code-base-works/auth-sessions-and-tokens.md
- docusaurus/docs/getting-started/development_environment.md
- docusaurus/docs/getting-started/ui-walkthrough.md
- docusaurus/docs/guide/auth-providers.md
- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/config/private-label.js
Replaced the old docs urls with the new ones. In some cases the english language code(`en`) needed to be removed from the url otherwise you would visit the "Page not found" page.
Fixes #9854
> Updated docs urls

- shell/components/nav/TopLevelMenu.vue
- shell/models/fleet.cattle.io.cluster.js
- shell/store/features.js
Fixes #9730 
- add new feature flag to gate workspace change on fleet clusters
- sneaky fix for `id` bug encountered on `provisioning.cattle.io.clusters` list view after deleting clusters
Cannot repro this because to this date on `v2.8-head` the feature flag `provisioningv2-fleet-workspace-back-population` isn't found.
- Navigate to cluster management and create a RKE2 cluster
- Navigate to Continuous delivery
- Ensure correct workspace with the clusters selected.
- Click on each cluster action
- RKE2 dropdown should have Change workspace action IF it RKE2 and feature flag `provisioningv2-fleet-workspace-back-population` is `true`
https://github.com/rancher/dashboard/assets/97888974/f604e54d-1f3f-44e7-a791-1998f0cb206e
_sneaky fix screenshots_
> add new feature flag to gate workspace change on fleet clusters

- shell/components/nav/Header.vue
Ensure the bottom border of the header goes all the way to the left when the shell is in single product / standalone mode
- move margin to icon rather than parent
- this overwrites the existing margin-left, so don't need to take that in to account
Before
After
> Fix single product / standalone ui header bottom border

- shell/assets/styles/themes/_dark.scss
- shell/assets/styles/themes/_light.scss
- shell/assets/translations/en-us.yaml
- shell/components/CodeMirror.vue
- shell/components/CopyToClipboardText.vue
- shell/components/DetailText.vue
- shell/components/DetailTop.vue
Fixes #9321
Fixes #9320
Fixed contrast issues in annotations and the YAML editor for light and dark themes.
- Go to any YAML editor section that should have new colors for the light/dark theme 
- got to the node > annotations section should have a new design for the Annotations display section
Annotations display:  https://xd.adobe.com/view/a9174e68-1483-4027-bca3-d5fb284fd35c-fc44/specs/
YAML new colors: https://xd.adobe.com/view/a2eb73f7-2a3c-4b21-a564-a5f95f4e5dce-f7b8/
====== Annotations display ======
====== Annotations display light theme ======
====== YAML light theme ======
====== YAML dark theme ======
> Annotations display redesign

- shell/components/AlertTable.vue
- shell/components/EtcdInfoBanner.vue
- shell/components/GrafanaDashboard.vue
- shell/pages/c/_cluster/monitoring/index.vue
- shell/utils/grafana.js
Fixes #9792 
This PR updates the various components that use rancher monitoring's embedded grafana dashboards so they do not require that the current user can view the monitoring app.
The local cluster's grafana dashboard url is different for some versions of monitoring. Consequently the UI attempts to fetch the monitoring app everywhere the grafana dashboard url is used. As described in #9792 it is possible for a user to have the necessary permissions to view grafana dashboards but no permission to view the monitoring app. This PR updates the grafana url-constructing logic to fall back to the grafana url that's valid for all but two monitoring versions instead of erroring out or hiding the embedded dashboards.
Grafana links didnt work for me when running the UI locally. I tested this by …
> check if a user can list apps before trying to fetch the monitoring app

- shell/utils/__tests__/object.test.ts
- shell/utils/object.js
Fixes #9249 
we were incorrectly creating a nested object where we should have had a primitive value when an object's key included a period. The root cause was that we weren't properly escaping the key names by surrounding them with double-quotes so that the `set` function knows not to split the string on those particular keys. This caused the "set" function to create additional levels of nesting and to create false keys that the API was not expecting.
The `diff` utility function now wraps individual keys in quotation marks so it doesn't confuse the `set` utility function when a key in a diff includes a dot.
It's possible that the full repro steps in the parent issue might still produce an error given the steps and depending on your environment, this mostly has to do with those steps …
> now properly escaping key names prior to diffing objects

- .vscode/settings.json
- shell/config/os.ts
- shell/edit/provisioning.cattle.io.cluster/index.vue
- shell/mixins/chart.js
- shell/models/__tests__/catalog.cattle.io.app.test.ts
- shell/models/catalog.cattle.io.app.js
- shell/models/chart.js
- shell/models/management.cattle.io.cluster.js
- shell/pages/c/_cluster/apps/charts/chart.vue
- shell/pages/c/_cluster/apps/charts/index.vue
- shell/pages/c/_cluster/apps/charts/install.vue
- shell/pages/c/_cluster/explorer/tools/index.vue
- shell/store/__tests__/catalog.test.ts
- shell/store/catalog.js
- shell/types/catalog.ts
- shell/utils/__tests__/array.test.ts
- shell/utils/__tests__/version.test.ts
- shell/utils/chart.ts
- shell/utils/version.js
Fixes #9613
Prevented to display mismatching updates if chart data is malformed and unable to filter other cases.
Specifically, it's not possible to filter charts with the same name using `repoName` and `repoType`.
- Refactored catalog store
- Moved functions into chart utils with TS and interface based on existing logic
- Moved constant into config
- Updated affected cases
- Added tests
- Catalog model
- Catalog store
- Version util `compare()` function
- Updated Version util `compare()` to handle cases without values and return `null`
- Updated test for Array util `filterBy()` for partial object filtering
Issue is very specific and requires dedicated instance with malformed data.
If necessary to mock, this is the dump:
Path: `/c/local/apps/catalog.cattle.io.app?q=epinio` …
> App upgrade notification shown for incorrect app

- shell/components/nav/TopLevelMenu.vue
- shell/components/nav/__tests__/TopLevelMenu.test.ts
- shell/utils/cluster.js
- shell/utils/sort.js
Fixes #9683
- Added tests
- Added several fallbacks
- Removed conditional chaining in some styling
- `SortBy()` utility if missing argument
- `filterOnlyKubernetesClusters()` if missing mgmt Clusters
- Several cases in the sidebar
- Changed getter map flavor due issues while mocking method
- Added comments to the markup to match to the UI
> Automation: No matching clusters msg fix

- shell/components/EmberPage.vue
Takeing the app bar's width into account so the iframe section doesn't overlap.
Fixes #9904 
Before:
After:
> Fix iframe overlap

- shell/assets/translations/en-us.yaml
- shell/edit/provisioning.cattle.io.cluster/Basics.vue
Fixes #9110 
- Add warning banner for amazon cloud provider when kubernetes version is `gte` to `v1.27`
- Go to `Cluster Management` -> and create a `RKE2` `Amazon EC2` cluster
- The `basics` Tab, select the combo of `kube version` at least `v1.27` + cloud provider `Amazon`
- A new banner should appear just like the screenshot
> add additional configuration banner for amazon cloud provider

- shell/edit/workload/mixins/workload.js
Fixes #9863 
The workload create/edit screen assumes access to two resources that the user might not have access to - in that case, the fetch errors out and we do not fetch secrets etc, so the form does not operate correctly.
Hard to automate test as this requires RBAC setup.
To test:
- As admin, create a user with user-base
- Create a project and add a namespace
- Create an image pull secret (registry secret) int this new namespace
- Give the new user member access to the project
- Login as the new user
- Go to create a new workload in the namespace in the project and in general, check the 'Pull Secrets' dropdown in the Image section - with this bug, this will be empty. With this fix, the list should show the secret that was created.
> Fix RBAC issue with workload create/edit screen

- pkg/kubectl-explain/components/SlideInPanel.vue
Fixes: #9107
Fixes an issue with the kubectl explain UI, where the RBAC schema group does not directly translate to the OpenAPI group - so the user is told there is no OpenAPI information available.
Added a manual mapping in this case.
> Fix no info on kubectl explain for RBAC resources

- shell/pages/c/_cluster/explorer/index.vue
- shell/pages/c/_cluster/monitoring/index.vue
- shell/utils/monitoring.js
Fixes #9792 - (look at latest comments for explanation)
This PR updates the cluster index to only show metrics tabs when the user can view the grafana endpoint. Prevously we checked if the relevant grafana links worked: this doesn't match the monitoring-ui-view permissions described in the docs  (https://github.com/rancher/dashboard/issues/9792#issuecomment-1766808320)
This matches the logic already in place on the monitoring index page so I moved that code to a utility.
Original repro steps in the issue 
Links on the monitoring index view
> hide embedded grafana graphs on cluster index when the user cant view grafana endpoint

- .github/workflows/port-issue.yaml
The port-issue workflow isn't working, see https://github.com/rancher/dashboard/actions/runs/6578593068/job/17872661826
I tested this change on a personal repo and it appears to fix the workflow.
> correct port-issue workflow github_token vars

- package.json
update reference for e2e tests to `2.8-head` based on the branching process step 2 https://confluence.suse.com/display/CU/Dashboard+and+Ember+Release+Process
> update reference for e2e tests to 2.8-head

- shell/models/cluster.x-k8s.io.machine.js
Fixes #9973 
See the issue for more details - the fix here is just to ensure `canScaleDown` doesn't break if `this.cluster` is undefined. I hit this bug with rancher turtles specifically; I can provide a test setup to repro the bug if needed.
> fix capi machine canScaleDown getter when machine' provisioning cluster is undefined.

- .github/workflows/port-issue.yaml
Per offline conversation with @gaktive, current guidance from QA is to add the `QA/None` label to backport issues - this PR updates the issue porting workflow to do so.
> update backport workflow to add QA/None label to backport issues

- shell/middleware/authenticated.js
- shell/package.json
- shell/utils/error.js
- if entering the product, loading cluster, etc fails extensions can now throw a `RedirectToError` error
- this avoids the user being redirect to the dashboard home or fail-whale page
- example - epinio auth fails and we want to return user to the epinio cluster list
In theory we should be able to to instanceof with something that extends error and has a `name`, unfortunately this does not work, so gone for something more manual.
Also bump shell so we can publish a new version
- user is navigated to the home page if the cluster id is unknown
> Allow extentions to redirect the user to another location if authentication fails

- cypress/e2e/po/pages/get-support.po.ts
- cypress/e2e/po/pages/home.po.ts
- cypress/e2e/po/side-bars/burger-side-menu.po.ts
- cypress/e2e/tests/pages/get-support.spec.ts
- cypress/e2e/tests/pages/home.spec.ts
- cypress/support/e2e.ts
This PR covers the functionality within the Get Support page
View Test Plan https://github.com/rancher/qa-tasks/issues/764
- added `navTo` method for the Home page and updated those tests
- enabled skipped tests after [bug fix](https://github.com/rancher/rancher-docs/issues/727)
> get support page tests

- shell/components/Carousel.vue
Fixes #9975
- Removed slide numbers from the titles
- Adjusted dividing line height in all the slides
Adjusted dividing line height in all the slides
**Before:**
**After:**
> Removed slide numbers from the titles, other small fix

- shell/components/nav/WindowManager/ContainerLogs.vue
Fixes #9437
Fixes #9931 
The container logs can end up not formatting correctly when including new-lines.
We assume that each websocket message only includes a single error message - this no longer seems to be the case and we can now get multiple lines.
The fix here is to split on newline and iterate through each line.
To test:
Create a pod from the image `nwmac/logtest` - this is a simple container that logs single and multiline messages.
Examine the container logs for this pod.
Prior to this fix, the output would look like this:
With this fix, the output now looks like this:
> Fix bug with container log formatting

- .github/workflows/test.yaml
- cypress/e2e/po/side-bars/user-menu.po.ts
- cypress/e2e/tests/pages/explorer/workloads/deployments.spec.ts
- cypress/e2e/tests/pages/user_menu/account-api-keys.spec.ts
- cypress/e2e/tests/pages/user_menu/logout.spec.ts
- cypress/e2e/tests/pages/user_menu/preferences.spec.ts
- cypress/e2e/tests/setup/rancher-setup.spec.ts
- package.json
- scripts/build-e2e
- Temporary fix for flaky user avatar based tests
- Added a way to skip the build
- Added tags for setup and flaky tests
- Temporary fix for flaky user avatar based tests
- It's not an ideal solution, but added 2 x 1 second `wait`s to fix flaky tests
- is quicker than everyone re-trying e2e gate multiple times
- brings down e2e gate total time to ~55 minutes 
- The tests have run a total of 8 times (3 as full suite) and all have passed first time.
Also....
- Added an optional, off by default, way to skip the build step and grab the dashboard from CDN
- `BUILD_DASHBOARD: false`
- As the code isn't instrumented the code cov parts are skipped
- This is only good for debugging e2e tests in GH
- Added setup and flaky to some tests.
- Can be used in conjunction with `BUILD_DASHBOARD` for super …
> Temporary fix for flaky tests

- shell/assets/translations/en-us.yaml
- shell/components/AsyncButton.vue
- shell/components/SortableTable/index.vue
Fixes #8645 
- create new `manual-refresh` action to not confuse with other refresh actions 
- update translations to match new `AsyncBtn` action
- remove tooltip from manual refresh button (we already have the text)
Go to `Settings` -> `Performance` ->  `Manual Refresh` -> and enable manual refresh with a low threshold (ex: 5)
Go to `local` cluster -> `events` -> and check that the button appears with the correct text label
> Use full text label "Refresh" on refresh button instead of just icon

- cypress/e2e/po/pages/explorer/cluster-project-members.po.ts
- cypress/e2e/tests/pages/explorer/cluster-project-members.spec.ts
Fixes #
fix flaky cluster-project-members.spec test by adding intercept logic and conditional statement.
addresses failure where cluster member does not display on Cluster and Project Members page: http://139.59.134.103/instance/6a70d355-1f33-4fc9-9816-7bd065185315/test/r3
> fix flaky cluster-project-members.spec test 

- cypress.config.ts
- cypress/e2e/po/components/shell.po.ts
- cypress/e2e/po/pages/cluster-manager/cluster-manager-list.po.ts
- cypress/e2e/tests/pages/cluster-manager.spec.ts
- cypress/support/e2e.ts
- package.json
- yarn.lock
This PR covers the functionality in the Cluster actions (within ellipsis)
View Test Plan https://github.com/rancher/qa-tasks/issues/753
Between the two download tests, the kubeconfig and YAML files are created with the same name in the downloads directory which is causing failures. The easiest solution was to add the [cypress-delete-downloads-folder ](https://www.npmjs.com/package/cypress-delete-downloads-folder) npm package to delete the downloads directory to avoid the conflicting files.
Changes include adding several lines of code to our Cypress configuration files which allows the cleanup of our downloads with `cy.deleteDownloadsFolder()` command.
> actions on cluster tests

- shell/chart/monitoring/grafana/index.vue
Default size value for Grafana v2 `10Gi` (same as v1)
Fixes rancher/dashboard#2615 
https://github.com/rancher/dashboard/assets/135728925/dd845141-9e0f-49c1-8b37-4550674c0376
> default size value for grafana v2

- shell/package.json
Ensure extension build-pkg succeeds when extension contains form validation
- if an extension uses form validation it brings in shell/utils/validators/formRules/index.ts
- that was recentely updated to import is-url (https://github.com/rancher/dashboard/pull/9701/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R149)
- is-url needs typing and will cause build-pkg to fail
- so add the typing, as per others, to shell/package dependencies
> Ensure extension build-pkg succeeds when extension contains form validation

- shell/components/nav/Header.vue
- shell/core/plugin-helpers.js
- Ensure `checkRouteProduct` works with route meta object
- `getProductFromRoute` falls back on product in route meta object
- in `checkRouteProduct` this was not passed through
- Ensure header action button enabled fn gets the same args
-  `handleExtensionAction` was `action.enabled.apply(this, [opts])`
- but in the template it is `action.enabled(ctx)`
- fix is to pass in ctx in `handleExtensionAction`
> Fix to extension bugs

- shell/store/index.js
Fixes #9733 
An extension can add to an existing product by nesting its routes, see https://github.com/rancher/capi-ui-extension/pull/3; however, if the product is cluster-scoped `loadCluster` will re-run when navigating into/out of the extension which causes a noticeable delay.
Locally build and load the capi extension, navigate to `c/local/manager` (note the cluster-scoping), navigate into/out of the capi section and use existing console logs to verify that the cluster store isn't re-initializing (attempting to subscribe to socket; re-loading schemas)
* navigating to a new package but same cluster id eg between epinio and cluster explorer
* navigating to an extension that adds a product to cluster explorer eg kubewarden
> update loadCluster to account for extensions adding to existing products

- shell/components/ResourceDetail/Masthead.vue
- shell/models/provisioning.cattle.io.cluster.js
Fixes #9993
Namespace's links in ClusterManagement/Cluster Detail header are broken because the `clusterId` is missing from the `namespaceLocation` of the namespace's links.
The issue can be reproduced with any type of clusters, is not specific for Harvester clusters.
Current changes will fix the issue assuming that the namespaces are always managed from `local` cluster.
- Cluster Management list -> Cluster Details -> namespace details
- `Masthead` component -> namespace links section
> Link namespaces in mgmt cluster to local cluster

- shell/edit/workload/storage/persistentVolumeClaim/persistentvolumeclaim.vue
Fixes ~# 9717~ This is the 2.8next1 PR
- default storage class is set via annotation
- annotations can be `"true"` or `"false"`
- previously we only checked for truthy when finding default
- this mean `"false"` counted as true
> Fix selection of default storage class

- shell/edit/workload/storage/persistentVolumeClaim/persistentvolumeclaim.vue
Fixes #9717
- default storage class is set via annotation
- annotations can be `"true"` or `"false"`
- previously we only checked for truthy when finding default
- this mean `"false"` counted as true
Backport of https://github.com/rancher/dashboard/pull/10051
> Fix default storage class selection backport

- cypress/jenkins/Jenkinsfile
- cypress/jenkins/Jenkinsfile_multi
- cypress/jenkins/cypress.sh
- cypress/jenkins/init.sh
- cypress/jenkins/junit_to_qase.py
- cypress/jenkins/reporter-options.json
- cypress/jenkins/scpget.sh
- cypress/jenkins/transform-junit.sh
This PR adds multi branch and multi tags capabilities for the existing Jenkins pipeline of UI automation.
The corral package side of this implementation can be found on these PRs:
https://github.com/rancherlabs/corral-packages/pull/19
https://github.com/rancherlabs/corral-packages/pull/26
A PR for the Jenkins configuration variables and pipeline is in a job builder private repo
A multi Jenkinsfile pipeline that's going to be triggered with the necessary configuration variables to execute a child Pipeline with different branch and tags. On a recurring basis, that configuration is in the jenkins builder.
The child pipeline now include logic to enable Qase reporting and Cleanup resources variables. (See Jenkinsfile)
This the next iteration of https://github.com/rancher/dashboard/pull/9726
> [Automation] - Recurring dashboard UI tests with multi branch pipeline and tags. Qase reporting

- cypress/e2e/tests/pages/get-support.spec.ts
- cypress/e2e/tests/pages/home.spec.ts
- shell/config/home-links.js
Expands Fix for #9855
- There's already a link ``Docs` that uses a var containing the correct root url
- This PR updates the link to the docs overview page to use the same root
- This means home page links to docs site go out to `https://ranchermanager.docs.rancher.com/v2.8`
> Ensure home page `Get Started` link uses correct docs link

- shell/assets/translations/en-us.yaml
- shell/pages/c/_cluster/apps/charts/index.vue
Fixes #10027
- Fixed enabledCharts, filteredCharts and getFeaturedCharts
- These should all behave differently given user filters
- enabledCharts should not include any user based filters
- filteredCharts should include allll the filters
- featuredCharts should not include invalid charts
- added descriptions of above as comments
- These fix
- carousel changing when user enters filters
- categories counts showing weird values  (categories now show numbers given user filters, not including itself)
- Sorted Categories list alphabetically
- Fixed css
- Repos dropdown colour blobs were misaligned... and text on hover was unreadable
- Fixed misleading error message when there are no charts shown
- App Charts page selected repos, selected categories and text filter
- Generally, and the results …
> Fix multiple issues with charts list

- shell/assets/translations/zh-hans.yaml
- shell/components/EtcdInfoBanner.vue
Fixes #9922
1. use commas to separate etcd information
2. `ETCD 有一个 Leader： 是`, `是`No translation into Chinese
3. `失败的 proposal 数量 0`,  add the ":" separator between key and value
> fix(EtcdInfoBanner): use commas to separate etcd information

- shell/components/fleet/FleetBundles.vue
- shell/components/fleet/FleetSummary.vue
- shell/components/fleet/__tests__/FleetSummary.test.ts
Fixes #9866 
This PR updates the bundle-filtering logic in FleetSummary to use the `repoName` getter, which references an annotation of the associated repo's name, instead of a regex. This is imiliar to a previous fix: https://github.com/rancher/dashboard/pull/5348
Also cleaned up misleading unnecessary filtering in FleetBundles -- the bundles there are already filtered by repo.
1. Gitrepo detail view when repos have similar names
before and after:
> Fix gitrepo detail view bundle count

- cypress/jenkins/Jenkinsfile_multi
- cypress/jenkins/init.sh
Rancher installation when the Jenkins job type
is recurring.
When the Job type is recurring in Jenkins get the latest Rancher chart to be used during the Rancher installation done by Corral.
This will allow to use the latest chart with the current *-head image.
The latest chart will be filtered by Rancher version 2.x (2.6, 2.7, 2.8 ..)
This change will allow the Dashboard tests package use the latest Rancher chart available, release candidate or release. This will allow using the more recent Rancher Image during helm install.
Jenkins pipeline setup.
> [Automation] - Use the latest Rancher chart to use during the Rancher installation when the Jenkins job is recurring.

- shell/components/Markdown.vue
- shell/plugins/clean-html.js
Fixes #9951 
- remove `DOMpurify` from markdown component (`v-clean-html` does exactly this, so need to duplicate it)
- add missing `html` tags to allowed tags in `v-clean-html` so that markdown content is rendered correctly
**NOTE:** links in markdown won't open in a new tab unless https://github.com/rancher/dashboard/pull/9928 is merged as well.
- Go to `https:///c/local/apps/charts/chart?repo-type=cluster&repo=rancher-partner-charts&chart=tomcat&version=10.10.10` and check that markdown is rendered correctly
> Wrong rendering of Markdown files

- pkg/rancher-components/package.json
This bumps Rancher Components to `v0.1.5-alpha.0`.
> Bump rancher-components to v0.1.5-alpha.0

- package.json
- Temporarily disable `sorry-cypress` to unblock our github pipelines
> Temporarily disable sorry-cypress to unblock our github pipelines

- shell/assets/images/providers/ovhcloudmks.svg
- shell/assets/images/providers/ovhcloudpubliccloud.svg
Fixes: #10064
Adds a logo for OVHCloud, a major cloud provider in Europe who wants to develop their own Rancher Node Drivers.
> Add Logo for OVHCloud (both RKE2 and Managed Kubernetes)

- shell/pages/auth/verify.vue
Fixes #9949
- When configuring a SAML auth provider a popup window is shown
- The popup window allows the user to log in to the SAML provider
- The same popup window gets redirected to auth/verify to check the response of the log in
- Normally there will be a state string. Recently code was added to show an error if this is missing
- If SAML though there is no state, so we would incorrectly show this error. This is the bug
- Note - the auth provider was enabled, so closing the popup and refreshing the original page would continue as normal
- See our confluence okta page on how to setup an okta provider
- This is a regression introduced in 2.7.7 via https://github.com/rancher/dashboard/pull/7623 (actual change was https://github.com/rancher/dashboard/pull/7299)
- A saml provider like OKTA …
> Ensure SAML providers popup closes correctly

- shell/assets/translations/en-us.yaml
- shell/components/Certificates.vue
- shell/components/ResourceTable.vue
- shell/components/formatter/LiveDuration.vue
- shell/models/secret.js
- shell/pages/c/_cluster/explorer/index.vue
- shell/plugins/dashboard-store/resource-class.js
- shell/plugins/steve/getters.js
- shell/utils/time.js
Fixes #10025
- Add a new tab, next to events, in the cluster dashboard
- Tab shows a list of all secrets of cert type
- List allows users to see which certs are expiring soon, how long they've lived etc
- Tab also shows a notification if certs are expiring or have expired
- Related fixes
- plumb in option list paging params (so we can show X of Y Certificates in pagination controls)
- fix usages of from = from || now
- Count requests to kube steve (`/k8s/cluster/<clusterid>/v1`) as steve requests (alongside local steve requests `/v1`)
- Cluster --> new `Certificates` Tab
- Certificates that are expiring
- Certificates that have expired
- General API requests made to the cluster when in explorer view
- Secrets List 
- Certs that are expiring should show have a red date (should be yellow - …
> Add certificates view to cluster dashboard

- shell/assets/translations/en-us.yaml
- shell/chart/monitoring/alerting/index.vue
- shell/chart/monitoring/index.vue
- shell/chart/monitoring/prometheus/index.vue
- shell/plugins/dashboard-store/actions.js
- shell/plugins/dashboard-store/getters.js
- shell/plugins/steve/getters.js
- shell/utils/monitoring.js
Contributes to #9964
- Remove the need to fetch ALL secrets
- Monitoring chart component fetched all secrets and then filtered list down to a single namespace
- So we now only fetch secrets from a specific namespace at the API level
- Remove the need to fetch ALL workload types
- When installing the montiring chart the component checks for existing workloads with prometheuos-operator like images
- It was doing this by fetchig ALL workload types and filtering by the image name
- If found it shows a warning
- For details see https://github.com/rancher/dashboard/issues/1167
- Now instead of fetching all workloads we filter them at the API level
Additionally 
- Fixed a scenario where findAll without restrictions --> findAll with namespace filter would return allll resources
- Improvement
- …
> Avoid fetching all secrets and workloads when installing Monitoring Chart

- cypress/jenkins/init.sh
The Jenkins pipeline is failing intermittently. The the official helm installation docs script makes this step in the pipeline unstable.
I am opting to make the manual binary install of helm on Linux when the Job type is recurring (automated)
Jenkins automation pipeline
Running the setup and E2E execution of the recurring pipeline.
> [Automation] - Fix the Helm installation using the bin tarball

- shell/components/ResourceYaml.vue
- shell/models/provisioning.cattle.io.cluster.js
- shell/plugins/codemirror.js
- shell/plugins/dashboard-store/resource-class.js
Fixes #8496 
This PR adds a fix that will fold the `dynamicSchemaSpec` of the YAML for an RKE2 cluster when using the `Edit YAML` function.
This PR:
- Adds the ability of models to specify json paths that should be folded when being edited in the YAML editor
- Upates the provisioing cluster model to auto-fold the `dynamicSchemaSpec` field
This PR requires manual testing:
- Provision an RKE2 cluster with 2 pools (more than 1, to validate that the `dynamicSchemaSpec` on each pool is folded)
- Edit the YAML for the cluster (you do not need to wait for it to provision)
- Validate that the `dynamicSchemaSpec` fields are folded (collapsed) in the editor by default, e.g.
Note: Before this fix, the `dynamicSchemaSpec` fields would not be folded by default.
> Yaml Editor: Auto-fold section in RKE2 cluster config

- cypress/e2e/po/components/kubectl.po.ts
- cypress/e2e/tests/pages/charts/prometheus.spec.ts
- shell/chart/monitoring/prometheus/index.vue
- shell/components/nav/WindowManager/index.vue
Fixes #10016
This PR fixes an issue with the monitoring helm chart with Prometheus persistent storage config, where when you add a selector, we add in empty selector, matchLabels and mathExpressions into the Helm values - if you then remove the selectors, this empty structure is left, which causes issues.
1. This PR removes the empty structure
2. Added an e2e test to test this behaviour and verified the test fails with the existing code
3. Minor change to the close icon size/style on the window manager - the close icon was resized some time ago and it loos quite big in the window manager - sized this down slightly and added hover behaviour.
4. Updated e2e test to set larger viewport size and to close the terminal window and scroll into view, so its easier to see what is going on when …
> Fix for Monitoring Helm chart sometimes adds empty selector

- cypress/e2e/po/components/code-mirror.po.ts
- cypress/e2e/po/components/input.po.ts
- cypress/e2e/po/components/storage/config-map.po.ts
- cypress/e2e/po/pages/explorer/config-map.po.ts
- cypress/e2e/tests/pages/explorer/storage/configmap.spec.ts
- shell/components/form/KeyValue.vue
- shell/edit/configmap.vue
- shell/utils/__tests__/create-yaml.test.ts
- shell/utils/create-yaml.js
This introduces the capability to customize `jsyaml.dump` options in the `dumpBlock` function, allowing developers to supply all of the dump options specified by `jsyaml.dump()`.
Fixes #10044 
- Utilize options in `jsyaml.dump` when they are provided to `dumpBlock()`
- Specify `lineWidth: -1` in the `yamlModifiers()` for `configmap.vue`
- Create new e2e test for `configmap`
- Update unit tests for `create-yaml`
- Creating/Editing/Viewing config maps
- Other areas of Rancher Dashboard that might focus on creating/editing yaml
> Allow for `jsyaml.dump()` Options in `dumpBlock`

- shell/utils/__tests__/create-yaml.test.ts
- shell/utils/create-yaml.js
Fixes #9841
This prevents `dumpBlock()` from mutating parsed yaml when a header can't be located. More investigation might be warranted to discover why the regex used by `getBlockHeader()` isn't matching the keys when parsing the example yaml:
```
apiVersion: v1
data:
a: "a\nb\tc"
b: "a\nb\tc"
kind: ConfigMap
metadata:
name: yaml-tab-test
```
but the crux of the issue still comes down to the fact that `dumpBlock()` will indiscriminately mutate yaml output when a key can't be located; it's important that this behavior is corrected.
Stop mutating parsed yaml if the header can't be located.
Follow the repro steps left in comments on the issue:
https://github.com/rancher/dashboard/issues/9841#issuecomment-1745771047
Any yaml editor used throughout Rancher Desktop, but I doubt there are …
> Prevent mutating yaml when a header isn't found

- shell/store/catalog.js
Fixes #10156
- If a user doesn't have permission to view helm repos an error is thrown
- Regression brought in by // https://github.com/rancher/dashboard/pull/8754/files#diff-31b0043fb6852fd3650396c7d7fbe3b5ae4ba1fe3a4293fadb00a712ac53684cR357
- Given the repo steps in the issue, the edit page won't display correctly even after any fix is applied. That's covered by SURE-5419
> Ensure catalog load respects missing permissions

- cypress/e2e/po/components/code-mirror.po.ts
- cypress/e2e/po/components/input.po.ts
- cypress/e2e/po/components/storage/config-map.po.ts
- cypress/e2e/po/pages/explorer/config-map.po.ts
- cypress/e2e/tests/pages/explorer/storage/configmap.spec.ts
- shell/components/form/KeyValue.vue
- shell/edit/configmap.vue
- shell/utils/__tests__/create-yaml.test.ts
- shell/utils/create-yaml.js
This introduces the capability to customize `jsyaml.dump` options in the `dumpBlock` function, allowing developers to supply all of the dump options specified by `jsyaml.dump()`.
Fixes #10069 
- Utilize options in `jsyaml.dump` when they are provided to `dumpBlock()`
- Specify `lineWidth: -1` in the `yamlModifiers()` for `configmap.vue`
- Create new e2e test for `configmap`
- Update unit tests for `create-yaml`
- Creating/Editing/Viewing config maps
- Other areas of Rancher Dashboard that might focus on creating/editing yaml
backports #10142
> Backport 2.7: Allow for `jsyaml.dump()` Options in `dumpBlock`

- cypress/jenkins/junit_to_qase.py
I've noticed that when running the Jenkins pipeline using the recurring Multi branch the report generated in Qase sometimes had some type of collisions and the report generated extra test cases on different branches. 
Debugging the issue I found that the QQL searches comparisons were unstable as sometimes it matched the proper string in the returned json object or not at all. 
There were some other edge cases like when either a test case or test suite returned multiple matches (duplicates) the logic wasn't smart enough to handle the differences.
To fix this I removed the QQL queries replacing them with direct calls to the `cases` and `suites` Qase API endpoints to then use the `id` and `title` to have more control over the data.
Multi branch running of the Automation UI tests. `v2.6`, …
> [Automation] - Refactor Jenkins Qase reporter to not use QQL endpoints and improve multi branch report creation

- shell/components/formatter/Checked.vue
- shell/components/formatter/__tests__/Checked.test.ts
Fixes #9800 
The 'Built-In' column references a property on the globalrole object: when a custom role is created, that property is undefined. Sortable table converts undefined values to empty strings: https://github.com/rancher/dashboard/blob/master/shell/components/SortableTable/index.vue#L776-L778. Vue coerces empty strings to `true` when passed to a Boolean prop..even though an empty string is falsy. This PR updates the `Checked` component to accept string values so it correctly interprets `''` `undefined` and `null` column values as falsy.
Global roles table + other tables that use the Checked formatter: 
* storage classes
* ingresses
* feature flags
* rke1 snapshots
* user detail view (permissions table)
> account for empty string values in Checked formatter

- cypress/jenkins/init.sh
Fixes:
An issue when configuring the Jenkins tests to run on an `existing` Rancher. The test was doing the `local` type instead.
`recurring` is unaffected.
Jenkins jobs execution using an existing Rancher, running the job on demand.
> [Automation] - Fixing logic for running Jenkins tests on existing Rancher

- shell/utils/__tests__/create-yaml.test.ts
- shell/utils/create-yaml.js
Fixes #10070
backports #10168
This prevents `dumpBlock()` from mutating parsed yaml when a header can't be located. More investigation might be warranted to discover why the regex used by `getBlockHeader()` isn't matching the keys when parsing the example yaml:
```
apiVersion: v1
data:
a: "a\nb\tc"
b: "a\nb\tc"
kind: ConfigMap
metadata:
name: yaml-tab-test
```
but the crux of the issue still comes down to the fact that `dumpBlock()` will indiscriminately mutate yaml output when a key can't be located; it's important that this behavior is corrected.
Stop mutating parsed yaml if the header can't be located.
Follow the repro steps left in comments on the issue:
https://github.com/rancher/dashboard/issues/9841#issuecomment-1745771047
Any yaml editor used throughout Rancher Desktop, but I …
> Backport 2.7: Prevent mutating yaml when a header isn't found

- docusaurus/package.json
the `image-size` library was bumped to 1.1.0 a few days ago and the node version requirement was bumped - this breaks our CI.
This PR pins image-size so we don't pick that newer version up.
I chose not to bump the node version as this has a wider impact.
> Fix docusaurus build

- .github/workflows/test.yaml
Commented out a workaround that was added to the e2e CI workflow that pinned the Chrome version.
There was a bug in Chrome > 116 and < 119 that broke our CI.
> Comment out Chrome 116 pinning as no longer needed

- cypress/e2e/blueprints/charts/rancher-backup-chart.ts
- cypress/e2e/tests/pages/charts/rancher-backup.spec.ts
- cypress/globals.d.ts
- cypress/support/commands/rancher-api-commands.ts
- shell/chart/rancher-backup/index.vue
Fixes #10090 
This is a simple bug fix - the UI assumed that a storage class has annotations - if it does not, the default storage class is not auto-selected on the Rancher Backups chart install page.
This used to cause a full-screen error page due to another bug that has been fixed.
This PR fixes the remaining auto-selection bug.
Added an automated e2e test to cover regression testing.
> Fix select does not select default storage class

- package.json
- scripts/e2e-docker-start
- shell/assets/translations/en-us.yaml
This bumps the rancher version to `v2.9-head` for e2e scripts
> Bump rancher version to `v2.9-head` for e2e scripts

- .vscode/settings.json
This updates the value for `source.fixAll.eslint` to `explicit` instead of `true`. It looks like vscode released an update in September 2023 that deprecated using boolean values in favor of the string representation [^1].  
This also configures vscode to use the typescript version specified in `package.json` instead of what vscode used by default [^2].
[^1]: https://code.visualstudio.com/updates/v1_83#_code-actions-on-save-and-auto-save
[^2]: https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-the-workspace-version-of-typescript
> Update `source.fixAll.eslint` and specify `typescript.tsdk` in `.vscode/settings.json`

- shell/config/harvester-manager-types.js
- shell/detail/provisioning.cattle.io.cluster.vue
- shell/models/cluster.x-k8s.io.machinedeployment.js
Fixes #9892
`isHarvester` could be also calculated by checking the provider name of the cluster.
Other solution to show the label: find required information for Harvester machine pools = `this.machines.pool`
Clusters details page
> Hide provider labels for Harvester clusters

- pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.test.ts
- pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue
- shell/composables/useCompactInput.ts
- shell/composables/useLabeledFormElement.ts
contributes to #10104 
Rewrote `compact-input.ts` and `labeled-form-element.ts` mixins as composables to address TypeScript issues when using mixins with `defineComponent`. The new composables are written to adhere to the conventions and best practices [^1] as best as possible, taking into consideration what's available to us in Vue 2.7.14. 
Moving to composables positions us for a smoother Vue 3 migration.
[^1]: https://vuejs.org/guide/reusability/composables.html#conventions-and-best-practices
Any forms that utilize `LabeledInput`
> Replace `Vue.extend` with `defineComponent` in `LabeledInput.vue`

- shell/components/SortableTable/index.vue
- shell/detail/provisioning.cattle.io.cluster.vue
Fixes #10062
Cluster manage -> details page -> 'Scale Down' action
> Backport 2.7: Fix 'Scale Down' crash in cluster provisioning details page

- cypress/e2e/tests/pages/charts/prometheus.spec.ts
- shell/chart/monitoring/grafana/index.vue
- shell/components/nav/WindowManager/index.vue
Fixes #10042
NOTE: This PR is based on top of https://github.com/rancher/dashboard/pull/10085, which needs to be reviewed and merged first.
This PR adds Grafana resource configuration fields to the UI for the Monitoring installation chart:
Also added an e2e test to verify that the values are correctly wired in to the relevant backend API request.
> Add grafana resource configuration

- shell/composables/useCompactInput.test.ts
- shell/composables/useCompactInput.ts
- shell/composables/useLabeledFormElement.test.ts
This provides unit tests for the new `useCompactInput` and `useLabeledForElement` composables. 
contributes to #10104
> Write tests for `useCompactInput` and `useLabeledFormElement`

- cypress/e2e/po/edit/management.cattle.io.user.po.ts
- cypress/e2e/po/pages/explorer/workloads/workloads.po.ts
- cypress/e2e/tests/pages/explorer/cluster-project-members.spec.ts
- shell/components/CruResource.vue
Fixes #10260 
- add retry logic for failing user creation network request
This is a video, with a couple of changes on the code in order to visualise the fix:
https://github.com/rancher/dashboard/assets/97888974/930a162d-7deb-4e82-8028-594d7282793d
> add retry logic for failing user creation network request

- cypress/e2e/tests/pages/explorer/cluster-dashboard.spec.ts
Skipping cluster events test until this issue has been resolved https://github.com/rancher/dashboard/issues/10265 to avoid PR CI from failing and blocking merging of PRs.
> skip failing cluster events test

- shell/models/workload.js
- There was a bug introduced via https://github.com/rancher/dashboard/pull/10037 that would cause workloads that did not contain init containers to fail on form save or create
- Ensure we safely check for existence of initContainer before accessing
- Also removed if blocks in favour of `?`
- Deployment Create/Edit via form
- Random other Workload types (not pods)
> Fix Creation and Edit of Workload bases Resources

- cypress/e2e/blueprints/manager/cluster-snapshots.ts
- cypress/e2e/po/detail/provisioning.cattle.io.cluster/cluster-detail-rke1-custom.po.ts
- cypress/e2e/po/detail/provisioning.cattle.io.cluster/cluster-detail-snapshots.po.ts
- cypress/e2e/po/detail/provisioning.cattle.io.cluster/cluster-detail.po.ts
- cypress/e2e/po/lists/snapshots-list.po.ts
- cypress/e2e/po/pages/cluster-manager/cluster-manager-list.po.ts
- cypress/e2e/tests/pages/manager/cluster-manager.spec.ts
- shell/config/product/explorer.js
- shell/config/product/manager.js
- shell/detail/provisioning.cattle.io.cluster.vue
Fixes https://github.com/rancher/dashboard/issues/9642
`v3/etcdbackups` results are limited to `1000`, meaning that the current UI excludes results from 1000 onwards.
This change will apply `depaginate` option to the snapshots query, where a new query is run until all results are retrieved.
snapshots e2e tests set the limit to 1 and prove that depaginate flag triggers a new request to fetch the remaining results
> Handle Cluster's snapshots pagination

- package.json
- pkg/rancher-components/package.json
- shell/package.json
- yarn.lock
I came across the following tsc warnings while working on #10104:
```
Excessive stack depth comparing types 'Vue<Record<string, any>, Record<string, any>, never, never, (event: string, ...args: any[]) => Vue<Record<string, any>, Record<string, any>, never, never, ...>> | HTMLElement' and 'ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, ComponentOptionsBase<any, any, any, any, any, any, any, any, any, any>> | Element | Vue<...>'.ts(2321)
Excessive stack depth comparing types 'ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, ComponentOptionsBase<any, any, any, any, any, any, any, any, any, any>> | Element | Vue<...>' and 'Vue<Record<string, any>, Record<string, any>, never, never, (event: string, ...args: any[]) => Vue<Record<string, any>, Record<string, any>, …
```
> Bump typescript to 4.5.5

- cypress/jenkins/Jenkinsfile
Formatting mainly indentation for better readability and mark the current build as failed after certain error is caught.
Not updating the result on those cases makes the build as success. 
Jenkins Pipeline file updated
A run was triggered on Jenkins to check that the pipeline is working after before the second stage. Usually if there's syntax errors in the script an exception is thrown immediately by the executor.  
None in the UI just the automation pipeline.
> [Automation] - Jenkinsfile formatting and failure flags

- pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.test.ts
- pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue
Fixes #10249 
- fix issue where `LabeledInput` input event was not working for type `multiline` (the component used is `TextAreaAutoGrow` which emits the `value` instead of an `event`)
> Fix issue LabeledInput with type "multiline"

- .github/workflows/build-extension-catalog.yml
- .github/workflows/build-extension-charts.yml
- shell/scripts/extension/parse-tag-name
build-extension-charts.yml workflow passes "charts" as GITHUB_WORKFLOW_TYPE build-extension-catalog.yaml workflow passes "catalog" as GITHUB_WORKFLOW_TYPE
This change utilizes correct workflow types in the parse-tag-name script. For charts it checks against package.json in pkg and for catalog it checks against root package.json
Examples of failing workflows:
https://github.com/suse-edge/dashboard-extensions/actions/runs/7554197375
https://github.com/suse-edge/dashboard-extensions/actions/runs/7554197372
> Fix parse-tag-name script to use correct GITHUB_WORKFLOW_TYPE

- shell/assets/translations/en-us.yaml
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes https://github.com/rancher/dashboard/issues/10299
Fixes https://github.com/rancher/dashboard/issues/10266
This is a backport of https://github.com/rancher/dashboard/pull/9643 and https://github.com/rancher/dashboard/pull/9914
UX for these issues changed from what was originally outlined in the above issues. The initial plan was to remove the aws cloud provider option for k8s versions >=1.27 (rke2 cloud provider options come from an api call, so no need to explicitly remove the option in the UI). Generalized UI code was added to handle the possibility that a user is upgrading a cluster with a cloud provider that is no longer supported. 
The plan for aws external cloud provider support changed, and new UX involves selecting the 'aws' cloud provider option then adding some extra …
> [2.7] AWS external cloud provider support

- cypress/e2e/blueprints/manager/clusterProviderUrlCheck.ts
- cypress/e2e/po/edit/provisioning.cattle.io.cluster/create/cluster-create.po.ts
- cypress/e2e/tests/pages/manager/cluster-manager.spec.ts
- shell/config/query-params.js
- shell/edit/provisioning.cattle.io.cluster/index.vue
Fixes #6299 
- add query param `rkeType` to cluster creation url
- add logic to take into consideration `rkeType` query param when reading cluster provisioning create url
- replace some strings for consts in `edit/provisioning.cattle.io.cluster`
- add e2e test
- enter the url `c/local/manager/provisioning.cattle.io.cluster/create?type=digitalocean&rkeType=rke1` and make sure it loads the ember interface
- enter the url `c/local/manager/provisioning.cattle.io.cluster/create?type=digitalocean&rkeType=rke2` and make sure it loads the vue interface
> Add missing routing segments or query parameters for cluster creation with RKE1/2

- cypress/e2e/po/components/checkbox-input.po.ts
- cypress/e2e/po/components/labeled-select.po.ts
- cypress/e2e/po/edit/provisioning.cattle.io.cluster/create/cluster-create-rke2-custom.po.ts
- cypress/e2e/tests/pages/manager/cilium-ipv6.spec.ts
- shell/edit/provisioning.cattle.io.cluster/__tests__/Basics.test.ts
- shell/edit/provisioning.cattle.io.cluster/__tests__/CustomCommand.test.ts
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
- shell/edit/provisioning.cattle.io.cluster/tabs/Basics.vue
Fixes https://github.com/rancher/dashboard/issues/10047
Supersedes https://github.com/rancher/dashboard/pull/10048
This PR fixes the IPv6 support for RKE2 + Cilium.
It ensures migration of the setting in the case that a 1.23 cluster is upgraded and it adds automated tests.
Notes:
- Changed the `Basics.vue` Tab component to take care of the structure and emit the change for the parent `rke2.vue` to update the model with.
- Renames two e2e test to `.test.st` from `.tests.ts` so that the typescript imports work correctly in vscode
- Updated checkbox and labeled select POs to make them more reliable
- Added a single e2e test that validates the changes made to `Basics.vue` that setting ipv6 is correctly wired into the request sent to create a cluster.
- Added unit tests to cover the various …
> Fix incorrect spec structure for cilium ipv6 configuration

- cypress/e2e/blueprints/manager/cloud-credential-create-payload.ts
- cypress/e2e/blueprints/manager/digital-ocean-cluster-provisioning-response.ts
- cypress/e2e/blueprints/manager/machine-pool-config-response.ts
- cypress/e2e/po/edit/provisioning.cattle.io.cluster/cluster-create-import.po.ts
- cypress/e2e/po/edit/provisioning.cattle.io.cluster/edit/cluster-edit-generic.po.ts
- cypress/e2e/po/pages/cluster-manager/cluster-manager-list.po.ts
- cypress/e2e/tests/pages/charts/rancher-backup.spec.ts
- cypress/e2e/tests/pages/explorer/node-list.spec.ts
- cypress/e2e/tests/pages/manager/cloud-credential.spec.ts
- cypress/globals.d.ts
- cypress/support/commands/rancher-api-commands.ts
- shell/assets/translations/en-us.yaml
- shell/edit/cloudcredential.vue
- shell/edit/provisioning.cattle.io.cluster/SelectCredential.vue
Fixes #10020 
- fix issue with duplicate labels on editing a cluster cloud credential
- update label on `SelectCredential` to display combination of name and id (optional?)
- fix label and placeholder on `cloudcredential` edit view 
- fix translation for credential name placeholder 
**Note:** Cannot create e2e tests for creating cloud credentials, since we need valid tokens for any of the options available on the UI.
I’ve compared the code for `SelectCredential`  for `2.7.5` and `master` and nothing relevant changed (template and `options`  variable logic), which to me means that we’ve always had this problem.
https://github.com/rancher/dashboard/blob/release-2.7.5/shell/edit/provisioning.cattle.io.cluster/SelectCredential.vue vs …
> fix issue with duplicate labels on editing a cluster cloud  credential

- shell/components/LandingPagePreference.vue
- shell/components/SingleClusterInfo.vue
- shell/plugins/dashboard-store/actions.js
- shell/store/index.js
Fixes #10285
- loadManagement and loadCluster run in parallel
- both make requests to fetch mgmt clusters
- normally this is fine (loadManagement fetch finishes first, loadCluster requests then use that result)
- however in scenarios where there are a lot of clusters multiple requests are made
- we now wait for the loadManagmeent request to finish
Additionally
- make requests to correct (though harmless) url path (cluster --> clusters)
In environments where the cluster request takes multiple seconds this will knock off about 2/3 of the time when reloading / navigating directly to a ds cluster
- cluster load on ds cluster
> Avoid duplicate / surplus requests to fetch mgmt clusters

- shell/edit/__tests__/service.test.ts
- shell/edit/service.vue
Fixes #10252
1. Set clusterIP to an empty string, if it exists and the value is not None when clone a service
2. Remove clusterIPs if it exists when clone a service
> fix(service): reset clusterIP(s) field  when clone a service

- shell/components/nav/TopLevelMenu.vue
- shell/components/nav/__tests__/TopLevelMenu.test.ts
Fixes #10140 
- Fix breaking of `TopLevelMenu` component when `ui-banner` settings has an old structure (upgrade scenario from an old version)
- update unit tests to cover regression scenario
- `FixedBanner` component, which is responsible for the rendering of the banners already covers the above scenario (double-checked)
- Edit the code for the `TopLevelMenu` component https://github.com/rancher/dashboard/blob/master/shell/components/nav/TopLevelMenu.vue#L73 so that:
```
const parsed = {
banner: {
color:      '#78c9cf',
background: '#27292e',
text:       'Hello World!'
},
showHeader: 'true',
showFooter: 'false'
};
```
- Check that no error is thrown on the console or UI
> Fix for custom banner header without fontSize breaks top navigation (old obj structure)

- cypress/e2e/po/components/code-mirror.po.ts
- cypress/e2e/po/components/input.po.ts
- cypress/e2e/po/components/storage/config-map.po.ts
- cypress/e2e/po/pages/explorer/config-map.po.ts
- cypress/e2e/tests/pages/explorer/storage/configmap.spec.ts
- shell/components/form/KeyValue.vue
- shell/edit/configmap.vue
- shell/utils/__tests__/create-yaml.test.ts
- shell/utils/create-yaml.js
This introduces the capability to customize `jsyaml.dump` options in the `dumpBlock` function, allowing developers to supply all of the dump options specified by `jsyaml.dump()`.
Fixes #10270 
- Utilize options in `jsyaml.dump` when they are provided to `dumpBlock()`
- Specify `lineWidth: -1` in the `yamlModifiers()` for `configmap.vue`
- Create new e2e test for `configmap`
- Update unit tests for `create-yaml`
- Creating/Editing/Viewing config maps
- Other areas of Rancher Dashboard that might focus on creating/editing yaml
backports #10142
> Backport 2.8: Allow for `jsyaml.dump()` Options in `dumpBlock`

- shell/utils/__tests__/create-yaml.test.ts
- shell/utils/create-yaml.js
Fixes #10310
backports #10168
This prevents `dumpBlock()` from mutating parsed yaml when a header can't be located. More investigation might be warranted to discover why the regex used by `getBlockHeader()` isn't matching the keys when parsing the example yaml:
```
apiVersion: v1
data:
a: "a\nb\tc"
b: "a\nb\tc"
kind: ConfigMap
metadata:
name: yaml-tab-test
```
but the crux of the issue still comes down to the fact that `dumpBlock()` will indiscriminately mutate yaml output when a key can't be located; it's important that this behavior is corrected.
Stop mutating parsed yaml if the header can't be located.
Follow the repro steps left in comments on the issue:
https://github.com/rancher/dashboard/issues/9841#issuecomment-1745771047
Any yaml editor used throughout Rancher Desktop, but I …
> Backport 2.8: Prevent mutating yaml when a header isn't found

- pkg/aks/components/CruAks.vue
- pkg/aks/components/__tests__/CruAks.test.ts
- pkg/aks/l10n/en-us.yaml
- pkg/aks/util/__tests__/validators.test.ts
- pkg/aks/util/validators.ts
Fixes #7163
This PR adds privateDnsZone, userAssignedIdentity, and managedIdentity inputs to AKS cluster provisioning. These fields should only be configurable when 'private cluster' is set.
> Add possibility to set private DNS zone on AKS clusters

- cypress/jenkins/init.sh
Fixes #
This adds a fix for when a RANCHER_VERSION variable is empty. Then we just pull the latest Rancher chart version to use during the Rancher install. This happens in the window where a RANCHER_IMAGE_TAG has the latest in development version but there's still not chart released.
Jenkins pipeline.
Jenkins environment setup. Recurring jobs
> [Automation] - adding fix for empty RANCHER_VERSION string

- cypress/e2e/po/components/sortable-table.po.ts
- cypress/e2e/tests/pages/explorer/namespace-picker.spec.ts
Fixes #
Namespaces groups title name validation on tests running on Jenkins and local.
Added a method to the `SortableTablePo` to look for specific namespace groups. Also added `scrollIntoView()` method in case the viewport has a small height.
Tests that are related to namespace picker. Validate pass on Jenkins.
```
Running:  namespace-picker.spec.ts                                                       (4 of 12)
Namespace picker
✓ can filter workloads by project/namespace from the picker dropdown (13279ms)
✓ can select only one of the top 5 resource filters at a time
✓ can select multiple projects/namespaces
✓ can deselect options
✓ can filter options by name
✓ newly created project/namespace appears in namespace picker (27672ms)
6 passing (49s)
<?xml version="1.0" encoding="UTF-8"?> …
```
> Adding fix for table rows groups name validation

- shell/store/plugins.js
When creating a custom node driver for OVHCloud, the UI shows all possible choices for cloud providers, including `aws` , `azure`, etc.
In order to restrict the choice to only, `rke2-embedded` and `external`, an entry to the map `driverToCloudProvider`, with an an empty string as a value, has to be added for `ovhcloudpubliccloud` key.
Only change is adding an `ovhcloudpubliccloud` entry to a hard-coded map.
- Check that when creating a node driver cluster using the UI, the traditional node drivers show the usual values in the list `Cloud Providers`
- Check that when creating an `ovhcloudpubliccloud` node driver cluster, the choice list is only `rke2-embedded` or `external` .
Probably node.
> Show specific providers when creating RKE2 cluster in OVH

- shell/scripts/extension/parse-tag-name
Fixes #10363 
This changes the workflow type in `parse-tag-name` to check for `catalog` instead of `charts`. The intent of this condition is to determine if there are any naming collisions with the release tag name and any package names when releasing an Extension Catalog Image.
The `else` condition will be checking for naming collisions with the release tag name and the root package name.
> Fix parse tag name condition to check for proper workflow types

- cypress/e2e/blueprints/manager/clusterProviderUrlCheck.ts
- pkg/aks/provisioner.ts
- shell/core/types-provisioning.ts
- shell/edit/provisioning.cattle.io.cluster/index.vue
- shell/models/management.cattle.io.kontainerdriver.js
Fixes #10302
This PR expands provisioning extension functionality to allow them to:
* overwrite existing node/machine/kontainer driver UI
* define support for importing clusters, with the default being that they do not
Previously the AKS provisioning extension replaced the old UI by marking the AKS kontainer driver as 'hidden' - this update allows prov extensions to replace builtin ui without further updating dashboard code.
I'm not confident that the way extensions may overwrite existing UI is clear enough: In this context the subtype `id` that needs to line up doesn't necessarily map to a driver resource's `id` as you might expect; kontainer drivers have this hard-coded mapping to align with Ember urls: https://github.com/rancher/dashboard/blob/871d059043c5a4b42c085ff944a53ecc0763e2b6/sh …
> Allow cluster provisioning extensions to define cluster-importing support

- shell/models/__tests__/storage.k8s.io.storageclass.test.ts
- shell/models/storage.k8s.io.storageclass.js
- storybook/.storybook/main.js
Fixes #9968 
- add `(CSI)` suffix to all non-builtin `storageClass` provisioners
- add unit test
- follow repro steps of #9968 (it should have the suffix in the end)
- follow repro steps of #9968 BUT edit the yaml provisioner to `kubernetes.io/azure-disk` (it should not show `(CSI)` suffix)
_Before_
_After_
> add CSI suffix to all non-builtin storageClass provisioners

- shell/detail/fleet.cattle.io.bundle.vue
It was reported in slack that the bundle page would error out when visiting the bundle pages due to an undefined reference. This resolves that issue.
Found the problem after replaying the user generated HAR file which yielded this in the console:
> Fixing an issue where a field can sometimes be undefined

- cypress/e2e/tests/pages/manager/cluster-manager.spec.ts
Fixes #
The bulk actions element seems to only appear below certain browser screen size. On Jenkins the viewport is of a more standard or real user screen which is larger than the default. To run the tests. 
Fix:
```
- Imported
- Generic
- can delete cluster by bulk actions
```
E2E tests execution on Jenkins pipeline.
Results on dockerized execution:
```
Imported
Generic
✓ can create new cluster (15092ms)
✓ can navigate to cluster edit page (6259ms)
✓ can delete cluster by bulk actions (8633ms)
<testsuite name="Root Suite.Cluster Manager.Imported.Generic" timestamp="2024-02-01T16:05:24" tests="3" time="30.439" failures="0">
<testcase name="can create new cluster" time="15.092" classname="Cluster Manager.Imported.Generic">
</testcase>
<testcase name="can navigate to cluster edit page" …
```
> [Automation] - Add specific viewport size for Bulk Actions element to show 

- shell/models/__tests__/provisioning.cattle.io.cluster.test.ts
- shell/models/provisioning.cattle.io.cluster.js
Fixes #10043 
- Update logic of `hasError` in `provisioning.cattle.io.cluster` model
- Add unit test for `cluster.status.conditions` which affect the outcome of `hasError` model property
- Check SURE details in #10043 and grab the HAR files
- Use https://github.com/rancher/dashboard/blob/master/docs/developer/har-files.md#yarn-dev to run this branch
- Verify that the cluster is available to "explore"
**NOTE:** I never tested it this way, so I am not 100% this will work. All of the investigation was based on the HAR files output and code checks in Dashboard which I've tried to sum up in the comments of #10043
> Update logic of 'hasError' in 'provisioning.cattle.io.cluster' model

- cypress/e2e/tests/pages/explorer/cluster-tools.spec.ts
- cypress/e2e/tests/pages/explorer/storage/configmap.spec.ts
Fixes #
Adding tags to a couple of e2e specs (`/explorer/cluster-tools.spec`, `/explorer/storage/configmap.spec`) that aren't running in CI as they're missing their group/user tag.
> Adding missing tags to tests

- shell/detail/__tests__/provisioning.cattle.io.cluster.test.ts
- shell/detail/provisioning.cattle.io.cluster.vue
- shell/models/__tests__/provisioning.cattle.io.cluster.test.ts
- shell/models/provisioning.cattle.io.cluster.js
Fixes #9402 
- change condition to show registration tab only on hosted providers with private endpoint/network on `detail/provisioning.cattle.io.cluster`
- Go to Cluster Management - Create - Select `Google GKE` hosted provider
- Move forward on the cluster creation until you get the `Cluster Options` tab
- On `Cluster Options` tab select `show advanced options` on the bottom-right corner
- After expanding, select `Enable Private Endpoint` and finish the creation process
- Go to that cluster details and make sure the `registration` tab appears
- Repeat the steps above to create another but WITHOUT enabling `Private endpoint`
- Check the details for this last cluster and make sure that the `registration` tab doesn't appear
> show registration tab only on hosted providers with private endpoint/network

- cypress/e2e/tests/pages/manager/cluster-manager.spec.ts
- cypress/e2e/tests/pages/manager/mock-responses.ts
- shell/edit/provisioning.cattle.io.cluster/index.vue
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
This ports RKE1 behavior over to RKE2 where we bypass the credential prompt when using a node driver with the `addCloudCredential` property set to false
This is achieved by having the cluster creation page pass the nodeDriver config object down to the rke2 component so the rke2 component can inspect the the property.
https://github.com/rancher/dashboard/issues/7023
I tested this using the `Nutanix` driver instead of the `Proxmoxve` since would get stuck in a `Downloading` state for me.
Drivers with and without the `addCloudCredential` should be tested. 
- I know Nutanix is false while Digitalocean is true.
> Make rke2 clusters respect the machingConfig `addCloudCredential` property set to false

- cypress/jenkins/cypress.sh
Fixes: An small fix to use an environment variable instead of an `--env` flag for `grepTags`. Using `--env` was unstable when using tags separated by commas.
Jenkins pipeline
N/A
> [Automation] - Use the grepTags as environment variable

- cypress/e2e/po/side-bars/burger-side-menu.po.ts
- cypress/e2e/tests/pages/global-settings/banners.spec.ts
- cypress/e2e/tests/pages/global-settings/branding.spec.ts
Fixed branding and banners tests:
- improved banner tests by adding an `afterAll` hook to restore settings to the original state
- replaced `navTo` with `goTo` in two places where the tests were hanging and eventually failed bc the loading indicator persists and the UI is covered by it. Note: this is an automation-specific issue.
- ~~navigation tests were failing in Jenkins bc the burger menu was not visible so updating the assertion to `should('exist')` did the trick.~~
Tests passing in Jenkins runs
> improvements and fix flaky global settings tests

- .github/workflows/port-issue.yaml
Backport issues created by the backport bot don't automatically have the `[Zube]: Triage` label. The workflow https://github.com/rancher/dashboard/blob/master/.github/workflows/port-issue.yaml uses a github token to create the issue, which doesn't trigger the `opened` event in https://github.com/rancher/dashboard/blob/master/.github/workflows/add-to-triage-label.yaml which adds the zube label (https://github.com/orgs/community/discussions/24953).
Update the port-issue workflow to add the `[zube]: Backlog` label (as this is more appropriate than triage)
> Add `[zube]: Backlog` label to backported issues

- cypress/e2e/po/side-bars/product-side-nav.po.ts
- cypress/e2e/tests/pages/charts/istio.spec.ts
We need to disable the Istio nav item checks after installation in e2e tests and fix the nav item selector.
- Fixes e2e tests `nav` items selector for when the DOM changes and the test is waiting for finding a new element.
- Istio nav item check suspended.
As follow up, we will re-enable the Istio nav item check once we figure out why Istio is not being installed.
none
> Fix e2e nav items selector and suspend Istio nav item check

- shell/components/SideNav.vue
- shell/components/nav/Jump.vue
- shell/components/nav/Type.vue
- shell/components/nav/__tests__/Type.test.ts
- shell/plugins/dashboard-store/getters.js
- shell/store/__tests__/type-map.test.ts
- shell/store/index.js
- shell/store/type-map.js
Fixes #7773
> The general refactor of the side nav is covered by https://github.com/rancher/dashboard/issues/5607
- getGroups creates the entries used in the side nav (and the explorer resource search modal)
- This previously was triggered often and on large / slow systems can run slowly, both impacting UI performance
- This PR improves this performance in two ways
- Improve performance of allTypes fn
- This consumed the majority of time within getGroups
- PR reduces execution time by a half
- It does this by 
- calculating entries for a product given all modes requests... rather than one per product per mode
- skip calling the costly labelFor fn unless we actually need to
- Reduce the amount of times getGroups is called
- don't trigger on changes to counts (which changes often). Instead …
> Improve getGroups performance

- shell/assets/translations/en-us.yaml
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
- shell/edit/provisioning.cattle.io.cluster/tabs/Basics.vue
This reverts changes made by  Aws In-tree support (#9643). While testing, it appears that the intent of this PR (to handle upgrade cases and display a banner) can never be triggered.
fixes #10426
> Revert "Aws In-tree support (#9643)"

- shell/assets/translations/en-us.yaml
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
This reverts changes made by  Aws In-tree support (#9643). While testing, it appears that the intent of this PR (to handle upgrade cases and display a banner) can never be triggered.
fixes #10427
backports #10426
> [backport v2.7.patch1] Revert "Aws In-tree support (#9643)"

- shell/assets/translations/en-us.yaml
- shell/edit/provisioning.cattle.io.cluster/Basics.vue
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
This reverts changes made by  Aws In-tree support (#9643). While testing, it appears that the intent of this PR (to handle upgrade cases and display a banner) can never be triggered.
fixes #10428
backports #10426
> [backport v2.8.next1] Revert "Aws In-tree support (#9643)"

- shell/components/ResourceYaml.vue
Fixes https://github.com/rancher/dashboard/issues/8999
When editing a resource by Yaml, we use different footer components depending on scenarios below:
- Edit resource -> Edit Yaml: `CruResourceFooter.vue` is used
VS
- Edit Yaml directly -> `Footer.vue` is used, it's not sticked to the bottom.
It adds same CSS classes of CruResource.vue to ResourceYaml.vue
Yaml Editor
> Stick ResourceYaml footer to the bottom

- shell/components/formatter/WorkloadDetailEndpoints.vue
- shell/components/formatter/__tests__/WorkloadDetailEndpoints.test.ts
Fixes #8087 
- update logic of `WorkloadDetailEndpoints` to consider hostname as a valid link if there is an `ingress` associated
- formatter code cleanup (unused computed property)
- Install repository as `git repo` -> `https://github.com/bashofmann/rodeo` - branch `master` in `apps` - `repositories` on `local` cluster
- in `apps` - `chart` on `local` cluster, find a card for `tetris` app that comes from the repo added on the step before and install it
- on `local` cluster, `workloads` - `deployments`, find the deployment associated with the deployment of `tetris`
- On the details in the top of the page, check that the `endpoints` link points to the hostname `tetris.kube-public.172.18.0.3` as per the changes on this PR 
**Before**
**After**
> update logic of `WorkloadDetailEndpoints` to consider hostname as a valid link if there is an `ingress` associated

- shell/utils/__tests__/create-yaml.test.ts
- shell/utils/create-yaml.js
Fixes #10371 
`dumpBlock` always expects to receive strings but in the case of registry configs/mirrors the value is an object. This change checks for string type before creating blocks in `dumpBlock`.
All the registries section functionalities.
https://github.com/rancher/dashboard/assets/135728925/ec8c69fa-f94d-4bc6-8866-462730b0adc7
> Fix TypeError when registries are added to cluster in Edit as YAML mode

- shell/plugins/dashboard-store/__tests__/actions.test.ts
- shell/plugins/dashboard-store/actions.js
- shell/plugins/steve/__tests__/getters.spec.ts
- shell/plugins/steve/getters.js
Fixes #10410
- much more detail in issue description
- the two fixes are small
- remove labelSelector from filter param and add direct to opt in findMatching
- explicitly add labelSelector to url in urlOptions
- add unit tests to ensure
- findMatching action calls urlFor with correct args
- urlOptions getter create correct url given labelSelector
- see issue description
> Fix issue where labelSelector param was incorrectly applied to filter param

- cypress/e2e/tests/pages/manager/cluster-manager.spec.ts
- shell/assets/translations/en-us.yaml
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
- shell/edit/provisioning.cattle.io.cluster/tabs/Basics.vue
Fixes #10338 
- add option of 'none' for Container Network select in Basics tab of RKE2 provisioning
- add e2e test to check that option is available and can be selected
- Under `Cluster Management`, create a `RKE2 custom` cluster
- On the `Basics` tab, `Container Network` select, select the option `none`
- Check that on the network request payload has been sent with `none` and check YAML after creation to confirm as well
`spec.rkeConfig.machineGlobalConfig.cni`
**Confirmation of data after cluster creation**
> add option of 'none' for Container Network select in Basics tab of RKE2 provisioning

- shell/package.json
This will bump the `@rancher/shell` package to version `0.5.3`.
There are a number of fixes for this release, but two that are rather notable:
- https://github.com/rancher/dashboard/pull/10413
- https://github.com/rancher/dashboard/pull/10008
> Bump @rancher/shell to 0.5.3

- shell/assets/translations/en-us.yaml
- shell/components/form/ArrayList.vue
- shell/edit/provisioning.cattle.io.cluster/__tests__/Advanced.test.ts
- shell/edit/provisioning.cattle.io.cluster/tabs/Advanced.vue
- shell/edit/provisioning.cattle.io.cluster/tabs/Basics.vue
Fixes https://github.com/rancher/dashboard/issues/10045
Rancher UI expects to find the `kubelet-arg` configuration in `spec.rkeConfig.machineSelectorConfig[0].config` where it can also be defined in `spec.rkeConfig.machineGlobalConfig`, see docs https://ranchermanager.docs.rancher.com/reference-guides/cluster-configuration/rancher-server-configuration/rke2-cluster-configuration#machineselectorconfig.
We are assuming the UI should take the kubelet-arg value from machineGlobalConfig when defined and display it in the same panel where it shows the kubelet-arg from machineSelectorConfig.
Use cases scenarios:
- Create:
-  only `machineSelectorConfig` is used
- Edit / View:
- in the case that ONLY machineSelectorConfig in the Yaml, UI can only add/modify kubelet-arg in machineSelectorConfig.
- …
> Handle `kubelet-arg` when defined in cluster's global configurations

- shell/machine-config/__tests__/vmwarevsphere.test.ts
- shell/machine-config/vmwarevsphere.vue
Fixes #10460 
`hostsystem` and `folder` can be `null` or `""`, this PR adds this into consideration before displaying error banners.
Provisioning vSphere Clusters
https://github.com/rancher/dashboard/assets/135728925/de64f2e2-058c-46f8-9379-3de0aceb94a6
> Fix displaying false vsphere errors

- shell/edit/provisioning.cattle.io.cluster/rke2.vue
- shell/edit/provisioning.cattle.io.cluster/tabs/MachinePool.vue
- shell/machine-config/__tests__/vmwarevsphere.test.ts
- shell/machine-config/vmwarevsphere.vue
Fixes #10476 
Note: Better to be merged after [this PR](https://github.com/rancher/dashboard/pull/10473).
Previously `vmwarevsphere.vue` relied only on `this.mode === _CREATE` to populate default values, but in Edit mode if you add a new pool you want the same behaviour. In order to detect this state `poolCreateMode` is passed as a prop to `vmwarevsphere.vue`.
Provisioning vSphere cluster with multiple pools.
Provisioning vSphere cluster.
https://github.com/rancher/dashboard/assets/135728925/00180e5f-139c-4ab0-9efb-68c524aaacbd
> Fix default values not being set when a new pool is added in edit mode

- .github/workflows/port-pr.yaml
This is a follow-up to #10478
The goal of this PR is to relay an error message when the Port PR action fails to apply a patch. The current behavior isn't very helpful and requires digging through logs for actions when a failure occurs. For example
|
> Relay an error message when the backport fails

- cypress/e2e/tests/pages/manager/cloud-credentials.spec.ts
- cypress/e2e/tests/pages/manager/cluster-manager.spec.ts
- cypress/e2e/tests/pages/manager/cluster-provisioning-amazon-ec2-rke2.spec.ts
- cypress/e2e/tests/pages/manager/drivers.spec.ts
- cypress/e2e/tests/pages/manager/machine-deployments.spec.ts
- cypress/e2e/tests/pages/manager/machine-sets.spec.ts
- cypress/e2e/tests/pages/manager/machines.spec.ts
- cypress/e2e/tests/pages/manager/node-templates.spec.ts
- cypress/e2e/tests/pages/manager/pod-security-admissions.spec.ts
- cypress/e2e/tests/pages/manager/pod-security-policy-templates.spec.ts
- cypress/e2e/tests/pages/manager/repositories.spec.ts
- cypress/e2e/tests/pages/manager/rke-templates.spec.ts
- cypress/e2e/tests/pages/users-and-auth/users.spec.ts
Fixes #
This PR addresses test failures/flaky tests in the Jenkins pipeline for manager and users tests
- Cypress clears aliases between tests; after the first test `undefined` is returned so I've moved the variables into beforeEach hook.
- rke2 aws cluster provisioning test was failing bc subnets were no longer available in the network that was previously selected. I've updated the selection to use a reliable VPC/subnet network.
- ~~change navTos to goTos in one test in each of these specs to prevent failures (drivers, rke templates, and node template tests)~~
- when using default viewport values, the download kubeconfig button should not appear in the bulk action menu dropdown. The fix here is to use `downloadKubeConfig` fn instead of clicking on it from the dropdown menu.
- set …
> address jenkins failures for manager and users tests

- cypress/e2e/po/edit/provisioning.cattle.io.cluster/create/cluster-create.po.ts
- cypress/e2e/po/side-bars/product-side-nav.po.ts
- cypress/e2e/tests/pages/manager/cluster-manager.spec.ts
Fixes #10056 
- add e2e test to to improve test coverage of #10056
> add e2e test to test issue 10056

- .github/workflows/port-pr.yaml
It looks like the Port PR workflow is now failing[^1] after attempting to better relay error messages in #10494. We should be using `test`[^2] to evaluate the conditional expression properly. This PR uses the `[...]` form.
[^1]: https://github.com/rancher/dashboard/actions/runs/8008010814/job/21874248633
[^2]: https://www.gnu.org/software/bash/manual/html_node/Bourne-Shell-Builtins.html#index-test
> [Workflow] Port PR: Use `[...]` to evaluate conditional expression

- shell/pages/c/_cluster/explorer/tools/__tests__/index.test.ts
- shell/pages/c/_cluster/explorer/tools/index.vue
Fixes https://github.com/rancher/dashboard/issues/10458
For Clusters having  `multi-cluster-management=false` the `project` schema is not available. 
We are avoiding to fetch `project` schema when `multi-cluster-management` is disabled.
- Install a new Rancher cluster with `multi-cluster-management=false`, https://github.com/rancher/dashboard/issues/10458#issuecomment-1959603429
- Go to `ClusterTools` page
> Disable project fetch in ClusterTools page when MCM is disabled

- .github/workflows/port-pr.yaml
This provides some additional enhancements for the Port PR workflow and includes the following
- Ensures that milestones can be added to title and assigned to backport PR
- Populates body of new PR with original PR body
- Updates the branch for the backport PR
- Add the original PR assignee to the newly created one
Fixes # 10511
> [Workflow] Port PR: Add Milestone, Body, and Assignee to New PR

- cypress/e2e/po/components/async-button.po.ts
- cypress/e2e/po/components/labeled-input.po.ts
- cypress/e2e/tests/pages/manager/cloud-credentials.spec.ts
- shell/assets/translations/en-us.yaml
- shell/edit/cloudcredential.vue
- shell/edit/provisioning.cattle.io.cluster/SelectCredential.vue
Fixes #10424 
- make name required by form validation 
- update form validation for creds that send validation from custom component 
- remove 'optional' from placeholder 
- allow editing of the 'name' prop in cloud creds 
- add tests
https://github.com/rancher/dashboard/assets/97888974/39fc2f8f-fbe8-460b-9942-60510ed7be8a
https://github.com/rancher/dashboard/assets/97888974/9c1a9ec6-163d-4b7c-bf62-600e1f7c0601
> Cloud Credentials: Missing Credential Name 

- shell/store/plugins.js
Summary
This is a backport of https://github.com/rancher/dashboard/pull/10313. For details see description
> ~Currently blocked on target branch version~
> [2.7] Adding ovhcloudpubliccloud to the driverToCloudProvider map in order to restrict options for Cloud Provider

- shell/edit/workload/mixins/workload.js
Fixes #9990 
Backport of https://github.com/rancher/dashboard/pull/9913
- Gate `workload mixin` fetches with `canList`
- As admin, create a user with user-base
- Create a project and add a namespace
- Create an image pull secret (registry secret) int this new namespace
- Give the new user member access to the project
- Login as the new user
- Go to create a new workload in the namespace in the project and in general, check the 'Pull Secrets' dropdown in the Image section - with this bug, this will be empty. With this fix, the list should show the secret that was created.
https://github.com/rancher/dashboard/assets/97888974/46e50372-659a-4456-94b5-c38e0879a479
> Issue 9990 - Fix RBAC issue with workload create/edit screen - Backport for PR 9913

- cypress/e2e/blueprints/global/settings/links.ts
- cypress/e2e/blueprints/global_settings/home-links-response.ts
- cypress/e2e/tests/pages/generic/collective.spec.ts
This is a small tidy-up.
I noticed that there was now a new `global_settings` folder in `blueprints`, so this PR moves the file added in the SUSE collective PR into that existing folder and file.
> Collective doc e2e: Merge links.ts into existing home-links-responses.ts

- cypress/jenkins/Jenkinsfile_multi
- cypress/jenkins/init.sh
This will use a k3s cluster for the Rancher installation. Originally using rke2.
This will rename the RKE2 kubernetes version variable to K3s and use a k3s corral package for the Rancher install.
This change is done to the Jenkins automation environment in order to mitigate any Rancher behavior dependent on cluster types.
Like is the case here. https://github.com/rancher/rancher/issues/28787#issuecomment-693611821 
This will require
> [Automation] - Change local HA cluster type configuration to k3s

- .github/workflows/port-issue.yaml
- This fails when there's a line break after the milestone in a comment
- https://github.com/rancher/dashboard/actions/runs/7974403963/job/21770298336
- Check milestone passes, Port Issue fails 
```
could not add to milestone 'v2.8.next1 ': 'v2.8.next1
' not found
Error: Process completed with exit code 1.
```
- I can't get check milestone to succeed locally with a line break in the milestone (tried a couple of different types)
- Adding better logging to see what happens if fails in future
> Add additional logging to port-issue workflow

- shell/assets/translations/en-us.yaml
- shell/pages/c/_cluster/longhorn/__tests__/longhorn.index.test.ts
- shell/pages/c/_cluster/longhorn/index.vue
Fixes #10259 
The Longhorn frontend UI would fail to load as the `namespace` was hard-coded to `longhorn-system`. Although setting this namespace is the [recommended approach](https://longhorn.io/docs/1.5.3/deploy/install/install-with-helm/#installing-longhorn) when installing Longhorn with Helm, users may still determine their own namespace.
This adds a computed property to find the Longhorn UI based on the label `app=longhorn-ui` which is defined in the [Longhorn Helm chart](https://github.com/rancher/charts/blob/38aed06f77002690b4857d84e79252bed828dc82/charts/longhorn/103.2.1%2Bup1.5.3/templates/deployment-ui.yaml#L16). 
If the service is found, the `externalLinks` will contain the correct namespace of this service in the `link` property.
I've also added a banner to display an error …
> Restructure longhorn UI proxy link to contain dynamic namespace

- .github/workflows/port-pr.yaml
This fixes some issues with relaying error messages and transferring assignees when backporting a PR.
- Properly relay an error message in the original PR when there is a problem running `git am` (example located in my fork [^1])
- Properly append the list of assignees (code taken from Port Issue [^2])
Fixes #10511
[^1]: https://github.com/rak-phillip/dashboard/pull/42#issuecomment-1967315236
[^2]: https://github.com/rancher/dashboard/blob/dbe99ccb00e294811d8938fa529e6b0bb8120c86/.github/workflows/port-issue.yaml#L77-L94
> [Workflow] Port PR: Fix issues with assignees and relaying error messages

- cypress/e2e/po/side-bars/burger-side-menu.po.ts
- cypress/e2e/tests/navigation/side-nav/main-side-menu.spec.ts
- cypress/e2e/tests/pages/charts/rancher-backup.spec.ts
- cypress/e2e/tests/pages/generic/home.spec.ts
- cypress/e2e/tests/pages/global-settings/feature-flags.spec.ts
- shell/assets/styles/themes/_dark.scss
- shell/components/nav/TopLevelMenu.vue
- shell/components/nav/__tests__/TopLevelMenu.test.ts
- shell/pages/home.vue
Fixes #10441 
Fixes #8854 
- Add cluster description to the `home` page cluster table
- Add cluster description to the side menu (main nav) clusters with a tooltip to display the description on hover
- Add unit and e2e tests
- Fix issue with e2e where the main side nav got into a weird state where button to toggle it was no longer visible, causing tests to fail
- Fix issue with e2e where some tests weren't running due to misusage of the `tag` property (should only accept arrays and not strings)
- Fix issue where if we were on home page and clicked on main nav link to go to home page wouldn't close the side nav
- Fix issue with e2e where asserting visibility of product (Harvester Manager) on main nav while disabling/enabling feature flag needed a page refresh
- Create/edit a couple of …
> Add cluster description to cluster side menu and main menu

- cypress/e2e/tests/pages/user-menu/logout.spec.ts
- shell/assets/translations/en-us.yaml
- shell/components/nav/Header.vue
- shell/config/query-params.js
- shell/pages/auth/login.vue
- shell/store/index.js
Fixes #10519 
- add logic to change copy of logout screen when logging out with an auth provider different than local
- add e2e test
- Enable `Github` auth provider via `Users & Authentication` -> `Auth Provider` (follow instructions displayed there)
- Do a `logout` and check that logout message is according to the issue `You've been logged out of Rancher, however you may still be logged in to your single sign-on identity provider`
- Disable `Github` auth provider, do a logout and check that message reverted to the old text
https://github.com/rancher/dashboard/assets/97888974/1a11b2c5-8a3a-4479-9679-6719ac2c67e0
> Improve logout message for SSO

- cypress/e2e/blueprints/manager/registries-rke2-payload.ts
- cypress/e2e/po/components/registries-tab.po.ts
- cypress/e2e/po/components/registry-configs.po.ts
- cypress/e2e/po/edit/provisioning.cattle.io.cluster/create/cluster-create-rke2-custom.po.ts
- cypress/e2e/tests/pages/registries.spec.ts
- shell/edit/provisioning.cattle.io.cluster/RegistryConfigs.vue
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #10514  and #10337 
Backport of PR to 2.8 => https://github.com/rancher/dashboard/pull/10397
Note: The folder re-structuring around `rke2.vue` doesn't exist in 2.8 so the changes ported to 2.8 a bit differently. Also some minor changes needed to make the e2e tests work.
> [2.8 Backport] Registry auth fix

- .github/workflows/pr-gh-project.yaml
- .github/workflows/pr-zube.yaml
- .github/workflows/scripts/pr-gh-project.js
- .github/workflows/scripts/request.js
- scripts/github/zube-migration
This PR adds a script to migrate the swimline from the Zube label on a GH issue to the GitHub Project.
It also adds a new workflow to move linked issues to the appropriate column in the GH Project.
Note:
- This is currently not complete, but needs to be merged, so I can test the permissions that the GH_TOKEN has, to understand if it can read the GH project.
> Add zube migration script (WIP)

- shell/config/uiplugins.js
- shell/vue.config.js
This resolves an error where importing extensions that utilize backported features will throw the error `object(...) is not a function` by explicitly importing `vue.runtime` to ensure that Dashboard is always exposing the UMD builds of Vue to the `window` object. This error originally occurred because different builds of Vue (ESM vs. UMD) are used depending on the environment; there are differences in how backported Vue 3 features are exposed in Vue 2.7[^1], so it's important that the intended build is explicitly attached to the `window` object so that extensions can be imported without error. 
For more information on different builds that are available to us, see the vue documentation for explanation of different builds [^2].
This also bumps the `UI_PLUGIN_API_VERSION` to signal that …
> [Extensions] Expose UMD Builds of Vue to the `window` Object

- shell/machine-config/__tests__/vmwarevsphere.test.ts
- shell/machine-config/vmwarevsphere.vue
Fixes #10500 
Backport of PR to 2.8 => https://github.com/rancher/dashboard/pull/10473
> [2.8 Backport] Fix vSphere hostsystem false error

- shell/components/AppModal.vue
- shell/components/PromptModal.vue
- shell/components/__tests__/AppModal.test.ts
- shell/dialog/RollbackWorkloadDialog.vue
- shell/public/index.html
- storybook/stories/components/AppModal.stories.mdx
This is the first of PRs to replace the existing `vue-js-modal` package with something that we can use to more easily transition Rancher Dashboard over to Vue 3.
The scope of this change is limited to `PromptModal.vue`; there are still instances of the `<modal>` component used throughout Rancher Dashboard. I find that it's best to limit the scope of this change to ensure that we cover all of the use cases for the `PromptModal`, which is widely used throughout Rancher Dashboard. 
Supports #8207
This PR adds a new `AppModal` component that serves as a replacement for the features that we rely on from `vue-js-modal`: displaying and sizing modal dialogs. 
I chose `portal-vue` as a replacement for `vue-js-modal` for the following reasons:
- Existing `vue-js-modal` is fairly simple and readily …
> Replace modal implementation in `PromptModal.vue`

- shell/plugins/dashboard-store/actions.js
- shell/plugins/steve/__tests__/getters.spec.ts
- shell/plugins/steve/getters.js
- shell/plugins/steve/mutations.js
- shell/plugins/steve/subscribe.js
> Requires v2.9-head at or passed 793118f (from late 2024-03-07)
Fixes #10540
- See issue description for detail. Description on how sockets work in https://github.com/rancher/rancher/issues/41809#issuecomment-1584899188
- Ensure that watches on single resources that fail with `too old` fetch the latest version of the resource and re-watch without a revision
- There were three bugs
- core issue - the re-watch used the same `too old` revision from the resource, resulting in the `too old` message again ad nauseam 
- the http request to fetch the latest version failed for namespaced resources
- the inError state is fetched via a key constructed of id, namespace and selector, however the inError state from resource.error messages only used the key... which meant for watches that used id or …
> Ensure `too old` messages for watches in individual resources are handled correctly

- shell/core/plugin.ts
- shell/edit/provisioning.cattle.io.cluster/index.vue
Fixes #10148
This PR allows extensions to override the icons for node providers.
This introduces the ability to override via: 
```
plugin.register('image', 'providers/openstack.svg', require('~shell/assets/images/providers/exoscale.svg'));
```
This has been tested by dev.
For QA, test when you go to the cluster creation screen, that the icons display correctly, e.g.:
Toggle between RKE1 and RKE2 and check the icons for both are okay and that there are no broken icons.
Note: The fix is quite simple, the main change in `shell/core/plugin.ts` is to allow both `models` and `images` to contain the `/` character in their names - currently only `models` do - for the other resources, the `/` is used differently.
> Allow extensions to override node provider icons

- .github/workflows/test.yaml
- cypress/e2e/tests/pages/global-settings/settings.spec.ts
- scripts/check-e2e-tests-for-tags
Fixes #9350 
This PR adds a script and a new step to the `tests` PR workflow that runs that script.
The script reads and parses all of the Cypress e2e test files and looks for any that do not have tags - it errors if there are tests without tags.
There was one such test in the repo - you can see how this new job and script detected it here: https://github.com/rancher/dashboard/actions/runs/8202971806/job/22434861248?pr=10578
This test was also subsequently updated as part of this PR, so that the PR passes the gates.
With the above, I don't think this needs QA other than the reviewer checking over the PR and the test run above.
Note: There was a suggestion to use a lint rule, but this seemed tricky given that tags apply downwards - so an `it` block may not have tags, but it will inherit …
> Add script and CI job to check that all e2e tests have tags

- .github/workflows/add-qa-label.yaml
- .github/workflows/scripts/add-qa-label.js
Fixes #10573
This PR adds a new GitHub action that runs when new issues are created and ensures that the issue has a QA label if it has none of these labels:
- `QA/dev-automation`
- `QA/manual-test`
- `QA/None`
The label that is added is chosen as follows:
1. If the issue has the `kind/tech-debt` label then we use `QA/None`
2. Otherwise, If the issue has the `ember` label then we use `QA/manual-test`
3. Otherwise we use `QA/dev-automation`
This action has been tested on a separate test repository and does not need QA.
> Add GH Action to ensure new issues have a QA label

- shell/assets/translations/en-us.yaml
- shell/machine-config/azure.vue
Fixes #9858 
Fixes #10470 
This is a remake of https://github.com/rancher/dashboard/pull/10083 which I do not have permission to push an additional fix to. This PR updates the azure machine config component to ensure that the node pool region set by default is available in the current credentail's environment (eg azure gov, azure china, azure public). 
Create/edit azure RKE2 clusters with azurepubliccloud credentials, and with either azure china or azure gov credentials. @smallteeths has verified with azure china credentials and I verified with azure gov credentials.
> Ensure Azure RKE2 default region is available with selected cloud credential

- shell/plugins/dashboard-store/actions.js
- shell/plugins/steve/__tests__/getters.spec.ts
- shell/plugins/steve/getters.js
- shell/plugins/steve/mutations.js
- shell/plugins/steve/subscribe.js
This is a backport of https://github.com/rancher/dashboard/pull/10579 and only contains cherry-picked commits from that PR
Fixes #10567
> Requires a 2.7.next1 RC OR locally built rancher from `release/2.7` to validate. Apart from that steps are no different from any of the others in this chain
> [backport v2.7.next1] Ensure too old messages for watches in individual resources are handled correctly

- shell/machine-config/__tests__/vmwarevsphere.test.ts
- shell/machine-config/vmwarevsphere.vue
Fixes #10460 
`contentLibrary` was added to the list of the fields that should be exempt from displaying errors when their value is `null` or `""`. Also found `network` and `tag` to be special cases where they're falsy
Provisioning vSphere Clusters
Provisioning vSphere Clusters
> Error handling for contentLibrary, tag and network fields

- package.json
- scripts/e2e-docker-start
`v2.9-head` recently introduced a breaking that causes e2e test related to installing extensions to fail. This is a temporary change to allow e2e tests to run successfully while we work on a fix.
With this change, e2e tests they will explicitly target `v2.9-a83e8c5526b54153aee0edbc2dc7b6d8ea982bec-head` instead of `v2.9-head`; the backend is essentially pinned to this version until we can unblock it.
> Target `v2.9-a83e8c5526b54153aee0edbc2dc7b6d8ea982bec-head` for e2e runs

- cypress/e2e/tests/pages/global-settings/settings-p2.spec.ts
Fixes # https://zube.io/rancher/rancher/c/64071
This pr disables server-url test and adds fallback to reset server-url via API call in case the test fails to prevent existing AWS/Azure provisioning tests from failing in the Jenkins pipeline. In the server-url test, the server-url is updated to a bogus url and because of a bug, the test fails to reset the server-url to its original state.
Fix includes:
- disabling the failing server-url test until the bug is fixed https://github.com/rancher/dashboard/issues/10613.
- putting in a fail-safe in an after() hook just in case the test fails in the future to prevent this from happening again.
> automation: fix provisioning tests by disabling global-settings -> server-url test and adding fallback 

- shell/components/PromptModal.vue
- shell/components/ResourceCancelModal.vue
- shell/dialog/RotateCertificatesDialog.vue
This updates the styles for `ResourceCancelModal.vue` so that the modal will render as it did before #10591 merged. 
Fixes #10648
- Use `customClass` prop for `app-modal`
- Remove `v--modal-box` styles - a quick review reveals that these styles weren't being applied to the original modal either, so they are not needed
- Keep styles `.header`, `.body`, and `.footer`
This can be tested as a part of any "Edit as YAML" form. For example:
1. Navigate to Local Cluster => Storage => ConfigMaps
2. Click on "Create"
3. Click on "Edit as YAML"
4. Click on "Back to Form"
Observe the design of the modal, it should match the original design from v2.8.x
> Fix styles for `ResourceCancelModal`

- shell/components/form/LabeledSelect.vue
- shell/components/form/__tests__/LabeledSelect.test.ts
- shell/edit/provisioning.cattle.io.cluster/tabs/Basics.vue
Fixes #9668 
This PR re-introduces https://github.com/rancher/dashboard/issues/8149 
This PR removes code added to make LabeledSelect option labels more dynamic because it causes a substantial performance hit. I have attempted a partial fix in the past; see https://github.com/rancher/dashboard/pull/9689 for details. Previously I was reluctant to re-introduce #8149 so I improved labeledselect performance only when the options provided are strings, not objects...this solution turns out to be inadequate, as we have some more complex dropdown options in EC2 and EKS
As this PR removes code added to fix #8133 I have added an alternative fix, supplying that LabeledSelect with a key which will force it to re-render if the option label changes. Though it was added for the psa dropdown, it is …
> Improve LabeledSelect performance

- shell/initialize/index.js
- shell/initialize/plugins.js
- shell/plugins/ember-cookie.js
One of a series of changes to simplify the bootstrapping and authentication code.
> Factoring plugin installation out of index.js.

- shell/assets/translations/en-us.yaml
- shell/pages/c/_cluster/explorer/__tests__/index.test.ts
- shell/pages/c/_cluster/explorer/index.vue
Fixes https://github.com/rancher/dashboard/issues/10517
We are adding 2 new boxes to show the status of `fleet` and `cattle` deployments in the Cluster's dashboard page.
- `cattle` box will be visible only for downstream clusters
- Added new `warning` status to show when the agents have replicas updating in progress.
- Added new `unavailable` status to show a spinner icon until deployments data are available; this will avoid the pop-up effect of the whole agent's boxes.
- When `cattle` is scaled up or down, the UI loses the web sockets connection; the cattle box will show an error status in this case, but we need to confirm that this is a normal behavior or is a backend bug.
Fleet:
- Go to either local or downstream cluster -> Dashboard page
- Open a new browser window and Go to Workloads …
> Add Fleet and Cattle health boxes in Dashboard Page

- shell/components/AppModal.vue
- shell/components/__tests__/AppModal.test.ts
- shell/dialog/AddCustomBadgeDialog.vue
This addresses a few issues with the `AppModal` component that were detailed in #10661.
Fixes #10661
- Fixes an error with the width validator when a valid string is provided
- Specifies `overflow: auto` on the modal container so that scrollbars are not present in chrome/brave
- Adjusts the bottom margin of the title in `shell/dialog/AddCustomBadgeDialog.vue` so that it appears as properly centered
Centering of the title was not a regression introduced in #9537, but is a result of the design of the card component. More details can be found here https://github.com/rancher/dashboard/issues/10661#issuecomment-2010031758
See the issue for more info.
> Update modal styles

- cypress/e2e/po/side-bars/product-side-nav.po.ts
- cypress/e2e/tests/navigation/side-nav/product-side-nav.spec.ts
- shell/components/nav/Group.vue
Fixes #10558
The link element had a padding around that wasn't clickable. Making the link the same size as the tab header fixed the problem.
I wasn't able to create a test that was failing before the change, so manual testing is required.
Some tests in cypress/e2e/tests/navigation/side-nav/product-side-nav.spec.ts were disabled pending #5966, which is now closed, so i enabled them back.
1. Go Local -> Workloads
2. Click on "Jobs" subgroup
3. Click back on "Workloads" below from the text
4. Workloads page should be opened
N/A
https://github.com/rancher/dashboard/assets/133266076/d0154e67-9d22-45f0-8929-06cd71f67d7c
> [FIX] Fixed clicking on a group header outside of text not working

- shell/components/formatter/ImagePercentageBar.vue
- shell/initialize/App.js
Fixes https://github.com/rancher/dashboard/issues/10681
We are disabling nuxt warning messages for Harvester clusters / fixing image's error message.
- Virtualization Management / Dashboard -> console
- Virtualization Management / Images -> console
> Fix warning messages in Harvester embedded view

- package.json
- shell/initialize/plugins.js
- shell/package.json
- shell/plugins/vue-js-modal.js
- yarn.lock
Fixes https://github.com/rancher/dashboard/issues/10675
Modal dialogs in Harvester embedded-mode require vue-js-modal package.
> Revert vue-js-modal removal as required in Harvester

- shell/store/index.js
Fixes https://github.com/rancher/dashboard/issues/10647
This fix is required when using Rancher v2.9-head with older Harvester versions (< v1.3.1)
The `getters` param is always null in Harvester store, since it is not pushing the `getters` param:
```
commit('updateNamespaces', {
filters: [],
all:     getters.filterNamespace(),
// getters
}, { root: true });
```
and this is causing the `undefined` error in the Rancher dashboard.
> Fix `updateNamespaces` to preserve compatibility with old Harvester versions

- cypress/e2e/tests/navigation/side-nav/product-side-nav.spec.ts
Fixes #10558
Needed to wait for the page to load before getting the URL.
> [FIX] Fixed broken test in product-side-nav.spec

- shell/plugins/dashboard-store/__tests__/mutations.test.ts
- shell/plugins/dashboard-store/actions.js
- shell/plugins/dashboard-store/mutations.js
- shell/plugins/steve/__tests__/mutations.test.ts
- shell/plugins/steve/__tests__/utils/mutation.test.helpers.ts
- shell/plugins/steve/mutations.js
Fixes #10479
- Ensure loadDataPage --> loadAdd updates pod by namespace cache
- Also address a possible race condition made more likely by change
- The bug can be tricky to reproduce, as the initial fetch of 100 pods which calls loadAll populates cache ok... it's the subsequent loadDataPage results which won't. So the deployment detail page needs to show pods that weren't fetched in the initial 100 pods. There's a tweak in code to make this easier to reproduce (by dropping 100 pod limit down), see issue description
As per issue (ensure exact env setup or hack using instructions in Additional context)
General incremental loading mechanism
> Ensure pods loaded by incremental loadDataPage make it to the pod by namespace cache

- cypress/e2e/po/lists/management.cattle.io.feature.po.ts
- cypress/e2e/po/pages/global-settings/feature-flags.po.ts
- cypress/e2e/po/pages/page.po.ts
- cypress/e2e/po/side-bars/product-side-nav.po.ts
- cypress/e2e/tests/pages/charts/monitoring-istio.spec.ts
- cypress/e2e/tests/pages/explorer/legacy/projects.spec.ts
- cypress/e2e/tests/pages/manager/cluster-manager.spec.ts
- shell/assets/translations/en-us.yaml
- shell/components/nav/Type.vue
- shell/config/product/legacy.js
- shell/store/type-map.js
Fixes #10595
- fixed scenario exposed by the project virtual type where call to allTypes ruled out all virt / spoofed types if basic mode has an invalid entry (!groupForBasicType)
- however also removed the project virtual type. the nav item comes from `Project` group specified in `basicTypes` call)
- fixed a few things around the project group
- add label for project group
- explicitly set project group root of app
- fixed display of namespace icon for a menu item if there are no counts
Also
- fixed some TS errors in test
- fixed typos in tests
- Contains e2e test that navigates to legacy --> project --> config maps
- virtual / spoof side nav menu items, like those in Global Settings
> Fix Legacy / Project group

- shell/plugins/plugin.js
Output the actual error that caused the plugin to not load. This will help debugging a lot in user land
- track the reason the promise failed
> Better logging for failed plugin loads

- cypress/e2e/tests/navigation/side-nav/main-side-menu.spec.ts
- shell/config/product/manager.js
Fixes #10631
Moves Cluster Management to the top of the Global Apps section in the side bar and adds an e2e test to check this.
Current order in the app bar is:
With the change in this PR, these are swapped, so that Cluster Management is at the top.
> Move cluster management to top of global apps

- shell/components/nav/TopLevelMenu.vue
Fixes https://github.com/rancher/dashboard/issues/10561
`getMatchedComponents` function throws a warning message when a route is not defined in `router.js` file.
We are removing getMatchedComponent, which is deprecated as well: https://router.vuejs.org/guide/migration/#Removal-of-router-getMatchedComponents-
before
after
> Remove Vue `getMatchedComponents`

- cypress.config.ts
- cypress/e2e/po/pages/rancher-setup-configure.po.ts
- cypress/e2e/po/pages/rancher-setup-login.po.ts
- cypress/e2e/tests/pages/charts/monitoring-istio.spec.ts
- cypress/e2e/tests/pages/generic/home.spec.ts
- cypress/e2e/tests/pages/generic/login.spec.ts
- cypress/e2e/tests/pages/global-settings/banners.spec.ts
- cypress/e2e/tests/setup/rancher-setup.spec.ts
- cypress/support/utils/settings-utils.ts
- shell/components/FixedBanner.vue
- shell/components/__tests__/FixedBanner.test.ts
- shell/config/types.js
- shell/middleware/authenticated.js
- shell/middleware/unauthenticated.js
- shell/mixins/brand.js
- shell/pages/auth/login.vue
- shell/pages/auth/setup.vue
- shell/plugins/dashboard-store/actions.js
- shell/plugins/dashboard-store/getters.js
- shell/store/auth.js
- shell/utils/settings.ts
Fixes #9304
1. Concurrent calls to findAll would always result in two requests
- when findAll runs we cache running results with key JSON.stringify(headers) + method + opt.url
- if a request is made with a matching key we return the promise associated with the first request (thus negating a second request)
- when mgmt settings were fetched with a hardcoded url ... url contains singular setting
- when mgmt settings are fetched without hardcoded url ... url contains plural settings
- therefore the second call to findAll was not using the cached promise from the first call.... resulting in a second request
After the above is fixed, noticed two other issues
2. When making a request we checked the response headers for a specific auth header which we pushed to the auth store.... however the …
> Remove duplicate calls to mgmt settings on fresh load

- shell/components/CruResource.vue
- shell/components/__tests__/CruResource.test.ts
- shell/components/form/NameNsDescription.vue
- shell/config/store.js
- shell/edit/__tests__/management.cattle.io.clusterroletemplatebinding.test.ts
- shell/edit/__tests__/management.cattle.io.setting.test.ts
- shell/store/cru-resource.ts
This replaces the pattern of `shell/components/form/NameNsDescription.vue` invoking its parent to emit the `createNamespace` event with a simple store. This store is only used to share data with `CruResource.vue` and is used to determine if a namespace should be created.  
I opted to use a store in this case in an effort to write something that will be Vue3 compatible without the requirement of additional libraries. An alternative would be to utilize an event bus, but that would require the addition of a dependency like mitt[^1] to remain Vue3 compatible[^2].
[^1]: https://www.npmjs.com/package/mitt
[^2]: https://v3-migration.vuejs.org/breaking-changes/events-api.html#migration-strategy
I also experimented with dynamically registering[^3] this store only when it was required by …
> Replace `createNamespace` pattern with a simple store for sharing data

- shell/components/TabTitle.vue
Watches and computed props didn't update based on the content of slots.
The render method would still be called when the slot was updated so I moved the update to there. I also just use a method to compute the title because the value would get cached and not updated even if you accessed it more than once.
https://github.com/rancher/dashboard/issues/9822#issuecomment-1976814164
> Making sure tabTitle updates if the content of a slot updates

- pkg/aks/components/AksNodePool.vue
- pkg/aks/components/CruAks.vue
- pkg/aks/components/__tests__/AksNodePool.test.ts
- pkg/aks/components/__tests__/CruAks.test.ts
- pkg/aks/l10n/en-us.yaml
- pkg/aks/util/__tests__/validators.test.ts
- pkg/aks/util/validators.ts
Fixes #10462 #9433 
This PR fixes the validation used for AKS node and resource group names. 
The previous regular expression used to validate resource group characters caused catastrophic backtracking https://www.regular-expressions.info/catastrophic.html
* resource group names containing invalid characters
* node pool names containing invalid characters/excessive length
> Fix AKS node pool and node resource group validation

- shell/assets/translations/en-us.yaml
- shell/components/SideNav.vue
- shell/components/nav/Header.vue
- shell/components/templates/default.vue
- shell/plugins/dashboard-store/actions.js
- shell/store/index.js
- shell/store/type-map.js
Fixes #10407
This PR improves the performance when switching between child products of explorer - to test, in a downstraam cluster, install Longhorn and NeuVector from Cluster Tools - these are two simple products that sit within the Explorer product that we can use for testing, as the time taken to switch between them represents the overhead in our nav code paths.
With this PR, switching between them is much faster as the 'rootProduct' (explorer) does not change, even though the current (child) product does - this means less gets re-evaluated.
Before this change, it takes in the order of ~250ms to switch between Longhorn and NeuVector - this is primarily because our nav code believes the product has changed, so we have to call `getGroups` - with this PR, the top-level/root product does …
> Add root product to improve performance of nav change within inExplorer products 

- .github/workflows/scripts/add-issue-labels.js
- there's some white space changes as well, auto-updated on save
- fix is `labels.filter((label) => label.name.indexOf('[zube]:') === 0)` to `labels.filter((label) => label.indexOf('[zube]:') === 0)`
> Fix undefined in add-issues-labels action's script

- shell/models/catalog.cattle.io.uiplugin.js
- shell/pages/c/_cluster/uiplugins/index.vue
This expands the cases of using the cache state to determine if a plugin has been initialized or not; an initialized plugin can either be in a "cached" or "disabled" state.
Fixes #10639
- This also removes the getters for `willBeCached()` and `isCached()` as they are unused by Dashboard with this change
- `noCache` can be manually set in the CRD so this isn't a good indicator for determining plugin initialization
- Managing plugins should remain unchanged
- Installing plugins should succeed when cache is disabled.
> Add new cache states to determine plugin init

- shell/components/__tests__/EtcdInfoBanner.test.ts
This PR adds a unit test for this issue: https://github.com/rancher/dashboard/issues/10172, PR: https://github.com/rancher/dashboard/pull/10173
This should avoid that issue to be manually tested.
> Add unit tests for etcd banner fix

- shell/edit/networking.k8s.io.networkpolicy/PolicyRuleTarget.vue
- shell/edit/networking.k8s.io.networkpolicy/__tests__/PolicyRuleTarget.spec.ts
Fixes #10641 
In `PolicyRuleTarget.vue` the matching messages we display rely on different props including `allNamespaces` which was missing in the `watch` block.
The component was failing to re-render after updating the `allNamespaces` prop.
n/a
n/a
https://github.com/rancher/dashboard/assets/135728925/626f8de3-9803-4d10-9b48-b3232076d390
> Fix re-render issue with the matching message in PolicyRuleTarget

- shell/pages/c/_cluster/explorer/__tests__/index.test.ts
- shell/pages/c/_cluster/explorer/index.vue
Fixes https://github.com/rancher/dashboard/issues/10705
- For the local clusters, there is no fleet-agent - we are now checking the `cattle-fleet-system/fleet-controller` deployment
- Adding 400 errors handling 
- Cluster's dashboard page -> health boxes
> Fix fleet health-box in local cluster

- cypress/e2e/tests/navigation/side-nav/main-side-menu.spec.ts
- shell/assets/translations/en-us.yaml
- shell/components/nav/TopLevelMenu.vue
Fixes #10706 
- add missing translation to hardcoded string and adjust of copy 
- change key shortcut to `ALT` key only 
- remove lodash usage
- adjust e2e test
**Note:** Pressing `COMMAND + F5` opens a system-like panel in mac OS, which might lead to the "icon" getting stuck and visible. Pressing `ALT` multiple times seems to get it unstuck. We cannot prevent system key combinations from possible overrides and it's side-effects, imo. If there's additional info that might change this, let me know.
https://github.com/rancher/dashboard/assets/97888974/0cb12512-db5f-455d-a802-26003ae52e25
- Bring up a second cluster in ready state (meaning you can navigate to cluster explorer)
- In that cluster, go to `project/namespaces`
- press the key `alt`
- while pressing the key, make sure the icons …
> Tweaks to new cluster switch feature

- pkg/aks/l10n/en-us.yaml
- pkg/aks/util/__tests__/validators.test.ts
- pkg/aks/util/validators.ts
Fixes #7163 
This PR fixes validation for the Private DNS Zone input field - see comments in 7163 for details. I made the validation regex pretty permissive about subscription id and resource group name because I couldn't find clear documentation on how to validate them more precisely.
1. entering invalid private DNS zone id values should disable the 'create' button
2. private dns zone id values that pass ui validation should pass BE validation
none - changes are isolated to privateDNSZone validation
> Fix AKS private DNS zone validation

- cypress/e2e/po/components/network-tab.po.ts
- cypress/e2e/po/edit/provisioning.cattle.io.cluster/create/cluster-create-rke2-custom.po.ts
- cypress/e2e/tests/pages/manager/cluster-manager.spec.ts
- shell/edit/provisioning.cattle.io.cluster/tabs/networking/index.vue
Fixes #10159 
- Add automated test for #10159
> 10159: add e2e test

- cypress/e2e/tests/navigation/side-nav/main-side-menu.spec.ts
- shell/assets/translations/en-us.yaml
Fixes #10192 
- Based on https://github.com/rancher/dashboard/issues/10192#issuecomment-2036594710, updated update documentation link for cluster edit banner
- updated e2e test in conformity
- Have an RKE2 cluster provisioned and ready, then go `Edit Config`
- On the banner on the top of the page, click on `documentation` and make sure link is the correct one `https://ranchermanager.docs.rancher.com/v2.8/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/rke1-vs-rke2-differences#cluster-api`
> update documentation link for cluster edit banner

- cypress/e2e/tests/pages/explorer/cluster-dashboard.spec.ts
- shell/pages/c/_cluster/explorer/EventsTable.vue
Fixes https://github.com/rancher/dashboard/issues/10265
The Events tab inside Cluster Dashboard page - `/c/local/explorer#cluster-events` - fetches and saves the events as a new `fetchedType` into the store.
We are removing the event type from the store before the Events tab is unmounted, so the events can be fetched again when navigating to Cluster/Events page.
- The same result can be achieved by using a custom list component for the Cluster/Events page; it seems that, using a new component and calling the `$fetchType` after the component is rendered, it fetches again the event resource. This is likely caused by an async behavior inside `resource-fetch.js` mixin and needs further investigations.
- it is not possible to call `cluster/forgetType` directly in the `beforeDestroy` because it …
> Remove `event` data from store when leaving Events tab

- cypress/e2e/po/detail/provisioning.cattle.io.cluster/cluster-detail.po.ts
- cypress/e2e/tests/pages/manager/cluster-manager.spec.ts
- cypress/jenkins/Dockerfile.ci
- cypress/jenkins/Jenkinsfile
- cypress/jenkins/cypress.sh
- cypress/jenkins/init.sh
Fixes #
Adds support for using a real cluster during imported cluster tests.
Updating the `init.sh` script to use a k3s cluster package to create a single node cluster. The information is then stored in the `corral` configuration for later use.
After creating the cluster[ the updates to the corral package](https://github.com/rancherlabs/corral-packages/pull/44) will allow the imported cluster create test to use it. 
Both PRs depend on each other.
https://github.com/rancher/dashboard/pull/10726
Jenkins pipeline
> [Automation] - Adding real cluster support for Imported Generic tests

- cypress/e2e/po/components/header.po.ts
- cypress/e2e/po/components/import-yaml.po.ts
- cypress/e2e/po/components/sortable-table.po.ts
- cypress/e2e/tests/pages/explorer/cluster-dashboard.spec.ts
- shell/components/Import.vue
- shell/components/SortableTable/index.vue
- shell/components/nav/Header.vue
Fixes #10656 
- remove state col and subrows from import YAML action success screen 
- prevent sub-row form showing state description
- add tests
- got header -> Import a YAML -> fill out the YAML editor and hit save (should not show state col)
https://github.com/rancher/dashboard/assets/97888974/8d9e5972-ed8e-4182-aa17-6fd1da55c28b
> Don't show state column on import yaml dialog

- shell/pages/c/_cluster/explorer/__tests__/index.test.ts
- shell/pages/c/_cluster/explorer/index.vue
Fixes https://github.com/rancher/dashboard/issues/10738
We are adding the fleet's StatefulSet in agent status calculation, for downstream clusters.
- local clusters:
- using both StatefulSet and Deployment
- rke2 downstream clusters:
- using StatefulSet since the deployment does not exist.
- cluster's dashboard -> healthboxes.
See https://github.com/rancher/dashboard/pull/10614 description.
- there is a known issue when scaling/redeploying fleet StatefulSet; it can be done using kubectl, see https://github.com/rancher/dashboard/issues/10762
> Fetch `statefulset` resource to calculate fleet agent status

- shell/utils/__tests__/create-yaml.test.ts
- shell/utils/create-yaml.js
This defaults to unlimited line width when dumping yaml blocks. This should resolve issues where newline characters are inserted into yaml while using the form editor, breaking previously functional manifests.
Fixes #10589 
I don't see any situation where it would be valid to insert newline characters at the default of 80 characters. If we do want this behavior, that would be the exception and we can supply proper options for a specific field we want to target.
An alternative approach would be to specify a `lineWidth` for individual fields like `metadata.annotations`, but I thought this too specific an approach, and leaves us in a situation where future tickets will open for properties that we haven't considered.
Configmaps - See the linked issues for detailed reproduction steps.
- …
> Default to unlimited line width when dumping yaml blocks

- cypress/e2e/blueprints/user_preferences/group_by.ts
- cypress/e2e/tests/pages/explorer/namespace-picker.spec.ts
- cypress/e2e/tests/pages/explorer/node-list.spec.ts
- cypress/e2e/tests/pages/fleet/gitrepo.spec.ts
- cypress/e2e/tests/pages/generic/home.spec.ts
- cypress/e2e/tests/pages/manager/pod-security-admissions.spec.ts
- cypress/e2e/tests/pages/manager/repositories.spec.ts
- cypress/globals.d.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1278
- address failing tests
- add missing tags to some of our older tests (created before `check-e2e-tags` test job)
- clean up code
> automation: address failing/flaky tests

- cypress/e2e/po/edit/auth/azuread.po.ts
- cypress/e2e/po/pages/users-and-auth/authProvider.po.ts
- cypress/e2e/tests/pages/users-and-auth/azuread.spec.ts
- shell/assets/translations/en-us.yaml
- shell/components/auth/AuthBanner.vue
- shell/edit/auth/__tests__/azuread.test.ts
- shell/edit/auth/azuread.vue
Fixes rancher/dashboard#10771
Added validation to AzureAD configuration 
- Fixed validation for AzureAD
- Replaced labels with translations
Had to use fvExtraRules() for validation since this.model() is used to set the values and it is undefined when data() is run, so default validation would be using this.value instead, which is incorrect.
- Go to Users & Authentication -> Auth provider ->AzureAD
- 'Enable' button should be disabled before any information is entered
- 'Enable' button should be enabled once Tenant ID, Application ID, and Application Secret are populated
- Switch 'Endpoints' to 'Custom'
- 'Enable' button should be disabled before any information is entered
- 'Enable' button should be enabled once Endpoint, Graph Endpoint, Token Endpoint, and Auth Endpoint are populated
- …
> [FEAT] Added validation to AzureAD

- cypress/e2e/po/components/password.po.ts
- cypress/e2e/po/pages/login-page.po.ts
- cypress/e2e/tests/pages/global-settings/branding.spec.ts
- shell/mixins/brand.js
Fixes #10788 
- update `brand` mixin to handle login scenario for branding application of `primary` color and `link` color 
- add e2e tests to cover possible regression scenario
Needed to convert the `globalSettings` variable in a getter-based in order to get the settings information from the network request done last to settings, which is done from the `login` view. Had to convert all the watchers to `immediate: true` in order to pick up changes
- This needs a backend version `2.9-head` with date 12th of April 2024 or later, due to changes done in `rancher/rancher` https://github.com/rancher/rancher/pull/45108
- Go to `Global Settings` -> `branding` and change `primary` color and `link` color to custom ones
- Log out of Rancher and check that the branding changes are applied
- Do a …
>  Rancher UI branding customisation is not persistent on the login screen

- cypress/e2e/tests/pages/generic/home.spec.ts
- shell/assets/styles/fonts/_icons.scss
- shell/assets/translations/en-us.yaml
- shell/components/SortableTable/THead.vue
- shell/config/labels-annotations.js
- shell/config/product/manager.js
- shell/list/provisioning.cattle.io.cluster.vue
- shell/models/provisioning.cattle.io.cluster.js
- shell/pages/c/_cluster/explorer/__tests__/index.test.ts
- shell/pages/c/_cluster/explorer/index.vue
- shell/pages/home.vue
Fixes https://github.com/rancher/dashboard/issues/10382
Adding cluster `architecture` info in various places:
- Homepage, Clusters table
- adding 'Distro' sub-label to Provider column.
- adding 'Architecture' sub-label to Kubernetes Version column.
- adding architecture info in Kubernetes Version cells
- Cluster Management, Clusters table
- same
- Cluster Dashboard, for each cluster
- adding the new 'Architecture' on top of the page.
- `SortableTable` component: fixed css -> header's alignment for tables containing columns with `subLabel`.
- Clusters tables
- SortableTable component
Homepage
Cluster Management
Cluster Dashboard (local)
Tooltips
- mixed
- mixed, one is unknown
- all are unknown
> Add cluster architecture info

- cypress/e2e/tests/navigation/side-nav/main-side-menu.spec.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1240
> automation: add check for cluster name in tooltip

- cypress.config.ts
- cypress/e2e/po/edit/provisioning.cattle.io.cluster/create/cluster-create.po.ts
- cypress/e2e/tests/pages/manager/cluster-manager.spec.ts
- cypress/jenkins/init.sh
Fixes https://github.com/rancher/qa-tasks/issues/749
Similar to the imported cluster tests updates to use real nodes for clusters. This adds a node to use on Custom Cluster provisioning. Using an instance to later register it as an all roles node for a cluster.
- Adds a node
- Provisioning with the `can create cluster` under `RKE2 Custom`
- Remote connects with ssh and runs the registration command.
- Wait until the cluster become Active
Add tags to only run on Jenkins
Jenkins pipelines
Jenkins pipelines
- [ x ] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [ x ] The PR has a Milestone 
- [ x ] The PR template has been filled out
- [ x ] The PR has been self reviewed 
- [ x ] The PR has a reviewer assigned
- [ x ] The PR has automated tests or …
> [Automation] - Adding support for RKE2 custom cluster provisioning

- cypress.config.ts
- cypress/e2e/tests/pages/explorer/cluster-dashboard.spec.ts
- cypress/e2e/tests/pages/explorer/namespace-picker.spec.ts
- cypress/e2e/tests/pages/fleet/gitrepo.spec.ts
Fixes #
Add intercept/waits to address 
- [namespace-picker failure](https://github.com/rancher/dashboard/actions/runs/8650616959/job/23720789908#step:9:223) in GA 
- [git repo failure](https://jenkins.int.rancher.io/job/rancher_qa/job/ui-automation-job-yonas/45/testReport/junit/Git%20Repo/Create/Should_be_able_to_create_a_git_repo/) in Jenkins
> automation: part 2 of fixing flaky tests

- pkg/rancher-components/src/components/Card/Card.vue
Fixes https://github.com/rancher/dashboard/issues/10784
> Fix AddProjectMemberDialog, remove scroll artifacts

- .github/workflows/scripts/pr-gh-project.js
- .github/workflows/scripts/request.js
This PR updates the GH Project automation.
- Adds the related issue(s) to the project board if not already there
- Sets the status of the related issue(s)
> GitHub project automation - add issue to board and change status

- cypress/e2e/tests/pages/charts/rancher-backup.spec.ts
- shell/chart/rancher-backup/index.vue
Fixes #10765 
The current logic pre-selects the storage class if a default storage class exists(i.e. it has `annotations: {'storageclass.kubernetes.io/is-default-class': 'true'}`) and no storage class is already set. Two scenarios needed to be addressed:
1. You've saved a storage class different from the default one and are currently viewing it
2. During editing, you've selected a storage class and switched tabs
In the summary^.
n/a
https://github.com/rancher/dashboard/assets/135728925/a31b5df5-50c4-46c5-ba48-fb7e7666e9c7
> Fix storage class not being selected properly

- .github/workflows/scripts/pr-gh-project.js
Fixes a small bug with the GH Project script - to handle the case where an issue is not in any project boards.
> Bug fix for adding issue to the GH Project board

- shell/models/provisioning.cattle.io.cluster.js
Fixes #10831
When a new cluster is provisioning, the architecture column should display dash or empty value
Cluster Management tab
> Fix architecture label for provisioning clusters

- shell/config/table-headers.js
This ensures that the Last Login, Disabled In, & Deleted In columns in the Users table are sorted by their epoch time values instead of the string representation. 
Fixes #10821
- Updates the sort key for `userLastLogin`, `userDisabledIn`, & `userDeletedIn`
- Sorting of the users table
> Sort by raw value instead of string value

- shell/components/Certificates.vue
Related to https://github.com/rancher/dashboard/issues/10025 / https://github.com/rancher/dashboard/pull/10024
- The cluster dashboard page contains tabs
- Tabs contain lists
- One tab shows lists of events (non-namespaced resource), the other certificates (namespaced resource)
- By default lists will filter rows of namespaced resources by the namespaces selected in the header filter
- This works fine for root lists, and is ignored for lists with in the detail page of resources (as they're showing resources associated with the primary resource)
- For lists that are in overview pages though we don't have a pattern
- For this context and use case it feels discombobulating to filter by namespace
- navigating to the local cluster and viewing cert list will by default not show any due to the …
> Make cluster dashboard certificates list ns filter agnostic

- cypress/e2e/po/components/ember/ember-textarea.po.ts
- cypress/e2e/po/edit/provisioning.cattle.io.cluster/create/cluster-create-rke1-amazonec2.po.ts
- cypress/e2e/tests/pages/manager/cluster-provisioning-amazon-ec2-rke1.spec.ts
- shell/components/nav/TopLevelMenu.vue
- shell/components/nav/__tests__/TopLevelMenu.test.ts
- shell/pages/home.vue
- shell/plugins/steve/hybrid-class.js
Fixes #10441 (based on reopening from QA by comment https://github.com/rancher/dashboard/issues/10441#issuecomment-2047009103)
- add `mgmt` cluster description to `prov` cluster description as fallback in home cluster list and main side nav clusters
Descriptions were not appearing because both lists are based on CAPI clusters and the ones mentioned by QA are MGMT clusters. Added the MGMT clusters to the home cluster list and main side nav clusters
- Edit `local` cluster and add a description
- Provision a AKS, EKS or GKE cluster with a description
- make sure description appears in the home page cluster list and main side nav clusters
> add mgmt cluster description to prov cluster description as fallback in home cluster list and main side nav clusters

- shell/components/KeyValueView.vue
- shell/components/form/ArrayList.vue
- shell/components/form/KeyValue.vue
Fixes #10829
As mentioned in the issue, this is a safe migration to Vue3 with limited use cases.
Using computed values based on props using i18n default values should be sufficient to not break anywhere.
A first attempt to use the global variable `t` has been carried out, unfortunately, it's not exposed in a prop scope and cannot be used.
Finally, as you can see by the commits and logs, it's mandatory to set a default empty value regardless, to not break existing logic.
> Replace default values of props using global variables with computed case

- pkg/harvester-manager/l10n/en-us.yaml
- pkg/harvester-manager/machine-config/harvester.vue
- shell/components/form/ArrayListSelect.vue
Fixes https://github.com/rancher/dashboard/issues/10593
We are adding the possibility to select a list of vGpus to assign to Harvester clusters. The list of available vGpus needs to be enabled in Harvester first.
It will also fix a bug in ArrayListSelect component when emitting new input event.
harvester.vue component
> [2.8]Add vGpus field in Harvester clusters provision

- pkg/harvester-manager/l10n/en-us.yaml
- pkg/harvester-manager/machine-config/harvester.vue
- shell/components/form/ArrayListSelect.vue
Fixes https://github.com/rancher/dashboard/issues/10588
We are adding the possibility to select a list of `vGpus` to assign to Harvester clusters. The list of available vGpus needs to be enabled in Harvester first.
It will also fix a bug in ArrayListSelect component when emitting new `input` event.
`harvester.vue` component
> Add vGpus field in Harvester clusters provision

- scripts/e2e-docker-start
Testing pinning backend image to older version.
Note, done in file rather than via a var on the repository, so it is very clear what version is being used and so that to change it, we have to use a PR, which will itself go through the gates.
> Pin rancher backend image version for e2e tests

- .github/workflows/scripts/add-issue-labels.js
As part of migration away from Zube, this updates the labelling GH Action to no longer add the Zube 'To Triage' label to new issues.
> Remove zube labelling of new issues

- cypress/e2e/po/components/ember/ember-modal-add-node-template-azure.po.ts
- cypress/e2e/po/detail/provisioning.cattle.io.cluster/cluster-detail-rke1-azure.po.ts
- cypress/e2e/po/edit/provisioning.cattle.io.cluster/create/cluster-create-rke1-azure.po.ts
- cypress/e2e/tests/pages/manager/cluster-provisioning-amazon-ec2-rke1.spec.ts
- cypress/e2e/tests/pages/manager/cluster-provisioning-azure-rke1.spec.ts
- cypress/globals.d.ts
- cypress/support/commands/rancher-api-commands.ts
Fixes #
https://github.com/rancher/qa-tasks/issues/1234
bugs that cause this test to fail:
- https://github.com/rancher/dashboard/issues/10640 for admin and standard-user
- https://github.com/rancher/dashboard/issues/10683 for standard user
> automation: rke1 cluster prov azure

- shell/config/product/legacy.js
Part of these two 'epic' backports:
https://github.com/rancher/dashboard/issues/10276
https://github.com/rancher/dashboard/issues/10277
Backport of https://github.com/rancher/dashboard/issues/10489
The `feature-flag.spec.ts` does not exist in the 2.8 release branch https://github.com/rancher/dashboard/tree/release-2.8/cypress/e2e/tests/pages/global-settings. So I omitted the commit from the original pr which added those tests.
> [backport v2.8.x] Remove v1 tools/pages under the legacy navigation item

- shell/assets/translations/en-us.yaml
- shell/models/management.cattle.io.user.js
This adds the user last login, disabled in, & deleted in values to the user detail page. 
Fixes #10820
- Adds new fields to the DetailTop of users detail page
Adding a customized suffix via the `formatterOpts` feels a little clunky, but it's sufficient for customizing the display format so that we can more closely match the design. Alternatives probably include building a new formatter, but this is too much given what we are trying to achieve.
- Users Details Page
- Users Details Page
> Display user dates in the resource detail subheader

- shell/pages/auth/login.vue
- shell/pages/auth/logout.vue
- shell/pages/auth/setup.vue
- shell/pages/c/_cluster/auth/config/index.vue
- shell/pages/c/_cluster/auth/roles/index.vue
Migrate the usage of asyncData to fetch. I'll remove the nuxt implementation of asyncData in a separate pr (https://github.com/rancher/dashboard/pull/10896/commits/3cdf3eceb4468eb7e4433cfcab07c1ff7d2569cd).
This will give us one less thing that we have to consider while working on Vue3. After the migration we will then remove all of the initialization code. 
The affected pages are, login, logout, setup, auth/config, and auth/roles.
All of these pages appear to be exercised through existing e2e tests.
> Migrate the usage of asyncData to fetch

- cypress/e2e/po/pages/page.po.ts
- cypress/e2e/tests/pages/extensions/extensions.spec.ts
- shell/assets/translations/en-us.yaml
- shell/config/uiplugins.js
- shell/core/plugins.js
- shell/pages/c/_cluster/uiplugins/InstallDialog.vue
- shell/plugins/plugin.js
- shell/store/index.js
Adding noAuth extension loading. This will allow specific extensions (such as extensions locale or login page modifications) to load even if the user isn't authenticated.
Fixes #9814
- When extensions are installed
- Extensions before a user logs in
- Extensions after a user logs in
- Extensions after a user logs out
- A cluster with 2 versions of harvester and navigating between the two separate instances
- When extensions are installed
- Extensions before a user logs in
- Extensions after a user logs in
- Extensions after a user logs out
- A cluster with 2 versions of harvester and navigating between the two separate instances
To test you can used the extensions in this repo https://github.com/rancher/ui-plugin-charts.
The uk-locale extension is one that can be loaded without …
> Adding noAuth extension loading

- shell/components/ResourceList/index.vue
- shell/initialize/App.js
- shell/initialize/client.js
- shell/pages/c/_cluster/auth/config/index.vue
- shell/utils/nuxt.js
Removing asyncData references and unused hot module reload code
While removing references to asyncData I noticed that the HMR code used for calling both asyncData and fetch were not actually being used on code changes. This lead me to deleting the HMR code as well. We can split this PR up into two separate if we deem necessary.
asyncData has already been removed so that area shouldn't be affected. We should verify that HMR still works for usages of fetch.
https://github.com/rancher/dashboard/assets/55104481/3c6ce97d-e9e4-47c4-b4c4-6448d809160c
> Remove async data implementation

- cypress/e2e/po/other-products/v2-monitoring.po.ts
- cypress/e2e/tests/pages/charts/v2-monitoring.spec.ts
- shell/edit/monitoring.coreos.com.prometheusrule/AlertingRule.vue
- shell/edit/monitoring.coreos.com.prometheusrule/GroupRules.vue
Fixes #9923 
- Add e2e test to prevent regression of issue #9923 where changing language to chinese should **NOT** affect value of severity in `PrometheusRules`
> add e2e test for issue 9923

- shell/edit/workload/mixins/workload.js
Fixes #10200
1. remove labels: `batch.kubernetes.io/controller-uid`, `batch.kubernetes.io/job-name`, `controller-uid`, `job-name`
2. remove annotation: `batch.kubernetes.io/job-tracking`
> fix(workload): clean up some labels,matchLabels and annotations when cloning a job

- cypress/e2e/tests/pages/generic/get-support.spec.ts
- cypress/e2e/tests/pages/generic/home.spec.ts
- cypress/support/utils/exception-utils.ts
Allow for specific exception to be thrown when visiting docs page
- For the two tests that go out to (roughly) https://ranchermanager.docs.rancher.com/v2.8/getting-started/overview tests fail given that page throws an error
- Solution is to ensure we don't the test if that target page has an error
See below for clean runs of test
- https://github.com/rancher/dashboard/actions/runs/8909502770/job/24467126788?pr=10928
- https://github.com/rancher/dashboard/actions/runs/8909502770/job/24467125339?pr=10928
> Allow for specific exception to be thrown when visiting docs page

- pkg/harvester-manager/machine-config/harvester.vue
- shell/assets/translations/en-us.yaml
- shell/components/form/ArrayListSelect.vue
- shell/components/form/Select.vue
Fixes https://github.com/rancher/dashboard/issues/10906
Adding a validation messsage in case the number of available vGpus are less then the number of cluster nodes.
- Create a new Harvester Cluster
- Assign a vGpus
- Add other nodes so their number is more then the allocatable vGPus
- Click on create button
> Validate allocatable vGPUs number in Harvester clusters creation

- pkg/harvester-manager/machine-config/harvester.vue
- shell/config/types.js
Fixes https://github.com/rancher/dashboard/issues/10905
The vGpu `name` should be same of vGpu id from Harvester device object.
- Create a new Harvester Cluster and assign vGpu device to it.
- Go to Harvester and select the cluster provisioning VM from Virtual Machines tab.
- Click on edit or view.
- Go to vGpus devices tab and check if the vGpu is assigned to the VM
> Assign vGpu id when assigning vGpus to Harvester Cluster

- pkg/harvester-manager/machine-config/harvester.vue
- shell/config/types.js
Fixes https://github.com/rancher/dashboard/issues/10914
See https://github.com/rancher/dashboard/pull/10913
> [2.8] Assign vGpu id when assigning vGpus to Harvester Cluster

- pkg/harvester-manager/machine-config/harvester.vue
Backporting issue: https://github.com/rancher/dashboard/issues/10908
Fixes #
This will fix a modeling issue. vGpu are select by type where we should use vGpu's id since there can be multiple vGpu profiles associated with the same vGpu type.
> [2.8] Select vGpus by id instead of vGpu type

- pkg/harvester-manager/machine-config/harvester.vue
Fixes https://github.com/rancher/dashboard/issues/10908
This will fix a modeling issue. vGpu are select by type where we should use vGpu's id since there can be multiple vGpu profiles associated with the same vGpu type.
Harvester cluster's creation
> Select vGpus by id instead of vGpu type

- cypress/e2e/po/pages/explorer/charts/tabs/grafana-tab.po.ts
- cypress/e2e/tests/pages/charts/monitoring-istio.spec.ts
- shell/chart/monitoring/grafana/index.vue
- shell/config/types.js
> Add e2e test to check default grafana storage size for statefulset type

- cypress/e2e/tests/pages/manager/cluster-provisioning-amazon-ec2-rke1.spec.ts
- cypress/e2e/tests/pages/manager/cluster-provisioning-azure-rke1.spec.ts
Fixes #
Address failing tests in Jenkins run 
[Provision Node driver RKE1 cluster with AWS.can delete a Amazon EC2 RKE1 cluster](https://jenkins.int.rancher.io/job/rancher_qa/job/ui-automation-job/854/testReport/(root)/Provision%20Node%20driver%20RKE1%20cluster%20with%20AWS/can_delete_a_Amazon_EC2_RKE1_cluster/)
[Provision Node driver RKE1 cluster with Azure."after all" hook: clean up for "can delete a Azure RKE1 cluster"](https://jenkins.int.rancher.io/job/rancher_qa/job/ui-automation-job/854/testReport/(root)/Provision%20Node%20driver%20RKE1%20cluster%20with%20Azure/_after_all__hook__clean_up_for__can_delete_a_Azure_RKE1_cluster_/)
> fix cluster prov tests

- shell/pages/auth/logout.vue
- shell/store/auth.js
This prevents us from redirecting multiple times when visiting the index on login 
Fixes #10926
There is still a case on the logout page that we need to be able to call logout even if the user hasn't been authenticated yet because the auth pages don't use the authenticated middleware.
This caused issues with the login page in a roundabout way. 
1. On the index page we authenticate the user so we can redirect them to the appropriate page if the user is logged in.
2. If a steve api fails due to authentication (happens if the user isn't logged in when visiting the index page) we immediately log the user out and redirect them to the login page.
3. Between the index page and steve api we would redirect multiple times and we now do a full page refresh on logout to shed all of the loaded …
> Only logout if the user is logged in

- cypress/e2e/tests/pages/explorer/namespace-picker.spec.ts
- cypress/e2e/tests/pages/manager/machine-deployments.spec.ts
- cypress/e2e/tests/pages/manager/machine-sets.spec.ts
- cypress/e2e/tests/pages/manager/machines.spec.ts
- cypress/e2e/tests/pages/manager/pod-security-admissions.spec.ts
- cypress/e2e/tests/pages/manager/repositories.spec.ts
Fixes #
- Most of these issues addressed in this PR are timing issues so adding `.waitForPage()` should help with flakiness 
- Pod Security Admissions and Repositories tests, it was discovered that duplicate entries were being created (when creating/cloning) so adding a page reload when multiple entries with the same name exist to resolve this.
> fix flaky tests - manager and explorer

- shell/initialize/plugins.js
- shell/plugins/global-formatters.js
- shell/plugins/portal-vue.js
- shell/plugins/portal.js
- shell/plugins/resize.js
- shell/plugins/shortkey.js
- shell/plugins/tooltip.js
- shell/plugins/v-select.js
- storybook/.storybook/preview.js
Fixes #10774 
Refactors:
- shell/plugins/resize.js
- shell/plugins/v-select.js
- shell/plugins/tooltip.js
- shell/plugins/shortkey.js
- shell/plugins/vue-js-modal.js - no Vue3
- shell/plugins/portal.js
- shell/plugins/portal-vue.js
- shell/plugins/global-formatters.js
The entire application is affected since these plugins are globally used.
The entire application is affected since these plugins are globally used.
> [INT] Refactored some of the plugins

- cypress/e2e/tests/pages/explorer/apps/index.spec.ts
- cypress/e2e/tests/pages/explorer/index.spec.ts
- cypress/e2e/tests/pages/explorer/manager/index.spec.ts
- cypress/e2e/tests/pages/explorer/mcapps/index.spec.ts
- cypress/e2e/tests/pages/global-settings/index.spec.ts
- cypress/e2e/tests/pages/legacy/index.spec.ts
- cypress/e2e/tests/pages/users-and-auth/index.spec.ts
- jest.setup.js
- shell/config/router.js
Also fixed a couple routes, and removed some test setup code that was commented on in another review.
I wanted to put these tests in place before changing or removing the middleware to make sure we keep the experience consistent.
These are the tests.
None
> Adding e2e tests for pages which use middleware to redirect

- cypress/e2e/po/pages/explorer/workloads-jobs.po.ts
- cypress/e2e/tests/pages/explorer/workloads/jobs.spec.ts
Fixes #10200
This PR adds test automation for the above issue.
> Add e2e test for job clone bug

- cypress/e2e/po/dialog/ResourceSearchDialog.po.ts
- cypress/e2e/po/pages/explorer/cluster-dashboard.po.ts
- cypress/e2e/tests/pages/explorer/resource-search.spec.ts
- shell/components/nav/Header.vue
Fixes #8656
Adds e2e tests for the issue where the resource search dialog appeared below the namespace filter when opened using the keyboard shortcut.
> Add e2e test for resource search and namespace filter issue

- shell/components/__tests__/ButtonGroup.test.ts
- shell/initialize/index.js
- shell/initialize/plugins.js
- shell/plugins/codemirror.js
- shell/plugins/index.js
- shell/plugins/positive-int-number.js
- shell/plugins/trim-whitespace.js
- storybook/.storybook/preview.js
Fixes #10774 
Refactors:
- trim-whitespace
- positive-int-number
- codemirror
The entire application is affected since these plugins are globally used.
In particular:
- make sure labels and icons look correct (ie spacing)
- make sure positive numbers are handled and displayed correctly
- make sure yaml editor works as expected
The entire application is affected since these plugins are globally used.
> [INT] Refactored some of the plugins - 2

- cypress/e2e/tests/pages/explorer/project-namespace.spec.ts
Fixes #5975 
Added a test case
N/A
N/A
Added a test
N/A
> [Automation] Added test to validate that Create button is disabled when attempting to create a project but name is not provided

- cypress/e2e/po/lists/chart-repositories.po.ts
- cypress/e2e/po/pages/chart-repositories.po.ts
- cypress/e2e/po/pages/explorer/charts/chart.po.ts
- cypress/e2e/po/pages/explorer/charts/charts.po.ts
- cypress/e2e/po/side-bars/burger-side-menu.po.ts
- cypress/e2e/tests/pages/explorer/apps/repositories.spec.ts
- shell/detail/catalog.cattle.io.app.vue
- shell/mixins/chart.js
- shell/pages/c/_cluster/apps/charts/index.vue
- shell/store/__tests__/catalog.test.ts
- shell/store/catalog.js
- shell/utils/install-redirect.js
Fixes #10448
- Reverts #7672, which was the fix for #7668. Supersedes another fix #10733
- #7672 revolved around a very outlier case where there was an update to an existing chart version (which are normally immutable) and using the 'Refresh' helm repo action failed to update it (note refreshing browser was a workaround)
- The fix for #7672 brought in a costly refresh of each helm repo at many different points in the dashboard. This impacts performance as users navigate around the dashboard, but we've also had customer's with large repos reporting timeouts which was compounded by that change. #10733 improved this by instead not caching individual chart versions and always going out and fetching them.
- See comment https://github.com/rancher/dashboard/pull/10733#issuecomment-2059034785 why …
> Improve Performance of many helm chart based pages

- cypress/e2e/blueprints/nav/edit-cluster.ts
- cypress/e2e/blueprints/nav/fake-cluster.ts
- cypress/e2e/po/edit/provisioning.cattle.io.cluster/edit/cluster-edit-generic.po.ts
- cypress/e2e/tests/pages/explorer/workloads/daemonsets.spec.ts
- cypress/e2e/tests/pages/manager/edit-fake-cluster.spec.ts
- shell/edit/provisioning.cattle.io.cluster/tabs/registries/RegistryConfigs.vue
Fixes #10412 (e2e testing)
- Adds pattern to e2e tests for editing a fake cluster (`edit config`)
- Add e2e test to prevent regression of issue #10412  , related to Registries tab in Cluster `Edit Config`, which should retain the value of the `Authentication` field when removing `Registry Authorization` blocks in the UI.
> add e2e test for issue 10412

- cypress/e2e/po/components/global-role-binding.po.ts
- cypress/e2e/po/edit/management.cattle.io.user.po.ts
- cypress/e2e/po/lists/role-list.po.ts
- cypress/e2e/po/pages/users-and-auth/users.po.ts
- cypress/e2e/tests/pages/users-and-auth/roles.spec.ts
- shell/components/GlobalRoleBindings.vue
Fixes #5291
- There were some existing e2e tests that create various roles
- Added checks to confirm that the setting is saved correctly and in the case of global roles is applied when creating a user
> Add automated tests to confirm Role's can be `default`

- docusaurus/docs/testing/e2e-test.md
Fixes #https://github.com/rancher/qa-tasks/issues/1293
Update docs to include best practices discussed with the UI team regarding how to utilize POs and cleaning up resources at the end of tests.
> update developer docs

- cypress/e2e/po/lists/provisioning.cattle.io.cluster.po.ts
- cypress/e2e/tests/pages/manager/cluster-manager.spec.ts
Fixes #6836 
Added E2E test to check that imported cluster displays provider type.
Added a E2E test. Unit tests were a part of the original change.
N/A
N/A
N/A
> [AUTOMATION] Added E2E test to confirm that imported cluster displays provider correctly

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/components/form/KeyValue.vue
This is a porting of https://github.com/harvester/dashboard/pull/1012
Support colon as separator when onPaste context in label key field.
Fixes # https://github.com/rancher/dashboard/issues/10958
Paste below text can be parsed to key and value
```
user-firstname: Andy Lee 
user-lastname: aaa
user-id: 123
```
> fix: support colon as separator when onPaste context in label key field

- shell/plugins/dashboard-store/getters.js
- shell/store/index.js
- shell/store/type-map.js
Fixes #10803
- when we change cluster we change state via `loadCluster`
- `loadCluster` with call `updateNamespaces` with current cluster filters and namespaces
- this was not happening when switching to a blank cluster, so anything that cached namespaces still had the old cluster's context
- also
- small optimisation to `count` getter (if not namespaced, don't mess around with ns cache)
- added comments to places
- considered updating the `count` function to ignore the cached namespaces if the current product does not show the ns filter... but that felt like more of a workaround and left us open to anything else that used the cached namespaces
- switching between local cluster, downstream cluster, back and forth, refresh at different points, etc
- areas that depends on namespaces within …
> Ensure blank cluster does not have a cluster namespace context

- shell/initialize/client.js
We previously initialized i18n on every middleware invocation. This happened to be called after harvester was loaded by the authenticated middleware which loaded it's i18n keys.
This will now call i18n/init in a 404 after the auth middleware is called and harvester pages are loaded.
Plugin translations, mostly Harvester.
> Initialize i18n after plugins load more

- cypress/e2e/po/pages/explorer/workloads-daemonsets.po.ts
- cypress/e2e/tests/pages/explorer/workloads/daemonsets.spec.ts
Fixes #9874 
- remove fake cluster from daemonset test and adjust e2e
> 9874 remove fake cluster from daemonset test and adjust e2e

- pkg/harvester-manager/machine-config/harvester.vue
- shell/components/form/ArrayList.vue
Fixes https://github.com/rancher/dashboard/issues/10992
Fixes https://github.com/rancher/dashboard/issues/10993
- It will limit the number of assigned vGPUs to 1 to prevent allocation issues.
- Label format is revisited.
We will remove the constraint once Harvester will support multiple vGPUs in Rancher provisioning.
See https://github.com/rancher/dashboard/pull/10991
> [2.8] Limit number of assigned vGPUs to 1 for each Machine Pool

- shell/list/fleet.cattle.io.cluster.vue
- shell/utils/cluster.js
Fixes https://github.com/harvester/harvester/issues/5546
> [2.7] show harvester cluster in fleet page

- .github/workflows/build-extension-catalog.yml
- .github/workflows/build-extension-charts.yml
Contributes to #10663
- yq should come as default
- https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
- Tested via repo containing pkgs pointing at workflows from this PR's branch
- https://github.com/richard-cox/extension-testing/actions/runs/9060291972
- https://github.com/richard-cox/extension-testing/actions/runs/9060291974/job/24889695939
- The output i think is all in https://github.com/richard-cox/extension-testing/tree/gh-pages
- I've tested https://richard-cox.github.io/extension-testing can be added as a repo and the extension installed
- This requires a thorough confirmation still though
> Remove yq install from build-extension-x workflows

- shell/assets/translations/en-us.yaml
- shell/config/settings.ts
- shell/pages/c/_cluster/settings/performance.vue
- shell/plugins/steve/__tests__/subscribe.spec.ts
- shell/plugins/steve/subscribe.js
- shell/store/features.js
- shell/utils/pagination-utils.ts
~Blocked on https://github.com/rancher/dashboard/pull/10761~
Contributes to https://github.com/rancher/dashboard/issues/9545
Gate server side pagination on 
- `on-disk-steve-cache` feature flag
- There's a backend in progress item to resolve a `revision` issue, so when this is enabled... disable watching on revisions
- new Global Settings - Performance - Server Side Pagination Setting
- Added new setting to enable server side pagination
- this is incompatible with two other performance settings
Also fix add temporary fix for an issue Bullseye team are working on
- new steve vai cache api does not return a revision number when we fetch resources
- this means the UI will watch resource using a revision from the resources themselves, which is often `too old`
- watch will fail given `too …
> Wire in Feature Flag and Performance Settings for Server-Side Pagination

- shell/components/SortableTable/THead.vue
Fixes #10842 
A computed property `hasColumnWithSubLabel` was created to conditionally add a css class name in order to style the headers.
This should only affect the tables where there's a sub-label like `Architecture` in the header(e.g. home and cluster list).
I don't think this change could cause a regression.
> Make tables headers vertically top aligned when a column with sub-label exists

- .github/workflows/docusaurus.yaml
Contributes to #10663
- Replace peaceiris/actions-gh-pages action with generic gh actions
- Means we have to
- Update settings to deploy gh pages from gh actions
- https://github.com/rancher/dashboard/settings/pages change to Source Github Actions
- https://github.com/rancher/dashboard/settings/environments/603599194/edit add `master` as a deployment branch
- Switch over the CI `Publish Docusaurus` gate block to the new build job
- Means we can
- drop the gh-pages branch
- drop GH_PAGES_DEPLOY_KEY
- See https://github.com/richard-cox/dashboard/actions/runs/9077572302 for working example (though gh pages doesn't load docusarus correctly given backed in domain name) 
- See https://github.com/richard-cox/dashboard/actions/runs/9112196237/job/25050946120 for a run from this PR
> Replace peaceiris/actions-gh-pages action with generic gh actions

- cypress/e2e/blueprints/manager/cloud-credential-create-payload.ts
- cypress/e2e/po/edit/provisioning.cattle.io.cluster/create/cluster-create-rke2-azure.po.ts
- cypress/e2e/po/edit/provisioning.cattle.io.cluster/tabs/machine-pools-tab-azure-rke2.po.ts
- cypress/e2e/tests/pages/manager/cloud-credential.spec.ts
- shell/machine-config/azure.vue
Fixes #10470 
Added E2E test
N/A
N/A
N/A
N/A
N/A
> [Automation] Added a test for credential changing the Azure environment

- cypress/e2e/po/edit/provisioning.cattle.io.cluster/cluster-create-import.po.ts
- cypress/e2e/po/edit/provisioning.cattle.io.cluster/tabs/basics-tab-rke2.po.ts
- cypress/e2e/tests/pages/manager/cluster-manager.spec.ts
Task #
https://github.com/rancher/qa-tasks/issues/1284
Refactor labelselect to be used from the BasicRke2 cluster create tab.
Use the TabbedPo to click on the Networking tab,
Refactor to organize a couple of `cy.get` to POs
Custom Cluster create test
Test Pipeline
> [Automation] - Move network labelselect to BasicRke2 create tab

- cypress/e2e/po/components/resource-table.po.ts
- cypress/e2e/po/detail/provisioning.cattle.io.cluster/cluster-detail.po.ts
- cypress/e2e/po/lists/cluster-recent-events-list.po.ts
- cypress/e2e/po/lists/cluster-snapshots-list.po.ts
- cypress/e2e/tests/pages/manager/cluster-provisioning-amazon-ec2-rke2.spec.ts
- cypress/e2e/tests/pages/manager/cluster-provisioning-azure-rke2.spec.ts
Related task: 
https://github.com/rancher/qa-tasks/issues/759
https://github.com/rancher/qa-tasks/issues/757
Adding checks to provisioned RKE2 clusters to validate Recent Event tabs and Snapshots on cluster details.
These two tabs are only visible on cluster driver provisioned clusters. These aren't shown on the local cluster details which is an Imported cluster
Those other checks are in this PR: https://github.com/rancher/dashboard/pull/10867
Jenkins pipelines
provisioning tests on Jenkins
> [Automation] - Adding Cluster Details and Snapshot tab check

- cypress/e2e/po/prompts/promptRemove.po.ts
- cypress/e2e/tests/pages/users-and-auth/roles.spec.ts
- cypress/globals.d.ts
- cypress/support/commands/commands.ts
- shell/assets/styles/themes/_light.scss
Fixes #10018
Reverted the styling for text-warning and added e2e test.
> Fix incorrect color for text-warning

- shell/assets/translations/en-us.yaml
- shell/edit/provisioning.cattle.io.cluster/__tests__/DirectoryConfig.test.ts
- shell/edit/provisioning.cattle.io.cluster/__tests__/utils/cluster.ts
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
- shell/edit/provisioning.cattle.io.cluster/tabs/Advanced.vue
- shell/edit/provisioning.cattle.io.cluster/tabs/DirectoryConfig.vue
Fixes #10824 
- add `data directory configuration` component to advanced tab in rke2 create/edit cluster interface 
- add unit test for `data directory configuration` component
- full manual test is dependent on https://github.com/rancher/rancher/issues/45038
- Go to RKE2 cluster creation interface and make sure the `data configuration` area is present on the `Advanced` tab of Cluster Configuration
- Make sure data persists and all works fine
- Make sure that cluster editing, the `data configuration` is disabled (not allowed to change the values)
**NOTE:** this video still doesn't cover the edit scenario properly, since we still don't have the changes needed on the backend to persist the data, but it proves the payload sent is correct …
> add `data directory` configuration component to advanced tab in rke2 create/edit cluster interface

- shell/detail/__tests__/service.test.ts
- shell/detail/service.vue
Fixes #10822
Returns an empty array if the service port is not set, to avoid js reporting errors
1. service detail page
> fix(detail/service): fix js error if no port is configured

- cypress/e2e/po/side-bars/burger-side-menu.po.ts
- cypress/e2e/tests/pages/extensions/extensions.spec.ts
- cypress/e2e/tests/pages/global-settings/branding.spec.ts
- cypress/e2e/tests/pages/users-and-auth/roles.spec.ts
- shell/components/nav/TopLevelMenu.vue
- shell/components/nav/Type.vue
- shell/config/product/explorer.js
- shell/store/type-map.js
Fixes #10576 
- fix issue with double active main menu items in app bar 
- add sneaky fix for Cluster and Project Members menu item not being highlighted
- add e2e test to prevent regression
- click on `local` cluster in app bar
- after than, go to one of the products that uses the `local` cluster for context such as `Global Settings`, `Extensions` or `Users & Authentication` and make sure the `local` cluster app bar menu is not highlighted as well.
- Try other page changes to make sure no double highlighting is occurring in the app bar
**Before**
**After**
**Cluster and Project members sneaky fix**
> The highlighted cluster in the App Bar retains its highlighting even when clicking on an item from the bottom category of the App Bar

- shell/components/nav/TopLevelMenu.vue
- shell/components/nav/__tests__/TopLevelMenu.test.ts
Fixes #10975 
- make sure local cluster appears always on top of pinned and unpinned cluster lists in main nav menu 
- create multiple ready clusters on DO, with names that you can distinguish easily the alphabetical ordering
- once they are all ready, make sure that they appear in alphabetical ordering (name) **BUT** with `local` cluster always on the top of the list (check pinned clusters list as well)
**Before**
**After**
> Local cluster does not appear at the top of the app bar

- cypress/e2e/tests/pages/global-settings/settings.spec.ts
- shell/edit/management.cattle.io.setting.vue
Fixes #10613
This PR updates the global settings edit page for `server-url` to make it so that you can not reset if to the default, since there is no default value.
Also adds an e2e test to verify this behaviour.
Handled by automated e2e test - checks that when you go to edit the `server-url` setting, that the `Reset to Default` button is not enabled.
> Disallow reset of server url

- pkg/aks/components/CruAks.vue
- pkg/aks/components/__tests__/CruAks.test.ts
- pkg/aks/util/__mocks__/aks.ts
Fixes #10431 
This PR updates the virtual networks dropdown to display subnets, grouped by network, and set the config.subnet field when one is selected (in addition to setting `config.virtualNetwork` and `config.virtualNetworkResourceGroup`, which it already does)
1. selecting one of the subnet options should set virtualNetwork, virtualNetworkResourceGroup, and subnet
2. selecting a subnet then selecting again the default 'none' option and saving should not return errors
> AKS - show subnets in virtual network dropdown

- cypress/e2e/tests/pages/users-and-auth/users.spec.ts
- shell/assets/translations/en-us.yaml
- shell/components/formatter/LiveDate.vue
- shell/config/table-headers.js
- shell/models/management.cattle.io.user.js
This addresses several issues identified with new Login fields added to the users table
- When Disable/Delete After fields reach 0, the relative date would start counting up
- When a user is disabled, there is no need to display a value for Disable After
- Update the user states to reach Enabled/Disabled instead of Active/Inactive
- Add a suffix to the last login column 
Fixes #11074
Fixes #11071
I originally attempted to expose the live date components through the cell slots for the table, but I found that the `LiveDate` component no longer works with this change. It appears that `LiveDate` is receiving updates via the prop on a regular basis while rendering from within the table, but that relationship is broken when data is exposed through a slot. I opted to add a new prop to the …
> Resolve issues with user last login fields

- pkg/aks/components/CruAks.vue
- pkg/aks/components/__tests__/CruAks.test.ts
Fixes #10965  
The 'container monitoring' checkbox should correspond to `aksConfig.monitoring` - previously it was just gating the visibility of the two log analytics inputs. This PR corrects that and adds a few unit tests.
1. create an AKS cluster with container monitoring enabled, and log analytics workspace name/group set - the payload should include `aksConfig.monitoring` = true
2. edit cluster and disable container monitoring - the payload should include `aksConfig.monitoring` = false, and `aksConfig.logAnalyticsWorkspaceName` and `aksConfig.logAnalyticsWorkspaceGroup` set to null
> AKS - fix container monitoring checkbox

- shell/middleware/authenticated.js
- shell/utils/auth.js
Small rework of two functions and then the extraction of a number of functions to the existing auth util. This is an effort to shrink down the code in authenticated middleware to make it a little easier to address.
It might be helpful to look at the two commits in this PR separately.
- Logging in
- Product not found
- Resource not found
https://github.com/rancher/dashboard/assets/55104481/da9ce56d-c844-42e6-a61b-68cfacf03a0a
> Simplify Authenticated Middleware

- .github/workflows/test.yaml
Contributes to #10663
- See https://github.com/rancher/dashboard/issues/11106 for details
- I've kept the upload of coverage artefacts as in, as soon we'll need them again
> Temporarily Remove codecov upload given caveats on `codecov/codecov-action` action

- shell/components/fleet/FleetClusters.vue
- shell/models/__tests__/fleet.cattle.io.cluster.test.ts
- shell/models/fleet.cattle.io.cluster.js
Fixes #[10542](https://github.com/rancher/dashboard/issues/10542)
- replace `nodeInfo` with `bundleInfo` in fleet cluster model 
- update fleet cluster table to display `bundles ready` instead of `nodes ready` (as per https://github.com/rancher/fleet/pull/2190)
- go to fleet clusters and check that we no longer display nodes ready (replaced by bundles ready)
**Before**
**Aft
er**
> Replace Fleet Cluster `Nodes Ready` column 

- package.json
- shell/assets/styles/fonts/_icons.scss
- shell/package.json
- yarn.lock
Fixes #7477
This PR fixes the above issue.
Rancher Icons is now published to npm as the package `@rancher/icons`
This PR updates the reference(s) to use this package rather than referencing GitHub.
Manual testing is needed to just check that the icons still appear correctly.
Check the app bar and explore a cluster and check the top bar - the icons should render as before, e.g. for the explorer top bar:
We just need to validate the overall mechanism for including the icon font is not broken - so we don't need to check all icons, just that the icons still show correctly.
> Use @rancher/icons package rather than a GH reference

- shell/plugins/dashboard-store/mutations.js
- shell/store/index.js
This utilizes `markRaw()` to ensure that certain properties in the Vuex store are marked as "non-reactive". 
Fixes #11098
Upon further review of #11062, I thought that `Object.defineProperty()` was being used, in part, to mark certain properties as "non-reactive" in the Dashboard store. `$plugin`, `$router`, & `$route` really don't need reactivity associated with them.
We might want to consider following up in the future to decide if any of these properties belong in the Vuex store at all. We can achieve a similar result by utilizing a singleton or some similar pattern that will allow us to share these definitions throughout Dashboard. 
Anything that accesses the $router, $route, or $plugin states stored in the store.
> Use `markRaw()` to signal non reactive data in store

- .github/workflows/build-and-upload-branch.yaml
- .github/workflows/build-and-upload-release-2-8.yaml
- .github/workflows/test.yaml
- This is the backport of https://github.com/rancher/dashboard/pull/11018
- It also includes the change 
- to split e2e build into a separate job (this will reduce runner load) https://github.com/rancher/dashboard/pull/10691
- remove stale docker files / references https://github.com/rancher/dashboard/pull/9763
Examples
- building from branch (with uploaded bits) -  https://github.com/rancher/dashboard/actions/runs/9159052158
- building from tag (with uploaded bit) - https://github.com/rancher/dashboard/actions/runs/9160038772
> [2.8.patch1] Port drone build tasks to gh workflows + actions

- cypress/e2e/po/lists/chart-repositories.po.ts
- cypress/e2e/po/pages/extensions.po.ts
- cypress/e2e/tests/pages/extensions/kubewarden.spec.ts
Fixes e2e tests
- Temporarily exclude the kubewarden extension test until it's possible to install extension (https://github.com/rancher/kubewarden-ui/pull/732 merged, new extension released
- also improve test to check the extension repo becomes active before looking for charts within
> Exclude kubewarden e2e test until it's possible to install extension again

- cypress/e2e/tests/pages/manager/cloud-credential.spec.ts
- cypress/e2e/tests/pages/manager/cloud-credentials.spec.ts
Fixes https://github.com/rancher/qa-tasks/issues/1335
Adding a cleanup step to the Cloud Credential spec. This will ensure the initial state of the cloud credentials data is always empty on retries.
I've tested the remove when there are credentials linked to a cluster. I left the API check out to avoid collisions with the provisioning tests. 
E2E tests. Provisioning and Cloud credentials. Low risk.
> [Automation] - Adding data state cleanup before running cloud-credential spec

- cypress/e2e/po/components/version-number.po.ts
- cypress/e2e/po/side-bars/product-side-nav.po.ts
- cypress/e2e/tests/pages/generic/version.spec.ts
- shell/components/SideNav.vue
- shell/components/nav/TopLevelMenu.vue
Fixes #11137
This PR removes the version from the bottom of the side nav and replaces the 'About' text in the app bar with the version number.
If the version number starts with 'v', we show that version - if it ends with '.0' - i.e. is a minor release, we remove that, so we show (e.g.) `v2.9`.
For development versions, we show 'About'
For long version numbers (e.g. `v2.10.11` we reduce the font size slightly so that it looks better) 
Automated tests added for the cases above.
> Remove version number from side nav and update app bar to show it instead

- cypress/e2e/po/components/keyboard-mapping-indicator.po.ts
- cypress/e2e/po/pages/explorer/yaml-editor.po.ts
- cypress/e2e/tests/pages/user-menu/preferences.spec.ts
- shell/assets/translations/en-us.yaml
- shell/components/CodeMirror.vue
- shell/components/__tests__/CodeMirror.test.ts
Fixes #11092
This PR fixes the above issue.
Instead of always showing the current keyboard mapping overlay on the yaml editor, we only show it when set to something other that the default (i.e. Emacs or Vim). The default is called 'Norman Human', so showing it just looks weird.
When shown now, the display has been changed to only show an icon with a tooltip, so that even when shown, it is less intrusive.
Was:
Now:
With the exiting UI/UX, the close icon appears and the label jolts as a result. With this change, subtle animations have been applied to make this is a nicer transition that is less jarry.
Automated tests are included.
Video before:
Video with this change:
> Improve keyboard mapping display

- shell/initialize/entry-helpers.js
Fixing a race condition with how we update/reset the title to "Rancher" if a page doesn't set the title.
Specifically addresses this comment https://github.com/rancher/dashboard/issues/9822#issuecomment-2078169973
Fixes #9822
Switched from a beforeEach to an afterEach routeGuard because sometimes we'd switch back to the 'Rancher' title before changing pages which would change the title the browser recorded in history.
> Fixing a race condition with how we update/reset the title to "Rancher" if a page doesn't set the title.

- cypress/e2e/po/components/footer.po.ts
- cypress/e2e/po/components/sortable-table.po.ts
- cypress/e2e/po/edit/catalog.cattle.io.clusterrepo.po.ts
- cypress/e2e/po/edit/chart-repositories.po.ts
- cypress/e2e/tests/pages/explorer/apps/repositories.spec.ts
- cypress/e2e/tests/pages/fleet/gitrepo.spec.ts
- cypress/e2e/tests/pages/manager/repositories.spec.ts
- shell/edit/catalog.cattle.io.clusterrepo.vue
- shell/plugins/dashboard-store/mutations.js
Fixes #11151
- Resources are added to our resource map & list on resource create and on socket updates
- When resources are created..
- the http response is usually received first, and the resource is added to both resource map and list
- any socket updates received afterwards will then update that first resource entry
- However there are scenarios where..
- the http response is sent, but response not yet received
- the socket event for the created resource is then received, and resource is added to resource map and list
- the http response is then received. the load mutator would then ADD to the list and SET in the map
- this caused two rows for the resource to show in it's list view
- Fix is to gate adding them to the list
Also contains
- General improvements for …
> Fix duplicate list rows on resource create race condition

- storybook/.storybook/main.js
- storybook/.storybook/preview.js
Fixes #11171 
Fixes the way i18n is used in Storybook so that the pages are not broken.
Also disables telemetry.
Issue is marked as QA/None - PR reviewer to validate locally on built Storybook - this should be sufficient - this is for the Storybook, not code that makes it into the product UI.
> Storybook: Fix i18n

- shell/components/form/ResourceTabs/index.vue
- shell/components/formatter/FleetSummaryGraph.vue
Fixes #11154
Fixes #11155
1. Unreleased Regression - Ensure the Resource Tabs Conditions tab correctly shows
- The `Conditions` tab shows when the resource's schema says the resource contains conditions
- Following the schema diet change this info isn't in the base schema, so we need to fetch the resources schema definition
- If not found we currently only print a warning to indicate the owning component needs to call `fetchResourceFields`. This was done to avoid making the request for every resource detail page. This resulted though in a number missed places (nodes, some fleet resources, etc)
- To avoid this we'll now make the request to fetch schema definitions on every resource tabs usages (with some caveats)
2. Legacy broken feature - Fleet Cluster List `Resources` column failed to …
> Fix `Conditions` tab, and Fleet Cluster `Resources` column

- cypress/e2e/po/lists/management.cattle.io.user.po.ts
- cypress/e2e/tests/pages/users-and-auth/roles.spec.ts
- shell/config/router/index.js
- shell/config/router/navigation-guards/attempt-first-login.js
- shell/config/router/navigation-guards/index.js
- shell/config/router/navigation-guards/load-initial-settings.js
- shell/initialize/app-extended.js
- shell/middleware/authenticated.js
- shell/utils/router.js
Pulling out authentication code into router navigation guards
I chose to migrate the code into a beforeEach navigation guard because it is the closest we have to maintaining the same execution timeline as the middleware. (Middleware is actually called from a beforeEach with the entry-helpers.js render method.
I do think it's a slightly kludgey implementation because we don't want it to execute for the `unauthenticated` routes. We may want to move this into a mixin at some point.
> Pulling out authentication code into router navigation guards

- shell/scripts/vue-migrate.js
Fixes #11178 
In https://github.com/rancher/dashboard/pull/10581 I introduced a number of instances of the .sync modifier which is [deprecated in vue 3](https://v3-migration.vuejs.org/breaking-changes/v-model.html#overview). This PR updates the migration script to convert all uses of .sync to v-model as outlined in the migration docs. 
The .sync modifier has been introduced in the eks built-in extension: files outside /pkg/eks/* should not be impacted.
> update migration script to handle .sync modifier

- shell/list/management.cattle.io.feature.vue
This increases the timeout for the restart modal to 5 seconds. 
Fixes #11087
While troubleshooting this issue, I noticed that we were receiving a 200 response from the server before the Rancher backend finished restarting. It must be that the backend is taking longer to shutdown and responding to our request when it does so.
I'm not a fan of increasing the timeout to an arbitrary number, but this is the most straightforward approach to resolve the issue at this point. The obvious issue with this approach is that we will see the same regression in the future if the backend takes any longer to shut down.
I also considered that we might be able to implement a function that initially polls at a greater duration and then incrementally steps down the timeout for each successive attempt. This …
> Increase restart modal timeout to 5 seconds

- cypress/e2e/po/edit/chart-repositories.po.ts
- cypress/e2e/tests/pages/manager/repositories.spec.ts
- shell/edit/catalog.cattle.io.clusterrepo.vue
Fixes #11123 
The main fix for this issue is done by the backend in [this PR](https://github.com/rancher/rancher/pull/45672), but there were some issues on the UI side too, such as sending unnecessary data to the backend e.g. sending `gitRepo: ''` when creating a helm/oci repos. Also setting a value for any inputs of `exponentialBackOffValues` and then clearing it was leading to send `0` which is fixed in this PR.
Added an E2E test to type a value for `exponentialBackOffValues` and then clearing it to check that the key of that input(e.g. `maxWait`) is not sent in the payload.
Creating git/helm repos should be checked just in case if the removal of some unnecessary data in the payload might have caused a regression. The current automation could be sufficient enough probably?
> Fix default values for exponentialBackOffValues

- cypress/jenkins/cypress.sh
Fixes CI
Fixing cypress not found on tests running on 2.7
this will force cypress to be installed before executing
Jenkins
> Trying forcing the Cypress binary install due to erros in CI

- shell/config/router/navigation-guards/attempt-first-login.js
- shell/config/router/navigation-guards/load-initial-settings.js
- shell/initialize/entry-helpers.js
- shell/mixins/brand.js
- shell/pages/auth/login.vue
- shell/pages/auth/setup.vue
- The from/to routes were transposed so I flipped them
- Load initial settings wasn't receiving the store and the error was swallowed.
- Fixed some error reporting instead of just swallowing exceptions
- Removed unnecessary calls to fetchInitialSettings
While working on other changes I noticed that fetchInitialSettings was failing and was being swallowed by the try catch.
> Found a few issues with navigation guards and fixed them

- cypress/e2e/po/edit/provisioning.cattle.io.cluster/create/cluster-create.po.ts
- cypress/e2e/po/pages/users-and-auth/authProvider.po.ts
- cypress/e2e/tests/pages/manager/cluster-manager.spec.ts
- shell/components/SelectIconGrid.vue
- shell/edit/provisioning.cattle.io.cluster/index.vue
Turns out that the order of the providers has changed (changes all the time?) so this broke the reliance on looking up elements based on index.
This change makes the relevant tests more robust by relying on names instead of indices.
Only our tests
> Fixing an azuread test where the wrong auth provider is being selected

- cypress/e2e/tests/navigation/side-nav/main-side-menu.spec.ts
- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/config/private-label.js
Fixes #10766 
Along with updating `DOCS_BASE` I've also updated a case(on Logging install steps page) where it was still using a hardcoded url. I've recorded a video of testing it.
https://github.com/rancher/dashboard/assets/135728925/47e86027-d992-406a-b437-0c41c5900fe8
> Update docs version

- shell/config/router/navigation-guards/attempt-first-login.js
- shell/config/router/navigation-guards/authentication.js
- shell/config/router/navigation-guards/index.js
- shell/config/router/routes.js
- shell/initialize/entry-helpers.js
- shell/middleware/authenticated.js
- shell/utils/auth.js
- shell/utils/router.js
Extracted the authentication portion of the authenticated middleware into a navigation guard
This is the closest analogue for getting authentication to be executed at the same point in time it was when it was in middleware.
I did verify this works for both local and github authentication providers.
All authenticated area
All authenticated area
> Extracted the authentication portion of the authenticated middleware into a navigation guard

- cypress/e2e/po/pages/explorer/ingress.po.ts
- cypress/e2e/tests/pages/explorer/service-discovery/ingress.spec.ts
- shell/components/formatter/IngressTarget.vue
- shell/list/networking.k8s.io.ingress.vue
Fixes #11086 
- add fix for missing secondary schemas in ingress list view
- add e2e test
- Go to `Ingress` list view and make sure we don't have the console warn related to `pathExistsInSchema`
**Before**
**After**
> Ingresses List warns pathExistsInSchema has been used without fetching the schema definition

- cypress/e2e/blueprints/settings/settings.ts
- cypress/e2e/po/components/fixed-banner.po.ts
- cypress/e2e/tests/pages/global-settings/banners.spec.ts
- cypress/globals.d.ts
- cypress/support/commands/rancher-api-commands.ts
- shell/assets/translations/en-us.yaml
- shell/components/FixedBanner.vue
- shell/components/nav/TopLevelMenu.vue
- shell/components/nav/__tests__/TopLevelMenu.test.ts
- shell/pages/auth/login.vue
- shell/pages/c/_cluster/settings/banners.vue
- shell/utils/banners.js
Fixes #7366
This PR addresses the above new feature.
We now allow for individual banner settings:
- `ui-banner-header`
- `ui-banner-footer`
- `ui-banner-login-consent`
When configured, these will be used in preference to the configuration in the existing single banner setting `ui-banners` - this makes it easier for users wishing to configure these banners independently.
When configured by the individual settings, the UI prevents editing of the banners for simplicity - e.g.
This PR included automated e2e tests to validate the existing behaviour and the new settings in various scenarios.
Banner configuration via the banner settings.
See above for the banner settings page when individual banner settings are present.
Banners should appear on pages exactly the same as when configured via the …
> Add support for Individual banner settings

- shell/scripts/extension/helm/charts/ui-plugin-server/templates/cr.yaml
- shell/scripts/extension/helm/charts/ui-plugin-server/values.yaml
- shell/scripts/extension/helm/scripts/patch
- shell/scripts/extension/publish
Fixes #11219
Updates the extension publish script so that if the extension's `package.json` file specifies `noAuth` then this will be wired into the extension Helm package.
Note: I also updated some of the log statements to refer to Extensions rather than Plugins.
No manual testing - we will test this as part of Extensions development.
> Extensions: Add support for noAuth in publish script

- shell/initialize/install-plugins.js
- shell/plugins/i18n.js
Fixes rancher/dashboard#11203
There was a race condition where certain pages would sometimes fail to render if the language was changed. This was caused by `i18n/init` sometimes not completing before some of the page would begin to render and would ultimately lead to `loadManagement` not getting called.
`/dashboard/c/_/fleet/fleet.cattle.io.gitrepo` in a production build. You can update the `ui-dashboard-index` global setting to `https://releases.rancher.com/dashboard/i18n-fix-dev/index.html` to test. 
I was only able to reproduce the original issue in Chrome with a production build by refreshing the gitrepo page over and over.
> Making the call to i18n/init blocking to resolve a race condition

- pkg/aks/components/CruAks.vue
- pkg/eks/components/CruEKS.vue
- shell/utils/kontainer.ts
Fixes #10966 
Fixes #3872 
Fixes #8501 
This PR corrects editing of imported clusters by fixing the upstream syncing logic. Hosted clusters (aks eks gke) track both the configuration managed through Rancher and the configuration managed through their respective cloud provider's platform. You can read more about syncing between the two in the Rancher docs [here](https://ranchermanager.docs.rancher.com/reference-guides/cluster-configuration/rancher-server-configuration/sync-clusters). 
When testing this PR, it should be noted that once a cluster has been updated through Rancher, it should _only_ be updated through Rancher.
To test issues with the node pool upgrade checkbox/banner stuff:
1. In the azure portal, create an AKS cluster that does not use the latest k8s version available.
2. …
> AKS - fix editing imported clusters

- cypress/e2e/tests/pages/fleet/gitrepo.spec.ts
- shell/edit/fleet.cattle.io.gitrepo.vue
This PR fixes SURE-6919
Fixes https://github.com/rancher/dashboard/issues/11211
There were recent fixes to the BRO codebase that corrected a bug which backed up far more data than it should have been backing up. In other terms, the resourceset filters BRO uses to collect resources for backups are properly followed now.
As such, the only fleet secrets that get backed up would be ones with the `"fleet.cattle.io/managed=true"` label. Since that is the existing rule defined for fleet within the resoruceset.
This PR aims to make sure that the secrets being created by the fleet UI are labeled as managed by fleet. This in turn will allow BROs rules to collect the secrets for backup.
This change is not retroactive - any existing secrets should be updated by Rancher admins to include the correct …
> Add default label to Fleet Secrets to enable BRO backups

- cypress/e2e/po/pages/extensions/kubewarden.po.ts
- cypress/e2e/tests/pages/extensions/kubewarden.spec.ts
This replaces the Kubewarden extension tests that were [excluded previously](https://github.com/rancher/dashboard/pull/11149) due to an incorrect Kubernetes version in the chart annotation of the extension.
The Kubernetes version has been updated in the [Kubewarden dashboard repo](https://github.com/rancher/kubewarden-ui/pull/732) and a release has been merged in the [`ui-plugin-charts` repo](https://github.com/rancher/ui-plugin-charts/pull/54)
- Removed the `-temp-excluded` tag kubewarden.spec.ts
- Replaced the `addChartsRepoIfNeeded` method from kubewarden page object
- Added wait to repository creation to ensure the repo is cached before continuing the tests.
> Include Kubewarden extension tests

- cypress/e2e/tests/pages/fleet/gitrepo.spec.ts
- shell/edit/fleet.cattle.io.gitrepo.vue
Fixes https://github.com/rancher/dashboard/issues/11230
Backport of: https://github.com/rancher/dashboard/pull/11209
See summary from there.
See from [original](https://github.com/rancher/dashboard/pull/11209).
See from [original](https://github.com/rancher/dashboard/pull/11209).
See from [original](https://github.com/rancher/dashboard/pull/11209).
See from [original](https://github.com/rancher/dashboard/pull/11209).
N/A
> [backport v2.8.next1] Add default label to Fleet Secrets to enable BRO backups

- cypress/e2e/po/pages/extensions/kubewarden.po.ts
- cypress/e2e/tests/pages/extensions/kubewarden.spec.ts
This reverts commit c4900df9c562ea6f4f224288158a5f80c5fe516a.
The kubewarden tests are failing on the pipeline causing all PRs to fail the checks needed to be merged. Reverting the commit that replaced those tests will at the very least allow other PRs to pass while a proper fix can be implemented.
Debugging the Kubewarden tests locally shows zero issues.
> Revert "Include Kubewarden extension tests"

- cypress/e2e/blueprints/explorer/cluster/events.ts
- cypress/e2e/po/components/pagination.po.ts
- cypress/e2e/po/components/sortable-table.po.ts
- cypress/e2e/po/pages/explorer/events.po.ts
- cypress/e2e/tests/pages/explorer/dashboard/cluster-dashboard.spec.ts
- cypress/globals.d.ts
- cypress/support/commands/chainable.ts
Covers pagination functionality for cluster events list.
To have deterministic tests for pagination, I used mock response (using cy.intercept) with lots of data hence the massive events data objects in `cypress/e2e/blueprints/explorer/cluster/events.js`. It's not pretty but, this is the easiest, most time efficient way to write these tests. Will revisit this when I have more time. https://github.com/rancher/qa-tasks/issues/1386
> vai pagination tests - cluster events

- cypress/e2e/tests/pages/manager/cluster-provisioning-amazon-ec2-rke1.spec.ts
- cypress/e2e/tests/pages/manager/cluster-provisioning-amazon-ec2-rke2.spec.ts
Fixes #10831
add check for the architecture column in existing e2e tests RKE1/RKE2 cluster provisioning
> automation: add check for architecture column

- pkg/eks/components/CruEKS.vue
- pkg/eks/components/__tests__/CruEKS.test.ts
- pkg/eks/l10n/en-us.yaml
- pkg/eks/util/__tests__/validators.test.ts
- pkg/eks/util/validators.ts
Fixes #11199 (see comment for details)
#11105 
This PR updates EKS form validators to not run until the form has renders. It also updates which name property is displayed in the name input, see https://github.com/rancher/dashboard/issues/11199#issuecomment-2163774098. This PR also has some tweaks to tab name/labels so there are no console errors thrown if the user tries to use duplicate node group names.
Validators have been moved out of CruEKS to  write unit tests without having to test form validation mixin functionality.
1. Create a cluster and verify that the POST request has correctly set both `cluster.name` and `cluster.eksConfig.displayName`
2. Edit the cluster and update the name; verify that both `cluster.name` and `cluster.eksConfig.displayName` are updated
Node groups:
1. Add a …
> EKS fix validation when no credential is found, cluster name display

- cypress/e2e/blueprints/explorer/cluster/events.ts
- cypress/e2e/tests/pages/explorer/dashboard/cluster-dashboard.spec.ts
Fixes https://github.com/rancher/qa-tasks/issues/1384
Updating the Cluster Dashboard events tests to include table headers validations. It currently does basic data validation.
- This is validating the empty table scenario.
- A basic table with data scenario already exist in the suite.
- Pagination is done in a separate PR https://github.com/rancher/dashboard/pull/11234
Automation pipeline
> [Automation] - Adding Cluster Events table tests

- docusaurus/docs/extensions/extensions-configuration.md
Fixes #
- update docs for noAuth annotation
> update docs for noAuth annotation

- shell/scripts/.gitlab/workflows/build-extension-catalog.gitlab-ci.yml
Fixes #11240 
Node.js `v14` is incompatible with the latest dashboard build, bumping the package to nodejs16 does not solve the problem of the openssl incompatibility. In order to circumvent this, node.js `v16` needs to be installed manually as the original package from `https://download.opensuse.org/repositories/devel:languages:nodejs/SLE_12_SP5/devel:languages:nodejs.repo` is outdated.
I've added a `node-setup` script to the pipeline that will download the specified release declared in the `NODE_DISTRO` variable from the [nodejs releases index](https://nodejs.org/download/release/). 
The `variables` stanza now has some variables to alleviate any further issues with upgrading node and yq.
Installing the Extension catalog image that is published to the gitlab container registry of the …
> Update gitlab pipeline with node setup

- cypress/e2e/po/components/pagination.po.ts
- shell/components/SortableTable/index.vue
Fixes https://github.com/rancher/qa-tasks/issues/1388
Positional locators aren't recommended and is a red flag on automation. Those shouldn't be used under any circumstance and is something commonly used as last resort.
Added `data-testid` for pagination navigation buttons.
Automation is only affected and this isn't a functional change in the Vue code.
Test done: Cluster Pagination tests executed and passed.
> [Automation] - Use testid locators rather than positional on pagination

- shell/pages/c/_cluster/explorer/index.vue
Fixes https://github.com/rancher/dashboard/issues/11181
When Rancher is freshly installed, it takes some time to create `cattle-fleet-local-system/fleet-agent` StatefulSet in `local` cluster. 
We are excluding it from` fleet agent` health checks during this startup period.
During the startup period:
- `cattle-fleet-local-system/fleet-agent` is null
- Rancher is able to create and communicate with new downstream clusters
- `cattle-fleet-system/fleet-controller` is OK
So it's reasonable to calculate the fleet agent status using only `cattle-fleet-system/fleet-controller` and include `cattle-fleet-local-system/fleet-agent` when available.
- cluster explorer -> local -> Dashboard page -> Health boxes -> fleet
- Install Rancher 2.9.x
- Check the fleet health box (see screenshot)
- …
> Fix fleet status calculation

- cypress/e2e/tests/pages/extensions/extensions.spec.ts
Fixes #10639 
**TO TEST/REVIEW THIS LOCALLY IT'S NEEDED:**
- https://github.com/rancher/dashboard/pull/11036 **to be merged** (done!)
- **needs Rancher backend 2.9-head from 24th May, 2024 minimum** -> tied to https://github.com/rancher/rancher/pull/45521
- Add e2e test to check that extensions with `cacheState: disabled` work on Rancher Dashboard
- Add git repo to Rancher for extension examples: local -> apps -> repositories
type: `git repo`
repo: `https://github.com/rancher/ui-plugin-examples`
branch: `main`
- Install extension `Large-extension` and make sure it works (top-level extension -> main nav)
> e2e test for large extension that disables cache

- shell/components/ResourceDetail/index.vue
- shell/config/product/explorer.js
- shell/config/types.js
- shell/plugins/dashboard-store/actions.js
- shell/store/type-map.utils.ts
- shell/types/store/dashboard-store.types.ts
Fixes #11024
- Support conditionally de-paginating resource lists
- Apply conditional de-pagination to cluster and project bindings. Counts of either over 5000 will mean NO de-pagination happens
- This will ensure users with an amount of resources that the UI can reasonable fetch and cache... are fetched. For users with too many the current functionality continues (some bindings will be missing)
- In the next feature release these changes will most probably be reverted and server-side pagination is used instead
Main change
- change `depaginate` `type` setting from boolean to boolean | function
- depaginate function will conditionally return true
- currently condition only supports a pre-defined count (don't de-paginate if there are too many resources)
In addition / supporting changes
- …
> Add conditional depagination by native api, apply to bindings

- cypress/e2e/tests/pages/extensions/extensions.spec.ts
- cypress/e2e/tests/pages/fleet/gitrepo.spec.ts
- shell/scripts/test-plugins-build.sh
This PR refactors extension uninstall tests so retries work. Currently, if one of the 3 extensions being uninstalled is successfully removed and another is not, when the test re-runs, it fails because its looking for an extension no longer present.
edit: updated the PR to disable the failing fleet test
> refactor extension uninstall tests

- pkg/aks/components/AksNodePool.vue
- pkg/aks/components/CruAks.vue
- pkg/aks/components/__tests__/AksNodePool.test.ts
- pkg/aks/l10n/en-us.yaml
Fixes #10952 
Fixes #11084 
This PR fixes an issue with node labels not being saved - the wrong key was used it should be `nodeLabels`, see `<rancher url>v3/schemas/aksNodePool`. This PR also corrects an issue with the form when saving throws an error ( see the issue for an example misconfiguration - many incorrect cluster configurations either throw inline form validation errors before saving or show up after saving when the user is taken back to the cluster list view)
The problem in #11084 appears to be related to the before save hook removing ui-only fields from AKS node pools. With the `__validation` property missing, some form validators start throwing errors; this sends the whole form out of whack (eg cluster name no longer being editable. idk). I realized as well that the ui-only …
> AKS: fix node labels and errors when saving the cluster fails immediately

- pkg/eks/components/CruEKS.vue
- pkg/eks/components/NodeGroup.vue
- pkg/eks/components/__tests__/CruEKS.test.ts
- pkg/eks/components/__tests__/NodeGroup.test.ts
- pkg/eks/l10n/en-us.yaml
- pkg/eks/types/index.d.ts
Fixes #11102 
Fixes #11202 
Fixes #11103
This PR updates the EKS node group component to disable inputs when the cluster is new _or_ when the current group is being added to a new cluster. It also adds version upgrading functionality in line with AKS  - node groups' versioning.
Create a new cluster with a kubernetes version less than the latest available:
1. Verify that the node group name is editable
2. Verify that adding data to 'instance tags' is reflected in the node group's spec when saving
3. Verify that there is a disabled input whose value aligns with the cluster kubernetes version 
Once that cluster has provisioned, go to edit it and verify that:
1. The name of the existing node group is not editable
2. When a new node group is added, its name is editable
3. When a new node group …
> EKS: fix node group versioning and name input

- shell/components/nav/Type.vue
fixes #10869
Depending on where/how the type component is used different events get triggered at different times. In the case of search we were navigating using the `<a href>` instead of `navigate`. 
Resource navigation
https://github.com/rancher/dashboard/assets/55104481/9e562b73-9edb-4ef9-8c8d-ffe7fc9b17ae
> Resolving an issue where resource search was reloading pages instead of navigating using vue-router

- cypress/e2e/tests/pages/global-settings/settings.spec.ts
- shell/assets/translations/en-us.yaml
- shell/config/settings.ts
- shell/edit/management.cattle.io.setting.vue
Fixes #11138 
This will add the `agent-tls-mode` setting to the Global Settings page, as well as a new optional property `warning` on the `GlobalSettings` interface that will display a warning banner when editing the setting.
The setting is an `enum` with two values: `strict` and `system-store`
To add a warning to the setting, the `advancedSettings.warnings` translation will require a property named after the setting, in this case `agent-tls-mode`.
Testing the setting works with both values, ensure the warning banner shows.
N/A
> Add agent tls mode to global settings

- cypress/e2e/po/detail/fleet/tabs/git-repos-tab.po.ts
- cypress/e2e/tests/pages/fleet/fleet-clusters.spec.ts
- shell/components/fleet/FleetIntro.vue
rancher/dashboard#11198
We were using a broken link. This fixes that broken link.
Just the Add Repository button.
https://github.com/rancher/dashboard/assets/55104481/35439b30-68db-41bf-8fe8-16106266e592
> Fixing the Add Repository button on the fleet cluster detail page

- cypress/e2e/po/components/global-role-binding.po.ts
- cypress/e2e/tests/pages/users-and-auth/users.spec.ts
- shell/components/GlobalRoleBindings.vue
Fixes #11013
This PR fixes the above issue - it applies a sort so that the global permissions are always listed in this order:
Administrator
Restricted Admin
Standard user
User base
An automated test is included.
> Ensure global roles are listed in a consistent order

- shell/package.json
- shell/scripts/publish-shell.sh
Bump extension api version and add `--tag` to release-2.8 yarn publish
PR based on our shell versioning document where `latest` releases are to be done from `master` and older releases are to be done from `release-2.8` branch in order to support pre v2.9 Rancher extensions.
> Bump extension api version and add tag to release-2.8 yarn publish

- pkg/harvester-manager/models/harvesterhci.io.management.cluster.js
- shell/edit/token.vue
- shell/pages/c/_cluster/apps/charts/install.vue
- shell/pages/c/_cluster/uiplugins/InstallDialog.vue
- shell/store/index.js
- shell/utils/version.js
This fixes a few instances where settings are referenced without using the constants. These were discovered while reviewing and validating changes for rancher/rancher#45894
> Replace settings strings with constants

- cypress/e2e/po/components/sortable-table.po.ts
- cypress/e2e/po/pages/explorer/workloads-pods.po.ts
- cypress/e2e/po/prompts/promptRemove.po.ts
- cypress/e2e/tests/pages/explorer/workloads/pods.spec.ts
- shell/components/PromptRemove.vue
- shell/promptRemove/pod.vue
Fixes #11247 
This PR fixes issue where pod deletion dialog remains on screen even after success.
Issue caused by modal refactor - the pod removal dialog references the parent directly by `$parent.$parent.$parent` - which is not great and this changed, causing the breakage.
This PR updates the dialog to not use this reference, instead using the passed in properties.
Automated tests added - check that the dialog closes correctly both via cancel and via delete.
> Fix bug with dialog for pod deletion

- shell/detail/__tests__/provisioning.cattle.io.cluster.test.ts
- shell/detail/provisioning.cattle.io.cluster.vue
Both isImported and isCustom end up being true when using a custom cluster. There's some prior art which seems to indicate swapping the evaluation is acceptable.
Fixes #11160
The root cause was the change in the definition of [isImported()](https://github.com/rancher/dashboard/commit/6d4f75afafe9c0ac43a69c93fd6f085730048c97#diff-d888082c4e23d876ed1154a65f0abf824000d685eda426eee3512d88318f7d2bR246-R259).
I noticed that the provider correctly selected 'custom' on the list page
And that we invert the evaluation of `isImported()` and `isCustom()` in this context so I did the same here.
https://github.com/rancher/dashboard/blob/master/shell/components/formatter/ClusterProvider.vue#L28-L33
Original case described in the issue
> Change the order we evaluate isImported with isCustom

- shell/assets/translations/en-us.yaml
- shell/config/product/auth.js
- shell/edit/auth/__tests__/oidc.test.ts
- shell/mixins/auth-config.js
- shell/models/management.cattle.io.authconfig.js
- shell/store/auth.js
- shell/utils/auth.js
This PR does not fix a targeted issue, although it is related to #11112 
This converts the provider context when using the Generic OIDC provider to use the `genericoidc` id and `genericOIDCConfig` type.
We previously were filtering out the `genericoidc` provider and showing the `oidc` provider. This context needed to be reversed where we are using the `genericoidc` provider when selecting "Generic OIDC" as an authentication provider.
This switches all instances of the `oidc` provider with `genericoidc`.
In `shell/mixins/auth-config.js` I added a ternary to ensure the Keycloak OIDC provider uses the related scope declared in `BASE_SCOPES.keycloakoidc`.
Both Generic OIDC and Keycloak OIDC providers should be tested to ensure there are no regressions. When enabling, editing, or disabling, …
> Switch context for generic oidc provider to the genericOIDCConfig type

- shell/package.json
update shell version to be up to par with latest published version for 2.8
We are now in version `1.2.3` released from `release-2.8` branch
https://www.npmjs.com/package/@rancher/shell?activeTab=versions
> update shell version to be up to par with latest published version for 2.8

- cypress/e2e/po/pages/explorer/charts/chart.po.ts
- cypress/e2e/tests/pages/charts/monitoring-istio.spec.ts
- 104.0.0+up45.31.1 is broken (crd installs, but not main chart)
> Fix monitoring chart version to one that works

- pkg/eks/components/CruEKS.vue
- pkg/eks/components/Logging.vue
- pkg/eks/components/Networking.vue
- pkg/eks/components/__tests__/Networking.test.ts
- pkg/gke/components/CruGKE.vue
- shell/utils/__tests__/kontainer.test.ts
- shell/utils/kontainer.ts
Fixes #11100 
Fixes #11104 
Fixes #10335 
Fixes #11291 
This PR updates EKS provisioning to incorporate the same upstream syncing behavior as AKS - see https://github.com/rancher/dashboard/pull/11120 for some background on why this is needed. This PR adds some fixes to the syncing utility as well as unit tests around the problems I found while working on the PR. There are also some minor fixes around the EKS components to correct console errors shown when editing an imported cluster.
Special notes about EKS:
- imported clusters with no nodeGroups are valid (they may have self-managed nodes)
- After following aws instructions to create an EKS cluster with default values and importing it into Rancher, the subnet/virtual network configuration is indistinguishable from an EKS cluster …
> EKS: edit imported clusters, and clusters with exclusively self-managed nodes

- cypress/e2e/tests/pages/manager/kontainer-drivers.spec.ts
- cypress/e2e/tests/pages/manager/node-drivers.spec.ts
- shell/assets/translations/en-us.yaml
- shell/dialog/DeactivateDriverDialog.vue
- shell/models/driver.js
- shell/models/kontainerdriver.js
- shell/models/nodedriver.js
- shell/pages/c/_cluster/manager/drivers/kontainerDriver/index.vue
- shell/pages/c/_cluster/manager/drivers/nodeDriver/index.vue
Fixes #11046
Fixes #10718 
Fixed deactivate driver bulk action, fixed displaying driver id instead of name for drivers that do not have translation.
Additionally, changed bulk activation action to follow pattern similar to other models.
When provisioning a cluster, driver name is used instead of the id.
N/A
[] Test that driver name is shown instead of id for non-builtin driver
[] Test that driver can be activated on its own
[] Test that drivers can be activated in bulk
[] Test that driver can be deactivated on its own
[] Test that drivers can be deactivated in bulk 
- Driver name is displayed instead of id inside of the cluster creation wizard.
> [FIX] Fixed some issues with driver pages

- pkg/gke/components/GKENodePool.vue
- pkg/gke/components/__tests__/GKENodePool.test.ts
- shell/components/form/KeyValue.vue
- shell/components/form/Taints.vue
- shell/components/form/__tests__/Taints.test.ts
Fixes #11293 
This PR fixes GKE node pool taints. The underlying issue appears to be the effect options' values, which should be uppercase snake case instead of camel case.
The PR expands functionality of the Taints component and adds unit tests to verify that default behavior is unaltered.
Verify new behavior in GKE provisioning following the steps in #11293 
Verify default Taints.vue behavior still works by creating an RKE2 cluster with taints 
- taints appear in the advanced section of the machine pool form
- they will show up in the request to create the provisioning cluster object under `spec.rkeConfig.machinePools[].taints`
> GKE: fix node pool taint effect options

- cypress/e2e/tests/pages/generic/loading.spec.ts
- shell/config/router/navigation-guards/i18n.js
- shell/config/router/navigation-guards/index.js
- shell/initialize/entry-helpers.js
- shell/middleware/authenticated.js
This resolves two issues around harvester i18n and harvester cluster page reload failures.
Fixes #11349
Fixes #11350
- i18n
- i18n we needed to ensure that `i18n/init` was invoked after the harvester plugin was loaded and added it's own strings. Previously this was done in authenticated middleware which was run before each (nearly every) page was rendered. This is now done as a part of a router navigation guard and is ran just as frequently as it used to be,
- Page refresh
- There was compounding factors which caused this but effectively we were no longer loading dynamic plugins in the authenticated middleware on 404s. I pulled the logic out of the authenticated middleware and put it in our render method. We probably want to get rid of this concept all together.
Harvester cluster pages
> Harvester i18n and page reload fixes

- shell/components/AlertTable.vue
- shell/components/GrafanaDashboard.vue
Fixes #11347
- Alerts - v1 endpoint no longer available in newer versions of the monitoring chart, so use v2 and fall back on v1 if not available
- Charts - Granfana charts now have unique class names (used to determine if loading indicator should be hidden). So we check for partial class names instead.
Note 1 - Charts fail to render when running the dashboard locally. To test this i created a `richard-dev` build, available to use with the `ui-dashboard-index`  setting
Note 2 - The latest chart fails to install, however with Preferences --> Helm Charts --> Include Prerelease checked there should be an RC version just below the latest helm chart version which will work and contain the breaking ui changes
- Cluster dashboard Metrics tabs
- Node Detail Metric tab
- Deployment Detail Metric …
> Fix two monitoring issues after chart bump

- shell/components/nav/Header.vue
Fixes https://github.com/rancher/dashboard/issues/11350
When reloading the page, the `currentProduct` in Header.vue component is undefined.
> Fixing harvester cluster page reload `currentProduct` null

- pkg/harvester-manager/config/harvester-manager.js
- shell/initialize/entry-helpers.js
Fixes #11350
- It fixes path parsing so it can get the `clusterId` from both local & production URLs.
- It fixes `router.resolve` to consider the Harvester routing.
I pushed the same changes in https://github.com/rancher/dashboard/tree/harvester-fix-3-dev so you can test the production build using the following ui configurations:
> Fixing harvester cluster page reload routing

- shell/config/router/navigation-guards/attempt-first-login.js
- shell/config/router/navigation-guards/authentication.js
- shell/config/router/navigation-guards/harvester.js
- shell/config/router/navigation-guards/i18n.js
- shell/config/router/navigation-guards/index.js
- shell/config/router/navigation-guards/load-initial-settings.js
- shell/config/router/navigation-guards/runtime-extension-route.js
- shell/config/router/routes.js
- shell/initialize/entry-helpers.js
- shell/pages/404.vue
This is done by providing a 404l page which is authenticated.
Fixes #11350
We will still need the fix from https://github.com/rancher/dashboard/pull/11359/commits/be1e27b0630d32d2309c5d3969643f5fa84df014 for prod.
404 routing.
Harvester routing.
Regular 404:
https://github.com/rancher/dashboard/assets/55104481/5d3d2fc8-0cbd-4d20-99e0-59dda8a0d8e3
Harvester 404:
https://github.com/rancher/dashboard/assets/55104481/310f10e4-6881-402f-8952-a55f9b846d82
I noticed a flicker of the resource page on this one. I can only reproduce this on the harvester cluster  but it's in `master` and unrelated to both this PR and harvester itself. If anyone else can reproduce this I'll resolve it as a separate issue.
> Handle harvester loading in a route guard to better handle the unauthenticated method.

- shell/pages/auth/login.vue
- shell/pages/auth/setup.vue
Fixes an issue where we were rendering the wrong loading screen layout. It was just a little jarring if the page took some time to load. I think we should actually work on just having the spinner show until the page fully loads but that's beyond the scope of this fix.
We want the loading component relative in these two areas because they aren't a part of our clusters and don't use that layout.
This issue was introduced in https://github.com/rancher/dashboard/commit/7d282bf1d0201f68eb034c3a5e669298dc1902cf
Login and setup pages.
Broken:
https://github.com/rancher/dashboard/assets/55104481/e30ed1bf-c736-4961-bcb2-86743b34bb35
Fixed:
https://github.com/rancher/dashboard/assets/55104481/11fc256c-06c7-40d9-a90c-6c20b451e134
> Relative mode for the loading component will make it appear full screen

- pkg/aks/util/__tests__/validators.test.ts
- pkg/aks/util/validators.ts
Fixes #11381 
This PR updates the AKS PrivateDNSZone validator to allow the value 'system' as well as a private dns zone resource id (previously validated per https://github.com/rancher/dashboard/issues/7163
If an AKS cluster with private cluster is created with PrivateDNSZone left blank, it will be auto-filled with 'system' when the cluster is successfully provisioned, see the first bullet-point here: https://learn.microsoft.com/en-us/azure/aks/private-clusters?tabs=azure-portal#configure-a-private-dns-zone
1. Create a private AKS cluster with PrivateDNSZone left empty.
2. Navigate to the cluster's detail page and copy the command shown
3. Open the azure portal ui, navigate to 'kubernetes services' and select the cluster you just created
4. Once the cluster is 'running' use the 'run …
> AKS - update privateDNSZone validator to allow 'system' value

- pkg/gke/components/Networking.vue
- pkg/gke/components/__tests__/Networking.test.ts
Fixes #11391 
This PR updates the GKE networking component to allow editing the master authorized network cidr block keyvalue input. Per #11391, that keyvalue should be editable all the time but when a cluster is provisioned the master authorized checkbox  should not be editable.
1. Provision a GKE cluster - under the 'advanced' section in networking you should be able to enable master authorized networks and add some cidr blocks
2. Once the cluster has finished provisioning, edit it and verify that you can update the list of cidr blocks
> GKE - allow user to edit master authorized network in provisioned clusters

- pkg/eks/components/CruEKS.vue
- pkg/eks/components/NodeGroup.vue
- pkg/eks/components/__tests__/NodeGroup.test.ts
- pkg/eks/l10n/en-us.yaml
Fixes #11390 
This PR updates the EKS provisioning form to fetch a list of ec2 ssh keys and populate a dropdown in the node group tab.
Functionality is copied from the Ember UI implementation: the list of ssh keys uses the `KeyName` property. The user also has the option of manually typing in a key name - in Ember, this was handled by swapping out the dropdown for a text input if no ssh keys were found. In this form, I've just allowed the user to type in their own key regardless of the list because it seems tidier.
1. Open the EKS cluster creation page and verify that there is a dropdown of key options in each node group. A good region to test would be `us-west-1`
2. When switching regions, a new list of keys should be loaded
3. After selecting an ec2 key, switch regions: if there's no …
> Add dropdown of ssh keys to EKS node groups

- shell/config/pagination-table-headers.js
Contributes to https://github.com/rancher/dashboard/issues/9545
- Currently isn't possible to sort/filter on fields like id and metadata.state.name
- Note - Server-side pagination is not supported in production atm and is in a 'trial' state. Once ready for production these will be supported
- So for server-side lists ensure we don't sort / filter by either
- column definitions used by server-side pagination should not define sort/filter fields
- should not be listed as supported in validation `shell/plugins/steve/steve-pagination-utils.ts` `VALID_FIELDS` (already done)
- This should be addressed in the next1 release (currently line item in https://github.com/rancher/rancher/issues/45635)
- With ui-sql-cache feature flag on, and servier-side performance setting enabled
- lists that use …
> Ensure current lack of server-side sorting/filtering on generated fields is handled

- shell/edit/provisioning.cattle.io.cluster/__tests__/DirectoryConfig.test.ts
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
- shell/edit/provisioning.cattle.io.cluster/tabs/DirectoryConfig.vue
Fixes #11397 
- fix issue with dataDirectories object being empty by initializing missing properties and adding optional chaining for increased code resilience
- add unit test
- Connect this PR's branch to the shared env and edit the cluster `fra-vgpu-allocation` and make sure there are no console errors and that edit succeeds.
https://github.com/rancher/dashboard/assets/97888974/244f45ae-0c80-414b-ab55-874bd19f1246
> Fix console errors in Harvester cluster's provisioning page

- pkg/aks/components/CruAks.vue
- pkg/aks/util/__tests__/validators.test.ts
- pkg/aks/util/validators.ts
Fixes #11405 - see comments for expected behavior
This PR updates the node pool name validator to check length as well as characters.
Open the AKS provisioning form and enter a pool name with >12 characters 
1. You should be prevented from saving
2. There should be an error icon in the node pool name input
3. If you add another pool and switch pool tabs, the inactive tab with validation error should have an error icon
> add node pool name length validation and refactor to allow unit tests

- pkg/eks/components/Config.vue
- pkg/eks/components/CruEKS.vue
- pkg/eks/components/__tests__/Config.test.ts
- pkg/eks/l10n/en-us.yaml
Fixes #11389 
This PR restricts users from upgrading their EKS clusters more than one minor version at a time
1 creating a new EKS cluster- users should be able to select versions 1.27, 1.28, 1.29 and 1.30
2. Editing an existing EKS cluster with a version >1 minor version behind the latest: users should only be able to pick the next minor version
> do not allow eks version upgrades >1 minor version

- pkg/eks/components/CruEKS.vue
- pkg/eks/components/Networking.vue
- pkg/eks/components/__mocks__/describeSecurityGroups.js
- pkg/eks/components/__mocks__/describeSubnets.js
- pkg/eks/components/__tests__/Networking.test.ts
- pkg/eks/l10n/en-us.yaml
- pkg/eks/types/aws-sdk.d.ts
Fixes #11412 
This PR adds a dropdown to select security groups when selecting an existing subnet. It also prevents the user from selecting subnets from different VPCs. I noticed the Ember UI doesn't have that restriction but EKS throws an error if you try to create a cluster using multiple VPCs. Security groups are scoped by VPC so allowing the user to select multiple VPCs would undermine the security group feature... Consequently, I fixed the multi-VPC issue as part of this PR, despite that not being explicitly called out in #11412 
1. Creating EKS cluster - verify that you can select security groups and their GroupId shows up in the network request under eksConfig.securityGroups
2. Edit EKS cluster - verify that, while you can't edit security groups the dropdown still shows previously …
> EKS - add ability to specify additional security groups

- shell/mixins/__tests__/chart.test.ts
- shell/mixins/chart.js
Fixes #11126
- When refreshing or navigating directly to the chart install page the chart was missing
- This was caused by the chart install page's mixin's computed property `chart` value never populating
- The computed method would be called, but before charts were loaded
- When charts loaded the computed property did not trigger again
- Whenever this.chart was used it would contain the stale value (falsy)
- Fix
- `chart` value must now be manually populated,
- this happens via existing `fetchChart`
- should be safe, given it's called by both `chart install` and `chart detail` page's $fetch
- Navigating to via dashboard links, also refreshing directly on the following pages
- Cluster tools --> Install App
- Cluster tools --> Upgrade App
- Apps --> Charts --> chart
- Apps --> Charts --> …
> Fix reload on chart install page

- cypress/e2e/tests/pages/generic/about.spec.ts
- cypress/e2e/tests/pages/generic/home.spec.ts
We have a few e2e tests failing because the server-version setting is set to `dev` instead of the usual version + commit id (eg `v2.9-3c4ccdc5bc9fde3510089153b5ad58fdbe604880-head`). Could be tied to this release blocker https://github.com/rancher/rancher/issues/46160
> Disable e2e tests that rely on the server-version setting

- pkg/eks/components/Config.vue
- pkg/eks/components/__mocks__/describeAddonVersions.js
- pkg/eks/components/__tests__/Config.test.ts
Fixes #11438 
#11438 reports an issue with the formatting of the node group version. It looks like the default value of the cluster kubernetes version was formatted incorrectly, leading to the node group version being wrong too.
The root cause of #11438 is a change in the structure of the list of k8s versions shown in the UI, done as part of https://github.com/rancher/dashboard/pull/11411. I've added unit tests that explicitly check that the kubernetes version is set with the right format when it is initially set. 
Create a new EKS cluster without changing the cluster kubernetes version and verify that:
1. The node group version is displayed correctly 
2. The POST request to create the cluster includes the correct `eksConfig.kubernetesVersion` (should be "1.30" at this time)
> EKS: fix k8s version selection

- shell/plugins/dashboard-store/getters.js
Contributes to https://github.com/rancher/dashboard/issues/7773
When `all` namespace filter selected the counts shown in side nav excluded resources in 'obscure' namespaces (c-, p-, user-, local-). However lists would show them (counts missaligned).
When anything other than `all` namespace filter is selected resources in obscure namespaces were filtered out from both side nav and list (counts align).
This is only visible for resources that are in those obscure namespaces, which isn't many
- A new `counts` getter was created to improve performance of the side nav (specifically Type component)
- https://github.com/rancher/dashboard/commit/48d5695359c60c2ba28d266adff0eeb803f1d357#diff-53d2b9025f17bb20287d00cbf1b9de5d7d43bd21b4c7d74c86ae2085e07936c6R381
- This contained the functionality from …
> Ensure count shown in side nav is correct

- shell/config/uiplugins.js
Fixes #https://github.com/rancher/elemental-ui/issues/202
- Add check for `head` string on Rancher version in dev builds so that QA can test Elemental releases properly
**Only occurs for head/dev builds of Rancher**
The `rancherVersion` in this particular case is `v2.9-a402bfa1ff0cc051cfabe3d9380b7eca678443f9-head` string which won't meet the condition in https://github.com/rancher/dashboard/blob/master/shell/config/uiplugins.js#L195 `isRancherVersionHashString` which was the only condition that defined versions that were "head" builds of some sort. With the inclusion of the above, these strings for `rancherVersion` would fall on the category to have this check ignored
- Go to `Extensions` -> try to install Elemental on a head build (I can provide access to a system with this problem)
- …
> encompass 'head' string as condition to allow installation of extension in dev builds

- cypress/e2e/tests/pages/generic/about.spec.ts
This reverts commit 2b0dcd639137101fe73783c5967efec037bf6619.
Fixes #11387 
This PR reinstates some failing e2e tests - -rc5 CLI builds appear to have been uploaded as expected, so these tests should pass now
> Revert "Remove download cli tests"

- pkg/aks/components/CruAks.vue
- pkg/aks/l10n/en-us.yaml
- pkg/aks/util/validators.ts
Fixes #11406 
This PR updates the AKS provisioning form to correct an issue with `Tab` props - duplicate pool names caused a problem due to tabs not having unique keys. This PR also adds validation for AKS pool name uniqueness. 
It's pretty easy to wind up with duplicate pool names here. In an effort to avoid adding QA burden to the fast-approaching 2.9.0 release I've filed a separate issue to improve node pool/group default naming more generally in a later release (https://github.com/rancher/dashboard/issues/11451), as technically, that is not a release-blocker (the workaround is immediately obvious: manually re-name any duplicate pools you've inadvertently created).
To clarify the `Tab` props in play here: in `CruAKS` `Tab` components need a `key` prop because they're part of a `v-for …
> AKS - fix tab component behavior when there are duplicate node pool names

- pkg/eks/components/CruEKS.vue
- pkg/eks/components/__tests__/CruEKS.test.ts
Fixes https://github.com/rancher/dashboard/issues/9905 - https://github.com/rancher/dashboard/issues/9905#issuecomment-2232680677
The EKS form was attempting to set `enableNetworkPolicy` (labeled "Project Network Isolation" in the UI) at the eksConfig level - it needs to be set higher in the cluster spec. 
1. Create an EKS cluster with 'project network isolation' checked - verify that the POST request has `<norman cluster>.enableNetworkPolicy: true`
2. Edit the EKS cluster - verify that the project network isolation checkbox is checked. Uncheck it and verify that the change is persisted
> EKS - fix project network isolation checkbox

- pkg/eks/components/CruEKS.vue
- pkg/eks/components/NodeGroup.vue
- pkg/eks/l10n/en-us.yaml
- pkg/eks/util/__tests__/validators.test.ts
- pkg/eks/util/validators.ts
Fixes #10510 specifically https://github.com/rancher/dashboard/issues/10510#issuecomment-2233654804
This PR adds validation for EKS node group min/max/desired size in relation to each other. I used the form validation mixin, but I have added an error banner rather than input-level error messages because of the way the mixin functions - validators run on individual inputs only receive the context of that input, and this validation needs to cover 3 input fields in tandem. 
Some unit tests added, but manual testing is still advisable as unit tests can't reasonably cover form validation mixin behavior. 
1. Verify that users cannot save EKS clusters with any node groups that have:
- min size greater than max size
- desired size less than min size
- desired size greater than max size
> EKS - add validation for node group desired size

- cypress/e2e/tests/pages/generic/about.spec.ts
- cypress/e2e/tests/pages/generic/home.spec.ts
> Reinstate e2e tests that rely on server-version setting

- pkg/eks/components/Config.vue
- pkg/eks/components/CruEKS.vue
- pkg/eks/components/NodeGroup.vue
- pkg/eks/components/__tests__/Config.test.ts
- pkg/eks/components/__tests__/NodeGroup.test.ts
- pkg/eks/l10n/en-us.yaml
- pkg/eks/types/index.d.ts
Fixes #11460 
This PR updates the EKS provisioning form to prevent users from upgrading the cluster (control plane) k8s version more than one minor version ahead of any node groups in the cluster.
1. Create an EKS cluster with an older version eg 1.27, upgrade it & edit it again - the version input should be disabled with a warning about node groups
2. Check all nodegroup upgrade checkboxes - the cluster version dropdown should stay disabled
3. Save the cluster
4. Edit again - now that nodegroups are the same version as the cluster, you should be able to upgrade the cluster again
> EKS - do not allow upgrades if any node groups would fall more than one minor version behind

- shell/pages/c/_cluster/settings/performance.vue
- shell/utils/settings.ts
Fixes #11496
- 2.8 based bug
- Only reproducible when
- performance settings have been changed
- navigating from performance page to list page
- prod build
- Root effect
- Constant trigger of two computed properties
- namespaceFilterRequired 
- shell/mixins/resource-fetch-namespaced.js 
- namespaceFilter --> __namespaceRequired --> value (all same colour, suggesting our code)
- tracing shows this also to start from shell/mixins/resource-fetch-namespaced.js
- Issue
- It looks like additional reactivity was happening around the `DEFAULT_PERF_SETTING` object
- This meant computed properties were continually being called making the browser hang
- Fix
- shell/pages/c/_cluster/settings/performance.vue removed assignment to component `data
- this alone would fix the issue
- vue will add …
> Fix navigation from Global Settings --> Performance to any Cluster Explorer custom list

- shell/components/form/ResourceLabeledSelect.vue
- shell/components/form/labeled-select-utils/labeled-select.utils.ts
- shell/plugins/dashboard-store/actions.js
- shell/types/store/pagination.types.ts
Fixes #11507
No Options Shown
- Ensure all ResourceLabeledSelect attributes reach LabelSelect component
- This worked at some point, but $attrs now does not contain values that are defined as component props
Cannot `Load More` options
- `Pages` param Missing in API response
- This has been removed, work around added
Search term isn't matching partial results
- ensure exact filter matching is off
- `pages` param was on the old api, seeking clarrification if it's never been there on the new api (not sure how i missed it) or it was recently removed
- vue attrs param was also weird, as this felt like it must have worked when the PR was created, tested and reviewed
- As per https://github.com/rancher/dashboard/pull/10786 test plan
- Quick validation of paginated list with server-side …
> Paginated Label Select Fixes

- shell/config/uiplugins.js
Backport - Fixes #https://github.com/rancher/elemental-ui/issues/202
Based on: https://github.com/rancher/dashboard/pull/11448
- Add check for `head` string on Rancher version in dev builds so that QA can test Elemental releases properly
**Only occurs for head/dev builds of Rancher**
The `rancherVersion` in this particular case is `v2.9-a402bfa1ff0cc051cfabe3d9380b7eca678443f9-head` string which won't meet the condition in https://github.com/rancher/dashboard/blob/master/shell/config/uiplugins.js#L195 `isRancherVersionHashString` which was the only condition that defined versions that were "head" builds of some sort. With the inclusion of the above, these strings for `rancherVersion` would fall on the category to have this check ignored
- Go to `Extensions` -> try to install Elemental on …
> Backport fix for elemental-ui issue 202

- .github/workflows/scripts/install-codecov.sh
- .github/workflows/test.yaml
- .gitignore
Fixes https://github.com/rancher/dashboard/issues/11106
- It re-enables tests coverage upload using the Codecov CLI.
- Using `codecov/codecov-action` is discouraged (issue available on request)
- Wait for coverage action to be completed, example: https://github.com/rancher/dashboard/actions/runs/9942926643/job/27465670805
- Click on the link from Github action log to be redirected to the Codecov homepage, example:
> Upload Codecov report using CLI 

- cypress/e2e/tests/pages/explorer/apps/charts.spec.ts
- cypress/e2e/tests/pages/explorer/apps/repositories.spec.ts
- Fix `Charts have expected icons` - `External IP Webhook` app was removed, we were checking it for a generic icon
- Fix `Repo Refresh results in correct api requests` - errent requests for chart icons were being treated as requests for a chart... which the test was ensuring were not happening. made this more resilient 
- Make Apps Repositories tests more resilient to cypress retries
- needs a forward port
> Fix two e2e tests given chart changes

- cypress/e2e/tests/pages/manager/jwt-authentication.spec.ts
- shell/pages/c/_cluster/manager/jwt.authentication/index.vue
- shell/plugins/steve/__tests__/getters.test.ts
- shell/plugins/steve/getters.js
Changed JWT Authentication page to disable ClusterProxyConfigs instead of removing
Fixes #11444 
The original behavior was to remove ClusterProxyConfig in the corresponding namespace if JWTA for that cluster is disabled. This change sets it to disabled instead.
This required changes to excludeFields behavior:
Current behavior: 'metadata.managedFields' is always excluded. If a list of fields to exclude is provided, 'metadata.managedFields' is appended to that list
New behavior: if a list of fields to exclude is provided, we just use it. A new option 'omitExcludeFields' is provided to make it possible to overwrite default exclude fields behavior.
JWT Authentication page:
- Check that JWTA can be enabled, disabled, and re-enabled for clusters. (covered by existing tests)
- Check that …
> [FIX] Changed JWT Authentication page to disable ClusterProxyConfigs

- package.json
- shell/vue.config.js
- yarn.lock
This replaces `@nuxt/babel-preset-app` with `@babel/preset-env` to support the effort of replacing nuxt dependencies throughout Dashboard.
Fixes #11375
It's important to note that `@babel/preset-env@7.21.4` is a transitive dependency of `@vue/cli-plugin-babel` that's hoisted from rancher components
```
➤ yarn why @babel/preset-env                                                                        
yarn why v1.22.19
[1/4] Why do we have the module "@babel/preset-env"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@babel/preset-env@7.21.4"
info Reasons this module exists
- "_project_#@rancher#components#@vue#cli-plugin-babel#@vue#babel-preset-app" depends on it
- Hoisted from …
```
> Replace `@nuxt/babel-preset-app` with `@babel/preset-env`

- shell/components/templates/blank.vue
- shell/components/templates/default.vue
- shell/components/templates/home.vue
- shell/components/templates/plain.vue
- shell/config/middleware.js
- shell/config/router/navigation-guards/authentication.js
- shell/config/router/navigation-guards/clusters.js
- shell/config/router/navigation-guards/history.js
- shell/config/router/navigation-guards/index.js
- shell/config/router/navigation-guards/products.js
- shell/initialize/entry-helpers.js
- shell/middleware/authenticated.js
- shell/store/index.js
- shell/utils/auth.js
Remove the remaining bits of the authenticated middleware
Moving the remaining bits to navigation guards.
Harvester clusters, products and cluster loading
> Remove the remaining bits of the authenticated middleware

- shell/config/router/routes.js
This ensures that paths are non-empty strings. Empty strings in paths aren't an issue now, but will have an effect on properly matching routes when migrating to Vue3. 
Vue router provides a path matching tool that can be used to debug potential issues[^1]. Using this tool with our current route definition will produce the following error:
```
Error parsing routes:
Invalid route at position 2: Property "path" must be a non-epmty string
```
This doesn't appear to be an issue in Vue2, but it's safe to fix this now so that there's less to track and troubleshoot for Vue3.
[^1]: https://paths.esm.dev/?p=AAMsIPQgYAEL9lNgQAECUgPgDIFiDgCg#
Anything that touches routing
- login
- logout
- navigating clusters
- navigating extensions
Anything that touches routing
- login
- logout
- navigating …
> Ensure that route paths are non-empty

- shell/config/router/navigation-guards/runtime-extension-route.js
contains ported partial fixes for https://github.com/rancher/dashboard/issues/9814
> Fixing harvester cluster page reload routing + Harvester console button

- package.json
- shell/package.json
- yarn.lock
Discovered that `@innologica/vue-dropdown-menu` is unused in our project while working on Vue3 migration. I think that we should get rid of it if we don't use it.
Fixes #11562
- Remove unused dependency `@innologica/vue-dropdown-menu`
- No usages of `@innologica/vue-dropdown-menu` throughout Dashboard, this looks safe to remove
- Any code that might have used `@innologica/vue-dropdown-menu`; I don't see any references in Dashboard 
- Any code that might have used `@innologica/vue-dropdown-menu`; I don't see any references in Dashboard
> Remove unused dependency `@innologica/vue-dropdown-menu`

- cypress/e2e/tests/pages/users-and-auth/index.spec.ts
- shell/composables/useI18n.ts
- shell/composables/useLabeledFormElement.ts
- shell/composables/useUserRetentionValidation.test.ts
- shell/composables/useUserRetentionValidation.ts
- shell/config/settings.ts
- shell/mixins/labeled-form-element.ts
- shell/pages/c/_cluster/auth/user.retention/index.vue
- shell/types/resources/settings.d.ts
This adds additional validation rules to the user retention form. The following validations have been added:
- Disable/Delete after
- validate the duration format `{h|m|s}`
- disallow fractional seconds
- validate that the value is greater than `auth-user-session-ttl-minutes`
- Delete after
- validate that the value is greater than 336h0m0s
Additional changes have been made to support the validation changes:
- Add `requireDirty` prop to the `useLabeledFormElement` composable under `shell/composables/useLabeledFormElement.ts`
- Emit `update:validation` events when validation fails for a given input
Fixes #11333 
- User Retention form
- Disable user after inactivity period validation
- Delete user after inactivity period validation
- User retention process schedule validation
- Validations …
> Introduce additional form validation for User Retention

- shell/components/ResourceList/Masthead.vue
This resolves an issue where the clickable area for the user retention settings link would span the width of its container.
Fixes #11338 
- Change the display mode for this anchor tag to `inline-block`
- Users page
- Ensure that content reflows properly when resizing the page
> Limit width of User retention settings link to contents

- shell/pages/c/_cluster/explorer/index.vue
Fixes #11524
- The Cluster Dashboard --> Certificates Tab --> Certificates list uses a filter that is not compatible with the Vai backed api
- So hide the tab when vai is enabled
- This is a 2.9 issue only, in 2.10 the table should be updated to handle the different way of filtering
As per issue
> Hide Certificates table if vai is enabled

- shell/assets/translations/en-us.yaml
- shell/edit/provisioning.cattle.io.cluster/__tests__/DirectoryConfig.test.ts
- shell/edit/provisioning.cattle.io.cluster/tabs/DirectoryConfig.vue
Backport - Fixes #11566 
- remove checkbox from `dataDirectories` cluster config
- Go to RKE2 cluster creation interface and make sure the `data configuration` area is present on the `Advanced` tab of Cluster Configuration
- Make sure data persists and all works fine
- Make sure that cluster editing, the `data configuration` is disabled (not allowed to change the values)
https://github.com/user-attachments/assets/8be24e9c-ecd7-4b7b-a9be-89a1371c6174
> Backport 11560 - remove checkbox from `dataDirectories` cluster config

- shell/assets/translations/en-us.yaml
- shell/cloud-credential/__tests__/harvester.test.ts
- shell/cloud-credential/harvester.vue
Original issue #11317 
Backport #11269 
Go to Cloud Credentials page => Click on Create => Choose Harvester, alternatively you can also see it if you have no Harvester credentials and you go to create a Harvester Cluster
> Backport harvester cloud creds warning

- pkg/eks/components/Config.vue
- pkg/eks/components/CruEKS.vue
- pkg/eks/components/__mocks__/listKeys.js
- pkg/eks/components/__tests__/Config.test.ts
Fixes #11558 
This PR updates the EKS provisioning form to set `eksConfig.secretsEncryption` when the 'Encrypt Secrets with a KMS key' checkbox is checked.
1. Create an EKS cluster, check the 'Encrypt secrets' checkbox and select a key. Verify that the save request includes `eksConfig.secrets.Encryption: true`
2. Wait for the cluster to provision; edit the cluster and verify that the kms key arn is shown in the form ,but is not editable
> EKS - fix secrets encryption with KMS key checkbox

- shell/pages/index.vue
Previously the page would just redirect using middleware so the template was never looked at. This puts in an empty template since we don't intend to render anything on this page.
fixes https://github.com/rancher/dashboard/issues/11585
> Fixing a warning where we didn't have a template tag

- shell/core/plugins.js
Fixes https://github.com/rancher/dashboard/issues/11563
> [backport v2.9.next1] Remove old extension from parentElement

- cypress/e2e/tests/pages/manager/jwt-authentication.spec.ts
- shell/pages/c/_cluster/manager/jwt.authentication/index.vue
- shell/plugins/steve/__tests__/getters.test.ts
- shell/plugins/steve/getters.js
Changed JWT Authentication page to disable ClusterProxyConfigs instead of removing
Backport - Fixes #11462 
The original behavior was to remove ClusterProxyConfig in the corresponding namespace if JWTA for that cluster is disabled. This change sets it to disabled instead.
This required changes to excludeFields behavior:
Current behavior: 'metadata.managedFields' is always excluded. If a list of fields to exclude is provided, 'metadata.managedFields' is appended to that list
New behavior: if a list of fields to exclude is provided, we just use it. A new option 'omitExcludeFields' is provided to make it possible to overwrite default exclude fields behavior.
JWT Authentication page:
- Check that JWTA can be enabled, disabled, and re-enabled for clusters. (covered by existing tests)
- Check …
> BP: [FIX] Changed JWT Authentication page to disable ClusterProxyConfigs

- cypress/e2e/tests/pages/manager/cluster-manager.spec.ts
- cypress/globals.d.ts
- cypress/support/commands/rancher-api-commands.ts
Issue
- Request counted on a specific value of a specific feature flag
- This was supplied by intercepting the request for all FFs and returning the desired one
- However the FF response supplied missed the `revision`
- The `revision` is used to watch for changes to the resource from a given point in history
- If no revision is supplied rancher will return the current value
- In the FF world this meant the intercepted response was overwritten by the actual value
Solution
- Fetch the rancher specific revision up front and then add to the intercept
I am slightly intrigued why this now fails more / repeatidly. It could be a timing thing (test completed before the socket message containing the real value was processed, or gh runner now is more performant), update thing (nuxt et al changes …
> Fix rke1-ui feature flag test

- shell/models/management.cattle.io.cluster.js
- shell/models/provisioning.cattle.io.cluster.js
- shell/pages/home.vue
- shell/plugins/steve/hybrid-class.js
Fixes #11588
- mgmt cluster is a steve resource, so can inherit the steve model
- this resolve the issue of mgmt cluster not having a description
- prv cluster uses it's own description, falls back on mgmt description
- custom stuff on home screen not needed
- fixes description on detail page of legacy clusters
- remove description from hybrid model
- this contains steve references and isn't needed
home page prov.description --> prov's description from extended steve model || mgmt's description from extended steve model
- One of EKS/AKS/GKE cluster created in old ui AND RKE2 cluster description should display on 
- home page cluster list
- side nav 
- cluster's detail page
- Automated tests have been written for description in
- https://github.com/rancher/dashboard/pull/10487/files
- …
> Fix home page cluster description scaling issue

- pkg/eks/components/CruEKS.vue
- pkg/eks/components/__tests__/CruEKS.test.ts
- pkg/eks/l10n/en-us.yaml
- pkg/eks/util/validators.ts
Fixes #11570 
This issue adds form validation to prevent users from saving EKS clusters with no node groups defined. This validation is not applied to imported EKS clusters because they may not require managed node groups.
* when editing EKS clusters provisioned through Rancher, users shouldn't be able to save clusters with no node groups
* users should still be able to save clusters with no node groups if the clusters are imported
> EKS - validate that at least one node group is defined

- pkg/eks/components/CruEKS.vue
- pkg/eks/components/__tests__/CruEKS.test.ts
- pkg/eks/l10n/en-us.yaml
- pkg/eks/util/validators.ts
Backport of https://github.com/rancher/dashboard/pull/11604
Fixes #11603
> [2.9.next1] EKS - validate that at least one node group is defined

- shell/scripts/test-plugins-build.sh
Added capi-ui-extension to the list of extensions to test with.
Fiixes #11415
N/A
N/A
N/A
N/A
> [INT] Added CAPI ui to the list of extensions to test

- shell/assets/translations/en-us.yaml
- shell/config/settings.ts
- shell/edit/management.cattle.io.setting.vue
* Add agent tls mode to global settings
* Update shell/assets/translations/en-us.yaml
* Move agent test to avoid issues with _ and local for cluster name based on previous test
---------
Fixes #11488
Backport of https://github.com/rancher/dashboard/pull/11287
> [Backport] Add agent tls mode to global settings (#11287)

- shell/initialize/App.vue
Fixes #11617
Issue can be reviewed with dev release https://github.com/rancher/dashboard/tree/nuxt-removal-dev
It contains the same picked commit.
> Restore Nuxt global variable for Harvester compatibility

- shell/components/form/Members/ClusterPermissionsEditor.vue
- shell/components/form/ProjectMemberEditor.vue
> fix(Project/ClusterMemberEditor): fix find roleTemplates bug

- shell/assets/translations/en-us.yaml
- shell/components/auth/RoleDetailEdit.vue
- shell/config/roles.ts
Fixes #11646
Generally....
- When creating roles (global, cluster or project/namespace) users specify grants on specific resources
- To help users we provide a list of resources to select
- These resources come from a set of hardcoded list
-  global - specifically global resources (basically resources expected to be in the local/upstream cluster)
-  cluster - non-namespaced resources
-  project/namespace - namespaced resources
- There's a component that handles role creation for the 3 different roles
- We don't show only the respective global, cluster, or project/namespace resources for each context
- global role - shows global, cluster and project/namespace options
- cluster role - shows cluster and project/namespace options
- project/namespace role - shows project/namespace options …
> Fix duplicate group and options when creating global, cluster and project/namespace roles

- pkg/aks/components/CruAks.vue
- pkg/aks/components/__tests__/CruAks.test.ts
Fixes #11634 
This PR fixes the default name value used when an AKS node pool is added to a cluster with no pools.
> AKS - fix default pool name

- cypress/e2e/tests/priority/vai-setup.spec.ts
- shell/pages/c/_cluster/settings/performance.vue
Fixes #11497
- Ensure that on cancel of incompatible performance settings modal the checkbox remains unchecked
- Do this by externally controlling the state of the checkbox in all scenarios
- As per description, plus edge cases
- Once pagination setting enabled refresh page and ensure checkbox continues to work as expected
> Ensure Performance --> Pagination setting only enables post compatible check

- shell/models/__tests__/apps.deployment.test.ts
- shell/models/apps.deployment.js
Fixes https://github.com/rancher/dashboard/issues/10236
Added a condition to the `replicaSetId` getter method in the Deployment class to accurately fetch the latest replicaSetId
`relationship.message.split(':')[1].trim() > 0;`
The issue seems to be that the get replicaSetId [method](https://github.com/rancher/dashboard/blob/master/shell/models/apps.deployment.js#L14) is not accurately identifying the correct ReplicaSet associated with the latest Deployment update. Let's say if you have multiple ReplicaSets, the logic needs to ensure it fetches the most recent one. Typically, k8s assigns ReplicaSets with a revision number, where a higher number indicates a newer ReplicaSet but we're not using them here, the current logic only fetches the first replica set id from the array... not the one …
> Fix grafana links for rancher workload deployment 

- cypress/e2e/blueprints/explorer/workloads/pods/pods-get.ts
- cypress/e2e/po/pages/users-and-auth/roles.po.ts
- cypress/e2e/tests/pages/explorer/more-resources/api/custom-resource-definitions.spec.ts
- cypress/e2e/tests/pages/explorer/workloads/pods.spec.ts
- cypress/e2e/tests/pages/fleet/advanced/workspaces.spec.ts
- cypress/e2e/tests/pages/user-menu/account-api-keys.spec.ts
- cypress/e2e/tests/pages/users-and-auth/roles.spec.ts
- cypress/e2e/tests/pages/users-and-auth/users.spec.ts
- cypress/globals.d.ts
- cypress/support/commands/rancher-api-commands.ts
Fixes https://github.com/rancher/qa-tasks/issues/1429
Set the pagination to 10 rows per page.
Reduce the resources creation from 100 to 25 for the pagination tests.
Update the assertion logic accordingly.
This change reduces the resources creation to speed up the pagination tests execution.
Check the pagination tests pass the execution with the assertions updates.
~~This doesn't include the Global Roles tests in the meantime as that page/table has an slight different layout using tabbed tables.~~ 
Found out the root cause of the issues with the Roles tests. Code is updated.
> [Automation] - Reduce execution time of pagination tests

- shell/assets/translations/en-us.yaml
- shell/components/nav/Header.vue
- shell/components/templates/home.vue
- shell/components/templates/plain.vue
- shell/config/query-params.js
- shell/dialog/SloDialog.vue
- shell/edit/auth/saml.vue
- shell/mixins/auth-config.js
- shell/pages/auth/login.vue
- shell/pages/auth/logout.vue
- shell/pages/auth/verify.vue
- shell/pages/diagnostic.vue
- shell/pages/fail-whale.vue
- shell/store/auth.js
- shell/store/index.js
- shell/utils/auth.js
Fixes #10941 
- update SAML auth provider edit/create interface to account for setting up this new log out behaviour config
- add dialog to Header component so that user can choose log out type based on the auth provider config (will only appear if `logoutAllEnabled` && `! logoutAllForced`)
- add `PromptModal` to the `home` template so that the user can get the logout modal while browsing pages that use `home` template
- update logout action in `auth` store to account for a different logout action
- various adjustments in order to have the logout flow running in all scenarios (`normal logout` and `logout ALL`)
To whoever is the reviewer of this PR, some notes on what each file's responsibility are:
`nav/Header.vue` -> where logout modal was added (if `logoutAllEnabled` && `! …
> SAML SLO support

- cypress/e2e/tests/pages/explorer/resource-search.spec.ts
- shell/components/nav/Jump.vue
This was changed in 7f1536d9cff20b73b8b42a703886f170a50fda5f and it appears that we didn't need this change for `Jump.vue` because `value` is declared as a data prop. Reverting back to `v-model` resolves the issue.
Fixes #11700 
- reintroduce two-way data binding in `Jump.vue`
- Resource Search
- N/A
https://github.com/user-attachments/assets/6092cfee-4675-48a6-bfef-546e4e7f1dad
> Use `v-model` for data binding on in Jump.vue

- cypress/e2e/po/side-bars/burger-side-menu.po.ts
- cypress/e2e/tests/navigation/side-nav/main-side-menu.spec.ts
Re-instates one of the tests we were skipping from the vue3 merge.
Partially resolves https://github.com/rancher/dashboard/issues/11622#issue-2457901883
Updates a selector used in one of the test pos to be inline with our new popover library.
N/A
N/A
> Fixing the tooltip selector used in the main-side-menu tests and renabled the test

- .github/workflows/release-rancher-components.yml
- pkg/rancher-components/package.json
This updates the `@rancher/components` release workflow so that releases tagged with `alpha.x` or `beta.x` will include a `dist-tag`[^1] on publish. `dist-tags` help by preventing users from inadvertently installing unstable versions published to npm.
[^1]: https://docs.npmjs.com/adding-dist-tags-to-packages
Fixes #11710
- Add alpha and beta `dist-tags` to `@rancher/components` release workflow
- Releasing `@rancher/components`
> Add alpha and beta `dist-tags` to `@rancher/components` release workflow

- .github/workflows/test.yaml
- cypress/e2e/tests/pages/explorer/more-resources/api/custom-resource-definitions.spec.ts
- cypress/e2e/tests/pages/explorer2/cluster-project-members.spec.ts
- cypress/e2e/tests/pages/explorer2/cluster-tools.spec.ts
- cypress/e2e/tests/pages/explorer2/index.spec.ts
- cypress/e2e/tests/pages/explorer2/namespace-picker.spec.ts
- cypress/e2e/tests/pages/explorer2/node-list.spec.ts
- cypress/e2e/tests/pages/explorer2/project-namespace.spec.ts
- cypress/e2e/tests/pages/explorer2/resource-search.spec.ts
- cypress/e2e/tests/pages/explorer2/storage/configmap.spec.ts
- cypress/e2e/tests/pages/explorer2/storage/persistent-volume-claims.spec.ts
- cypress/e2e/tests/pages/explorer2/storage/persistent-volumes.spec.ts
- cypress/e2e/tests/pages/explorer2/storage/storage-classes.spec.ts
- cypress/e2e/tests/pages/explorer2/workloads/daemonsets.spec.ts
- cypress/e2e/tests/pages/explorer2/workloads/deployments.spec.ts
- cypress/e2e/tests/pages/explorer2/workloads/jobs.spec.ts
- cypress/e2e/tests/pages/explorer2/workloads/pods.spec.ts
- cypress/e2e/tests/pages/explorer2/workloads/workloads.spec.ts
- cypress/e2e/tests/pages/user-menu/account-api-keys.spec.ts
- cypress/e2e/tests/pages/users-and-auth/roles.spec.ts
- cypress/e2e/tests/pages/users-and-auth/users.spec.ts
- cypress/e2e/tests/setup/rancher-setup.spec.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1423
Currently, the explorer test run for admin takes 27 minutes to complete so we need to split explorer tests into two buckets for efficiency (based on PR review https://github.com/rancher/dashboard/pull/11374#pullrequestreview-2171608065)
> automation: split explorer tests into two buckets

- pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue
- shell/components/SortableTable/index.vue
- shell/components/auth/RoleDetailEdit.vue
- shell/components/form/KeyValue.vue
- shell/components/form/MatchExpressions.vue
- shell/components/form/Ports.vue
- shell/components/form/ServicePorts.vue
- shell/components/nav/TopLevelMenu.vue
- shell/components/nav/WindowManager/ContainerLogs.vue
- shell/dialog/ForceMachineRemoveDialog.vue
- shell/edit/networking.k8s.io.ingress/RulePath.vue
- shell/edit/token.vue
This reverts the remaining changes from 7f1536d9cff20b73b8b42a703886f170a50fda5f, where we modified `v-model` usage for html elements to reduce errors when running the migration script.
After encountering a second issue related to this change (#11723), I thought it was best to revert the change so that we could get back to the original behavior.
Fixes #11723 
- reverts commit 7f1536d9cff20b73b8b42a703886f170a50fda5f
- Each element should behave as it did before 7f1536d9cff20b73b8b42a703886f170a50fda5f was introduced
- double check each modified component is not mutating a prop via `v-model`
> Revert Refactoring the plain element <input> data bindings

- shell/edit/cloudcredential.vue
Fixes #11721 
This PR allows extensions to override the icons for node providers on the create cloud credentials screen.
This introduces the ability to override via:
```
plugin.register('image', 'providers/YOUR_PROVIDER_NAME.svg', require('./PATH_TO_YOUR_ICON/WHATEVER_ICON_NAME.svg'));
```
For QA, test when you go to the cloud credentias creation screen, that the icons display correctly, e.g.:
> Allow extensions to override node provider icons for cloud credentials

- shell/components/form/InputWithSelect.vue
- shell/components/form/Select.vue
- shell/components/form/ServiceNameSelect.vue
- shell/components/form/__tests__/InputWithSelect.test.ts
- shell/components/form/__tests__/Select.test.ts
- shell/components/form/__tests__/ServiceNameSelect.test.ts
This exposes the `canPaginate()` computed prop so that it can be accessed in the `labeled-form-element` mixin. 
`Select.vue` never had `canPaginate()` defined because it didn't make use of any mixin that defines this computed prop. 
Fixes #11722 
- Add `labeled-select-pagination` mixin to `Select.vue`
The warning printed to the console is Vue3 warning us that something is wrong with the design of our components:
```
labeled-form-element.ts:123 [Vue warn]: Property "canPaginate" was accessed during render but is not defined on instance. 
at <Select value="minute" onUpdate:value=fn disabled=true  ... > 
at <Token key=3 ref="comp" value= __WEBPACK_DEFAULT_EXPORT__ {type: 'token', __clone: true, metadata: {…}, $ctx: {…}}  ... > 
at <AsyncComponentWrapper key=3 ref="comp" value= …
```
> Add `canPaginate` computed prop to components that use `LabeledFormElement` mixin

- cypress/jenkins/init.sh
Upstream corral package commit was reverted.
https://github.com/rancherlabs/corral-packages/pull/58
naming of generated packages is affected. Reverting to original after upstream was reverted.
Fix Jenkins CI
Jenkins
> [Automation] - Fix naming after a change was reverted on corral-packages

- .github/workflows/release-shell-pkg.yaml
- .github/workflows/scripts/check-package-tag-version.sh
- shell/creators/extension/package.json
- shell/scripts/publish-shell.sh
- shell/scripts/test-plugins-build.sh
Fixes #11694 
- add step for checking tag version matching on publish shell workflow -> `check-package-tag-version.sh`
- update `publish-shell` script to allow for independent publish of either `Shell` or `Creators` packages to NPM
- remove unused `TMP_DIR` var in `publish-shell` script
- update creators package version to match what was published on NPM
- you can run a check for the `check-package-tag-version.sh` script by running it manually with a `TAG` of your choice, such as:
```
export TAG=shell-pkg-v2.0.1 && .github/workflows/scripts/check-package-tag-version.sh
```
> Update publish shell workflow to allow for independent release of either shell or creators packages

- shell/components/nav/WindowManager/ContainerLogs.vue
This updates the follow behavior in `ContainerLogs.vue` so that it retains similar follow behavior that we had in Vue 2 by
- introducing a `scrollThreshold` to allow for some flexibility when determining if the logs are at the bottom
- `updateFollowing()` now calculates distance based off the threshold instead of expecting an exact match
- `updateFollowing()` is now debounced to prevent excessive calls
- a watcher has been added to `lines` to scroll to the bottom when new lines are added
- `follow()` explicitly sets `isFollowing` to true
Fixes #11486 
- there's still some scenarios where multiline logs can exceed the scroll threshold, causing follow to stop 
- container logs
- container logs
> Update follow behavior in `ContainerLogs.vue`

- pkg/rancher-components/src/components/Form/TextArea/TextAreaAutoGrow.vue
- shell/components/nav/Header.vue
- shell/edit/auth/saml.vue
Fixes #11766 
**Original work was done on this PR https://github.com/rancher/dashboard/pull/11182**
- add missing bits to make SAML SLO feature work (`Header` component missing a part of template)
- fix  `$set` notations on `saml.vue`
- fix problem of data propagation on the SAML auth providers for certificates where when you added a certificate the textarea wouldn't show the certificate data `TextAreaAutoGrow`
Follow instructions on https://github.com/rancher/dashboard/pull/11182
- There some problems with the styling on the popover that comes from clicking on the avatar icon on the header, especially for different themes (light vs dark) but that's tracked already in https://github.com/rancher/dashboard/issues/11684
> Fix -> Vue3: SAML SLO support - feature is broken

- shell/components/CruResource.vue
This resolves the issue of `CruResource` rendering duplicate templates by excluding the default slot from being provided to `CruResourceFooter`.
Fixes #11716
Fixes #11741
- don't expose the default slot in `CruResourceFooter`
This behavior is directly related to Vue3 Slot Unification[^1] and is only an issue in instances where we iterate over slots.
In Vue2, this template would iterate over scoped slots via `v-for="(_, slot) of $scopedSlots"`. Since `$scopedSlots` has been merged with `$slots` in Vue3, we are now inadvertently picking up the default slot along with the rest. 
In previous instances of this error, we filtered for scoped slots via `v-if="typeof $slots[slot] === 'function'"`. For the offending instances addressed in this PR, `default` was also being treated as a scoped slot …
> Don't provide default slot to `CruResourceFooter`

- cypress/e2e/po/pages/explorer/config-map.po.ts
- cypress/e2e/tests/pages/explorer2/storage/configmap.spec.ts
- shell/edit/configmap.vue
Fixes #11690 
Fixed configmap not creating and not being able to switch from form view to yaml. Reenabled the test.
waitForMastheadTitle in E2E test seem to only work for create/edit forms and not for lists.
without inheritAttrs: false, resource attribute is passed as a string and not an object, which makes schema fetching not work correctly
added inheritAttrs: false
- creating a config map should work in Config Maps page
- it should be possible to switch from form view to edit as yaml view when creating a configMap
None
> Fixed configmaps not creating

- cypress/jenkins/Dockerfile.ci
- cypress/jenkins/init.sh
Force use of a common node version `16` for releases 2.9 and below down to 2.7.
Bumping kubectl to a newer version as each version support one version up and down. This to mitigate any kubectl client errors during setup.
Jenkins pipelines that are `release-2.9` and older fail to use `node 20` which is a new requirement on `master` / `latest` 
Jenkins pipelines
CI
> [Automation] - Forcing use of node 16 for branches 2.9 and below. Bump kubectl client

- shell/components/nav/NamespaceFilter.vue
Fixes #11728 
In Vue3 `disabled` attribute on div elements doesn't get removed when its value is `false`, `null` should be used instead.
Select different items in namespace selector, and hover on the items.
n/a
> Fix namespace selector's hovered/selected styling

- shell/edit/provisioning.cattle.io.cluster/__tests__/rke2.test.ts
- shell/edit/provisioning.cattle.io.cluster/rke2.vue
Contributes to https://github.com/rancher/dashboard/issues/11360
The Unsupported Azure warning banner is showing up for all providers https://github.com/rancher/dashboard/issues/11360#issuecomment-2274228896
We are limiting the warning message to show up only if Azure is included in the cloud providers option.
> Show Unsupported Azure warning message only if Azure is an option

- shell/vue.config.js
Fixes #11744
There's an issue with the extensions caused by this configuration of the aliases and I'm investigating with https://github.com/rancher/dashboard/issues/11706
> Restore vueconfig cleanup with Vue3 migration fixes

- shell/components/ButtonDropdown.vue
- shell/components/CruResource.vue
- shell/components/form/ArrayList.vue
- shell/components/form/ArrayListGrouped.vue
- shell/edit/workload/storage/index.vue
This resolves several issues associated with the Pod Storage tab under when creating new deployments:
- `ButtonDropdown.vue` now renders a label
- `ButtonDropdown.vue` now renders a list volumes
- Selecting a volume now renders the associated form in `ArrayListGrouped.vue`
Fixes #11787
Several issues are resolved in this PR:
- Updates the slot syntax to be more consistent with `CruResource.vue`. This should help with accurately rendering slot content when we iterate over component slots.
- `v-select` now makes use of `modelValue`/`update:modelValue` for two-way data binding. This is consistent with the Vue3 migration guide.
- This approach uses the spread operator to create a new array instead of using push. It appears that using push on a nested property of a reactive object was not …
> Resolve issues with workload pod storage

- shell/models/__tests__/apps.deployment.test.ts
- shell/models/apps.deployment.js
Fixes #11319
- This is a direct, cherry-pick backport of https://github.com/rancher/dashboard/pull/11297 (see for details)
A good way to setup set
- Create a deployment in the default namespace
- `kubectl get rs` should show the replicas for the deployment (<deployment name>-<unique id>)
- edit the deployment (for example add a description)
- `kubectl get rs` should now show two replicas for the deployment. We're interested in the one that has desired/current/ready.
- Go to Deployments --> click on deployment --> Metrics tab --> (when grafana metrics are available) hover over any of the lines and it should show the replica set we're interested in (<replica set id>-<unique id>)
> Fix grafana links for rancher workload deployment

- pkg/aks/util/aks.ts
Fixes #11817 
This PR removes the incorrect regions southcentral and us and adds 
- japanwest
- southcentralus
- newzealandnorth
- mexicocentral
- spaincentral
1. The AKS cluster creation region dropdown should include the above regions under the first section of the list, 'Regions with Availability Zone Support
2. When one of the above regions is selected, the user should be able to configure node group availability zones, and the availability zone input shouldn't show any errors.
> Update AKS region data

- shell/assets/styles/base/_variables.scss
- shell/assets/styles/global/_select.scss
- shell/components/auth/RoleDetailEdit.vue
- shell/components/form/Select.vue
Resolve two bug
I've bundled these two together as they're the same problem, however different issues. If needs be can investigate splitting in two with the hope there's no overlap 
- Remove custom code, use new generic code that follows 'compact' concept used elsewhere
- Apply to all four fields in row
- Also fix a bug where selecting verbs such that another row is shown would grow height of all other inputs in row
- How it worked/works
- Vue2
- Part 1 - Component would inherit attributes, such as class from owning element. For example classes applied to `<Select` would be applied to the first element within the Select component
- Part 2 - $attrs property does not contain some properties from the parent, such as class
- Vue3
- Part 1 - Component does not inherit attributes of owning …
> Fix height of rows containing Select compoent/s

- docusaurus/docs/internal/getting-started/development_environment.md
Tag `v2.6-head` no longer points to a recent Rancher commit.
This PR only updates internal docs, making them version-agnostic in that regard.
> Update documented latest Rancher version

- pkg/aks/components/AksNodePool.vue
- pkg/aks/components/CruAks.vue
- pkg/aks/l10n/en-us.yaml
- pkg/aks/util/validators.ts
Fixes #11842
This PR updates AKS validation to allow users to specify a min and max node counts of 0, and a node count of 0 if autoscaling is enabled. All 3 inputs allow a maximum of 1000. These limitations mirror the azure portal validation.
1. Create new aks cluster without autoscaling in any pools: 'Node Count' should be validated to be >0
2. Create an AKS cluster with autoscaling enabled in a pool: 'Node Count' should be validated to be >=0, <=max count, and >= min count.
3. Max and min count should also be limited to 1000
> aks node pools - allow 0 count when autoscaling is enabled

- pkg/eks/l10n/en-us.yaml
- pkg/eks/util/__tests__/validators.test.ts
- pkg/eks/util/validators.ts
Fixes #11827
Backport of https://github.com/rancher/dashboard/pull/11858
> [2.9]eks - allow node groups with 0 min size

- pkg/eks/l10n/en-us.yaml
- pkg/eks/util/__tests__/validators.test.ts
- pkg/eks/util/validators.ts
Fixes #11826 
This PR corrects an EKS form validator to allow '0'. I also fixed a typo while in the neighborhood.
1. Create an EKS cluster - node group 'minimum asg size' should be validated to be >=0
> eks - allow node groups with 0 min size

- pkg/aks/components/AksNodePool.vue
- pkg/aks/components/CruAks.vue
- pkg/aks/l10n/en-us.yaml
- pkg/aks/util/validators.ts
Fixes https://github.com/rancher/dashboard/issues/11848
Backport of https://github.com/rancher/dashboard/pull/11855 minus some vue3 v-model syntax.
> [2.9] aks node pools - allow 0 count when autoscaling is enabled

- pkg/gke/components/CruGKE.vue
- pkg/gke/components/GKENodePool.vue
- pkg/gke/l10n/en-us.yaml
- pkg/gke/util/__tests__/validators.test.ts
- pkg/gke/util/validators.ts
Fixes #11844 
This PR updates the GKE provisioning form to validate that node pools' initial node count is >=0 and <=1000
I moved the validator to a utility file so I could write a couple unit tests. Also fixed a couple issues related to vue3 migration that prevented the form from working.
Create a GKE cluster - node pools' initial node count should be validated to be >=0 and <=1000
> GKE - allow initial node count to be 0

- shell/edit/auth/__tests__/azuread.test.ts
- shell/edit/auth/azuread.vue
Fixes #11784 
Fixed Azure AD validation. Looks like migration code used wrong syntax
Changed how key value is assigned
Azure AD validation:
Users & Authentication -> Auth Provider -> Azure AD
1. Populating "Tenant id", "Application id", "Application secret" fields should enable "Enable" button with a default "Standard" endpoint.
2. Switching to "China" endpoint should keep "Enable" button enabled.
3. Switching to "Custom" endpoint should disable "Enable" button.
4. Populating the rest of the fields with valid values should enable "Enable" button back.
None
https://github.com/user-attachments/assets/e39362dd-19ce-432e-955f-99cb04ea3745
> Vue 3: Fixed Azure AD validation

- shell/edit/workload/index.vue
Fixes #11850
- Ensure the Workload --> Container --> Resources tab populates correctly
- cause was `template` element related (single `template` in a `Tab`)
i've gone through the other usages of Tab with a nested Template, there are others but they work... (shell/detail/secret.vue, shell/detail/node.vue)
Deployment, Pod, Job, etc container Resources tab renders correctly
See issue
> Remove breaking `template` from Workload Pod Resource tab

- cypress/e2e/po/components/namespace-filter.po.ts
- cypress/e2e/tests/pages/explorer2/namespace-picker.spec.ts
- shell/components/nav/NamespaceFilter.vue
This prevents the mousedown event from triggering focus to fix an issue where the focus event would open the NamespaceFilter dropdown and the subsequent click event would toggle the dropdown to closed. 
Fixes #11683 
- Add mousedown.prevent to the containing div that manages focus for the NamespaceFilter component
- The focus event and the click event were both triggering, causing the dropdown to open and immediately close
- NamespaceFilter component
- NamespaceFilter component
> Prevent mousedown event from triggering focus in NamespaceFilter.vue

- .vscode/settings.json
- shell/core/plugin-helpers.ts
- shell/core/plugin.ts
This fixes an issue with rendering components that are lazy loaded via an extension configuration. For example:
```
plugin.addCard(
CardLocation.CLUSTER_DASHBOARD_CARD,
{ cluster: ['local'] },
{
label: 'some-label2',
labelKey: 'plugin-examples.card-title-three',
component: () => import('./components/MastheadDetailsComponent.vue')
}
);
```
`defineAsyncComponent` helps Vue handle the asynchronous nature of lazy loading and `markRaw` prevents Vue from making the component reactive, which can help with performance.
- wrap the component property for Card, Tab, and Panel in `defineAsyncComponent` and `markRaw`
- This has been tested with [extensions-api-demo](https://github.com/rancher/ui-plugin-examples/tree/main/pkg/extensions-api-demo)
- Other extensions should be tested and verified
- …
> Allow for loading dynamic components defined in extensions

- shell/store/type-map.js
We need to wrap the auto-imported components with `defineAsyncComponent` so it behaves like all of the native components. This should fix the auto imports from directories like lists, edit, detail etc.
Any vue3 extension which made resource overrides using the list, edit, detail etc directories.
> Fix for auto-imported components from extensions

- shell/components/CruResource.vue
- shell/components/Wizard.vue
This ensures that the Wizard footer will render properly within CruResource. 
I'm not finding any docs that explains this change, but the best I can infer is that the `footer` slot is defined within the `controlsContainer` slot of the Wizard component; Vue3 must be more strict about slot hierarchy than Vue2. (footer is a slot of CruResource, not Wizard)
Fixes #11882
- Remove the nested `<template #footer>` to render the footer for the Wizard
- Resolve console warning related to missing `LazyImage` component import
- Fleet
- Other instances of CruResource that render the Wizard component
> Render wizard footer in CruResource

- pkg/aks/components/AksNodePool.vue
- pkg/aks/components/CruAks.vue
- pkg/aks/components/__tests__/AksNodePool.test.ts
- pkg/aks/l10n/en-us.yaml
- pkg/aks/util/__tests__/validators.test.ts
- pkg/aks/util/validators.ts
Fixes #11842 - see [comments](https://github.com/rancher/dashboard/issues/11848#issuecomment-2345074794) in the backport issue
This PR updates AKS node pool count validation. Based off what I see in the Azure portal, AKS pools may have a count of 0 if the pool mode is 'User' - I wish I understood where I got the idea that this was actually dependent on the enableAutoScaling property last week but life is full of mysteries I guess.
I moved the validator function into a utility to make it easier to add some unit tests. 
Verify that node pool count is validated to be >=1 in system pools and >=0 in user pools (ie when count is invalid an error message is shown and create button greyed out)
https://github.com/user-attachments/assets/c7290273-b1e7-443d-85a2-8c7528b46302
> Fix AKS count validation message

- cypress/e2e/po/pages/explorer/workloads.po.ts
- cypress/e2e/po/side-bars/slide-in.po.ts
- cypress/e2e/tests/pages/explorer2/describe-resource.spec.ts
- pkg/kubectl-explain/components/ExplainPanel.vue
- pkg/kubectl-explain/components/SlideInPanel.vue
- pkg/kubectl-explain/slide-in.js
Fixes #11699 
Vue.extend is not available in Vue3 and the result of our migration script didn't work.
Changed the component following https://v3-migration.vuejs.org/breaking-changes/global-api
Describe resource should work for all pages that have it as an action
None
> Vue 3: Fixed describe resource not working

- cypress/e2e/po/pages/explorer/cluster-project-members.po.ts
- cypress/e2e/tests/pages/explorer2/cluster-project-members.spec.ts
- shell/edit/management.cattle.io.clusterroletemplatebinding.vue
Fixes #11821 
Passed attributes were incorrect
Added "inheritAttrs: false,"
Adding project and cluster members
No other areas should be affected.
> Vue 3: Fixed cancelling adding members returns to the wrong page
