rancher/dashboard

shell/assets/translations/en-us.yaml, shell/pages/auth/login.vue, shell/store/auth.js
Fixes https://github.com/rancher/dashboard/issues/9504
Forwardport of https://github.com/rancher/dashboard/pull/9503
=> Forwardport ad migration

cypress/e2e/tests/pages/extensions.spec.ts, shell/components/ResourceTable.vue, shell/detail/node.vue
Fixes #9515
- caused by localisation missing required strings
- change probably happened when lists in node tabs changed from  sortable tables to resource tables. https://github.com/rancher/dashboard/pull/9186
- also fixed width of image list (see screenshots)
=> Fix issue causing node detail page to be unreachable

shell/components/PromptModal.vue, shell/package.json
Contributes to https://github.com/epinio/ui/issues/301
=> Add option to avoid PromptModal clicking outside

shell/assets/translations/en-us.yaml, shell/store/auth.js
Follow on from https://github.com/rancher/dashboard/issues/9482, occurred is misspelled.
=> Ad migration error typo

shell/assets/translations/en-us.yaml, shell/store/auth.js
Forwardport of https://github.com/rancher/dashboard/pull/9567
=> Forwardport ad migration error typo

shell/components/formatter/LinkName.vue, shell/middleware/authenticated.js, shell/utils/auth.js
Fixes #9445
1. If the user is not authorized to access the node, display plain text
=> fix(LinkName): add node schema checking

shell/package.json
This bumps the shell package to `0.3.22`.
=> Bump shell 0.3.22

shell/promptRemove/management.cattle.io.project.vue
Fixes #9517 
- update logic to have option for cluster member to delete a project without deleting the namespaces associated
When reviewing, should consider commit https://github.com/rancher/dashboard/commit/506934acfd9ccc42923e5b84e957de65f45a69de of PR https://github.com/rancher/dashboard/pull/6611 of issue #6594 made by @mantis-toboggan-md 
Follow repro steps of #9517 
https://github.com/rancher/dashboard/assets/97888974/b60f0565-812c-49de-b5a7-cb0a3b110080
=> Delete project as cluster member -  option to not delete namespaces

shell/edit/provisioning.cattle.io.cluster/rke2.vue
Just a simple array and string type checks for CNI values.
Fixes #9378
=> Support array type for cni values in yaml

shell/edit/workload/storage/ContainerMountPaths.vue
Fixes #9631
Backport of https://github.com/rancher/dashboard/pull/9617
=> [Backport v2.7] Fix volumeMounts from being overwritten

shell/assets/styles/themes/_light.scss, shell/components/nav/Group.vue, shell/components/nav/Type.vue, shell/store/type-map.js
Fixes #9428
Fixes #9429
Fixes #9430
Fixed following in Cluster Explorer sidenav:
Ref XD: https://xd.adobe.com/view/1453b6a5-ca9c-4794-8fbf-34f1349e45a3-4100/
- Highlight navigation groups when child items are selected
- Update icons and location for the namespace icon
- Enhance styles, spacing, width, font size, etc.
=> Highlight navigation groups

shell/plugins/dashboard-store/resource-class.js
Fixes #9592
- ensure we await the async function that saves yaml
- regression in 2.7.7, caused by https://github.com/rancher/dashboard/pull/9383
=> Ensure failures when saving YAML are caught

shell/plugins/dashboard-store/resource-class.js
Fixes #9655
see https://github.com/rancher/dashboard/pull/9647
=> [Backport v2.7] Ensure failures when saving YAML are caught

shell/assets/translations/en-us.yaml
=> Grammar fixes

shell/components/SideNav.vue, shell/components/nav/Group.vue, shell/components/nav/Type.vue
Fixes #9659
Fixed New Side Nav Visual Bugs
============
============
============
=> Side nav visual bugs

shell/components/Loading.vue, shell/components/nav/Group.vue, shell/components/nav/Header.vue, shell/layouts/default.vue, shell/layouts/home.vue, shell/layouts/plain.vue, shell/store/index.js
Fixes #9673
Fixed APP Bar overlaps bug in Firefox. 
=====================
=====================
=====================
=> Fix app bar overlaps issue

shell/components/nav/Group.vue, shell/layouts/default.vue
Fixes #9703
- Fixed header font size in the side nav
- Clean up CSS
- Highlight header when active 
================
=> Fixed header highlight issue when not expanded

shell/assets/translations/en-us.yaml, shell/edit/provisioning.cattle.io.cluster/MachinePool.vue, shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/machine-config/vmwarevsphere.vue
This PR aims to inform users when their vSphere config might not match expected values in the form while editing by adding error messages that communicate what the error might be. 
closes #9699
closes #9698
- No longer replace values when the provided value doesn't match in the vSphere cluster provisioning form
- Relay an error message to detail potential problems with provided values in the form 
This doesn't make use of the form validation mixin, but instead opts for building up a collection of errors and relaying this collection of errors to the root form. I think that this resolves the problem for the near-term, but relying on proper and more sophisticated form validation will go a great way to enhance the solution proposed here.
- Editing RKE2 vSphere clusters
- Editing RKE2 vSphere …
=> Relay error  messages when errors are detected in the vSphere form

shell/edit/__tests__/namespace.test.ts, shell/edit/namespace.vue
Fixes #9731 
Swap `Tabbed` for `ResourceTabs` to pick up tabs added via the extension `addTab` method
- create/edit namespaces
- namespace 'view config'
=> use resourcetabs in namespace edit component

shell/utils/version.js
Fixes #9734 
Ember side: https://github.com/rancher/ui/pull/5069
=> update isdevbuild to include -alpha versions

shell/detail/__tests__/autoscaling.horizontalpodautoscaler.test.ts, shell/detail/autoscaling.horizontalpodautoscaler/index.vue
Fixes #9621
Cluster Explorer -> Service Discovery -> HorizontalPodAutoscaler
=> HPA details page, fix duplicate metrics

shell/components/nav/Type.vue, shell/config/router.js
Fixes #9169
Fixed  highlight issue for `Cluster and Project Members` and other menu items with hash in URL
https://github.com/rancher/dashboard/assets/18264463/fc853c62-35cb-46bb-b5cb-b8cf172fda6b
=> Fixed navigation  state

.vscode/settings.json, shell/edit/workload/storage/persistentVolumeClaim/__tests__/persistentvolumeclaim.test.ts, shell/edit/workload/storage/persistentVolumeClaim/persistentvolumeclaim.vue
Fixes #9585
Default value is now automatically assigned after fetching the data.
Unit test has been created but it's not possible to use it till we do not integrate `fetch()` in the test suite.
https://github.com/rancher/dashboard/assets/5009481/70b29e37-a15b-456d-a786-beb2d990c7a3
=> Add automatically default value for deployment PVC

shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml
Fixes #2405
N/A
Fixed typo in translations.
N/A
N/A
N/A
=> Fixed typo in translations for Backup/Restore tooltip

shell/components/ClusterIconMenu.vue, shell/components/Questions/__tests__/Yaml.test.ts, shell/components/form/__tests__/KeyValue.test.ts, shell/edit/workload/storage/__tests__/Storage.test.ts
Fixes #8907 
https://github.com/rancher/dashboard/assets/135728925/ad03d3b0-3b1a-424d-9fd3-e3fea038c53d
=> Fixed unit tests warnings

shell/components/formatter/PrincipalGroupBindings.vue
Fixes #9751 
- Changed getter of `NORMAN.PRINCIPAL` resource in component to make it reactive
- Added optional chaining to obj property to prevent console error
- Asks me for system credentials (needs to be a specific system)
- Go to `Users & Authentication` -> `Groups` check if `Group Role Names` appear
- Without refreshing (using side nav) navigate to `Users & Authentication` -> `Auth Provider`
- Without refreshing (using side nav) navigate back to `Users & Authentication` -> `Groups`
- Make sure that `Group Role Names` appear again correctly
=> fixes issue with Group Roles disappear in users & auth -> groups screen

shell/assets/styles/themes/_light.scss
Fixes #
Fixed  side nav width to 250 px
===============
===============
===============
===============
=> Fixed side nav width

shell/pages/c/_cluster/monitoring/index.vue
Fixes #4466
The GET request to` v1/endpoints/cattle-monitoring-system/rancher-monitoring-alertmanager` fails with 403 forbidden, for non-admin users.
This was blocking the ui from generating the monitoring links correctly.
However the 403 error appears to be a backend issue.
Cluster Explorer -> Monitoring
How to create and assign correct roles to the non-admin user: https://github.com/rancher/rancher-docs/pull/286/commits/5baae45a9f21fdb972a78bdb72a8131a54f17827
=> Fix monitoring links generation by removing possible 403 errors

shell/components/auth/login/saml.vue
Fixes https://github.com/rancher/dashboard/issues/9608
- Login using the token command from rancher CLI
Internal reference: confluence - Okta SAML setup Creation
0. Enable the SAML authentication on your rancher instance
- Internal reference: confluence - Okta SAML setup Creation
- docs: https://developer.okta.com/docs/guides/build-sso-integration/saml2/create-your-app/
- video: https://www.youtube.com/watch?v=Kqn3YHyIBdk
- Rancher reference: https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/okta/
1. Install the [rancher cli](https://ranchermanager.docs.rancher.com/reference-guides/cli-with-rancher/rancher-cli#docusaurus_skipToContent_fallback).
2. Using the Rancher cli, attempt to generate a token using rancher token --server=$RANCHER_HOST --cluster=$CLUSTER …
=> Add missing parameters to SAML auth request

cypress/e2e/po/pages/istio/istio-dashboard.po.ts, cypress/e2e/tests/pages/charts/istio.spec.ts
Fixes https://github.com/rancher/dashboard/issues/9719
=> Istio e2e tests

shell/mixins/create-edit-view/impl.js, shell/models/cluster.x-k8s.io.machinedeployment.js, shell/plugins/dashboard-store/normalize.js, shell/utils/__tests__/object.test.ts, shell/utils/object.js
Fixes  #9597
- fixes issue in handleConflict that meant
- conflicts were not detected
- non-conflicting changes were not applied to users resource
- see #9597 issue description for a lot more detail
- pods are good to test a resource that might be being modified in the background
- secrets are good if a stable test env is needed
- Editing kube resources via edit pages with forms
- Scaling RKE2 machine pools
- See issue for more detail
=> Fix resource modified handler

shell/list/fleet.cattle.io.cluster.vue, shell/utils/cluster.js
After enabling `harvester-baremetal-container-workload`, the harvester cluster should be displayed.
Fixes #
- https://github.com/harvester/harvester/issues/4482
=> show harvester cluster in fleet page

shell/components/form/Members/ClusterPermissionsEditor.vue, shell/models/management.cattle.io.clusterroletemplatebinding.js, shell/models/management.cattle.io.projectroletemplatebinding.js
=> Safe ClusterRoleTemplateBinding with a non-existent user

shell/components/SortableTable/index.vue, shell/detail/provisioning.cattle.io.cluster.vue
Fixes https://github.com/rancher/dashboard/issues/9665
Cluster manage -> details page -> 'Scale Down' action
=> Fix 'Scale Down' crash in cluster provisioning details page

shell/components/form/ArrayList.vue, shell/components/form/__tests__/ArrayList.test.ts, storybook/stories/components/ArrayList.stories.mdx, storybook/stories/components/PercentageBar.stories.js, storybook/stories/form/Editor.stories.mdx
Fixes #9630
- Allow to past single lines, previously restricted
- Created consistency within the component, emitting `input` also in case of multilines, keeping the same functionalities
- Added unit tests for paste cases
- Added all the missing stories for ArrayList, including slots
- Fixed issues with existing stories: Editor and Percentage
Try to past either single and multiple lines. Any list can be used within Rancher, otherwise can be tried on Storybook.
https://github.com/rancher/dashboard/assets/5009481/2cfcda61-8081-46c4-8591-7dd8163567af
Preview if you want to avoid to launch Storybook
=> Cannot paste into textboxes under Advanced section

shell/utils/__tests__/version.test.ts
=> automation: update isdevbuild to include -alpha versions

pkg/rancher-components/src/components/Form/Radio/RadioGroup.test.ts, pkg/rancher-components/src/components/Form/Radio/RadioGroup.vue
Fixes #8977
Added test using an example wrapper to integrate slot case.
=> Automation: RadioGroup: Expose isDisabled slot prop

.vscode/launch.json
Fixes #9876
As alternative to current run, this allows to run tests exclusively to focused files opposed to the Jest option `onlychanged` which currently involve more files.
=> Add VSCode launcher options for relative files on Jest

shell/assets/styles/themes/_dark.scss, shell/assets/styles/themes/_light.scss, shell/assets/translations/en-us.yaml, shell/components/CodeMirror.vue, shell/components/CopyToClipboardText.vue, shell/components/DetailText.vue, shell/components/DetailTop.vue
Reverts rancher/dashboard#9835
Fixes #9895
=> Revert "Annotations display redesign"

shell/components/nav/__tests__/Type.test.ts
Fixes https://github.com/rancher/dashboard/issues/9169
Added tests.
Note: Router and Route behaved in a weird way without allow me to change them.
=> Automation: Fixed navigation state

.github/workflows/port-issue.yaml
rancherbot is gone and with it our automatic issue backporting functionality. This workflow is taken from internal docs provided with the rancherbot shutdown announcement.
=> add port-issue workflow

shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml
Fixes #9901
Changed version 2.7 to 2.8 on the homepage banner.
=> Change version 2.7 to 2.8 on the homepage banner

shell/utils/validators/formRules/index.ts, shell/utils/validators/role-template.js
Fixes #9078 (specifically this comment: https://github.com/rancher/dashboard/issues/9078#issuecomment-1758276384)
=> was incorrectly checking for apiGroups on the missingOneResource error.

shell/components/Wizard.vue
Fixes #9917
For a dev there's an easy way to generate an error in order to test. You can just throw an error in the finish method of the install component
Chart installation when errors occur
Chart installation
https://github.com/rancher/dashboard/assets/55104481/e2c48e94-706e-4bd9-9fd2-6b740bdd3ffe
=> Fix the visibility of errors during helm app installation

shell/assets/translations/en-us.yaml, shell/components/GlobalRoleBindings.vue, shell/components/auth/RoleDetailEdit.vue, shell/pages/c/_cluster/auth/roles/index.vue, shell/plugins/clean-html-directive.js
- add deprecation notice for restricted-admin role in `user creation/edit` + `Role template list view` + `edit/detail view for global role of restricted-admin`
=> add deprecation notice for restricted-admin role

shell/promptRemove/management.cattle.io.project.vue
Reverts rancher/dashboard#9594
FYI @anupama2501
=> Revert "Delete project as cluster member -  option to not delete namespaces"

pkg/rancher-components/package.json, pkg/rancher-components/src/components/StringList/StringList.test.ts, pkg/rancher-components/src/components/StringList/StringList.vue, storybook/stories/components/StringList.stories.mdx
Fixes #9707
Add bulk addition option to string list component.
[rd.webm](https://github.com/rancher/dashboard/assets/8761082/5e341626-c84f-4b1e-907e-c6f3f779826e)
=> Add bulk addition to string list component

README.md
Improve the README text that introduces extensions. This also removes a there/their typo
=> Improve README extension intro

shell/components/Carousel.vue
Fixes #10002
Removed number from chart carousel title
=> Removed number from chart carousel title

cypress/e2e/po/pages/explorer/cluster-dashboard.po.ts, cypress/e2e/po/pages/explorer/cluster-tools.po.ts, cypress/e2e/po/pages/explorer/install-charts.po.ts, cypress/e2e/tests/pages/explorer/cluster-tools.spec.ts
This PR covers the functionality within the Cluster Tools window
View Test Plan https://github.com/rancher/qa-tasks/issues/761
Open bug causing tests to fail:: https://github.com/rancher/dashboard/issues/9940
=> cluster tools tests

shell/assets/translations/en-us.yaml, shell/edit/workload/index.vue
Fixes #4941
- This makes it clearer we only show certain types of secrets (docker related)
=> Add a tooltip to Workload image pull secret select

shell/assets/translations/en-us.yaml, shell/machine-config/__tests__/vmwarevsphere.test.ts, shell/machine-config/vmwarevsphere.vue
Fixes #9620 
https://github.com/rancher/dashboard/assets/135728925/0d297a40-a625-4609-865c-d330641ba330
https://github.com/rancher/dashboard/assets/135728925/ecdff31f-2d6a-4340-b62c-617dd69ad908
=> expose gracefulShutdownTimeout option for vsphere

shell/components/SortableTable/THead.vue
Fixes # https://github.com/rancher/elemental-ui/issues/133
- fix position of advanced table option
- Clone https://github.com/rancher/elemental-ui
- yarn link this branch `shell` to elemental-ui
- Run `elemental-ui` project (should appear the `Elemental` extension on the main nav menu)
- Go to `Elemental` - install operator if needed - then `Inventory of machines`, then go to the 3 dots next to `age` col and click it (create a `Inventory of machines` via YAML if needed)
- check that position of menu box is correct
_Before_
_After_
=> fix position of advanced table option

cypress/e2e/po/components/header.po.ts, cypress/e2e/po/components/namespace-filter.po.ts, cypress/e2e/po/components/shell.po.ts, cypress/e2e/po/components/workspace-switcher.po.ts, cypress/e2e/po/lists/pods-list.po.ts, cypress/e2e/po/pages/explorer/cluster-dashboard.po.ts, cypress/e2e/po/pages/explorer/workloads-pods.po.ts, cypress/e2e/po/pages/fleet/gitrepo-create.po.ts, cypress/e2e/tests/pages/explorer/namespace-picker.spec.ts, cypress/globals.d.ts, cypress/support/commands/rancher-api-commands.ts
This PR covers the functionality in Namespace picker
View Test Plan https://github.com/rancher/qa-tasks/issues/760
=> namespace picker tests

.github/workflows/test.yaml
Fixes #9885
Added suffix for both files and folders, while they will be merged together with everything.
=> Prevent overriding User E2E test coverage over Admin

.github/workflows/scripts/pr.js
This PR updates our Zube workflow.
When a PR is merged, any linked issues will be moved to "QA Review" instead of "To Test" IF the issue has the "QA/dev-automation' label - which indicates that automated tests should have been written for the issue and that QA need to review that these tests are sufficient to test the feature, rather than "To Test', which indicates that QA need to manually test the issue.
Tested this manually on a test repository.
=> Update Zube worklow to move issues to "QA Review" for QA/dev-automation

shell/initialize/index.js, shell/plugins/clean-html-directive.js, shell/plugins/clean-html.js, shell/plugins/clean-tooltip-directive.js, shell/plugins/index.js
Fixes #9920
To test:
Go to User Mgmt and the Restricted Admin role page.
Click on 'Release Notes' in the top banner and verify that this now opens in a new tab.
=> Support "target=_blank" in A links via clean-html directive

shell/edit/monitoring.coreos.com.prometheusrule/GroupRules.vue
Fixes #9926
1. Before adding a default rule, should make a copy of the default rule
=> fix(GroupRules): fix multiple alert rules modification errors

shell/edit/workload/Upgrading.vue
Fixes #9874
DaemonSet/StatefulSet  spec.updateStrategy.type can be "RollingUpdate" or "OnDelete". Default is RollingUpdate.
ref:
https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/daemon-set-v1/#DaemonSetSpec
=> fix(workload/Upgrading): fix DaemonSet/StatefulSet update strategy failed issue

shell/edit/monitoring.coreos.com.prometheusrule/AlertingRule.vue
Fixes #9923
1. add label and value to servrity options
=> fix(AleringRule): fix servrity options value error

docs/developer/README.md, docs/developer/api-resources-and-schemas.md, docusaurus/docs/code-base-works/api-resources-and-schemas.md
Move documentation specifically regarding APIs out of docusarus
=> Move API docs out of docusaurus

package.json, shell/components/CopyCode.vue, shell/components/CopyToClipboard.vue, shell/components/CopyToClipboardText.vue, shell/components/StatusTable.vue, shell/components/__tests__/CopyCode.test.ts, shell/components/form/Password.vue, shell/edit/provisioning.cattle.io.cluster/__tests__/CustomCommand.tests.ts, shell/initialize/index.js, shell/models/__tests__/management.cattle.io.cluster.test.ts, shell/models/management.cattle.io.cluster.js, shell/package.json, shell/plugins/vue-clipboard2.js, shell/utils/clipboard.js, yarn.lock
Fixes #9536 
Replaced vue-clipboard2 library with clipboard-polyfill as recommended by @nwmac.
clipboard-polyfill was chosen because it is supported by older browser versions. In the future, this library is unlikely to continue being maintained and should be eventually replaced by navigator.clipboard.writeText(...)
Replaced all uses of $copyText with a new function. Everything that needs to copy to clipboard is affected
Verify that the following copies content to the clipboard
1. Go to 'Cluster management' -> select a cluster -> click 'Copy KubeConfig to Clipboard'
2. Go to 'Users & User administration' -> 'Create' -> 'Generate a random password' -> Copy
3. Harvester -> Virtual machine image -> Copy image URL
4. First time login -> Both commands should be copied to clipboard on click.
5. …
=> [INT] Replaced vue-clipboard2 library with clipboard-polyfill

shell/edit/workload/mixins/workload.js
Fixes https://github.com/rancher/dashboard/issues/9978 fix err when save deployment and  service annotations is null
=> Fix err when save deployment and service annotations is null

shell/scripts/publish-shell.sh, shell/scripts/test-plugins-build.sh
Fixes #6871 
- After some investigation on how to run the e2e tests that are already coded for `Kubewarden` and `Elemental` from a Dashboard workflow, it's very difficult to achieve because one of those e2e it's written for `Playwright` ()kubewarden) and the other has a very specific environment that it runs on (elemental - https://github.com/rancher/elemental/tree/main/tests/cypress/latest).
Improving the `test-plugins-build` script to test extension build seems like an "easy" win in light to the work to run those e2e (if it's even possible to do so). With this we are increasing our test coverage on extension, even if indirectly.
- improve `test-plugins-build` script to test extension build with newly built version of the `shell` package
To test, just run …
=> improve test plugins build script

shell/edit/provisioning.cattle.io.cluster/AddOnConfig.vue, shell/edit/provisioning.cattle.io.cluster/Advanced.vue, shell/edit/provisioning.cattle.io.cluster/Basics.vue, shell/edit/provisioning.cattle.io.cluster/Etcd.vue, shell/edit/provisioning.cattle.io.cluster/Networking.vue, shell/edit/provisioning.cattle.io.cluster/Registries.vue, shell/edit/provisioning.cattle.io.cluster/Upgrade.vue, shell/edit/provisioning.cattle.io.cluster/__tests__/rke2.test.ts, shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes rancher/dashboard#9869
Part two to https://github.com/rancher/dashboard/pull/9566 
No behavior should change from this change.
RKE2 cluster provisioning and editing are affected. NO changes in behavior should be present. Refer to https://github.com/rancher/dashboard/pull/9566  for expected behavior description.
RKE2 cluster provisioning and editing.
=> Separated remaining tabs into separate components in rke2 file

.eslintignore, .github/workflows/check-plugins.yaml, shell/scripts/test-plugins-build.sh
Fixes #10116
Added artifacts upload on failure with 2 days of retention for the paths:
```
/tmp/tmp.**/test-app
!/tmp/tmp.**/test-app/node_modules/
!/tmp/tmp.**/test-app/pkg/test-pkg/node_modules/
```
- ~Commented removal logic for the process.~ Conditionally persisted build, default to remove
- Added logs for removed paths
- Updated RegEx to include `-alpha.x`, `-releasex.x.x` and `-rc.x` while selecting versions
- Excluded paths for `elemental-ui/` and `kubewarden-ui/` for eslint
=> Upload artifacts as output of check-plugins check for debugging

shell/chart/monitoring/index.vue
- Came in with https://github.com/rancher/dashboard/pull/10054
- The TODO relates to testing locally and shouldn't have been merged
=> Remove testing artefact

docusaurus/docs/code-base-works/nuxt-plugins.md, shell/components/nav/WindowManager/index.vue, shell/components/nuxt/nuxt-child.js, shell/config/store.js, shell/core/plugins-loader.js, shell/edit/auth/googleoauth.vue, shell/initialize/App.js, shell/initialize/index.js, shell/list/management.cattle.io.feature.vue, shell/middleware/authenticated.js, shell/mixins/auth-config.js, shell/pages/auth/setup.vue, shell/pages/c/_cluster/apps/charts/install.vue, shell/pages/support/index.vue, shell/plugins/axios.js, shell/plugins/back-button.js, shell/plugins/codemirror-loader.js, shell/plugins/dashboard-store/classify.js, shell/plugins/dashboard-store/index.js, shell/plugins/dashboard-store/mutations.js, shell/plugins/dashboard-store/resource-class.js, shell/plugins/steve/subscribe.js, shell/store/index.js, shell/store/prefs.js, shell/store/type-map.js, shell/utils/axios.js, shell/utils/nuxt.js, shell/utils/router.scrollBehavior.js, shell/vue.config.js
Fixes #10120 
- Remove all of the `process.client`, `process.server` and `process.static` mentions from Dashboard and adjust code.
Notes: 
- `process.client` was being set to `true` by default: https://github.com/rancher/dashboard/blob/master/shell/vue.config.js#L390
- `process.server` was exclusively related to SSR
- `process.static` seemed to be tied to nuxt generate, which is related to pre-rendering and was only `true` when the command `nuxt generate` ran, which we don't have on the codebase anymore
=> remove "process." mentions from Dashboard and adjust code

cypress/e2e/po/components/cluster-badge.po.ts, cypress/e2e/po/components/custom-badge-dialog.po.ts, cypress/e2e/po/components/header.po.ts, cypress/e2e/po/lists/events-list.po.ts, cypress/e2e/po/lists/nodes-list.po.ts, cypress/e2e/po/pages/explorer/cluster-dashboard.po.ts, cypress/e2e/po/pages/explorer/events.po.ts, cypress/e2e/po/pages/explorer/nodes.po.ts, cypress/e2e/tests/pages/explorer/cluster-dashboard.spec.ts, cypress/globals.d.ts, cypress/support/commands/rancher-api-commands.ts
This PR covers the functionality within the Cluster Explore pg
View Test Plan https://github.com/rancher/qa-tasks/issues/736
Note: some of the tests here rely on the [Cluster Tools](https://github.com/rancher/dashboard/pull/9749) branch which has yet to be merged into the master — I left comments for myself to update the code when that branch is merged in.
=> cluster explore page tests

.github/workflows/release-shell-pkg.yaml, package.json, shell/package.json, shell/scripts/publish-shell.sh
Fixes #9796 
- Add automated workflow to publish @rancher/shell to npm
=> Add automated workflow to publish @rancher/shell to npm

.github/workflows/test.yaml
Fixes #10150
Allow to re-run just failed jobs and cut down the risks of flaky tests on the way.
Removed coverage for E2E and flags which will speed up process. Workflow is kept the same even if just unit tests for clearance and open to changes.
=> Remove coverage for E2E

shell/config/router.js, shell/initialize/client.js, shell/initialize/index.js, shell/utils/nuxt.js
Fixes #10130 
- Remove argument `ssrContext` from `createApp` function and it's subsequent calls, since it was only used as `null`
=> remove argument "ssrContext" from "createApp" function and it's subsequent calls

package.json, shell/components/nuxt/nuxt-child.js, shell/config/product/explorer.js, shell/initialize/App.js, shell/initialize/client.js, shell/initialize/index.js, shell/package.json, shell/plugins/transitions.js, yarn.lock
Fixes #10124 
- remove page transitions from Dashboard
- seems like the package `vue2-transitions` wasn't needed anymore, so I proceeded to remove it
-
=> remove page transitions from Dashboard

cypress/jenkins/junit_to_qase.py
This PR is fixing the Jenkins pipeline Qase reporting. The report script was creating duplicated Test Suites on Qase on certain conditions.
This fix increases the results limit to the maximum the Qase QQL API allow which is 100 but to prevent hitting this I've added a string lookup that will get unique results using the Qase QQL.
Sometimes the logic that checks if a Suite exist got limited results returned by the Qase API as the default limit is 10. Due to this as there wasn't a match then a new Suite was getting created.
Jenkins automation pipeline reporting
=> [Automation] - Fixing Qase Suites dupes by increasing results limit and using string matching

shell/assets/translations/zh-hans.yaml
Fixes #10174
fix: Chart Installation insufficient Memory Prompt Chinese translation error
=> fix(translations): fix insufficientMemory Chinese translation error

shell/components/EtcdInfoBanner.vue
Fixes #10172
Remove the curly braces `} `
=> fix(EtcdInfoBanner): fix canList getters access error

.github/workflows/release-shell-pkg.yaml, shell/scripts/publish-shell.sh
Fixes #9796
- update shell pkg workflow to release the remaining pkgs that are usually published in tandem with shell on npm
- This can't be unequivocally proven from a PR coming from a fork because we cannot access secrets, but this run https://github.com/rancher/dashboard/actions/runs/7264363457/job/19791741370?pr=10185 proves that the version number is correct and that the `YARN_REGISTRY` variable has been correct reset to point to NPM `https://registry.npmjs.org/`. Otherwise, this is the script we run "manually" to publish Shell and all it's packages to NPM so I believe it should work.
=> update shell pkg workflow to release the remaining pkgs that are usually published in tandem with shell on npm

shell/package.json
Fixes #
- revert changes to shell version - now back to current version (allows us to test newly merged workflow without actually publishing packages)
=> revert changes to shell version - now back to current version

shell/components/IconOrSvg.vue
Fixes #10198 
- Add missing check to string `BODY` on Safari and Firefox
https://github.com/rancher/dashboard/assets/97888974/99c48d11-969d-4a8b-92a7-bc9c73344604
=> fix bug with color utils

shell/assets/translations/en-us.yaml
Fixes #10192 
Removing an extra target attribute preventing the doc link from opening in a new tab.
=> Remove duplicate target attribute

storybook/stories/global.scss
Fixes #9754
Fix the `Description` section in the storybook doc section.
Run storybook > switch to dark theme > go to doc section of any components eg. `Alert` 
text should be visible for the `Description` section
===== Before ======
===== After ======
=> Fixed Description text in dark mode

shell/store/i18n.js
Fixes #10153
Fix plugin missing translation fallback
=> fix(i18n): Always load default language translation for fallback

jest.setup.js, shell/components/nav/WindowManager/ContainerLogs.vue, shell/components/nav/WindowManager/__tests__/ContainerLogs.test.ts
=> fix(ContainerLogs): fix display error if log is truncated

shell/assets/translations/en-us.yaml, shell/pages/c/_cluster/uiplugins/CatalogList/CatalogLoadDialog.vue
Fixes #10205
- caused via original translation changing to an object. see https://github.com/rancher/dashboard/pull/10028
- give this translation it's own entry... and use the same tooltip
=> Fix translation of Extension Import Catalog Secret

docusaurus/package.json
Reverts https://github.com/rancher/dashboard/pull/10204
- Reverts changes done in https://github.com/rancher/dashboard/pull/10204 as `image-size` as reverted the node version change https://github.com/image-size/image-size/compare/v1.1.0...v1.1.1
=> revert docusaurus build change

README.md
=> Update copyright year in README to 2024

shell/assets/images/providers/ovhcloudmks.svg, shell/assets/images/providers/ovhcloudpubliccloud.svg
Fixes #10065 (backport of https://github.com/rancher/dashboard/issues/10064 )
- added same logos as per https://github.com/rancher/dashboard/pull/10060
=> [2.7] Add Logo for OVHCloud (both RKE2 and Managed Kubernetes)

cypress/e2e/blueprints/explorer/nodes.ts, cypress/e2e/po/components/sortable-table.po.ts, cypress/e2e/tests/pages/explorer/node-list.spec.ts, cypress/globals.d.ts, cypress/support/commands/rancher-api-commands.ts, shell/components/formatter/PercentageBar.vue, shell/list/node.vue, shell/models/cluster/node.js
Fixes #9955
Fixes bug where some manually added nodes can break the node list page.
Automated e2e test included
=> Fix bug where a manually added node breaks the node list page

cypress/e2e/tests/pages/charts/prometheus.spec.ts
Fixes #10237 
- Remove chart version from the e2e test spec (fortunately all the checks didn't take that into account)
- Fix issue where we were looking for a `POST` on an endpoint ending in `?action=install`, which has turned into  `?action=upgrade`
- Just check if all the gates on this PR pass
=> Fix e2e tests failing on prometheus.spec

shell/components/AsyncButton.vue, shell/components/Certificates.vue, shell/components/DraggableZone.vue, shell/components/PodSecurityAdmission.vue, shell/components/form/Error.vue, shell/components/form/Footer.vue, shell/components/form/GitPicker.vue, shell/edit/management.cattle.io.podsecurityadmissionconfigurationtemplate.vue, shell/mixins/create-edit-view/index.js, shell/tsconfig.paths.json, shell/types/vue-shim.d.ts, shell/utils/git.ts
contributes to #10104
This replaces the usage of `Vue.extend` with `defineComponent` throughout multiple components located under `shell/components/`. `defineComponent` provides better type inference, improved TypeScript support, and will be the recommended way to define components when Dashboard migrates to Vue 3.
- Replaced instances of `Vue.extend` with `defineComponent` for components located under `shell/components/`
- Refactored code as necessary to maintain to take advantage of the better TypeScript support
Omitting updates to `Vue.extend` in `shell/mixins/compact-input.ts` & `shell/mixins/labeled-form-element.ts`. Updating these mixins to use `defineComponent` caused compilation errors that I don't think will be worth assessing, given that `shell/composables/useCompactInput.ts` & …
=> Replace `Vue.extend` with `defineComponent` in shell

shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #10250 
https://github.com/rancher/dashboard/assets/135728925/ed635e03-91eb-4a02-9b23-1ea92bbab6c1
=> fixed passing fvUnreportedValidationErrors to CruResource

shell/initialize/App.js, shell/initialize/client.js, shell/initialize/index.js, shell/mixins/fetch.client.js, shell/vue.config.js
Fixes #9979 
backport of https://github.com/rancher/dashboard/issues/9542
As per https://github.com/rancher/dashboard/pull/9543
=> [2.7] Fix white page errors in prod

cypress/e2e/po/side-bars/burger-side-menu.po.ts, cypress/e2e/tests/pages/charts/istio.spec.ts, cypress/e2e/tests/pages/explorer/cluster-dashboard.spec.ts, cypress/e2e/tests/pages/extensions/extensions.spec.ts, cypress/e2e/tests/pages/fleet/dashboard.spec.ts, cypress/e2e/tests/pages/fleet/gitrepo.spec.ts, cypress/e2e/tests/pages/global-settings/branding.spec.ts, cypress/e2e/tests/pages/manager/cluster-manager.spec.ts, cypress/e2e/tests/pages/users-and-auth/roles.spec.ts, shell/components/nav/TopLevelMenu.vue, shell/config/product/fleet.js
Fixes #10010 
- Add method `checkActiveRoute` to check and apply a class `active-menu-link` to main nav menu items
- Update Fleet product route to enforce the use of `blank` cluster
- Update e2e tests in key places to check if main nav menu items are highlighted correctly when navigating to sub-routes
- Update e2e tests for Fleet to navigate to it's routes using `blank` cluster
- Generally test navigation to all the different products Rancher Dashboard has to offer
=> Fix highlight main nav menu items

shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes https://github.com/harvester/harvester/issues/4350
This is meant to add Machine Pools validation before editing Yaml file; the yaml Validation is triggered after the user clicks on 'Edit as YAML' button and saves the Machine Configurations:
=> Validate Harvester clusters

shell/assets/translations/en-us.yaml, shell/components/ExplorerProjectsNamespaces.vue, shell/components/ResourceDetail/Masthead.vue
Fixes #9790 
- Adds CSS in order to display truncated name of Project in `list` view and `edit` view
- Cannot write any tests from "ellipsis-ed" text (tried for 4 hours e2e tests until I realised it's not possible - we can only assert the inner text of the element rather than the rendered text)
- Create a project with a long name and check the `list` view and `edit` view
=> Truncate long Project names

shell/config/system-namespaces.js, shell/models/__tests__/namespace.test.ts, shell/models/namespace.js
Fixes #10214 
- update logic to decide if a namespace is a system one
- improve curated list of system namespaces
- update unit tests
Agreed with @nwmac the curated list of system namespaces + the change in the `isSystem` logic
=> System namespaces curation

shell/pages/c/_cluster/uiplugins/CatalogList/index.vue
=> fix(CatalogList): fix catalog action menu display error

cypress/e2e/tests/pages/manager/cilium-cni.spec.ts, shell/assets/translations/en-us.yaml, shell/edit/provisioning.cattle.io.cluster/__tests__/Basics.test.ts, shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/edit/provisioning.cattle.io.cluster/tabs/Basics.vue
Fixes #10049
This is a re-work of this PR: https://github.com/rancher/dashboard/pull/10050
This PR updates the approach slightly to follow the work done in this related PR: https://github.com/rancher/dashboard/pull/10304 and it adds automated tests.
The test follow the same approach as the PR mentioned above and verify that the setting is sent to the backend via an e2e test and also checks various config is set correctly via unit tests.
=> Cilium bandwidth manager support

shell/package.json
Releases `@rancher/shell` version `0.5.0`
This is a Minor version bump for the breaking changes:
- https://github.com/rancher/dashboard/pull/10084
- https://github.com/rancher/dashboard/pull/10072
=> Bump shell version `0.5.0`

pkg/rancher-components/package.json
Fixes #
- bump rancher components version to prepare for release of new version of lib
=> bump rancher components version to prepare for release of new version of lib

pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue
Reverts rancher/dashboard#10226 due to the problem with usage of defineComponent and extensions
when comparing with the original PR, I decided to leave the composables created as they aren't used anywhere and we should be able to revert this situation in the future. There are unit tests associated with them, which are deleted in https://github.com/rancher/dashboard/pull/10346
=> Revert "Replace `Vue.extend` with `defineComponent` in `LabeledInput.vue`"

shell/package.json
=> bump shell pkg version

pkg/rancher-components/package.json
- bump rancher components version
=> bump rancher components version

shell/components/nav/TopLevelMenu.vue
Backport of PR https://github.com/rancher/dashboard/pull/10242
Fixes #10357 
- Fix breaking of `TopLevelMenu` component when `ui-banner` settings has an old structure (upgrade scenario from an old version)
- `FixedBanner` component, which is responsible for the rendering of the banners already covers the above scenario (double-checked)
- Edit the code for the `TopLevelMenu` component https://github.com/rancher/dashboard/blob/master/shell/components/nav/TopLevelMenu.vue#L73 so that:
```
const parsed = {
banner: {
color:      '#78c9cf',
background: '#27292e',
text:       'Hello World!'
},
showHeader: 'true',
showFooter: 'false'
};
```
- Check that no error is thrown on the console or UI
=> backport fix for 10140

shell/store/plugins.js
This is a backport of https://github.com/rancher/dashboard/pull/10313. For details see description
=> Adding ovhcloudpubliccloud to the driverToCloudProvider map in order to restrict options for Cloud Provider

storybook/package.json
Fixes #10373 
- Pin `polished` lib to version `4.2.2` which is compatible with node 16 in order to fix pipeline issues
=> Pin `polished` lib to version `4.2.2` which is compatible with node 16

shell/assets/images/providers/ovhcloudmks.svg, shell/assets/images/providers/ovhcloudpubliccloud.svg
Summary
Fixes https://github.com/rancher/dashboard/issues/10233 (backport of https://github.com/rancher/dashboard/issues/10064 )
Occurred changes and/or fixed issues
added same logos as per https://github.com/rancher/dashboard/pull/10060
=> Add Logo for OVHCloud (both RKE2 and Managed Kubernetes)

shell/edit/monitoring.coreos.com.alertmanagerconfig/types/opsgenie.vue, shell/edit/monitoring.coreos.com.alertmanagerconfig/types/pagerduty.vue, shell/edit/monitoring.coreos.com.alertmanagerconfig/types/slack.vue
Fixes https://github.com/rancher/dashboard/issues/10389
=> Rename proxyURL field in monitoring configs page

shell/pages/c/_cluster/uiplugins/AddExtensionRepos.vue, shell/pages/c/_cluster/uiplugins/SetupUIPlugins.vue, shell/pages/c/_cluster/uiplugins/__tests__/AddExtensionRepos.test.ts, shell/pages/c/_cluster/uiplugins/__tests__/SetupUIPlugins.test.ts
Fixes #10343  
- update logic of `AddExtensionRepos` and `SetupUIPlugins` components to only show the checkbox to add Official Rancher Extensions if the product is Prime
- Make sure your Rancher is **not** Prime
- Go to `Extensions` -> 3 dots on the top right -> `Add repositories`
- Make sure that the modal **doesn't display** a checkbox to `Add Official Rancher extensions repository`
- Change https://github.com/rancher/dashboard/blob/master/shell/config/version.js#L6-L8 to return `true` (is Prime)
- Go to `Extensions` -> 3 dots on the top right -> `Add repositories`
- Make sure that the modal **displays** a checkbox to `Add Official Rancher extensions repository`
=> Only add Rancher UI Extension repository if prime

.github/pull_request_template.md
- Ensure all checkboxes can be ticked (where not applicable)
=> Updates to PR checklist

shell/assets/translations/en-us.yaml, shell/components/CodeMirror.vue, shell/components/YamlEditor.vue, shell/components/__tests__/CodeMirror.spec.ts, storybook/stories/form/Editor.stories.mdx
Fixes https://github.com/rancher/dashboard/issues/9757
It adds a small box on top-right of the YAML editor, with the `keymap` preference of the User (Yaml, Emacs, Normal Human)
- Yaml editor
view 
mouse over
overlay
Storybook
=> Add keymap info box to Yaml Editor

cypress/e2e/tests/pages/explorer/apps/charts.spec.ts, cypress/e2e/tests/pages/explorer/cluster-dashboard.spec.ts, cypress/e2e/tests/pages/explorer/storage/configmap.spec.ts, cypress/e2e/tests/pages/extensions/extensions.spec.ts, cypress/e2e/tests/pages/fleet/dashboard.spec.ts, cypress/e2e/tests/pages/global-settings/settings.spec.ts, shell/components/ResourceDetail/Masthead.vue, shell/components/ResourceList/Masthead.vue, shell/components/TabTitle.vue, shell/components/__tests__/TabTitle.test.ts, shell/components/nav/Type.vue, shell/config/private-label.js, shell/initialize/client.js, shell/pages/about.vue, shell/pages/account/index.vue, shell/pages/c/_cluster/apps/charts/index.vue, shell/pages/c/_cluster/explorer/index.vue, shell/pages/c/_cluster/explorer/tools/index.vue, shell/pages/c/_cluster/settings/brand.vue, shell/pages/c/_cluster/settings/links.vue, shell/pages/c/_cluster/uiplugins/index.vue, shell/pages/home.vue, shell/pages/prefs.vue, shell/pages/support/index.vue, shell/utils/title.ts
=> More informative page titles

shell/edit/provisioning.cattle.io.cluster/tabs/registries/RegistryConfigs.vue
Fixes #10412 
Vue was not able to re-render items properly after removing an item because of not providing a unique key.
https://github.com/rancher/dashboard/assets/135728925/32767e9a-0f19-420a-b1de-f40d07e833c4
=> Fix SelectOrCreateAuthSecret not re-rendering properly after removing

cypress/e2e/po/components/checkbox-input.po.ts, cypress/e2e/tests/pages/charts/monitoring-istio.spec.ts, cypress/e2e/tests/pages/global-settings/banners.spec.ts, cypress/e2e/tests/pages/global-settings/branding.spec.ts, cypress/e2e/tests/pages/user-menu/preferences.spec.ts, pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue, shell/edit/provisioning.cattle.io.cluster/tabs/Basics.vue
fix issue with squashed custom box in Checkbox + add tests + sneaky fix for prop as computed
Fixes #10000 
- fix issue with squashed custom box in Checkbox 
- add tests 
- sneaky fix for prop as computed
- Follow repro steps in #10000 and make sure box is not squashed and is always 14px x 14px
=> fix issue with squashed custom box in Checkbox

cypress/e2e/po/components/checkbox-input.po.ts, cypress/e2e/po/pages/preferences.po.ts, cypress/e2e/tests/pages/user-menu/preferences.spec.ts, shell/assets/translations/en-us.yaml
Fixes #8670 
-change label text to a more meaningful copy 
- add test
=> Preferences: The functionality of the 'Hide All Type Descriptions' checkbox is unclear to user

.github/workflows/port-pr.yaml
This add the Port PR workflow to Dashboard, this workflow is taken from internal docs provided with the rancherbot shutdown announcement. [^1]
closes #10218 
[^1]: https://github.com/rancherlabs/rancherbot/blob/master/ALTERNATIVES.md#backportingforwardporting-issues
=> Add the Port PR workflow

shell/config/router.js, shell/initialize/index.js, shell/middleware/authenticated.js, shell/pages/fail-whale.vue
Removing code from the authenticated middleware that doesn't perform authentication. Doing this slowly to make removing the authenticated middleware more tractable.
=> Removal a small chunk of code that doesn't preform any authentication from the authenticated middleware

.github/workflows/test.yaml, cypress.config.ts, cypress/e2e/po/components/resource-yaml.po.ts, cypress/e2e/po/pages/explorer/workloads/workloads.po.ts, cypress/e2e/tests/components/yaml-editor.spec.ts, cypress/e2e/tests/setup/rancher-setup.spec.ts, cypress/globals.d.ts, cypress/support/commands/chainable.ts, cypress/support/e2e.ts, docusaurus/docs/testing/e2e-test.md
Related issue: https://github.com/rancher/dashboard/issues/8999
It adds e2e tests for `ResourceYaml` component.
- Check body and footer to be visible at human eye.
- Add new `components` tag for UI elements.
- Add new Cypress Command to check elements visibility.
=> E2E Test: YAML editor

shell/config/uiplugins.js, shell/vue.config.js
=> Bugfix/10543 extensions 2.7 dev

cypress.config.ts, cypress/e2e/blueprints/global/settings/links.ts, cypress/e2e/po/components/component.po.ts, cypress/e2e/po/pages/global-settings/home-links.po.ts, cypress/e2e/po/pages/home.po.ts, cypress/e2e/tests/pages/generic/collective.spec.ts, shell/assets/translations/en-us.yaml, shell/config/home-links.js, shell/pages/c/_cluster/settings/DefaultLinksEditor.vue, shell/pages/c/_cluster/settings/links.vue
Fixes #10393
Backport of PR to 2.8: [#10393](https://github.com/rancher/dashboard/pull/10496)
=> [2.8 backport] Add SUSE Collective doc link (prime)

shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #10549 
Backport of PR to 2.8 => https://github.com/rancher/dashboard/pull/10251
=> [2.8 Backport] Fix Closing vSphere's Error Banners

shell/components/form/ArrayListSelect.vue, shell/machine-config/__tests__/vmwarevsphere.test.ts, shell/machine-config/vmwarevsphere.vue
Fixes #10550 
Backport of PR to 2.8 => https://github.com/rancher/dashboard/pull/10143
=> [2.8 Backport] Expose raw data in vSphere cluster form

shell/edit/provisioning.cattle.io.cluster/MachinePool.vue, shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/machine-config/__tests__/vmwarevsphere.test.ts, shell/machine-config/vmwarevsphere.vue
Fixes #10531 
Backport of PR to 2.8 => https://github.com/rancher/dashboard/pull/10477
=> [2.8 Backport] Fix default values for vSphere when adding a new pool

shell/components/LandingPagePreference.vue, shell/components/SingleClusterInfo.vue, shell/plugins/dashboard-store/actions.js, shell/store/index.js
Fixes #10370
Summary
This is a backport of https://github.com/rancher/dashboard/pull/10313. For details see description
=> [2.8] Avoid duplicate / surplus requests to fetch mgmt clusters

shell/assets/translations/en-us.yaml, shell/machine-config/azure.vue
Fixes #10468
backport of https://github.com/rancher/dashboard/pull/10471
=> [2.8] Ensure Azure RKE2 default region is available with selected cloud credential

shell/assets/translations/en-us.yaml, shell/mixins/__tests__/chart.test.ts, shell/mixins/chart.js, shell/models/catalog.cattle.io.app.js
Fixes https://github.com/rancher/dashboard/issues/10409
It adds warning messages when the User try to edit or delete a managed Application.
- cluster explorer-> Apps -> Installed Apps -> Edit application
managed app example - `traefik`
edit
delete
=> Add warning when edit/delete managed Apps

cypress/e2e/po/components/select-or-create-auth.po.ts, cypress/e2e/po/edit/chart-repositories.po.ts, cypress/e2e/po/lists/chart-repositories.po.ts, cypress/e2e/po/pages/chart-repositories.po.ts, cypress/e2e/po/pages/global-settings/home-links.po.ts, cypress/e2e/tests/pages/manager/repositories.spec.ts, cypress/globals.d.ts, cypress/support/commands/commands.ts, pkg/rancher-components/src/components/Form/TextArea/TextAreaAutoGrow.vue, shell/components/form/SelectOrCreateAuthSecret.vue, shell/components/form/__tests__/KeyValue.test.ts, shell/edit/catalog.cattle.io.clusterrepo.vue
Fixes #10461 
Backport of PR to 2.8 => https://github.com/rancher/dashboard/pull/10563
=> [2.8 Backport] Fix Create Repo with Secret

shell/assets/translations/en-us.yaml, shell/components/CruResource.vue, shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes https://github.com/rancher/dashboard/issues/10607
Backport of https://github.com/rancher/dashboard/pull/10073 -> requires backport of https://github.com/rancher/dashboard/pull/9798
=> [2.7 Backport] Implement Machine Pool Yaml Validation

shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #10605
Backport of https://github.com/rancher/dashboard/pull/10073
=> [2.8 Backport] Implement Machine Pool Yaml Validation

cypress/e2e/tests/pages/global-settings/feature-flags.spec.ts, shell/config/product/legacy.js
Fixes #10489 
Remove v1 tools/pages under the legacy navigation item, except for project config-maps and secrets
Deprecated items got removed from where we create the legacy menu items for the side nav in `legacy.js`. The removal of Ember pages will be addressed in a separate ticket #10617.
- Nothing noteworthy to mention
Enable legacy from Global Settings/Feature Flags
Go to Explore => Click on Legacy item from side nav
Check Items under Legacy
Shouldn't cause any regressions.
=> Remove v1 tools/pages under the legacy navigation item

package.json, scripts/e2e-docker-start
Issues in `v2.9-head` have been resolved in rancher/rancher#44808. This reverts the change introduced in #10630.
=> Target `v2.9-head` for e2e runs

shell/scripts/extension/helm/package/Dockerfile
This is a security related PR to bump BCI base image to 15.5, because 15.4 is EOL for quite some time and doesn't receive security updates.
=> Bump BCI image version to 15.5

shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml, shell/pages/c/_cluster/explorer/tools/index.vue
Fixes #10488
More information can be found reading these comments https://github.com/rancher/dashboard/issues/10488#issuecomment-2014672674
Just the cluster tools page
Just the cluster tools page
=> Removing legacy apps from cluster tools because they are no longer supported

shell/edit/__tests__/kontainerDriver.test.ts, shell/edit/__tests__/nodeDriver.test.ts
Fixes failing unit tests, eg https://github.com/rancher/dashboard/actions/runs/8456072084/job/23164999921?pr=10712#step:5:112
=> fix driver unit tests

cypress/e2e/tests/navigation/side-nav/main-side-menu.spec.ts, shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #10192 
- Add automated test for #10192
=> add e2e test to issue 10192

shell/components/Carousel.vue, shell/components/__tests__/Carousel.test.ts
Fixes #9975 
- code cleanup 
- fix breaking logic on unit test with non-existance of nodes to clone 
- add unit test to cover regression scenario of #9975 
- Go to `local` cluster -> apps -> charts and make sure carousel displays and works fine
screenshot of error in unit tests and why logic had to change slightly (doesn't happen in PROD because the `Carousel` render is gated by the existance of slides https://github.com/rancher/dashboard/blob/master/shell/pages/c/_cluster/apps/charts/index.vue#L387-L393)
=> 9975: code update and add unit test

cypress/e2e/po/components/header.po.ts, cypress/e2e/tests/pages/user-menu/preferences.spec.ts, shell/components/nav/Header.vue
=> 10153: add e2e test

.github/workflows/test.yaml, cypress/e2e/tests/pages/generic/get-support.spec.ts, cypress/e2e/tests/pages/generic/home.spec.ts, cypress/e2e/tests/pages/global-settings/branding.spec.ts, scripts/check-e2e-tests-for-tags
Fixes #
https://zube.io/rancher/rancher/c/64628
=> backport check-e2e-tags ci job to v2.8

cypress/e2e/blueprints/charts/prometheus-chart.ts, cypress/e2e/tests/pages/charts/monitoring-istio.spec.ts
Fixes # https://zube.io/rancher/dashboard-ui/c/10841
fix failing charts e2e tests to unblock CI
=> automation: fix failing charts tests

cypress/e2e/tests/pages/user-menu/preferences.spec.ts
Fixes #
https://github.com/rancher/qa-tasks/issues/1268
=> automation: add page reload to e2e test

shell/components/nav/TopLevelMenu.vue
Fixes #10694 
- Fix visual bug with cluster description on main side nav
- Follow repro steps on #10694 
**Before**
**After**
=> Fix visual bug with cluster description on main side nav

cypress/e2e/tests/components/yaml-editor.spec.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1241
=> automation: add intercept logic in yaml-editor test

cypress/e2e/po/components/select.po.ts, cypress/e2e/po/pages/charts.po.ts, cypress/e2e/tests/pages/explorer/apps/charts.spec.ts, shell/pages/c/_cluster/apps/charts/index.vue
Fixes #10027 
- add e2e test where filtering by either repo, category or text query should not affect entries in the carousel, as per description of #10027
=> 10027: add e2e test

cypress/e2e/tests/pages/users-and-auth/azuread.spec.ts
Fixes #10616
Added a missing test tag for AzureAD.spec.test
Added test tag
=> Added a missing test tag for AzureAD.spec.test

.github/workflows/pr-gh-project.yaml, .github/workflows/scripts/pr-gh-project.js
Fixes https://github.com/rancher/dashboard/issues/10501
This PR updates the GH Workflow to correctly read secrets in order to generate a token for GH Project access in workflows.
=> Update workflow to use secrets

.github/workflows/pr-gh-project.yaml
Addresses https://github.com/rancher/dashboard/issues/10501
This PR updates the GH Project workflow with a permission that is needed.
=> GH Projects action: Add required permission to write id token

jest.setup.js, shell/components/form/__tests__/KeyValue.test.ts, shell/composables/useStore.ts, shell/initialize/index.js, shell/initialize/plugins.js, shell/plugins/i18n.js
=> recreate phil PR 10801 for testing

.github/workflows/scripts/pr-gh-project.js
Fixes yet another bug in the script
=> GitHub Project migration script bug fix

.github/workflows/scripts/pr-gh-project.js, .github/workflows/scripts/request.js
=> Fix for issue number on GH Project automation

.github/workflows/scripts/pr-gh-project.js
Final fix I hope to the parsing of the repo URL
=> GitHub Project action: Fix repository URL parsing

.github/workflows/scripts/pr-gh-project.js, .github/workflows/scripts/request.js
Should be 'Review' not 'In Review'
Also updated the logging
=> GitHub Project automation -  fix review state name

.github/workflows/scripts/pr-gh-project.js
Fix for the wrong ID being used when moving the issue on the board.
Tweaked the Logging
=> GitHub Action: GH Projects: Fix ID used to move issue on board

shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml, shell/pages/c/_cluster/explorer/tools/index.vue
https://github.com/rancher/dashboard/issues/10277
https://github.com/rancher/dashboard/issues/10276
[backport v2.8.x] https://github.com/rancher/dashboard/issues/10488#issuecomment-2014672674
=> [backport v2.8.x] Removing legacy apps from cluster tools because they are no longer supported

.github/workflows/scripts/pr-gh-project.js
Fixes a small bug with the GH action automation for GitHub projects.
=> GH Project Action: Fix clean labels bug

scripts/e2e-docker-start
Backend has addressed issue which broke things.
Un-pinning the backend to pick up the latest version.
=> Unpin Rancher backend

pkg/harvester-manager/machine-config/harvester.vue, shell/assets/translations/en-us.yaml, shell/components/form/ArrayListSelect.vue, shell/components/form/Select.vue
Fixes https://github.com/rancher/dashboard/issues/10916
See https://github.com/rancher/dashboard/pull/10911
=> [2.8] Validate allocatable vGPUs number in Harvester clusters creation

.github/workflows/test.yaml, docusaurus/docs/code-base-works/on-screen-text-and-translations.md, scripts/check-i18n, shell/components/AsyncButton.vue, shell/components/CommunityLinks.vue, shell/components/GlobalRoleBindings.vue, shell/components/ResourceDetail/Masthead.vue, shell/components/SortableTable/index.vue, shell/components/TypeDescription.vue, shell/components/Wizard.vue, shell/components/fleet/FleetRepos.vue, shell/config/home-links.js, shell/config/uiplugins.js, shell/edit/management.cattle.io.setting.vue, shell/edit/monitoring.coreos.com.alertmanagerconfig/receiverConfig.vue, shell/edit/workload/mixins/workload.js, shell/edit/workload/storage/emptyDir.vue, shell/mixins/auth-config.js, shell/models/fleet.cattle.io.gitrepo.js, shell/models/management.cattle.io.globalrole.js, shell/models/monitoring.coreos.com.receiver.js, shell/models/service.js, shell/pages/c/_cluster/longhorn/index.vue, shell/pages/c/_cluster/neuvector/index.vue, shell/pages/c/_cluster/uiplugins/index.vue, shell/pages/support/index.vue, shell/plugins/plugin.js, shell/store/type-map.js, shell/utils/time.js, shell/utils/validators/index.js
Fixes https://github.com/rancher/dashboard/issues/10358
This PR adds a script that checks that we are not missing i18n strings that are referenced in code.
Currently the check added to our CI workflow does not fail if there are missing strings.
Added to the i18n docs to describe the script and the comments that can be used to correct detections.
In addition to the script, this PR uses the new i18n comments to correct some uses in our code base - more to be done and we need to address the 16 missing strings that are detected.
=> Add i18n string usage checker script

cypress/e2e/po/components/sortable-table.po.ts, cypress/e2e/po/detail/provisioning.cattle.io.cluster/cluster-detail.po.ts, cypress/e2e/po/lists/cluster-conditions-list.po.ts, cypress/e2e/po/lists/cluster-provisioning-log.po.ts, cypress/e2e/po/lists/cluster-referred-to-list.po.ts, cypress/e2e/po/lists/machine-pools-list.po.ts, cypress/e2e/po/pages/cluster-manager/cluster-manager-list.po.ts, cypress/e2e/tests/pages/manager/cluster-manager.spec.ts
Related task https://github.com/rancher/qa-tasks/issues/758
Adding navigation to the Conditions and Related Resources tabs on Cluster Details.
Navigation and basic assertion of tables and rows content.
N/A
Automation
- [ x ] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [ x ] The PR has a Milestone 
- [ x ] The PR template has been filled out
- [ x ] The PR has been self reviewed 
- [ x ] The PR has a reviewer assigned
- [ x ] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
=> [Automation] - Cluster Details - Conditions and Related

cypress/e2e/tests/pages/generic/home.spec.ts
Fixes #
Address test failure in Jenkins/GA 
[Home Page.Home Page.Can navigate to release notes page for latest Rancher version](https://jenkins.int.rancher.io/job/rancher_qa/job/ui-automation-job/848/testReport/junit/Home%20Page/Home%20Page/Can_navigate_to_release_notes_page_for_latest_Rancher_version/)
[Video Recording](http://139.59.134.103/instance/7777eda8-e984-4737-8391-292698f36d88/others/RECORDED_VIDEO)
=> fix home page test

cypress/e2e/po/edit/management.cattle.io.globalrole.po.ts, cypress/e2e/po/edit/role.po.ts, cypress/e2e/po/pages/users-and-auth/roles.po.ts, cypress/e2e/tests/pages/users-and-auth/roles.spec.ts
Fixes #9800 (e2e testing)
- Add e2e test to prevent regression of issue #9800  , related to user created `GlobalRoles` which were falsely indicated in the UI as built-in
=> add e2e test for issue 9800

cypress/e2e/blueprints/nav/fake-cluster.ts, cypress/e2e/blueprints/nav/k8s-schemas.ts, cypress/e2e/po/pages/explorer/workloads-daemonsets.po.ts, cypress/e2e/tests/pages/explorer/workloads/daemonsets.spec.ts
Fixes #9874 (e2e testing)
- Adds pattern to e2e tests for editing a `daemonset` on a fake cluster
- Add e2e test to prevent regression of issue #9874 , related to Scaling and Upgrade Policy sending the wrong type string for option `On Delete`
=> add e2e test for issue 9874

cypress/e2e/po/detail/provisioning.cattle.io.cluster/cluster-detail.po.ts, cypress/e2e/po/pages/cluster-manager/namespace.po.ts, cypress/e2e/tests/pages/manager/cluster-manager.spec.ts, shell/components/ResourceDetail/Masthead.vue
Fixes #9993
This PR adds e2e test for the above issue.
=> Add e2e test for cluster manager namespace bug

shell/pages/auth/login.vue, shell/pages/auth/verify.vue
https://github.com/rancher/dashboard/issues/
Fixes #10974 
In the self review comments I mentioned auth/verify being broken. This is due to the removal of the invocation of legacy fetch methods. I explained in a little more detail in that comment.
Logging in with different auth providers. I've opened an issue to add test automation around auth providers https://github.com/rancher/dashboard/issues/10984
Logging in
https://github.com/rancher/dashboard/assets/55104481/91fea7ad-edb4-406e-8665-4b84b5c057cb
=> Resolve an issue where we weren't allowing users to login with other auth providers

cypress/e2e/po/components/certificates.po.ts, cypress/e2e/po/components/tabbed.po.ts, cypress/e2e/po/lists/secrets-list.po.ts, cypress/e2e/po/pages/explorer/cluster-dashboard.po.ts, cypress/e2e/po/pages/explorer/secrets.po.ts, cypress/e2e/tests/pages/explorer/dashboard/certificates.spec.ts, cypress/e2e/tests/pages/explorer/dashboard/cluster-dashboard.spec.ts, shell/assets/translations/en-us.yaml, shell/components/Certificates.vue, shell/components/Tabbed/index.vue, shell/components/__tests__/Certificates.test.ts, shell/pages/c/_cluster/explorer/index.vue
Fixes #10025
- e2e test to confirm table renders, correct state for expired is shown and the link to the full secret list works
- unit test to confirm expiring banner is shown (this can't be done in e2e test)
Also fixed an issue where the certificates list still filtered itself by namespace
=> Add automated tests for Cluster Dashboard Certificates view

pkg/harvester-manager/machine-config/harvester.vue, shell/components/form/ArrayList.vue
Fixes https://github.com/rancher/dashboard/issues/10982
Fixes https://github.com/rancher/dashboard/issues/10947
- It will limit the number of assigned vGPUs to 1 to prevent allocation issues.
- Label format is revisited.
We will remove the constraint once Harvester will support multiple vGPUs in Rancher provisioning.
Add button
Add button disabled
=> Limit number of assigned vGPUs to 1 for each Machine Pool

cypress/e2e/po/components/select-icon-grid.po.ts, cypress/e2e/po/pages/explorer/charts/chart.po.ts, cypress/e2e/po/pages/explorer/charts/charts.po.ts, cypress/e2e/tests/pages/explorer/apps/charts.spec.ts, cypress/e2e/tests/pages/explorer/apps/repositories.spec.ts, shell/pages/c/_cluster/apps/charts/index.vue
Fixes #10868
- includes some improvements to another test to ensure state is correct before and after
- also includes some helpers for chart grid
=> Add automated tests to ensure Chart icons are correct

docusaurus/docusaurus.config.js
Updates to have docusaurus at extensions.rancher.io
=> Update docusaurus for extensions domain

docusaurus/docusaurus.config.js
=> revert url change for docusaurus

docusaurus/docusaurus.config.js
Testing different URL to get publishing working
=> Docusarus site: Trying a different URL

.github/workflows/docusaurus.yaml, docusaurus/docusaurus.config.js
Fix extensions.rancher.io for docs
=> Extensions docs: Add cname to gh-pages branch

shell/assets/translations/en-us.yaml
This updates the labels for the new User fields so that their behavior is made more clear. Rationale regarding this change can be found in  #10978. 
Fixes #10978
=> Update user Deleted/Disabled labels

docusaurus/docs/extensions/migration.md, package.json, shell/scripts/vue-migrate.js
Fixes #9541
This script is not aimed at fixing 100% of the issues and will require manual tests and further reviews.
Unit test migration to be carried with external script `npx vue-upgrade-tool --files 'shell/**/*.test.ts'` as defined in the documentation.
- Created script to fully migrate Rancher Dashboard and Extensions to Vue3
- Added documentation with current state-of-art
=> Create Vue3 migration script: upgrade libraries, configuration, syntax and tools (extension ready)

shell/vue.config.js
Fixes #11000
Mainly split into functions, making the exported configuration more linear, with meaningful names and better-pinned comments.
I took the chance to use more modern syntax in some cases and avoided single assignments in trivial cases.
=> Vue config cleanup

cypress/e2e/po/detail/fleet/fleet.cattle.io.gitrepo.po.ts, cypress/e2e/po/pages/fleet/fleet.cattle.io.gitrepo.po.ts, cypress/e2e/tests/pages/fleet/gitrepo.spec.ts, shell/detail/fleet.cattle.io.gitrepo.vue, shell/models/fleet.cattle.io.gitrepo.js, shell/pages/c/_cluster/fleet/index.vue
Fixes #9866 
- add cluster tab to git repo details 
- improve code on fleet dashboard view (better code abstraction + adding missing data fetches, etc) 
- fix count of clusters in fleet dashboard view badges (`targetClustersReady` prop)
- add e2e test for 9866
- Follow repro steps of #9866 and check that the following views in Fleet all work fine: Dashboard view, Git Repo list view, Git Repo detail view, Git Repo edit view.
**Note:** if you are having problems finding proper examples of git repos to add in order to test functionality, just check what was done in `gitrepo.spec.ts` and re-create those manually on Rancher Dashboard. They use a repo called `fleet-examples` and work just fine (this is repo is also mentioned in the official docs for Fleet)
Mentioned in the previous point
> - …
=> Test GitRepo detail view displays incorrect number of bundles + code improvements and fixes

cypress/e2e/po/components/header.po.ts, cypress/e2e/po/pages/explorer/cluster-dashboard.po.ts, cypress/e2e/tests/pages/explorer/dashboard/cluster-dashboard.spec.ts, cypress/e2e/tests/pages/explorer/resource-search.spec.ts, shell/components/nav/Header.vue
Fixes https://github.com/rancher/qa-tasks/issues/762
- Adding actions locators to the Header Actions page object. 
- Including a couple of new tests to ensure functionality. 
- Some tests like the Search component exist on their own test suite.
Automation Pipelines
Header Actions. There are new `data-testid` properties added. But is very low risk.
=> [Automation] - Cluster Actions Header

shell/initialize/client.js, shell/utils/nuxt.js
Removing a few more pieces of dead code that I noticed
Nowhere, the code shouldn't be used.
=> Removing a few more pieces of dead code that I noticed

shell/initialize/App.vue, shell/initialize/index.js, shell/utils/nuxt.js
Convert App.js to App.vue to make a standard component with a template
Either nowhere or everywhere since it's the root of the app.
=> Convert App.js to App.vue to make a standard component with a template

.github/workflows/docusaurus.yaml, .github/workflows/test.yaml, shell/creators/pkg/files/.github/workflows/build-container.yml, shell/creators/pkg/files/.github/workflows/build-extension.yml
Contributes to https://github.com/rancher/dashboard/issues/10663
Backports of
- https://github.com/rancher/dashboard/pull/11107
- https://github.com/rancher/dashboard/pull/11015
- different files
- https://github.com/rancher/dashboard/pull/11023
- ~https://github.com/rancher/dashboard/pull/11021~ not applicable
=> [2.7] Backport changes for gh action updates 

cypress/e2e/blueprints/global_settings/settings-data.ts, cypress/e2e/tests/pages/global-settings/settings-p2.spec.ts, cypress/e2e/tests/pages/global-settings/settings.spec.ts
Fixes #https://github.com/rancher/dashboard/issues/10613
- Consolidated server-url tests into one `it` block
-  enable and updated the original test to reflect the new behavior
=> update server-url tests

shell/initialize/app-extended.js, shell/utils/nuxt.js
Removing some more unused code
We don't use async components so we can remove a chunk of code we don't need. The rest was dead code that wasn't referenced anywhere.
=> Removing some more unused code

README.md, docusaurus/docusaurus.config.js, docusaurus/src/components/Contribute/index.js, docusaurus/src/components/HomepageFeatures/index.js, docusaurus/src/pages/index.js
Fixes broken links in the readme and on the docs landing page.
Extra fixes for: #11116
=> Fix broken links on readme and docs homepage

.github/workflows/fossa.yaml
- As per slack (link on request), three's a security team provided fossa workflow
- This is it for us...
=> Add new FOSSA worfklow

shell/list/management.cattle.io.feature.vue
Ensure we look at the correct resource type when enabling Feature Flag edits
- Backport of https://github.com/rancher/dashboard/pull/9759
- Reach out to me for more detail
=> Ensure we look at the correct resource type when enabling Feature Flag edits

cypress/support/utils/settings-utils.ts
Fixes #
- Fixes failing e2e tests due to problem on `rancher-setup` spec https://github.com/rancher/dashboard/actions/runs/9402395062/job/25896738866?pr=11164
=> update partial settings threshold (failing e2e tests)

shell/edit/provisioning.cattle.io.cluster/__tests__/rke2.test.ts, shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #11061 
- add `k8sDistro` dir to harvester cloud config path 
- add unit test
- I just tested RKE2 cluster provisioning in general and it's working, afaik. Don't know how to test this further
=> Rancher provisioned/managed RKE2/K3s data-dir support

cypress/e2e/blueprints/fleet/gitrepos.ts, cypress/e2e/po/components/sortable-table.po.ts, cypress/e2e/po/components/tabbed.po.ts, cypress/e2e/po/detail/fleet/fleet.cattle.io.cluster.po.ts, cypress/e2e/po/detail/fleet/fleet.cattle.io.gitrepo.po.ts, cypress/e2e/po/detail/fleet/tabs/bundles-tab.po.ts, cypress/e2e/po/detail/fleet/tabs/git-repos-tab.po.ts, cypress/e2e/po/edit/fleet/fleet.cattle.io.cluster.po.ts, cypress/e2e/po/lists/fleet/fleet.cattle.io.cluster.po.ts, cypress/e2e/po/lists/fleet/fleet.cattle.io.gitrepo.po.ts, cypress/e2e/po/pages/explorer/workloads/workloads.po.ts, cypress/e2e/po/pages/fleet/fleet.cattle.io.cluster.po.ts, cypress/e2e/po/pages/fleet/fleet.cattle.io.gitrepo.po.ts, cypress/e2e/tests/pages/fleet/fleet-clusters.spec.ts, cypress/e2e/tests/pages/fleet/gitrepo.spec.ts, cypress/globals.d.ts, cypress/support/commands/rancher-api-commands.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1359
=> fleet cluster list page

pkg/eks/assets/data/__tests__/eks-versions.tests.ts, pkg/eks/assets/data/eks-versions.js
Fixes #11195
Fixes the typo and adds a unit test to check that the versions in the array are valid.
=> Fix typo in EKS versions and add unit test

shell/models/provisioning.cattle.io.cluster.js, shell/pages/c/_cluster/explorer/__tests__/index.test.ts, shell/pages/c/_cluster/explorer/index.vue
Fixes https://github.com/rancher/dashboard/issues/10831
We want to show empty character during cluster provisioning phase.
Dashboard page
Clusters management page
=> Show empty architecture during cluster provisioning

cypress/e2e/po/detail/fleet/fleet.cattle.io.gitrepo.po.ts, cypress/e2e/tests/pages/fleet/gitrepo.spec.ts, shell/components/fleet/ForceDirectedTreeChart/index.vue
Fixes https://github.com/rancher/dashboard/issues/11133
It will fix the watchers; it needs to be triggered `immediate`.
Fleet -> Git Repos -> Details -> Graph
=> Fix Fleet Git repos - Graph tab

storybook/package.json
No issue is needed
Out storybook step was failing because of the Node version requirements. Currently, we do not want to upgrade to a higher node version.
Overwrote playwright version 
No area should be affected.
No area should be affected.
N/A
=> changed storybook  runner version

cypress/e2e/blueprints/explorer/workloads/pods/pods-get.ts, cypress/e2e/po/components/header-row.po.ts, cypress/e2e/po/components/sortable-table.po.ts, cypress/e2e/tests/pages/explorer/dashboard/cluster-dashboard.spec.ts, cypress/e2e/tests/pages/explorer/namespace-picker.spec.ts, cypress/e2e/tests/pages/explorer/workloads/pods.spec.ts, cypress/e2e/tests/pages/fleet/fleet-clusters.spec.ts, cypress/e2e/tests/pages/fleet/gitrepo.spec.ts, cypress/globals.d.ts, cypress/support/commands/rancher-api-commands.ts
Covers pagination functionality for pods list.
=> vai pagination tests - pods

shell/pages/c/_cluster/apps/charts/index.vue
Fixes #11042 
Add/remove query parameter `deprecated` when enabling/disabling the filter to preserve its state while navigating back and forth in browser.
https://github.com/rancher/dashboard/assets/135728925/af2fe441-681c-4ec2-a8b2-15755bb9da4c
=> Fix preserve filter status when navigating

shell/list/management.cattle.io.feature.vue
This PR:
1. stops printing errors to the console by removing the reassignment of the `rows` computed prop
2. adds a conditional to check the status of `waiting` before recursively calling `waitForBackend()`
Fixes #11175 
Fixes #11325
1. `rows` is a computed property and doesn't require reassignment; changes to the store will trigger reactivity, updating the list component
2. `waitForBackend()` had no terminating condition in its recursive calls. Adding one allows for properly clearing the timeout. 
- Global Settings => Feature Flags
- Modify a setting that Requires Restart
- Global Settings => Feature Flags
=> Resolve issues with Feature Flags that require restart

shell/package.json, shell/scripts/publish-shell.sh
bump shell version + make sure we delete local racher-components folder to fix manual release procedure
=> bump shell version + make sure we delete local racher-components folder to fix manual release procedure

shell/config/product/explorer.js, shell/config/types.js, shell/plugins/dashboard-store/actions.js, shell/store/type-map.utils.ts, shell/types/store/dashboard-store.types.ts, shell/types/store/vuex.d.ts
Fixes #11280
As per https://github.com/rancher/dashboard/pull/11215
- Some additional shell/types files were backported
=> Add conditional depagination by native api, apply to bindings

pkg/eks/assets/data/eks-versions.js
=> Add k8s v1.30 to EKS

pkg/aks/package.json, pkg/eks/package.json, pkg/gke/package.json
=> bump aks eks gke extensions to 1.0.0

shell/components/nav/TopLevelMenu.vue
Fixes #11368 
- update css to get SVG icon added from extension with the correct alignment in the top level menu
- Do a local build + developer load of the stackstate extension
- check that icon displays with the correct alignment
**before**
**after**
=> update css to get SVG icon added from extension with the correct alignment in the top level menu

pkg/harvester-manager/package.json
=> bump harvester-manager extension to 1.0.0

.github/workflows/check-plugins.yaml, .github/workflows/storybook.yaml, cypress/e2e/tests/pages/generic/about.spec.ts, package.json, shell/creators/app/app.package.json, shell/package.json, storybook/package.json
Fixes #
Fixes a couple of issues with node versions on our pipelines:
https://github.com/rancher/dashboard/actions/runs/9838028411/job/27157042656?pr=11376 and also  https://github.com/rancher/dashboard/actions/runs/9838028406/job/27157042446?pr=11376
=> update node version on workflows

shell/initialize/entry-helpers.js
Fixes https://github.com/rancher/dashboard/issues/11369
- We should identify other cases, if any, where the indicator should be triggered on route change.
=> Show loading indicator on route change

cypress/e2e/blueprints/explorer/more-resources/api/custom-resource-definition-get.ts, cypress/e2e/blueprints/explorer/more-resources/api/custom-resource-definition.yml, cypress/e2e/po/edit/custom-resource-definitions.po.ts, cypress/e2e/po/pages/explorer/custom-resource-definitions.po.ts, cypress/e2e/tests/pages/explorer/more-resources/api/custom-resource-definitions.spec.ts
Covers pagination functionality for resource list under CustomResourceDefinitions.
=> vai pagination tests - CustomResourceDefinitions

cypress/e2e/blueprints/roles/global-roles-get.ts, cypress/e2e/blueprints/users/users-get.ts, cypress/e2e/po/components/sortable-table.po.ts, cypress/e2e/po/pages/users-and-auth/roles.po.ts, cypress/e2e/po/pages/users-and-auth/users.po.ts, cypress/e2e/tests/pages/explorer/dashboard/events.spec.ts, cypress/e2e/tests/pages/user-menu/account-api-keys.spec.ts, cypress/e2e/tests/pages/users-and-auth/roles.spec.ts, cypress/e2e/tests/pages/users-and-auth/users.spec.ts, cypress/globals.d.ts, cypress/support/commands/rancher-api-commands.ts
Covers pagination functionality for resource list under 
- Users and Auth > Role Templates
- Users and Auth > Users
=> vai pagination tests - role templates and users

cypress/e2e/blueprints/fleet/workspaces-get.ts, cypress/e2e/po/detail/fleet/fleet.cattle.io.fleetworkspace.po.ts, cypress/e2e/po/lists/fleet/fleet.cattle.io.workspace.po.ts, cypress/e2e/po/pages/fleet/fleet.cattle.io.fleetworkspace.po.ts, cypress/e2e/tests/pages/fleet/advanced/workspaces.spec.ts, cypress/e2e/tests/pages/fleet/dashboard.spec.ts, cypress/globals.d.ts, cypress/support/commands/rancher-api-commands.ts
Covers pagination functionality for resource list under Fleet Workspaces
=> vai pagination test - Fleet Workspaces

shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes #10338 
A simple optional chaining in order to guard against `undefined` value.
=> Add optional chaining to guard against `undefined` value

shell/edit/provisioning.cattle.io.cluster/tabs/registries/RegistryConfigs.vue, shell/edit/provisioning.cattle.io.cluster/tabs/registries/__tests__/RegistryConfigs.test.ts
Fixes https://github.com/rancher/dashboard/issues/10725
=> Fix CA Bundle format

shell/components/AssignTo.vue
=> Add missing AppModal import to fleet workspace-changing modal

cypress/e2e/blueprints/charts/prometheus-chart.ts, cypress/e2e/tests/pages/charts/monitoring-istio.spec.ts
https://github.com/rancher/dashboard/actions/runs/9981860113/job/27586561849?pr=11468#step:8:72
sorrycypress reports suggest prometheusSpec has changed in the latest monitoring version
=> Fix monitoring tests' prometheusSpec data

.github/workflows/build-and-upload-release.yaml, shell/assets/translations/en-us.yaml
References to `v2.9-head` will need updating when there's a rancher 2.10 build
=> Updates following `release-2.9` branch

shell/edit/provisioning.cattle.io.cluster/tabs/registries/RegistryConfigs.vue, shell/edit/provisioning.cattle.io.cluster/tabs/registries/__tests__/RegistryConfigs.test.ts
Fixes https://github.com/rancher/dashboard/issues/11532
=> [backport v2.9.next1] Fix CA Bundle format

.github/workflows/test.yaml
Temporary disable codecov report upload - `secrets.CODECOV_TOKEN` is missing.
=> Temporary disable codecov report upload

cypress/e2e/tests/pages/explorer/apps/charts.spec.ts, cypress/e2e/tests/pages/explorer/apps/repositories.spec.ts
Forward port of https://github.com/rancher/dashboard/pull/11529
=> Fix two e2e tests given chart changes

shell/scripts/vue-migrate.js
This ensures that the path for locating eslint configs is based on the current working directory, which should be the same location as the `migrate` script command. 
- Use `process.cwd()` instead of `__dirname`
- This could cause issues if the script is run from outside the root directory for Rancher Dashboard
- Running the migration script
- Running the migration script outside of the root directory for Rancher Dashboard
=> Use `process.cwd()` for locating eslint files

shell/config/router/navigation-guards/runtime-extension-route.js
This is a backport of https://github.com/rancher/dashboard/pull/11556
=> [backport-v2.9] Fixing harvester cluster page reload routing + Harvester console button

shell/core/plugins.js
Fixes https://github.com/rancher/dashboard/issues/11559
=> Remove old extension from parentElement

shell/config/router/navigation-guards/index.js, shell/config/router/navigation-guards/page-title.js, shell/config/router/navigation-guards/server-upgrade-growl.js, shell/initialize/app-extended.js, shell/initialize/entry-helpers.js
Port some code from vue3 migration into master and reduce the amount of entry code
Any page, harvester more likely than other pages.
=> Port some code from vue3 migration into master and reduce the amount of entry code

shell/edit/provisioning.cattle.io.cluster/RegistryConfigs.vue, shell/edit/provisioning.cattle.io.cluster/__tests__/RegistryConfigs.test.ts, shell/edit/provisioning.cattle.io.cluster/__tests__/utils/cluster.ts
Fixes https://github.com/rancher/dashboard/issues/11533
=> [backport v2.8.next1]  Fix CA Bundle format

pkg/eks/components/Config.vue, pkg/eks/components/CruEKS.vue, pkg/eks/components/__mocks__/listKeys.js, pkg/eks/components/__tests__/Config.test.ts
Fixes #11569 
Backport of https://github.com/rancher/dashboard/pull/11576
=> [2.9.next1] EKS - fix secrets encryption with KMS key checkbox

pkg/aks/components/CruAks.vue, pkg/aks/components/__tests__/CruAks.test.ts
Backport of https://github.com/rancher/dashboard/pull/11644
Fixes https://github.com/rancher/dashboard/issues/11642
=> [2.9.1] AKS - fix default pool name

shell/assets/translations/en-us.yaml, shell/components/auth/RoleDetailEdit.vue, shell/config/roles.ts
Fixes #11647
Backport of https://github.com/rancher/dashboard/pull/11651
=> Fix duplicate group and options when creating global, cluster and project/namespace roles

cypress/e2e/po/pages/extensions.po.ts, cypress/e2e/tests/pages/extensions/extensions.spec.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1402
This pr adds an e2e test to check the versions for built-in extensions.
=> automation: check versions for built-in extensions

docusaurus/docs/extensions/advanced/safe-mode.md
Fixes #
- fix query param on docs to be correct (correct is `safemode` not `safeMode`)
=> fix query param on docs to be correct

cypress/jenkins/init.sh
Update the Jenkins init script to disable the `@vai` tags on Ranchers without the feature or the feature off by default.
Updated the init script, check the Rancher image tag and disable `@vai` tests accordingly.
Jenkins
CI Pipelines
=> [Automation] - Disable @vai tag on unsupported or default off Rancher

package.json, shell/initialize/install-plugins.js, shell/package.json, shell/plugins/vue-js-modal.js, shell/yarn.lock, storybook/yarn.lock, yarn.lock
This removes the `vue-js-modal` dependency from Dashboard. `vue-js-modal` is not compatible with Vue3 and has been previously replaced with `portal-vue` in #10591.
Fixes #9537
- Removes outdated `vue-js-modal` dependency
- See previous efforts in #10591
- Take note of Harvester issues from #10675
Also, take note of the changes in `storybook/yarn.lock`. It looks like additional changes were required to the lockfile, I'm guessing that most of these are a result of 1f6a726c9a64f18fdecc8eb50b5b12e1e766eedd
- This dependency was only kept around to maintain Harvester compatibility
- N/A
=> Remove `vue-js-modal` dependency

cypress/e2e/tests/pages/extensions/extensions.spec.ts, shell/pages/c/_cluster/uiplugins/index.vue
Fixes #11696 
The issue stems from having a second `template` element wrapping the content of the tabs.
- Removed the unneeded `template` element surrounding the extension tabs. 
- Enabled a few of the e2e tests related to displaying extensions
- Navigate to the Extensions page
- Ensure all tabs show relevant content
__Before__
__After__
=> Remove unnecessary template wrapping extension tabs

shell/scripts/extension/helm/charts/ui-plugin-server/Chart.yaml
Fixes #
- bump upper limit of kube version annotation in default chart.yaml, as Rancher 2.9 use kube version `1.30`
=> bump upper limit of kube version annotation in default chart.yaml

cypress/jenkins/init.sh
Improve the `existing` type job to add clusters during initialization when the `CREATE_INITIAL_CLUSTERS` variable is enabled. Otherwise pass this variable value to the corral package script for updating the `cypress.sh` removing references to kubectl.
Updated the Jenkins initialization script
Depends on:
https://github.com/rancherlabs/corral-packages/pull/60
https://github.com/rancherlabs/jenkins-job-builder/pull/503
Jenkins CI
Nothing except the CI configuration is affected. This is innocuous to the UI code.
=> [Automation] - Refactor logic to improve existing job type

docusaurus/docs/extensions/rancher-2.10-support.md, docusaurus/docs/extensions/rancher-2.9-support.md
Minor changes to the extensions docs for 2.9 and 2.10 changes.
=> Minor changes to the extensions docs for 2.9 and 2.10 changes

.github/workflows/test.yaml, cypress/e2e/tests/pages/explorer2/workloads/deployments.spec.ts
=> fix flaky e2e tests

shell/scripts/extension/helm/charts/ui-plugin-server/Chart.yaml
Fixes #
- remove upper limit on kube version for default annotations on extensions
=> remove upper limit on kube version for default annotations on extensions

README.md
- we no longer build via drone, so removed drone status from README
=> Remove drone build status from README

jest.setup.js, shell/components/nav/NamespaceFilter.vue, shell/initialize/install-plugins.js, shell/plugins/floating-vue.js, storybook/.storybook/preview.js
Fixes #11689 
After migrating from `v-tooltip` library to `floating-vue` the default value for rendering tooltip's html content has changed to `false`. This PR fixes the issue by setting `html: true` globally.
For more info refer to the library's [migration doc](https://floating-vue.starpad.dev/migration/migration-from-v2).
https://github.com/user-attachments/assets/5f641741-c1d0-4a0c-86f5-e30dc24886cc
There are some styling discrepancies compare to Vue2 that'll be fixed by #11763
=> Fix rendering raw html content

creators/extension/package.json, shell/package.json
This will bump the shell package version to `3.0.0-rc.1` and the extension creator version to `1.0.0-rc.1`
- `./shell/package.json` version bumped
- `./creators/extension/package.json` version bumped
=> Bump Shell 3.0.0-rc.1

.github/workflows/release-shell-pkg.yaml, .github/workflows/scripts/check-package-tag-version.sh
Following the changes of https://github.com/rancher/dashboard/pull/11758 and https://github.com/rancher/dashboard/pull/11808, the `release-shell-package` workflow needs to match the same steps required to run the `test-plugins-build.sh` script.
- Added enabling corepack step
- Fixed path for extension creator within the `check-package-tag-version.sh` script
The workflow can be tested using [nektos/act](https://github.com/nektos/act):
__Shell publish test__
```bash
act -W .github/workflows/release-shell-pkg.yaml --env GITHUB_REF_NAME=shell-pkg-v3.0.0-rc.1 --env GITHUB_REF=refs/tags/shell-pkg-v3.0.0-rc.1
```
__Creators publish test__
```bash
act -W .github/workflows/release-shell-pkg.yaml --env GITHUB_REF_NAME=creators-pkg-v1.0.0-rc.1 --env GITHUB_REF=refs/tags/creators-pkg-v1.0.0-rc.1
```
=> Update publish-shell workflow with corepack

pkg/harvester-manager/list/harvesterhci.io.management.cluster.vue, shell/components/ActionMenu.vue, shell/pages/c/_cluster/istio/index.vue, shell/pages/c/_cluster/monitoring/index.vue
Fixes #11746 
I searched for the `:disabled` attribute throughout the app and didn't find any cases other than those already mentioned in the issue.
=> Fix problematic boolean attributes

.github/workflows/test.yaml, cypress/e2e/tests/pages/explorer/workloads/deployments.spec.ts
Backport of https://github.com/rancher/dashboard/pull/11775
=> [2.9] fix flaky e2e tests

pkg/aks/util/aks.ts
Fixes #11816 
Backport of https://github.com/rancher/dashboard/pull/11831
=> [2.9] Update AKS region data

pkg/gke/components/CruGKE.vue, pkg/gke/components/GKENodePool.vue, pkg/gke/l10n/en-us.yaml, pkg/gke/util/__tests__/validators.test.ts, pkg/gke/util/validators.ts
Fixes #11849 
Backport of https://github.com/rancher/dashboard/pull/11860 minus some vue3 syntax fixes.
=> [2.9]GKE - allow initial node count to be 0

cypress/jenkins/init.sh
fix the if statement for calculating the RANCHER_VERSION using RANCHER_IMAGE_TAG in init script for recurring job type
=> fix if statement in init script

cypress/e2e/tests/pages/explorer2/project-namespace.spec.ts, pkg/aks/components/AksNodePool.vue
Fixes a failing test suite, https://github.com/rancher/dashboard/actions/runs/10799817857/job/29956427762#step:3:646
=> fix failing aks unit tests

package.json, shell/core/plugin-routes.ts, shell/core/plugins-loader.js, yarn.lock
- The first one we needed a way to include the vue library for the extensions which are built as libraries and therefore do not include vue as a part of the bundle.
- The second one was related to routes. The old way where we replaced the router matcher no longer seems to function. I'm guessing that the router methods are closures which are capturing a matcher that we don't actually see. We may want to come up with a faster way to update routes. I'm not sure why our plugin add/removeRoute can't just call the methods directly on our router.
I think we can simplify the plugin router significantly but I don't really want to make big changes like that right now. I've opened a tech-debt issue to simplify later https://github.com/rancher/dashboard/issues/11876.
`ui-plugin-examples` should be …
=> Adding in some fixes for extensions in vue3

pkg/aks/components/AksNodePool.vue, pkg/aks/components/CruAks.vue, pkg/aks/components/__tests__/AksNodePool.test.ts, pkg/aks/l10n/en-us.yaml, pkg/aks/util/__tests__/validators.test.ts, pkg/aks/util/validators.ts
Backport of https://github.com/rancher/dashboard/pull/11907
Fixes https://github.com/rancher/dashboard/issues/11848#issuecomment-2345074794
=> [2.9]fix aks pool count validator and add some unit tests

pkg/rancher-components/src/components/LabeledTooltip/LabeledTooltip.vue, shell/assets/styles/global/_layout.scss, shell/assets/styles/global/_tooltip.scss, shell/components/ActionDropdown.vue, shell/components/LocaleSelector.vue, shell/components/auth/SelectPrincipal.vue, shell/components/fleet/FleetStatus.vue, shell/components/formatter/AppSummaryGraph.vue, shell/components/formatter/FleetSummaryGraph.vue, shell/components/formatter/MachineSummaryGraph.vue, shell/components/formatter/Scale.vue, shell/components/formatter/Weight.vue, shell/components/nav/NamespaceFilter.vue, shell/components/nav/TopLevelMenu.vue, shell/components/nav/WindowManager/ContainerLogs.vue, shell/detail/helm.cattle.io.projecthelmchart.vue
Fixes #11763 
Fixes #11810 
Fixes #11814
=> Fix Tooltip and Dropdown issues

shell/components/Import.vue
Fixes #11811 
This needs to be merged after https://github.com/rancher/dashboard/pull/11880
=> Fix import yaml's dropdown styling

shell/edit/auth/ldap/config.vue, shell/edit/auth/saml.vue
Just shifted variables around so we wouldn't need a circular dependency import.
https://github.com/rancher/dashboard/issues/11934
LDAP Auth provider page `/c/local/auth/config/openldap?mode=edit`
Shouldn't be any others. I didn't notice imports anywhere else for these two variables.
=> Break a circular dependency

cypress/jenkins/init.sh
Fixes #https://github.com/rancher/qa-tasks/issues/1518
depends on [ jenkins-job-builder pr](https://github.com/rancherlabs/jenkins-job-builder/pull/525) and https://github.com/rancherlabs/corral-packages/pull/63
=> add support for additional rancher helm repos

scripts/patch-docker-container
Dev PR - adds a script useful for building the dashboard and copying the assets into a running container.
This allows testing of changes locally, by running the Rancher container and then running this script with your code chanages.
=> Add a helper script to build and update the dashboard UI in a running container

.github/workflows/test.yaml, .vscode/settings.json, cypress/e2e/po/lists/fleet/fleet.cattle.io.gitrepo.po.ts, cypress/e2e/po/pages/fleet/fleet-dashboard.po.ts, cypress/e2e/po/pages/fleet/fleet.cattle.io.gitrepo.po.ts, cypress/e2e/po/pages/fleet/gitrepo-create.po.ts, cypress/e2e/po/side-bars/burger-side-menu.po.ts, cypress/e2e/tests/pages/explorer/workloads/deployments.spec.ts, cypress/e2e/tests/pages/fleet/gitrepo.spec.ts, cypress/e2e/tests/pages/generic/home.spec.ts
There were a number of issues with the e2e tests on the `release-2.8` branch, this PR includes a few manual fixes and one backport.
- [Backport] 3836bcce4aede1d053790f0a3a0fa5bba833600f
- Updated request interception to be more specific, targeting the `POST` requests to `/v1/apps.deployments`.
- Added an isolated test suite for the home page to ensure state resets and proper navigation to the release notes page.
=> Fix 2.8 e2e tests

shell/components/nav/Type.vue
Fixes #12047
- Apply correct styling to ensure icon is centrally aligned 
Before
After
=> Ensure the navlink icon is centrally aligned

.github/workflows/test.yaml, scripts/check-i18n-links, shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml
Fixes #12040 
- Adds a script which checks the doc http/s links for broken links
- Fixes 3 links that ended in /, which caused a 404 error - fix is to remove trailing slash
- Fixes 3 links by using the correct link in the docs
- Updated the test workflow to run the check script so that this is done as part of the PR workflow
=> Add script to check http links in our translation files

shell/components/form/Members/ClusterPermissionsEditor.vue, shell/components/form/ProjectMemberEditor.vue
Fixes #11638
backport of #10895
=> [2.9] fix(Project/ClusterMemberEditor): fix find roleTemplates bug

shell/components/AlertTable.vue, shell/components/GrafanaDashboard.vue
Fixes #11592
- This is a direct backport of https://github.com/rancher/dashboard/pull/11351
Setup
- install v2.8-head image. update rancher chart repo to point from release-2.8 to dev-v2.8 and refresh it
- enable prerelease versions from user preferences
- install monitoring `103.2.0-rc.1+up57.0.3`
Validation
- nav to cluster explorer --> cluster group --> scroll down
- Alerts tab should be populated with at lease one line
- Below that grafana dashboard should be visible
=> Fix two monitoring issues after chart bump

package.json, shell/package.json, shell/yarn.lock, storybook/yarn.lock, yarn.lock
This gets the transitive `fast-xml-parser` to >=4.2.4 by bumping `@aws-sdk/client-ec2` & `@aws-sdk/client-iam` to 3.658.1.
Fixes #12088 
- Bump `@aws-sdk/client-ec2` to 3.658.1
- Bump `@aws-sdk/client-iam` to 3.658.1 
`fast-xml-parser` is a transitive dependency in Dashboard. Bumping `@aws-sdk/client-ec2` & `@aws-sdk/client-iam` to the latest versions gets us to a version of `fast-xml-parser` that's acceptable for the project.
```
➤ yarn why fast-xml-parser
yarn why v1.22.19
[1/4] Why do we have the module "fast-xml-parser"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "fast-xml-parser@4.4.1"
info Reasons this module exists
- "shell#@aws-sdk#client-ec2#@aws-sdk#core" depends on it
- Hoisted from …
```
=> Bump `@aws-sdk/client-ec2` & `@aws-sdk/client-iam` to 3.658.1

shell/assets/translations/en-us.yaml, shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/edit/provisioning.cattle.io.cluster/tabs/AddOnAdditionalManifest.vue, shell/edit/provisioning.cattle.io.cluster/tabs/AddOnConfig.vue, shell/utils/cluster.js
Fixes #12068
- Manual backport of https://github.com/rancher/dashboard/pull/12056
- 2.9 contained lots of changes to rke2.vue
- mainly factors out tab functionality into individual components, so a direct cherry-pick was messy
- So this is a manually crafted backport of the feature, with testing in each part
- One bit of code was removed (refresh of yaml on click on the advanced tab)
- was accepted at the time https://github.com/rancher/dashboard/pull/9735#discussion_r1433101255
As per parent PR
As per parent PR
=> [2.8] Split add-on tab into separate tabs for each add-on

shell/scripts/extension/publish
Fixes #12078
Fixes  #11416 
This PR updates the publish script to allow existing charts to be updated.
=> Update publish script to update existing charts

shell/pkg/vue.config.js
=> Add NodePolyfillPlugin - required to build rancher pkgs

.github/workflows/build-extension-catalog.yml, .github/workflows/build-extension-charts.yml
With the addition of corepack to the extension chart publish workflow, yarn no longer needs to be setup as a separate step. When yarn is setup separately it will install yarn classic `1.22.2` which will cause a corepack error:
```console
Error: Error when performing the request to https://registry.npmjs.org/yarn/latest; for troubleshooting help, see https://github.com/nodejs/corepack#troubleshooting
at fetch (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22762:11)
at async fetchAsJson (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22776:20)
... 4 lines matching cause stack trace ...
at async Object.runMain (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:24232:5) {
[cause]: TypeError: globalThis.fetch is not a function
```
[Example action …
=> Remove unnecessary yarn setup step in extension publish workflow

cypress/e2e/po/components/namespace-filter.po.ts, cypress/e2e/po/detail/provisioning.cattle.io.cluster/cluster-detail.po.ts, cypress/e2e/po/lists/provisioning.cattle.io.cluster.po.ts, cypress/e2e/po/pages/explorer/workloads.po.ts, cypress/e2e/po/pages/explorer/workloads/workloads.po.ts, cypress/e2e/po/prompts/promptRemove.po.ts, cypress/e2e/po/side-bars/product-side-nav.po.ts, cypress/e2e/tests/pages/explorer/legacy/projects.spec.ts, cypress/e2e/tests/pages/explorer/policy/network-policy.spec.ts, cypress/e2e/tests/pages/explorer2/workloads/deployments.spec.ts, cypress/e2e/tests/pages/generic/home.spec.ts, cypress/e2e/tests/pages/manager/cluster-manager.spec.ts, cypress/e2e/tests/pages/users-and-auth/roles.spec.ts
This pr fixes various flaky tests from Jenkins test run
Fixes #
https://github.com/rancher/qa-tasks/issues/1573
https://github.com/rancher/qa-tasks/issues/1568
https://github.com/rancher/qa-tasks/issues/1563
https://github.com/rancher/qa-tasks/issues/1562
https://github.com/rancher/qa-tasks/issues/1564
https://github.com/rancher/qa-tasks/issues/1561
=> fix various flaky tests from Jenkins test run

pkg/harvester-manager/machine-config/harvester.vue, shell/assets/translations/en-us.yaml
Fixes https://github.com/rancher/dashboard/issues/10989
It adds a banner to provide guidelines about vGPUs allocation.
=> Add vGPU allocatable warning banner

.github/workflows/build-extension-catalog.yml, .github/workflows/build-extension-charts.yml
Backport of https://github.com/rancher/dashboard/pull/12132
With the addition of corepack to the extension chart publish workflow, yarn no longer needs to be setup as a separate step. When yarn is setup separately it will install yarn classic `1.22.2` which will cause a corepack error:
```console
Error: Error when performing the request to https://registry.npmjs.org/yarn/latest; for troubleshooting help, see https://github.com/nodejs/corepack#troubleshooting
at fetch (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22762:11)
at async fetchAsJson (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22776:20)
... 4 lines matching cause stack trace ...
at async Object.runMain (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:24232:5) {
[cause]: TypeError: …
```
=> [Backport 2.8] Remove unnecessary yarn setup step in extension publish workflow

shell/package.json
Fixes #
- bump version of shell pkg in order to do a new release of rc version
=> bump version of shell pkg in order to do a new release of rc version

shell/components/nav/HeaderPageActionMenu.vue
Fixes #12126
It looks like [a typo in the file of this PR](https://github.com/rancher/dashboard/pull/12076/files#diff-96875b30a5bfa7c314a6cdac8fadc75ffb2306402c633573bfdf5a4a019d1be4R80) has styled it globally, although that's not the documented way to remove it, I am not going to refactor everything with this PR since it's out of scope.
Thanks @aalves08 for pointing it out the existing work to adapt the style to current state.
Please rely on images from the issue as reference to the restored parts.
=> Vue3: Tooltip styling has changed

pkg/harvester-manager/l10n/en-us.yaml, pkg/harvester-manager/machine-config/harvester.vue, shell/assets/translations/en-us.yaml
- Select vGpus by type
- Remove vGpu profile from labels
- Add support for Harvester legacy versions - allocatable info is empty
- Replace vGpu name with a placeholder
Fixes https://github.com/rancher/dashboard/issues/12135
=> [backport 2.9] Improve vGPU allocation

pkg/harvester-manager/l10n/en-us.yaml, pkg/harvester-manager/machine-config/harvester.vue, shell/assets/translations/en-us.yaml
Fixes https://github.com/rancher/dashboard/issues/12134
=> [backport 2.8] Improve vGPU allocation

pkg/harvester-manager/machine-config/harvester.vue, shell/assets/translations/en-us.yaml
This is a backport for https://github.com/rancher/dashboard/pull/11017
Fixes https://github.com/rancher/dashboard/issues/11517
=> [backport 2.9] Add vGPU allocatable warning banner

shell/assets/translations/en-us.yaml, shell/components/formatter/CloudCredExpired.vue, shell/components/formatter/Date.vue, shell/config/labels-annotations.js, shell/list/provisioning.cattle.io.cluster.vue, shell/models/cloudcredential.js, shell/models/provisioning.cattle.io.cluster.js, shell/pages/c/_cluster/manager/cloudCredential/index.vue
Fixes #11270
- Cloud Credentials List
- If there's a cloud cred of type harvester,  show an `Expires` column
- Expires column is populated ig cloud cred has expired annotation (empty if not)
- For cloud creds with an expiration, show a 'Renew' action
- Renew action is provider specific, provide one for harvester which updates the kubeconfig within the cred
- Cluster List
- If there's a cloud cred associated with the harvester cluster (cloud cred `harvestercredentialConfig.clusterId`) check it's expired date, warn if within 7 days of expiring or has expired
- If there's a cloud cred with expiration, show the `Renew Cloud Credential` action
- Action does same as cloud cred renew
- Banners
- In both lists show a banner warning of soon to expire or expired creds
- End to end
-  Renew Cloud …
=> [2.9] Show Cloud Credential Expiration information for Harvester Creds, add actions to renew

shell/assets/translations/en-us.yaml, shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/utils/cluster.js, shell/utils/v-sphere.ts
Fixes #11920
- Create a secret to sync to downstream vsphere cluster
- Reference secret in chart values
In Addition
- Update `Add-on:` tab titles
- Contact @richard-cox 
- Contact @richard-cox
=> [2.9] vSphere Secrets Sync

shell/cloud-credential/aws.vue, shell/cloud-credential/azure.vue, shell/cloud-credential/digitalocean.vue, shell/cloud-credential/gcp.vue, shell/cloud-credential/linode.vue, shell/cloud-credential/pnap.vue, shell/cloud-credential/s3.vue, shell/cloud-credential/vmwarevsphere.vue, shell/edit/cloudcredential.vue, shell/edit/provisioning.cattle.io.cluster/SelectCredential.vue
Fixes #12054 
Fixed cloud config wizard validation.
Changed how we identify that validation status has changed.
Changed name validation to respond to typing instead of focus out.
Changed components to use validation mixin instead of emitting validation changed event on every user input.
Cluster manager -> cloud credentials -> create new credential
Cluster manager -> cloud credentials -> edit existing credential
Cluster manager -> create new cluster -> create new credential
For all of these scenarios, validation should 
- respond appropriately to changes in required fields
- react to name change as user types
No other areas should be affected
=> Fixed cloud credential validation

cypress/e2e/tests/pages/global-settings/feature-flags.spec.ts
backport of https://github.com/rancher/dashboard/pull/12199
=> [2.9]update feature flag table test to dynamically check feature flag count

shell/assets/translations/en-us.yaml, shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/edit/provisioning.cattle.io.cluster/tabs/AddOnConfig.vue, shell/utils/cluster.js, shell/utils/v-sphere.ts
Fixes #11892
- Create a secret to sync to downstream vsphere cluster
- Reference secret in chart values
In Addition
- Update `Add-on:` tab titles
- Contact @richard-cox 
- Contact @richard-cox
=> [2.10] vSphere Secrets Sync

cypress/e2e/tests/pages/manager/cloud-credential.spec.ts
Improve cloud cred e2e tests
- The tests recently took 4 retries to pass
- Improvements
- don't nuke all cloud creds before tests starts, instead tidy up cloud creds created during tests at end
- some developers run this against long standing rancher instance with lots of creds in
- it's also best practise to leave the env in the same state as when the tests started
- use safer method of creating cloud creds and running dependent tests
- instead of looping over blocks that create creds and then last one run tests.... chain create them creds then run test at end
- most important one, make creds THEN navigate to the page to ensure all creds are correctly in store
- there's no socket updates for these, so we have to be sure they can be returned before we load the dashboard
Forward port …
=> [2.9] Improve cloud cred e2e tests

shell/package.json, shell/scripts/typegen.sh
Fixes: #12223 
When running the publish-shell workflow the typegen script would not include the necessary typescript definitions for the `@rancher/shell` library.
The issue was caused by incorrectly referencing the shell directory within the runner. When the script is ran locally there is no issue as the `shell` directory is accessible. However, within a workflow runner the `shell` directory was in a different location.
- Replaced the `BASE_DIR` value to use `git rev-parse --show-toplevel` to ensure the correct repository level regardless of the runner's current working directory.
- Replaced the `shell/*` directory matching when running the `tsc` command to `SHELL_DIR` which is accessible to the worker.
- Added a log of the contents within the `${SHELL_DIR}/tmp` directory.
- Publishing a …
=> Fix typegen script shell directory paths

shell/config/labels-annotations.js, shell/models/cloudcredential.js
Contributes to #11270
- this magically worked before because const y = ['a']; this.x[y] --> this.['a']
- if anything else was added to the array it would fail
- included in 2.10 via https://github.com/rancher/dashboard/pull/12157
=> Fix Cloud Credential Annotation collection

shell/utils/v-sphere.ts
contributes to #11920 
Changing CPI/CSI secret names as backend needs it.
=> [2.9] Change CPI/CSI secret names

shell/utils/v-sphere.ts
contributes to #12065 
Changing CPI/CSI secret names as backend needs it.
=> [2.8] Backport cpi and csi secret name updates

shell/utils/v-sphere.ts
contributes to #11892 
Changing CPI/CSI secret names as backend needs it.
=> [2.10] Update CPI and CSI secret names

shell/components/auth/RoleDetailEdit.vue, shell/components/auth/__tests__/RoleDetailEdit.test.ts, shell/models/management.cattle.io.globalrole.js, shell/models/management.cattle.io.roletemplate.js, shell/plugins/dashboard-store/resource-class.js
Fixes #12052
Added test to the existing suite, to ensure value is kept as it is.
https://github.com/user-attachments/assets/324055fc-104f-4666-9b61-11505dd02a1d
=> Clone of global admin role not a 100% carbon copy

shell/components/CodeMirror.vue
Fixes #12290 
This just reverts the css index to 1 in order to fix the overlay issue with the keyboard icon.
=> Fix keyboard icon overlay

cypress/e2e/po/edit/provisioning.cattle.io.cluster/create/cluster-create.po.ts, cypress/e2e/tests/pages/global-settings/peformance.spec.ts, cypress/e2e/tests/pages/manager/cluster-manager.spec.ts, cypress/e2e/tests/pages/manager/mock-responses.ts, docusaurus/docs/extensions/api/components/node-drivers.md, shell/components/Questions/index.vue, shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/models/nodedriver.js, shell/store/type-map.js
Fixes #11974
Fixes #11936
- This is a direct port of https://github.com/rancher/dashboard/pull/11984. See description for more details
- Validated using nutanix, and test extensions ec2 and outscale
=> Fix two node driver based issues

creators/extension/init, creators/extension/migrate/config.js, creators/extension/migrate/ignore.js, creators/extension/migrate/init, creators/extension/migrate/package.json, creators/extension/migrate/params.js, creators/extension/migrate/stats.js, creators/extension/migrate/tasks/eslintUpdates.js, creators/extension/migrate/tasks/index.js, creators/extension/migrate/tasks/nvmUpdates.js, creators/extension/migrate/tasks/packageUpdates.js, creators/extension/migrate/tasks/routerUpdates.js, creators/extension/migrate/tasks/stylesUpdates.js, creators/extension/migrate/tasks/tsUpdates.js, creators/extension/migrate/tasks/vueConfigUpdates.js, creators/extension/migrate/tasks/vueSyntaxUpdates.js, creators/extension/migrate/utils/content.js, creators/extension/migrate/utils/index.js, creators/extension/migrate/utils/vueSyntax.js, creators/extension/package.json
Fixes #12276 
The script found in `./shell/scripts/vue-migrate.js` was originally intended for migrating the Dashboard to Vue 3 compliance. In order to leverage this script with extensions, it makes the most sense to modularize it and add it as a creator within the npm library for `@rancher/create-extension`.
This will allow extension developers to run the migrate command within their extensions to have most of the heavy lifting applied for them, with some options to limit the scope of the migration and provide suggested changes before applying any modifications.
- Added an option for migration to the `@rancher/extension` creator
- Allows for `--suggestion` option to create a diff file containing the suggested changes without modifying the extension
- Updates the annotations necessary for …
=> Add Vue3 migration helper to extension creator

shell/edit/provisioning.cattle.io.cluster/__tests__/rke2.test.ts, shell/edit/provisioning.cattle.io.cluster/rke2.vue
Fixes https://github.com/harvester/harvester/issues/6821
=> Fix rke2 payload

creators/extension/package.json
Bumps the extension creator to `1.0.0`
=> Bump extension creator

.github/workflows/build-and-upload-branch.yaml
Trigger branch based builds for hotfixes
- branch pattern matches core rancher hotfixes
=> Trigger branch based builds for hotfixes

shell/pages/auth/setup.vue
Fixes: #12145
- See screenshots
- scroll bar flush with graphic
- give more room for form
- Held off doing this as there was a PR that totally changed the whole setup / login page flow, however i think that's now DOA
- So this is a quick fix for a long time annoyance
- The file is a mess of styles, will need tidying up one day
- setup pages
- loign pages (just in case)
Before
After
=> Ensure the vertical scroll bar on setup page is flush with graphic

.github/workflows/build-and-upload-release.yaml
…
Much like https://github.com/rancher/dashboard/pull/12316, trigger a hotfix build specifically for embedded in rancher use case
=> Trigger release based builds for hotfixes

shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml
Fixes #12334 
Just a simple URL change.
n/a
Watch the attached video
n/a
https://github.com/user-attachments/assets/2fdd1f19-56de-49a4-b83c-56d36e4d51d5
=> Update EULA url

shell/detail/catalog.cattle.io.app.vue, shell/mixins/chart.js, shell/models/catalog.cattle.io.app.js, shell/pages/c/_cluster/apps/charts/install.vue
Fixes #12168
Cherry-picks of https://github.com/rancher/dashboard/pull/12317
=> [2.8] Update Helm App Values Approach

shell/detail/catalog.cattle.io.app.vue, shell/mixins/chart.js, shell/models/catalog.cattle.io.app.js, shell/pages/c/_cluster/apps/charts/install.vue
Fixes #12167
Cherry-picks of https://github.com/rancher/dashboard/pull/12317
=> [2.9] Update Helm App Values Approach

shell/detail/catalog.cattle.io.app.vue, shell/mixins/chart.js, shell/models/catalog.cattle.io.app.js, shell/pages/c/_cluster/apps/charts/install.vue
=> [2.10] Update Helm App Values Approach

shell/components/fleet/FleetClusters.vue, shell/detail/fleet.cattle.io.cluster.vue, shell/detail/fleet.cattle.io.gitrepo.vue, shell/models/fleet.cattle.io.gitrepo.js, shell/pages/c/_cluster/fleet/index.vue, shell/utils/string.js
Fixes #12378
- Cherry pick of https://github.com/rancher/dashboard/pull/12375
=> [2.9] Fleet Improvements

shell/assets/translations/en-us.yaml, shell/edit/fleet.cattle.io.gitrepo.vue, shell/models/fleet.cattle.io.gitrepo.js, shell/utils/validators/formRules/__tests__/index.test.ts, shell/utils/validators/formRules/index.ts
Fixes #12204 
Updated validation for GitRepo form.
- Updated when name validation is triggered
- Added validation to repo url and made this field required
- Added a check to see if repo exists when displaying the list of repositories
- Gitrepo form should become valid when required values are provided 
- Repository field should handle both HTTPS and SSH urls
N/A
=> [FIX] Fixed validation on Gitrepo page

shell/assets/translations/en-us.yaml, shell/edit/provisioning.cattle.io.cluster/__tests__/DirectoryConfig.test.ts, shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/edit/provisioning.cattle.io.cluster/tabs/Advanced.vue, shell/edit/provisioning.cattle.io.cluster/tabs/DirectoryConfig.vue
Fixes #11560 
- update data directories inputs to match new user interface solution, as per https://github.com/rancher/dashboard/issues/11560#issuecomment-2438039194
- update unit tests
- create a rke2 cluster, keep kubernetes version to `rke2`
- edit cluster above
- create a rke2 cluster, changes kubernetes version to any `k3s`
- edit cluster above (check that distro path is k3s)
**CREATE scenario**
**EDIT scenario**
=> Update Data Directory Configuration interface

shell/models/management.cattle.io.project.js
Fixes #12403
- at some point we must have changed from project returning norman object with namespace property to mgmt object without ... or mgmt object extends was changed
- lo-bar fix is to add description getter, better but more risky fix is to update mgmt project to extend steve instead of hybrid base class
- used in https://github.com/rancher/dashboard/blob/885f0a8cde8bee1d10db17d755a891f1581a656b/shell/components/ExplorerProjectsNamespaces.vue#L341-L344
Projects/Namespaces list, grouped by project, projects with and without namespace
=> Fix for missing project/namespace description in project/namespace list

cypress/e2e/tests/pages/extensions/extensions.spec.ts, shell/pages/c/_cluster/uiplugins/index.vue
Fixes #12376 
- fix issue banner extensions prime users not being displayed due to setting value being defined as an empty string by backend 
- add e2e test
- Check issue description for repro steps
=> fix issue banner extensions prime users not being displayed

shell/assets/translations/en-us.yaml, shell/models/provisioning.cattle.io.cluster.js, shell/pages/c/_cluster/explorer/__tests__/index.test.ts, shell/pages/c/_cluster/explorer/index.vue
Fixes https://github.com/rancher/dashboard/issues/12330
Backport of https://github.com/rancher/dashboard/pull/12252
=> [Backport 2.9.4] - Lowercase architecture labels

shell/package.json
Bumps the `rancher/shell` version to `2.0.2`
=> Bump shell 2.0.2

shell/package.json
=> Bump @rancher/shell 3.0.0

cypress/e2e/po/detail/management.cattle.io.roletemplate.po.ts, shell/components/ResourceDetail/Masthead.vue
Addressing https://github.com/rancher/dashboard/pull/12419#pullrequestreview-2408518863
=> Fixing a typo found in a backport

cypress/e2e/tests/pages/global-settings/branding.spec.ts
=> Enabling the branding e2e tests and fixing what's broken

cypress/e2e/po/pages/explorer/uiplugins.po.ts, cypress/e2e/po/pages/extensions.po.ts, cypress/e2e/tests/pages/extensions/extensions.spec.ts
Fixes #12499 
- re-enable e2e tests for extensions that were being skipped due to vue3 migration in `pages/extensions/extensions.spec.ts` and improve e2e test on `large-extension`
=> Re-enable e2e tests for `pages/extensions/extensions.spec.ts`

shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/store/features.js, shell/utils/v-sphere.ts
Fixes #12530 
Checking `provisioningprebootstrap` flag before running the logic for handling vSphere secret creation.
=> Take `prebootstrap` flag into account before creating vSphere secrets

shell/assets/translations/en-us.yaml, shell/components/formatter/ClusterProvider.vue, shell/models/__tests__/management.cattle.io.cluster.test.ts, shell/models/__tests__/provisioning.cattle.io.cluster.test.ts, shell/models/management.cattle.io.cluster.js, shell/models/provisioning.cattle.io.cluster.js
Fixes #12572
Fixes #12465
Backport of https://github.com/rancher/dashboard/pull/12583
=> [2.10]Fix editing local rke1 and eks clusters

shell/assets/translations/en-us.yaml, shell/components/formatter/ClusterProvider.vue, shell/models/__tests__/management.cattle.io.cluster.test.ts, shell/models/__tests__/provisioning.cattle.io.cluster.test.ts, shell/models/management.cattle.io.cluster.js, shell/models/provisioning.cattle.io.cluster.js
#12613 was merged by mistake
That PR is slotted for `v2.9.5` and needs to be held off from merging until `v2.9.4` is released.
=> Revert #12613

shell/vue.config.js
Fxes: #12515
Port of https://github.com/rancher/dashboard/pull/12400
=> [2.9 backport] Avoid embedding web-worker polyfill 

cypress/e2e/tests/pages/fleet/advanced/bundles.spec.ts, cypress/e2e/tests/pages/generic/about.spec.ts, shell/components/ResourceDetail/index.vue, shell/components/fleet/FleetRepos.vue, shell/config/labels-annotations.js, shell/detail/fleet.cattle.io.bundle.vue, shell/detail/fleet.cattle.io.gitrepo.vue, shell/models/fleet.cattle.io.bundle.js, shell/models/fleet.cattle.io.gitrepo.js, shell/pages/c/_cluster/fleet/index.vue, shell/types/resources/fleet.d.ts, shell/utils/auth.js, shell/utils/fleet.ts
Fixes #12516
Fixes #12578
Forward-port of #12443
=> [2.10] Use BundleDeployment status to calculate GitRepo resources

creators/extension/app/files/.github/workflows/build-extension-charts.yml, creators/extension/package.json, creators/extension/pkg/init, creators/extension/pkg/package.json
Fixes #12635 
- fix `build-extension-charts` workflow
- harcode meaningful extension annotations according to version used
- remove `fetchLatestVersion` function
https://www.npmjs.com/package/@rancher/create-extension?activeTab=versions
=> Fix some issues with extensions creator's package in release 2.8

creators/extension/app/files/.github/workflows/build-extension-charts.yml, creators/extension/package.json, creators/extension/pkg/init, creators/extension/pkg/package.json
Fixes #12635 
- fix `build-extension-charts` workflow
- harcode meaningful extension annotations according to version used
- remove `fetchLatestVersion` function
https://www.npmjs.com/package/@rancher/create-extension?activeTab=versions
=> Fix some issues with extensions creator's package in release 2.9

creators/extension/app/app.package.json, creators/extension/app/files/.github/workflows/build-extension-charts.yml, creators/extension/package.json, creators/extension/pkg/init, creators/extension/pkg/package.json
Fixes #12635 
- fix `build-extension-charts` workflow
- update `dependencies` and `resolutions` for a Rancher 2.10 system boilerplate app/extension
- harcode meaningful extension annotations according to version used
- remove `fetchLatestVersion` function
https://www.npmjs.com/package/@rancher/create-extension?activeTab=versions
=> Fix some issues with extensions creator's package in master

.github/workflows/build-extension-catalog.yml, .github/workflows/build-extension-charts.yml, .github/workflows/release-shell-pkg.yaml, shell/scripts/extension/parse-tag-name, shell/scripts/publish-shell.sh
Fixes #12159 
Fixes #12032 
Based on the work done in https://github.com/aalves08/dashboard/pull/4
- Adjust extension workflows in branch `release 2.9` for nightly run tests for extensions
=> Adjust extension workflows in branch 'release 2.9' for nightly run tests for extensions

creators/extension/app/files/gitignore
Fixes #12645 
- add dist-pkg to gitignore
=> add dist-pkg to gitignore

.github/workflows/scripts/retrieve-versions.sh, shell/scripts/extension/parse-tag-name, shell/scripts/typegen.sh
Fixes #12675 
Fixes #12627
Fixes #12652
- add missing script `retrieve-versions`
- Update `parse-tag-name` to allow for release of both `charts` and `catalog` with the same tag - #12627  
- Update typegen - #12652
=> add missing script - 2.9

.github/workflows/scripts/retrieve-versions.sh, shell/scripts/extension/parse-tag-name, shell/scripts/typegen.sh
Fixes #12675
Fixes #12627
Fixes #12652 
- add missing script `retrieve-versions`
- Update `parse-tag-name` to allow for release of both `charts` and `catalog` with the same tag - #12627 
- Update typegen - #12652
=> add missing script - 2.8

creators/extension/package.json
Fixes #
- bump creators version
=> bump creators version

creators/extension/package.json, creators/extension/pkg/package.json
Fixes #
-  update default for `ui-extensions-version` to `"catalog.cattle.io/ui-extensions-version": ">= 3.0.0 < 4.0.0"` so that we won't hit problems in the future with extensions on rancher systems non-compliant with extensions version (with breaking changes)
- bump `creators` package version
=> update default for ui-extensions-version

.github/workflows/test-extension-workflows-master.yml, .github/workflows/test-extension-workflows-release-2.8.yml, .github/workflows/test-extension-workflows-release-2.9.yml
Fixes #
- fix workflow slack msg for https://github.com/rancher/dashboard/actions/runs/12041142481/job/33572872014
=> fix workflow slack msg

.github/workflows/scripts/retrieve-versions.sh
Fixes #
- Fix for  workflow test extensions release-2.9, as per: https://github.com/rancher/dashboard/actions/runs/12041416368/job/33573247605
=> Fix workflow test extensions release-2.9

.github/workflows/scripts/retrieve-versions.sh
Fixes #
- Fix for  workflow test extensions release-2.8, as per: https://github.com/rancher/dashboard/actions/runs/12041424401/job/33573271261
=> Fix workflow test extensions release-2.8

shell/package.json
PR https://github.com/rancher/dashboard/pull/12659 is merged, bump rancher/shell to `3.0.1-rc.2`
Fixes #
https://github.com/rancher/dashboard/issues/12347
=> bump rancher/shell 3.0.1-rc.2

.github/workflows/test-extension-workflows-release-2.8.yml, .github/workflows/test-extension-workflows-release-2.9.yml, creators/extension/migrate/tasks/packageUpdates.js, docusaurus/docs/extensions/extensions-getting-started.md, docusaurus/docs/extensions/rancher-2.10-support.md
Fixes #
- small fix extensions workflow tests by using the correct repo to test with, since the script to get the versions is already using `elemental-ui` repo
- update docs for extensions (recommended node version + update annotation recommendation in 2.10 migration docs)
=> Small fixes for docs and extensions workflow tests

shell/assets/translations/zh-hans.yaml, shell/components/GlobalRoleBindings.vue, shell/components/auth/RoleDetailEdit.vue, shell/pages/c/_cluster/auth/roles/index.vue
Fixes #12706
- remove all mentions for the `restricted admin` role
Some areas where banners/text could be found:
=> remove all mentions for the restricted admin role

shell/components/SortableTable/THead.vue
Fix table header align not work. 
Note. will need `shell-pkg-v3.0.1-rc.3` release after this fix merged. 
https://github.com/harvester/harvester/issues/7058
`.table-header-container` display css was changed in https://github.com/rancher/dashboard/commit/be3ce0c7eef6808e8b4bbad388e94563eecb8e64.
After fix
=> Fix table header align not work

.github/workflows/scripts/publish-storybook
Fixes #12715
For some reason, the script no longer has access to the `./storybook` path, so it has been added when needed to be specified like copying the folder to publish.
Passing build/copy part so no need test, https://github.com/cnotv/dashboard/actions/runs/12117704029/job/33780682534
=> Fix Storybook publishing

shell/edit/provisioning.cattle.io.cluster/index.vue
Fixes #12599
Backport of https://github.com/rancher/dashboard/pull/12587
=> [2.9.5]fix ember routing for non built-in container drivers

shell/package.json
https://github.com/rancher/dashboard/pull/12713 is merged, bump rancher/shell to v3.0.1-rc.3
Fixes 
https://github.com/harvester/harvester/issues/7058
=> bump rancher/shell to v3.0.1-rc.3

creators/extension/migrate/init, creators/extension/migrate/tasks/packageUpdates.js, creators/extension/migrate/utils/content.js, creators/extension/package.json
Fixes #12656
- fix issue with migration script not updating resolutions properly
- update libraries used
- add completion log to inform user to install dependencies
=> Tackle issues with migration script

cypress/e2e/tests/navigation/side-nav/main-side-menu.spec.ts, cypress/e2e/tests/pages/explorer2/workloads/jobs.spec.ts, cypress/e2e/tests/pages/global-settings/feature-flags.spec.ts, cypress/e2e/tests/pages/global-settings/index.spec.ts, cypress/e2e/tests/pages/manager/edit-fake-cluster.spec.ts, cypress/e2e/tests/pages/manager/jwt-authentication.spec.ts, cypress/e2e/tests/pages/users-and-auth/index.spec.ts, cypress/jenkins/init.sh
Fixes #
https://github.com/rancher/qa-tasks/issues/1556
https://github.com/rancher/qa-tasks/issues/1565
https://github.com/rancher/qa-tasks/issues/1566
https://github.com/rancher/qa-tasks/issues/1567
https://github.com/rancher/qa-tasks/issues/1569
- I've added fixes to various tests that are flaky in Jenkins (see above tickets).
- Our Jenkins runs fail when `RANCHER_VERSION=2.10.0`, so I've updated the init.sh script to prevent that.
=> update e2e tests

docusaurus/docs/internal/getting-started/concepts.md
This is the only typo that jumped out.
=> Remove a stutter in the sentence.

shell/models/__tests__/management.cattle.io.cluster.test.ts, shell/models/management.cattle.io.cluster.js, shell/models/provisioning.cattle.io.cluster.js
Backport of https://github.com/rancher/dashboard/pull/12694
Fixes #12663
=> [2.10.1] Fix editing rke2/k3s clusters in 'pending' state

shell/assets/translations/en-us.yaml, shell/components/formatter/ClusterProvider.vue, shell/models/__tests__/management.cattle.io.cluster.test.ts, shell/models/__tests__/provisioning.cattle.io.cluster.test.ts, shell/models/management.cattle.io.cluster.js, shell/models/provisioning.cattle.io.cluster.js
Backport of https://github.com/rancher/dashboard/pull/12694 and https://github.com/rancher/dashboard/pull/12583 
Fixes #12664
Fixes #12609
Fixes #12610
=> [2.9.5] Fix editing rke2/k3s clusters in 'pending' state

creators/extension/app/app.package.json, creators/extension/app/init, creators/extension/package.json, creators/extension/pkg/init, creators/extension/pkg/package.json
The pkg and app creators were out of sync with what was in the master branch, this would cause a failure when attempting to create and build an extension for Rancher 2.9.
- Aligned pkg/init and app/init with the versions in master
- Removed the unnecessary dependencies and resolutions in the `app.package.json` 
- Added resolutions for `@types/node` and `@types/lodash` in the `app.package.json`
- Fixed node version in pkg.package.json to `16`
=> [2.9.5] Align pkg and app creators with master

creators/extension/app/app.package.json, creators/extension/app/init, creators/extension/package.json, creators/extension/pkg/init, creators/extension/pkg/package.json
The pkg and app creators were out of sync with what was in the master branch, this would cause a failure when attempting to create and build an extension for Rancher 2.8.
- Aligned pkg/init and app/init with the versions in master
- Removed the unnecessary dependencies and resolutions in the app.package.json
- Added resolutions for @types/node and @types/lodash in the app.package.json
- Fixed node version in pkg.package.json to `v16`
=> [2.8.11] Align pkg and app creators with master

creators/extension/package.json, creators/extension/update/init, creators/extension/update/upgrade
The Update creator was not aligned with the master branch and was missing a conditional to check for a dependencies object prior to iterating over them.
This will add the condition.
=> [2.8.11] Add condition for latestPackage.dependencies

creators/extension/package.json, creators/extension/update/upgrade
Fixes #
- change script to bash 
- bump version
=> change script to bash + bump version

.github/workflows/build-extension-charts.yml
=> wf with information dump

cypress/e2e/po/pages/explorer/workloads-pods.po.ts, cypress/e2e/tests/pages/explorer2/workloads/pods.spec.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1621
=> yaml footer e2e test

pkg/harvester-manager/l10n/en-us.yaml, pkg/harvester-manager/list/harvesterhci.io.management.cluster.vue, pkg/harvester-manager/types.js, shell/utils/uiplugins.ts
Blcoked by https://github.com/rancher/dashboard/pull/12770
Fixes https://github.com/rancher/dashboard/issues/12688
=> [backport 2.10] Virtualization Management, automate Harvester extension installation

cypress/e2e/tests/pages/fleet/fleet-clusters.spec.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1574
- Updated git repo url/paths used in tests to resolve Jenkins failures
- General refactor of fleet-clusters tests
=> fix fleet tests

cypress/e2e/po/other-products/logging/logging-clusterflow-po.ts, cypress/e2e/po/other-products/logging/logging-clusteroutput.po.ts, cypress/e2e/po/pages/explorer/charts/chart.po.ts, cypress/e2e/tests/pages/charts/logging.spec.ts
Fixes 
https://github.com/rancher/dashboard/issues/11933
https://github.com/rancher/qa-tasks/issues/1593
Adding a P0 scenario for the Logging chart in Rancher using the UI
Automation pipelines
Jenkins CI
=> [Automation] - Adding logging chart test

.github/workflows/test.yaml, cypress/e2e/tests/pages/generic/home.spec.ts
Fixes #https://github.com/rancher/dashboard/issues/11836
- Unpinned Chrome version
- Moved `Can navigate to release notes page for latest Rancher version` to run last; The test clicks on a link that opens a new tab which is causing issues with subsequent tests (once we are able to upgrade our Cypress version, test order will not matter).
=> unpin chrome version

.github/workflows/test.yaml, cypress/e2e/tests/pages/generic/home.spec.ts
Fixes #https://github.com/rancher/dashboard/issues/11836
- Unpinned Chrome version
- Moved Can navigate to release notes page for latest Rancher version to run last; The test clicks on a link that opens a new tab which is causing issues with subsequent tests (once we are able to upgrade our Cypress version, test order will not matter).
=> [backport v2.10.1] unpin chrome version

shell/package.json, shell/scripts/extension/parse-tag-name
Fixes #[12718](https://github.com/rancher/dashboard/issues/12718)
- fix `parse-tag-name` to prevent workflow from running when a tag check is not met (`gh run cancel` is not enough)
- bump `shell` version
=> fix parse-tag-name to prevent workflow from running when a tag check is not met

shell/scripts/test-plugins-build.sh
Fixes #[12598](https://github.com/rancher/dashboard/issues/12598)
- add harvester extension to our extensions to check with the `test-plugins-build` script
=> add harvester extension to our extensions to check with the test-plugins-build script

cypress/e2e/blueprints/explorer/workloads/deployments/deployment-create.ts, cypress/e2e/po/pages/explorer/workloads/workloads.po.ts, cypress/e2e/tests/pages/explorer2/workloads/deployments.spec.ts
Fixes
https://github.com/rancher/qa-tasks/issues/1587
https://github.com/rancher/qa-tasks/issues/1630
Expanded the pod scaling test to actually scale and downscale pods.
Re-structure the deployments spec file to ensure the tests can be executed independently.
Github Actions
Jenkins Pipelines
=> [Automation] - Adding pod scaling test and simplify deployment spec structure

cypress/e2e/po/components/assign-to-dialog.po.ts, cypress/e2e/po/pages/fleet/fleet.cattle.io.cluster.po.ts, cypress/e2e/tests/pages/fleet/fleet-clusters.spec.ts, shell/components/AssignTo.vue
Fixes #https://github.com/rancher/qa-tasks/issues/737
added e2e test to cover https://github.com/rancher/dashboard/issues/11434
=> automation: assign cluster to fleet workspace

pkg/eks/components/CruEKS.vue, pkg/eks/components/__mocks__/describeKeyPairs.js, pkg/eks/components/__tests__/CruEKS.test.ts
Fixes #12878
Backport of https://github.com/rancher/dashboard/pull/12879
=> fix eks sshkey dropdown and add unit test

.github/workflows/test-extension-workflows-master.yml, .github/workflows/test-extension-workflows-release-2.8.yml, .github/workflows/test-extension-workflows-release-2.9.yml
Fixes #
Fixes https://github.com/rancher/dashboard/actions/runs/12306968380/job/34350302524, https://github.com/rancher/dashboard/actions/runs/12307261565, https://github.com/rancher/dashboard/actions/runs/12307269246
=> fix slack msg failing on extensions workflows tests

shell/assets/translations/en-us.yaml, shell/pages/c/_cluster/explorer/__tests__/index.test.ts, shell/pages/c/_cluster/explorer/index.vue
Fixes #10723
- Adding a tooltip in case of warning/error status
- Clickable action to the fleet/cattle deployments in case of warning/error status
[Screencast from 2024-12-16 16-03-07.webm](https://github.com/user-attachments/assets/15edfb99-94eb-4b64-9bfb-c615951414e5)
=> Enhancements to fleet/cattle status on cluster dashboard page

.github/workflows/test-extension-workflows-master.yml, .github/workflows/test-extension-workflows-release-2.8.yml, .github/workflows/test-extension-workflows-release-2.9.yml
Fixes #
- Fix issue with output not being passed correctly for upgrade test in `master` workflow
- Fix problem with regex where it's was incorrect for the case of an empty string in the title https://github.com/rancher/dashboard/actions/runs/12363915065/job/34506301018
=> fix slack msg (again)

shell/core/types.ts, shell/package.json
Fixes #12899 (low bar fix)
- add `ifHave` property to types + bump shell
=> Add type for mechanism to allow to register custom pages conditionally (based on resource type)

storybook/package.json
Fixes storybook gate
- Pin esbuild version
- Issue with details and to unpin https://github.com/rancher/dashboard/issues/12924
=> Pin storybook esbuild version to avoid TS error

shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml
Fixes #12933
- https://docs.rke2.io/install/containerd_registry_configuration --> https://docs.rke2.io/install/private_registry
- See https://github.com/rancher/rke2-docs/pull/296/files
- file / link was renamed to private_registry
- Create / Edit rke2 cluster --> registries --> advanced (see screenshot) --> docs link
- see check-i18n-links job
=> Fix moved rke2 doc link

shell/components/form/Taints.vue
Fixes #12749 
Another victim of Vue 3 migration
Updated how we update the value for node taints
I feel like writing a test case for this is not a worthy time investment.
1. Cluster Explorer --> Nodes --> Edit Config of a node --> Add Taint
2. Add name and value
3. Click save
4. Check that PUT request contains spec.taints object with correct values
5. Go to Edit config of the same node. Check that it contains previously added taint.
None
https://github.com/user-attachments/assets/e0db28fe-6e7d-4786-bda8-47ef053039fe
=> Fixed not being able to update node taints

.github/workflows/test.yaml
Fixes #12856
- https://github.com/rancher/rancher/pull/48530 has merged (contains a fix for vai indexed fields) and `head` has been updated (https://hub.docker.com/layers/rancher/rancher/head/images/sha256-d5cff407da4e2aa7d1d92be70431a92b807310ad006ea2e132dfdfc3ed9f0c16)
- Reverts https://github.com/rancher/dashboard/pull/12857
=> Re-enable vai e2e tests

shell/assets/styles/base/_basic.scss, shell/assets/styles/base/_mixins.scss, shell/assets/styles/global/_button.scss, shell/assets/styles/themes/_dark.scss, shell/assets/translations/en-us.yaml, shell/components/BackLink.vue, shell/pages/about.vue
Fixes #12786 
- Fix keyboard nav for `about` page
- Go to the about page, click on the page and browse the UI elements with the tab key
- use enter or space key to trigger UI elements on the page
https://github.com/user-attachments/assets/41321ad6-2b98-4d83-922b-d27d0672b48f
=> fix keyboard nav for about page

shell/chart/monitoring/StorageClassSelector.vue
Fixes : #12971
As part of Vue 3 migration, we needed to remove @input from compponents that use LabeledSelect
Fixed event listener in StorageClassSelector.
I've checked and other LabeledSelects should be fine (there is a PR for Node Scheduling already). We also have components that are listening for 'search' event, which is not declared on LabeledSelect, but it seems to work and I think will require more investigation.
1. Create a new StorageClass
2. Apps -> Charts -> Monitoring -> Install/Update -> Prometheus -> Persistent Storage for Prometheus -> Storage Class name -> You should be able to select a storage class
3. Apps -> Charts -> Monitoring -> Install/Update -> Grafana -> "Enable with PVC Template" Grafana storage -> Storage Class name -> You should be able to select a storage class …
=> [FIX] Storage class selector not working

.github/workflows/scripts/pr-check-checklist.sh, .github/workflows/valid-pr-description.yaml
Add PR gate to ensure checklist has been created
- There's been PRs that have merged without the required checklist being completed (for instance missing milestones, no reviewers, missing template, dark mode not tested, etc)
- This PR will ensure all PRs have every checkbox in the pr description checked
- This does not ensure all required checklists entries are checked, we can update in future if that gap is being abused
- Gate will check on pr creation and description edit
=> Add PR gate to ensure checklist has been completed

README.md
=> Bump README copyright

shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml
Fixes #12986 
Fixed broken link.
Create / Edit rke2 cluster --> registries --> advanced (see screenshot) --> docs link
https://github.com/user-attachments/assets/3c2053b4-a86f-44bc-8b98-0be1a70cead4
=> [2.10] Fix moved rke2 doc link

creators/extension/app/app.package.json, creators/extension/app/files/.github/workflows/build-extension-catalog.yml, creators/extension/package.json
Fixes #12993 
Fixes #12988 
- fix workflow for `catalog` build on `creators` package by adding missing `tagged_release` input
- fix dependencies resolutions because of node package updates upstream that are incompatible with node 16
=> [release-2.9] fix wf catalog build on creators + creators version bump

creators/extension/app/app.package.json, creators/extension/app/files/.github/workflows/build-extension-catalog.yml, creators/extension/package.json
Fixes #12993 
Fixes #12995 
- fix workflow for `catalog` build on `creators` package by adding missing `tagged_release` input
- fix dependencies resolutions because of node package updates upstream that are incompatible with node 16
=> [release-2.8] fix wf catalog build on creators + creators version bump

shell/components/form/Taints.vue
Fixes #13013 
Backport of updating how we update the value for node taints.
1. Cluster Explorer --> Nodes --> Edit Config of a node --> Add Taint
2. Add name and value
3. Click save
4. Check that PUT request contains spec.taints object with correct values
5. Go to Edit config of the same node. Check that it contains previously added taint.
=> [2.10] Fixed not being able to update node taints

package.json, pkg/harvester-manager/machine-config/harvester.vue, shell/edit/provisioning.cattle.io.cluster/tabs/registries/RegistryConfigs.vue, shell/edit/provisioning.cattle.io.cluster/tabs/registries/__tests__/RegistryConfigs.test.ts, shell/utils/string.js, yarn.lock
- Support caBundle plain text
- Remove is-base64 dependency
Fixes #12684
=> [2.10.2] Support caBundle plain text

.github/workflows/test.yaml
Fixes #12858
Reverts rancher/dashboard#12859
=> [2.10] Re-enable vai e2e tests

docusaurus/docs/extensions/publishing.md, docusaurus/extensions_versioned_docs/version-v2/publishing.md, shell/scripts/.gitlab/workflows/build-extension-catalog.gitlab-ci.yml
This updates the node and yq versions within the `build-extension-catalog.gitlab-ci.yml` file that is used by an extension through the reusable workflow mechanism.
- Added documentation around setting the correct target branch for the reusable Gitlab workflow
- Bumped node version `v20.17.0`
- Bumped yq version `v4.4.6`
- Bumped extension creator version `3.0.8`
=> Update extension gitlab workflow node version

creators/extension/app/files/.gitlab-ci.yml, creators/extension/package.json, shell/scripts/.gitlab/workflows/build-extension-catalog.gitlab-ci.yml
This updates the target branch of the reusable workflow within the `.gitlab-ci.yml` file that is imported into an extension through the creator and ensures we are targeting the correct branch of the workflow file.
- Backporting the `build-extension-catalog.gitlab-ci.yml` file to be used as a reusable workflow
- Bumped extension creator version `1.0.9`
=> [2.8] Align gitlab resuable workflow with release-2.8

pkg/aks/components/CruAks.vue, pkg/aks/components/__tests__/CruAks.test.ts
Fixes #12469 
Backport of https://github.com/rancher/dashboard/pull/13037
=> [2.10.2] fix aks region being overwritten when editing unprovisioned aks clusters

README.md, shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml
Update the copyright message for SUSE
=> Update copyright for SUSE

cypress/e2e/tests/pages/fleet/gitrepo.spec.ts, pkg/aks/l10n/en-us.yaml, pkg/aks/util/__tests__/validators.test.ts, pkg/aks/util/validators.ts
Fixes #12470 
Backport of https://github.com/rancher/dashboard/pull/13039
=> [2.10.2] validate that AKS node pool count is no more than 1000

shell/components/ClusterIconMenu.vue, shell/components/nav/TopLevelMenu.vue, shell/models/management.cattle.io.cluster.js
Fixes #13127 
Backport of #12582
=> [2.10.2] - Backport fix for the badge background color issue

cypress/e2e/tests/pages/fleet/gitrepo.spec.ts, package.json, shell/components/fleet/FleetBundles.vue, shell/list/fleet.cattle.io.bundle.vue
Fixes https://github.com/rancher/dashboard/issues/13134
See https://github.com/rancher/dashboard/issues/13134#issuecomment-2595284946
See https://github.com/rancher/dashboard/issues/13134#issuecomment-2595284941
Also the Continuous Delivery --> Advanced --> Bundles page (should load and show at least one bundle)
=> [2.10] Fix gitrepo bundle list and bundle list when there's a gitrepo that does not contain a summary

shell/package.json
=> release rc version of shell for testing

pkg/harvester-manager/l10n/en-us.yaml, pkg/harvester-manager/list/harvesterhci.io.management.cluster.vue, pkg/harvester-manager/types.js, shell/utils/uiplugins.ts
=> [backport 2.10] Match Harvester community repo check via regex

shell/assets/styles/vendor/vue-select.scss
Fixes #
- Fix style regression referenced in https://github.com/rancher/dashboard/pull/13139/files/9e6a8e64181de4525ad378d4d1b93c8efc2ed6d5#r1929296126
=> fix style regression

shell/list/workload.vue
Workloads page title is missing.
fixes #13197
- Workloads nav, to verify Resource's titles of Workloads and other sub types (e.g.: Pods, Jobs, ....)
Before
After
=> Fix missing Workloads page title.

shell/core/plugins.js
The goal is to simplify the logic while possibly improving performance. 
fixes https://github.com/rancher/dashboard/issues/8895
Removed the logic based on this comment in the issue https://github.com/rancher/dashboard/issues/8895#issuecomment-2462054949.
With extensions installed verify the extensions behave as expected wth:
- Logging in
- Logging out
- Navigating between pages
See above
No functional/visual changes should be present.
=> Removing unload logic from the plugin load logic

shell/assets/translations/en-us.yaml
Fix typo in container shell failure message
Fixes #13254
=> Fix typo in container shell failure message

shell/components/fleet/ForceDirectedTreeChart/index.vue, shell/pages/c/_cluster/fleet/GitRepoGraphConfig.js
Fixes #13271
New cluster link format: `namespace`:`displayName`
=> Replace clusterId with cluster Name in Fleet Graphs links

.github/workflows/add-issue-labels.yaml, .github/workflows/build-and-upload.yaml, .github/workflows/build-extension-charts.yml, .github/workflows/build-test.yaml, .github/workflows/check-plugins.yaml, .github/workflows/docusaurus.yaml, .github/workflows/pr-gh-project.yaml, .github/workflows/rancher-components.yaml, .github/workflows/release-rancher-components.yml, .github/workflows/release-rancher-desktop.yml, .github/workflows/test.yaml, cypress/e2e/tests/pages/fleet/gitrepo.spec.ts
- bump deprecated gh action artifact v3 to v4
- similar to https://github.com/rancher/dashboard/pull/13102 and https://github.com/rancher/dashboard/pull/13100
=> [2.9] Bump version of gh artifact actions 

cypress/e2e/tests/pages/generic/links.spec.ts, shell/assets/translations/en-us.yaml, shell/config/home-links.js, shell/pages/c/_cluster/settings/links.vue
Fixes #13022
This PR swaps the SUSE Collective link for SUSE Application Collection.
It also updates the automated tests accordingly.
=> Change SUSE Collective link

.github/workflows/build-and-upload.yaml, .github/workflows/build-extension-charts.yml, .github/workflows/build-test.yaml, .github/workflows/docusaurus.yaml, .github/workflows/pr-zube.yaml, .github/workflows/rancher-components.yaml, .github/workflows/release-rancher-components.yml, .github/workflows/test.yaml, docusaurus/docs/guide/build-for-container-registry.md
Fixes #
Fixes https://github.com/rancher/dashboard/actions/runs/13063888181/job/36469998342
=> Fix extensions tests failing for 2.8

cypress/e2e/tests/pages/fleet/gitrepo.spec.ts, shell/components/fleet/FleetBundles.vue, shell/list/fleet.cattle.io.bundle.vue
Blocked on https://github.com/rancher/dashboard/pull/13304
Fixes #13160
- Fix is same as others (sans gate fixes)
- https://github.com/rancher/dashboard/pull/13137
- https://github.com/rancher/dashboard/pull/13135
- details see https://github.com/rancher/dashboard/issues/13134#issuecomment-2595284946
see original description and comment https://github.com/rancher/dashboard/issues/13134#issuecomment-2595284941
=> [2.9] Fix fleed bundle missing status summary

shell/package.json
Bump shell package version to release a new RC
=> bump shell to 3.0.2-rc.3

pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue, shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml, shell/edit/__tests__/fleet.cattle.io.gitrepo.test.ts, shell/edit/fleet.cattle.io.gitrepo.vue
Fixes #12461
- Removed repository banner, see screenshots
- Adding a title for GitHub & Helm section: 'Source', should be changed with something more appropriate 
- Removed banner from Paths ArrayList, see screenshots
- Fixed grammar in `Always Keep Resources`
- Fixed Repository placeholder, using the text from old banner
- Removed banners from checkbox fields
Git Repo section
Removed Banners
=> [2.10.3] Improve fleet git repo wizard

cypress/e2e/po/edit/provisioning.cattle.io.cluster/create/cluster-create-rke1-custom.po.ts, cypress/e2e/po/edit/provisioning.cattle.io.cluster/create/cluster-create.po.ts, cypress/e2e/tests/pages/manager/cluster-manager.spec.ts, cypress/jenkins/cypress.config.jenkins.ts, cypress/jenkins/cypress.sh, cypress/jenkins/init.sh
Fixes: https://github.com/rancher/qa-tasks/issues/1223
Adding real infrastructure to the existing RKE1 Custom cluster test
Jenkins CI
Corral
CI
Depends on: https://github.com/rancherlabs/corral-packages/pull/73
=> Support for Custom RKE1

shell/components/Carousel.vue, shell/components/__tests__/Carousel.test.ts
Fixes #12480 
Unfortunately css translate properties are treated differently in different browsers, so the css left property is used instead for consistent rendering.
- Added `isTransitioning` flag to block fast clicking on the prev/next buttons.
- Added `shouldDisableTransition` to create the illusion of an infinite carousel.
- Used refs instead of DOM selectors.
- Fixed disabled styling for next/prev buttons.
- Removed some unused code.
- Added some unit tests
Test it on different browsers.
https://github.com/user-attachments/assets/7087158e-6b23-4ab9-9016-09bebf16b4e0
=> Fix Featured Charts Carousel

shell/assets/translations/en-us.yaml, shell/components/CopyToClipboardText.vue, shell/components/PromptChangePassword.vue, shell/pages/account/index.vue
Fixes #13237 
- address modal issue on account and api keys
- improve accessibility/keyboard nav on account and api keys screen
=> address modal issue on account and api keys

.github/workflows/test.yaml, cypress/e2e/po/pages/virtualization-mgmt/harvester-clusters.po.ts, cypress/e2e/tests/pages/virtualization-mgmt/harvester.spec.ts, cypress/e2e/tests/setup/rancher-setup.spec.ts, cypress/globals.d.ts, cypress/support/commands/rancher-api-commands.ts, cypress/support/utils/api-endpoints.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1651
- This PR adds overage for harvester install/upgrade and messaging scenarios (https://github.com/rancher/dashboard/issues/13203). 
- Note: some PR checks are pending due to branch protection (which is expected). @richard-cox will force merge this PR once it's ready and then update the branch protection rules from there.
=> automation: harvester tests

shell/models/provisioning.cattle.io.cluster.js, shell/package.json
- bump the shell package version in preparation for a new RC
- fixed a typo in a translation string
=> bump shell version to 3.0.2-rc.4

shell/assets/translations/en-us.yaml, shell/components/CopyToClipboardText.vue, shell/components/nav/WindowManager/ContainerLogs.vue, shell/components/nav/WindowManager/index.vue
Fixes #12805 
- add missing alt to image elements
=> add missing alt to image elements

shell/assets/translations/en-us.yaml, shell/components/ButtonGroup.vue, shell/components/ButtonMultiAction.vue, shell/components/ExplorerProjectsNamespaces.vue, shell/components/SortableTable/index.vue, shell/list/management.cattle.io.setting.vue
Fixes #12806 
- fix missing textual description on image buttons
- not all changes are in this PR because they had been included in previously merged PR's for accessibility
=> fix missing textual description on image buttons

creators/extension/app/app.package.json, creators/extension/package.json
Fixes https://github.com/rancher/dashboard/actions/runs/13274976383/job/37062693792
- add needed resolution
- bump creators package
=> Fix workflow test for extensions on master - creator test for legacy v1

cypress/e2e/tests/pages/generic/get-support.spec.ts, cypress/e2e/tests/pages/generic/home.spec.ts, shell/config/home-links.js
Backport of https://github.com/rancher/dashboard/pull/13407
=> change forums.rancher.com to forums.suse.com

creators/extension/app/app.package.json, creators/extension/package.json
Fixes #
Same as https://github.com/rancher/dashboard/pull/13381 which fixed the issue for `legacy-v1` (or 2.8 world). Does _not_ impact `Dashboard` product in any way.
- Fix ext test fail creators `legacy-v2`
- bump creators version
I've also checked `latest` and all is good there ✅
=> Fix workflow test for extensions on master - creator test for legacy v2

pkg/rancher-components/src/components/RcDropdown/RcDropdownItem.vue
This removes the update to focus when hovering dropdown menu items. 
Based on follow-up conversations for https://github.com/rancher/ux/issues/120, we decided that focus should not update on mouse hover either.
- remove the update to focus when hovering over dropdown menu items
NA
- dropdown menus
- dropdown menus
NA
=> Remove focus on mouse enter for dropdown menu items

shell/package.json
Bumpp the shell package version in preparation for a new @rancher/shell RC
=> bump shell package version to 3.0.2-rc5

shell/components/formatter/WorkloadHealthScale.vue
Fixes #12782 
- fix space key triggering scroll on page
=> fix space key triggering scroll on page

shell/components/form/SelectOrCreateAuthSecret.vue, shell/components/form/__tests__/SelectOrCreateAuthSecret.test.ts, shell/edit/fleet.cattle.io.gitrepo.vue
=> Hide SSH_KNOWN_HOSTS outside of Fleet

pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue, shell/pages/auth/login.vue, shell/utils/string.js
Fixes #12804 
- fix form fields missing label associations
=> fix form fields missing label associations

cypress/e2e/tests/pages/virtualization-mgmt/harvester.spec.ts, shell/assets/translations/en-us.yaml, shell/pages/auth/login.vue, shell/pages/auth/verify.vue, shell/store/auth.js
Fixes #6343
This PR fixes the above issue - for  oauth providers, if the user is redirected back to the UI, then they are able to login - i.e. their credentials are correct - but they do not have access - we now detect this and return with the error message `You are not authorized to use this system.`
=> Fix GitHub auth error

cypress/e2e/po/pages/page.po.ts, cypress/e2e/tests/pages/user-menu/preferences.spec.ts, cypress/globals.d.ts, cypress/support/commands/rancher-api-commands.ts, shell/components/LandingPagePreference.vue, shell/components/templates/default.vue, shell/config/router/navigation-guards/index.js, shell/config/router/navigation-guards/record-last-route.js, shell/store/prefs.js, shell/utils/auth.js
Fixes https://github.com/rancher/dashboard/issues/11224
I fixed and simplified a few of the code-paths regarding the `Take me to the area I last visited` user preference. This should help prevent future breakages of this feature and reduce a small amount of a our tech debt.
Login landing page. Verifying that the user it taken to the correct landing page after logging in.
Login landing page. Verifying that the user it taken to the correct landing page after logging in.
https://github.com/user-attachments/assets/1f634715-49a9-4ad2-840e-dc9d954f8270
=> Adding a after login redirect for the case when a user enters a url but gets redirected to the login page

cypress/jenkins/cypress.config.jenkins.ts
Fixes jenkins issue when running tests
=> Jenkins cypress config

cypress/e2e/blueprints/fleet/gitrepos.ts, cypress/e2e/po/components/select-or-create-auth.po.ts, cypress/e2e/po/pages/fleet/gitrepo-create.po.ts, cypress/e2e/po/prompts/KnownHostsEditDialog.po.ts, cypress/e2e/tests/pages/fleet/gitrepo.spec.ts, shell/assets/translations/en-us.yaml, shell/assets/translations/zh-hans.yaml, shell/components/Wizard.vue, shell/components/form/ArrayList.vue, shell/components/form/KeyValue.vue, shell/components/form/Labels.vue, shell/components/form/SSHKnownHosts/KnownHostsEditDialog.vue, shell/edit/__tests__/fleet.cattle.io.gitrepo.test.ts, shell/edit/fleet.cattle.io.gitrepo.vue
Fixes #13402
Fixes #13473
Metadata
Repository details
Target Details
Advanced
=> Fleet GitRepo wizard UX improvements, new steps, fields size and banners

package.json
Fixes #
- re-enable sorry cypress in `master`
=> re-enable sorry cypress in `master`

shell/components/fleet/FleetRepos.vue, shell/edit/__tests__/fleet.cattle.io.gitrepo.test.ts, shell/edit/fleet.cattle.io.gitrepo.vue
=> Fleet: hide advanced info banner in view mode and vue3 errors fix

pkg/aks/components/__tests__/Taint.test.ts, shell/edit/secret/__tests__/ssh.test.ts, shell/edit/secret/ssh.vue, shell/models/__tests__/secret.test.ts, shell/models/secret.js
=> Fix SSH Key missing fields

pkg/rancher-components/src/components/Form/Radio/RadioButton.vue, pkg/rancher-components/src/components/Form/Radio/RadioGroup.vue, shell/components/LandingPagePreference.vue, shell/components/form/ColorInput.vue
Fixes #13427 
- fix space scrolling page selecting radio inputs and color inputs
- fix/improve keyboard navigation in radio groups
=> fix space scrolling page selecting radio inputs and color inputs

cypress/e2e/tests/pages/virtualization-mgmt/harvester.spec.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1709
This pr fixes flaky harvester extension test
=> fix flaky harvester test

cypress/e2e/tests/pages/explorer/apps/charts.spec.ts, cypress/e2e/tests/pages/global-settings/feature-flags.spec.ts
Temporary skip global settings tests.
=> Disabled global settings tests

shell/assets/translations/en-us.yaml, shell/models/management.cattle.io.fleetworkspace.js, shell/promptRemove/management.cattle.io.fleetworkspace.vue
=> Fleet improve Workspaces delete dialog

shell/assets/translations/en-us.yaml
This adds missing localizations for key/value aria labels. 
Fixes #12813
- Add missing localizations for key/value aria labels. 
The localized values were omitted from  #13261, causing the behavior noted in QA review (https://github.com/rancher/dashboard/issues/12813#issuecomment-2688805229). 
- Key/Value component
- NA
- NA
=> Add missing localizations for Key/Value aria labels

cypress/e2e/tests/pages/virtualization-mgmt/harvester.spec.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1709
This is my second attempt to resolve the flakiness of the Harvester tests, as my [first attempt](https://github.com/rancher/dashboard/pull/13536) was unsuccessful.
=> fix flaky harvester test p2

pkg/rancher-components/src/components/RcButton/RcButton.test.ts
This adds unit tests for the RcButton component.
- Add unit tests for the RcButton component
The RcButton component needs unit tests, this adds some.
The unit tests should pass.
The unit tests should pass.
- NA
=> Add unit tests for RcButton

.github/workflows/test.yaml, shell/plugins/steve/steve-pagination-utils.ts
Re-enable via tests
- vai tests are disabled given some pending backend changes - https://github.com/rancher/rancher/issues/48965
- this enables them, and also updates given change to exact/partial filter
- vai on and bring up dashboard. the api requests to support the side nav should not fail
=> Enable vai e2e tests

pkg/aks/l10n/en-us.yaml
Fix spelling mistakes in aks plugin
- highlighted by trusty `Code Spell Checker` vs code extension
=> Fix spelling mistakes in aks plugin

shell/edit/monitoring.coreos.com.prometheusrule/AlertingRule.vue, shell/edit/monitoring.coreos.com.prometheusrule/RecordingRule.vue
Fixes #13621 
- fix all instances of `CodeMirror` component inside `LabeledInput` by setting the correct width
=> fixes difficulty inserting text in the PromQLExpression field while creating PrometheusRules

.github/workflows/scripts/check-creators-workflows-code.sh, .github/workflows/test-extension-workflows-master.yml
Fixes #12657 
- Fixes the broken workflow tests for extensions
- The changes proposed are based on the work done in https://github.com/rancher/dashboard/pull/13551 + https://github.com/aalves08/dashboard/actions/workflows/test-wf.yml
=> fix broken extension tests in master

shell/components/form/Members/MembershipEditor.vue
=> [Backport] - Fix project members not showing up

shell/machine-config/vmwarevsphere.vue
Fixes https://github.com/rancher/dashboard/issues/13441
We were resetting the values to the disabled/default values instead of letting the custom values persist. This was happening when we were setting the mode.
Editing the vapp properties.
https://github.com/user-attachments/assets/b6be492c-c431-4d62-9d75-6fde7cacf452
=> Preventing the UI from overriding custom vapp fields when they're set

pkg/gke/components/Import.vue, pkg/gke/components/__tests__/Import.test.ts
=> GKE - Filter importable clusters to only the running clusters

pkg/gke/components/Config.vue, pkg/gke/components/CruGKE.vue, pkg/gke/components/Import.vue, pkg/gke/components/__tests__/Config.test.ts, pkg/gke/components/__tests__/Import.test.ts, pkg/gke/types/gcp.d.ts, pkg/gke/util/__mocks__/gcp.ts
Fixes #13686 
Fixes #13695
Fixes #13696 
Fixes #13697 
- add a loading spinner to the cluster dropdown
- hide the 'extra zones' checkboxes when importing gke clusters
- validate that a cluster name is defined
- fix broken cluster name text input
Importing GKE clusters, as described in the linked issues above
Create new GKE cluster - verify that the extra zones checkboxes are rendered, and that form validation is still working (nbo extra name validator)
=> Fix gke import loading

.eslintrc.default.js, jest.setup.js, package.json, pkg/rancher-components/package.json, pkg/rancher-prime/config/constants.ts, pkg/rancher-prime/config/index.ts, pkg/rancher-prime/config/navigation.ts, pkg/rancher-prime/index.ts, pkg/rancher-prime/l10n/en-us.yaml, pkg/rancher-prime/pages/Registration.vue, pkg/rancher-prime/pages/__tests__/Registration.test.ts, pkg/rancher-prime/routing/index.ts, shell/components/StatusBadge.vue, shell/package.json, storybook/src/stories/Components/IconMessage.mdx, storybook/src/stories/Components/IconMessage.stories.ts, storybook/src/stories/Components/StatusBadge.mdx, storybook/src/stories/Components/StatusBadge.stories.ts, yarn.lock
Fixes #13288
Added product configurations:
- Registration route `/c/local/settings/registration`
- Side navigation in `Global Settings/Registration`
- Registration page (mocked UI)
- `StateBadge` component
- Added unit tests for all the input combinations
- Bumped `eslint-plugin-vue` to `9.32.0`
- Added StateBadge component based on existing implementation
- Storybook
- Created Story for `IconMessage` as part of the icon investigation with the design
- Created Story for `StateBadge`
- In Jest setup 
- Added `useI18n` mock to prevent issues with the hook globally, matching current configuration for Options API
- Muted `[Vue warn]` console warning as unnecessary
As per video.
- Navigate to `Global Settings/Registration` 
- Insert registration code online
- Submit registration code
- …
=> Create page for SCC registration for Rancher Prime

shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/utils/object.js
Fixes #13768 
Revert using `mergeWithReplaceArrays` in `initYamlEditor` instead of simple `merge`. This will undo the fix for #12418 .
=> Fix vSphere CSI/CPI config not being sent properly

shell/scripts/extension/helm/charts/ui-plugin-server/templates/_helpers.tpl
Fixes https://github.com/rancher/dashboard/issues/13584
This change enhances the extension-server.labels directive in _helpers.tpl to avoid error when setting the app.kubernetes.io/version label with version which includes + character. This is valid for semver but not for label version.
The solution adopts the convention used in Helm which replaces + with _ when storing the version in places which don't allow + usage, e.g. OCI repository.
The same approach is already used in the `extension-server.chart` directive, which is also used as a label value.
=> Sanitize the version when setting it in UIPlugin label

pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue, shell/components/form/UnitInput.vue, shell/components/form/__tests__/UnitInput.test.ts, shell/edit/service.vue, shell/edit/workload/Job.vue, shell/edit/workload/__tests__/Job.test.ts, shell/package.json
Fixes #13784
- fix `UnitInput` component by reacting to `update:change`
- adjust unit tests
- bump shell version so that we can release a new version for a partner extension with this fix
**Before**
https://github.com/user-attachments/assets/699ce72a-9c5c-4b37-94de-61a0974ba566
**After**
https://github.com/user-attachments/assets/5169c2a2-17fb-4f58-b13e-3df5f8e80cbb
=> fix bug with Unit Input component not updating correctly

shell/scripts/test-plugins-build.sh
Fixes #13173
Fixes #13141
- re-enable extension checks
=> re-enable extension checks

shell/edit/fleet.cattle.io.gitrepo.vue
Fixes #13824
[Screencast from 2025-03-20 10-01-53.webm](https://github.com/user-attachments/assets/e5f225be-a5a6-4020-ba79-64c31ae72a8c)
=> Fleet, set default pollingInterval on creation

docusaurus/docs/extensions/catalog.mdx
Bug fix for https://github.com/rancher/dashboard/issues/13512
Fixes broken link - the link for developer docs is incorrect. 
I've removed the sentence about developing, since the docs is already within the developer docs.
=> Fix community catalog docs page broken link

shell/edit/logging-flow/Match.vue
=> Fix namespaces selector in Match.vue component

shell/assets/translations/en-us.yaml, shell/components/form/ArrayList.vue, shell/components/form/KeyValue.vue, shell/edit/fleet.cattle.io.gitrepo.vue
Fixes #13831 
- fix some a11y items on `ArrayList` (unique `remove` labels + add missing roles + add ability to provide `aria-label` to generic input)
- fix some a11y items on `KeyValue` (unique `remove` labels)
=> fix some a11y items on ArrayList and KeyValue

shell/components/auth/Principal.vue, shell/pages/about.vue
Fixes #13818 
- add missing `th` to tables with headers on the left side
Solution based on https://www.w3.org/WAI/tutorials/tables/one-header/#table-with-header-cells-in-the-first-column-only
=> add missing th to tables with headers on the left side

docusaurus/docs/extensions/advanced/version-compatibility.md, docusaurus/docs/extensions/extensions-configuration.md, docusaurus/extensions_versioned_docs/version-v2/advanced/version-compatibility.md, docusaurus/extensions_versioned_docs/version-v2/extensions-configuration.md
Fixes #
- remove documentation about catalog.cattle.io/ui-version as its a pattern we should not encourage
=> remove documentation about catalog.cattle.io/ui-version

docusaurus/extensions/catalog/partner/app-launcher.yaml
Fixes #
- add krumware app-launcher extension to catalog in docs
=> add krumware app-launcher extension to catalog in docs

shell/components/ExplorerMembers.vue
Fixes #13801 
Added `force: true` argument when getting `projectRoleTemplateBindings` from the store in `ExplorerMembers.vue` in order to update the project members list.
https://github.com/user-attachments/assets/b3a90b4b-c8a5-4c69-b37f-72ea00f8244f
=> Fix missing project members

cypress/e2e/tests/pages/global-settings/branding.spec.ts, cypress/e2e/tests/pages/global-settings/settings.spec.ts, shell/assets/translations/en-us.yaml, shell/pages/auth/login.vue, shell/pages/home.vue
Fixes #13849 
- fix identical page title in `login` and `home` pages
=> fix identical page title

docusaurus/extensions/catalog/vcloud-director.yaml
=> remove catalog entry

shell/edit/auth/__tests__/oidc.test.ts
Fixes #
- fix `oidc` unit test
=> fix unit test

pkg/eks/components/Config.vue, pkg/eks/components/CruEKS.vue, pkg/eks/components/Networking.vue, pkg/eks/components/__tests__/Config.test.ts, pkg/eks/components/__tests__/CruEKS.test.ts, pkg/eks/components/__tests__/Networking.test.ts, shell/store/aws.js
Fixes #13685
Backport of #13730
=> [2.11.1]handle aws pagination

pkg/eks/components/Config.vue, pkg/eks/components/CruEKS.vue, pkg/eks/components/Networking.vue, pkg/eks/components/__tests__/Config.test.ts, pkg/eks/components/__tests__/CruEKS.test.ts, pkg/eks/components/__tests__/Networking.test.ts, shell/store/aws.js
Fixes #13762 
Backport of #13730
=> [2.10.5] handle aws pagination

shell/models/management.cattle.io.node.js
Fixes #13660 
Backport of #14001
=> [2.11.1] Hide the 'scale down' action on the kontainer driver cluster detail page

.github/workflows/add-issue-labels.yaml, .github/workflows/build-and-upload-branch.yaml, .github/workflows/build-and-upload-release.yaml, .github/workflows/build-and-upload.yaml, .github/workflows/close-stale-enhancement-requests.yaml, .github/workflows/extensions-compatibility-tests.yaml, .github/workflows/fossa.yaml, .github/workflows/pr-gh-project.yaml, .github/workflows/release-rancher-components.yml
Fixes #13986
Updates appropriate workflows to restrict them to running on `rancher/dashboard` and not on forks.
=> Update some workflows to only run on rancher/dashboard

docusaurus/docs/internal/testing/e2e-test.md
Update e2e docs for `data-testid`
=> Update e2e docs for `data-testid`

cypress/e2e/po/prompts/deactivateDriverDialog.po.ts, cypress/e2e/tests/pages/manager/kontainer-drivers.spec.ts, shell/assets/translations/en-us.yaml, shell/dialog/DeactivateDriverDialog.vue, shell/models/kontainerdriver.js, shell/models/nodedriver.js
Fixes #9183 
Added growls to activate requests
For both node (not covered by E2E tests) and cluster drivers verify that if activate, deactivate, activate in bulk, and deactivate requests fail, appropriate error is displayed.
None
https://github.com/user-attachments/assets/a28142b3-9dc8-499a-a883-1531dcd213c5
=> [FIX] Added error handling when driver activation fails

shell/assets/translations/en-us.yaml, shell/components/CopyToClipboardText.vue, shell/components/DetailText.vue, shell/components/formatter/InternalExternalIP.vue, shell/dialog/ForceMachineRemoveDialog.vue, shell/edit/auth/azuread.vue, shell/edit/auth/googleoauth.vue, shell/pages/account/index.vue, shell/pages/auth/setup.vue
Fixes #14013
- Add meaningful `aria-label`'s to `CopyToClipboard` and `CopyToClipboardText` components
=> fix aria-labels in "copy to clipboard"

shell/components/form/UnitInput.vue, shell/components/form/__tests__/UnitInput.test.ts, shell/edit/service.vue, shell/edit/workload/Job.vue, shell/edit/workload/__tests__/Job.test.ts
Backport for #13784 
Fixes #14022
- fix `UnitInput` component by reacting to `update:change`
- adjust unit tests
**Before**
https://github.com/user-attachments/assets/699ce72a-9c5c-4b37-94de-61a0974ba566
**After**
https://github.com/user-attachments/assets/5169c2a2-17fb-4f58-b13e-3df5f8e80cbb
=> backport PR 13780 - 2.11

shell/components/form/UnitInput.vue, shell/components/form/__tests__/UnitInput.test.ts, shell/edit/service.vue, shell/edit/workload/Job.vue, shell/edit/workload/__tests__/Job.test.ts
Backport for #13784 
Fixes #14023
- fix `UnitInput` component by reacting to `update:change`
- adjust unit tests
**Before**
https://github.com/user-attachments/assets/699ce72a-9c5c-4b37-94de-61a0974ba566
**After**
https://github.com/user-attachments/assets/5169c2a2-17fb-4f58-b13e-3df5f8e80cbb
=> backport PR 13780 - 2.10

shell/components/PromptRemove.vue, shell/components/PromptRestore.vue, shell/list/management.cattle.io.feature.vue
Fixes #13906 
Fixes #13907 
Fixes #13910  
- Fix focus trap for `PromptRemove` modal
- Fix focus trap for `PromptRestore` modal
- Fix focus trap for modal in `management.cattle.io.feature` list view
- to test the `PromptRemove` modal just go to cluster management and try to delete a cluster
- to test the `PromptRestore` modal you should provision a downstream cluster like Digital Ocean (need to be able to manage snapshots), then on Cluster Management list view, go to table action `Restore Snapshot`
- to test the modal in `management.cattle.io.feature` list view, just go to Global Settings - Feature flags - then try to enable/disable a flag that needs a Rancher system restart
https://github.com/user-attachments/assets/82e12f2e-bdd3-4832-a955-3420501a25c8 …
=> fix focus trap in various modals - part 2

cypress/e2e/po/extensions/imported/cluster-edit.po.ts, cypress/e2e/po/extensions/imported/cluster-import-generic.po.ts, cypress/e2e/tests/pages/manager/cluster-manager.spec.ts
Fixes #
https://github.com/rancher/qa-tasks/issues/1757
https://github.com/rancher/qa-tasks/issues/1767
This PR updates imported clusters tests:
- fixes issues seen in Jenkins
- add steps to verify accordion elements display properly
=> update imported cluster tests

cypress/e2e/po/components/create-edit-view.po.ts, cypress/e2e/po/edit/provisioning.cattle.io.cluster/cluster-create-import.po.ts, cypress/e2e/po/pages/global-settings/performance.po.ts, cypress/e2e/po/prompts/shared/promptInstances.po.ts, cypress/e2e/tests/pages/global-settings/performance.spec.ts, cypress/e2e/tests/pages/manager/cluster-list.spec.ts, cypress/e2e/tests/pages/users-and-auth/users.spec.ts, cypress/e2e/tests/priority/vai-setup.spec.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1699
- This PR adds an e2e test to ensure that clusters can be grouped by namespace
- Fixes flaky users tests
=> automation: group by namespace feature test

shell/package.json, shell/scripts/extension/publish
Fixes #13648
- Add `pipefail` to `publish` script
- Bump shell version to `3.0.5-rc.1`
=> add pipefail to publish script + bump shell version

shell/chart/monitoring/index.vue
Fixes #13866
- we were fetching a specific path on all workload types
- however it doesn't exist for cron jobs, so exclude
- as per issue
=> Ensure Monitoring install wizard storage class can be selected

cypress/e2e/tests/pages/global-settings/feature-flags.spec.ts
Fixes #13575
- Given backend blocking [issue](https://github.com/rancher/rancher/issues/49303) has been fixed, so re-enable the disabled E2E tests
=> Re-Enable FF e2e tests

storybook/package.json
This removes the esbuild resolution that was set in the Storybook package.json.
Fixes #12924 
- remove the esbuild resolution that was set in the Storybook package.json
Previous issues that required the resolution were resolved via https://github.com/evanw/esbuild/releases/tag/v0.24.2
Storybook should build and run without errors
NA
NA
=> Remove esbuild resolution in storybook dependencies

shell/components/form/ArrayList.vue, shell/components/form/__tests__/ArrayList.test.ts, shell/edit/provisioning.cattle.io.cluster/__tests__/Advanced.test.ts
Fixes #14084
Added a prop to allow components provide a prefix for data-testid properties so ensure uniqueness.
None
None
=> Added data-testid prefix prop to ArrayList

pkg/harvester-manager/l10n/en-us.yaml
Fixes # https://github.com/harvester/docs/pull/754#pullrequestreview-2763355921
Update non-supported harvester message based on technique writer suggestion
=> Update non-supported harvester message

pkg/harvester-manager/edit/harvesterhci.io.management.cluster.vue
Fixes # https://github.com/rancher/dashboard/issues/14181
This is the backport PR for 2.11 from https://github.com/rancher/dashboard/pull/13779.
=> [backport 2.11] Error banners are not being displayed in import harvester edit page

shell/models/management.cattle.io.node.js
Fixes #12464
Backport of #14001
=> [2.10.6] Hide the scale up/down actions on AKS, EKS, and GKE cluster detail pages

.github/workflows/test.yaml
- see slack conversation
- https://github.com/rancher/dashboard/issues/14230
=> Temporarily comment out CI runs on merges to master

pkg/harvester-manager/machine-config/harvester.vue
Fixes # https://github.com/rancher/dashboard/issues/14223
Backport https://github.com/rancher/dashboard/issues/14219 to release-2.11.
=> [Backport 2.11] uncheck install guest agent when choosing user data template in harvester downstream provision page

shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/pages/c/_cluster/apps/charts/install.vue, shell/utils/__tests__/object.test.ts, shell/utils/object.js
=> [Backport 2.11.2] - Logging chart yaml

shell/edit/provisioning.cattle.io.cluster/__tests__/DirectoryConfig.test.ts, shell/edit/provisioning.cattle.io.cluster/tabs/DirectoryConfig.vue
Fixes https://github.com/rancher/dashboard/issues/14287
Original kudos to @khushalchandak17 for the fix in https://github.com/rancher/dashboard/pull/14262. Re-did the PR so that we could add/update unit tests
- address issue with common config and updating k8s version
- updates unit tests
Test creating and editing clusters with all three directory configuration options (Default, Common, Custom) and changing the Kubernetes version during and after creation to ensure the directory settings behave as described.
=> address issue with common config and updating k8s version

shell/detail/catalog.cattle.io.app.vue
Fixes #13980
Changes to merge behavior so that user supplied values overwrite default values when merging.
Similar to work done in #14200 for the edit view, we also need to use the updated merge behavior for the details view.
See comment in https://github.com/rancher/dashboard/issues/13980#issuecomment-2864342017.
I don't think there's any other areas where we perform this merging behavior for the installed apps yaml, but I think it's best to be on the lookout in the event that we missed anything at this point.
Since we are changing the merge behavior, the yaml representation could be different from before.
=> Detail view: Overwrite defaults with user-supplied chart values

shell/package.json, shell/scripts/extension/publish
Fixes #14345 
- revert pipefail change 
- bump shell
=> revert pipefail change + bump shell

cypress/e2e/po/side-bars/slide-in.po.ts, cypress/e2e/tests/pages/explorer/dashboard/cluster-dashboard.spec.ts, pkg/kubectl-explain/components/SlideInPanel.vue, shell/assets/styles/global/_layout.scss, shell/components/SlideInPanelManager.vue, shell/components/nav/WindowManager/index.vue
Fixes #14314 
- fix problem with extra space and scroll on settings banner page
Couldn't really find the root cause, but the overflow on that CSS rule doesn't do anything apparently (it's a grid well defined in size) and it's causing that extra scroll to happen. Only seems to happen on chromium based browsers
=> fix problem with extra space and scroll on settings banner page

.github/pull_request_template.md
Fixes #14276 
- update PR template to consider accessibility when reviewing
=> update PR template to consider accessibility when reviewing

cypress/e2e/tests/pages/global-settings/settings-p2.spec.ts, package.json, scripts/e2e-docker-start
This targets the staging repo for running e2e tests in the release-2.10 branch.
- Target the staging repo for running e2e tests in the release-2.10 branch
The staging repo contains the images that we need for running accurate and up to date e2e tests for 2.10 releases. 
- e2e tests should pass in CI
- Previous e2e test regressions should be resolved
NA
NA
=> Migrate to staging repository for e2e tests

cypress/e2e/tests/pages/manager/machine-deployments.spec.ts
A visual test has been created using Percy to verify the machine deployments screen within Rancher. The goal of this test is to ensure that the user interface is displayed correctly and detect any unexpected visual changes
Page route:
`/dashboard/c/_/manager/cluster.x-k8s.io.machinedeployment`
#Fixes:
fixes:
https://github.com/rancher/qa-tasks/issues/1829
=> Implementation of Visual Test with Percy for Machine Deployments page 

.github/workflows/scripts/pr-gh-project.js, docusaurus/package.json
Fixed docusaurus failing
None
None
None
None
=> Fixed docusaurus failing

shell/components/form/LabeledSelect.vue, shell/components/form/Select.vue, shell/components/form/__tests__/LabeledSelect.test.ts, shell/components/form/__tests__/Select.test.ts
Fixes #14373 
- fix problem with `space` key on searchable selects 
- test both `LabeledSelect` and `Select` components, both `searchable` or not
- possible regression on https://github.com/rancher/dashboard/issues/13252#issuecomment-2672428059
=> backport PR 14362

shell/assets/translations/en-us.yaml
Fixes #14087
- Follow on from https://github.com/rancher/dashboard/pull/14086
- update formatting to be inline with other messages
- given above reworded to maintain settings/ff split
=> SSP: Update formatting and text of now defunct performane setting

shell/plugins/steve/steve-pagination-utils.ts
Fixes #14283
Should also finish off https://github.com/rancher/rancher/issues/49802
- if a ssp filter value contains a special character ensure that the value is "quoated"
- chose to optionally do this to avoid increasing the length of the query strings (there can be quite a few when it comes to ns/projects
- Primarily lists and the free text search
=> SSP: Quote filter values that contain special characters

shell/components/ExplorerProjectsNamespaces.vue, shell/components/formatter/Description.vue, shell/config/table-headers.js
Fixes https://github.com/harvester/harvester/issues/6869
SURE-5788
- Add description formatter to avoid too long description column.
- Add description column in project/namespace table
Before 
After 
Add description column
=> Add description formatter

package.json, yarn.lock
Fixes #14465
Updates axios to 1.9.0.
Updates versions in `package.json` and includes the updated `yarn.lock` file.
Change log checked and this update should be compatible with previously used 1.8.3 - see: https://github.com/axios/axios/releases
e2e tests should be sufficient to validate that API requests are being made correctly.
=> Update axios to 1.9.0

shell/components/Certificates.vue, shell/components/SortableTable/index.vue
Fixes #14423
- see issue for detail
- fix is to break visibility of refresh button on singleton isTooManyItemsToAutoUpdate
as per issue
manual refresh button with vai on (though note this is soon to be hidden via another PR)
=> Don't show invalid `Refresh` button in cluster certificates list

.github/workflows/scripts/update-cloud-data.sh, scripts/azure/update-data
Minor fixes to the script to update Azure cloud data and the GH action that runs this periodically.
Minor changes to slightly improve the logging:
- Fix newline issue in the GH Action script which resulted in `\n` appearing in the log
- Updated the Azure script to be clearer about the government regions that are managed seperately
=> Minor tweaks to cloud update script and GH workflow script

shell/package.json
Bump shell/package version to 3.0.5-rc.4
=> Bump shell/package version to 3.0.5-rc.4

shell/edit/fleet.cattle.io.gitrepo.vue, shell/edit/fleet.cattle.io.helmop.vue
Fixes #14539
- Saving `spec.pollingInterval` on blur to avoid conflict between form update and user input value when assigning `null`.
[Screencast from 2025-06-19 16-14-11.webm](https://github.com/user-attachments/assets/e7aadb24-7430-4e09-977c-9a063d4ef4a9)
=> Fleet fix Polling Interval update

cypress/e2e/blueprints/fleet/gitrepos.ts, cypress/e2e/po/pages/fleet/fleet.cattle.io.application.po.ts, cypress/e2e/tests/pages/fleet/gitrepo.spec.ts, shell/assets/translations/en-us.yaml, shell/components/fleet/FleetGitRepoPaths.vue, shell/components/fleet/__tests__/FleetGitRepoPaths.test.ts, shell/components/form/ArrayList.vue, shell/components/form/KeyValue.vue, shell/edit/__tests__/fleet.cattle.io.gitrepo.test.ts, shell/edit/fleet.cattle.io.gitrepo.vue, shell/utils/__tests__/string.test.ts, shell/utils/string.js
Fixes https://github.com/rancher/dashboard/issues/13188
It adds the possibility to define `bundles` paths, see https://github.com/rancher/fleet/issues/210#issuecomment-2909041872
GitRepo create/edit pages.
- Go to GitRepo create
- Add new paths and subpaths
- Possible test cases: https://github.com/rancher/fleet/issues/210#issuecomment-2912370546
[Screencast from 2025-06-12 18-18-32.webm](https://github.com/user-attachments/assets/170c559a-b50b-4bb2-98c9-d1e206a3d944)
=> Fleet GitRepo Bundles and Paths refactoring

shell/plugins/steve/steve-pagination-utils.ts
Fixes #14283
Affects https://github.com/rancher/rancher/issues/49802
- Follow on from https://github.com/rancher/dashboard/pull/14409
- To avoid a 500 error, for ssp lists, we now filter out the `"` character
- This isn't great, ideally we should prevent the user from entering the char at the component level
- https://github.com/rancher/dashboard/issues/14549
- This is the lo bar fix though given the time we have
- ssp enabled, any supported list, filter by `=`, no error should be seen on screen or failed network requests
- None
=> SSP: Remove `=` from ssp search term filters

shell/components/fleet/FleetResources.vue
Fixes #14592
- Replacing `SortableTable` with `ResourceTable` to get the default pagination from prefs.
=> Fleet fix missing pagination in GitRepos Resources table

shell/edit/fleet.cattle.io.helmop.vue
Fixes https://github.com/rancher/dashboard/issues/14569
Contributes to https://github.com/rancher/dashboard/issues/14547
=> Fleet fix HelmOps `valuesFrom` index

shell/components/fleet/FleetRepos.vue, shell/components/fleet/dashboard/ResourcePanel.vue, shell/models/fleet.cattle.io.gitrepo.js, shell/pages/c/_cluster/fleet/application/create.vue, shell/pages/c/_cluster/fleet/index.vue
Fixes https://github.com/rancher/dashboard/issues/14570
Contributes to https://github.com/rancher/dashboard/issues/14547
- #14570 - fixing Cancel button in App Bundles create page
- #14547 - fixing Icons, fixing Dashboard chart, fixing buttons position
- Pie Chart
=> Fleet improve Dashboard and App Bundles style

shell/components/fleet/dashboard/ResourceDetails.vue, shell/components/formatter/FleetApplicationSource.vue
Fixes #
Contributes to #14547
- App bundle details drawer title should be an h3 for accessibility, and Source and Resources should be h4
- Branch @ commit text should have the same colour as input labels
=> Fleet fix slide-in Resource Details style

pkg/technical-interview/babel.config.js, pkg/technical-interview/config/tech-interview.ts, pkg/technical-interview/index.ts, pkg/technical-interview/l10n/en-us.yaml, pkg/technical-interview/package.json, pkg/technical-interview/pages/tab-page.vue, pkg/technical-interview/routing/interview-routing.ts, pkg/technical-interview/tsconfig.json, pkg/technical-interview/vue.config.js
Update `technical-interview` branch to latest
=> Technical interview

cypress/e2e/blueprints/global_settings/settings-data.ts, cypress/e2e/tests/pages/global-settings/settings-p2.spec.ts, shell/assets/translations/en-us.yaml, shell/config/settings.ts
Fixes #13065 
Adjusted the wording for the description of the k3s-based-upgrader-uninstall-concurrency global setting.
Added a new 'system-agent-upgrader-install-concurrency' global setting.
Go to global settings:
1. Find 'k3s-based-upgrader-uninstall-concurrency'. Confirm that description has changed
2. Find 'system-agent-upgrader-install-concurrency' setting. Confirm it is present, has correct description, and correct default value
None
=> [FEAT] Added new system-agent-upgrader-install-concurrency setting

shell/components/form/ArrayList.vue, shell/components/form/__tests__/ArrayList.test.ts, shell/edit/networking.k8s.io.ingress/Rule.vue
This adds an id to rows in ArrayList so that members can be properly removed.
Fixes #14404
- Add an id to track members of ArrayList.vue
The previous implementation that uses `index` as the key is convenient, but using `index` as a key it is generally discouraged because the index can change if items are added, removed, or reordered in the array. This can lead to unexpected behavior, like we saw in the associated issue.
This is a fundamental change to ArrayList.vue - we might need to select different examples used throughout dashboard to smoke test. The base case described in the issue should be resolved, other usages should not regress when adding, editing, and deleting members of the collection. 
This is a fundamental change to ArrayList.vue - we might need to select different examples …
=> Add an id to track members of ArrayList.vue

shell/edit/fleet.cattle.io.helmop.vue, shell/models/fleet.cattle.io.helmop.js
Fixes #14618
Blocked on `v0.13.0-alpha.8` release
- OCI registry source will be saved in `spec.helm.repo` instead of `spec.helm.chart`
- We need to test this against next alpha Fleet version: `v0.13.0-alpha.8` - let's coordinate offline
App Bundles -> create/edit/view HelmOps
=> Fleet fix HelmOp OCI storage field

shell/components/form/Labels.vue, shell/components/form/__tests__/Labels.test.ts
Contributes to https://github.com/rancher/dashboard/issues/11229
Contributes to https://github.com/rancher/dashboard/issues/13655
`Show System Labels and Annotations` is visible if custom protected labels are defined, we are extending this rule to include labels/annotations that match `/cattle\.io\//`
=> Extend Show System labels toggler to `cattle.io/`

shell/assets/translations/en-us.yaml, shell/components/form/KeyValue.vue, shell/components/form/Labels.vue
=> [2.9.11] Fix protected Labels 

shell/assets/styles/base/_spacing.scss, shell/assets/translations/en-us.yaml, shell/components/ConfigMapSettings/index.vue, shell/components/KeyValueView.vue, shell/components/fleet/FleetClusterTargets/TargetsList.vue, shell/components/fleet/FleetClusterTargets/index.vue, shell/components/fleet/FleetGitRepoPaths.vue, shell/components/fleet/dashboard/ResourcePanel.vue, shell/components/form/ArrayList.vue, shell/components/form/MatchExpressions.vue, shell/components/form/ValueFromResource.vue, shell/detail/management.cattle.io.fleetworkspace.vue, shell/edit/fleet.cattle.io.gitrepo.vue, shell/edit/fleet.cattle.io.helmop.vue, shell/pages/c/_cluster/fleet/application/create.vue, shell/utils/fleet.ts
Fixes #14661
Fixes #14663
Fixes #14685
Contributes to #14547
- Fixing 14663 - gitRepo icon:
- Fixing Dashboard chart's tooltips:
- Remove border in workspace's details page
pre:
post:
- Settings -> Apply button
- Target Clusters
- Git Repo paths/subpaths
- Assign focus on adding new Paths
[Screencast from 2025-07-01 16-48-36.webm](https://github.com/user-attachments/assets/83b116e2-d57b-4831-90b4-b3f9a5843ffd)
- Assign focus on adding new Cluster Targets and Custer targets rules
[Screencast from 2025-07-01 16-49-33.webm](https://github.com/user-attachments/assets/968af16b-a52a-46e4-99c9-051acd837887)
=> Fleet cosmetic fixes

creators/extension/app/app.package.json, creators/extension/package.json
Fixes various failures for the extensions workflow in `master` that occurred last week: https://github.com/rancher/dashboard/actions/workflows/test-extension-workflows-master.yml, more specifically https://github.com/rancher/dashboard/actions/runs/16104591921/job/45438098486
- Add resolution for `minimatch` package
- bump `creators` package version
=> Fix extensions tests creators 2.9

cypress/e2e/tests/pages/fleet/resources/workspaces.spec.ts, shell/assets/translations/en-us.yaml, shell/config/product/fleet.js, shell/detail/management.cattle.io.fleetworkspace.vue, shell/models/management.cattle.io.fleetworkspace.js
Fixes #14710
Details page
Table
=> Fleet Add HelmOps in Workspace pages

cypress/e2e/tests/pages/explorer/apps/charts.spec.ts
Fixes update e2e test cis benchmark app name that has changed
- update e2e test cis benchmark app name that has changed to `Rancher Compliance` as per https://github.com/rancher/dashboard/actions/runs/16140978252/job/45552999322?pr=14730
=> update e2e test cis benchmark app name that has changed

shell/components/form/ArrayList.vue, shell/components/form/__tests__/ArrayList.test.ts, shell/edit/networking.k8s.io.ingress/Rule.vue
This reverts commit 6ee27db90d4b72f1d04efa62eeca5b49bc8d9e72.
Reverting the change that adds ids to ArrayList. There are too many edge cases that are affecting the stability if the component. Reopening #14404 to find an alternate solution. 
fixes #14692
=> Revert add an id to track members of ArrayList.vue

shell/components/fleet/FleetClusterTargets/TargetsList.vue, shell/components/fleet/FleetClusterTargets/index.vue
=> Fleet fix target cluster names

shell/pages/c/_cluster/fleet/index.vue
=> Fleet fix dashboard class name conflicts

cypress/e2e/tests/pages/fleet/cluster-groups.spec.ts, cypress/e2e/tests/pages/fleet/fleet-clusters.spec.ts, shell/assets/translations/en-us.yaml, shell/components/fleet/FleetClusters.vue, shell/models/fleet.cattle.io.cluster.js
Fixes #14713
- Adding `Helm Ops Ready` column in clusters table.
- Changing columns order
1. Go to Fleet
2. App Bundles -> Create a new HelmOp
3. 
- Example 1:
Namespace: `fleet-local`
Name: test-nginx
Source Type: Repository
URL: `https://kubernetes.github.io/ingress-nginx`
Chart: `ingress-nginx`
- Example 2:
Namespace: `fleet-local`
Name: test-oci
Source Type: OCI Registry
URL: `oci://ghcr.io/rancher/fleet-test-configmap-chart`
5. Go to last step -> Create
[Screencast from 2025-07-10 09-53-01.webm](https://github.com/user-attachments/assets/73c24a72-172f-40ce-b75d-5dff7a70a30a)
=> Fleet add HelmOps in cluster pages

shell/package.json
- bump shell version to 3.0.5-rc.6
- bump shell version to 3.0.5-rc.6
=> bump shell version to 3.0.5-rc.6

cypress/e2e/blueprints/manager/registries-rke2-payload.ts, cypress/e2e/tests/pages/manager/registries.spec.ts, shell/edit/provisioning.cattle.io.cluster/tabs/registries/RegistryConfigs.vue
Fixes #14769
[Screencast from 2025-07-11 11-24-56.webm](https://github.com/user-attachments/assets/6813eceb-c2be-4e6b-a62b-3b0f786d8ac9)
=> Handle `CA Cert Bundle` empty value

shell/components/ResourceYaml.vue, shell/edit/configmap.vue, shell/edit/provisioning.cattle.io.cluster/rke2.vue, shell/mixins/create-edit-view/impl.js, shell/models/cluster.x-k8s.io.machinedeployment.js, shell/models/fleet.cattle.io.cluster.js, shell/plugins/dashboard-store/__tests__/normalize.test.ts, shell/plugins/dashboard-store/__tests__/resource-class.test.ts, shell/plugins/dashboard-store/normalize.js, shell/plugins/dashboard-store/resource-class.js
Fixes #14703
Fixes #11705
We are applying the `handleConflict` method to `saveYaml` to handle 409 errors.
When the UI gets a 409 error, it should try to resolve the conflicts by merging background changes with user's changes, and re-send the PUT request.
Fleet -> GitRepo YAML edit.
[Screencast from 2025-07-07 10-47-33.webm](https://github.com/user-attachments/assets/11c6bdca-f87d-4479-a49c-b1953a3f53c5)
=> Fix YAML 409 conflict errors

shell/components/fleet/dashboard/ResourcePanel.vue
=> Fleet fix badges background error color in preparation of new theme colors

pkg/kubectl-explain/components/SlideInPanel.vue, shell/assets/styles/base/_variables.scss, shell/components/Drawer/Chrome.vue, shell/components/SlideInPanelManager.vue, shell/pages/c/_cluster/fleet/index.vue
Fixes #14833
Modals, tooltips and drawers
=> Resolving some z-index issues around tooltips and slide-ins

cypress/e2e/tests/pages/users-and-auth/users.spec.ts
Update `View Yaml` e2e test following public api change
- Public API support for users changed the management.cattle.io.user resource to be editable - https://github.com/rancher/rancher/pull/50740
- Ensure our e2e test changes as well
=> Update `View Yaml` e2e test following public api change

shell/package.json
Bump shell to `3.0.5-rc.7` and release to npm later.
Bump shell to `3.0.5-rc.7` and release to npm later.
=> chore: bump shell to 3.0.5-rc.7

shell/assets/translations/en-us.yaml, shell/edit/__tests__/fleet.cattle.io.helmop.test.ts, shell/edit/fleet.cattle.io.gitrepo.vue, shell/edit/fleet.cattle.io.helmop.vue, shell/models/fleet-application.js, shell/models/fleet.cattle.io.gitrepo.js, shell/models/fleet.cattle.io.helmop.js
Fixes #14809
We are revisiting the polling interval for HelmOps based on  comments in https://github.com/rancher/dashboard/issues/14809
- Removing Enable/Disable Polling actions.
- Hide Polling fields when source is OCI or Tarball.
- Disable Polling if Version is null or static.
- Set default Polling Interval to zero (disabled) - see https://fleet.rancher.io/helm-ops#polling
- Set minimum Polling Interval to `15s` (like GitRepos)
- GitRepo -> polling Interval
Create/View
[Screencast from 2025-07-18 09-55-07.webm](https://github.com/user-attachments/assets/677c93d2-4ad8-4e9e-90ee-7a0b0a65a448)
Edit
[Screencast from 2025-07-18 09-57-08.webm](https://github.com/user-attachments/assets/c93d1e63-7188-4895-80c1-11dfa79ce316)
=> Fleet fix HelmOps polling interval

shell/assets/translations/en-us.yaml
Fixes #14917
Helm Op source examples: https://fleet.rancher.io/helm-ops#supported-use-cases
Repository
OCI Registry
Tarball
=> Fleet use examples from Fleet documentation in Helm Op wizard

docusaurus/docs/extensions/api/panels.md, docusaurus/docs/extensions/api/tabs.md
…
Fixes #12651 
- add docs for `addTab` about accessible Vue props 
- fix minor typo in `panels` docs
=> add docs for addTab about accessible Vue props

shell/assets/translations/en-us.yaml, shell/machine-config/google.vue
Fixes #14836 
Added preemptible setting to GCE provisioning wizard
Added a new checkbox
Cluster management -> Create -> Google GCE -> Advanced
New setting "preemptible" has been added
None
=> Added preemptible setting to GCE provisioning

.github/workflows/port-issue.yaml, .github/workflows/port-pr.yaml
This migrates Port PR and Port Issue workflows to use github apps. 
Fixes #10586
- Replace GITHUB_TOKEN with secrets from eio vault
Secrets are provided by EIO and should allow backports to trigger other github actions like e2e tests. 
Backport actions - Port PR/Issue
Backport actions - Port PR/Issue
NA
=> Migrate backport actions to use github app secrets

shell/assets/translations/en-us.yaml
=> [2.12.1] Fleet rename Settings to Continuous Delivery

shell/assets/translations/en-us.yaml, shell/edit/__tests__/fleet.cattle.io.helmop.test.ts, shell/edit/fleet.cattle.io.gitrepo.vue, shell/edit/fleet.cattle.io.helmop.vue, shell/models/fleet-application.js, shell/models/fleet.cattle.io.gitrepo.js, shell/models/fleet.cattle.io.helmop.js
=> [2.12.1] Fleet fix HelmOps polling interval

shell/assets/translations/en-us.yaml
=> [2.12.1] Fleet use examples from Fleet documentation in Helm Op wizard

shell/assets/translations/en-us.yaml, shell/pages/c/_cluster/fleet/__tests__/index.test.ts, shell/pages/c/_cluster/fleet/index.vue
=> [2.12.1] Fleet add search input to filter Dashboard's cards

.github/workflows/port-issue.yaml, .github/workflows/port-pr.yaml
This attempts to fix continued issues with the backport bot by updating the secrets to match those that are present in `pr-gh-project.yaml`.
- Update secrets in `port-pr.yaml` and `port-issue.yaml`
The backport bot continues to exhibit issues with fetching secrets. In the original PR, I had a hunch that the secrets I received might be inaccurate.
Continued efforts to resolve #14776
Backport bot should work after merging
Backport bot is already failing - attempting to fix.
NA
=> Update backport bot secrets to match `pr-gh-project.yaml`

pkg/rancher-prime/pages/registration.composable.ts
Fixes #14880
Restricted secrets to namespaced case only using existing options `opt: { namespaced: REGISTRATION_NAMESPACE }`
https://github.com/user-attachments/assets/ea591042-d643-4f71-a9c7-a1e9dfcdb55d
=> SCC Page fetches all secrets

.github/workflows/port-pr.yaml
This updates permissions for the `port-pr` workflow to help address permissions issues when backporting PRs.
- Update permissions for the `port-pr` workflow
`port-issue` is working, but it appears that `port-pr` is still failing[^1]. 
[^1]: https://github.com/rancher/dashboard/actions/runs/16728388998/job/47351608256
Backporting PRs - can be tested after merge.
Attempting to fix a regression introduced via #14776
NA
=> Update permissions for port-pr workflow

cypress/e2e/tests/pages/virtualization-mgmt/harvester.spec.ts, pkg/harvester-manager/l10n/en-us.yaml, pkg/harvester-manager/list/harvesterhci.io.management.cluster.vue
Fixes #13072
feat: add harvester ui ext version in update message
=> feat: add harvester ui extension version in update message

shell/assets/translations/en-us.yaml, shell/edit/fleet.cattle.io.gitrepo.vue, shell/edit/fleet.cattle.io.helmop.vue, shell/utils/validators/formRules/__tests__/index.test.ts, shell/utils/validators/formRules/index.ts
=> [2.12.1] Fleet improve Repository URL and OCI registry validation

cypress/jenkins/cypress.config.jenkins.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1904
This is a backport of https://github.com/rancher/dashboard/pull/14962
=> [Backport][Automation]: Add missing cypress-terminal-report plugin to Jenkins config

.github/workflows/port-pr.yaml
This updates the git user info for the `port-pr` workflow.
The git user used in the port-pr workflow could be at the root of the 403 response in the port-pr workflow:
https://github.com/rancher/dashboard/actions/runs/16729782291/job/47354806454
Backport PRs
NA
NA
=> Update global git user in `port-pr`

.github/workflows/port-pr.yaml
This reverts the change to the secrets for the `port-pr` workflow.
- revert secrets in the `port-pr` workflow to original values
The original attempt to read secrets in 601bbb30bb465e5d1a161a40c9b4ede75b22931c omitted the permissions entirely. This could have been the contributor as to why we could not get secrets from the vault on the first attempt.
Port PR workflow
NA
NA
=> Update secret path for port-pr workflow

.github/workflows/port-pr-bot.yaml
This attempts to log into the gh cli before running commands in the Port PR step
More Info: https://github.com/cli/cli/discussions/5095
=> Authenticate gh cli with token

pkg/harvester-manager/list/harvesterhci.io.management.cluster.vue, pkg/harvester-manager/types.js, shell/utils/uiplugins.ts
Fixes #15079 
Backport of https://github.com/rancher/dashboard/pull/15044
=> [2.12] Do not show repository missing warning if installed harvester ui extension from catalog

.github/workflows/port-pr-bot.yaml
This passes the `APP_TOKEN` to the `gh auth login` command for the `port-pr-bot` workflow.
=> Pass the `APP_TOKEN` environment variable to `gh auth login`

pkg/gke/components/CruGKE.vue
Fixes #15112
Backport of https://github.com/rancher/dashboard/pull/15108/commits
=> [2.12.1]fix issue importing gke clusters when using third party auth

shell/models/fleet.cattle.io.gitrepo.js
Fixes #14907
See https://github.com/rancher/dashboard/issues/14907#issuecomment-3116912724
=> [2.10.9] Fix matching between GitRepos and bundles list

shell/components/form/SecretSelector.vue, shell/components/form/labeled-select-utils/labeled-select-pagination.ts, shell/edit/logging.banzaicloud.io.output/index.vue, shell/edit/logging.banzaicloud.io.output/providers/awsElasticsearch.vue
Fixes #14990
- Backport of https://github.com/rancher/dashboard/pull/15013
- cherry-pick'd single commit
=> [2.12] Ensure SecretSelector resets on namespace change

shell/detail/workload/index.vue
Fixes #14991
- backport of #14994
- cherry-pick of merge commit
=> [2.12] Improvements to workload detail page resource lists 

shell/detail/workload/index.vue, shell/mixins/resource-fetch-api-pagination.js, shell/models/workload.js, shell/plugins/dashboard-store/actions.js
Fixes #14989
- backport of https://github.com/rancher/dashboard/pull/15011
- cherry-pick of merge commit
=> [2.12] Fix general and specific resource detail watch issues

shell/assets/translations/en-us.yaml, shell/models/__tests__/chart.test.ts, shell/models/chart.js, shell/pages/c/_cluster/apps/charts/AppChartCardSubHeader.vue
=> [2.12.1 - backport] Fix broken zero date for charts version date

shell/components/Markdown.vue
Fixes #15142 
- Added `max-width: 100%;` to prevent images breaking their parent element's layout
Example in the issue's description
Before:
After:
=> Fix broken images in markdown contents

shell/assets/brand/classic/metadata.json, shell/assets/styles/app.scss, shell/assets/styles/themes/_dark.scss, shell/assets/styles/themes/_light.scss, shell/assets/styles/themes/_modern.scss
This prepares for larger theme updates by creating a new `_modern.scss` theme. This also allows the original light/dark themes to be enabled by setting `ui-brand` to `classic`. 
fixes #15167
- Add `_modern.scss` and make it the default
- Allow `_light.scss` and `_dark.scss` to be accessible via updating `ui-brand` to `classic`
This is the first step of breaking out the work done in #14367 down into individual pieces. 
There should be no changes to the themes - at this point, the modern them matches the light/dark themes.  
We can test that the classic theme is loading properly by setting the `ui-brand` setting to `classic`. Change a css variable like `--nav-bg` to an interesting color like `orangered` in `_light.scss`/`_dark.scss` to confirm the classic theme loads. 
Reset `ui-brand` to …
=> Themes: Create a classic theme as a fallback

.github/workflows/update-e2e-rancher-version.yml, scripts/update-e2e-rancher-version.sh
This workflow updates the Rancher version used for e2e tests each time a release branch is created. 
- Add a new github workflow that updates the Rancher version used for e2e tests when a release branch is created
- Create a script that updates the e2e test version based on the branch created
This workflow automates a step in our release checklist and aims to reduce the amount of work for release captains when it comes time to branch for a release. 
Example test run and PR:
- https://github.com/rak-phillip/dashboard/pull/183
- https://github.com/rak-phillip/dashboard/actions/runs/16894218422/job/47860677020
We will need to test this workflow by creating release branches - the workflow should trigger and raise a PR with the correct changes in place.
NA
NA
=> Add a workflow to update the Rancher version used for e2e tests when a release branch is created

shell/package.json
Fixes #14418
chore: bump shell version to 3.0.5-rc.8
=> chore: bump shell version to 3.0.5-rc.8

cypress/e2e/po/components/rc-item-card.po.ts, cypress/e2e/po/pages/explorer/cluster-tools.po.ts, cypress/e2e/tests/pages/charts/logging.spec.ts, cypress/e2e/tests/pages/explorer2/cluster-tools.spec.ts, pkg/rancher-components/src/components/RcItemCard/RcItemCard.vue, pkg/rancher-components/src/components/RcItemCard/RcItemCardAction.vue, shell/pages/c/_cluster/explorer/tools/__tests__/index.test.ts, shell/pages/c/_cluster/explorer/tools/index.vue
Fixes #15109 
- Implemented the new design using the new card component
- Tests
Cards actions should work as expected.
Actions
=> Cluster tools page

cypress/e2e/tests/pages/global-settings/home-links.spec.ts, shell/config/home-links.js
Fixes #15204
This PR improves the handling of custom home page links.
Check that custom links can still be added via settings and show on the home page links section.
This is a scoped change and is not expected to impact other areas.
=> Improve handling of custom home page links

shell/detail/fleet.cattle.io.cluster.vue, shell/models/fleet-application.js
=> [2.12.2] Fleet fix missing resources from clusters details page

shell/detail/fleet.cattle.io.cluster.vue, shell/models/fleet.cattle.io.gitrepo.js
=> [2.11.6] Fleet fix missing resources from clusters details page

pkg/rancher-components/src/components/Pill/RcTag/RcTag.test.ts, pkg/rancher-components/src/components/Pill/RcTag/RcTag.vue, pkg/rancher-components/src/components/Pill/RcTag/index.ts, pkg/rancher-components/src/components/Pill/RcTag/types.ts, shell/assets/styles/base/_color.scss, shell/assets/styles/themes/_dark.scss, shell/assets/styles/themes/_light.scss, shell/assets/styles/themes/_modern.scss, storybook/src/stories/Components/Pill/RcTag.mdx, storybook/src/stories/Components/Pill/RcTag.stories.ts
Storybook component
Looks like story book is partly broken right now so I added the components to a page to test.
The dark theme follows the tags we already have in the detail page masthead even though it's not specified in the DS figma.
=> Implement the Tag component as defined by the DS system

shell/core/extension-manager-impl.js, shell/core/plugins.js, shell/edit/cloudcredential.vue, shell/edit/provisioning.cattle.io.cluster/index.vue, shell/types/extension-manager.ts
Fixes #15238
Added a check for extensions to add cloud credentials.
You can use https://github.com/rancher/ali-ui/pull/1 to test
Added a check for extensions when getting a list of available cloud credential providers.
Run https://github.com/rancher/ali-ui/pull/1  locally with shell yarn linked.
Verify that Alibaba Cloud credential is available in the list and can be created successfully
We need to verify that AKS, EKS, GKE cloud credentials are not affected by this change
=> Added providing credentials from extension

shell/config/router/navigation-guards/clusters.js, shell/config/router/navigation-guards/products.js, shell/utils/__tests__/product.test.ts, shell/utils/__tests__/resource.test.ts, shell/utils/auth.js, shell/utils/product.ts, shell/utils/resource.ts
A simple reorganization of some code that didn't belong in our auth util
Fixes #11111
=> Reorganizing some code that was left inside our auth util

shell/config/product/explorer.js
Fixes https://github.com/rancher/dashboard/issues/15140
- Don't use the new formatter 
- we want the description to consume the space in this table, so width needs to be undefined
- as width is undefined it won't truncate the text (breaking the elispes in formatter
- as per issue
=> Fix width of PSA description column

shell/dialog/ImportDialog.vue
Fixes #15452
Before assigning the first namespace as the default namespace we first look to see if the `default` namespace is present in the list of options and assign it if present.
Import dialog
To verify you'll want to create a new user with `User-Base` global permissions:
Give that user cluster membership with `View Nodes` permission:
Add that user to a project with minimal namespaces as a `Project Member`:
Import dialog
User with many namespaces including `default`:
User without `default` namespace:
User without any namespaces:
=> We now use the 'default' namespace when it's available and fallback on the first namespace

shell/package.json
chore: bump shell version to 3.0.5-rc.9
=> chore: bump shell version to 3.0.5-rc.9

.github/workflows/storybook.yaml
=> Limit the scenarios that the Storybook workflow runs

shell/package.json
Fixes #
- bump shell version to `3.0.5`
=> bump shell version to 3.0.5

shell/store/auth.js
Fixes #11392
This was causing auth's that require redirect to fail.
Introduced in https://github.com/rancher/dashboard/pull/15424
Several auth providers: amazon cognito, keycloak, okta saml
Several auth providers: amazon cognito, keycloak, okta saml
=> Fixes an issue where we didn't properly reference the root store

pkg/rancher-prime/pages/Registration.test.ts, pkg/rancher-prime/pages/Registration.vue, pkg/rancher-prime/pages/registration.composable.ts
Fixes #15375
- Added ID mapped value to registration
- Replaced link to router-link
- Ensured correct path by routing resolution
- Added test to link (resolution is out of scope)
=> SCC: Online registration - Click Product name and jump to 404 page

cypress/e2e/po/components/fleet/fleet-dashboard-workspace-card.po.ts, cypress/e2e/po/pages/fleet/fleet-dashboard.po.ts, cypress/e2e/tests/pages/fleet/dashboard.spec.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1986
This PR updates Fleet Dashboard tests which were failing on Jenkins.
It updates the test and page objects to work with the current codebase.
=> Automation: fix fleet dashboard tests

shell/utils/pagination-utils.ts
Fixes #15548
- ensure that `setting` `ui-performance` previously populated with now obsolete information is ignored
- also ensure any missing config uses defaults
- before 2.11.0 
- user enables SSP via `ui-performance` setting, list of resources that SSP is applied on save
- this was problematic, as the list would not update and get new supported resources on upgrade
- after 2.11.0
- we introduced a new process that explicitly stated whether to use a default list of resources in code (that would be updated each version)
- this did not work as expected, as previously saved `ui-performance` settings were still used
- to avoid upgrading from 2.10-->2.11-->2.12 stale `ui-performance` values can manually be applied (see steps to repo in issue)
- with stale ui-performance applied the …
=> Ensure we ignore stale pre-2.11 pagination configuration

shell/config/uiplugins.js, shell/package.json, shell/plugins/dashboard-store/resource-class.js
Fixes #15564 
- fix issue with extensions and show configuration on rancher systems <  2.13 
- bump shell version
Check original issue description
=> Fix extension bug with Show configuration

shell/assets/translations/en-us.yaml, shell/edit/auth/oidc.vue
This adds custom OIDC mappings for the Generic OIDC provider.
Fixes #14842 
- Add custom OIDC mappings under the advanced tab of the Generic OIDC provider
- Email
- Name
- Groups
This only applies to Generic OIDC.
The new fields are under the "Add custom claims" checkbox. Checking the box will display the custom claims form. 
If the form is rendered with values in one of the custom claims fields, the checkbox should be checked by default and the fields should be displayed.
If there are values in the custom claims and the checkbox is unchecked, the values will be deleted when the user clicks save. 
- Generic OIDC
- NA
=> Add custom OIDC mappings

cypress/e2e/po/lists/jwt-authentication-list.po.ts, cypress/e2e/po/pages/cluster-manager/jwt-authentication.po.ts, cypress/e2e/tests/pages/manager/jwt-authentication.spec.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1974
Fixed JWT Authentication test flakiness by adding page settling logic to wait for table rendering before test interactions, eliminating race conditions that caused intermittent test failures.
=> Automation: fix jwt auth tests

shell/assets/styles/base/_color.scss, shell/assets/styles/global/_button.scss
This replaces the `!important` flag used throughout `shell/assets/styles/global/_button.scss`, favoring increased specificity instead.
Fixes #15503 
- Replace the `!important` flag used throughout `shell/assets/styles/global/_button.scss`, favoring increased specificity
The `!important` flag is to be avoided when possible.
Button styles:
- role-primary
- role-secondary
- role-tertiary
- overflow buttons
- button groups
- header buttons
- disabled styles
- link buttons
- light/dark mode
- small/large buttons
This affects buttons used throughout dashboard - we expect the button styles to remain consistent with how they were rendered before.
=> Replace `!important` flag in favor of increased specificity

cypress/e2e/po/pages/chart-installed-apps.po.ts, cypress/e2e/tests/extensions/elemental/elemental.spec.ts
Fixes #https://github.com/rancher/qa-tasks/issues/1945
Updated the Elemental test to use version 3.0.1 instead of 2.0.0-rc2. This resolves the API compatibility issues and allows the tests to pass in Jenkins.
=> Automation: fix elemental tests
